### PR TITLE
py-notebook: add new version

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 10.15.6 with Python 3.8.5 and Apple Clang 11.0.3.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Review by alalazo — DISMISSED** [review]
Depends on #18626

**Review by becker33 — COMMENTED** [review]
@adamjstewart there are several places where you removed constraints on dependencies. Are those intentional/were the initial constraints incorrect?

**Comment by adamjstewart** [comment]
I'm not sure which constraints you're talking about specifically. Most constraints were simply moved around. Some were removed (one for a variant that doesn't exist). I think the current constraints are correct but you can go through the history of the package if you want.

**Comment by becker33** [comment]
@adamjstewart py-ipykernels was the dependency that most concerned me. It currently has different version constraints for python2 and python3, and this PR removes those constraints.

**Comment by becker33** [comment]
It looks like the other things I was looking at were the one package that went away, and another that I missed where the constraint was moved to. So I think it's just the one we need to look at.

**Comment by adamjstewart** [comment]
@becker33 I think someone added that due to concretizer bugs (if you choose to build a package with Python 2, it will still grab the latest version even if Python 2 isn't supported), but the versions weren't even correct anyway. There is no such constraint in any `setup.py` that I saw. I don't use Python 2 anymore, and the new concretizer will solve this, so I don't think it's worth retaining.

**Review by becker33 — APPROVED** [review]

**Pull request merged**
