### PR TITLE
CMake: add v3.28.0

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by scheibelp** [comment]
@johnwparent 

CI failure looks possibly legitimate: 

https://gitlab.spack.io/spack/spack/-/jobs/9388257

```
  >> 71    CMake Error at src/CMakeLists.txt:56 (target_link_libraries):
     72      Target "caliper-serial" links to:
     73    
     74        CUDA::cupti
     75    
     76      but the target was not found.  Possible reasons include:
     77    
     78        * There is a typo in the target name.
     79        * A find_package call is missing for an IMPORTED target.
     80        * An ALIAS target is missing.
```

possibly there is a change in how the latest CMake handles these options?

**Comment by johnwparent** [comment]
> @johnwparent
> 
> CI failure looks possibly legitimate:
> 
> https://gitlab.spack.io/spack/spack/-/jobs/9388257
> 
> ```
>   >> 71    CMake Error at src/CMakeLists.txt:56 (target_link_libraries):
>      72      Target "caliper-serial" links to:
>      73    
>      74        CUDA::cupti
>      75    
>      76      but the target was not found.  Possible reasons include:
>      77    
>      78        * There is a typo in the target name.
>      79        * A find_package call is missing for an IMPORTED target.
>      80        * An ALIAS target is missing.
> ```
> 
> possibly there is a change in how the latest CMake handles these options?

@scheibelp 
Confirmed this is a CMake bug in 3.28.0 that is fixed in 3.28.1. I can backport a patch into 3.28.0 in Spack or we can just skip 3.28.0 and jump right to 3.281 as we just released 3.28.1 a moment ago. We should probably just skip 3.28.0, but if you'd like in in Spack I can start work on a patch.

**Comment by scheibelp** [comment]
Interesting: IMO skip 3.28.0 and using 3.28.1 is easiest (maybe put a comment in the package.py saying that 3.28.0 should not be used)

**Comment by johnwparent** [comment]
3.28.0 includes breaking bugs for Spack packages. Closing in favor of: https://github.com/spack/spack/pull/41689

**Pull request closed without merging**
