### PR TITLE
Add LLVM_ENABLE_RTTI option to llvm-amdgpu package, required by mesa.

### PR DESCRIPTION
**Pull request by nicholas-sly**
This change is required to enable building mesa against this package, as is done when building the E4S full-stack in their own minimal container.

### CODE REVIEW

**Review by becker33 — APPROVED** [review]

**Review by srekolam — COMMENTED** [review]
This flag does not seem to be set in our internal CI builds. I need to reconfirm if this is can be enabled . Just need a little time more time to consult with the team

**Review by srekolam — APPROVED** [review]
verified with the team internally. It is okay if this needs to be enabled for mesa. In our internal ci builds,  it is turned off though.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by becker33** [comment]
@spackbot run pipeline

**Pull request merged**
