### PR TITLE
Add more functionality to the stage cmd

### PR DESCRIPTION
**Pull request by psakievich**
Improve the `stage` command. Specifically:

- Stop trying to stage externals
- Allow users to specify specs to skip
- Give users the opportunity to skip restaging specs that are already installed (env's)

Please note this fixes a bug. If I run `spack stage` without this change

``` console
$ spack stage
==> Staging specs from environment /scratch/psakiev/test/environments/tony_profile_build
==> Staged curl in /tmp/psakiev/spack-stage/spack-stage-curl-8.7.1-dvpnwerqufcygph7viieupogrjapacam
==> Staged gcc-runtime in /tmp/psakiev/spack-stage/spack-stage-gcc-runtime-10.3.0-kf2facnybyqqxggunmoktoqkzhfwfsxu
==> Error: Couldn't find archive file
Failed on expand() for URL https://ftpmirror.gnu.org/libc/glibc-2.28.tar.gz
[psakiev@compsim003 tony_profile_build]$ spack find gcc-runtime
==> In environment /scratch/psakiev/sierra/environments/tony_profile_build
==> 3 root specs
[+] ninja@kitware 

-- linux-rhel8-x86_64 / gcc@10.3.0 ------------------------------
gcc-runtime@10.3.0
==> 1 installed package
==> 0 concretized packages to be installed (show with `spack find -c`)
```

Trying to stage a package that is already installed. Also fails on `glibc` as reported in slack.

### CODE REVIEW

**Review by becker33 — CHANGES_REQUESTED** [review]
This looks great to me, it just needs unit tests.

**Comment by psakievich** [comment]
@becker33 tests added. Dissapointed that I have to reconcertize for every parameterization though. I tried to get around it but mock packages require function scope.  These test take 3.5 sec on my a laptop. I bet if we could cache the concretization it would take less than 1.

**Comment by becker33** [comment]
@psakievich does the `default_mock_concretization` fixture help? It caches concretizations across tests, so if another test is using the same spec it helps a lot.

**Comment by psakievich** [comment]
@becker33 i wasn't aware of that. I'll try it out.

**Comment by psakievich** [comment]
@becker33 it has a conflict with the `config` and `mutable_config` fixtures. I manually disabled the module scoped fixtures to test the speed but it was not any faster. I'd say let's just merge.

**Review by becker33 — APPROVED** [review]
This looks great to me, it just needs unit tests.

**Pull request merged**
