### PR TITLE
py-scipy: add v1.11.4

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/scipy/scipy/releases/tag/v1.11.4

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @adamjstewart. LGTM assuming CI passes; I don't expect any surprises here.

**Review by manuelakuhn — COMMENTED** [review]
There are additional upper bounds specified in the [pyproject.toml](https://github.com/scipy/scipy/blob/v1.11.4/pyproject.toml):
```
    # Reason for `<`: future-proofing (0.14.0 released and known to work)
    "meson-python>=0.12.1,<0.15.0",
    # Reason for `<`: future-proofing (0.14.0 released and known to work)
    "pythran>=0.12.0,<0.15.0",
```

According to https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy shouldn't the upper limit for `py-numpy` be `@1.21.6:1.26`?

**Comment by adamjstewart** [comment]
* We decided to drop upper bounds on meson/pythran because all versions work fine and it makes concretization easier
* I'll let @rgommers comment on the numpy dep, I only trust `pyproject.toml`/`setup.py` which say `@1.21.6:1.27`

**Comment by rgommers** [comment]
The `numpy` 1.26 vs. 1.27 doesn't really matter because it's highly unlikely that there will ever be a 1.27 release (2.0 is next instead). However, if there will be one, it will certainly be backwards compatible with 1.26, so using `:1.27` is fine.

**Review by manuelakuhn — APPROVED** [review]
Thanks for clarifying!

**Pull request merged**
