### PR TITLE
Backports: v0.22.1

### PR DESCRIPTION
**Pull request by haampie**
- [x] Set version to v0.22.1.dev0
- [x] #44154
- [x] #44127
- [x] #44191
- [x] #44219
- [x] #44248 
- [x] #43136  
- [x] #44272
- [x] #44182
- [x] #44214
- [x] #44315
- [x] #44335
- [x] #44264 
- [x] #44307 
- [x] #44316
- [x] #44156
- [x] #44373
- [x] #44279
- [x] #43967
- [x] #44126
- [x] #44213
- [x] #43851
- [x] #43965
- [x] #44382
- [x] #44740
- [x] #44893 
- [x] #44870
- [x] #44834
- [x] #44950 
- [x] #44949
- [x] #44976
- [x] #44981
- [x] Updated CHANGELOG
- [x] Bumped version to v0.22.1

**Pipelines and unit tests failure**

- [x] #44210 
- [x] #44443
- [x] #44627
- [x] #44582

### CODE REVIEW

**Review by alecbcs — DISMISSED** [review]
Looks good to me

**Comment by haampie** [comment]
Needs more things

**Comment by alalazo** [comment]
@alecbcs FYI, these backports PRs are to be "rebase and merged" rather than "squashed and merged" to keep track of what was cherry-picked on the release branch. Usually they are kept open until we are ready for a point release, and merged when the CHANGELOG and version bump are there.

**Comment by alalazo** [comment]
@spackbot run pipeline :sob:

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
