### PR TITLE
OpenBLAS: Add a symbol suffix option

### PR DESCRIPTION
**Pull request by haampie**
Some packages use a `64_` or `_64` symbol suffix for the ilp64 (= 64-bit
integers) interface for BLAS. In particular if we want to support shim
libraries like libopenblastrampoline supporting both the 32 and 64 bit
integer version of blas, it must be possible to distinguish between the
two.

### CODE REVIEW

**Comment by haampie** [comment]
@sethrj would you care to have a look at this one too? :D

**Comment by haampie** [comment]
or maybe @michaelkuhn.

@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by sethrj — DISMISSED** [review]
Underscore variants are ugly but can't really be helped. Looks good to me.

**Comment by haampie** [comment]
Now we just have to convince spackbot it should do something with this PR

**Review by sethrj — APPROVED** [review]

**Pull request merged**
