### PR TITLE
Add HDF5 version 1.14.1

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Review by hyoklee — DISMISSED** [review]

**Comment by lrknox** [comment]
@spackbot run pipeline

**Comment by lrknox** [comment]
@spackbot run pipeline

**Comment by lrknox** [comment]
@spackbot run pipeline

**Review by brtnfld — DISMISSED** [review]
LGTM

**Review by hyoklee — DISMISSED** [review]
verified sha256sum.

**Review by tldahlgren — APPROVED** [review]
Also verified the sha256.

**Review by tldahlgren — DISMISSED** [review]
Also verified the sha256.

**Comment by eugeneswalker** [comment]
Looking at E4S OneAPI CI stack failure, I see this error building `pflotran` using the new HDF5.
* [(specs) pflotran/25a2ufa 4.0.1 oneapi@=2023.0.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/6937621)
```
 >> 101    /tmp/root/spack-stage/spack-stage-pflotran-4.0.1-25a2ufak5dwhhac25x
            xdy4aerlpcfpv6/spack-src/src/pflotran/hdf5_aux.F90(5): error #7002:
             Error in opening the compiled module file.  Check INCLUDE paths.  
             [H5ES]
     102      use hdf5
     103    ------^
  >> 104    /tmp/root/spack-stage/spack-stage-pflotran-4.0.1-25a2ufak5dwhhac25x
            xdy4aerlpcfpv6/spack-src/src/pflotran/hdf5_aux.F90(97): error #6404
            : This name does not have a type, and must have an explicit type.  
             [LOGGING]
     105      call PetscLogEventBegin(logging%event_read_ndim_real_array_hdf5, 
            &
     106    --------------------------^
```

I don't know what the best way to handle this is, but one option is to amend this PR to include a `conflict` statement to `pflotran`'s package.py so that it won't use the newest HDF5 when building with OneAPI. Alternatively, we could amend this PR so that the E4S OneAPI stack explicitly requests that `pflotran` use a different HDF5 version.

What do you think?

**Comment by lrknox** [comment]
We would be fine with either - I'm not sure if you were addressing us or @tldahlgren.  I think I understand the first but wouldn't know where to start for the second.  @eugeneswalker, are either of these something you will do?  Oh, you mean edit this pr to make a change to pflotran/package.py?  Is it ok for me to do that?

**Comment by eugeneswalker** [comment]
> We would be fine with either - I'm not sure if you were addressing us or @tldahlgren. I think I understand the first but wouldn't know where to start for the second. @eugeneswalker, are either of these something you will do? Oh, you mean edit this pr to make a change to pflotran/package.py? Is it ok for me to do that?

I believe I can amend this PR myself to do either of these. Both will cause CI to go green.

It seems like the right thing to do, at least until the build error can be diagnosed and resolved, is to modify `pflotran`'s package.py so that it says `conflict("^hdf5@1.14.1", when="%oneapi")` -- this would cause pflotran to pick a different HDF5 version and cause CI to pass. If you are OK with this, I will push an update to this PR to include that.

**Comment by lrknox** [comment]
> > We would be fine with either - I'm not sure if you were addressing us or @tldahlgren. I think I understand the first but wouldn't know where to start for the second. @eugeneswalker, are either of these something you will do? Oh, you mean edit this pr to make a change to pflotran/package.py? Is it ok for me to do that?
> 
> I believe I can amend this PR myself to do either of these. Both will cause CI to go green.
> 
> It seems like the right thing to do, at least until the build error can be diagnosed and resolved, is to modify `pflotran`'s package.py so that it says `conflict("^hdf5@1.14.1", when="%oneapi")` -- this would cause pflotran to pick a different HDF5 version and cause CI to pass. If you are OK with this, I will push an update to this PR to include that.

Yes, please do.  Thank you!

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
