### PR TITLE
Bazel: add GCC 13 support for v6

### PR DESCRIPTION
**Pull request by adamjstewart**
Extracted from #45644

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
@LydDeb Do you want to comment on this PR before the merge?

**Comment by LydDeb** [comment]
I'm currently testing the recipe in an offline installation. I'll be back right away.

**Comment by LydDeb** [comment]
I failed to install bazel@7.0.2 with a RHEL 8 type distribution.
```
==> [2024-09-18-11:30:08.480283] '/usr/bin/bash' './compile.sh'
Building Bazel from scratch...scripts/bootstrap/compile.sh: line 255: shasum: command not found
```
Indeed shasum is not on available on RHEL/Centos 8.

I then noticed that this `shasum` only appeared in `compile.sh` in version 7.0.x.
I try the installation in 6.5.0.

**Comment by adamjstewart** [comment]
This PR doesn't affect bazel 7.0.2 or 6.5.0...

**Comment by LydDeb** [comment]
Sorry, my bad. Apart from that, offline installation of bazel@6.4.0 fails. I suggest adding `com_google_absl` in `resource_dictionary`:
```diff
     resource_dictionary = {}
+    resource_dictionary["com_google_absl"] = {
+        "url": "https://github.com/abseil/abseil-cpp/archive/refs/tags/20230802.0.tar.gz",
+        "sha256": "59d2976af9d6ecf001a81a35749a6e551a335b949d34918cfade07737b9d93c5",
+        "when": "@6:6.4",
+    }
````
I suceeded to install bazel@6.4.0 with these modifications.

**Comment by adamjstewart** [comment]
I've only tested bazel 6.1.0. Was 6.4.0 working for you before this PR or did I break something?

**Review by LydDeb — CHANGES_REQUESTED** [review]
I suggest these modifications in order to perform offline installation
```diff
     resource_dictionary = {}
+    resource_dictionary["com_google_absl"] = {
+        "url": "https://github.com/abseil/abseil-cpp/archive/refs/tags/20230802.0.tar.gz",
+        "sha256": "59d2976af9d6ecf001a81a35749a6e551a335b949d34918cfade07737b9d93c5",
+        "when": "@6:6.4",
+    }
```

**Comment by LydDeb** [comment]
> I've only tested bazel 6.1.0. Was 6.4.0 working for you before this PR or did I break something?

I will check

**Comment by adamjstewart** [comment]
If I didn't break anything, let's fix offline installation in another PR. That's a can of worms I don't want to mess with.

**Comment by LydDeb** [comment]
You did not break anything. It was already impossible to install offline before your PR.

**Comment by LydDeb** [comment]
I spoke too soon. I relaunched an offline installation of bazel@6.4.0 in the develop branch (without the patch `https://github.com/bazelbuild/bazel/pull/20785.patch?full_index=1`) and it succeeded.
The previous proposition seems to be necessary :/

**Review by LydDeb — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
