### PR TITLE
qemu: add pkgconfig to avoid build error

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@anderbubble can you review this PR?

@darmac when you open a PR to fix a build error, can you post the build error so we know what it is you're fixing?

**Comment by darmac** [comment]
OK, Error log is here:
```
==> 90444: Installing qemu
==> Finding buildcaches at http://172.19.16.223/spack_mirror/build_cache
==> Fetching http://172.19.16.223/spack_mirror/build_cache/linux-debian10-aarch64-gcc-8.3.0-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg.spec.yaml
==> Failed to fetch file from URL: http://172.19.16.223/spack_mirror/build_cache/linux-debian10-aarch64-gcc-8.3.0-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg.spec.yaml
    URL http://172.19.16.223/spack_mirror/build_cache/linux-debian10-aarch64-gcc-8.3.0-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg.spec.yaml was not found!
==> Fetching from http://172.19.16.223/spack_mirror/build_cache/linux-debian10-aarch64-gcc-8.3.0-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg.spec.yaml failed.
==> Using cached archive: /home/spack-develop/var/spack/cache/_source-cache/archive/ed/ed6fdbbdd272611446ff8036991e9b9f04a2ab2e3ffa9e79f3bab0eb9a95a1d2.tar.xz
==> Staging archive: /tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/qemu-4.1.1.tar.xz
==> Created stage in /tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg
==> No patches needed for qemu
==> 90444: qemu: Building qemu [AutotoolsPackage]
==> 90444: qemu: Executing phase: 'autoreconf'
==> 90444: qemu: Executing phase: 'configure'
==> [2020-08-10-14:38:31.953789, 90450] '/tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-src/configure' '--prefix=/home/spack-develop/opt/spack/linux-debian10-aarch64/gcc-8.3.0/qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg'

ERROR: pkg-config binary 'pkg-config' not found

==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-src/configure' '--prefix=/home/spack-develop/opt/spack/linux-debian10-aarch64/gcc-8.3.0/qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg'
See build log for details:
  /tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-build-out.txt

==> Error: Failed to install qemu due to ChildError: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-src/configure' '--prefix=/home/spack-develop/opt/spack/linux-debian10-aarch64/gcc-8.3.0/qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg'See build log for details:
  /tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-build-out.txt
Traceback (most recent call last):
  File "/home/spack-develop/lib/spack/spack/build_environment.py", line 823, in child_process
    return_value = function()
  File "/home/spack-develop/lib/spack/spack/installer.py", line 1133, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/spack-develop/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/spack-develop/lib/spack/spack/build_systems/autotools.py", line 322, in configure
    inspect.getmodule(self).configure(*options)
  File "/home/spack-develop/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg/spack-src/configure' '--prefix=/home/spack-develop/opt/spack/linux-debian10-aarch64/gcc-8.3.0/qemu-4.1.1-gq34jhp5wjwcermtj332z35o6iacbqfg'
```

**Comment by adamjstewart** [comment]
No response from @anderbubble so I'm going to merge.

**Comment by anderbubble** [comment]
@adamjstewart and @darmac sorry for not responding. The fact is I'm not a qemu user; I just put this package together for one of our cluster users who requested access to qemu.

So I should have responded and reviewed the PR, and I apologize; but I'm sure your perspective is just as valid as mine.

**Pull request merged**
