### PR TITLE
rocm-openmp-extras: Fix resource download URLs

### PR DESCRIPTION
**Pull request by wyphan**

### CODE REVIEW

**Review by afzpatel — APPROVED** [review]

**Review by tldahlgren — DISMISSED** [review]
Confirmed a subset of the resource URL archive files exist.

**Comment by tldahlgren** [comment]
@estewart08 @renjithravindrankannath @srekolam Is it okay to merge this PR?

**Review by renjithravindrankannath — APPROVED** [review]

**Comment by renjithravindrankannath** [comment]
> @estewart08 @renjithravindrankannath @srekolam Is it okay to merge this PR?

Approved.

**Review by srekolam — COMMENTED** [review]
I think the L213 (tag= "rocm-" can be removed as well.

**Review by srekolam — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
