### PR TITLE
replace libelf with elfutils in hip-rocclr

### PR DESCRIPTION
**Pull request by srekolam**
i had a ticket that requested to replace libelf with elfutils from @mwkrentel  . i replaced it now and for testing built the packages (rocblas) for rocm-3.9.0,rocm-3.10.0, 4.0.0 . need review on the same.

### CODE REVIEW

**Comment by haampie** [comment]
Hi @srekolam, seems like libelf is not a dependency of hip-rocclr anymore since version 3.9.0: https://github.com/ROCm-Developer-Tools/ROCclr/commit/e1e09e8e45b49a54c12fe6f8a4f48734d7632766

And I think they shipped (a custom?) libelf with the sources of hip-rocclr <= 3.8.0, so I don't think there is a need to have the dependency at all?

**Comment by mwkrentel** [comment]
@srekolam Have you tried running this with elfutils?  I tried
replacing a few depends_on(libelf) with elfutils, and I was amazed
that all the ones I tried actually built cleanly.  But I didn't try running
anything.

Or, as @haampie suggested, maybe it doesn't use an external elf at all.

Btw, does ROCM build on macOS/darwin?

**Comment by srekolam** [comment]
@mwkrentel  , i have not yet tried running with elfutils.. 
With regard to ROCm supporting  OS , here is complete list  of supported operating systems 
 https://github.com/RadeonOpenCompute/ROCm

**Comment by haampie** [comment]
@srekolam can we improve this package more generally?

1. drop the elf dep, cause it's probably not used at all

2. Why do we have `resource(name='opencl-on-vdi' ..` for every release? Shouldn't that be its own package?

**Comment by haampie** [comment]
Investigating a bit more and I've come to the conclusion that we're missing AMD's libOpenCL.so for which the sources are https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime. We should really move that to its own package.

**Comment by srekolam** [comment]
Yeah..hip-rocclr uses header files from opencl-on-vdi.  We will take your review comments as  input and move opencl-on-vdi as a own package. i will start on it. 
can i remove the elf dependency from hip-rocclr for this PR to go ?

**Comment by haampie** [comment]
Sounds good to me! I'd be happy to test that package providing libOpenCL.so (:

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
Should be good to go now, right?

**Comment by mwkrentel** [comment]
I was kinda hoping someone would actually try running it to make sure all the
pieces fit together.

**Comment by haampie** [comment]
@mwkrentel i'm running CI after the fact every few days :p but not ahead of time. Did you test it @srekolam?

**Comment by srekolam** [comment]
i have built the rocblas for rocm-3.9.0 , rocm-3.10.0,rocm-4.0.0 after making this change.  this has built successfully.

**Pull request merged**
