### PR TITLE
Backport fix for buliding vtk-m diy with GCC 11

### PR DESCRIPTION
**Pull request by kwryankrattiger**
FYI: @eugeneswalker @wspear

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
@kmorel

**Comment by kwryankrattiger** [comment]
Tested this building on crusher from v1.30:1.8.0 using gcc 11.

**Review by kmorel — APPROVED** [review]
Seems reasonable to me for versions before the fix in VTK-m.

**Review by vicentebolea — APPROVED** [review]
+1

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
