### PR TITLE
LLVM: replace libelf dependency with elf

### PR DESCRIPTION
**Pull request by iarspider**
I didn't test this extensively, but in CMS LLVM builds just fine with elfutils.

### CODE REVIEW

**Comment by iarspider** [comment]
@spackbot fix style

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by bernhardkaindl** [comment]
@iarspider It should work of coruse because the libelf from elfutils is compatible with libelf, but what should be the benefit?

I only see the drawback of adding more dependencies (the dependencies of elfutils) into the build for (I think) no gain.

For your PRs in general but for this one specially: Can you please add the motivation why merging your PR(s) would be beneficial and worth the incurred drawbacks? Thanks!

**Review by bernhardkaindl — COMMENTED** [review]
@iarspider It should work of course because the libelf from elfutils is compatible with libelf, but what should be the benefit?

I only see the drawback of adding more dependencies (the dependencies of elfutils) into the build for (I think) no gain.

For your PRs in general but for this one specially: Can you please add the motivation why merging your PR(s) would be beneficial and worth the incurred drawbacks? Thanks!

**Comment by iarspider** [comment]
@bernhardkaindl `libelf` and `elfutils` both provide virtual package `elf`. Also, `libelf` is not maintained anymore, and it's recommended to use `elfutils` instead. This PR replaces hard dependency on `libelf` with a virtual dependency on `elf`. I think, this is kind of recommended way of writing package recipes: unless package X can only be used (built or ran) with specific provider of virtual package Y, put dependency on Y.

**Comment by iarspider** [comment]
One additional benefit of using `elf` vs `libelf`: if `elfutils` is already in the environment, it will be picked up instead of `libelf` - one less dependency.

**Review by bernhardkaindl — APPROVED** [review]
Thanks, looks good.

**Comment by iarspider** [comment]
Unless there is a package that can only be built with `libelf`, we can probably deprecate `libelf` and replace all dependencies on `libelf` or `elf` with `elfutils` (since this will be the only provider of `elf`), but this is outside of this PR's scope.

**Pull request merged**
