### PR TITLE
Bump mathematica version

### PR DESCRIPTION
**Pull request by antoniokaust**
I added version `12.1.1` to this recipe.

I added `url_for_version` method to pickup correct installer based on version.

I also used native Linux `cp` program to backup `.spack` folder since `copy_tree` failed me. I'd be happy to revert if you can give me options on why it failed.

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
`url_for_version` isn't needed, Spack knows how to find the right version:
```console
$ spack url parse file:///Users/Adam/spack/lib/spack/spack/Mathematica_12.0.0_LINUX.sh
==> Parsing URL: file:///Users/Adam/spack/lib/spack/spack/Mathematica_12.0.0_LINUX.sh

==> Matched version regex  0: r'^[a-zA-Z+._-]+[._-]v?(\\d[\\d._-]*)$'
==> Matched  name   regex 10: r'^([A-Za-z\\d+\\._-]+)$'

==> Detected:
    file:///Users/Adam/spack/lib/spack/spack/Mathematica_12.0.0_LINUX.sh
                                             ----------- ~~~~~~
    name:    Mathematica
    version: 12.0.0

==> Substituting version 9.9.9b:
    file:///Users/Adam/spack/lib/spack/spack/Mathematica_9.9.9b_LINUX.sh
                                             ----------- ~~~~~~
```
The change from `copy_tree` to `cp` isn't portable to Windows, which we hope to support someday. Can you describe the issue you saw with `copy_tree`? Let's fix that instead.

**Comment by antoniokaust** [comment]
> `url_for_version` isn't needed, Spack knows how to find the right version:

So I can just put back `url` field?

> 
> The change from `copy_tree` to `cp` isn't portable to Windows, which we hope to support someday. Can you describe the issue you saw with `copy_tree`? Let's fix that instead.

I agree with you but this installer is only for Linux (at least today) unless new WSL supports `.sh` files.

The method `copy_tree` (in verbose mode) said that it would copy the directory but just didn't. The installation would fail when we had to copy `.spack` back to where it belongs. How can I debug why that's happening? Do you know if something changed in `copy_tree` that prevents copying `.spack`?

**Comment by adamjstewart** [comment]
> So I can just put back url field?

Yes.

> copy_tree

What's the output when you run `spack -ddd install -v mathematica`? It should at least tell you the source and destination directories so you can confirm if those are correct. `copy_tree` has changed a bit (supports globs now), but I don't think that would cause this. The stage directory changed, which could explain the problem.

**Comment by antoniokaust** [comment]
> > copy_tree
> 
> What's the output when you run `spack -ddd install -v mathematica`? It should at least tell you the source and destination directories so you can confirm if those are correct. `copy_tree` has changed a bit (supports globs now), but I don't think that would cause this. The stage directory changed, which could explain the problem.

I found out stage directory change the hard way, the installation failed because `copy_tree` does not support `StageComposite`.
I kept watching the stage directory to see if `.spack` got copied over, it never did even though `spack install -v mathematica` would print out that it had copied it. Tomorrow I'll use your command to see if I can get more details.

**Comment by antoniokaust** [comment]
> I found out stage directory change the hard way, the installation failed because `copy_tree` does not support `StageComposite`.
> I kept watching the stage directory to see if `.spack` got copied over, it never did even though `spack install -v mathematica` would print out that it had copied it. Tomorrow I'll use your command to see if I can get more details.

```
==> [2020-11-12-08:22:07.210180, 20542] 20534: mathematica: Executing phase: 'install'
==> [2020-11-12-08:22:07.210815] Copying /sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack to /sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo

<<MATHEMATICA INSTALLER HERE IN THE MIDDLE>>

==> [2020-11-12-08:35:44.186905] Copying /sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack to /sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo
==> [2020-11-12-08:35:44.189114, 20542] WRITE LOCK (spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo): /sw/staging/a-arenaam/.lock[7816855302471970269:1] [Releasing]
==> [2020-11-12-08:35:44.189277, 20542] WRITE LOCK (spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo): /sw/staging/a-arenaam/.lock[7816855302471970269:1] [Released at 08:35:44.189253]
==> [2020-11-12-08:35:44.207861, 20534] Error: FileNotFoundError: [Errno 2] No such file or directory: '/sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack/'

/sw/spack/var/spack/repos/builtin/packages/mathematica/package.py:54, in install:
         51            ln('-s', ws_path, ws_link_path)
         52
         53        # Move back .spack where it belongs
  >>     54        copy_tree(join_path(self.stage.path, '.spack'), prefix)
 ```

I checked from the beginning, the `.spack` directory wasn't copied to staging directory.
We're using Spack v0.15.4. I don't see anything funny in `copy_tree` that wouldn't make this work.
BTW, does Spack have a `mv` method? It's probably better to move the `.spack` directory then move it back.

**Comment by adamjstewart** [comment]
Spack doesn't have a `mv` method, only `copy` and `install`. We could add one, but there aren't a ton of packages that care about the difference.

If you replace `stage` with `stage.path`, does `copy_tree` work? I don't see any reason why they would be different. You could also put a print statement in the for-loop of `copy_tree` to see if it isn't detecting any files or something weird.

I don't have a mathematica license, so it's hard for me to debug this locally.

**Comment by antoniokaust** [comment]
> If you replace `stage` with `stage.path`, does `copy_tree` work? I don't see any reason why they would be different. You could also put a print statement in the for-loop of `copy_tree` to see if it isn't detecting any files or something weird.

I had to replace `stage` with `stage.path` otherwise `copy_tree` fails. It prints correct path but doesn't copy anything. I'll add some debug statements in `copy_tree` to see if I can spot the culprit.

**Comment by antoniokaust** [comment]
@adamjstewart It looks like `copy_tree` doesn't copy recursively anymore. Here are my debug prints:

```
==> [2020-11-13-11:30:13.199866] Copying /sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack to /sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo
==> [2020-11-13-11:30:13.200109] copy_tree: traverse_tree gave s('/sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack/', '/sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/') and d('/sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack/spec.yaml', '/sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/spec.yaml')
==> [2020-11-13-11:30:13.200176] copy_tree: /sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack/ is a dir
==> [2020-11-13-11:30:13.200219] copy_tree: mkdirp(/sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/) was called
==> [2020-11-13-11:30:13.200547] copy_tree: shutil.copy2(/sw/workstations/apps/linux-ubuntu18.04-ivybridge/mathematica/12.1.1/gcc-7.5.0/seucg4nubnqwh5tjpz3m2qmfrzg2cglo/.spack/spec.yaml, /sw/staging/a-arenaam/spack-stage-mathematica-12.1.1-seucg4nubnqwh5tjpz3m2qmfrzg2cglo/spec.yaml) was called
```

The file `spec.yaml` is copied into the parent directory because `.spack` wasn't created in the destination directory.

Just before clicking `Comment`, I read `travers_tree` documentation which says the following:

```
        root/
          a/
            file1
            file2
          b/
            file3

    When called on dest, this yields::

        ('root',         'dest')
        ('root/a',       'dest/a')
        ('root/a/file1', 'dest/a/file1')
        ('root/a/file2', 'dest/a/file2')
        ('root/b',       'dest/b')
        ('root/b/file3', 'dest/b/file3')
```

So it's behaving as expected. I'm quite sure it was working differently back in April when you merged my PR using `copy_tree` to backup the `.spack` directory. Any suggestions?

**Comment by adamjstewart** [comment]
Hmm, the last PR in which I modified `copy_tree` was #18376. Maybe you could try before and after that commit?

**Comment by antoniokaust** [comment]
> Hmm, the last PR in which I modified `copy_tree` was #18376. Maybe you could try before and after that commit?

I'll try it but I need to know, according to your knowledge of the code, if `copy_tree` is supposed to copy `.spack` over to destination or just its contents as stated in `travers_tree` docs?

**Comment by adamjstewart** [comment]
My goal with `copy` and `copy_tree` was to make them behave as close as possible to Python's `shutil.copy` and `shutil.copytree` and the command-line `cp` and `cp -R`. So I think what you actually need is:
```python
copy_tree('.spack', join_path(prefix, '.spack'))
```
I don't think this behavior has ever changed. For example, `copy_tree('.', prefix)` should copy all files/dirs in the current directory to the prefix, not to `<prefix>/cwd-name`.

**Comment by adamjstewart** [comment]
Hmm, it seems like the behavior of `shutil.copytree` and `cp -R` depends on whether or not the destination directory already exists. Should we change Spack's utils to match this? 

EDIT: Specifically, `shutil.copytree` crashes if the destination directory already exists, whereas `cp -R` copies the directory itself into this directory. I prefer the former behavior, but we decided against that because `prefix` is always present during installation and we wanted `copy_tree('.', prefix)` to work. We could of course use `copy_tree('*', prefix)` to get around this limitation, but I don't think that works for single files, only directories? Not sure what the best behavior is here, or whether the [documented behavior](https://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.copy_tree) even matches the actual behavior.

**Comment by antoniokaust** [comment]
> My goal with `copy` and `copy_tree` was to make them behave as close as possible to Python's `shutil.copy` and `shutil.copytree` and the command-line `cp` and `cp -R`. So I think what you actually need is:
> 
> ```python
> copy_tree('.spack', join_path(prefix, '.spack'))
> ```
> 
> I don't think this behavior has ever changed. For example, `copy_tree('.', prefix)` should copy all files/dirs in the current directory to the prefix, not to `<prefix>/cwd-name`.

I'll try your suggestion. I'm sure the recipe worked because that's how we installed Mathematica in KAUST; but I agree with you that it should have not worked 😄

**Review by adamjstewart — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
