### PR TITLE
e4s: expand macos stack [DON'T-MERGE-YET]

### PR DESCRIPTION
**Pull request by eugeneswalker**
Now that we have the M1 studio, let us try building more packages and see how it handles it.

@wspear

### CODE REVIEW

**Comment by eugeneswalker** [comment]
FYI @alalazo looks like many of those packages that were added to this stack, in addition to the ones I tried to add right now, will not build because of the issues shown in the pipeline here:
* https://gitlab.spack.io/spack/spack/-/pipelines/157765
* https://gitlab.spack.io/spack/spack/-/pipelines/157766

also CC @adamjstewart in case these are of interest to him

**Comment by adamjstewart** [comment]
Very much of interest to me. I've been dying for some good ol' M1 clingo binaries. @alalazo are you working on adding these now that we can do so in CI?

**Comment by adamjstewart** [comment]
FWIW, libzmq, hwloc, gettext, and perl all build on my M1. Will check build logs.

**Comment by adamjstewart** [comment]
Didn't see anything obvious in the build logs that would explain why things are failing for you but not for me. I assume you have direct access to this machine, but let me know if you need any help debugging.

**Comment by eugeneswalker** [comment]
> Didn't see anything obvious in the build logs that would explain why things are failing for you but not for me. I assume you have direct access to this machine, but let me know if you need any help debugging.

Yes I have access. I will login and try the build manually. Perhaps just some system packages need to be present. I don't know. I don't do any builds on it manually, we just got it, and I'm not very experienced with MacOS + Spack. Will investigate.

**Comment by adamjstewart** [comment]
I have all the macOS + Spack experience you could ever dream of if you need it 😄

**Comment by alalazo** [comment]
> are you working on adding these now that we can do so in CI?

No, just moved them from GA to pipelines to reduce the pressure on free macOS runners, see https://github.com/spack/spack/pull/32231 Do I recall correctly that the macOS pipeline is not required, and that is why I got :heavy_check_mark: in the PR just linked?

**Comment by eugeneswalker** [comment]
> > are you working on adding these now that we can do so in CI?
> 
> No, just moved them from GA to pipelines to reduce the pressure on free macOS runners, see #32231 Do I recall correctly that the macOS pipeline is not required, and that is why I got ✔️ in the PR just linked?

Yes, that is right. We set it up that way because we were expecting to hit some issues potentially with not enough throughput on the machine, so were expecting time out failures, and didn't want to block all PRs. We weren't sure we'd hit those issues, we wanted to find out, just not find out in a way that breaks peoples PRs.

**Comment by eugeneswalker** [comment]
Looking at one of the failing packages `libzmq`
1. I can build `libzmq` using this exact spack.yaml, on the same runner machine, manually, when I build all dependencies from source (i.e. when I don't use cached dependency binaries)
2. I can reproduce the exact error seen here`libzmq`, manually, when I build `libzmq` using the cached dependency binaries

Which leads me to conclude something is wrong with the dependency binaries. I don't know what...

All the `e4s-mac` CI runs are hitting this error and failing (looking at other PRs) -- could we clear out the `e4s-mac` binary cache and see if regenerating the binaries fixes things? I don't have permission to do this @scottwittenburg could you do this?

By the way, the error for `libzmq` showing in the pipeline (but not showing if you build the package and its dependencies manually from source, i.e. no cached dependency binaries) is:
* https://gitlab.spack.io/spack/spack/-/jobs/3171701
* https://gitlab.spack.io/spack/spack/-/jobs/3171701/raw
```
...
checking for pkg-config... /Users/gitlab-runner/builds/builds/-hmC4tot/0/spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path/darwin-monterey-m1/apple-clang-13.1.6/pkgconf-1.8.0-ett7ygi7ft3lg6iekce3ts2qscv7kxk2/bin/pkg-config
checking pkg-config is at least version 0.9.0... /var/folders/6n/pw9tmf6n08dfgg5td4_w9wh00000gx/T/gitlab-runner/spack-stage/spack-stage-libzmq-4.3.4-2tk2a5ywqd6azigkb536dqrttlina2ec/spack-src/configure: line 6527: 30471 Killed: 9               $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version
...
/var/folders/6n/pw9tmf6n08dfgg5td4_w9wh00000gx/T/gitlab-runner/spack-stage/spack-stage-libzmq-4.3.4-2tk2a5ywqd6azigkb536dqrttlina2ec/spack-src/configure: line 421: test: then: integer expression expected
configure: error: run
/var/folders/6n/pw9tmf6n08dfgg5td4_w9wh00000gx/T/gitlab-runner/spack-stage/spack-stage-libzmq-4.3.4-2tk2a5ywqd6azigkb536dqrttlina2ec/spack-src/configure: line 310: return: then: numeric argument required
/var/folders/6n/pw9tmf6n08dfgg5td4_w9wh00000gx/T/gitlab-runner/spack-stage/spack-stage-libzmq-4.3.4-2tk2a5ywqd6azigkb536dqrttlina2ec/spack-src/configure: line 320: exit: then: numeric argument required
```

**Comment by eugeneswalker** [comment]
Something is wrong with macOS binary relocation:
* https://github.com/spack/spack/issues/32571

**Pull request closed without merging**
