### PR TITLE
py-vermin: add latest version 1.3.0

### PR DESCRIPTION
**Pull request by netromdk**
New [1.3.0 release](https://github.com/netromdk/vermin/releases/tag/v1.3.0):
- Python 3.10 support
- More rules
- A few speedups

@adamjstewart @alalazo

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
If this is the first release that supports Python 3.10 you could add something like:
```python
depends_on('python@2.7:3.9', when='@:1.2', type=('build', 'run'))
```
to prevent people from building older vermin with Python 3.10.

**Comment by netromdk** [comment]
Thanks for the advice, @adamjstewart. Vermin can be executed with all versions of Python: v2.7 through 3.10. And covers v2.0-2.7 and v3.0-3.10 results wise. But v2.7 is still the minimum version, though the newest version is always recommended for the newest language features to be detected.

Is there a way to annotate that the minimum version is v2.7 but it's recommended to use v3.10 (for the time being) though not requiring it outright?

**Comment by adamjstewart** [comment]
> Vermin can be executed with all versions of Python: v2.7 through 3.10

Ah, so you're saying that all versions of vermin (including vermin 0.10) can be built and used with Python 3.10 but vermin 1.3.0 is the first version that actually tests that? Or is it that vermin 1.3.0 adds support for detecting new features added in Python 3.10 whereas older versions can't do that? Either way, the build recipe is fine as is.

> Is there a way to annotate that the minimum version is v2.7 but it's recommended to use v3.10 (for the time being) though not requiring it outright?

Spack defaults to Python 3.8 (because that's what Conda/Homebrew default to), but users can install with a different version if they want to:
```console
$ spack install py-vermin ^python@3.10.0  # not currently released
$ spack install py-vermin ^python@2.7.18
```

**Comment by netromdk** [comment]
It is exactly this:
> Or is it that vermin 1.3.0 adds support for detecting new features added in Python 3.10 whereas older versions can't do that?

Any rules that pertain to using specific functions, classes etc. that require 3.10 as minimum will work with earlier versions of Python 3.10 when running Vermin 1.3.0, but Python 3.10 language specific features, like pattern matching, will only be detected from Python 3.10 onward. 

Thanks for the clarification. Then I think it's good as-is.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
