### PR TITLE
qt: fix ~opengl and use_spack_dep

### LINKED ISSUE #30485: qt@5.15.3 build fails: qt/package.py:541, in common_config_args: '_use_spack_dep' is not defined
### Steps to reproduce the issue

`qt@5.15.3` build fails using:
* `spack/develop` (250d5d2c00ad9d6a747499b1160bc4a460266fae from `Wed May 4 13:30:15 2022 -0400`)
* Ubuntu 20.04, X86_64
* GCC 11.1.0

Concrete spec: [qt-vsih2gf.spec.json.txt](https://github.com/spack/spack/files/8626807/qt-vsih2gf.spec.json.txt)

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 250d5d2c0)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./qt-vsih2gf.spec.json

$> spack install --no-cache -f ./qt-vsih2gf.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing qt-5.15.3-vsih2gfjjg63nwtm7bfhkw32ua33kqhv
==> Fetching https://mirror.spack.io/_source-cache/archive/b7/b7412734698a87f4a0ae20751bab32b1b07fdc351476ad8e35328dbe10efdedb.tar.xz
==> Fetching https://mirror.spack.io/_source-cache/archive/93/9378afd071ad5c0ec8f7aef48421e4b9fab02f24c856bee9c0951143941913c5
==> Fetching https://mirror.spack.io/_source-cache/archive/20/2081e9cb85f6712be9b63c70204efa3da954c07d857283eeae16d1b0409704bd
==> Fetching https://mirror.spack.io/_source-cache/archive/84/84b099109d08adf177adf9d3542b6215ec3e42138041d523860dbfdcb59fdaae
==> Applied patch /spack/var/spack/repos/builtin/packages/qt/qt5-pcre.patch
==> Applied patch /spack/var/spack/repos/builtin/packages/qt/qt5-15-gcc-10.patch
==> Applied patch /spack/var/spack/repos/builtin/packages/qt/qt515-quick3d-assimp.patch
==> Applied patch https://src.fedoraproject.org/rpms/qt5-qtbase/raw/6ae41be8260f0f5403367eb01f7cd8319779674a/f/qt5-qtbase-gcc11.patch
==> Applied patch https://src.fedoraproject.org/rpms/qt5-qtdeclarative/raw/593481a2541d3218f285dd7b46bdc5f4c76075ab/f/qt5-qtdeclarative-gcc11.patch
==> Applied patch https://src.fedoraproject.org/rpms/qt5-qtwebsockets/raw/f54f4ce6fa27941e9e6d606103d32056078edc74/f/qt5-qtwebsockets-gcc11.patch
==> Ran patch() for qt
==> qt: Executing phase: 'configure'
==> Error: NameError: name '_use_spack_dep' is not defined

/spack/var/spack/repos/builtin/packages/qt/package.py:541, in common_config_args:
        538            spec, config_args, spack_pkg, qt_name)
        539
        540        if '+gui' in spec:
  >>    541            use_spack_dep('freetype')
        542            if not MACOS_VERSION:
        543                config_args.append('-fontconfig')
        544        else:

See build log for details:
  /tmp/root/spack-stage/spack-stage-qt-5.15.3-vsih2gfjjg63nwtm7bfhkw32ua33kqhv/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (250d5d2c00ad9d6a747499b1160bc4a460266fae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8626825/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8626826/spack-build-out.txt)

@sethrj @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by sethrj**
https://github.com/spack/spack/pull/30460 broke qt. 

Closes #30485 .

### CODE REVIEW

**Comment by wdconinc** [comment]
FYI I won't get a chance to run a test build against this until late evening Central time.

**Comment by sethrj** [comment]
Thanks @wdconinc . I tested `@5.13 ~opengl` on my mac and it behaves as expected.

**Review by chuckatkins — APPROVED** [review]

**Comment by chuckatkins** [comment]
Looking forward to getting this in ci to preemptively catch these things 🤦‍♂️

**Review by wdconinc — APPROVED** [review]
Managed to start a test earlier. The build succeeded with all +opengl and -opengl combinations for the following versions:
```
19:49:03 wdconinc@electroweak ~/git/spack (qt-fix-30485 $%=) $ spack config get
spack:
  specs:
  - qt@5.15.3~dbus~debug~doc~examples~framework~gtk+gui+opengl~phonon+shared+sql+ssl+tools~webkit
    ^mesa+glx~llvm+opengl+opengles+osmesa~strip
  - qt@5.14.2~dbus~debug~doc~examples~framework~gtk+gui+opengl~phonon+shared+sql+ssl+tools~webkit
    ^mesa+glx~llvm+opengl+opengles+osmesa~strip
  - qt@5.12.10~dbus~debug~doc~examples~framework~gtk+gui+opengl~phonon+shared+sql+ssl+tools~webkit
    ^mesa+glx~llvm+opengl+opengles+osmesa~strip
  - qt@5.15.3~dbus~debug~doc~examples~framework~gtk+gui~opengl~phonon+shared+sql+ssl+tools~webkit
  - qt@5.14.2~dbus~debug~doc~examples~framework~gtk+gui~opengl~phonon+shared+sql+ssl+tools~webkit
  - qt@5.12.10~dbus~debug~doc~examples~framework~gtk+gui~opengl~phonon+shared+sql+ssl+tools~webkit
  packages:
    all:
      compiler: [gcc@11.3.0]
  view: false
```

**Comment by eugeneswalker** [comment]
Thank you for this! Any reason not to merge now?

**Pull request merged**
