### PR TITLE
mumps: add v5.7.2

### PR DESCRIPTION
**Pull request by jcortial-safran**

### CODE REVIEW

**Review by balay — APPROVED** [review]
Good to also add in 5.7.0, 5.7.1?

**Comment by jcortial-safran** [comment]
> Good to also add in 5.7.0, 5.7.1?

I did not add either 5.7.0 or 5.7.1 since they are essentially variants of 5.7.2 with some bugs not yet fixed but I tested 5.7.1 at some point and it worked.

I am not sure what is the policy for spack in that regard. I wouls not mind adding 5.7.0 and 5.7.1 if needed.

**Comment by balay** [comment]
perhaps @alalazo or @tldahlgren can clarify the policy here  - I think generally such older versions also get listed - in case someone wants to install/check them out - for whatever reason.

And most (regular) users get the  latest version (that satisfies dependency rules) anyway - so they won't be using older buggy versions [unless they explicitly ask spack to install them].

There is also a deprecation policy - for older versions that shouldn't be used [or unsupported]..
 
https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
I would not add older versions, unless they are needed for any reason :wink:

**Pull request merged**
