### PR TITLE
Fix typo in GitHub Actions step name

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
6th time's the charm!

**Pull request merged**
