### PR TITLE
Make Boost an optional feature of Trilinos.

### PR DESCRIPTION
**Pull request by KineticTheory**
I have been unable to build Boost with some toolset/platform combinations. The users I support don't need the Boost features in Trilinos, so I have been manually hacking trilinos/package.py to disable boost. I would like to propose that these changes be added to the released version.

+ Add boost as a variant, default to true so there is no change to existing behavior.
+ Move the CMake configure options related to Boost into a conditional block that is triggered by `if '+boost' in spec`.
+ Fix formatting to meet code style guidelines.

### CODE REVIEW

**Comment by mathstuf** [comment]
Looks good, but would you mind splitting the cosmetic changes into a separate commit?

**Comment by KineticTheory** [comment]
@mathstuf As requested, I broke the PR into a commit for the logic change and another commit for the formatting changes.  I wasn't sure how to revert my original PR so I could break it into 2 commits. Hopefully my approach is okay. Let me know if there is a better way.

**Comment by davydden** [comment]
in order to rewrite commits, you roughly do the following on your local branch
```
// reset your branch to the current state of develop.
// That will undo all commits locally.
// "Soft" reset is done by default, so all modified files stay but they are not commited
git reset develop 
// add files and select which chunk of chagnes you want to be commited
// so it's at this point you split into proper changes and cosmetic ones
git add <filename> -p
// usual business of commiting
git commit -m <message>
// after you repeat the add-commit steps enough times:
// before pushing you can make sure that your rewriting history is the same as
// current state of your remote branch on github:
git diff <your remote>/pkg-trilinos
// if there is no difference, then you rewrote history ok and you can push force now:
git push <your remote> --force
```

**Comment by davydden** [comment]
as for the current state, i belive you can just squash first three commits into 1:
```
// you have 4 commits in total:
git rebase -i HEAD~4 
// you will see file to edit, make first 3 to squash into one and leave the last one (formatting) intact.
```

**Comment by alalazo** [comment]
@davydden I think what @KineticTheory did is better practice than what you propose : he already published his branch and if somebody merged it somewhere else for some reason a `revert` is better then a `push --force`. Same goes for squashing.

**Comment by davydden** [comment]
@alalazo but no one merged it, right? If someone would, then i would not recommend this. I believe that squashing and cleaning up commits BEFORE it is merged anywhere it perfectly fine and i prefer this as opposed to commits which do not serve any purpose (like one which undoes another).

**Comment by davydden** [comment]
at the end of the day, it's all a matter of usage context and personal preference. I just do not agree with calling the current state

>  a better practice

**Comment by alalazo** [comment]
@davydden How do you know if somebody merged it or not? The branch is already a PR. Somebody may have merged it in a branch to try it out early because he needed the feature.

**Comment by mathstuf** [comment]
Merging crap history is a heavier burden than the off chance that someone was expecting *that exact commit* being considered merged or not. As someone who regularly has to trawl history to fix bugs, conflated commits and crap messages (e.g., "fix the bug"; what bug? how was it fixed? why does the commit have a reindentation of the whole file?) make it a nightmare to figure out what exactly broke. Handling local patches is fine, but you cannot rely on submitting it upstream to not need changes or such.

The ban on force pushing is largely dead with a fork-based workflow IMO. I do not expect things like non-integration branches to be canon on forks of projects and personally will regularly rewrite for clarity or a rebase (just look at dep-types and tell me that the current history isn't better than what was there before).

**Comment by davydden** [comment]
@alalazo IMHO what is important is if it is merged into the intended destination (`develop` branch in this case). Whether or not somebody checked it out to try locally -- is not important as one may as well reset to the current state of the remote branch to keep trying the updated version.

**Comment by alalazo** [comment]
@mathstuf I obviously don't agree, but don't want to start a flame on this :smile: 

I think it is not uncommon for this project that people merge multiple ongoing PRs on a side branch that they use in production at their sites. Rewriting history for those PRs could turn into a merge nightmare.

That said, reworking and rewriting your local history BEFORE pushing it on your fork is instead something I would encourage to avoid the problem you just listed.

**Comment by mathstuf** [comment]
Merging unreviewed code and relying on it with an expectation of zero work when it gets merged is not a friendly thing IMO.

For something like dep-types, the branch is just too long-lived and affects lots of code to just not publish it before it is "perfect". Right now, it's history is logical and shows a clear direction towards to final implementation. Using the history as I wrote it would be unreadable and, frankly, unreviewable.

Here's a reduction ad absurdum: if history is so precious, why not create a commit for each keystroke in your editor? Every insertion, deletion, typo, etc. This is, I think, obviously too fine-grained, so instead, we chunk work at logical spots and write a description of what was done to that point. The next is just committing at the end of every hour or day or whatever. This also isn't necessarily meaningful. A commit of "checkpoint; lunch" helps no one understand what changed. Instead, I argue that a branch's history should show logical, progressive steps towards the goal. I don't care about what commands you used in your editor, when you took breaks, etc. Document it in the commit messages (i.e., "the code does X and not Y is because it was tried and doesn't work because Z") but don't split them that way.

**Comment by alalazo** [comment]
> Here's a reduction ad absurdum: if history is so precious, why not create a commit for each keystroke in your editor? Every insertion, deletion, typo, etc. This is, I think, obviously too fine-grained, so instead, we chunk work at logical spots and write a description of what was done to that point. The next is just committing at the end of every hour or day or whatever. This also isn't necessarily meaningful. A commit of "checkpoint; lunch" helps no one understand what changed. Instead, I argue that a branch's history should show logical, progressive steps towards the goal. I don't care about what commands you used in your editor, when you took breaks, etc. Document it in the commit messages (i.e., "the code does X and not Y is because it was tried and doesn't work because Z") but don't split them that way

This brings it a bit too far, it's not what we are discussing here...

**Comment by KineticTheory** [comment]
@mathstuf @alalazo @davydden 
I decided to re-write the history of this PR based on davydden's guidance. I didn't know how to do this before but the prescription was straight forward. Additionally, this change is so small (in terms of code logic) that I don't think there is any loss of information due to re-writing the history.

**Comment by mathstuf** [comment]
Thanks. Much easier to review now :) . LGTM.

**Comment by tgamblin** [comment]
Just to weigh in on this, I generally agree with Ben and consider `master` and `develop` to be "published", while PRs and public feature branches are transient and I don't mind people rewriting them.  I think it's nice to be able to iterate with PR submitters.

So, if people are working *together* on a feature branch they need to coordinate about not force pushing.  And if people want to add a feature early and they're worried about garbage history on their beta branch, they should be sure to merge the PR into a temporary branch to try it out, and not into their copy of `develop` if they want to receive from upstream.

**Pull request merged**
