### PR TITLE
graphviz: Added documentation variant

### PR DESCRIPTION
**Pull request by tuxfan**
- Default is 'ON' (consistent with current behavior)
- This variant allows the user to turn off a lot of dependencies, e.g.,
  ghostscript (mesa, and llvm).

### CODE REVIEW

**Comment by adamjstewart** [comment]
@sethrj @michaelkuhn this looks like a duplicate of #19615, can you take a look?

**Comment by sethrj** [comment]
@adamjstewart Ha, yes, good catch! @tuxfan the current graphviz fails to build even when `~documentation` (or `~doc`) unless ghostscript is available. We're waiting on an upstream PR to create a new tagged graphviz version.

**Comment by tuxfan** [comment]
@adamjstewart I'm not sure that I understand your comment. Will the upstream PR allow us to turn off the documentation build?

**Comment by adamjstewart** [comment]
Yes, it looks like the upstream PR has been merged, we're just waiting for a new release. @sethrj maybe we could backport the merged commit?

**Comment by sethrj** [comment]
@adamjstewart Patch doesn't apply -- it's a bunch of changes to numerous makefiles. 🤢  I could create a new fake version (2.44.1.dev) but that has the potential to be confusing.

**Comment by tuxfan** [comment]
@adamjstewart Are we still waiting on the upstream PR? I was wondering if we couldn't use my PR as a temporary fix?

**Comment by sethrj** [comment]
@tuxfan I'd submitted a previous PR that did the same thing, but it was rejected because `~doc` will fail to compile on systems that don't have `ghostscript` already installed. The same will happen here: even with `~documentation` the build/install may fail.

**Comment by adamjstewart** [comment]
Do we have external detection for Ghostscript? Maybe adding that would help while we wait.

**Comment by sethrj** [comment]
> Do we have external detection for Ghostscript? Maybe adding that would help while we wait.

I added the necessary external `groff` detection, but ghostscript has so many options and so many build products I'm hesitant to try it. I think it's mainly `ps2pdf` that's needed by doxygen.

**Comment by adamjstewart** [comment]
> ghostscript has so many options and so many build products I'm hesitant to try it.

It's fine to add partial support, just detecting the version and nothing else.

Anyway, let's close this PR and continue any discussion in #19615.

**Pull request closed without merging**
