### PR TITLE
linux-perf: New package, fix the build of its dependencies

### PR DESCRIPTION
**Pull request by Jordan474**
Add linux-perf, with latest stable version 6.9 and longterm versions 6.6 and 5.15.

Tested on ubuntu 22 and rhel 8.

Notes:

At build time, perf complains about linux-headers not matching system's. But I tested `perf-linux@6.1`'s `perf record` on a rhel8 (kernel 4.18) and it works well AFAIK.

I didn't test an previous install after the system's kernel version changed.

### CODE REVIEW

**Review by bernhardkaindl — DISMISSED** [review]
@Jordan474 I added https://github.com/Jordan474/spack/blob/linux-perf/var/spack/repos/builtin/packages/libtraceevent/package.py to #45364 because I'd like to build `uftrace` with it.

With it, `libtraceevent` is now is the latest `develop` branch.

Could you re-base this PR on top of the merged commit on develop, and fix the two easy conflicts that occur?
- `babeltrace` and `audit-userspace` - `develop` got 4.0.1 meanwhile - maybe you don't need 3.1.2 then?

You could also squash your commits together into one commit or two (preferably one for the `perf` package itself, and one before that for the other needed fixes) when it all works and is ready for final review (optional, we can squash on merge too)

Or, would you mind if I rebase your `linux-perf` branch in your repo on top of the `spack` `develop` branch with the merge of `libtraceevent`? (I can do it if you gave maintainers permission to write to your branch - there is a checkbox in the PR that you may have left at the default checked or may have disabled by unchecking it).

Just tell me and let's proceed however works for you.

Mention me with @bernhardkaindl to ping me if you want to reach me and re-request my review if you pushed to your branch, and it is then ready for final review.

**Comment by Jordan474** [comment]
Done, I rebased it on develop, thank for the heads-up.

`audit-userspace@4.0.1` did not install for me, thankfully I found an official patch and backported it.

**Comment by Jordan474** [comment]
I squashed all the linux-perf commits, and kept other patches separate.

**Review by bernhardkaindl — APPROVED** [review]
@Jordan474 I had one issue attempting to build it on Ubuntu 22.04:

When clang is installed, I get `clang: Permission denied`.
Setting `CLANG` to the full path of `clang` fixes this.
Therefore, I added a commit to set it in this case:

`linux-perf: If clang is in PATH, pass "CLANG=" + shutil.which("clang")`

To build the `xmlto` dependency, I cherry-picked a commit from the latest develop branch: `hotfix upstream patch removed by fedora` (spack#45551)

And I added a final commit to add a variant for building with the capstone disassembler:
`linux-perf: Add capstone variant to build with capstone disassembler`

I hope you have no issues with adding the capstone variant and setting CLANG= to the path of clang.

I approved and enabled auto-merge.

**Pull request merged**
