### PR TITLE
upcxx: Fixes for Cray targets

### PR DESCRIPTION
**Pull request by bonachea**
This PR improves automated default behavior for a few Cray XC/EX systems.

Successfully validated on ALCF Polaris and ALCF Theta

### CODE REVIEW

**Review by PHHargrove — APPROVED** [review]
I have verified that the EX updated platform detection now works on ALCF's Sunspot, where the previous logic would fail.

I have visually inspected the XC platform detection changes.

All LGTM.

**Review by PHHargrove — CHANGES_REQUESTED** [review]
Sorry, but upon further on Sunspot, I find that `upcxx-run` is not getting the right PMI run command (or not using PMI?).  I will share details in Pagoda's Slack workspace.

**Review by PHHargrove — DISMISSED** [review]
LGTM now, including passing where I'd previously reported an issue w/ the PMIRUN_CMD.

**Review by PHHargrove — APPROVED** [review]
Still "LGMT" with the recent addition of `level_zero` variant detection.

**Review by becker33 — APPROVED** [review]

**Comment by becker33** [comment]
@bonachea while I appreciate and often share your frustration with rigid style guideline enforcement, I'd prefer if you did not analogize the rigidity with nazism in your commit messages.

**Pull request merged**
