### PR TITLE
Add missing and new versions of htslib and samtools.

### PR DESCRIPTION
**Pull request by dunatotatos**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
@glennpj As the recommended reviewer, would you like to review this PR before it is merged?

**Comment by dunatotatos** [comment]
Is something missing from my side to get this PR merged?

**Comment by glennpj** [comment]
I will take a look.

**Review by glennpj — COMMENTED** [review]
This looks good to me. I am not sure why this PR was closed but it can be reopened if desired.

**Comment by tldahlgren** [comment]
Has this been rebased to the latest version of `develop`?  I'm not able to initiate that from here.

**Comment by dunatotatos** [comment]
Something weird happens with this PR. I re-based the source branch, but the PR is not updated. I close this one and create a new one. #32259

**Pull request closed without merging**
