### PR TITLE
vecgeom: new version 1.2.0

### PR DESCRIPTION
**Pull request by sethrj**
VecGeom 1.2 onward requires C++17 or higher.

### CODE REVIEW

**Review by drbenmorgan — COMMENTED** [review]
Annoyingly I can't post the comment next to the lines in question... One further change that 1.2.0 introduced was to prefix CMake arguments with `VECGEOM_....` so that the `cmake_args` function would need the default set updated to something like:

```python
        args = [
            define('VECGEOM_VECTOR', target_instructions),
            self.define_from_variant('BUILD_SHARED_LIBS', 'shared'),
            self.define_from_variant('CMAKE_CXX_STANDARD', 'cxxstd')
        ]   
        
        if spec.satisfies('@1.2:'):
            args.extend([
                define('VECGEOM_BACKEND', 'Scalar'),
                define('VECGEOM_BUILTIN_VECCORE', False),
                define('VECGEOM_NO_SPECIALIZATION', True),
                self.define_from_variant('VECGEOM_GDML', 'gdml'),
                self.define_from_variant('VECGEOM_GEANT4', 'geant4'),
                self.define_from_variant('VECGEOM_ROOT', 'root'),
            ])
        else:
            args.extend([
                define('BACKEND', 'Scalar'),
                define('BUILTIN_VECCORE', False),
                define('NO_SPECIALIZATION', True),
                self.define_from_variant('GDML'),
                self.define_from_variant('GEANT4'),
                self.define_from_variant('ROOT'),
            ])
```

That's a bit inelegant, but should work for now.

**Comment by sethrj** [comment]
Ah, thanks for the update... I guess I should have installed and verified before opening the PR 😅

**Comment by sethrj** [comment]
OK, I built it on my mac and verified the options, and am trying to build with CUDA now...

**Comment by sethrj** [comment]
OK, confirmed the build of `vecgeom@1.2.0+cuda+gdml~geant4~ipo~root+shared build_type=RelWithDebInfo cuda_arch=70 cxxstd=17` installs as expected!

**Review by drbenmorgan — APPROVED** [review]
👍 on the simplification to the options with the prefix! All good to go I think pending CI completion!

**Review by tldahlgren — APPROVED** [review]
LGTM Confirmed sha256.

**Pull request merged**
