### PR TITLE
update hip-rocclr recipe and fix dangling pointer in rocm-smi-lib

### PR DESCRIPTION
**Pull request by srekolam**
modified the recipe for the issue reported #24497 , and cleaned up the hip-rocclr recipe.
for hip-rocclr, i just built hip-rocclr@4.2.0 , hip-rocclr-4.1.0 and hip-rocclr-3.5.0 .
After from that i built the hipcub@4.2.0. i did not see any failures etc.

### CODE REVIEW

**Comment by haampie** [comment]
can you fix

```

var/spack/repos/builtin/packages/rocm-smi-lib/package.py:8: [I100] Import statements are in the wrong order. 'import shutil' should be before 'from spack import *' and in a different group.
var/spack/repos/builtin/packages/rocm-smi-lib/package.py:8: [I201] Missing newline between import groups. 'import shutil' is identified as Stdlib and 'from spack import *' is identified as Application.
var/spack/repos/builtin/packages/rocm-smi-lib/package.py:9: [I100] Import statements are in the wrong order. 'import os' should be before 'import shutil'
```

if you want to run the style test locally install https://pypi.org/project/flake8-import-order/ first

**Review by haampie — DISMISSED** [review]

**Comment by srekolam** [comment]
@haampie , @tldahlgren  i see this still as open . Let me know if there is anything to do  from my side

**Comment by haampie** [comment]
@spack-bot re-run pipelines

**Comment by UweSauter** [comment]
@srekolam Could you take another look at this?

**Comment by haampie** [comment]
I've taken the liberty to rebase onto develop to make the gitlab ci pass

**Review by haampie — APPROVED** [review]

**Pull request merged**
