### PR TITLE
Remove maintainership from some packages and verify generated language dependencies

### PR DESCRIPTION
**Pull request by sethrj**
This removes myself as maintainer from packages that satisfy both:
- I don't use or have a stake in
- I don't own.

I haven't directly done anything with Qt not Trilinos in quite a long time.

### CODE REVIEW

**Review by wdconinc — APPROVED** [review]
Thanks for all your hard work on these packages!

**Review by tldahlgren — APPROVED** [review]
By removing `# generated` from the new language dependencies I am assuming you're also verifying that the generated ones are accurate.

**Comment by sethrj** [comment]
@spackbot run ci

**Comment by psakievich** [comment]
This PR makes me sad. Will definitely miss having you on the Trilinos maintainers list.  🫡

**Comment by sethrj** [comment]
Thanks @psakievich , if you think there's something I can particularly help with (or you want my opinionated views on a design decision or something) I'm glad to give input, but I'm no longer really qualified to do version bumps and the like... when I first started maintaining, the two primary projects I worked on had very tight coupling with trilinos. Nowadays, I really don't use it at all. I appreciate your support though!

**Pull request merged**
