### PR TITLE
LAMMPS: Add new versions

### PR DESCRIPTION
**Pull request by rbberger**
* adds missing versions to LAMMPS spackage
* update official website URL
* add myself as a maintainer (I am one of the LAMMPS core devs and want to start to be more actively involved in supporting this spackage)
* deprecate versions before stable release on March 3, 2020 (I would deprecate more, but I want to do it gradually, this is a suggestion for an initial batch)

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Thanks - I was not very active for some time and it seems the others overlooked this

**Comment by bernhardkaindl** [comment]
@rbberger I had some error when trying to build this, merging with develop

**Comment by rbberger** [comment]
@bernhardkaindl what kind of failures? Or was it resolved with getting getting up-to-date with develop?

**Review by bernhardkaindl — APPROVED** [review]
built on arm64

**Review by sethrj — APPROVED** [review]

**Pull request merged**
