### PR TITLE
add support for oneapi compiler to wrf 4.4

### PR DESCRIPTION
**Pull request by Andrey1994**

### CODE REVIEW

**Review by MichaelLaufer — APPROVED** [review]
LGTM.
@Andrey1994 can you submit this patch upstream as well?

**Review by rscohn2 — APPROVED** [review]
A maintainer of the package approved, and I reviewed it too. Thanks @Andrey1994

**Comment by Andrey1994** [comment]
I see somebody sent a PR to WRF repo 2 days ago - https://github.com/wrf-model/WRF/pull/1893

**Comment by rscohn2** [comment]
After it is merged, we should switch to their patch and limit the patch to the current release.

**Comment by Andrey1994** [comment]
yes

**Pull request merged**
