### PR TITLE
z3: New version 4.8.16

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
The CI pipe stopped with an ephemeral (?) error, but Github didn't notice. Can you restart it?

**Comment by tgamblin** [comment]
@eschnett you can ask spackbot too (authors of PRs can) -- can you try it?

**Review by tgamblin — APPROVED** [review]

**Comment by eschnett** [comment]
@spackbot help

**Pull request merged**
