### PR TITLE
Adding support for spack monitor with containerize

### PR DESCRIPTION
**Pull request by vsoch**
This should get us most of the way there to support using monitor during a spack container build, for both Singularity and Docker. Some quick notes:

### Docker
Docker works by way of BUILDKIT and being able to specify --secret. What this means is that you can prefix a line with a mount of type secret as follows:

```bash
# Install the software, remove unnecessary deps
RUN --mount=type=secret,id=su --mount=type=secret,id=st cd /opt/spack-environment && spack env activate . && export SPACKMON_USER=$(cat /run/secrets/su) && export SPACKMON_TOKEN=$(cat /run/secrets/st) && spack install --monitor --fail-fast && spack gc -y
```
Where the id for one or more secrets corresponds to the file mounted at `/run/secrets/<name>`. So, for example, to build this container with su (spackmon user) and sv (spackmon token) defined I would export them on my host and do:

```bash
$ DOCKER_BUILDKIT=1 docker build --network="host" --secret id=st,env=SPACKMON_TOKEN --secret id=su,env=SPACKMON_USER -t spack/container . 
```
And when we add `env` to the secret definition that tells the build to look for the secret with id "st" in the environment variable `SPACKMON_TOKEN` for example.

If the user is building locally with a local spack monitor, we also need to set the `--network` to be the host, otherwise you can't connect to it (a la isolation of course.)

## Singularity

Singularity doesn't have as nice an ability to clearly specify secrets, so (hoping this eventually gets implemented) what I'm doing now is providing the user instructions to write the credentials to a file, add it to the container to source, and remove when done.

## Tags

Note that the tags PR https://github.com/spack/spack/pull/23712 will need to be merged before `--monitor-tags` will actually work because I'm checking for the attribute (that doesn't exist yet):

```bash
"tags": getattr(args, "monitor_tags", None)
```
So when that PR is merged to update the argument group, it will work here, and I can either update the PR here to not check if the attribute is there (it will be) or open another one in the case this PR is already merged. 

Finally, I added a bunch of documetation for how to use monitor with containerize. I say "mostly working" because I can't do a full test run with this new version until the container base is built with the updated spack (the request to the monitor server for an env install was missing so I had to add it here).

Signed-off-by: Vanessa Sochat <sochat1@llnl.gov>

### CODE REVIEW

**Comment by vsoch** [comment]
The only fail was on RHEL, I've never seen this before:

```

Red Hat Universal Base Image 8 (RPMs) - CodeRea  93 kB/s |  15 kB     00:00    
Package curl-7.61.1-18.el8.x86_64 is already installed.
Package gnupg2-2.2.20-2.el8.x86_64 is already installed.
Package gzip-1.9-12.el8.x86_64 is already installed.
Package which-2.21-12.el8.x86_64 is already installed.
Error: 
 Problem 1: conflicting requests
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
  - nothing provides libgomp = 8.4.1-1.el8 needed by gcc-8.4.1-1.el8.x86_64
 Problem 2: conflicting requests
  - nothing provides libquadmath = 8.4.1-1.el8 needed by gcc-gfortran-8.4.1-1.el8.x86_64
  - nothing provides libgfortran = 8.4.1-1.el8 needed by gcc-gfortran-8.4.1-1.el8.x86_64
 Problem 3: package gcc-c++-8.4.1-1.el8.x86_64 requires gcc = 8.4.1-1.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libgomp = 8.4.1-1.el8 needed by gcc-8.4.1-1.el8.x86_64
Error: Process completed with exit code 1.
```

**Comment by trws** [comment]
That looks a whole lot like somehow it hit an inconsistent package mirror state, which shouldn't happen, but I hit restart on it hopefully it will just go through this time.

**Comment by vsoch** [comment]
uhoh @trws it happened again! :scream:

**Comment by trws** [comment]
That's incredibly odd.  Maybe file an issue on it, I'm not sure 
who the best person to poke about this is, but my RHEL packaging 
knowledge is rusty at best.

**Comment by vsoch** [comment]
I guess I can try running it once more time in case there was something about yesterday...

**Comment by alecbcs** [comment]
Hey all! Any updates on this? It would be great to get this into develop so that we can integrate Spack Monitor into Autamus and start submitting logs!

**Pull request merged**
