### PR TITLE
Add new package for rhash, a cmake dependency

### LINKED ISSUE #620: `cmake` not defined
Spack defines a `cmake` command by default. I find that this is `None` unless `cmake` is installed on the system; Spack does not pick up `cmake` as installed by a dependency on `cmake.`

I'm looking at `setup_package` -- maybe `which("cmake")` is called before the dependencies have a chance to modify `PATH`?

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #620 

Still need to test on Linux, but passes all tests on macOS. @manish2479 can you test this out to see if it solves your problem?

### CODE REVIEW

**Comment by adamjstewart** [comment]
Tested on Linux. Should be good to go.

**Comment by manish2479** [comment]
Hi Adam,

I am bit new to using spack so How do I update my spack repo with new
changes, is there any specific command which do safe updates of repo
without changes with other installed applications. Can you provide me the
steps on how I get updates files without any breakdown of my spack
environment.

Thank You,
                  Manish

**Comment by adamjstewart** [comment]
@manish2479 There are no Spack commands for updating, you would use git to update. Installed applications aren't tracked by git, so you don't have to worry about them being overwritten. This hasn't been merged yet, so you would have to fetch this specific branch from my repo.

In the meantime, does `cmake+ownlibs` install for you? CMake should be picking up its own copies of rhash and its other dependencies.

**Comment by manish2479** [comment]
Hi Adam,

When I ran git fetch it didn't got the changes for "features/rhash" so which branch is that and what exact fetch command I should use it. 

> git fetch
warning: redirecting to https://github.com/LLNL/spack/
remote: Counting objects: 258, done.
remote: Total 258 (delta 158), reused 158 (delta 158), pack-reused 100
Receiving objects: 100% (258/258), 55.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (185/185), completed with 49 local objects.
From http://github.com/LLNL/spack
 * [new branch]          efischer/161221-FixSetup                 -> origin/efischer/161221-FixSetup
 * [new branch]          efischer/170808-FixSetup                 -> origin/efischer/170808-FixSetup
 * [new branch]          features/better-io-redirection           -> origin/features/better-io-redirection
 * [new branch]          features/show-build-log-on-build-failure -> origin/features/show-build-log-on-build-failure

Thank You,
                 Manish

**Comment by adamjstewart** [comment]
@manish2479 Take a look at https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by manish2479** [comment]
Hi Adam,

Thank you for that link and I was able to fetch that change. So I tried to install cmake with that new repo and its now failed for package "LibUV".

```
-- Could NOT find LibUV: Found unsuitable version "", but required is at least "1.0.0" (found LibUV_LIBRARY-NOTFOUND)
CMake Error at CMakeLists.txt:526 (message):
  CMAKE_USE_SYSTEM_LIBUV is ON but a libuv is not found!
Call Stack (most recent call first):
  CMakeLists.txt:663 (CMAKE_BUILD_UTILITIES)
```

Thank You,
                 Manish

**Comment by adamjstewart** [comment]
@mathstuf Do you happen to know what version the `libuv` dependency was added?

@manish2479 Are you building `cmake+ownlibs` or `cmake~ownlibs`?

**Comment by manish2479** [comment]
Hi Adam,

I am building "cmake~ownlibs".

Thank You,
                 Manish

**Comment by adamjstewart** [comment]
@manish2479 Is there some reason you can't build `cmake+ownlibs`? Then you don't have to worry about any of these missing dependencies. That is the default variant, which explains why you're the first person who ran into this problem.

**Comment by adamjstewart** [comment]
Added the libuv dependency. Let me know if it is missing anything else.

**Comment by manish2479** [comment]
Hi Adam,

Yes I am not able to build using "cmake+ownlibs" or just "cmake"

I tried bot version 3.9 latset and 3.8.1 with install command 

./spack install cmake+ownlibs qt=true
./spack install cmake+ownlibs@3.8.1 qt=true

Both didn't worked and logs as on https://pastebin.com/2h2NraPq

Thank You,
                 Manish

**Comment by adamjstewart** [comment]
@mathstuf might want to take a look at this.

**Comment by manish2479** [comment]
Hi 

So whatever changes happened lately seems fixed the cmake install issues using 

spack install cmake~ownlibs qt=true

Thank You,
                Manish

**Pull request merged**
