### PR TITLE
helics: Add versions 2.8.0, 3.0.0, and 3.0.1

### PR DESCRIPTION
**Pull request by nightlark**
Adds v2.8.0, v3.0.0, and v3.0.1 to the HELICS package versions.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256s.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by scheibelp** [comment]
@spackbot re-run pipeline

**Comment by sethrj** [comment]
@spackbot re-run pipeline

**Pull request merged**
