### PR TITLE
Pkg/arpack 3.4.0

### PR DESCRIPTION
**Pull request by davydden**
update arpack, fix their cmake.

tested on macOS.

### CODE REVIEW

**Comment by davydden** [comment]
fixes https://github.com/LLNL/spack/issues/699

**Comment by davydden** [comment]
patches submitted upstream https://github.com/opencollab/arpack-ng/pull/39

**Comment by adamjstewart** [comment]
Wow, that package description is ridiculous. We can probably cut that down to a couple sentences.

**Comment by alalazo** [comment]
@adamjstewart @davydden ...just asking out of curiosity... but what's the issue with long package descriptions ?

**Comment by tgamblin** [comment]
I don't think there's a problem with them if the first line is short and sweet, like python docstrings.

**Comment by davydden** [comment]
@alalazo Spack shows description as a single paragraph, which IMHO is difficult to read if the description is too long. Here the text was formatted for several paragraphs and a bullet points lists, which all collapse into one paragraph anyway.

**Comment by davydden** [comment]
but i can also drop the shortening commit, if you prefer.

**Comment by tgamblin** [comment]
We could change the way spack formats the description, if that's an issue, although maybe a paragraph is better.  @alalazo: do you like longer, multi-paragraph comments?  I'm on the fence.

**Comment by alalazo** [comment]
@tgamblin Well, usually I try to re-use what the package developer already provide... that's why I was asking. I would like if in the future we could set for something like python docstrings : a good one liner and then a more accurate description if available

**Comment by adamjstewart** [comment]
I guess I don't mind longer descriptions, I just suggested shortening it for consistency with other packages. But a 23 line description is probably overkill. If we want multi-paragraph descriptions, I agree that we need to change the way that Spack formats them. At the very least, empty lines should remain empty lines. Formatting bullet points might be more difficult.

It's really a matter of what we want to use package descriptions for. Here are some good uses for package descriptions:

1. They should differentiate packages with similar names or uses
2. They can now be searched with `spack list -d`, so they should contain keywords like BLAS/LAPACK or DFT or CFD
3. They should contain special installation instructions if necessary (see `pgi`).
4. They should warn the user of deprecated software (see `netcdf-cxx`)

But I see a lot of developer descriptions for packages that:

1. Brag about how awesome their software is
2. Say how their software is better than someone elses
3. Talk about who developed it or where it was developed

I don't think these things are as useful in package descriptions.

**Comment by davydden** [comment]
that's ready to review. Works as expected, as far as i can tell on macOS.

**Pull request merged**
