### PR TITLE
LCIO: add new version: 2.15.[0123]

### PR DESCRIPTION
**Pull request by andresailer**
Adds new and older version for LCIO

### CODE REVIEW

**Comment by andresailer** [comment]
@vvolkl @gaede, please review

**Review by vvolkl — APPROVED** [review]
Looks good!

**Review by vvolkl — APPROVED** [review]

**Review by gaede — COMMENTED** [review]
The 2.14.x versions have a severe memory leak when using LCReader::readNextEvent().
I am not sure we should have them in the spack recipe at all...
Apart from that it's fine with me.

**Comment by andresailer** [comment]
My rational for putting them in was that
```
$ spack versions lcio
==> Safe versions (already checksummed):
  master  2.15.2  2.15    2.14.1  2.13.3  2.13.1
  2.15.3  2.15.1  2.14.2  2.14    2.13.2
==> Remote versions (not yet checksummed):
==> Warning: Found no unchecksummed versions for lcio
```
can then be used to see if there are new versions available

**Review by gaede — APPROVED** [review]
Ok, makes sense.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
