### PR TITLE
ParaView: Add variant for VisItBridge

### PR DESCRIPTION
**Pull request by kwryankrattiger**

### CODE REVIEW

**Comment by cessenat** [comment]
Just to know : do you manage to read Silo files in Paraview thereafter ? I never managed to make it work.
See discussion https://discourse.paraview.org/t/adding-a-reader-plugin-via-visit-bridge/2177/15

**Comment by kwryankrattiger** [comment]
@mirenradia This may be of interest to you. I finally got around to breaking out bits from that other PR.

**Comment by mirenradia** [comment]
> @mirenradia This may be of interest to you. I finally got around to breaking out bits from that other PR.

Great, thanks for tagging me. Am looking forward to seeing this merged!

**Comment by kwryankrattiger** [comment]
@cessenat 
> do you manage to read Silo files in Paraview thereafter ?

AFAIK it is working in 5.10

**Comment by cessenat** [comment]
> @cessenat
> 
> > do you manage to read Silo files in Paraview thereafter ?
> 
> AFAIK it is working in 5.10

Yes it seems to work, despite I do not manage to get the pseudocolor plot that I so easily get with VisIt, I join a screenshot.
At least I have the mesh. Well probably Paraview's learning curve is much higher than
Capture d’écran du 2022-11-09 21-39-04
 the one of VisIt, I'm only a user of visualization tools, not an expert !

**Comment by cessenat** [comment]
This PR goes into the right direction ; I'm disappointed not to get with Paraview what I get with VisIt, but that is likely another matter.

**Comment by cessenat** [comment]
> This PR goes into the right direction ; I'm disappointed not to get with Paraview what I get with VisIt, but that is likely another matter.

Stupid me, someone showed me how to plot in paraview : now it is fine. This PR is fine for me.

**Comment by kwryankrattiger** [comment]
@vicentebolea Can you review this

**Review by vicentebolea — APPROVED** [review]
LGMT Good job @kwryankrattiger :)

**Comment by kwryankrattiger** [comment]
@tldahlgren Can you give this the green light?

**Review by mathstuf — APPROVED** [review]

**Review by scottwittenburg — APPROVED** [review]

**Pull request merged**
