### PR TITLE
Set # of ninja procs to 'make_jobs' for scipy

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR uses the `make_job` variable to set the number of build procs for py-scipy. Without it, builds can fail on high-CPU count, low-process limit systems.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Will wait for @rgommers to confirm that this looks right

**Review by rgommers — COMMENTED** [review]
The `-Ccompile-args=-j<int>` is correct. I couldn't see where `make_jobs` is defined, but if it's guaranteed to exist and be an integer, then this LGTM. If users want to set that, it comes from `--jobs` I think (https://spack.readthedocs.io/en/latest/packaging_guide.html#parallel-builds). And if users don't set it, is there a default?

**Comment by adamjstewart** [comment]
This is one of the parts of Spack that's a little _too_ magic. It's defined [here](https://github.com/spack/spack/blob/v0.20.1/lib/spack/spack/build_environment.py#L540) and introduced at module scope [here](https://github.com/spack/spack/blob/v0.20.1/lib/spack/spack/build_environment.py#L588). The default is `max(# cores, 16)` and it's always guaranteed to be an integer.

**Comment by rgommers** [comment]
Great, thanks for the explanation! This change should be the right one to make then for all packages that use `meson-python`.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
It seems there are issues on Apple `aarch64` pipelines

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
