### PR TITLE
exago@1.4.1: : needs py-pytest

### PR DESCRIPTION
**Pull request by eugeneswalker**
`exago@1.4.1:` needs `py-pytest` 

@ashermancinelli

### CODE REVIEW

**Review by ashermancinelli — APPROVED** [review]

**Comment by eugeneswalker** [comment]
So `py-pytest` is not needed for `@5-18-2022-snapshot` right? 

Unfortunately, `when='@1.4.1:'` will match `@5-12-2022-snapshot` -- I wonder if there might be another way to express this constraint so as to exclude `@5-18-2022-snapshot` from that match.

**Comment by cameronrutherford** [comment]
Perhaps we could attempt something similar to the HiOp version matrix to express this dependency? This should be something spack can handle...

**Comment by eugeneswalker** [comment]
Is it possible `py-pytest` is needed by the May 18th snapshot when building `exago +ipopt` ? I was having trouble building certain combinations of `exago@2022-05-18-snapshot +ipopt` before, but since trying with the py-pytest dependency I'm seeing some of those builds go through. I could be mistaken, but it seems like things are building now that were not previously.

**Comment by cameronrutherford** [comment]
> Is it possible `py-pytest` is needed by the May 18th snapshot when building `exago +ipopt` ? I was having trouble building certain combinations of `exago@2022-05-18-snapshot +ipopt` before, but since trying with the py-pytest dependency I'm seeing some of those builds go through. I could be mistaken, but it seems like things are building now that were not previously. 

https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/merge_requests/346 was the MR that introduced PyTest into develop. 

https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/blob/5-18-2022-snapshot/tests/interfaces/python/CMakeLists.txt - this is the CMakeLists in that snapshot. It doesn't require pytest at all, but perhaps there is some dependency with pybind11 submodule that isn't being expressed properly in that version?

**Comment by cameronrutherford** [comment]
I don't know what the issue would be with ExaGO + Ipopt and that version. We only test Ipopt with COINHSL instead of Mumps, so perhaps that's something else to try? Would be happy to work through any issues you're seeing, although that snapshot is quite out of date at this point

**Review by wspear — APPROVED** [review]
Looks good to me.

**Review by pelesh — APPROVED** [review]
Looks ok. Tests pass.

**Comment by pelesh** [comment]
> I don't know what the issue would be with ExaGO + Ipopt and that version. We only test Ipopt with COINHSL instead of Mumps, so perhaps that's something else to try? 

Ipopt's interface to Mumps has been buggy and we were seeing convergence failures that we could not reproduce with MA27 or MA57. We didn't have cycles to drill down that issue, so the next best solution was to build Ipopt without Mumps.

**Review by cameronrutherford — APPROVED** [review]

**Pull request merged**
