### PR TITLE
Update Stanford Legion Package

### PR DESCRIPTION
**Pull request by tuxfan**
- Switch to real project repository (previous was a mirror that is not
  kept up-to-date)
- Changed sha256 hashes to named tags
- Added version 20.03.0

### CODE REVIEW

**Comment by alalazo** [comment]
> Switch to real project repository (previous was a mirror that is not
kept up-to-date)

I have to say that this is a bit confusing. I see changes from 3 hours ago on the master branch on Github, lot more issues on Github than on Gitlab (but most PRs closed and not merged), their homepage points to Github (I see no links to Gitlab).

**Review by junghans — CHANGES_REQUESTED** [review]
I prefer tarballs over git tags as it is easier to mirror.

**Comment by junghans** [comment]
@streichler @elliottslaughter @lightsighter GitHub or GitLab, what is better?

**Comment by junghans** [comment]
> I prefer tarballs over git tags as it is easier to mirror.

I stand corrected, the mirroring issue has been solved. I, however, still don't like the fact that tags can change and there is no way of knowing for the user.

**Comment by streichler** [comment]
> @streichler @elliottslaughter @lightsighter GitHub or GitLab, what is better?

https://github.com/StanfordLegion/legion is the "public" repository - please build from clones of that repo or releases listed there.

**Comment by streichler** [comment]
> I stand corrected, the mirroring issue has been solved. I, however, still don't like the fact that tags can change and there is no way of knowing for the user.

If it makes you feel better, I can say that we "never" change tags used for releases.

**Comment by adamjstewart** [comment]
By the way, would any of you be interested in being "maintainers" for this Spack package? You don't have to be a Spack expert, it just gives us someone to contact for PR reviews or bug reports. If so, we can add your GitHub usernames in a `maintainers` list in the package.

**Comment by tuxfan** [comment]
@streichler @elliottslaughter @lightsighter: I don't understand your response. I think that it was just last week that Mike asked us to stop using github. He indicated that you would not be updating tags on the github mirror, and that we should use gitlab. What gives? We need versioning tags in one place or the other.

**Comment by junghans** [comment]
I separated the version bump into #16848

**Comment by junghans** [comment]
@tuxfan, you could use a different url pulling from gitlab for some versions if needed, e.g:
```diff
diff --git a/var/spack/repos/builtin/packages/legion/package.py b/var/spack/repos/builtin/packages/legion/package.py
index cac38dd03..bfc66daee 100644
--- a/var/spack/repos/builtin/packages/legion/package.py
+++ b/var/spack/repos/builtin/packages/legion/package.py
@@ -26,7 +26,7 @@ class Legion(CMakePackage):
     git      = "https://github.com/StanfordLegion/legion.git"

     version('master', branch='master')
-    version('ctrl-rep', branch='control_replication')
+    version('ctrl-rep', branch='control_replication', git='https://gitlab.com/StanfordLegion/legion.git'))
     version('20.03.0', sha256='ae5feedb5ed9f357b56424b9d73cea4f224a61e291e022556f796d1ff24d1244')
     version('19.12.0', sha256='ea517638de7256723bb9c119796d4d9d4ef662c52d0151ad24af5288e5a72e7d')
     version('19.09.1', sha256='c507133fb9dce16b7fcccd7eb2933d13cce96ecf835da60a27c0f66840cabf51')
```

**Comment by streichler** [comment]
> last week that Mike asked us to stop using github. He indicated that you would not be updating tags on the github mirror, and that we should use gitlab. What gives? We need versioning tags in one place or the other.

I apologize - I was unaware of the background for this request.  I still think that using github is the right answer, but let me sync up with Mike before causing y'all to thrash any more.

**Comment by streichler** [comment]
> By the way, would any of you be interested in being "maintainers" for this Spack package? You don't have to be a Spack expert, it just gives us someone to contact for PR reviews or bug reports. If so, we can add your GitHub usernames in a `maintainers` list in the package.

Go ahead and list me as the point of contact on the Legion side.

**Comment by jpietarilagraham** [comment]
Could the legion branches include a change to cmake so that legion_prof.py etc. end up in my path after I "activate" spack?

**Pull request closed without merging**
