### PR TITLE
add sra-toolkit@2.10.7

### PR DESCRIPTION
**Pull request by manifestoso**
new bio tools sra-toolkit

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like #16950 contains these same modifications. It's best to make each change on a separate branch and submit a separate PR for each package change. If you make all of the changes on a single branch (develop) then those changes will show up in all of your PRs.

**Comment by manifestoso** [comment]
> 
> 
> It looks like #16950 contains these same modifications. It's best to make each change on a separate branch and submit a separate PR for each package change. If you make all of the changes on a single branch (develop) then those changes will show up in all of your PRs.

Thx @adamjstewart for picking this one out. My bad ignorance. Now git history cleaned for this PR.

**Comment by adamjstewart** [comment]
It looks like there is already a `sratoolkit` package in Spack: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/sratoolkit/package.py

Maybe you can add a new version to that and add yourself as a maintainer?

**Comment by manifestoso** [comment]
> 
> 
> It looks like there is already a `sratoolkit` package in Spack: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/sratoolkit/package.py
> 
> Maybe you can add a new version to that and add yourself as a maintainer?

Oops I missed this one. Will comply. Thx @adamjstewart

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
