### PR TITLE
netlib-lapack: New version 3.10.1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by haampie — DISMISSED** [review]

**Review by eugeneswalker — COMMENTED** [review]
When I ran the checksums I got something different:
```
$> spack checksum netlib-lapack@3.10.0
...
version('3.10.0', sha256='92872e77feeade8d0156814ddfeecd250f933f4dcb882b7a46cc8fec581ae643')
```

And
```
$> spack checksum netlib-lapack@3.10.1
...
version('3.10.1', sha256='5c9c0fc37d8ddb5264ba996a08974596e1bc480dfac227c6bb00047894ef856e')
```

**Comment by haampie** [comment]
right, the spider follows the links from https://www.netlib.org/lapack/ which point to github as of 3.9.0 indeed... but we download from netlib.org because shasums from generated tarballs on github are unreliable

**Comment by eschnett** [comment]
@haampie I added explicit url. Is that what you suggested, or do I need to do something else?

**Comment by eschnett** [comment]
@haampiek @eugeneswalker what should I do? The checksums are working for me, I can `spack fetch netlib-lapack`. Please let me know what error your are seeing, or what actions I should take.

**Review by eugeneswalker — APPROVED** [review]
Thank you!

**Pull request merged**
