### PR TITLE
Add new versions for toml11

### PR DESCRIPTION
**Pull request by alephpiece**
Added 3.8.0 and 3.8.1

@spackbot fix style

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed both new version sha256s.  Will defer merge decision to give @toruniina and or @ashermancinelli time to comment (in case there are other related changes needed).

**Review by ToruNiina — COMMENTED** [review]
I also checked sha256sum of `v3.8.1.tar.gz` and `v3.8.0.tar.gz`.

I don't know anything about spack config file, but don't we need to update the `url` to the latest version?

**Review by ashermancinelli — APPROVED** [review]
If the hashes are good then it lgtm. @tldahlgren knows better, but I don't think we need to update the url. Thanks!

**Comment by tldahlgren** [comment]
> I also checked sha256sum of `v3.8.1.tar.gz` and `v3.8.0.tar.gz`.

My main concern is whether there are changes needed to dependencies -- new ones need to be added and or old ones no longer apply -- for any of the new version(s).  If changes are needed then there is likely a need for conditional dependencies (see docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#conditional-dependencies).

> 
> I don't know anything about spack config file, but don't we need to update the `url` to the latest version?

Not necessary IF spack can make the version substitution in the current url.  This is touched on in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls.

**Comment by ToruNiina** [comment]
There is no dependency except for the language standard library.

> Not necessary IF spack can make the version substitution in the current url.

Then, it's okay.

**Comment by tldahlgren** [comment]
Looks like the build of toml11 is failing, e.g.,

```
     13    -- Detecting CXX compile features
     14    -- Detecting CXX compile features - done
  [0;91m>> 15    CMake Error at CMakeLists.txt:18 (message):[0m
     16      CMAKE_CXX_STANDARD is not defined.  The C++ standard whose feature
           s are
     17      requested to *build* all targets.  Remember that toml11 is a heade
           r only
     18      library that does NOT require compilation to use.
     19    
     20    
     21    -- Configuring incomplete, errors occurred!
```

**Comment by alephpiece** [comment]
Just noticed the cxx standard variable was unset, starting from 3.8. Will fix it soon!

**Comment by alephpiece** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Thanks.

**Pull request merged**
