### PR TITLE
New version: py-testpath 0.6.0; update py-flit-core dependency

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@spackbot run pipeline

**Review by adamjstewart — DISMISSED** [review]

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@adamjstewart can this be merged?

**Comment by alalazo** [comment]
@iarspider Can you please rebase this PR?

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
