### PR TITLE
Update amrex maintainers

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Review by asalmgren — APPROVED** [review]

**Review by tldahlgren — COMMENTED** [review]
@atmyers please confirm your willingness to be a maintainer (see docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers).

(Note: The @atmyers account doesn't auto fill.)

**Review by tldahlgren — APPROVED** [review]
Hoping for a response before merging.

**Comment by atmyers** [comment]
I confirm my willingness to be a maintainer.

**Comment by tldahlgren** [comment]
> I confirm my willingness to be a maintainer.

Thanks.

**Pull request merged**
