### PR TITLE
Remove special logic for build dependencies from uninstall

### LINKED ISSUE #31366: Spack emits warnings when uninstalling
### Steps to reproduce

Install a fake hdf5 spec:
```console
% spack install --fake hdf5~mpi
```
then try to uninstall everything:
```
% spack uninstall -ay
```

### Error message

It seems a few specs are uninstalled after their dependencies:
```console
% spack uninstall -ay          
==> Successfully uninstalled hdf5@1.12.2%apple-clang@13.1.6~cxx~fortran~hl~ipo~java~mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=darwin-monterey-cannonlake/caxxhht
==> Successfully uninstalled perl@5.34.1%apple-clang@13.1.6+cpanm+shared+threads arch=darwin-monterey-cannonlake/l4d3tqx
==> Successfully uninstalled diffutils@3.8%apple-clang@13.1.6 arch=darwin-monterey-cannonlake/677cyo3
==> Successfully uninstalled cmake@3.23.2%apple-clang@13.1.6~doc+ncurses+ownlibs~qt build_type=Release arch=darwin-monterey-cannonlake/tq6p7gg
==> Successfully uninstalled gdbm@1.19%apple-clang@13.1.6 arch=darwin-monterey-cannonlake/4ybhqy2
==> Successfully uninstalled pkgconf@1.8.0%apple-clang@13.1.6 arch=darwin-monterey-cannonlake/fmbswuq
==> Successfully uninstalled libiconv@1.16%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-cannonlake/jccfr3e
==> Successfully uninstalled berkeley-db@18.1.40%apple-clang@13.1.6+cxx~docs+stl patches=b231fcc arch=darwin-monterey-cannonlake/emmgknu
==> Successfully uninstalled openssl@1.1.1p%apple-clang@13.1.6~docs~shared certs=mozilla arch=darwin-monterey-cannonlake/qgrwq3g
==> Warning: Inconsistent state! Dependent l4d3tqxkjeemrtchiti6styj6uvf7edg of c2ltv4o2apqzkwoddn2chb5so247yjw6 not in DB
==> Successfully uninstalled bzip2@1.0.8%apple-clang@13.1.6~debug~pic+shared arch=darwin-monterey-cannonlake/c2ltv4o
==> Warning: Inconsistent state! Dependent 4ybhqy26jqehdr24exjfx2kgxgbs2guu of 4brdp3xifvsyf7lvxw64osk5flfft7g2 not in DB
==> Warning: Inconsistent state! Dependent l4d3tqxkjeemrtchiti6styj6uvf7edg of 4brdp3xifvsyf7lvxw64osk5flfft7g2 not in DB
==> Successfully uninstalled readline@8.1%apple-clang@13.1.6 arch=darwin-monterey-cannonlake/4brdp3x
==> Warning: Inconsistent state! Dependent l4d3tqxkjeemrtchiti6styj6uvf7edg of idlxgon6vnmzvr4mdr6tgiatdsszurz6 not in DB
==> Successfully uninstalled zlib@1.2.12%apple-clang@13.1.6+optimize+pic+shared patches=0d38234 arch=darwin-monterey-cannonlake/idlxgon
==> Successfully uninstalled ca-certificates-mozilla@2022-03-29%apple-clang@13.1.6 arch=darwin-monterey-cannonlake/obbwdew
==> Successfully uninstalled ncurses@6.2%apple-clang@13.1.6~symlinks+termlib abi=none arch=darwin-monterey-cannonlake/p7kdu65
```

### Information on your system

* **Spack:** 0.19.0.dev0 (58b144c0dae88d6a06d3d138c077c4c70909c5f7)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-cannonlake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes #31366

### CODE REVIEW

**Comment by tgamblin** [comment]
A build dependency shouldn't force something to stay installed -- because it's not a runtime requirement.  We should fix the warning, not this logic.

**Comment by alalazo** [comment]
Fair. There's another possible issue here though. After the full hash change the `ref_count` in the DB is also counting build dependencies. So, before that change my understanding was that `ref_count` was counting how many specs were still depending on the current one to run.[^1] Right now build dependencies are also counted, so it's unclear to me what `ref_count` represents, since it's not an indicator anymore if something is not safe to remove.

[^1]: To be clear, it was counting direct `link` and `run` dependents

**Comment by tgamblin** [comment]
It's still counting the number of directly installed dependents, like it was before (we just previously forgot about build dependents).  I agree it's not very useful for uninstall now.  I'm not sure we really need it, since we'll always have the dependent edges to look at, and the check we need to do is more complicated now.  I'm not opposed to deprecating ref_count.

**Comment by alalazo** [comment]
> I agree it's not very useful for uninstall now. I'm not sure we really need it, since we'll always have the dependent edges to look at, and the check we need to do is more complicated now. I'm not opposed to deprecating ref_count.

I agree with that. Was wondering if we can keep `ref_count` in the DB, but count as before, i.e. only direct `link` and `run` dependencies. In that way any context that needs to uninstall can rely on `ref_count` and the complexity is pushed to a few methods in `database.py`.

**Comment by tgamblin** [comment]
I don't see anything fundamentally wrong with that, but I'm not sure it covers all the cases.  The ref count not only tells you whether you can uninstall, but also whether you should keep a node in the database (installed or not). I think it still serves the latter purpose in its current form, but wouldn't with this change.  So would *that* logic become more complicated?

**Comment by haampie** [comment]
We can probably work around it by uninstalling in topo order #33817.

Edit: ah no. I misunderstood. So the idea previously was to take a package to be uninstalled, collect its parents of link/run type recursively, and then `for root in subdag: delete node`. Well, the latter can be done in a nice way with topo sort (instead of the iterative business we have now), but that doesn't solve the underlying problem that `ref_count == 0` iff package is a root in the sub-dag of link/run edges no longer holds.

To be fair, there's no point of deleting in order if you can just as well do a batch update to the database... it will be in a consistent state after the batch delete :upside_down_face:

**Comment by haampie** [comment]
Actually the issue is gone for me after a topo sort:

```diff
diff --git a/lib/spack/spack/cmd/uninstall.py b/lib/spack/spack/cmd/uninstall.py
index 8c112840fd..d0ac3a0456 100644
--- a/lib/spack/spack/cmd/uninstall.py
+++ b/lib/spack/spack/cmd/uninstall.py
@@ -19,6 +19,8 @@
 import spack.store
 from spack.database import InstallStatuses
 
+import spack.traverse as traverse
+
 description = "remove installed packages"
 section = "build"
 level = "short"
@@ -234,6 +236,10 @@ def do_uninstall(env, specs, force):
         specs (list): list of specs to be uninstalled
         force (bool): force uninstallation (boolean)
     """
+    ordered = list(reversed(list(traverse.traverse_nodes(specs, order="topo", direction="parents", deptype=("link", "run")))))
+    assert set(ordered) == set(specs)
+    specs = ordered
+
     packages = []
     for item in specs:
         try:
@@ -260,9 +266,8 @@ def is_ready(dag_hash):
             for dspec in record.spec.edges_from_dependents()
         )
 
-    while packages:
-        ready = [x for x in packages if is_ready(x.spec.dag_hash())]
-        if not ready:
+    for p in packages:
+        if not is_ready(p.spec.dag_hash()):
             msg = (
                 "unexpected error [cannot proceed uninstalling specs with"
                 " remaining link or run dependents {0}]"
@@ -270,9 +275,7 @@ def is_ready(dag_hash):
             msg = msg.format(", ".join(x.name for x in packages))
             raise spack.error.SpackError(msg)
 
-        packages = [x for x in packages if x not in ready]
-        for item in ready:
-            item.do_uninstall(force=force)
+        p.do_uninstall(force=force)
 
 
 def get_uninstall_list(args, specs, env):
```

Before:

```
harmen-desktop tmp.U9l0CBMmJp $ spack -c config:install_tree:root:here uninstall --dependents zlib
==> The following packages will be uninstalled:

    -- linux-ubuntu22.04-zen2 / gcc@11.2.0 --------------------------
    54v6eey autoconf@2.69    ze4qep2 cmake@3.24.3    i7fwmmx krb5@1.19.3      xd7knzw libxml2@2.10.1   hna2id7 openssh@9.1p1   sevlta2 pigz@2.7       3cwnime spglib@1.16.1  i55tsxs zlib@1.2.13
    fqz7v3y automake@1.16.5  7kfcdxp gettext@0.21.1  cd5sgyq libevent@2.1.12  vtwf2iv numactl@2.0.14   t7yk5k6 openssl@1.1.1s  gm6nmxp pmix@4.1.2     he5h4dd sqlite@3.39.4
    ju6bnpf bison@3.8.2      zgfaibe hwloc@2.8.0     qqi57ki libxc@5.2.3      7zsdvme openblas@0.3.21  vc4kuph perl@5.36.0     fchzidv python@3.10.8  aculmda tar@1.34

==> Do you want to proceed? [y/N] y
==> Successfully uninstalled python@3.10.8%gcc@11.2.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-ubuntu22.04-zen2/fchzidv
==> Successfully uninstalled openssh@9.1p1%gcc@11.2.0+gssapi build_system=autotools arch=linux-ubuntu22.04-zen2/hna2id7
==> Successfully uninstalled pmix@4.1.2%gcc@11.2.0~docs+pmi_backwards_compatibility~restful build_system=autotools arch=linux-ubuntu22.04-zen2/gm6nmxp
==> Successfully uninstalled numactl@2.0.14%gcc@11.2.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu22.04-zen2/vtwf2iv
==> Successfully uninstalled automake@1.16.5%gcc@11.2.0 build_system=autotools arch=linux-ubuntu22.04-zen2/fqz7v3y
==> Successfully uninstalled spglib@1.16.1%gcc@11.2.0~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-ubuntu22.04-zen2/3cwnime
==> Successfully uninstalled autoconf@2.69%gcc@11.2.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu22.04-zen2/54v6eey
==> Successfully uninstalled cmake@3.24.3%gcc@11.2.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-zen2/ze4qep2
==> Successfully uninstalled bison@3.8.2%gcc@11.2.0 build_system=autotools arch=linux-ubuntu22.04-zen2/ju6bnpf
==> Successfully uninstalled openblas@0.3.21%gcc@11.2.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=none threads=openmp arch=linux-ubuntu22.04-zen2/7zsdvme
==> Successfully uninstalled libxc@5.2.3%gcc@11.2.0~cuda+shared build_system=autotools arch=linux-ubuntu22.04-zen2/qqi57ki
==> Successfully uninstalled krb5@1.19.3%gcc@11.2.0+shared build_system=autotools arch=linux-ubuntu22.04-zen2/i7fwmmx
==> Successfully uninstalled libevent@2.1.12%gcc@11.2.0+openssl build_system=autotools arch=linux-ubuntu22.04-zen2/cd5sgyq
==> Successfully uninstalled hwloc@2.8.0%gcc@11.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2/zgfaibe
==> Successfully uninstalled perl@5.36.0%gcc@11.2.0+cpanm+shared+threads build_system=generic arch=linux-ubuntu22.04-zen2/vc4kuph
==> Successfully uninstalled sqlite@3.39.4%gcc@11.2.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-zen2/he5h4dd
==> Successfully uninstalled gettext@0.21.1%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu22.04-zen2/7kfcdxp
==> Successfully uninstalled openssl@1.1.1s%gcc@11.2.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-zen2/t7yk5k6
==> Successfully uninstalled tar@1.34%gcc@11.2.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-zen2/aculmda
==> Successfully uninstalled libxml2@2.10.1%gcc@11.2.0~python build_system=autotools arch=linux-ubuntu22.04-zen2/xd7knzw
==> Successfully uninstalled pigz@2.7%gcc@11.2.0 build_system=makefile arch=linux-ubuntu22.04-zen2/sevlta2
==> Warning: Inconsistent state! Dependent vc4kuphzwsemw23up4o2kwx5tja5gvmq of i55tsxsepukei4klbtquplznt5oxzyvy not in DB
==> Successfully uninstalled zlib@1.2.13%gcc@11.2.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-zen2/i55tsxs
```

After:

```
harmen-desktop tmp.U9l0CBMmJp $ spack -c config:install_tree:root:here uninstall --dependents zlib
==> The following packages will be uninstalled:

    -- linux-ubuntu22.04-zen2 / gcc@11.2.0 --------------------------
    54v6eey autoconf@2.69    ze4qep2 cmake@3.24.3    i7fwmmx krb5@1.19.3      xd7knzw libxml2@2.10.1   hna2id7 openssh@9.1p1   sevlta2 pigz@2.7       3cwnime spglib@1.16.1  i55tsxs zlib@1.2.13
    fqz7v3y automake@1.16.5  7kfcdxp gettext@0.21.1  cd5sgyq libevent@2.1.12  vtwf2iv numactl@2.0.14   t7yk5k6 openssl@1.1.1s  gm6nmxp pmix@4.1.2     he5h4dd sqlite@3.39.4
    ju6bnpf bison@3.8.2      zgfaibe hwloc@2.8.0     qqi57ki libxc@5.2.3      7zsdvme openblas@0.3.21  vc4kuph perl@5.36.0     fchzidv python@3.10.8  aculmda tar@1.34

==> Do you want to proceed? [y/N] y
==> Successfully uninstalled python@3.10.8%gcc@11.2.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-ubuntu22.04-zen2/fchzidv
==> Successfully uninstalled openssh@9.1p1%gcc@11.2.0+gssapi build_system=autotools arch=linux-ubuntu22.04-zen2/hna2id7
==> Successfully uninstalled pmix@4.1.2%gcc@11.2.0~docs+pmi_backwards_compatibility~restful build_system=autotools arch=linux-ubuntu22.04-zen2/gm6nmxp
==> Successfully uninstalled krb5@1.19.3%gcc@11.2.0+shared build_system=autotools arch=linux-ubuntu22.04-zen2/i7fwmmx
==> Successfully uninstalled numactl@2.0.14%gcc@11.2.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu22.04-zen2/vtwf2iv
==> Successfully uninstalled automake@1.16.5%gcc@11.2.0 build_system=autotools arch=linux-ubuntu22.04-zen2/fqz7v3y
==> Successfully uninstalled spglib@1.16.1%gcc@11.2.0~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-ubuntu22.04-zen2/3cwnime
==> Successfully uninstalled autoconf@2.69%gcc@11.2.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu22.04-zen2/54v6eey
==> Successfully uninstalled libevent@2.1.12%gcc@11.2.0+openssl build_system=autotools arch=linux-ubuntu22.04-zen2/cd5sgyq
==> Successfully uninstalled hwloc@2.8.0%gcc@11.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2/zgfaibe
==> Successfully uninstalled cmake@3.24.3%gcc@11.2.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-zen2/ze4qep2
==> Successfully uninstalled bison@3.8.2%gcc@11.2.0 build_system=autotools arch=linux-ubuntu22.04-zen2/ju6bnpf
==> Successfully uninstalled gettext@0.21.1%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu22.04-zen2/7kfcdxp
==> Successfully uninstalled openssl@1.1.1s%gcc@11.2.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-zen2/t7yk5k6
==> Successfully uninstalled openblas@0.3.21%gcc@11.2.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=none threads=openmp arch=linux-ubuntu22.04-zen2/7zsdvme
==> Successfully uninstalled libxc@5.2.3%gcc@11.2.0~cuda+shared build_system=autotools arch=linux-ubuntu22.04-zen2/qqi57ki
==> Successfully uninstalled perl@5.36.0%gcc@11.2.0+cpanm+shared+threads build_system=generic arch=linux-ubuntu22.04-zen2/vc4kuph
==> Successfully uninstalled tar@1.34%gcc@11.2.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-zen2/aculmda
==> Successfully uninstalled sqlite@3.39.4%gcc@11.2.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-zen2/he5h4dd
==> Successfully uninstalled libxml2@2.10.1%gcc@11.2.0~python build_system=autotools arch=linux-ubuntu22.04-zen2/xd7knzw
==> Successfully uninstalled pigz@2.7%gcc@11.2.0 build_system=makefile arch=linux-ubuntu22.04-zen2/sevlta2
==> Successfully uninstalled zlib@1.2.13%gcc@11.2.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-zen2/i55tsxs
```

Question remains: why

**Pull request closed without merging**
