### PR TITLE
amrex: add SYCL support

### PR DESCRIPTION
**Pull request by mic84**

### CODE REVIEW

**Comment by adamjstewart** [comment]
We don't normally add dependencies on compilers, as users can choose which compiler to use via `spack install amrex %oneapi`

Also, can you resolve the merge conflicts?

**Comment by mic84** [comment]
@adamjstewart amrex supports SYCL via dpcpp only so the dependency on the oneapi compilers is necessary when `+sycl`. I think this may be the case for most of the packages currently supporting SYCL. I could get rid of the oneapi dependency but then I will have to error if any compiler other than `dpcpp` is used.

**Comment by adamjstewart** [comment]
Hmm, is it possible/useful to build `amrex %oneapi ~sycl`?

**Comment by mic84** [comment]
if `~sycl`, there are no constrains on the compiler, at least in principle. Plus, I think that currently  `intel-oneapi-compiler` does not define any compiler in the environment so it cannot be used without manually tinkering with the `compiler.yaml` ( this is last week status, not sure if a fix has been issued by now). 

The issue here is that only `amrex %oneapi +sycl` will work, hence the dependency on oneapi, i.e. `amrex %any-compiler-but-oneapi +syc` will not work.

This PR temporally addresses the need to provide support for SYCL while waiting for a "native" Spack implementation. We discussed this issue at the E4S hackathon last week and it seems there are not many better ways to do this for the time being. @sshudler any thought on this?

**Comment by adamjstewart** [comment]
Thanks for the clarification! One more question: if I build `amrex %gcc +sycl`, will it use GCC to build all the C/C++/Fortran-stuff and OneAPI for the SYCL stuff?

**Comment by mic84** [comment]
`amrex %gcc +sycl` will not work as stated in my previous answer. If SYCL is enabled, you need oneapi. It will not work with any other compiler, hence the dependency on oneapi.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
