### PR TITLE
gcta: use intel-oneapi-mkl, fix build with gcc-13+

### PR DESCRIPTION
**Pull request by hainest**
intel-mkl fails to concretize with the 'Cannot select a single version' error. My guess would be because all of its versions are marked deprecated.

### CODE REVIEW

**Comment by snehring** [comment]
I'm sure this change is fine, but I'm actually having issues compiling gcta at all at the moment.

**Comment by snehring** [comment]
Newer cmake versions cause issues seemingly, I'll fix that after this is merged. @hainest what cmake did you build this with out of curiosity?

**Comment by snehring** [comment]
Disregard. My package.py was just in a weird state.

**Review by snehring — APPROVED** [review]
lgtm.

**Review by tldahlgren — DISMISSED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
The following specs were checked (extracted from `gh pr diff`):
- `gcta`

These specs were installed (`~disabled` variants are hidden):
```py
bin/spack find --variants gcta | sed 's/~[a-z]*//g;s/ [a-z0-9_]*=[a-zA-Z0-9]*//g'
-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
gcta@1.91.2
gcta@1.94.0beta
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -a
```

**Pull request merged**
