### PR TITLE
hpctoolkit: add variants for gtpin and opencl

### PR DESCRIPTION
**Pull request by mwkrentel**
Reorder a few options to better group them by function.

### CODE REVIEW

**Comment by mwkrentel** [comment]
ping @jmellorcrummey if you want to review or comment
I can't seem to officially request you as reviewer.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
Will defer merge (decision) until @jmellorcrummey has a chance to comment (given the above request).

**Comment by tldahlgren** [comment]
> ping @jmellorcrummey if you want to review or comment
> I can't seem to officially request you as reviewer.

FWIW. I can't either.

**Comment by jmellorcrummey** [comment]
LGTM. Merge away!

**Pull request merged**
