### PR TITLE
Spack Bioconductor package updates

### PR DESCRIPTION
**Pull request by glennpj**
This PR updates the Spack BioConductor R packages to BioConductor Release 3.16.

[Bioconductor - Bioconductor 3.16 Released](https://bioconductor.org/news/bioc_3_16_release/)

### CODE REVIEW

**Comment by glennpj** [comment]
@spackbot start pipeline

**Comment by glennpj** [comment]
@spackbot run pipeline

**Review by tldahlgren — COMMENTED** [review]
I was able to confirm the commits/sha256 for all but two packages:

- r-delayedmatrixstats@1.20.0
- r-phyloseq@1.42.0

**Comment by glennpj** [comment]
> I was able to confirm the commits/sha256 for all but two packages:
> 
> * r-delayedmatrixstats@1.20.0
> * r-phyloseq@1.42.0

@tldahlgren What was your process for checking these? Looking in the respective git repos the commits match what is in the package.

**Comment by tldahlgren** [comment]
> > I was able to confirm the commits/sha256 for all but two packages:
> > 
> > * r-delayedmatrixstats@1.20.0
> > * r-phyloseq@1.42.0
> 
> @tldahlgren What was your process for checking these? Looking in the respective git repos the commits match what is in the package.

I have a script I'm working on that tries to perform a quick check.  It resorts to `spack stage` if it can't use any of the easier approaches.

Not being an `R` person, I wasn't sure of a good, general, fast approach to go from a Spack package to the `cran` or `bioc` repos to confirm commits.  Any suggestions are appreciated.

**Comment by tldahlgren** [comment]
> > I was able to confirm the commits/sha256 for all but two packages:
> > 
> > * r-delayedmatrixstats@1.20.0
> > * r-phyloseq@1.42.0
> 
> @tldahlgren What was your process for checking these? Looking in the respective git repos the commits match what is in the package.

Manually checking them, whether `fetch` or `stage`, I get:

```
$ spack fetch r-delayedmatrixstats@1.20.0
==> Error: No valid version for 'r-matrix' satisfies '@1.5-0:'
$ spack fetch r-phyloseq@1.42.0
==> Error: No valid version for 'r-ade4' satisfies '@1.7-4:'
```

**Comment by glennpj** [comment]
@tldahlgren Good catch!

R packages use either "." or "-" in their version specifiers. Sometimes the packages change formats, and sometimes the wrong format is used in the `DESCRIPTION` file. In both of these cases, previous versions had specified the dependency versions incorrectly. Using the format in the `DESCRIPTION` file:
`r-matrix>=1.5.0` instead of `r-matrix>=1.5-0`
`r-ade>=1.7.4` instead of `r-ade>=1.7-4`

Since the incorrectly labeled versions do not exist in Spack, it produces an error. It is interesting that the error lists the version with the correct specification as not valid. In any event, I just pushed a commit so fetching/staging should work for those now.

**Review by tldahlgren — APPROVED** [review]
Confirmed all of the new versions (sha256's and commits).

**Pull request merged**
