### PR TITLE
Ascent: Patch @0.8: for finding RAJA

### PR DESCRIPTION
**Pull request by willdunklin**

### CODE REVIEW

**Review by cyrush — APPROVED** [review]

**Comment by willdunklin** [comment]
@cyrush I see you've approved the branch. Is there any chance this could get merged in? Thanks

**Comment by cyrush** [comment]
@willdunklin I don't have merge powers.
@tldahlgren  can you help us with the final review?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Just as a note, the title is inconsistent. This PR patches v0.9.0 for finding raja - not v0.8 and greater. IF that was not just a typo, feel free to submit a fix and ping me there.

**Comment by cyrush** [comment]
I think we will want this for just `0.9.0`

**Pull request merged**
