### PR TITLE
py-kaleido: Fix broken package.py

### LINKED ISSUE #43302: Installation issue: py-kaleido
### Steps to reproduce the issue

```console
$ spack install py-kaleido@0.2.1
```

### Error message

Two issues...

Firstly, the `sha256` for this version has changed. The new one is:
`version("0.2.1", sha256="372928676d2843e316ea7d7272d6a85f10f936a0ca685b56db410e88769f4cdd")`

Secondly, the install process attempts to find a `spack-src/repos/kaleido/py/repos/kaleido/py/kaleido/_version` file, which is absent, giving:

<details><summary>Error message</summary>

<pre>
     64          setup_py_code = "from setuptools import setup; setup()"
     65    
     66      exec(compile(setup_py_code, filename, "exec"))
     67      '"'"''"'"''"'"' % ('"'"'/opt/software/.spack/build/root/spack-stage-py-kaleido-0.2.1-2iqpnu3zgryqv3imtx3maksjpkdj74g2/spack-src/repos/kaleido/py/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-gev2sn6_
     68      cwd: /opt/software/.spack/build/root/spack-stage-py-kaleido-0.2.1-2iqpnu3zgryqv3imtx3maksjpkdj74g2/spack-src/repos/kaleido/py/
     69      Preparing metadata (setup.py): finished with status 'error'
  >> 70    error: metadata-generation-failed
     71    
     72    × Encountered error while generating package metadata.
     73    ╰─> See above for output.
     74    
     75    note: This is an issue with the package mentioned above, not pip.
     76    hint: See above for details.
</pre></details>

This file could be inserted, but it appears from the [docs](https://pypi.org/project/kaleido/) that the install methods are all actually reliant on Docker. I'm not sure how this was installing itself before (I assume it was doing so correctly?), therefore, as it's otherwise a very minimal `package.py`.

Preferred means of distribution appears to be by [`.whl`](https://pypi.org/project/kaleido/0.2.1/#files).

### Information on your system

```
* **Spack:** 0.22.0.dev0 (b521b5edefa0393eae6b05c22a1456fdbed20729)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-icelake
* **Concretizer:** clingo
```

### Additional information

@Pandapip1 There's obviously been a change in what's downloaded as the `sha256` has changed. Was this definitely working previously?

[spack-build-env.txt](https://github.com/spack/spack/files/14694738/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14694739/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by Pandapip1**
Fixes https://github.com/spack/spack/issues/43302

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Was able to install py-kaleido@0.2.1 with the current state

**Review by Queenkaz — COMMENTED** [review]
K

**Comment by haampie** [comment]
@bernhardkaindl can you please not merge these type of PRs? We want source builds, not prebuilt binaries.

**Comment by scheibelp** [comment]
@haampie I mentioned in slack that it's prebuilt binaries either way you do this (either the wheels or the zips provided with the releases) - to be more precise, we anticipate that the more-general (but still-platform-specific) binaries provided by e.g. `kaleido_minimal_linux_x64.zip` in https://github.com/plotly/Kaleido/releases/tag/v0.2.0 will be less of a maintenance burden.

**Comment by haampie** [comment]
@bernhardkaindl was not part of that conversation?

**Comment by scheibelp** [comment]
> bernhardkaindl was not part of that conversation?

@haampie are you responding to https://github.com/spack/spack/pull/43309#issuecomment-2019551353? If so, I'm confused:

* You say in https://github.com/spack/spack/pull/43309#issuecomment-2019542472 that we want source builds vs. prebuilt binaries
* I'm pointing out to you that we spoke on Slack and that all solutions that we discussed (including the one used by Conda) involve using prebuilt binaries (Conda just limits itself to a more-general set of prebuilt binaries)

**Comment by Pandapip1** [comment]
Also, the package was broken and was already using binaries. Having working binaries isn't perfect, but it's better than broken ones. +1 to source builds, but that's a bit more work than I'm comfortable doing (I managed to mess up a binary package, after all!).

**Pull request merged**
