### PR TITLE
pax-utils: add v1.3.3

### PR DESCRIPTION
**Pull request by alecbcs**
Add pax-utils v1.3.3.

**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Comment by alecbcs** [comment]
@junghans as the original author of this package in Spack, would you be interested in joining as a maintainer?

**Comment by junghans** [comment]
> @junghans as the original author of this package in Spack, would you be interested in joining as a maintainer?

Meh, not even sure what I needed this package for.

**Review by junghans — APPROVED** [review]

**Comment by alecbcs** [comment]
> Meh, not even sure what I needed this package for.

If no one else happens to be using this package, perhaps we should think about removing it from the repository.

**Comment by junghans** [comment]
I remember now, there is a sandbox package that we wanted to use to restrict write permission during build, not sure we ever got to it.

**Pull request merged**
