### PR TITLE
py-tensorflow: fix numa build

### LINKED ISSUE #63080: Failing to build version 2.14.0 with numa
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

linux rocky8

### Mobile device

_No response_

### Python version

3.8.7

### Bazel version

6.1.0

### GCC/compiler version

gcc 11.3.0

### CUDA/cuDNN version

cuda 11.8.0

### GPU model and memory

_No response_

### Current behavior?

tensorflow v2.14.0 seems to fail configuring when adding --config=numa 
```
bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spackweoy5szc' 'build' '--color=no' '--jobs=10' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=numa' '--config=v2' '//tensorflow/tools/pip_package:build_pip_package'
...
ERROR: Config value 'numa' is not defined in any .rc file
```

### Standalone code to reproduce the issue

```shell
bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spackweoy5szc' 'build' '--color=no' '--jobs=10' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=numa' '--config=v2' '//tensorflow/tools/pip_package:build_pip_package'
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by adamjstewart**
@fgava90 can you test this? If this works, I think we can close https://github.com/tensorflow/tensorflow/issues/63080

### CODE REVIEW

**Comment by adamjstewart** [comment]
I'm also thinking about changing the variant defaults from the minimal build to the default build like we did with PyTorch. This will enable numa by default. But want to do that in a separate PR.

**Comment by fgava90** [comment]
Hi @adamjstewart , 
Thanks for fixing this. 
ATM i'm swamped, but as soon as i have a minute i'll try this fix and let you know!

**Comment by adamjstewart** [comment]
Ping @fgava90

**Review by fgava90 — APPROVED** [review]
Tested and working with specs `py-tensorflow@2.14.0%gcc@11.4.0~android~aws~computecpp+cuda~dynamic_kernels~gcp~gdr~hdfs~ios~jemalloc~mkl~monolithic+mpi+nccl~ngraph+numa~opencl~rocm~tensorrt~verbs+xla build_system=generic cuda_arch=75,80 patches=2017b3e arch=linux-rocky8-x86_64`

**Review by alalazo — APPROVED** [review]

**Pull request merged**
