### PR TITLE
More consistent yes/no prompts

### PR DESCRIPTION
**Pull request by adamjstewart**
Previously, there were two functions, `tty.get_yes_or_no` and `spack.cmd.ask_for_confirmation` that basically did the same thing. They were formatted slightly differently (one added a newline character and one didn't). I prefer the former, so I refactored things and removed `spack.cmd.ask_for_confirmation`.

@alalazo

### CODE REVIEW

**Comment by adamjstewart** [comment]
One more difference: `tty.get_yes_or_no` and `tty.get_number` don't actually print the colored `==>` prefix. Do we want them to?

**Comment by tgamblin** [comment]
Thanks!  I have been wanting to remove the newline for a while.  I don't know other things that prompt like that.  

> One more difference: tty.get_yes_or_no and tty.get_number don't actually print the colored ==> prefix. Do we want them to?

Seems reasonable to make them consistent.

**Comment by adamjstewart** [comment]
Done. The `tty` module is pretty sweet, but it could use a bit more documentation... It's hard to tell what arguments each method takes, and why they would be different at all. They also duplicate a lot of work. Aside from the color and whether or not they result in `sys.exit`, they should be identical.

**Comment by citibeth** [comment]
Those utilities could also be pulled out into another package.  See what happens without that:

https://github.com/citibeth/modele-control/tree/develop/lib

**Pull request merged**
