### PR TITLE
fix berkelygw without-mpi variant

### PR DESCRIPTION
**Pull request by glaweh**
closes #34061

The package.py assumed "+mpi" in many places, without checking for the variant. This problem went undetected, as a hard dependency on scalapack pulled an mpi implementation into the dependency chain (this is also fixed).

### CODE REVIEW

**Comment by migueldiascosta** [comment]
thanks @glaweh, you're absolutely right

better let https://github.com/spack/spack/pull/33898 go in first, and maybe we can then also address the python deps (https://github.com/spack/spack/pull/33898#pullrequestreview-1180065850)

**Review by bernhardkaindl — DISMISSED** [review]
@migueldiascosta: I think dropping python EOL versions in #33898 may need more time

AFAICS, this PR has nothing to do with python and it is usually better to not lump many different things into one PR.

Also, I do not want to burden @glaweh with having to wait an monitor the python EOL PR and then burden him to add this as well. It's more focussed and light-weight to merge this now, get this fix out and then handle python in a separate PR - This PR already has many lines of diff.

**Comment by migueldiascosta** [comment]
@bernhardkaindl ok. but are you guys able to actually install berkeleygw with the current `develop` branch? I get  `Error: AttributeError: 'str' object has no attribute 'propagate'` at the end of the `install` step

**Comment by bernhardkaindl** [comment]
> @bernhardkaindl ok. but are you guys able to actually install berkeleygw with the current `develop` branch? I get `Error: AttributeError: 'str' object has no attribute 'propagate'` at the end of the `install` step

Thanks for testing! Yes, I did, and I reproduced this as well. 

But I found that this PR is not the cause of it:

Thru the github search, I found that this error was reported with `ncurses` 16 days ago,
in issue #33696.

I also found that I reproduced the same error also without this PR.

I bisected where the Error occurred first: It appears since https://github.com/spack/spack/pull/29761 (Enable/Disable Propagation for Compiler Flags & Variants) was merged.

I came up with a simple check and fallback for when this attribute is missing and found that this fixes the AttributeError: #34019

@migueldiascosta Because you can review #34019, would you review (maybe test) and approve it?

Otherwise, would you add a comment to #34019 that this fixes the AttributeError? Thanks!

Since the `AttributeError: 'str' object has no attribute 'propagate'` with #33 is an independent issue, I think we can apply this update as unrelated to the AttributeError.

**Comment by bernhardkaindl** [comment]
@glaweh @migueldiascosta `spack install berkeleygw~scalapack` results in an error, scalapack is needed for MPI:
```py
../Common/primme_interface.f90:3:4: error: #error ScaLAPACK is required for MPI builds.
```
We need to add this to make them to be selected and deselected together as a unit by the solver:
```py
+    # scalapack and mpi variants need each other, make the solver (de)select the other too:
     conflicts(
         "+scalapack", when="~mpi", msg="scalapack is a parallel library and needs MPI support"
     )
+    conflicts(
+        "~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw"
+    )


```

**Comment by bernhardkaindl** [comment]
I could not push (deny updating a hidden ref) to @glaweh's branch, possibly due not giving write permission when opening the PR. **Opened #34061 to review and merge the needed update to develop and the conflicts for the solver.**

**Comment by bernhardkaindl** [comment]
migueldiascosta was right, there is now another conflict with develop due to #33898 being merged.

I've pushed the rebase to the new post-python2 develop branch in #34061 (and alalazo requested a variant change)

**Comment by bernhardkaindl** [comment]
@migueldiascosta and @glaweh You may want to review #34061, after review from alalazo, the new updated title is:

**berkelygw: Use mpi variant to select parallel or serial support**

**Comment by alalazo** [comment]
Oh, I didn't realize #34061 was a re-pushed PR. Maybe @glaweh wants to bring @bernhardkaindl changes into this PR ?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks @glaweh @bernhardkaindl !

**Pull request merged**
