### PR TITLE
autotools: change user writable before copy config.*

### PR DESCRIPTION
**Pull request by tkameyama**
In #18347, we changed copy of config.guess and config.sub.
But when these files is not allow user write, the copy is failed.
This PR fix this by change user writable before copt the files.

### CODE REVIEW

**Comment by tkameyama** [comment]
ping @alalazo

**Comment by alalazo** [comment]
Can you give a use case for this that can be reproduced? Asking since I would lean on the side of not messing with file permissions if not absolutely necessary.

**Comment by tkameyama** [comment]
> 
> 
> Can you give a use case for this that can be reproduced? Asking since I would lean on the side of not messing with file permissions if not absolutely necessary.

For example, libxcomposite and amrvis.

**Comment by t-nojiri** [comment]
I have confirmed this phenomenon with the following OSS.
　  autogen, beforelight, amrvis, editres, ico, lbxproxy, libxcomposite, libxdamage, motif, proxymngr,
      rstart, viewres, xkbutils, xmessage, xorg-docs, xorg-sgml-doctools, xpr, xsm, xstdcmap, xwud,
      hdf-eos5, genfit
I hope for an early solution.

**Comment by tkameyama** [comment]
@alalazo  
> Can you give a use case for this that can be reproduced? Asking since I would lean on the side of not messing with file permissions if not absolutely necessary.

I change user writable only during copy, and restore original permissions when copy is done.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
