### PR TITLE
Switch http to https where latter exists

### PR DESCRIPTION
**Pull request by tldahlgren**
Scripts were used to extract, check for existence, and change the URLs from `http:` to `https:`.  This PR is the result.

Update: The second pass skipped homepage (only) changes to avoid duplication with recently merged PR(s). Note that the programmatic extraction and update processes did not distinguish between URLs in comments versus meaningful code.

### CODE REVIEW

**Comment by tgamblin** [comment]
@tldahlgren: this looks great. Have you looked at `spack url stats`, or is that what you are using for this? That should list all URLs.

One last question on this from me: did you verify the checksums for these new URLs? e.g. by trying to stage them?

**Comment by tldahlgren** [comment]
> @tldahlgren: this looks great. Have you looked at `spack url stats`, or is that what you are using for this? That should list all URLs.

I had already extracted the URLs before Adam reminded me about `spack url`.

> 
> One last question on this from me: did you verify the checksums for these new URLs? e.g. by trying to stage them?

Not yet.  My extract script grabbed *every* `http:`, including home pages and comments (so commented out entries).

I'll have to be more sophisticated the next pass. :grin:

**Comment by tldahlgren** [comment]
> > One last question on this from me: did you verify the checksums for these new URLs? e.g. by trying to stage them?

`spack stage` can be problematic when it results in `unsatisfiable version constraint` errors.

**Comment by tgamblin** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
> > > One last question on this from me: did you verify the checksums for these new URLs? e.g. by trying to stage them?
> 
> `spack stage` can be problematic when it results in `unsatisfiable version constraint` errors.

I ran  scripts to use `spack stage` when possible and `spack checksum` when not.  I also manually checked that the URLs for some that had other issues (e.g., concretization conflicts, read operation timeouts, no checksum on file, etc.) are valid (and have associated checksum/`sha256`) to see if I missed anything.

@tgamblin

**Review by alalazo — APPROVED** [review]
I agree with the spirit of the PR (but didn't check every single link!). For a follow up PR, should we have explicit checks in `spack audit` to ensure we don't use `http` if `https` is available?

**Comment by tldahlgren** [comment]
> I agree with the spirit of the PR (but didn't check every single link!). 

Thanks!

FWIW I used scripts using curl to confirm that all of the non-`format`d links returned `200` and adjusted a few `format`'d ones when I ran across them.

> For a follow up PR, should we have explicit checks in `spack audit` to ensure we don't use `http` if `https` is available?

IMO That's a great idea.

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
Before this PR:

```
(spackle):spack> spack url stats
==> URL stats for 5845 packages:
--------------------------------------------------------------
stat                    versions        %   resources        %
--------------------------------------------------------------
url                        17730    86.5%         792    87.9%
    schemes
        file                 102     0.5%          89     9.9%
                               1     0.0%           3     0.3%
        http                1995     9.7%          73     8.1%
        https              15548    75.9%         619    68.7%
        ftp                   84     0.4%           8     0.9%
```

After this PR:


```
(spackle):spack> spack url stats
==> URL stats for 5845 packages:
--------------------------------------------------------------
stat                    versions        %   resources        %
--------------------------------------------------------------
url                        17730    86.5%         792    87.9%
    schemes
                               1     0.0%           3     0.3%
        ftp                   84     0.4%           8     0.9%
        http                1175     5.7%          47     5.2%
        https              16368    79.9%         645    71.6%
        file                 102     0.5%          89     9.9%
    checksums
        sha256             17701    86.4%         789    87.6%
        md5                   22     0.1%           0     0.0%
        no checksum            7     0.0%           3     0.3%
```

getting closer 🎉

**Comment by tldahlgren** [comment]
> Before this PR:
> 
> ```
> (spackle):spack> spack url stats
> ==> URL stats for 5845 packages:
> --------------------------------------------------------------
> stat                    versions        %   resources        %
> --------------------------------------------------------------
> url                        17730    86.5%         792    87.9%
>     schemes
>         file                 102     0.5%          89     9.9%
>                                1     0.0%           3     0.3%
>         http                1995     9.7%          73     8.1%
>         https              15548    75.9%         619    68.7%
>         ftp                   84     0.4%           8     0.9%
> ```
> 
> After this PR:
> 
> ```
> (spackle):spack> spack url stats
> ==> URL stats for 5845 packages:
> --------------------------------------------------------------
> stat                    versions        %   resources        %
> --------------------------------------------------------------
> url                        17730    86.5%         792    87.9%
>     schemes
>                                1     0.0%           3     0.3%
>         ftp                   84     0.4%           8     0.9%
>         http                1175     5.7%          47     5.2%
>         https              16368    79.9%         645    71.6%
>         file                 102     0.5%          89     9.9%
>     checksums
>         sha256             17701    86.4%         789    87.6%
>         md5                   22     0.1%           0     0.0%
>         no checksum            7     0.0%           3     0.3%
> ```
> 
> getting closer 🎉

Yeah but not as much as I'd originally hoped.  I abandoned any updates related to following redirected URLs but I don't recall if that would have made much, if any, difference in the `http` -> `https` numbers.  

I also excluded the `homepage` URLs on my second pass since @vsoch had been working on them.

**Comment by vsoch** [comment]
yeah I think I finished those! These two:

 - https://github.com/spack/spack/pull/25653
 - https://github.com/spack/spack/pull/25670

**Comment by adamjstewart** [comment]
@tldahlgren this PR breaks bootstrapping of curl. Many packages like `zlib` have an explicit comment like:
```
# URL must remain http:// so Spack can bootstrap curl
```
yet the URL uses https instead of http now. Can you go through all packages that are dependencies of curl and revert this change?

**Comment by tgamblin** [comment]
@adamjstewart are you seeing this issue somewhere?  The issue is that there are systems we use where raw `http` is completely disallowed, so reverting this breaks everything there.

**Comment by adamjstewart** [comment]
Nope, but presumably this comment was added for a reason. There are systems where curl is installed without https certs where the only way to use Spack is to install curl with Spack, right?

**Comment by tgamblin** [comment]
Yes but we decided with this PR to go with the lesser of two evils. I’d propose either removing the comment or making an option to try http first for some (or all checksummed?) https urls.

**Pull request merged**
