### PR TITLE
cmd/load: only process run deps for load

### LINKED ISSUE #37704: Packages depending on ninja to build, cannot be loaded if ninja is uninstalled
### Steps to reproduce

```console
$ spack install glib
$ spack gc
# This will remove ninja
$ . share/spack/setup-env.sh
$ spack load glib                     
==> Error: spack requires 'ninja'. Make sure it is in your path.
```

### Error message

This seems to be due to ninja's `setup_dependent_package` requiring the ninja binary to be present.

```
==> [2023-05-16-15:38:22.149154] CommandNotFoundError: spack requires 'ninja'. Make sure it is in your path.
==> [2023-05-16-15:38:22.149178] Error: spack requires 'ninja'. Make sure it is in your path.
Traceback (most recent call last):
  File "$SPACK/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/cmd/load.py", line 114, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/user_environment.py", line 91, in environment_modifications_for_spec
    spack.build_environment.modifications_from_dependencies(
  File "$SPACK/lib/spack/spack/build_environment.py", line 999, in modifications_from_dependencies
    add_modifications_for_dep(dspec)
  File "$SPACK/lib/spack/spack/build_environment.py", line 976, in add_modifications_for_dep
    dpkg.setup_dependent_package(current_module, spec)
  File "$SPACK/var/spack/repos/builtin/packages/ninja/package.py", line 86, in setup_dependent_package
    determine_number_of_jobs(parallel=dspec.package.parallel),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/util/path.py", line 198, in path_filter_caller
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "$SPACK/lib/spack/spack/util/executable.py", line 307, in which_string
    raise CommandNotFoundError("spack requires '%s'. Make sure it is in your path." % args[0])
spack.util.executable.CommandNotFoundError: spack requires 'ninja'. Make sure it is in your path.
```

### Information on your system

* **Spack:** 0.20.0.dev0 (0d991de50af99c9938b3c376cea44cd4656f336e)
* **Python:** 3.11.3
* **Platform:** linux-fedora38-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by trws**
original patch thanks to @tgamblin
fixes #37704

### CODE REVIEW

**Comment by haampie** [comment]
See also https://github.com/spack/spack/pull/35737 (from February this year)

Or even https://github.com/spack/spack/pull/25732 from 2 years ago.

Do you wanna help push 35737 through? That gives you a single function

```
env = environment_modifications_for_specs(*specs)
```

to set up the run environment for one or more specs, correctly.

**Comment by trws** [comment]
Ok, that seems like a more complete solution to the issue @haampie.  What's the blocker?  I'd be happy to push that through, but hesitant to block this for it if it's going to take some finagling or require a break somewhere.  Either way I'll help out with #35737 since that seems like the right long-term solution.

**Comment by eugeneswalker** [comment]
This PR resolves https://github.com/spack/spack/issues/37704 for me. Thank you.

**Comment by trws** [comment]
This should have been resolved by #35737 just now, @eugeneswalker could you confirm? If so I'll close this.

**Comment by eugeneswalker** [comment]
> This should have been resolved by #35737 just now, @eugeneswalker could you confirm? If so I'll close this.

Yes, this is now resolved by PR #35737. Thanks!

**Pull request closed without merging**
