### PR TITLE
add pmix versions 4.2.7, 4.2.8, 4.2.9

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
Duplicates #44576   (sans `5.0.2`).

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the 3 new version sha256s.

**Comment by tldahlgren** [comment]
@shahzebsiddiqui Looks like there's a conflict that needs to be resolved.

**Review by rhc54 — COMMENTED** [review]
Do you want the 5.0.2 release as well?

https://github.com/openpmix/openpmix/releases/tag/v5.0.2

Also, didn't someone just do this a little while ago? I seem to recall approving a PR for this purpose, and they marked a number of versions as deprecated at the same time.

**Comment by tldahlgren** [comment]
> Do you want the 5.0.2 release as well?
> 
> https://github.com/openpmix/openpmix/releases/tag/v5.0.2
> 
> Also, didn't someone just do this a little while ago? I seem to recall approving a PR for this purpose, and they marked a number of versions as deprecated at the same time.

Great catch.  I hadn't seen that.

**Comment by tldahlgren** [comment]
Closing as duplicate (#44576 )

**Pull request closed without merging**
