### PR TITLE
amrex: new version 21.01

### PR DESCRIPTION
**Pull request by mic84**

### CODE REVIEW

**Comment by mic84** [comment]
@balay can you please check why the CI fails?

**Comment by balay** [comment]
@mic84 I don't really know how the CI works. I've attempted to restart - and it failed again.
```

Exception occurred:
  File "/home/runner/work/spack/spack/lib/spack/spack/repo.py", line 121, in __getattr__
    setattr(self, name, __import__(submodule))
ModuleNotFoundError: No module named 'spack.pkg.__sphinx_mock__'
The full traceback has been saved in /tmp/sphinx-err-3i0je506.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
Makefile:90: recipe for target 'html' failed
Error: Process completed with exit code 2.
```
Perhaps @adamjstewart has a better advice

**Review by tldahlgren — APPROVED** [review]
Confirmed release exists

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
CI was failing due to a change in the last Sphinx release, it should be working now.

**Comment by tldahlgren** [comment]
Yay!  It got past the style and docs failure it was previously hung on.

**Review by ax3l — APPROVED** [review]
:tada:

**Pull request merged**
