### PR TITLE
Add lmod files to MODULEPATH

### PR DESCRIPTION
**Pull request by adamjstewart**
Is there a reason we weren't already doing this...?

### CODE REVIEW

**Comment by tgamblin** [comment]
nope.

**Comment by alalazo** [comment]
Wait, this seems wrong: `tcl` and `lmod` are competitors. You'll have in MODULEPATH two modules for the same thing (but with a different layout). Besides that, you need to define a `core_compilers` section in `modules.yaml` for hierarchical module files to be written properly.

**Comment by tgamblin** [comment]
@alalazo: ack.  I should've put you as a reviewer.  So should we revert this for now and figure out a decent way to pick one?  Also, could we get better defaults out of the box for Lmod and make it the default?

**Comment by alalazo** [comment]
> So should we revert this for now and figure out a decent way to pick one?

:+1: for me

> Also, could we get better defaults out of the box for Lmod and make it the default?

I can take care of this. Do you want me to handle it in #3183 or in another PR? I think the only part that requires some logic is choosing a "core" compiler.

**Comment by tgamblin** [comment]
@alalazo I think doing it in #3183 would be good.

**Comment by adamjstewart** [comment]
Yeah no rush from me. I think Tcl is still a better default as it is compatible with both modules and Lmod. Probably don't need dotkit by default either. But we should probably add what's enabled to the MODULEPATH, not just some random choice. If I only have Lmod enabled, it doesn't work right now.

**Pull request merged**
