### PR TITLE
omega-h: add v9.34.13

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add new version: `omega-h@9.34.13`.

Hoping this new version will enable us to add `omega-h +cuda` to E4S CI:
* https://github.com/spack/spack/pull/32156

which is currently blocked because of:
* https://github.com/spack/spack/pull/32156#issuecomment-1223079213

@cwsmith @wspear

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Will defer merge to give @cwsmith a chance to comment.

**Review by cwsmith — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
> LGTM

Great!  Hopefully all the required checks pass.

**Pull request merged**
