### PR TITLE
Syscalc hash

### LINKED ISSUE #19321: Installation issue: syscalc fails with ChecksumError
### Steps to reproduce the issue

```console
$ spack install syscalc
```

yields

```
==> Installing syscalc
==> No binary for syscalc found: installing from source
==> Fetching http://madgraph.phys.ucl.ac.be/Downloads/SysCalc_V1.1.7.tar.gz
######################################################################## 100.0%
==> Error: ChecksumError: sha256 checksum failed for /tmp/root/spack-stage/spack-stage-syscalc-1.1.7-zlus4tseqby2qpwa2wnan23c5kvgwnif/SysCalc_V1.1.7.tar.gz
    Expected d33219a525a54733bdfd02d8314288bdecd977fb1e97ddeaf13bf470bbbdd386 but got 5b06f4955508f7c59660fa632ede9265d8f2ca7d9cd87f145a083da74e54602f

/spack/lib/spack/spack/package.py:1266, in do_fetch:
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
  >>   1266        if checksum and self.version in self.versions:
       1267            self.stage.check()
       1268
       1269        self.stage.cache_local()
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.15.4-1462-383b5b7
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake
```

### Additional information

It seems that that the file that is found at the location specified by the package:
https://github.com/spack/spack/blob/e4c1cb380beb088393e47ba9caa27a2e5953b4db/var/spack/repos/builtin/packages/syscalc/package.py#L13-L15

has changed, as directly downloading it and running
```
$ sha256sum SysCalc_V1.1.7.tar.gz 
5b06f4955508f7c59660fa632ede9265d8f2ca7d9cd87f145a083da74e54602f  SysCalc_V1.1.7.tar.gz
```

does not yield the expected checksum.

`spack maintainers syscalc` doesn't yield anything, so I am paging @iarspider here, which is the only one that turned up for syscalc using `git blame`.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by iarspider**
Closes #19321

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
Do we know why the hash changed?

**Comment by iarspider** [comment]
@alalazo no idea. I can try asking madgraph developers...

**Comment by alalazo** [comment]
> I can try asking madgraph developers...

Thanks, it would be good to confirm that they indeed changed the tarball.

**Comment by iarspider** [comment]
It's not the first time they do it. We (SPI) use our own mirror for all packages, and the tarball has a different hash there (both from the current one and the one that was there before).

**Comment by iarspider** [comment]
@alalazo you can follow the question yourself: https://answers.launchpad.net/mg5amcnlo/+question/693475

**Comment by iarspider** [comment]
The hash has changed again, btw...

**Review by adamjstewart — APPROVED** [review]
From https://answers.launchpad.net/mg5amcnlo/+question/693475 it sounds like we now have a stable checksum.

**Pull request merged**
