### PR TITLE
Revert "Add colon escape logic to config add"

### PR DESCRIPTION
**Pull request by haampie**
Reverts spack/spack#39279

### CODE REVIEW

**Comment by haampie** [comment]
Breaks CI

**Comment by scheibelp** [comment]
@haampie can you include details here, e.g. links to failing pipelines?

**Comment by johnwparent** [comment]
> @haampie can you include details here, e.g. links to failing pipelines?

Slack thread for context:
https://spackpm.slack.com/archives/C02N33GM28H/p1693837612996109

**Comment by scheibelp** [comment]
(EDIT: this is a different, spurious error message not related to the problem, see below for actual error)

@johnwparent I think https://gitlab.spack.io/spack/spack/-/jobs/8102725 might be a good example of where this fails (part of https://github.com/spack/spack/pull/39822)

I'm not sure if that will last (and the slack link will definitely disappear) so I'll copy the stack trace here:

```
Traceback (most recent call last):
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/cmd/ci.py", line 767, in ci
    return args.func(args)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/cmd/ci.py", line [220](https://gitlab.spack.io/spack/spack/-/jobs/8102725#L220), in ci_generate
    remote_mirror_override=buildcache_destination,
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/ci.py", line 707, in generate_gitlab_ci_yaml
    env.concretize()
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/environment/environment.py", line 1336, in concretize
    return self._concretize_separately(tests=tests)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/environment/environment.py", line 1493, in _concretize_separately
    _ = spack.repo.PATH.provider_index
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/llnl/util/lang.py", line 825, in __getattr__
    return getattr(self.instance, name)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/repo.py", line 763, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 233, in merge
    other = other.copy()  # defensive copy.
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in copy
    clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 122, in _transform
    return _transform(self.providers, transform_fun, out_mapping_type)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 324, in _transform
    for name, mappings in providers.items()
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 324, in <genexpr>
    for name, mappings in providers.items()
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 323, in <listcomp>
    (name, out_mapping_type([transform_fun(vpkg, pset) for vpkg, pset in mapiter(mappings)]))
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in <lambda>
    clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in <genexpr>
    clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/spec.py", line 4085, in copy
    clone._dup(self, deps=deps, **kwargs)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/spec.py", line 3992, in _dup
    self.variants = other.variants.copy()
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 639, in copy
    clone[name] = variant.copy()
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 334, in copy
    return type(self)(self.name, self._original_value, self.propagate)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line [254](https://gitlab.spack.io/spack/spack/-/jobs/8102725#L254), in __init__
    self.value = value
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 291, in value
    self._value_setter(value)
  File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 312, in _value_setter
    self._value = tuple(sorted(set(value)))
TypeError: unhashable type: 'list'
```

**Comment by scheibelp** [comment]
Apparently there is also https://gitlab.spack.io/spack/spack/-/jobs/8102444:

```
spack config add "config:install_tree:projections:${SPACK_JOB_SPEC_PKG_NAME}:'morepadding/{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'"
...
==> Error: <unknown file>: {'projections': 'morepadding/{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'} is not valid under any of the given schemas
```

**Comment by johnwparent** [comment]
> @johnwparent I think https://gitlab.spack.io/spack/spack/-/jobs/8102725 might be a good example of where this fails (part of #39822)
> 
> I'm not sure if that will last (and the slack link will definitely disappear) so I'll copy the stack trace here:
> 
> ```
> Traceback (most recent call last):
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/bin/spack", line 52, in <module>
>     sys.exit(main())
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack_installable/main.py", line 37, in main
>     sys.exit(spack.main.main(argv))
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 1023, in main
>     return _main(argv)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 978, in _main
>     return finish_parse_and_run(parser, cmd_name, env_format_error)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
>     return _invoke_command(command, parser, args, unknown)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/main.py", line 647, in _invoke_command
>     return_val = command(parser, args)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/cmd/ci.py", line 767, in ci
>     return args.func(args)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/cmd/ci.py", line [220](https://gitlab.spack.io/spack/spack/-/jobs/8102725#L220), in ci_generate
>     remote_mirror_override=buildcache_destination,
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/ci.py", line 707, in generate_gitlab_ci_yaml
>     env.concretize()
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/environment/environment.py", line 1336, in concretize
>     return self._concretize_separately(tests=tests)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/environment/environment.py", line 1493, in _concretize_separately
>     _ = spack.repo.PATH.provider_index
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/llnl/util/lang.py", line 825, in __getattr__
>     return getattr(self.instance, name)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/repo.py", line 763, in provider_index
>     self._provider_index.merge(repo.provider_index)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 233, in merge
>     other = other.copy()  # defensive copy.
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in copy
>     clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 122, in _transform
>     return _transform(self.providers, transform_fun, out_mapping_type)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 324, in _transform
>     for name, mappings in providers.items()
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 324, in <genexpr>
>     for name, mappings in providers.items()
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 323, in <listcomp>
>     (name, out_mapping_type([transform_fun(vpkg, pset) for vpkg, pset in mapiter(mappings)]))
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in <lambda>
>     clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/provider_index.py", line 272, in <genexpr>
>     clone.providers = self._transform(lambda vpkg, pset: (vpkg, set((p.copy() for p in pset))))
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/spec.py", line 4085, in copy
>     clone._dup(self, deps=deps, **kwargs)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/spec.py", line 3992, in _dup
>     self.variants = other.variants.copy()
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 639, in copy
>     clone[name] = variant.copy()
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 334, in copy
>     return type(self)(self.name, self._original_value, self.propagate)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line [254](https://gitlab.spack.io/spack/spack/-/jobs/8102725#L254), in __init__
>     self.value = value
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 291, in value
>     self._value_setter(value)
>   File "/home/gitlab-runner-4/builds/CZHkQ52f/0/spack/spack/lib/spack/spack/variant.py", line 312, in _value_setter
>     self._value = tuple(sorted(set(value)))
> TypeError: unhashable type: 'list'
> ```

I don't see any of the methods we changed anywhere in this stack trace. A grep for `process_config_path` and `add` returns nothing.

**Comment by haampie** [comment]
@scheibelp the first thing you've posted is unrelated to the pr, it's a spurious error for a while now.

**Comment by johnwparent** [comment]
@scheibelp @haampie https://github.com/spack/spack/pull/39831 is a remake of https://github.com/spack/spack/pull/39279 with this bug patched. I've added you both as reviewers.

**Pull request merged**
