### PR TITLE
texinfo: add v7.0.3

### PR DESCRIPTION
**Pull request by alecbcs**
Add texinfo v7.0.3. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.  `spack spec` succeeds.

**Comment by tldahlgren** [comment]
Something strange appears to be going on with CI.

**Comment by tldahlgren** [comment]
Haven't investigated but this is causing problems with its dependents on several stacks (e.g., `binutils`, `gcc`).

```
$ spack dependents texinfo
amdfftw    cln           gengetopt     mpfi                r
aocc       e2fsprogs     groff         mpfr                riscv-gnu-toolchain
bc         emacs         iegenlib      nco                 rocm-device-libs
binutils   fujitsu-fftw  libconfig     octave              rocm-gdb
bpp-suite  gcc           libtool       pinfo               sherpa
cgdb       gdb           libunistring  process-in-process  source-highlight
```

**Comment by alecbcs** [comment]
I'm seeing those jobs fail with an invalid argument error which seems to be breaking a ton of jobs in CI right now. My guess would be that this is related to the CI craziness going on right now. Probably best to wait until we hear back from the kitware folks and then try again. If those packages continue to fail I'll check out what might be going on.

**Pull request merged**
