### PR TITLE
Update 2.33 hash, add syscall variant

### PR DESCRIPTION
**Pull request by wspear**

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Review by sameershende — APPROVED** [review]
New features for tracking syscalls (similar to strace) using tau_exec -syscall ./a.out. Approved.

**Comment by eugeneswalker** [comment]
`tau +mpi +python +syscalls` build is failing on POWER - maybe we disable syscall in power pipelines for now?
* [ tau@2.33 /x34dage %gcc@9.4.0 arch=linux-ubuntu20.04-ppc64le E4S Power ](https://gitlab.spack.io/spack/spack/-/jobs/8959261)
```
...
  >> 1508    scalls_ppc.c:442:14: error: '__NR_close_range' undeclared (first u
             se in this function)
     1509      442 |     __scalls[__NR_close_range] = "close_range";
     1510          |              ^~~~~~~~~~~~~~~~
     1511    scalls_ppc.c:442:14: note: each undeclared identifier is reported 
             only once for each function it appears in
  >> 1512    scalls_ppc.c:443:14: error: '__NR_openat2' undeclared (first use i
             n this function)
     1513      443 |     __scalls[__NR_openat2] = "openat2";
     1514          |              ^~~~~~~~~~~~
  >> 1515    scalls_ppc.c:444:14: error: '__NR_faccessat2' undeclared (first us
             e in this function); did you mean 'SYS_faccessat'?
     1516      444 |     __scalls[__NR_faccessat2] = "faccessat2";
     1517          |              ^~~~~~~~~~~~~~~
     1518          |              SYS_faccessat
  >> 1519    make[1]: *** [Makefile:18: scalls.o] Error 1
```

**Review by eugeneswalker — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
`amdblis` and `hdf5-vol-async` builds are failing in CI pipelines here, and it is unrelated to the content of this PR.  Not sure what is going on with this. 
* [ amdblis@4.1 /q36pvev %gcc@11.4.0 arch=linux-ubuntu20.04-neoverse_v1 E4S ARM Neoverse V1](https://gitlab.spack.io/spack/spack/-/jobs/8967174)
* [ amdblis@4.1 /fbrfxiu %gcc@9.4.0 arch=linux-ubuntu20.04-ppc64le E4S Power ](https://gitlab.spack.io/spack/spack/-/jobs/8967178)
* [ hdf5-vol-async@1.7 /a73ssvc %gcc@11.4.0 arch=linux-ubuntu20.04-neoverse_v1 E4S ARM Neoverse V1 ](https://gitlab.spack.io/spack/spack/-/jobs/8967175)

**Comment by eugeneswalker** [comment]
Closing in favor of https://github.com/spack/spack/pull/40851 due to CI failures unrelated to this PR.

**Comment by alalazo** [comment]
@sameershende Would it be possible to release a patch version next time?

**Pull request closed without merging**
