### PR TITLE
gromacs: add 2022.3

### PR DESCRIPTION
**Pull request by zzzoom**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Will defer merge decision to give @junghans and or @marvinbernhardt a chance to comment.

**Review by marvinbernhardt — APPROVED** [review]
confirmed sha256

**Comment by junghans** [comment]
@tldahlgren what are we waiting for here?

**Comment by tldahlgren** [comment]
> @tldahlgren what are we waiting for here?

I was waiting on a maintainer to respond.  Some package maintainers complain if a package is merged without their input so we have an informal policy of giving maintainers about a week to approve or suggest changes.

Since you enabled auto-merge, this PR will be merged when all required checks to pass.

**Pull request merged**
