### PR TITLE
py-matplotlib: add v3.7.1

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/matplotlib/matplotlib/releases/tag/v3.7.1

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
