### PR TITLE
added dyninst 11.0.0

### PR DESCRIPTION
**Pull request by lee218llnl**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed tag is available.

**Comment by hainest** [comment]
@lee218llnl @tldahlgren This should not have been merged. Dyninst 11.0 comes with additional dependencies that are not reflected by this PR.

**Comment by lee218llnl** [comment]
> @lee218llnl @tldahlgren This should not have been merged. Dyninst 11.0 comes with additional dependencies that are not reflected by this PR.

Can you please elaborate on what dependencies are required or perhaps submit another issue and/or a PR?

**Comment by hainest** [comment]
@lee218llnl There were two items added for 11.0: Boost >= 1.67, gcc >= 6. I'm testing a PR for these now. I'll ping you when I push it.

**Comment by tldahlgren** [comment]
> @lee218llnl @tldahlgren This should not have been merged. Dyninst 11.0 comes with additional dependencies that are not reflected by this PR.

Thanks for the information *and* the follow-on PR.

**Pull request merged**
