### PR TITLE
Bump py-boto3 and its dependencies

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot commands

**Comment by alalazo** [comment]
Just checking if fixing style issues automatically has been deployed...

**Comment by adamjstewart** [comment]
This would be easier to review if you split each package into a separate PR

**Comment by haampie** [comment]
Closing in favor of

https://github.com/spack/spack/pull/25211
https://github.com/spack/spack/pull/25210
https://github.com/spack/spack/pull/25209
https://github.com/spack/spack/pull/25208
https://github.com/spack/spack/pull/25207

**Pull request closed without merging**
