### PR TITLE
Use boost system layout by default

### PR DESCRIPTION
**Pull request by scheibelp**
This includes:

* use system layout by default
* prevent building multi- and single-threaded libs when using system layout
* build multi-threaded libs by default
* add in symlinks which emulate tagged layout when multithreaded libs are built with system layout (for packages like valgrind which expect the -mt suffix)

This addresses #710 (reasoning here also suggests that multi-threaded libs will nearly always be suitable as a drop-in replacement for single-threaded libs) and #1820.

### CODE REVIEW

**Comment by davydden** [comment]
does boost `1.62.0` build for you or is it for `1.61.0`?

**Comment by adamjstewart** [comment]
While, you're at it, can you change the Cantera package so that it uses the new library names? I added [a hack](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/cantera/package.py#L100) to get it to find the boost libraries, and if it isn't needed anymore then I don't want to use it.

**Comment by scheibelp** [comment]
> does boost 1.62.0 build for you or is it for 1.61.0?

I have the same issue described in #1903 now that you mention it. Let me see if I can fix that up here.

**Comment by tgamblin** [comment]
@scheibelp: can valgrind and other packages be easily modified to emulate the `-mt` layout?  It would be nice to just not rely on it.

**Comment by scheibelp** [comment]
> can valgrind and other packages be easily modified to use the system layout and NOT the -mt layout?

I don't think this can be done for valgrind without patching its configure script.

Also: latest commit appears to get boost 1.62 building. Honestly I'm not sure why it fails without. The issue appeared to be related to iostreams library with bzip support (building without iostreams succeeds), but documentation for 1.62 zlib/bzip2 does not change and the release notes don't mention any issues. Not much changed in the build system between 1.61 and 1.62 - if I do a build for 1.62 and replace the 1.62 build system with the 1.61 build system it fails in the same way.

**Comment by scheibelp** [comment]
Also regarding not using -mt libs: is there a reason to avoid this? I've seen a few error messages around where some packages (not necessarily maintained by Spack) depend on the -mt suffix.

**Comment by tgamblin** [comment]
@adamjstewart: any objections to leaving `-mt` symlinks?

**Comment by adamjstewart** [comment]
No objections. Can you fix Cantera though? Might as well point to the default library names if they exist now.

**Pull request merged**
