### PR TITLE
Updated merlin requirements.

### PR DESCRIPTION
**Pull request by bvanessen**
Added new versions to ensure that dependent packages built.

### CODE REVIEW

**Comment by bvanessen** [comment]
@koning Here are the updates that I had to do to get spack to build merlin.

**Comment by koning** [comment]
Thanks Brian, I also have a set edits that I will add to my spack repo and let you know when they are ready.

**Comment by koning** [comment]
A number of dependent python packages updated recently so we are testing for compatibility.

**Comment by koning** [comment]
Here is a link to the new merlin version https://github.com/koning/spack/tree/merlin_update

I'm waiting to find out if there will be a merlin1.7.5 update using celery 5.0.0.

**Comment by bvanessen** [comment]
@koning Are you going to push changes to this PR or do something else to update merlin and its dependencies.

**Comment by koning** [comment]
In the past they have asked to separate the PR into individual package PRs. Have they allowed multiple package updates in your PRs?

**Comment by bvanessen** [comment]
Yes they have in the past.  Are you pushing these as separate PRs?

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by koning** [comment]
Yes, I'll separate them and push the PRs.

**Comment by bvanessen** [comment]
Okay great.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by koning** [comment]
PRs are up.

**Comment by adamjstewart** [comment]
Is this PR still needed? Most of these changes have been split into separate PRs.

**Comment by koning** [comment]
I believe the change Brian made for an external python in  lib/spack/spack/build_systems/python.py is still needed from this PR. The others are in separate PRs.

**Comment by bvanessen** [comment]
@adamjstewart I will check that everything needed is covered in a separate PR.  I believe that the update to spack itself was covered in another PR as well.

**Pull request closed without merging**
