### PR TITLE
Hide package repository count when redirecting stdout

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
This fixes the extra `==>` item when completing `spack repo`.
```bash
$ spack repo rm <press tab>
==>      builtin
```

### CODE REVIEW

**Comment by haampie** [comment]
nice. i've also seen some odd tab completion erroring with `spack unit-test <tab>`, is that similar?

**Review by haampie — DISMISSED** [review]

**Comment by KiruyaMomochi** [comment]
> nice. i've also seen some odd tab completion erroring with `spack unit-test <tab>`, is that similar?

That's another problem. We need to change `spack test -l` to `spack unit-test -l` in `spack-completion.in`:
https://github.com/spack/spack/blob/93377942d17d356aaae793c5d665a3e48ab7649e/share/spack/bash/spack-completion.in#L211-L217

Should I commit to this PR or open another one?

**Comment by haampie** [comment]
Good catch! A separate pr would be fine, thanks for digging into this.

The current PR seems to have the same test failure as https://github.com/spack/spack/commit/a39a6c4ea7863031d1c89fea05b3b3be76e25f2f on develop, so let me try to make a fix for that and then we can re-run CI here.

**Comment by haampie** [comment]
closing/opening to see if the test failure goes away.

**Comment by haampie** [comment]
The fix is in #29419. So that should get in first...

**Comment by haampie** [comment]
CI really does not like this PR :(. now the docs fail.

**Review by haampie — APPROVED** [review]

**Pull request merged**
