### PR TITLE
git: new versions and deprecations

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by haampie** [comment]
@jennfshr somehow your message doesn't appear in the PR, but the rational is:

https://lore.kernel.org/git/xmqq4jw1uku5.fsf@gitster.g/T/#u

All non-deprecated versions have security backports.

**Review by tldahlgren — APPROVED** [review]
Confirmed the 12 new version's sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to @jennfshr

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@jennfshr Giving this PR a fast track since it was just adding versions with vulnerability fixes

**Comment by jennfshr** [comment]
Thanks @alalazo sorry for my delay!

**Comment by alalazo** [comment]
No worries!

**Pull request merged**
