### PR TITLE
py-plotnine: add v0.10.1

### PR DESCRIPTION
**Pull request by qwertos**
Depends on: #36500 #36499

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Need to add new py-mizani version

**Comment by adamjstewart** [comment]
Ah, I see you did that in a different PR. For the record, it's fine to submit a single PR for multiple packages if one package requires the changes in another package.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
