### PR TITLE
py-tensorflow-probability: Re-activate +py-jax variant for @0.20:, Add 0.23.0

### PR DESCRIPTION
**Pull request by jonas-eschle**
Adding 0.23 of TFP, [release notes are here (technically)](https://github.com/tensorflow/probability/releases/tag/v0.23.0)

Unfortunately, 0.24 is trickier: TF is there, but this [requires a new package](https://github.com/tensorflow/probability/releases/tag/v0.24.0), `tf-keras`, for backwards compatibility, with building etc that I am not familiar with

### CODE REVIEW

**Comment by jonas-eschle** [comment]
@aweits this is ready from my side

**Review by bernhardkaindl — APPROVED** [review]
@aweits: This looks ready to be merged in the next days, any comment?

Built it successfully on x86_64-linux-gnu.

According to @jonas-eschle, work on #43200 is waiting until this is merged:
https://github.com/spack/spack/pull/43200#issuecomment-2004538454

@jonas-eschle Feel free to ping me (and/or others in case I forget), because by Saturday, @aweits would have had 5 days to review it. After they have passed, this is free to merge.

**Review by bernhardkaindl — APPROVED** [review]
@jonas-eschle PS:
> tf-keras does not (yet) exist on Spack, i.e. the TF extra won't work, see below
> TODO(0.24): requires tf-keras on Spack
> depends_on("py-tf-keras", when="@0.24:", type=("build", "run"))
> depends_on("py-tensorflow@2.16", when="@0.24", type=("build", "run"))

Do you refer to https://github.com/keras-team/keras?

It may be added as `py-teras` soon:

I guess `py-tf-keras` may be a different package?

#43283 was opened 2 days ago to update `py-teras` to 3.1.1.

**Comment by jonas-eschle** [comment]
Thanks for the review!

> I guess `py-tf-keras` may be a different package?

Yes, AFAIU [from the release notes](https://github.com/tensorflow/probability/releases/tag/v0.24.0), keras upgraded to version 3, as TFP does not yet support that, they made a [Keras2 package, called tf-keras](https://github.com/tensorflow/probability/releases/tag/v0.24.0).

**Review by bernhardkaindl — APPROVED** [review]
Reviewed again, updated PR title for the squashed commit for merge.

**Pull request merged**
