### PR TITLE
xcfun: Add @2.1.1

### PR DESCRIPTION
**Pull request by prckent**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Will defer merge decision until tests pass and at least one maintainer has a chance to comment.

**Comment by prckent** [comment]
Please can you retrigger the tests? The unit test failure looks like an infrastructure problem to me.

**Review by robertodr — APPROVED** [review]

**Comment by tldahlgren** [comment]
Updated the branch through GitHub to force re-running unit tests.

**Comment by bast** [comment]
Thank you!

**Pull request merged**
