### PR TITLE
e4s: add axom +cuda

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `axom +cuda` to E4S stack

@wspear @white238

### CODE REVIEW

**Review by white238 — DISMISSED** [review]
Thanks!

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by tldahlgren — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
From the failed `axom@0.6.1 +cuda` build:
* [(specs) axom/wxk2iz7 0.6.1 gcc@11.2.0 linux-ubuntu22.04-x86_64 New PR testing workflow](https://gitlab.spack.io/spack/spack/-/jobs/3041261)
```
...
  >> 820    /tmp/tmpxft_00002275_00000000-6_StringUtilities.cudafe1.stub.c:14: 
            undefined reference to `__cudaRegisterLinkedBinary_e2f2e14a_19_Stri
            ngUtilities_cpp_6cf878fc'
     821    /usr/bin/ld: ../../../core/CMakeFiles/core.dir/utilities/System.cpp
            .o: in function `__sti____cudaRegisterAll()':
  >> 822    /tmp/tmpxft_00002273_00000000-6_System.cudafe1.stub.c:14: undefined
             reference to `__cudaRegisterLinkedBinary_c02a4a6a_10_System_cpp_0e
            b8e2f3'
     823    /usr/bin/ld: ../../../core/CMakeFiles/core.dir/utilities/Utilities.
            cpp.o: in function `__sti____cudaRegisterAll()':
...
```

Looks like this issue is not resolved:
*  https://github.com/spack/spack/issues/29520

**Comment by eugeneswalker** [comment]
Just re-based on develop to see if new version `axom@0.7.0` is OK with `+cuda`

**Pull request closed without merging**
