### PR TITLE
espressopp -> py-espressopp

### PR DESCRIPTION
**Pull request by junghans**
espressopp is a python module.

### CODE REVIEW

**Comment by tgamblin** [comment]
Is it just python or do people typically run it NOT as a python module? Not all python modules have to start with `py-` -- we've been reserving that for the pure python ones or the ones that are always used as Python modules.  Not things that happen to have bindings.

**Comment by junghans** [comment]
Yes, it can only be used as a python module!

**Comment by junghans** [comment]
I actually installs everything python's site_package.

**Comment by junghans** [comment]
@scheibelp

**Comment by tgamblin** [comment]
just waiting for travis.

**Pull request merged**
