### PR TITLE
Update py-werkzeug version dependency for py-graphene-tornado@2.6.1

### PR DESCRIPTION
**Pull request by climbfuji**
I was looking into the dependencies for `py-graphene-tornado` because I simply couldn't get something that dependent on `py-graphene-tornado` (currently only version 2.6.1 coded up) to build with Python newer than 3.9.

The py-werkzeug dependency in the package had `0.12.2` as version, but according to https://github.com/graphql-python/graphene-tornado/blob/v2.6.1/requirements.txt it should be `0.15.3`. I made this change and was able to build the dependent package I was after (`py-cylc-uiserver`) fine.

I was able to launch the `jupyter-cylc` dashboard fine with the so-built packages. I didn't test the cylc flow server itself, but given that the `py-cylc-flow` package is already happy with newer Python versions (it doesn't use `py-werkzeug`), I guess it's ok?

### CODE REVIEW

**Review by manuelakuhn — COMMENTED** [review]
The `py-werkzeug@0.12.2` dependency came from the [`py-setup.py#L56`](https://github.com/graphql-python/graphene-tornado/blob/v2.6.1/setup.py#L56).
It seems that the `requirements.txt` and `setup.py` diverge here. Usually we take the specification in `setup.py`/`pyproject.toml` because that are the ones pip would use as well.
I just verified that I get errors when installed with pip because py-werkzeug is too old, so the recipe there seems wrong. 
I also verified that the example in the [getting started](https://github.com/graphql-python/graphene-tornado/tree/v2.6.1#getting-started) works fine with the change in this PR.

It would be great if you could add a comment that this dependency version is coming from `requirements.txt` so that we know for the future.

**Comment by LydDeb** [comment]
I made a new installation of py-cylc-uiserver with this version of werkzeug, and a python 3.11. I confirm that the `cylc gui` command opens the cylc board in my browser.

**Comment by climbfuji** [comment]
Thank you both for checking @LydDeb and @manuelakuhn. I'll add a note as requested.

**Comment by climbfuji** [comment]
> Thank you both for checking @LydDeb and @manuelakuhn. I'll add a note as requested.

Done in https://github.com/spack/spack/pull/41426/commits/3d68c03c26a43368e3fe77bcad1552cc49ec863f

**Review by manuelakuhn — APPROVED** [review]
Thanks.

**Review by LydDeb — APPROVED** [review]

**Pull request merged**
