### PR TITLE
Ci backwards compat

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Add a shim into the CI module to translate the deprecated CI format to the new layout.

Also fixed a copy-paste issue in the CI docs.

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
@becker33 Is this something that can be "easily" moved to an update script as well.

The only thing I can really see to do is to run the translation, clear the `gitlab-ci` section, and then update the `ci` section in the config scope. But since I can't import `spack.config` at the top level in a schema I am not sure how to do that exactly.

One idea was to `import spack.config` inside of the `update` API and hope that doesn't break, but I am not sure how stable that is.

**Comment by alalazo** [comment]
@kwryankrattiger Can you open a brief issue with an explanation + reproducer of the problem (i.e. #34272 was a breaking change, configuration X fails with this error, etc.) and add a test in this PR that references that issue with:
```python
@pytest.mark.regression(XXXXX)
```
? I find that this makes it easier, when a refactor occurs in the future, to understand the context of changes we made to the code.

**Comment by kwryankrattiger** [comment]
@alalazo I added two unit tests, but it seems there is a bug in the `config update ci` where it doesn't work inside of an environment. I tried this outside of the pytest stack and got the error...

```console
$ ls var/spack/environments/test/spack.yaml -l    
-rw-rw-rw- 1 ryan.krattiger domain^users 445 Mar 24 09:49 var/spack/environments/test/spack.yaml
$ spack config update ci                   
==> Error: Detected permission issues with the following scopes:

        [scope=env:test, cfg=~/spack/var/spack/environments/test/spack.yaml]

Either ensure that you have sufficient permissions to modify these files or do not include these scopes in the update.
```

I don't know if there is an open issue for this, the GitHub search is really bad at fuzzy matching. Not sure if this is just a user error or what, but it basically makes the `spack config update ci` useless since the old `gitlab-ci` section could *only* exist in an environment.

It is also not possible to update the `ci` configs using `spack -C ./testing/ config update ci` with a `spack.yaml`, the `ci` config needs to be moved to a `ci.yaml` just to be detected. Then, in the case of a custom config scope, it aborts with this error...

```console
==> Error: Cannot write to immutable scope <ImmutableConfigScope: cmd_scope_0: test-env>
```

If you or @becker33 have ideas on how to make this work that would be great, but I think it was a "nice-to-have" feature for CI anyway so NBD.

**Comment by haampie** [comment]
Yeah, I think updating config in environments is somewhat broken, as it hits a code path that expects a config dir, not an environment file.

I think you're supposed to use `spack env update <name/path>`

**Comment by kwryankrattiger** [comment]
> I think you're supposed to use spack env update <name/path>

That command's documentation does not imply that at all...But good to know, I thought it was something to reactivate/refresh an environment to make it look like it needed to re-concretize.

**Comment by kwryankrattiger** [comment]
Tested the `spack env update` and it does not detect the `ci` section in the environment nor update it...so I guess that is also broken. So to get that to work I also need to add the update to the `schema/env.py`...ugh

**Comment by kwryankrattiger** [comment]
@scottwittenburg and @becker33 Could you please review this, I think it is officially ready to go.

**Comment by haampie** [comment]
See #36542 which makes spack config update work for environments

**Comment by scottwittenburg** [comment]
@kwryankrattiger I noticed in the deprecated stack that the CDash buildgroup cannot be created due to a 404 bad request.  To be fully backwards compatible, does this PR need to handle getting CDash info from the `spack.yaml` file instead of the config, like it did before boilerplate?  Or am I missing something?

**Comment by kwryankrattiger** [comment]
It should be getting the cdash config from the `spack.yaml`..not sure why it is having trouble uploading. New cdash group needed to be registered in the cdash.spack.io? @zackgalbreath

**Review by scottwittenburg — APPROVED** [review]
@kwryankrattiger Thanks for adding the tiny new deprecated stack so we can make sure this continues working until it can be removed.  I think it's ok to look into the CDash build group issue in a subsequent PR.

**Pull request merged**
