### PR TITLE
Features/rename nobuild

### PR DESCRIPTION
**Pull request by mplegendre**
By popular request, rename nobuild to buildable

### CODE REVIEW

**Comment by tgamblin** [comment]
Any reason why not just 'build'?

**Comment by mplegendre** [comment]
'build' is a fairly generic word that could be a verb or noun--it has lots 
of possible meanings.

'buildable' is an adjective and more better describes that we're talking 
about whether a package can be built.

-Matt

**Comment by tgamblin** [comment]
Fair enough.  Looks like it's conflicted though

**Comment by mplegendre** [comment]
Conflicts resolved.

**Comment by tgamblin** [comment]
Squashed and merged.

**Pull request closed without merging**
