### PR TITLE
gromacs: prevent version conflict after enabling plumed

### PR DESCRIPTION
**Pull request by w8jcik**
Consider following example

```bash
spack install gromacs@2021.7+plumed ^plumed@2.9.0
```

Without the change concretization fails, because GROMACS 2021 needs Plumed `2.7.1:2.7.2`, but GROMACS 2021.7 needs `2.8.2:2.9.0` which is mutually exclusive.

Defined in following dictionary

```
plumed_patches = {
  ...
  "2021.7": "2.8.2:2.9.0",
  ...
  "2021": "2.7.1:2.7.2",
  ...
}
```

The bug probably appeared after the change in handling of versions by Spack.  
In current version of Spack `2021.7` is `2021`. Some time ago they were two different versions.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Well spotted!

I haven't got the chance to see Spack exact versions (`@=`) at play yet. However my impression is that, as a result of using exact versions generically in line 262, there are a lot of required version specifications in the `plumed_patches` dictionary, see line 228 onwards. 

For instance, for 2023 versions, with exact versions only `2023` gets its Plumed version explicit,  all of `2023.x` don't.

Suggestion: why not reverting line 263, and instead editing line 236?
```
"2021": "2.7.1:2.7.2",   ->    "=2021": "2.7.1:2.7.2",
```
In addition, missing `2021.x` versions should be explicitly specified in `plumed_patches`, 2021.1, 2021.2, 2021.3 I think. Well, version ranges for Gromacs can be used for conciseness, when the version matrix allows.

By editing the 2021 specifically in `plumed_patches` rather than in the templated `depends_on` statement futher down, it is possible to keep the syntax more concise and at the same time flexible, i.e. adapt it version by version.

In alternative, you can keep the general change in line 262, but then every single supported version of Gromacs needs its own line in the `plumed_patches` dictionary.

What do you think?

**Comment by w8jcik** [comment]
You are right, it is better to move `=` to keys of dictionary.
I was avoiding duplication out of habit, but it is more flexible to not split version specification.

> I haven't got the chance to see Spack exact versions (@=) at play yet.

For example GROMACS 2023 is a valid version, released just before 2023.1.  
But for Spack `@2023` means `2023 <= version < 2024`.  
Typing `spack install gromacs@2023` installs the latest 2023 (2023.4).  
In case you really need 2023, you can use `@=2023`.

It is described here https://github.com/spack/spack/releases/tag/v0.20.0

> with exact versions only 2023 gets its Plumed version explicit, all of 2023.x don't

Correct me if I am wrong, but I think Plumed needs specific versions, otherwise it refuses to install, so 2.9.0 refuses to install with 2023.1, 2023.2, ... . Only =2023 works.

What we could do is to add conflict lines. We could say that all other versions of GROMACS are in conflict with Plumed. The issue is that after adding conflicts, unlisted versions of Plumed (2.10b, future version, or a git branch) would no longer install. This is probably why conflicts are missing.

> In addition, missing 2021.x versions should be explicitly specified in plumed_patches, 2021.1, 2021.2, 2021.3 I think.

Is there some compatibility matrix that I am not aware of? I was looking into files in plumed repository to create this dictionary and I believe that all supported versions are listed.

Plumed 2.7.2 -> 2.7.3 jumps from GROMACS 2021 to 2021.4, so `2021.1:2021.3` seems unsupported.

**Comment by w8jcik** [comment]
Are there any more issues with this change or can we merge it?

**Comment by marcodelapierre** [comment]
Hi Maciej, apologies for the wait.

> Correct me if I am wrong, but I think Plumed needs specific versions, otherwise it refuses to install, so 2.9.0 refuses to install with 2023.1, 2023.2, ... 

Yes, you are right, thank you for pointing out, my original argument was partially flawed.

> It is described here https://github.com/spack/spack/releases/tag/v0.20.0

Thank you for highlighting this. By reading again, I noticed the PR details are quite useful, as they provide examples of how the behaviour has changed (https://github.com/spack/spack/pull/36273).

My last suggestion is one to try and keep the code clean and flexible at the same time: because Gromacs versions are either `YYYY` or `YYYY.x`, you actually need the new syntax `@=` only in the first case (the one that now implies a range). Because there is no bugfix release `YYYY.x.z`, the second case never represents a range.  
So, in practice, it looks to me like the only required changes are:
```
"=2023": "2.9.0",
..
"=2021": "2.7.1:2.7.2",
```
Then, just before the beginning of definition of the `plumed_patches` list, you can add a comment to refer to this change in Spack syntax, to provide context:
```
# Above dependencies can be verified, and new versions added, by going to
# https://github.com/plumed/plumed2/tree/v2.9.0/patches
# and switching tags.

# Versions without minor release number, such as `2023` and `2021,
# require exact specifcation using `@=`, starting from Spack v0.20.0, see
# https://github.com/spack/spack/releases/tag/v0.20.0
plumed_patches = {
```

What do you think?

I will seek to approve after this.

**Comment by marcodelapierre** [comment]
Hi @w8jcik when you get the chance, please have a look at my comment above.

**Comment by w8jcik** [comment]
@marcodelapierre I have changed it according to you suggestions.

**Review by marcodelapierre — APPROVED** [review]
Thank you Maciej, good to go for me!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
