### PR TITLE
gcc: generate spec file and fix external libc default paths after install from cache

### PR DESCRIPTION
**Pull request by haampie**
This PR triggers GCCs `spec` file to be extended with `-B<libc startfile path>` and `-isystem <libc include dir>`.

This makes it possible to install a non-multiarch GCC on a multiarch system.

The search works as follows:

1. Look up the dynamic linker location from `gcc -### hello.c`
2. Compute the libc prefix from that
3. Do a fixed depth scan for the `crt1.o` startfile, e.g. `$libc/lib/x86_64-linux-gnu/`
4. Replace the `lib*` component with `include` and look for a representative header file for the libc flavor.

(It makes use of an undocumented callback during install from build cache. I don't want to make that callback public API, since it will be abused. Arguably we're already abusing it, since in the case of GCC we expect a topological order of operations during install, as we need to run gcc right relocation, whereas it would be great if install from cache was unordered and massively parallel.)

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
This is still subtly wrong. I am testing with this small specfile for convenience:
```
.xx:
./test.sh %S %i
```
It seems that if we pass the `-pie` option we get stuff like:
```
./test.sh S/usr/lib/x86_64-linux-gnu/crt1.o /usr/lib/x86_64-linux-gnu/crti.o /home/culpo/PycharmProjects/spack/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-7zvrhtb4fhmfk2niuqa2uhlfho6ub2rw/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.0/crtbeginS.o file.xx
```
Note the initial `S` in the first path. That one should read:
```
/usr/lib/x86_64-linux-gnu/crt1.o /usr/lib/x86_64-linux-gnu/Scrti.o
```
(the initial S is for the c object file name).

**Comment by haampie** [comment]
Feel free to change the regex

**Comment by alalazo** [comment]
It seems we also miss includes:
```c
#include <stdio.h>

int main() {
  printf("Hello world!\n");
}
```
This gives me:
```
$ /home/culpo/PycharmProjects/spack/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-7zvrhtb4fhmfk2niuqa2uhlfho6ub2rw/bin/gcc main.c 
In file included from main.c:1:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
so we need to patch `%I` too :sweat:

**Comment by haampie** [comment]
Ah...

```
$ readlink /usr/include/bits
x86_64-linux-gnu/bits
```

that's why it worked for me :(

It's all very ugly.

**Comment by alalazo** [comment]
@trws Can you check if this solves the `gcc` issues for you? It does for me on my ubuntu laptop. Also, any advice on what to look for to find the include folder for musl is welcome.

**Comment by haampie** [comment]
it's convoluted and ugly :+1: hopefully can improve on it at a later stage.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
