### PR TITLE
llvm: added external detection capabilities

### PR DESCRIPTION
**Pull request by alalazo**
@naromero77 @trws

### CODE REVIEW

**Comment by naromero77** [comment]
Can you say a little bit more about what this PR is trying to fix?

**Comment by alalazo** [comment]
Sure @naromero77 It's not trying to fix anything, but if you happen to have clang installed on your system and you run:
```console
$ spack external find llvm
```
with this PR Spack will automatically add entries like:
```yaml
packages:
  llvm:
    externals:
    - spec: llvm@3.9.1+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-3.9
          cxx: /usr/bin/clang++-3.9
    - spec: llvm@4.0.1+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-4.0
          cxx: /usr/bin/clang++-4.0
    - spec: llvm@5.0.1+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-5.0
          cxx: /usr/bin/clang++-5.0
    - spec: llvm@8.0.0+clang+lld+lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-8
          cxx: /usr/bin/clang++-8
          ld: /usr/bin/ld.lld-8
          lldb: /usr/bin/lldb-8
```
to your `packages.yaml` Documentation on the feature is [here](https://spack.readthedocs.io/en/latest/packaging_guide.html#making-a-package-discoverable-with-spack-external-find)

**Comment by naromero77** [comment]
OK, thanks.

My only request is that you add some comment near the top saying these class, methods, etc. are for external detection. Otherwise, @trws and I will look at this a year from now and may be totally perplexed.

**Comment by trws** [comment]
I'm with @naromero77, otherwise this looks good.

**Comment by naromero77** [comment]
I am OK with merging this PR.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
