### PR TITLE
py-pip: add v23.2.1 -> v24.3.1

### PR DESCRIPTION
**Pull request by dmagdavector**

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Can you also add:
```python
depends_on("python@3.8:", when="@24.1:", type=("build", "run"))
```

**Comment by dmagdavector** [comment]
Added new `depends_on` line.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by dmagdavector** [comment]
CI failure seems to be unrelated to `py-pip`, but rather to fetching the source for `gdk-pixbuf`:

>  ==> Error: FetchError: All fetchers failed for spack-stage-gdk-pixbuf-2.42.12-inzlrdk34cksgmqwshbhdjilboqwoh5f
        https://mirror.spack.io/_source-cache/archive/b9/b9505b3445b9a7e48ced34760c3bcb73e966df3ac94c95a148cb669ab748e3c7.tar.xz: DetailedHTTPError: GET https://mirror.spack.io/_source-cache/archive/b9/b9505b3445b9a7e48ced34760c3bcb73e966df3ac94c95a148cb669ab748e3c7.tar.xz returned 404: Not Found
>     https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz: DetailedHTTPError: GET https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz returned 403: Forbidden
>     https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz: DetailedHTTPError: GET > https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.40/gdk-pixbuf-2.42.12.tar.xz returned 403: Forbidden

* https://gitlab.spack.io/spack/spack/-/jobs/13859817

and for `visit`:

> ==> Installing vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua [122/122]
> ==> Fetching s3://spack-binaries-prs/pr47753_pypip/data-vis-sdk/build_cache/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spec.json
> ==> Error: sha256 checksum failed for /tmp/root/spack-stage/spack-stage-nobsp5ib/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spack

* https://gitlab.spack.io/spack/spack/-/jobs/13859818

**Comment by adamjstewart** [comment]
Just keep running:

@spackbot run pipeline 

until everything passes.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by dmagdavector** [comment]
Same issues as before (`gdk-pixbuf` and `visit`) with:
* e4s-build [#904213](https://gitlab.spack.io/spack/spack/-/pipelines/904213)
* data-vis-sdk-build [#904204](https://gitlab.spack.io/spack/spack/-/pipelines/904204)

@spackbot run pipeline

**Comment by dmagdavector** [comment]
For e4s-build [#905654](https://gitlab.spack.io/spack/spack/-/pipelines/905654), things consistently fail when trying to install `gdk-pixbuf` with the same error a few times now:

```
==> Error: FetchError: All fetchers failed for spack-stage-gdk-pixbuf-2.42.12-inzlrdk34cksgmqwshbhdjilboqwoh5f
        https://mirror.spack.io/_source-cache/archive/b9/b9505b3445b9a7e48ced34760c3bcb73e966df3ac94c95a148cb669ab748e3c7.tar.xz: DetailedHTTPError: GET https://mirror.spack.io/_source-cache/archive/b9/b9505b3445b9a7e48ced34760c3bcb73e966df3ac94c95a148cb669ab748e3c7.tar.xz returned 404: Not Found
    https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz: DetailedHTTPError: GET https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz returned 403: Forbidden
    https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz: DetailedHTTPError: GET https://ftp.acc.umu.se/pub/gnome/sources/gdk-pixbuf/2.40/gdk-pixbuf-2.42.12.tar.xz returned 403: Forbidden
```

The broken mirror seems to have been fixed in PR #47825 that was 'just' merged.

**Comment by dmagdavector** [comment]
For data-vis-sdk-build [#905653](https://gitlab.spack.io/spack/spack/-/pipelines/905653), consistently get an error for an incorrect checksum:

```
==> Installing vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua [122/122]
==> Fetching s3://spack-binaries-prs/pr47753_pypip/data-vis-sdk/build_cache/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spec.json
==> Fetching s3://spack-binaries-prs/pr47753_pypip/data-vis-sdk/build_cache/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/vtk-9.2.6/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spack
==> Extracting vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua from binary cache
Expected a074ec645a10bd61d7043ffa0ff38b847a013dcf84b29930d6e731cd94849fba but got 14e63aa9f17a5c8ccfad7dba943dd318f1e1b886068a46a950becca5c7acf260.  […]
```

CCing maintainers of `vtk` package: @chuckatkins @danlipsa @johnwparent

**Comment by johnwparent** [comment]
> For data-vis-sdk-build [#905653](https://gitlab.spack.io/spack/spack/-/pipelines/905653), consistently get an error for an incorrect checksum:
> 
> ```
> ==> Installing vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua [122/122]
> ==> Fetching s3://spack-binaries-prs/pr47753_pypip/data-vis-sdk/build_cache/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spec.json
> ==> Fetching s3://spack-binaries-prs/pr47753_pypip/data-vis-sdk/build_cache/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/vtk-9.2.6/linux-ubuntu20.04-x86_64_v3-gcc-11.1.0-vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua.spack
> ==> Extracting vtk-9.2.6-atky3pu7sqixzmii62het6o5ohzl3hua from binary cache
> Expected a074ec645a10bd61d7043ffa0ff38b847a013dcf84b29930d6e731cd94849fba but got 14e63aa9f17a5c8ccfad7dba943dd318f1e1b886068a46a950becca5c7acf260.  […]
> ```
> 
> CCing maintainers of `vtk` package: @chuckatkins @danlipsa @johnwparent

Cache mismatches like this are a factor of the Spack CI buildcache, not the packages themselves, looping in folks with more knowledge in that domain: @kwryankrattiger

**Comment by dmagdavector** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
I don't have time to dig into this deeply today, but I did the close/open work around to clear the PR cache and rerun the pipeline, so hopefully that is enough to get this unstuck. Will check back later to see if this is still failing.

**Comment by dmagdavector** [comment]
@spackbot run pipeline

**Pull request merged**
