### PR TITLE
Add glibc and an old gnu make

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by vvolkl** [comment]
@haampie this looks super interesting, but I understand that there have been previous attempts to add recipes for glibc and it would require substantial changes to the dependency model for compilers for it to work? @tgamblin  Is this still the case?

**Comment by haampie** [comment]
Hi @vvolkl, yes, don't expect `depends_on('glibc')` to work, see https://sourceware.org/glibc/wiki/Testing/Builds on how glibc can be used.

My goal with this PR is to just have glibc available for testing purposes, and I was hoping I could avoid having to use an ancient distro to build binaries that run on many distros.

**Comment by vvolkl** [comment]
So I tried this on arch. For gmake@3.82, I tried with gcc@9.3.0, gcc@11.1.0 and clang@11.1.0, it only built successfully with gcc@9.3.0 . For the newer gcc and clang, I got this error:

```
k4-arch-01: ~/spack (add-glibc)$ spack install gmake@3.82%clang
==> Warning: Missing a source id for texinfo@6.7
[+] /usr (external gettext-0.21-ubknm4vaxlq6432whqlwvnfu2h3zfdxn)
[+] /usr (external texinfo-6.7-iqvvitb37nzl4rzk7mxm3vraxeg7d5ri)
==> Installing gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs
==> No binary for gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs found: installing from source
==> Warning: Missing a source id for texinfo@6.7
==> Using cached archive: /home/arch/spack/var/spack/cache/_source-cache/archive/3d/3d991b33e604187c5881a0abc2e102d5b9776da5569640e73778f85d617242e7.tar.gz
==> Using cached archive: /home/arch/spack/var/spack/cache/_source-cache/archive/ca/ca60bd9c1a1b35bc0dc58b6a4a19d5c2651f7a94a4b22b2c5ea001a1ca7a8a7f
==> Applied patch https://src.fedoraproject.org/rpms/make/raw/519a7c5bcbead22e6ea2d2c2341d981ef9e25c0d/f/make-4.2.1-glob-fix-3.patch
==> gmake: Executing phase: 'autoreconf'
==> gmake: Executing phase: 'configure'
==> gmake: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'

1 error found in build log:
     346    /usr/bin/ld: rule.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/s
            pack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-stage-g
            make-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
     347    /usr/bin/ld: signame.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ih
            s/spack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-stag
            e-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
     348    /usr/bin/ld: strcache.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4i
            hs/spack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-sta
            ge-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
     349    /usr/bin/ld: variable.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4i
            hs/spack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-sta
            ge-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
     350    /usr/bin/ld: vpath.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/
            spack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-stage-
            gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
     351    /usr/bin/ld: hash.o:/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/s
            pack-src/make.h:347: multiple definition of `stack_limit'; ar.o:/tmp/arch/spack-stage/spack-stage-g
            make-3.82-hvmqpi2biqokpn5lbmsj6kkyt4xk4ihs/spack-src/make.h:347: first defined here
  >> 352    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
     353    make[2]: *** [Makefile:482: make] Error 1
     354    make[2]: Leaving directory '/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4
            xk4ihs/spack-src/spack-build'
     355    make[1]: *** [Makefile:593: all-recursive] Error 1
     356    make[1]: Leaving directory '/tmp/arch/spack-stage/spack-stage-gmake-3.82-hvmqpi2biqokpn5lbmsj6kkyt4
            xk4ihs/spack-src/spack-build'
     357    make: *** [Makefile:382: all] Error 2

```
maybe you want to add a conflict?

**Comment by vvolkl** [comment]
glibc@2.33 built successfully with gcc@11.1.0 (haven't tried with other compilers yet), I'm looking into how to use it now. @haampie, Maybe it should have a `setup_run_environment`/`setup_dependend_build_environment` though, as currently `spack load glibc` ignores `sbin` and some other installed directories
```
k4-arch-01: ~/spack (add-glibc)$ spack load --sh glibc
export SPACK_LOADED_HASHES=hse2m43lyrv5g4lrhnfzqvo7fge6jn4k;
export CMAKE_PREFIX_PATH=/home/arch/spack/opt/spack/linux-archrolling-broadwell/gcc-11.1.0/glibc-2.33-hse2m43lyrv5g4lrhnfzqvo7fge6jn4k;
export PATH=/home/arch/spack/opt/spack/linux-archrolling-broadwell/gcc-11.1.0/glibc-2.33-hse2m43lyrv5g4lrhnfzqvo7fge6jn4k/bin:/home/arch/spack/bin:/home/arch/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl;
export LD_LIBRARY_PATH=/home/arch/spack/opt/spack/linux-archrolling-broadwell/gcc-11.1.0/glibc-2.33-hse2m43lyrv5g4lrhnfzqvo7fge6jn4k/lib;

```
Also, is there a way to use the `testrun.sh` that is mentioned in the linked wiki page with the spack installation?

**Pull request closed without merging**
