### PR TITLE
add transitive run dependencies of direct build dependencies

### PR DESCRIPTION
**Pull request by davydden**
Closes #3772.

implement https://github.com/LLNL/spack/pull/4069#issuecomment-299079865

### CODE REVIEW

**Comment by citibeth** [comment]
@scheibelp @davydden 
Is this PR consistent with what we have decided in #3768?  If not, we need to either revise this PR or #3768.

**Comment by davydden** [comment]
@citibeth 

> Is this PR consistent with what we have decided in #3768?

i guess that's exactly 

> For X->Y->Z the following deptype pairs are important (and this explains the relationship between X and Z):
> ...
> build, run: 5 (e.g. transitive run dependencies of build dependencies should modify PATH for X at build time)

written by @scheibelp . If you look at OP link, you'll see that I implement his request.

**Comment by adamjstewart** [comment]
This should fix #3772 right?

**Comment by davydden** [comment]
> This should fix #3772 right?

i would say so.

**Comment by scheibelp** [comment]
Looks good - thanks!

**Pull request merged**
