### PR TITLE
New package: flecsi

### PR DESCRIPTION
**Pull request by junghans**
Fixes laristra/flecsi#235

### CODE REVIEW

**Comment by junghans** [comment]
@adamjstewart : I broke the dependency with #3779, so that can be merged.

**Comment by adamjstewart** [comment]
Hmm, I'd rather see #3779 merged first...

**Comment by junghans** [comment]
Sure, me too, but I won't have any time to write these tests in the next two weeks, plus I am guessing this involve a lot of refactor, iterating, documentation updates and more.

**Comment by adamjstewart** [comment]
Personally, I don't think #3779 should be held up by unit tests. Those lines weren't being tested before, and it's only a 2 line change. But I see your point. I'll merge this once the unit tests pass if you promise to remember to fix this package once #3779 is merged.

**Comment by junghans** [comment]
Will do, we should also rework `rust`.

**Pull request merged**
