### PR TITLE
pfunit: add versions 4.7.1, 4.7.2, 4.7.3

### PR DESCRIPTION
**Pull request by mathomp4**
This adds the latest versions of pFUnit

### CODE REVIEW

**Comment by mathomp4** [comment]
I don't think I'm responsible for the CI failure. It looks like an Error 429 with github. I'm also not sure how to re-submit that job. I don't have the rights...

**Review by tldahlgren — APPROVED** [review]
Confirmed the three new version sha256.

**Comment by mathomp4** [comment]
@tldahlgren Should I press the "update branch" button, or will that be automatically taken care of at some point?

**Comment by tldahlgren** [comment]
> @tldahlgren Should I press the "update branch" button, or will that be automatically taken care of at some point?

You could do that or manually rebase to `develop` and force push.

**Comment by tldahlgren** [comment]
I just forced it to re-run the style checks.  Not sure why it had problems accessing the Spack URL.  That may be sufficient to resolve the problem.

**Comment by tldahlgren** [comment]
> > @tldahlgren Should I press the "update branch" button, or will that be automatically taken care of at some point?
> 
> You could do that or manually rebase to `develop` and force push.

Although, it is generally not needed UNLESS there is a conflict that needs to be resolved; some other PR merged that fixes an issue (with the checks for example); or there are checks that can't be re-run without an update.

**Comment by tldahlgren** [comment]
> I just forced it to re-run the style checks. Not sure why it had problems accessing the Spack URL. That may be sufficient to resolve the problem.

Looks like this PR is now past that temporary style issue and waiting on CI.  Let's see how that goes.

**Pull request merged**
