### PR TITLE
arm-forge: add 22.1.3

### PR DESCRIPTION
**Pull request by kent-cheung-arm**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
I cannot confirm any of the new version sha256 since I'm getting:

```
$ spack checksum arm-forge 22.1.3
==> Error: Could not find any remote versions for arm-forge
```

Also, for future reference, we encourage the creation of branches for PRs.  The process is documented at https://spack.readthedocs.io/en/latest/contribution_guide.html#branching.

**Comment by kent-cheung-arm** [comment]
Thanks, I'll keep that in mind for next time.

That command works for me:
```
$ spack checksum arm-forge 22.1.3
==> Found 1 version of arm-forge:

  22.1.3  https://content.allinea.com/downloads/arm-forge-22.1.3-linux-x86_64.tar

==> Fetching https://content.allinea.com/downloads/arm-forge-22.1.3-linux-x86_64.tar

    version("22.1.3", sha256="4f8a8b1df6ad712e89c82eedf4bd85b93b57b3c8d5b37d13480ff058fa8f4467")
```

**Review by tldahlgren — APPROVED** [review]
I still can't confirm but will approve base on your results.

Also deferring merge decision to give @NickRF a chance to comment.

**Review by NickRF — APPROVED** [review]

**Comment by kent-cheung-arm** [comment]
Thanks, @tldahlgren.

**Pull request merged**
