### PR TITLE
Add compatibility system for python 2/3

### PR DESCRIPTION
**Pull request by krafczyk**
Add zip and zip_longest to this compatibility system to fix a bug
with spack info

### CODE REVIEW

**Comment by adamjstewart** [comment]
> ... to fix a bug with spack info

What bug?

**Comment by adamjstewart** [comment]
Also, if it relates to Python 2/3 compatibility, you should probably just use `six`. It's already included in our external packages.

**Comment by adamjstewart** [comment]
Ah, I see the error:
```
$ python3 $(which spack) info hdf
Package:    hdf
Homepage:   https://www.hdfgroup.org/products/hdf4/

Safe versions:  
    4.2.12    https://www.hdfgroup.org/ftp/HDF/releases/HDF4.2.12/src/hdf-4.2.12.tar.gz
    4.2.11    https://www.hdfgroup.org/ftp/HDF/releases/HDF4.2.11/src/hdf-4.2.11.tar.gz

Variants:
    Name [Default]    Allowed values    Description

==> Error: module 'itertools' has no attribute 'izip_longest'
```

**Comment by krafczyk** [comment]
Hahha, oops, I totally forgot to define the error! That's the one.

for me it was `spack info autogen`.

If there's a better way to fix this, I'm happy to use that.

**Comment by krafczyk** [comment]
I'm closing this PR, please take #4391 instead.

**Pull request closed without merging**
