### PR TITLE
Dyninst: Add dependencies for v11.0.0

### PR DESCRIPTION
**Pull request by hainest**
This is an update to the v11.0.0 PR (#22949) from @lee218llnl.

### CODE REVIEW

**Comment by hainest** [comment]
ping @mwkrentel

**Review by lee218llnl — DISMISSED** [review]

**Comment by hainest** [comment]
@adamjstewart The "linux tests / style" test in CI picked up a flake8 issue that `spack style` didn't.

**Comment by adamjstewart** [comment]
"linux tests / style" seems to be passing, it's "linux tests / centos6" that's failing:
```
==> Warning: gcc@4.4.7 cannot build optimized binaries for "skylake". Using best target possible: "core2"
==> Error: Conflicts in concretized spec "mpileaks@1.0%gcc@4.4.7 stackstart=0 arch=linux-centos6-core2/wdxbiwf"

List of matching conflicts for spec:

    dyninst@11.0.0%gcc@4.4.7~ipo+openmp~stat_dysect~static build_type=RelWithDebInfo arch=linux-centos6-core2
        ^boost@1.72.0%gcc@4.4.7+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 patches=e13cca1cfad7dcce9ed3d4ef989c14e464c4ea00caaf335f762e3677b35cab61 visibility=hidden arch=linux-centos6-core2
            ^bzip2@1.0.8%gcc@4.4.7+shared arch=linux-centos6-core2
                ^diffutils@3.7%gcc@4.4.7 arch=linux-centos6-core2
                    ^libiconv@1.16%gcc@4.4.7 arch=linux-centos6-core2
            ^zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-centos6-core2
        ^cmake@3.20.1%gcc@4.4.7~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos6-core2
            ^ncurses@6.2%gcc@4.4.7~symlinks+termlib abi=none arch=linux-centos6-core2
                ^pkgconf@1.7.4%gcc@4.4.7 arch=linux-centos6-core2
            ^openssl@1.1.1k%gcc@4.4.7~docs+systemcerts arch=linux-centos6-core2
                ^perl@5.32.1%gcc@4.4.7+cpanm+shared+threads arch=linux-centos6-core2
                    ^berkeley-db@18.1.40%gcc@4.4.7+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos6-core2
                    ^gdbm@1.19%gcc@4.4.7 arch=linux-centos6-core2
                        ^readline@8.1%gcc@4.4.7 arch=linux-centos6-core2
        ^elfutils@0.170%gcc@4.4.7~bzip2~debuginfod+nls~xz arch=linux-centos6-core2
            ^gettext@0.21%gcc@4.4.7+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos6-core2
                ^libxml2@2.9.10%gcc@4.4.7~python arch=linux-centos6-core2
                    ^xz@5.2.5%gcc@4.4.7~pic arch=linux-centos6-core2
                ^tar@1.34%gcc@4.4.7 arch=linux-centos6-core2
            ^m4@1.4.18%gcc@4.4.7+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-centos6-core2
                ^libsigsegv@2.12%gcc@4.4.7 arch=linux-centos6-core2
        ^intel-tbb@2020.3%gcc@4.4.7+shared+tm cxxstd=default patches=62ba015ebd1819c45bef47411540b789b493e31ca668c4ff4cb2afcbc306b476,ce1fb16fb932ce86a82ca87cf0431d1a8c83652af9f552b264213b2ff2945d73,d62cb666de4010998c339cde6f41c7623a07e9fc69e498f2e149821c0c2c6dd0 arch=linux-centos6-core2
        ^libiberty@2.33.1%gcc@4.4.7+pic arch=linux-centos6-core2

1. "%gcc@:5.99.99" conflicts with "dyninst@11.0.0:"
```

**Comment by hainest** [comment]
There was a timing issue here. I updated the flake8 error and pushed before you responded. The CentOS error is new. We require gcc >= 6 now, so Dyninst won't build on default CentOS 6.

**Comment by hainest** [comment]
@adamjstewart Since the CentOS gcc-4.4.7 test is the only one failing, I'm ready to merge when you are.

**Comment by adamjstewart** [comment]
The CentOS 6 tests are required, so the PR can't be merged until it passes. Could we change the test to run spec on an older version of dyninst?

**Comment by hainest** [comment]
@adamjstewart Can that be done from within the Dyninst package? If not, let me know if I can be of help.

**Comment by adamjstewart** [comment]
You can either set `preferred=True` to an older version so that that version is installed by default, or by specifying which version to install in the unit tests themselves.

**Comment by hainest** [comment]
@adamjstewart

>You can either set preferred=True to an older version so that that version is installed by default,

I'd rather keep the latest version the default.

>specifying which version to install in the unit tests themselves.

The root error is

    Error: Conflicts in concretized spec "mpileaks@1.0%gcc@4.4.7 stackstart=0 arch=linux-centos6-core2/wdxbiwf"

which I believe is coming from [`mpileaks^gcc@4.4.7`](https://github.com/spack/spack/blob/develop/lib/spack/spack/test/concretize.py#L693). I don't want to change that test, so I think the fix would be to update the mpileaks package to use an older Dyninst when using an older gcc. Thoughts?

**Comment by adamjstewart** [comment]
I would personally just change the test. This won't be an issue for the new concretizer anyway, it's only a problem with the old concretizer.

**Review by adamjstewart — DISMISSED** [review]

**Comment by hainest** [comment]
@adamjstewart The changes to the unit test don't seem to be propagating. I'm still getting the error:

    Error: Conflicts in concretized spec "mpileaks@1.0%gcc@4.4.7 stackstart=0 arch=linux-centos6-core2/wdxbiwf"

**Comment by adamjstewart** [comment]
The specific test that is failing is https://github.com/spack/spack/blob/develop/share/spack/qa/run-unit-tests#L40, I think you need to modify this one (just tell it to install an older version of dyninst).

**Comment by hainest** [comment]
@adamjstewart Ready to merge.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Would like to see one more person review before merging.

**Review by lee218llnl — APPROVED** [review]

**Comment by mwkrentel** [comment]
I also approve.

**Pull request merged**
