### PR TITLE
lmod : updated package and dependencies

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications : 
- [x] updated lmod versions and dependencies
- [x] added `lua-luafilesystem`
- [x] added three convenience properties to `version.py`
- [x] added unit tests for the properties above

### CODE REVIEW

**Comment by alalazo** [comment]
@tgamblin @trws the PR is ready to be reviewed

**Comment by trws** [comment]
This looks solid to me. Only question that comes to mind, should lmod itself also be a Lua extension package, due to its Lua source components?


________________________________

**Comment by alalazo** [comment]
@trws I don't think so, but in case anybody uses it as a `lua` extension, it wouldn't be a problem to change the `depends_on` into an `extend`.

**Comment by trws** [comment]
Ok, lets leave it as it is.  I'm good with merging it at this point.

**Pull request merged**
