### PR TITLE
perl-archive-zip: add dependency

### PR DESCRIPTION
**Pull request by teaguesterling**
Adding the dependency of `perl-compress-raw-zlib` to `perl-archive-zip`.

### CODE REVIEW

**Comment by alecbcs** [comment]
@teaguesterling do you know if this dependency is optional or was the previous install incomplete / broken?

**Comment by teaguesterling** [comment]
I will confirm through testing if it's actually necessary but the
dependency was explicitly declared in the Makefile.pl in the source package.

**Comment by teaguesterling** [comment]
It seems I may not have been comprehensive:
https://metacpan.org/pod/Archive::Zip#REQUIRED-MODULES


That said, I will still test to make sure it's actually broken.

**Comment by teaguesterling** [comment]
A basic test indicates that this isn't actually needed for basic functionality, however there are places in the code that actually use `Compress::Raw::Zlib` as well as `Carp` explicitly so we should make sure they are dependencies.

**Comment by EbiArnie** [comment]
Hi there!

The reason why these packages are not showing up as dependencies is because they are distributed with Perl itself.

$ corelist Carp
Data for 2021-05-20
Carp was first released with perl 5

$ corelist Compress::Raw::Zlib
Data for 2021-05-20
Compress::Raw::Zlib was first released with perl v5.9.4


The current policy is to depend on a minimum Perl version and trust that the packages are available.
Since the lowest Perl version in Spack is 5.16.3, even that can be omitted.

Arguably, the perl-carp and perl-compress-raw-zlib should probably be removed from Spack.

In the future, I would like to see this (which Perl version provides which other module versions) being modelled explicitly, but I haven't gotten around to doing that.

By the way, all dependencies for Archive::Zip are in core.
I recommend to close this PR without merging.

**Comment by teaguesterling** [comment]
Thank you for taking the time to explain!

**Pull request closed without merging**
