### PR TITLE
mfem: Extract setup of mfem's configuration options into separate function

### PR DESCRIPTION
**Pull request by kennyweiss**
This enables derived classes to more easily override the configuration options.

### CODE REVIEW

**Comment by kennyweiss** [comment]
@spackbot fix style

**Comment by kennyweiss** [comment]
In case it's helpful, my derived class is using `umpire@2024.02` and as a quick fix, I needed to add link flags for Umpire's `fmt` dependency

```py
from spack.pkg.builtin.mfem import Mfem as BuiltinMfem

class Mfem(BuiltinMfem):

    ...

    def configure_options(self, spec, prefix):
        """overrides the parent class's configure_options method"""

        options = super().configure_options(spec, prefix)

        # override umpire config options to add fmt, when appropriate
        if "+umpire" in spec:
            if "+umpire^fmt" in spec:
                options += [
                    "UMPIRE_OPT=-I{} -I{}".format(spec["fmt"].prefix.include, spec["umpire"].prefix.include),
                    "UMPIRE_LIB={} {}".format(self.ld_flags_from_library_list(spec["fmt"].libs), self.ld_flags_from_library_list(spec["umpire"].libs)),
                ]
            else:
                options += [
                    "UMPIRE_OPT=-I{}".format(spec["umpire"].prefix.include),
                    "UMPIRE_LIB={}".format(self.ld_flags_from_library_list(spec["umpire"].libs)),
                ]
        
        return options
```

**Comment by v-dobrev** [comment]
@kennyweiss, this has some overlaps with my PR for mfem-v4.7, #44010, which also addresses a request in #41673 to separate the config options in a separate function.

My PR also addresses the `fmt` issue with Umpire.

**Comment by kennyweiss** [comment]
Thanks @v-dobrev!  Looks like your PR entirely covers my use-case, so I'll close this PR.

The only thing I added that's not in your PR is exposing the internal utility functions like `ld_flags_from_library_list`, which might be helpful/necessary if anyone's adding additional flags (?).

**Comment by v-dobrev** [comment]
> Thanks @v-dobrev! Looks like your PR entirely covers my use-case, so I'll close this PR.
> 
> The only thing I added that's not in your PR is exposing the internal utility functions like `ld_flags_from_library_list`, which might be helpful/necessary if anyone's adding additional flags (?).

I will add that to my PR.

**Comment by v-dobrev** [comment]
> > Thanks @v-dobrev! Looks like your PR entirely covers my use-case, so I'll close this PR.
> > The only thing I added that's not in your PR is exposing the internal utility functions like `ld_flags_from_library_list`, which might be helpful/necessary if anyone's adding additional flags (?).
> 
> I will add that to my PR.

@kennyweiss, how does https://github.com/spack/spack/pull/44010/commits/ba2df61c30c11ddb3745abb963e2afb8be34946a in #44010 look?

**Comment by kennyweiss** [comment]
Thanks @v-dobrev -- looks great!

**Pull request closed without merging**
