### PR TITLE
Add NAG Fortran Compiler support

### PR DESCRIPTION
**Pull request by adamjstewart**
Ok, I have NAG mostly supported now. For example, `spack compiler info nag` works as expected. However, `spack compiler add /soft/nag/6.0/bin` returns `==> Found no new compilers` Any idea how to get this working?

### CODE REVIEW

**Comment by adamjstewart** [comment]
Just noticed that all of the other compilers had a symlink in lib/spack/env pointing to cc. Added one for nagfor. Not sure how this works, but do I have to add ones for gcc if I want to mix compilers?

**Comment by adamjstewart** [comment]
I just discovered why `spack compiler add` wasn't finding any NAG compilers.

Unlike all of the other compilers, `nagfor -V` sends its version information to STDERR, not STDOUT. `get_compiler_version()` in lib/spack/spack/compiler.py is setup to send all error messages to /dev/null:
```python
output = compiler(version_arg, return_output=True, error=os.devnull)
```
Since get_compiler_version doesn't get any version output, it sets the version to "unknown". `find` is setup to "skip compilers with unknown version", and therefore can't find any compilers even though they exist.

The easiest solution to this problem would be to change '-V' in Nag.py to '-V 2>&1' so that nagfor sends it version information to STDOUT. However, this seems kind of hacky to me. If someone adds another compiler in the future that sends its version information to STDERR, they will run into the same problem.

A better solution, in my opinion, would be to change the above compiler call so that it returns STDOUT and STDERR. I can't foresee this causing any major problems, unless an older version of a compiler doesn't support a particular option and the regexp is too generic. I'm not sure if this change needs to take place inside of executable.py's `__call__()` or if I can change the input parameters inside of get_compiler_version, but I will continue to play around with it.

Let me know which of these solutions you would prefer.

**Comment by tgamblin** [comment]
@adamjstewart: Nice!  Sorry I wasn't able to look at this sooner.  I think changing that call to return error code as well would be good... you can probably just put `error=sys.stdout` there to get that to happen.  Can you try that and see if it still finds other compilers as well?  I do not see where this would break something, unless some other compiler prints garbage to `stderr` for some reason.   I think when I wrote that line, I redirected error to `os.devnull` so that compiler detection wouldn't print a bunch of garbage to the user's screen.

**Comment by adamjstewart** [comment]
I agree, I also want to prevent it from printing anything to the user's screen. When I changed it to `error=sys.stdout`, it printed to the user's screen, but it did not get returned by compiler().

**Comment by tgamblin** [comment]
This might be kludginess in `executable.py`... lemme look at this

**Comment by adamjstewart** [comment]
Fixed. `spack compiler add` now works as expected. `~/.spack/compilers.yaml` contains:
```
    nag@6.0:
      cc: null
      cxx: null
      f77: /blues/gpfs/home/software/nag/6.0/bin/nagfor
      fc: /blues/gpfs/home/software/nag/6.0/bin/nagfor
```
and `spack compiler info nag` prints:
```
nag@6.0:
	cc  = None
	cxx = None
	f77 = /blues/gpfs/home/software/nag/6.0/bin/nagfor
	fc  = /blues/gpfs/home/software/nag/6.0/bin/nagfor
```
At this point, this pull request might be ready to merge. I'm going to try creating my own custom compiler that mixes GCC for cc/cxx and NAG for f77/fc. If I can get that working as expected, I will be very happy. If not, I guess I'll have some more work to do. But I think adding mixed compiler support is more general and would deserve its own pull request.

**Comment by tgamblin** [comment]
@adamjstewart: Thanks!  This looks quite good to me.  I am also going to improve the interface for `Executable.__call__`, as I find the current interface a bit clunky, but that can be separate from this.

**Pull request merged**
