### PR TITLE
Fix for py-cffi sha256sum issue

### LINKED ISSUE #19140: Installation issue: py-cffi
It seems that maybe #19078 has broken `py-cffi`, as the source checksum added in that PR for version `1.14.3` does not seem to match.  

I downloaded the package from pypi manually, and I got the erroneous checksum mentioned in the error message below.

```
==> [2020-10-03-03:26:18.867764] '/usr/bin/curl' '-C' '-' '-o' '/tmp/root/spack-stage/spack-stage-py-cffi-1.14.3-vzeiz2uf7wdujtbcy5fmnrcoco632o5j/cffi-1.14.3.tar.gz.part' '-f' '-D' '-' '-L' 'https://pypi.io/packages/source/c/cffi/cffi-1.14.3.tar.gz' '-k' '-sS' '--connect-timeout' '10'
...
==> [2020-10-03-03:26:19.037170] Error: ChecksumError: sha256 checksum failed for /tmp/root/spack-stage/spack-stage-py-cffi-1.14.3-vzeiz2uf7wdujtbcy5fmnrcoco632o5j/cffi-1.14.3.tar.gz
    Expected 18d82244ee114f543149c66a6e0c14e9c4f8a1044b5cdaadd0f82159d6a6ff59 but got f92f789e4f9241cd262ad7a555ca2c648a98178a953af117ef7fad46aa1d5591

/builds/spack/e4s/spack/lib/spack/spack/package.py:1266, in do_fetch:
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
  >>   1266        if checksum and self.version in self.versions:
       1267            self.stage.check()
       1268
       1269        self.stage.cache_local()
```

### Steps to reproduce the issue

```console
$ spack install py-cffi
...
```

### Information on your system

```
root@95b373678ddb:/work# spack debug report
* **Spack:** 0.15.4-1263-7cfdf6197
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-haswell
```

The `py-cffi` package does not list any maintainers:

```
root@95b373678ddb:/work# spack maintainers py-cffi
root@95b373678ddb:/work#
```

### PR DESCRIPTION
**Pull request by koning**
Closes #19140 
Closes #19145

### CODE REVIEW

**Comment by adamjstewart** [comment]
Do you know where the incorrect checksum came from?

**Review by eugeneswalker — APPROVED** [review]
LGTM. @adamjstewart should we wait to merge until we figure out the story behind the origination of bad checksum? I'm assuming the tarball just changed -- but that kinda begs the question of why and whether the changes was legitimate or not. Should we wait for more info to develop, or merge now?

**Comment by adamjstewart** [comment]
> I'm assuming the tarball just changed

Actually, that shouldn't be possible on PyPI. If it was downloading from GitHub it could change, but PyPI prevents you from re-uploading a version. We should definitely wait until we know where the old checksum came from or why it changed before merging.

**Comment by koning** [comment]
I went back to the source tarballs downloaded for a wheel install and it matches the new sh256sum. I think it was a cut and paste error from Mac off of pypi to the vnc session, (bad cut and paste). I was creating 23 PRs so it must have been for a different package.  My local install did not catch this issue though.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
