### PR TITLE
Fix superclass constructor args.

### LINKED ISSUE #1494: DeprecationWarning in repository.py
```
/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/repository.py:81: DeprecationWarning: object.__init__() takes no parameters
  super(ModuleType, self).__init__(self, namespace)
```
It seems like the super class of ModuleType is object, so there must be a bug in here. @tgamblin, it seems like you're the only one to edit this file recently.

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #1494.

@adamjstewart: does this work for you?

### CODE REVIEW

**Comment by adamjstewart** [comment]
I still get the same message. You need to drop the self argument too.

**Comment by tgamblin** [comment]
duh -- fixed.

**Comment by adamjstewart** [comment]
Looks good now. As in it will no longer issue a warning message. Although I'm not sure what that line was for and how important it is so hopefully it doesn't break anything. I'll trust you on this one :smile:

**Comment by adamjstewart** [comment]
Ah, this is from #1015, that explains why I just started seeing it. I thought it was because I tried running Spack on a different machine.

**Comment by tgamblin** [comment]
It's just habit of calling superclass constructors for exceptions -- usually I pass the message.  Actually not sure why it was allowed in the first place if the `ModuleType` constructor doesn't take args.

The new module type is there to dynamically import package names from spack namespaces.  e.g. `import spack.pkg.builtin` will not load all packages in `builtin`, and thereafter referencing `spack.pkg.builtin.foo` will lazily load `foo`.

**Comment by adamjstewart** [comment]
That line doesn't call the ModuleType constructor, it calls the constructor for ModuleType's super class, in this case object. And object doesn't take any arguments.

The internet tells me to avoid using super in Python. Maybe this is why :stuck_out_tongue:

**Comment by tgamblin** [comment]
@adamjstewart Apparently I shouldn't work on two things at once. I _think_ this is now correct.  `SpackNamespace` should be calling the `ModuleType` constructor 😄

**Pull request merged**
