### PR TITLE
adding butterflypack v2.2.0

### PR DESCRIPTION
**Pull request by liuyangzhuan**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha2456.

**Comment by tldahlgren** [comment]
Looks like conflicts for both packages need to be resolved first (before further review).

**Review by tldahlgren — COMMENTED** [review]
The diff looks fine but there are a lot of extraneous commits associated with this PR.  

We can either squash it (once the conflicts are resolved) or perhaps only those relevant commits could be added to PR-specific branch.

**Comment by liuyangzhuan** [comment]
@tldahlgren  not sure what's going on with the conflict and the commit history. I'm going to create a clean PR again.

**Comment by balay** [comment]
I suspect part of the issue here is - the changes are in `master` branch in your fork instead of a separate branch. There are potentially 2 issues here.
- for a PR  for `spack:develop`  we are to make changes over `develop` branch, not `master` branch
- local changes on develop [or master] branch will cause conflicts later when we pull on these branch to get latest spack changes - resulting in merges/conflicts etc in the commit history.

So its  best to do this via a new branch [i.e do not directly add commits to master/develop branch in a fork]

perhaps:
```
git checkout develop
git pull
git checkout -b new-feature
<edit/commit>

now create PR from `[liuyangzhuan:new-feature]` to `spack:develop`

**Comment by liuyangzhuan** [comment]
Thanks for the explanation. See my fix in https://github.com/spack/spack/pull/32670

**Pull request closed without merging**
