### PR TITLE
[WIP] Try optimized runner images

### PR DESCRIPTION
**Pull request by alalazo**
:warning: **Do not merge** :warning: 

This PR is currently to try optimized images created in https://github.com/spack/gitlab-runners using ideas from https://github.com/haampie/spack-docker-bootstrap

### CODE REVIEW

**Comment by alalazo** [comment]
@scottwittenburg Here I'm trying to use a new image for the build-system pipeline but, if I read the logs correctly, old images are used instead. What am I doing wrong?

**Comment by scottwittenburg** [comment]
fyi @zackgalbreath

**Comment by scottwittenburg** [comment]
Pipeline generation is controlled by `share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml`, and `build_systems` appears to be using the default image, defined [here](https://github.com/spack/spack/blob/227c6061e5f390e00e4e10b6fef53d32a1d1e31d/share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml#L4).  You could either change that default, or you could make `build_systems` use a custom image, like some other stack do, e.g. `radius-aws`, [here](https://github.com/spack/spack/blob/227c6061e5f390e00e4e10b6fef53d32a1d1e31d/share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml#L482).

**Comment by alalazo** [comment]
Thanks @scottwittenburg Just for my understanding, do the images I changed in `build_systems/spack.yaml` have any effect on pipelines?

**Comment by scottwittenburg** [comment]
> do the images I changed in build_systems/spack.yaml have any effect on pipelines?

Yes, those control the images used by the build jobs.  Early on, we didn't want to (or need to?) restrict the user to concretize and build with the same image, but maybe now we need that, and it no longer makes sense to specify those images separately.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request closed without merging**
