### PR TITLE
py-pillow: add v11.0.0

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/python-pillow/Pillow/releases/tag/11.0.0

Minor hiccup: https://github.com/python-pillow/Pillow/issues/8468

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot fix style

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
Build results on Ubuntu 22.04.4 LTS:
2 failed specs:
- `py-pillow~jpeg~zlib+raqm@11.0.0`
- `py-pillow~jpeg~zlib+webpmux@11.0.0`
### `py-pillow~jpeg~zlib+raqm@11.0.0`:
```py
     18    
  >> 19    ../spack-src/meson.build:38:13: ERROR: Automatic wrap-based subproject downloading is disabled
     20    
     21    A full log can be found at .stage/spack-stage-libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzao
           ccy/spack-build-26f5fcs/meson-logs/meson-log.txt


```
Build log:
```py
==> libraqm: Executing phase: 'meson'
==> [2024-10-16-15:57:22.071321] 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/meson-1.5.1-6xhfletdtuqtea33w3nrnc4t6ziqj25m/bin/meson' 'setup' '.stage/spack-stage-libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy/spack-src' '-Dprefix=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy' '-Dlibdir=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy/lib' '-Dbuildtype=release' '-Dstrip=false' '-Ddefault_library=shared' '-Dwrap_mode=nodownload'
Version: 1.5.1
Source dir: .stage/spack-stage-libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy/spack-src
Build dir: .stage/spack-stage-libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy/spack-build-26f5fcs
Build type: native build
Project name: raqm
Project version: 0.9.0
C compiler for the host machine: lib/spack/env/gcc/gcc (gcc 13.1.0 "gcc-13 (Ubuntu 13.1.0-8ubuntu1~22.04) 13.1.0")
C linker for the host machine: lib/spack/env/gcc/gcc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Did not find pkg-config by name 'pkg-config'
Found pkg-config: NO
Run-time dependency freetype2 found: NO (tried pkgconfig)
Looking for a fallback subproject for the dependency freetype2

../spack-src/meson.build:38:13: ERROR: Automatic wrap-based subproject downloading is disabled

A full log can be found at .stage/spack-stage-libraqm-0.9.0-26f5fcsr5o4gnpx3en5fljentyzaoccy/spack-build-26f5fcs/meson-logs/meson-log.txt

```
### `py-pillow~jpeg~zlib+webpmux@11.0.0`:
```py

```
spack failed to concretize specs due to conflicts.
This is likely intentional due to a conflict() in the recipe(s).
Please fix the failed specks and check the changes.
Then push the changes to the PR branch and change the PR status to 'Ready for review'.
Generated and submitted by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -uq queue.txt -may
```

**Comment by adamjstewart** [comment]
* Build error: this PR does not touch libraqm, so this build issue is not caused by this PR
* Concretization error: this is expected, as the webpmux variant was removed in 11.0.0.

**Review by bernhardkaindl — APPROVED** [review]
@adamjstewart Thanks for checking.

The build failure on the libraqm is due to som other reason, this build just triggered it.

**Pull request merged**
