### PR TITLE
julia: patch for gcc12 support

### PR DESCRIPTION
**Pull request by heerener**

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
Hm, actually this will be an issue for the next gcc release too. Alternatively can you use this patch:

```diff
diff --git a/contrib/normalize_triplet.py b/contrib/normalize_triplet.py
index 88849e9e6f..77c047b360 100755
--- a/contrib/normalize_triplet.py
+++ b/contrib/normalize_triplet.py
@@ -2,8 +2,8 @@
 
 import re, sys
 
-# This script designed to mimick `src/PlatformNames.jl` in `BinaryProvider.jl`, which has
-# a method `platform_key_abi()` to parse uname-like output into something standarized.
+# This script designed to mimic `src/PlatformNames.jl` in `BinaryProvider.jl`, which has
+# a method `platform_key_abi()` to parse uname-like output into something standardized.
 
 if len(sys.argv) < 2:
     print("Usage: {} <host triplet> [<gcc version>] [<cxxabi11>]".format(sys.argv[0]))
@@ -106,19 +106,29 @@ def p(x):
 
 # If the user passes in a GCC version (like 8.2.0) use that to force a
 # "-libgfortran5" tag at the end of the triplet, but only if it has otherwise
-# not been specified
+# not been specified.
 if libgfortran_version == "blank_libgfortran":
     if len(sys.argv) >= 3:
-        libgfortran_version = {
-            "4":  "libgfortran3",
-            "5":  "libgfortran3",
-            "6":  "libgfortran3",
-            "7":  "libgfortran4",
-            "8":  "libgfortran5",
-            "9":  "libgfortran5",
-            "10": "libgfortran5",
-            "11": "libgfortran5",
-        }[list(filter(lambda x: re.match("\d+\.\d+(\.\d+)?", x), sys.argv[2].split()))[-1].split('.')[0]]
+        # If there was no gfortran/gcc version passed in, default to the latest libgfortran version
+        if not sys.argv[2]:
+            libgfortran_version = "libgfortran5"
+        else:
+            # Grab the first number in the last word with a number
+            # This will be the major version number.
+            major_ver = -1
+            words = sys.argv[2].split()
+            for word in words[::-1]:
+                major_ver = re.search("[0-9]+", word)
+                if major_ver:
+                    major_ver = int(major_ver.group())
+                    break
+
+            if major_ver <= 6:
+                libgfortran_version = "libgfortran3"
+            elif major_ver <= 7:
+                libgfortran_version = "libgfortran4"
+            else:
+                libgfortran_version = "libgfortran5"
 
 if cxx_abi == "blank_cxx_abi":
     if len(sys.argv) == 4:
```

**Review by haampie — CHANGES_REQUESTED** [review]
Actually, this is going to get backported: https://github.com/JuliaLang/julia/pull/46116/commits/21a2c43ffb67c093d32c0b057ef58eef08dc899e

I don't think it makes sense to patch patch releases. Would it be OK to just add a conflict instead?

```python
conflicts("%gcc@12:", when="@:1.6.7")
```

**Comment by vchuravy** [comment]
GCC12 changed the FP16 ABI so supporting it on older release will be hard. @haampie idea of declaring a conflict is right

**Comment by haampie** [comment]
What Julia versions should have the conflict?

**Comment by vchuravy** [comment]
@giordano do you remember of the top of your head? I think we backported it to 1.8, right?

**Comment by giordano** [comment]
I think the PR was https://github.com/JuliaLang/julia/pull/45649 and according to https://github.com/JuliaLang/julia/pull/45649#issuecomment-1364589140 backporting to 1.6 was problematic, I can't find it applied to 1.6.7, so no I don't this was ever backported to v1.6.  Probably safer to set the conflict until v1.7

**Comment by haampie** [comment]
Okay

```python
# https://github.com/JuliaLang/julia/pull/45649#issuecomment-1364589140
conflicts("%gcc@12:", when="@:1.6")
```

then

**Comment by giordano** [comment]
v1.7 is probably also not good, because https://github.com/JuliaLang/julia/pull/45649 was backported only to v1.8

**Comment by haampie** [comment]
Okay

```python
# https://github.com/JuliaLang/julia/pull/45649#issuecomment-1192377430
conflicts("%gcc@12:", when="@:1.7")
```

then :laughing:

**Comment by heerener** [comment]
I'm not sure I'm following completely :-) 

Do I understand correctly that for now I add the suggested conflict, and it will get removed again once there is a julia 1.6 / 1.7 version which has https://github.com/JuliaLang/julia/pull/47352 included? Or the conflict stays and 1.6 will never work with `gcc@12`?

**Comment by haampie** [comment]
It will stay there, because there are incompatibilities with GCC 12's libgfortran.so.5, even though the soname was not changed.

**Review by haampie — APPROVED** [review]

**Pull request merged**
