### PR TITLE
GNU m4 depends on libsigsegv

### PR DESCRIPTION
**Pull request by adamjstewart**
http://www.perzl.org/aix/index.php?n=Main.M4

### CODE REVIEW

**Comment by tgamblin** [comment]
Seems to be optional -- do you think a variant with `default=False` would be better?  `sigsegv` isn't very big, though.

**Comment by adamjstewart** [comment]
Honestly, doesn't really matter to me. I was having trouble installing m4 with PGI and noticed that the configure script recommended I install libsigsegv. Unfortunately, this didn't help me with my PGI problems, but I figured it would be better to include all dependencies that don't come with Linux. Would you like me to make it a variant?

**Comment by tgamblin** [comment]
Yeah go ahead and make it a variant.  I think `default=True` is probably ok.  Just would allow someone to turn it off if it hurts something.

**Comment by adamjstewart** [comment]
All done!

**Comment by tgamblin** [comment]
Thanks -- added minor tweaks to put the args on there explicitly (could still pick up a system libsigsegv inadvertently)

**Comment by adamjstewart** [comment]
:+1:

**Pull request merged**
