### PR TITLE
trilinos: explicitly use variants instead of spec for TPLs

### PR DESCRIPTION
**Pull request by sethrj**
Fixes https://github.com/spack/spack/pull/27188#issuecomment-961212214

@balay Can you verify this fixes the cuda error?

### CODE REVIEW

**Review by keitat — APPROVED** [review]

**Review by keitat — COMMENTED** [review]
Are you removing STRUMPAK?

**Comment by keitat** [comment]
Trilinos 13.0.2 or later has STRUMPAK interface in Amesos2...  This fix won't cause any problem, but limiting its capability.

**Comment by sethrj** [comment]
> Are you removing STRUMPAK?

~~Ack, that's a typo. Good catch, thank you!~~

Never mind, @keitat I moved it to the `tpl_variant_map`  since it's got an independent variant to control its enable.

**Comment by sethrj** [comment]
@balay I'm going to assume this fixes the xsdk build. It's rather sad that Trilinos for exascale has to build without GPU support... (not to mention without "long long" global indexing...)

**Comment by balay** [comment]
yeah basic build worked fine. But I haven't yet tried the full suite. Now that its merged -I'll rebase my branches over it.
And will report if I see any new issues.

**Pull request merged**
