### PR TITLE
hdf5: add v1.13.1 - experimental release.

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Comment by haampie** [comment]
@lrknox can you add `preferred=True` to all the versions listed under "maintenance versions" while you're at it?

**Comment by lrknox** [comment]
> @lrknox can you add `preferred=True` to all the versions listed under "maintenance versions" while you're at it?

I can, but I didn't realize that there could be more than one "preferred" version.  Could you explain the effect of having multiple preferred versions?

**Comment by haampie** [comment]
I didn't either until recently. Spack takes from preferred versions first. So when version 14 comes out and you make it preferred, 13 is a development version, then some package conflicting with 14 should not default to 13, but rather pick the previous stable release. And that's done by preferring all stable versions.

**Review by haampie — APPROVED** [review]

**Comment by lrknox** [comment]
> I didn't either until recently. Spack takes from preferred versions first. So when version 14 comes out and you make it preferred, 13 is a development version, then some package conflicting with 14 should not default to 13, but rather pick the previous stable release. And that's done by preferring all stable versions.

@haampie we made all stable versions preferred in PR #29514 when we added experimental release version 1.13.1.  The 1.13.x versions were all removed after 1.14.0 (followed by 1.14.1, 1.14.2 and 1.14.3) were released.  Do we no longer need more than one "preferred" version?  Or at most one each for 1.14.x, 1.12.x, 1.10.x and 1.8.x?

**Pull request merged**
