### PR TITLE
bump mochi-margo to 0.9.6

### PR DESCRIPTION
**Pull request by carns**
Point release of Margo, includes some performance optimizations, better error messages, better unit tests, and support for the upcoming Mercury 2.1.0 release.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Review by mdorier — APPROVED** [review]

**Review by bernhardkaindl — COMMENTED** [review]
Hi @carns, I built your branch using `spack install -v --test=root mochi-margo %gcc@11.2.0` and got these:
```py
>> 309    FAIL: tests/unit-tests/margo-addr
>> 316    FAIL: tests/unit-tests/margo-init
```
Looking into the `test-suite.log`, I saw many of these
```
 # na_ofi_provider_check(): Requested OFI provider "tcp;ofi_rxm" (derived from "tcp"
   protocol) is not available. Please re-compile libfabric with support for
   "tcp;ofi_rxm" or use one of the following available providers:
   udp tcp sockets
```
They appear to be fixed by adding it to the default fabrics of libfabric:
```
     variant('fabrics',
-            default='sockets,tcp,udp',
+            default='sockets,tcp,udp,rxd,rxm,shm',
             description='A list of enabled fabrics',
             values=fabrics,
             multi=True)
```
So far so good. In addition, then using  `spack uninstall -ay --dependents mercury && spack install -v --test=all mochi-margo`, the testsuite of mercury still has many fails.

This is with rxd and shm added as well:
```py
     1087    45% tests passed, 104 tests failed out of 189
     1088    
     1089    Total Test time (real) =  50.35 sec
     1090    
  >> 1091    The following tests FAILED:
     1092         2 - mercury_rpc_ofi_rxd_busy (Failed)
     1093         3 - mercury_rpc_ofi_rxd (Failed)
     1094         4 - mercury_rpc_ofi_rxm_busy (Failed)
     1095         5 - mercury_rpc_ofi_rxm (Failed)
     1096         6 - mercury_rpc_ofi_shm_busy (Failed)
     1097         7 - mercury_rpc_ofi_shm (Failed)
     ...
     1194       172 - mercury_kill_ofi_udp_busy (Failed)
     1195       173 - mercury_kill_ofi_udp (Failed)
     1196    Errors while running CTest
```

Adding just `rxd` to libfabric also raises the number of tests run by `mercury`, and must added tests pass, but the total number of fails does not decrease, so it looks like some other dependency or feature used by `mercury` might be missing. In it's `configure` output, I saw a check for `rdma`, no idea if related.

The used compiler was %gcc@11.2.0, but also happens with gcc@7.5.0 as shipped in Ubuntu 18.04.

**Comment by mdorier** [comment]
Regarding the tests that fail in margo, I think the better solution should be to make them use `na+sm` instead of `ofi+tcp_rxm`.

**Comment by carns** [comment]
Thanks @bernhardkaindl and @mdorier .  The tcp test cases have been stripped from the mochi-margo repo origin/main (https://github.com/mochi-hpc/mochi-margo/pull/164).  The tests only require the sm transport now, which is built into Mercury and doesn't require any extra variants or dependencies.

@bernhardkaindl is it Ok to accept this PR as is (with the test cases corrected in a future 0.9.7 point release when we have other improvements accumulated as well), or would you prefer that we make new 0.9.6.1 tag and checksum to pick up this change immediately?  I would prefer not to alter the existing 0.9.6 tag upstream.

As for the Mercury test cases, can we address those in a separate issue if they still remain without the additional fabrics?

**Review by bernhardkaindl — APPROVED** [review]
> @bernhardkaindl is it Ok to accept this PR as is (with the test cases corrected in a future 0.9.7 point release when we have other improvements accumulated as well), or would you prefer that we make new 0.9.6.1 tag and checksum to pick up this change immediately? I would prefer not to alter the existing 0.9.6 tag upstream.

Nice to see this done for 0.9.7, very well.
> As for the Mercury test cases, can we address those in a separate issue if they still remain without the additional fabrics?

Yes, they are present also without the additional fabrics, just from a lesser amount of total test cases of course. It sounds nice that would look into them. Of course it's fine to address those in a separate PR.

I just took the chance to raise these findings because I saw them.

**Comment by carns** [comment]
Thanks @bernhardkaindl !

@soumagne any thoughts on the mercury test errors described above?  We can pursue those in a separate issue and/or pr.

**Comment by soumagne** [comment]
Mercury currently does not support the `rxd` and `shm` providers from libfabric. Also it sounds like some of the protocols were passed without the underlying provider being used. `mercury_rpc_ofi_rxm` is not a valid test with a valid protocol. `rxm` or `rxd` can't be passed alone to the mercury test suite because they are utility providers and need to be combined with another provider like `tcp`. In general we also avoid to explicitly mention those because CMake interprets semi-colons as separate list members, hence would generate a test for each provider individually, which I guess is what happens here.

**Comment by soumagne** [comment]
@bernhardkaindl just as an FYI, I'll make a PR when I bump the mercury version in a couple of days that also addresses the testing issues that you were seeing

**Comment by bernhardkaindl** [comment]
Nice!

**Pull request merged**
