### PR TITLE
Feature Proposal : Make All Python Extensions User Configuration Independent

### PR DESCRIPTION
**Pull request by xjrc**
This pull request is a continuation of #950 that makes all `python` extension packages independent of user configuration on installation.  For more information about these changes what they entail, please see #950 and #1424.

### CODE REVIEW

**Comment by xjrc** [comment]
I've updated this PR to remove all merge conflicts.  @tgamblin: I think that this should be ready.

**Comment by adamjstewart** [comment]
Can you resolve the new merge conflicts and see if any other `python()` packages have creeped in? @tgamblin Can we get this merged?

**Comment by tgamblin** [comment]
@xjrc: I rebased this for you -- can you update the PR by force pushing `features/setup_py` from the main repo to your fork?  Then I can merge it and you'll be the commit author.

**Comment by xjrc** [comment]
@tgamblin: Yeah, I'll get around to updating this sometime tomorrow.

**Comment by tgamblin** [comment]
@xjrc: I've rebased it so if you allow maintainers to push into the PR (it's a new checkbox I think) then I can just take care of it.

**Comment by xjrc** [comment]
@tgamblin: That would be great.  I enabled maintainer edits so you should be able to push, but let me know if there are any issues.  Thanks!

**Comment by tgamblin** [comment]
merged.

**Pull request merged**
