### PR TITLE
On uninstall, change shortcut flag for --dependents to -R, as per Spa…

### PR DESCRIPTION
**Pull request by citibeth**
The convention we last discussed is:

  -r = Recurse through dependencies
  -R = Recurse THE OTHER WAY through dependents

Unless we want to agree on a different convention...

### CODE REVIEW

**Comment by tgamblin** [comment]
Thanks!

**Comment by tgamblin** [comment]
@citibeth: minor nit: I didn't notice this til too late but can you keep commit msgs short (60 chars)?

**Comment by tgamblin** [comment]
probably this should get added to the style checker. So maybe I shouldn't even mention it and should roll it into `spack test` or `spack flake8`

**Comment by alalazo** [comment]
@tgamblin Do you mean just the first line or you want commit messages of less than 60 chars always?

**Comment by adamjstewart** [comment]
We also need to be careful that we remember to update our tab completion for flag/command changes. I'll submit a PR shortly to do this.

**Comment by citibeth** [comment]
Huh?

**Comment by adamjstewart** [comment]
See #3175.

**Comment by adamjstewart** [comment]
Bash tab completion was added after you started your PR, so don't worry about it.

**Comment by tgamblin** [comment]
@alalazo:
> Do you mean just the first line or you want commit messages of less than 60 chars always?
 just the first line.

**Pull request merged**
