### PR TITLE
Update the version details for rocm-5.2.3 release

### PR DESCRIPTION
**Pull request by srekolam**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Verified all package sh256.  Are the following supposed to be updated as well?

- `mivisionx`
- `rccl`
- `rocs-tensile`
- `rocm-validation-suite`

**Comment by tldahlgren** [comment]
Looks like pipeline might be having pod issues.

@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
@renjithravindrankannath Do you have any issues with this PR being merged?

**Comment by tldahlgren** [comment]
Hmmm.  Three AWS stacks are having `pod` issues, e.g.:

```
	Unschedulable: "0/35 nodes are available: 35 node(s) didn't match Pod's node affinity/selector."
Waiting for pod pipeline/runner-4z7sm6g6-project-2-concurrent-2z7b4z to be running, status is Pending
	Unschedulable: "0/35 nodes are available: 35 node(s) didn't match Pod's node affinity/selector."
Waiting for pod pipeline/runner-4z7sm6g6-project-2-concurrent-2z7b4z to be running, status is Pending
	Unschedulable: "0/35 nodes are available: 35 node(s) didn't match Pod's node affinity/selector."
Waiting for pod pipeline/runner-4z7sm6g6-project-2-concurrent-2z7b4z to be running, status is Pending
	Unschedulable: "0/35 nodes are available: 35 node(s) didn't match Pod's node affinity/selector."
Waiting for pod pipeline/runner-4z7sm6g6-project-2-concurrent-2z7b4z to be running, status is Pending
	Unschedulable: "0/35 nodes are available: 35 node(s) didn't match Pod's node affinity/selector."
ERROR: Job failed (system failure): prepare environment: waiting for pod running: timed out waiting for pod to start. Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by renjithravindrankannath — APPROVED** [review]

**Comment by renjithravindrankannath** [comment]
LGTM @tldahlgren.

**Comment by srekolam** [comment]
@tldahlgren  Thanks a lot !!!

**Pull request merged**
