### PR TITLE
GitHub Actions: do not install six in CI

### PR DESCRIPTION
**Pull request by alalazo**
I started seeing intermittent failures due to `six` not being installable, like in [this job](https://github.com/spack/spack/actions/runs/4851839887/jobs/8646173618). Since we don't need `six`, I removed it from our workflow setup.

Modifications:
- [x] Do not install `six` in CI
- [x] Remove workflow code that was commented out
- [x] Removed leftover use of `six` in packages

### CODE REVIEW

**Comment by alecbcs** [comment]
@alalazo we should probably look at caching the pip environment in CI (something like [this blog post](https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/)) or instead building it into a custom container that is run on all unit tests.

**Review by tldahlgren — COMMENTED** [review]
Looks like `six` is being imported in `multimethod` and `raiser` mock packages.  Should they be removed with this PR?

**Comment by alalazo** [comment]
> we should probably look at caching the pip environment in CI (something like [this blog post](https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/)) or instead building it into a custom container that is run on all unit tests.

I agree with that. My understanding though is that we need something slightly more complex, i.e. check how many different environments we have (Python version x type of test) and have e.g. a `requirements.txt` file for each one of them. Once we do that I think we can use:
```yaml
uses: actions/setup-python@v4
with:
    python-version: ${{inputs.python_version}}
    cache: 'pip'
    cache-dependency-path: |
      <some-dir>/requirements*.txt
```
If we pin versions of tools we use in CI for the different Python versions, we can probably have dependabot update them automatically too (so we'll move occasional breakage from `develop` to PRs).

**Comment by alalazo** [comment]
@tldahlgren Removed any leftover use of `six` from packages in b73b726

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
