### PR TITLE
[DO NOT MERGE] check effect of dropping LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by haampie**
- Don't set LD_LIBRARY_PATH on Linux
- poke gitlab/aws to build the world

### CODE REVIEW

**Comment by haampie** [comment]
or is cherry-picking e4a9dc4d3e5f11426eb209128aba42e32bbb3e25 wrong @tgamblin, am I now potentially using Tom's cache from another PR?

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
> or is cherry-picking e4a9dc4d3e5f11426eb209128aba42e32bbb3e25 wrong @tgamblin, am I now potentially using Tom's cache from another PR?

Gah -- it looks like that was wrong -- it's using Tom's cache.  Can you use `-noexist-32019` or something like that?

**Comment by tgamblin** [comment]
Or maybe just `-32019`, since `-noexist` clearly wasn't the best name in hindsight.

**Comment by haampie** [comment]
I don't think it used the cache, i started it twice, only the second time it used its own cache

- https://gitlab.spack.io/spack/spack/-/pipelines/152123
- https://gitlab.spack.io//spack/spack/-/pipelines/152618

**Comment by tgamblin** [comment]
Thanks -- I saw only the last one of those.  It does look like everything is passing!

**Pull request closed without merging**
