### PR TITLE
py-jaxlib: add external ROCm support

### PR DESCRIPTION
**Pull request by afzpatel**
This will only work with external ROCm and not spack-built ROCm.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can we get this supported upstream instead of relying on a fork?

**Comment by afzpatel** [comment]
> Can we get this supported upstream instead of relying on a fork?

This will work with the upstream releases. I just added the fork releases in case the user chooses to run those. 
So both of these should work: `spack install py-jaxlib@0.4.30-rocm-enhanced +rocm` and  `spack install py-jaxlib@0.4.30 +rocm`

**Comment by afzpatel** [comment]
@spackbot re-run pipeline

**Comment by afzpatel** [comment]
@spackbot rerun pipeline

**Comment by adamjstewart** [comment]
In that case I would prefer not to add the fork to keep the package simple.

**Comment by adamjstewart** [comment]
Can you also add this to CI? `share/spack/gitlab/cloud_pipelines/stacks/ml-linux-x86_64-rocm/spack.yaml`

**Comment by afzpatel** [comment]
> Can you also add this to CI? `share/spack/gitlab/cloud_pipelines/stacks/ml-linux-x86_64-rocm/spack.yaml`

This will only work on ROCm external and not spack-built ROCm

**Comment by adamjstewart** [comment]
Is there any progress on support for Spack-installed ROCm? I know a lot of that work is happening inside XLA, but we could also add patches from XLA to these patches. Worst case, we could also add ROCm to the CI images we use.

**Comment by afzpatel** [comment]
> Is there any progress on support for Spack-installed ROCm? I know a lot of that work is happening inside XLA, but we could also add patches from XLA to these patches.

No not currently. 

>Worst case, we could also add ROCm to the CI images we use.

Could we add py-jaxlib to the already existing e4s-rocm-external ci stack?

**Comment by adamjstewart** [comment]
I don't control the E4S stacks, only the ML stacks.

**Comment by afzpatel** [comment]
> I don't control the E4S stacks, only the ML stacks.

Ok, I'm fine with add ROCm to the ML ci image for testing jax and pytorch since they aren't currently supporting spack built ROCm.

**Comment by adamjstewart** [comment]
This is the file we would need to edit to do this: https://github.com/spack/gitlab-runners/blob/main/Dockerfiles/ubuntu-24.04.dockerfile

**Review by adamjstewart — APPROVED** [review]
Can't yet be tested in CI, so I'm just hoping this works.

**Comment by afzpatel** [comment]
@spackbot rerun pipeline

**Comment by afzpatel** [comment]
@spackbot rerun pipeline

**Comment by adamjstewart** [comment]
If it still doesn't work, try merging/rebasing develop. There were several recent fixes to CI.

**Pull request merged**
