### PR TITLE
kripke: update version to 1.2.7

### PR DESCRIPTION
**Pull request by afzpatel**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the three new version commits.

**Comment by tldahlgren** [comment]
Would like to hear from @vsrana01 since there are more extensive changes than adding a few version directives.

**Comment by afzpatel** [comment]
Hi @vsrana01, could you please review this pr

**Review by tldahlgren — APPROVED** [review]
Merging since it's been 2 weeks.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
