### PR TITLE
openblas: add v0.3.27

### PR DESCRIPTION
**Pull request by zzzoom**

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by zzzoom** [comment]
I'll have to narrow down the test failures when building with oneapi.

**Comment by zzzoom** [comment]
Tagging `@0.3.27 %oneapi` as a conflict until https://github.com/OpenMathLib/OpenBLAS/issues/4713 is fixed.

**Comment by zzzoom** [comment]
Fix is up.

**Comment by zzzoom** [comment]
@alalazo ping

**Review by alalazo — APPROVED** [review]

**Pull request merged**
