### PR TITLE
build_systems/python.py: Fix handling of python import checks

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Background:

When python packages are built using `spack install --test=[root|all]`,
the python build_system's test() function checks importing the modules
installed by the built package.

To see the actual error, spack `install --test=[root|all] --verbose`
had to be used.

Because `run_tests()` tries to add the error to the `test_log_file`
which failed because it was not set, test() terminated after the
first error by raising the `AttributeError` exception.

This improved with `b6169c` after which the `Attribute` exception
is no longer catched by the test callback handler, terminating spack
with an exception when such exception occurs.

Implementation of this patch:

Fix this by preparing and finishing the calls to run_tests() like
lib/spack/spack/package.py does for running stand-alone tests:

Define and create the expected self.test_log_file and initialize
self.failed_tests which run_test() expects for saving test failures.

After all python import tests completed, if there are tests failures,
raise TestFailure(), showing the log of all failed import checks
and adding the indication that tests of that package failed.

As of this commit, the package py-hypothesis is a good test case:
It has two import check failures which are shown by this commit on
`spack install --test=root py-hypothesis`

### CODE REVIEW

**Comment by adamjstewart** [comment]
Okay, my understanding of this PR and the underlying issue is that:

1. `spack test py-foo` works correctly
2. `spack install --test=root py-foo` runs the tests, but the installation succeeds even if the tests fail, which it shouldn't
3. This PR should fix 2) so that the installation fails and the import error is reported

I've also noticed this behavior and was meaning to fix this. Thanks for figuring it out!

Will test this locally with a couple packages and report back.

There are a lot of other packages with import tests that don't inherit from `PythonPackage`. Will those packages need this as well?

**Comment by bernhardkaindl** [comment]
> Okay, my understanding of this PR and the underlying issue is that:
> 
>     1. `spack test py-foo` works correctly

I think so, at least it looks correct there, the initial commit of this PR is based on what looks like the code for it.

>     2. `spack install --test=root py-foo` runs the tests, but the installation succeeds even if the tests fail, which it shouldn't

This was the status in September, the handling changed now. It shows an AttributeError now (better than nothing).
I think this might have been an effect of this commit: https://github.com/spack/spack/commit/b6169c213de742dc036d6eec0079bd22ee377071

>     3. This PR should fix 2) so that the installation fails and the import error is reported

Yes, and all import errors shall be collected and shown as recorded in a clean logfile, which it does with the current commit.

> I've also noticed this behavior and was meaning to fix this. Thanks for figuring it out!

Me too.

> Will test this locally with a couple packages and report back.
> 
> There are a lot of other packages with import tests that don't inherit from `PythonPackage`. Will those packages need this as well?

If they use `self.run_test()`, possibly. `grep` finds many callers of it in `var/spack/repo`, for various checks, not just import checks, and all uses of `self.run_test()` could be considered in this context.

I didn't encounter non-PythonPackage import checks before, but using 'grep`, I've found a few, eg `mxnet` and `gdal`.

With the new exception handling for the test callback (by the commit linked above), a fail from a not correctly integrated self.run_test() it should at least not go unnoticed because it should throw an exception in that case.

`lib/spack/spack/build_systems/sip.py` appears to be fixable likewise:
```py
grep -r 'run_test(' lib/spack/spack/
lib/spack/spack/build_systems/sip.py:            self.run_test(inspect.getmodule(self).python.path,
lib/spack/spack/build_systems/python.py:            self.run_test(inspect.getmodule(self).python.path,
lib/spack/spack/package.py:    def run_test(self, exe, options=[], expected=[], status=0,
```
It could be considered or checked if the test callback handler should do the setup and post-test handling of self.run_tests() instead, so all build_systems and packages using it from their test callback could have a common solution for it. I think it should work. That should then be moved to the location where the test callback is called, I assume to the location where the commit linked above changed the exception handling and the callback is called.

**Comment by adamjstewart** [comment]
@tldahlgren and I were just talking about this. I wonder if it would be easier to, in the `run_test` method, check to see if the `test_log_file` attribute is defined, and only write to that file in the case that it is. This has several benefits:

1. We don't need to change this in dozens of places (`PythonPackage`, `SIPPackage`, `gdal`, `mxnet`, etc.)
2. The same `test` method will work both at build-time and post-installation
3. It keeps the `test` method as simpler as possible

In the long run, @tldahlgren is working on changing a lot of the `spack test` framework to be more `pytest`-like, so this will likely get reworked anyway. We really just need a short-term solution.

**Comment by tldahlgren** [comment]
> @tldahlgren and I were just talking about this. I wonder if it would be easier to, in the `run_test` method, check to see if the `test_log_file` attribute is defined, and only write to that file in the case that it is. This has several benefits:
> 
> 1. We don't need to change this in dozens of places (`PythonPackage`, `SIPPackage`, `gdal`, `mxnet`, etc.)
> 2. The same `test` method will work both at build-time and post-installation
> 3. It keeps the `test` method as simpler as possible
> 
> In the long run, @tldahlgren is working on changing a lot of the `spack test` framework to be more `pytest`-like, so this will likely get reworked anyway. We really just need a short-term solution.

For background, the original intent of `PackageBase.test()` was for `spack test`, which is expected to be run weeks to months **after** the software is installed, i.e., it was not intended to be used by `spack install`.  Hence, the problems we're encountering when the method is used outside the original use case.

Of course, the current inability for `spack tests` to access `test`-only dependencies -- and in some cases key build dependencies -- is causing additional "challenges".

@tgamblin, @becker33 and I have discussed a couple of long-term solutions to some of these issues.

**Comment by bernhardkaindl** [comment]
> @tldahlgren and I were just talking about this. I wonder if it would be easier to, in the `run_test` method, check to see if the `test_log_file` attribute is defined, and ***only write to that file in the case that it is***. This has several benefits:
> 
>  1. We don't need to change this in dozens of places (`PythonPackage`, `SIPPackage`, `gdal`, `mxnet`, etc.)
> 
>  2. The same `test` method will work both at build-time and post-installation
> 
>  3. It keeps the `test` method as simpler as possible

***emphasis added by me***

@tldahlgren @adamjstewart:

*Not writing to the logfile hides all test failures (not just those of import tests) which use self.run_test() inside of the package build.*

That would not be what you want when you want to have test results -- Which it why spack has test cases in the first place.

> In the long run, @tldahlgren is working on changing a lot of the `spack test` framework to be more `pytest`-like, so this will likely get reworked anyway. We really just need a short-term solution.

***This PR*** is the short-term solution for >99% of the packages which need it, and we can improve on that in follow-up PRs.

At least on failure, when a caller of self.run_test() is not fixed, an exception is raised, even if the logfile isn't defined, so an error is shown and can be investigated. If no error is shown, the import issues won't be fixed by the developers.

We can check later (for the long-term solution) if we can move the setup and handling of test_failures to the main package class itself, so all users of run_test() in packages could be fixed by it.

**Comment by tldahlgren** [comment]
> > @tldahlgren and I were just talking about this. I wonder if it would be easier to, in the `run_test` method, check to see if the `test_log_file` attribute is defined, and only write to that file in the case that it is. This has several benefits:
> > 
> > 1. We don't need to change this in dozens of places (`PythonPackage`, `SIPPackage`, `gdal`, `mxnet`, etc.)
> > 2. The same `test` method will work both at build-time and post-installation
> > 3. It keeps the `test` method as simpler as possible
> > 
> > In the long run, @tldahlgren is working on changing a lot of the `spack test` framework to be more `pytest`-like, so this will likely get reworked anyway. We really just need a short-term solution.
> 
> For background, the original intent of `PackageBase.test()` was for `spack test`, which is expected to be run weeks to months **after** the software is installed, i.e., it was not intended to be used by `spack install`. Hence, the problems we're encountering when the method is used outside the original use case.
> 
> Of course, the current inability for `spack tests` to access `test`-only dependencies -- and in some cases key build dependencies -- is causing additional "challenges".
> 
> @tgamblin, @becker33 and I have discussed a couple of long-term solutions to some of these issues.

I should also note that the stand-alone test process does more than running the package (and its inherited) `test` methods.  For example, it runs `test` methods for the virtuals the package provides. It can also copy cached tests -- not appropriate for this context -- and custom tests to test stage directories.

While we can definitely push the variables you need for import tests to `PackageBase` so it can be re-used (separate PR coming shortly), one concern I have is whether this is really the approach we *should* be using given the added complexity baked into stand-alone tests.

Would it not be more appropriate to have import tests being separate methods (e.g., `import_test` :grin:) that are added to the callback?

**Comment by bernhardkaindl** [comment]
> I should also note that the stand-alone test process does more than running the package (and its inherited) `test` methods. For example, it runs `test` methods for the virtuals the package provides. It can also copy cached tests -- not appropriate for this context -- and custom tests to test stage directories.

Yes I saw that the stand-alone test does a lot more.

> While we can definitely push the variables you need for import tests to `PackageBase` so it can be re-used (separate PR coming shortly), one concern I have is whether this is really the approach we _should_ be using given the added complexity baked into stand-alone tests.

Using a separate alternative run_test method for build-time tests would be desirable I guess. For now it can work this way, but maybe you want to change the code in the future without breaking the other user of it. You can also add a comment to the code that it is currently used for these two different purposes.

> Would it not be more appropriate to have import tests being separate methods (e.g., `import_test` grin) that are added to the callback?

I've reviewed again where import tests (or rather, the users of `run_test()`) are:

1. There are the two buildsystem-specific import tests in `PythonPackage` and `SIPPackage`:
If these use similar code(AFACIS yes), it would make total sense to move the code for it into `PackageBase` and just call it using `import_test()` :+1: 

2. Then I there are 76 packages which use `run_test(` in var/spack/repos/builtin, but all of them also have 'def test(self`:
```
grep -rlI 'run_test(' var/spack/repos/builtin | wc -l
76
grep 'def test(self' `grep -rlI 'run_test(' var/spack/repos/builtin` | wc -l
76
```
If my guess is correct, all of these uses are stand-alone tests, so they are using it for the normal use case the run_test() function, no problem there.

@tldahlgren This means we only have python.py and sip.py which need a fix to have working import tests:
``` 
grep -rlI 'run_test(' lib/spack/spack/
lib/spack/spack/build_systems/sip.py
lib/spack/spack/build_systems/python.py
lib/spack/spack/package.py
```
For these, a common `import_test()` looks best indeed!

**Comment by tldahlgren** [comment]
> > While we can definitely push the variables you need for import tests to `PackageBase` so it can be re-used (separate PR coming shortly), one concern I have is whether this is really the approach we _should_ be using given the added complexity baked into stand-alone tests.
> 
> Using a separate alternative run_test method for build-time tests would be desirable I guess. For now it can work this way, but maybe you want to change the code in the future without breaking the other user of it. You can also add a comment to the code that it is currently used for these two different purposes.

I didn't mean an alternative to `run_test()`.  That's easy enough to push to `PackageBase` in association with these install callback without causing problems with its use for the original use case.

**Comment by bernhardkaindl** [comment]
> I didn't mean an alternative to `run_test()`. That's easy enough to push to `PackageBase` in association with these install callback without causing problems with its use for the original use case.

Ok, an `python_import_test()` function (or so) in `PackageBase`, using the `run_test()` infrastructure, used by `PythonPackage` and `SIPPackage` to run the python import tests looks good. Looking forward for your implementation/PR: Yes, it should be easy enough, just the same what `PythonPackage` has with this PR, just moved up to `PackageBase`, I guess.

**Comment by tldahlgren** [comment]
> > I didn't mean an alternative to `run_test()`. That's easy enough to push to `PackageBase` in association with these install callback without causing problems with its use for the original use case.
> 
> Ok, an `python_import_test()` function (or so) in `PackageBase`, using the `run_test()` infrastructure, used by `PythonPackage` and `SIPPackage` to run the python import tests looks good. Looking forward for your implementation/PR: Yes, it should be easy enough, just the same what `PythonPackage` has with this PR, just moved up to `PackageBase`, I guess.

Yes, it is very close to what you have here.  I'm double-checking the logging ATM.  I also assume it would be good to copy the test log to the installation directory much as we do with the build log file.

**Comment by tldahlgren** [comment]
@bernhardkaindl Is this PR still active/needed?  

Note https://github.com/spack/spack/pull/26594 generalized use of `run_test` for build- and install-time test callbacks.

**Comment by becker33** [comment]
@adamjstewart may also know whether this should have been superseded by #26594

**Comment by tldahlgren** [comment]
FYI. This is still an issue in the since that including `test` in the 

> @bernhardkaindl Is this PR still active/needed?
> 
> Note #26594 generalized use of `run_test` for build- and install-time test callbacks.

🤔  #26594 allows `run_test` to be re-used in the callbacks but doesn't perform the check used in this PR that raises the exception if any failures are detected.

By the nature of using a list of post-install callbacks, we get the messages from the `install` phase that claim the package installed successfully, which are confusing when, based on my testing, the installation of the root spec fails.

**Comment by tldahlgren** [comment]
> FYI. This is still an issue in the since that including `test` in the
> 
> > @bernhardkaindl Is this PR still active/needed?
> > Note #26594 generalized use of `run_test` for build- and install-time test callbacks.
> 
> 🤔 #26594 allows `run_test` to be re-used in the callbacks but doesn't perform the check used in this PR that raises the exception if any failures are detected.
> 
> By the nature of using a list of post-install callbacks, we get the messages from the `install` phase that claim the package installed successfully, which are confusing when, based on my testing, the installation of the root spec fails.

CORRECTION: After removing a local (bootstrap) configuration file that was causing weird errors and forcing failures in the python `test` method, I confirmed that the current code in `develop` works as expected.  That is, the installation fails and does NOT get reported as successful if a dependency's test fails (`--test all`) or if the package's test fails (`--test root`).

So, IMO, this PR can be closed.

**Review by tldahlgren — COMMENTED** [review]
IMO After testing (with a good `bootstrap` configuration file), it appears this PR is no longer needed (see #26594).

**Comment by bernhardkaindl** [comment]
Thanks, closing as obsolete.

**Pull request closed without merging**
