### PR TITLE
Add Pybind11 v2.8

### PR DESCRIPTION
**Pull request by brenthuisman**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.  Deferring merge until maintainer(s) approve.

**Review by adamjstewart — COMMENTED** [review]
We need to add:
```python
depends_on('python@2.7:2.8,3.5:', type=('build', 'run'))
```
Maybe @ax3l knows if that applies to all versions?

**Comment by brenthuisman** [comment]
Might I ask why v2.5.0 is flagged `preferred`?

**Comment by adamjstewart** [comment]
That is a great question. I'll let @ax3l answer that one, but you could also check `git blame` to see which PR added it and hopefully it's explained there. Not sure if it still needs to be preferred or not.

**Review by adamjstewart — DISMISSED** [review]

**Comment by ax3l** [comment]
> depends_on('python@2.7:2.8,3.5:', type=('build', 'run'))

Yes, that's correct!

**Comment by ax3l** [comment]
> Might I ask why v2.5.0 is flagged preferred?

I added this in #20061 quoting:

>  Since release 2.6.0 was a major release with many changes in the build system, prefer 2.5.0 for now.

Feel free to the `preferred` please :)

**Comment by brenthuisman** [comment]
> Feel free to the `preferred` please :)

I'm guessing 'remove' is the word you forgot, and I have made the commit :)

**Review by adamjstewart — DISMISSED** [review]

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
If either @adamjstewart / @ax3l approves it should be good to go, would be great to not have an old `preferred` version in the next spack release

**Comment by brenthuisman** [comment]
A test failed, but I believe it was a problem downloading the code for a Github Action (never saw this occur before). If someone can restart the test(s), I'm sure they're going to pass fine like the others.

**Comment by haampie** [comment]
done that, note that close + reopen restarts gha too

**Review by ax3l — APPROVED** [review]

**Pull request merged**
