### PR TITLE
timemory: created +python_deps variant

### PR DESCRIPTION
**Pull request by jrmadsen**
- the timemory python bindings can still be imported without these runtime packages and forcing a dependency by default significantly increases the spack install time

### CODE REVIEW

**Comment by adamjstewart** [comment]
I'm trying to understand the behavior you want. I think what you want is that no Python things are installed by default, but if the user adds `+python`, then only python and cython are installed. But if they add `+python+python_deps` then it also installs the additional dependencies, correct?

**Comment by jrmadsen** [comment]
@adamjstewart Yes, you are correct. There is a whole new suite of stand-alone python classes in the develop branch now that basically give you access to every tool individually and don't rely on all those extra dependencies in the slightest. So theoretically, if one just wants to build their own python profiling tool from those classes, forcing those dependencies to be installed is an unnecessary burden.

Also, not directly related to this PR, but this package is starting to support more packages and features and I want to simplify a few things. Is there a way for me to set up something like:

```python
# new simpler option
variant('kokkos', ...)
# old options
variant('kokkos_tools', hidden=True, ...)
variant('kokkos_build_config, hidden=True, ...)
```

so that `spack info timemory` will just show the simpler options but any older/deprecated variants will still be accepted if used by some existing setup?

**Comment by adamjstewart** [comment]
@jrmadsen got it. In that case, I think you want to add:
```python
conflicts('+python_deps', when='~python')
```
This will prevent users from building `timemory~python+python_deps`.

> Is there a way for me to set up something like:

Not at the moment, but you could open an issue as a feature request if you think it would be useful.

**Comment by jrmadsen** [comment]
@adamjstewart I lost track of this PR but yep, forgot that conflict

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
