### PR TITLE
Trilinos: add threadsafe variant

### LINKED ISSUE #43454: Installation issue: Trilinos does not have variant `Trilinos_ENABLE_THREAD_SAFE`
### Steps to reproduce the issue

Trilinos can be built to be thread safe with `-DTrilinos_ENABLE_THREAD_SAFE`. However, there is no variant that enables this.

https://docs.trilinos.org/files/TrilinosBuildReference.html#enabling-disabling-thread-safety

### Error message

Code that uses TPetra has various memory error due to it not being thread safe, e.g.,
```
Kokkos::Impl::SharedAllocationRecord 'Tpetra::CrsGraph::ptr' failed decrement count = 
```

### Information on your system

```
spack debug report
* **Spack:** 0.22.0.dev0 (23eec9d0378c818e73426bef68c3571932ad84a8)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-icelake
* **Concretizer:** clingo
```

### Additional information

@jwillenbring  @keitat  @kuberry  @psakievich  @sethrj

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by Chrismarsh**
Fixes #43454 by exposing the variant `+threadsafe`

### CODE REVIEW

**Comment by Chrismarsh** [comment]
@sethrj

**Comment by Chrismarsh** [comment]
@spackbot fix style

**Review by sethrj — DISMISSED** [review]
Great! It may need formatting though?

**Comment by Chrismarsh** [comment]
Yup sorry, thought I caught them all. Should be good now

**Review by psakievich — APPROVED** [review]

**Pull request merged**
