### PR TITLE
petsc: add variants strumpack, scalapack

### PR DESCRIPTION
**Pull request by balay**
and switch strumpack defaut to +shared

### CODE REVIEW

**Comment by pghysels** [comment]
Thank you Satish!

I'm trying this, but I keep getting this error message, in spack-build-out.txt:

```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-strumpack-dir=/home/pieterg/local/spack/opt/spack/linux-ubuntu21.04-zen2/gcc-10.3.0/strumpack-master-2pq5yb3nfkljdwl4eo4iim4dvjpedv55 did not work
*******************************************************************************
```

I tried:
`spack install petsc +strumpack ^strumpack@master ^openblas threads=openmp`
and
`spack install petsc@main +strumpack ^strumpack@master ^openblas threads=openmp`

Am I missing something?

STRUMPACK seems to be installed correctly:
```
ls /home/pieterg/local/spack/opt/spack/linux-ubuntu21.04-zen2/gcc-10.3.0/strumpack-master-2pq5yb3nfkljdwl4eo4iim4dvjpedv55/*
/home/pieterg/local/spack/opt/spack/linux-ubuntu21.04-zen2/gcc-10.3.0/strumpack-master-2pq5yb3nfkljdwl4eo4iim4dvjpedv55/include:
BLR         dense  HSS        kernel  python  SparseSolverBase.hpp  StrumpackConfig.hpp  StrumpackFortranCInterface.h  StrumpackOptions.hpp     StrumpackSparseSolver.h    StrumpackSparseSolverMixedPrecisionMPIDist.hpp
clustering  HODLR  iterative  misc    sparse  structured            strumpack_dense.mod  strumpack.mod                 StrumpackParameters.hpp  StrumpackSparseSolver.hpp  StrumpackSparseSolverMPIDist.hpp

/home/pieterg/local/spack/opt/spack/linux-ubuntu21.04-zen2/gcc-10.3.0/strumpack-master-2pq5yb3nfkljdwl4eo4iim4dvjpedv55/lib:
cmake  libstrumpack.so
```

**Comment by balay** [comment]
Hm - I just tried this and the install went through fine.
```
[balay@pj01 spack]$ spack install petsc +strumpack ^strumpack@master ^openblas threads=openmp
<snip>
[+] /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/petsc-3.15.2-idhbs2soschzko653a2wfiflrzhvkybp
```
I had updated this PR a couple of time - so perhaps you can retry with the latest changes [I don't think they should make a difference], and send me (or attach) the corresponding configure.log file - that should have details on the failure

**Comment by balay** [comment]
This feature [add strumpack variant to petsc] triggered code reorg - its currently a separate commit - perhaps I should create a separate  PR for it..

**Comment by balay** [comment]
Created a separate PR for PETSc cleanup changes

https://github.com/spack/spack/pull/25074

**Comment by adamjstewart** [comment]
@balay why did you remove the request for review from @jedbrown and @BarrySmith? They're listed as maintainers of the package, so presumably they would be the best people to review this PR.

**Comment by balay** [comment]
> @balay why did you remove the request for review from @jedbrown and @BarrySmith? They're listed as maintainers of the package, so presumably they would be the best people to review this PR.

As I'm the primary maintainer - I'm just hoping to get a review from spack side of things.

**Review by adamjstewart — APPROVED** [review]
From the Spack side of things, this is all valid Spack.

**Comment by balay** [comment]
Thanks! Perhaps @pghysels can approve again - and then this MR can be merged in

**Review by pghysels — APPROVED** [review]

**Pull request merged**
