### PR TITLE
Preliminary IcedTea Package.

### PR DESCRIPTION
**Pull request by tgamblin**
@adamjstewart @davydden @citibeth: this is RedHat's IcedTea bootstrap system for OpenJDK.

I am trying to focus on the core stuff so that we can get `0.10` out.  If @adamjstewart wants to look at this and #2622 then I would be most appreciative.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I'll test it out tomorrow. Remind me if I forget.

**Comment by tgamblin** [comment]
@adamjstewart: thanks!  The build currently fails for me on my mac, but it seems to be linux-specific in that it looks for stuff in `/etc/alternatives`.  I am not sure how universal this build really is.

**Comment by davydden** [comment]
license header is missing :-)

**Comment by citibeth** [comment]
Looks like it needs GNU fastjar:
https://savannah.nongnu.org/projects/fastjar

**Comment by adamjstewart** [comment]
I added more of the dependencies listed at: http://icedtea.classpath.org/wiki/BuildRequirements

Apparently I have fastjar available, so I was able to get past that problem. I'm still stuck at the JDK dependency (which is what I thought the whole point of this package was).
```
checking whether to build a bootstrap version first... yes
checking whether to download tarballs... yes
checking for a JDK home directory... not specified
checking for /usr/lib/jvm/icedtea-8... not found
checking for /usr/lib/jvm/java-1.8.0-openjdk... not found
checking for /usr/lib/jvm/java-1.8.0-openjdk.x86_64... not found
checking for /usr/lib64/jvm/java-1.8.0-openjdk... not found
checking for /usr/lib/jvm/java-1.8.0... not found
checking for /usr/lib/jvm/java-8-openjdk... not found
checking for /usr/lib/jvm/icedtea-7... not found
checking for /usr/lib/jvm/icedtea7... not found
checking for /usr/lib/jvm/java-1.7.0-openjdk... not found
checking for /usr/lib/jvm/java-1.7.0-openjdk.x86_64... not found
checking for /usr/lib64/jvm/java-1.7.0-openjdk... not found
checking for /usr/lib/jvm/java-1.7.0... not found
checking for /usr/lib/jvm/java-7-openjdk... not found
checking for /usr/lib/jvm/cacao... not found
checking for /usr/lib/jvm/java-openjdk... not found
checking for /usr/lib/jvm/openjdk... not found
checking for /usr/lib/jvm/java-icedtea... not found
checking for /etc/alternatives/java_sdk_openjdk... not found
configure: error: "A JDK home directory could not be found."
```
It requires:

* A working Free Software JDK e.g.
  * GCC including g++ and libgcj (version 4.3.0 or higher or any libgcj backport [with generics] of GNU Classpath >= 0.95) with JDK tree emulation (--enable-java-home) and Eclipse Java Compiler (ecj) 3.2.1 or later
  * Earlier releases of IcedTea, usually provided by your distribution

**Comment by citibeth** [comment]
@adamjstewart This is good progress!  The path that seems to make the most sense is to use GCJ+ecj to build OpenJDK/IcedTea.  A few issues to be aware of here:

 1. GCJ is part of GCC, and does not need Java to build.  Hence it's good for bootstrapping, if nothing else.

 2. GCJ compiles Java directly to object code, instead of the standard Java bytecode.  It's not really compatible with "normal" Java, but can be used to successfully compile many Java programs (think IronPython vs. regular CPython).

 3. The Java runtime libraries have always been the Achillee's heel for getting a working Java system.  I believe there are at least two open-source attempts.  A "JDK" apparently means a compiler + runtime libraries.

 4. Apparently, ECJ is another free Java compiler from Eclipse.  It looks like you use GCJ to compile ECJ; and then ECJ to build IcedTea.
I think that the "right" route to take is to use GCJ+ecj to bootstrap IcedTea.  Here's a web page with more info: http://www.linuxfromscratch.org/blfs/view/7.6/general/gcc-java.html

So probably best to break this down into pieces:

1. Get GCJ installing correctly.  That's pretty easy, you just have to turn it on when you build GCC; and apparently you need the `--enable-java-home` flag when you configure GCC.  The outstanding problem here (in my mind) is **how do we deal with another compiler from the GCC**?  Do we add GCJ to `compilers.yaml`?  Or is there another way; can we just use `gcc+java` as a build-time dependency for ECJ?

2. Get `fastjar` building.  This looks straightforward, it's just a c program from GNU.  But it looks like we'll need it, because Java tarballs are shared as `.jar` instead of `.tar.gz`.

3. Get ECJ building and installing correctly, with `gcc+java` as a build-time dependency.

4. With that in place, we should be able to build IcedTea and get a "real, certified" JDK.  The difference is that GCJ, ECJ, etc. are "mystery meat" Java installations; that is, they may or may not work on any particular Java program.  IcedTea has been through a greater effort at standards compliance.

**Comment by adamjstewart** [comment]
Oh boy, what a nightmare. Adding a GCJ option to the GCC build doesn't sound hard, but I think you might be right that we really need to add a new compiler type to Spack. @tgamblin How much work would this be? It sounds like either way this probably won't be ready in time for `0.10`, but it might be a good option in the long run. We've talked before about making compilers a more formal pseduo-dependency. It wouldn't be hard to declare that this package requires a java compiler.

**Comment by adamjstewart** [comment]
@hartzell Can you try again now that fastjar has been added? What OS are you on btw?

**Comment by citibeth** [comment]
What happens if we stop adding compiler types and just make `gcc+java` a
build dependency?  It's only one package (and will never be more than a
handful); so trying it out for a while can't hurt.

**Comment by adamjstewart** [comment]
I think the main difference would be we couldn't do anything special with compiler wrappers, like injecting RPATHs, include and lib flags, or special things like openmp flags. Not sure how many flags GCJ accepts though.

**Comment by citibeth** [comment]
GCJ is just another GCC front-end, it should accept flags similar to g++ or
gcc.

I think it would be reasonable to go without the `compilers.yaml` support
for now.  If we don't get RPATH, then that's not the end of the world.
Remember that right now, we want GCJ to build ECJ, which we would use to
build IcedTea.  As long as the final JVM is RPATH'd, we should be OK.

**Comment by adamjstewart** [comment]
I don't think it should be too much work to add a Java compiler to Spack. It might even be a fun exercise! Let me try this (assuming I'm not too busy after New Year's 😆)

1. Modify `gcc` to build the Java compiler
2. Modify the compiler wrappers to add support for a Java compiler
3. Add an `ecj` package
4. Get IcedTea/OpenJDK working

**Comment by citibeth** [comment]
Is this the best use of our efforts?  Gcj is not commonly used.

**Comment by adamjstewart** [comment]
Not sure. I barely even use Java. I've only had one user request Java support before. But it sounds like the _right_ way to do it, if there ever even is such a thing. I'm interested to here how @tgamblin feels about adding more than `CC/CXX/F77/FC` compilers to Spack in light of his plans on pseudo-dependency compilers.

**Comment by tgamblin** [comment]
@adamjstewart: I think it is a noble effort but I would rather not add more to the already 4-tuple of paths that is the current spack "compiler".  I think it's better to just have a build dep on gcc+java.  For java the compiler wrappers wouldn't buy you much anyway -- there are no RPATHs to be set or include/lib search paths.  There is only CLASSPATH, which we can set via setup_dependent_package.  There is the obvious issue that now we have to build gcc to build openjdk, but I think that can be worked out when we make compilers proper dependencies and merge the compilerdetection with externals.  

So I guess I agree with @citibeth that this is not the best thing to spend time on, especially since it could be a lot of work.

**Comment by citibeth** [comment]
In simple terms, GCJ isn't really Java, and it's not what users want when they request it.  A few Java programs can be built with GCJ and can then be thought of as more "regular" applications with RPATHs and all (Eclipse).  But most Java programs cannot, or if they can be built that way, they won't be built that way.  The build files and build process for GCJ is completely different from how you "normally" build Java programs with JDK.

The goal here needs to be to get a quality JDK unencumbered by Oracle license agreements and binary-only downloads; not to make life good for GCJ.

Let's also remember that missing RPATHs is not the end of the world.  Spack is the only auto-builder that does it; but even with Spack, RPATHs are not universal.  You still have to load modules when running Python, for example.

**Comment by adamjstewart** [comment]
Closing in favor of #4804.

**Pull request closed without merging**
