### PR TITLE
libxdmcp: add v1.1.4

### PR DESCRIPTION
**Pull request by alecbcs**
Add libxdmcp v1.1.4.

**Changelog:**
https://cgit.freedesktop.org/xorg/lib/libXdmcp/log/

**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by alecbcs** [comment]
@spackbot run pipeline 🥺

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alecbcs** [comment]
@spackbot run pipeline 🥺

**Pull request merged**
