### PR TITLE
require fortran for MPI providers to avoid delayed compiler errors

### PR DESCRIPTION
**Pull request by davydden**
As per discussion in https://github.com/LLNL/spack/issues/1859, require Fortran for now with `mpi` providers.

fixes https://github.com/LLNL/spack/issues/1859

### CODE REVIEW

**Comment by davydden** [comment]
@alalazo @nrichart @adamjstewart @bhatele @suraia @mathstuf @eschnett @KineticTheory ping.

**Comment by adamjstewart** [comment]
Should we do the same thing for all packages with a `+fortran` variant for consistency?

**Comment by davydden** [comment]
> Should we do the same thing for all packages with a +fortran variant for consistency?

i would not. It is only for virtual dependencies because you can't write
```
depends_on('mpi+fortran`)
```
in `package.py` (see https://github.com/LLNL/spack/issues/1712 )

**Comment by davydden** [comment]
> Should we do the same thing for all packages with a +fortran variant for consistency?

essentially, once we can pass variants in virtual dependencies, we can again allow `mpi`  providers to build without fortran unless we require a fortran variant.

**Comment by davydden** [comment]
@tgamblin : given that in  #1859 at least 3 people in addition to myself agree with requiring for now Fortran in mpi providers, probably this PR can be merged, unless there are further opinions against.

**Comment by adamjstewart** [comment]
@davydden Looks like there's a merge conflict. Can you rebase?

**Comment by davydden** [comment]
rebased.

**Pull request merged**
