### PR TITLE
Update hdf5 vol async version

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Review by hyoklee — APPROVED** [review]

**Review by houjun — APPROVED** [review]

**Review by jeanbez — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed tag exists.

**Comment by tldahlgren** [comment]
There are a number of unrelated commits from November 28th, possibly from a non-"standard" branch rebase.  The net change is the last commit but it would be better to drop those that aren't related to this PR.

**Comment by tldahlgren** [comment]
They are all of yours @lrknox so I think it would be fine to squash and merge.  Just let me know your preference.

**Comment by lrknox** [comment]
Yes, please squash and merge.  I tried to get rid of those commits by deleting the branch and creating it again, but that was not effective.

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
