### PR TITLE
Fixed the dependency of newer OpenMPI on current hwloc.

### PR DESCRIPTION
**Pull request by bvanessen**
Patch contributed by Thorsten Kurth.

### CODE REVIEW

**Comment by alalazo** [comment]
@hppritcha Can you please have a look at this?

**Comment by bvanessen** [comment]
@alalazo @scheibelp @becker33 Can we get this merged?

**Comment by alalazo** [comment]
@bvanessen This has now a conflict with `openmpi` in `develop`. @hppritcha ping

**Comment by bvanessen** [comment]
@alalazo I fixed the merge conflict.

**Comment by bvanessen** [comment]
@hppritcha ping

**Review by becker33 — APPROVED** [review]

**Pull request merged**
