### PR TITLE
ECP-SDK: HDF5 minimum version update

### PR DESCRIPTION
**Pull request by kwryankrattiger**

### CODE REVIEW

**Review by wspear — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
Rebase

**Comment by alalazo** [comment]
@kwryankrattiger Is this still relevant? If so, please rebase it and ping me - I'll try to merge it as soon as CI is :heavy_check_mark:

**Comment by kwryankrattiger** [comment]
This is redundant with #35195 now, I would much rather force the version update based on the vol adapter deps than hard code it in the spec.

**Comment by alalazo** [comment]
> This is redundant with https://github.com/spack/spack/pull/35195 now

Ok, closing the PR then. Thanks for the reply.

**Pull request closed without merging**
