### PR TITLE
sirius: add libxc constraint

### PR DESCRIPTION
**Pull request by RMeli**
Add constraint on `libxc` plus some cleanup.

### CODE REVIEW

**Review by mtaillefumier — APPROVED** [review]
Actually, unless we tested sirius with libxc 7, I would constrain libxc to  6.x. The rest is alright thanks for fixing this.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
🤔 Wondering if I should wait on one of the pre-PR maintainers to approve this change before merging. Please ping me on this.

**Comment by mtaillefumier** [comment]
i think we can merge it. These changes are really minor.

**Review by AdhocMan — APPROVED** [review]
Looks good to me.

**Pull request merged**
