### PR TITLE
Enable views test on windows

### PR DESCRIPTION
**Pull request by jamessmillie**
I removed the decorator that was preventing a views.py test from running on windows and it worked for me locally.

### CODE REVIEW

**Comment by johnwparent** [comment]
@jamessmillie this PR looks good. Would you mind attempting to use view's locally to validate whether they actually work on Windows? I've had a few issues with regeneration and some other operations and I wonder if perhaps this test suite doesn't have sufficient coverage to catch these cases. 
I know this is a bit outside the scope of "re-enabling views tests" but typically we say that once a test suite is enabled on Windows we officially support the feature so I just want to be sure the feature actually works as advertised on the platform, which has not been my experience.

**Review by bernhardkaindl — COMMENTED** [review]
@jamessmillie Could you check John's comment?

**Comment by jamessmillie** [comment]
Here is the testing that I have done on windows with the following details:

`spack view add zlib zlib` - worked
`spack view symlink C:\Users\qar\Documents\Tech-X zlib` - worked
`spack view hardlink C:\Users\qar\Documents\Tech-X\zlib1 zlib` - Failed, hard links on windows have to be on the same drive
`spack view hardlink D:\zlib1 zlib` - worked (my spack is installed on D:\)
`spack view statlink zlib` - worked
`spack view remove zlib -a` - worked

Am I missing anything?

**Comment by johnwparent** [comment]
> Here is the testing that I have done on windows with the following details:
> 
> `spack view add zlib zlib` - worked `spack view symlink C:\Users\qar\Documents\Tech-X zlib` - worked `spack view hardlink C:\Users\qar\Documents\Tech-X\zlib1 zlib` - Failed, hard links on windows have to be on the same drive `spack view hardlink D:\zlib1 zlib` - worked (my spack is installed on D:) `spack view statlink zlib` - worked `spack view remove zlib -a` - worked
> 
> Am I missing anything?

From today's sync: My use case has been solved (by the symlink PR or something else in develop I'm still not sure) so this testing is sufficient, thanks!

Let me know if you need help re-enabling the `cmd/views.py` tests.

**Review by bernhardkaindl — APPROVED** [review]
@johnwparent wrote:
> From today's sync: My use case has been solved (by the symlink PR or something else in develop I'm still not sure) so this testing is sufficient, thanks!
>
> Let me know if you need help re-enabling the cmd/views.py tests.

@johnwparent Does this mean that we can merge this PR, or should tests be updated as well?

**Comment by johnwparent** [comment]
> @johnwparent Does this mean that we can merge this PR, or should tests be updated as well?

I'd like to get as much of the CI running on Windows as possible as soon as possible. So if we can merge this and do the rest in a follow-up, that'd be ideal. 

Thanks said if @jamessmillie is still working on this or would like to just work from this PR, there are only a couple tests added by this PR so it's not the worst thing to wait.

**Review by johnwparent — APPROVED** [review]
Approval pending whether or not @jamessmillie wants to add the `cmd` tests here or in a followup. These changes are fine to go in on their own however.

**Comment by jamessmillie** [comment]
The `cmd` tests are waiting on #39729 so this can be merged and I can open a new PR once that is in.

**Comment by techxdave** [comment]
See https://github.com/spack/spack/pull/41810

**Comment by bernhardkaindl** [comment]
@techxdave wrote:
> See https://github.com/spack/spack/pull/41810

This is too much for me to judge. @jamessmillie, I think you are fine to have this merged now?

Cc: @johnwparent - thanks!

**Comment by johnwparent** [comment]
> @techxdave wrote:
> 
> > See #41810
> 
> This is too much for me to judge. @jamessmillie, I think you are fine to have this merged now?
> 
> Cc: @johnwparent - thanks!

@bernhardkaindl This should _not_ be merged at this point. Dave linked #41810 as the new blocker for the CMD tests. Discussion on #41810 has been partially resolved, I'll be pushing something up there shortly and will update here when that's done and this is good to go. 

For now I'm going to leave a blocking review.

**Review by johnwparent — CHANGES_REQUESTED** [review]
Waiting on #41810

**Pull request closed without merging**
