### PR TITLE
py-reretry: add new versions

### PR DESCRIPTION
**Pull request by w8jcik**
Installation succeeds

```bash
spack install py-reretry@0.11.8 py-reretry@0.11.7 py-reretry@0.11.1
```

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
FYI. Confirmed the two version sha256.

**Review by charmoniumQ — APPROVED** [review]

**Comment by charmoniumQ** [comment]
Note that 0.11.7 was "yanked". The artifacts are still downloadable, but presumably the author doesn't intend them to be downloaded. @adamjstewart What's Spack's policy for packages which have been yanked in PyPI?

v0.11.8 looks great though :+1:

**Comment by w8jcik** [comment]
> Note that 0.11.7 was "yanked". [...] What's Spack's policy for packages which have been yanked in PyPI?

I believe that for packages that shouldn't be used, we add `deprecated=True`.

But this is only for versions that were in repository before and someone might have installed them.
In this case we can just remove `0.11.7`. Would it be fine?

**Comment by w8jcik** [comment]
I have removed `0.11.7`.

**Review by charmoniumQ — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
