### PR TITLE
harfbuzz: new versions 7.*, removed preferred from 5.3.1

### PR DESCRIPTION
**Pull request by wdconinc**
This adds the new 7.0.0, 7.0.1, and 7.1.0 versions of harfbuzz.

This also removes the 'preferred' tag on the 5.3.1 version, which was just marked that way because only 6.0.0 was available when previous versions were added (commit 904eefc9304).

I tested that all new versions build, and that all dependents of harfbuzz build correctly against 7.1.0 (or at least fail for other reasons*):
```console
$ spack find -lxv
==> In environment harfbuzz
==> Root specs
------- harfbuzz@7.1.0  ------- libraqm  ------- mesa@23.0.0 +glx~llvm+opengl+opengles+osmesa  ------- pango        ------- py-xdot  ------- qt-base  ------- r-textshaping
------- kitty           ------- mapnik   ------- opencv                                        ------- py-dask-glm  ------- qt       ------- r        ------- texlive

==> Installed packages
-- linux-ubuntu23.04-skylake / gcc@12.2.0 -----------------------
3cexrin harfbuzz@7.1.0+graphite2~strip build_system=meson buildtype=debugoptimized default_library=shared
igmlprg libraqm@0.9.0~strip build_system=meson buildtype=debugoptimized default_library=shared
jjs35qf mesa@23.0.0~egl+glx~llvm+opengl+opengles+osmesa~strip build_system=meson buildtype=release default_library=shared patches=ee737d1
vtwkhaa opencv@4.6.0~1394~ade~alphamat~android_mediandk~android_native_camera~annotation~aruco~avfoundation~barcode~bgsegm~bioinspired~calib3d~cap_ios~carotene~ccalib~clp+contrib~cpufeatures~createsamples~cublas~cuda~cudaarithm~cudabgsegm~cudacodec~cudafeatures2d~cudafilters~cudaimgproc~cudalegacy~cudaobjdetect~cudaoptflow~cudastereo~cudawarping~cudev~cudnn~cufft~cvv~datasets~directx~dnn~dnn_objdetect~dnn_superres~dpm~dshow~eigen~face~fast-math~features2d~ffmpeg~flann~freetype~fuzzy~gapi~gdal~gtk~hdf~hfs~highgui~hpx~img_hash~imgcodec_hdr~imgcodec_pfm~imgcodec_pxm~imgcodec_sunraster~imgcodecs~imgproc~intensity_transform~interactive-calibration~ipo~ipp~itt~jasper~java~java_bindings_generator~jpeg~lapack~line_descriptor~matlab~mcc~ml~model-diagnostics~msmf~msmf_dxva~nonfree~objc~objc_bindings_generator~objdetect~onnx~opencl~opencl_d3d11_nv~openexr~opengl~openjpeg~openmp~optflow~phase_unwrapping~photo~plaidml~plot~png~powerpc~protobuf~pthreads_pf~python3~python_bindings_generator~python_tests~qt~quality~quirc~rapid~reg~rgbd~saliency~sfm~shape+shared~stereo~stitching~structured_light~superres~surface_matching~tbb~tengine~tesseract~text~tiff~tracking~traincascade~ts~v4l~version~video~videoio~videostab~visualisation~viz~vtk~vulcan~webp~wechat_qrcode~win32ui~world~xfeatures2d~ximgproc~xobjdetect~xphoto build_system=cmake build_type=RelWithDebInfo generator=make patches=2aea289,3cab451
4iocqyd pango@1.50.13+X~strip build_system=meson buildtype=debugoptimized default_library=shared
xwntcgl py-dask-glm@0.2.0~docs build_system=python_pip
wk5mnfd py-xdot@1.2 build_system=python_pip
j7vnxpb qt@5.15.9~dbus~debug~doc~examples~framework~gtk+gui~opengl~phonon+shared+sql+ssl+tools~webkit build_system=generic patches=2081e9c,51aeba5,75bcb42,7f34d48,84b0991,9378afd
eeom5dr qt-base@6.5.0+accessibility~dbus~framework~gtk+gui~ipo~network~opengl+shared+sql+widgets build_system=cmake build_type=RelWithDebInfo generator=ninja
hdfhnum r@4.2.2~X~external-lapack~memory_profiling~rmath build_system=autotools
ahqqht6 r-textshaping@0.3.6 build_system=generic
hhk2sjr texlive@20220321 build_system=autotools scheme=small
nyne7pc xcb-proto@1.15.2 build_system=autotools
waqlllw xtrans@1.4.0 build_system=autotools
==> 14 installed packages
```

Failing packages: kitty and mapnik, both for unrelated reasons (and both need updates anyway).

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the four affected version sha256.

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
The CI stack is failing on `harfbuzz` due to a `make` issue, e.g.:

```
make: *** No rule to make target 'install-deps/harfbuzz-7.1.0-nxpd5x52ktpgqpvlc5pyqpoha6subpz7'.  Stop.
```

**Comment by wdconinc** [comment]
That's a make from `spack env depfile` or `spack ci generate`. No actual build issue visible in those pipelines. Not sure what's going on ...

**Comment by alalazo** [comment]
There has been a bug in `develop` for a couple of hours for depfiles. I think you were unlucky and run pipelines in that time window.

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by wdconinc** [comment]
@alecbcs In https://github.com/spack/spack/pull/37492 you added 7.2.0, but you didn't remove the `preferred` on 5.3.1. This PR added newer versions AND removed the `preferred` on the older version.

I am quite discouraged from submitting new PRs because I end up having to resolve conflicts when others do part of the same work, and it's really just becoming a waste of time for me. If you are updating a package, please run a search to see if someone has already submitted something similar.

**Comment by alecbcs** [comment]
@wdconinc Oh man I'm sorry! Apologies for the conflict. I do check for existing open PRs before submitting a package bump. Unfortunately it seems I missed this PR since it's titled with `7.*` instead of the full versions affected. 

One way to fix this could be for me to reduce the complexity of the search queries to simply include the name of the package, although I've found that increases the number of false positives, and as a result I almost never end up submitting a version bump for a package like `go` since the letters "g" and "o" end up in PRs modifying `hugo`, `ginkgo`, `xlogo`, etc....

Perhaps another way to go about solving this issue, would be to have @spackbot send out notifications to an author of a PR when another PR is opened modifying the same file. That way you'd be made aware of a conflict prior to it ending up in develop. 

Does this sound reasonable to you? Or is there something else I'm overlooking? Happy to brainstorm some ideas together if you're interested.

**Comment by wdconinc** [comment]
No problem, and I'm sorry; I was just having a rough day :-)

I've also wondered about spackbot and how it can help here. For many of these packages there is no maintainer. And it isn't the maintainer who makes the changes. Maybe it can go in the opposite direction too: if someone submits a PR on some file, spackbot could post a comment with links to potentially relevant already open PRs that are touching the same files (possibly within limits, maybe only under var/spack/repos/builtin, and can be disabled when title has `treewide` or so). That centralizes the info instead of spreading it across a number of already open PRs. It would still generate back-reference links as well, but not notify the subscribers of the original PRs.

Something like this (modeled after the spackbot maintainer comment above):

> Hi @wdconinc! I noticed that you are modifying the following package(s):
> - harfbuzz
> 
> Here are some open PRs that modify the same package(s) and may contain related changes:
> - #37492

**Comment by wdconinc** [comment]
Closing since now https://github.com/spack/spack/pull/37753 has also changed the `preferred` assignment.

**Comment by michaelkuhn** [comment]
Sorry, not sure how I missed this PR. I normally search for open PRs before opening one myself.

**Comment by wdconinc** [comment]
No problem. I think @alecbcs was on to something useful with a feature for the bot to add more alerting on related PRs.

**Pull request closed without merging**
