### PR TITLE
rust: enable vendor

### PR DESCRIPTION
**Pull request by LydDeb**
Add '--enable-vendor' during configure to use vendor dependencies instead of download them during the build.

### CODE REVIEW

**Comment by alecbcs** [comment]
@LydDeb thanks for the PR! Let's just make this the default functionality instead of including it as a variant.

**Review by alecbcs — CHANGES_REQUESTED** [review]
@LydDeb thanks for the PR! Unless you've got a particular use case where you'd like to use the latest dependencies, let's just make this the default functionality instead of including it as a variant.

**Comment by LydDeb** [comment]
> @LydDeb thanks for the PR! Unless you've got a particular use case where you'd like to use the latest dependencies, let's just make this the default functionality instead of including it as a variant.

You are welcome. I just removed the variant and kept the `--enable-vendor` configuration option.

**Review by alecbcs — APPROVED** [review]
Looks good to me. @LydDeb thanks for the quick turn around!

**Pull request merged**
