### PR TITLE
workaround to ILCSoft/LCIO#114 parallel builds

### PR DESCRIPTION
**Pull request by joequant**
This is a workaround for a missing dependency for Lcio
that shows up in massive builds

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi @joequant, what is the error this fixes? Can you submit this patch to LCIO so the developers can discuss it?
Thanks!

**Comment by vvolkl** [comment]
I think this is superseded by https://github.com/spack/spack/pull/18841

**Comment by adamjstewart** [comment]
No response from @joequant so I assume this PR is no longer needed

**Comment by joequant** [comment]
Just checked, the patch is still needed and has not been fixed.

The issue is that there is a race condition in the build.  The build will fail if it's run in parallel and the lcio examples finishes the build before the libraries have also completed their build.  The patch delays the building of the examples until the lcio library is built.

I'm running into this problem because I'm caching the builds and so some of the builds will finish in a different order.

**Comment by joequant** [comment]
Checked again.  The patch was fixed in 2.15 :-)   It's all good.  :-)

**Pull request closed without merging**
