### PR TITLE
pyscf: Add @2.0.1, update dependencies

### PR DESCRIPTION
**Pull request by prckent**
(Second attempt, hopefully cleaner)

Add latest version 2.0.1 released 4 November 2021. Also update python deps consistent with the setup.py for version >= 2.

This is a minimal update to get the current version working in spack. There are numerous options that could be added by someone who needs more than basic functionality and who has more time.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the tag exists.  Will defer merge decision until maintainer has a chance to comment.

**Review by naromero77 — APPROVED** [review]
@prckent Sorry for the delay. 

Is there someone else from the QMCPACK project that is willing to be the official maintainer?

**Comment by prckent** [comment]
@naromero77 Thanks for the approval. Did you ever discuss with anyone from PySCF directly? While we use this code to generate inputs for QMCPACK, the ideal would be for someone from that project to be responsible for the spack packaging.

**Comment by naromero77** [comment]
> @naromero77 Thanks for the approval. Did you ever discuss with anyone from PySCF directly? While we use this code to generate inputs for QMCPACK, the ideal would be for someone from that project to be responsible for the spack packaging.

Yes, it would be ideal if someone from the PySCF project owns the package. No, I didn't talk to anyone from the project before I created this package.

**Pull request merged**
