### PR TITLE
kealib: add 1.5.1 and 1.5.2 versions

### PR DESCRIPTION
**Pull request by gillins**
ping @neilflood

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256s.

**Comment by tldahlgren** [comment]
@gillins @neilflood @petebunting Is this PR ready to be merged?

**Comment by gillins** [comment]
Yes - thanks!

**Comment by neilflood** [comment]
@gillins You mentioned privately that the HDF5 HL dependency is now only for earlier versions (did I understand that right?). I think you should be able to capture this with a pair of depends_on() directives, something like
```
depends_on("hdf5+cxx+hl", when="@:1.5.1")
depends_on("hdf5+cxx", when="@1.5.2:")
```
meaning that the HL is required up to version 1.5.1, but not after that.

Would that capture what you intended?

**Comment by gillins** [comment]
Thanks @neilflood, I couldn't work out the syntax. I'll update.

**Review by neilflood — APPROVED** [review]
OK, I think that all looks good now, thanks.

**Comment by tldahlgren** [comment]
There was a timeout on one stack. Unfortunately, IIRC all of the stacks have to be re-run.

@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
