### PR TITLE
Don't immediately raise an error when an editor is not found

### LINKED ISSUE #4526: Default Editor in Non-Interactive Mode
Hi,

with the latest updates in `develop` (tested: 790b06e0c363ce1598deb3bde217c4685701b61d) spack seems to require to know my `default editor` when installing software, even in non-interactive mode.

On the first call to `spack install` it now fails if *no editor is installed* on a system (which is quite often the case in docker images #4480):
```
Traceback (most recent call last):
  File "/home/src/spack/bin/spack", line 80, in <module>
    import spack.main  # noqa
  File "/home/src/spack/lib/spack/spack/__init__.py", line 227, in <module>
    default = default_editors[0]
NameError: name 'default_editors' is not defined
```

This was not required earlier this week, so it might have been introduced quite recently. IMHO, spack should not need to know my editor for such a task :) (only for `spack create`-like commands)

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #4526 

Closes #4527 

@tgamblin @ax3l Can you test this?

### CODE REVIEW

**Comment by tgamblin** [comment]
@adamjstewart: In the original version, you get this when `EDITOR` is not set:

```console
$ spack edit mpich
==> Error: 'NoneType' object is not callable
```

I put in a small change to make this raise a sensible error when Spack tries to use a nonexisting editor:

```
$ spack edit mpich
==> Error: No text editor found! Please set the EDITOR environment variable to your preferred text editor.
```

With this change it works for me, and things that don't require editors will still work without `EDITOR` being set.

**Comment by adamjstewart** [comment]
> you get this when EDITOR is not set

You mean when `EDITOR` is set but to a non-existent editor? It still goes through the `which` if `EDITOR` is not set, right?

**Comment by tgamblin** [comment]
Actually I mean if `EDITOR` is not set *and* neither `vim`, `vi`, `emacs`, nor `nano` is installed.  In that case you'll just get `None` and later try to call it

**Comment by tgamblin** [comment]
If `EDITOR` is set to something nonsensical it'll still just trust it and try to execute it.  I think that is ok.

**Comment by adamjstewart** [comment]
I'm not sure if we'll ever see a case where none of these editors is installed in an interactive session, but I must admit I never knew a docker image had none of these editors, so never say never I guess. LGTM.

**Comment by ax3l** [comment]
> I'm not sure if we'll ever see a case where none of these editors is installed in an interactive session

@adamjstewart yep exactly, if you run a docker minimal container interactively, you won't have any of the editors. for example is `ubuntu:16.04`.

**Pull request merged**
