### PR TITLE
Create new test file about cmd.

### PR DESCRIPTION
**Pull request by TomohiroAkashi**
This file was added for the "checksum" , "clone" and "module" cmd test.

### CODE REVIEW

**Comment by adamjstewart** [comment]
```
UnknownPackageError: Package 'patchcmd' not found.
```
It seems you need to add a new mock package or use an existing one.

**Comment by TomohiroAkashi** [comment]
>adamjstewart
Thank you for comments.
I  add the mock package, but I don't understand about Reviews.
Do they all need to write the code to pass?
For example, I didn't consider "macos" test, so ...

**Comment by TomohiroAkashi** [comment]
> 
> 
> ```
> UnknownPackageError: Package 'patchcmd' not found.
> ```
> 
> It seems you need to add a new mock package or use an existing one.

adamjstewart
Thank you for comments.
I add the mock package, but I don't understand about Reviews.
Do they all need to write the code to pass?
For example, I didn't consider "macos" test, so ...

**Comment by adamjstewart** [comment]
Yes, they all need to pass.

**Comment by TomohiroAkashi** [comment]
> 
> 
> Yes, they all need to pass.

Thanks for fast reply.
OK, I try fix and check the code.

**Comment by TomohiroAkashi** [comment]
To find out why the implementation of "patchcmd" does not pass review, we will withdraw the modifications to the following related commands.

- patch-cmd.patch
- package.py,
- patch.py
- restage.py
- stage.py

I would like to make a pull request for the following changes.

- fetch.py
- clone.py
- checksum.py
- module.py
- modules.yaml

**Comment by alalazo** [comment]
Apologies for these PRs of yours getting lost in the queue of other PRs. I'm seeing them today as I'm trying to go through the queue of open PRs starting from the tail :sweat:  

I'd be for closing them, since tests have been refactored in the meanwhile, but please:
1. Reopen this if you disagree
2. Feel free to submit another PR and ping me repeatedly for review if I don't reply

Note that we try to privilege small unit tests, rather than "full integration tests" via spack commands since a while (unless they really test some code logic).

**Pull request closed without merging**
