### PR TITLE
Bump up the version for ROCm-6.0.0

### PR DESCRIPTION
**Pull request by renjithravindrankannath**
Bump up the version for ROCm-6.0.0

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed all of the version directive sha256.  There are definitely CI build problems however.

**Comment by renjithravindrankannath** [comment]
Multiple apps failing to build in ci-gitlab due to the commit [504e670d7329bf75a31f4b1ce0eae40346a59701](https://github.com/ROCm/HIP/commit/504e670d7329bf75a31f4b1ce0eae40346a59701).

**Review by tldahlgren — DISMISSED** [review]

**Comment by renjithravindrankannath** [comment]
@spackbot rerun pipeline

**Comment by renjithravindrankannath** [comment]
@spackbot rerun pipeline

**Comment by renjithravindrankannath** [comment]
Hi @trws ,
adios2 build in ci-gitlab [failing](https://gitlab.spack.io/spack/spack/-/jobs/9803146) due to the commit [c508ff1e5fe06b5723c7a31d31757c37cba39013](https://github.com/spack/spack/commit/c508ff1e5fe06b5723c7a31d31757c37cba39013) from the PR [42111](https://github.com/spack/spack/pull/42111)
Please let us know if any changes required in adios2 recipe side.

**Comment by trws** [comment]
Did you bisect this @renjithravindrankannath?  The error is adios not finding a Kokkos header file for some reason, and doesn't invoke any of the flags that changed behavior.

**Comment by renjithravindrankannath** [comment]
> Did you bisect this @renjithravindrankannath? The error is adios not finding a Kokkos header file for some reason, and doesn't invoke any of the flags that changed behavior.

Hi @trws , I tried adios2@2.9.2 +rocm build on the develop branch (rocm 5.7.1) and it failed.
After reverting only this change from PR 42111 the build was success.

**Comment by dguibert** [comment]
> After reverting only this change from PR 42111 the build was success.

I've also hit this problem, `hipify-clang` build when it is reverted.

**Comment by renjithravindrankannath** [comment]
> > After reverting only this change from PR 42111 the build was success.
> 
> I've also hit this problem, `hipify-clang` build when it is reverted.

yes. hipify-clang@5.7.1 failed to build on the develop branch with this change.
Hi @tldahlgren, ci-gitlab builds are complete except the failure in adios2 due the commit [c508ff1e5fe06b5723c7a31d31757c37cba39013](https://github.com/spack/spack/commit/c508ff1e5fe06b5723c7a31d31757c37cba39013).
Could you please review and let us know if any changes needed to get this merged.

**Comment by trws** [comment]
The change was reverted in #42196.

**Comment by renjithravindrankannath** [comment]
> The change was reverted in #42196.

Thank you @trws  ..!

**Comment by tldahlgren** [comment]
Uh oh.  It looks like something went wrong with the latest rebase.  There are about 6 commits from other PRs now being associated with this PR.

**Comment by renjithravindrankannath** [comment]
> Uh oh. It looks like something went wrong with the latest rebase. There are about 6 commits from other PRs now being associated with this PR.

Hi @tldahlgren , Reverted the incorrect rebase and merged the changes correctly.
Thanks

**Review by tldahlgren — APPROVED** [review]
Re-confirmed all of the version directive's sha256.

**Comment by tldahlgren** [comment]
Should I wait for feedback from one of the other maintainers before merging?

**Review by srekolam — APPROVED** [review]

**Comment by renjithravindrankannath** [comment]
> Should I wait for feedback from one of the other maintainers before merging?

Hi @tldahlgren , Sreeni reviewed and approved.

**Review by afzpatel — APPROVED** [review]

**Pull request merged**
