### PR TITLE
zlib: fix shared libraries when '%nvhpc'

### PR DESCRIPTION
**Pull request by skosukhin**
@haampie you will probably like this

### CODE REVIEW

**Comment by haampie** [comment]
sigh :(

(personally I think zlib should be replaced with zstd everywhere)

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
Ugh, this really feels like it's not the way :|

**Comment by alalazo** [comment]
It's a fix for `%nvhpc` only, happy to merge anything better.

**Comment by haampie** [comment]
I don't agree with the soname change (it's not necessarily related to the zlib version number), and I think it's better to spend the energy fixing this upstream instead of in Spack. Also Mark Adler is open for that: https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/configure#L360

**Pull request merged**
