### PR TITLE
meson: add version 1.3.2

### PR DESCRIPTION
**Pull request by mwkrentel**

### CODE REVIEW

**Review by alecbcs — APPROVED** [review]
Confirmed SHA. Looks good to me.

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Comment by mwkrentel** [comment]
The pipeline says, "In progress, queued for 21 seconds",
but it's said "21 seconds" for over 3 hours.
I think something is stuck.

**Comment by mwkrentel** [comment]
@spackbot restart pipeline

**Comment by mwkrentel** [comment]
@spackbot re-run pipeline

**Pull request merged**
