### PR TITLE
update vtk-h release

### PR DESCRIPTION
**Pull request by mclarsen**
Adds bug fixes for cmake FindMPI problems and algorithms.

### CODE REVIEW

**Comment by mclarsen** [comment]
@eugeneswalker as requested.

**Review by eugeneswalker — APPROVED** [review]
Thanks for doing this!

**Comment by eugeneswalker** [comment]
Should it be okay to build Ascent with this new version, `vtk-h@0.6.2` ?

**Comment by mclarsen** [comment]
Yes, ascent@develop will build with this and should automatically use v0.6.2. The same cmake fix is merged into ascent@develop.

**Pull request merged**
