### PR TITLE
adios2: add v2.9.2 release

### PR DESCRIPTION
**Pull request by vicentebolea**
:tada: :tada: :tada: 

Finally! ADIOS2 v2.9.2 patch release is out.

This bring exiting new features and bugfixes. Find the release notes at:
https://github.com/ornladios/ADIOS2/releases/tag/v2.9.2

Let me know if we need to change anything else in the package

ViB

:tada: :tada: :tada:

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new version's sha256.  

Is there a reason for dropping `2.9.1`?  Would it be more appropriate to deprecate it (https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions)?

**Comment by vicentebolea** [comment]
> Is there a reason for dropping 2.9.1? Would it be more appropriate to deprecate it (https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions)?

That makes sense, find the changed pushed

**Comment by tldahlgren** [comment]
> > Is there a reason for dropping 2.9.1? Would it be more appropriate to deprecate it (https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions)?
> 
> That makes sense, find the changed pushed

Did you want to also deprecate all of the listed versions prior to `2.9.1`?

**Comment by vicentebolea** [comment]
Actually nevermind @tldahlgren, there is no reason to deprecate/remove older patch releases.

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by tldahlgren** [comment]
Shall I merge or wait for @ax3l and or @williamfgc to comment?

**Comment by vicentebolea** [comment]
@tldahlgren I think that if this pass CI is good to merge.

**Comment by williamfgc** [comment]
LGTM

**Review by tldahlgren — DISMISSED** [review]

**Comment by vicentebolea** [comment]
@tldahlgren I just rebased to get rid of some errors in older develop in the Gitlab CI. Can you re-review :angel: ?

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
