### PR TITLE
add mvapich support for intel scalapack_libs

### PR DESCRIPTION
**Pull request by khsa1**
The correct scalapack libs are set for `mvapich2` with Intel but mvapich@3.0 uses `mvapich`, not `mvapich2`.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
LGTM. Waiting for @rscohn2 to comment. Do we need to change anything in OneAPI packages, along the same lines?

**Comment by khsa1** [comment]
I ran into this issue while building `cp2k` with `oneapi`. I'm not sure what the interaction is between the intel and oneapi build systems. Maybe someone on the spack team can provide more insight?

**Comment by rscohn2** [comment]
> I ran into this issue while building `cp2k` with `oneapi`. I'm not sure what the interaction is between the intel and oneapi build systems. Maybe someone on the spack team can provide more insight?

oneapi has a separate build system and the equivalent logic is in the `intel-oneapi-mkl` package: https://github.com/spack/spack/blob/b33e2d09d352ef2f7c1db2f856e18fa8bd0630df/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py#L223

It tries to guess based on package name, and also has mpi_family variant for explicit control if the package is not recognized. We are missing `mvapich` and `mvapich2`. Could you add them?

**Comment by khsa1** [comment]
Sure, just pushed that

**Review by rscohn2 — APPROVED** [review]
Thanks!

**Pull request merged**
