### PR TITLE
omega-h: add variants gmsh and kokkos

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by cwsmith — APPROVED** [review]
LGTM

**Comment by tristan0x** [comment]
Hello @cwsmith
Thank you for the review. Is there something I can do to move this contribution forward?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@tristan0x Please read this: https://github.com/spack/spack-infrastructure/blob/main/docs/deferred_pipelines.md Here we are waiting for Gitlab pipelines to run, so I'm sorry to say that the more you merge develop into the PR, the longer it may potentially take :worried: [^1]

[^1]: I think this is one of those cases where the software being updated is not yet in our pipelines. We are working on optimizing this use case, but as of now our CI will realize this only after concretization is run in Gitlab.

**Comment by tristan0x** [comment]
> @tristan0x Please read this: https://github.com/spack/spack-infrastructure/blob/main/docs/deferred_pipelines.md Here we are waiting for Gitlab pipelines to run, so I'm sorry to say that the more you merge develop into the PR, the longer it may potentially take 😟 [1](#user-content-fn-1-93c213bc146c14c4a4ff8c5c1876f955)

Thank you very much for your kind and instructive message even though I am slowing down the build...
Maybe spackbot-app can send a message upon PR creation to educate newbies like me.
Cheers

**Comment by alalazo** [comment]
> Maybe spackbot-app can send a message upon PR creation to educate newbies like me.

That would not be a bad idea actually, pinging @tgamblin @scottwittenburg

**Pull request merged**
