### PR TITLE
Update darshan package with mpi variant

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you negate the logic so that the variant is called `+mpi` and is enabled by default? That will be more in-line with other Spack packages.

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Comment by adamjstewart** [comment]
@gartung you might want to ping the package maintainers to make sure they are okay with this change: @shanedsnyder @carns

**Comment by shanedsnyder** [comment]
All looks good to me, including the change to 'mpi' variant with default of True. Thanks @gartung!

**Comment by carns** [comment]
Yep, what @shanedsnyder said :)

**Pull request merged**
