### PR TITLE
dav sdk ci: use 2023-01-01 runner images

### PR DESCRIPTION
**Pull request by eugeneswalker**
Use newer runner image `2023-01-01`

CC @wspear @kwryankrattiger

### CODE REVIEW

**Review by kwryankrattiger — DISMISSED** [review]
Thanks!

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Review by kwryankrattiger — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by scottwittenburg** [comment]
This needs a newer `develop` parent in the merge commit tested by gitlab, to fix the tagging problem it just ran into, where specs need `x86_64_v3`, but concretization job is tagged `x86_64`.  That was fixed in #34789.

Since spackbot doesn't make merge commits or push any branches to gitlab, the way to do this is just to rebase on a newer `develop` and force-push.  To avoid having any extra waiting, you could rebase this on [f4dac7cd](https://gitlab.spack.io/spack/spack/-/commit/f4dac7cd4c727afafb9959fca1fa6627de36db7f), a commit for which the pipeline has already finished.

**Comment by eugeneswalker** [comment]
> you could rebase this on [f4dac7cd](https://gitlab.spack.io/spack/spack/-/commit/f4dac7cd4c727afafb9959fca1fa6627de36db7f), a commit for which the pipeline has already finished.

Done! Thank you for the notice and the tip on what commit to use!

**Pull request closed without merging**
