### PR TITLE
PMIX: add current 4.2.x releases

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Comment by hppritcha** [comment]
It would be nice to get this PR merged in soon.  We discovered an issue in the openmpi spackage that can't be fixed till spack "learns" about these releases.

**Comment by rhc54** [comment]
Do you want to add the v4.2.4rc in there as well? It is what is inside OMPI v5 at the moment.

**Comment by hppritcha** [comment]
no i'd rather keep it simple and just include release tarballs.

**Review by rhc54 — APPROVED** [review]
Sounds good!

**Review by tldahlgren — APPROVED** [review]
Confirmed the three version sha256.

**Pull request merged**
