### PR TITLE
kokkos, kokkos-kernels, kokkos-nvcc-wrapper: add v4.4.01

### PR DESCRIPTION
**Pull request by balay**
And:

trilinos: update @[master,develop] dependency on kokkos

```
==> Error: InstallError: For Trilinos@[master,develop], ^kokkos version in spec must match version in Trilinos source code. Specify ^kokkos@4.4.01 for trilinos@[master,develop] instead of ^kokkos@4.4.00.
```

### CODE REVIEW

**Review by psakievich — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
FWIW. Confirmed the new sha256s.

**Comment by tldahlgren** [comment]
@psakievich Is it safe to assume the reason this is't merged is it's waiting on feedback from one or more of the maintainers (@srajama1 @lucbv @brian-kelley @Rombur @nmm0 @cedricchevalier19 )?

**Comment by cedricchevalier19** [comment]
We haven't been invited to review by the bot. I will try to add us manually in order to be able to do the review.

**Comment by psakievich** [comment]
@tldahlgren sorry I could have merged. I checked the sha's as well, but I've never done it formally on a review before.

**Review by cedricchevalier19 — APPROVED** [review]
For Kokkos, Spack selects the tarball  to be the github created one and not the official https://github.com/kokkos/kokkos/releases/download/4.4.01/kokkos-4.4.01.tar.g, which has a different checksum.

Is it better to fix this in a separate PR?

**Comment by psakievich** [comment]
@cedricchevalier19 yes I think separate PR if we need to redo all of them.

**Comment by psakievich** [comment]
I'll merge this one and then we can open a second one.

**Comment by tldahlgren** [comment]
> @tldahlgren sorry I could have merged. I checked the sha's as well, but I've never done it formally on a review before.

No worries.  I didn't want to "step on your toes" with the PR.  Plus I'm trying to make it a habit to ping maintainers before I merge even basic PRs.

**Pull request merged**
