### PR TITLE
add conduit 0.8.5 release and caliper variant

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@cyrush Can you please rebase to re-trigger a pipelines run? I'd do it myself, but it is currently not possible to do so if the PR comes from an organization.

**Comment by cyrush** [comment]
@alalazo I merged with latest which re-triggered

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by cyrush** [comment]
thanks all!

**Pull request merged**
