### PR TITLE
Add build editions for catalyst builds.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@chuckatkins Please review. This is for an ECP milestone.
Run with:
spack install -j40 paraview+python3^llvm@11.1.0^doxygen@1.8.20

**Comment by danlipsa** [comment]
@chuckatkins ping. Can we merge this?

**Comment by danlipsa** [comment]
@chuckatkins Can you take a look now. Build editions are only added for 5.8 and higher.

**Comment by danlipsa** [comment]
@chuckatkins @vicentebolea Please review.

**Review by chuckatkins — APPROVED** [review]

**Comment by dylex** [comment]
This seems to break paraview.  The build succeeds but does not produce a paraview binary.  I think this is because the cmake rules (for paraview 2.9.1 anyway) compare `PARAVIEW_BUILD_EDITION` to `CANONICAL` (uppercase) while spack is setting to lower case, and as a result, no features are enabled.

**Pull request merged**
