### PR TITLE
cuda: Add 12.4.1

### PR DESCRIPTION
**Pull request by pauleonix**
`cuda` package:
- Add newest patch version

CUDA build system:
- Add gcc/clang conflicts for `cuda@12.4` which were missed in #42748
- Fix/relax existing clang conflict which was too strict from #41304

`ginkgo` package:
- Change conflict introduced in #42748 from `cuda@12.4.0` to `cuda@12.4` as the necessary fix wasn't included in `cuda@12.4.1`. (Ginkgo is also preparing a workaround in https://github.com/ginkgo-project/ginkgo/pull/1569, but it isn't merged/released at the time of writing)

### CODE REVIEW

**Comment by pauleonix** [comment]
For the conflict change in the CUDA build system see [CUDA 12.1 requirements](https://docs.nvidia.com/cuda/archive/12.1.0/cuda-installation-guide-linux/index.html#system-requirements) and [CUDA 12.3 requirements](https://docs.nvidia.com/cuda/archive/12.3.0/cuda-installation-guide-linux/index.html#host-compiler-support-policy)

**Comment by pauleonix** [comment]
CUDA 12.4.0 [officially supports](https://docs.nvidia.com/cuda/archive/12.4.0/cuda-installation-guide-linux/index.html#host-compiler-support-policy) gcc 13, **but** the CUDA 12.4.1 [patchnotes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id3) say:
> #### Resolved Issues
> - If nvcc uses gcc 13 host compiler and some versions of GLIBC, such as GLIBC 2.35, nvcc would report `error: invalid combination of type specifiers` for `_FloatN`. This has been fixed in CUDA 12.4 Update 1.
 > - Nvcc failed to compile `immintrin.h` for gcc 13 host compiler with `-O2` option due to missing `__builtin_ia32_cmpccxadd[64]` support. This has been fixed in CUDA 12.4 Update 1.

So maybe `cuda@12.4.0` should still conflict with `gcc@13` to avoid these issues?

**Comment by pauleonix** [comment]
@spackbot re-run pipeline

**Review by tcojean — APPROVED** [review]
LGTM for Ginkgo

**Comment by alalazo** [comment]
@ax3l @Rombur

**Review by Rombur — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
Failures in pipelines are unrelated (pod not starting...)

**Comment by zzzoom** [comment]
This should be good to go, right?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
