### PR TITLE
PLUMED: Using a C compiler variable

### PR DESCRIPTION
**Pull request by etiennemlb**
During the cython build step, we want to give python's setup tool which c compiler it should sue. Currently it falls out of confinement (does not use the spack wrappers) because we give it a cpp compiler instead. 

For fear of breaking stuff I just added the CC variable but I think what was meant initially was only `CC=.. LDSHARED=`.

@marcodelapierre

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Thanks for opening this PR @etiennemlb !

Because I don't know much about the Plumed - Python interface, I would like to get @gtribello and @RemiLacroix-IDRIS views on this one.  

In particular: shall we also update `LDSHARED` to point to `spack_cc`, or shall we leave it to `spack_cxx`?

Thank you in advance folks.

**Comment by etiennemlb** [comment]
LDSHARED should also, for homogeneity/correctness(?)'s sake, be `spack_cc` but as it is used for the link step (if used at all in our case) then a C or C++ compiler driver may not change much. I'm in favor of changing it too if no one sees an issue with that.

**Comment by RemiLacroix-IDRIS** [comment]
I would change it too but I think it would make sense that `LDCXXSHARED` uses  `spack_cxx` since it's meant for linking C++ code.

**Comment by marcodelapierre** [comment]
Looks good to me, however I see the ci/gitlab-ci pipeline is failing amongs the checks

**Comment by etiennemlb** [comment]
This is weird. the failure appears in the configure not during the part we modified. It seems we are experiencing the same issue as: https://github.com/spack/spack/pull/46094. The config.log shows a link error at the very start of the configure:

```
configure:4115: /opt/cray/pe/mpich/8.1.25/ofi/cray/10.0/bin/mpicxx -O3  -L/home/gitlab-runner-2/builds/EdVvum-Bg/0/spack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__sp/linux-rhel8-zen4/cce-15.0.1/gsl-2.7.1-oaynqd75f7c6auvog6hckmrneufzms7n/lib -L/opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/lib -lgsl -lsci_cray_mpi -lsci_cray conftest.cpp  >&5
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlclose
>>> referenced by /opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/lib/libsci_cray.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlopen
>>> referenced by /opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/lib/libsci_cray.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: dlsym
>>> referenced by /opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/lib/libsci_cray.so
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4119: $? = 1
configure:4160: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "PLUMED"
| #define PACKAGE_TARNAME "plumed"
| #define PACKAGE_VERSION "2"
| #define PACKAGE_STRING "PLUMED 2"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
```
From: https://gitlab.spack.io/spack/spack/-/jobs/12369696/artifacts/browse/jobs_scratch_dir/logs/

**Comment by marcodelapierre** [comment]
I see, thanks for pointing to that issue @etiennemlb . 
Having a full look at the CI pipelines, I think we can go ahead, the failure is related to the Cray setup of that specific CI pipeline, not to this CR.

**Review by marcodelapierre — APPROVED** [review]
Good to go, after the additional changes were implemented

**Review by marcodelapierre — APPROVED** [review]
Good to go, after the additional changes were implemented

**Comment by marcodelapierre** [comment]
@eugeneswalker  pinging you as I see you had worked on #46094  . 

I think this current PR can be merged, the CI failure stems from a Cray pipeline specific failure, see linked PR above. However, I have no privileges to go ahead myself.  Do you?  Or otherwise whom shall I ping?  

Thank you

**Review by eugeneswalker — APPROVED** [review]
Thanks!

**Comment by eugeneswalker** [comment]
The cray failure can be ignored, yes. We recently updated ci to allow that pipeline to fail without blocking merge— but these changes are in develop. I updated this branch now so we should be set once the CI re-runs!

**Pull request merged**
