### PR TITLE
dealii:: add support for 9.5.0

### PR DESCRIPTION
**Pull request by masterleinad**
Part of https://github.com/dealii/dealii/issues/15383.

### CODE REVIEW

**Comment by luca-heltai** [comment]
@masterleinad I will include your changes on Kokkos in #38802.

I think we should also enforce that Kokkos is compiled with cuda if deal.ii has cuda enabled.

**Comment by masterleinad** [comment]
> I think we should also enforce that Kokkos is compiled with cuda if deal.ii has cuda enabled.

Yes, I agree.

**Comment by luca-heltai** [comment]
Did we ever solve this issue?

```
# TODO: temporary disable Tpetra when using CUDA due to
    # namespace "Kokkos::Impl" has no member "cuda_abort"
    depends_on(
        "trilinos@master+rol~amesos2~ifpack2~intrepid2~kokkos~tpetra~zoltan2",
        when="+trilinos+cuda",
    )
```

I.e., can we have external kokkos+external trilinos both with cuda?

**Comment by masterleinad** [comment]
> I.e., can we have external kokkos+external trilinos both with cuda?

Yes, AFAIK that works.

**Comment by luca-heltai** [comment]
The only problem I see, is that trilinos (in spack) does not seem to use external kokkos. This compilcates things a bit. I'm not sure how to tell trilinos to use kokkos compiled externally (without editing trilinos package definition, that is...).

**Comment by masterleinad** [comment]
> The only problem I see, is that trilinos (in spack) does not seem to use external kokkos. This compilcates things a bit. I'm not sure how to tell trilinos to use kokkos compiled externally (without editing trilinos package definition, that is...).

Oh, using `Trilinos` with an external `Kokkos` installation is a very new feature anyway. I meant to say that using `Trilinos+Cuda` with `deal.II+Cuda` should work using the `Kokkos` installation bundled with `Trilinos`.

**Comment by luca-heltai** [comment]
So, can I remove this check, for recent versions of Trilinos? 
```
# TODO: temporary disable Tpetra when using CUDA due to
    # namespace "Kokkos::Impl" has no member "cuda_abort"
    depends_on(
        "trilinos@master+rol~amesos2~ifpack2~intrepid2~kokkos~tpetra~zoltan2",
        when="+trilinos+cuda",
    )
```
This disables kokkkos in trilinos when we ask for cuda support + trilinos.

**Comment by masterleinad** [comment]
> So, can I remove this check, for recent versions of Trilinos?

Yes. I would expect it to work for older `Trilinos` versions (and `deal.II` 9.5.0), too.

**Pull request closed without merging**
