### PR TITLE
scons: add a new version

### PR DESCRIPTION
**Pull request by hyoklee**
This will help https://github.com/spack/spack/pull/35649

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256.

**Review by adamjstewart — COMMENTED** [review]
The base class adds python as a build/run dep, but the package adds it as a build/link dep. Does the package actually link to python's libs/headers? If not I would remove the python dep since it's already added by the base class and Spack only supports 3.7+ anyway

**Comment by hyoklee** [comment]
> 

@adamjstewart , would you please ping the original author of this package?
 If no one maintains it, I can try removing Python dependency but 
I want to defer to someone who wrote this package first.

**Comment by adamjstewart** [comment]
I'm pretty sure I'm the one who wrote it. I just checked and it doesn't link to python, so you can simply remove the dep and use the one inherited from the base class.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
