### PR TITLE
root: new version 6.26.04

### PR DESCRIPTION
**Pull request by wdconinc**
New bugfix release, release notes: https://root.cern/doc/v626/release-notes.html#release-6.2604

Maintainers: @HadrienG2  @chissg  @drbenmorgan  @vvolkl

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Deferring merge decision until at least one maintainer has a chance to comment.

**Comment by tldahlgren** [comment]
Warning: I just updated through GitHub app to see if that will resolve the odd style issue.

**Comment by tldahlgren** [comment]
Oops.  Merged before giving time for maintainers.  Please let me know if you want me to revert the change..

**Comment by HadrienG2** [comment]
It's okay, I just cross-checked the release notes and aside from a GCC12 build bugfix for a specific variant, there is nothing visible from a build system side.

**Pull request merged**
