### PR TITLE
rocfft test require rocm-openmp-extras instead llvm-amdgpu +opemnp

### PR DESCRIPTION
**Pull request by renjithravindrankannath**
test depends on llvm-amdgpu +openmp which is failing.
It can depend on rocm-openmp-extras with the latest changes.

### CODE REVIEW

**Comment by cgmb** [comment]
There are three packages that depend on `llvm-amdgpu +openmp`.
```
var/spack/repos/builtin/packages/rocblas/package.py:    depends_on('llvm-amdgpu +openmp', type='test')
var/spack/repos/builtin/packages/rocfft/package.py:    depends_on('llvm-amdgpu +openmp', type='test')
var/spack/repos/builtin/packages/rocm-tensile/package.py:        depends_on('llvm-amdgpu@' + ver,               when='@' + ver + '+openmp')
```

Can we not just fix `llvm-amdgpu +openmp`? I mean, the option exists... shouldn't it work?

**Comment by cgmb** [comment]
I applied this patch on 31c24cd0d543f3bc06311fe148751fe88a11ecbb and installed it on a clean Ubuntu 20.04 docker image. When I tried `spack install --test root rocfft amdgpu_target=gfx1011`, it failed with an error:
```
/tmp/ubuntu/spack-stage/spack-stage-rocfft-5.2.0-jcvrmggxdttn3lrqvte7c2ndzey63l5n/spack-src/clients/tests/../fft_params.h:29:10: fatal err 
            or: 'omp.h' file not found
```
I assume that this built correctly for you, so perhaps rocfft found a copy of OpenMP in your system environment?

**Comment by cgmb** [comment]
I think the cause of the failure is that openmp-extras from apt installs omp.h to

    /opt/rocm-5.2.0/llvm/lib/clang/14.0.0/include/omp.h

while spack installs omp.h to

    spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/rocm-openmp-extras-5.2.0-pjj4szpyeb47vvcdvzmlt5eeb5jdqnfl/include/omp.h

It seems that rocFFT assumes that omp.h will be in the clang include directory. I suppose I'll see if using `find_package(OpenMP)` can fix this problem

**Comment by renjithravindrankannath** [comment]
Closing this PR since rocm-openmp-extras will be included in [32250](https://github.com/spack/spack/pull/32250)

**Pull request closed without merging**
