### PR TITLE
singularity: new variants to enable non-suid and non-network builds

### PR DESCRIPTION
**Pull request by aweits**
...but leave the defaults as they are currently.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@ArangoGutierrez @alalazo

**Comment by hartzell** [comment]
How does the suid change interact with the helpful message that the package prints out (haven't tried it lately...) about setting the ownership and setuid bits on a couple of things, e.g. [these lines](https://github.com/spack/spack/blob/e476a9061b2d712361a8551e72100b89548595cc/var/spack/repos/builtin/packages/singularity/package.py#L108-L159)?

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you address @hartzell comment? When `singularity~suid` is installed the file `libexec/singularity/bin/starter-suid` is not built.

**Comment by hartzell** [comment]
Looks like the helper bits have been handled.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
