### PR TITLE
ParaView: add latest release v5.11.0-RC1

### PR DESCRIPTION
**Pull request by vicentebolea**
:tada: :tada: :tada:

Finally! ParaView 5.11.0-RC1 is out

This PR updates the ParaView Spack package to use this new release while keeping its last final release ParaView v5.10.1 as the preferred version.

Let me know if we need to change anything else in the package.

:tada: :tada: :tada:

### CODE REVIEW

**Comment by cquammen** [comment]
@vicentebolea some style CI is failing

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256 and noted preferred version is (still) stable.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Given the comment, I will defer the merge to give the other maintainers a chance to comment.

**Comment by EthanS94** [comment]
@vicentebolea I think `nlohmann-json` may need to be a dependency when `@5.11:`. I got an error when building with this PR:

```
  >> 187    CMake Error at VTK/CMake/vtkModule.cmake:4579 (message):
     188      Could not find the nlohmann_json external dependency.
     189    Call Stack (most recent call first):
     190      VTK/CMake/vtkModule.cmake:5173 (vtk_module_find_package)
     191      VTK/CMake/vtkModule.cmake:5044 (vtk_module_third_party_external)
     192      VTK/ThirdParty/nlohmannjson/CMakeLists.txt:1 (vtk_module_third_pa
            rty)
```

**Comment by EthanS94** [comment]
@vicentebolea Same with the `proj` dependency

**Comment by vicentebolea** [comment]
@EthanS94 thanks for pointing it out, find it resolved in the last push. I succesfully tested it locally

**Comment by EthanS94** [comment]
@vicentebolea Just thought of one more thing. I haven't tested it, but I think [this line](https://github.com/spack/spack/blob/fb0f389d998ef6de9f13704640fafe69c10009e8/var/spack/repos/builtin/packages/paraview/package.py#L281) needs to be changed to `5.11`

**Comment by vicentebolea** [comment]
@EthanS94 thanks for pointing it out. Find the change in the last push

**Review by alalazo — APPROVED** [review]

**Pull request merged**
