### PR TITLE
MFEM version 3.1

### PR DESCRIPTION
**Pull request by goxberry**
MFEM is a free, lightweight, scalable C++ library for finite element
methods.

### CODE REVIEW

**Comment by goxberry** [comment]
FWIW, I intend to add more variants (`hypre`, `suitesparse`, `metis`, and `mpi`) are all things I will eventually need. My impression was that there were some issues in building the latest hypre on OS X, so my first thought was to try and land this PR while continuing to do work on mfem packaging in parallel.

**Comment by goxberry** [comment]
Actually, `hypre` seems to build fine, so let's make this WIP, and I'll comment when it's ready to merge.

**Comment by goxberry** [comment]
Stuck on the `metis` variant right now. The PR is ready to merge as is. I can add a `metis` variant based on METIS 4 if PR #750 lands. If the CMake build error I see in #620 is resolved, I can try again with what I have for METIS 5, but for now, installing METIS 5 hangs when I try to build CMake 3.5.1.

If the `metis` variant issues are resolved, the next step after that would be a parallel build, i.e., an `mpi` variant.

**Comment by tgamblin** [comment]
Does `spack install mfem %gcc ^cmake %clang` work?  If so do you want me to wait for your metis 4 fix or just merge this?

**Comment by goxberry** [comment]
`spack install metis@5: %gcc ^cmake %clang` works, which is what I was getting hung up on. I'll get back to `metis` variants.

**Comment by goxberry** [comment]
@tgamblin `spack install mfem ^cmake %clang` does not work; I get

```
narella:spack oxberry1$ bin/spack install --verbose mfem+metis ^cmake %clang
==> Error: mfem does not depend on cmake
```

which is true; `mfem` does not depend on cmake, but `metis` does. I think I can hack around this in the short term by adding `depends_on(`cmake', when='+metis@5:')`. Longer-term, the `cmake` dependency is going to look odd, in that MFEM doesn't depend on CMake directly; METIS 5 depends on CMake, and MFEM depends on METIS version greater than or equal to 4.

**Comment by goxberry** [comment]
@tgamblin I think this commit is ready for review; there is probably a better way to handle forcing cmake to compile with clang than explicitly including it as a dependency.

**Comment by tzanio** [comment]
It might be useful to also look at the following version, that @markcmiller86 wrote last year: https://github.com/markcmiller86/spack/blob/master/var/spack/packages/mfem/package.py

**Comment by goxberry** [comment]
Added hack around the URL redirect; this hack should enable adding other versions, too.

**Comment by goxberry** [comment]
Added a debug flag from @markcmiller86's version.

**Comment by goxberry** [comment]
@tgamblin Any suggestions on what might help get this PR merge-ready?

**Comment by tgamblin** [comment]
@goxberry sorry for the delay -- been catching up after getting back from SIAM.  Looks good to me.  I think I can also make this way more convenient -- it used to work in Spack but the mirror logic has started assuming an extension from the URL rather than from the downloaded file.

**Pull request merged**
