### PR TITLE
acts dependencies: new versions as of 2024/12/02

### PR DESCRIPTION
**Pull request by stephenswat**
This commit adds a new version of detray and two new versions of vecmem.

### CODE REVIEW

**Review by wdconinc — DISMISSED** [review]
Checksums verified.

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by stephenswat** [comment]
Hi @wdconinc, I have decided to add my weekly ACTS update commit to this PR for the sake of simplicity; let's see what the CI says as it seems to have been having some issues.

**Review by wdconinc — APPROVED** [review]
Additional commit sha and checksum verified.

**Pull request merged**
