### PR TITLE
perl: add 5.38.0, 5.36.1; prefer all even minor versions over development versions

### PR DESCRIPTION
**Pull request by haampie**
Add latest Perl releases.

Prefer all even versions, so that all development versions are pessimized.

### CODE REVIEW

**Comment by alecbcs** [comment]
Similar to `url_for_version()` perhaps we should consider making a `preference_for_version()` function that'd allow us to algorithmically set the preferred versions of a package without having to directly set each and every production version as preferred. (And thus taking up multiple lines per version.)

**Comment by haampie** [comment]
Or maybe a custom comparator would help :upside_down_face: `def version_is_less(x, y)`.

But I don't think we have many cases like Perl to make it worthwhile.

**Review by alecbcs — APPROVED** [review]
That's probably true. Anyway SHAs confirmed. This all looks good to me.

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
It needs #38710

**Pull request merged**
