### PR TITLE
openssh: New version 9.1p1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to give @bernhardkaindl a chance to comment.

**Comment by eschnett** [comment]
@spackbot run pipeline

**Review by bernhardkaindl — APPROVED** [review]

**Comment by eschnett** [comment]
https://github.com/AMReX-Codes/amrex/issues/3009

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by scottwittenburg** [comment]
Looks like this needs [b55509f](https://github.com/spack/spack/commit/b55509ffa89f847df3c24ff2a90ce8a11d154a96), which should fix errors with not being able to install dependencies from binary when `--cache-only` was specified.

**Pull request merged**
