### PR TITLE
sqlite: add NMake build system support

### PR DESCRIPTION
**Pull request by johnwparent**
Closes #41824

resubmission of #41761 with #41824 included

### CODE REVIEW

**Comment by johnwparent** [comment]
@spackbot run pipeline

**Comment by johnwparent** [comment]
Gitlab pipeline failure wholly unrelated to these changes (`glew` failed to fetch). Re-running pipeline.

**Comment by scheibelp** [comment]
@spackbot run pipeline

**Comment by scheibelp** [comment]
@spackbot run pipeline

**Review by scheibelp — APPROVED** [review]

**Pull request merged**
