### PR TITLE
nalu-wind: add +cuda variant

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add new variant: `nalu-wind+cuda`

Incorporates modifications from `exawind/exawind-builder` custom Spack repo.
https://github.com/Exawind/exawind-builder/blob/main/etc/repos/exawind/packages/nalu-wind/package.py

@jrood-nrel @sayerhs

### CODE REVIEW

**Review by jrood-nrel — APPROVED** [review]
This looks good to me. @psakievich does this look fine to you?

**Comment by psakievich** [comment]
@eugeneswalker have you tested this with cuda and were able to run?  I put together something similar [here](https://github.com/psakievich/spack-manager/blob/1a506ec696cb047bc6f2e5b998df5d2ebcfa1512/repos/exawind/packages/nalu-wind/package.py#L7) but I also added some cxx flag injections and environment stuff which I thought was required to get kokkos to work properly with Cuda. Most of this I just shamelessly copied from the `trilinos` package.

I haven't been following the kokkos/trilinos stuff as much lately so perhaps those are no longer needed?

**Comment by eugeneswalker** [comment]
> @eugeneswalker have you tested this with cuda and were able to run?

I used this to build on Summit for the V100 and on one of my local broadwell machines with a GV100. To test the build I ran the `ablNeutralNGPTrilinos` regression test and evaluated the output using the `pass_fail.py` script. In both cases, `pass_fail.py` reported a PASS.

This was the spec I was building:
`nalu-wind+fftw+hypre~openfast~tioga~wind-utils~shared+cuda cuda_arch=70 ^cuda@10.2.89`

**Review by sayerhs — APPROVED** [review]

**Comment by sayerhs** [comment]
@psakievich you don't need to set those environment variables. Those should be handled automatically by the Kokkos nvcc-wrapper dependency.

**Comment by psakievich** [comment]
Okay looks good to me. Thanks for clarifying!

**Review by psakievich — APPROVED** [review]

**Comment by psakievich** [comment]
@sayerhs thats what I thought. I recall having trouble with it at the time but that was right around the time the current cuda variant was getting put into the trilinos package and there were a couple pr's trying to do it at once. so it could be unrelated errors. Either way glad to have this in the main repo so I can clean up my dev packages.

**Review by becker33 — APPROVED** [review]

**Pull request merged**
