### PR TITLE
readline: New version 8.1.2

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by michaelkuhn — DISMISSED** [review]
WFM

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
The CI pipeline reports errors such as
```
==> [2022-06-09-02:43:48.048825] SpackWebError: Download failed: <urlopen error An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.>
```
(see https://gitlab.spack.io/spack/spack/-/jobs/2671909/raw).

This looks ephemeral, so I am restarting the CI pipeline. But I've seen this error several times by now.

**Comment by eschnett** [comment]
The error persists. It seems that a binary cache for cmake cannot be downloaded.

**Comment by eschnett** [comment]
@michaelkuhn do you know what might cause this error? restarting the pipeline doesn't seem to help.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@alalazo Same error, again...

**Comment by eschnett** [comment]
@alalazo @michaelkuhn It seems this error is related to downloading (from a cache?) some binaries for the `aarch64` architecture. Who could help with this?

**Comment by alalazo** [comment]
@scottwittenburg or @zackgalbreath

**Comment by alalazo** [comment]
I'm trying to reproduce an error from the failing pipeline locally:
```console
$ spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/2682440/artifacts [--working-dir <dir>]
```
Will report here on the outcome. Note that the instructions need not to be followed verbatim, otherwise it's likely that you'll be running an `aarch64` build on a `x86_64` architecture. I am currently giving the `--platform=arm64` option to `docker run` and setting `SPACK_ROOT` manually within the container.

**Comment by alalazo** [comment]
@eschnett I could reproduce locally the error in the pipeline above:
```
[ ... ]
==> [2022-06-16-09:14:19.907777] 'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/home/software/spack/[padded-to-384-chars]/morepadding/linux-amzn2-aarch64/gcc-7.3.1/netlib-scalapack-2.2.0-g734laidge7v233jlkv2xq2qhia6y3gj' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/home/software/spack/[padded-to-384-chars]/morepadding/linux-amzn2-aarch64/gcc-7.3.1/netlib-scalapack-2.2.0-g734laidge7v233jlkv2xq2qhia6y3gj/lib;/home/software/spack/[padded-to-487-chars]/morepadding/linux-amzn2-aarch64/gcc-7.3.1/netlib-scalapack-2.2.0-g734laidge7v233jlkv2xq2qhia6y3gj/lib64;/home/software/spack/[padded-to-489-chars]/linux-amzn2-aarch64/gcc-7.3.1/openblas-0.3.10-7hbaun357liy6mqg5ep7u67ve3bqso6t/lib;/home/software/spack/[padded-to-468-chars]/linux-amzn2-aarch64/gcc-7.3.1/openmpi-4.1.4-rb4pstxmumbxv5jkl2rdwoniylknnecr/lib;/home/software/spack/[padded-to-466-chars]/linux-amzn2-aarch64/gcc-7.3.1/hwloc-2.7.1-zjykuhom22w4ot6vbgmnfqux5icn5xav/lib;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/libpciaccess-0.16-rlxjfd4ez3nr7bp5oh4vur2m33t2ykfn/lib;/home/software/spack/[padded-to-470-chars]/linux-amzn2-aarch64/gcc-7.3.1/libxml2-2.9.13-tx26yhlnlt7ev2ym64oxvshrx7nt2zpp/lib;/home/software/spack/[padded-to-467-chars]/linux-amzn2-aarch64/gcc-7.3.1/libiconv-1.16-nlz2at3uavndpsw7yzxydw5mju5tx6xw/lib;/home/software/spack/[padded-to-466-chars]/linux-amzn2-aarch64/gcc-7.3.1/xz-5.2.5-ao33z7ylmuecbv3oxzhcqlykrsqh7p7g/lib;/home/software/spack/[padded-to-461-chars]/linux-amzn2-aarch64/gcc-7.3.1/zlib-1.2.12-con4lu7s2tmys5gqwetz6grur7klart7/lib;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/ncurses-6.2-rirdnttzjtk6u6xacdbnbyla3m5x63va/lib;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/libfabric-1.14.1-pzjescfsfqedyzigqxzbyrkxxlltoem2/lib;/home/software/spack/[padded-to-469-chars]/linux-amzn2-aarch64/gcc-7.3.1/rdma-core-39.1-2oktlbd5rphk5zyjspfmhhcsdmzrazpe/lib;/home/software/spack/[padded-to-467-chars]/linux-amzn2-aarch64/gcc-7.3.1/libnl-3.3.0-yritgyumsvwniblpuuj4zdcsho7ypcds/lib;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/numactl-2.0.14-bw5vbb256brlatoqpnm46mhmwp4bhm2g/lib;/home/software/spack/[padded-to-467-chars]/linux-amzn2-aarch64/gcc-7.3.1/pmix-4.1.2-5e2i2ptmzuqzakug2h6gnyrv57ygsp37/lib;/home/software/spack/[padded-to-463-chars]/linux-amzn2-aarch64/gcc-7.3.1/libevent-2.1.12-6mjyypnmog5veh6soeptxh5t4z2h6ymk/lib;/home/software/spack/[padded-to-468-chars]/linux-amzn2-aarch64/gcc-7.3.1/openssl-1.1.1o-roafzsnoxzb3etetcoxugatoyidrt32z/lib;/home/software/spack/[padded-to-467-chars]/linux-amzn2-aarch64/gcc-7.3.1/rdma-core-39.1-2oktlbd5rphk5zyjspfmhhcsdmzrazpe/lib64' '-DCMAKE_PREFIX_PATH:STRING=/home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/openmpi-4.1.4-rb4pstxmumbxv5jkl2rdwoniylknnecr;/home/software/spack/[padded-to-462-chars]/linux-amzn2-aarch64/gcc-7.3.1/pmix-4.1.2-5e2i2ptmzuqzakug2h6gnyrv57ygsp37;/home/software/spack/[padded-to-459-chars]/linux-amzn2-aarch64/gcc-7.3.1/libevent-2.1.12-6mjyypnmog5veh6soeptxh5t4z2h6ymk;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/numactl-2.0.14-bw5vbb256brlatoqpnm46mhmwp4bhm2g;/home/software/spack/[padded-to-463-chars]/linux-amzn2-aarch64/gcc-7.3.1/libfabric-1.14.1-pzjescfsfqedyzigqxzbyrkxxlltoem2;/home/software/spack/[padded-to-465-chars]/linux-amzn2-aarch64/gcc-7.3.1/rdma-core-39.1-2oktlbd5rphk5zyjspfmhhcsdmzrazpe;/home/software/spack/[padded-to-463-chars]/linux-amzn2-aarch64/gcc-7.3.1/libnl-3.3.0-yritgyumsvwniblpuuj4zdcsho7ypcds;/home/software/spack/[padded-to-460-chars]/linux-amzn2-aarch64/gcc-7.3.1/hwloc-2.7.1-zjykuhom22w4ot6vbgmnfqux5icn5xav;/home/software/spack/[padded-to-460-chars]/linux-amzn2-aarch64/gcc-7.3.1/libxml2-2.9.13-tx26yhlnlt7ev2ym64oxvshrx7nt2zpp;/home/software/spack/[padded-to-463-chars]/linux-amzn2-aarch64/gcc-7.3.1/xz-5.2.5-ao33z7ylmuecbv3oxzhcqlykrsqh7p7g;/home/software/spack/[padded-to-457-chars]/linux-amzn2-aarch64/gcc-7.3.1/libpciaccess-0.16-rlxjfd4ez3nr7bp5oh4vur2m33t2ykfn;/home/software/spack/[padded-to-466-chars]/linux-amzn2-aarch64/gcc-7.3.1/openblas-0.3.10-7hbaun357liy6mqg5ep7u67ve3bqso6t;/home/software/spack/[padded-to-464-chars]/linux-amzn2-aarch64/gcc-7.3.1/cmake-3.23.2-m6fi47othda4637vkzuc5ggogmihpcku;/home/software/spack/[padded-to-461-chars]/linux-amzn2-aarch64/gcc-7.3.1/openssl-1.1.1o-roafzsnoxzb3etetcoxugatoyidrt32z;/home/software/spack/[padded-to-463-chars]/linux-amzn2-aarch64/gcc-7.3.1/zlib-1.2.12-con4lu7s2tmys5gqwetz6grur7klart7;/home/software/spack/[padded-to-460-chars]/linux-amzn2-aarch64/gcc-7.3.1/libiconv-1.16-nlz2at3uavndpsw7yzxydw5mju5tx6xw;/home/software/spack/[padded-to-462-chars]/linux-amzn2-aarch64/gcc-7.3.1/ncurses-6.2-rirdnttzjtk6u6xacdbnbyla3m5x63va' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DBUILD_STATIC_LIBS:BOOL=OFF' '-DLAPACK_FOUND=true' '-DLAPACK_INCLUDE_DIRS=/home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/openblas-0.3.10-7hbaun357liy6mqg5ep7u67ve3bqso6t/include' '-DLAPACK_LIBRARIES=/home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/openblas-0.3.10-7hbaun357liy6mqg5ep7u67ve3bqso6t/lib/libopenblas.so' '-DBLAS_LIBRARIES=/home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/openblas-0.3.10-7hbaun357liy6mqg5ep7u67ve3bqso6t/lib/libopenblas.so' '-DCMAKE_C_FLAGS:STRING=' '/tmp/root/spack-stage/spack-stage-netlib-scalapack-2.2.0-g734laidge7v233jlkv2xq2qhia6y3gj/spack-src'
-- The C compiler identification is GNU 7.3.1
-- The Fortran compiler identification is GNU 7.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /builds/spack/spack/spack/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /builds/spack/spack/spack/lib/spack/env/gcc/gfortran - skipped
-- Checking for module 'mpi-c'
--   No package 'mpi-c' found
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_WORKS) 
-- Checking for module 'mpi-fort'
--   No package 'mpi-fort' found
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_Fortran_FOUND) 
-- Found MPI_LIBRARY : FALSE 
CMake Error at CMakeLists.txt:77 (message):
  --> MPI Library NOT FOUND -- please set MPI_BASE_DIR accordingly --
[ ... ]
```
Not sure if this is tied in any way to the new `readline` version. I suspect it's not, but can you please investigate that? Feel free to ping me if you have issues.

**Comment by alalazo** [comment]
What I can say is that `openmpi` has been extracted:
```console
bash-4.2# ls /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path/linux-amzn2-aarch64/gcc-7.3.1/openmpi-4.1.4-rb4pstxmumbxv5jkl2rdwoniylknnecr/bin/
mpic++	mpicc  mpiCC  mpicxx  mpiexec  mpif77  mpif90  mpifort	mpirun	ompi-clean  ompi_info  ompi-server  opal_wrapper  ortecc  orte-clean  orted  orte-info	orterun  orte-server
bash-4.2# ls /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path/linux-amzn2-aarch64/gcc-7.3.1/openmpi-4.1.4-rb4pstxmumbxv5jkl2rdwoniylknnecr/lib
libmpi.a		 libmpi.so.40.30.4	      libmpi_usempi_ignore_tkr.so.40	   libopen-pal.so	   mpi_ext.mod			     mpi.mod
libmpi_mpifh.a		 libmpi_usempif08.a	      libmpi_usempi_ignore_tkr.so.40.30.0  libopen-pal.so.40	   mpi_f08_callbacks.mod	     openmpi
libmpi_mpifh.so		 libmpi_usempif08.so	      libompitrace.a			   libopen-pal.so.40.30.2  mpi_f08_ext.mod		     pkgconfig
libmpi_mpifh.so.40	 libmpi_usempif08.so.40       libompitrace.so			   libopen-rte.a	   mpi_f08_interfaces_callbacks.mod  pmpi_f08_interfaces.mod
libmpi_mpifh.so.40.30.0  libmpi_usempif08.so.40.30.0  libompitrace.so.40		   libopen-rte.so	   mpi_f08_interfaces.mod
libmpi.so		 libmpi_usempi_ignore_tkr.a   libompitrace.so.40.30.1		   libopen-rte.so.40	   mpi_f08.mod
libmpi.so.40		 libmpi_usempi_ignore_tkr.so  libopen-pal.a			   libopen-rte.so.40.30.2  mpi_f08_types.mod
```

**Comment by eschnett** [comment]
I see that CI won't run for draft PRs. I'm thus marking this again as "ready to merge". Still, DO NOT MERGE, THIS PR IS NOT READY.

**Comment by eschnett** [comment]
@alalazo The current version of this PR installs the (old) readline 8.1, with a modification to the Python script to ensure everything is rebuilt. The pipeline still fails, in essentially the same way.

**Comment by eschnett** [comment]
ping?

**Comment by eschnett** [comment]
@michaelkuhn @alalazo ping

**Comment by alalazo** [comment]
Rebased, let's :crossed_fingers: again. Otherwise we need to take a closer look at the failure.

**Comment by eschnett** [comment]
@alalazo I think we need to take a closer look at the failure.

**Comment by alalazo** [comment]
@spackbot run pipeline 

(This time we got a lot of 500 errors :cry: )

**Comment by eschnett** [comment]
@alalazo I see 404 errors again.

**Comment by alalazo** [comment]
@eschnett Can you restore this PR to its original form, i.e. without the "pointless" commit? I'll try to get back to it asap, and check what is the build error. If you're tired of modifying this PR (which would be completely understandable) I can also do that :slightly_smiling_face:

**Comment by eschnett** [comment]
It's green! Quick, someone please merge this PR...

**Review by michaelkuhn — APPROVED** [review]
The saga comes to an end...

**Comment by alalazo** [comment]
@michaelkuhn Everybody knows that a saga of success has always a sequel :laughing:

**Pull request merged**
