### PR TITLE
LLVM: Revert build_llvm_dylib to llvm_dylib

### PR DESCRIPTION
**Pull request by kwryankrattiger**
@trws

### CODE REVIEW

**Review by trws — DISMISSED** [review]
LGTM

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@kwryankrattiger GitLab CI failed with:
```py
==> Error: trying to set variant "build_llvm_dylib" in package "llvm", but the package has no such variant [happened during concretization of llvm%gcc+all_targets+build_llvm_dylib+clang+compiler-rt~cuda+flang+libcxx+lld+lldb arch=linux-None-x86_64]
```
See `git grep  build_llvm_dylib`:
```yaml 
share/spack/gitlab/cloud_pipelines/stacks/e4s-on-power/spack.yaml:    - llvm +all_targets +clang +compiler-rt +libcxx +lld +lldb +build_llvm_dylib +flang ~cuda
share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml:    - llvm +all_targets +clang +compiler-rt +libcxx +lld +lldb +build_llvm_dylib +flang ~cuda
```
You'd need to update `+build_llvm_dylib` (or remove, I hope you know) in these files too.

**Comment by kwryankrattiger** [comment]
@bernhardkaindl Thanks, I always forget to update those, should be good now.

**Review by bernhardkaindl — APPROVED** [review]
GitLab CI has passed, looks good now.

**Pull request merged**
