### PR TITLE
Changes to AOCC compiler spack recipe to use new compiler download URLs

### LINKED ISSUE #36129: Installation issue:  AOCC@4.0.0 didn't install because of a timeout
### Steps to reproduce the issue

run:
spack install -v aocc@4.0.0 +license-agreed

As a side note, "spack install -v aocc@3.2.0 +license-agreed" worked.

### Error message

==> No binary for aocc-4.0.0-vyyhc5bzoktt64a3nbcwav4id3mpwltz found: installing from source
==> Error: TimeoutError: The read operation timed out

/opt/spack/lib/spack/spack/package_base.py:1445, in do_fetch:
       1442
       1443        self.stage.create()
       1444        err_msg = None if not self.manual_download else self.download_instr
  >>   1445        start_time = time.time()
       1446        self.stage.fetch(mirror_only, err_msg=err_msg)
       1447        self._fetch_time = time.time() - start_time
       1448

### Information on your system

Don't know if there is an NDA on file.

### Additional information

_No response_

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
Fixes #36129 

No code changes, only the URL path for the 4.0.0 and 3.2.0 versions are changed.

### CODE REVIEW

**Comment by amd-toolchain-support** [comment]
Note:

Following old versions of AOCC are dropped in the new recipe.

- 3.1.0
- 3.0.0
- 2.3.0
- 2.2.0

**Review by tldahlgren — COMMENTED** [review]
Confirmed all of the URLs are valid.

We generally discourage removing versions without first deprecating them (see https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions) because someone -- perhaps locally? -- may have them in a build cache.

**Review by tldahlgren — APPROVED** [review]
Confirmed the two sha256.

**Comment by tldahlgren** [comment]
We encourage the use of non-`develop` branches for PRs.  The contribution workflow is described at https://spack.readthedocs.io/en/latest/contribution_guide.html#branching.

**Comment by tldahlgren** [comment]
Is there a reason to drop instead of deprecate the older versions?

**Comment by amd-toolchain-support** [comment]
> Is there a reason to drop instead of deprecate the older versions?
Please note that older versions will be considered if any explicit request comes up.

**Comment by amd-toolchain-support** [comment]
> We encourage the use of non-`develop` branches for PRs. The contribution workflow is described at https://spack.readthedocs.io/en/latest/contribution_guide.html#branching.

Okay we will follow the suggested workflow next time, for now, we would like to request you to consider this an exception and provide your approval

**Comment by amd-toolchain-support** [comment]
We have addressed all the comments to the best of our knowledge, could you please approve this change set to resolve the following reported issue:
https://github.com/spack/spack/issues/36129

**Pull request merged**
