### PR TITLE
py-beautifulsoup4: Added version 4.5.1

### PR DESCRIPTION
**Pull request by cmacmackin**
Added version 4.5.1 of beautifulsoup4. I could not find a permanent link for its tarball on PyPI, so I used the one from the library website instead.

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like it's on PyPi, but only if you include the hash in the URL. We've had a lot of problems with this lately and are still trying to come up with a good permanent solution. @citibeth can point you to a few discussions on this.

**Comment by citibeth** [comment]
Yes, see #2281.  I believe it's ready to go, somebody just has to do it.

**Comment by adamjstewart** [comment]
Basically, I don't think it's enough of a problem to hold up this PR. Once we create a PythonPackage class, we ought to be able to replace the url and url_for_version for most Python packages, including this one.

**Comment by citibeth** [comment]
Aw c**p, I think you're right.  OK, best to leave it at `:3.4` until
someone tries / gets it working on 3.5.

**Comment by citibeth** [comment]
(oops, wrong thread)

**Pull request merged**
