### PR TITLE
protobuf: add new versions

### PR DESCRIPTION
**Pull request by adamjstewart**
Extracted out of #36263

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by hyoklee — DISMISSED** [review]
Thanks for the update!

**Comment by adamjstewart** [comment]
@danlipsa @vicentebolea @kwryankrattiger @jcftang any idea how to resolve the paraview build failures? The latest version of abseil-cpp requires C++14 or newer, so I forced it to use that, but it seems like paraview is still building with older C++? Is there a way to bump that up? I'm surprised it's linking to abseil-cpp at all since it's not listed as a dep.

**Comment by vicentebolea** [comment]
> @danlipsa @vicentebolea @kwryankrattiger @jcftang any idea how to resolve the paraview build failures? The latest version of abseil-cpp requires C++14 or newer, so I forced it to use that, but it seems like paraview is still building with older C++?

It seems that best course of action is to build the paraview pkg with c++14. ParaView does not set the CMAKE_CXX_STANDARD but VTK does it. However the VTK flag VTK_IGNORE_CMAKE_CXX11_CHECKS allows it.

**Comment by adamjstewart** [comment]
Would I just copy the example from `abseil-cpp`? Or would any `paraview` maintainers like to do this themselves? Not sure if `abseil-cpp` should be a direct dependency or if we need to force both to be built with the same standard.

**Comment by vicentebolea** [comment]
My bad, lets do it differently: how about making ParaView to depend on a older Alseil, we do not need it as for now. Paraview/VTK will eventually default to C++14, maybe next release? At that time we can support newwer Alseil

**Comment by adamjstewart** [comment]
Should it depend on older `abseil-cpp` or `abseil-cpp cxxstd=11`? Like if I build with older `abseil-cpp cxxstd=14` will that still work?

**Comment by vicentebolea** [comment]
> Should it depend on older abseil-cpp or abseil-cpp cxxstd=11?

#paraview pkg
```
depends_on(protobuf ^abseil-cpp@:20220623.0) #(it implicity defaults to cxxstd=11)
```

**Comment by adamjstewart** [comment]
`depends_on` statements can't contain `^`, so I used a `conflict` instead. See if the latest commit looks good, hopefully CI will pass now.

**Review by hyoklee — APPROVED** [review]

**Review by vicentebolea — APPROVED** [review]
Paraview-wise

**Review by alalazo — APPROVED** [review]

**Pull request merged**
