### PR TITLE
spack external find: expand symlinks in package prefix

### LINKED ISSUE #24418: Use of `prefix: /` in `packages.yaml` can cause traversal of entire file system
It appears that `prefix: /` in `packages.yaml` can cause Spack to traverse the entire file system.

For example, on an Ubuntu 20.04 system, `spack external find` nondeterministically locates `xz` as having prefix either `/` or `/usr` (though I don't think there's anything specific to `xz` here, just for minimality since `packages.yaml` seemingly must have at least one package).  The former case is problematic:

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git
$ cd spack
$ spack compiler find --scope=site
$ spack external find xz --scope=site
# assume spack chooses `/`,
# or edit `etc/spack/packages.yaml` as follows:
packages:
  xz:
    externals:
    - spec: xz@5.2.4
      prefix: /
$ spack install python@3.8.10
 ...
==> Ran patch() for python
```

At this point the build appears to hang, and `strace` reveals calls to `lstat` on files in my `/projects` directory, which is immense.

### Information on your system

```
* **Spack:** 0.16.2-3199-383d4cc84c
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by adamjstewart**
@bcdarwin can you see if this fixes #24418?

### CODE REVIEW

**Comment by alalazo** [comment]
This may change how we detect stuff in subtle ways, so we must be careful about that. For instance, if we expect to see 2 executables in a directory to call package `foo` detected and:
- Those executables are symlinked into the same directory 
- Their realpath directory is different

I think we would actually detect `foo` but we wouldn't be able to after this PR.

**Comment by adamjstewart** [comment]
I see what you mean. Are there currently any packages which require more than 1 executable to be found in order to be considered "detected"?

**Comment by bcdarwin** [comment]
As mentioned in #24418, @adamjstewart (and I) see this as more of a workaround than a fix, so maybe it shouldn't be enabled by default due to the above-mentioned subtleties (and others, e.g. it may expand symlinks revealing non-'logical' details of the filesystem layout)?

**Comment by haampie** [comment]
This looks a lot like https://github.com/spack/spack/pull/23009

Can you test this on an environment view `PATH=view/bin:$PATH` where you have `git` installed? I recall there were some issues when you follow the symbolic links "too early". Yeah, see the thread. My first commit there https://github.com/spack/spack/pull/23009/commits/beda99a980efa7bc93eee78fc1b64e73ddc1af65 is the same as this.

**Comment by adamjstewart** [comment]
Thanks, looks like this is a duplicate.

**Pull request closed without merging**
