### PR TITLE
Update dotnet-core-sdk to version 6.0.25 and add binaries for 'aarch64'

### PR DESCRIPTION
**Pull request by grospelliergilles**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]

**Comment by tldahlgren** [comment]
@grospelliergilles Can you resolve the conflicts so this PR can be merged?

**Comment by grospelliergilles** [comment]
> @grospelliergilles Can you resolve the conflicts so this PR can be merged?

Yes I will do that. Thanks

**Comment by grospelliergilles** [comment]
Hello @tldahlgren, do you need anything else before merging ?

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
> Hello @tldahlgren, do you need anything else before merging ?

No.  Thanks for pinging me.

**Pull request merged**
