### PR TITLE
py-numpy: add v2.0.2

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/numpy/numpy/releases/tag/v2.0.2

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, and CI seems happy. This was a very minor bugfix release indeed, so good to see it worked without hiccups.

**Comment by adamjstewart** [comment]
I'm surprised you even fixed it instead of only supporting 2.1.X. Is that a new numpy policy to support older minor releases for longer?

**Comment by rgommers** [comment]
It's normal to do several bugfix releases for each minor release, yes. We usually don't go back two minor versions, but if there's a reason for 2.0.3 that may still appear as well. IIRC the highest we ever went was `1.xx.6`.

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
