### PR TITLE
netcdf packages: filter compiler wrappers in the *-config files

### PR DESCRIPTION
**Pull request by skosukhin**
We should have done this long ago. However, it looks like nobody really cares about compiler-related entries in those files.

Whoever reviews this, please, take a look at the long-pending #31953. Thank you.

### CODE REVIEW

**Comment by skosukhin** [comment]
Oh, `ncview` now gives a wonderful configure-time message:
```
======================================================================
Configuration error: You specified that the "/scratch/local1/spack/lib/spack/env/gcc/gcc" C compiler should be
used to build ncview, but the netcdf library was compiled with the "/usr/bin/gcc"
compiler.  Here is the path where I found the netcdf library:
     -L/scratch/local1/mysw/packages/gcc-10.2.1-sys/netcdf-c-4.8.1/lib -lnetcdf
You must use the same compiler for ncview as was used to build the netcdf library!

There are two possible ways to fix this.

1) Download the netcdf library and compile it with the /scratch/local1/spack/lib/spack/env/gcc/gcc compiler,
install it, and try again to build ncview.  NOTE that if you do this,
you might have more than one version of the netcdf library on your system,
built with differnt compilers, which can get confusing.  If you do this,
you will have to specify the path to the (new) version of nc-config
that was compiled using the /scratch/local1/spack/lib/spack/env/gcc/gcc compiler by configuring ncview in a
way similar to this:

   ./configure --with-nc-config=/path/to/newly/compiled/nc-config

2) Configure ncview to use the /usr/bin/gcc compiler.
To do this, set environmental variable CC to /usr/bin/gcc
and run ./configure again
===================================================================
```
I will try to fix this one tomorrow but there might be more packages that do a similar thing.

**Review by alalazo — COMMENTED** [review]
@skosukhin Feel free to ping me when done

**Comment by skosukhin** [comment]
The most simple solution to the problem that I could come up with is to back up the unmodified `nc-config` and make it available in the dependent build environment via the `PATH` variable. This works for `ncview` but might not work for a package that makes assumptions on the relative path of `nc-config`:
1. A package might expect the installation prefix of `netcdf-c` to be the result of something like:
    ```bash
    netcdf_prefix="$(dirname $(which nc-config))/.."
    ```
    It doesn't look like a reasonable thing to do but you never know.
2. A package might be given an installation prefix to `netcdf-c` and expect `nc-config` in the `bin` subdirectory of the prefix. In this case, the package will work with the modified `nc-config`. As far as I remember, `cdo` will do that. Luckily, it does not care about what `nc-config --cc` returns.

An alternative solution that covers such cases could be to modify `nc-config` in a way that it returns Spack wrapper in the Spack build environment (e.g. `netcdf-c` sets something like `SPACK_NETCDF` for the dependent build environment, which would be the trigger for `nc-config`) and the real compiler otherwise. But that would require us to either duplicate the already quite complex logic of `filter_compiler_wrappers` or extend `filter_compiler_wrappers` itself. I don't really want to do that right now.

I also would like not to do the same thing for `netcdf-fortran` and `netcdf-cxx4` unless somebody gives me an example of when that is required (I'm not aware of packages that call `nf-config` or `ncxx4-config`). In that case, however, I would appreciate a piece of advice on how to avoid code duplication.

@alalazo

**Comment by skosukhin** [comment]
I have searched for `nc-config`, `nf-config` and `ncxx4-config` in the package repository and decided to ping maintainers of packages that use the config scripts explicitly so they could tell whether they forsee any problems caused by this PR:

- @adamjstewart: `gmt`, `grass`
- @climbfuji, @jedwards4b: `esmf`
- @t-yamaura: `scale`
- @amd-toolchain-support: `roms`

Maybe we need a different solution after all.

**Review by jedwards4b — APPROVED** [review]

**Review by t-yamaura — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
I don't think this will cause a problem, but testing it to the full extent will take some time. Please go ahead with the PR, if we run into problems later on we'll let you know.

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@adamjstewart @amd-toolchain-support Waiting some time for you to report if this works with the packages mentioned above.

**Review by adamjstewart — APPROVED** [review]
Confirmed that `gmt` and `grass+netcdf` both build on this branch.

**Pull request merged**
