### PR TITLE
fix rocm testing in heffte

### PR DESCRIPTION
**Pull request by mkstoyanov**
* fix testing issues with heffte+rocm

### CODE REVIEW

**Comment by mkstoyanov** [comment]
@tldahlgren is something wrong with the CI, it seems stuck

**Comment by tldahlgren** [comment]
> @tldahlgren is something wrong with the CI, it seems stuck

Looks like there were failures with packages that are flagged as failures in the base develop commit.  We can try again.

@spackbot run pipeline

**Review by tldahlgren — CHANGES_REQUESTED** [review]
In order to work, this needs to be called post-install to ensure the path is written out.  For example:

```
    @run_after("install")
    def setup_test(self):
        self.cmake_bin(set=True)
```

As is, the stand-alone tests fail:

```
==> [2022-10-24-18:21:32.591949] Skipping heffte test: cmake_bin_path.txt not found
==> [2022-10-24-18:21:32.592056] Completed testing
```

The raw output for the pipeline jobs can be found at:

- https://gitlab.spack.io/spack/spack/-/jobs/3948575/raw
- https://gitlab.spack.io/spack/spack/-/jobs/3948576/raw

**Comment by tldahlgren** [comment]
> In order to work, this needs to be called post-install to ensure the path is written out. For example:
> 
> ```
>     @run_after("install")
>     def setup_test(self):
>         self.cmake_bin(set=True)
> ```
> 
> As is, the stand-alone tests fail:
> 
> ```
==> Testing package heffte-2.2.0-mihypmy
==> [2022-10-24-18:21:32.591949] Skipping heffte test: cmake_bin_path.txt not found
==> [2022-10-24-18:21:32.592056] Completed testing
> ```

The raw output for the pipeline jobs can be found at:

- https://gitlab.spack.io/spack/spack/-/jobs/3948575/raw
- https://gitlab.spack.io/spack/spack/-/jobs/3948576/raw

**Comment by mkstoyanov** [comment]
@tldahlgren I'm closing this one in favor of #33536

I need to add the new release of heffte for the xSDK release

**Pull request closed without merging**
