### PR TITLE
Boost: add version 1.79.0

### PR DESCRIPTION
**Pull request by hainest**
No new libraries were added. https://www.boost.org/users/history/version_1_79_0.html

### CODE REVIEW

**Comment by hainest** [comment]
@spackbot run e4s-pr-build

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
There are issues building `precice` in the pipelines, can you double check if that is related to the new boost version?

**Review by alalazo — CHANGES_REQUESTED** [review]
There are issues building `precice` in the pipelines, can you double check if that is related to the new boost version?

**Comment by hainest** [comment]
@alalazo I saw that. I request a pipeline re-run, but evidently it seems you can re-run just part of the pipeline. The issue is that src/com/ConnectionInfoPublisher.cpp only includes `istream` instead of `fstream`. That bug has been there a long time, but I have a feeling it went unnoticed because some other header (likely a boost one) was dragging it in.

I'm testing now. If need be, I'll submit a bug report to precice and put a conflict in their package.

```
src/com/ConnectionInfoPublisher.cpp: In member function 'std::__cxx11::string precice::com::ConnectionInfoReader::read() const':
src/com/ConnectionInfoPublisher.cpp:63:17: error: aggregate 'std::ifstream ifs' has incomplete type and cannot be defined
   std::ifstream ifs;
                 ^~~
src/com/ConnectionInfoPublisher.cpp:67:35: error: incomplete type 'std::ifstream {aka std::basic_ifstream<char>}' used in nested name specifier
     ifs.open(path, std::ifstream::in);
                                   ^~
src/com/ConnectionInfoPublisher.cpp: In member function 'void precice::com::ConnectionInfoWriter::write(const string&) const':
src/com/ConnectionInfoPublisher.cpp:93:23: error: variable 'std::ofstream ofs' has initializer but incomplete type
     std::ofstream ofs(tmp.string(), std::ofstream::out);
                       ^~~
src/com/ConnectionInfoPublisher.cpp:93:52: error: incomplete type 'std::ofstream {aka std::basic_ofstream<char>}' used in nested name specifier
     std::ofstream ofs(tmp.string(), std::ofstream::out);
                                                    ^~~
```

**Review by alalazo — APPROVED** [review]

**Pull request merged**
