### PR TITLE
hpctoolkit: add version 2021.10.15

### PR DESCRIPTION
**Pull request by mwkrentel**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the commit exists in the repository.

**Comment by mwkrentel** [comment]
@tldahlgren Hold off on merging.   I think we're going to add one more
bug fix to the release.   Sigh.

**Comment by mwkrentel** [comment]
@tldahlgren I've updated the commit hash and the gitlab-ci pipeline has finished.
So, I'm now ready (again).

**Review by tldahlgren — APPROVED** [review]
Confirmed the commit exists in the repo (and associated with a release-related comment).

**Comment by tldahlgren** [comment]
@mwkrentel Is this ready to be merged?

**Comment by mwkrentel** [comment]
@tldahlgren Yes, please, ready to be merged.

**Pull request merged**
