### PR TITLE
Fix py-scientificpython and py-argcomplete dependencies

### PR DESCRIPTION
**Pull request by hegner**
py-scientificpython had a missing dependency on py-numpy
py-argcomplete had a missing setuptools build dependency

### CODE REVIEW

**Comment by adamjstewart** [comment]
**py-scientificpython**
I'm surprised they didn't hardcode the dependency in `setup.py`, but I'm seeing a couple references to it, so I'll trust you. Btw, doesn't this package depend on NetCDF? I'm seeing a lot of references to that.

**py-argcomplete**
Technically, this package also depends on `py-argparse`, which isn't in Spack right now. If it isn't available (for example, in Python 2.6), pip will try to download it. If you really want to be thorough, you should add a `py-argparse` package and add dependencies to `py-argcomplete` for `when='^python@:2.6,3.0:3.1'`

**Comment by hegner** [comment]
@adamjstewart. I didn't see any problems with NetCDF on py-scientificpython. 

For py-argcomplete you are right. I built with a newer python. I wonder however how much backwards-compatibility with older versions we want to provide. Such fixes tend to accumulate quickly.

**Comment by adamjstewart** [comment]
@hegner It's up to you. For NetCDF, it may have picked up a system installation. Or it might be something that isn't required unless you enable a specific option. I'm not familiar with `py-scientificpython`.

**Comment by hegner** [comment]
@adamjstewart - let me check the logs/status for NetCDF. I will let you know.
The backwards-compatibility of py-argcomplete I would leave aside for now.

**Comment by hegner** [comment]
@adamjstewart - the NetCDF is optional

**Pull request merged**
