### PR TITLE
slurm: Fix build with gcc@10:

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Comment by scheibelp** [comment]
Closing/reopening to restart tests

**Review by scheibelp — APPROVED** [review]
Pending flake, this LGTM. I'd update the commit message to say something like:

> gcc@10: defaults to -fno-common and earlier versions effectively defaulted to -fcommon. Slurm versions at or before 20-02-1 need to set -fcommon when using later versions of gcc. See also: https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by michaelkuhn** [comment]
Pushed a new version with a short commit message describing the problem.

**Comment by scheibelp** [comment]
Thanks! FYI I appreciate the force push with updated commit message, but I can merge it either way (I can modify the commit message when I merge).

**Pull request merged**
