### PR TITLE
test/url_parse.py: ported to pytest

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by adamjstewart** [comment]
I would wait on rewriting this one until after #2972 is finished. I'm rewriting the whole test suite anyway: https://github.com/LLNL/spack/pull/2972/files#diff-2a74fb73f0a3ed36773beeec3a2d0cc1

**Comment by alalazo** [comment]
@adamjstewart Ouch, the work here is already done :smile: (I just picked one of the random 30 something test modules that are still written using `unittest` and ported it). Maybe you can use the implementation here as a reference to port #2972 to `pytest` and close this PR when done?

**Comment by adamjstewart** [comment]
I can try, but I still find `pytest` much harder to understand than `unittest`. It is much shorter though.

**Comment by alalazo** [comment]
@adamjstewart I marked this WIP (to signal the conflict and that this PR is not to be merged yet). Just ping me here when you're done with the rest of #2972 (if you need help). Or I can rework this completely after #2972 will be merged.

**Comment by adamjstewart** [comment]
It would probably be easier for me if you could rework this after #2972 is merged. We just had a new cluster delivered yesterday so I've been way too swamped to do much Spack work lately.

**Comment by alalazo** [comment]
@adamjstewart Can you have a look at this when you have time?

**Comment by adamjstewart** [comment]
@alalazo Sorry about the conflict. Can you add the test from #4014 and rebase/merge?

**Comment by alalazo** [comment]
> Sorry about the conflict. Can you add the test from #4014 and rebase/merge?

@adamjstewart Yes, no worries.

**Comment by alalazo** [comment]
OT: there's since a couple of days this annoying thing that running `spack test` changes:
```
var/spack/repos/builtin.mock/packages/flake8/package.py
```
which is a git tracked file. Is this wanted?

**Comment by adamjstewart** [comment]
Oops, that explains a lot. I'll see if I can fix that.

**Comment by alalazo** [comment]
@tgamblin ping. Made the same changes as in #4032

**Pull request merged**
