### PR TITLE
Add patch to allow PGI to build M4

### PR DESCRIPTION
**Pull request by adamjstewart**
When trying to install M4 with PGI, I ran into a problem. `make` would crash and `spack-build.out` would contain dozens of lines like:
```
builtin.o: In function `xnmalloc':
/tmp/ajstewart/spack-stage/spack-stage-Mus3U5/m4-1.4.17/src/../lib/xalloc.h:104: multiple definition of `xnmalloc'
m4.o:/tmp/ajstewart/spack-stage/spack-stage-Mus3U5/m4-1.4.17/src/../lib/xalloc.h:104: first defined here
```
After submitting a [bug report](http://lists.gnu.org/archive/html/bug-gnulib/2016-03/msg00006.html) with the developers of M4, they provided me with this patch to get things working.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Note that there is one last problem to solve. The patch works as expected, but applying it has one unforeseen consequence. Now, `make` crashes with the following message:
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /tmp/ajstewart/spack-stage/spack-stage-wHnXsx/m4-1.4.17/build-aux/missing aclocal-1.14 -I m4
/tmp/ajstewart/spack-stage/spack-stage-wHnXsx/m4-1.4.17/build-aux/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
```
When I run `make -d`, I see useful messages like:
```
Prerequisite `m4/extern-inline.m4' is newer than target `aclocal.m4'.
Must remake target `aclocal.m4'.
```
The problem is that the timestamp of extern-inline.m4 is newer than aclocal.m4, so `make` refuses to compile. There are a couple solutions to this problem. One is to run:
```
touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
```
before `./configure`. Another is to run `autoreconf` before `./configure`. Yet another is to apply the patch but somehow not change the timestamp. Any suggestions on how to do this through Spack? It would be nice if this could be worked into the code that runs `patch` so that is applies to all patched packages.

**Comment by eschnett** [comment]
Using `touch` this way can lead to hard-to-debug problems: `touch` uses the time of the system on which Spack is running, while modifying a file uses the time of the file server, if you are using a networked file system. If these times differ (that shouldn't happen, but it does), things will fail spuriously.

`touch` has an option `-r` that lets you set the timestamp of a file to that of another file; I'd use this instead.

To call `touch` from Spack, say
```
touch = which('touch')
touch('-r', 'configure' 'configure.ac', 'aclocal.m4', 'Makefile.am', 'Makefile.in')
```
(`configure` is not listed among the files that have their time stamp changed).

**Comment by adamjstewart** [comment]
@eschnett: I was unable to get your suggestion to work. I also tried several other variants on your touch command. None of them produced errors, but `make` failed just like it used to.

When I build M4 by hand, using touch solves the problem.

**Comment by eschnett** [comment]
@adamjstewart How do the time stamps of the files look like afterwards? Can you send me the output of `ls -l` in the respective directory? Please also check whether `touch` ran in the correct directory, or whether it created files elsewhere.

**Comment by adamjstewart** [comment]
With a touch command of:
```python
touch('-r', 'configure', 'configure.ac', 'aclocal.m4', 'Makefile.am', 'Makefile.in')
```
```bash
$ ls -l m4-1.4.17
-rw-r--r-- 1 ajstewart lcrcsys  863 Sep 22  2013 acinclude.m4
-rw-r--r-- 1 ajstewart lcrcsys  47K Sep 22  2013 aclocal.m4
-rw-r--r-- 1 ajstewart lcrcsys 2.4K Sep 22  2013 AUTHORS
-rw-r--r-- 1 ajstewart lcrcsys 2.6K Sep 22  2013 BACKLOG
-rwxr-xr-x 1 ajstewart lcrcsys 140K Sep 22  2013 bootstrap
drwxr-xr-x 3 ajstewart lcrcsys  420 Mar  7 14:05 build-aux
-rw-r--r-- 1 ajstewart lcrcsys  15K Sep 22  2013 c-boxes.el
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Sep 22  2013 cfg.mk
-rw-r--r-- 1 ajstewart lcrcsys 191K Sep 22  2013 ChangeLog
drwxr-xr-x 2 ajstewart lcrcsys 4.8K Mar  7 14:06 checks
-rw-r--r-- 1 ajstewart lcrcsys 389K Mar  7 14:06 config.log
-rwxr-xr-x 1 ajstewart lcrcsys  74K Mar  7 14:06 config.status
-rwxr-xr-x 1 ajstewart lcrcsys 1.1M Sep 22  2013 configure
-rw-r--r-- 1 ajstewart lcrcsys 7.8K Sep 22  2013 configure.ac
-rw-r--r-- 1 ajstewart lcrcsys  35K Sep 22  2013 COPYING
drwxr-xr-x 2 ajstewart lcrcsys  300 Mar  7 14:06 doc
drwxr-xr-x 2 ajstewart lcrcsys 1.1K Mar  7 14:06 examples
-rw-r--r-- 1 ajstewart lcrcsys 4.5K Sep 22  2013 GNUmakefile
-rw-r--r-- 1 ajstewart lcrcsys  16K Sep 22  2013 INSTALL
drwxr-xr-x 4 ajstewart lcrcsys 5.7K Mar  7 14:06 lib
drwxr-xr-x 2 ajstewart lcrcsys 4.0K Mar  7 14:05 m4
-rw-r--r-- 1 ajstewart lcrcsys  62K Sep 22  2013 maint.mk
-rw-r--r-- 1 ajstewart lcrcsys  55K Mar  7 14:06 Makefile
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Sep 22  2013 Makefile.am
-rw-r--r-- 1 ajstewart lcrcsys  68K Sep 22  2013 Makefile.in
-rw-r--r-- 1 ajstewart lcrcsys  30K Sep 22  2013 NEWS
-rw-r--r-- 1 ajstewart lcrcsys 3.9K Sep 22  2013 README
-rw-r--r-- 1 ajstewart lcrcsys 4.6K Mar  7 14:05 spack-build.env
-rw-r--r-- 1 ajstewart lcrcsys  23K Mar  7 14:06 spack-build.out
drwxr-xr-x 3 ajstewart lcrcsys  360 Mar  7 14:06 src
-rw-r--r-- 1 ajstewart lcrcsys   29 Mar  7 14:06 stamp-h
drwxr-xr-x 3 ajstewart lcrcsys 5.6K Mar  7 14:06 tests
-rw-r--r-- 1 ajstewart lcrcsys 6.3K Sep 22  2013 THANKS
-rw-r--r-- 1 ajstewart lcrcsys 2.1K Sep 22  2013 TODO
$ ls -l m4-1.4.17/m4/extern-inline.m4
-rw-r--r-- 1 ajstewart lcrcsys 3.2K Mar  7 14:05 m4-1.4.17/m4/extern-inline.m4
```
With a touch command of:
```python
touch('-r', 'm4/extern-inline.m4', 'configure', 'configure.ac', 'aclocal.m4', 'Makefile.am', 'Makefile.in')
```
```bash
$ ls -l m4-1.4.17
-rw-r--r-- 1 ajstewart lcrcsys  863 Sep 22  2013 acinclude.m4
-rw-r--r-- 1 ajstewart lcrcsys  47K Mar  7 14:10 aclocal.m4
-rw-r--r-- 1 ajstewart lcrcsys 2.4K Sep 22  2013 AUTHORS
drwxr-xr-x 2 ajstewart lcrcsys  100 Mar  7 14:11 autom4te.cache
-rw-r--r-- 1 ajstewart lcrcsys 2.6K Sep 22  2013 BACKLOG
-rwxr-xr-x 1 ajstewart lcrcsys 140K Sep 22  2013 bootstrap
drwxr-xr-x 3 ajstewart lcrcsys  420 Mar  7 14:10 build-aux
-rw-r--r-- 1 ajstewart lcrcsys  15K Sep 22  2013 c-boxes.el
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Sep 22  2013 cfg.mk
-rw-r--r-- 1 ajstewart lcrcsys 191K Sep 22  2013 ChangeLog
drwxr-xr-x 2 ajstewart lcrcsys 4.8K Mar  7 14:11 checks
-rw-r--r-- 1 ajstewart lcrcsys 389K Mar  7 14:11 config.log
-rwxr-xr-x 1 ajstewart lcrcsys  74K Mar  7 14:11 config.status
-rwxr-xr-x 1 ajstewart lcrcsys 1.1M Mar  7 14:10 configure
-rw-r--r-- 1 ajstewart lcrcsys 7.8K Mar  7 14:10 configure.ac
-rw-r--r-- 1 ajstewart lcrcsys  35K Sep 22  2013 COPYING
drwxr-xr-x 2 ajstewart lcrcsys  300 Mar  7 14:11 doc
drwxr-xr-x 2 ajstewart lcrcsys 1.1K Mar  7 14:11 examples
-rw-r--r-- 1 ajstewart lcrcsys 4.5K Sep 22  2013 GNUmakefile
-rw-r--r-- 1 ajstewart lcrcsys  16K Sep 22  2013 INSTALL
drwxr-xr-x 5 ajstewart lcrcsys 6.0K Mar  7 14:11 lib
drwxr-xr-x 2 ajstewart lcrcsys 4.0K Mar  7 14:10 m4
-rw-r--r-- 1 ajstewart lcrcsys  62K Sep 22  2013 maint.mk
-rw-r--r-- 1 ajstewart lcrcsys  55K Mar  7 14:11 Makefile
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Mar  7 14:10 Makefile.am
-rw-r--r-- 1 ajstewart lcrcsys  68K Mar  7 14:10 Makefile.in
-rw-r--r-- 1 ajstewart lcrcsys  30K Sep 22  2013 NEWS
-rw-r--r-- 1 ajstewart lcrcsys 3.9K Sep 22  2013 README
-rw-r--r-- 1 ajstewart lcrcsys 4.0K Mar  7 14:10 spack-build.env
-rw-r--r-- 1 ajstewart lcrcsys  74K Mar  7 14:11 spack-build.out
drwxr-xr-x 3 ajstewart lcrcsys  360 Mar  7 14:11 src
-rw-r--r-- 1 ajstewart lcrcsys   29 Mar  7 14:11 stamp-h
drwxr-xr-x 3 ajstewart lcrcsys 5.6K Mar  7 14:11 tests
-rw-r--r-- 1 ajstewart lcrcsys 6.3K Sep 22  2013 THANKS
-rw-r--r-- 1 ajstewart lcrcsys 2.1K Sep 22  2013 TODO
$ ls -l m4-1.4.17/m4/extern-inline.m4
-rw-r--r-- 1 ajstewart lcrcsys 3.2K Mar  7 14:10 m4-1.4.17/m4/extern-inline.m4
```
With a touch command of:
```python
touch('configure', 'configure.ac', 'aclocal.m4', 'Makefile.am', 'Makefile.in')
```
```bash
$ ls -l m4-1.4.17
-rw-r--r-- 1 ajstewart lcrcsys  863 Sep 22  2013 acinclude.m4
-rw-r--r-- 1 ajstewart lcrcsys  47K Mar  7 14:13 aclocal.m4
-rw-r--r-- 1 ajstewart lcrcsys 2.4K Sep 22  2013 AUTHORS
drwxr-xr-x 2 ajstewart lcrcsys  100 Mar  7 14:15 autom4te.cache
-rw-r--r-- 1 ajstewart lcrcsys 2.6K Sep 22  2013 BACKLOG
-rwxr-xr-x 1 ajstewart lcrcsys 140K Sep 22  2013 bootstrap
drwxr-xr-x 3 ajstewart lcrcsys  420 Mar  7 14:13 build-aux
-rw-r--r-- 1 ajstewart lcrcsys  15K Sep 22  2013 c-boxes.el
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Sep 22  2013 cfg.mk
-rw-r--r-- 1 ajstewart lcrcsys 191K Sep 22  2013 ChangeLog
drwxr-xr-x 2 ajstewart lcrcsys 4.8K Mar  7 14:15 checks
-rw-r--r-- 1 ajstewart lcrcsys 389K Mar  7 14:15 config.log
-rwxr-xr-x 1 ajstewart lcrcsys  74K Mar  7 14:15 config.status
-rwxr-xr-x 1 ajstewart lcrcsys 1.1M Mar  7 14:13 configure
-rw-r--r-- 1 ajstewart lcrcsys 7.8K Mar  7 14:13 configure.ac
-rw-r--r-- 1 ajstewart lcrcsys  35K Sep 22  2013 COPYING
drwxr-xr-x 2 ajstewart lcrcsys  300 Mar  7 14:15 doc
drwxr-xr-x 2 ajstewart lcrcsys 1.1K Mar  7 14:15 examples
-rw-r--r-- 1 ajstewart lcrcsys 4.5K Sep 22  2013 GNUmakefile
-rw-r--r-- 1 ajstewart lcrcsys  16K Sep 22  2013 INSTALL
drwxr-xr-x 5 ajstewart lcrcsys 6.0K Mar  7 14:15 lib
drwxr-xr-x 2 ajstewart lcrcsys 4.0K Mar  7 14:13 m4
-rw-r--r-- 1 ajstewart lcrcsys  62K Sep 22  2013 maint.mk
-rw-r--r-- 1 ajstewart lcrcsys  55K Mar  7 14:15 Makefile
-rw-r--r-- 1 ajstewart lcrcsys 1.9K Mar  7 14:13 Makefile.am
-rw-r--r-- 1 ajstewart lcrcsys  68K Mar  7 14:13 Makefile.in
-rw-r--r-- 1 ajstewart lcrcsys  30K Sep 22  2013 NEWS
-rw-r--r-- 1 ajstewart lcrcsys 3.9K Sep 22  2013 README
-rw-r--r-- 1 ajstewart lcrcsys 4.1K Mar  7 14:13 spack-build.env
-rw-r--r-- 1 ajstewart lcrcsys  74K Mar  7 14:15 spack-build.out
drwxr-xr-x 3 ajstewart lcrcsys  360 Mar  7 14:15 src
-rw-r--r-- 1 ajstewart lcrcsys   29 Mar  7 14:15 stamp-h
drwxr-xr-x 3 ajstewart lcrcsys 5.6K Mar  7 14:15 tests
-rw-r--r-- 1 ajstewart lcrcsys 6.3K Sep 22  2013 THANKS
-rw-r--r-- 1 ajstewart lcrcsys 2.1K Sep 22  2013 TODO
$ ls -l m4-1.4.17/m4/extern-inline.m4
-rw-r--r-- 1 ajstewart lcrcsys 3.2K Mar  7 14:13 m4-1.4.17/m4/extern-inline.m4
```

**Comment by eschnett** [comment]
Ha. I didn't look at the patch carefully enough.

`touch` can't fix this. With this patch, the package needs to depend on the autotools, and needs to run `autoconf` afterwards. Sorry about the misunderstanding.

**Comment by adamjstewart** [comment]
With autoconf:
```
$ cat /tmp/ajstewart/spack-stage/spack-stage-9LSlKz/m4-1.4.17/spack-build.out
==> /usr/bin/autoconf
aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:25: error: Autoconf version 2.65 or higher is required
aclocal.m4:438: AM_INIT_AUTOMAKE is expanded from...
configure.ac:25: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
```
With autoreconf:
```
$ cat /tmp/ajstewart/spack-stage/spack-stage-aZ9sIO/m4-1.4.17/spack-build.out
==> /usr/bin/autoreconf
configure.ac:25: require Automake 1.11.6, but have 1.11.1
autom4te: closing standard output: Broken pipe
autoreconf: automake failed with exit status: 1
```
It's weird that touch works locally but not within Spack. Back to the drawing board...

**Comment by eschnett** [comment]
`touch` can be made to work from within Spack. However, the patch modifies one of the input files that is used to generate `configure`, it does not update `configure` itself. Without running `autoconf` or similar, you'll be using the old `configure` -- `touch` only circumvents the error message.

**Comment by adamjstewart** [comment]
Theoretically, I could install a newer version of Autotools and just run autoreconf. But if the system Autotools on CentOS 6 is too old, then this will probably affect a lot of users. I don't want to introduce a commit that prevents everyone from installing M4 on CentOS 6 or older.

**Comment by eschnett** [comment]
You can add a conditional dependency on autotools -- they are supported by Spack.

**Comment by adamjstewart** [comment]
I'm starting to wonder whether or not every package that is built by Autotools should depend on autotools and every package built by CMake should depend on cmake. I know this idea has been tossed around before. The problem is that there is currently no way to tell Spack to use the newly installed Autotools instead.

**Comment by adamjstewart** [comment]
Finally got something working. I had to hack `configure.ac` so that it didn't depend on a specific version of Autotools. If someone can think of something better let me know. Otherwise I think we're good to go.

**Comment by adamjstewart** [comment]
Note that the developers of M4 actually recommended this solution

> You can probably get by with an older automake.  Automake has the nasty
habit of hard-coding its version string into the generated files; to
overcome that, you can try 'autoreconf --force' to do a clean build from
scratch rather than an incremental build, since it is only the
incremental builds that are picky about versioning.

**Comment by eschnett** [comment]
Packages built by autotools are self-contained, and don't need the autotools to run.

Instead of using autotools, it might be easier to look in the file `configure` for the (probably) one line that is affected by the change in the patch, and to make this change manually, updating the patch. This would remove the need to re-run autotools every time the package is built.

**Comment by tgamblin** [comment]
I like @eschnett's last suggestion.  The change in the patch is really small. You can probably find which lines of configure it affects and edit it by hand.  Alternately, you could check out the project, get the same version of autotools as what they used to generate configure, and run autoreconf, then generate the patch again.  These basically accomplish the same thing.

**Comment by eschnett** [comment]
Running autoreconf is likely to introduce tons of irrelevant differences, e.g. due to version numbers of line numbers.

**Comment by adamjstewart** [comment]
I tried searching `configure` for the definitions that might be affected by the original patch but I couldn't find anything. And `configure` is 40,000 lines long, so going through it manually isn't feasible.

@tgamblin: I tried your second suggestion. Spack installs automake@1.11.6 and autoconf@2.62, but when I run autoreconf, I get the error message:
```
aclocal: couldn't open directory '/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-4.4.7/automake-1.11.6-pt3uqpcwkqf62ecnrrdgfxik5mbumlhz/share/aclocal': No such file or directory
autoreconf: aclocal failed with exit status: 1
```
Something must be up with that package because `share/aclocal` exists for the system autoconf. When I delete the version constraints in `configure.ac` and run the system autoreconf, it completes, but as @eschnett predicted, there are hundreds of lines that are changed and none of them look relevant. Any other suggestions?

**Comment by tgamblin** [comment]
The patch doesn't actually modify macros that modify `configure` :).  It only modifies `config.hin`. Here's a new patch.  I generated it with automake `1.14` and autoconf `2.69`.  You only have to get close and this seemed to do the trick.

```patch
diff -Naur /g/g21/gamblin2/m4-1.4.17/lib/config.hin m4-1.4.17/lib/config.hin
--- /g/g21/gamblin2/m4-1.4.17/lib/config.hin	2016-03-08 14:16:01.519998000 -0800
+++ m4-1.4.17/lib/config.hin	2016-03-08 14:54:26.000000000 -0800
@@ -1510,6 +1510,7 @@
       ? defined __GNUC_STDC_INLINE__ && __GNUC_STDC_INLINE__ \
       : (199901L <= __STDC_VERSION__ \
          && !defined __HP_cc \
+         && !defined __PGI \
          && !(defined __SUNPRO_C && __STDC__))) \
      && !defined _GL_EXTERN_INLINE_APPLE_BUG)
 # define _GL_INLINE inline
diff -Naur /g/g21/gamblin2/m4-1.4.17/m4/extern-inline.m4 m4-1.4.17/m4/extern-inline.m4
--- /g/g21/gamblin2/m4-1.4.17/m4/extern-inline.m4	2016-03-08 14:16:02.152050000 -0800
+++ m4-1.4.17/m4/extern-inline.m4	2016-03-08 14:14:30.179143985 -0800
@@ -34,6 +34,7 @@
       ? defined __GNUC_STDC_INLINE__ && __GNUC_STDC_INLINE__ \
       : (199901L <= __STDC_VERSION__ \
          && !defined __HP_cc \
+         && !defined __PGI \
          && !(defined __SUNPRO_C && __STDC__))) \
      && !defined _GL_EXTERN_INLINE_APPLE_BUG)
 # define _GL_INLINE inline
```

**Comment by adamjstewart** [comment]
This looks a lot less hacky! Unfortunately, we're back to square one now:
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /tmp/ajstewart/spack-stage/spack-stage-z1HbKn/m4-1.4.17/build-aux/missing aclocal-1.14 -I m4
/tmp/ajstewart/spack-stage/spack-stage-z1HbKn/m4-1.4.17/build-aux/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
```
CentOS 6 only comes with aclocal-1.11.

**Comment by eschnett** [comment]
If you want to avoid running the autotools, then you need to create a patch that modifies `configure`, and nothing else. All other files are used by the autotools as input when `configure` is created.

**Comment by tgamblin** [comment]
@adamjstewart: @eschnett is right; in this case you want to remove the part of the patch that modifies `extern-inline.m4` and just keep the part that modifies `config.hin`.  Generally the macros in the m4 files end up as part of `configure`, which is why @eschnett is saying that, but this particular macro only affects `config.hin`.  So try deleting everything from the second line that starts with `diff` down.

**Comment by adamjstewart** [comment]
It works!!! Thanks for not giving up on me. Now if only I can figure out how to get PGI to install libpciaccess...

**Comment by tgamblin** [comment]
so is this PR ready to merge?  I assume the libpciaccess stuff will be in another PR?

**Comment by tgamblin** [comment]
FYI: you could try just building libpciaccess with gcc and mixing it with the PGI build.  Does this work?

```
spack install some-package %pgi  ^libpciaccess %gcc
```

It may fail to link if there are gcc runtime libraries needed here, but I believe PGI includes most of them when it links.

**Comment by eschnett** [comment]
I tried this with Python. It works, but is quite inconvenient.

For every package that even indirectly depends on `libpciaccess`, Spack will be slightly confused, and you'll have to specify manually that `libpciaccess` is to be built with GCC, and that every other (direct or indirect) dependency is to be built with PGI. If you don't do this, Spack will rebuild some packages with GCC.

**Comment by adamjstewart** [comment]
Yes, this PR is ready to merge. I will put any libpciaccess related patches in another PR. For reference, this is the current state of libpciaccess:
https://bugs.freedesktop.org/show_bug.cgi?id=94398
http://www.pgroup.com/userforum/viewtopic.php?t=5126

**Comment by tgamblin** [comment]
@eschnett: I agree that it is inconvenient to have to specify `libpciaccess%gcc` all the time.

Part of what I would like to do to solve this is allow packages to require particular compilers (or no compilers as in #458).  For example, system tools like `dyninst` want to be built with gcc and you don't really care about having an optimized or compiler-specific version.  Combining with what we talked about in #311 (smarter concretization), I think we could pretty easily use this to set better policies for picking compilers for dependencies in cases like this...

**Pull request merged**
