### PR TITLE
gobject-introspection: Python 3.12 still not supported

### PR DESCRIPTION
**Pull request by adamjstewart**
Give them a few more years and they might catch up to 2022.

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by wdconinc** [comment]
This is a bit more subtle than "python 3.12 still not supported", right? At least, I don't think `gobject-introspection` devs consider this broken in python 3.12 (see https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/395 with suggestion "You can install setuptools", which effectively means they think we should just have `depends_on("py-setuptools", when="^python@3.12:")` instead of a conflict). 

The intended workaround/solution for python 3.12 is to install `py-setuptools` and use its `_distutils_hack`, which is automatically loaded as `distutils` *if* `py-setuptools` installs the `distutils-precedence.pth` path file into python's `sys.prefix`. That's not the case in spack, since `sys.prefix` is the `python-venv` prefix. If we had a(n acceptable) way of registering/installing path files from python packages into the venv, then none of this would be a problem and `py-setuptools` would just work when python itself doesn't have `distutils`. (Note, same thing for e.g. https://github.com/spack/spack/issues/45579 for which https://github.com/spack/spack/pull/46528 is too restrictive.)

Case in point, here's a build-env with failing gobject-introspection install, then a cp of the path file to where it will be loaded, and then the succeeding rest of the installation:
```
  File "/opt/spack/stage/wdconinc/spack-stage-gobject-introspection-1.78.1-r565am5mqxdapjf4v5gfy75god3wn72j/spack-build-r565am5/tools/g-ir-scanner", line 99, in <module>
    from giscanner.utils import dll_dirs
  File "/opt/spack/stage/wdconinc/spack-stage-gobject-introspection-1.78.1-r565am5mqxdapjf4v5gfy75god3wn72j/spack-build-r565am5/giscanner/utils.py", line 385, in <module>
    import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'
[15/83] Compiling C object tests/offsets/gitestoffsets.p/gitestoffsets.c.o
ninja: build stopped: subcommand failed.
$ python 
Python 3.12.5 (main, Nov 26 2024, 23:02:06) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
>>> 
$ cp /opt/software/linux-ubuntu24.10-skylake/gcc-14.2.0/py-setuptools-73.0.1-vidwyz3zqnln36xifplupt2sad6iflv6/lib/python3.12/site-packages/distutils-precedence.pth /opt/software/linux-ubuntu24.10-skylake/gcc-14.2.0/python-venv-1.0-7gpcu5mlqgcwasfvjriygk4r5p22aanv/lib/python3.12/site-packages
$ python 
Python 3.12.5 (main, Nov 26 2024, 23:02:06) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
>>> 
$ ninja
[16/69] Generating gir/gir-glib with a custom command
/opt/software/linux-ubuntu24.10-skylake/gcc-14.2.0/glib-2.82.2-gf273jbkhcxyawgfpkpxzky3bxpz6nei/include/glib-2.0/glib/gstdio.h:61: the __GI_SCANNER__ constant should only be used with simple #ifdef or #endif: #if  defined(G_OS_UNIX) && !defined(G_STDIO_WRAP_ON_UNIX) && !defined(__GI_SCANNER__)

[69/69] Generating tests/scanner/generate-typelib-regress with a custom command
$ 
```

So, is there any way to get the path file from `py-setuptools` to show up in the `python-venv` prefix that it depends on? I can't quite find where we create the venv. Also, `py-setuptools` is not the only package that distributes path files that are normally (i.e. outside spack) automatically loaded; `py-protobuf` is another.

**Comment by adamjstewart** [comment]
^ @haampie

**Comment by haampie** [comment]
@wdconinc's idea does not work because (a) different versions of py-setuptools depend on the same python-venv and (b) dependents shouldn't modify the prefix of dependencies.

> I don't think gobject-introspection devs consider this broken

They are mistaken, which is not a Spack problem :p `_distutils_hack` is not something to rely on. They could easily do `import setuptools` in code before they import from `distutils`, which is reliable.

**Comment by wdconinc** [comment]
> They are mistaken, which is not a Spack problem :p

Fair enough, but we'd still like to give our users python@3.12 :-) How about, until they fix it upstream, we get python@3.12 unstuck by patching this locally? I took a stab at that at https://github.com/spack/spack/pull/47879. Further discussion there.

**Comment by flxmr** [comment]
@wdconinc possible workaround could be to add a directory in the build stage to the PYTHONPATH, put a "reeentrant" sitecustomize.py in it and do `import setuptools` there. Afterwards `import distutils` works. have done this for LLVM@14 build-script and will prepare a patch - maybe this can be adapted.

**Pull request merged**
