### PR TITLE
Merge @citibeth and @alalazo's petsc fixes from #515 and #517

### PR DESCRIPTION
**Pull request by tgamblin**
For review by @citibeth and @alalazo.  I have attempted to merge the concurrent changes to petsc.

### CODE REVIEW

**Comment by tgamblin** [comment]
@eschnett @alalazo: ok I took out the HDF5 change.  Now that I look at what unsupported does, why is it an option?  Why don't we just remove the `unsupported` variant altogether, since it just allows us to use certain options together...

**Comment by eschnett** [comment]
Good point. The option name sure is confusing.

**Comment by tgamblin** [comment]
@alalazo @citibeth I'll merge if this PR works for you.  Not that it fixes some typos too.

**Comment by citibeth** [comment]
I'd like to table this until we've merged support for build dependencies
into dev.  The reason is that PETSc has a build dependency on Python 2.7,
but not a runtime dependency.  To get it working (with my Python3-enabled
project), I'm having to temporarily comment out that dependency, since it
shows up to later packages as an actual dependency.

It would also be nice to figure out the Python2 vs Python3 issue, but I
don't think that's critical for PETSc.

**Comment by tgamblin** [comment]
@mathstuf should be done with build deps soon -- can we merge this and at least get the fixes in?

**Comment by citibeth** [comment]
OK, the parts that I understand look good to me.  (The stuff with hdf5 is going over my head right now, I'll defer to others).

My only suggestion would be to add a comment above the following code to explain in English what it does:

```
 +            errors = [error_message_fmt.format(library=x)
+                      for x in ('hdf5', 'hypre', 'parmetis')
+                      if ('+'+x) in self.spec]
```

Maybe:

```
# +hdf5, +hypre and +parmetis all require +mpi as well.
```

**Comment by tgamblin** [comment]
Ah, list comprehensions.  I added some language to describe it.  See what you think.

**Pull request merged**
