### PR TITLE
add package py-py-cpuinfo

### PR DESCRIPTION
**Pull request by healther**

### CODE REVIEW

**Comment by adamjstewart** [comment]
This gets into a discussion I was having in https://github.com/LLNL/spack/pull/2972#issuecomment-278070646. How do people think we should go about naming Python packages? For example, for a package like `py-cpuinfo`, should we really call it `py-py-cpuinfo`? What about for `py-pyzmq`? What about for `py-python-meep`? Then there's `py-netcdf4-python` and `py-tap-py`. Originally I was thinking about simply removing the duplication, but it gets a lot more complicated. We obviously don't want to rename `py-numpy` to `py-num`. And it looks like `py-qtpy` and `py-pyqt` are separate packages. I'm starting to think that it's safer to always add `py-` to the tarball name and be done with it. Thoughts?

**Comment by healther** [comment]
There doesn't seem to be a consensus in the python community regarding package naming, as such spack can really only do one of two things:
- prefix a ```py-``` if its not already there
- always prefix a ```py-```

For consistency I would just go and always prefix, which would allow "guessing" the correct spack name, given one knows the python-package name.

**Comment by adamjstewart** [comment]
@citibeth Can you approve for now? We can rename it later if we want to.

**Comment by citibeth** [comment]
The doube-dash is getting me now.  Can we call this `py-pycpuinfo`?

**Comment by adamjstewart** [comment]
Let's just go with `py-cpuinfo`. No one in their right mind would actually search for `py-py-cpuinfo`.

**Comment by healther** [comment]
I renamed the package to ```py-cpuinfo``` however I still think it's inconsistent. In order to have at least some consistency it would be advantageous to just use the pypi names and put a ```py-``` marker in front of them. Then people would have the chance of correctly guessing.

I'm not sure about spack's search capabilities right now, but when I last tried there was no partial matching, so in order to find a package I would have to go to [](https://spack.readthedocs.io/en/latest/) and search the website. This will lead to people adding packages for themselves and producing duplicated PRs.

**Comment by adamjstewart** [comment]
> I'm not sure about spack's search capabilities right now, but when I last tried there was no partial matching

Currently (and it's been this way for a long time), Spack automatically converts your search string to lowercase and adds glob characters to the front and back. For example, if you run `spack list py-`, it will print a list of all Python packages. What it doesn't do right now (and probably should) is to ignore dashes so that `spack list pycpuinfo` would find `py-cpuinfo`. But regardless, `spack list cpuinfo` will find `py-cpuinfo`. 

> This will lead to people adding packages for themselves and producing duplicated PRs.

One thing I've been meaning to work on is better detection of package names that are "close enough". One way is to have `spack create` guess a reasonable name and check if that package already exists. If we are consistent and always add `py-` to the front, Spack can quickly check to see if the exact same package name exists, and will prevent you from adding a duplicate package. In fact, when I run `spack create` on the URL for this package, it actually names it `py-cpuinfo`. [This line](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/cmd/create.py#L241) prevents the duplicate `py-py-`. I'm not sure how you guys create your packages, but you should really start using `spack create`.

**Comment by adamjstewart** [comment]
@citibeth can you approve?

**Comment by healther** [comment]
Unfortunately I don't really know either. Most of the packages were created when spack was comparatively new (e.g. ```py-ipython``` didn't exist yet). As such a lot of conventions simply didn't exist and it's quite painful to merge it now. One lesson for us is to stay closer to ```LLNL/spack```, but at the same time, ```spack``` itself matured a lot and as such it's much easier to abide to conventions now.
If you are looking for ways to make the learning curve less painful, then I would say the single most helpful thing was an answer from either @adamjstewart or @citibeth regarding the wanted conventions for URLs. I.e. ```https``` over ```http``` except for crypto and ```pypi.io``` over everything else for python packages.
Thanks for your help and (at least sometimes) the necessary patience.

**Comment by tgamblin** [comment]
@healther: thanks for all the contributions and for working with spack's growing pains!

**Comment by adamjstewart** [comment]
Yeah, I try to stay as close to upstream develop as possible. My develop branch is identical to LLNL so I don't need to wonder if the bug I've come across has already been fixed. Spack is still in beta, and evolves so quickly that it is hard to work off the previous release. Hopefully things will begin to stabilize over time.

**Pull request merged**
