### PR TITLE
New recipe for rocm-opencl-runtime ,bump up version for rdc for rocm-4.1.0 Release

### PR DESCRIPTION
**Pull request by srekolam**
the new recipe is created based on @haampie  comment for the prev rocm-4.0.0 release. I have verified for rocm-4.0.0 and rocm-4.1.0 release. i see *.so created.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed new version of RDC on site and the new package has all releases on its site.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Please resolve the following flake8 errors:

```
var/spack/repos/builtin/packages/rocm-opencl-runtime/package.py:11: [E501] line too long (107 > 88 characters)
16
var/spack/repos/builtin/packages/rocm-opencl-runtime/package.py:45: [E303] too many blank lines (2)
```

**Review by tldahlgren — APPROVED** [review]
Approved contingent on all required tests passing.

**Comment by haampie** [comment]
Thanks @srekolam! I'll test this soon :)

**Review by haampie — APPROVED** [review]

**Pull request merged**
