### PR TITLE
Make jpeg a virtual dependency.

### PR DESCRIPTION
**Pull request by skosukhin**
This implements #1286

@ax3l, I had to fix 'isaac-server'. Could you, please, check if it is installed correctly with both libjpeg and libjpeg-turbo. And a question regarding 'isaac': are you sure that a header-only library needs all those dependencies?
@bvanessen, @mwilliammyers, @mathstuf, @alalazo could you check if I didn't break 'opencv'?

### CODE REVIEW

**Comment by ax3l** [comment]
fancy change, thanks!

can `jpeg-turbo` be the default or can you make it the dependency of isaac, please? We need a very low latency jpeg lib to be useful for interactive sims.

header-only dependencies: yes, although the install itself does not need the dependencies, this is the only way to properly express dependencies without letting a downstream project search for all the indirect dependencies itself: #2378

**Comment by tgamblin** [comment]
I'd be ok with `jpeg-turbo` being the default here.  It's apparently the [default in many distros already](https://en.wikipedia.org/wiki/Libjpeg#libjpeg-turbo).  The concerns bt/w libjpeg and libjpeg-turbo seem to revolve around ABI compatibility bt/w JPEG versions 6 and up, but this shouldn't matter in Spack since we only really care about API compatibility.

@skosukhin @ax3l: any other worries?

**Comment by skosukhin** [comment]
@tgamblin @ax3l I have no objections against making libjpeg-turbo the default.

**Comment by ax3l** [comment]
+1 from me, that's all :) 
Thanks for your PR! :)

**Comment by healther** [comment]
This seems to have broken ```py-matplotlib``` concretization (see #5281)

**Comment by JusticeForMikeBrown** [comment]
Can we please get this fixed?

**Comment by skosukhin** [comment]
@JusticeForMikeBrown, could you check that your problem remains after complete reinstallation of all packages from scratch?

**Comment by tgamblin** [comment]
I'm working on this -- if I can't get it fixed I may revert this until I can figure out exactly what breaks.

**Comment by JusticeForMikeBrown** [comment]
Thanks @tgamblin!

Hi @skosukhin 

I would like to test that idea though I don't have time at the moment.

**Comment by ax3l** [comment]
@skosukhin should the `openjpeg` (jpeg 2000) package be included there as well or does it provide a different functionality & API?

**Comment by skosukhin** [comment]
@ax3l jpeg2000 is a different functionality, which is implemented by openjpeg and jasper packages, which have different API =)

**Comment by JusticeForMikeBrown** [comment]
@tgamblin Any idea if this has been fixed through other method than reinstalling all child packages?

**Comment by scheibelp** [comment]
> Any idea if this has been fixed through method other than reinstalling all child packages?

@JusticeForMikeBrown if you are referring to #5281, that would not be resolved by reinstalling all child packages. You may be referring to #5293, in which case #5297 is intended to allow you to use the prior jpeg install.

**Comment by JusticeForMikeBrown** [comment]
Great!  Let's please merge #5297!

**Pull request merged**
