### PR TITLE
Bug fix for building hdf4 on Apple M1

### PR DESCRIPTION
**Pull request by climbfuji**
Building `hdf@4.2.15` on Apple M1 natively fails with
```
887 In file included from df24.c:40:
 888 In file included from ./hdf.h:20:
 889 ./hdfi.h:1349:1: error: unknown type name 'If'
 890 If you get an error on this line more than one machine type has been defined.
 891 ^
 892 ./hdfi.h:1349:7: error: expected ';' after top level declarator
 893 If you get an error on this line more than one machine type has been defined.
 894       ^
 895       ;
 896 ./hdfi.h:1352:9: warning: 'GOT_MACHINE' macro redefined [-Wmacro-redefined]
 897 #define GOT_MACHINE
 898         ^
 899 ./hdfi.h:511:9: note: previous definition is here
 900 #define GOT_MACHINE 1
 901         ^
 902 ./hdfi.h:1356:9: warning: 'DF_MT' macro redefined [-Wmacro-redefined]
 903 #define DF_MT             DFMT_LINUXAARCH64
 904         ^
 905 ./hdfi.h:503:9: note: previous definition is here
 906 #define DF_MT DFMT_APPLE_INTEL
 907         ^
 908 In file included from cnbit.c:37:
 909 In file included from ./hdf.h:20:
.
.
.
```
See https://github.com/NOAA-EMC/spack-stack/issues/317 for full details. I searched the issues and there is no existing one for this error.

This PR fixes it by avoiding that Apple M1 is identified as both "Apple" and "arch64" system. I tested this on my macOS using `apple-clang@13.1.6` and gfortran@12.2.0` and ran the unit tests that come with `hdf@4.2.15`, they all pass.

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Is obviously clearly needed, to fix the wrong assumption that __aarch64__ is always Linux. @lrknox: LGTM

**Comment by bernhardkaindl** [comment]
@climbfuji: I approve with LGTM. In case @lrknox does not respond in 5 days, please ping me or another maintainer for the merge.

**Review by lrknox — APPROVED** [review]
Patch verified on  macOS Apple M1 11.6 and tested on several other platforms.
@bernhardkaindl @climbfuji:  I approve but I don't have write access to merge.

**Comment by climbfuji** [comment]
@bernhardkaindl This is ready to merge, I think. Thanks very much in advance!

**Comment by bernhardkaindl** [comment]
> @bernhardkaindl This is ready to merge, I think. Thanks very much in advance!

Thanks also for the second reminder, I was very busy when I approved it. It's merged now.

**Pull request merged**
