### PR TITLE
py-torch-scatter: add v2.1.2

### PR DESCRIPTION
**Pull request by adamjstewart**
Same idea as #43955

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the two version sha256s but looks like the builds fail in CI.

**Comment by adamjstewart** [comment]
Ah, didn't realize it's actually needed. See #43962.

**Comment by adamjstewart** [comment]
I think py-torch-sparse needs a link dep on torch so that it can find pybind11. Let me try fixing this in a separate PR.

**Comment by adamjstewart** [comment]
Actually, let me just combine all these PRs so we don't need to wait on CI so many times. They're all made by the same developer.

**Pull request closed without merging**
