### PR TITLE
Ole' GNU nano

### PR DESCRIPTION
**Pull request by robertdfrench**
Strong to medium-strong text editor.

### CODE REVIEW

**Comment by tgamblin** [comment]
can you clean up the `FIXME`s and commented deps?

**Comment by robertdfrench** [comment]
Doh! Glad you caught that. Fixed now.

**Comment by robertdfrench** [comment]
Jeeeez maybe I will learn to use git one day. NOW it is fixed.

**Comment by tgamblin** [comment]
@robertdfrench: flake errors :)

**Comment by robertdfrench** [comment]
One day, @tgamblin, I am gonna be like, the *best* package contributor. But today might not be that day.

**Comment by adamjstewart** [comment]
LGTM

**Pull request merged**
