### PR TITLE
rclone: add 1.58

### PR DESCRIPTION
**Pull request by drkrynstrng**
Adding latest releases of rclone.

Also, the rclone docs recommend a Go version of at least 1.15, so I added that to the dependency.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Review by alecbcs — CHANGES_REQUESTED** [review]
@drkrynstrng nice work! I just noticed the rclone repository has actually moved since it was initially added to Spack. Would you be willing to update the URL to `rclone/rclone` from `ncw/rclone`?

**Comment by drkrynstrng** [comment]
@alecbcs Yes, just updated it.

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256 (new and a subset of old).

**Comment by alecbcs** [comment]
@drkrynstrng looks great thank you!

**Pull request merged**
