### PR TITLE
updated version of py-cutadapt

### PR DESCRIPTION
**Pull request by glennpj**

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
You'll need to update the dependencies as well:
```
    setup_requires=['setuptools_scm'],  # Support pip versions that don't know about pyproject.toml
    install_requires=[                                                          
        'dnaio~=0.4.2',                                                         
        'xopen~=0.8.4',                                                         
    ],    
    python_requires='>=3.5',                                                    
```

**Comment by adamjstewart** [comment]
So in my understanding, `xopen~=0.8.4` translates to `py-xopen@0.8.4:0.8.999` in Spack's logic.

**Comment by glennpj** [comment]
> So in my understanding, `xopen~=0.8.4` translates to `py-xopen@0.8.4:0.8.999` in Spack's logic.

Okay; I went through all of the versions from 2.0 and up and set the constraints based on that. This should be complete now.

**Comment by glennpj** [comment]
I see some errors in the version translation; one more commit.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
