### PR TITLE
Python libraries incorrectly determined in boost

### PR DESCRIPTION
**Pull request by mdavezac**

### CODE REVIEW

**Comment by adamjstewart** [comment]
I noticed this same bug when I was working on #3293. I'll test this out tomorrow.

**Comment by adamjstewart** [comment]
This does indeed solve the problem for me! Testing now on Python 3.

**Comment by adamjstewart** [comment]
Although things work, I think we can do a lot more to simplify `bjam_python_line`. For example, why are we globbing `incs` if it doesn't contain any glob characters? I'm not sure why multiple Python libraries would be found, but if they were, why not just use the first one instead of using none? Here's what I think things should look like:
```python
def bjam_python_line(self, spec):
    all_libs = glob(spec['python'].python_lib_dir)            
    libs = set([realpath(u) for u in all_libs                               
                if splitext(u)[1] == '.' + dso_suffix])                     
    if len(libs) == 0:                                                      
        libs = set([realpath(u) for u in all_libs if splitext(u)[1] == '.a'])
                                                                                
    # bjam only accepts one library. So if more than one is found, use the first
    if len(libs) > 0:
        libs = libs[0]
    else:
        libs = ''
                             
    return 'using python : {0} : {1} : {2} : {3} ;\n'.format(                       
        spec['python'].version.up_to(2),
        python_exe,
        spec['python'].python_include_dir,
        libs)
```
I think things can be further simplified with the use of `find_libraries` in `lib/spack/llnl/util/filesystem.py`. @alalazo or @davydden may be able to help with this. Can you test this out and play around with it more?

**Comment by mdavezac** [comment]
Fair enough. It'll probably be a week or two until I can get back to it though.

**Comment by adamjstewart** [comment]
@mdavezac I don't want to steal credit for your hard work, but if you want I can open up my own PR with these changes and do some testing.

**Comment by mdavezac** [comment]
That would be great! Frankly, as long as I can do `spack install boost` and have it install stuff automagically, that's all I care about. Just let me know if you do, so we don't repeat each other's work. 
Cheers

**Comment by adamjstewart** [comment]
I'm going to close this as #3367 should be a much more robust solution.

**Pull request closed without merging**
