### PR TITLE
CP2K: Add version 2023.1

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Comment by alalazo** [comment]
I just merged the bugxfix on `libxc` - rebased to check that pipelines still pass.

**Review by alalazo — APPROVED** [review]
Waiting for @dev-zero feedback before merging

**Comment by RemiLacroix-IDRIS** [comment]
@dev-zero : Did you have time to check this PR?

**Review by dev-zero — APPROVED** [review]
sorry for the delay, ACK, thanks for the PR!

**Pull request merged**
