### PR TITLE
netlib-scalapack: add 2.2.0

### PR DESCRIPTION
**Pull request by zzzoom**

### CODE REVIEW

**Comment by zzzoom** [comment]
Build failed on some compilers and needs new patches, closing for the moment.

**Review by alalazo — COMMENTED** [review]
Is there any way to retrieve this patch from a url and apply it directly?

**Comment by zzzoom** [comment]
You could download it from https://github.com/Reference-ScaLAPACK/scalapack/pull/57.diff or https://patch-diff.githubusercontent.com/raw/Reference-ScaLAPACK/scalapack/pull/57.diff, but I don't know how stable those URLs are.

**Comment by zzzoom** [comment]
@alalazo there you go.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
