### PR TITLE
test-install command : added elapsed time + xml is prettyprinted

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications : 
- [x] elapsed time has been added to each test case
- [x] the xml file is pretty-printed
- [x] `FetchError` exceptions are considered as errors in the tests
- [x] `InstallError` exceptions are considered as failures in the tests
- [x] fix unit tests failures due to refactoring  

##### Notes
This is the modified version of `test-install` that we use internally at EPFL. I refactored the file quite a bit, but basically the added features / modified behaviors are the ones listed above.

If in the future we will start allowing for external dependencies, at least for a limited set of commands, then we may consider using [this](https://github.com/kyrus/python-junit-xml) (or similar things) to remove a hundred lines of code or so in `spack`.

### CODE REVIEW

**Comment by tgamblin** [comment]
Checks failed but it looks like a transient problem I've seen a couple times.  I re-triggered the build to see if it goes away b/c I think the bug is unrelated.  This is the issue:

```
==> zmpi is already installed in /tmp/tmpzxPw4t/linux-x86_64/gcc-4.5.0/zmpi-1.0-tpwhotrz7hjsg3dmzuzyofzsugygw4lh
==> Building mpileaks
==> Successfully installed mpileaks
==> Error: mpileaks matches multiple packages:
==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
==> Error: Will not uninstall libelf@0.8.13%gcc@4.5.0-3jwggjl
==> Error: You can use spack uninstall --dependents to uninstall these dependencies as well
```

Anyone seen that?

**Comment by alalazo** [comment]
@tgamblin The error you are seeing is part of the `cmd.uninstall` test case. What was bothering me here is a different behavior in python 2.6 vs 2.7. But it was a bug indeed... :smile:

**Comment by alalazo** [comment]
@tgamblin Just to clarify the line above, the : 
```
==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
==> Error: Will not uninstall libelf@0.8.13%gcc@4.5.0-3jwggjl
==> Error: You can use spack uninstall --dependents to uninstall these dependencies as well
```
is not really an error, it's just a test checking a branch of the code that uses `tty.error`.

**Comment by tgamblin** [comment]
Looks good.  Thanks!

**Pull request merged**
