### PR TITLE
arm: Add version 22.0.2 and rename package from arm to acfl

### PR DESCRIPTION
**Pull request by annop-w**
- Add version 22.0.2
- Rename package from arm to acfl
- Add annop-w as maintainer
- Modify default url to point to version 22.0.2

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by annop-w** [comment]
@alalazo Thank you for fixing the style. Is it now ready to be merged ?

**Comment by alalazo** [comment]
I'm waiting for a review from @OliverPerks Can you explain why this has been renamed?[^1]

[^1]: Renaming packages has been causing issues to people moving across branches with git, so usually we try to avoid that if there isn't a compelling reason.

**Comment by annop-w** [comment]
The main reason is we simply would like the package name to reflect the actual package installed, which is the Arm Compiler for Linux (ACfL) package. ACfL also installs Arm Performance Libraries (ArmPL), which we would like to expose later (in a separate commit). There are currently 2 versions of ArmPL: one compiled with Arm compiler and one compiled with GNU compiler. The version with GNU compiler can be installed via the armpl-gcc package in Spack.

I discussed with @OliverPerks some time ago and we seemed to agree with the above. Does this make sense ?

**Comment by annop-w** [comment]
@alalazo Seems like Oliver is not available. Can somebody else review this ?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@annop-w Merged, this has been sitting here long enough :wink:

**Comment by annop-w** [comment]
@alalazo Thank you. I wanted this merged because we now have new releases for ACfL and ArmPL. So, two new PRs coming in soon 😉

**Comment by alalazo** [comment]
@annop-w Feel free to ping me on those, thanks!

**Pull request merged**
