### PR TITLE
gaudi: Add version 38 and a gaudialg variant

### PR DESCRIPTION
**Pull request by jmcarcell**
gaudialg introduced here for 37: https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1444 and disabled by default here for 38: https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1531

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Waiting for maintainers review before merging

**Comment by wdconinc** [comment]
Did you check that 37.0 builds with `~gaudialg` but other variants incl test enabled? Wondering if there are more potential cases like https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1474.

**Comment by vvolkl** [comment]
For, me there's no difference between 37.0+gaudialg and 37.0~gaudialg, however both fail with:
```
Total Test time (real) =  60.37 sec

The following tests did not run:
        239 - GaudiExamples.jira.gaudi_1174 (Disabled)
        279 - GaudiExamples.root_io.extcoll.read (Disabled)
        280 - GaudiExamples.root_io.extcoll.write (Disabled)
        291 - GaudiExamples.skipped_test (Skipped)

The following tests FAILED:
         35 - GaudiKernel.pytest.nose.test_Configurables (Failed)
        173 - GaudiExamples.pytest.test_opts_export (Failed)
        225 - GaudiExamples.google_auditors.heapchecker (Failed)
        226 - GaudiExamples.google_auditors.heapprofiler (Failed)
Errors while running CTest
Output from these tests are in: /tmp/root/spack-stage/spack-stage-gaudi-37.0-aydufk7vxh6a7s2zsnmqhjea7xrikohy/spack-build-aydufk7/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:94: test] Error 8
```
The  spec I used was was 
```
gaudi@37.2%gcc@12.1.0+aida+cppunit~docs+examples~gaudialg+gperftools+heppdt+ipo+jemalloc+unwind~vtune+xercesc build_system=cmake build_type=Release generator=make arch=linux-centos7-zen2 ^root@6.28.10~x
```

Tests 35 and 173 should be fixed by https://github.com/spack/spack/pull/43116/files

**Comment by wdconinc** [comment]
dd4hep installs fine with the new variant set to off, but downstream packages fail due to references to `Gaudi::GaudiAlgLib` that have not had a chance to propagate to using this variant (e.g. https://github.com/key4hep/k4FWCore/blob/main/k4FWCore/CMakeLists.txt#L31). I think the default should therefore remain true for some time.

**Comment by wdconinc** [comment]
> I think the default should therefore remain true for some time.

I guess there's really no reason to believe that downstream users will find out about the existance of this new variant, and if we switch it from `True` to `False` later on we'll just have the same problem of breaking workflows. So, I'm just going to approve as is.

**Review by wdconinc — APPROVED** [review]

**Comment by jmcarcell** [comment]
> > I think the default should therefore remain true for some time.
> 
> I guess there's really no reason to believe that downstream users will find out about the existance of this new variant, and if we switch it from `True` to `False` later on we'll just have the same problem of breaking workflows. So, I'm just going to approve as is.

My thinking was that building gaudi outside of spack will now cause downstream packages to break if they use GaudiAlg so from the packaging point of view we're just replicating what one would find with gaudi standalone.

**Pull request merged**
