### PR TITLE
Remove centos:6 image references

### LINKED ISSUE #26096: CentOS 6 image doesn't build with clingo on Dockerhub
### Steps to reproduce

Has to do with failure on centos:6

```
Step 17/19 : RUN spack spec hdf5+mpi
 ---> Running in 8335d48ff53f
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> Warning: the original concretizer is currently being used.
        Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack starting at v0.18.0
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64"
Input spec
--------------------------------
hdf5+mpi

Concretized
--------------------------------
==> Bootstrapping clingo from pre-built binaries
The command 'docker-shell spack spec hdf5+mpi' returned a non-zero code: 3
```

---

So it bootstraps *during* concretization?

### PR DESCRIPTION
**Pull request by haampie**
closes #26155
closes #26096

This was EOL November 30th, 2020. I believe the "builds" are failing on develop because of it.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]
I''d really like to remove this, but last time I checked with other core devs `centos:6` was still used and we agreed to go with the fix in #24804. Bottomline +1 from me to delete this, but pinging other reviewers for comments before merging.

**Comment by haampie** [comment]
It turns out there is some legit issue https://github.com/spack/spack/issues/26096 regarding bootstrapping, so converting this into a draft.

Otherwise we should say 'no' to people using EOL distros :D

**Comment by haampie** [comment]
```
  Could not fetch URL https://pypi.python.org/simple/boto3/: 403 Client Error: SNI is required - skipping
  Could not find a version that satisfies the requirement boto3 (from versions: )
No matching distribution found for boto3
```

On the 0.16.3 backports this is the release blocker after cherry-picking 2a858f8f3d18ac22eff6ceccb3ceb44e5ad93486

---

The issue is https://github.com/pypa/pypi-support/issues/978

For users of Python 2.6.x and lower:
Neither the Python core developers, or pip maintainers support Python 2.6 and below.
If someone is aware of a work around for this issue (SNI support specifically) they are welcome to share it here for others.
There is no recommended solution from the PyPI team.

**Comment by alalazo** [comment]
Cherry pick also #24813

**Comment by alalazo** [comment]
Even though I'd really prefer to remove this since maintenance becomes problematic.

**Comment by haampie** [comment]
Let's please remove centos:6, our support makes no sense whatsoever. We currently download a repo from a completely arbitrary website https://www.getpagespeed.com/files/centos6-eol.repo without checksum validation, it looks very shady... Better get this PR in and be done with a distro that's been EOL for almost a year.

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
