### PR TITLE
Build multiple FFTW variants simultaneously

### PR DESCRIPTION
**Pull request by eschnett**
FFTW can build only one floating point precision (float, double, long double, quad) at once, but they can all be installed simultaneously as the libraries have different names. It is common packages to decide only at run time which precision FFTW they need, and thus FFTW should offer all precisions at once.

### CODE REVIEW

**Comment by tgamblin** [comment]
I actually think I like this version better.  @nrichart, @alalazo: do you have any issues with this?  If the libraries have different names and that's the usual way of linking, I think offering all of them is probably the most robust way to install.

**Comment by alalazo** [comment]
If there are no incompatibilities with headers / FORTRAN modules I agree that this modification is an improvement over the previous one. The only minor change I would suggest is to change the default for quad precision to `True` (so that the default will be install everything you can in serial mode). @nrichart has more experience with this library than I do, so he may have more to say.

**Comment by eschnett** [comment]
`+quad` requires gcc (and conflicts with `+mpi`).

**Comment by alalazo** [comment]
@eschnett : good enough as it is then! :-)

**Pull request merged**
