### PR TITLE
Xl default flags

### PR DESCRIPTION
**Pull request by serbanmaerean**
Change the default Fortran flags for the XL compiler to only "-qzerosize" from "-qzerosize -qfixed".

### CODE REVIEW

**Comment by tgamblin** [comment]
@serbanmaerean: Thanks! FYI, it looks like you're still pulling in a lot of extra commits on your branches.  I'll still squash and merge these changes and they'll appear as one collapsed commit when they go on `develop`.

**Comment by serbanmaerean** [comment]
@tgamblin: my extra commit were due to the fact that my fork was out of sync with the ustream and I wanted to clean it up.  I took the hard way, apparently, but in the end I have a clean develop branch in my fork that is in sync w/the upstream and I have other changes in different branches.
One question is, going forward, I want to add a package for IBM MPI (spectrum-mpi).  I will drop that next, as many other packages depend on it.

**Comment by pramodk** [comment]
>  I want to add a package for IBM MPI (spectrum-mpi). 

@serbanmaerean : just curious : I assume IBM provides binary / rpm packages for customers only (?). Are you planning to create package for the installer? (Or just setting environment for pre-installed package?)

**Comment by serbanmaerean** [comment]
Yes, IBM Spectrum MPI is a commercial product.  I will create a package for Spectrum MPI as an external package.

**Pull request merged**
