### PR TITLE
Add package for Julia

### PR DESCRIPTION
**Pull request by eschnett**
Note that this branch is based on the `correct-cc` branch, not on the `develop` branch.

### CODE REVIEW

**Comment by aashish24** [comment]
Nice @eschnett !

**Comment by tgamblin** [comment]
@eschnett: even though you're basing it on `correct-cc`, when you do a PR into develop, the other stuff comes with it (PRs are like `rebase --onto`.  Can you factor the Julia stuff out and submit it separately, or does it need something in `correct-cc`?

**Comment by eschnett** [comment]
@tgamblin I've separated out the Julia changes; it's now based on a recent `develop`.

**Comment by tgamblin** [comment]
Thanks!  I'll merge this; I normally don't like commented out code but I think the notes here are really useful!

I think I need to look through this and also some of @nrichart and @alalazo's proposal for how best to handle BLAS, LAPACK, and external dependencies.  I'll revisit this stuff after #120 is merged.

**Pull request merged**
