### PR TITLE
Update cmake to build with the IBM XL compilers

### PR DESCRIPTION
**Pull request by serbanmaerean**
I need to merge the following commit from serbanmaerean/spack:
commit 7504d57cf5baf4387288d7d9f462f305350b2945
Author: Serban Maerean <serban@us.ibm.com>
Date:   Fri Jan 27 14:23:56 2017 -0500

    Update cmake to work with the IBM XL compilers (xl and xl_r)
    
    Due to differences in how the -qstrict flag is handled in the f77 and
    f90 XL compilers, we created some uniformity by using the -qstrict
    Fortran compiler flag by default. The package files can undo the default
    setting by using the -qfree option (as the last option wins.)
    The problem occurs when cmake builds test programs to detect compiler
    capabilities, as it uses the default flags.  Consequently, f90 test
    programs in free form will fail to build with the -qstrict flag.
    
    This commit changes the free form for the cmake test programs to strict
    form, to allow the use of both f77 and f90 compilers.
    
    Install cmake under spack for XL compilers as follows:
    
    spack install cmake%xl_r+openssl+ncurses^openssl%gcc^ncurses%gcc
    
    This will build openssl and ncurses with the gcc compiler (there is
    no openssl and ncurses code in the final math library) and cmake with
    the xl(_r) compiler.

### CODE REVIEW

**Comment by davydden** [comment]
have not you already added `xl_r` compilers in https://github.com/LLNL/spack/pull/2894 ?  Should not this PR contain only extra patches for `cmake`?

**Comment by serbanmaerean** [comment]
That's what I wanted to do, i.e. add only the changes for cmake.  I need to rebase my fork, correct?  Does a git fetch from llnl/spack will do that?

**Comment by davydden** [comment]
@serbanmaerean please read through https://spack.readthedocs.io/en/latest/contribution_guide.html#git-workflows . A few advises: you generally don't want to do anything locally on `develop`. I find it more convent if your local `develop` tracks remote `develop`. Then you do `git pull` locally and everything is up-to-date and ready to roll. For PR one normally create a separate branch. So once you are on a fresh `develop`, you do `git checkout -b my_feature_name` and work from there. That's where you would commit only changes to `cmake` package and extra patches.

**Comment by davydden** [comment]
you could do something along the lines
```
# starting from your current develop
git checkout -b develop_backup
git checkout develop
git reset --hard <your-name-for-spack-remote>/develop
```
and create a new branch...

**Comment by tgamblin** [comment]
@serbanmaerean: just that one and not the other here?  I think things are going to be easier for you if you do your PRs on separate branches in your fork, rather than on develop.  See [branching](https://spack.readthedocs.io/en/latest/contribution_guide.html#branching) in the contributor guide.

In general here is what I would do to get to a more consistent state:

```console
git remote add upstream https://github.com/LLNL/spack.git   # add main spack repo as a remote
git fetch upstream   # sync state with upstream (note this doesn't change any of your local data)

# now create a branch for the pull request *based on upstream develop*
git checkout -b ibm-cmake-support upstream/develop 

# cherry-pick the one commit you want onto that branch.
git cherry-pick 7504d57

# Push the new branch into your fork and create a new pull request from it
git push origin ibm-cmake-support
```

You really want to have YOUR `develop` branch in sync with upstream develop.  Currently you're making all your changes on your own develop branch.  Others including you are modifying upstream develop, so if you try to pull from upstream your commits will be in the way of remote changes.  

Probably you want to do this:

```console
# rename your current develop branch to something unique to you.
git branch -m develop saerbans-changes

# fresh checkout of out your fork's develop branch 
git checkout -t origin/develop

# pull changes from upstream onto your local develop branch
git pull upstream develop

# Force-push upstream develop into your fork, so it is in sync.
# You only need to use `-f` this once.  in the future it will be in
# sync so a simple push will do
git push -f origin develop
```

When I am working on a `github` project, I *only* ever pull `upstream/develop` into my `develop` branch.  That allows me to stay in sync with the upstream project, compare my changes to those on develop, etc.  I make my changes on separate branches, and periodically rebase them onto `develop`, or merge `develop` into them.  The key is that all your changes are made on side branches, and you only receive changes from upstream on `develop`.  Other git workflows may keep `master` as the main branch, but otherwise the general idea is the same.

**Pull request closed without merging**
