### PR TITLE
Add numactl dependency to hip dependents

### PR DESCRIPTION
**Pull request by haampie**
hipcc 3.7.0 always adds an `-lnuma` linker flag, meaning that numactl
should be a link dependency of all packages using it.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@srekolam @arjun-raj-kuppala can you review?

**Comment by srekolam** [comment]
I have already added numactl dependency for some of the math libs through #18495 and #18497 .

**Comment by haampie** [comment]
Ping @srekolam / @arjun-raj-kuppala, can you check this out again? It adds some missing dependencies on numactl

**Review by srekolam — APPROVED** [review]

**Comment by adamjstewart** [comment]
Why not just add `numactl` as a dependency of `hip`?

**Comment by haampie** [comment]
hipcc actually adds this package as a dependency, but it might itself be just a build dep, since it's a compiler. Maybe some (all?) packages currently use hip as a link dep too, in which case your suggestion would work indeed @adamjstewart what do you think?

**Comment by adamjstewart** [comment]
Hmm, compilers are complicated. You can think of them as a build dependency because you can uninstall the compiler and your installation will still work. But the compiler may provide libraries that need to be linked to (for example, GCC provides libstdc++ and things like that). So I would add `hip` as a build/run dependency instead.

**Comment by adamjstewart** [comment]
Is this PR still needed? It seems pretty outdated now.

**Comment by haampie** [comment]
I'm just gonna close it for now

**Pull request closed without merging**
