### PR TITLE
Adding a flag to solve 'undefined reference to libintl_dgettext' in extrae package

### PR DESCRIPTION
**Pull request by kserradell**
Related to #3213 and #3216.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I tried building binutils on Linux (from develop, without this change). Although it seems to build fine, I'm also seeing this missing symbol:
```
$ ldd -r libopcodes.so 
	linux-vdso.so.1 (0x00007ffd369dc000)
	libbfd-2.27.so => /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/binutils-2.27-5lkml3x6kntz6ipdqigkrnzle7umnqqe/lib/libbfd-2.27.so (0x00007fa12c27a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa12be97000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa12bc93000)
	/lib64/ld-linux-x86-64.so.2 (0x000055aa37d87000)
undefined symbol: libintl_dgettext	(/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/binutils-2.27-5lkml3x6kntz6ipdqigkrnzle7umnqqe/lib/libbfd-2.27.so)
undefined symbol: libintl_dgettext	(./libopcodes.so)
```
Should we consider adding a gettext dependency instead of disabling nls? I'm not sure how often users will need i18n support.

**Comment by adamjstewart** [comment]
@kserradell Does #3423 fix this for you?

**Comment by kserradell** [comment]
@adamjstewart, I tested but I can't clone the repo.

```
==> Trying to clone git repository:
  git://git.fedorahosted.org/git/elfutils.git
  at tag elfutils-0.163
Cloning into 'elfutils'...
fatal: unable to connect to git.fedorahosted.org:
git.fedorahosted.org[0: 140.211.169.199]: errno=Connection refused

Cloning into 'elfutils'...
fatal: unable to connect to git.fedorahosted.org:
git.fedorahosted.org[0: 140.211.169.199]: errno=Connection refused
```

**Comment by adamjstewart** [comment]
You can change the URL to point to a release:
https://sourceware.org/elfutils/ftp/

Honestly, we should probably be doing that already. Feel free to submit a PR with just that change.

**Comment by kserradell** [comment]
Done

**Comment by kserradell** [comment]
@adamjstewart, extrae fails now with elfutils@0.168

**Pull request closed without merging**
