### PR TITLE
libjpeg-turbo: fixed sha256

### LINKED ISSUE #17153: Incorrect sha256sum for libjpeg-turbo@2.0.4
There is a mismatch between the shasum in the recipe and the shasum of the tarball hosted on github. (Note that the shasum matches that of the tarball at the sourceforge mirror)  Bug seems to have been introduced in #17132

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git
$ source spack/share/spack/setup-env.sh
$ spack install libjpeg-turbo@2.0.4
```
### Information on your system
Spack debug report:
```console
* **Spack:** 0.14.2-1480-1de20f0
* **Python:** 2.7.5
* **Platform:** linux-centos7-skylake
```

### Additional information
No build logs created.

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files (N/A)
- [x] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alalazo**
fixes #17153 

Modifications:

- [x] Fixed sha256 for v2.0.4
- [x] Docstring has now a short first sentence and then a longer description in a following paragraph

### CODE REVIEW

**Comment by alalazo** [comment]
@ptooley

**Comment by ikitayama** [comment]
Is this merged to develop?

**Comment by ikitayama** [comment]
@alalazo @scheibelp ?

**Comment by alalazo** [comment]
@ikitayama Yes, it was merged 27 days ago in commit 6d9f0262de6269b895673315a1c36c4f6888419e

**Pull request merged**
