### PR TITLE
pmix: add 4.2.4 and disable munge explicitly

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Deferring merge to give @rhc54 time to comment, especially since this PR involves an option change.

**Review by rhc54 — COMMENTED** [review]
Not sure how to advise you here. Leaving out munge support only impacts the application proc's connection to the Slurm stepd.

If both the Slurm plugin and the app are using the same PMIx installation, then the configure option doesn't matter. I suspect that is the expected environment? If so, then this is fine. Means that you won't get failures if the munge daemon isn't running for some reason (I don't recall - does Slurm allow that?).

If the Slurm plugin and app are using different installations, then this will cause failures if the  app used this package while the PMIx installation used by Slurm was configured with munge _and_ the plugin mandated its use. Not sure if that is a supported configuration or not - just pointing it out.

**Comment by michaelkuhn** [comment]
> Not sure how to advise you here. Leaving out munge support only impacts the application proc's connection to the Slurm stepd.

I ran into similar messages as in https://github.com/open-mpi/ompi/issues/11557 and noticed during debugging that we don't explicitly disable Munge, so PMIx could pick it up if it is installed on the system (I still get the same messages with `--without-munge`, though). If we want to enable it explicitly, we should add a proper dependency on Munge.

**Comment by tldahlgren** [comment]
@michaelkuhn @rhc54 Let me know when this is ready to merge.

**Comment by rhc54** [comment]
@tldahlgren I have no issues committing this as-is. I'll talk to SchedMD about how we should handle the PMIx client-server connections wrt munge going forward.

**Pull request merged**
