### PR TITLE
opendjk: add 11.0.23+9, 17.0.11+9, 21.0.3+9

### PR DESCRIPTION
**Pull request by dialvarezs**

### CODE REVIEW

**Comment by wdconinc** [comment]
Should we update the preferred version from 11 to 21 too? Or is that still appropriate? You added this in https://github.com/spack/spack/commit/5f928f71c0fe3957dfa2d30204c9cfe9a59526e4.

https://github.com/spack/spack/blob/3a6afcd34ba63a7665295841eea178614406506c/var/spack/repos/builtin/packages/openjdk/package.py#L396

**Comment by wdconinc** [comment]
All checksums verified.

**Comment by dialvarezs** [comment]
@wdconinc I was wondering the same.
If you ask me, I would be a little more conservative and stick with 17 for now that has been out for more than 2 years.
I am not aware if is there any software that could be broken by this, but I guess those packages can specify java@11 directly.

**Comment by wdconinc** [comment]
> stick with 17 for now

Sounds good with me. Another approach could be to raise it more gradually: 15 now, 16 later, etc.

There are too many dependencies here to test them all, but you could also test a few key packages. Not sure how you'd select those though (those with a dependency on openjdk regardless of variant, or for default variant, and that have had a change in the last half year or so?).

**Comment by wdconinc** [comment]
> you could also test a few key packages

This is just a suggestion since openjdk is a key package. There is no expectation that you test downstream packages.

**Comment by dialvarezs** [comment]
> Another approach could be to raise it more gradually: 15 now, 16 later, etc.
Right now 15 and 16 are unsupported, only 17 because it's an LTS.

I can try a few packages, and make a new PR for that.

**Review by wdconinc — APPROVED** [review]
I was able to install all three new versions on x86_64.

**Pull request merged**
