### PR TITLE
[TAU Package] Updates for rocm

### PR DESCRIPTION
**Pull request by jordialcaraz**
Updated for rocm@6
Added conflict between rocprofiler and roctracer.
Request either +rocprofiler or +roctracer when +rocm. In this case, it automatically builds for one, instead of displaying the message.  Request +rocm when using either +rocprofiler or +roctracer. In this case, it automatically builds with +rocm, instead of displaying the message.

Disabled the tests. Will update them with the new test method.

@spackbot fix style
@spackbot help

### CODE REVIEW

**Comment by jordialcaraz** [comment]
Should I add myself to maintainers to receive messages?

**Comment by jordialcaraz** [comment]
Can test using Omnia with:

spack install -v tau@master+roctracer ^rocm-core@6.0.0 %gcc@11;spack install -v tau@master+rocprofiler ^rocm-core@6.0.0 %gcc@11; spack install -v tau@master+roctracer+rocprofiler ^rocm-core@6.0.0 %gcc@11; spack find -v -p tau

This one should fail and show the conflicts:
spack install -v tau@master+roctracer+rocprofiler


Tau should have tag rocmv6 (shared-rocm-rocprofiler-rocmv6-papi-pthread-pdt) after being installed.

**Comment by jordialcaraz** [comment]
@spackbot fix style

**Comment by jordialcaraz** [comment]
@spackbot help

**Comment by eugeneswalker** [comment]
Will these changes be compatible with ROCm 5.7.1? Do you know?

**Comment by jordialcaraz** [comment]
The conflicts and requires should be like that for any version of TAU with rocm support. 

The other part is only to detect if we are using rocmv6  to enable the rocmv6 related parts of TAU's configure script. So it has no effect when using ROCM 5.7.1 or older version. Also, the changes are only required if ROCm is installed using spack, if ROCm was installed with apt or yum, there is no effect. If the question is regarding the E4S release, I already talked with Sameer and this is not necessary for the new release.

**Comment by jordialcaraz** [comment]
Thinking about it a bit more. It could affect rocm-5.7.1 but I was never able to build it succesfully with Spack, I always had issues with a library. I even opened an issue about it, but the answer was that the library was not included with Spack packages and only available with apt or yum. So it does not affect rocm-5.7.1 as the use case were it would be needed, does not work for ROCm versions olden than 6.0.0.

**Comment by jordialcaraz** [comment]
Any additional comments?

**Review by eugeneswalker — APPROVED** [review]
Thanks!

**Pull request merged**
