### PR TITLE
strumpack: Patch for building shared lib when enabling ROCm.

### PR DESCRIPTION
**Pull request by pghysels**
Fixes this issue: https://github.com/spack/spack/issues/25225

A fix is in STRUMPACK master, so will be in future releases:
https://github.com/pghysels/STRUMPACK/commit/23f2e974e51306f3a4c6eec5463480d080dfc411

@eugeneswalker could you try this?

### CODE REVIEW

**Comment by eugeneswalker** [comment]
> @eugeneswalker could you try this?

I cherry-picked this commit and now getting this error:
```
4 errors found in build log:
     85    cd /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts && /spack/opt/spack/linux-ubunt
           u20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -E make_directory /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw
           /spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/.
     86    cd /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts && /spack/opt/spack/linux-ubunt
           u20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=RELWITHDEBINFO -D generated_file:STRING=/tmp/root/sp
           ack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_generated_FrontalMatrixHIP.hip.cpp
           .o -P /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/strumpack_generated_FrontalM
           atrixHIP.hip.cpp.o.cmake
     87    -- Removing /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_generated_
           FrontalMatrixHIP.hip.cpp.o
     88    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -E remove /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dt
           js4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_generated_FrontalMatrixHIP.hip.cpp.o
     89    -- Generating dependency file: /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/str
           umpack_generated_FrontalMatrixHIP.hip.cpp.o.depend.pre
     90    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hip-4.2.0-6ztqrqnwwfcholfcndkn4niectkxmlda/bin/hipcc -M /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suu
           z5rm7gnflw/spack-src/src/sparse/fronts/FrontalMatrixHIP.hip.cpp -o /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles
           /strumpack.dir/src/sparse/fronts/strumpack_generated_FrontalMatrixHIP.hip.cpp.o.depend.pre --amdgpu-target=gfx906 -D__HIP_PLATFORM_HCC__=1 -D__HIP_PLATFORM_AMD__=1 --shared -Xcompi
           ler '-fPIC' -I/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-src/src -I/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4ch
           b5suuz5rm7gnflw/spack-build-mpnyxk2 -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qspz2o4tb7pc6mk2cafuklj/include -I/spack/opt/spack/linux-ubuntu20.04-
           x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qspz2o4tb7pc6mk2cafuklj/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qspz2o4tb7pc6mk2cafuklj/include -I/
           spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/parmetis-4.0.3-rdrwwqrizoiz4h3xiehqqwfzimpuv5zh/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/metis-5.1.0-lxkd2th
           zi5xc5z3aqvw4eodot57r53y5/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zfp-0.5.5-bu5zrporgont6p2ppehprhd3j7w22uxt/include -I/spack/opt/spack/linux-ubuntu20.04-x86_
           64/gcc-9.3.0/butterflypack-1.2.1-xr64oqutguponm7k2m252cdyxpe7ndus/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/butterflypack-1.2.1-xr64oqutguponm7k2m252cdyxpe7ndus
           /include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hipblas-4.2.0-hnr6sro7h7s6xvdxsyg5iqxp6z364bws/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hipblas-
           4.2.0-hnr6sro7h7s6xvdxsyg5iqxp6z364bws/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocblas-4.2.0-5sfe5wjjm6g6nqqjpzn5o4swk3mxugjp/include -I/spack/opt/spack/linux
           -ubuntu20.04-x86_64/gcc-9.3.0/rocblas-4.2.0-5sfe5wjjm6g6nqqjpzn5o4swk3mxugjp/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hip-4.2.0-6ztqrqnwwfcholfcndkn4niectkxmld
           a/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hsa-rocr-dev-4.2.0-i4ob2ubvtr4dpaogzjqi2ux4z24yjzkg/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/ro
           csolver-4.2.0-efs6jkuxldtr7rat2rbsxu7r5c7igtx5/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocsolver-4.2.0-efs6jkuxldtr7rat2rbsxu7r5c7igtx5/include
  >> 91    clang-12: error: no such file or directory: ''-fPIC''
  >> 92    CMake Error at strumpack_generated_FrontalMatrixHIP.hip.cpp.o.cmake:138 (message):
     93      Error generating
     94      /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_generated_FrontalMat
           rixHIP.hip.cpp.o
     95
     96
  >> 97    make[2]: *** [CMakeFiles/strumpack.dir/build.make:80: CMakeFiles/strumpack.dir/src/sparse/fronts/strumpack_generated_FrontalMatrixHIP.hip.cpp.o] Error 1
     98    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2'
  >> 99    make[1]: *** [CMakeFiles/Makefile2:961: CMakeFiles/strumpack.dir/all] Error 2
     100   make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-mpnyxk2'
     101   make: *** [Makefile:149: all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-mpnyxk25y2dtjs4chb5suuz5rm7gnflw/spack-build-out.txt
```

**Comment by pghysels** [comment]
Sorry, I had tested with the master branch, not with 5.1.1., and I have since update the FindHIP.cmake. I'm trying to figure out where the quotes are added around '-fPIC'.

**Comment by eugeneswalker** [comment]
Should I try this again?

**Comment by pghysels** [comment]
Yes, please if you don't mind. 
I pushed a fix so I think it should work now. But I didn't test it through spack because I have been stuck compiling rocBLAS.

**Comment by eugeneswalker** [comment]
Using your branch I still get this error:

```
...
==> Installing strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t
==> Fetching https://mirror.spack.io/_source-cache/archive/6c/6cf4eaae5beb9bd377f2abce9e4da9fd3e95bf086ae2f04554fad6dd561c28b9.tar.gz
==> Applied patch /spack/var/spack/repos/builtin/packages/strumpack/shared-rocm.patch
==> strumpack: Executing phase: 'cmake'
==> strumpack: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     85    cd /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/spar
           se/fronts && /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -E make_directory
           /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/sparse/
           fronts/.
     86    cd /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/spar
           se/fronts && /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -D verbose:BOOL=1
           -D build_configuration:STRING=RELWITHDEBINFO -D generated_file:STRING=/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5
           sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_generated_FrontalMatrixHIP.hip.cpp.o -P /tmp/root/
           spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/sparse/fronts/str
           umpack_generated_FrontalMatrixHIP.hip.cpp.o.cmake
     87    -- Removing /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir
           /src/sparse/fronts/./strumpack_generated_FrontalMatrixHIP.hip.cpp.o
     88    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5/bin/cmake -E remove /tmp/root/spack-stage
           /spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/sparse/fronts/./strumpack_ge
           nerated_FrontalMatrixHIP.hip.cpp.o
     89    -- Generating dependency file: /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMake
           Files/strumpack.dir/src/sparse/fronts/strumpack_generated_FrontalMatrixHIP.hip.cpp.o.depend.pre
     90    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hip-4.2.0-6ztqrqnwwfcholfcndkn4niectkxmlda/bin/hipcc -M /tmp/root/spack-stage/spack-sta
           ge-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-src/src/sparse/fronts/FrontalMatrixHIP.hip.cpp -o /tmp/root/spack-stage/spack-sta
           ge-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/sparse/fronts/strumpack_generated_Fron
           talMatrixHIP.hip.cpp.o.depend.pre --amdgpu-target=gfx906 -D__HIP_PLATFORM_HCC__=1 -D__HIP_PLATFORM_AMD__=1 --shared -Xcompiler '-fPIC' -I/t
           mp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-src/src -I/tmp/root/spack-stage/spack-stage-strumpac
           k-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qsp
           z2o4tb7pc6mk2cafuklj/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qspz2o4tb7pc6mk2cafuklj/include -I/
           spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-nawpdrhj3qspz2o4tb7pc6mk2cafuklj/include -I/spack/opt/spack/linux-ubuntu20.0
           4-x86_64/gcc-9.3.0/parmetis-4.0.3-rdrwwqrizoiz4h3xiehqqwfzimpuv5zh/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/metis-5.1.
           0-lxkd2thzi5xc5z3aqvw4eodot57r53y5/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zfp-0.5.5-bu5zrporgont6p2ppehprhd3j7w22uxt
           /include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/butterflypack-1.2.1-xr64oqutguponm7k2m252cdyxpe7ndus/include -I/spack/opt/sp
           ack/linux-ubuntu20.04-x86_64/gcc-9.3.0/butterflypack-1.2.1-xr64oqutguponm7k2m252cdyxpe7ndus/include -I/spack/opt/spack/linux-ubuntu20.04-x8
           6_64/gcc-9.3.0/hipblas-4.2.0-hnr6sro7h7s6xvdxsyg5iqxp6z364bws/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hipblas-4.2.0-h
           nr6sro7h7s6xvdxsyg5iqxp6z364bws/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocblas-4.2.0-5sfe5wjjm6g6nqqjpzn5o4swk3mxugj
           p/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocblas-4.2.0-5sfe5wjjm6g6nqqjpzn5o4swk3mxugjp/include -I/spack/opt/spack/l
           inux-ubuntu20.04-x86_64/gcc-9.3.0/hip-4.2.0-6ztqrqnwwfcholfcndkn4niectkxmlda/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/
           hsa-rocr-dev-4.2.0-i4ob2ubvtr4dpaogzjqi2ux4z24yjzkg/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocsolver-4.2.0-efs6jkuxl
           dtr7rat2rbsxu7r5c7igtx5/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/rocsolver-4.2.0-efs6jkuxldtr7rat2rbsxu7r5c7igtx5/incl
           ude
  >> 91    clang-12: error: no such file or directory: ''-fPIC''
  >> 92    CMake Error at strumpack_generated_FrontalMatrixHIP.hip.cpp.o.cmake:138 (message):
     93      Error generating
     94      /tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu/CMakeFiles/strumpack.dir/src/spars
           e/fronts/./strumpack_generated_FrontalMatrixHIP.hip.cpp.o
     95
     96
  >> 97    make[2]: *** [CMakeFiles/strumpack.dir/build.make:80: CMakeFiles/strumpack.dir/src/sparse/fronts/strumpack_generated_FrontalMatrixHIP.hip.c
           pp.o] Error 1
     98    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu'
  >> 99    make[1]: *** [CMakeFiles/Makefile2:961: CMakeFiles/strumpack.dir/all] Error 2
     100   make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-strumpack-5.1.1-5hejtuutkcqtwmsycq5sigk54jpemv3t/spack-build-5hejtuu'
     101   make: *** [Makefile:149: all] Error 2

```

**Comment by eugeneswalker** [comment]
Do you have an account on the University of Oregon NIC/Frank systems?  If so I could give you access to my Docker build container, which already has the hipblas and big dependencies built.

**Comment by pghysels** [comment]
Hi, sorry no I do not have a Frank account.
But I managed to build rocblas now, and I reproduced your issue and pushed a fix.
```
spack find -Lv | grep "strumpack"
tyafonmgypelohdpcfyumadiizrqv3ad strumpack@5.1.1~build_dev_tests~build_tests+butterflypack+c_interface~count_flops~cuda~ipo+mpi+openmp+parmetis+rocm~scotch+shared~slate~task_timers+zfp amdgpu_target=gfx906 build_type=RelWithDebInfo cuda_arch=none patches=9b504fc58c17fe32fcb605564c21547f8bdbd6b495f77f7af5c91fb38d617806
```

**Review by eugeneswalker — APPROVED** [review]
Worked for me! Thank you!

**Comment by eugeneswalker** [comment]
Should we merge?

**Comment by balay** [comment]
I think it would be good to test if strumpack@master also works - before merging..

**Comment by pghysels** [comment]
Good idea. That works for me. The master has a fix for this, so it doesn't need the patch.
```
spack find -Lv | grep "strumpack" | grep "+rocm"
tyafonmgypelohdpcfyumadiizrqv3ad strumpack@5.1.1~build_dev_tests~build_tests+butterflypack+c_interface~count_flops~cuda~ipo+mpi+openmp+parmetis+rocm~scotch+shared~slate~task_timers+zfp amdgpu_target=gfx906 build_type=RelWithDebInfo cuda_arch=none patches=9b504fc58c17fe32fcb605564c21547f8bdbd6b495f77f7af5c91fb38d617806
sof2ua2lemfdw4uxccpbbzu7vgcng3xx strumpack@master~build_dev_tests~build_tests+butterflypack+c_interface~count_flops~cuda~ipo+mpi+openmp+parmetis+rocm~scotch+shared~slate~task_timers+zfp amdgpu_target=gfx906 build_type=RelWithDebInfo cuda_arch=none

```

**Comment by eugeneswalker** [comment]
Worked for me too!

**Pull request merged**
