### PR TITLE
Octave pcre2

### PR DESCRIPTION
**Pull request by davidedelvento**
Explicit dependency on PCRE2 only when desired and if so specifying the correct spack-installed location, to avoid inadvertently pulling in the system-installed version which leads to bug #39090

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
@samcmill Any issues or concerns with merging this PR?

**Comment by samcmill** [comment]
> @samcmill Any issues or concerns with merging this PR?

This PR does not touch anything I watch, so no opinion.

**Comment by tldahlgren** [comment]
> > @samcmill Any issues or concerns with merging this PR?
> 
> This PR does not touch anything I watch, so no opinion.

My apologies.  I was simultaneously reviewing two PRs and changed focus to the wrong one when I added that note.

**Comment by tldahlgren** [comment]
@mtmiller Any issues or concerns with merging this PR?

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@davidedelvento Can you solve the conflict?

**Comment by davidedelvento** [comment]
Looks like github does not have a nice way to go line-by-line and just mark the description as the appropriate way to solve the conflict, so I need to go into my file and edit that. Will do, but sorry for the wait

**Comment by davidedelvento** [comment]
I added the commits https://github.com/spack/spack/pull/39126/commits/857587a3afa28a644a9f6316916d91142bfccef1 and 
https://github.com/spack/spack/pull/39126/commits/f191194e0985e4c327493ed138cc2dbc21dab560 (as it is shown in this description right above this comment) but the [diff tab](https://github.com/spack/spack/pull/39126/files) in this PR hasn't updated accordingly yet at time of writing. Not sure if GH will eventually update it or if anybody (I??) need to do anything to trigger that

**Comment by davidedelvento** [comment]
And by the way, I actually dislike this way of setting the description, which does not add any information and feels very error-prone and just a typo waiting to happen. Couldn't the variant call automatically create a description by querying the relevant package for its preferred name and prefix that by "Use " instead? That would have been more robust, in my humble opinion. Even if there is not a "preferred name" yet in packages (in such a case the string of the package name could be used as a backup) adding that would have been just a single line for each package. This way is all dependencies for each package which feels like a nightmare. But, as it usually happen, I digress... and should have done so in a different context, not here, sorry about that.

**Comment by tldahlgren** [comment]
> I added the commits [857587a](https://github.com/spack/spack/commit/857587a3afa28a644a9f6316916d91142bfccef1) and
> [f191194](https://github.com/spack/spack/commit/f191194e0985e4c327493ed138cc2dbc21dab560) (as it is shown in this description right above this comment) but the [diff tab](https://github.com/spack/spack/pull/39126/files) in this PR hasn't updated accordingly yet at time of writing. Not sure if GH will eventually update it or if anybody (I??) need to do anything to trigger that

When I get frustrated with the delay I'll click the refresh icon.  Usually that works for me.

**Comment by davidedelvento** [comment]
Thanks @tldahlgren if you mean the browser refresh button, I've tried that several times to no avail. If you mean a github button, I can't find it. Perhaps it is waiting for the various checks and prechecks to complete before updating the conflict section and hence diffs? Given that [commits](https://github.com/spack/spack/pull/39126/commits) are updated I don't think there is anything else I can do at this point (other than getting dinner :rofl:)

**Comment by tldahlgren** [comment]
> Thanks @tldahlgren if you mean the browser refresh button, I've tried that several times to no avail.

Yes, that's what I meant. 

I didn't realize your issue was with the reported conflicting files not disappearing.

**Comment by alalazo** [comment]
Superseded by #42636

**Pull request closed without merging**
