### PR TITLE
hypre: Add new versions

### PR DESCRIPTION
**Pull request by quellyn**
This PR adds two new releases of `hypre`:  `2.21.0` and `2.22.0`.

### CODE REVIEW

**Comment by quellyn** [comment]
`flake8` caught this style failure:
```
==> style: running flake8 checks on spack.
==> Error: Flake8 style checks found errors
var/spack/repos/builtin/packages/hypre/package.py:7: [I100] Import statements are in the wrong order. 'import os' should be before 'from spack import *' and in a different group.
var/spack/repos/builtin/packages/hypre/package.py:7: [I201] Missing newline between import groups. 'import os' is identified as Stdlib and 'from spack import *' is identified as Application.
```

I'm not sure what to do about it because
1) My patch doesn't actually change those lines, 
2) The order it's complaining about appears in *many* other package recipes; `adios2`, for example:
```
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack import *
import os


class Adios2(CMakePackage):
```

**Comment by sethrj** [comment]
@quellyn The style failures are a consequence of https://github.com/spack/spack/pull/23947, which will hopefully be simplified by https://github.com/spack/spack/pull/24071 and the existing failures fixed by https://github.com/spack/spack/pull/24695 . You can wait for those to be merged, or try fixing them yourself in the meantime. Sorry for the hassle!

**Comment by quellyn** [comment]
> @quellyn The style failures are a consequence of #23947, which will hopefully be simplified by #24071 and the existing failures fixed by #24695 . You can wait for those to be merged, or try fixing them yourself in the meantime. Sorry for the hassle!

As long as it's not weeks and weeks away, I can wait for the real fixes to come in. Thank you for letting me know!

**Comment by sethrj** [comment]
@quellyn package fixes just got merged! Could you rebase off develop/master and force-push? Should be good to go then.

**Comment by osborn9** [comment]
Thanks for adding the recent versions of hypre! Modulo the style updates, this looks good to me.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
