### PR TITLE
node-js: add v17.9.1, v20.15.0, v21.7.3, v22.3.0, v22.4.0

### PR DESCRIPTION
**Pull request by teaguesterling**
Adding a handful of versions for `node-js` to ensure we have at least one major version for the last few releases, as well as the latest 3 versions, including a new preferred LTS release. The previous preferred version was incompatible with `gcc@14:` so a conflict was added.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the newly added version sha256s.  

Would like to give @cosmicexplorer time to comment on the other changes and if there are additional changes needed for any of these versions.

**Comment by teaguesterling** [comment]
Looks like I need to make a style fix, too.

**Comment by teaguesterling** [comment]
@spackbot fix styles

**Comment by teaguesterling** [comment]
@spackbot fix style

**Comment by teaguesterling** [comment]
@spackbot rerun pipeline

**Comment by teaguesterling** [comment]
CI failure seems to be related to: https://github.com/nodejs/node/issues/52223 Will need to investigate a bit further.

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by teaguesterling** [comment]
> @spackbot run pipeline

Thanks! Looks like I have some additional conflicts to add still.

**Comment by teaguesterling** [comment]
🤦‍♂️

**Comment by teaguesterling** [comment]
This is now passing the CI pipeline and ready to go @tldahlgren and @cosmicexplorer

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
