### PR TITLE
hdf5: add a map variant

### PR DESCRIPTION
**Pull request by hyoklee**
This is a new variant that is required for HDF5 DAOS VOL.

### CODE REVIEW

**Review by lrknox — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
LGTM

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by hyoklee** [comment]
@spackbot run pipeline

**Comment by hyoklee** [comment]
Buildbot failure is irrelevant:

```
==> SPACK_BUILDCACHE_DESTINATION=s3://spack-binaries-prs/pr35523_hdf5-map/e4s-power
To reproduce this build locally, run:
    spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/6360337/artifacts [--working-dir <dir>]
If this project does not have public pipelines, you will need to first:
    export GITLAB_PRIVATE_TOKEN=<generated_token>
... then follow the printed instructions.
==> Error: Unable to copy files (/tmp/root/spack-stage/spack-stage-mercury-2.1.0-vaizim3n2ljrlrlork2t75mu35rls5f5/spack-build-out.txt) to artifacts /builds/spack/spack/jobs_scratch_dir/logs due to exception: No such file or directory: '/tmp/root/spack-stage/spack-stage-mercury-2.1.0-vaizim3n2ljrlrlork2t75mu35rls5f5/spack-build-out.txt'
```

@tldahlgren , would you please merge this PR?

**Comment by tldahlgren** [comment]
> Buildbot failure is irrelevant:
> 
> ```
> ==> SPACK_BUILDCACHE_DESTINATION=s3://spack-binaries-prs/pr35523_hdf5-map/e4s-power
> To reproduce this build locally, run:
>     spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/6360337/artifacts [--working-dir <dir>]
> If this project does not have public pipelines, you will need to first:
>     export GITLAB_PRIVATE_TOKEN=<generated_token>
> ... then follow the printed instructions.
> ==> Error: Unable to copy files (/tmp/root/spack-stage/spack-stage-mercury-2.1.0-vaizim3n2ljrlrlork2t75mu35rls5f5/spack-build-out.txt) to artifacts /builds/spack/spack/jobs_scratch_dir/logs due to exception: No such file or directory: '/tmp/root/spack-stage/spack-stage-mercury-2.1.0-vaizim3n2ljrlrlork2t75mu35rls5f5/spack-build-out.txt'
> ```
> 
> @tldahlgren , would you please merge this PR?

It is but CI is a required check.  I noticed an issue with `cmake` as well.  Are these consistent errors?

**Comment by tldahlgren** [comment]
Going to try an Update Branch in case we need to pick something up to get CI to pass.

**Comment by hyoklee** [comment]
Thank you so much, @tldahlgren !

**Pull request merged**
