### PR TITLE
meson: New version 0.64.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
If I understand correctly, the patch spec for oneapi.patch applies to all versions >= 0.62, but oneapi support has been upstreamed in Meson now, so that patch should be tightened up to no longer apply.

**Review by michaelkuhn — CHANGES_REQUESTED** [review]
Our rpath patch does not apply anymore:
```
==> Patch $SPACK/var/spack/repos/builtin/packages/meson/rpath-0.58.patch failed.
```
The oneAPI patch also fails (see the comment by @eli-schwartz):
```
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
==> Patch $SPACK/var/spack/repos/builtin/packages/meson/oneapi.patch failed.
```

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Comment by kwryankrattiger** [comment]
This also seems to require updates to the `build_systems/meson.py` to add the new `setup` keyword to the meson step. I cannot find the docs for this, but the errors I am getting now suggest that.

https://gitlab.spack.io/spack/spack/-/jobs/4422221

**Comment by kwryankrattiger** [comment]
I double checked the CI, and somehow this didn't rebuild meson or any of the meson deps... @scottwittenburg Do we have any ideas as to why this is? I know we have been discussing/tuning the pruning strategy recently.

**Comment by scottwittenburg** [comment]
Looks like at least e4s did rebuild `meson` for this PR, just not in the *most recent* pipeline.  But you can search the pipelines that ran for a branch, and for this PR, it was one pipeline back where `meson` was built.  I didn't search all the stacks, but it was at least built under e4s.

**Comment by eli-schwartz** [comment]
> This also seems to require updates to the `build_systems/meson.py` to add the new `setup` keyword to the meson step. I cannot find the docs for this, but the errors I am getting now suggest that.
> 
> https://gitlab.spack.io/spack/spack/-/jobs/4422221

The error you are getting in that job is not about "setup" -- there's a warning for that, but Meson specifically made it a warning, not an error, to give people time to migrate. :)

```
../spack-src/meson.build:21:0: ERROR: Unknown options: "gallium-xvmc"
A full log can be found at /tmp/root/spack-stage/spack-stage-mesa-main-77cbj3cv346lkl3edtd4qpp3uxywb4ig/spack-build-77cbj3c/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

Note spack itself handles this too:

> 1 error found in build log:
It highlights the line `ERROR: Unknown options: "gallium-xvmc"` in red and adds arrows on the side pointing at it.

**Comment by kwryankrattiger** [comment]
I saw that, but when I see a warning saying something is ambiguous I generally start there for backing out the error. I fixed the warning so we will see if that helps at all.

**Pull request merged**
