### PR TITLE
libfabric: add versions 1.17.0, 1.16.0, 1.15.2

### PR DESCRIPTION
**Pull request by jack-morrison**
SHAs from the ofiwg releases at https://github.com/ofiwg/libfabric/releases

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by rajachan — DISMISSED** [review]

**Review by haampie — DISMISSED** [review]

**Comment by scheibelp** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by jack-morrison** [comment]
Superseded by https://github.com/spack/spack/pull/36474

**Pull request closed without merging**
