### PR TITLE
Create new package for cmake-gui

### PR DESCRIPTION
**Pull request by KineticTheory**
Split the cmake package into two parts.  The new package, cmake-gui, will provide the Qt based cmake-gui application and requires the cmake~qt package to be available. This change eliminates a circular dependency: cmake-gui -> Qt -> cmake reported in PR#792.

### CODE REVIEW

**Comment by luigi-calori** [comment]
Tested with spack  install -v -j 30 cmake-gui  %gcc@4.8.2  ^qt@4.8.6 ^libxml2+python   everything seems ok.... much better experience . It builds automatically both cmake version...  if both cmake and cmake-gui are loaded, there are two cmake executable, if built the same version should not be a problem.
maybe cmake-gu should conflict with cmake in environment modules
Removing #792

**Comment by mathstuf** [comment]
Hmm. This brings up the question of how we want to handle bootstrapping loops. glib and pkg-config have the same thing, but is broken because pkg-config contains a subset of glib so you can build it without an external glib. Other things might have similar problems, but I guess they'll be mostly in the stack of build dependencies.

It is possible that allowing build-only specs to not have to share specs with other bits in the concretized dag would make this moot.

**Comment by tgamblin** [comment]
@mathstuf: I thought the same thing.  I was planning on merging build deps this week -- do you want to take a stab at tweaking this aspect of concretization before I do?  If so we could have a more elegant solution here.

**Comment by tgamblin** [comment]
@mathstuf: Also, we could have a call to talk about the implementation -- I think if build deps were concretized independently per package it would make this work just fine but that isn't in the main normalize/concretize loop right now.

**Comment by mathstuf** [comment]
#378 has been around for long enough that adding things to it that aren't strictly necessary is only going to delay it more :/ .

**Comment by mathstuf** [comment]
The builddeps being concretized independently is #839.

**Comment by luigi-calori** [comment]
Sorry to bother:
spack spec cmake +qt

still return 
Error: +qt does not satisfy ~qt

Also this PR does seems not to be mergeable automatically any more.
Is there a workaround ?   Otherwise I' ll try to merge and add it to my private packages.

**Comment by adamjstewart** [comment]
@luigi-calori It can't be merged automatically because there are merge conflicts. @KineticTheory will have to rebase off of the current develop HEAD and resolve any merge conflicts.

**Comment by KineticTheory** [comment]
I'll update this today.

**Comment by adamjstewart** [comment]
I think there's a better way to do this. Both packages are essentially the same. They have the same URL, versions, hash, and almost all of the same dependencies and build instructions. If the only reason for splitting the package is to get around a circular dependency with CMake and Qt, why not have Qt depend on `cmake~qt`?

**Comment by adamjstewart** [comment]
Oh wait, never mind. Apparently a Spack package can't depend on itself, even though the spec is different. I tried adding a jsoncpp dependency to CMake and told jsoncpp to depend on `cmake~jsoncpp` but I got the error message:
```
Error: +jsoncpp does not satisfy ~jsoncpp
```
I guess Spack tries to force every installation to have a single unique spec per package. @tgamblin is this something that we should consider changing? So far it's only a problem for CMake.

**Comment by mathstuf** [comment]
This is basically what #839 addresses.

**Comment by adamjstewart** [comment]
If #839 will eventually solve this problem, then I think it's best to wait and `depends_on('cmake~qt')` instead of adding a new package and removing it later. But I don't really use `cmake+qt`, so if it's an urgent need then I'll leave it up to @tgamblin.

**Comment by KineticTheory** [comment]
Closing this issue as `cmake+qt` appears to work again in the current develop version.

**Pull request closed without merging**
