### PR TITLE
libpciaccess: add v0.17

### PR DESCRIPTION
**Pull request by alecbcs**
Add libpciaccess v0.17.

**Changelog:**
https://cgit.freedesktop.org/xorg/lib/libpciaccess/log/

**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Kokkos failed for one stack with a timeout error.  Let's see if a re-run helps CI.

@spackbot run pipeline

**Comment by alecbcs** [comment]
@spackbot run pipeline 🥺

**Comment by alecbcs** [comment]
@spackbot run pipeline 😭

**Pull request merged**
