### PR TITLE
vecgeom: fix cuda arch

### PR DESCRIPTION
**Pull request by sethrj**
See #29488

### CODE REVIEW

**Review by drbenmorgan — DISMISSED** [review]
Brilliant, thanks for the fix and nice refactor @sethrj!

**Comment by sethrj** [comment]
Sorry @drbenmorgan I introduced a copy-paste error (args not  options, missing local spec). I'm also suppressing the `-mavx2` flag when CUDA is enabled, because that's caused us different problems on a couple of different versions now.

**Comment by drbenmorgan** [comment]
No worries @sethrj, I've disabled auto merge for now!

**Comment by sethrj** [comment]
@drbenmorgan I pushed fixes and actually tested the changeset :) so it should be good to go now.

**Comment by drbenmorgan** [comment]
Are the ISA flags issues with CUDA builds related to them getting forward to `nvcc` or something else? The flag forwarding _should_ have been fixed upstream.

Anyway, not a problem to disable them, so looks good to go once tests pass.

**Review by drbenmorgan — APPROVED** [review]

**Comment by sethrj** [comment]
> Are the ISA flags issues with CUDA builds related to them getting forward to `nvcc` or something else? The flag forwarding _should_ have been fixed upstream.

It looks like they're being forwarded, but even then it looks like GCC can't handle it:
```
/projects/spack/opt/spack/gcc-9.4.0/cuda/fdurbcw/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/g++ -DVECCORE_ENABLE_CUDA -I/tmp/suter/spack-stage/spack-stage-vecgeom-1.1.19-2waovxh7qlubvs75kcu27pqxi6d5wlux/spack-build-2waovxh -I/tmp/suter/spack-stage/spack-stage-vecgeom-1.1.19-2waovxh7qlubvs75kcu27pqxi6d5wlux/spack-src -isystem=/projects/spack/opt/spack/gcc-9.4.0/veccore/6cujhjc/include -isystem=/projects/spack/opt/spack/gcc-9.4.0/cuda/fdurbcw/include -O2 -g -DNDEBUG -line-info --generate-code=arch=compute_52,code=[compute_52,sm_52] -Xcompiler=-fPIC -Xcompiler=-faligned-new,-mavx2 -std=c++14 -MD -MT CMakeFiles/vecgeomcuda_obj.dir/cuda_src/UnplacedPolycone.cu.o -MF CMakeFiles/vecgeomcuda_obj.dir/cuda_src/UnplacedPolycone.cu.o.d -x cu -dc /tmp/suter/spack-stage/spack-stage-vecgeom-1.1.19-2waovxh7qlubvs75kcu27pqxi6d5wlux/spack-build-2waovxh/cuda_src/UnplacedPolycone.cu -o CMakeFiles/vecgeomcuda_obj.dir/cuda_src/UnplacedPolycone.cu.o
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9155): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14797): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14806): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9155): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9155): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14797): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14806): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1365): error: identifier "__builtin_ia32_fpclassss" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1372): error: identifier "__builtin_ia32_fpclasssd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14797): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14806): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1365): error: identifier "__builtin_ia32_fpclassss" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1372): error: identifier "__builtin_ia32_fpclasssd" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1365): error: identifier "__builtin_ia32_fpclassss" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1372): error: identifier "__builtin_ia32_fpclasssd" is undefined
```

It's definitely safer to disable the architecture flags for CUDA builds ... :(

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by drbenmorgan** [comment]
Thanks @sethrj, yep, definitely looks best to disable them...

**Comment by vvolkl** [comment]
This broke `vecgeom~cuda` ( the `cuda_arch` variant is only available when `+cuda` and will throw a KeyError otherwise). A quick fix (to be tested) is here: https://github.com/spack/spack/pull/29716

**Pull request merged**
