### PR TITLE
vim8 is out!

### PR DESCRIPTION
**Pull request by robertdfrench**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Damn, 40 years later, vi is still kicking. I wonder what new features 8 brings. LGTM.

**Comment by tgamblin** [comment]
@robertdfrench: should this be `when='@8.0:'`?

**Comment by robertdfrench** [comment]
@tgamblin Probably. Does that make it bind to 8.0 or greater instead of just '8.0' exactly?

**Comment by adamjstewart** [comment]
@robertdfrench Basically, `when='@8.0'` means if you're trying to build vim 8.0, it depends on ncurses. But if someone adds vim 8.1 someday, the package says it doesn't depend on ncurses. By using `when='@8.0:'`, it means versions 8 and up depend on ncurses.

**Comment by adamjstewart** [comment]
By the way, what error message were you seeing when building without ncurses? Are you sure vim 7 and earlier don't depend on ncurses?

**Comment by robertdfrench** [comment]
I was building this on a pre-release system that had absolutely no packages
installed. It may be that vim normally satisfies itself with the
system-provided ncurses and I just managed not to have that in this case.

I have a zoo of systems here, I should start making sure the problems I am
trying to fix actually exist in multiple places.

Good thinking.

**Pull request merged**
