### PR TITLE
eckit: add v1.27.0

### PR DESCRIPTION
**Pull request by srherbener**
This PR adds the latest version of eckit to the package.py script. This version is needed to pick up a fix for building on MacOS.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
No new build options that need to be configured? (just checking)

**Comment by srherbener** [comment]
It worked on my mac as is. The fix for the mac was to put in a missing `#include <cstddef>` statement.

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
> It worked on my mac as is. The fix for the mac was to put in a missing `#include <cstddef>` statement.

Has or do any of the maintainers want to confirm for themselves that there are no additional changes needed beyond the version directive?  Or is this good to merge?

**Comment by climbfuji** [comment]
> > It worked on my mac as is. The fix for the mac was to put in a missing `#include <cstddef>` statement.
> 
> Has or do any of the maintainers want to confirm for themselves that there are no additional changes needed beyond the version directive? Or is this good to merge?

I took a quick look at https://github.com/ecmwf/eckit/compare/1.25.2...1.27.0 and there is a whole bunch of new options, but all  are off by default and none of them urgently needed as far as I know. So I think this is good to merge.

**Comment by srherbener** [comment]
I built spack-stack on Orion using these changes for eckit and the build was successful. I think we are good with just the version directive, and this can be merged. Thanks!

**Pull request merged**
