### PR TITLE
FFTW: remove search for IBM XL threaded compiler when compiler is not gcc

### PR DESCRIPTION
**Pull request by serbanmaerean**
When building with PGI, the configuration file is looking for the IBM XL's xlc_r compiler, if --enable-threads.

Patching the FFTW build configuration file when %pgi seems to fix the issue.

### CODE REVIEW

**Comment by serbanmaerean** [comment]
Is it possible to have this pull request merged if all good?  Thanks.

**Comment by serbanmaerean** [comment]
@adamjstewart can you pls check this pull request?  I wanted to merge only the changes for the following commit:
fftw: patch configuration file to remove search for xlc_r compiler when compiler not gcc.
Not sure why the pull request has all the other changes.

**Comment by adamjstewart** [comment]
The commits look fine, since it's all squashed when merging it shouldn't be a problem.

I don't know much about all of the lines you removed from `configure`, but I'm wondering if there is a better way to do this. Have you submitted a bug report with the developers?

**Comment by serbanmaerean** [comment]
I have not opened a bug report with the community.  FFTW assumes gcc or IBM XL compilers.  There sure is a better way, i.e. check for IBM XL compiler instead of gcc compiler, as it does today.  If IBM XL, then check for xl_r, if not just skip it.  I just took the easy way out for the PGI compiler and removed the IBM XL specific code.

**Comment by serbanmaerean** [comment]
@adamjstewart I tried adding a new check for the IBM XL compiler, but I couldn't make things work, there are too many tests involved and I'm sure I missed a few.  By removing the part from configure that calls out IBM XL compiler directly, only for PGI builds work fine and I would leave it as such.  I will send a note to FFTW folks, to see if they are willing to provide an updated configure script.

**Comment by adamjstewart** [comment]
Let's see what the developers have to say.

**Comment by serbanmaerean** [comment]
@adamjstewart, considering that I have not heard anything back from FFTW in quite a while (I sent a note to fftw@fftw.org on 5/30), can you pls merge these changes for now?  The patch is limited to the current version, so future versions that may provide a fix will not be impacted by this patch.

**Pull request merged**
