### PR TITLE
gaudi: new version 37.2

### PR DESCRIPTION
**Pull request by wdconinc**
No major changes, https://gitlab.cern.ch/gaudi/Gaudi/-/compare/v37r1...v37r2?from_project_id=38&straight=false

### CODE REVIEW

**Comment by jmcarcell** [comment]
Because of the issue pointed out in this PR: https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1515, `Gaudi@:37.1` won't build with `catch2@3.1:`. Could you add it to the test dependencies? I think two lines with `depends_on("catch2@:3.0.1", when="@:37.1", type="test")` and the same with `+examples` should be enough without having to modify the for loop.

**Comment by wdconinc** [comment]
Thanks. I'll modify that tonight.

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256.

**Comment by wdconinc** [comment]
@jmcarcell It seems that we already patch for that MR for 37.1. I think that means we don't need the additional dependencies, but maybe we need to apply the patch to a wider ranges of versions (I think based on blame it might apply cleanly for 36.10 through 37.1, but I haven't tried). What do you think?

**Comment by tldahlgren** [comment]
Saw the requested change so *ping* me when this is ready to merge.

**Comment by jmcarcell** [comment]
Indeed, it was me who added the patch :facepalm:, this is ready to be merged

**Review by jmcarcell — APPROVED** [review]

**Comment by tldahlgren** [comment]
I took the last comment and approval as an indication this PR is ready to merge.  Let me know if I am wrong.

**Pull request merged**
