### PR TITLE
openblas: do not build tests when installing

### PR DESCRIPTION
**Pull request by sethrj**
Recent builds of OpenBLAS, 0.21 and later on my M1 and M2 macOS computers (perhaps due to newer versions of Gfortran?) have been failing during installation due to some odd crashes coming from the tests. This simply disables the runtime test since they seem to be unreliable.

---

The failure during build is:
```
/bin/sh: line 1: 60172 Killed: 9               OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat2 < ./sblat2.dat
make[1]: *** [level2] Error 137
make: *** [tests] Error 2
```
Running the test manually shows the same thing:
```
$ ./sblat1
[1]    60454 killed     ./sblat1
```
though running through lldb seems to partly fix it:
```
$ lldb -- ./sblat1
...
Test of subprogram number  1             SDOT
                                    ----- PASS -----
...
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
Process 60470 exited with status = 0 (0x00000000)
```

The console output shows:
```
default	10:40:46.285929-0400	kernel	CODE SIGNING: cs_invalid_page(0x105cd0000): p=61462[sblat1] final status 0x23020200, denying page sending SIGKILL
default	10:40:46.285955-0400	kernel	CODE SIGNING: process 61462[sblat1]: rejecting invalid page at address 0x105cd0000 from offset 0x0 in file "/opt/homebrew/Cellar/gcc/13.1.0/lib/gcc/current/libgfortran.5.dylib" (cs_mtime:1686155331.25907876 == mtime:1686155331.25907876) (signed:1 validated:1 tainted:1 nx:0 wpmapped:0 dirty:0 depth:0)
```

and I'm attaching the log.
[sblat1-2023-06-27-103225.ips.txt](https://github.com/spack/spack/files/11884279/sblat1-2023-06-27-103225.ips.txt)

### CODE REVIEW

**Review by eschnett — CHANGES_REQUESTED** [review]
I don't understand these errors. The first (`IEEE_DIVIDE_BY_ZERO`) sounds like an integer division by zero. The other (next?) sounds like a jump to a non-existing memory address. Both shouldn't happen in a test case.

Having said this, I confirm that I see the same error when building on macOS (with an Intel CPU). I haven't seen these errors on other platforms. Maybe you can update your patch to skip the tests only on macOS?

Can you add a comment to your code pointing to this PR as explanation?

**Comment by sethrj** [comment]
The usual behavior of spack packages is *not* to build and run tests -- there's an old disused options for building tests during the `spack install` process, and there's a separate "smoke test" option for checking an installation.

I'm not sure what's going on with the test either: the crash sounds like it's due to some library loading issue, and maybe loading `lldb` first pulls in the right libraries. The FPE is non-fatal so the test passes even though the debugger notices the signal.

I'll add a note to the `make` line that we're only building installable targets. It's worth noting that homebrew's recipe only installs the same targets.

**Comment by sethrj** [comment]
Also it looks like this is a code signing issue? The error is similar to `https://github.com/dotnet/maui/issues/12483` and the termination log has:
```
Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000103bf4000
Exception Codes:       0x0000000000000032, 0x0000000103bf4000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page
```

**Comment by sethrj** [comment]
@eschnett I added the note as requested. Since the default for spack should be to *not* run tests while building (since in theory you could be cross-compiling or building on a node with a different number of GPUs etc)., I've left the tests suppressed. However, the package *does* have the logic implemented to build and run the `tests` target if you use `spack install --test openblas`.

**Review by eschnett — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
