### PR TITLE
hpctoolkit: add version 2020.07.21

### PR DESCRIPTION
**Pull request by mwkrentel**

### CODE REVIEW

**Comment by mwkrentel** [comment]
Flake hasn't started in 20 hours for a 1-line patch.
I'll try the close/reopen restart.  If there's a better way ....

**Review by tldahlgren — COMMENTED** [review]
Visually confirmed the commit hash matches one in the repository.  Currently confirming can successfully build the new version on an LC machine.

**Comment by tldahlgren** [comment]
Re-running the tests since it is not clear why the macos tests failed.

**Comment by mwkrentel** [comment]
I don't know if it matters or what the macos tests test for, but we
(hpctoolkit) don't support macos.  We only run on Linux.

**Comment by tldahlgren** [comment]
> I don't know if it matters or what the macos tests test for, but we
> (hpctoolkit) don't support macos. We only run on Linux.

They're basically testing Spack.

**Review by tldahlgren — APPROVED** [review]
I successfully built the new version of the package on a Linux machine.

**Comment by tldahlgren** [comment]
I will merge this PR once the last queued test completes.

**Comment by mwkrentel** [comment]
> I will merge this PR once the last queued test completes.

That's kinda the problem.  Tests get stuck in the queue and never run.
20 hours after I first submitted the PR, the flake test hadn't
started.  I closed/reopened which restarts ALL the tests and flake
finished in 28 seconds.

But I don't know how to restart just one test.  I could close/reopen
again, but then a different test will get stuck in the queue.

**Comment by tldahlgren** [comment]
> > I will merge this PR once the last queued test completes.
> 
> That's kinda the problem. Tests get stuck in the queue and never run.
> 20 hours after I first submitted the PR, the flake test hadn't
> started. I closed/reopened which restarts ALL the tests and flake
> finished in 28 seconds.
> 
> But I don't know how to restart just one test. I could close/reopen
> again, but then a different test will get stuck in the queue.

I get the impression you can't restart just one test.  It's unfortunate, especially when there are a lot of PRs queued.

**Comment by mwkrentel** [comment]
Well, I'll give it a little longer and then kick it with close/reopen.
It's been stuck for 4 hours and all the other tests finished within
15-25 minutes.  Either that or you can say it doesn't matter.

**Comment by tldahlgren** [comment]
> Well, I'll give it a little longer and then kick it with close/reopen.
> It's been stuck for 4 hours and all the other tests finished within
> 15-25 minutes. Either that or you can say it doesn't matter.

**Comment by mwkrentel** [comment]
Note that all the tests were successful except that macos was hung
(never started), so I'm thinking that all we really need is that macos
finishes and succeeds.  OK?

**Comment by tldahlgren** [comment]
> Note that all the tests were successful except that macos was hung
> (never started), so I'm thinking that all we really need is that macos
> finishes and succeeds. OK?

For a second it looked to me like all of the tests passed after I told it to re-run the jobs.  Unfortunately, it looks like I triggered a close.  

At this point I'm just waiting for it to enable the `merge` button.

**Comment by tldahlgren** [comment]
I went ahead and merged since all of the tests have passed at one point or another while waiting on queued tasks.

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Pull request merged**
