### PR TITLE
Nalu requires Trilinos with Exodus support

### PR DESCRIPTION
**Pull request by jrood-nrel**
In regards to #4502 .

### CODE REVIEW

**Comment by jrood-nrel** [comment]
Ok, actually it looks like maybe that already happened. If that's the solution, I will just close this then.

**Comment by davydden** [comment]
@jrood-nrel i think you should still be explicit in `nalu` to require `+exodus` if that's the case.

**Comment by davydden** [comment]
otherwise someone may try building `nalu^trlinos~exodus` and will expect it to work.

**Comment by davydden** [comment]
> actually it looks like maybe that already happened.

yes, indeed https://github.com/LLNL/spack/pull/4501

**Comment by jrood-nrel** [comment]
Ok I will reopen this and make the change here, so we have the discussion of it.

**Comment by tgamblin** [comment]
FWIW, I think PRs like this will be useful for the Trilinos folks to see how people actually use Trilinos.

**Pull request merged**
