### PR TITLE
SIRIUS: optionlal dependency on Python

### PR DESCRIPTION
**Pull request by toxa81**
We don't need Python for the "standard" build.

### CODE REVIEW

**Review by simonpintarelli — COMMENTED** [review]
Agree, python isn't needed anymore for the standard build. Except for some older versions, everything before `v6.4.4` needs python to create the `config.hpp` file. Starting from 6.5.0 python isn't needed anymore to create the header files.
Should we remove them from the package.py or add the version specifier to the `depends_on`?

**Comment by toxa81** [comment]
I would remove old versions from the package.py. They are obsolete and unused.  @haampie what do you think? Shall we remove old versions (for example older than 7.x)?

**Comment by toxa81** [comment]
I also notices this lines
```
depends_on('elpa+openmp', when='+elpa+openmp')
depends_on('elpa~openmp', when='+elpa~openmp')
```
aren't they redundant?

**Comment by toxa81** [comment]
@kabicm Hey Marko, I had to edit the sha256 sum and add the shared library switch.

**Comment by simonpintarelli** [comment]
> I also notices this lines
> 
> ```
> depends_on('elpa+openmp', when='+elpa+openmp')
> depends_on('elpa~openmp', when='+elpa~openmp')
> ```
> 
> aren't they redundant?

The first one forces elpa to be compiled with openmp if SIRIUS has openmp enabled, the second line does the opposite. 
@toxa81 do you know if these are constraints? I assume sirius~openmp would also work with openmp enabled elpa?

**Comment by toxa81** [comment]
> I assume sirius~openmp would also work with openmp enabled elpa?

Yes, it will work. I'm fine with those lines if they are needed.

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by toxa81** [comment]
@haampie can you merge this one?

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
