### PR TITLE
Add new package: abi-dumper

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Review by michaelkuhn — CHANGES_REQUESTED** [review]
Same here. What about the dependencies at: https://github.com/lvc/abi-dumper#requires

**Comment by michaelkuhn** [comment]
Doesn't it also require ABI Compliance Checker? And how should we take care of the cyclic dependency?

**Comment by darmac** [comment]
> Doesn't it also require ABI Compliance Checker? And how should we take care of the cyclic dependency?

I opened an issue for this question:
https://github.com/lvc/abi-dumper/issues/24

**Comment by darmac** [comment]
According to https://github.com/lvc/abi-dumper/issues/24
Can we merge this PR now?
@michaelkuhn

**Review by michaelkuhn — APPROVED** [review]

**Pull request merged**
