### PR TITLE
streamstat: new package

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed branch exists.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Looks like there are a number of style errors across tools.

**Comment by cyrush** [comment]
Screen Shot 2022-12-07 at 12 12 57 PM

Looks like the reformat bot is not having good day. Not sure how to interpret that. 

I'll look at the other output. 

Also - I asked the authors to do a release with a version number b/c I think life will be to complex tied to the `main` branch.

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@cyrush Due to limitations on GitHub, people can't give push permissions on branches belonging to organizations (like Alpine-DAV). Therefore `spackbot` can't be of much help here - you need to run `spack style --fix` locally and push the changes.

**Comment by alalazo** [comment]
Closing. The package points to a fork, and it seems there are no version, or development ongoing https://github.com/LLNL/STREAMSTAT

**Pull request closed without merging**
