### PR TITLE
Bug fix for findutils: apply nonnull.patch only for versions 4.8.0+

### LINKED ISSUE #28856: Building findutils <= 4.7.0 fails after patch was added recently
### Steps to reproduce

PR https://github.com/spack/spack/pull/28316 added a patch to the `findutils` package that is applied unconditionally. However, as noted by @kgerheiser, the file that is patched does not exist in earlier versions than 4.8.0. This causes build errors.

To reproduce:
```
spack install findutils@4.7.0
```

### Error message

```
==> Installing findutils-4.7.0-h3fhihbyipvpkpyosc3v3bseblc4ak3s
==> No binary for findutils-4.7.0-h3fhihbyipvpkpyosc3v3bseblc4ak3s found: installing from source
/Users/heinzell/work/jedi-stack/spack-stack-new-joint/spack-stack-develop-20220209/spack/lib/spack/spack/target.py:137: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@13.0.0 for further details]
  warnings.warn(msg.format(compiler))
The text leading up to this was:
--------------------------
|--- a/gl/lib/malloc/dynarray-skeleton.c
|+++ b/gl/lib/malloc/dynarray-skeleton.c
--------------------------
File to patch:
Skip this patch? [y]
1 out of 1 hunk ignored
==> Fetching https://mirror.spack.io/_source-cache/archive/c5/c5fefbdf9858f7e4feb86f036e1247a54c79fc2d8e4b7064d5aaa1f47dfa789a.tar.xz
==> Patch /Users/heinzell/work/jedi-stack/spack-stack-new-joint/spack-stack-develop-20220209/spack/var/spack/repos/builtin/packages/findutils/nonnull.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/Users/heinzell/work/jedi-stack/spack-stack-new-joint/spack-stack-develop-20220209/spack/var/spack/repos/builtin/packages/findutils/nonnull.patch' '-d' '.'
```

### Information on your system

```
* **Spack:** 0.17.1-1126-c5f0284d40
* **Python:** 3.9.10
* **Platform:** darwin-monterey-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by climbfuji**
Fixes https://github.com/spack/spack/issues/28856.

### CODE REVIEW

**Comment by scheibelp** [comment]
Close/reopen to restart CI

**Review by scheibelp — APPROVED** [review]

**Comment by scheibelp** [comment]
@spackbot re-run pipeline

**Comment by climbfuji** [comment]
Thanks for rerunning the pipeline. The job failed because of:
```
==> Error: Pipeline generation failed due to the presence of the following specs that are known to be broken in develop:
[266](https://gitlab.spack.io/spack/spack/-/jobs/1717548#L266)* ascent@develop%gcc@7.5.0~adios~adios2~babelflow~cuda~doc+dray~fides+fortran~ipo~mfem+mpi+openmp+python+serial+shared+test+vtkh build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^apcomp@0.0.4%gcc@7.5.0+blt_find_mpi+mpi+openmp+shared arch=linux-ubuntu18.04-x86_64 ^autoconf@2.69%gcc@7.5.0 patches=35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2,7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7,a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee arch=linux-ubuntu18.04-x86_64 ^automake@1.16.5%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu18.04-x86_64 ^blt@0.4.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared arch=linux-ubuntu18.04-x86_64 ^camp@0.2.2%gcc@7.5.0~cuda~ipo~rocm~tests build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^cmake@3.22.2%gcc@7.5.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu18.04-x86_64 ^conduit@0.8.2%gcc@7.5.0~adios+blt_find_mpi~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi+parmetis+python+shared~silo+test~zfp build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^diffutils@3.8%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^dray@0.1.8%gcc@7.5.0+blt_find_mpi~cuda~logging+mpi+openmp+shared~stats~test~utils arch=linux-ubuntu18.04-x86_64 ^expat@2.4.4%gcc@7.5.0+libbsd arch=linux-ubuntu18.04-x86_64 ^gdbm@1.19%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^gettext@0.21%gcc@7.5.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-x86_64 ^hdf5@1.8.22%gcc@7.5.0~cxx+fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^hwloc@2.7.0%gcc@7.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-ubuntu18.04-x86_64 ^hypre@2.23.0%gcc@7.5.0~complex~cuda~debug+fortran~gptune~int64~internal-superlu~mixedint+mpi~openmp+shared~superlu-dist~unified-memory arch=linux-ubuntu18.04-x86_64 ^libbsd@0.11.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libedit@3.1-20210216%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libevent@2.1.12%gcc@7.5.0+openssl arch=linux-ubuntu18.04-x86_64 ^libffi@3.3%gcc@7.5.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu18.04-x86_64 ^libiconv@1.16%gcc@7.5.0 libs=shared,static arch=linux-ubuntu18.04-x86_64 ^libmd@1.0.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libpciaccess@0.16%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libsigsegv@2.13%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libtool@2.4.6%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libxml2@2.9.12%gcc@7.5.0~python arch=linux-ubuntu18.04-x86_64 ^m4@1.4.19%gcc@7.5.0+sigsegv patches=9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573,bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89 arch=linux-ubuntu18.04-x86_64 ^metis@5.1.0%gcc@7.5.0~gdb~int64~real64+shared build_type=Release patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1,b1225da886605ea558db7ac08dd8054742ea5afe5ed61ad4d0fe7a495b1270d2 arch=linux-ubuntu18.04-x86_64 ^mfem@4.3.0%gcc@7.5.0~amgx+conduit~cuda~debug~examples~gnutls~gslib~lapack~libceed~libunwind+metis~miniapps~mpfr+mpi~netcdf~occa~openmp~petsc~pumi~raja~rocm+shared~slepc+static~strumpack~suite-sparse~sundials~superlu-dist~threadsafe~umpire+zlib patches=ccc98d6d874a760218c9f6e4bcf3a97ea79746b0f28997f4312fcf02a0beae6e timer=auto arch=linux-ubuntu18.04-x86_64 ^ncurses@6.2%gcc@7.5.0~symlinks+termlib abi=none arch=linux-ubuntu18.04-x86_64 ^numactl@2.0.14%gcc@7.5.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94,62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006,ff37630df599cfabf0740518b91ec8daaf18e8f288b19adaae5364dc1f6b2296 arch=linux-ubuntu18.04-x86_64 ^openblas@0.3.19%gcc@7.5.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-ubuntu18.04-x86_64 ^openmpi@4.1.2%gcc@7.5.0~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~pmix+romio~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-ubuntu18.04-x86_64 ^openssh@8.8p1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^openssl@1.1.1m%gcc@7.5.0~docs certs=system arch=linux-ubuntu18.04-x86_64 ^parmetis@4.0.3%gcc@7.5.0~gdb~int64~ipo+shared build_type=RelWithDebInfo patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d arch=linux-ubuntu18.04-x86_64 ^perl@5.34.0%gcc@7.5.0+cpanm+shared+threads arch=linux-ubuntu18.04-x86_64 ^pkgconf@1.8.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-cython@0.29.24%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-mpi4py@3.1.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-numpy@1.22.2%gcc@7.5.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-ubuntu18.04-x86_64 ^py-pip@21.3.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-setuptools@59.4.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-wheel@0.37.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^python@3.9.10%gcc@7.5.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu18.04-x86_64 ^raja@0.14.0%gcc@7.5.0~cuda+examples+exercises~ipo+openmp~rocm+shared~tests build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^readline@8.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^sqlite@3.37.1%gcc@7.5.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu18.04-x86_64 ^tar@1.34%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^umpire@6.0.0%gcc@7.5.0+c~cuda~deviceconst+examples~fortran~ipo~numa~openmp~rocm+shared build_type=RelWithDebInfo tests=none arch=linux-ubuntu18.04-x86_64 ^util-linux-uuid@2.36.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^util-macros@1.19.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^vtk-h@0.7.1%gcc@7.5.0~contourtree~cuda~logging+mpi+openmp+serial+shared arch=linux-ubuntu18.04-x86_64 ^vtk-m@1.6.0%gcc@7.5.0~64bitids+ascent_types~cuda+doubleprecision~ipo~kokkos~logging+mpi+openmp+rendering~rocm+shared~tbb~testlib~virtuals build_type=Release arch=linux-ubuntu18.04-x86_64 ^xz@5.2.5%gcc@7.5.0~pic libs=shared,static arch=linux-ubuntu18.04-x86_64 ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 (eko2klvpav5cilvwqo36xlqc5z273f3d)
```

**Comment by alalazo** [comment]
Closed and reopen to let CI generate a new merge commit for the Gitlab pipelines. The error in CI is unrelated to this PR and hopefully solved by #28871

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
