### PR TITLE
Updating AOCC patches for WRF

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
- Updated few flags in AOCC patches for WRF v.3.9.1.1
- Added 2 new patches for AOCC 3.1 and 3.2 for compiling WRF v4.2

### CODE REVIEW

**Comment by amd-toolchain-support** [comment]
Hi @ptooley , please have a look at this pull request and do the needful!

**Comment by amd-toolchain-support** [comment]
Hi @adamjstewart , can you please review this request and do the needful.

**Comment by MichaelLaufer** [comment]
LGTM,
Although I would suggest working with upstream WRF to add native support for AOCC.
Adding additional versions of WRF will be a big pain with the current implementation.

**Comment by adamjstewart** [comment]
@amd-toolchain-support if you submit these patches upstream I'll merge this 😄

**Comment by amd-toolchain-support** [comment]
Hi @adamjstewart  and @MichaelLaufer , we are forwarding this to the concerned team to upstream to WRF source code, but those changes may reflect in upcoming releases only right, we should still have to use the patches for released versions.

**Comment by amd-toolchain-support** [comment]
Hi @adamjstewart , can you please do the needful for this request.

**Review by alalazo — CHANGES_REQUESTED** [review]
This PR needs to be rebased to pass CI tests that have been added in the meanwhile.

One question: looking at [WRF issue pages](https://github.com/wrf-model/WRF/issues?q=is%3Aissue+is%3Aopen+aocc) I don't see anything mentioning `aocc`. Did you submit any issue upstream to have better support for this compiler?

**Comment by amd-toolchain-support** [comment]
> This PR needs to be rebased to pass CI tests that have been added in the meanwhile.
> 
> One question: looking at [WRF issue pages](https://github.com/wrf-model/WRF/issues?q=is%3Aissue+is%3Aopen+aocc) I don't see anything mentioning `aocc`. Did you submit any issue upstream to have better support for this compiler?

Hi @alalazo , we have not raised an issue with WRF yet, but surely it is in our priority list for this year.
We will update you once upstream request is submitted.
Thanks.

**Comment by alalazo** [comment]
> We will update you once upstream request is submitted.

Thanks! The reason I ask for this is that there is a stream of patches in this package that are meant to make `aocc` work, if I understand them correctly, so I think it would be better to fix the issue upstream and have a clean, patch-less recipe in Spack.

**Comment by amd-toolchain-support** [comment]
> fix the issue upstream and have a clean, patch-less recipe in Spack.

Agree with you @alalazo

**Comment by amd-toolchain-support** [comment]
Hi @alalazo , we have started working towards upstreaming the `configure` changes to WRF, please note that the support for `AOCC` will be provided only after WRF community accepts the requested changes and release a latest `version`.

But, for released versions like `3.9.1.1` and `4.2` will require patches provided in this pull request to support AOCC compiler.

**Comment by alalazo** [comment]
@amd-toolchain-support Is there any PR in the WRF repo that we can mention in a comment?

**Comment by amd-toolchain-support** [comment]
Hi @alalazo ,
Please find the pull request raised by AMD with WRF for AOCC support.
link: https://github.com/wrf-model/WRF/pull/1684

**Comment by alalazo** [comment]
@amd-toolchain-support Referring to https://github.com/spack/spack/pull/29106#issuecomment-1048423759, this PR is not closed :slightly_smiling_face:

**Comment by amd-toolchain-support** [comment]
closing this PR as new PR is initiated

**Pull request closed without merging**
