### PR TITLE
Remove remote website pinging from OpenSSL

### LINKED ISSUE #1332: OpenSSL checks are too slow
I often work on systems that can't see the outside world.  On such systems, everytime spack queries the OpenSSL package, a 2 minute delay is added to my command.  For example:

```
% time spack spec openssl%intel@16.0.3
<output trimmed>
==> Warning: This installation depends on an old version of OpenSSL, which may have known security issues. 
==> Warning: Consider updating to the latest version of this package.
==> Warning: More details at http://www.openssl.org
<output trimmed>

real	2m9.064s
user	0m0.632s
sys	0m0.216s
```

Also:

```
% spack -p spec openssl%intel@16.0.3
  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1  127.316  127.316  127.316  127.316 {method 'connect' of '_socket.socket' objects}
        3    0.689    0.230    0.689    0.230 {built-in method poll}
<output trimmed>
  
```

Is there any way to disable this check? or make it time-out after 15-20 seconds?  For now, I just comment out this section of openssl/package.py.

### PR DESCRIPTION
**Pull request by tgamblin**
Resolves #1332.  

- OpenSSL no longer checks remote versions on the openssl site.

- Spack is used on systems that aren't connected to the internet, and
  this check is probably in the wrong place and affects too many
  commands.  We can work on figuring out a better, more configurable
  place to put a check like this.

@alalazo @KineticTheory @citibeth @adamjstewart

### CODE REVIEW

**Comment by adamjstewart** [comment]
Should we remove the older versions from the package since url_for_version no longer locates them properly?

**Comment by citibeth** [comment]
Unless someone is willing to research the whys and whats of past OpenSSL
versions, I'd be fine to remove all OpenSSL versions except the newest.
Older versions almost certainly have security problems.

**Comment by alalazo** [comment]
> Unless someone is willing to research the whys and whats of past OpenSSL
versions, I'd be fine to remove all OpenSSL versions except the newest.
Older versions almost certainly have security problems.

Without an automated update / notification of some kind on new versions of OpenSSL this would very likely be a thing done halfway. How long spack newest will be an old OpenSSL before someone will notice it and update `openssl/package.py`?

**Comment by adamjstewart** [comment]
@alalazo I suspect someone will notice right away if a new version comes out since OpenSSL archives the old download URL. Anything that depends on OpenSSL will break because Spack can't download any version of OpenSSL. That's the original reason we added the complex `url_for_version` logic.

**Comment by alalazo** [comment]
@adamjstewart But now we have caches that mitigate the problem, right ?

**Comment by alalazo** [comment]
Anyhow, I don't mean to be picky on this. I just see a point that we should deal with in the long run...

**Comment by adamjstewart** [comment]
@alalazo Ah, I see what you mean.

**Comment by adamjstewart** [comment]
@tgamblin Can you remove the no longer necessary imports? There's also an extra blank line.

**Comment by tgamblin** [comment]
@adamjstewart: done

**Pull request merged**
