### PR TITLE
e4s oneapi ci: try enabling some disabled specs

### PR DESCRIPTION
**Pull request by eugeneswalker**
E4S OneAPI CI: try enabling some disabled specs to see what/if-any build issues have been resolved.

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by wspear — APPROVED** [review]

**Pull request merged**
