### PR TITLE
PLASMA: add support for building with 'cray-libsci'

### PR DESCRIPTION
**Pull request by v-dobrev**
This should allow PLASMA to be built on OLCF's Crusher with Cray's LibSci (optimized BLAS/LAPACK/ScaLAPACK) library.

### CODE REVIEW

**Review by luszczek — APPROVED** [review]
Thanks for the changes. https://github.com/icl-utk-edu/plasma/pull/28 and https://github.com/icl-utk-edu/plasma/pull/26 fix some of this in `@develop`

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
CI failures are a bit random :(

@spackbot run pipeline

**Review by balay — APPROVED** [review]

**Pull request merged**
