### PR TITLE
apple-libuuid: update installation directory

### PR DESCRIPTION
**Pull request by adamjstewart**
Directory moved in Xcode 15?

### CODE REVIEW

**Comment by adamjstewart** [comment]
I'm not sure what the best solution is here.

The header file lives in:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/uuid/uuid.h
```
The library _seems_ to live in:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.B.tbd
```
However, using:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr
```
as the prefix for apple-libuuid causes packages like GDAL and OpenCV to break:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/climits:46:5: error: <climits> tried including <limits.h> but didn't find libc++'s <limits.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
#   error <climits> tried including <limits.h> but didn't find libc++'s <limits.h> header. \
    ^
```
When inspecting `uuidgen`, I found:
```
> otool -L /usr/bin/uuidgen
/usr/bin/uuidgen:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2048.1.255)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```
Using `/usr` as the prefix works even though `/usr/lib/libSystem.B.dylib` doesn't actually exist.

I _think_ the right thing to do is to use `/usr` for all system libs and let the linker figure out where they actually live. We already do this for libunwind. I don't know what this means for GL/GLU.

**Comment by aphecetche** [comment]
@adamjstewart do you specify some special variants for e.g. gdal ? 

Trying a simple `spack install gdal` worked for me with `develop (0.21.0.dev0 (3e1f2392d44c590e9d2a6c0176b5f397bf6a34a7))` ?

```
...
==> Installing gdal-3.7.2-sxyb6skuol2babwyljz7mi7xomkvn5jg [21/21]
==> No binary for gdal-3.7.2-sxyb6skuol2babwyljz7mi7xomkvn5jg found: installing from source
==> Fetching https://download.osgeo.org/gdal/3.7.2/gdal-3.7.2.tar.xz
==> Ran patch() for gdal
==> gdal: Executing phase: 'cmake'
==> gdal: Executing phase: 'build'
==> gdal: Executing phase: 'install'
==> gdal: Successfully installed gdal-3.7.2-sxyb6skuol2babwyljz7mi7xomkvn5jg
  Stage: 50.97s.  Cmake: 20.13s.  Build: 1m 38.58s.  Install: 0.47s.  Post-install: 0.15s.  Total: 2m 50.41s
[+] /Users/laurent/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gdal-3.7.2-sxyb6skuol2babwyljz7mi7xomkvn5jg

```

**Comment by adamjstewart** [comment]
The develop branch "works" in the sense that the previous directory has no `lib` or `include` directories. So nothing breaks the compiler, you just get warnings by build systems like meson. I tried adding the `usr` subdirectory which exists but that breaks things like GDAL. So it seems like the best thing to do is to use `/usr`.

**Comment by adamjstewart** [comment]
I'm using `gdal+curl+openjpeg+python`. I think it's specifically `+python` that causes apple-libuuid to be added to the link path since `python+uuid` links to it.

**Comment by aphecetche** [comment]
Hum. I would feel more confortable pointing to the (XCode provided) SDK instead of `/usr` (but I can't say I fully understand the implications here). Could it be that the problem is not the default prefix that is used but how the apple-libuuid package itself is specifying/finding the lib and headers from that prefix ? (just guessing here, will have to actually play a bit with it) 

BTW shouldn't we also uniformize a bit the default prefixes for apple-xxx stuff that are in `spack/etc/spack/defaults/darwin/packages.yaml` ?  We currently have `/usr`, `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`, and `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`. The latter ones actually I no longer understand : I know for instance that no longer install common line tools on my Mac and things seem to compile just fine.

**Comment by adamjstewart** [comment]
If we use the correct path[^1], then `.libs` and `.headers` will work correctly. However, building packages like GDAL and OpenCV will fail. If we use the incorrect path[^2], `.libs` and `.headers` break, but I was able to build my entire environment. I don't know of a way to get both to work correctly. Based on the error msg:

> This usually means that your header search paths are not configured properly. The header search paths should contain the C++ Standard Library headers before any C Standard Library, and you are probably using compiler flags that make that not be the case.

I think the correct solution is to not use any `-L` so that the linker can find it on its own.

[^1]: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr
[^2]: /usr

**Comment by aphecetche** [comment]
Just an observation :  from `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` two `uuid.h` files can be found, which are not exactly the same : 

```
diff ./usr/include/uuid/uuid.h ./System/Library/Frameworks/Kernel.framework/Versions/A/Headers/uuid/uuid.h

64a65
> void uuid_generate_early_random(uuid_t out);
```

Also, there's no `uuid.h` under `/usr` at all so it's strange to set that as the prefix for libuuid, is it not ?

**Comment by aphecetche** [comment]
Using the same kind of procedure as in e.g. `apple-gl` (i.e. pointing to a framework), gdal compiles. And the paths probably make more sense than `/usr` ? 

```
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class AppleLibuuid(BundlePackage):
    """Placeholder package for Apple's analogue to non-GNU libuuid"""

    homepage = "https://opensource.apple.com/tarballs/Libsystem/"

    version("1353.100.2")

    provides("uuid")

    # Only supported on 'platform=darwin'
    conflicts("platform=linux")
    conflicts("platform=cray")

    @property
    def libs(self):
        return LibraryList(join_path("self.prefix", "System/Library/Frameworks/Kernel.framework"))

    @property
    def headers(self):
        return HeaderList(join_path("self.prefix", "System/Library/Frameworks/Kernel.framework"))

```

**Comment by adamjstewart** [comment]
Honestly I don't think I know enough about frameworks to know how this should work. And Apple has little to no documentation on this kind of stuff.

I think the most important question is what `-L` and `-I` paths does the linker need to find things? If we can find docs or run experiments with that, we can later decide what the root is and what trick should be used to find the exact path to use. I agree that it would be nice to use the same technique for all `apple-*` packages.

**Comment by aphecetche** [comment]
Agreed.
But I'm unsure how to experiment, as it seems `clang` is actually finding `libuuid` without any need for `-L` or `-I` : 

```
📦~/spack/tmp [develop] $ cat test.c
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test.c
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #include <stdio.h>
   2   │ #include <uuid/uuid.h>
   3   │
   4   │ int main() {
   5   │   uuid_t uid;
   6   │   uuid_generate(uid);
   7   │   char out[33];
   8   │   uuid_unparse(uid, out);
   9   │   printf("uuid=%s\n", out);
  10   │   return 0;
  11   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────
📦~/spack/tmp [develop] $ clang -o toto test.c
📦~/spack/tmp [develop] $ ./toto
uuid=57C54692-E3FE-45B4-BA1B-7823B19F265C

```

**Comment by adamjstewart** [comment]
That's what I observed as well. If you use `otool -L` on that file, it will claim to link to `/usr/lib/libSystem.B.dylib` even though that file doesn't exist.

**Comment by adamjstewart** [comment]
@aphecetche what do you want to do here? The current directory is definitely wrong because it doesn't exist, and packages like numpy/scipy will issue thousands of warnings about this fact. The only reason it works is because the linker knows where to find things anyway. I'm leaning towards doing something like `apple-gl` but don't know the right paths to use.

**Comment by aphecetche** [comment]
@adamjstewart well, not sure either, but I would say `System/Library/Frameworks/Kernel.framework`, like in https://github.com/spack/spack/pull/40416#issuecomment-1759676663, as at least there's a `uuid.h` there ?

**Comment by adamjstewart** [comment]
Okay, this seems to be working. I'll let someone else figure out apple-libunwind, I'm too afraid to touch anything else.

**Review by becker33 — APPROVED** [review]
I gather the explanatory comment was removed because we decided we actually don't understand at all, which seems fair enough given the conversation.

**Pull request merged**
