### PR TITLE
[WIP] ML CI: Linux aarch64

### PR DESCRIPTION
**Pull request by adamjstewart**
Copied our existing CI from x86_64 to aarch64

### CODE REVIEW

**Comment by adamjstewart** [comment]
Any idea why the compiler isn't working? I naively copied the x86_64 version and just replaced x86_64 with aarch64, not sure what other changes need to be made.

**Comment by adamjstewart** [comment]
@scottwittenburg any thoughts on this one?

**Comment by scottwittenburg** [comment]
I think again here, you want to specify compiler and arch as part of a spec matrix.  It seems by default the concretizer picked `linux-amzn2-haswell`, when you wanted `aarch64`.

Also I noticed at least one of the pipeline generation jobs had `x86_64` tag instead of `aarch64`.  I see you've tried to add the `aarch64` tag, in a way similar to how some of the other pipelines for that arch do it, but somehow it's not working in your case.  I'll let you know if I discover the cause of this, but in the meantime you could try extending the existing `.pr-generate-aarch64` and `.protected-generate-aarch64` definitions.

**Comment by adamjstewart** [comment]
It's working! Now to fix some package build issues...

**Comment by adamjstewart** [comment]
First up: intel-oneapi-tbb

```
==> [2022-12-09-23:30:50.352912] 'bash' 'l_tbb_oneapi_p_2021.7.1.15005_offline.sh' '-s' '-a' '-s' '--action' 'install' '--eula' 'accept' '--install-dir' '/home/software/spack/[padded-to-384-chars]/morepadding/linux-amzn2-aarch64/gcc-7.3.1/intel-oneapi-tbb-2021.7.1-upblbuqdyzjtki4kqvfqhwqu2huhs2tu'
/tmp/root/spack-stage/spack-stage-intel-oneapi-tbb-2021.7.1-upblbuqdyzjtki4kqvfqhwqu2huhs2tu/spack-src/l_tbb_oneapi_p_2021.7.1.15005_offline/install.sh: line 34: /tmp/root/spack-stage/spack-stage-intel-oneapi-tbb-2021.7.1-upblbuqdyzjtki4kqvfqhwqu2huhs2tu/spack-src/l_tbb_oneapi_p_2021.7.1.15005_offline/bootstrapper: cannot execute binary file
```
@rscohn2 does intel-oneapi-tbb not work on aarch64? If so I can add a conflict.

**Comment by adamjstewart** [comment]
Next: valgrind
```
/usr/lib/gcc/aarch64-redhat-linux/7/libgcc.a(lse-init.o): In function `init_have_lse_atomics':
(.text.startup+0xc): undefined reference to `getauxval'
(.text.startup+0xc): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `getauxval'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1112: memcheck-arm64-linux] Error 1
```
Tried adding a newer version of valgrind in #34436, if we're lucky that may help. If not, I'll just disable it in the PyTorch package. I'm guessing that's the only thing that needs it.

**Comment by adamjstewart** [comment]
py-tensorboard-data-server issues fixed in https://github.com/spack/spack/pull/34437 and https://github.com/tensorflow/tensorboard/pull/6101

**Comment by rscohn2** [comment]
> @rscohn2 does intel-oneapi-tbb not work on aarch64? If so I can add a conflict.

None of the packages will work so I added a conflict in the base package: #34441

**Comment by adamjstewart** [comment]
Next round of build failures. LLVM:
```
/tmp/root/spack-stage/spack-stage-llvm-14.0.6-5raql5vuvka6tcsadwnnzh6elturcyel/spack-src/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_arm64.cpp:63:28: error: aggregate 'lldb_private::process_linux::NativeRegisterContextLinux::CreateHostNativeRegisterContextLinux(const lldb_private::ArchSpec&, lldb_private::process_linux::NativeThreadLinux&)::user_sve_header sve_header' has incomplete type and cannot be defined
     struct user_sve_header sve_header;
                            ^~~~~~~~~~
/tmp/root/spack-stage/spack-stage-llvm-14.0.6-5raql5vuvka6tcsadwnnzh6elturcyel/spack-src/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_arm64.cpp: In member function 'virtual lldb_private::Status lldb_private::process_linux::NativeRegisterContextLinux_arm64::WriteRegister(const lldb_private::RegisterInfo*, const lldb_private::RegisterValue&)':
/tmp/root/spack-stage/spack-stage-llvm-14.0.6-5raql5vuvka6tcsadwnnzh6elturcyel/spack-src/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_arm64.cpp:376:13: error: 'sve_vl_valid' was not declared in this scope
         if (sve_vl_valid(vg_value * 8)) {
             ^~~~~~~~~~~~
```
@haampie @trws ever seen this one before?

**Comment by adamjstewart** [comment]
PyTorch:
```
  cc1: error: invalid feature modifier in '-march=armv8.2-a+dotprod'
```
Looks like the same issue as https://github.com/google/XNNPACK/issues/1551 and https://discuss.pytorch.org/t/installation-from-source-on-aarch64-meet-march-armv8-2-a-fp16-dotprod-failure/162336/2. Solution is to use a newer compiler. Not really sure how to get a newer GCC on these images though...

Update: easier solution is just to disable XNNPACK

**Comment by adamjstewart** [comment]
Ping @haampie @trws. LLVM is the only thing holding up this new pipeline at the moment. I could disable TF on aarch64, but I'd rather test it if possible.

**Comment by trws** [comment]
Nope, that’s a new one. All I know is it’s an sve related issue, I’ve seen a couple issues due to arch detection but this looks like a header version problem, maybe whatever is providing that header is too old?


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On December 23, 2022 at 12:22:35 PM PST, Adam J. Stewart ***@***.***> wrote:

Ping @haampie<https://urldefense.us/v3/__https://github.com/haampie__;!!G2kpM7uM-TzIFchu!jPwoVKCOyxjrneKjjNZyw8a6ZNdoDP-Fvz_KNS--LQx-yFPiIL3CW7_MuMwLFD7gJw$> @trws<https://urldefense.us/v3/__https://github.com/trws__;!!G2kpM7uM-TzIFchu!jPwoVKCOyxjrneKjjNZyw8a6ZNdoDP-Fvz_KNS--LQx-yFPiIL3CW7_MuMymHmVvcQ$>. LLVM is the only thing holding up this new pipeline at the moment. I could disable TF on aarch64, but I'd rather test it if possible.

**Comment by adamjstewart** [comment]
I could have sworn PyTorch was building before...

New build issue:
```
  /home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/cuda-11.8.0-wiyn3mcz4hhvd6rx6ysqbbbv45rwi6y3/lib64/libcurand.so: undefined reference to `expf@GLIBC_2.27'
  /home/software/spack/[padded-to-384-chars]/linux-amzn2-aarch64/gcc-7.3.1/cuda-11.8.0-wiyn3mcz4hhvd6rx6ysqbbbv45rwi6y3/lib64/libcurand.so: undefined reference to `logf@GLIBC_2.27'
```

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
This is outdated after the CI refactor. I'll create a new PR when I get a chance.

**Pull request closed without merging**
