### PR TITLE
kokkos and kokkos-kernels: add new versions

### PR DESCRIPTION
**Pull request by balos1**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed all (3) new sha256.  Rest LGTM.

**Comment by tldahlgren** [comment]
Will defer merge decision to give maintainers a chance to comment.

**Comment by balos1** [comment]
@tldahlgren Can this be merged now?

**Review by brian-kelley — APPROVED** [review]
Looks fine to me.

**Pull request merged**
