### PR TITLE
ArrayFire improvements

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**
Improve the package so that ArrayFire's libraries are actually found and so that it can be compiled with the FFTW wrappers from MKL.

### CODE REVIEW

**Comment by tldahlgren** [comment]
@Sinan81 Can you look over these changes?

**Comment by Sinan81** [comment]
> @Sinan81 Can you look over these changes?

will do today or so.

**Comment by Sinan81** [comment]
I don't see any issues. `arrayfire+cuda` installs fine on my Centos system, all the libs are properly located after installation. Please go ahead and the merge it. Thanks.

**Review by Sinan81 — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Can you resolve the merge conflicts?

**Comment by RemiLacroix-IDRIS** [comment]
> Can you resolve the merge conflicts?

Done!

**Pull request merged**
