### PR TITLE
gBenchmark: Development Package

### PR DESCRIPTION
**Pull request by ax3l**
Add the development version (master branch) of `gBenchmark`

(post 1.1.0 release adds proper [cmake config package](https://github.com/google/benchmark/issues/423) installs)

### CODE REVIEW

**Comment by ax3l** [comment]
uh, true!

the other package removes the `-Werror` they ship, I like that.

**Comment by adamjstewart** [comment]
Feel free to keep the `filter_file` and move it to `benchmark`.

**Comment by ax3l** [comment]
done so, thanks!

**Comment by adamjstewart** [comment]
It looks like @mdavezac added the `gbenchmark` package in #2627. I would like to make sure this change is okay with him.

**Comment by ax3l** [comment]
Yes please, absolutely.

**Comment by mdavezac** [comment]
Thanks @adamjstewart. Yes let's remove gbenchmark. I guess I missed benchmark originally...

**Comment by ax3l** [comment]
@mdavezac thank you for the quick feedback!

**Pull request merged**
