### PR TITLE
Update py-sympy version

### PR DESCRIPTION
**Pull request by LDAmorim**
Hi everyone,

I wanted to update the current version of the python package `py-sympy` (to use `multigamma`, for example).

And I found its information in:
https://github.com/sympy/sympy/releases

I am testing this in my local machine (with a full `spack` installation - and python 3.8.6) and it seems to work well.

It might be useful to update also the *url* to the `.tar.gz` files for the recent versions (which seems to be different now).
What do you think?

Thanks,
Diana

### CODE REVIEW

**Comment by adamjstewart** [comment]
> It might be useful to update also the url to the .tar.gz files for the recent versions (which seems to be different now).
What do you think?

You can if you want to, but it doesn't make a difference. Spack automatically parses the URL, removes what it thinks the version is, and replaces it with the version you request. That's how we can have several versions but only a single URL.

**Review by adamjstewart — CHANGES_REQUESTED** [review]
It looks like the latest version requires Python 3.5+ and setuptools:
```python
depends_on('python@3.5:', when='@1.6:', type=('build', 'run'))
depends_on('py-setuptools', when='@1.6:', type=('build', 'run'))
```
You should dig through the changelog a bit and see which versions actually added these new requirements.

**Comment by LDAmorim** [comment]
Hi @adamjstewart , thank you very much for the quick feedback.
I will check that out and add those requirements.

**Comment by LDAmorim** [comment]
I will keep investigating this better, to correct the dependencies details.
But so far it seems python 3.5 is no longer supported:
https://github.com/sympy/sympy/pull/20145

**Comment by adamjstewart** [comment]
That must be in master, 3.5 is still supported in the latest release you added.

**Comment by alalazo** [comment]
@LDAmorim

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if you want to continue working on this.

**Pull request closed without merging**
