### PR TITLE
Add CPATH pointing to include directories.

### PR DESCRIPTION
**Pull request by glennpj**
This pull request adds CPATH to the module files. This will allow the header files to be available for development outside of spack.

### CODE REVIEW

**Comment by tgamblin** [comment]
Thanks!

**Comment by alalazo** [comment]
@tgamblin @glennpj  Honestly I would be against this change. Having `CPATH` set is like an implicit `-I<folder>` to the compiler that is ALWAYS set, on every call to the compiler. This can mask errors in build scripts that would have been revelead otherwise. Having a `XXX_INCLUDE_PATH` variable set is usually sufficient, as it is then the job of the developer to correctly set the dependencies selecting the ones he needs for each particular target.

**Comment by tgamblin** [comment]
@alalazo: actually I agree with this.  I was actually thinking of removing `LIBRARY_PATH` for similar reasons -- we've seen issues where CMake assumes from `LIBRARY_PATH` that certain link paths are implicit, which causes `RPATH` to be set incorrectly if you link with `LIBRARY_PATH` set.

@glennpj: do you need to have CPATH in your module files?  Would you be ok with removing it?  Or do we need to make this configurable?

**Comment by glennpj** [comment]
Well, I have CPATH set in my current (non-spack) modules and have never had a problem. If people think it causes a problem with spack then take it out. My only comment is that one of the purposes of environment modules is to provide path information for software that needs to find headers and libraries in, from its perspective, non standard locations.

**Comment by tgamblin** [comment]
I'll revert this commit and also take out `LIBRARY_PATH`, but we'll provide some customization in the config file so that you can reenable them if you want. This would let you enable them even if they are disabled by default.

I've only actually seen real issues with builds breaking (or not having proper `RPATHs`, at least) with `LIBRARY_PATH`.  This was due to assumptions made about [implicit link paths](https://cmake.org/pipermail/cmake/2011-June/044828.html).  I have not seen issues like this with `CPATH`.

**Comment by alalazo** [comment]
@glennpj Problems I have encountered with `CPATH` basically falls into two categories:

1. a project is developed on a system with `CPATH` and when you port that project somewhere else you see that the build-system is broken (usually missing dependencies) but `CPATH` was masking the problem on the development machine
2. header name clash among libraries and dependency on the order in which you load the modules

My point is that `CPATH` is basically a fat interface (if a single target of your project depends on a library, then every target will have it) and as such should be avoided.

**Comment by citibeth** [comment]
I agree on the evils of CPATH and LD_LIBRARY_PATH.  But... Spack DOES need to provide help for developers building new projects on the basis of standard Spack-compiled projects.  See here for some ideeas: https://github.com/LLNL/spack/pull/474

The idea there is to have Spack call cmake for you, setting things up based on a package.py file.  The nice thing is... when you're done with your project, you can put your package.py file directly into the Spack repo!

Other possibilities would be:
*) Have a spack command that loads a bunch of specs (making sure they're already built), and then generates custom compiler wrappers based on those specks.  For example: 
       spack generate-wrappers udunits2 netcdf gcc
Then you can use those generated wrappers locally in your project.

*) Have the same Spack command generate a custom "env" wrapper that can be used to run anything.  CPATH, etc would go in this wrapper. Then you set your compiler to "./env gcc" or whatever.

**Comment by eschnett** [comment]
I've tried to use `module` for this; Spack seems to generate definition files for it. However, I haven't been able to build `module` on HPC systems since it requires TCL. There's also a version written in Lua, but this didn't work for me either since it requires certain Lua packages that don't build for me.

This is what I'm using at the moment:
```sh
# This file needs to be sourced, not executed

compiler='%gcc@5.3.0-spack'

export SPACK_DIR=/Users/eschnett/src/spack
source $SPACK_DIR/share/spack/setup-env.sh
export SPACK_COMPILER_DIR=$(spack location -i gcc@5.3.0)
export SPACK_BOOST_DIR=$(spack location -i boost $compiler)
export SPACK_CURL_DIR=$(spack location -i curl $compiler)
export SPACK_FFTW_DIR=$(spack location -i fftw $compiler)
export SPACK_GSL_DIR=$(spack location -i gsl $compiler)
export SPACK_HDF5_DIR=$(spack location -i hdf5 $compiler)
export SPACK_HWLOC_DIR=$(spack location -i hwloc $compiler)
export SPACK_HYPRE_DIR=$(spack location -i hypre $compiler)
export SPACK_OPENBLAS_DIR=$(spack location -i openblas $compiler)
export SPACK_OPENMPI_DIR=$(spack location -i openmpi $compiler)
export SPACK_OPENSSL_DIR=$(spack location -i openssl $compiler)
export SPACK_PAPI_DIR=$(spack location -i papi $compiler)
export SPACK_PETSC_DIR=$(spack location -i petsc $compiler)
export SPACK_PETSC_LIBS="$(echo $(
    env PKG_CONFIG_LIBDIR=$SPACK_PETSC_DIR/lib/pkgconfig pkg-config --libs --static PETSc;
    env PKG_CONFIG_LIBDIR=$SPACK_PETSC_DIR/lib/pkgconfig pkg-config --libs PETSc) |
  perl -pe '
    s{(\S+)/lib([^ /]+)\.a}{-L\1 -l\2}g;
    s{-L([^ :]+):(\S+)}{-L\1 -L\2}g;
    s{lib([^ /]+)\.a}{-l\1}g;
    s{-L(\S+)}{-L\1 -Wl,-rpath,\1}g')"
export SPACK_ZLIB_DIR=$(spack location -i zlib $compiler)
```

In my projects, I'm using these `DIR` variables to set include and library path, and I'm also adding the respective `rpath` options. It would be nicer if Spack provided these environment variables automatically, or if it could generate pkgconfig descriptions for each package.

**Comment by glennpj** [comment]
@alalazo Yes, CPATH is a "fat interface" but so are all of the *PATH environment variables. The module load order is always a factor and one is probably more likely to see a problem with PATH than CPATH. Specifically regarding header name clash, that is what the module 'conflict' directive is for in module files. Header name clashes should not occur within a set of properly written environment modules. If a clash does arise, it is a bug that is fixed by adding conflict statements to the respective module files.

@tgamblin Please make it a configuration option to support *PATH settings. There is an expectation of users that when loading an environment module that the environment is setup to make use of that package.

**Comment by citibeth** [comment]
Erik,

There's gotta be a better way.  The file you show above is the same amount
of work as writing a package.py file and its depends_on() declarations.
Surely, Spack can generate environment-setup scripts like this
automatically.

-- Elizabeth

**Comment by eschnett** [comment]
I'm sure it can. I'm also sure it should. But this script works here and now. I'll be the first to switch over to a better mechanism once it's available as pull request.

**Comment by citibeth** [comment]
Erik,

The following will do that:

https://github.com/LLNL/spack/pull/474

It's a bit of a hack right now, really a first proof of functionality.  But
it gets the job done, and I'm working on an improved UI for it.  If you can
comment on some of the proposals/questions I pose in the discussion, that
would be really helpful!

**Comment by alalazo** [comment]
@glennpj I think you won't buy me on that :smile: Build system like CMake know very well how to tell the compiler where to look for headers and they do it at the proper granularity. In my experience `CPATH` has always caused more troubles than benefits, but I guess that other people may have different opinions on that.

**Pull request merged**
