### PR TITLE
New package: py-ghp-import

### PR DESCRIPTION
**Pull request by myan-rarcellino-nnl**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Will defer merge decision until @adamjstewart has a chance to comment.

**Comment by tldahlgren** [comment]
I should note the build fails for me on the `py-python-dateutil` package:

```
==> py-python-dateutil: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/usr/tce/bin/python3.7' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss' '.'

2 errors found in build log:
     11    Created temporary directory: /tmp/dahlgren/pip-install-mtilkmg1
     12    Processing /tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-
           2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src
     13      Added file:///tmp/dahlgren/spack-stage/spack-stage-py-python-dateu
           til-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src to build tracke
           r '/tmp/dahlgren/pip-build-tracker-swfy5ozu'
     14      Created temporary directory: /tmp/dahlgren/pip-modern-metadata-52y
           2u1nm
     15      Preparing metadata (pyproject.toml): started
     16      Running command Preparing metadata (pyproject.toml)
  >> 17    setup.py:18: DeprecationWarning: distutils Version classes are depre
           cated. Use packaging.version instead.
     18        if LooseVersion(setuptools.__version__) <= LooseVersion("24.3"):
     19      Traceback (most recent call last):
     20        File "/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-bro
           adwell/gcc-8.3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/
           python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py
           ", line 363, in <module>
     21          main()
     22        File "/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-bro
           adwell/gcc-8.3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/
           python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py
           ", line 345, in main
     23          json_out['return_val'] = hook(**hook_input['kwargs'])

     ...

     62      ╰─> See above for output.
     63    
     64      note: This error originates from a subprocess, and is likely not a
            problem with pip.
     65      full command: /usr/tce/packages/python/python-3.7.2/bin/python3 /u
           sr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8
           .3.1/py-pip-22.1.2-hkjcjrncrfss35k66x75jr27ujkk2gjr/lib/python3.7/si
           te-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_met
           adata_for_build_wheel /var/tmp/dahlgren/tmp6rxhwu2r
     66      cwd: /tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-2.8.
           2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-src
     67      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 68    error: metadata-generation-failed
     69    
     70    × Encountered error while generating package metadata.
     71    ╰─> See above for output.
     72    
     73    note: This is an issue with the package mentioned above, not pip.
     74    hint: See above for details.

See build log for details:
  /var/tmp/dahlgren/spack-stage/spack-stage-py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss/spack-build-out.txt

==> Warning: Skipping build of py-ghp-import-2.1.0-75yddpx7rbybi6k2qwhd2rj7t53uyht3 since py-python-dateutil-2.8.2-d5e5cpga2s547en3mxhd7yqtenvcqdss failed
==> Error: py-ghp-import-2.1.0-75yddpx7rbybi6k2qwhd2rj7t53uyht3: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
@tldahlgren can you open an issue and assign me? Our error msg regex is useless for Python build failures so the actual build failure is somewhere else in the log.

**Pull request merged**
