### PR TITLE
glib: add missing libelf dep

### PR DESCRIPTION
**Pull request by haampie**
Detected using #28109

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot fix style

**Review by michaelkuhn — COMMENTED** [review]
Thanks! Could you also add `args.append("-Dlibelf=enabled")` in `meson_args`?

**Review by michaelkuhn — APPROVED** [review]
Thanks!

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Pull request merged**
