### PR TITLE
Separate integration tests; simplify test scripts

### PR DESCRIPTION
**Pull request by tgamblin**
Test scripts now build `libdwarf`, `HDF5` and `py-numpy` in parallel with the unit tests.  This also reworks and simplifies the test scripts a bit, so they're easier to maintain.

- [x] Move build tests out of the regular Travis unit tests, add more smoke test packages to build.

- [x] Run all test scripts with bash -e, which fails on error.

- [x] Factor coverage out into a Travis environment variable, so it's more obvious from .travis.yml which tests contribute to coverage and which don't.

- [x] Factor dependency checking and much of the front-matter in tests scripts into a setup.sh script, which is sourced by all the test scripts.  Extra cruft in each tests script now reduced to 2 lines at the beginning.

### CODE REVIEW

**Comment by tgamblin** [comment]
I suppose we could parallelize those built tests a bit if we need to.  For example, the package built could be a Travis env var.  At this granularity, I'm not sure whether it is better to have many containers or one.

**Comment by alalazo** [comment]
:+1: This will prevent smoke build tests to fail and Travis to give green light because unit tests succeeded (as sometimes happen right now)

**Comment by adamjstewart** [comment]
HDF5 and Numpy take a while to build. I'll be interested to see how this affects total test time.

**Comment by tgamblin** [comment]
I wanted something with MPI, BLAS, and Python to be tested.  So that's the rationale.  We could take out libdwarf, probably, and separating the builds will probably reduce test time as well.  Let's see how long it takes joined.  On my Mac it actually doesn't take all THAT long to build these.

**Comment by adamjstewart** [comment]
Honestly, I still think we should go with my proposal in #1576. Not all PRs are created equal, yet we run the same battery of tests on all of them. If I fixed a typo in the documentation, why should Travis try to build MPI, BLAS, and Python? If I add a new version of zlib, what good are the unit tests? If I add a new package to Spack or modify an existing package, Travis should actually try to _build_ that package. I know we're working on the test-suite stuff separately, and that's a good idea, but we really need to know immediately whether or not a PR will break a package before we merge it.

**Comment by tgamblin** [comment]
@adamjstewart: I think we should go with your proposal, too, but there's not currently a way to get Travis to do analysis on the code *before* spawning the build matrix, so I can't, e.g., *just* spawn the doc check.  I'd like it if they gave me one container to analyze the code with, then I could conditionally launch parts of the build matrix.

If we did a conditional build and only built the package that changed, or things that immediately depend on it, I think we'd quickly exceed the build time limit.  We could try it, though.  We could select one or two things that depend on the changed packages, but some of the larger packages are still going to require lots of deps to be built.  With #3845 and successors, we'll have binary installs soon, so that may change things in that we can quickly install the entire dependency stack and *just* test the root package.

The idea with this PR is just to get a slightly better smoke test in there, and to declutter the scripts.

Thoughts?

**Comment by adamjstewart** [comment]
I don't disagree with this PR, and there are certainly things in it that we definitely need, like fixing the exit codes and exiting immediately. I just feel like building MPI, BLAS, HDF5, Python, Numpy, etc takes longer than building most packages and all of their dependencies. There are obviously some extreme cases of course. 

My point isn't that tests take too long, it's that we need to selectively run tests based on what files were modified in a PR. I understand that Travis won't less us change the build matrix after the fact, but we can exit immediately from tests if they're pointless. That would be better than waiting.

What if we skipped the installation and just tested things like `spack fetch`, `spack patch`, and `spack spec` for every modified package? That would be better than testing nothing at all. It would allow us to easily add installation later if we decide we want to do that too. I'm willing to take a stab at this maybe next month. We can talk about the implementation details later if you think that's the way to go.

**Comment by alalazo** [comment]
First issue here:
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by tgamblin** [comment]
The Python 3 builds failed with #4004, which is the kind of coverage I was going for.  I want to have at least something in the travis tests that hits the full pipeline.

The other errors, though,  are bearing out the idea that travis is not particularly well suited to this type of test.  The previous round failed for lack of log output -- so we have to run with install -v, but then we hit the size limit.  I think the solution is to build something simple, like we did before, and hurry up and get the package build bit we're working on done.

I will note that total CPU time here was 1h22m, vs. 44m for the mainline,, but the latency of the full suite was ~22m for both.  So I think we can add more parallel tests (at least with Linux workers) without reducing turnaround for small PRs.

**Comment by alalazo** [comment]
@tgamblin 
> If we did a conditional build and only built the package that changed, or things that immediately depend on it, I think we'd quickly exceed the build time limit. 

I agree that Travis is not the right tool to do something like that. 

In the long run I think we should better construct on @kielfriedt #2917 and have a few sites polling github, trying just the builds that are relevant for the packages that were modified in a PR and pushing a notification to github once they know if the builds succeeded or not. 

From Spack perspective I think we need a couple of commands like (naming is provisional, of course):
```console
# Creates a stack.yaml file inspecting what changed in this branch
# with respect to develop, the same way `spack flake8` does
spack create-build-stack ...

# Then use the newly created build matrix
spack install -f suite.yaml
```
Once #2917 will be in place I don't see this part as extremely difficult to treat. Probably it will take a lot longer to decide what is relevant to build (that information should come with packages, and we can't try every sample in the combinatorial space) and to set up "our build farms" around the world :smile:

**Comment by tgamblin** [comment]
> In the long run I think we should better construct on @kielfriedt #2917 and have a few sites polling github, trying just the builds that are relevant for the packages that were modified in a PR and pushing a notification to github once they know if the builds succeeded or not.

This is actually what we're working on today 😄   So stay tuned...

**Comment by tgamblin** [comment]
@adamjstewart @alalazo: ok, this completed successfully, and this increases coverage by .64%

I removed the OpenMPI build (which is long) and reduced the number of test packages to one (`hypre^mpich`).  That package has depends on `blas`, `lapack`, and `mpi`, so I think it is a reasonable test.  Both Linux builds also completed before the mac builder.

We could, as @adamjstewart suggests, add more commands to the test scripts to get the commands covered better.  That seems like something for another PR -- it could be a separate scripts alongside the others.

**Pull request merged**
