### PR TITLE
Add fpm 0.7.0

### PR DESCRIPTION
**Pull request by wyphan**
SHA256 sum taken from GitHub release page.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to give @awvwgk time to comment.

**Review by awvwgk — APPROVED** [review]
Thanks, looks good to me.

**Comment by tldahlgren** [comment]
One of the CI stacks has the failure:

```
...
Waiting for pod pipeline/runner-sasncrpb-project-2-concurrent-7tnmkl to be running, status is Pending
	ContainersNotInitialized: "containers with incomplete status: [init-permissions]"
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
WARNING: Failed to pull image with policy "IfNotPresent": image pull failed: pull QPS exceeded
ERROR: Job failed: prepare environment: waiting for pod running: pulling image "ghcr.io/spack/e4s-ubuntu-18.04:v2021-10-18": image pull failed: pull QPS exceeded. Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

**Comment by wyphan** [comment]
@spackbot rerun pipeline

**Pull request merged**
