### PR TITLE
petsc: add +hwloc and +openmp variants

### LINKED ISSUE #23550: Installation issue: petsc+mumps [^mumps+openmp]
```console
$ spack install petsc+mumps
```
fails since PRs https://github.com/spack/spack/pull/23161 by @RemiLacroix-IDRIS (add `+openmp` version to mumps)  and https://github.com/spack/spack/pull/23143 by me (set `+openmp` as default for mumps): a test program for mumps fails for not finding openmp in petsc's configure.

https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MATSOLVERMUMPS.html reads 
> "Use` ./configure --with-openmp --download-hwloc` (or `--with-hwloc`) to enable running MUMPS in MPI+OpenMP hybrid mode and non-MUMPS in flat-MPI mode."

@balay @jedbrown @BarrySmith 
I can work on a PR for this.

Just adding 
```python
            if spec.satisfies('^mumps+openmp'):
                options.extend([
                    '--with-openmp=1'
                ])
```
solves the installation issue, but as far as I understand, when `^mumps+openmp`, petsc should depend on hwloc and have `--with-openmp=1` and `--with-hwloc-dir=...`
Am I correct?

Or should we add `+openmp` and `+hwloc` variants to petsc and use conflicts to forbid `spack install petsc ~openmp ^mumps +openmp` and `spack install petsc ~hwloc ^mumps +openmp`?

### PR DESCRIPTION
**Pull request by lpoirel**
fixes #23550 

@jedbrown @balay @BarrySmith

### CODE REVIEW

**Comment by alalazo** [comment]
@jedbrown @balay @BarrySmith ping

**Comment by lpoirel** [comment]
Hi,
Is there something I can do to make reviewing easier?

**Review by alalazo — APPROVED** [review]
This LGTM, but it would be good if one of the maintainer could also take a look.

**Comment by alalazo** [comment]
@jedbrown @balay @BarrySmith Can you check if the changes in this PR are fine?

**Comment by alalazo** [comment]
Going ahead with the merge since we had no reply in two weeks. Feel free to comment if there is need for follow up changes.

**Pull request merged**
