### PR TITLE
[py-statsmodels] added version 0.12.1 and updated dependencies accord…

### PR DESCRIPTION
**Pull request by qwertos**
…ingly

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Shouldn't `python@:3.6` be `python@3.6:`?

**Comment by qwertos** [comment]
Double check the when arguments on that line and the line below it

**Comment by adamjstewart** [comment]
Ah, in that case we need a new line because the latest version only supports Python 3.6+

**Comment by qwertos** [comment]
fixed

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
