### PR TITLE
New package: py-torchdiffeq

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new sha256.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
Do we want to include this in CI? We have just about every other ML package in CI now. You would just add a new line to `share/spack/gitlab/cloud_pipelines/stacks/ml-*/spack.yaml`

**Review by adamjstewart — DISMISSED** [review]

**Comment by tldahlgren** [comment]
There are still style checks that need to be corrected manually:

```
==> Running black checks
--- var/spack/repos/builtin/packages/py-torchdiffeq/package.py	2022-12-08 19:31:33.451928 +0000
+++ var/spack/repos/builtin/packages/py-torchdiffeq/package.py	2022-12-08 19:31:59.506692 +0000
@@ -8,13 +8,13 @@
 
 class PyTorchdiffeq(PythonPackage):
     """ODE solvers and adjoint sensitivity analysis in PyTorch."""
 
     homepage = "https://github.com/rtqichen/torchdiffeq"
-    pypi     = "torchdiffeq/torchdiffeq-0.2.3.tar.gz"
+    pypi = "torchdiffeq/torchdiffeq-0.2.3.tar.gz"
 
-    version('0.2.3', sha256='fe75f434b9090ac0c27702e02bed21472b0f87035be6581f51edc5d4013ea31a')
+    version("0.2.3", sha256="fe75f434b9090ac0c27702e02bed21472b0f87035be6581f51edc5d4013ea31a")
 
-    depends_on('python@3.6:3', type=('build', 'run'))
-    depends_on('py-setuptools', type='build')
-    depends_on('py-torch@1.3:', type=('build', 'run'))
-    depends_on('py-scipy@1.4:', type=('build', 'run'))
+    depends_on("python@3.6:3", type=("build", "run"))
+    depends_on("py-setuptools", type="build")
+    depends_on("py-torch@1.3:", type=("build", "run"))
+    depends_on("py-scipy@1.4:", type=("build", "run"))
would reformat var/spack/repos/builtin/packages/py-torchdiffeq/package.py
Oh no! 💥 💔 💥
1 file would be reformatted.
  black found errors
==> Running flake8 checks
==> Error: spack style found errors
var/spack/repos/builtin/packages/py-torchdiffeq/package.py:13: [E221] multiple spaces before operator
  flake8 found errors
```

**Comment by adamjstewart** [comment]
Spackbot should have fixed those. I'll try again and report the issue on #ci-and-pipelines

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
> Spackbot should have fixed those. I'll try again and report the issue on #ci-and-pipelines

I think that can depend on how a PR is created (i.e., if allow maintainers(?) to edit then it will fix, if not it won't).

I had someone have this issue within the last couple of weeks.  He said he switched to allow edits but spackbot still couldn't do it.

**Comment by qwertos** [comment]
I have allow edits by maintainers enabled

**Comment by tldahlgren** [comment]
> I have allow edits by maintainers enabled

🤔

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
