### PR TITLE
opengl: fix concretization

### PR DESCRIPTION
**Pull request by nilsvu**
The `provides` statements generated unsatisfiable constraints. When `opengl@4.1` was added as an external package, then

```
spack --show-cores=minimized spec paraview ^opengl
```

was unsatisfiable, although `paraview` lists `depends_on('gl@3.2:')`:

```
Input spec
--------------------------------
 -   paraview
 -       ^opengl

Concretized
--------------------------------
==> Error: paraview ^opengl is unsatisfiable, conflicts are:
  Single valued variants must have a single value
  condition(3379)
  condition(3601)
  condition(4244)
  condition(4245)
  dependency_type(4244,"build")
  dependency_type(4245,"build")
  imposed_constraint(3379,"version_satisfies","gl",":1.0")
  imposed_constraint(4244,"version_satisfies","gl","1.2:")
  imposed_constraint(4245,"version_satisfies","gl","3.2:")
  no version satisfies the given constraints
  node("opengl")
  root("paraview")
  variant_condition(3601,"paraview","opengl2")
  variant_single_value("paraview","opengl2")
  version_satisfies("gl",":1.2","1.0")
  version_satisfies("gl",":1.2","1.2")
  version_satisfies("gl",":1.3","1.0")
  version_satisfies("gl",":1.3","1.3")
  version_satisfies("gl",":1.4","1.0")
  version_satisfies("gl",":1.4","1.4")
  version_satisfies("gl",":1.5","1.0")
  version_satisfies("gl",":1.5","1.5")
  version_satisfies("gl",":2.0","1.0")
  version_satisfies("gl",":2.0","2.0")
  version_satisfies("gl",":2.1","1.0")
  version_satisfies("gl",":2.1","2.1")
  version_satisfies("gl",":3.0","1.0")
  version_satisfies("gl",":3.0","3.0")
  version_satisfies("gl",":3.1","1.0")
  version_satisfies("gl",":3.1","3.1")
  version_satisfies("gl",":3.2","1.0")
  version_satisfies("gl",":3.2","3.2")
  version_satisfies("gl",":3.3","1.0")
  version_satisfies("gl",":3.3","3.3")
  version_satisfies("gl",":4.1","1.0")
  version_satisfies("gl",":4.1","4.1")
  version_satisfies("gl",":4.2","1.0")
  version_satisfies("gl",":4.2","4.2")
  version_satisfies("gl",":4.3","1.0")
  version_satisfies("gl",":4.3","4.3")
  version_satisfies("gl",":4.4","1.0")
  version_satisfies("gl",":4.4","4.4")
  version_satisfies("gl",":4.5","1.0")
  version_satisfies("gl",":4.5","4.5")
  version_satisfies("opengl","1.0:","4.1")
```

 This may be a bug in the concretizer, so this PR may not be the ideal solution.

`spack debug report`:

* **Spack:** 0.17.1-758-0277067e5f
* **Python:** 3.9.9
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo

### CODE REVIEW

**Comment by nilsvu** [comment]
Question: When I set `opengl@2.1` as an external package, then `paraview ^opengl` still picks it up although it doesn't meet the version requirement `opengl@3.2:`. Is this expected or a bug?

**Comment by nilsvu** [comment]
Another question: On macOS, `glxinfo` seems to report the wrong version. Based on https://support.apple.com/en-us/HT202823 my machine should have OpenGL 4.1, but `glxinfo` reports 2.1, so `spack external find` adds an entry for `opengl@2.1`. Does anyone have more information on this, or ideas what to do about it?

Edit: I believe the reason for this might be that `glxinfo` reports the OpenGL compatibility/legacy mode version. This may be misleading..

**Comment by nilsvu** [comment]
@tgamblin I believe this might be a concretizer bug, could you take a look?

**Comment by alalazo** [comment]
Closing since the `opengl` package has been reworked extensively in the meanwhile

**Pull request closed without merging**
