### PR TITLE
Add patch for compiling `llvm ~omp_as_runtime`

### PR DESCRIPTION
**Pull request by msimberg**
Without this patch `llvm ~omp_as_runtime` fails as soon as the `build` stage starts with the following error:
```
==> llvm: Executing phase: 'build'
==> [2022-05-10-11:28:11.264234] 'ninja' '-j8' '-v'
ninja: error: '/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hwloc-2.7.1-2535mvwrxweatvm755qjqmdudpbtlmuh/lib/libhwloc.so -lrt', needed by 'lib/libomp.so', missing and no known rule to make it
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j8' '-v'

1 error found in build log:
     1035        PYTHON_EXECUTABLE
     1036
     1037
     1038    -- Build files have been written to: /run/user/24491/simbergm/spack-stage-llvm-13.0.1-gngi3qbhwmk52fii4gkftuo2y7ybuhsy/spack-build-gngi3qb
     1039    ==> llvm: Executing phase: 'build'
     1040    ==> [2022-05-10-11:28:11.264234] 'ninja' '-j8' '-v'
  >> 1041    ninja: error: '/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hwloc-2.7.1-2535mvwrxweatvm755qjqmdudpbtlmuh/lib/libhwloc.so -lrt', needed by 'lib/libomp.so', missing and no known rule to make it

See build log for details:
  /run/user/24491/simbergm/spack-stage-llvm-13.0.1-gngi3qbhwmk52fii4gkftuo2y7ybuhsy/spack-build-out.txt
```
The reason for this seems to be that if `LIBOMP_CONFIGURED_LIBFLAGS` is a plain string in this call: https://github.com/llvm/llvm-project/blob/f14a1f26ade3786d3cda566a1c38f92f7fbb24b3/openmp/runtime/src/CMakeLists.txt#L148 CMake interprets the variable as one thing to link to. In this case `/apps/daint/UES/simbergm/spack/opt/spack/cray-cnl7-haswell/gcc-11.2.0/hwloc-2.7.1-2535mvwrxweatvm755qjqmdudpbtlmuh/lib/libhwloc.so -lrt` is considered one single dependency. If the variable is turned into a CMake list it configures and builds correctly. OpenMP also seems to work fine from what I can tell with a simple test.

In practice I don't see this error with `llvm` <= 11 becase the older versions don't add `-lrt` (https://github.com/llvm/llvm-project/blob/02d6845234865675d7e802e1982efca6ca86c866/openmp/runtime/cmake/LibompHandleFlags.cmake#L135-L137). However, I think the fundamental problem is still there so I'm applying the patch for older versions as well. It just happens that `LIBOMP_CONFIGURED_LIBFLAGS` doesn't have more than one item in those older versions in my typical configuration (on linux), but it would still be a problem on other platforms. The oldest version where the patched file exists is 3.7 and the patch still applies there. I have not tested this on e.g. 3.7.

I suppose this needs to be upstreamed and they may have another solution to the problem.

### CODE REVIEW

**Comment by haampie** [comment]
Can we upstream this?

**Review by haampie — APPROVED** [review]

**Comment by msimberg** [comment]
> Can we upstream this?

Yes, that's the plan. I just have to familiarise myself with how to do that on llvm's phabricator thing.

**Comment by msimberg** [comment]
@JDeVlieghere pinging you since you may have comments on this?

**Comment by trws** [comment]
This looks really good.  I had basically written this off as an option but I'd be happy to take it.

**Comment by msimberg** [comment]
For reference, here's the same patch submitted upstream: https://reviews.llvm.org/D125370. Awaiting comments over there.

**Comment by trws** [comment]
Nice, looks already approved.  Merging, and thanks for the patch this is great!

**Comment by msimberg** [comment]
> Nice, looks already approved. Merging, and thanks for the patch this is great!

Note that it was @haampie who (accidentally?) approved it. Not a core llvm maintainer. So they may still request changes to it...

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
