### PR TITLE
glib: add v2.82.2

### PR DESCRIPTION
**Pull request by adamjstewart**
Distutils was finally removed

Closes #44323

### CODE REVIEW

**Comment by michaelkuhn** [comment]
Has anything changed regarding the gobject-introspection situation mentioned in #44323? If not, this will break once we update gobject-introspection. Moreover, 2.83 is a development version, which we have traditionally not included.

**Comment by adamjstewart** [comment]
> Has anything changed regarding the gobject-introspection situation mentioned in #44323? If not, this will break once we update gobject-introspection.

Thanks, hadn't noticed that PR. I don't know anything about glib or gobject-introspection, I'm just trying to add support for Python 3.12+. Note that gobject-introspection still doesn't support Python 3.12+ anyway: https://github.com/spack/spack/pull/47767

> Moreover, 2.83 is a development version, which we have traditionally not included.

I'm happy to add `preferred=True` to the older version, but would like to be able to build with Python 3.12+ so let's add this development version.

**Comment by adamjstewart** [comment]
Which versions are dev versions? Can we add 2.82?

**Comment by michaelkuhn** [comment]
Let's prefer 2.78 for now to make sure nothing breaks. I'll try to take a look at the gobject-introspection situation again, but sadly I don't have too much time for Spack-related stuff at the moment.

**Comment by adamjstewart** [comment]
Note that the default version of glib would then not be compatible with the default version of Python. I'm not sure which the concretizer would choose in the case. I suspect it depends on what is already installed.

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Pull request merged**
