### PR TITLE
intel-mpi-benchmarks: Take in upstream bugfix patches.

### PR DESCRIPTION
**Pull request by t-karatsu**
Take in the following upstream bugfix patches.:
https://github.com/intel/mpi-benchmarks/pull/19
https://github.com/intel/mpi-benchmarks/pull/20

### CODE REVIEW

**Comment by tldahlgren** [comment]
@carsonwoods Would you like to review this PR?

**Comment by carsonwoods** [comment]
@t-karatsu @tldahlgren this PR looks good. The only question I have is, do these patches apply to all versions of the benchmarks? Or only version 2019.6? If they're explicitly for the latest release, then the version modifiers should be added like this (or should be adjusted to match the proper version):

```
patch(‘add_const.patch’, when=‘@2019.6’)
patch(‘reorder_benchmark_macros.patch’, when=‘@2019.6’)
``` 

Regardless, they should probably have a version cap, so that if a future release is added, they are not reapplied. I believe something like this would do that:

```
patch(‘add_const.patch’, when=‘@:2019.6’)
patch(‘reorder_benchmark_macros.patch’, when=‘@:2019.6’)
```

**Comment by t-karatsu** [comment]
@carsonwoods 
Thanks for comment. Since I was able to build the version from `2019.2` to `2019.5` with patches, I changed it to patch up to the current latest version.

**Review by carsonwoods — APPROVED** [review]
Great, this looks good to me now.

**Review by tldahlgren — APPROVED** [review]
@carsonwoods Thanks!

**Comment by tldahlgren** [comment]
Thank you for your contribution!

**Pull request merged**
