### PR TITLE
tests/remaining E4S packages: convert to new stand-alone test process

### PR DESCRIPTION
**Pull request by tldahlgren**
Depends on #34236 

TODO:

- [ ] Update after above PR is merged
- [ ] (re)test

### CODE REVIEW

**Review by kmorel — APPROVED** [review]
The VTK-m changes look good to me. I defer to @vicentebolea if there are any errors with it.

**Comment by vicentebolea** [comment]
> The VTK-m changes look good to me. I defer to @vicentebolea if there are any errors with it.

Looks good to me too

**Review by bosilca — APPROVED** [review]
the parsec change looks ok.

**Review by cwsmith — APPROVED** [review]
The Omega_h and PUMI changes look good.  Thank you.

**Review by pmccormick — APPROVED** [review]
Looks good to me.  Thanks.

**Review by vicentebolea — APPROVED** [review]

**Comment by tldahlgren** [comment]
Superseded by combination of: #45010 #44733 #44712 #45170 #45122 #45699 #45181 #44874 #45373 #44705

**Pull request closed without merging**
