### PR TITLE
GMT: add new versions

### PR DESCRIPTION
**Pull request by adamjstewart**
I was originally planning on removing GMT 4 to simplify the package, but it turns out a lot of other packages depend on GMT 4.

Confirmed that GMT 6 and 4 still build. GMT 5 doesn't seem to build properly on macOS arm64, so I couldn't test that.

@alalazo you might want to review this to make sure I got the multi-build system stuff correct. I noticed that setting:
```python
parallel = False
```
in `AutotoolsBuilder` didn't actually work, I had to override the `build` and `install` methods.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
Ping @alalazo

**Review by alalazo — APPROVED** [review]
I think we didn't move `parallel` to `Builders`, so it's still on `Packages` currently. Did you try to use:
```python
@property
def parallel(self):
    return self.spec.satisfies("build_system"=cmake)
```
?

**Comment by adamjstewart** [comment]
Update: both the parallel attribute and property work when in the package class, but not when in the builder class. I would expect parallel to only work in the builder class since it only relates to compilation.

**Comment by adamjstewart** [comment]
Will merge this to get it out of my queue, but @alalazo can you open an issue about the parallel thing so we don't forget?

**Pull request merged**
