### PR TITLE
UPC++/GASNet-EX 2023.3.0 update

### PR DESCRIPTION
**Pull request by bonachea**
Updates UPC++ and GASNet-EX to 2023.3.0 release, which includes new support for Level Zero on Intel GPUs.

Add recent releases to oneapi-level-zero in order to satisfy a version requirement.

### CODE REVIEW

**Review by PHHargrove — DISMISSED** [review]
I have verified the new sha256 hashes for GASNet-EX and UPC++, and I have visually verified that the new and updated logic in `upcxx/package.py` appears correct to me.

I have not attempted to verify the added hashes for recent oneapi-level-zero versions.

**Review by tldahlgren — APPROVED** [review]
Confirmed all 9 affected version sha256.  Would like to here from @rscohn2 at least about the `oneapi-level-zero` changes.

**Review by PHHargrove — APPROVED** [review]

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
I'm merging this so I have a develop commit to backport to 0.19, if there are comments on the intel-oneapi-levelzero changes then we'll hear it 🙃

**Comment by rscohn2** [comment]
Looks good

**Pull request merged**
