### PR TITLE
Implemented +sycl for slate

### PR DESCRIPTION
**Pull request by G-Ragghianti**

### CODE REVIEW

**Comment by G-Ragghianti** [comment]
@eugeneswalker @mgates3 The e4s CI has failed because the concretizer has elected to use `~mpi` even though the package has it on by default.  SLATE requires MPI support, so I think it may be prudent to disable the mpi variant for the current and future releases.  Thoughts?

**Comment by eugeneswalker** [comment]
> @eugeneswalker @mgates3 The e4s CI has failed because the concretizer has elected to use `~mpi` even though the package has it on by default. SLATE requires MPI support, so I think it may be prudent to disable the mpi variant for the current and future releases. Thoughts?

I don't know why the concretizer did that, but I just pushed 7550fc0e75afa3430d8b05ae2a17c1e06e517a51 which is explicit that we want `slate +sycl +mpi`

**Comment by G-Ragghianti** [comment]
The e4s pipeline is failing now due to timeout.

**Comment by eugeneswalker** [comment]
> The e4s pipeline is failing now due to timeout.

I believe there is a concretization issue when I try to force `slate +sycl +mpi` and perhaps this is related to why the concretizer will select `~mpi` when only `slate +sycl` is specified, despite `+mpi` being the default both in Slate's package.py and [in the E4S OneAPI Spack environment](https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml#L17).

I filed an issue here:
* https://github.com/spack/spack/issues/40118

Should we remove `slate +sycl` from CI so that this PR can move forward in the meantime? Or, should we wait and see what @alalazo might have to say about this? Perhaps it is something that can be addressed here by change to package.py. What do you think?

**Comment by G-Ragghianti** [comment]
OK, I think understand the issue now.  SLATE currently requires the intel-oneapi-mpi MPI implementation when supporting sycl.  This is enforced in the slate/package.py.  However the e4s environment requires mpich.  I think we can't include SLATE in the sycl e4s until SLATE supports mpich.

@mgates3 Do you concur?

~~The e4s environment has "unify: false", so I think it should still be able to concretize the environment, but maybe it is just too difficult of a task (and therefore times out).  I'm going to try to concretize the e4s environment on my system to see if it would eventually succeed or fail.~~

**Comment by eugeneswalker** [comment]
I just commented it out in our E4S OneAPI stack for now. We will find a way to get it in ASAP, but in the meantime we don't want to hold up this PR. Thanks!

**Comment by mgates3** [comment]
I don't know a reason that SLATE would require Intel MPI when using SYCL. Is there an inherent incompatibility between (MPICH or Open MPI) and SYCL? It seems that would affect other packages besides SLATE.

In SLATE's GitHub CI, there's a comment that "Open MPI hides SYCL devices, at least in our current CI." I suspect this is an incompatibility in our install of Open MPI, rather than an inherent incompatibility between Open MPI and SYCL. Perhaps building Open MPI without CUDA support would fix it.

**Comment by G-Ragghianti** [comment]
OK, I'm going to expand my tests to include openmpi, mpich, and intel-oneapi-mpi.  If this is good, then we can add slate+sycl back to the oneapi e4s stack.

> I don't know a reason that SLATE would require Intel MPI when using SYCL. Is there an inherent incompatibility between (MPICH or Open MPI) and SYCL? It seems that would affect other packages besides SLATE.
> 
> In SLATE's GitHub CI, there's a comment that "Open MPI hides SYCL devices, at least in our current CI." I suspect this is an incompatibility in our install of Open MPI, rather than an inherent incompatibility between Open MPI and SYCL. Perhaps building Open MPI without CUDA support would fix it.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
all checks are green- should we merge?

**Comment by G-Ragghianti** [comment]
Yes please, and thanks!

**Pull request merged**
