### PR TITLE
geant4: GEANT4_INSTALL_DATA=OFF and depends_on geant4-data type=run

### PR DESCRIPTION
**Pull request by wdconinc**
Geant4 doesn't need to use the geant4-data prefix, as discussed in https://github.com/spack/spack/pull/28388#issuecomment-1018612751

Tested that this still picks up the data files through the environment variables and works fine.

Maintainer: @drbenmorgan

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
The addition of `type=run` seems sensible to me for a data only package. I'll be waiting for maintainer's review before merging.

**Review by drbenmorgan — APPROVED** [review]
All good for me, many thanks @wdconinc!

**Comment by sethrj** [comment]
@wdconinc @drbenmorgan This change breaks CMake configure file installed by Geant4: `Geant4_DATASETS` references locations at `$PREFIX/share/Geant4-10.7.3/data/` that no longer exist. Our project uses the Geant4 CMake environment rather than less stable environment variables to find the correct geant data for testing etc. Can I add a  PR to symlink the `geant4-data` share directory to the Geant4-created directory?

**Comment by wdconinc** [comment]
Sorry to hear this broke the configure file. I think that such a link would be a great way to fix this.

**Pull request merged**
