### PR TITLE
Nextflow: add 23.04.1

### PR DESCRIPTION
**Pull request by dialvarezs**
And deprecate versions lower than 22.04.

### CODE REVIEW

**Review by marcodelapierre — CHANGES_REQUESTED** [review]
Thanks for your contribution.
May I ask you what is the rationale behind deprecating those earlier versions?

**Comment by dialvarezs** [comment]
Sure. The reasoning behind this is that in 22.04, DSL2 became the default syntax for Nextflow. Considering that a year has already passed, it might not be the best practice to continue using DSL1, and most actively maintained pipelines have already migrated to DSL2 AFAIK.

Additionally, the development process of Nextflow does not consider backports of changes to older versions (only the current version is developed), so it would generally be recommended to use the latest version.

**Comment by marcodelapierre** [comment]
Thanks for clarifying. Let me ping @pditommaso from Seqera , I think it is beneficial to get the Nextflow devs view on this aspect.

**Comment by pditommaso** [comment]
It think it makes sense, not much that can be done on nextflow side

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256.

**Comment by tldahlgren** [comment]
@marcodelapierre Are you okay with this PR being merged at this point or did you want change(s)?

**Review by marcodelapierre — APPROVED** [review]
Just had a quick chat with Paolo from Seqera on this one, all good!

**Pull request merged**
