### PR TITLE
py-scipy: py-pythran is only a build dep

### PR DESCRIPTION
**Pull request by adamjstewart**
This should hopefully make it possible to concretize TF once @becker33 and @alalazo finish adding support for multiple versions of build deps in the DAG.

I could have sworn we linked to pythran, at least in older versions of scipy, but I can't test this due to older scipy not supporting newer pythran and older pythran not supporting newer macOS, so the mystery will always remain unless someone else wants to test and check the build log.

### CODE REVIEW

**Review by rgommers — DISMISSED** [review]
LGTM, thanks @adamjstewart. Glad we caught this. And yeah, let's not worry about older versions at this point.

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by bernhardkaindl** [comment]
@spackbot run pipeline

**Comment by bernhardkaindl** [comment]
@spackbot help

**Review by bernhardkaindl — APPROVED** [review]
Establish the approved state after the cosmetic update of pypi= after two LGTM approvals.

**Pull request merged**
