### PR TITLE
Update my mailmap entry

### PR DESCRIPTION
**Pull request by ax3l**
Affiliation update (a bit overdue).

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by tldahlgren** [comment]
@alalazo How is this file used?  Generated?  Maintained?

**Comment by tldahlgren** [comment]
> @alalazo How is this file used? Generated? Maintained?

I ask because I see at least 2 missing accounts and one with duplicate entries (both with invalid email in the fourth column).

**Comment by ax3l** [comment]
I think this is manually maintained.

Afaik, @tgamblin uses this to attribute institutional contributions to packages and code.

**Comment by tldahlgren** [comment]
> I think this is manually maintained.
> 
> Afaik, @tgamblin uses this to attribute institutional contributions to packages and code.

I hope not this version of it.  LLNL won't be getting as much credit as it could if that is the case.

**Comment by ax3l** [comment]
This file just defines aliases, otherwise people are identified by their usual commit email. But as I said, I am not sure.

**Comment by tgamblin** [comment]
I use this: https://github.com/spack/spack-contributions/blob/main/author-to-org.json

It really needs an update for different orgs by time of contribution.

But making mailmap correct is still good for looking at logs.

**Comment by tldahlgren** [comment]
> I use this: https://github.com/spack/spack-contributions/blob/main/author-to-org.json
> 
> It really needs an update for different orgs by time of contribution.
> 
> But making mailmap correct is still good for looking at logs.

Okay.  So the missing ppl that I noticed are in that list. 🙃

**Pull request merged**
