### PR TITLE
Jali: update version; delete older buggy versions

### PR DESCRIPTION
**Pull request by raovgarimella**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@raovgarimella we usually don't remove old versions of software from Spack packages in case someone needs to reproduce a previous build. See #15896 for more discussion. Can you leave the old versions in for now?

**Comment by raovgarimella** [comment]
OK. Will do.

I was unsure of the policy.


---------------------------------------------------------
Rao V Garimella                 Tel: (505) 665-2928
T-5, MS B284                    Email: rao@lanl.gov
Los Alamos National Lab         '\    '\
Los Alamos, NM 87545              ( )-( )
---------------------------------------------------------

________________________________

**Comment by adamjstewart** [comment]
Yeah, unfortunately there isn't really a policy right now, hence why I opened #15896.

**Comment by raovgarimella** [comment]
Shoot. I screwed something up in a rebase. I have to redo this PR

**Pull request closed without merging**
