### PR TITLE
Remove support for BlueGene/Q

### PR DESCRIPTION
**Pull request by alalazo**
Only a few BlueGene/Q remain in the top 500 and both Vulcan and Sequoia have been decommissioned. This PR removes support for BlueGene/Q in both core Spack and builtin packages. 

It can be merged as soon as there is agreement that we can deprecate support for BlueGene/Q.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM.  Only question is if you want to make additional related changes in this PR?

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Did you want to make related changes in the files listed below in the previous commit in this or a separate PR?

- `docs/basic_usage.rst`
- `docs/features.rst`
-  `llnl/util/lang.py`
- `spack/compiler.py`
- `spack/spec.py`

**Comment by alalazo** [comment]
@tldahlgren I think I changed all the places mentioning `bgq` in the docs. Let me know if you see others. Thanks for the review!

**Review by tldahlgren — APPROVED** [review]
LGTM.  Great catches on updating some of the API docstrings!

**Comment by tldahlgren** [comment]
Note the brew issue and what appears to be a hung `Waiting for status to be reported` issue (for `centos6`) are affecting required checks ATM.

**Comment by alalazo** [comment]
> Note the brew issue and what appears to be a hung Waiting for status to be reported issue (for centos6) are affecting required checks ATM.

Merged a fix for MacOS and re-run tests. It seems everything but `e4s` is green now but `e4s ` is failing also on `develop`. I need to check why but wouldn't consider that essential here. Imo this is ready to be triggered as soon as we want to :wave:  BG/Q

**Comment by becker33** [comment]
The e4s failure is because of `conduit ^hdf5~hl` not playing nicely with the newest version of `cmake`. Conduit developers and cmake developers are aware of it and I'm sure we'll have a fix soon, in the meantime @eugeneswalker is working on a version constraint to avoid the versions that don't play nicely together

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
