### PR TITLE
fast-float: new package

### PR DESCRIPTION
**Pull request by pranav-sivaraman**
Edit: Converting to draft since I need to handle the vendored test library.

### CODE REVIEW

**Comment by pranav-sivaraman** [comment]
@spackbot fix style

**Comment by pranav-sivaraman** [comment]
Why does this package fetch test files from the internet??????

**Comment by wdconinc** [comment]
> Why does this package fetch test files from the internet??????

If you wish to avoid the testing (which FetchContent does), you can apply either of two changes here:
- set `FASTFLOAT_SUPPLEMENTAL_TESTS` to `False`,
- provide `https://github.com/fastfloat/supplemental_test_files`, branch `main`, as a spack `resource` and use `FETCHCONTENT_SOURCE_DIR_SUPPLEMENTAL_TESTS_FILES` to point to it.

If you are interested in doing either of this (or something else), let me know. Otherwise, we can also just move forward with this and make a note that testing requires an internet connection.

**Comment by pranav-sivaraman** [comment]
I'll do the second option since it's always nice to have the tests. I need to submit a patch upstream that does a call to `find_package(doctest)` so I can change the dependency types for doctest to just `type=test`. Otherwise `doctest` will always appear as a dependency.

**Comment by wdconinc** [comment]
> so I can change the dependency types for doctest to just `type=test`

Won't work, unfortunately. Right now `CMakePackage`s suffer from the problem that the test dependendencies are mostly designed to solve the way tests are used in python. So, `depends_on("doctest", type="test")` will make `doctest` available only for the `ctest` run, not the build phase. Instead, we often end up just depending with `type="build"` instead, especially since test dependencies are typically light (and header only), so the cost of the extra install is minimal. See https://github.com/spack/spack/issues/29447 for more details.

**Comment by pranav-sivaraman** [comment]
> Won't work, unfortunately.

Hmm. I applied the PR patch locally and converted the `doctest` dependency to just `type=test` and both the package tests ran successfully. If I remove the patch then the build fails. 

> will make doctest available only for the ctest run, not the build phase.

Your correct in that `type=test` will make the dependency only available in the run phase not the build phase. Now I need to figure why is this working in the first place. I'm wondering if `CMAKE_PREFIX_PATH` gets populated for all dependencies and then `find_package` is able to correctly add the build dependency.

**Comment by pranav-sivaraman** [comment]
```shell
CMAKE_PREFIX_PATH variable [CMAKE_FIND_USE_CMAKE_PATH].

    /Users/psivaram/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/doctest-2.4.11-c6k3rhqejvrlii3gzqtjbuncmf6igpc5
    /Users/psivaram/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/cmake-3.30.2-dgmwj2dlinbjcclzdun6lwtj5zshoesa
    /Users/psivaram/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/gmake-4.4.1-di47qxldinwh7cwkn3vec4r7hny6jnhu
``` 

Looking at the `--debug-find` output I see that `doctest` gets added to the CMAKE_PREFIX_PATH variable. Now to narrow where in Spack is this being added.

**Comment by pranav-sivaraman** [comment]
How do you get `spack mirror` to fetch a git repo as a resource and then use it? I'm trying to test whether this works or not, but then Spack proceeds to do a git clone anyways for the resource when doing an install.

**Comment by wdconinc** [comment]
> How do you get `spack mirror` to fetch a git repo as a resource and then use it? I'm trying to test whether this works or not, but then Spack proceeds to do a git clone anyways for the resource when doing an install.

Good question, and not one I have the answer for. I'd ask this one on slack.

**Comment by pranav-sivaraman** [comment]
Seems to be following lines found in `build_environment.py`
```python
def get_cmake_prefix_path(pkg):
    # Note that unlike modifications_from_dependencies, this does not include
    # any edits to CMAKE_PREFIX_PATH defined in custom
    # setup_dependent_build_environment implementations of dependency packages
    build_deps = set(pkg.spec.dependencies(deptype=("build", "test")))
``` 
`doctest` gets added to `build_deps` since it matches the deptype of `test`. This then inserts `doctest`'s install location to `CMAKE_PREFIX_PATH` which causes the build work with a `find_package(doctest)` call. 

Not sure if this behavior is expected? I guess it should be fine for now?

**Review by wdconinc — APPROVED** [review]
Thanks. This looks fine now (and I was able to install and test in a clean spack install).

Thanks for figuring out that `doctest` as a `type="test"` dependency is fine. Maybe that issue I linked is only present for environments...

**Pull request merged**
