### PR TITLE
perl: add v5.40.0

### PR DESCRIPTION
**Pull request by wdconinc**
A new version of perl is out ([diff](https://github.com/Perl/perl5/compare/v5.38.2...v5.40.0)).

Let's see what breaks in the pipelines... Nothing!

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the version sha56.

Should the older versions still be marked `preferred`?

**Comment by wdconinc** [comment]
> Should the older versions still be marked `preferred`?

Perl uses even/odd maintenance/development releases. The package recipe marks all even releases as preferred over the odd releases which are not marked (or marked as deprecated).

**Comment by tldahlgren** [comment]
> > Should the older versions still be marked `preferred`?
> 
> Perl uses even/odd maintenance/development releases. The package recipe marks all even releases as preferred over the odd releases which are not marked (or marked as deprecated).

@alalazo Can correct me if I'm wrong but my recollection is that the concretizer wants/expects only one preferred version.

**Review by bernhardkaindl — COMMENTED** [review]
@wdconinc

All development releases (odd numbers) have been removed from the `perl` recipe.

Thus, all `preferred=True` can (and, I think, should) be removed as well.

Also, like Tamara pointed out, it is likely true that only one release should be preferred, and only if a newer development release is added.

I started a build with this change and could push it possibly later as an additional commit to be squashed on merge of this PR.

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
