### PR TITLE
Spack info maintain variant declaration order

### PR DESCRIPTION
**Pull request by markcmiller86**
fixes https://github.com/LLNL/spack/issues/4529

Since sorting one way or the other didn't seem to be a big deal, I adjusted logic so that variants are displayed during `spack info` in the order a package declares them.

This required me to add a member to a variant indicating its declaration order. Didn't see a cleaner way to handle it.

### CODE REVIEW

**Comment by markcmiller86** [comment]
Ok, I've tried this and it works. That said, doesn't this change the ordering used in *all* directive types? I am not sure I understand the implications of that throughout Spack and certainly don't have a test suite to test whether it might break some logic somewhere else?

**Comment by davydden** [comment]
something is wrong, from Travis:
```
Input spec
--------------------------------
mpileaks
Normalized
--------------------------------
==> Error: 'module' object has no attribute 'OrderedDict'
```

**Comment by davydden** [comment]
@markcmiller86 github can automatically close issues when PRs are merged, see https://github.com/blog/1506-closing-issues-via-pull-requests I edited your OP to make sure it will be done.

**Comment by alalazo** [comment]
@davydden I think this solution works only for `python@2.7:,3.2:`. More info [here](https://docs.python.org/2/library/collections.html).

**Comment by tgamblin** [comment]
@markcmiller86: can you add `from ordereddict_backport import OrderedDict` to this?  We use a backport (in, e.g., concretize and config) because `OrderedDict` was not in Python 2.6.

**Comment by tgamblin** [comment]
@markcmiller86:

> That said, doesn't this change the ordering used in all directive types? 

It does but since they used a regular `dict` before, there was (or shouldn't have been) any assumed ordering.  The places where it matters, like `Spec.to_node_dict()` (which is used by `Spec.to_yaml()`, which is used by `Spec.dag_hash()`) do their own sort to ensure determinism.

**Comment by markcmiller86** [comment]
> @tgamblin can you add from `ordereddict_backport import OrderedDict to this`?

I sure can. That said, I am curious about something on github. It seems like it is more work to have you type that request in here, me read it, then type it into my branch on my laptop, commit it and push it than it is for you to simply do it? Is that possible in a github PR? I mean, is it possible for a project member with admin privs. to revise the PR themselves? I am just really curious because in my work on other projects...I would not ever bother to ask some other developer to make a one line fix that I can easily make myself.

**Pull request closed without merging**
