### PR TITLE
Add new package: istio

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is it possible to build from source instead? I see some source tarballs available for download on GitHub. Spack is designed for HPC, where the performance boost from building from source is really important.

**Comment by darmac** [comment]
> Is it possible to build from source instead? I see some source tarballs available for download on GitHub. Spack is designed for HPC, where the performance boost from building from source is really important.

We want to build from source too, but according to the `Makefile`, it depends on docker, I'm afraid it will import some architecture conflicts(e.g. some tools may be amd64 binary).

Anyway, We will try build at first, if any problem blocking it, I will update some comments here.

**Comment by adamjstewart** [comment]
@darmac did you ever manage to build this from source?

**Comment by darmac** [comment]
> @darmac did you ever manage to build this from source?

Yes, but it looks little hard on `aarch64` platform. (It depends on `docker` and should add some more patch), 
I will discuss this package with my work-mate if we still need support a source building package next month

**Comment by darmac** [comment]
> @darmac did you ever manage to build this from source?

After we tried some building methods, I think it's hard to transplant the souce code building flow to `spack` now, it depends on 'docker' and some 'docker images'.
So shall we merge it by using binary or close this PR for now?

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
