### PR TITLE
g2tmpl: add 1.13.0

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds g2tmpl@1.13.0. No new variants or dependencies.

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Review by wdconinc — APPROVED** [review]
Checksum verified.

**Comment by tldahlgren** [comment]
Interesting.  One of the stacks failed with `Out of disk space` error.  Have notified ppl and hope it is fixed soon.

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Pull request merged**
