### PR TITLE
Add hdf5 versions 1.14.0, develop-1.14 and update develop version from develop-1.13 to develop-1.15

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Review by kwryankrattiger — DISMISSED** [review]

**Comment by lrknox** [comment]
Conflict added for MPICH@4.0:4.03.  When recent versions of HDF5 are built with mpich in this version range that was built with ch4:ofi the testphdf5 test will fail.  Previous mpich versions are not affected and the bug has been fixed in MPICH 4.1.

@kwryankrattiger, please review new change

**Review by byrnHDF — DISMISSED** [review]

**Review by kwryankrattiger — DISMISSED** [review]
LGTM

**Comment by kwryankrattiger** [comment]
[hdf5_1_14_config_find_mpi.patch.txt](https://github.com/spack/spack/files/10439004/hdf5_1_14_config_find_mpi.patch.txt)

https://github.com/HDFGroup/hdf5/pull/2400

**Review by hyoklee — DISMISSED** [review]

**Review by byrnHDF — DISMISSED** [review]

**Review by kwryankrattiger — DISMISSED** [review]

**Review by byrnHDF — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
I need to merge another fix that lets paraview work woth 1.14...I thought that was done already :/

**Comment by kwryankrattiger** [comment]
@lrknox The fixes for ParaView and VTK for 1.14 have been merged. A rebase should be enough to get this to pass now.

**Review by hyoklee — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
I am hoping the CI failed because of the Gitlab maintenance...but I will restart the pipelines once that is done to see what happened.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
Failures in CI are now all unrelated to the HDF5 version dump...
* Cannot pull image
* Race condition when installing deps
* Cannot find packages in mirror

Likely we can just keep telling spackbot to run pipelines until the all pass.

For the paraviews that did build with HDF5 1.14 the patch is now correctly applied. It isn't in the PR, but a followup should be made to make HDF5 a dep of ParaView always.

@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by lrknox** [comment]
@spackbot run pipeline
previous pipeline run failed 3 test configurations:
    ml-linux-x86_64-cpu-pr-build
    ml-linux-x86_64-cuda-pr-build
    ml-linux-x86_64-rocm-pr-build
One other configuration failed the previous time, trying again.

**Comment by kwryankrattiger** [comment]
Looks like newer versions of HDF5 changed the location of the fd version in the `H5FD_class_t` structure which leads to incorrect mappings in h5py. Updated version constraint to address this issue.

**Comment by kwryankrattiger** [comment]
ml-* Tensorflow errors seem unrelated now, couldn't reproduce locally.

other issues seem to be related to corrupted downloads as well, not able to reproduce a couple of them locally so rerunning pipeline manually.

@spackbot run pipeline

**Review by kwryankrattiger — APPROVED** [review]

**Comment by balay** [comment]
I'm seeing many build failures due to this PR across OSes, compilers...

- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3716526789
- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3716526793
- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3716526802


https://xsdk-project.gitlab.io/-/spack-xsdk/-/jobs/3716526789/artifacts/spack-stage/balay/spack-stage-hdf5-1.14.0-fezxjhdu46jpzcyaedjz5ekljye6pt7r/spack-build-02-build-out.txt

**Comment by kwryankrattiger** [comment]
I looked at the log and it doesn't seem to have any meaningful information on the error you are seeing. Were you able to reproduce this outside of CI and get to what the actual error is?

**Comment by hyoklee** [comment]
@byrnHDF and @brtnfld, is Fortran broken for hdf5 1.14.0 + openmpi 4.1.4? Is it part of CI testing? 

```
make[2]: *** No rule to make target `/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/openmpi-4.1.4-766fvr7pas2jkwcqhroktpnbyf43kile/lib/libmpi.so>', needed by `bin/libhdf5_fortran.so.310.0.0'.  Stop.
make[2]: *** Waiting for unfinished jobs....
...
make[2]: Leaving directory `/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-hdf5-1.14.0-fezxjhdu46jpzcyaedjz5ekljye6pt7r/spack-build-fezxjhd'
make[1]: *** [fortran/src/CMakeFiles/hdf5_fortran-shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by kwryankrattiger** [comment]
I would be willing to bet that is related to the public MPI change, but likely it is missing from the Fortran part. That is by bad for missing the Fortran targets. I thought that was part of my testing, but I guess I missed some.

**Comment by balay** [comment]
> I looked at the log and it doesn't seem to have any meaningful information on the error you are seeing

The primary error:

```
make[2]: *** No rule to make target `/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/openmpi-4.1.4-766fvr7pas2jkwcqhroktpnbyf43kile/lib/libmpi.so>', needed by `bin/libhdf5_fortran.so.310.0.0'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

> Were you able to reproduce this outside of CI and get to what the actual error is?

yes, reproducible with:

```
./bin/spack install hdf5+mpi+fortran+hl
```

[spack-build-out.txt](https://github.com/spack/spack/files/10668642/spack-build-out.txt)

**Comment by balay** [comment]
BTW: Same error with:
```
./bin/spack install hdf5+mpi+fortran+hl ^mpich
```
[spack-build-out.txt](https://github.com/spack/spack/files/10668772/spack-build-out.txt)

**Comment by lrknox** [comment]
> BTW: Same error with:
> 
> ```
> ./bin/spack install hdf5+mpi+fortran+hl ^mpich
> ```
> 
> [spack-build-out.txt](https://github.com/spack/spack/files/10668772/spack-build-out.txt)

I see this error in spack-build-out.txt:  make[2]: *** No rule to make target `/data/balay/spack.y/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/mpich-4.1-jukox2b26zj4kwapucq464mpjallhkbp/lib/libmpi.so>', needed by `bin/libhdf5_fortran.so.310.0.0'.  Stop.

I tried this command with spack@develop on a local machine:  " spack install hdf5@1.14.0 ^mpich@4.1".  It succeeded for me.  I'm curious as to the contents of /data/balay/spack.y/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/mpich-4.1-jukox2b26zj4kwapucq464mpjallhkbp/lib.  I have libmpi.so in my mpich-4.1 directory.

I'm curious about the contents of your /data/balay/spack.y/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/mpich-4.1-jukox2b26zj4kwapucq464mpjallhkbp/lib?

**Comment by balay** [comment]
Ok - so this build was using a pre-installed cmake@3.22.2. To reproduce - try:
```
./bin/spack install hdf5+mpi+fortran+hl  ^cmake@3.22.2
```
 Did the cmake requirement (intentionally) change with this release of hdf5?

**Comment by lrknox** [comment]
The required cmake version for HDF5 1.14.0 was intentionally changed from 3.12 to 3.18.  We have tests on local machines that are using CMake 3.21.7, 3.22.1 and 3.22.3.  Those versions in spack on the same centos7 machine that uses 3.22.3 fail with the same error that you report - libmpi.so is not found for hdf5 fortran lib.  I've run a number of tests with and without spack, and it appears that the failing combination for hdf5 1.14.0, hdf5 develop-1.15 and hdf5-develop-1.12 is spack+mpi+fortran+cmake.  This combination fails with CMake 3.18, 3.25.2 and the 3.22 versions.  CMake builds not using spack don't fail, nor do spack~mpi+fortran+cmake builds with either 3.18.0 or 3.25.2.  hdf5 1.12.2, 1.10.9 and develop-1.10 are also ok.  We'll continue to investigate, probably looking for a solution to be added to the spack hdf5 package and to code for future releases as needed.

**Comment by hyoklee** [comment]
@balay, thank you for testing it thoroughly.
Yes, I could reproduce the error using GitHub Actions:

https://github.com/hyoklee/actions/actions

**Pull request merged**
