### PR TITLE
Better spack spec

### LINKED ISSUE #2224: Hash codes on `spack spec`
I'm getting unusual rebuilding... some packages seem to want to install a new version every time I do a `spack install`, for no apparent reason.

In order to debug this, I would like a command flag on `spack spec` that display the hash code of each node in the DAG.  Then I can (for example) do a bunch of `spack spec` calls and see if/when the hashcode changes for certain dependencies.

### LINKED ISSUE #2229: Inconsistent Specs for the Same Package
@tgamblin @alalazo @adamjstewart 

I've had some problems with the same package being installed twice under different hashcodes, even though NOTHING relevant changed.  Certain packages seem to be "hot spots" for this behavior; for example, `py-numpy` in my case.  See:

```
$ ls -ltd py-numpy-*
drwxr-xr-x. 5 rpfische rpfische 4096 Nov  2 20:48 py-numpy-1.11.1-4x5i7jdcohqmmygrihehgstdrwhrh5xy
drwxr-xr-x. 5 rpfische rpfische 4096 Oct 12 14:59 py-numpy-1.11.1-gvcr5ncrxern5m7g67q5r5d3p3odbkq5
drwxr-xr-x. 5 rpfische rpfische 4096 Oct  6 13:31 py-numpy-1.11.1-5fjabod6muxily63zp3qjdczj6v3yowg
```
The last change to my Spack was Oct 6, so why does it keep re-installing?  Let's look at the `.spack/spec.yaml` for each of them:

[spec-4x5i7jdcohqmmygrihehgstdrwhrh5xy.yaml.txt](https://github.com/LLNL/spack/files/568735/spec-4x5i7jdcohqmmygrihehgstdrwhrh5xy.yaml.txt)
[spec-gvcr5ncrxern5m7g67q5r5d3p3odbkq5.yaml.txt](https://github.com/LLNL/spack/files/568734/spec-gvcr5ncrxern5m7g67q5r5d3p3odbkq5.yaml.txt)
[spec-5fjabod6muxily63zp3qjdczj6v3yowg.yaml.txt](https://github.com/LLNL/spack/files/568736/spec-5fjabod6muxily63zp3qjdczj6v3yowg.yaml.txt)

Let's compare the most recent two (again, no relevant changes to my Spack in that time).  First of all, a quick look at `spec-gvc...` looks wrong, what is this `&id001` stuff?
```
spec:
- py-numpy:
    version: 1.11.1
    compiler:
      name: gcc
      version: 4.9.3
    namespace: builtin
    parameters:
      blas: true
      lapack: true
      cflags: &id001 []
      cppflags: &id002 []
      cxxflags: &id003 []
      fflags: &id004 []
      ldflags: &id005 []
      ldlibs: &id006 []
```

Second... the dependencies listed in these files are different, even though `py-numpy/packages.yaml` never changed!  For example, `spec-gv..` has `py-nose`, but `spec-5f..` does not.

In my work, from time to time I install the same package from different top-level `spack install` commands.  For example, both `spack setup icebin` and `spack install env-modele` ( https://github.com/citibeth/spack/blob/efischer/develop/var/spack/repos/builtin/packages/env-modele/package.py ) will result in `py-numpy` being installed.  But Spack is apparently installing them under different hash codes (this would be easier to prove directly with #2224).

My best guess about what's going on here... when I say `spack spec`, I get a tree in which every package is listed *exactly once*.  We all know that dependencies form a DAG, not a tree --- where a single dependency can appear along multiple paths from the root.  Spack converts the DAG to tree in an arbitrary way.  The result is that the set of dependencies for the same package will look different in the tree, depending on whether some of its dependencies were "stolen" by other packages elsewhere in the same tree.  Thus, the apparent dependencies of a package will differ depending on the top-level package in the DAG.

It had been my implicit assumption that Spack operated on a DAG, and was just showing it as a tree as a matter of practical convenience for the user when displying `spack spec`.  But... it appears that this tree, no the full DAG, is *actually* what's used in `spec.yaml` and in computing hashes.  That is *clearly* buggy behavior, and would explain a lot of the "mysterious" re-installs we've been experiencing.

This bug should be fixed; relying on already-installed packages, as oft-talked about, will likely not fix this bug.  If we have #2224, then I believe I could prepare a pair of `spack spec` statements that produce a different hash for the same package, thus nailing down an easy test case.  But even without #2224, I'm fairly confident I've figured out the root cause of this mysterious behavior.

[For the record... I do all my install commands with "clean" command lines, i.e. no `^xxx` stuff.  See enclosed `packages.yaml` that controls the versions and variants of things that get installed: 
[packages.yaml.txt](https://github.com/LLNL/spack/files/568753/packages.yaml.txt) ]

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #2229.  Resolves #2224.

**Bugfix**
- [x] Gets rid of YAML aliases in `spec.yaml`

@citibeth @alalazo @adamjstewart can you verify?

`spack spec`:
- [x] `-I` option to show whether packages are installed, missing, or not yet installed.
- [x] `--cover` option to control tree traversal depth
- [x] `-l` and `-L` options to show short and long hashes like `spack find`
- [x] `--yaml` option to just print out the concrete `spec.yaml`

Here's the new `spack spec` output:
```console
$ spack spec -h
usage: spack spec [-h] [-l] [-L] [-y] [-c {nodes,edges,paths}] [-I] ...

positional arguments:
  specs                 specs of packages

optional arguments:
  -h, --help            show this help message and exit
  -l, --long            Show dependency hashes as well as versions.
  -L, --very-long       Show full dependency hashes as well as versions.
  -y, --yaml            Print concrete spec as YAML.
  -c {nodes,edges,paths}, --cover {nodes,edges,paths}
                        How extensively to traverse the DAG. (default: nodes).
  -I, --install-status  Show if deps are installed [+] or missing [-] from DB.
```

```console
$ spack spec -Il nettle
Input spec
--------------------------------
     tvbiazl  nettle

Normalized
--------------------------------
     h3wm75e  nettle
     pvwnyri      ^gmp
     zwmnoet          ^m4

Concretized
--------------------------------
     kdctsd6  nettle@3.2%gcc@5.3.0 arch=darwin-elcapitan-x86_64
[+]  hqdjcbh      ^gmp@6.1.1%gcc@5.3.0 arch=darwin-elcapitan-x86_64
[+]  ygxpr52          ^m4@1.4.17%gcc@5.3.0+sigsegv arch=darwin-elcapitan-x86_64
[+]  rapr3qu              ^libsigsegv@2.10%gcc@5.3.0 arch=darwin-elcapitan-x86_64
```

### CODE REVIEW

**Comment by alalazo** [comment]
LGTM apart two minor issues. First one:
```console
$ spack spec -Il hdf5+mpi+szip%gcc@4.8
Input spec
--------------------------------
     xtczpp5  hdf5%gcc@4.8+mpi+szip

Normalized
--------------------------------
     dkjld44  hdf5%gcc@4.8+mpi+szip
     2xnea7r      ^mpi
     4445jvm      ^szip
     j52z7qb      ^zlib@1.1.2:

Concretized
--------------------------------
     fby56m6  hdf5@1.10.0-patch1%gcc@4.8+cxx~debug+fortran+mpi+shared+szip~threadsafe arch=linux-Ubuntu14-x86_64
     dhkbno5      ^openmpi@2.0.1%gcc@4.8~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-Ubuntu14-x86_64
     uofzaak          ^hwloc@1.11.4%gcc@4.8 arch=linux-Ubuntu14-x86_64
     agw4feb              ^libpciaccess@0.13.4%gcc@4.8 arch=linux-Ubuntu14-x86_64
     v7gy3pk                  ^libtool@2.4.6%gcc@4.8 arch=linux-Ubuntu14-x86_64
[+]  iggewke                      ^m4@1.4.17%gcc@4.8+sigsegv arch=linux-Ubuntu14-x86_64
[+]  avb6azw                          ^libsigsegv@2.10%gcc@4.8 arch=linux-Ubuntu14-x86_64
     4klsvhu                  ^pkg-config@0.29.1%gcc@4.8+internal_glib arch=linux-Ubuntu14-x86_64
     vyz5zbm                  ^util-macros@1.19.0%gcc@4.8 arch=linux-Ubuntu14-x86_64
     4pzj45c      ^szip@2.1%gcc@4.8 arch=linux-Ubuntu14-x86_64
[+]  bds4ies      ^zlib@1.2.8%gcc@4.8 arch=linux-Ubuntu14-x86_64
```
does not agree with the `help` that says:
```console
  -I, --install-status  Show if deps are installed [+] or missing [-] from DB
```
in that it shows no `[-]` symbols. I would be for changing the help rather than the implementation, as I find the output clearer like it is right now. 

The other minor thing is that the command permits to have `-y` together with other arguments:
```console
$ spack spec -yl hdf5+mpi+szip%gcc@4.8
spec:
- hdf5:
    version: 1.10.0-patch1
    compiler:
      name: gcc
      version: '4.8'
    namespace: builtin
    parameters:
      cxx: true
      debug: false
      fortran: true
      mpi: true
      shared: true
      szip: true
      threadsafe: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    arch:
...
```

**Comment by tgamblin** [comment]
@alalazo: maybe the help needs to be cleaner.  "Missing" is different from "not installed".  Missing means something is in the DB bc it is still needed by another package, but it has no install directory.  You can get that if you rm -rf an install dir then reindex.

**Comment by alalazo** [comment]
@tgamblin Ok, then it definitly LGTM :+1:

**Comment by citibeth** [comment]
You mean all that torture I endured was fixed by a two-line commit?  I've
cherry-picked that into my `efischer/develop` branch.  Cherry-picking the
new feature would be a bit trickier (I'm behind), I'll see if I can wait on
that until my next big Spack update.

I'll see how the fix works for me, big thanks!

**Comment by tgamblin** [comment]
Updated to fix flake errors in the test and to clarify `spack spec` documentation.  I'll merge once Travis says it's ok

**Comment by tgamblin** [comment]
@citibeth: Well, I'm still a little nervous about the deptypes on your branch in #2229.  This fixes at least one of your problems, and I don't know if you have more than one 😄.  So let me know if this fixes it now that you can get a little more insight into the specs.

**Comment by tgamblin** [comment]
Also note to everyone that this will change hashes (in that it keeps them from changing as much 😄)

**Comment by adamjstewart** [comment]
@tgamblin Would you be willing to increment the version count since this PR changes the hashes (or wait until 0.10 is ready before merging)? I'm trying to keep a separate Spack installation for each spec change/version. I'm hoping that someday this won't be necessary anymore and a changing hash doesn't mean I need to throw everything away and start over.

**Comment by tgamblin** [comment]
@adamjstewart: I don't mind changing the version.  What I would rather not do is keep changing it in `develop` -- if I change the `0.10` here and there are other changes later, before the `0.10` release, can we keep the version in `develop` at `0.10`?

**Comment by citibeth** [comment]
Can I advocate again for checksumming the `spec` DAG directly, rather than
checksumming the YAML output?  I have a lot of experience with checksumming
big Python data structures, and am confident it would work well.
Advantages of this would be:

1. More control over checksums, and how/when they are changed.  For
example, the Package author could now have control over what changes to the
Package change its checksum, and what changes do not.

2. Re-Use: once a `spec` object is checksummed once, that checksum can be
store for later use.

3. Efficiency: If I checksum the top-level node of a DAG, I will get not
just a checksum for that node, but also a checksum for *every node in the
DAG*.

I'm deeply familiar with the algorithms in place now... but (2) and (3)
might enable significant speedup of concretization.

If people are not against direct checksumming of the specs, I could work up
a PR that does it.

**Comment by adamjstewart** [comment]
> if I change the `0.10` here and there are other changes later, before the `0.10` release, can we keep the version in `develop` at `0.10`?

That depends on whether or not they are changes to the spec 😆 

On second thought, don't worry about it, I can just re-install Spack in a `spack-0.10` dir for now. It will be the correct version soon enough.

In all seriousness though, we need to start thinking about solving some of the issues I brought up in #1325. For example, once the hash changes, it is no longer possible to say "build with this thing I already have installed". I'm not just talking about things from the old spec; I mean new things installed on the same spec. This makes `spack activate` and `spack deactivate` useless, because when I try to activate a package, it asks me to be more specific. Of course, there are literally no differences between the two specs, aside from the hash, so being more specific isn't possible. And specifying activation by hash doesn't work.

We don't use modules yet, but we plan on making the switch. What happens when I have two packages installed with the same spec? They'll generate two very similar module files with only a hash as the difference. Should I expect hundreds of emails from users asking me if `mvapich2-2.2-dfsajga` is better or worse than `mvapich2-2.2-sfsdafas` and which they should use?

In an ideal world, I would like Spack to use things that are already installed, unless I am explicitly installing them, in which case they should update to the latest version. @citibeth has concerns about reproducibility, so this should be configurable. But even without the "already installed vs. rebuild" debate, when a hash changes and the installed package is identical, Spack should still use it (to avoid the activate/deactivate bug I mentioned). Harcoding the hash into the installation directory makes this a bit more challenging, as `spack reindex` can't update installed packages with the new spec. But if you can think of another way to solve the problem, that works too.

**Comment by tgamblin** [comment]
@citibeth:

1. I don't want the package author to control when checksums change (what does the checksum even tell me if every package determines how it checksums?).  Also, I am *planning* on adding checksumming *of the package.py file itself* to Spack, but am holding off so that @adamjstewart does not murder me due to #1325-related concerns.  We need concretization-based-on-installed things before that will work well.
1. We already do this with the current DAG hash.  Hashes are cached for concrete specs.
1. See (2).

To add to (1), hashing the YAML is done so that the hash is reproducible after the fact.  You can take a `spec.yaml`, strip the hash fields from it, hash it, and reproduce the DAG hash.  Not so for in-memory hashes -- they change with the spack version.  That said, you may not realize there are *two* DAG hashes for specs.  One *is* done in memory (see `hash` in `spec.py`) and is way faster.  It's used for looking up specs.  The DAG hash is also used at runtime, but it is typically only computed once at package install time.  When we read already-installed specs from disk, they retain their *original* hash even if Spack's hashing scheme has changed.  This allows you to refer to specific builds by hash.

**Comment by tgamblin** [comment]
@adamjstewart: I have like half a page written on #1325 that I never finished.  Sorry I didn't clarify this stuff earlier.

> For example, once the hash changes, it is no longer possible to say "build with this thing I already have installed". I'm not just talking about things from the old spec; I mean new things installed on the same spec.

False (*ish).  These are two different problems.  See my response to @citibeth above.  When you install something in Spack, the hash it gets at *install time* is its hash forever.  When Spack reads specs back in, they have the same hash (we cache it on the spec).  So you *can* refer to them by hash, and Spack doesn't assume that the spec's hash is what would be generated by the current implementation of `dag_hash()`.  If we didn't do this, the output of Spack find would change over time and install directory names would become wrong whenever `dag_hash()` changed.

*Clarification: there is an annoying bug that I am fixing right now that *fails to actually compare specs by hash* when you refer to them by hash on the command line.  This is why Spack complains about ambiguity.  I think this is causing confusion about specs. Sorry!  It'll be in 0.10 (MUST WORK FASTER 🏃 💨 )

> We don't use modules yet, but we plan on making the switch. What happens when I have two packages installed with the same spec?

Take a look at what @scheibelp is doing in #2168 -- this is what we're trying to do with NERSC to solve this.

> But even without the "already installed vs. rebuild" debate, when a hash changes and the installed package is identical, Spack should still use it (to avoid the activate/deactivate bug I mentioned). Harcoding the hash into the installation directory makes this a bit more challenging, as spack reindex can't update installed packages with the new spec. But if you can think of another way to solve the problem, that works too.

Yes.  We have `Spec.satisfies()` for this.  It's actually the reason you see the issue with spec ambiguity when you do refer to a spec by hash.

The hash reference `/abc123` causes Spack to look up the old spec from the DB.  It reads the `spec` it in, builds the DAG structure, *and* memo-izes the hash.  When spack look to see what Spec you mean, it asks whether any other Spec in the DB `satisifes(<spec read in by hash>)`.  That can actually be true for multiple specs if the hash algorithm has changed -- which is what you want.  In this case, it should be comparing by hash, but it *isn't*, which is why you get the bug.

So we *can* see if an old spec matches a new one in all ways but by hash.  We just need to integrate it into the concretization algorithm, so Spack will look first at what is installed, then concretize based on it.  And we can maintain the current behavior as an option.  Interesting side note: the same issue comes up in the Javascript universe with [npm (nondeterministic) vs yarn (deterministic)](https://code.facebook.com/posts/1840075619545360).  Spack is a little more involved (it's more than just package/version) but it's effectively the same issue.  I see advantages to both.

**Comment by tgamblin** [comment]
Ok given @adamjstewart's response, merging this.

**Comment by tgamblin** [comment]
@citibeth: please let me know whether this fixes your problem

**Comment by tgamblin** [comment]
@citibeth: one other point that I probably didn't make clear here: the `dag_hash()` is calculated not on the whole `spec.yaml` but on the root node's `node_dict()`, which includes dependency hashes but not the dependencies' full YAML specification.  So it this *is* really a merkle DAG hash (which is what I assume you are describing).

**Comment by citibeth** [comment]
Thanks for explaning!

**Comment by citibeth** [comment]
> @citibeth: please let me know whether this fixes your problem

The reality is, it's going to be more rebuilding, which I can only do so often (especially since I basically have built what I need right now).  Once Spack 0.10 is released, I will try it out.  If past upgrades are a guide, it will take me a day chasing down newly introduced bugs/issues.

**Comment by citibeth** [comment]
OK, I'm trying the latest Spack now.  Things are working really smoothly; and there are only a very few differences now between the Spack I'm using and the `develop` branch.  So far it's built about 30 packages with no need for intervention.

**Comment by citibeth** [comment]
This is really working well for me.  The hash printouts on `spack spec` allow me to check that the hashes remain the same, whether I install something directly or as a dependency of something else --- BEFORE I install.  So far, I have found no discrepancies.

**Pull request merged**
