### PR TITLE
acts: add v35.1.0, v35.2.0

### PR DESCRIPTION
**Pull request by wdconinc**
This PR adds `acts` versions 35.1.0 and 35.2.0.

*Edit:* The three new plugins are not active yet in the v35 series, only added in the CMakeLists.txt, but will need to be added when the plugins do something (in v36?). The necessary dependencies are added in:
- `acts-dfelibs`: https://github.com/spack/spack/pull/44860
- `acts-algebra-plugins`: https://github.com/spack/spack/pull/44861

### CODE REVIEW

**Comment by wdconinc** [comment]
Interesting new issue: `acts` can now depend on `traccc`, and `traccc` depends on `acts` (PluginJson in io/). Does anyone know how deep the dependency is?

(tagging @stephenswat too)

**Comment by wdconinc** [comment]
There does not seem to be any actual functionality enabled by the covfie, detray, traccc options, and they appear provided for [forward planning only](https://github.com/acts-project/acts/commit/210b8979078704af25154b594071826f3dbb2a59). There are missing definitions of `_acts_traccc_version` (and similar) at e.g. https://github.com/acts-project/acts/blob/3eb039a744c052260f2587fdb136d5c496370230/CMakeLists.txt#L327, so enabling `traccc` (and similar) functionality will fail anyway at this point.

@spackbot fix style

**Comment by stephenswat** [comment]
Hi @wdconinc, the long-term planning is for the traccc project to be completely merged into Acts, so at that point it will suffice for us to have a `+gpu` option (or something similar) for the Acts. Until that merge happens, we are indeed stuck in this dependency loop which we expect to be broken only by Acts importing traccc in its CMake configuration. I agree that this is an undesirable setup, so I suggest that we ignore it in the Spack spec (i.e. not add any options to compile traccc) yet, and we wait for the integration to be complete.

**Comment by stephenswat** [comment]
Please note #44860 and #44861.

**Comment by wdconinc** [comment]
> Please note #44860 and #44861.

Ha, I overlooked those. I will review them.

**Comment by stephenswat** [comment]
> Ha, I overlooked those. I will review them.

It does look like your specs are a bit more elaborate in some cases; perhaps we should use yours instead!

**Comment by wdconinc** [comment]
> It does look like your specs are a bit more elaborate in some cases; perhaps we should use yours instead!

Since you were first and therefore deserve the credit (and, to a lesser degree, since it is a separate PR, which is preferable for new packages), it makes more sense to go with your PR.

At this point, if we aren't quite adding these packages as dependencies of acts v35, adding the new dependency packages also doesn't really fit inside this PR anymore.

**Comment by wdconinc** [comment]
This PR is now ready for review. It doesn't add the new packages, and only adds v35.1.0 and v35.2.0.

`fastor` has since been added to `develop` in a separate PR; `acts-dfelibs` is added through #44860; and `acts-algebra-plugins` is added through #44861.

**Review by tldahlgren — APPROVED** [review]
Confirmed the two new version commits.

**Comment by tldahlgren** [comment]
Ping me when the PR is ready to merge.  Also if @HadrienG2 wants to commit and or thinks it's ready.

**Comment by wdconinc** [comment]
In light of @HadrienG2 (sorry, one last notification) message in #45071, after many years of dedication to these packages, I think we can go ahead and merge.

**Pull request merged**
