### PR TITLE
[pkg: damaris] added new versions in damaris package and fixed dependency

### PR DESCRIPTION
**Pull request by mdorier**
This RP adds 2 new versions to the Damaris package and also adds the missing `+system` variant in the boost dependency.

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
Can you fix the conflicts if still required?

**Comment by mdorier** [comment]
Seems like @jcbowden has taken over maintaining this package. My was adding the `master` version and the `+multithreaded~singlethreaded` variants in boost, but I'm not sure these variants are actually necessary.
I'll let @jcbowden judge and edit the PR if needed (or simply close it).

**Comment by jcbowden** [comment]
@mdorier It would be good to have you as a maintainer also. I did not get around to asking you when spackbot suggested someone should be set when I updated the package.py file recently. 

I'm not sure of the exact reasons for needing boost multithreading support. Perhaps if the Damaris servers start using pluggins that use multiple threads. This potentially will be more and more likely these days I guess.

As I snuck in and updated the package.py recently, could you use the updated version (in spack develop branch)? You can add back master as an install option if you like. I removed it as I was not updating master, it (master) was just was another version of the most recent tagged release.

Thanks,

**Comment by mdorier** [comment]
Ok then let's just close this PR without merging it.

**Pull request closed without merging**
