### PR TITLE
Added py-typeguard package.

### PR DESCRIPTION
**Pull request by hategan**

### CODE REVIEW

**Comment by hategan** [comment]
Dependencies added. Should be good to go now.

**Comment by bernhardkaindl** [comment]
Hi @hategan, looks good, just two major points which I hope also work for you:

For py-sphinx-autodoc-typehints:
```diff
-    version('1.9.0', sha256='0dfd26be5b81049ce81b644913a06a12795ded2791adc0a4e13420eb9a832852')
+    version('1.12.0', sha256='193617d9dbe0847281b1399d369e74e34cd959c82e02c7efde077fca908a9f52')
```
Without it, `spack install --test=root py-sphinx-autodoc-typehints` did fail for me with sphinx.util.inspect.Signature missing in the import test,. it's deprecated and was possibly removed in the version my build picked:
https://github.com/agronholm/sphinx-autodoc-typehints/issues/133

```diff
-    depends_on('py-dataclasses', type=('test', 'run'))
+    depends_on('py-dataclasses',   type=('test', 'run'), when='^python@:3.6')
```
py-dataclasses contrains itself to python@3.6 as 3.7: has it already.
Depending on it unconditionally would make all users of it (py-typeguard) limited to 3.6 as well, and if 3.6 wasn't built in spack already it would by built especially for it.
    
Making py-dataclasses only a dependeny when ^python@3.6 is used, allows the two pacakges to be built whith 3.6 and with never python. (tested with 3.6 and 3.8)

This works for me, you can test if it works for you too, thanks!

**Review by bernhardkaindl — APPROVED** [review]
Builds for me with `install -v --test=root py-sphinx-autodoc-typehints py-typeguard`

Unfortunately the import tests run by `--test=` do not fail the build, so you have to also use `-v`, and check the output of the import tests of both packages.

**Comment by hategan** [comment]
> Unfortunately the import tests run by `--test=` do not fail the build, so you have to also use `-v`

Thanks. I din't know that. I would maybe like to note that this does appear to stray from "least astonishment". I will keep it in mind in the future.

Also thanks for the `when=` bit. Didn't quite know the right incantation there.

> This works for me, you can test if it works for you too, thanks!

Yes, `--test=root -v` works for me, too, for both typeguard and sphinx-autodoc-typehints. Thanks again for all the help.

**Pull request merged**
