### PR TITLE
geant4: sha256sum has changed

### PR DESCRIPTION
**Pull request by joequant**
getting checksum errors with download

### CODE REVIEW

**Comment by sethrj** [comment]
@joequant this can indicate a malicious actor providing a bad version of Geant4, or it could indicate that the upstream developers have changed the code but without tagging a new version. It *also* can be a result of different repository systems packaging the same code differently.

In any case, changing the shasum can break the builds for users who've already installed it. @drbenmorgan @wdconinc can you please verify which shasum is correct and why the incorrect one is in the package recipe?

**Comment by wdconinc** [comment]
This seems to be an upstream change. Release was first published on December 10 (see geant4 download page), but the current tarball linked there (with the new hash) was created on December 12.

**Comment by wdconinc** [comment]
Looking at the github mirror at https://github.com/Geant4/geant4/commits/master, there are two "Import Geant4 11.0.0 source tree" commits, one on December 10, and one on December 12. The later change set https://github.com/Geant4/geant4/commit/84f33a068c5e0acb278dc4e4acb6a2822c6e7bca appears to consist only of g4py test suite and README changes.

**Comment by wdconinc** [comment]
Confirmed this in email with geant4 release manager Gabriele Cosmo, cc'ed to @drbenmorgan. The new hash is the one to use going forward.

**Comment by sethrj** [comment]
Thanks for looking into that.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
