### PR TITLE
kokkos: add v3.2.00

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@jjwilke

**Comment by junghans** [comment]
Should it get installed at all?

**Comment by jjwilke** [comment]
What should get installed?

**Comment by junghans** [comment]
sorry, `libprinter-tool.so`, but that is now https://github.com/kokkos/kokkos/pull/3308.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
