### PR TITLE
Add new versions of tinyxml2

### PR DESCRIPTION
**Pull request by alephpiece**
Added 7.0.0 to 10.0.0

### CODE REVIEW

**Comment by alephpiece** [comment]
@spackbot fix style

**Review by tldahlgren — DISMISSED** [review]
Confirmed the new version sha256s.

**Comment by tldahlgren** [comment]
@tgamblin @boomanaiden154 As recent contributors to this package, do either of you want to confirm that no other changes are needed for these four new versions?

**Comment by alephpiece** [comment]
Much thanks!

**Comment by boomanaiden154** [comment]
Haven't really contributed to this package in the past (other than the mass license annotations), but I can confirm that the following specs build on my system:
```
tinyxml2@10.0.0%clang@18.0.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen2
tinyxml2@9.0.0%clang@18.0.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen2
tinyxml2@8.0.0%clang@18.0.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen2
tinyxml2@7.0.0%clang@18.0.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen2
```

I haven't confirmed any functionality or that the downstream packages (seems like there's only one) still build and don't lose any functionality, but adding the additional versions seems reasonable enough to me.

**Comment by alephpiece** [comment]
Added the variant `shared` because tinyxml2 won't build a shared library by default.

**Comment by tldahlgren** [comment]
One stack timed out so let's re-run CI.

@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
