### PR TITLE
libuv: use generated configure script if available

### PR DESCRIPTION
**Pull request by haampie**
The (giant) julia patch includes a configure script

### CODE REVIEW

**Comment by nkgh77** [comment]
Sorry if I am doing something stupid, but this is the result.

==> Installing libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez
==> No binary for libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez found: installing from source
==> Using cached archive: /dvlscratch/SHI/KUSHIDA/SPACK/spack/var/spack/cache/_source-cache/archive/37/371e5419708f6aaeb8656671f89400b92a9bba6443369af1bb70bcd6e4b3c764.tar.gz
==> Using cached archive: /dvlscratch/SHI/KUSHIDA/SPACK/spack/var/spack/cache/_source-cache/archive/35/35e5613ae0e56bffcad9d0c59f74389c19385fde18fe3b923fa31d66a9519128
==> Applied patch https://raw.githubusercontent.com/spack/patches/b106c034796ff5fc8e07e15722e5a369f68d4bc9/julia/libuv-1.42.0-1.patch
==> libuv: Executing phase: 'autoreconf'
==> libuv: Executing phase: 'configure'
==> Error: ProcessError: /var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-src/configure: Permission denied
    Command: '/var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-src/configure' '--prefix=/dvlscratch/SHI/KUSHIDA/SPACK/spack/opt/spack/linux-rhel6-x86_64/gcc-11.2.0/libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez'
See build log for details:
  /var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-build-out.txt

**Comment by nkgh77** [comment]
Sorry if I am doing something stupid, but this is the result

==> Installing libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez
==> No binary for libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez found: installing from source
==> Using cached archive: /dvlscratch/SHI/KUSHIDA/SPACK/spack/var/spack/cache/_source-cache/archive/37/371e5419708f6aaeb8656671f89400b92a9bba6443369af1bb70bcd6e4b3c764.tar.gz
==> Using cached archive: /dvlscratch/SHI/KUSHIDA/SPACK/spack/var/spack/cache/_source-cache/archive/35/35e5613ae0e56bffcad9d0c59f74389c19385fde18fe3b923fa31d66a9519128
==> Applied patch https://raw.githubusercontent.com/spack/patches/b106c034796ff5fc8e07e15722e5a369f68d4bc9/julia/libuv-1.42.0-1.patch
==> libuv: Executing phase: 'autoreconf'
==> libuv: Executing phase: 'configure'
==> Error: ProcessError: /var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-src/configure: Permission denied
    Command: '/var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-src/configure' '--prefix=/dvlscratch/SHI/KUSHIDA/SPACK/spack/opt/spack/linux-rhel6-x86_64/gcc-11.2.0/libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez'
See build log for details:
  /var/tmp/kushida/spack-stage/spack-stage-libuv-1.42.0-ngmcav5pminj64cb77fckbhm6u672mez/spack-build-out.txt

**Comment by haampie** [comment]
Sigh :p i guess file modes are not in diffs?

**Comment by haampie** [comment]
Maybe it's better to just create a separate julia-libuv package which provides libuv@1.42.0...

**Comment by glennpj** [comment]
I was able to build julia and the patched libuv without issue.

**Comment by glennpj** [comment]
How will this work with the spack `--reuse` option? Will the julia patched libuv work with other packages that need libuv? If so, then perhaps the patch could always be applied to libuv. If not, then it probably needs to be distinguished somehow to not get picked up with `--reuse`.

**Comment by haampie** [comment]
Dropping this, #28755 is because of a buggy old `patch`.

**Pull request closed without merging**
