### PR TITLE
scorep: Add Score-P 7.0 release, and new `url`

### PR DESCRIPTION
**Pull request by ikitayama**

### CODE REVIEW

**Comment by ikitayama** [comment]
I'd like @adamjstewart to take a quick look on this PR, thanks!

**Comment by cessenat** [comment]
Hello @ikitayama ; in the meanwhile I made the same PR + I corrected many dependencies from previous releases which were too large. This is PR #23418. I believe only one of our 2 PRs should be merged to develop.

**Comment by ikitayama** [comment]
Your is the best

**Comment by ikitayama** [comment]
Olivier would you take care of the new URL locations mentioned by
Christian? Thanks!

**Comment by ikitayama** [comment]
@cessenat , would you add yourself to the maintainers list to the Score-P and other spack packages? Thanks!

> Hello @ikitayama ; in the meanwhile I made the same PR + I corrected many dependencies from previous releases which were too large. This is PR #23418. I believe only one of our 2 PRs should be merged to develop.

**Comment by cessenat** [comment]
> @cessenat , would you add yourself to the maintainers list to the Score-P and other spack packages? Thanks!
> 
> > Hello @ikitayama ; in the meanwhile I made the same PR + I corrected many dependencies from previous releases which were too large. This is PR #23418. I believe only one of our 2 PRs should be merged to develop.

Thank you @ikitayama.
There are two things:
- generic url brings only scorep-7.0, it may be masked by the spack mirrror on AWS ; so, I feel it is better to only set a url attribute to version 7.0, unless I misunderstood the spack policy about that ; what do you think ? I took care to use an https url BTW.
-  in fact there should be more knowledgeable people about scorep than me, so I'd better wait they take it in charge. If in the future I make some contributions, then why not. Thank you for proposing anyway.

**Comment by ikitayama** [comment]
Please go ahead on the URL attribute point and okay let’s find other folks
to stand up as the maintainers.

**Comment by eugeneswalker** [comment]
Closed in favor of https://github.com/spack/spack/pull/23418 . If I misread the conversation and you do in fact want to merge elements of this PR, in addition to #23418 please let me know and we can re-open this. Thanks!

**Pull request closed without merging**
