### PR TITLE
Fix Apptainer

### PR DESCRIPTION
**Pull request by charmoniumQ**

### CODE REVIEW

**Comment by charmoniumQ** [comment]
I was wondering if I could get a review from @tgamblin, @trws , or @matz-e  who have worked on this package.

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
@matz-e As the original contributor of the package, would you care to comment on these changes?

**Comment by tldahlgren** [comment]
> I was wondering if I could get a review from @tgamblin, @trws , or @matz-e who have worked on this package.

Didn't see this when I started my checks.

**Comment by matz-e** [comment]
Thanks for the ping and the update, looks good from my side!

**Pull request merged**
