### PR TITLE
[intel-*] remove deprecated packages

### PR DESCRIPTION
**Pull request by rscohn2**
Deprecated in v22 release, removing for v23 release.

Let me know if you think it will be a problem.

@stephenmsachs

### CODE REVIEW

**Comment by stephenmsachs** [comment]
Thanks for asking. We are using the `intel-*` as backup providers in our stacks. I believe when the packages are removed lines like `providers: mkl: [intel-oneapi-mkl, intel-mkl]` are no longer legal. This is not a blocker, but the stacks need to be updated. ~~This affects other (non-aws) stacks as well:~~

```
~/git/spack/share/spack/gitlab/cloud_pipelines$ grep -rEl -- 'intel-[A-Z,a-n,p-z]' .
./stacks/gpu-tests/spack.yaml
./stacks/aws-isc-aarch64/spack.yaml
./stacks/tutorial/spack.yaml
./stacks/e4s-neoverse-v2/spack.yaml
./stacks/e4s-power/spack.yaml
./stacks/aws-pcluster-x86_64_v4/packages.yaml
./stacks/e4s-neoverse_v1/spack.yaml
./stacks/e4s-oneapi/spack.yaml
./stacks/e4s-rocm-external/spack.yaml
./stacks/aws-isc/spack.yaml
./stacks/e4s-cray-sles/spack.yaml
./stacks/e4s/spack.yaml
./stacks/e4s-cray-rhel/spack.yaml
./configs/win64/packages.yaml
./configs/linux/ci.yaml
```

I just realized you are leaving the `intel-tbb` package untouched. So, this only affects the `aws-pcluster-x86_64_v4` stack.

**Comment by rscohn2** [comment]
Reducing the packages that are deleted to ipp and daal. mkl, parallel-studio, mpi, and intel packages have conditional `depends` and other references so deleting them needs a separate commit.

**Comment by rscohn2** [comment]
> I just realized you are leaving the `intel-tbb` package untouched. So, this only affects the `aws-pcluster-x86_64_v4` stack.

intel-tbb is for the open source package and includes oneapi versions so I will not delete that one. Thanks for updating the aws stack.

**Comment by rscohn2** [comment]
@haampie: Can you review this? It is ready to merge.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
