### PR TITLE
py-tensorflow: fix aarch64 build

### PR DESCRIPTION
**Pull request by aweits**

### CODE REVIEW

**Comment by aweits** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
Oof, this is ugly. Can we not use a normal patch directive like we did for other third_party libs?
```python
    patch(                                                                                          
        "https://github.com/google/breakpad/commit/605c51ed96ad44b34c457bbca320e74e194c317e.patch?full_index=1",
        sha256="694d83db3a2147d543357f22ba5c8d5683d0ed43e693d42bca8f24ec50080f98",                  
        when="+breakpad",                                                                           
        working_dir="third_party/breakpad",                                                         
    )     
```

**Comment by adamjstewart** [comment]
Also, need to add comment linking to upstream so we know when to remove the patch.

**Comment by aweits** [comment]
> Oof, this is ugly. Can we not use a normal patch directive like we did for other third_party libs?
> 
> ```python
>     patch(                                                                                          
>         "https://github.com/google/breakpad/commit/605c51ed96ad44b34c457bbca320e74e194c317e.patch?full_index=1",
>         sha256="694d83db3a2147d543357f22ba5c8d5683d0ed43e693d42bca8f24ec50080f98",                  
>         when="+breakpad",                                                                           
>         working_dir="third_party/breakpad",                                                         
>     )     
> ```

I don't like it either - but this starts the discussion of who wants to carry a change/patch to the vendored absl in TF

**Comment by adamjstewart** [comment]
We don't have to use a URL, we could just use a patch file. But I think we can use the directive instead of filter_file. But yeah, we definitely want to update upstream too. Has this been fixed in upstream absl?

**Comment by aweits** [comment]
> We don't have to use a URL, we could just use a patch file. But I think we can use the directive instead of filter_file. But yeah, we definitely want to update upstream too. Has this been fixed in upstream absl?

Has not been fixed upstream.

**Comment by adamjstewart** [comment]
Let's upstream to absl before upstreaming to TF. I would do it myself, but I don't have access to aarch64 to test, nor do I fully understand the bug or the fix.

**Comment by adamjstewart** [comment]
@aweits any updates? Would like to test this in #39666

**Comment by aweits** [comment]
> @aweits any updates? Would like to test this in #39666

I've done some more testing/etc (learned a few more things) and tried to abstract the issue into a example which is here: https://github.com/abseil/abseil-cpp/issues/1665

**Comment by adamjstewart** [comment]
We can still finish this PR while waiting on upstream.

**Comment by aweits** [comment]
> We can still finish this PR while waiting on upstream.

Sure thing! I pushed this - but still double-checking a few things on my end, will check the output from CI and the tests running on my side in the morning...

**Comment by adamjstewart** [comment]
Instead of writing a patch that creates and runs a patch file, why don't we just apply the patch directly? That's how the breakpad patch works. Or does `third_party/absl` not get downloaded until halfway through the build process?

**Comment by aweits** [comment]
>  Or does `third_party/absl` not get downloaded until halfway through the build process?

Yep.

**Comment by adamjstewart** [comment]
Ah, gotcha. So then this is probably as good as we can get for now. Let me know when you finish testing on your side. Also, can you double check that the patch correctly applies to all versions of PyTorch available in Spack or limit the patch if not? At least test the oldest version of bisect or something. We'll have proper CI set up later.

**Review by adamjstewart — DISMISSED** [review]
Seems legit to me. Let's see what upstream says. I can merge as soon as you finish your local tests, then I'll test it in CI.

**Review by adamjstewart — APPROVED** [review]

**Comment by nouiz** [comment]
I pushed this patch to abseil-cpp:
https://github.com/abseil/abseil-cpp/pull/1732

**Pull request merged**
