### PR TITLE
update ncurses- add v6.3, symlink libcurses -> libncurses

### PR DESCRIPTION
**Pull request by eugeneswalker**
* Update `ncurses` - add `v6.3` and create symlink `libcurses.so` -> `libncurses.so`

Repurposes this PR for ncurses update, merge this PR instead of https://github.com/spack/spack/pull/32037

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
Looks like pipeline is failing due to an LLVM build issue.  Unfortunately, the log is truncated.  (FWIW. I have some changes that should address the truncation issue that I need to move to a separate PR.)

**Comment by eugeneswalker** [comment]
LLVM dependency build is failing:
* [(specs) llvm/75ybli4 14.0.6 gcc@11.2.0 linux-ubuntu22.04-x86_64 New PR testing workflow](https://gitlab.spack.io/spack/spack/-/jobs/2959873)

Unfortunately, the job log is truncated so I cannot see the error. Will reproduce locally and report back.

**Comment by tldahlgren** [comment]
> LLVM dependency build is failing:
> 
> * [(specs) llvm/75ybli4 14.0.6 gcc@11.2.0 linux-ubuntu22.04-x86_64 New PR testing workflow](https://gitlab.spack.io/spack/spack/-/jobs/2959873)
> 
> Unfortunately, the job log is truncated so I cannot see the error. Will reproduce locally and report back.

There was a PR merged within the hour (#31998 ) that *might* help reduce the verbosity of the output to the point of allowing the failure to show up.

**Comment by eugeneswalker** [comment]
The LLVM issue here will be resolved by https://github.com/spack/spack/pull/32037, so I have cherry-picked that here. We'll want to let the other one merge before we merge this FYI.

**Review by alalazo — DISMISSED** [review]

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
