### PR TITLE
davix: Improve shared library building on macOS

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
Add -DCMAKE_MACOSX_RPATH=ON to cmake.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is this a general CMake option available to all builds? Maybe we could put it in the base class.

**Comment by ChristianTackeGSI** [comment]
Yes, this is a general variable.
Yes, it could be added to the main cmake class.

I think, this was proposed a while back already and rejected.
I _think_, the result was:
This option fixes one specific problem on macOS. And there are multiple problems and they even need specific fixes in specific cases.
I am definitely not an expert on macOS.

That said, I know
* For some versions of davix, this definitely fixes problems in our builds.
* CMake 3.0 defaults to this variable being ON
* Policy [CMP0042](https://cmake.org/cmake/help/latest/policy/CMP0042.html) has all the details on which versions of cmake do what.
* Packages missing to declare, that they're compatible with CMake 3.0, will get CMake 2.x behaviour.

**Comment by adamjstewart** [comment]
Ah, I see. It was proposed in #9249 but rejected. In that case, I think this PR is the right thing to do.

**Review by adamjstewart — APPROVED** [review]

**Comment by ChristianTackeGSI** [comment]
Thanks for digging up the correct reference! That was exactly the one I meant.

**Pull request merged**
