### PR TITLE
Add shared variant for fftw to allow static-only builds

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a shared variant for fftw to allow static-only builds. These changes support NOAA/National Weather Service R&D and operational forecasting applications.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot run pipeline

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot run pipeline

**Review by alalazo — COMMENTED** [review]
What is the benefit in disallowing shared library builds? It seems that `fftw` default is to build both, and avoiding shared libraries saves only a few MBs.

**Comment by AlexanderRichert-NOAA** [comment]
Partly it's to satisfy organizational requirements of minimizing the number of shared libraries available to developers, and also not all build systems are good at distinguishing between static and shared if both are available, so we want to access that feature of the build system when we know we only need static.

**Review by becker33 — APPROVED** [review]

**Pull request merged**
