### PR TITLE
py-igraph: add v0.11.6

### PR DESCRIPTION
**Pull request by szhorvat**

### CODE REVIEW

**Comment by szhorvat** [comment]
@alecbcs Is there anything specific needed before this can be merged?

**Review by bernhardkaindl — APPROVED** [review]
Built igraph-0.11.6 on Ubuntu 22.04

**Review by ChristopherChristofi — COMMENTED** [review]
Hello, thank you, yes for the new version looks all good to me.
I can see it has already been merged, but in setup we still need the upper version constraint on the extra matplotlib variant when working with the older py igraph

**Comment by szhorvat** [comment]
I am not aware of any incompatibility between python-igraph 0.10.6 and matplotlib newer than 3.5.

**Comment by alecbcs** [comment]
@ChristopherChristofi did you find a failing build with an older version of matplotlib?

**Comment by ChristopherChristofi** [comment]
Hello @alecbcs, for py-igraph at `0.10.6` I would not have tested matplotlib at a version other than `3.5` as that would be inconsistent with the source setup instructions: https://github.com/igraph/python-igraph/blob/0.10.6/setup.py#L979

**Pull request merged**
