### PR TITLE
libedit depends on ncurses

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Wow, the documentation on libedit is abysmal. Can you provide me with a link to something that says it depends on ncurses? While you're at it, can you resolve the conflicts on this branch?

**Comment by eschnett** [comment]
Documentation? No. But I tried to build libedit on a system that didn't have ncurses installed, and there was an error message. I don't recall the details, but the error was probably "ncurses.h not found".

See also e.g. <https://build.opensuse.org/package/view_file/X11:Sugar/libedit/libedit-ncurses-pkg-config.patch?rev=c9e57100ceff63307a17523e95c3bb65> on the web.

Will resolve the conflict.

**Comment by adamjstewart** [comment]
Works for me!

**Comment by eschnett** [comment]
Conflict resolved.

**Comment by tgamblin** [comment]
Thanks!

**Pull request merged**
