### PR TITLE
gtkplus: Add old gtkplus 3.22.30 for old glib 2.56

### PR DESCRIPTION
**Pull request by Jordan474**
This change allows concretization and installation of gtkplus with external glib 2.56 on rhel7 and rhel8.

I'm not sure how to check if glibc 3.22 is deprecated, but [Gtk+ 2.22.30 is rhel7 and rhel8's version](https://pkgs.org/search/?q=gtk3).

Notes:
- I tested `spack install gtkplus@3.22.30` (spack-installed): OK
- I tested `spack install gtkplus@3.22.30 ^glib@2.56` (spack-installed): FAIL: glib fails for some obscure reason. Removing filter_file of glib-genmarshal.in fixes it but I cannot find why...
 - I tested `spack install gtkplus@3.22.30 ^glib@2.56-as-external-rpm-rhel7/8`: OK **(may require external pkgconf too)**
- a few other packages don't support external glib 2.56. I have a few quick and dirty fixes I need to cleanup for another PR.

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
Can we use multiple build systems, instead of abusing `meson` here? This was not introduced by this PR, but still is something that should be fixed either here or in a following PR.

**Comment by wdconinc** [comment]
> Can we use multiple build systems

This is a somewhat older PR, so I don't want to assume that @Jordan474 will have the bandwidth or need to fix this. If we merge this, I can take care of converting to multiple build systems in a separate PR.

**Comment by alalazo** [comment]
@wdconinc Feel free to merge, ping me in the next PR if you need a reviewer :wink:

**Comment by wdconinc** [comment]
FYI, #46869 sanitizes the multiple build systems.

**Comment by Jordan474** [comment]
> FYI, https://github.com/spack/spack/pull/46869 sanitizes the multiple build systems.

Thank you. I'm good rebasing after #46869 merge, if you didn't take care of it already.

**Comment by alalazo** [comment]
FYI #46869 has been merged

**Comment by wdconinc** [comment]
Conflict resolved.

**Comment by Jordan474** [comment]
I am currently running the tests I did back then for rhel7 and rhel8  (centos7/almalinux8) to make sure there is no new issues for me. I'll get back to you as soon as possible.

**Comment by Jordan474** [comment]
I am good with merging this PR as-is.

But I encountered other somewhat unrelated issues, so I will open a couple Issues to discuss those. (`dbus` fail on almalinux, and `/usr` external glib missing `PKG_CONFIG_PATH`)

EDIT: Update on those unrelated issues: they can be workaround, for the record:
- Spack chose the non-preferred `dbus@1.15.10` for some reason (?), and it fails on a chgrp `messagebus` (the default "dbus_user" meson option) because I'm running as root in the container, and on almalinux `messagebus` does not exist. The preferred `dbus@1.14` is not affected. And I think it's [not fatal](https://gitlab.freedesktop.org/dbus/dbus/-/blob/c59108890aab69357ac6dca244520193a32a7ce8/meson_post_install.py#L99) anymore in more recent dbus versions anyway. However, we might still want to enforce a `dbus_user=<currentuser>` to avoid having installed files with the `messagebus` group (can happen in ubuntu when installing as root)...
- The missing `PKG_CONFIG_PATH=/usr/...` can be workaround with an external `pkgconf` that will look up /usr as last resort.
- There are a few more fixes in other packages to support external `/usr` glib, but I am not sure those would be beneficial to other Spack users.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
