### PR TITLE
r-backports: add 1.4.1

### PR DESCRIPTION
**Pull request by manuelakuhn**

### CODE REVIEW

**Comment by glennpj** [comment]
@adamjstewart 
@manuelakuhn has submitted several R package PRs. Should #28786 be merged first and then review the other PRs, or should these individual R PRs get merged first and #28786 rebased later?

**Comment by adamjstewart** [comment]
@glennpj up to you. Let me know if #28786 is ready for me to review.

**Comment by manuelakuhn** [comment]
Sorry, I must have overlooked this PR. Feel free to let me know if I can help with it.

**Comment by glennpj** [comment]
@adamjstewart Besides the pipeline failing, #28786 is ready for review.

**Review by glennpj — APPROVED** [review]

**Pull request merged**
