### PR TITLE
tmux should not set PKG_CONFIG_PATH

### PR DESCRIPTION
**Pull request by YtterbiJum**
tmux should not set "PKG_CONFIG_PATH=..." in the call to configure() in package.py.

This overwrites the environment's PKG_CONFIG_PATH, which causes problems with the Cray compiler wrappers (cc, CC, and ftn).  The Cray compiler wrappers use pkg-config to find packages according to the modules loaded in the environment.  But it can't find these packages if the PKG_CONFIG_PATH is improperly set.

For example, after running `spack install -v tmux`, I was seeing errors like this:

```
configure:3021: checking for gcc
configure:3048: result: /p/home/sbateman/spack/lib/spack/env/gcc/gcc
configure:3277: checking for C compiler version
configure:3286: /p/home/sbateman/spack/lib/spack/env/gcc/gcc --version >&5
pkg-config error:
Package AtpSigHandler was not found in the pkg-config search path.
Perhaps you should add the directory containing `AtpSigHandler.pc'
to the PKG_CONFIG_PATH environment variable
No package 'AtpSigHandler' found
configure:3297: $? = 1
```

This pull request fixes the problem by removing the "PKG_CONFIG_PATH=..." argument from the call to configure().  `spack install -v tmux` seems to correctly find the libevent and ncurses libraries anyway.

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like this has been in the package since @davidbeckingsale first wrote it in e402a2e27cc2942a20916615c8eb06999c0320e6.

**Comment by davidbeckingsale** [comment]
I'm happy with the change provided it's tested properly. I'm not sure that:

>  spack install -v tmux seems to correctly find the libevent and ncurses libraries anyway.

is good enough. I can't remember, but I'm assuming I only set the `PKG_CONFIG_PATH` because it didn't correctly find them on my system. If this is now handled by spack internally then that's fine.

**Comment by adamjstewart** [comment]
Just ran some quick tests on CentOS 6 with GCC 6.3.0. Everything builds okay, but it doesn't seem to be linking to `ncurses`:
```
$ ldd -r bin/tmux 
	linux-vdso.so.1 =>  (0x00002b708baaf000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002b708bcb2000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00002b708beb5000)
	libevent-2.0.so.5 => /blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0/libevent-2.0.21-faapuxg23mxdhnkrz7dykv37tzosbovd/lib/libevent-2.0.so.5 (0x00002b708c0d7000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b708c32b000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00002b708c533000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b708c74e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b708cae2000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b708ba8f000)
```

**Comment by YtterbiJum** [comment]
@adamjstewart 
Good idea, I changed `Package` to `AutotoolsPackage`.

@davidbeckingsale 
I think the `depends_on(...)` will automatically set `PKG_CONFIG_PATH` correctly to find those libraries.  I'm not really sure how to test that, though.  I don't think any other packages explicitly set `PKG_CONFIG_PATH` in their package.py files.

**Comment by adamjstewart** [comment]
> I think the `depends_on(...)` will automatically set `PKG_CONFIG_PATH` correctly to find those libraries.

That is correct. It sets them [here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L304).

**Comment by adamjstewart** [comment]
It looks like `libtinfo` was merged into `libncurses`. I was able to get `tmux` to link to the correct libraries:
```
$ ldd -r tmux 
	linux-vdso.so.1 =>  (0x00007ffec5d98000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002b1bc3939000)
	libncurses.so.6 => /blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0/ncurses-6.0-7p4ir7ttynua6ejffsgwva34vdclnzga/lib/libncurses.so.6 (0x00002b1bc3b3c000)
	libevent-2.0.so.5 => /blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0/libevent-2.0.21-faapuxg23mxdhnkrz7dykv37tzosbovd/lib/libevent-2.0.so.5 (0x00002b1bc3da0000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b1bc3ff4000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00002b1bc41fc000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b1bc4417000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b1bc47ab000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b1bc3716000)
```
with the following change to `tmux`:
```python
def configure_args(self):                                                   
    return ['LIBTINFO_LIBS=-lncurses']
```

**Comment by YtterbiJum** [comment]
@adamjstewart Done.

I realized I also accidentally included some extra commits from the "master" branch, because I was following some instructions for doing pull requests (this is new to me) that includes `git pull upstream master`, without realizing the main branch is called "develop".

**Comment by adamjstewart** [comment]
Don't worry about the extra commits. We squash all PRs before merging anyway.

**Comment by adamjstewart** [comment]
@davidbeckingsale Can you test this and make sure it works for you?

**Comment by davidbeckingsale** [comment]
Looks good.

**Pull request merged**
