### PR TITLE
sundials: add new version and fix smoke tests

### PR DESCRIPTION
**Pull request by balos1**
CC @wspear

### CODE REVIEW

**Review by wspear — DISMISSED** [review]
This works for me! Will the test exercise cuda/rocm/sycl acceleration if one of those variants is active?

**Comment by balos1** [comment]
> This works for me! Will the test exercise cuda/rocm/sycl acceleration if one of those variants is active?

Yes, if cuda/rocm/sycl variant is active those smoke tests will run.

**Review by wspear — DISMISSED** [review]
Still works for me.

**Review by gardner48 — DISMISSED** [review]

**Review by gardner48 — APPROVED** [review]

**Comment by eugeneswalker** [comment]
I restarted the failed CI job -- it was a runner system error -- the job has now passed and hopefully the pipeline will finish green very shortly.

**Pull request merged**
