### PR TITLE
Add latest version of PGI compilers

### PR DESCRIPTION
**Pull request by adamjstewart**
Also updated comment. The tarball no longer needs to be renamed.

### CODE REVIEW

**Comment by serbanmaerean** [comment]
What happens if I have the PGI compiler already installed in /opt/pgi?
I have the community edition and chose to install it in the default location, /opt/pgi, but `spack compiler find` does  not find it.  I also tried `spack compiler find /opt/pgi/linuxpower/17.4`, but no luck.
Is there anything else I can do go get spack to recognize it?

**Comment by adamjstewart** [comment]
Can you run:
```
$ ls /opt/pgi/linuxpower/17.4
```
and give me the output?

**Comment by adamjstewart** [comment]
Try `spack compiler find /opt/pgi/linuxpower/17.4/bin`.

**Comment by adamjstewart** [comment]
Also, what's the output of `pgcc -V`?

**Comment by serbanmaerean** [comment]
--> ls -l /opt/pgi/linuxpower/17.4
total 24
drwxr-xr-x 2 sserban users 4096 May  5 16:10 bin
drwxr-xr-x 3 sserban users  201 May  5 16:10 doc
-rw-r--r-- 1 root    root     5 May  5 16:10 glibc_version
drwxr-xr-x 4 sserban users 4096 Apr 21 12:59 include
drwxr-xr-x 2 sserban users  267 Apr 21 12:59 include_acc
drwxr-xr-x 3 sserban users   70 Apr 21 12:59 include-gcc48
drwxr-xr-x 3 sserban users   54 Apr 21 12:59 include-gcc49
drwxrwxr-x 2     921  1016   73 Apr 21 12:59 include_man
drwxr-xr-x 2 sserban users   53 Apr 21 13:00 include_pin
lrwxrwxrwx 1 root    root     4 May  5 16:10 jre -> /usr
drwxrwxr-x 2     921  1016 4096 Apr 21 12:59 lib
drwxr-xr-x 3 sserban users   18 Apr 21 13:00 man
drwxr-xr-x 2 sserban users 4096 Apr 21 13:00 REDIST
drwxr-xr-x 3 sserban users   18 Apr 21 13:00 share
drwxr-xr-x 2 sserban users  170 Apr 21 13:00 src
-rw-r--r-- 1 sserban users 2479 Apr 21 12:59 SUPPORT_SERVICE

--> pgcc -V

pgcc 17.4-0 linuxpower target on Linuxpower 
PGI Compilers and Tools
Copyright (c) 2017, NVIDIA CORPORATION.  All rights reserved.

I tried the different combinations, same results:
--> spack compiler list
==> Available compilers
-- gcc rhel7-ppc64le --------------------------------------------
gcc@4.8.5

-- xl rhel7-ppc64le ---------------------------------------------
xl@14.1

-- xl_r rhel7-ppc64le -------------------------------------------
xl_r@14.1
--> spack compiler find /opt/pgi
==> Found no new compilers
==> Compilers are defined in the following files:
    /home/sserban/.spack/linux/compilers.yaml
--> spack compiler find /opt/pgi/linuxpower/17.4
==> Found no new compilers
==> Compilers are defined in the following files:
    /home/sserban/.spack/linux/compilers.yaml
--> spack compiler find /opt/pgi/linuxpower/17.4/bin
==> Found no new compilers
==> Compilers are defined in the following files:
    /home/sserban/.spack/linux/compilers.yaml

**Comment by adamjstewart** [comment]
Ah, I know what the problem is. I can fix that. I'll send out a PR shortly.

**Pull request merged**
