### PR TITLE
SEACAS: Update package.py to handle new SEACAS project name

### PR DESCRIPTION
**Pull request by gsjaardema**
The base project name for the SEACAS project has changed from "SEACASProj" to "SEACAS" as of @2022-10-14, so the package needed to be updated to use the new project name when needed.

The refactor also changes several:
    `"-DSome_CMAKE_Option:BOOL=ON"`
to
   `define("Some_CMAKE_Option", True)`

### CODE REVIEW

**Review by sethrj — DISMISSED** [review]
LGTM

**Comment by gsjaardema** [comment]
@sethrj Sorry, should have just done a regular merge instead of force-push which dismissed your review...

**Comment by gsjaardema** [comment]
@sethrj Sorry, I accidentally dismissed your review during a merge to bring PR up-to-data.  Could you re-review.

**Review by sethrj — APPROVED** [review]

**Comment by gsjaardema** [comment]
recheck

**Pull request merged**
