### PR TITLE
Package/mirdeep/fix for new url take2

### PR DESCRIPTION
**Pull request by Sinan81**
fixes for new url

### CODE REVIEW

**Comment by adamjstewart** [comment]
It still has conflicts though. You need to rebase off of the latest develop.

**Comment by Sinan81** [comment]
Not sure how to do the rebasing. Could you provide some help?

**Comment by scheibelp** [comment]
> Not sure how to do the rebasing. Could you provide some help?

Do you know how to merge develop into your branch (and resolve conflicts)? If so that should be sufficient for this PR (as long as the person who accepts it uses a squash merge). If not:

* update the develop branch: `git checkout develop` + `git fetch upstream` + `git merge upstream/develop`
* merge develop into your branch (there will be errors): `git checkout <your branch>` + `git merge develop`
* it will complain: look for and resolve conflicts in reported files, once finished add them with `git add <file that was conflicting>` and then manually commit the merge

For rebasing, you can do:

`GIT_EDITOR=vi git rebase --interactive develop`

this will bring up a text file describing the edits. Generally you would want to look up a tutorial on rebasing but in this case you want to just apply all your edits as is, so `:x!` the file. It will complain, at which point you resolve the errors and follow the directions that `git rebase` gave when it encountered the conflict to continue.

Note: Rebasing changes the commit history on your branch so when you update this PR you will need to do a force push.

**Comment by Sinan81** [comment]
@scheibelp Thanks! I followed the steps you suggested and forcefully pushed it in the end. But now, I am not seeing any updates on this PR issue. I am curious if it worked or not.

**Pull request merged**
