### PR TITLE
New MFEM version: 4.5

### LINKED ISSUE #30483: mfem@4.4.0 +rocm build fails: config/defaults.mk:184: Unable to determine HIP_DIR...
### Steps to reproduce the issue

`mfem@4.4.0 +rocm` build fails using:
* `spack/develop` (250d5d2c00ad9d6a747499b1160bc4a460266fae from `Wed May 4 13:30:15 2022 -0400`)
* Ubuntu 20.04, X86_64
* GCC 9.4.0
* ROCm 5.0.2

Concrete spec: [mfem-6kjw6vo.spec.json.txt](https://github.com/spack/spack/files/8626733/mfem-6kjw6vo.spec.json.txt)

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 250d5d2c0)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./mfem-6kjw6vo.spec.json

$> spack install --no-cache -f ./mfem-6kjw6vo.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/37/37250dbef6e97b16dc9ab50973e8d68bc165bb4afcdaf91b3b72c8972c87deef.tar.gz
==> No patches needed for mfem
==> mfem: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 2:
    'make' 'config' 'PREFIX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt' 'MFEM_USE_MEMALLOC=YES' 'MFEM_DEBUG=NO' 'CXX=/spack/lib/spack/env/gcc/g++' 'MFEM_USE_LIBUNWIND=NO' 'MFEM_USE_ZLIB=YES' 'MFEM_USE_METIS=YES' 'MFEM_USE_METIS_5=YES' 'MFEM_THREAD_SAFE=NO' 'MFEM_USE_MPI=YES' 'MFEM_USE_LAPACK=NO' 'MFEM_USE_SUPERLU=NO' 'MFEM_USE_STRUMPACK=NO' 'MFEM_USE_SUITESPARSE=NO' 'MFEM_USE_SUNDIALS=NO' 'MFEM_USE_PETSC=NO' 'MFEM_USE_SLEPC=NO' 'MFEM_USE_PUMI=NO' 'MFEM_USE_GSLIB=NO' 'MFEM_USE_NETCDF=NO' 'MFEM_USE_MPFR=NO' 'MFEM_USE_GNUTLS=NO' 'MFEM_USE_OPENMP=NO' 'MFEM_USE_CONDUIT=NO' 'MFEM_USE_CUDA=NO' 'MFEM_USE_HIP=YES' 'MFEM_USE_OCCA=NO' 'MFEM_USE_RAJA=NO' 'MFEM_USE_AMGX=NO' 'MFEM_USE_CEED=NO' 'MFEM_USE_UMPIRE=NO' 'MFEM_MPIEXEC=mpirun' 'MFEM_MPIEXEC_NP=-np' 'MPICXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mpich-4.0.2-ezlhwrd3oenacpj4jstb2o7jsxebfdwn/bin/mpic++' 'HYPRE_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/include' 'HYPRE_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -lHYPRE -lopenblas' 'METIS_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/include' 'METIS_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -lmetis' 'ZLIB_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/include' 'ZLIB_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -lz' 'HIP_CXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hip-5.0.2-zxtdoythrectfv7epw3a3kdeayjsap2g/bin/hipcc' 'HIP_ARCH=gfx908'

1 error found in build log:
     1    ==> mfem: Executing phase: 'configure'
     2    ==> [2022-05-04-12:51:42.830382] 'make' 'config' 'PREFIX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mfem-4.4.0-6kjw6voapywitf
          bej42dh7o35sbfwyxt' 'MFEM_USE_MEMALLOC=YES' 'MFEM_DEBUG=NO' 'CXX=/spack/lib/spack/env/gcc/g++' 'MFEM_USE_LIBUNWIND=NO' 'MFEM_USE_ZLIB=
          YES' 'MFEM_USE_METIS=YES' 'MFEM_USE_METIS_5=YES' 'MFEM_THREAD_SAFE=NO' 'MFEM_USE_MPI=YES' 'MFEM_USE_LAPACK=NO' 'MFEM_USE_SUPERLU=NO' '
          MFEM_USE_STRUMPACK=NO' 'MFEM_USE_SUITESPARSE=NO' 'MFEM_USE_SUNDIALS=NO' 'MFEM_USE_PETSC=NO' 'MFEM_USE_SLEPC=NO' 'MFEM_USE_PUMI=NO' 'MF
          EM_USE_GSLIB=NO' 'MFEM_USE_NETCDF=NO' 'MFEM_USE_MPFR=NO' 'MFEM_USE_GNUTLS=NO' 'MFEM_USE_OPENMP=NO' 'MFEM_USE_CONDUIT=NO' 'MFEM_USE_CUD
          A=NO' 'MFEM_USE_HIP=YES' 'MFEM_USE_OCCA=NO' 'MFEM_USE_RAJA=NO' 'MFEM_USE_AMGX=NO' 'MFEM_USE_CEED=NO' 'MFEM_USE_UMPIRE=NO' 'MFEM_MPIEXE
          C=mpirun' 'MFEM_MPIEXEC_NP=-np' 'MPICXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mpich-4.0.2-ezlhwrd3oenacpj4jstb2o7jsxebfd
          wn/bin/mpic++' 'HYPRE_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/include'
           'HYPRE_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -Wl,-rpat
          h,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -L/spack/opt/spack/linux-ub
          untu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/ope
          nblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -lHYPRE -lopenblas' 'METIS_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0
          /metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/include' 'METIS_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis
          -5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhm
          zbiqssru/lib -lmetis' 'ZLIB_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/inc
          lude' 'ZLIB_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -L/spa
          ck/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -lz' 'HIP_CXX=/spack/opt/spack/linux-
          ubuntu20.04-x86_64/gcc-9.4.0/hip-5.0.2-zxtdoythrectfv7epw3a3kdeayjsap2g/bin/hipcc' 'HIP_ARCH=gfx908'
  >> 3    config/defaults.mk:184: *** Unable to determine HIP_DIR. Please set it manually..  Stop.

See build log for details:
  /tmp/root/spack-stage/spack-stage-mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (250d5d2c00ad9d6a747499b1160bc4a460266fae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8626742/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8626743/spack-build-out.txt)

@acfisher @goxberry @markcmiller86 @tzanio @v-dobrev @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by v-dobrev**
Also, add new MFEM variants: ginkgo, hiop.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.  Rest LGTM.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by eugeneswalker — APPROVED** [review]

**Comment by v-dobrev** [comment]
Hmm, why the merge? This was marked `WIP`. I have more changes and I wanted to do more testing.

**Comment by eugeneswalker** [comment]
> Hmm, why the merge? This was marked `WIP`. I have more changes and I wanted to do more testing.

Oops! Sorry!  I did not mean to merge this one. I can submit a reversion right now. I apologize for this.

**Comment by v-dobrev** [comment]
Not a big deal. I created a follow up PR: #33603.

**Comment by eugeneswalker** [comment]
> Not a big deal. I created a follow up PR: #33603.

OK. Sorry. I will be more careful.

**Pull request merged**
