### PR TITLE
Build OpenMP in LLVM via LLVM_ENABLE_RUNTIMES.

### PR DESCRIPTION
**Pull request by ye-luo**
Default build OpenMP in LLVM via LLVM_ENABLE_RUNTIMES since LLVM 12.
The post installation build for the bitcode library is no more needed in this case.

@trws

### CODE REVIEW

**Review by trws — APPROVED** [review]
I'm ok with taking this.  I've got an in-progress patch that does this, but also builds the other runtimes this way.  It has turned into a much larger job than I was hoping though, so we may as well get the benefits of this now.  Thanks!

**Comment by tgamblin** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
@ye-luo: in the future you can ask @spackbot to run pipelines for you if they are backlogged.

**Comment by ye-luo** [comment]
> @ye-luo: in the future you can ask @spackbot to run pipelines for you if they are backlogged.

@tgamblin thank you. That is helpful.

**Pull request merged**
