### PR TITLE
updates to conduit to add hostcfg and use cmake base

### PR DESCRIPTION
**Pull request by cyrush**
adds hostconfig stage

### CODE REVIEW

**Comment by tldahlgren** [comment]
@cyrush Interesting that the last of the required checks have *finally* passed within the last few minutes.  I've been trying to build this on quartz and it fails due to `TypeError`s.  I have not yet determined the source, which is another reason I have not yet approved and merged this PR yet.

**Comment by cyrush** [comment]
@tldahlgren strange, if I can help debug anything -- let me know.

**Comment by tldahlgren** [comment]
> @tldahlgren strange, if I can help debug anything -- let me know.

Thanks.  One of the Spack team members has a fix for Python 3 that appears to have resolved my problem.  (See #22328.)

**Review by tldahlgren — DISMISSED** [review]
I can build the software with these changes (after #22328 patch for python 3).

**Comment by tldahlgren** [comment]
Update:  

- `spack install conduit` builds successfully for me
- `spack install conduit +zfp` fails for me in the `conduit` installation's attempt to build `t_h5z_zfp_smoke.dir/t_h5z_zfp_smoke.cpp.o` (`H5public.h:63:10: fatal error: api.h: No such file or directory)
- `spack install conduit +hdf5+zfp` fails with constraint satisfaction issue: `conduit requires hdf5 version 1.8.19:1.8.999, but spec asked for 1.10.7`

**Comment by tldahlgren** [comment]
> Update:
> 
> * `spack install conduit` builds successfully for me
> * `spack install conduit +zfp` fails for me in the `conduit` installation's attempt to build `t_h5z_zfp_smoke.dir/t_h5z_zfp_smoke.cpp.o` (`H5public.h:63:10: fatal error: api.h: No such file or directory)
> * `spack install conduit +hdf5+zfp` fails with constraint satisfaction issue: `conduit requires hdf5 version 1.8.19:1.8.999, but spec asked for 1.10.7`

Going back to `develop`, the failing installations above work.  So there are changes in this PR that appear to break the Spack build for me.

**Comment by cyrush** [comment]
@tldahlgren Thanks, I'll get to the bottom of the issues with zfp support

**Comment by cyrush** [comment]
the compile error with `+zfp` is an issue with h5z-zfp support in conduit's build system (missing implied mpi dependency for that specific smoke test), I am working on a fix.


The failure with `+hdf5+zfp` seems to be a spack concretizer issue:

If I explicitly add `^hdf5@1.8.19` as a constraint, it concretizes.

without constraint: (failure)


```
root@b570336e657f:/spack# bin/spack spec  conduit+hdf5+zfp        
Input spec
--------------------------------
conduit+hdf5+zfp

Concretized
--------------------------------
==> Warning: gcc@7.5.0 cannot build optimized binaries for "zen2". Using best target possible: "zen"
==> Error: An unsatisfiable version constraint has been detected for spec:

    hdf5@1.10.7%gcc@7.5.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=none arch=linux-ubuntu18.04-zen


while trying to concretize the partial spec:

    conduit@develop%gcc@7.5.0~adios~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi~python+shared~silo+test+zfp build_type=RelWithDebInfo arch=linux-ubuntu18.04-zen
        ^cmake@3.19.5%gcc@7.5.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu18.04-zen
            ^ncurses
                ^pkgconfig
            ^openssl
                ^perl@5.14.0:
                    ^berkeley-db
                    ^gdbm
                        ^readline
                ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu18.04-zen
        ^zfp@0.5.5%gcc@7.5.0~aligned~c~cuda~fasthash~fortran~ipo~openmp~profile~python+shared~strided~twoway bsws=8 build_type=RelWithDebInfo cuda_arch=none arch=linux-ubuntu18.04-zen


conduit requires hdf5 version 1.8.19:1.8.999, but spec asked for 1.10.7
```

with constraint: (success)

```
root@b570336e657f:/spack# bin/spack spec  conduit+hdf5+zfp ^hdf5@1.8.19
Input spec
--------------------------------
conduit+hdf5+zfp
    ^hdf5@1.8.19

Concretized
--------------------------------
==> Warning: gcc@7.5.0 cannot build optimized binaries for "zen2". Using best target possible: "zen"
conduit@develop%gcc@7.5.0~adios~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi~python+shared~silo+test+zfp build_type=RelWithDebInfo arch=linux-ubuntu18.04-zen
    ^cmake@3.19.5%gcc@7.5.0~doc+ncurses+openssl+ownlibs~qt build_type=Release patches=b48396c0e4f61756248156b6cebe9bc0d7a22228639b47b5aa77c9330588ce88 arch=linux-ubuntu18.04-zen
        ^ncurses@6.2%gcc@7.5.0~symlinks+termlib arch=linux-ubuntu18.04-zen
            ^pkgconf@1.7.3%gcc@7.5.0 arch=linux-ubuntu18.04-zen
        ^openssl@1.1.1j%gcc@7.5.0~docs+systemcerts arch=linux-ubuntu18.04-zen
            ^perl@5.32.1%gcc@7.5.0+cpanm+shared+threads arch=linux-ubuntu18.04-zen
                ^berkeley-db@18.1.40%gcc@7.5.0~docs patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu18.04-zen
                ^gdbm@1.18.1%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                    ^readline@8.0%gcc@7.5.0 arch=linux-ubuntu18.04-zen
            ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu18.04-zen
    ^h5z-zfp@0.8.0%gcc@7.5.0~fortran arch=linux-ubuntu18.04-zen
        ^hdf5@1.8.19%gcc@7.5.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=none patches=b61e2f058964ad85be6ee5ecea10080bf79e73f83ff88d1fa4b602d00209da9c arch=linux-ubuntu18.04-zen
            ^openmpi@4.0.5%gcc@7.5.0~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-ubuntu18.04-zen
                ^hwloc@2.4.1%gcc@7.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-ubuntu18.04-zen
                    ^libpciaccess@0.16%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                        ^libtool@2.4.6%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                            ^m4@1.4.18%gcc@7.5.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-ubuntu18.04-zen
                                ^libsigsegv@2.12%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                        ^util-macros@1.19.1%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                    ^libxml2@2.9.10%gcc@7.5.0~python arch=linux-ubuntu18.04-zen
                        ^libiconv@1.16%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                        ^xz@5.2.5%gcc@7.5.0~pic arch=linux-ubuntu18.04-zen
                ^libevent@2.1.12%gcc@7.5.0+openssl arch=linux-ubuntu18.04-zen
                ^numactl@2.0.14%gcc@7.5.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94,62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006 arch=linux-ubuntu18.04-zen
                    ^autoconf@2.69%gcc@7.5.0 arch=linux-ubuntu18.04-zen
                    ^automake@1.16.3%gcc@7.5.0 arch=linux-ubuntu18.04-zen
        ^zfp@0.5.5%gcc@7.5.0~aligned~c~cuda~fasthash~fortran~ipo~openmp~profile~python+shared~strided~twoway bsws=8 build_type=RelWithDebInfo cuda_arch=none arch=linux-ubuntu18.04-zen

```

Also, `+hdf5` is a the default variant choice for conduit, so `conduit+zfp` should be the same as `conduit+hdf5+zfp`

Just to double check, they do resolve to the same variant selections:

```
spack spec  conduit+hdf5+zfp ^hdf5@1.8.19


conduit@develop%gcc@7.5.0~adios~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi~python+shared~silo+test+zfp build_type=RelWithDebInfo arch=linux-ubuntu18.04-zen
```

```
spack spec  conduit+zfp

conduit@develop%gcc@7.5.0~adios~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi~python+shared~silo+test+zfp build_type=RelWithDebInfo arch=linux-ubuntu18.04-zen
```

**Comment by cyrush** [comment]
@tldahlgren I merged a build system fix, so `conduit@develop` should now build for the `+zfp` case.  I am not sure if there is a way to defend against the concertizer confusion.

**Review by tldahlgren — APPROVED** [review]
Thanks for the fixes Cyrus!  

My builds are now consistent with what you're reporting.

**Comment by tldahlgren** [comment]
Thank you for your contribution Cyrus!

**Comment by cyrush** [comment]
@tldahlgren  thanks!

**Pull request merged**
