### PR TITLE
Add support for mfem cuda build

### PR DESCRIPTION
**Pull request by aaroncblack**
Add missing 'cublas' dependency in MFEM library spack build.

### CODE REVIEW

**Comment by aaroncblack** [comment]
@v-dobrev @tzanio I spoke briefly with Veselin about this in the past.  Cublas is a dependency on newer hypre versions for the cuda build.

Veselin, I wasn't sure if you had a planned change already for this spack package but I went ahead and created this PR.

**Review by v-dobrev — DISMISSED** [review]
Thanks @aaroncblack, this looks good and it should be fine with older hypre versions too.

**Comment by aaroncblack** [comment]
@v-dobrev I'm not sure who has permissions to merge this.  (I don't).  I'm guessing you and @tzanio do, as the mfem owners, but if 'Merge pull request' is greyed out with "You’re not authorized to merge this pull request." let me know.   I can ask Todd Gamblin about it.

**Review by v-dobrev — DISMISSED** [review]

**Comment by v-dobrev** [comment]
I think I have permission to merge this after all PR checks pass, however I typically wait for someone from the Spack team to do it since I'm not familiar with all the policies on merging.

**Review by alalazo — APPROVED** [review]
@v-dobrev already approved

**Review by v-dobrev — APPROVED** [review]

**Comment by v-dobrev** [comment]
@alalazo, I tried hitting the "Update branch" button to get clean CI checks to trigger the auto-merge but that did not work. What can we do to get this merged?

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
Tried re-running the two spuriously failed builds.

**Pull request merged**
