### PR TITLE
root: new version 6.22.08

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
Maintainer-ping: @chissg, @HadrienG2, @drbenmorgan, @vvolkl

### CODE REVIEW

**Comment by HadrienG2** [comment]
May I ask you to request TBB < 2021.1.1 for root <= 6.22, since newer TBB is now [officially unsupported](https://github.com/root-project/root/issues/6933) by this ROOT branch ?

**Review by tldahlgren — APPROVED** [review]
Confirmed version available on the site

**Comment by ChristianTackeGSI** [comment]
> May I ask you to request TBB < 2021.1.1 for root <= 6.22, since newer TBB is now [officially unsupported](https://github.com/root-project/root/issues/6933) by this ROOT branch ?

Some info:
* The intel-tbb package still hasn't 2021.1.1. I am considering to add it soon (unless someone else is quicker anyway). So this problem is currently not super important. Still good to adress it.
* Currently, `root` has a `depends_on('tbb')`. `tbb` is a virtual package and `intel-tbb` provides it. The virtual package has no version information (yet).

We could:
1. Turn the `depends_on('tbb')` into a `depends_on('intel-tbb')` and properly version it. But unless ROOT actually can't run with the other providers, that's probably not a good idea.
2. Start to version the virtual package. (I think, that is possible.)
3. Put a `conflicts('^intel-tbb@2021.1:`, when='@:6.22`, msg='Please use an older TBB version')` in the root recipe. Should do the job easily. But requires people to add a `^intel-tbb@2020.3` to their install lines.
4. Put a `depends_on('intel-tbb@:2021.0', when='@:6.22 ^intel-tbb')`. This looks like it works. BUT the classic concretizer can't handle it (I tried it). I hope the new one can handle it (didn't yet try it). The problem with the old concretizer is, that the error message is not easy to understand. So a user wouldn't easily know how to fix it.

I don't know, which is best, really. I personally would prefer (4) despite the classic concretizer not working with it.

Not to mention, we'd need to understand the other tbb providers and their versioning.

**Comment by vvolkl** [comment]
Thanks @ChristianTackeGSI for the comprehensive comment. I tend to use conflicts in situations like this, so I vote Option 3., which seems the most straighforward. Maybe the current `intel-tbb` version can be the `preferred` one for a while, that would help with concretizing the default spec.

**Comment by HadrienG2** [comment]
I would vote for either option 2 or 3 at your preference. Option 3 seems easier to implement but will not prevent incompatibilities with other implementors of `tbb` like `intel-mkl`, something which option 2 should help with.

**Comment by ChristianTackeGSI** [comment]
Thanks @vvolkl and @HadrienG2

Suggestion:
Let's start with (3) (plus preferring intel-tbb for a bit).
```python
conflicts('^intel-tbb@2021.1:', when='@:6.22', msg='Please use an older intel-tbb version')
```
what do you think about this one?

That seems the most straight forward and least invasive solution for the time being.

Should we file an issue like "Consider versioning virtual tbb package" to track looking into (2)?

**Comment by HadrienG2** [comment]
Sounds good to me!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
