### PR TITLE
e4s ci: add trilinos +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
FYI @keitat @kuberry @sethrj @wspear

### CODE REVIEW

**Review by sethrj — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by sethrj — DISMISSED** [review]

**Review by keitat — DISMISSED** [review]

**Comment by tldahlgren** [comment]
Looks like the `trilinos` package doesn't build with these variants per https://gitlab.spack.io/spack/spack/-/jobs/2808509.  Although the job log is truncated, the build log can be found at https://gitlab.spack.io/spack/spack/-/jobs/2808509/artifacts/browse/jobs_scratch_dir/logs/.

**Comment by sethrj** [comment]
Hah, this is a similar error to what I've seen on windows:
```
spack-src/packages/belos/src/BelosBiCGStabSolMgr.hpp:280:37: error: dynamic initialization is not supported for __device__, __constant__, __shared__, and __managed__ variables.
    static constexpr std::ostream * outputStream_default_ = &std::cout;
                                    ^                       ~~~~~~~~~~
```

This line of code makes me sad.

**Comment by keitat** [comment]
I am going to bring this to the Belos developers.

**Comment by eugeneswalker** [comment]
> I am going to bring this to the Belos developers.

Any update? Would it make sense to add a patch?

**Comment by eugeneswalker** [comment]
Trying `trilinos@13.4.0 ~belos +rocm ...` to see if that helps.

**Comment by sethrj** [comment]
Not sure if this helps, but here's a patch (which predates the current half-baked fix so can't be directly applied) that I think will fix the underlying problem:
https://github.com/sethrj/Trilinos/commit/71677252d632093bd7b0002ffe07e58b6024d3e8

**Comment by eugeneswalker** [comment]
Testing this locally, I had to set `~belos ~stokhos ~ifpack2` to get it to build. Just updated the PR here. Expect it to pass this time.

**Comment by sethrj** [comment]
If we can't build the fundamental "modern" linear solver package, how much point is there in distributing Trilinos with E4S :(

**Comment by eugeneswalker** [comment]
> If we can't build the fundamental "modern" linear solver package, how much point is there in distributing Trilinos with E4S :(

100% but, better to put this in now where we are to ensure at least it remains buildable, and then, when the issues are resolved, enable the other variants.

**Comment by eugeneswalker** [comment]
Re-based on develop since `e4s-pr-generate` is failing because of known broken specs in develop.

**Review by tldahlgren — APPROVED** [review]

**Review by sethrj — APPROVED** [review]

**Pull request merged**
