### PR TITLE
Miniconda3: Added Versions: 24.3.0, 24.1.2, 23.11.0, 23.9.0, 23.5.2, 23.5.1, 23.5.0, 23.3.1, 23.1.0

### PR DESCRIPTION
**Pull request by huston-rogers**
Miniconda3: Added Versions: 24.3.0, 24.1.2, 23.11.0, 23.9.0, 23.5.2, 23.5.1, 23.5.0, 23.3.1, 23.1.0 to package.py

### CODE REVIEW

**Comment by wdconinc** [comment]
Installs fine in codespaces:
```
# spack find -lv miniconda3
-- linux-ubuntu20.04-x86_64_v3 / gcc@11.4.0 ---------------------
35imdl3 miniconda3@23.1.0 build_system=generic  vrlws26 miniconda3@23.5.1 build_system=generic   tpvwxxx miniconda3@24.1.2 build_system=generic
2gcfn2f miniconda3@23.3.1 build_system=generic  77ryg6r miniconda3@23.9.0 build_system=generic   j5q6gbb miniconda3@24.3.0 build_system=generic
4orhfz3 miniconda3@23.5.0 build_system=generic  svsvuye miniconda3@23.11.0 build_system=generic
==> 8 installed packages
```

**Review by wdconinc — APPROVED** [review]

**Comment by wdconinc** [comment]
I'm wondering (likely out of scope of this PR) whether there is any interest in adding a variant for the python version, and to add the other platform system-machine (Linux-x86_64) tuples. That would allow miniconda installs on aarch64 or windows too.

**Comment by huston-rogers** [comment]
> I'm wondering (likely out of scope of this PR) whether there is any interest in adding a variant for the python version, and to add the other platform system-machine (Linux-x86_64) tuples. That would allow miniconda installs on aarch64 or windows too.

I also thought about this when I was adding the package descriptions. I defaulted to "latest python" for each release. We were only concerned about miniconda on linux x86, but agree there is value in expanding to other arch's

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Pull request merged**
