### PR TITLE
Add ECP tags for CoPA and related packages

### PR DESCRIPTION
**Pull request by streeve**

### CODE REVIEW

**Comment by aprokop** [comment]
@streeve What does `ecp` tag do and where does this requirement come from?

**Comment by streeve** [comment]
> @streeve What does `ecp` tag do and where does this requirement come from?

No requirement, just a new way to find packages, as I understand

**Comment by aprokop** [comment]
Where was this mentioned?

**Comment by streeve** [comment]
> Where was this mentioned?

I just noticed when creating a new package. #23382 discusses in some detail

**Comment by mkstoyanov** [comment]
I agree that we all need to identify as being under the DoE umbrella, but what's the difference between `e4s` and `ecp` as tags. Is there anyone in `e4s` that isn't also part of `ecp`?

I don't mind adding the tag, I just don't know if it is meaningful.

**Comment by aprokop** [comment]
> I just noticed when creating a new package. #23382 discusses in some detail

Thanks for the reference. But it still confuses me what `ecp` tag is for. They decided to **not** add `ecp` tag in that PR.

**Comment by aprokop** [comment]
> I just noticed when creating a new package. #23382 discusses in some detail

Thanks for the reference. But it still confuses me what `ecp` tag is for. They decided to **not** add `ecp` tag in that PR.

**Comment by aprokop** [comment]
I see that some of the `ecp` and `ecp-apps` tags were added in #8490, which predates E4S.

**Comment by alalazo** [comment]
I see some discussion is going on here. Feel free to ping me if you decide to merge the PR.

**Comment by aprokop** [comment]
fwiw, I don't really care whether this is merged or not, just curious.

**Comment by sethrj** [comment]
```console
$ spack list --tag ecp-proxy-app
==> 18 packages.
amg                ember      macsio   miniqmc   nekbone     swfft
candle-benchmarks  examinimd  miniamr  minitri   picsarlite  thornado-mini
ecp-proxy-apps     laghos     minife   minivite  sw4lite     xsbench
$ spack list --tag ecp
==> 25 packages.
amr-wind  chai              er       kvtree  nalu-wind  nektools   qmcpack  rmgdft    veloc
amrex     chombo            exawind  lammps  nek5000    nwchem     rankstr  shuffile
axl       ecp-data-vis-sdk  filo     latte   nekrs      parsplice  redset   spath
```

Looks like this PR fits in, so I'll merge.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
