### PR TITLE
Improve Ferret package

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**
Various improvements to the Ferret package.

### CODE REVIEW

**Comment by alalazo** [comment]
@RemiLacroix-IDRIS Would it be fine to add yourself as a maintainer?

**Comment by RemiLacroix-IDRIS** [comment]
> @RemiLacroix-IDRIS Would it be fine to add yourself as a maintainer?

Sure, although I am no Ferret expert.

**Comment by alalazo** [comment]
Thanks @RemiLacroix-IDRIS Then the only change needed here is to add:
```python
maintainers = ['RemiLacroix-IDRIS']
```
as a class attribute :slightly_smiling_face:

**Comment by RemiLacroix-IDRIS** [comment]
@alalazo: Done.

**Review by alalazo — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
