### PR TITLE
fix reference to spec in apex package

### PR DESCRIPTION
**Pull request by lee218llnl**
@adamjstewart sorry, I missed the apex package in #5075 fixes for #4975. Please take a look at this one too.

### CODE REVIEW

**Comment by lee218llnl** [comment]
please hold on this, have another commit coming soon

**Comment by lee218llnl** [comment]
OK, now they're building for me with updated md5 sums.

**Comment by adamjstewart** [comment]
Can you confirm with the developers that the hash change is due to a patch and their downloads haven't been compromised?

**Comment by lee218llnl** [comment]
OK, we'll see: https://github.com/khuck/xpress-apex/issues/81

**Comment by lee218llnl** [comment]
@adamjstewart I'm not sure if this is confirmation enough for you:

"Yes, I likely changed them. I’ll get around to updating the Spack package as soon as I can. Kevin"

It sounds like Kevin will be pushing new versions in there.

**Comment by lee218llnl** [comment]
More from khuck:

> Yes. I have it on my plate to update the TAU Spack module, too. The “versioning” of APEX is pretty sloppy, due to the fact that it is a research tool. I got a little ahead of myself on the numbering, so it’s somewhat meaningless. But the MD5 hash should be fixed, I agree. The LLVM OpenMP library that I have a Spack module for is an old fork of the true LLVM OpenMP runtime. The specification for OMPT is still evolving (as it is a draft standard under review), so we chose to freeze a version many moons ago. However, in October the specification will get a final vote from the OpenMP committee (to be part of the 5.0 standard), and the hope is that we can use the true LLVM OpenMP runtime that has OMPT hooks in it going forward, rather than the University of Oregon fork. Thanks - Kevin

**Comment by adamjstewart** [comment]
Good enough for me.

**Pull request merged**
