### PR TITLE
Add Boost 1.77.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by haampie** [comment]
`nvhpc-find_address.patch` and `context-macho-gcc.patch` still apply to 1.77, `nvhpc-1.76.patch` does not. What about

```
    conflicts('%gcc', when='@:1.76 +system platform=darwin')
```
I don't have a mac to test on

**Comment by msimberg** [comment]
> `nvhpc-find_address.patch` and `context-macho-gcc.patch` still apply to 1.77, `nvhpc-1.76.patch` does not. What about
> 
> ```
>     conflicts('%gcc', when='@:1.76 +system platform=darwin')
> ```
> 
> I don't have a mac to test on

No idea about the nvhpc patch, but the macho patch is meant to make compilation work on macOS exactly for those versions so I'm not sure why we should make it conflict. The 1.76 might have to be changed to 1.77 though, because as far as I can tell the patch is not in 1.77.

**Comment by hainest** [comment]
@msimberg 

> No idea about the nvhpc patch, but the macho patch is meant to make compilation work on macOS exactly for those versions so I'm not sure why we should make it conflict. The 1.76 might have to be changed to 1.77 though, because as far as I can tell the patch is not in 1.77.

[This](https://github.com/STEllAR-GROUP/hpx/issues/5442#issuecomment-880272305) comment on your HPX issue seems to suggest that it was fixed with boost@master back in July. Are you able to confirm/deny? I don't have a mac to test on.

**Comment by msimberg** [comment]
> [This](https://github.com/STEllAR-GROUP/hpx/issues/5442#issuecomment-880272305) comment on your HPX issue seems to suggest that it was fixed with boost@master back in July. Are you able to confirm/deny? I don't have a mac to test on.

Me neither. @eschnett or @albestro, would you be able to check if 1.77 works ok now with HPX without patches? I take back my statement about it not making it into 1.77. It does look like it's there: https://github.com/boostorg/context/blob/8f69d9d03c685e0ea6969699e00780bf330fab8d/build/Jamfile.v2#L649-L658.

**Comment by albestro** [comment]
I've just checked out this branch and built successfully `spack install hpx%gcc ^boost@1.77.0`.

EDIT:
I've just tried to do `spack install hpx%gcc ^boost@1.76.0` and it does not build HPX due to a problem that @msimberg already knows about, aka "boost::system::error_code vs std::error_code".

* **Spack:** 0.16.2-3962-4b286bda4b
* **Python:** 3.8.5
* **Platform:** darwin-mojave-skylake
* **Concretizer:** clingo

**Comment by msimberg** [comment]
Thanks @albestro! There are two separate issues with Boost, HPX, and GCC on macOS. The patch fixes one of them. The other one is slightly more complicated, so I'll open a separate PR for HPX to add a conflict with GCC and Boost < 1.77 on macOS.

**Review by haampie — APPROVED** [review]

**Comment by hainest** [comment]
@msimberg Since @albestro showed boost@1.77.0 is working on Darwin, I think we should update this PR to remove the conflict there.

**Comment by msimberg** [comment]
> @msimberg Since @albestro showed boost@1.77.0 is working on Darwin, I think we should update this PR to remove the conflict there.

Hmm, which conflict are we talking about exactly? There's currently a conflict up to 1.76 on `darwin` with `gcc` as the compiler: https://github.com/spack/spack/blob/4b286bda4b5c2d6a946d11b7074166cc63f02693/var/spack/repos/builtin/packages/boost/package.py#L208. Am I missing another one? The patch also only applies up to 1.76: https://github.com/spack/spack/blob/4b286bda4b5c2d6a946d11b7074166cc63f02693/var/spack/repos/builtin/packages/boost/package.py#L292.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
I'll be adding this new version. We can work on fixes to the current conflicts in a following PR.

**Comment by hainest** [comment]
@msimberg Ah, nevermind. I evidently can't read!

**Pull request merged**
