### PR TITLE
erlang: add v25.2

### PR DESCRIPTION
**Pull request by alecbcs**
Add Erlang v25.2.

**Changelog:**
https://github.com/erlang/otp/compare/OTP-23.2.7.5...OTP-24.3.4.9

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by alecbcs** [comment]
@tldahlgren you might have forgotten to enable auto-merge for this PR. (Please ignore this if that that was a conscious decision 😄.)

**Comment by tldahlgren** [comment]
> @tldahlgren you might have forgotten to enable auto-merge for this PR. (Please ignore this if that that was a conscious decision 😄.)

Thanks.  Was joining a meeting at the time.

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Pull request merged**
