### PR TITLE
ecflow: polish recipe

### PR DESCRIPTION
**Pull request by alalazo**
refers #34028

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@climbfuji This builds successfully for me on:

* **Spack:** 0.20.0.dev0 (e2dc0b3691c2025a228aeea0ba51a1c9ee0dda8f)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

Let me know if it works also in your case.

**Comment by alalazo** [comment]
@climbfuji Can you confirm this solves #34028?

**Review by climbfuji — APPROVED** [review]
Yes, that works for me. Thanks @alalazo

**Pull request merged**
