### PR TITLE
swig: add version 4.0.2 and 4.0.2-fortran

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Review by aprokop — APPROVED** [review]
Looks fine to me.

**Comment by aprokop** [comment]
I did not realize that `fortran` was already part of the package. I think making `fortran` a variant of the package would be clearer, especially if the plan is to keep versions in sync, but not going to push that.

**Comment by sethrj** [comment]
@aprokop To my knowledge, variants cannot change the URL or version for the software being downloaded, which is what we need here. (SWIG-fortran is a fork, not a configuration option, sadly.) I added the "fortran" version some time ago to enable its installation via spack.

**Comment by aprokop** [comment]
@sethrj If you could use it as a variant, would you do that? If yes, I wonder if any of the spack stages can be hijacked to substitute the link, or download it after.

**Comment by sethrj** [comment]
It seems that most "forks" or other different version distribution mechanisms  use `version` rather than `variant`, which is IMHO consistent with the variant <=> build option mapping.

**Pull request merged**
