### PR TITLE
Various FleCSI updates

### PR DESCRIPTION
**Pull request by rbberger**
* removes deprecated versions after latest Spack release
* propagate `+openmp` to kokkos and Legion
* add explicit conflict for `+hdf5` when using HPX backend
* remove `doc` variant for versions prior to `2.2`

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by tldahlgren** [comment]
Not sure why prechecks are failing.  Going to click `Update branch` to see if that resolves the problem.

**Comment by rbberger** [comment]
@tldahlgren sry, pushed one more small update to the spackage.

**Comment by rbberger** [comment]
@tldahlgren auto-merge got dismissed the other day when I pushed another small update [232bbab](https://github.com/spack/spack/pull/41068/commits/232bbab8406d6b8230237a2e544d86ddd54511b7). This should be ready to go.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
