### PR TITLE
zlib-ng: Fix build with NVHPC

### PR DESCRIPTION
**Pull request by skosukhin**
This makes it possible to install `zlib-ng` with `%nvhpc`. More or less similar to what we have in [`zlib`](https://github.com/spack/spack/blob/7440bb4c36fb2482b86abdf3bf90db6123cf9269/var/spack/repos/builtin/packages/zlib/package.py#L86-L121).

### CODE REVIEW

**Comment by haampie** [comment]
Can you fix it upstream?

**Comment by skosukhin** [comment]
If only it were a proper Autotools package :( I'll see what I can do.

**Comment by haampie** [comment]
They're open to contributions -- although maybe you have to push a bit for changes to their configure script since they focus on cmake. :crossed_fingers:

**Comment by skosukhin** [comment]
@haampie the only reason I care about the `autotools` builder here is that it's the default one. Do you know another way to resolve [this](https://github.com/spack/spack/blob/772928241b2e721724cbaa4a3a07a6ce0753c0e7/var/spack/repos/builtin/packages/zlib-ng/package.py#L42-L43)? I tried to add `conflicts("zlib-ng build_system=cmake")` to the `cmake` package but the conretizer preferred `zlib` over `zlib-ng build_system=autotools`.

I also think that I can make this PR more lightweight. I'll just make the configure script "think" that `nvhpc` is `gcc`.

**Comment by skosukhin** [comment]
@haampie how about now?

**Review by eugeneswalker — DISMISSED** [review]

**Review by bernhardkaindl — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
@skosukhin wrote:
> This makes it possible to install zlib-ng with %nvhpc. More or less similar to what we have in zlib.

Reviewed again: 5 days passed since the last changes and except for optionally enabling tests (if requested for this build), the changes are specific to %nvhpc. AFAICS, it should be clear to merge.

**Pull request merged**
