### PR TITLE
Revert change that broke py-scipy

### PR DESCRIPTION
**Pull request by citibeth**
@davydden  A recent change broke py-scipy:
https://github.com/LLNL/spack/commit/1e10309ff707a29fe91993d9a9b408182ffa77f1

This PR reverts (part of) that change by re-instating the symlinks to `libblas.so` and `liblapack.so`.

In hind sight... it looks like @davydden grepped for ``depends_on('blas')`` and ``depends_on('lapack')`` in making that change... and made sure that all those places worked.  ``py-scipy`` did not contain those ``depends_on()`` declarations, so no surprise it was missed (dependency is implict through ``py-numpy``).

This seemed wrong, and is likely why it was missed by @davydden.  I added ``depends_on('blas')`` and ``depends_on('lapack')``, although that change in and of itself does not fix the build (env['BLAS'], etc. were previously being set properly even without the ``depends_on()`` statments).

It's curious that ``py-numpy`` builds just fine but ``py-scipy`` seems to need the symlinks to ``libblas.so`` and ``liblapack.so``.  :shrug:

### CODE REVIEW

**Comment by tgamblin** [comment]
@alalazo @davydden

**Comment by davydden** [comment]
i will see if i can fix it without adding back symlinks as this is not really a solution and won't work for `mkl` and `atlas`.

**Comment by davydden** [comment]
let's not merge it as is. Most likely one needs to provide extra options to `py-scipy` to specify what blas/lapack is.

**Comment by citibeth** [comment]
> let's not merge it as is.

...except that anyone who tries to build ``py-scipy`` will fail.  I think
it's better to merge as-is (since that restores a previous status quo that
worked), and then work on a better solution.

**Comment by tgamblin** [comment]
I'd rather move to the new and much more robust lapack/blas handling scheme that @alalazo and @davydden came up with and would like to see the effort there.  Their scheme handles cases that the users care about on cray and other platforms -- if @davydden can't come up with a fix today we can revert, but I suspect there is a simpler way to do this.

**Comment by citibeth** [comment]
I saw the new scheme in the Git history, and I agree there's a lot good
about it.  Just to be clear... this PR doesn't revert their work.  It just
adds back one section of code that they'd removed, in the hopes that it was
no longer needed.

**Comment by davydden** [comment]
I will look at it within the next few hours. If i won't find a solution, i'll post here. Otherwise i will create a PR with a fix.

**Comment by davydden** [comment]
know wha to fix, PR incoming...

**Comment by citibeth** [comment]
Awesome! :-)

**Comment by davydden** [comment]
superseeded by https://github.com/LLNL/spack/pull/1949

@citibeth please, see if that PR fixes the issue for you.

**Comment by citibeth** [comment]
Please do not close again without consensus.

**Pull request closed without merging**
