### PR TITLE
e4s ci: restore power builds

### PR DESCRIPTION
**Pull request by eugeneswalker**
FYI @wspear 

Not expecting everything to build out of the gate. Will commit to this PR until the whole stack builds.

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
I don't see the pipeline being generated :thinking:

**Comment by eugeneswalker** [comment]
> I don't see the pipeline being generated 🤔

oops, good catch. i must’ve missed something, will update PR w fix.

**Comment by eugeneswalker** [comment]
Having issues with our two power8 nodes -- I've disabled those temporarily. Let us see if that does it!

@spackbot run pipeline

**Comment by eugeneswalker** [comment]
The pipeline has passed but GitHub is not picking up on that. @zackgalbreath Can you help us with this?

**Review by wspear — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
Had to rebase on develop to pick up some changes to the CI/GitHub Action checks -- all checks passing now @wspear !

**Review by wspear — APPROVED** [review]

**Pull request merged**
