### PR TITLE
pkgconf: add v1.9.5

### PR DESCRIPTION
**Pull request by alecbcs**
Add pkgconf v1.9.5. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
This seems a legitimate build error to be investigated:[^1]

Screenshot from 2023-03-27 09-49-34

[^1]: per our Friday discussion, I think this one is categorized as `SpackError` so we probably need to refine that category

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256 and able to build successfully.

**Comment by haampie** [comment]
Bisected this and created an issue upstream:

https://github.com/pkgconf/pkgconf/issues/293

**Review by haampie — APPROVED** [review]

**Pull request merged**
