### PR TITLE
New package: MDSplus

### PR DESCRIPTION
**Pull request by wmvanvliet**
MDSplus is a set of software tools for data acquisition and storage and a methodology for management of complex scientific data.

https://www.mdsplus.org

The fusion group of our university uses this software for their data management.

### CODE REVIEW

**Comment by alalazo** [comment]
Duplicate of #21897

**Comment by wmvanvliet** [comment]
Code coverage is complaining. Is there a way to add a test for this package?

**Comment by alalazo** [comment]
@wmvanvliet Don't bother with coverage. If you rebase and push it should go away. We reworked CI for PRs that do only changes to packages and now it should be much faster.

**Comment by wmvanvliet** [comment]
all green now!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
