### PR TITLE
cray fixes through 01/12/2021

### PR DESCRIPTION
**Pull request by gwagenbreth**
fixes for rzwhamo cray environment, including @becker33 fixes for numpy libsci and mpi libraries

### CODE REVIEW

**Comment by mwkrentel** [comment]
Why are you changing the sha256sums for several packages?
Some of these I object to.

Are you working off an old rev of spack or something?

Ok, I see.  The conflicts indicate that you do have an old rev of spack.

You should rebase your changes onto a current rev of spack.
That should eliminate the conflicts and produce a smaller, more focused diff.

**Comment by gwagenbreth** [comment]
I made some changes to packages by putting a modified tar file in a mirror.
I need to go back and do a patch instead. You probably do not want the modified
package files at this time.

Sorry, I wanted to make sure that patches made by Greg Becker to spack python sources got pushed/saved. I will
be adding more modifications as I clean up.

Gene W

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by gwagenbreth** [comment]
Will do. It will be a few days as there are other problems I am resolving.

**Comment by alalazo** [comment]
Closing since the PR seems stale

**Pull request closed without merging**
