### PR TITLE
qt-tools: new package

### PR DESCRIPTION
**Pull request by wdconinc**
This PR adds the Qt Tools module, since used by paraview.

Cherry-picked from #45300.

### CODE REVIEW

**Review by bernhardkaindl — COMMENTED** [review]
@wdconinc When I tried to build it, it somehow appears to have found the clang-14 of Ubuntu 22.04:
```py
-- The CXX compiler identification is GNU 11.4.0
-- The C compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/t_bernhardk/spack.5/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/t_bernhardk/spack.5/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
CMake Error at /usr/lib/llvm-14/lib/cmake/clang/ClangTargets.cmake:750 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/llvm-14/lib/libclangBasic.a"
```
I then ran `sudo apt-get install libclang-14-dev libclang-cpp14-dev libclang-common-14-dev` to install this file as well.

Then, and also after I ran `sudo apt remove $(dpkg -l |grep clang |cut -d' ' -f3)`, the configure ends in this error:

```py
-- Found WrapAtomic: TRUE
CMake Error at src/assistant/CMakeLists.txt:31 (add_subdirectory):
  add_subdirectory given source "qlitehtml/src" which is not an existing
  directory.


CMake Error at src/assistant/CMakeLists.txt:52 (message):
  qlitehtml not found.  Did you run git submodule update --init --recursive?
```
So it looks like you need to include `qlitehtml` to the build:

https://github.com/qt/qttools/blob/dev/.gitmodules
```js
[submodule "src/assistant/qlitehtml"]
	path = src/assistant/qlitehtml
	url = https://code.qt.io/playground/qlitehtml.git
```

- https://doc.qt.io/qt-6/qtassistant-attribution-litehtml.html
- https://github.com/litehtml/litehtml

**Review by bernhardkaindl — COMMENTED** [review]
@wdconinc The error on missing the `qlitehtml` also didn't go away after rebasing this to the new `develop` branch with your `qt-base` update merged. So it looks like you have to fix the missing submodule.

**Comment by wdconinc** [comment]
Test build (yeah, with 6.8.0):
```
==> Installing qt-tools-6.8.0-t336nu5wbe6f6mr3xnvbsixszu6xlxqa [93/93]
==> No binary for qt-tools-6.8.0-t336nu5wbe6f6mr3xnvbsixszu6xlxqa found: installing from source
==> No patches needed for qt-tools
==> qt-tools: Executing phase: 'cmake'
==> qt-tools: Executing phase: 'build'
==> qt-tools: Executing phase: 'install'
==> qt-tools: Successfully installed qt-tools-6.8.0-t336nu5wbe6f6mr3xnvbsixszu6xlxqa
  Stage: 0.00s.  Cmake: 2.94s.  Build: 8m 13.88s.  Install: 0.30s.  Post-install: 0.45s.  Total: 8m 18.00s
[+] /opt/software/linux-ubuntu24.10-skylake/gcc-14.2.0/qt-tools-6.8.0-t336nu5wbe6f6mr3xnvbsixszu6xlxqa
```

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
<details><summary>Hello @wdconinc! I encountered an install failure of qt-tools+assistant@=6.7.3. Could you check it?</summary><br>

Hello @wdconinc,

I am terribly sorry, but my attempt on the installation of `qt-tools+assistant@=6.7.3` failed in an automated build.

 But I've got a detailed report for you that may allow you to fix it based on the knowledge that you have about these recipes.



This command failed: `bin/spack install -v --fail-fast qt-tools+assistant@=6.7.3`
<details><summary>Click here to drill down to the logs from building the failed spec: qt-tools+assistant@=6.7.3</summary>

### `qt-tools+assistant@=6.7.3`:
<details><summary><b>Click here to expand the full build log</b> for qt-tools+assistant@=6.7.3</summary>

```py
==> qt-tools: Executing phase: 'cmake'
==> [2024-11-13-01:28:57.671973] '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/cmake-3.30.5-r354rtgocnne6niww4ax2gvpn2ozc4xd/bin/cmake' '-G' 'Ninja'
-- The CXX compiler identification is GNU 13.1.0
-- The C compiler identification is GNU 13.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: $PWD/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: $PWD/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.2-g2hflqvg43mwsr6mteejxlgy7v4lbj3b/lib/cmake/Qt6/Qt6ConfigVersion.cmake:56 (message):
  Version 6.7.3 of package Qt6 was requested but an incompatible version was
  found: 6.7.2.  You can pass -DQT_NO_PACKAGE_VERSION_CHECK=TRUE to disable
  the version check and force the incompatible version to be used.  There is
  no guarantee the build will succeed.  Use at your own risk.  You can
  silence this warning by passing
  -DQT_NO_PACKAGE_VERSION_INCOMPATIBLE_WARNING=TRUE
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a configuration file for package "Qt6" that is compatible
  with requested version "6.7.3".
  The following configuration files were considered but not accepted:
    $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.2-g2hflqvg43mwsr6mteejxlgy7v4lbj3b/lib/cmake/Qt6/Qt6Config.cmake, version: 6.7.2
-- Configuring incomplete, errors occurred!

```
</details>

```py
-- Configuring incomplete, errors occurred!
==> Error: ProcessError: Command exited with status 1:
    opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/cmake-3.30.5-r354rtgocnne6niww4ax2gvpn2ozc4xd/bin/cmake -G Ninja -DPython3_EXECUTABLE:STRING=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/python-3.11.9-gavdfv2fdlnfn222ysg5a727nqdfcarx/bin/python3.11

     25    
  >> 26    CMake Error at CMakeLists.txt:21 (find_package):
     27      Could not find a configuration file for package "Qt6" that is compatible
     28      with requested version "6.7.3".
```

</details>



<details><summary>Click here to expand the output of: "spack spec {spec}"</summary>

```yaml
Input spec
--------------------------------
 -   qt-tools@6.7.3+assistant

Concretized
--------------------------------
 -   qt-tools@6.7.3%gcc@13.1.0+assistant~designer~ipo
[+]      ^cmake@3.30.5%gcc@13.1.0~doc+ncurses+ownlibs~qtgui patches=dbc3892
[+]          ^curl@8.10.1%gcc@13.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl
[+]              ^nghttp2@1.63.0%gcc@13.1.0
[+]          ^gmake@4.4.1%gcc@13.1.0~guile
[+]          ^ncurses@6.5%gcc@13.1.0~symlinks+termlib abi=none patches=7a351bc
[+]          ^zlib-ng@2.2.1%gcc@13.1.0+compat+new_strategies+opt+pic+shared
[+]      ^gcc-runtime@13.1.0%gcc@13.1.0
[e]      ^glibc@2.35%gcc@13.1.0
[+]      ^llvm@18.1.8%gcc@13.1.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd compiler-rt=runtime libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=all version_suffix=none
[+]          ^binutils@2.42%gcc@13.1.0~gas+gold~gprofng+headers~interwork+ld~libiberty~lto~nls~pgo+plugins compress_debug_sections=zlib libs=shared,static
[+]              ^diffutils@3.10%gcc@13.1.0
[+]          ^hwloc@2.11.1%gcc@13.1.0~cairo~cuda~gl~libudev+libxml2~nvml~oneapi-level-zero~opencl+pci~rocm libs=shared,static
[+]              ^libpciaccess@0.17%gcc@13.1.0
[+]          ^libedit@3.1-20240808%gcc@13.1.0
[+]          ^libffi@3.4.6%gcc@13.1.0
[+]          ^libxml2@2.10.3%gcc@13.1.0+pic~python+shared
[+]              ^libiconv@1.17%gcc@13.1.0 libs=shared,static
[+]          ^lua@5.3.6%gcc@13.1.0~pcfile+shared fetcher=curl
[+]              ^unzip@6.0%gcc@13.1.0 patches=f6f6236
[+]          ^perl-data-dumper@2.173%gcc@13.1.0
[+]              ^perl@5.40.0%gcc@13.1.0+cpanm+opcode+open+shared+threads
[+]                  ^berkeley-db@18.1.40%gcc@13.1.0+cxx~docs+stl patches=26090f4,b231fcc
[+]          ^swig@4.1.1%gcc@13.1.0
[+]          ^xz@5.4.6%gcc@13.1.0~pic libs=shared,static
[+]      ^ninja@1.12.0%gcc@13.1.0+re2c
[+]          ^re2c@3.0%gcc@13.1.0
[+]      ^pkgconf@2.2.0%gcc@13.1.0
[+]      ^python@3.11.9%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib patches=13fa8bf,b0615b2,ebdca64,f2fd060
[+]          ^bzip2@1.0.8%gcc@13.1.0~debug~pic+shared
[+]          ^expat@2.6.3%gcc@13.1.0+libbsd
[+]              ^libbsd@0.12.2%gcc@13.1.0
[+]                  ^libmd@1.0.4%gcc@13.1.0
[+]          ^gdbm@1.23%gcc@13.1.0
[+]          ^gettext@0.22.5%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz
[+]              ^tar@1.34%gcc@13.1.0 zip=pigz
[+]                  ^pigz@2.8%gcc@13.1.0
[+]          ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api patches=4885da3
[+]          ^openssl@3.3.1%gcc@13.1.0~docs+shared certs=mozilla
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0
[+]          ^readline@8.2%gcc@13.1.0 patches=bbf97f1
[+]          ^sqlite@3.46.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree
[+]          ^util-linux-uuid@2.40.2%gcc@13.1.0
[+]      ^qt-base@6.7.2%gcc@13.1.0~accessibility~dbus~framework~gtk+gui~ipo+network~opengl+shared+sql+widgets
[+]          ^double-conversion@3.3.0%gcc@13.1.0~ipo
[+]          ^fontconfig@2.15.0%gcc@13.1.0~pic
[+]              ^font-util@1.4.1%gcc@13.1.0 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1
[+]                  ^autoconf@2.72%gcc@13.1.0
[+]                  ^automake@1.16.5%gcc@13.1.0
[+]                  ^bdftopcf@1.1%gcc@13.1.0
[+]                      ^fontsproto@2.1.3%gcc@13.1.0
[+]                      ^libxfont@1.5.4%gcc@13.1.0
[+]                  ^mkfontdir@1.0.7%gcc@13.1.0
[+]                  ^mkfontscale@1.2.3%gcc@13.1.0
[+]                      ^libfontenc@1.1.8%gcc@13.1.0
[+]              ^gperf@3.1%gcc@13.1.0 patches=3dd36db
[+]          ^freetype@2.13.2%gcc@13.1.0+pic+shared
[+]          ^harfbuzz@9.0.0%gcc@13.1.0~graphite2~strip buildtype=release default_library=shared
[+]              ^cairo@1.16.0%gcc@13.1.0~X~fc+ft+gobject+pdf+pic~png+shared~svg patches=7097196,7c4da77
[+]                  ^libtool@2.4.7%gcc@13.1.0
[+]                      ^findutils@4.9.0%gcc@13.1.0 patches=440b954
[+]                  ^pixman@0.42.2%gcc@13.1.0+shared
[+]                  ^which@2.21%gcc@13.1.0
[+]              ^glib@2.78.3%gcc@13.1.0~libmount~strip buildtype=release default_library=shared tracing=none
[+]                  ^elfutils@0.191%gcc@13.1.0~debuginfod+exeprefix+nls
[+]              ^gobject-introspection@1.78.1%gcc@13.1.0~strip buildtype=release default_library=shared
[+]                  ^flex@2.6.3%gcc@13.1.0+lex~nls
[+]              ^meson@1.5.1%gcc@13.1.0_pip patches=0f0b1bd
[+]                  ^py-pip@23.1.2%gcc@13.1.0
[+]                  ^py-setuptools@69.2.0%gcc@13.1.0
[+]                  ^py-wheel@0.41.2%gcc@13.1.0
[+]                  ^python-venv@1.0%gcc@13.1.0
[+]          ^icu4c@74.2%gcc@13.1.0 cxxstd=11
[+]          ^libdrm@2.4.120%gcc@13.1.0~docs
[+]              ^libpthread-stubs@0.5%gcc@13.1.0
[+]          ^libjpeg-turbo@3.0.3%gcc@13.1.0~ipo~jpeg8~partial_decoder+pic libs=shared,static
[+]              ^nasm@2.15.05%gcc@13.1.0
[+]          ^libpng@1.6.39%gcc@13.1.0~ipo~pic libs=shared,static
[+]          ^libproxy@0.4.17%gcc@13.1.0~ipo~perl~python
[+]          ^libx11@1.8.9%gcc@13.1.0
[+]              ^inputproto@2.3.2%gcc@13.1.0
[+]              ^kbproto@1.0.7%gcc@13.1.0
[+]              ^util-macros@1.20.1%gcc@13.1.0
[+]              ^xextproto@7.3.0%gcc@13.1.0
[+]              ^xproto@7.0.31%gcc@13.1.0
[+]              ^xtrans@1.5.0%gcc@13.1.0
[+]          ^libxcb@1.17.0%gcc@13.1.0
[+]              ^libxau@1.0.11%gcc@13.1.0
[+]              ^libxdmcp@1.1.5%gcc@13.1.0
[+]              ^xcb-proto@1.17.0%gcc@13.1.0
[+]          ^libxkbcommon@1.7.0%gcc@13.1.0~strip~wayland buildtype=release default_library=shared
[+]              ^bison@3.8.2%gcc@13.1.0~color
[+]              ^xkbdata@1.0.1%gcc@13.1.0
[+]                  ^xkbcomp@1.4.7%gcc@13.1.0
[+]                      ^libxkbfile@1.1.3%gcc@13.1.0
[+]          ^libxrender@0.9.11%gcc@13.1.0
[+]              ^renderproto@0.11.1%gcc@13.1.0
[+]          ^pcre2@10.43%gcc@13.1.0~jit+multibyte
[+]          ^xcb-util@0.4.1%gcc@13.1.0
[+]          ^xcb-util-cursor@0.1.4%gcc@13.1.0
[+]              ^m4@1.4.19%gcc@13.1.0+sigsegv patches=9dc5fbd,bfdffa7
[+]                  ^libsigsegv@2.14%gcc@13.1.0
[+]          ^xcb-util-image@0.4.1%gcc@13.1.0
[+]          ^xcb-util-keysyms@0.4.1%gcc@13.1.0
[+]          ^xcb-util-renderutil@0.3.10%gcc@13.1.0
[+]          ^xcb-util-wm@0.4.2%gcc@13.1.0
[+]          ^zstd@1.5.6%gcc@13.1.0+programs compression=none libs=shared,static


```

</details>


</details>

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
<details><summary>Hello @wdconinc! I encountered an install failure of qt-tools+designer@=6.7.3. Could you check it?</summary><br>

Hello @wdconinc,

I am terribly sorry, but my attempt on the installation of `qt-tools+designer@=6.7.3` failed in an automated build.

 But I've got a detailed report for you that may allow you to fix it based on the knowledge that you have about these recipes.



This command failed: `bin/spack install -v --fail-fast qt-tools+designer@=6.7.3`
<details><summary>Click here to drill down to the logs from building the failed spec: qt-tools+designer@=6.7.3</summary>

### `qt-tools+designer@=6.7.3`:
<details><summary><b>Click here to expand the full build log</b> for qt-tools+designer@=6.7.3</summary>

```py
==> qt-tools: Executing phase: 'cmake'
==> [2024-11-13-02:00:17.367400] '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/cmake-3.30.5-r354rtgocnne6niww4ax2gvpn2ozc4xd/bin/cmake' '-G' 'Ninja'
-- The CXX compiler identification is GNU 13.1.0
-- The C compiler identification is GNU 13.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: $PWD/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: $PWD/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.2-g2hflqvg43mwsr6mteejxlgy7v4lbj3b/lib/cmake/Qt6/Qt6ConfigVersion.cmake:56 (message):
  Version 6.7.3 of package Qt6 was requested but an incompatible version was
  found: 6.7.2.  You can pass -DQT_NO_PACKAGE_VERSION_CHECK=TRUE to disable
  the version check and force the incompatible version to be used.  There is
  no guarantee the build will succeed.  Use at your own risk.  You can
  silence this warning by passing
  -DQT_NO_PACKAGE_VERSION_INCOMPATIBLE_WARNING=TRUE
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a configuration file for package "Qt6" that is compatible
  with requested version "6.7.3".
  The following configuration files were considered but not accepted:
    $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.2-g2hflqvg43mwsr6mteejxlgy7v4lbj3b/lib/cmake/Qt6/Qt6Config.cmake, version: 6.7.2
-- Configuring incomplete, errors occurred!

```
</details>

```py
-- Configuring incomplete, errors occurred!
==> Error: ProcessError: Command exited with status 1:
    opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/cmake-3.30.5-r354rtgocnne6niww4ax2gvpn2ozc4xd/bin/cmake -G Ninja -DPython3_EXECUTABLE:STRING=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/python-3.11.9-gavdfv2fdlnfn222ysg5a727nqdfcarx/bin/python3.11

     25    
  >> 26    CMake Error at CMakeLists.txt:21 (find_package):
     27      Could not find a configuration file for package "Qt6" that is compatible
     28      with requested version "6.7.3".
```

</details>



<details><summary>Click here to expand the output of: "spack spec qt-tools+designer@=6.7.3"</summary>

```yaml
Input spec
--------------------------------
 -   qt-tools@6.7.3+designer

Concretized
--------------------------------
 -   qt-tools@6.7.3%gcc@13.1.0~assistant+designer~ipo
[+]      ^cmake@3.30.5%gcc@13.1.0~doc+ncurses+ownlibs~qtgui patches=dbc3892
[+]          ^curl@8.10.1%gcc@13.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl
[+]              ^nghttp2@1.63.0%gcc@13.1.0
[+]          ^gmake@4.4.1%gcc@13.1.0~guile
[+]          ^ncurses@6.5%gcc@13.1.0~symlinks+termlib abi=none patches=7a351bc
[+]          ^zlib-ng@2.2.1%gcc@13.1.0+compat+new_strategies+opt+pic+shared
[+]      ^gcc-runtime@13.1.0%gcc@13.1.0
[e]      ^glibc@2.35%gcc@13.1.0
[+]      ^llvm@18.1.8%gcc@13.1.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd compiler-rt=runtime libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=all version_suffix=none
[+]          ^binutils@2.42%gcc@13.1.0~gas+gold~gprofng+headers~interwork+ld~libiberty~lto~nls~pgo+plugins compress_debug_sections=zlib libs=shared,static
[+]              ^diffutils@3.10%gcc@13.1.0
[+]          ^hwloc@2.11.1%gcc@13.1.0~cairo~cuda~gl~libudev+libxml2~nvml~oneapi-level-zero~opencl+pci~rocm libs=shared,static
[+]              ^libpciaccess@0.17%gcc@13.1.0
[+]          ^libedit@3.1-20240808%gcc@13.1.0
[+]          ^libffi@3.4.6%gcc@13.1.0
[+]          ^libxml2@2.10.3%gcc@13.1.0+pic~python+shared
[+]              ^libiconv@1.17%gcc@13.1.0 libs=shared,static
[+]          ^lua@5.3.6%gcc@13.1.0~pcfile+shared fetcher=curl
[+]              ^unzip@6.0%gcc@13.1.0 patches=f6f6236
[+]          ^perl-data-dumper@2.173%gcc@13.1.0
[+]              ^perl@5.40.0%gcc@13.1.0+cpanm+opcode+open+shared+threads
[+]                  ^berkeley-db@18.1.40%gcc@13.1.0+cxx~docs+stl patches=26090f4,b231fcc
[+]          ^swig@4.1.1%gcc@13.1.0
[+]          ^xz@5.4.6%gcc@13.1.0~pic libs=shared,static
[+]      ^ninja@1.12.0%gcc@13.1.0+re2c
[+]          ^re2c@3.0%gcc@13.1.0
[+]      ^pkgconf@2.2.0%gcc@13.1.0
[+]      ^python@3.11.9%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib patches=13fa8bf,b0615b2,ebdca64,f2fd060
[+]          ^bzip2@1.0.8%gcc@13.1.0~debug~pic+shared
[+]          ^expat@2.6.3%gcc@13.1.0+libbsd
[+]              ^libbsd@0.12.2%gcc@13.1.0
[+]                  ^libmd@1.0.4%gcc@13.1.0
[+]          ^gdbm@1.23%gcc@13.1.0
[+]          ^gettext@0.22.5%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz
[+]              ^tar@1.34%gcc@13.1.0 zip=pigz
[+]                  ^pigz@2.8%gcc@13.1.0
[+]          ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api patches=4885da3
[+]          ^openssl@3.3.1%gcc@13.1.0~docs+shared certs=mozilla
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0
[+]          ^readline@8.2%gcc@13.1.0 patches=bbf97f1
[+]          ^sqlite@3.46.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree
[+]          ^util-linux-uuid@2.40.2%gcc@13.1.0
[+]      ^qt-base@6.7.2%gcc@13.1.0~accessibility~dbus~framework~gtk+gui~ipo+network~opengl+shared+sql+widgets
[+]          ^double-conversion@3.3.0%gcc@13.1.0~ipo
[+]          ^fontconfig@2.15.0%gcc@13.1.0~pic
[+]              ^font-util@1.4.1%gcc@13.1.0 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1
[+]                  ^autoconf@2.72%gcc@13.1.0
[+]                  ^automake@1.16.5%gcc@13.1.0
[+]                  ^bdftopcf@1.1%gcc@13.1.0
[+]                      ^fontsproto@2.1.3%gcc@13.1.0
[+]                      ^libxfont@1.5.4%gcc@13.1.0
[+]                  ^mkfontdir@1.0.7%gcc@13.1.0
[+]                  ^mkfontscale@1.2.3%gcc@13.1.0
[+]                      ^libfontenc@1.1.8%gcc@13.1.0
[+]              ^gperf@3.1%gcc@13.1.0 patches=3dd36db
[+]          ^freetype@2.13.2%gcc@13.1.0+pic+shared
[+]          ^harfbuzz@9.0.0%gcc@13.1.0~graphite2~strip buildtype=release default_library=shared
[+]              ^cairo@1.16.0%gcc@13.1.0~X~fc+ft+gobject+pdf+pic~png+shared~svg patches=7097196,7c4da77
[+]                  ^libtool@2.4.7%gcc@13.1.0
[+]                      ^findutils@4.9.0%gcc@13.1.0 patches=440b954
[+]                  ^pixman@0.42.2%gcc@13.1.0+shared
[+]                  ^which@2.21%gcc@13.1.0
[+]              ^glib@2.78.3%gcc@13.1.0~libmount~strip buildtype=release default_library=shared tracing=none
[+]                  ^elfutils@0.191%gcc@13.1.0~debuginfod+exeprefix+nls
[+]              ^gobject-introspection@1.78.1%gcc@13.1.0~strip buildtype=release default_library=shared
[+]                  ^flex@2.6.3%gcc@13.1.0+lex~nls
[+]              ^meson@1.5.1%gcc@13.1.0_pip patches=0f0b1bd
[+]                  ^py-pip@23.1.2%gcc@13.1.0
[+]                  ^py-setuptools@69.2.0%gcc@13.1.0
[+]                  ^py-wheel@0.41.2%gcc@13.1.0
[+]                  ^python-venv@1.0%gcc@13.1.0
[+]          ^icu4c@74.2%gcc@13.1.0 cxxstd=11
[+]          ^libdrm@2.4.120%gcc@13.1.0~docs
[+]              ^libpthread-stubs@0.5%gcc@13.1.0
[+]          ^libjpeg-turbo@3.0.3%gcc@13.1.0~ipo~jpeg8~partial_decoder+pic libs=shared,static
[+]              ^nasm@2.15.05%gcc@13.1.0
[+]          ^libpng@1.6.39%gcc@13.1.0~ipo~pic libs=shared,static
[+]          ^libproxy@0.4.17%gcc@13.1.0~ipo~perl~python
[+]          ^libx11@1.8.9%gcc@13.1.0
[+]              ^inputproto@2.3.2%gcc@13.1.0
[+]              ^kbproto@1.0.7%gcc@13.1.0
[+]              ^util-macros@1.20.1%gcc@13.1.0
[+]              ^xextproto@7.3.0%gcc@13.1.0
[+]              ^xproto@7.0.31%gcc@13.1.0
[+]              ^xtrans@1.5.0%gcc@13.1.0
[+]          ^libxcb@1.17.0%gcc@13.1.0
[+]              ^libxau@1.0.11%gcc@13.1.0
[+]              ^libxdmcp@1.1.5%gcc@13.1.0
[+]              ^xcb-proto@1.17.0%gcc@13.1.0
[+]          ^libxkbcommon@1.7.0%gcc@13.1.0~strip~wayland buildtype=release default_library=shared
[+]              ^bison@3.8.2%gcc@13.1.0~color
[+]              ^xkbdata@1.0.1%gcc@13.1.0
[+]                  ^xkbcomp@1.4.7%gcc@13.1.0
[+]                      ^libxkbfile@1.1.3%gcc@13.1.0
[+]          ^libxrender@0.9.11%gcc@13.1.0
[+]              ^renderproto@0.11.1%gcc@13.1.0
[+]          ^pcre2@10.43%gcc@13.1.0~jit+multibyte
[+]          ^xcb-util@0.4.1%gcc@13.1.0
[+]          ^xcb-util-cursor@0.1.4%gcc@13.1.0
[+]              ^m4@1.4.19%gcc@13.1.0+sigsegv patches=9dc5fbd,bfdffa7
[+]                  ^libsigsegv@2.14%gcc@13.1.0
[+]          ^xcb-util-image@0.4.1%gcc@13.1.0
[+]          ^xcb-util-keysyms@0.4.1%gcc@13.1.0
[+]          ^xcb-util-renderutil@0.3.10%gcc@13.1.0
[+]          ^xcb-util-wm@0.4.2%gcc@13.1.0
[+]          ^zstd@1.5.6%gcc@13.1.0+programs compression=none libs=shared,static


```

</details>


</details>

**Review by bernhardkaindl — APPROVED** [review]
@wdconinc: The variants of `qt-tools@6.7.2` built successfully.

If I add
```py
version("6.8.0", commit="13dbc0cb7a2eabb27d99ae0ac00d38af1aa03d9c", submodules=True)
```
then I get this error:
```py
1 error found in build log:
     20      silence this warning by passing
     21      -DQT_NO_PACKAGE_VERSION_INCOMPATIBLE_WARNING=TRUE
     22    Call Stack (most recent call first):
     23      CMakeLists.txt:21 (find_package)
     24
     25
  >> 26    CMake Error at CMakeLists.txt:21 (find_package):
     27      Could not find a configuration file for package "Qt6" that is compatible
     28      with requested version "6.9.0".
     29
     30      The following configuration files were considered but not accepted:
     31
     32        opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/qt-base-6.7.2-g2hflqvg43mwsr6mteejxlgy7v4lbj3b/lib/cmake/Qt6
           /Qt6Config.cmake, version: 6.7.2
```

**Comment by wdconinc** [comment]
@bernhardkaindl Rebased so the `qt-tools@6.7.3` has a `qt-base@6.7.3` version to depend on. Before rebase the most recent was `qt-base@6.7.2`. Let me know if you want to retry the builds, or happy to consider approved and ready to merge.

**Review by bernhardkaindl — APPROVED** [review]
@wdconic: Thanks, no problem: Knowing that it is fine is of course enough for me.

Especially because it's a new package, there is no regression even if there would be some issue.

Therefore, I gave the approval and renew it as well.

**Pull request merged**
