### PR TITLE
py-numpy: add v1.23.4

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Review by rgommers — DISMISSED** [review]
LGTM. The CI errors don't look related to me. Although output is cut off in some cases, so it's not possible to tell what goes wrong.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Pull request merged**
