### PR TITLE
py-pythran: customize headers attribute

### LINKED ISSUE #33237: linux: environment variable values grow beyond `MAX_ARG_STRLEN`, making exec fail
Currently `py-scipy` fails to build in gitlab ci, due the following:

- `py-pythran` generates 256 include dirs, which are set as a colon-seperated string in the `SPACK_INCLUDE_DIRS` environment variable;
- due to install path padding each path is at least 512 bytes in size

This results in a string of at least 128KB, which is at least `MAX_ARG_STRLEN = 32 * PAGE_SIZE = 32 * 4KB = 128KB`.

And this makes exec syscalls fail, since they have a limit on the argument length (env variables are just arguments after argv):

https://github.com/torvalds/linux/blob/49da070062390094112b423ba443ea193527b2e4/fs/exec.c#L291-L294

https://github.com/torvalds/linux/blob/49da070062390094112b423ba443ea193527b2e4/fs/exec.c#L535-L541

resulting in `E2BIG` or `Argument list too long`, which is the build error we see.

### PR DESCRIPTION
**Pull request by alalazo**
Fixes `py-scipy` build in gitlab (see #33237 for details)

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
I've updated the description so that we don't close #33237, since this issue of long strings in env variables can pop up in general

**Review by haampie — DISMISSED** [review]

**Review by adamjstewart — DISMISSED** [review]

**Review by haampie — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Comment by haampie** [comment]
uh, similar issues in ci?

**Comment by adamjstewart** [comment]
That `py-torch-geometric` test really doesn't want to finish. Do we wait for the 6 hr timeout or boot it?

**Comment by alalazo** [comment]
We need to do something to speed-up relocation. 3hrs to relocate binaries is a bit too much

**Comment by haampie** [comment]
@alalazo it's your lucky day: #33248 (assuming you meant that installing dependencies is slow)

**Pull request merged**
