### PR TITLE
`nccl-tests`: add version v2.13.6

### PR DESCRIPTION
**Pull request by thomas-bouvier**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
@aweits Did you want to comment on this PR since you are the original contributor?

**Comment by thomas-bouvier** [comment]
I think this can be merged safely as the dependencies don't change wit that release :)

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
