### PR TITLE
added GFDL FMS package

### PR DESCRIPTION
**Pull request by edwardhartnett**
added GFDL FMS package

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by edwardhartnett** [comment]
Looks like a timeout problem...

**Comment by alalazo** [comment]
@edwardhartnett Just restarted the pipeline, thanks!

**Pull request merged**
