### PR TITLE
Add checksum for gmp 6.2.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by scheibelp** [comment]
@spackbot run pipeline

**Review by adamjstewart — DISMISSED** [review]

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@adamjstewart can this be merged?

**Comment by scheibelp** [comment]
@spackbot run pipeline

(I think there was an issue with the pipelines that has since been resolved)

**Comment by alalazo** [comment]
There need to be a change in the PR branch to trigger a new pipeline run on a different merge commit :cry:  Can you please rebase?

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
