### PR TITLE
lmod : added support for the creation of hierarchical lua module files

### PR DESCRIPTION
**Pull request by alalazo**
Includes :
- treatment of a generic hierarchy (i.e. lapack + mpi + compiler)
- possibility to specify which compilers are to be considered Core
- correct treatment of the 'family' directive
- unit tests for most new features

### CODE REVIEW

**Comment by alalazo** [comment]
#107 seems to have problem triggering travis, trying to open a new PR.

**Comment by alalazo** [comment]
@tgamblin @becker33 @mathstuf @glennpj @adamjstewart @citibeth  In a couple of days it will be the first birthday of #107 ... are we still interested in this PR ?

**Comment by tgamblin** [comment]
@alalazo: We may have some updates for this soon but I'm just going to get it merged. Sorry it's taken so long to merge!  I should've gotten this in a while ago.

@scheibelp is working on unifying the syntax between `Spec.format()`, what we use for RPM generation, and the various module naming expressions you support in here.

**Comment by alalazo** [comment]
@tgamblin Cool. Let me know if you need help for the implementation of the thing once you have sound design.

**Comment by alalazo** [comment]
@tgamblin By the way, would you like me to add a few slides about hierarchical module files generation for the tutorial?

**Comment by tgamblin** [comment]
@alalazo yes!

**Pull request merged**
