### PR TITLE
Update vendored dependency: distro v1.6.0

### PR DESCRIPTION
**Pull request by alalazo**
depends on #27256 

Modifications:
- [x] Update `distro` to v1.6.0

### CODE REVIEW

**Comment by haampie** [comment]
Yay, this could improve startup times by 50ms (i think). Or wait, maybe it still calls lsb_release. You have to check what triplet you get with arch linux here.

**Comment by haampie** [comment]
So, this does not disable lsb_release by default. Basically there's no real change.

I'd be a fan of disabling lsb_release (since it's not a standard system executable), but that can go in another PR.

**Comment by alalazo** [comment]
> So, this does not disable lsb_release by default. Basically there's no real change

This vendors distro v1.6.0 without any other modification. The changes are in the changeset of distro, I think the most relevant for us are a few bugfixes and detection of new distros.

**Comment by haampie** [comment]
Yes sure, I just thought there were some performance improvements upstream, but I misremembered

**Review by haampie — APPROVED** [review]

**Pull request merged**
