### PR TITLE
expat: Add latest release 2.4.4 with security fixes

### PR DESCRIPTION
**Pull request by hartwork**
Hi!

[libexpat 2.4.4](https://github.com/libexpat/libexpat/releases/tag/R_2_4_4) with **security fixes** has been released, the upstream [change log](https://github.com/libexpat/libexpat/blob/R_2_4_4/expat/Changes) has more details.

Thanks for updating! :pray: 

Best, Sebastian

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Checksum verified.

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot ping

**Comment by scottwittenburg** [comment]
@spackbot hello

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Pull request merged**
