### PR TITLE
HIP: document variables, apply patches to older versions, fix build issues

### PR DESCRIPTION
**Pull request by haampie**
Since there are many variables being set I thought it would be a good idea to document them better and slightly simplify the logic for external vs not-external.

Supersedes #21822 ping @bvanessen

### CODE REVIEW

**Comment by haampie** [comment]
Also pinging @srekolam

**Comment by haampie** [comment]
Ok, I've also fixed the situation with rocm 3.8.0 a hair: `--rocm-path` didn't exist in that version yet, so I dropped it, and the patch for getting a proper patch version number in libamdhip64.so applied to 3.8.0 too.

**Review by srekolam — COMMENTED** [review]
i would like try this change but what i know is, You should see following with ROCm4.1:
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr

**Comment by haampie** [comment]
I'm building the following:

```yaml
spack:
  view: false
  specs:
  - matrix:
    - [sirius@develop+rocm ^openmpi ^openblas threads=openmp arch=linux-centos8-zen]
    - [^rocblas@3.7.0, ^rocblas@3.8.0, ^rocblas@3.9.0, ^rocblas@3.10.0, ^rocblas@4.0.0]
  packages:
    all:
      variants: amdgpu_target=gfx906 tensile_architecture=gfx906
```
only waiting for 3.7.0 to finish, but the rest works fine.

**Comment by haampie** [comment]
My packages build fine with 3.7, 3.8, 3.9, 3.10 and 4.0 (which include rocblas & rocfft). Only 3.5 does not work because because it is missing that patch for the shared lib name, but that was the case from the beginning.

So this PR is ready for review now

**Comment by bvanessen** [comment]
@haampie Any idea on when this PR will merge?

**Comment by haampie** [comment]
As soon as @srekolam agrees with it, so soon (tm)

**Review by srekolam — APPROVED** [review]
i built few packages like rocblas,rocrand , rocfft for @3.7.0 ,@3.8.0, @3.9.0,@4.0.0 successfully with this PR changes.The changes look good .. @haampie  ,thanks!!!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
