### PR TITLE
Spec.format updates to full-string property specification

### PR DESCRIPTION
**Pull request by scheibelp**
Address request in #2240 to support "COMPILERVERSION" in Spec.format

(as mentioned in #2240, the issue was already resolved by an existing PR, this just addresses a side request)

Originally only "COMPILERVER" was supported; this was the only truncated reference.

This supports both "COMPILERVER" and "COMPILERVERSION"

### CODE REVIEW

**Comment by tgamblin** [comment]
Thanks @scheibelp!  OT, while we're waiting for Travis, is there any chance we could make the variables case-insensitive in a follow-up PR?  I feel like my `modules.yaml` is screaming at me.

**Comment by scheibelp** [comment]
Yeah I'll add that in the next 30 minutes or so

**Comment by adamjstewart** [comment]
Looks good. I vote we keep the variables in the documentation as ALL-CAPS, as it makes it more obvious what is a variable and what is a string.

**Comment by scheibelp** [comment]
>any chance we could make the variables case-insensitive in a follow-up PR

I overlooked the "in a follow-up PR" part of that request and added that here (which was bad form given that people have already approved it - sorry about that!)

If preferred I can move it to a separate PR. In the meantime I'm renaming this request and marking it WIP pending an acknowledgement

**Comment by tgamblin** [comment]
@adamjstewart: I don't feel too strongly about that but I do prefer lowercase most everywhere.

@scheibelp: no need for a separate PR. Thanks!

**Comment by scheibelp** [comment]
OK, I have removed the WIP label then and will be more conscious about not appending stuff to PRs that have already been accepted in the future.

**Comment by tgamblin** [comment]
@scheibelp: I honestly don't think your judgement call here was in error 😄 Same PR was just fine

**Comment by adamjstewart** [comment]
@tgamblin I find ALL-CAPS a lot more obvious, especially for common directory names like `spack`. If I see:
```
directory: $spack/share/spack/lmod
```
it doesn't jump out at me that `spack` is a variable. But if I see:
```
directory: $SPACK/share/spack/lmod
```
it's pretty obvious.

**Comment by tgamblin** [comment]
What about `${spack}/share/spack/lmod`?

**Comment by tgamblin** [comment]
or even the more python-ish `{spack}/share/spack/lmod`?

**Comment by adamjstewart** [comment]
Why not all of the above? 😆

**Comment by alalazo** [comment]
I must say though that I kind of liked the configuration files that *were screaming at you* ( @tgamblin :tm: ) :smile:

**Comment by tgamblin** [comment]
@citibeth had suggested going with `{}` format-string-ish syntax for configs, as `$` is bash-y.  I'd be tempted to allow it and swap the documentation to use just `{}`. We'd need `Spec.format` to be a little more sophisticated though.  Not my top priority at the moment but something to think about.  Maybe if the configs yell at me enough I'll fix them.

**Pull request merged**
