### PR TITLE
root: add CLING_CXX_PATH variable to CMake build

### PR DESCRIPTION
**Pull request by arekfu**
Closes issue #23886.

### CODE REVIEW

**Comment by arekfu** [comment]
pinging @HadrienG2 @chissg @drbenmorgan @vvolkl

**Comment by drbenmorgan** [comment]
I'll leave the approval/merge to @vvolkl, but will this introduce a hard-coded absolute path into the `root` binaries (and thus non-relocatable build caches)? Or will the current relocation mechanism be able to rewrite this? NB: I'm not objecting to an absolute path (if it's needed, it's needed), but the necessity and consequences should be recorded.

**Comment by arekfu** [comment]
@drbenmorgan I think this bakes the path in the binary, yes. I don't know enough about how build caches work to see if this would also be a problem with the other solution discussed in #23888 (dumping a symlink to the compiler in `$ROOTSYS/bin`).

**Comment by drbenmorgan** [comment]
Thanks @arekfu, I'm not sure if the `root` package is in anycase fully relocatable (@gartung and @vvolkl will be able to clarify). The symlink would, _I guess_, also have the issue of hardcoding a path in, though _might_ be easier to fix up (but adding a `cc` link in `bin` when `root` could appear in a spack environment might have issues/clashes). 

However, I'll leave this decision up to @vvolkl - the changes are otherwise all fine, so ready to merge after approval!

**Comment by vvolkl** [comment]
Thanks @drbenmorgan for taking a look, the "relocatability" is a valid concern. However, this path should matter only when the compiler is relocated, not when root is relocated, and the issue it fixes is somewhat serious, I think.

I'm actually curious about this, as soon as I find some time I'm going to investigate if there are any relocation issue with root. I've been happily using the binaries you can download from the root website from all kinds of paths, so it's clear there is no issue on the root side.

And finally I do like this solution better than adding a `cc` symlink to root, because it's less surprising -  as you say, I'm also not 100% confident there won't be any issues with having this symlink in views/environments.

So I say this looks good to me as is. Thanks @arekfu for the fix!

**Review by vvolkl — APPROVED** [review]

**Review by gartung — APPROVED** [review]

**Pull request merged**
