### PR TITLE
pybind11: v2.10.1

### PR DESCRIPTION
**Pull request by ax3l**
Add the latest release of pybind11:
  https://github.com/pybind/pybind11/releases/tag/v2.10.1

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha256 and that the existing version has are still correct.

**Review by adamjstewart — APPROVED** [review]

**Comment by ax3l** [comment]
that CI pipeline fail looks unrelated.

**Comment by ax3l** [comment]
@spackbot re-run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
