### PR TITLE
Bump reframe

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by vkarak — APPROVED** [review]
Thanks @haampie !

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by haampie** [comment]
@spackbot run

**Comment by haampie** [comment]
@spackbot re-run

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
