### PR TITLE
Features/compiler config consistency

### PR DESCRIPTION
**Pull request by scheibelp**
Trying to address #2164 

(EDIT) This PR makes the following changes:

* ensure that "spack config edit X" will by default edit [user]/[platform]/X.yaml
  * this is important for compilers in particular, primarily to be consistent with "spack compiler find" default
* ensure that "spack compiler find" will not generate a "duplicate" compiler entry: if a compiler with the same spec is defined at any scope it is not added
  * this is important because concretizing compilers is independent of scope

TODOs (now complete):

- [x] "spack config edit" should only default to platform-specific config files for compilers
- [x] There should be a check at spack startup that ensures each compiler spec occurs only once across all scopes (EDIT: instead this PR modifies the error message printed during concretization)

Original PR message:

So far I have:

* ensure that "spack config edit X" will by default edit [user]/[platform]/X.yaml
  * this is important for compilers in particular, primarily to be consistent with "spack compiler find" default
* ensure that "spack compiler find" will not generate a "duplicate" compiler entry: if a compiler with the same spec is defined at any scope it is not added
  * this is important because concretizing compilers is independent of scope
	
However:

* a user can still manually edit [user]/compilers.yaml after "spack compiler find" updates [user]/[platform]/compilers.yaml, perhaps with the expectation that the instance they edited will take precedence. I can think of two general approaches to handle this case:
  * perhaps there should be a "spack compiler check" command to make sure no spec is repeated multiple times. Or more likely the check should occur at spack startup
  * (this seems harder) perhaps user-created and system-generated compilers should be able to coexist, and the user-created instance should be used in that case
* a user will be dumped into [user]/[platform]/modules.yaml by default for "spack config edit modules", and platform-specific module file generation may be confusing
  * IMO default editing should only be platform-specific for compilers

### CODE REVIEW

**Comment by scheibelp** [comment]
> There should be a check at spack startup that ensures each compiler spec occurs only once across all scopes

Instead of adding that overhead I improved the exception to point the user to the files where the duplicates appear:

```
$ spack spec zlib
==> Error: Compiler gcc@4.8.5 for architecture linux-rhel6-x86_64 is duplicated in the following config files:
	/home/scheibel/repos/spack/etc/spack/compilers.yaml: 1 time
	/home/scheibel/.spack/linux/compilers.yaml: 1 time
```

**Comment by pramodk** [comment]
> ==> Error: Compiler gcc@4.8.5 for architecture linux-rhel6-x86_64 is duplicated in the follo

just to clarify : this error will appear if there is a duplicate `spec` specification (and not when we use same compiler in different specs, e.g. when mix gfortran with clang on OS X)

**Comment by scheibelp** [comment]
> just to clarify : this error will appear if there is a duplicate spec specification (and not when we use same compiler in different specs, e.g. when mix gfortran with clang on OS X)

I updated the error message to hopefully make this clearer:

```
==> Error: Compiler configuration contains entries with duplicate specification (gcc@4.8.5, linux-rhel6-x86_64) in the following files:
	/home/scheibel/repos/spack/etc/spack/compilers.yaml: 1 time
	/home/scheibel/.spack/linux/compilers.yaml: 1 time
```

**Comment by becker33** [comment]
What about compilers that share a spec because they are identical compilers on different systems? For example, when I run `spack compilers` on one of our clusters, I see 3 of every compiler. One for rhel6, one for rhel7 x86_64, and one for rhel7 ppc64le. We should filter those to show separately in the `spack compilers` output.

**Comment by scheibelp** [comment]
> We should filter those to show separately in the spack compilers output.

Do you mean for example have sections like:

```
-- gcc rhel7 x86_64 ---------------------------------------------------
gcc@4.8.5  gcc@4.6.1  gcc@4.4.7
-- gcc rhel6 ----------------------------------------------------------
gcc@4.8.5  gcc@4.6.1  gcc@4.4.7
-- gcc rhel7 ppc64le --------------------------------------------------
gcc@4.8.5  gcc@4.6.1  gcc@4.4.7
```

? I could do that. To be clear this is an additional change. Rather than an edit to the existing changes.

**Comment by becker33** [comment]
That was the change I had in mind. I did not realize that was fully orthogonal to what you were doing.

**Comment by scheibelp** [comment]
Latest two commits add in requested functionality and tests it. This also involves refactoring some code in compilers/__init__ (trying to clarify a distinction between a compiler and a compiler spec)

**Pull request merged**
