### PR TITLE
Patch to support aarch64 and powerpc in siesta

### PR DESCRIPTION
**Pull request by danielecesarini**
As above

### CODE REVIEW

**Comment by haampie** [comment]
Can you clarify where/how you got this patch? Is it from official sources? Is there a URL for it?

**Comment by danielecesarini** [comment]
The patch is mine, it is a simple update of two config.guess files with a new version to support a larger number of architectures where is possible to install Siesta.

**Comment by haampie** [comment]
Ah okay, I looked at siesta and I couldn't even see if it was an autotools package or not from their gitlab sources.

If it's an autotools package, then can you make it that? Then you don't need patches, see https://spack.readthedocs.io/en/latest/build_systems/autotoolspackage.html?highlight=autotools#old-autotools-helper-scripts

**Comment by danielecesarini** [comment]
I didn't know about this, thanks, I will go over it in the next days. 

In the meantime, I have closed the PR and I will come back.

**Pull request closed without merging**
