### PR TITLE
Various updates to wget and dependencies

### PR DESCRIPTION
**Pull request by adamjstewart**
- [x] Adds latest versions
- [x] Adds missing dependencies
- [x] Converts to `AutotoolsPackage`

Currently blocked by #4113 and #4112. Marking this as a WIP.

### CODE REVIEW

**Comment by alalazo** [comment]
Apparently Travis didn't trigger.

**Comment by adamjstewart** [comment]
Hopefully I didn't get banned like @svenevs 😆

**Comment by adamjstewart** [comment]
Now that #4113 has been resolved, this PR can be merged whenever Travis passes.

**Comment by alalazo** [comment]
Hey, I completely forgot about this one. I'll try to have #4112 solved by the end of the week.

**Comment by adamjstewart** [comment]
@alalazo No rush, it's just a _nice to have_ feature at this point. We've gotten by this long without it.

**Pull request merged**
