### PR TITLE
bdw-gc: add v8.2.4

### PR DESCRIPTION
**Pull request by ivmai**

### CODE REVIEW

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Confirmed the new version sha256; however, cannot confirmed those of `7.6.0` or `7.4.4`.  It looks like the URL changed around `8.0.0` to one where the older versions are not available.

Probably the easiest way to handle this, assuming someone will want to deprecated and eventually remove versions prior to `8.0.0`, would be to add the appropriate URLs to the older version directives:

```
    version(
        "7.6.0",
        sha256="a14a28b1129be90e55cd6f71127ffc5594e1091d5d54131528c24cd0c03b7d90",
        url="http://www.hboehm.info/gc/gc_source/gc-7.6.0.tar.gz",
    )
    version(
        "7.4.4",
        sha256="e5ca9b628b765076b6ab26f882af3a1a29cde786341e08b9f366604f74e4db84",
        url="http://www.hboehm.info/gc/gc_source/gc-7.4.4.tar.gz",
    )

```

BTW I did confirm the above version sha256 with the added URL arguments.

**Comment by ivmai** [comment]
> It looks like the URL changed around 8.0.0 to one where the older versions are not available.
> Probably the easiest way to handle this, assuming someone will want to deprecated and eventually remove versions prior to 8.0.0, would be to add the appropriate URLs to the older version directives

Thank you. Committed.

**Comment by ivmai** [comment]
I will fix formatting issue later

**Comment by ivmai** [comment]
> I will fix formatting issue later

Done

**Review by tldahlgren — APPROVED** [review]
(Re)confirmed the sha256.

**Pull request merged**
