### PR TITLE
saws: add version 0.1.1 [with python3 fixes]

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Comment by adamjstewart** [comment]
> with python3 fixes

This package doesn't list a dependency on Python. Should it?

**Comment by balay** [comment]
Added the dependency on python.

Also this package  has a dependency on pthread. How can I add this? [I'm unable to locate example code for this usage]. Right now its picking up from default compiler paths.. [pthread.h, -lpthread]

**Comment by balay** [comment]
Also `-lm`. I don't how the correct way to use this in spack [as this can be `-limf` for Intel compilers]

**Comment by adamjstewart** [comment]
I think pthread and m can be taken from the OS.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
