### PR TITLE
LAMMPS: adds ROCm LLVM lib path to `LD_LIBRARY_PATH`.

### PR DESCRIPTION
**Pull request by dipietrantonio**

### CODE REVIEW

**Review by rbberger — COMMENTED** [review]
This looks over engineered. All of this just to set the `LD_LIBRARY_PATH`? What problem is it trying to solve? Most of this is already done in `hip/package.py`.

**Comment by dipietrantonio** [comment]
@rbberger Apologies for leaving no description. I accidentally added two packages here instead of one. The KOKKOS one should have had its own PR.

I asked my colleagues who worked on these recipes, and at the time they were created these variables were necessary as the compilation failed without them. I agree these should have been included in the HIP recipe.

I am double checking now whether these changes are still necessary.

**Comment by cedricchevalier19** [comment]
@dipietrantonio You can add environment definition while configuring your compiler for Spack. You should not need to modify the recipe of all the rocm packages you use.

**Comment by rbberger** [comment]
Closing, since this should be a non-issue with a corrected configuration as mentioned above. @dipietrantonio reopen if you disagree.

**Pull request closed without merging**
