### PR TITLE
fix ipyrad numpy dependencies

### PR DESCRIPTION
**Pull request by mikerenfro**
ipyrad versions through 0.9.90 use np.int, which is deprecated in numpy 1.20. Thus, making py-ipyrad@:0.9.90 depend explicitly on py-numpy@:1.19, and py-ipyrad@0.9.91: depend on py-numpy@1.20: . Arguably, we could make py-ipyrad@0.9.91: depend on any version of numpy, since the main issue is that 0.9.90 requires an older numpy.

References:
- https://github.com/dereneaton/ipyrad/blob/b28d8a3733c64f14b7787d86880c58d5cd409f28/newdocs/releasenotes.rst#L28
- https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### CODE REVIEW

**Comment by adamjstewart** [comment]
Deprecated does not mean removed. When was the attribute completely removed? I also don't see any evidence that older versions of numpy no longer work.

**Comment by mikerenfro** [comment]
> Deprecated does not mean removed. When was the attribute completely removed? I also don't see any evidence that older versions of numpy no longer work.

Will verify. Pretty sure I saw an end user getting errors related to this, but I could have misread it.

**Comment by mikerenfro** [comment]
Ok, so data that prompted this, even though I probably arrived at the wrong solution. Error screenshot from py-ipyrad 0.9.90, submitted by my end user:
image

# Further investigation:

## Spec details from a fresh Vagrant host using the `develop` branch:

```
[vagrant@localhost ~]$ spack --version
0.22.0.dev0 (c508ff1e5fe06b5723c7a31d31757c37cba39013)
[vagrant@localhost ~]$ spack spec py-ipyrad
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-x86_64-gcc-10.2.1-patchelf-0.18.0-afv7arjarb7nzmlh7c5slkfxykybuqce.spec.json
...
Input spec
--------------------------------
 -   py-ipyrad

Concretized
--------------------------------
 -   py-ipyrad@0.9.90%gcc@8.5.0 build_system=python_pip arch=linux-rocky8-sandybridge
...
 -       ^py-numpy@1.26.3%gcc@8.5.0 build_system=python_pip patches=873745d arch=linux-rocky8-sandybridge
...
```

## NumPy release notes:

[`np.int` was deprecated in NumPy 1.20, and expired entirely in 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations)

## ipyrad repository notes:

- Commit that fixed the issue: [Fix numpy deprecation of np.int and np.bool](https://github.com/dereneaton/ipyrad/commit/3b39f7b5e907af72de1323e596b363521af5ea0a), part of 0.9.91 and above.
- [Sample line of code from 0.9.90 that won't work with NumPy 1.24 and above](https://github.com/dereneaton/ipyrad/blob/eb83a894bae11e8e10c2cc382cefe21622a1999a/ipyrad/assemble/demultiplex.py#L280)

# Updated solution proposal:

1. Add py-ipyrad 0.9.91 and later versions, depending on any version of numpy.
2. Edit dependencies on py-ipyrad 0.9.90 and below, requiring numpy below 1.24.

@adamjstewart -- does this sound better?

**Comment by adamjstewart** [comment]
Yes, makes sense. You can also add a comment linking to the issue so we remember why old ipyrad doesn't work with new numpy.

**Comment by mikerenfro** [comment]
> Yes, makes sense. You can also add a comment linking to the issue so we remember why old ipyrad doesn't work with new numpy.

@adamjstewart [new commit should fix all this](https://github.com/spack/spack/pull/42098/commits/22d07f45690dc8d4927f5cb90c6231a3778e51bc)

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
