### PR TITLE
FleCSI dependency updates

### PR DESCRIPTION
**Pull request by rbberger**
- boost requirements will become less in future releases, `+stacktrace` was added for consistency, even though it's always included.
- add missing `+kokkos` propagation for non-GPU cases
- Legion now uses the full `CudaPackage.cuda_arch_values` list, so remove the custom list we copied from them, remove limitation and get newer cuda_archs automatically.
- Make use of `requires` to specify GCC version requirement
- Add missing graphviz dependency for `+doc`

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by rbberger** [comment]
@tldahlgren pushed one more change that added a missing dependency we just noticed. that should be it for now.

**Review by tldahlgren — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Because @rbberger is one of the two maintainers, I think we can merge.
Built a few variants, including +kokkos, +openmp, +doc, on Ubuntu 20.04 with gcc-11.

**Review by bernhardkaindl — APPROVED** [review]
@rbberger, @hkaiser JFYI, building 2.x (also I've issues with 1.x) with backend=hpx does not work, but for this you have #32355

**Comment by rbberger** [comment]
@bernhardkaindl yes, that is known. we're actively working to get HPX into our next FleCSI release.

**Pull request merged**
