### PR TITLE
arpack-ng: Fix build with gcc@10:

### PR DESCRIPTION
**Pull request by lorddavidiii**
`arpack-ng` is currently not building with gcc10. This is already fixed upstream, but there is no new release yet ( see this issue: https://github.com/opencollab/arpack-ng/issues/261 for example).  
I create a patch based on these two commits:
  - https://github.com/opencollab/arpack-ng/commit/9418632214acf6d387896ab29a8f5bdff2d4e38a
  - https://github.com/opencollab/arpack-ng/commit/ad82dcbc0beeed5616e2d5a28a089d9785f8b8b8

This works for me ( archlinux, gcc 10.1.0) and patch applies for 3.7.0, 3.6.3 and 3.6.2.

### CODE REVIEW

**Review by michaelkuhn — COMMENTED** [review]
How about doing something like this instead?
```python
    def setup_build_environment(self, env):
        # https://github.com/opencollab/arpack-ng/issues/261
        if self.spec.satisfies('@:3.7.0 %gcc@10:'):
            env.set('FFLAGS', '-fallow-argument-mismatch')
```
This saves us from having to carry the rather large patch and should work with all versions.

**Comment by lorddavidiii** [comment]
thanks  for the tip, I was not aware of this compiler flag. Looks better to me, I will test and update this PR.

**Comment by alalazo** [comment]
Just leaving a comment, but I'm always worried when I see a 4k lines patch and I think of building from "pristine" sources... Does anybody know when a new release will be cut upstream?

**Comment by lorddavidiii** [comment]
> Does anybody know when a new release will be cut upstream?

I would assume soonish as noted in this comment: https://github.com/opencollab/arpack-ng/pull/264#issuecomment-639668360

**Comment by alalazo** [comment]
@lorddavidiii Then I'd rather go with @michaelkuhn suggestion and add a new release as soon as it is published.

**Comment by lorddavidiii** [comment]
Ok, I have update now this PR with the suggestion from @michaelkuhn and tested it in my environment.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
