### PR TITLE
hipblaslt: new package

### PR DESCRIPTION
**Pull request by afzpatel**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the homepage and version sha256s.  

Any chance of getting the patch upstreamed?

**Comment by afzpatel** [comment]
> Confirmed the homepage and version sha256s.
> 
> Any chance of getting the patch upstreamed?

I don't think so since it's assuming that everything is in a single ROCm path like **/opt/rocm**. That's the common case but not in spack, so we need a patch to set the path for binaries in the LLVM path

**Comment by tldahlgren** [comment]
Is this ready to merge?  Or should I wait for @renjithravindrankannath and or @srekolam to comment?

**Review by tldahlgren — APPROVED** [review]

**Comment by afzpatel** [comment]
> Is this ready to merge? Or should I was for @renjithravindrankannath and or @srekolam to comment?

I think give them some time to comment

**Review by srekolam — APPROVED** [review]

**Review by renjithravindrankannath — APPROVED** [review]

**Pull request merged**
