### PR TITLE
ninja: add 1.12.1

### PR DESCRIPTION
**Pull request by msimberg**
https://github.com/ninja-build/ninja/releases/tag/v1.12.1

### CODE REVIEW

**Review by RMeli — APPROVED** [review]
SHA256 verified.

**Comment by RMeli** [comment]
https://github.com/ninja-build/ninja/releases/tag/v1.12.1

**Comment by msimberg** [comment]
@adamjstewart `py-torchaudio` is failing on this PR on `ml-linux-x86_64-cuda-build` with (https://gitlab.spack.io/spack/spack/-/jobs/12259570#L578):
```
/tmp/root/spack-stage/spack-stage-py-torchaudio-2.4.0-mpg6ccza5cherdh5yynz6c22mbi5mdda/spack-src/src/libtorchaudio/cuctc/src/ctc_prefix_decoder_kernel_v2.cu(154): error: identifier "FLT_MAX" is undefined
          ptable[idout] = -FLT_MAX;
```
Does it look familiar to you or do you see any reason why the ninja version bump would make it fail? I did report #45788, but that was with ninja going from 1.11.1 to 1.12.0, not a patch version bump as I assume this PR should do for that pipeline (1.12.0 to 1.12.1).

**Comment by adamjstewart** [comment]
See https://github.com/spack/spack/pull/45773. It's failing in develop, not just your PR.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
