### PR TITLE
py-mpi4py: always force rebuild cython sources

### PR DESCRIPTION
**Pull request by balay**
ref: https://github.com/spack/spack/pull/36406

cc: @dalcinl @joseeroman

### CODE REVIEW

**Comment by haampie** [comment]
Possibly relevant: #35995 (edit: noticed the thread in a linked PR).

@adamjstewart fwiw, didn't read the entire thread, but it's necessary for the build system to call cythonize(...), which normally doesn't do anything when generated source files are already included. So I guess this change is fine.

**Comment by balay** [comment]
@haampie the 3 pkgs mpi4py, petsc4py, slepc4py appear unaffected by `CYTHON_FORCE_REGEN=1` - i.e using pre-generated cython sources in the tarball  - unless `cythonize()` is invoked.

This was discussed in #36406 wrt petsc4py.  And corresponding slepc4py change is at #36401. This PR has this change for mpi4py

**Comment by adamjstewart** [comment]
@haampie is it always necessary to run cythonize, or is that only for these 3 packages? If the former, maybe we should add a step to the base class.

**Review by adamjstewart — APPROVED** [review]

**Comment by haampie** [comment]
Idk what's standard in Python packaging. Probably every package is a unique little snowflake ;p I would hope setup.py normally calls `cythonize` and it normally wouldn't do a thing when generated files come with the tarball -- except with our cython defaults it should always regenerate then.

**Comment by dalcinl** [comment]
@adamjstewart This special cythonize step is something very particular of my *4py packages. I know it looks awkward, but this stuff is as old as the beginning of the Cython project, when things like the `cythonize()` function did not even exist. Fortunately, from now on all this nonsense is gone, and Cython is build-time dependency, so Cython will always run.

**Pull request merged**
