### PR TITLE
Add relocatable code flag to trilinos for CUDA builds

### PR DESCRIPTION
**Pull request by psakievich**
I've been testing out the cuda option that was added into trilinos via #19119 but I keep getting `ptxas fatal: Unresolved extern function` errors when trying to use it as a dependency.

This resolve that error.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Pinging folks from the other PR: @keitat @aprokop @Char-Aznable @sethrj @amklinv-nnl

**Comment by sethrj** [comment]
Cuda relocatable code?! 😱 it’s the worst. Trust me that you want to look for any other solution. At best this should be a variant, but I would strongly recommend you find another fix.

**Comment by psakievich** [comment]
@sethrj I'll admit I'm a bit ignorant on the impacts of this. I'm fairly new to the GPU game. I've been reading a bit about it here: https://forums.developer.nvidia.com/t/the-cost-of-relocatable-device-code-rdc-true/47665/10
So my understanding is the issue is using the strategy of breaking up nested function calls across separate files causes the need for relocatable code. Is that correct?

That seems like basic strategy for decreasing CPU compile time on large projects. Do you have any other advice on how to avoid needing this flag? 

As for the PR I'm fine with adding it as a variant. Or just dropping it and using it in my repo specific inherited packages. It just depends on how useful this would be to others in the community. I was assuming other trilinos/kokkos users would need it regularly, but if that's not the case then I can restrict it to my own build process internally.

**Comment by sethrj** [comment]
Sorry @psakievich , I wasn't trying to be condescending or anything 😓, but I'm working on a new project that has an upstream "cuda relocatable" requirement and it has a tendency to destroy one's will to live. What we're finding is that the upstream relocatable code requires your  project's library to enable the `CUDA_SEPARABLE_COMPILATION` target property, which then forces the CUDA linker (rather than the host linker) to be used on any downstream target; and the CUDA linker (in our case) takes ~30 seconds as opposed to a fraction of a second.

CUDA separable compilation is something that Nvidia added but hasn't really documented well and is hard to find support for. It seems like a great idea in principle since compiling CUDA files tends to take a long time, but it really just shifts the time to the linking stage, which then is multiplied by the number of downstream targets you have.

Maybe @aprokop or other CUDA-enabled-Kokkos users could comment on separable compilation and how/whether Kokkos  needs it?

**Comment by amklinv-nnl** [comment]
Is this in any way related to: https://github.com/kokkos/kokkos/issues/1500?

**Comment by psakievich** [comment]
@amklinv-nnl I don't believe so. This works fine for me when I include this flag. That issue looks like the inverse of my problem. I include this flag when I build trilinos with Cuda manually as well so the spack build is replicating my manual build so far.

**Comment by psakievich** [comment]
So I've done a little more digging and it seems like we use this flag on the several Trilinos dependent projects at Sandia where we are refactoring legacy code to run on device.  @sethrj your case sounds like a nightmare the way you describe it.  Fortunately, all of the projects I'm involved in don't have much Cuda dependent code beyond Trilinos and the end application for which Trilinos is a direct dependency so there isn't a lot of chain reaction linker penalties occurring.  

I'll go ahead and update the PR to make this a variant.  My question for the larger community is what would you like it defaulted to? off or on?

**Comment by sethrj** [comment]
OK that's good to know! I'd wait to hear from more projects (especially @Char-Aznable who first added the cuda capability) before defaulting the variant to `on`, or maybe at least one other project downstream of Kokkos.

**Comment by psakievich** [comment]
I just did some local tests and the logic screwed up non-cuda builds as I put it in. just going to default it to off for now.

**Comment by Char-Aznable** [comment]
To be honest, I only use Kokkos, Kokkos-Kernels, Tpetra and a little bit of Techos from Trilinos. I never had to explicitly turn on RDC. I don't know if there are components of Trilinos that absolutely require RDC so maybe we can make this as a dependee for certain Trilinos variants? But in general, I don't have strong objection of this as long as it's default off.

**Comment by aprokop** [comment]
I have no opinion on this, I never used it.

**Comment by keitat** [comment]
I have used RDC with Kokkos-based code, but never used it with Trilinos.

**Review by sethrj — APPROVED** [review]
This all seems good based on the discussions we've had.

**Pull request merged**
