### PR TITLE
CI: Require target x86_64{_v3} for all stacks

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Some of the stacks were concretizing with incorrect targets. Adding this requirement to the force archs to be uniform across all stacks.

### CODE REVIEW

**Comment by haampie** [comment]
https://github.com/spack/spack/pull/36158#issuecomment-1472325122

Maybe this is fixed, but I think you need a list not a string?

**Review by eugeneswalker — DISMISSED** [review]
Thanks!

**Comment by kwryankrattiger** [comment]
@haampie 

> Maybe this is fixed, but I think you need a list not a string?

The string concatenation feature that was added the boilerplate might fix this? Or were you saying the `all` section is just completely skipped for merging?

**Comment by kwryankrattiger** [comment]
Quick rename of the targets so they are consistent. The old naming was a legacy "typo" that was been erroneously carried through the refactor.

In theory we could also remove the `spack:packages:all:target:[...]` from the stacks, but I don't think it really matters.

**Review by eugeneswalker — APPROVED** [review]

**Comment by haampie** [comment]
Can we merge #36158 first? It's been sitting in CI for a while and does the same

@kwryankrattiger I think the confusing thing is that `require:` takes lists or strings, and only if lists are used consistently it's extensible, otherwise it overrides. So, your packages.yaml isn't guaranteed to work, it depends on what's used in each environment. (And tbh that makes it very brittle...)

**Comment by haampie** [comment]
#36158 is merged, I'm still fine with this PR. I've proposed to deprecated `require: <string>` syntax, and let it automatically update to `require: [<string>]` with our deprecation scheme. Then this PR would make a lot of sense.

Created a PR for that here: https://github.com/spack/spack/pull/36526

**Comment by kwryankrattiger** [comment]
This is redundant with #36158 and it seems like the `require` keyword isn't great for composed environments right now, so I am going to drop this for now until https://github.com/spack/spack/pull/36526 goes in.

**Pull request closed without merging**
