### PR TITLE
Nalu: adding support for Trilinos 14.2.0 for Nalu 1.6.0

### PR DESCRIPTION
**Pull request by lucbv**
Additionally restricting a bit more the packages used from Trilinos to reduce build time.

### CODE REVIEW

**Comment by lucbv** [comment]
If you wouldn't mind having a look at this PR, it does not change the package that much and passed previously but got out of sync with develop. Will merge develop again but it would be nice to have someone give this a quick look!
Thanks : )

**Review by psakievich — APPROVED** [review]

**Comment by lucbv** [comment]
Hm, the error reported in CI seems to be unrelated, probably some network issue? @tldahlgren @alalazo if one of you has the time, a quick review would be good and also hit the `update branch` button and add the auto-merge label.
I could rebase myself again but it seems like a waste of compute cycle to retest without reviews...

**Comment by psakievich** [comment]
@lucbv I'll take care of it. I can merge this once CI passes.

**Comment by lucbv** [comment]
@psakievich sorry I forgot that you are on the spack-maintainer team. Thanks for having a look : )

**Comment by lucbv** [comment]
Funny, the branch is both out of date and too new to get tested by gitlab-CI, that seems like a CI infrastructure bug...

**Comment by psakievich** [comment]
There is a huge backlog of CI jobs right now due to the `*-runtimes` changes on compilers that affects everything. It might be a while. There is an investigation going on how to speed things up.

**Pull request merged**
