### PR TITLE
Change license dir from hard-coded to a configurable item

### PR DESCRIPTION
**Pull request by robgics**
Allow the user to specify a new location for the licenses that Spack touches.  Defaults to the current location of <spack>/etc/spack/licenses.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Seems fine to me. Only thing to think about is whether we want it to be a string or a list of strings. We haven't exactly been consistent with our other config vars in this regards.

**Comment by robgics** [comment]
How would a list of license directory locations work?  Spack takes the license file you specify in the package.py and makes a symlink to that file within the licenses directory...so, there really couldn't be more than one license dir, right?

**Comment by adamjstewart** [comment]
I guess that's true given how it's currently written (it's been like 7 years since I wrote this). Do we look for existing licenses in multiple directories, or is this only used to write a new license file?

**Comment by robgics** [comment]
It's where the license file goes if you set license_required to true.  If there's not already a license there, then it pops up the default one to fill out.  It then links any license files you indicated in the package license_files array to that license file.  So Spack doesn't do any license file looking that I'm aware of.  Just a "putting" of one.

**Review by adamjstewart — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
I would recommend submitting PRs on a separate branch than develop. Otherwise, every time you update, GitHub will have to re-run all tests. Also, it looks like the unit tests don't cover the line of code you added.

**Comment by robgics** [comment]
I thought PRs were always supposed to be from develop.  What branch should I create the PR from?  The latest codecov failure was for a file I didn't even modify, so that's a little perplexing....I figured someone else's commit to develop was causing that failure, so that's why I just kept updating. That's what happened last time I did a PR (for a package).

**Comment by robgics** [comment]
Ok, it's been a while since my last PR...I think I DID create my own branch back then.  So I'll do that and get it to pass on my branch.

**Comment by adamjstewart** [comment]
The PR should always be submitted AGAINST develop (i.e. once the PR is merged, it will be merged into develop). However, it's best to create the PR on a branch off of develop.

I'm not sure why coverage is failing on a different file though, that is weird...

**Comment by robgics** [comment]
Ok, thanks.

**Pull request closed without merging**
