### PR TITLE
Update NetCDF to version 4.4.1

### PR DESCRIPTION
**Pull request by eschnett**
This version supports HDF5 1.10 in a backward-compatible manner.

### CODE REVIEW

**Comment by citibeth** [comment]
The following text comes from the NetCDF release notes:

> Note: The combination of netCDF-C library versions earlier than 4.4.1 and libhdf5 1.10.0+ should be avoided, as they will result in binary files not readable by systems using earlier libhdf5 versions.

This needs to be enforced somehow, or else someone somewhere will have things stop working and won't know why.  Time simplest alternative would be to comment out all versions of NetCDF earlier than 4.4.1.  Or else do fancy Spack `where=` stuff.  Either way should work.  NetCDF has maintained a great level of backwards compatibility, and I don't know why anyone would WANT any version earlier than 4.4.1

**Comment by davydden** [comment]
why not adding this note to docstring?

> This needs to be enforced somehow

see https://github.com/LLNL/spack/pull/1275#issuecomment-233447932 why i think it should not.

**Comment by citibeth** [comment]
Thanks @davydden I read your comment but I disagree.

> i would not constrain netcdf to use hdf5@:1.8 only, especially given your memo that says it DOES work with 1.10, the results are just incompatible with netcdf+hdf5@1.8...
> It just does not feel right to me to introduce a constraint hdf5@:1.8 which is not a constraint de facto but a feature, although undesirable by users.

Remember that NetCDF does not control its backend (HDF5), but still needs to provide certain guarantees to users, regardless of what the HDF5 project chooses to do.  One of those guarantees is to maintain backwards compatibility.

This issue caught NetCDF somewhat by surprise, and broke backwards compatibility.  Nobody wants to be writing incompatible NetCDF files, and these are not supported by NetCDF.  NetCDF maintainers have explicitly stated so.  NetCDF has opted to maintain backwards compatibility, so files written by NetCDF 4.4.1 can be read by older versions of NetCDF4 that people were using previously.  See:

https://github.com/Unidata/netcdf-c/issues/250
http://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2016/msg00061.html

Eventually, they fixed the HDF5@1.10 problem as follows:

> [File Change] Starting with release 4.4.1, netCDF-4 files created will have superblock version 0 instead of superblock version 2, as was observed in previous netCDF versions. This is due to a workaround required to avoid backwards binary incompatibility when using libhdf5 1.10.x or greater. Superblock versions 0 and 2 appear to be forward and backward compatible. Other than a different superblock number the data should remain consistent.

We don't need to worry about the details.  The takeaway is that NetCDF@4.4.1 works with any version of HDF5, but NetCDF@:4.4.0 does not work with HDF5@1.10.  Even if it can link and run, the result produces files that no one wants, and is not supported or endorsed by NetCDF.

I think we should just delete pre-4.4.1 versions of NetCDF from the package and be done with it.  Any objections?

**Comment by davydden** [comment]
@citibeth i see, that makes sense.

Instead of deleting i would just specify
```
depends_on('hdf5@:1.8', when='@:4.4.0')
depends_on('hdf5', when='@4.4.1:')
```
which should do the trick.

**Comment by eschnett** [comment]
I updated the PR according to @davydden's suggestion.

**Comment by adamjstewart** [comment]
LGTM

**Comment by davydden** [comment]
LGTM

**Comment by citibeth** [comment]
Looks Good To Me

**Pull request merged**
