### PR TITLE
Bugfix/test: properly check installed specs

### LINKED ISSUE #29210: test_env_install_two_specs_same_dep is asserting the wrong object
### Steps to reproduce

The test:

https://github.com/spack/spack/blob/d62b8f0bf37e6066639be89d099709d492dff544/lib/spack/spack/test/cmd/env.py#L294-L298

is asserting the `installed` attribute on the wrong object. Since it is getting the *package class* as opposed to a *package instance* what the test is asserting is the presence of a property on the class. A simple reproducer of the behavior below:
```python
Spack version 0.17.1
Python 3.8.10, Linux x86_64
>>> import spack.repo
>>> zlib = spack.repo.path.get_pkg_class('zlib')
>>> type(zlib)
<class 'spack.package.PackageMeta'>
>>> zlib.installed
<property object at 0x7f2612bf1090>
>>> assert zlib.installed
>>> bool(zlib.installed)
True
```

### Error message

There is no error message, but the assertions in the test are wrong, since they don't check if a package object is installed or not - they check if the package class has a true-ish attribute defined.

### Information on your system

* **Spack:** 0.17.1-1358-5d46e5856c
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by tldahlgren**
Fixes #29210

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
Thanks!

**Review by alalazo — DISMISSED** [review]

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@alalazo Looks like the pipeline finally completed successfully.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks @tldahlgren

**Pull request merged**
