### PR TITLE
arm: Add version 22.0.2 and rename package from arm to acfl

### PR DESCRIPTION
**Pull request by annop-w**
- Add version 22.0.2
- Rename package from arm to acfl
- Add annop-w as maintainer
- Modify default url to point to version 22.0.2

### CODE REVIEW

**Review by OliverPerks — APPROVED** [review]
Looks good to me, thanks for updating to 22.0.2

**Review by OliverPerks — APPROVED** [review]
Thanks @annop-w This looks really good. Thanks for bumping the versions.

**Review by alalazo — CHANGES_REQUESTED** [review]
LGTM, after the conflicts are solved

**Comment by alalazo** [comment]
@annop-w @OliverPerks I can't take any direct action to solve the conflict myself, since I don't have permissions to edit @annop-w branch. Can you solve the conflict? Is this PR still of interest to you?

**Comment by annop-w** [comment]
@alalazo I am currently taking parental leave and will return to work in September. I will resolve the conflict as soon as I am back in the office. Sorry for any inconvenience.

**Comment by alalazo** [comment]
@annop-w Enjoy your leave then! Feel free to ping me when you get back in September!

**Pull request closed without merging**
