### PR TITLE
HPX: Add 1.9.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Review by albestro — DISMISSED** [review]
Verified SHA for new version and that I can download both 1.8.0 (old name url patter) and new 1.9.0.

No reference for the conflicts, but I fully trust you @msimberg and @spack/maintainers 

Personal opinion here: if you have any issue/reference to the doc about them, it might be a good idea to add a comment with the link (not needed in this PR, just an idea for the future).

**Comment by giordano** [comment]
@albestro I believe you just tagged all the 350+ members of the `maintainers` team, many of whom may not be interested in this PR :slightly_smiling_face:

**Comment by msimberg** [comment]
> Personal opinion here: if you have any issue/reference to the doc about them, it might be a good idea to add a comment with the link (not needed in this PR, just an idea for the future).

I'll just link them here: https://hpx-docs.stellar-group.org/tags/v1.9.0/html/releases/whats_new_1_9_0.html#breaking-changes. We haven't really documented "simple" version requirement changes so far so I'm not going to do that now either. To clarify, the "conflicts" I added here are simply updates to the minimum version requirements. For more complicated conflicts I fully agree with adding issues or links if possible.

> @albestro I believe you just tagged all the 350+ members of the `maintainers` team, many of whom may not be interested in this PR slightly_smiling_face

No such thing as bad publicity!?

**Comment by albestro** [comment]
😅 sorry, I tagged @msimberg and @hkaiser and for some reason it ended up with all maintainers.

Sorry to everyone for the annoying notification!

**Review by eugeneswalker — APPROVED** [review]

**Comment by msimberg** [comment]
@spackbot run pipeline

**Comment by andersp** [comment]
Please remove me from your mass mailings.
Thanks!
Anders

From: Mikael Simberg ***@***.***>
Date: Thursday, May 4, 2023 at 11:39 AM
To: spack/spack ***@***.***>
Cc: Petersson, Anders ***@***.***>, Team mention ***@***.***>
Subject: Re: [spack/spack] HPX: Add 1.9.0 (PR #37426)

@spackbot<https://urldefense.us/v3/__https:/github.com/spackbot__;!!G2kpM7uM-TzIFchu!xHulsvZNHx84csUfwQiYcWV9OzKQdEowtlXTlk1KRlmndZ4MDUO8Sd_7n-TDSiOuByO8uvAQ3gci7D1DvTzkWGlLeEc$> run pipeline

**Comment by nightlark** [comment]
@andersp (and others): the email notifications have an unsubscribe link at the bottom that you can use to stop getting emails every time a new comment is made here. Or from the PR there's a section in the sidebar (or bottom of the mobile website) that says "Notifications" with an "Unsubscribe" button... in the GitHub mobile app the "..." dropdown menu at the top of the app has an "Unsubscribe" option when you're viewing the PR.

**Comment by andersp** [comment]
Hi Ryan,
I have never subscribed to this PR but I still keep getting these notifications. Any idea why?
Thanks,
Anders

From: Ryan Mast ***@***.***>
Date: Thursday, May 4, 2023 at 1:43 PM
To: spack/spack ***@***.***>
Cc: Petersson, Anders ***@***.***>, Mention ***@***.***>
Subject: Re: [spack/spack] HPX: Add 1.9.0 (PR #37426)

@andersp<https://urldefense.us/v3/__https:/github.com/andersp__;!!G2kpM7uM-TzIFchu!wZ77MoGIs_zCEniQSK7UojYVNWM-K5yBQzOIqLxFN_L0qu3UVwhR57YToTvUq4sSVjDNs3qRnzQokcaOOb3HY2_OF70$> (and others): the email notifications have an unsubscribe link at the bottom that you can use to stop getting emails every time a new comment is made here. Or from the PR there's a section in the sidebar (or bottom of the mobile website) that says "Notifications" with an "Unsubscribe" button... in the GitHub mobile app the "..." dropdown menu at the top of the app has an "Unsubscribe" option when you're viewing the PR.

**Comment by HadrienG2** [comment]
Because albestro tagged spack/maintainers in the opening comment, which is much broader than they realized

**Comment by msimberg** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Pull request merged**
