### PR TITLE
docs: install intel-parallel-studio with patchelf%gcc (fixes #31474)

### LINKED ISSUE #31474: Internal compiler installation with stubs not working
### Steps to reproduce

The steps described here do not work any more:
https://github.com/spack/spack/blob/develop/lib/spack/docs/build_systems/intelpackage.rst#install-steps-for-packages-with-compilers-and-libraries

Step 4 says: `$ spack install intel-parallel-studio@cluster.2018.3  %intel@18.0.3`

This does not work anymore as `intel-parallel-studio` depends on `patchelf` at build time. Spack will try to build `patchelf %intel@18.0.3`, which fails as the compilers are set to `/usr/bin/true`.

### Error message

```console
+ command spack install intel-parallel-studio@cluster.2020.4 %intel@20.0.4
+ spack install intel-parallel-studio@cluster.2020.4 %intel@20.0.4
==> Installing patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5
==> No binary for patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5 found: installing from source
==> Using cached archive: /shared/spack/var/spack/cache/_source-cache/archive/11/113ada3f1ace08f0a7224aa8500f1fa6b08320d8f7df05ff58585286ec5faa6f.tar.gz
==> No patches needed for patchelf
==> patchelf: Executing phase: 'autoreconf'
==> patchelf: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/shared/tmp/stesachs/spack-stage/spack-stage-patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5/spack-src/configure' '--prefix=/shared/spack/opt/spack/linux-amzn2-x86_64/intel-20.0.4/patchelf-0.14.5-eoorf3qh'

2 errors found in build log:
     8     checking whether make sets $(MAKE)... yes
     9     checking whether make supports nested variables... yes
     10    checking for strip... strip
     11    checking whether make supports the include directive... yes (GNU style)
     12    checking for gcc... /shared/spack/lib/spack/env/intel/icc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/shared/tmp/stesachs/spack-stage/spack-stage-patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details

See build log for details:
  /shared/tmp/stesachs/spack-stage/spack-stage-patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5/spack-build-out.txt

==> Warning: Skipping build of intel-parallel-studio-cluster.2020.4-44g722q5nbqfb6syefrrrvpfbxzbpima since patchelf-0.14.5-eoorf3qhdx3x66n32j66uz4mzuco7zk5 failed==> Error: intel-parallel-studio-cluster.2020.4-44g722q5nbqfb6syefrrrvpfbxzbpima: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```

### Information on your system

$ spack debug report
* **Spack:** 0.19.0.dev0 (510c7e853a6154aaa9d13ce15d81661ba855ec33)
* **Python:** 3.7.10
* **Platform:** linux-amzn2-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by stephenmsachs**

### CODE REVIEW

**Comment by wdconinc** [comment]
I'm going through some older pull requests that would allow us to close some open issues on the known bugs list.

Is this PR still relevant? Can you verify that the documentation change still resolves the problem? In my tests, it seems that the libc detection may fail to work on the `/usr/bin/true` stubs.

**Comment by stephenmsachs** [comment]
Yes, the whole [intel-parallel-studio](https://github.com/spack/spack/blob/develop/lib/spack/docs/build_systems/intelpackage.rst#install-steps-for-packages-with-compilers-and-libraries) installation does not work anymore since the `libc` check. I don't think this is still relevant as Intel now packages their compilers through oneapi.

**Comment by wdconinc** [comment]
Does it make sense in that case to close this PR and open a new PR that adds a call-out in the documentation that lets users know which approach is preferred now? Adding @rscohn2 for input.

**Comment by alalazo** [comment]
@stephenmsachs Closing this one. Let me know if you'd have preferred otherwise.

**Pull request closed without merging**
