### PR TITLE
python: sequential make install

### LINKED ISSUE #34311: file too short when building with Python 10
In case there is insight here, I wanted to open an issue. Flux core failed building tonight because of:

```console
 ==> Warning: Module file /opt/spack/share/spack/modules/linux-ubuntu22.04-x86_64_v4/openssl-1.1.1s-gcc-12.1.0-uafqtva exists and will not be overwritten
==> Error: ProcessError: Command exited with status 2:
    'make' '-j2' 'install'

2 errors found in build log:
     1299    if test "3.10" != "3.10"; then \
     1300    	if test -f /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-1
             2.1.0/python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin/python3.1
             0 -o -h /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-12.1.
             0/python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin/python3.10; \
     1301    	then rm -f /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-1
             2.1.0/python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin/python3.1
             0; \
     1302    	fi; \
     1303    	(cd /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-12.1.0/p
             ython-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin; ln python3.10 p
             ython3.10); \
     1304    fi
  >> 1305    ./python: error while loading shared libraries: /opt/spack/opt/spa
             ck/linux-ubuntu22.04-x86_64_v4/gcc-12.1.0/python-3.10.8-vyifnzccjm
             6iquatjeiig4fbm4gcjlsb/lib/libpython3.10.so.1.0: file too short
  >> 1306    make: *** [Makefile:637: sharedmods] Error 127
     1307    make: *** Waiting for unfinished jobs....
     1308    if test "x" != "x" ; then \
     1309    	rm -f /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-12.1.0
             /python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/binpython3.10-32; 
             \
     1310    	lipo  \
     1311    		-output /opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-12.
             1.0/python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin/python3.10-
             32 \
     1312    		/opt/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-12.1.0/pyth
             on-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/bin/python3.10; \

See build log for details:
  /tmp/runner/spack-stage/spack-stage-python-3.10.8-vyifnzccjm6iquatjeiig4fbm4gcjlsb/spack-build-out.txt
```
It's a weird error - "file too short" and looks like it happens during the install phase:

https://github.com/flux-framework/spack/actions/runs/3616888046/jobs/6096151257

Could it be ephemeral - something with the runner or download? I'm too tired to debug now. Does spack not support Python 3.10 yet?

### PR DESCRIPTION
**Pull request by haampie**
See https://github.com/python/cpython/issues/102007

Fixes #34311

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is only Python 3.11+ affected or is it all versions?

Note that #34933 removes this chunk of code so we'll have to make sure it doesn't get undone @johnwparent

**Comment by haampie** [comment]
I didn't check older Python versions yet. Will look at it later

**Comment by johnwparent** [comment]
@adamjstewart I've already made a fix and pushed. Will update as needed.

**Comment by adamjstewart** [comment]
Let's also keep the comment, hopefully this can be removed or patched in the future.

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by alalazo — DISMISSED** [review]

**Comment by adamjstewart** [comment]
Still want to know if this bug affects all Python versions or only 3.11. Also curious how much longer `make install` takes in serial than it did in parallel.

**Comment by dslarm** [comment]
> Still want to know if this bug affects all Python versions or only 3.11. Also curious how much longer `make install` takes in serial than it did in parallel.

I can reproduce with python-3.9.15 regularly. 

Using Graviton (c7g.metal) - I see failure 2 in 6 times for 'spack install mpich' and the fail is due to python install failing with a "{...}lib/libpython3.9.so.1.0: file too short"

Having tried the fix in @scottwittenburg 's pull request (parallel=False for the make install), I then successfully ran 6 out of 6 installs (which would've had a chance of 8% of happening by chance if 1/3 is fail rate).

**Comment by dslarm** [comment]
This also looks like the cause of #34311.

**Comment by adamjstewart** [comment]
> Still want to know if this bug affects all Python versions or only 3.11. Also curious how much longer `make install` takes in serial than it did in parallel.

Still waiting for the answer to these questions.

**Comment by haampie** [comment]
It looks like it's an issue since Python 2.1. The install phase takes 3% of the total build time so I don't think it's something to care about

**Review by adamjstewart — APPROVED** [review]
Ran a quick test on M2 Pro.

### Before

  Stage: 6.47s.  Configure: 41.94s.  Build: 1m 48.36s.  Install: 5.89s.  Total: 2m 42.73s

### After

  Stage: 0.56s.  Configure: 36.61s.  Build: 1m 48.49s.  Install: 6.03s.  Total: 2m 31.75s

So the increased install time is not statistically significant. Should be safe to merge. If your issue is ever solved we can add a version specifier to restrict it.

**Comment by haampie** [comment]
It's weird nobody has pointed out the issue in the last 2 decades :p

**Pull request merged**
