### PR TITLE
geant4: Add a patch for twisted tubes

### PR DESCRIPTION
**Pull request by jmcarcell**
See https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2619. I have been told by @atolosadelgado that this is the corresponding patch that has been merged upstream, and it doesn't work for versions before 11.2.0.

### CODE REVIEW

**Comment by sethrj** [comment]
@jmcarcell I don't think the standard policy for spack (or any other application) is to backport runtime bug fixes to older versions, making the results you'd get from 11.2.0 different between a newer or older version of spack (or a different installation process). Patches are almost exclusively about compiler errors and other compatibility updates needed to get newer compilers working *without* changing the output of the code.

Experiment frameworks themselves are usually responsible for adding patches to Geant4 during installation.

And incidentally, twisted tubes aren't the only surfaces broken in Geant4 11.2; there's an incoming patch for twisted traps as well.

**Comment by atolosadelgado** [comment]
> And incidentally, twisted tubes aren't the only surfaces broken in Geant4 11.2; there's an incoming patch for twisted traps as well.

Hi @sethrj 

Thank you for the explanation about spack. 

Out of curiosity, is the patch for the twisted surfaces/shapes available for testing? 

Thank you for your time.

Alvaro

**Comment by sethrj** [comment]
@atolosadelgado I've uploaded the patch here: https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2547 but since it's basically a rewrite of the trapezoid, it may not apply cleanly.

**Comment by atolosadelgado** [comment]
> @atolosadelgado I've uploaded the patch here: https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2547 but since it's basically a rewrite of the trapezoid, it may not apply cleanly.

Thanks for the patch. 

In addition, you mentioned twisted traps, and other twisted surfaces which you fixed, is that incoming patch available for testing?

Thanks for your time

**Comment by sethrj** [comment]
I personally haven't fixed the twisted traps, that was Evgueni; the link  includes the patch to that. I wasn't aware of the twisted cylinder issues until your comment. It also sounds from @tgamblin that bug fixes are eligible for us to backport into Spack, but I wanted @drbenmorgan to weigh in since he had opinions about data usage in Geant4 strictly matching the "official" version.

**Comment by tgamblin** [comment]
I'm fine with back porting bugfixes -- we do this fairly frequently and the patches are modeled in package specs (so they are included in hashes).  I think @sethrj was worried that this would cause confusion and reduce reproducibility, but we do have the metadata.

**Comment by sethrj** [comment]
This sounds like some of the same philosophical discussion that was in #44830, whether it's OK to backport fixes...

**Comment by drbenmorgan** [comment]
I'll check upstream with the Geant4 release manager on this - going out on a limb I'd suspect this is going to depend on whether this patch changes/is expected to change physics validations, nominally point 2 in my comment the #44830 pointed to by @sethrj (and yes, I might end up contradicting myself...).

**Review by bernhardkaindl — APPROVED** [review]
@jmcarcell @drbenmorgan Is this fix ready for merge now?

Please @mention me if this is ready for merge.

**Comment by jmcarcell** [comment]
It's ready to be merged @bernhardkaindl from my side, it has been in our builds for some time and other people have confirmed they fixed the issues with twisted tubes.

**Review by bernhardkaindl — APPROVED** [review]
Thanks @jmcarcell for the added information on testing:  
> It's ready to be merged @bernhardkaindl from my side, it has been in our builds for some time and other people have confirmed they fixed the issues with twisted tubes.

With this, I see no reason hindering the merge, will do so now.

I think the discussion on backporting fixes didn't end in a rejection of it (not from Todd Galbin and didn't see a response from the Geant4 release manager thru @drbenmorgan) 

Just for the summary, I mention that there was this question by @atolosadelgado: 
> In addition, you mentioned twisted traps, and other twisted surfaces which you fixed, is that incoming patch available for testing?

**Comment by sethrj** [comment]
I don't think we got confirmation about the policy from @drbenmorgan ... also my concern is that now we can no longer test for correct behavior in downstream  applications based on _version_ alone.

**Pull request merged**
