### PR TITLE
Add fismahigh variant

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a `fismahigh` variant for ecbuild, eckit, netcdf-c, and yafyaml.

These changes are to support NOAA/National Weather Service operations, where the security review has mandated these modifications in order to comply with FISMA standards.

We will likely follow a similar approach for a number of other packages in the future, so I'm tagging @tgamblin @adamjstewart @tldahlgren @haampie @climbfuji for feedback. In the future, the hope for some or all of these packages is that we can work with developers to incorporate these changes into packages themselves so that this variant will trigger a built-in build option rather than patching, but for NOAA/NWS operations, we need these changes for existing package versions. After getting any feedback, I'm happy to split this out into separate PRs for each package.

### CODE REVIEW

**Review by mathomp4 — APPROVED** [review]
Approved for yafyaml

**Review by climbfuji — APPROVED** [review]
I reviewed and approved those changes earlier in our spack fork.

I should probably be listed as maintainer for the ECMWF packages (ecbuild, eckit, and others that I am going to contribute in the near future). We at JCSDA are working closely with ECMWF, using and sometimes contributing to these packages, and we offered ECMWF to help support their software in spack.

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot re-run pipeline

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot re-run pipeline

**Pull request closed without merging**
