### PR TITLE
updating samtools to 1.13

### PR DESCRIPTION
**Pull request by vsoch**
You can see the successful build here: https://github.com/autamus/registry/pull/752

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by samfux84** [comment]
It seems like something changed in the installation of htslib. The installation of 1.10.2 and 1.12 work without problems, but when I try to install version 1.13, then it fails with an error message about "Too many levels of symbolic links".

```
[spackapps@eu-a6-002-19 ~]$ spack install htslib@1.13 %$SSTDCOMP arch=$OS_ARCH
==> bzip2 is already installed in /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/bzip2-1.0.8-vo74kz4rcpe526v5flv72caevt2w7yfg
==> xz is already installed in /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/xz-5.2.3-gla7wvbtt5igzfbgwlazihdhqxz43avb
==> zlib is already installed in /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-tu4n3a4rud6dtfqmgmgfrb32liysc5lu
==> Installing htslib
==> Fetching https://github.com/samtools/htslib/releases/download/1.13/htslib-1.13.tar.bz2
######################################################################## 100.0%
==> Staging archive: /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13.tar.bz2
==> Created stage in /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu
==> No patches needed for htslib
==> Building htslib [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j72'

1 error found in build log:
     69    config.status: linking /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/
           htslib-1.13/htslib.mk to htslib.mk
     70    config.status: executing mkdir commands
     71    ==> Executing phase: 'build'
     72    ==> 'make' '-j72'
     73    make: Makefile: Too many levels of symbolic links
     74    make: stat: Makefile: Too many levels of symbolic links
  >> 75    make: *** No rule to make target 'Makefile'.  Stop.

See build log for details:
  /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13/spack-build.out
[spackapps@eu-a6-002-19 ~]$
```

@vsoch Does the installation of htslib  1.13 work for you? In my case, SPACK creates a symlink for the Makefile and htslib.mk pointing to itself:

```
[spackapps@eu-a6-002-19 htslib-1.13]$ pwd
/cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13
[spackapps@eu-a6-002-19 htslib-1.13]$ ls -ltr | tail -n 10
-rwxr-xr-x  1 spackapps spackapps-group  31860 Oct  1 09:26 config.status
-rw-r--r--  1 spackapps spackapps-group   3777 Oct  1 09:26 config.mk
-rw-r--r--  1 spackapps spackapps-group    494 Oct  1 09:26 htslib.pc.tmp
-rw-r--r--  1 spackapps spackapps-group   2761 Oct  1 09:26 htslib_vars.mk
-rw-r--r--  1 spackapps spackapps-group   4119 Oct  1 09:26 config.h
lrwxrwxrwx  1 spackapps spackapps-group     20 Oct  1 09:26 htscodecs.mk -> htscodecs_bundled.mk
lrwxrwxrwx  1 spackapps spackapps-group    101 Oct  1 09:26 Makefile -> /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13/Makefile
lrwxrwxrwx  1 spackapps spackapps-group    102 Oct  1 09:26 htslib.mk -> /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13/htslib.mk
-rw-r--r--  1 spackapps spackapps-group  33093 Oct  1 09:26 config.log
-rw-r--r--  1 spackapps spackapps-group   3611 Oct  1 09:26 spack-build.out
[spackapps@eu-a6-002-19 htslib-1.13]$
```

I am not using the newest SPACK version and would like to find out if this is a general issue or only a problem on my side because of using some older SPACK version.

Any help is appreciated.

Best regards

Sam

**Comment by vsoch** [comment]
Hey Sam! I would compare your install with the autamus install in this container, where it built successfully. https://github.com/orgs/autamus/packages/container/samtools/8136304?tag=1.13. Indeed it could be version or something like that. Let me know if you have any questions, or tell us what you find! Everything in the container should be under /opt.

**Comment by samfux84** [comment]
Hi @vsoch, Thank you for your reply.

I compared the build logs from my 1.12 installation with the failed 1.13 installation and it looks like the issue is coming from the configure script of htslib, which creates a script config.status which creates the symbolic links:

1.12:

```
configure: creating ./config.status
config.status: creating config.mk
config.status: creating htscodecs.mk
config.status: creating htslib.pc.tmp
config.status: creating config.h
==> Executing phase: 'build'
```

1.13:

```
configure: creating ./config.status
config.status: creating config.mk
config.status: creating htslib.pc.tmp
config.status: creating htslib_vars.mk
config.status: creating config.h
config.status: linking htscodecs_bundled.mk to htscodecs.mk
config.status: linking /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13/Makefile to Makefile
config.status: linking /cluster/apps/spack/var/spack/stage/htslib-1.13-vmsaet7oyapqknvnuqjsijnqqqrmd3lu/htslib-1.13/htslib.mk to htslib.mk
config.status: executing mkdir commands
==> Executing phase: 'build'
```

Therefore I think it is an issue on my side and does not relate to SPACK

**Pull request merged**
