### PR TITLE
AutotoolsPackage / MakefilePackage: add gmake build dep

### PR DESCRIPTION
**Pull request by haampie**
This should drop the system dependency on gmake.

Adding `gmake` as a dep in a build system affects builtin.mock packages too, unfortunately. I've tried to relax the assumptions in tests on a particular DAG if possible.

Also extracted #40576 into a separate PR; it's an issue here because all dev-build previously had no dependencies -- here they do.

### CODE REVIEW

**Comment by haampie** [comment]
Hm, unfortunately:

```
spack spec zlib ^gmake+guile
```

errors instead of picking `zlib ^(gmake+guile ^(guile ^gmake~guile))`

**Comment by alalazo** [comment]
@haampie Yep. This needs more work to allow "full" separation of the build deps stack (we need to build `zlib-api` for guile too, and that is not allowed by default right now).

**Comment by haampie** [comment]
curiously failure to build patchelf triggers an infinite loop, due to patchelf having a dependency now?

**Review by alalazo — APPROVED** [review]
More boilerplate to adjust tests than I would have expected.

**Pull request merged**
