### PR TITLE
squashfuse: add v0.1.105

### PR DESCRIPTION
**Pull request by vvolkl**
@haampie This should let you remove https://github.com/eth-cscs/spack-batteries-included/blob/master/build/patches/squashfuse.patch

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to @haampie

**Comment by vvolkl** [comment]
ping @haampie

**Comment by vvolkl** [comment]
Superseded by https://github.com/spack/spack/pull/42589

**Pull request closed without merging**
