### PR TITLE
spark: remove whitespaces from run_env variable

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by adamjstewart** [comment]
What did it look like before? I'm worried about what would happen if someone installed Spack in a directory with whitespaces in the path, but I'm sure half of Spack would break in that case anyway.

**Comment by alalazo** [comment]
For me it resulted in a string with `\n` not in final position, so `str.strip()` didn't work (and lua modules breaks because of that). But honestly I didn't go in with a debugger to see how the string looks like.

**Comment by adamjstewart** [comment]
It might be safer to do:
```python
hadoop_classpath = hadoop_classpath.replace('\n', '')
```
and see if that works.

**Comment by alalazo** [comment]
It doesn't work, must be another white space character that goes in. I'll check it tomorrow, but I agree that it is better to be defensive here.

**Pull request merged**
