### PR TITLE
Add FFTW variant to MKL

### PR DESCRIPTION
**Pull request by RMeli**
Add FFTW variant to MKL since it is not otherwise possible to cherry pick virtual dependencies (yet, see #35322). Inspired by the `nvhpc` package (which has `+blas` and `+lapack` variants).

### CODE REVIEW

**Comment by rscohn2** [comment]
I don't understand how this will work. What prevents the application from using the fft in mkl? I don't see a separate library for fft so the symbols will be available to link against, whether or not spack thinks mkl is providing fft.

**Comment by RMeli** [comment]
You are right. But currently it is impossible to concretize MKL with other packages providing `fftw-api@3`, such as the `fftw` package itself.

`intel-mkl~fftw` would allow to concretize an environment with `intel-mkl` (providing BLAS/LAPACK/ScaLAPACK) and `fftw`. It remains up to the build system to link against the correct library.

**Comment by rscohn2** [comment]
If you want to use blas from mkl, then you link with libmkl_core. If you want to use fft from mkl, you also link with libmkl_core. If the function names are the same between the 2 fft implementations, then there will be a conflict. I can ask the MKL maintainer if there is a way to get blas and not get fft.

**Comment by rscohn2** [comment]
I asked for help here: https://spackpm.slack.com/archives/C5VL7V81G/p1691492931019759

**Comment by mtaillefumier** [comment]
MKL has its own fft implementation that is not API compatible with fftw. It means that symbols starting with "fftw_" are **not** present in `libmkl_core.so`  or any other library included in the mkl package. 

Intel provides the source code that wraps fftw calls to their own implementation of the FFT algorithm but it is not compiled by default. To use it, we have to compile the wrapper and include the corresponding library to the build.

So by default, MKL does not provide fftw (although the wrapper is there) out of the box and I would simply suggest to remove the `provides("fftw-api@3", when="@2017:")` entirely or find a way to compile this wrapper through spack.

**Comment by rscohn2** [comment]
Thanks. I will look into both next week.

**Comment by mtaillefumier** [comment]
contrary to my statement, we found out (well @haampie discovered it) that MKL does have fftw symbols defined in libmkl_intel_lp64.so (or the gnu version). No work is needed to have the intel implementation of fftw3 except being careful with the order of the libraries if the original fftw3 and mkl are used together. 

I  am preparing a patch for the cp2k recipe to take this into account. 

running `nm --defined-only libmkl_gf_lp64.so | grep "fftw"` will return

```
00000000001f3980 T dfftw_cleanup_
00000000001f3990 T dfftw_cleanup_threads_
00000000001f39a0 T dfftw_destroy_plan_
00000000001f39b0 T dfftw_execute_
00000000001f39c0 T dfftw_execute_dft_
00000000001f39d0 T dfftw_execute_dft_c2r_
00000000001f39e0 T dfftw_execute_dft_r2c_
00000000001f39f0 T dfftw_execute_r2r_
00000000001f3a00 T dfftw_execute_split_dft_
00000000001f3a10 T dfftw_execute_split_dft_c2r_
00000000001f3a20 T dfftw_execute_split_dft_r2c_
00000000001f3a30 T dfftw_export_wisdom_
00000000001f3a40 T dfftw_flops_
00000000001f3a50 T dfftw_forget_wisdom_
00000000001f3a60 T dfftw_import_system_wisdom_
00000000001f3a80 T dfftw_import_wisdom_
00000000001f3aa0 T dfftw_init_threads_
00000000001f3ac0 T dfftw_plan_dft_
00000000001f3bf0 T dfftw_plan_dft_1d_
00000000001f3c20 T dfftw_plan_dft_2d_
00000000001f3c60 T dfftw_plan_dft_3d_
00000000001f3cb0 T dfftw_plan_dft_c2r_
00000000001f3e10 T dfftw_plan_dft_c2r_1d_
00000000001f3e30 T dfftw_plan_dft_c2r_2d_
00000000001f3e60 T dfftw_plan_dft_c2r_3d_
00000000001f3ea0 T dfftw_plan_dft_r2c_
00000000001f4000 T dfftw_plan_dft_r2c_1d_
00000000001f4020 T dfftw_plan_dft_r2c_2d_
00000000001f4050 T dfftw_plan_dft_r2c_3d_
00000000001f4090 T dfftw_plan_guru_dft_
00000000001f4380 T dfftw_plan_guru_dft_c2r_
00000000001f4660 T dfftw_plan_guru_dft_r2c_
00000000001f4940 T dfftw_plan_guru_r2r_
00000000001f4bd0 T dfftw_plan_guru_split_dft_
00000000001f4eb0 T dfftw_plan_guru_split_dft_c2r_
00000000001f5190 T dfftw_plan_guru_split_dft_r2c_
00000000001f5470 T dfftw_plan_many_dft_
00000000001f5610 T dfftw_plan_many_dft_c2r_
00000000001f5780 T dfftw_plan_many_dft_r2c_
00000000001f58f0 T dfftw_plan_many_r2r_
00000000001f5a90 T dfftw_plan_r2r_
00000000001f5be0 T dfftw_plan_r2r_1d_
00000000001f5c10 T dfftw_plan_r2r_2d_
00000000001f5c90 T dfftw_plan_r2r_3d_
00000000001f5d50 T dfftw_plan_with_nthreads_
00000000001f5d60 T dfftw_print_plan_
0000000000d0e180 D fftw3_mkl
00000000001ebf50 T fftw_alignment_of
00000000001ebf60 T fftw_alloc_complex
00000000001ebf80 T fftw_alloc_real
0000000000837a75 R fftw_cc
00000000001ebfa0 T fftw_cleanup
00000000001ebfb0 T fftw_cleanup_threads
0000000000837a76 R fftw_codelet_optim
00000000001ebfc0 T fftw_cost
00000000001ebfd0 T fftw_destroy_plan
00000000001ebff0 T fftw_estimate_cost
00000000001ec000 T fftw_execute
00000000001ec020 T fftw_execute_dft
00000000001ec0a0 T fftw_execute_dft_c2r
00000000001ec110 T fftw_execute_dft_r2c
00000000001ec180 T fftw_execute_r2r
00000000001ec1f0 T fftw_execute_split_dft
00000000001ec260 T fftw_execute_split_dft_c2r
00000000001ec270 T fftw_execute_split_dft_r2c
00000000001ec280 T fftw_export_wisdom
00000000001ec290 T fftw_export_wisdom_to_file
00000000001ec2a0 T fftw_export_wisdom_to_filename
00000000001ec2b0 T fftw_export_wisdom_to_string
00000000001efd90 T fftwf_alignment_of
00000000001efda0 T fftwf_alloc_complex
00000000001efdc0 T fftwf_alloc_real
0000000000837aa9 R fftwf_cc
00000000001efde0 T fftwf_cleanup
00000000001efdf0 T fftwf_cleanup_threads
0000000000837aaa R fftwf_codelet_optim
00000000001efe00 T fftwf_cost
00000000001efe10 T fftwf_destroy_plan
00000000001efe30 T fftwf_estimate_cost
00000000001efe40 T fftwf_execute
00000000001efe60 T fftwf_execute_dft
00000000001efee0 T fftwf_execute_dft_c2r
00000000001eff60 T fftwf_execute_dft_r2c
00000000001effe0 T fftwf_execute_r2r
00000000001f0060 T fftwf_execute_split_dft
00000000001f00e0 T fftwf_execute_split_dft_c2r
00000000001f00f0 T fftwf_execute_split_dft_r2c
00000000001f0100 T fftwf_export_wisdom
00000000001f0110 T fftwf_export_wisdom_to_file
00000000001f0120 T fftwf_export_wisdom_to_filename
00000000001f0130 T fftwf_export_wisdom_to_string
00000000001f0140 T fftwf_flops
00000000001f0150 T fftwf_forget_wisdom
00000000001f0160 T fftwf_fprint_plan
00000000001f0170 T fftwf_free
00000000001f0180 T fftwf_import_system_wisdom
00000000001f0190 T fftwf_import_wisdom
00000000001f01a0 T fftwf_import_wisdom_from_file
00000000001f01b0 T fftwf_import_wisdom_from_filename
00000000001f01c0 T fftwf_import_wisdom_from_string
00000000001f01d0 T fftwf_init_threads
00000000001ec2c0 T fftw_flops
00000000001f01f0 T fftwf_malloc
00000000001ec2d0 T fftw_forget_wisdom
00000000001f0200 T fftwf_plan_dft
00000000001f03b0 T fftwf_plan_dft_1d
00000000001f03d0 T fftwf_plan_dft_2d
00000000001f03f0 T fftwf_plan_dft_3d
00000000001f0420 T fftwf_plan_dft_c2r
00000000001f0600 T fftwf_plan_dft_c2r_1d
00000000001f0620 T fftwf_plan_dft_c2r_2d
00000000001f0640 T fftwf_plan_dft_c2r_3d
00000000001f0670 T fftwf_plan_dft_r2c
00000000001f0850 T fftwf_plan_dft_r2c_1d
00000000001f0870 T fftwf_plan_dft_r2c_2d
00000000001f0890 T fftwf_plan_dft_r2c_3d
00000000001f0e50 T fftwf_plan_guru64_dft
00000000001f1460 T fftwf_plan_guru64_dft_c2r
00000000001f17f0 T fftwf_plan_guru64_dft_r2c
00000000001f1b80 T fftwf_plan_guru64_r2r
00000000001f2850 T fftwf_plan_guru64_split_dft
00000000001f2e10 T fftwf_plan_guru64_split_dft_c2r
00000000001f2e20 T fftwf_plan_guru64_split_dft_r2c
00000000001f08c0 T fftwf_plan_guru_dft
00000000001f09d0 T fftwf_plan_guru_dft_c2r
00000000001f0ae0 T fftwf_plan_guru_dft_r2c
00000000001f0bf0 T fftwf_plan_guru_r2r
00000000001f0d00 T fftwf_plan_guru_split_dft
00000000001f0e30 T fftwf_plan_guru_split_dft_c2r
00000000001f0e40 T fftwf_plan_guru_split_dft_r2c
00000000001f2e30 T fftwf_plan_many_dft
00000000001f3050 T fftwf_plan_many_dft_c2r
00000000001f3290 T fftwf_plan_many_dft_r2c
00000000001f34d0 T fftwf_plan_many_r2r
00000000001f36f0 T fftwf_plan_r2r
00000000001f3890 T fftwf_plan_r2r_1d
00000000001f38c0 T fftwf_plan_r2r_2d
00000000001f38f0 T fftwf_plan_r2r_3d
00000000001f3940 T fftwf_plan_with_nthreads
00000000001ec2e0 T fftw_fprint_plan
00000000001f3950 T fftwf_print_plan
00000000001ec2f0 T fftw_free
00000000001f3960 T fftwf_set_timelimit
00000000001f3970 T fftwf_sprint_plan
0000000000837a88 R fftwf_version
00000000001ec300 T fftw_import_system_wisdom
00000000001ec310 T fftw_import_wisdom
00000000001ec320 T fftw_import_wisdom_from_file
00000000001ec330 T fftw_import_wisdom_from_filename
00000000001ec340 T fftw_import_wisdom_from_string
00000000001ec350 T fftw_init_threads
00000000001ec370 T fftw_malloc
00000000001ec380 T fftw_plan_dft
00000000001ec530 T fftw_plan_dft_1d
00000000001ec550 T fftw_plan_dft_2d
00000000001ec570 T fftw_plan_dft_3d
00000000001ec5a0 T fftw_plan_dft_c2r
00000000001ec780 T fftw_plan_dft_c2r_1d
00000000001ec7a0 T fftw_plan_dft_c2r_2d
00000000001ec7c0 T fftw_plan_dft_c2r_3d
00000000001ec7f0 T fftw_plan_dft_r2c
00000000001ec9d0 T fftw_plan_dft_r2c_1d
00000000001ec9f0 T fftw_plan_dft_r2c_2d
00000000001eca10 T fftw_plan_dft_r2c_3d
00000000001ecfd0 T fftw_plan_guru64_dft
00000000001ed5e0 T fftw_plan_guru64_dft_c2r
00000000001ed970 T fftw_plan_guru64_dft_r2c
00000000001edd00 T fftw_plan_guru64_r2r
00000000001eebc0 T fftw_plan_guru64_split_dft
00000000001ef180 T fftw_plan_guru64_split_dft_c2r
00000000001ef190 T fftw_plan_guru64_split_dft_r2c
00000000001eca40 T fftw_plan_guru_dft
00000000001ecb50 T fftw_plan_guru_dft_c2r
00000000001ecc60 T fftw_plan_guru_dft_r2c
00000000001ecd70 T fftw_plan_guru_r2r
00000000001ece80 T fftw_plan_guru_split_dft
00000000001ecfb0 T fftw_plan_guru_split_dft_c2r
00000000001ecfc0 T fftw_plan_guru_split_dft_r2c
00000000001ef1a0 T fftw_plan_many_dft
00000000001ef3c0 T fftw_plan_many_dft_c2r
00000000001ef600 T fftw_plan_many_dft_r2c
00000000001ef840 T fftw_plan_many_r2r
00000000001efa60 T fftw_plan_r2r
00000000001efc00 T fftw_plan_r2r_1d
00000000001efc30 T fftw_plan_r2r_2d
00000000001efc60 T fftw_plan_r2r_3d
00000000001efcb0 T fftw_plan_with_nthreads
00000000001efcc0 T fftw_print_plan
00000000001efcd0 T fftw_set_timelimit
00000000001efce0 T fftw_sprint_plan
0000000000837a54 R fftw_version
00000000001f5d70 T sfftw_cleanup_
00000000001f5d80 T sfftw_cleanup_threads_
00000000001f5d90 T sfftw_destroy_plan_
00000000001f5da0 T sfftw_execute_
00000000001f5db0 T sfftw_execute_dft_
00000000001f5dc0 T sfftw_execute_dft_c2r_
00000000001f5dd0 T sfftw_execute_dft_r2c_
00000000001f5de0 T sfftw_execute_r2r_
00000000001f5df0 T sfftw_execute_split_dft_
00000000001f5e00 T sfftw_execute_split_dft_c2r_
00000000001f5e10 T sfftw_execute_split_dft_r2c_
00000000001f5e20 T sfftw_export_wisdom_
00000000001f5e30 T sfftw_flops_
00000000001f5e40 T sfftw_forget_wisdom_
00000000001f5e50 T sfftw_import_system_wisdom_
00000000001f5e70 T sfftw_import_wisdom_
00000000001f5e90 T sfftw_init_threads_
00000000001f5eb0 T sfftw_plan_dft_
00000000001f5fe0 T sfftw_plan_dft_1d_
00000000001f6010 T sfftw_plan_dft_2d_
00000000001f6050 T sfftw_plan_dft_3d_
00000000001f60a0 T sfftw_plan_dft_c2r_
00000000001f6200 T sfftw_plan_dft_c2r_1d_
00000000001f6220 T sfftw_plan_dft_c2r_2d_
00000000001f6260 T sfftw_plan_dft_c2r_3d_
00000000001f62c0 T sfftw_plan_dft_r2c_
00000000001f6420 T sfftw_plan_dft_r2c_1d_
00000000001f6440 T sfftw_plan_dft_r2c_2d_
00000000001f6480 T sfftw_plan_dft_r2c_3d_
00000000001f64e0 T sfftw_plan_guru_dft_
00000000001f67d0 T sfftw_plan_guru_dft_c2r_
00000000001f6ab0 T sfftw_plan_guru_dft_r2c_
00000000001f6d90 T sfftw_plan_guru_r2r_
00000000001f7020 T sfftw_plan_guru_split_dft_
00000000001f7300 T sfftw_plan_guru_split_dft_c2r_
00000000001f75e0 T sfftw_plan_guru_split_dft_r2c_
00000000001f78c0 T sfftw_plan_many_dft_
00000000001f7a60 T sfftw_plan_many_dft_c2r_
00000000001f7bd0 T sfftw_plan_many_dft_r2c_
00000000001f7d40 T sfftw_plan_many_r2r_
00000000001f7ee0 T sfftw_plan_r2r_
00000000001f8030 T sfftw_plan_r2r_1d_
00000000001f8060 T sfftw_plan_r2r_2d_
00000000001f80e0 T sfftw_plan_r2r_3d_
00000000001f81a0 T sfftw_plan_with_nthreads_
00000000001f81b0 T sfftw_print_plan_

```

**Pull request closed without merging**
