### PR TITLE
Add new package: arpack

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
This package was explicitly removed in #5391 Is there any reason to restore it and not use `arpack-ng`?

**Comment by darmac** [comment]
We want support it just because CentOS still support both `arpack` and `arpack-ng`,
I'm afraid some one still use this package.

**Comment by adamjstewart** [comment]
I have no preference on this, what do you think @alalazo?

**Comment by alalazo** [comment]
@darmac Do you have a concrete use case that requires `arpack` but won't work with `arpack-ng`?

**Comment by darmac** [comment]
> @darmac Do you have a concrete use case that requires `arpack` but won't work with `arpack-ng`?

I didn't try that. if you think no one need this package, we can close this PR for now.

**Pull request closed without merging**
