### PR TITLE
boost: add v1.84.0

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Uh oh.  It looks like a lot of CI stacks aren't happy building this version of boost (https://gitlab.spack.io/spack/spack/-/pipelines/577970).

**Comment by hainest** [comment]
@tldahlgren That's... neat. I'm on vacation right now, but I'll take a look when I get back next week.

**Comment by hainest** [comment]
@tldahlgren The problem was that 1.84.0 dropped support for 98/03. I can split that change out into a separate PR to make this PR more topical, if folks prefer.

**Review by tldahlgren — APPROVED** [review]
LGTM and CI is passing.

**Pull request merged**
