### PR TITLE
Support packages which need to explicitly refer to dpcpp by name

### PR DESCRIPTION
**Pull request by scheibelp**
See: https://github.com/spack/spack/pull/26868

This compiler behaves exactly like `oneapi` but uses `dpcpp` instead of `icpx`. 

Arguably this could be folded into the `oneapi` compiler definition, although that would minimally require:

* Programmatic access of `link_paths` (e.g. right now it's a dictionary and we would have to replace that with an object that has more functionality to customize what is returned)
* A switch to the compiler object itself to activate/deactivate dpcpp (and users like `ginkgo` would have to flip this switch

It would be appealing to have a compiler automatically detect DPC++ and use dpcpp for it (in which case this wouldn't be needed assuming the logic mentioned in MKL's .cmake file were updated accordingly), although I don't know if that is feasible for the compiler to do.

### CODE REVIEW

**Comment by tcojean** [comment]
Thanks for this, I tested it with #26868 and it works really well. Having this extra `dpcpp` definition already simplifies things greatly! I only needed to do two small changes to get it fully working when using a pre-installed dpcpp:
+ add `dpcpp` to the list of C++ compilers in `spack/lib/spack/env/cc`.
+ Add as `extra_rpaths` in `~/.spack/linux/compilers.yml`:
      ``` 
      - /opt/intel/oneapi/compiler/latest/linux/lib
      - /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64/
      ```

**Comment by scheibelp** [comment]
>  I only needed to do two small changes to get it fully working when using a pre-installed dpcpp:
> add dpcpp to the list of C++ compilers in spack/lib/spack/env/cc.

(EDIT: I think I interpreted this wrong: see https://github.com/spack/spack/pull/27168#issuecomment-962378222) To check, do you mean you needed to create a link in `lib/spack/env/dpcpp` pointing to `lib/spack/env/cc`?

We also have support to detect libraries which should be RPATH'ed (generally stored into `implicit_rpaths`) I'm wondering why that isn't happening here but will have to think on how to investigate that.

**Comment by scheibelp** [comment]
>> I only needed to do two small changes to get it fully working when using a pre-installed dpcpp:
>> add dpcpp to the list of C++ compilers in spack/lib/spack/env/cc.

> To check, do you mean you needed to create a link in lib/spack/env/dpcpp pointing to lib/spack/env/cc?

Oh wait I think I know what you mean: does https://github.com/spack/spack/pull/27168/commits/18823d202c51414819b2b6a15eaf119d3a06bebb cover it?

**Comment by tcojean** [comment]
> > > I only needed to do two small changes to get it fully working when using a pre-installed dpcpp:
> > > add dpcpp to the list of C++ compilers in spack/lib/spack/env/cc.
> 
> > To check, do you mean you needed to create a link in lib/spack/env/dpcpp pointing to lib/spack/env/cc?
> 
> Oh wait I think I know what you mean: does [18823d2](https://github.com/spack/spack/commit/18823d202c51414819b2b6a15eaf119d3a06bebb) cover it?

Thanks! Yes that was exactly what I meant. Sorry that this wasn't clear.

**Comment by tcojean** [comment]
I think the current form looks good to me, what else are we missing?

**Review by tcojean — APPROVED** [review]
LGTM. Thanks for this!

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
