### PR TITLE
Add mpi_f08 variant to CP2K

### PR DESCRIPTION
**Pull request by RMeli**

### CODE REVIEW

**Comment by haampie** [comment]
Looks good. Do you know the following:

- Does `cp2k` use this internally? Or is this because `dbcsr` uses it? (I guess not, cause with `build_system=cmake` we use `dbcsr` as an actual dependency instead of the vendored copy)

- In #40494 I added this for `dbcsr`, and added a conflict `~mpi_f08 ^mpich@4.1:`, since only mpich 4.1+ errored without, same applies here?

- What about other MPI implementations than `mpich`? :thinking:

**Comment by RMeli** [comment]
1. It is needed also for CP2K. See https://github.com/cp2k/cp2k/pull/3044#issuecomment-1766259094.
2. Yes, the same applies here. I can add the same conflict, and also look into adding the same flag to the non-CMake builder (I have zero experience with it).
3. I have no idea... I only ever used `cray-mpich` as an alternative and never encountered the `type mismatch` issue.

**Comment by RMeli** [comment]
1. Needed at least when building CP2K manually with CMake, whith `dbcsr+mpi_f08` from Spack.

```
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:33099:62:

33099 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:28392:62:

28392 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:23685:62:

23685 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:18978:62:

18978 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:14271:62:

14271 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
/home/rmeli/git/cp2k/build-dlaf-test/src/mpiwrap/message_passing.F:9564:62:

 9564 |       CALL MPI_ALLOC_MEM(mp_size, mp_info, mp_baseptr, mp_res)
      |                                                              1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
make[2]: *** [src/CMakeFiles/cp2k.dir/build.make:17102: src/CMakeFiles/cp2k.dir/mpiwrap/message_passing.F.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:232: src/CMakeFiles/cp2k.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by haampie** [comment]
OK yeah, I was wondering whether it'd be better to just force the cmake define for particular MPI providers/versions instead of using a variant.

The issue is that a conflict on `"~mpi_f08 ^mpich@4.1:` will hold back mpich at 4.0, rather than toggling the variant value; defaults of the root packages are considered more important than versions of the dependencies.

Anyways, if it's too much to work it out, a variant is fine...

**Comment by RMeli** [comment]
The idea of the variant is that one can enable the F08 module even if it's not strictly required to compile. Is it possible to have the variant available and also force it for specific MPI providers/versions?

**Comment by haampie** [comment]
We don't have conditional default values ;p `conflicts(...)`  are the way :tm:

**Comment by mtaillefumier** [comment]
we need also a fix on cp2k side. I already pushed a commit fixing the issue. 
I wonder if we should not include a patch for the 2023.2 branch as well fixing the cp2k.pc name and other errors that @haampie reported to me.

**Review by mtaillefumier — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
