### PR TITLE
Added GPTune v3.0.0 and its dependency py-pymoo

### PR DESCRIPTION
**Pull request by liuyangzhuan**

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]
Checksum verified. Thanks!

**Review by wspear — CHANGES_REQUESTED** [review]
This PR didn't work for me. I got this error:
```
$ spack install gptune
==> Error: module 'spack.pkg.builtin.py-pymoo' has no attribute 'PyPymoo'
```

**Comment by liuyangzhuan** [comment]
@wspear Sorry my bad, a minor fix has been pushed. Can you try it again?

**Review by wspear — CHANGES_REQUESTED** [review]
This installed for me without trouble. I tried running `spack test run /{hash}` and killed the test after it sat for 15 minutes. If the expected runtime is longer than that I'll make this an approve but I suspect it's hanging.

This is the log output as of when I killed it:

```
==> Testing package gptune-3.0.0-3ppswdv
==> [2022-04-19-17:32:49.012768] Installing /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-3ppswdvhciqh6opngqbkkpdmiexlxjsu/.spack/test to /home/wspear/.spack/test/csbqt5rsp3jd5owsf5ql6nlo2b6c3els/gptune-3.0.0-3ppswdv/cache/gptune
==> [2022-04-19-17:33:00.867483] test: cp: expect command status in [0]
==> [2022-04-19-17:33:00.867722] '/bin/cp' 'run_env.sh' '/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-3ppswdvhciqh6opngqbkkpdmiexlxjsu/lib/python3.8/site-packages/gptune/.'
PASSED
==> [2022-04-19-17:33:00.899476] test: cp: expect command status in [0]
==> [2022-04-19-17:33:00.899934] '/bin/cp' 'run_env.sh' '/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-3ppswdvhciqh6opngqbkkpdmiexlxjsu/.spack/test/.'
PASSED
==> [2022-04-19-17:33:00.905387] gptune smoke test for Scalapack-PDGEQRF_RCI
==> [2022-04-19-17:33:00.905680] '/bin/bash' 'run_examples.sh'
```

**Comment by liuyangzhuan** [comment]
@wspear That's right. I've made another commit to fix the test error. Could you try it again?

**Comment by wspear** [comment]
@liuyangzhuan I let it run for 25 minutes. Looks like the test is still hanging. This is what the log contained after I killed it. Let me know if I can provide any more info.

```
wspear@yu:~/bin/SPACK/spack$ spack test results -l 2vrcbdpjs7ql2bioxafhcp5tl6z7zzw5
==> Results for test suite '2vrcbdpjs7ql2bioxafhcp5tl6z7zzw5':
==>   gptune-3.0.0-2pfg5ew FAILED
==> Testing package gptune-3.0.0-2pfg5ew
==> [2022-04-20-09:35:50.275423] Installing /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-2pfg5ewoangx3qhvtytlbae3437a4kgq/.spack/test to /home/wspear/.spack/test/2vrcbdpjs7ql2bioxafhcp5tl6z7zzw5/gptune-3.0.0-2pfg5ew/cache/gptune
==> [2022-04-20-09:35:50.599380] test: cp: expect command status in [0]
==> [2022-04-20-09:35:50.599581] '/bin/cp' 'run_env.sh' '/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-2pfg5ewoangx3qhvtytlbae3437a4kgq/lib/python3.8/site-packages/gptune/.'
PASSED
==> [2022-04-20-09:35:50.605344] test: cp: expect command status in [0]
==> [2022-04-20-09:35:50.605544] '/bin/cp' 'run_env.sh' '/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/gptune-3.0.0-2pfg5ewoangx3qhvtytlbae3437a4kgq/.spack/test/.'
PASSED
==> [2022-04-20-09:35:50.610700] gptune smoke test for Scalapack-PDGEQRF_RCI
==> [2022-04-20-09:35:50.610883] '/bin/bash' 'run_examples.sh'

======================== 1 failed, 0 passed of 1 specs =========================
```

**Comment by liuyangzhuan** [comment]
@wspear  did you forget to spack load gptune before spack test run gptune?

**Review by wspear — APPROVED** [review]
This works for me! (I did forget to load the package before running the test initially)

**Comment by liuyangzhuan** [comment]
@wspear Thanks!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
