### PR TITLE
edm4hep: Add latest version and Catch2 test depenency

### PR DESCRIPTION
**Pull request by tmadlener**
Add latest version and the dependency on Catch2 v3 for tests.

### CODE REVIEW

**Review by vvolkl — DISMISSED** [review]

**Comment by bernhardkaindl** [comment]
@tmadlener I get this from `spack install -v --test=root edm4hep`:
```py
     405    80% tests passed, 1 tests failed out of 5
     406    
     407    Total Test time (real) =   1.24 sec
     408    
  >> 409    The following tests FAILED:
     410          4 - test_rdf (Subprocess aborted)
```
LastTest.log has:
```py
4/5 Testing: test_rdf
4/5 Test: test_rdf
Command: "/home/kaindlb/spack/spack/.stage/spack-stage-edm4hep-0.3.2-6sfydbsdbxttpnjcj6ww5c2bmucb7zhg/spack-build-6sfydbs/test/test_rdf"
Directory: /home/kaindlb/spack/spack/.stage/spack-stage-edm4hep-0.3.2-6sfydbsdbxttpnjcj6ww5c2bmucb7zhg/spack-build-6sfydbs/test
"test_rdf" start time: Oct 12 14:39 UTC
Output:
----------------------------------------------------------
Create RDataFrame ...
Apply selectors and define new branches ...
Error in <TFile::ReadBuffer>: error reading all requested bytes from file edm4hep_events.root, got 252 of 300
Error in <TFile::Init>: edm4hep_events.root failed to read the file type data.
Error in <TFile::ReadBuffer>: error reading all requested bytes from file edm4hep_events.root, got 252 of 300
Error in <TFile::Init>: edm4hep_events.root failed to read the file type data.
terminate called after throwing an instance of 'std::runtime_error'
  what():  GetBranchNames: error in opening the tree events
<end of output>
Test time =   0.28 sec
----------------------------------------------------------
Test Failed.
"test_rdf" end time: Oct 12 14:39 UTC
"test_rdf" time elapsed: 00:00:00
```

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@tmadlener Please check if you can remove/disable/skip the test_rdf test case which fails on Ubuntu-18.04 (my container)

**Comment by tmadlener** [comment]
Apologies for the delayed response. Fixed a problem in the CMake config via an additional patch. Upstream fixes in key4hep/EDM4hep#126

**Review by bernhardkaindl — APPROVED** [review]
> Apologies for the delayed response. Fixed a problem in the CMake config via an additional patch. Upstream fixes in key4hep/EDM4hep#126

No, you did great! Looks great to me :+1:  Greetings from Kagran(Vienna) to HEPHY Vienna! :1st_place_medal: :)

**Pull request merged**
