### PR TITLE
os.link can not work for dir

### PR DESCRIPTION
**Pull request by fun2yang**

### CODE REVIEW

**Comment by fun2yang** [comment]
@becker33  it can be merge, or i need to change something  make the error become corret

**Comment by alalazo** [comment]
@fun2yang It seems something went very wrong with merges in this PR. Can you rebase it?

**Comment by fun2yang** [comment]
@alalazo i hane rebase it

**Comment by alalazo** [comment]
Apologies for the late reply. Can you add more description of the bug it fixes and the rationale of this PR? I am looking through old PRs and wondering if this one is still relevant.

**Comment by alalazo** [comment]
Closing as it had no reply in a few months. Feel free to reopen in case you disagree.

**Pull request closed without merging**
