### PR TITLE
hpctoolkit: fix broken patches

### PR DESCRIPTION
**Pull request by haampie**
The patches don't have a stable checksum:

```
7eb3a21c9bf9e1b65ef0375609665d36e5f7a74c664eb474cba728faada9baeb *411d62544717873432c49ef45c7cb99cc5de2fb8.patch
ccf7a319be0362d8a047953aa5d594b386acc7d6ea21fdc15925e926f83c7bd0 *511afd95b01d743edc5940c84e0079f462b2c23e.patch
```

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by mwkrentel** [comment]
@haampie @alalazo 
Well, I was going to update the checksums in #35662 or #35648 (now
reverted), but whatever.

So, does this mean that we should never use URL patches from gitlab?

And in the future, I would prefer you not to submit, approve and merge
patches to hpctoolkit all while I (as maintainer) am asleep.

In this case, the better fix is to delete the 411 patch and replace it
with a conflict as I did in #35662.  But it's short and I'll fix it in
#35662.

**Comment by alalazo** [comment]
> And in the future, I would prefer you not to submit, approve and merge patches to hpctoolkit all while I (as maintainer) am asleep.

@mwkrentel Apologies, that seemed a trivial fix for something that was reported broken since last Wednesday - so I went ahead and merged as requested by @haampie I'll keep that in mind that you prefer to review all changes to `hpctoolkit` in the future. Also, let me know if you have other preferred solutions, I'll try to prioritize reviewing them.

**Comment by alalazo** [comment]
The other thing to note is that, since `hpctoolkit` is in pipelines, failure to verify the checksum of patches means failure to pass pipelines tests.

**Comment by mwkrentel** [comment]
@alalazo I mainly wanted a chance to discuss updating the checksums
vs copying the patch.   Does this mean that we should never use a URL
patch from gitlab?

**Comment by alalazo** [comment]
> I mainly wanted a chance to discuss updating the checksums vs copying the patch

The chance is still there, and we can revert and go back to a URL if we find a way to have a stable shasum. This was mainly to avoid failures in pipelines due to a changing shasum. I didn't check yet if Gitlab has something similar to `?full_index=1` for GitHub

**Comment by mwkrentel** [comment]
When it comes to code and commits, I'm like John Roberts (Chief
Justice, US Supreme Court).  I prefer to make the smallest change that
gets the job done, unless there's a compelling reason to do otherwise.

In this case, if it were me, I would have just updated the sha256 sums
as the smaller change.  But now that they're switched to actual
patches, I prefer to leave it as is.  I'm going to delete one of them
in a couple days anyway.

**Comment by haampie** [comment]
I'm sure GitLab will at some point produce a slightly different diff
with one whitespace or line of context more ore less, etc. It'd be
better if we as a general rule would not allow any dynamically
generated content in source and patch urls.

**Pull request merged**
