### PR TITLE
mumps: Fix for problematic src/makefile patch (#20590)

### LINKED ISSUE #20590: mumps@5.3.3 fails: patch rejected
`mumps@5.3.3` is failing, I think, because of the patch introduced with 0150b394d7df0a3b6104f061514dfa5539bddde0

Using:
* `spack@develop` (1e971b62de76d731d5a220a0b271e105bf01caca)
* `Mon Dec 28 13:48:20 2020 -0800`
* Ubuntu 18.04 on x86_64

Concrete spec: [mumps-nnlqlp.spec.yaml.txt](https://github.com/spack/spack/files/5748938/mumps-nnlqlp.spec.yaml.txt)

```
$> spack install -f ./mumps-nnlqlp.spec.yaml
...
==> Installing mumps-5.3.3-nnlqlpa4wpvksountoctpeu25pndj2ui
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/27/27e7749ac05006bf8e81a457c865402bb72a42bf3bc673da49de1020f0f32011.tar.gz
##################################################################################################################################################################### 100.0%
1 out of 2 hunks FAILED -- saving rejects to file src/Makefile.rej
==> Patch /opt/spack/var/spack/repos/builtin/packages/mumps/mumps.src-makefile.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/opt/spack/var/spack/repos/builtin/packages/mumps/mumps.src-makefile.patch' '-d' '.'
```

@payerle @adamjstewart @scottwittenburg

### PR DESCRIPTION
**Pull request by payerle**
Minor change in src/Makefile between 5.2.0 and 5.3.3 causing patch to
break.  Split into 2 patchfiles

Should fix #20590

### CODE REVIEW

**Comment by eugeneswalker** [comment]
I didn't get the patch error, but I did get this:

```
$> (cd /opt/spack && git checkout mumps-patchfix-20590)
$> spack install mumps target=x86_64
...
==> Installing mumps-5.3.3-dqg3vrt7xrzzfzraf26jhsldqwzghfmf
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/27/27e7749ac05006bf8e81a457c865402bb72a42bf3bc673da49de1020f0f32011.tar.gz
##################################################################################################################################################### 100.0%
==> mumps: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j24' 'sexamples'

13 errors found in build log:
     287    (cd examples ; make s)
     288    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-mumps-5.3.3-dqg3vrt7xrzzfzraf26jhsldqwzghfmf/spack-src/examples'
     289    /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/openmpi-4.0.5-yzjauey6uo4qmgdb5zndem6miz6irbrt/bin/mpif90 -fPIC -O -DALLOW_NON_INIT -I.
             -I../include -I../src  -c ssimpletest.F -ossimpletest.o
     290    /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/openmpi-4.0.5-yzjauey6uo4qmgdb5zndem6miz6irbrt/bin/mpif90 -fPIC -O -DALLOW_NON_INIT -I.
             -I../include -I../src  -c ssimpletest_save_restore.F -ossimpletest_save_restore.o
     291    /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/openmpi-4.0.5-yzjauey6uo4qmgdb5zndem6miz6irbrt/bin/mpif90 -o ssimpletest -fPIC -O ssimp
            letest.o  ../lib/libsmumps.so ../lib/libmumps_common.so  -L../PORD/lib/ -lpord    -lpthread
     292    /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/openmpi-4.0.5-yzjauey6uo4qmgdb5zndem6miz6irbrt/bin/mpif90 -o ssimpletest_save_restore -
            fPIC -O ssimpletest_save_restore.o  ../lib/libsmumps.so ../lib/libmumps_common.so  -L../PORD/lib/ -lpord    -lpthread
  >> 293    ../lib/libmumps_common.so: undefined reference to `freeElimTree'
  >> 294    ../lib/libmumps_common.so: undefined reference to `firstPostorder'
  >> 295    ../lib/libmumps_common.so: undefined reference to `nextPostorder'
  >> 296    ../lib/libmumps_common.so: undefined reference to `SPACE_ordering'
  >> 297    collect2: error: ld returned 1 exit status
     298    Makefile:30: recipe for target 'ssimpletest' failed
  >> 299    make[1]: *** [ssimpletest] Error 1
     300    make[1]: *** Waiting for unfinished jobs....
  >> 301    ../lib/libmumps_common.so: undefined reference to `freeElimTree'
  >> 302    ../lib/libmumps_common.so: undefined reference to `firstPostorder'
  >> 303    ../lib/libmumps_common.so: undefined reference to `nextPostorder'
  >> 304    ../lib/libmumps_common.so: undefined reference to `SPACE_ordering'
  >> 305    collect2: error: ld returned 1 exit status
     306    Makefile:58: recipe for target 'ssimpletest_save_restore' failed
  >> 307    make[1]: *** [ssimpletest_save_restore] Error 1
     308    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-mumps-5.3.3-dqg3vrt7xrzzfzraf26jhsldqwzghfmf/spack-src/examples'
     309    Makefile:49: recipe for target 'sexamples' failed
  >> 310    make: *** [sexamples] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-mumps-5.3.3-dqg3vrt7xrzzfzraf26jhsldqwzghfmf/spack-build-out.txt
```

On `Ubuntu 18.04` for `x86_64` w/ `GCC 7.5.0`
Concrete spec: [mumps.spec.yaml.txt](https://github.com/spack/spack/files/5789535/mumps.spec.yaml.txt)
Full build log: [mumps-build-out.txt](https://github.com/spack/spack/files/5789529/mumps-build-out.txt)

**Comment by payerle** [comment]
Weird.  I did check on my system (RHEL8, gcc@8.4.0, openmpi@3.1.5; albeit spack 0.14.2) and it built successfully with spack.

I am confused by the errors reported; my build shows freeElimTree and the other missing symbols as being defined in libpord.so, which seems to be properly linked to in the compilation line.

If you still have the stage directory, can you see if libpord.so was built in spack-src/PORD/lib and if it contains the symbols being complained about?

Can you try building with the mumps.src-makefile*.patch commented out?  I just did so on my system and it built w/out issue (the patch was to improve ability to link to libs afterwards) --- I do not see how my patch could be causing these undefined symbol errors, so I just want to confirm if it is my patch or something else.  Again, I cannot reproduce the issue so need to ask you to do so.

**Comment by eugeneswalker** [comment]
> If you still have the stage directory, can you see if libpord.so was built in spack-src/PORD/lib and if it contains the symbols being complained about?

Yes, `spack-src/PORD/lib/libpord.so` contains all the symbols which are being flagged as undefined.

> Can you try building with the mumps.src-makefile*.patch commented out?

Builds just fine w/ your patch commented out.

**Comment by payerle** [comment]
I have managed to reproduce the issue in a Ubuntu18.04 based singularity container.
I am still confused as to what the issue is --- but at least have something to play with.

**Comment by payerle** [comment]
@eugeneswalker 
The above patch fixes the issue in my Ubuntu18 singularity container, so I am hoping it will resolve it in your case as well.

I don't claim to really understand what the underlying issue is, but adding libport as well as libmumps_common as explicit dependencies to libsmumps, etc. seems to have fixed it.

**Comment by eugeneswalker** [comment]
> ... so I am hoping it will resolve it in your case as well.

It works for me! Thank you! 

Should we merge this now? Do we wanna get anyone else's feedback first? What do you think?

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
