### PR TITLE
new package: r-devtools

### PR DESCRIPTION
**Pull request by glennpj**
This PR brings in the R devtools package and it dependencies.

### CODE REVIEW

**Comment by mathstuf** [comment]
> Fix flake8 errors

Are the templates that are auto-generated not flake8-clean?

**Comment by adamjstewart** [comment]
> Are the templates that are auto-generated not flake8-clean?

@mathstuf: Nope. The template doesn't have two empty lines between import and function. See #994, which replaced #945. I've been trying to fix them for a while now :)

As for this specific "Fix flake8 errors" commit, I wasn't aware that there was a problem with the R installation command. If there is, please let me know and I'll add it to the template in #994.

**Comment by mathstuf** [comment]
I don't know :) . I'm not a fan of how strict flake8 is and all the "appease flake8" commits it has spawned, but it's weird seeing new packages needing flake8 touchups especially when they're largely made of code written by spack itself. Seems like unnecessary work to me.

**Comment by adamjstewart** [comment]
I agree that the template at least needs to be correct. I have mixed feelings about flake8. Personally, I think when we merge PRs, all of the commits should be squashed (GitHub has automatic ways of doing this). That way it doesn't really matter in the long run. But it is annoying when you edit a file in the Spack library and a one line change requires hundreds of lines of flake8 reformatting. I've been avoiding it because there are so many open PRs that already fix flake8 for that file.

**Comment by mathstuf** [comment]
For dependency types, I just fixed the flake8 errors that were reported for the code I touched (or was a line away from for line spacing and such). As for squashing, I think that it's a bad idea; it's a bad solution to people making bad history on branches. The dependency types branch commits do not belong together; it'd be *way* too noisy of a commit if it were squashed.

**Comment by adamjstewart** [comment]
Yes, but in general, Spack would be very broken if we went back a few commits from HEAD. The current HEAD should be fine, and the tip of the merged branch should be fine, but the inbetween commits are generally riddled with bugs that are caught and fixed. It makes sense to me to squash all of these upon merging.

**Comment by glennpj** [comment]
The template in develop is not flake8 clean. I pulled the template code from #994 and was using that but that needs to have different wrapping on the R command. I think what happened here is that I ran things through autopep8 but that did not get it quite the way flake8 wanted it so I had to fix it. I think I was at 80 characters on a line rather than 79. I modified my local template to avoid the issue going forward but had not gotten around to commenting on this in #994 yet.

**Comment by mathstuf** [comment]
I think that commits fixing bugs introduced in the branch should be squashed directly into the commit introducing it so that every commit does work on its own (as much as possible). That doesn't require squashing the whole branch together though.

**Pull request merged**
