### PR TITLE
update gmsh to v4.11.1

### PR DESCRIPTION
**Pull request by bfovet**

### CODE REVIEW

**Review by alecbcs — APPROVED** [review]
Confirmed SHA. Looks good to me

**Comment by tldahlgren** [comment]
Look like the build for the package in one of the E4S stacks is failing, see https://gitlab.spack.io/spack/spack/-/jobs/7305576.

**Comment by bfovet** [comment]
Looks like there are missing headers in `GModelIO_OCC.cpp`. I'll try building with the `oce` package instead of `opencascade` and see what that does.

**Comment by isaachyw** [comment]
Hello, is there some update on this error, I have the same issue with my pull request [PR](https://github.com/spack/spack/pull/39112).

**Comment by bfovet** [comment]
Yes just took some time to look at it. Gmsh 4.11.1 builds with `opencascade` but not with `oce` because of missing headers in `GModelIO_OCC.cpp`. Looks like it's been patched just days after the 4.11.1 release : [missing includes for OCC 6.9](https://gitlab.onelab.info/gmsh/gmsh/-/commit/48c7a17ab1a04b3bf1b0cc454673600603cc3ada).
Closing this PR. I'll open a another one when a new version is released.

**Pull request closed without merging**
