### PR TITLE
New versions: geant4@10.7.2, geant4-data@10.7.2

### PR DESCRIPTION
**Pull request by wdconinc**
No major changes for this bugfix release, but nevertheless we would like to take advantage of them when 0.17 is tagged :-)

Release notes: https://geant4-data.web.cern.ch/ReleaseNotes/Patch4.10.7-2.txt

Maintainer: @drbenmorgan

### CODE REVIEW

**Comment by wdconinc** [comment]
Tested on a few more systems.

**Review by vvolkl — DISMISSED** [review]

**Comment by wdconinc** [comment]
Gentle ping @drbenmorgan :-)

**Review by alalazo — DISMISSED** [review]
@wdconinc Ping me in a few days if you don't receive any reply and I'll merge, thanks!

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by drbenmorgan — DISMISSED** [review]
Apologies for the delay @wdconinc, all good for me and thanks for the update!

**Comment by drbenmorgan** [comment]
@alalazo, I *think* the `ci/gitlab-ci` failure is unrelated to this PR? If so, I'll go ahead and merge, but wanted to be sure!

**Comment by alalazo** [comment]
@wdconinc Can you please rebase on the latest develop? That _should_ ensure that Gitlab is not encountering issues with the DB format.

**Comment by wdconinc** [comment]
Rebased.

**Review by alalazo — APPROVED** [review]

**Comment by wdconinc** [comment]
`ci/gitlab-ci — Pipeline failed` in `e4s-pr-generate` seems unrelated.

**Comment by drbenmorgan** [comment]
@spackbot run pipeline

**Comment by drbenmorgan** [comment]
O.k., I don't have perms to trigger the pipeline - @alalazo modulo the pipeline fail, this is good to merge, but I can't override the auto-merge. Could you merge or advise how to fix the pipeline issue, thanks!

**Comment by alalazo** [comment]
@drbenmorgan Pipelines are under maintenance, so let's give it some more time. If they're not functional by tomorrow, ping me again for a merge. Sorry for the inconvenience.

**Comment by wdconinc** [comment]
Pinging.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
