### PR TITLE
Autoconf: add spack external find support

### PR DESCRIPTION
**Pull request by adamjstewart**
```yaml
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /Users/Adam/.spack/darwin/.spack-env/view
```

### CODE REVIEW

**Comment by adamjstewart** [comment]
Ping @alalazo

**Review by alalazo — APPROVED** [review]

**Comment by roblatham00** [comment]
Maybe this should be a separate bug report, but on the other hand this appears to be a regression from the 0.15.3 release

On older environments, autoconf package now seems to think "autoconf" is some random file in the autom4te directory.  I don't know how this is related to spack external support exactly...

When I try to build automake, it is unable to find a working autoconf.  instead here's what it finds:

```
configure:3019: checking whether autoconf works
configure:3027: cd conftest && autoconf -o /dev/null conftest.ac
Can't open perl script "/nfs2/robl/src/mochi-all/spack/opt/spack/linux-ubuntu14.04-broadwell/gcc-8.2.1/autoconf-2.69-rjic3u4gul42fqgtdejkzuqxeoshbjny/bin/autom4te --language=autoconf --output=/dev/null conftest.ac": No such file or directory
configure:3030: $? = 2
```
Here's some more information about autoconf as built by spack: as you can see it's an older system.  We've also seen this on Ubuntu-16.04
```
$ spack find -fvld autoconf
==> 1 installed package
-- linux-ubuntu14.04-broadwell / gcc@8.2.1 ----------------------
rjic3u4 autoconf@2.69%gcc 
ekgjlkg     m4@1.4.18%gcc +sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8
yxfe36t         libsigsegv@2.12%gcc 
dcmol6w     perl@5.30.3%gcc +cpanm+shared+threads
uwwtufa         berkeley-db@18.1.40%gcc 
5vdzi4l         gdbm@1.18.1%gcc 
i3jwko6             readline@8.0%gcc 
327asun                 ncurses@6.2%gcc ~symlinks+termlib
```

(adam if you still have MCS credentials, this was compute002)

**Comment by roblatham00** [comment]
Oh, and while the commit says "spack external find support", I have not run "spack external find"  -- my packages.yaml file has no autoconf stanza

**Comment by adamjstewart** [comment]
I wonder if this is related to #19580, there was a recent change in `sbang` that might be the issue. You could try reverting to the commit before that PR. This doesn't seem related to external detection of autoconf.

**Comment by roblatham00** [comment]
Maybe related, but I'm skeptical.  

Autoreconf is not failing for me.  In the linked issue, something tried to execute the script `/home/mumble/gcc-8.3.0/autoconf-2.69-mumble/bin/autoreconf -ivf -I /home/mumble`, including the spaces, instead of separating script from arguments. 

 In my case, something thinks it needs to execute a script from deep inside the autoconf build tree (the autom4te directory specifically).

**Comment by chuckatkins** [comment]
This looks exactly the issue that I reported in #19580 .  I saw it crop up in a variety of places with autoreconf in some form or another.

**Comment by roblatham00** [comment]
well clearly i'm wrong:  aebf20ebdc seems to fix the autoconf/automake problem I was seeing.

**Comment by adamjstewart** [comment]
Sometimes it's good to be wrong. Glad the issue is fixed!

**Pull request merged**
