### PR TITLE
add z-checker

### PR DESCRIPTION
**Pull request by disheng222**
z-checker: http://github.com/CODARcode/Z-checker
a library to characterize the data and check the compression results of lossy compressors

I have added variant of mpi and removed the useless comment description. Thanks.

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Missing dependency on MPI

**Review by adamjstewart — APPROVED** [review]

**Comment by disheng222** [comment]
I just added the dependency of MPI. Thanks.

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/z-checker/package.py:24: [W291] trailing whitespace
var/spack/repos/builtin/packages/z-checker/package.py:25: [E301] expected 1 blank line, found 0
```

**Comment by disheng222** [comment]
Done. Thanks.

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/z-checker/package.py:24: [W291] trailing whitespace
```

**Comment by disheng222** [comment]
Done. Thanks.

**Pull request merged**
