### PR TITLE
Make the state of the Python Front End (PFE) and Python data reader

### PR DESCRIPTION
**Pull request by bvanessen**
support sticky so that the concretizer does not arbitrarily disable them.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@bvanessen This one is :heavy_check_mark: as soon as you fix style.

**Comment by bvanessen** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@bvanessen I pushed the style change, hope you don't mind

**Pull request merged**
