### PR TITLE
Trilinos Dependencies for Windows

### PR DESCRIPTION
**Pull request by jpopelar**
Includes Windows packaging for a number of Trilinos dependencies, including hdf5, boost, openblas, py-setuptools

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is this PR supposed to modify hundreds of files?

**Comment by jpopelar** [comment]
No; this branch was based off an older version of develop that I was left
in charge of. I'll rebase it here soon

**Comment by jpopelar** [comment]
Remaking this abomination; a lot of the work is no longer relevant (hdf5 merged in a while ago and openblas has a new buildsystem). Will open a new PR with a fresh branch momentarily

**Comment by jpopelar** [comment]
Now in #34622; will update the flowchart accordingly

**Pull request closed without merging**
