### PR TITLE
Prepare hpcviewer for Mac OS platform

### PR DESCRIPTION
**Pull request by pramodk**
* Adapt URL parsing for Mac OS
 * Adapt install method for Mac OS

Todo:
- [x] Update versions
- [x] Polish implementation

cc: @mwkrentel 

Note: We need #23054 for testing this PR:

```console
→ spack spec -I hpcviewer
Input spec
--------------------------------
 -   hpcviewer

Concretized
--------------------------------
 -   hpcviewer@2021.03%apple-clang@12.0.0 arch=darwin-catalina-skylake
 -       ^openjdk@11.0.2%apple-clang@12.0.0 arch=darwin-catalina-skylake

→ spack install hpcviewer
==> Installing openjdk-11.0.2-kvhanirclvrqbpqlytiiosgbycxynphf
==> No binary for openjdk-11.0.2-kvhanirclvrqbpqlytiiosgbycxynphf found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
==> Fetching https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz
...
[+] /Users/pramod/Downloads/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/openjdk-11.0.2-kvhanirclvrqbpqlytiiosgbycxynphf
==> Installing hpcviewer-2021.03-cz4t4lloaq7yig52b6obbyknpc4rgyjf
==> No binary for hpcviewer-2021.03-cz4t4lloaq7yig52b6obbyknpc4rgyjf found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
==> Fetching http://hpctoolkit.org/download/hpcviewer/2021.03/hpcviewer-2021.03-macosx.cocoa.x86_64.zip
....
==> hpcviewer: Successfully installed hpcviewer-2021.03-cz4t4lloaq7yig52b6obbyknpc4rgyjf
  Fetch: 5.79s.  Build: 0.93s.  Total: 6.71s.
[+] /Users/pramod/Downloads/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/hpcviewer-2021.03-cz4t4lloaq7yig52b6obbyknpc4rgyjf
```

and it should be ready:

```
→ module load hpcviewer-2021.03-apple-clang-12.0.0-cz4t4ll
→ hpcviewer
```
image

### CODE REVIEW

**Comment by mwkrentel** [comment]
@pramodk Thanks for doing this !

I checked the Linux side, and that seems Ok.  I guess if it was me,
I'd make the new keys a triple, eg, `('2021.03', 'linux', 'x86_64')`
instead of hyphenated, but whatever.

Also, let's update the package description to:

```
class Hpcviewer(Package):
    """Binary distribution of hpcviewer and integrated traceviewer
    for the Rice HPCToolkit (MacOS x86_64, and Linux x86_64, ppc64le
    and aarch64).  Note: hpctoolkit databases are platform independent,
    so you don't need to install hpctoolkit to run the viewer, and
    it's common to run hpcrun and hpcviewer on different machines."""
```

As for the Macos versions, my Macbook is currently stuck in a bad
state where it won't run the Xcode tools (git).  When I get that
resolved, then I'll check out the Macos side, which is the whole point
of the PR.

But without running this, I guess I don't see how spack connects the
Java 11 dependency for hpcviewer on a Mac that doesn't already have
Java 11.

@laksono Any thoughts ?

**Comment by pramodk** [comment]
> I checked the Linux side, and that seems Ok. I guess if it was me,
> I'd make the new keys a triple, eg, ('2021.03', 'linux', 'x86_64')
> instead of hyphenated, but whatever.

I was thinking that but I did this way because `openjdk` package has this scheme. So thought to do the same way.

>  When I get that resolved, then I'll check out the Macos side, which is the whole point of the PR.

Ok. I am testing on Mac OS. So I am sure that this is working.

> But without running this, I guess I don't see how spack connects the Java 11 dependency for hpcviewer on a Mac that doesn't already have Java 11.

hpcviewer has dependency with Java. So it installs OpenJDK and rest should work? (May be I should remove my system Java and test again).

**Comment by mwkrentel** [comment]
Or, you could install system Java 8 and see how the viewer reacts.
Or, install both old (java 8) and new (java 11) versions of the viewer and 
see if they both run without making any system adjustment.
But I never run spack on Macos, so I'm just guessing.

**Comment by pramodk** [comment]
I did following:

```bash
# remove java
sudo rm -rf /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin  
sudo rm -rf /Library/PreferencePanes/JavaControlPanel.prefPane  
sudo rm -rf /Library/Application\ Support/Oracle/Java/ 
sudo rm -rf /Library/Java/JavaVirtualMachines 

# now there is no java
○ → java
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

# install fresh hpcviewer with openjdk

○ → spack install hpcviewer
==> Installing openjdk-11.0.2-pdv6wir3l7vnqmmz6mrf2fnnlcv6fbf4
==> No binary for openjdk-11.0.2-pdv6wir3l7vnqmmz6mrf2fnnlcv6fbf4 found: installing from source
/Users/pramod/Downloads/spack/lib/spack/spack/architecture.py:205: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
  warnings.warn(msg.format(compiler))
==> Fetching https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz
########################################################################################################################################################################## 100.0%
==> No patches needed for openjdk
==> openjdk: Executing phase: 'install'
==> openjdk: Successfully installed openjdk-11.0.2-pdv6wir3l7vnqmmz6mrf2fnnlcv6fbf4
  Fetch: 12.60s.  Build: 3.78s.  Total: 16.38s.
[+] /Users/pramod/Downloads/spack/opt/spack/darwin-bigsur-skylake/apple-clang-12.0.0/openjdk-11.0.2-pdv6wir3l7vnqmmz6mrf2fnnlcv6fbf4
==> Installing hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5
==> No binary for hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5 found: installing from source
/Users/pramod/Downloads/spack/lib/spack/spack/architecture.py:205: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
  warnings.warn(msg.format(compiler))
==> Using cached archive: /Users/pramod/Downloads/spack/var/spack/cache/_source-cache/archive/ef/ef7598b2a8d6574f315915452015d4b50ad8631165a872d1fbccac80284db160.zip
==> No patches needed for hpcviewer
==> hpcviewer: Executing phase: 'install'
==> hpcviewer: Successfully installed hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5
  Fetch: 0.09s.  Build: 0.92s.  Total: 1.01s.
[+] /Users/pramod/Downloads/spack/opt/spack/darwin-bigsur-skylake/apple-clang-12.0.0/hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5

# try only hpcviewer module

○ → module show hpcviewer-2021.03-apple-clang-12.0.0-rsjhuiq
-------------------------------------------------------------------
/Users/pramod/Downloads/spack/share/spack/modules/darwin-bigsur-skylake/hpcviewer-2021.03-apple-clang-12.0.0-rsjhuiq:

module-whatis   {Binary distribution of hpcviewer and hpctraceviewer for the Rice HPCToolkit (Linux x86_64, ppc64le and aarch64). Note: hpctoolkit databases are platform independent, so you don't need to install hpctoolkit to run the viewers and it's common to run hpcrun and hpcviewer on different machines.}
prepend-path    PATH /Users/pramod/Downloads/spack/opt/spack/darwin-bigsur-skylake/apple-clang-12.0.0/hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5/bin
prepend-path    CMAKE_PREFIX_PATH /Users/pramod/Downloads/spack/opt/spack/darwin-bigsur-skylake/apple-clang-12.0.0/hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5/
-------------------------------------------------------------------

○ → module load hpcviewer-2021.03-apple-clang-12.0.0-rsjhuiq
○ → which hpcviewer
/Users/pramod/Downloads/spack/opt/spack/darwin-bigsur-skylake/apple-clang-12.0.0/hpcviewer-2021.03-rsjhuiqdi2wp3sn2a4yeydwrsoluiht5/bin/hpcviewer
○ → hpcviewer
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

Script started, output file is /dev/null
java_home: unrecognized option `--request'
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

# there is java module auto-loaded yet and hence hpcviewer didn't work. Try loading it:

○ → module load openjdk-11.0.2-apple-clang-12.0.0-pdv6wir
○ → hpcviewer
```

image

So everything looking good!

**Review by adamjstewart — APPROVED** [review]

**Comment by mwkrentel** [comment]
@pramodk I get different results and I think I see why.  For me, java
dies with "does not contain the JNI_Create_JavaVM symbol." because
I don't have java 11 installed.

First, you're using modules, but I don't have modules installed.
Did you do this with spack's bootstrap for modules?
Or, are the modules somehow builtin to the Macos shell?

Also, it looks like you load both the viewer and java modules, is that
right?  That's how hpcviewer finds java by loading the java module.

I'd like to see if there is a way to make this work without using
modules, or if we have to use modules, then write the java path into
the hpcviewer module.  On Linux, we do this with the install script.

I think we're close, but I'd like to make this a little easier for the
user and maybe more macos-thematic, if that's possible.

**Comment by pramodk** [comment]
> First, you're using modules, but I don't have modules installed.
> Did you do this with spack's bootstrap for modules?
> Or, are the modules somehow builtin to the Macos shell?

I typically use `brew` to install common packages:

```
brew install modules
source /usr/local/opt/modules/init/bash
```
and it should setup `module`.

> Also, it looks like you load both the viewer and java modules, is that
> right? That's how hpcviewer finds java by loading the java module.

Thats correct. But note that we don't need modules nowadays i.e. you can justo use `spack load` to load packages: `spack load openjdk hpcviewer` 

> I'd like to see if there is a way to make this work without using
> modules, or if we have to use modules, then write the java path into
> the hpcviewer module.

I was thinking the same i.e. I would also prefer not generate module or load openjdk. So would support adding env variables in hpcviewer itself.

**Comment by mwkrentel** [comment]
Ok, I think `spack load` is a good alternative to modules.

I fixed my Xcode problems, but I'm seeing some strange (and broken)
results depending on how I run things.  Let me check this with
@laksono for the best way to launch the viewer and connect with java.

**Comment by mwkrentel** [comment]
Ok, I discussed the Macos side with Laksono.  There are a few more
things we need to do to make the Macos side work like it should.
They're all pretty short but important.

The first three are for the darwin install only.  The last one is for
the linux install.

(1) There needs to be an extra directory between the spack install
prefix and the Contents directory, named 'hpcviewer.app'.  So:

```
  ...
    darwin-bigsur-broadwell
      apple-clang-12.0.0
        hpcviewer-2021.03-gpqletix66isc3fr53kfgq5rl5teqpt2
	  hpcviewer.app
	    Contents
	      Eclipse
              Info.plist
              MacOS
              Resources
```

The hpcviewer.app directory is very important for the Macos side.  You
can either cd to the `hpcviewer-2021.03` directory and say `open hpcviewer.app`,
or you can click your way through Finder and double
click on that icon.  Either of those will open the viewer.

(2) I would prefer making the `bin` symlink relative, so it's contents
would be `hpcviewer.app/Contents/MacOS`.

(3) We need to add two lines to the beginning of the `hpcviewer.ini`
file in the `Eclipse` directory.  The lines are: `-vm` and the full
path to the `java` binary in the `bin` directory of the java/jdk
package.  These go on separate lines as the first two lines of the
file.  For example:

```
hpcviewer.ini:

-vm
/Users/krentel/viewer/install/darwin-bigsur-broadwell/apple-clang-12.0.0/openjdk-11.0.2-d5g4zxhilgfjuuugcvjhywkxe2ybxbtu/bin/java
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
...
```

Note that the value for `-vm` (line 2) ends with `.../bin/java`  (it's a long line).
Also, it's just one dash in `-vm`.

This is very important for how the viewer finds the right java.  It
also means that we don't really need to add a prepend-path PATH or
JAVA_HOME for the viewer module to find java.


(4) The `@when('platform=linux')` decorator is not correct because it
misses cray.  Note that in this context, `platform` is the spack
platform (where linux and cray are different), not the python
platform.  To fix it, we need to use the python plaform like this:

```
    # Both hpcviewer and trace viewer have an install script.
    @when(platform.system().lower() == 'linux')
    def install(self, spec, prefix):
        ...
```

So, it seems like a lot, but they're all short and all necessary.  In
the end, it will be thematically correct for Macos.

Btw, I figured out how hpcviewer was picking up the correct java
without your doing anything explicit for it.  In spack, hpcviewer
depends on openjdk, so when you ran `spack load hpcviewer`, spack
automatically also loaded the openjdk package.  You can see this with
`spack find --loaded`.

Or, with modules, if you load both, then you'll get the right java.

Anyway, make these changes, then I'll run through the steps to test it
one last time, and then we'll be done!

Thanks !

**Pull request closed without merging**
