### PR TITLE
Return non-zero from CDash reporter when errors are detected

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Review by scottwittenburg — APPROVED** [review]
I didn't try this, but it looks pretty straightforward.  If it's working for you, let's get it in!  Thanks @zackgalbreath 🎉

**Comment by zackgalbreath** [comment]
Indeed, it does what it's supposed to. Here's a snippet from my local manual testing.

```
$ spack install  --cdash-upload-url=http://localhost/CDash/submit.php?project=MyTestProj tar cppflags="-std=notreal"

...
View your build results here:
libiconv: http://localhost/CDash/buildSummary.php?buildid=45
tar: http://localhost/CDash/buildSummary.php?buildid=46
==> Error: Errors encountered, see above for more details

$ echo $?
1
```

**Comment by eugeneswalker** [comment]
One thing I've started seeing since this was merged is `spack install` exiting non-zero because of "configure errors" that show in CDash, but that in actual fact do not prevent the package from being successfully installed. So you've got `spack install` successfully installing the target package, but `spack install` ultimately exits non-zero because of what CDash identifies as configure errors. I think @scottwittenburg  has also observed this in his pipelines too.

**Comment by zackgalbreath** [comment]
Thanks for the heads up, I'm on the case.

**Pull request merged**
