### PR TITLE
ninja: New version 1.11.1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by michaelkuhn — APPROVED** [review]
works for me

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by alalazo** [comment]
`py-scipy` is failing as in a few other PRs. @adamjstewart FYI

**Comment by haampie** [comment]
For the py-scipy issue see https://github.com/spack/spack/issues/33237, we can fix it separately and then merge this pr.

**Comment by eschnett** [comment]
@spackbot run pipeline

**Pull request merged**
