### PR TITLE
Update Petaca

### PR DESCRIPTION
**Pull request by zjibben**
This PR adds recent releases of Petaca.

### CODE REVIEW

**Review by pbrady — APPROVED** [review]
LGTM!

**Comment by nncarlson** [comment]
If it's not too late can you add petaca 24.04 to the new releases?  It includes workarounds for a gfortran bug that affected 23.12.

**Comment by zjibben** [comment]
@nncarlson No problem, I just added it now.

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256s.

**Pull request merged**
