### PR TITLE
docs/getting_started: s/Macintosn/Macintosh/;

### PR DESCRIPTION
**Pull request by goxberry**
Minor typo fix for docs.

### CODE REVIEW

**Comment by goxberry** [comment]
@citibeth Found this typo, wanted to give you a heads up. Thank you for all the work you've done on the docs!

**Comment by citibeth** [comment]
Can you submit a PR?

**Comment by tgamblin** [comment]
This is a PR.  It’s merged.

**Comment by citibeth** [comment]
Clearly I need to go to bed...

**Pull request merged**
