### PR TITLE
libffi %oneapi@2023: -Wno-error=implicit-function-declaration

### PR DESCRIPTION
**Pull request by eugeneswalker**
`libffi %oneapi@2023.0.0` requires explicit `-Wno-error=implicit-function-declaration` to prevent
```
  >> 202    ../src/tramp.c:262:22: error: call to undeclared function 'open_tem
            p_exec_file'; ISO C99 and later do not support implicit function de
            clarations [-Wimplicit-function-declaration]
     203      tramp_globals.fd = open_temp_exec_file ();
     204                         ^
     205    1 error generated.
  >> 206    make[3]: *** [Makefile:1319: src/tramp.lo] Error 1
```

@wspear

### CODE REVIEW

**Review by wspear — APPROVED** [review]

**Comment by eugeneswalker** [comment]
CI failing at least in part because of issues unrelated to this PR:
* [aws-ahug-aarch64-pr-generate](https://gitlab.spack.io/spack/spack/-/jobs/5254415)

```
Error: This pipeline generated hashes known to be broken on develop:
```

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
Closing as already completed via https://github.com/spack/spack/pull/34634

**Pull request closed without merging**
