### PR TITLE
Make gcc work on OS X

### PR DESCRIPTION
**Pull request by eschnett**
Don't use binutils on OS X; it is not necessary there, and many binutils are not supported on OS X (e.g. assembler or linker).

Disable go language on OS X; it is not supported there.

### CODE REVIEW

**Comment by eschnett** [comment]
Note that this patch is built on the "correct-cc" branch.

**Comment by alalazo** [comment]
As in #257 I would prefer not to be forced to call my architecture `linux` to enable binutils build : on our site, for instance, we tend to identify the system type in spack by processor + network characteristics e.g. `x86_E5v2_IntelIB`.

I understand though that OS X is an issue that should be taken care of. Maybe we could leverage some `sys` and `os` functionality to detect in which operative system we are running. This plus dependencies that support predicates should do the trick.

@tgamblin : what do you think? Are `os.name`, `sys.platform` and the likes portable enough to write a simple os detection predicate? I was thinking of something like:
```python
depends_on("binutils~libiberty", when=os_not_in(['OSX']))
```

**Comment by eschnett** [comment]
@alalazo If you are using essentially arbitrary strings to describe your system architecture, then you're circumventing all architecture-specific settings in Spack. I appreciate the need to differentiate between different systems in your setup, but saying "my system is not Linux" if it actually is might lead to problems down the line. It might be that Spack is lacking a capability here.

However -- what if a package actually needs to distinguish between Linux or Windows, or Linux and OS X (as is the case here?) At the moment, things work since you can say "my system is not Linux" as long as I correctly identify my Darwin systems as "my system is Darwin", allowing architecture-specific differences. But in the long term this is unlikely to work.

Your proposal `when_os_in(OSX)` is what the current `=darwin` already does, except that you're saying "what is currently called 'architecture' should be called 'os' instead, and people should be free to set 'architecture' to anything they want (and Spack doesn't need to encode the OS into the package specification since people will never install packages for multiple OSes on the same system)". If you look at the documentation, you'll see that architecture is meant to differentiate between entities such as "linux", "darwin", "bgq", etc.

You could e.g. modify your architecture descriptions to keep "linux-x86_64" as prefix. Then, if Spack matches architecture prefixes, things would continue to work for you. Using prefixes is also convenient since then "linux" can mean both "linux-i368" and "linux-x86_64".

**Comment by alalazo** [comment]
> If you look at the documentation, you'll see that architecture is meant to differentiate between entities such as "linux", "darwin", "bgq", etc.

RTFM argument : please point me to the section where those things are said, as I cannot find them. I see though from the [examples](http://llnl.github.io/spack/basic_usage.html#seeing-installed-packages) that `chaos_5_x86_64_ib` is used as an architecture name (and would not comply with `=linux`). [Here](http://llnl.github.io/spack/basic_usage.html#architecture-specifier) it says that *"This is mostly used for architectures that need cross-compilation..."*. This gave me the impression that the main purpose of *architecture* would have been to cross-compile software for BG or similar machines (i.e. to reserve names for those unique architectures), not to discriminate OSes. But I may of course be wrong on that. I think @tgamblin  may clarify the intent of this part of the spec.

> Your proposal when_os_in(OSX) is what the current =darwin already does, except that you're saying "what is currently called 'architecture' should be called 'os' instead, and people should be free to set 'architecture' to anything they want (and Spack doesn't need to encode the OS into the package specification since people will never install packages for multiple OSes on the same system)".

People are already free to set architecture to anything they want. In fact its value is computed like this :
```python
def sys_type():
    """Returns a SysType for the current machine."""
    methods = [get_sys_type_from_spack_globals,
               get_sys_type_from_environment,
               get_sys_type_from_platform]

    # search for a method that doesn't return None
    sys_type = None
    for method in methods:
        sys_type = method()
        if sys_type: break

    # Couldn't determine the sys_type for this machine.
    if sys_type is None:
        return "unknown_arch"

    if not isinstance(sys_type, basestring):
        raise InvalidSysTypeError(sys_type)

    return sys_type
```
It could be set from globals, read from the environment or guessed from the module `platform`. My guess is that `sys.platform` could be the right tool to solve the OS X problem (instead of the achitecture) as :

1. its return values are specified in the python documentation (they are not strings on which we need to agree upon)
2. it has a granularity which seems just right for what we need

To use something like that the keywork `when=` in the `depends_on` directive must be able to accept a boolean as a value.

> You could e.g. modify your architecture descriptions to keep "linux-x86_64" as prefix. Then, **if Spack matches architecture prefixes**, things would continue to work for you. Using prefixes is also convenient since then "linux" can mean both "linux-i368" and "linux-x86_64".

Personally, I find this solution rather disappointing : `linux-i386` is not `linux` and as far as the spec grammar is concerned architecture is a single id. That said, my point in contributing to spack is not making things *work for me*, but rather making things *work*. The comment I made above was just to point out that spreading `when='=linux'` all over the packages may solve the OS X problem at expenses of introducing glitches for other non OS X users, and that there may be a cleaner solution to this.

> If you are using essentially arbitrary strings to describe your system architecture, then you're circumventing all architecture-specific settings in Spack. I appreciate the need to differentiate between different systems in your setup, but saying "my system is not Linux" if it actually is might lead to problems down the line. It might be that Spack is lacking a capability here.

They're not arbitrary string : we actually do have E5 v2 Intel processors with Infiniband interconnects :-) Oh, and I am not saying "My system is not linux" anywhere!

Cheers,
M.

**Comment by adamjstewart** [comment]
@eschnett: If you are abandoning this pull request in favor of #364, can you close this PR?

**Comment by eschnett** [comment]
Superseded by #364.

**Pull request closed without merging**
