### PR TITLE
py-torch-nvidia-apex: ~cuda does not build

### PR DESCRIPTION
**Pull request by adamjstewart**
Discovered in CI

See https://github.com/NVIDIA/apex/issues/1498

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM.  Am curious as to the motivation behind the switch from `install_options` to `global_options`.

**Comment by adamjstewart** [comment]
[Installation instructions](https://github.com/NVIDIA/apex#linux) say to use `--global-option`. I'm guessing we were using `--install-option` by accident.

**Comment by tldahlgren** [comment]
@aweits Did you want to comment on this PR before it is merged?

**Review by aweits — APPROVED** [review]
lgtm.

**Pull request merged**
