### PR TITLE
Updated intel-gtpin package.py for  most recent version, GTPin 3.0.

### PR DESCRIPTION
**Pull request by rashawnLK**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by rashawnLK** [comment]
@tldahlgren , I am not sure what to do next. I fixed the style issues found in the first automated review or PR, and it looks like all the automated check passed, but I see that at least one approving review is required by reviewer(s) with write access. Is this you?

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
