### PR TITLE
patch directive : fixed retrieval from urls ( fixes #1584 )

### LINKED ISSUE #1584: support archived patches ( https://path/to/my.patch.gz )
some packages distributed patches as archives. My understanding is that Spack currently can't unarchive patches before trying to apply them.

Of course a workaround is to download patches and ship them inside Spack.

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications :
 - [x] add support for 'gz' archives
 - [x] fixed bugs with URL patches
 - [x] updated nwchem

### CODE REVIEW

**Comment by alalazo** [comment]
@tgamblin @adamjstewart I think the compression and the stage/fetcher part need some additional cleaning and testing. Is there some work already on-going ?

**Comment by tgamblin** [comment]
@alalazo: not that I know of unless @scheibelp has refactored that.  I don't believe he has, though.

**Comment by alalazo** [comment]
> I think this would actually be pretty easy to do if you just make the patch directive call resource behind the scenes

@tgamblin I'll have a look if this can be done easily and come back asap. I was wondering if you see cases in which the `if self.url:` path may fail. The logic there seems to me quite fragile and not very well tested ...

**Comment by adamjstewart** [comment]
@alalazo I'm not working on any stage/fetcher logic at the moment so go ahead.

**Comment by scheibelp** [comment]
> alalazo: not that I know of unless scheibelp has refactored that. I don't believe he has, though.

I have a minor PR #1822 which fixes a bug and does a minor amount of refactoring.

I was working on a larger refactor but that isn't a PR yet (and appears compatible).

**Comment by alalazo** [comment]
@tgamblin 

> We need checksums on remotely fetched hashes.

Done. Using `resource`s seemed non trivial (as they are expected to be copied somewhere within the stage of the master package). I also refactored a bit `patch.py`. If there are no additional requests I'll consider this ready.

**Comment by tgamblin** [comment]
If you don't use resources, how do the patches get mirrored?

**Comment by alalazo** [comment]
@tgamblin I didn't check if they are mirrored... can you give me a pointer where the code doing the mirroring is located ?

**Comment by tgamblin** [comment]
Based on the changes, I think this is not actually being mirrored.  If you look at `mirror.py` in `add_single_spec`, all the mirror stuff happens there.  It mirrors the main archive for the package as well as the various resources that are fetched with it.

**Comment by alalazo** [comment]
The latest commit seems to work for me
```
$ ls var/spack/cache/nwchem
Config_libs66.patch.gz   Dplot_tolrho.patch.gz     Ga_defs.patch.gz           Notdir_fc.patch.gz    Sym_abelian.patch.gz    Txs_gcc6.patch.gz          Xccvs98.patch.gz
Cosmo_dftprint.patch.gz  Driver_smalleig.patch.gz  Gcc6_macs_optfix.patch.gz  nwchem-6.6.tar.gz     Tddft_mxvec20.patch.gz  Util_getppn.patch.gz       Zgesvd.patch.gz
Cosmo_meminit.patch.gz   Ga_argv.patch.gz          Gcc6_optfix.patch.gz       Raman_displ.patch.gz  Tools_lib64.patch.gz    Util_gnumakefile.patch.gz
```
Can somebody else confirm this ? @davydden ?

**Comment by davydden** [comment]
caching works for me as well:
```
$ ls ~/spack/var/spack/cache/nwchem/
Config_libs66.patch.gz		Dplot_tolrho.patch.gz		Ga_defs.patch.gz		Notdir_fc.patch.gz		Tddft_mxvec20.patch.gz		Util_getppn.patch.gz		Zgesvd.patch.gz
Cosmo_dftprint.patch.gz		Driver_smalleig.patch.gz	Gcc6_macs_optfix.patch.gz	Raman_displ.patch.gz		Tools_lib64.patch.gz		Util_gnumakefile.patch.gz	nwchem-6.6.tar.gz
Cosmo_meminit.patch.gz		Ga_argv.patch.gz		Gcc6_optfix.patch.gz		Sym_abelian.patch.gz		Txs_gcc6.patch.gz		Xccvs98.patch.gz
```

**Comment by alalazo** [comment]
Thanks @davydden . Then I think that the two issues : 

- [x] md5 checksum
- [x] caching of patches

have been taken care of, at least from user perspective. As I said, I think the whole stage / fetching mechanism may need some rethinking as the classes involved appear tightly coupled together, but I would save that for a later PR (after SC16).

**Comment by tgamblin** [comment]
LGTM thanks!

**Pull request merged**
