### PR TITLE
Add ReFrame 3.6.3

### PR DESCRIPTION
**Pull request by vkarak**

### CODE REVIEW

**Review by victorusu — DISMISSED** [review]
`lgtm`

**Comment by haampie** [comment]
can you fix

```
var/spack/repos/builtin/packages/reframe/package.py:7: [I100] Import statements are in the wrong order. 'import shutil' should be before 'from spack import *' and in a different group.
var/spack/repos/builtin/packages/reframe/package.py:7: [I201] Missing newline between import groups. 'import shutil' is identified as Stdlib and 'from spack import *' is identified as Application.
```

you can install `flake8-import-order` to fix it locally (run ./share/spack/qa/run-style-tests), it's a new check

**Comment by vkarak** [comment]
Yes, I'll do that.

**Comment by vkarak** [comment]
@haampie Is the CI failure now relevant to this PR? I've done the style changes requested.

**Review by haampie — APPROVED** [review]

**Pull request merged**
