### PR TITLE
Add packages for three common homomorphic encryption libraries.

### PR DESCRIPTION
**Pull request by wohlbier**
HElib, Palisade, and Seal. Also add package for number theoretic library NTL.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by wohlbier** [comment]
@spackbot run pipeline

**Comment by wohlbier** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Please rebase to `develop` to get the `hpx` package corrections that are causing the pipeline to fail.

**Comment by wohlbier** [comment]
@tldahlgren will do. When do you think this might be merged? Thanks!

**Pull request closed without merging**
