### PR TITLE
blaze: add v3.8.1, v3.8.2

### PR DESCRIPTION
**Pull request by nilsvu**

### CODE REVIEW

**Comment by alalazo** [comment]
Pipeline failures seems to be due to selecting the wrong architecture for the runner :sob: 

- https://gitlab.spack.io/spack/spack/-/pipelines/726149

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by nilsvu** [comment]
something went wrong with the CI pipeline again

**Comment by alalazo** [comment]
This is the fix for pipelines https://github.com/spack/spack/pull/44582 Trying to check why it fails Windows CI

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
