### PR TITLE
adding support for perl@5.35.0 and above to output version-less binaries

### LINKED ISSUE #29409: perl no longer installs un-versioned binaries
For singularity HPC, we create recipes that can confidently say the path and name of a binary in advance. E.g., for our perl recipe we have:

```yaml
aliases:
  perl: /opt/view/bin/perl
  perlbug: /opt/view/bin/perlbug
  perldoc: /opt/view/bin/perldoc
  perlivp: /opt/view/bin/perlivp
  perlthanks: /opt/view/bin/perlthanks
```
As of perl 5.34, this tree (and the subsequent view) turns out correctly - e.g., I have a perl / perlthanks and all the expected executables in bin.
```bash
$ ls opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/perl-5.34.0-bvgnm2ejnajpvaruta22d5c24g6qi4zu/bin/
corelist  h2ph       perl        perlthanks  pod2text    ptardiff   xsubpp
cpan      h2xs       perl5.34.0  piconv      pod2usage   ptargrep   zipdetails
cpanm     instmodsh  perlbug     pl2pm       podchecker  shasum
enc2xs    json_pp    perldoc     pod2html    prove       splain
encguess  libnetcfg  perlivp     pod2man     ptar        streamzip
```
However with 5.35.0 I no longer have any un-versioned binaries. They all end in the version.

```bash
 ls opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/perl-5.35.0-smm2auqgf4jwkvi7uzvrvjmqdxcwqtkc/bin/
corelist5.35.0   json_pp5.35.0     pl2pm5.35.0       ptardiff5.35.0
cpan5.35.0       libnetcfg5.35.0   pod2html5.35.0    ptargrep5.35.0
cpanm            perl5.35.0        pod2man5.35.0     shasum5.35.0
enc2xs5.35.0     perlbug5.35.0     pod2text5.35.0    splain5.35.0
encguess5.35.0   perldoc5.35.0     pod2usage5.35.0   streamzip5.35.0
h2ph5.35.0       perlivp5.35.0     podchecker5.35.0  xsubpp5.35.0
h2xs5.35.0       perlthanks5.35.0  prove5.35.0       zipdetails5.35.0
instmodsh5.35.0  piconv5.35.0      ptar5.35.0
```
I suspect this was implemented to make them install nicely alongside one another, but I consider it a bug that the install cannot output the plain binary. If this was done at the level of perl (e.g., outside of spack) I'd want to suggest that (for spack) we go ahead and create links so that the correct names are present. I think this should be the default (what is expected) and turned off with a variant if someone has issue. Thanks!

### PR DESCRIPTION
**Pull request by vsoch**
It is expected behavior for a software install to generate binaries that are naked, or not with a version. After perl 5.34.x it looks like this is not the case for perl, and all binaries are generated with a versioned suffix. This is not ideal for tools or people that use the install directory and expect to find, for example, just perl. This fix will, for versions 5.35.0 and later, ensure that we do a final pass through the install directory and given a binary that ends with the version, we also generate a link to its version-less self (only if it does not already exist). For some niche cache where this is not desired, a variant can be flipped to disable it.
I have made it the default because as a user I expect my binaries without a weird version suffix. 

Here is a default install of the latest (5.35.0):

```bash
$ spack install perl@5.35.0
```
results in a bin with and without versioned binaries:

```bash
opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/perl-5.35.0-d5v2mtmjk7lu5k6f6gasm7y53ht4c452/bin/
├── corelist
├── corelist5.35.0
├── cpan
├── cpan5.35.0
├── cpanm
├── enc2xs
├── enc2xs5.35.0
├── encguess
├── encguess5.35.0
├── h2ph
├── h2ph5.35.0
├── h2xs
├── h2xs5.35.0
├── instmodsh
├── instmodsh5.35.0
├── json_pp
├── json_pp5.35.0
├── libnetcfg
├── libnetcfg5.35.0
├── perl
├── perl5.35.0
├── perlbug
├── perlbug5.35.0
├── perldoc
├── perldoc5.35.0
├── perlivp
├── perlivp5.35.0
├── perlthanks
├── perlthanks5.35.0
├── piconv
├── piconv5.35.0
├── pl2pm
├── pl2pm5.35.0
├── pod2html
├── pod2html5.35.0
├── pod2man
├── pod2man5.35.0
├── pod2text
├── pod2text5.35.0
├── pod2usage
├── pod2usage5.35.0
├── podchecker
├── podchecker5.35.0
├── prove
├── prove5.35.0
├── ptar
├── ptar5.35.0
├── ptardiff
├── ptardiff5.35.0
├── ptargrep
├── ptargrep5.35.0
├── shasum
├── shasum5.35.0
├── splain
├── splain5.35.0
├── streamzip
├── streamzip5.35.0
├── xsubpp
├── xsubpp5.35.0
├── zipdetails
└── zipdetails5.35.0
```

And to say "only generate me a versioned bin I'm a monster"

```bash
$ spack install perl +versioned-bin
```
results in a monster's bin:

```bash
├── corelist5.35.0
├── cpan5.35.0
├── cpanm
├── enc2xs5.35.0
├── encguess5.35.0
├── h2ph5.35.0
├── h2xs5.35.0
├── instmodsh5.35.0
├── json_pp5.35.0
├── libnetcfg5.35.0
├── perl5.35.0
├── perlbug5.35.0
├── perldoc5.35.0
├── perlivp5.35.0
├── perlthanks5.35.0
├── piconv5.35.0
├── pl2pm5.35.0
├── pod2html5.35.0
├── pod2man5.35.0
├── pod2text5.35.0
├── pod2usage5.35.0
├── podchecker5.35.0
├── prove5.35.0
├── ptar5.35.0
├── ptardiff5.35.0
├── ptargrep5.35.0
├── shasum5.35.0
├── splain5.35.0
├── streamzip5.35.0
├── xsubpp5.35.0
└── zipdetails5.35.0
```
:japanese_ogre: 

This will close #29409

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by haampie** [comment]
Isn't this just because odd numbered perl minor versions correspond to development releases?

**Comment by vsoch** [comment]
No idea but we need a fix for it.

**Comment by haampie** [comment]
I'm saying this is the case for all perl development releases `5.35.x`, `5.33.x`, `5.31.x`, so it's not "after perl 5.34". I don't think introducing a variant to change this is a good idea. Maybe we can default to adding symlinks in bin/ for development releases. That's for @glennpj to decide. (or maybe just drop development releases?)

**Comment by vsoch** [comment]
I’m good with either of those.. I just need a fix. :)

**Comment by glennpj** [comment]
Looking at the versions in the package file, it looks like only "stable" versions were put in spack, until 5.31. I think it is possibly useful to have development versions available in spack as some people may need them. I think in most cases a stable release is preferred and the spack recipe currently prefers the latest stable release. I think that is sensible so it seems that this change is not really necessary for "production" use. I suppose it would be convenient to have the symlinks if one is working with a development version but it also seems like having to type the version is a useful reminder that it is a development version.

With all of that said, if the symlinks are desired for development versions I do not think a variant is appropriate. If the symlinks are important then I think testing for odd numbered versions is a better way to go.

**Comment by vsoch** [comment]
I’m happy to change however is desired, let me know what y’all decide!

**Comment by glennpj** [comment]
> I’m happy to change however is desired, let me know what y’all decide!

My opinion is that this could be changed to

1. drop the variant
2. check for odd versions and add symlinks
3. make sure that the latest even numbered version is preferred
I know this is not changed in this PR, I am only stating that for completeness.

**Comment by vsoch** [comment]
Ok will do! ETA tomorrow because I’m off to bed. Thanks for the feedback @glennpj.

**Comment by haampie** [comment]
Looking at perl I wonder if we need multiple preferred versions so that `spack install perl@:5.33` installs 5.32 instead of 5.33 by default... See https://github.com/spack/spack/pull/29456

**Comment by alalazo** [comment]
#29456 has been merged

**Comment by vsoch** [comment]
oh nice! So @alalazo does that make this issue here defunct?

**Pull request closed without merging**
