### PR TITLE
asp: memoize the list of all target_specs to speed-up setup phase

### PR DESCRIPTION
**Pull request by alalazo**
This modification shaves a few seconds on the setup phase of each solve.

### CODE REVIEW

**Comment by aweits** [comment]
This looks promising, I've been doing cumulative timing tests against concretizing all packages:
#20423 yields this up to "chai":
```console
{'setup': 740.4090619087219, 'load': 0.6598348617553711, 'ground': 634.3016400337219, 'solve': 728.9909963607788, 'reparse': 203.29622197151184}

```
this yields:
```console
{'setup': 387.70626878738403, 'load': 0.535090446472168, 'ground': 399.3583173751831, 'solve': 757.533967256546, 'reparse': 139.9334716796875}
```
Will update when this runs to completion.

**Comment by alalazo** [comment]
@aweits Can you try #20426 + this cherry picked?

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
@aweits: does your setup number include grounding?

**Comment by aweits** [comment]
> @aweits: does your setup number include grounding?

No, these are cumulative summations of the timer calls as they are with the addition of an additional "reparse" phase just before timer.write()

**Pull request merged**
