### PR TITLE
New package for the Mercurial (hg) version control system

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by adamjstewart** [comment]
I added a [`py-mercurial`](https://github.com/adamjstewart/spack/blob/e450016d275a44e02cfc652fa6bad5df256ae5d3/var/spack/repos/builtin/packages/py-mercurial/package.py) package to #1576. Not sure which one we should go with. Mercurial does indeed come with a site-packages directory when built with Python.

**Comment by eschnett** [comment]
A user of Mercurial doesn't know that Mercurial is built on Python. Mercurial isn't used via `import mercurial` in a Python script (as you'd say e.g. for `import h5py`); Mercurial is used via stand-alone scripts that happen to require a Python interpreter. Thus I went without the `py-` prefix in the package name, and without an `extends` clause.

**Comment by adamjstewart** [comment]
I'm willing to agree with that. The only possible problem is if there's another Python module out there that depends on `py-mercurial`, but until we see that, I agree that it's not very likely. Let's go with your package.

**Comment by tgamblin** [comment]
we have some other packages like `geos` that are primarily not Python packages but `extend` `python`.  I agree with _not_ using the python convention for these.

If we have tags (to categorize packages) it might make sense to get rid of prefixes like this, although I think it helps to namespace things to some extent...

**Pull request merged**
