### PR TITLE
r-viridislite: add 0.4.0

### PR DESCRIPTION
**Pull request by manuelakuhn**

### CODE REVIEW

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Confirmed the sha256; however, the user can no longer fetch the earlier versions.

The way to fetch the earlier versions needs to be changed.  You might find some useful info in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#versions-and-fetching.

**Comment by manuelakuhn** [comment]
I see what you mean, and can reproduce it. When I try to fetch on older version on this branch, I get
```
» spack fetch r-viridislite@0.3.0
==> Fetching https://mirror.spack.io/_source-cache/archive/78/780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af.tar.gz
==> Error: [Errno 2] No such file or directory: '$stage/spack-stage-r-viridislite-0.3.0-5hd72gunkmyu3sfqhm7ttncl34t5rrts/viridisLite_0.3.0.tar.gz'
```
but `install` works.
This does not really make sense because using cran sets the `url` and `list_url` to the same as they were before: https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/r.py#L52

I could also reproduce the error by changing the original file like this:
```diff
@@ -10,7 +10,7 @@ class RViridislite(RPackage):
     """viridisLite: Default Color Maps from 'matplotlib' (Lite Version)"""
 
     homepage = "https://github.com/sjmgarnier/viridisLite"
-    url      = "https://cloud.r-project.org/src/contrib/viridisLite_0.2.0.tar.gz"
+    url      = "https://cloud.r-project.org/src/contrib/viridisLite_0.4.0.tar.gz"
     list_url = "https://cloud.r-project.org/src/contrib/Archive/viridisLite"
 
     version('0.3.0', sha256='780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af')
```
Is this a bug in fetch?

**Comment by tldahlgren** [comment]
> I see what you mean, and can reproduce it. When I try to fetch on older version on this branch, I get
> 
> ```
> » spack fetch r-viridislite@0.3.0
> ==> Fetching https://mirror.spack.io/_source-cache/archive/78/780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af.tar.gz
> ==> Error: [Errno 2] No such file or directory: '$stage/spack-stage-r-viridislite-0.3.0-5hd72gunkmyu3sfqhm7ttncl34t5rrts/viridisLite_0.3.0.tar.gz'
> ```
> 
> but `install` works. This does not really make sense because using cran sets the `url` and `list_url` to the same as they were before: https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/r.py#L52
> 
> I could also reproduce the error by changing the original file like this:
> 
> ```diff
> @@ -10,7 +10,7 @@ class RViridislite(RPackage):
>      """viridisLite: Default Color Maps from 'matplotlib' (Lite Version)"""
>  
>      homepage = "https://github.com/sjmgarnier/viridisLite"
> -    url      = "https://cloud.r-project.org/src/contrib/viridisLite_0.2.0.tar.gz"
> +    url      = "https://cloud.r-project.org/src/contrib/viridisLite_0.4.0.tar.gz"
>      list_url = "https://cloud.r-project.org/src/contrib/Archive/viridisLite"
>  
>      version('0.3.0', sha256='780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af')
> ```
> 
> Is this a bug in fetch?

Good question.  AFAICT There are a combination of things going on.  

Older versions appear to be in the mirror/cache so the process of fetching the source from URL(s) in the package isn't being done.  There's also more complexity surrounding alternate algorithms related to fetching, etc.

**Comment by glennpj** [comment]
I am not seeing the fetch problem. I disabled all mirrors and cleaned all caches and tested.
```console
spack clean --all ; spack fetch r-viridislite@0.3.0 ; ls -R /tmp/gpjohnsn/spack-stage
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
==> Fetching https://cloud.r-project.org/src/contrib/Archive/viridisLite/viridisLite_0.3.0.tar.gz
/tmp/gpjohnsn/spack-stage/:
spack-src  spack-stage-r-viridislite-0.3.0-kzbizcoiimjxsnhr3km67tf3qhwg2u4h

/tmp/gpjohnsn/spack-stage/spack-src:

/tmp/gpjohnsn/spack-stage/spack-stage-r-viridislite-0.3.0-kzbizcoiimjxsnhr3km67tf3qhwg2u4h:
viridisLite_0.3.0.tar.gz
```
I then added the spack public mirror back and tried with that.
```console
spack clean --all ; spack fetch r-viridislite@0.3.0 ; ls -R /tmp/gpjohnsn/spack-stage/
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
==> Fetching https://mirror.spack.io/_source-cache/archive/78/780ea12e7c4024d5ba9029f3a107321c74b8d6d9165262f6e64b79e00aa0c2af.tar.gz
/tmp/gpjohnsn/spack-stage/:
spack-src  spack-stage-r-viridislite-0.3.0-kzbizcoiimjxsnhr3km67tf3qhwg2u4h

/tmp/gpjohnsn/spack-stage/spack-src:

/tmp/gpjohnsn/spack-stage/spack-stage-r-viridislite-0.3.0-kzbizcoiimjxsnhr3km67tf3qhwg2u4h:
viridisLite_0.3.0.tar.gz
```

**Review by glennpj — APPROVED** [review]

**Comment by manuelakuhn** [comment]
Yes, this really seems to be a caching problem. I only ran "spack clean -d" which was not enough and resulted in the error. On a new spack clone (with this PR added) fetching works for the old version and new version. Running `spack clean --all` on my normal spack clone also removes the error.

**Comment by tldahlgren** [comment]
I should've been clearer. When I originally said the older versions can no longer be fetched, I meant `spack checksum` fails to fetch them.

```
$ spack checksum r-viridislite 0.4.0 0.3.0 0.2.0
==> Found 3 versions of r-viridislite:
  
  0.4.0  https://cloud.r-project.org/src/contrib/viridisLite_0.4.0.tar.gz
  0.3.0  https://cloud.r-project.org/src/contrib/viridisLite_0.3.0.tar.gz
  0.2.0  https://cloud.r-project.org/src/contrib/viridisLite_0.2.0.tar.gz

==> Fetching https://cloud.r-project.org/src/contrib/viridisLite_0.4.0.tar.gz
==> Something failed on https://cloud.r-project.org/src/contrib/viridisLite_0.3.0.tar.gz, skipping.  (All fetchers failed for spack-stage-3dq04ist)
==> Something failed on https://cloud.r-project.org/src/contrib/viridisLite_0.2.0.tar.gz, skipping.  (All fetchers failed for spack-stage-b0wtzsvo)

    version('0.4.0', sha256='849955dc8ad9bc52bdc50ed4867fd92a510696fc8294e6971efa018437c83c6a')
```

**Review by tldahlgren — COMMENTED** [review]
I can only confirm that the sha256 is correct for the latest version.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Interesting GitHub UI for "removing" a change request.  I have "approved" the changes since this is not the first package to switch to the `cran` property.

However, I have reservations about the fact that `spack checksum` no longer works for older packages, making it harder to confirm the `sha256` of older versions is correct.

**Comment by manuelakuhn** [comment]
Unfortunately the problem with `spack checksum` is already known and was already there before this PR, see #26977 and #11680

**Comment by tldahlgren** [comment]
> Unfortunately the problem with `spack checksum` is already known and was already there before this PR, see #26977 and #11680

Ah.  I hadn't checked so was not aware of #26977.  I thought #11680 had been fixed but that *might* explain things.

I had noticed `r.py`'s `list_url` depends on `https://cloud.r-project.org/src/contrib/Archive/` but, IIRC, I had problems/delays accessing it; whereas I had more success accessing `https://cloud.r-project.org/src/contrib/00Archive/`.  I just checked and those issues no longer appear to be occurring (i.e., I can access the tarballs from either URL, which now have timestamps from earlier today).

**Pull request merged**
