### PR TITLE
license year bump

### PR DESCRIPTION
**Pull request by haampie**
Why don't we just drop years (like curl did).

### CODE REVIEW

**Comment by tldahlgren** [comment]
Oh fun! 

```
==> Error: 78 improperly licensed files
```

**Comment by haampie** [comment]
> Oh fun!
> 
> ```
> ==> Error: 78 improperly licensed files
> ```

This was missed in 2022 ;)

So was the docs year.  See #35000

**Review by tldahlgren — APPROVED** [review]
Confirmed all of the copyrights with `Lawrence` have been updated for the files as of https://github.com/spack/spack/pull/34921/commits/cb1d0a501767a2f20f9aabccb35bf623e986857f.

**Comment by tgamblin** [comment]
> This was missed in 2022 ;)

I built a year of leeway into the `license.py` script to avoid breaking `develop` and in-flight PRs when these updates go in.  You can have a one-year-out-of-date copyright, but not two.  I think it's ultimately better because then the chore falls on some maintainer, not 100 PRs.

I'm in favor of dropping years.  I agree it's a lot of useless churn.
* Curl did this here: https://github.com/curl/curl/pull/10205/
* This blog post (from the comments there) is pretty useful: https://hynek.me/til/copyright-years/

I'll look at putting together something for this.

**Pull request merged**
