### PR TITLE
CoinHSL: Support the Meson build system

### PR DESCRIPTION
**Pull request by AndrewLister-STFC**
The current recipe for CoinHSL is outdated and only supports versions that are no longer available to download.
This PR adds support for the Meson build system that newer versions require while maintaining backwards compatibility.

There are 2 types of version for CoinHSL, a partial version (referred to as "archive") with reduced support but less restrictive licence, and a full version. The archive version has no dependencies, although I'm not sure how best to capture that in the recipe.

Q by @AndrewLister-STFC: Any suggestions on the best way to define a different set of dependencies for the archive and full versions?
A by @bernhardkaindl: It is possible to set different dependencies with `when`:
```py
    depends_on("dependency1", when="@:2.21")  # Versions up to 2.21 get dependency1
    depends_on("dependency2", when="@2.22:")  # Versions since 2.22 get dependency2
```
Does this answer your question?

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@AndrewLister-STFC
> Any suggestions on the best way to define a different set of dependencies for the archive and full versions?

It is possible to set different dependencies with `when`:
```py
    depends_on("dependency1", when="@:2.21")  # Versions up to 2.21 get dependency1
    depends_on("dependency2", when="@2.22:")  # Versions since 2.22 get dependency2
```
Does this answer your question?

**Comment by AndrewLister-STFC** [comment]
> @AndrewLister-STFC
> 
> > Any suggestions on the best way to define a different set of dependencies for the archive and full versions?
> 
> It is possible to set different dependencies with `when`:
> 
> ```python
>     depends_on("dependency1", when="@:2.21")  # Versions up to 2.21 get dependency1
>     depends_on("dependency2", when="@2.22:")  # Versions since 2.22 get dependency2
> ```
> 
> Does this answer your question?

I ended up using something like this, although I now have a very odd versioning scheme to accommodate it:
```
archive-2023.11.17
archive-...
2014.01.10 -\
2014.01.17  |
2015.06.23  |- legacy builds (on autotools)
2019.05.21 -/
2023.11.17
...
```

Anything before "b" or after "2022" can use meson, anything before "b" doesn't need any deps, anything after "2022" has deps (blas, lapack, metis). The legacy autotools build that was already in the recipe is in the middle.

Ideally this would be in a different order but all I could find was operations on the ranges. I'd like the order to be:
```
2014.01.10 -\
2014.01.17  |
2015.06.23  |- legacy builds (on autotools)
2019.05.21 -/
2023.11.17-archive
2023.11.17
...
```

Having tested this, we've found an issue in the meson build system with the libmetis_path argument. I'll have to put in a new release and skip some versions in the spack recipe to make it work with the spack location of metis. I should have some time to work on this next week.

**Comment by AndrewLister-STFC** [comment]
I can rebase and squash the commits on this if that's preferred for the repo

**Review by bernhardkaindl — APPROVED** [review]
@AndrewLister-STFC wrote:
> I can rebase and squash the commits on this if that's preferred for the repo

That would not be needed because the merge-to-develop maintainers will usually select GitHub's option to let GitHub squash the commits when merging a PR unless it's better to not squash the commits.

In this case, as I think your question means that you're/this PR is ready to merge and as no other reviewers or assignees showed up, I'd approve.

I'm going to enable auto-merge, setup for auto-squash after (when) the GitLab CI finishes successfully, which is likely many, many, many hours out:

As an initial step, GitLab PR will be pending waiting until the current commit on develop that you rebased on has successfully built in GitLab CI, then this PR can start building in GitLab CI.

That means it will likely take maybe even 24 hours or so until the pending wait of the GitLab CI frees this push to be built, so there is plenty of time left, and patience (due to the rebase to the current develop).

If you find an issue before the automerge was executed, just change the PR to draft again, which should disable the auto-merge. Also, another push would disable the auto-merge and restart CI with the new push.

**Pull request merged**
