### PR TITLE
gmsh: add v4.11.1, master

### PR DESCRIPTION
**Pull request by fspiga**
https://gitlab.onelab.info/gmsh/gmsh/-/releases#changelog

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256.  Thanks for signing up to maintain the package (https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers).

**Comment by tldahlgren** [comment]
Looks like the package doesn't build for one of the stacks.  See https://gitlab.spack.io/spack/spack/-/pipelines/564559.  For example:

```
tmp/root/spack-stage/spack-stage-gmsh-4.11.1-z2ln34ycaeaqkj2pswoqtadhbkqhgrx3/spack-src/src/geo/GModelIO_OCC.cpp:1298:36: error: variable 'TColgp_Array1OfVec Tangents' has initializer but incomplete type
```
```

**Comment by alecbcs** [comment]
@fspiga could you take a look at the failing build and see if this is either a missing dep or incompatibility with a specific arch/compiler? I'm not familiar with `gmsh`.

**Comment by wdconinc** [comment]
@fspiga now that v4.12.0 has been merged in #41854, along with the require oce to opencascade change, do you want to rebase this to resolve conflicts, or just close this PR and not include the v4.11.1 release?

**Comment by wdconinc** [comment]
Merged updates from develop, so this PR now consists of:
- adding v4.11.1,
- adding maintainer.

Since #41854 has addressed the `oce` issue by defining a conflict for all recent versions, the concern in https://github.com/spack/spack/pull/41320#issuecomment-1834739586 has been addressed (see also https://github.com/spack/spack/pull/41854#issuecomment-1894582939).

I'll approve and this can get auto-merged.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
