### PR TITLE
package/npm update

### PR DESCRIPTION
**Pull request by Sinan81**
add new versions, specify node-js versions.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the two version sha256s.

**Comment by adamjstewart** [comment]
@Sinan81 these new versions appear to be broken. If you look in the installation prefix:
```console
> ls -lhA bin
total 0
lrwxrwxr-x  1 Adam  staff    38B Apr 26 15:31 npm@ -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxr-x  1 Adam  staff    38B Apr 26 15:31 npx@ -> ../lib/node_modules/npm/bin/npx-cli.js
> ls -lhA lib/node_modules/npm 
lrwxrwxr-x  1 Adam  staff   168B Apr 26 15:31 lib/node_modules/npm@ -> ../../../../../../../../../../private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-npm-10.5.2-womsq2q7znbturqjw572trye3slkluuh/spack-src
```
The stage directory ends up being symlinked, but it no longer exists. This was not the case in 9.3.1. Can you take a look at what changed, or should we revert this PR?

**Comment by Sinan81** [comment]
we should revert it. not sure If I can look into this quickly.

**Comment by Sinan81** [comment]
it seems as of npm@9.4.2 an implicit option `--install-links` was flipped from true to false. When I pass this option to Spack's install command, install seems be working fine. Will submit a new PR.
https://github.com/npm/cli/pull/6142

**Pull request merged**
