### PR TITLE
celeritas: new version 0.3.0

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Comment by sethrj** [comment]
@spackbot run pipeline

**Comment by sethrj** [comment]
@drbenmorgan This should be a pretty easy PR: note that the newest version of celeritas is compatible with Geant4@11.1, whereas 0.2 is only compatible with up to 11.0.

**Review by drbenmorgan — APPROVED** [review]
Hash and `depends_on` look o.k. so good the merge, thanks @sethrj!

**Comment by sethrj** [comment]
@spackbot run pipeline

**Pull request merged**
