### PR TITLE
Expand/clarify description of dependency types

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you rebase this off of develop so that it runs my new documentation tests?

**Comment by tgamblin** [comment]
Nice!  Everyone is on a documentation spree!

**Comment by adamjstewart** [comment]
> Everyone is on a documentation spree!

Said no one ever. Man, SC16 is really whipping us into shape.

**Comment by eschnett** [comment]
Rebased.

**Comment by adamjstewart** [comment]
Passes all documentation tests! LGTM

**Pull request merged**
