### PR TITLE
Apply black 2024 style to Spack

### PR DESCRIPTION
**Pull request by adamjstewart**
The new 2024 black style changes are out: https://github.com/psf/black/releases/tag/24.1.0

This one was pretty minor, and should largely be backwards compatible. This PR applies all changes to all of Spack and updates the version of black used during testing.

Do we also need to separately update the version used by spackbot?

### CODE REVIEW

**Review by aprokop — APPROVED** [review]
lgtm

**Comment by haampie** [comment]
I approve, this stuff

```python
lambda x: f(x) if x in xs else g(x)
```

is pretty confusing:

```python
lambda x: (f(x) if x in xs else g(x))  # probably this
(lambda x: f(x)) if x in xs else g(x)  # and not this
```

**Review by ethanjjjjjjj — APPROVED** [review]

**Review by alalazo — DISMISSED** [review]

**Review by albestro — DISMISSED** [review]

**Review by eloop — APPROVED** [review]
Lgtm

**Comment by haampie** [comment]
Can you also update `lib/spack/spack/bootstrap/environment.py`

**Review by jcortial-safran — APPROVED** [review]

**Review by haampie — APPROVED** [review]

**Pull request merged**
