### PR TITLE
Add CUDA 12.0.1 and 12.1.0

### PR DESCRIPTION
**Pull request by wyphan**
SHA256 checksums manually computed locally after confirming the MD5 checksums from the download page.

### CODE REVIEW

**Comment by wyphan** [comment]
@spackbot run pipeline

**Comment by wyphan** [comment]
@scheibelp I think I messed up the rebase, would you mind fixing it? 😂 
Also, the previous CI results were affected by the `ppc64le` tag mix-up, so I just asked spackbot to re-run it

**Comment by scheibelp** [comment]
> I think I messed up the rebase, would you mind fixing it?

I don't have any extra powers that would speed this along: I recommend opening a new PR with just the edits you want. Generally I recommend merging rather than rebasing.

**Comment by wyphan** [comment]
Closing stale PR since #37083 has been merged.

**Pull request closed without merging**
