### PR TITLE
New format for packages.yaml, simplify detection protocol

### PR DESCRIPTION
**Pull request by alalazo**
closes #16526

This is a rebased version of #16526 where commits have been factored to reflect functional changes:

- 9ce78be Has all the changes related to the new `packages.yaml` format and the configuration updates needed to support the conversion from the old format to the new one
- e5c689c Contains the simplifications / extensions to the detection protocol for external packages

This is in preparation for a "rebase and merge" rather than a single squashed commit. Thanks to @scheibelp for the extensive review in #16526 and help writing the detailed commit messages in this PR.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by scheibelp** [comment]
I have a couple requests related to the factoring of the commits:

* Can the bash completion updates be combined with the commit that does the associated command changes (in other words, combine the 1st and 3rd commits)? If it comes to bisects that make use of `spack test` the tests would not pass without the bash completion.
* Can the package changes be combined with the commit which makes the associated changes to the package? I think it's useful to have the associated package changes in the same commit so that people reading through the commit see the examples along with the changes

If you think it's better to keep the commits split as they are, let me know.

**Comment by adamjstewart** [comment]
Ping @scheibelp

**Comment by jedbrown** [comment]
Is this intended to give instructions on how to revise or is the user expected to consult the repository or website to figure it out?
```
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('mpich@3.4a2', '/opt/mpich')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('openmpi@4.0.4', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('autoconf@2.69', '/usr/bin')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('libtool@2.4.6', '/usr/bin')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cmake@3.18.1', '/usr/bin')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('hwloc@2.2.0', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('libxml2@2.9.10', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('hdf5@1.12.0', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('blis@0.7.0', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('netlib-lapack@3.9.0', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('ncurses@6.2', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('bzip2@1.0.8', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('openssl@1.1.1.g', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('readline', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('sqlite', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('python@2.7', '/usr'), ('python@3.8', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cuda@11.0.2', '/opt/cuda')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('m4@1.4.18', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('pkgconf', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('libx11@1.6.10', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('libxt@1.2.0', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('xproto', '/usr')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('zlib@1.2.11', '/usr')])]
```

**Comment by alalazo** [comment]
@jedbrown There is a command to update the configuration file:
```console
$ spack config update packages
```
it's interactive by default and should explain caveats of the update. There's also a command to revert the update:
```console
$ spack config revert packages
```
Reference documentation for the `config` command is [here](https://spack.readthedocs.io/en/latest/command_index.html#spack-config) and I agree that there should be a pointer to that command in the warning. Documentation for external packages is instead [here](https://spack.readthedocs.io/en/latest/build_settings.html#external-packages) with examples of the format they have.

Also, I never worked with so many external packages as you have above and looking at that output it should be less verbose by default - will put together a PR soon and ping you for review. In the meanwhile if you have suggestions they are welcome.

**Comment by jedbrown** [comment]
Yeah, though this isn't very discoverable to a user who encounters this warning and needs to either go explore the website or the repository history. Perhaps the syntax warning can run (in memory) the update packages to confirm that it works and suggest that the user run it to update their configuration. And link to a page that concisely explains the syntax change instead of leaving it to the user to explore.

I'd still love a lighter way to ask Spack to use system packages. I realize that a lot of HPC facilities run older systems, but some of us run a current OS and are using Spack on top, perhaps for a containerized stack. Waiting to build the system components is tiresome and wastes space. So we have lots of externals.

**Comment by alalazo** [comment]
> I'd still love a lighter way to ask Spack to use system packages.

For what is worth this PR goes in that direction. Try for instance:
```console
$ spack external find --not-buildable cmake openssl
```
and check `packages.yaml`. Detection of external packages was introduced in #15158 and this PR simplifies what needs to be implemented for a package to be detectable. Thanks for the feedback!

**Comment by jedbrown** [comment]
Is this how it's supposed to work (openssl is in /usr)? Is the user expected to write a script that deletes `~/.spack/packages.yaml` and re-runs this with a list of packages?

```
$ spack external find --not-buildable cmake openssl
$ cat .spack/packages.yaml 
packages:
  cmake:
    externals:
    - spec: cmake@3.18.1
      prefix: /
    buildable: false
$ spack external find --not-buildable cmake openssl
$ cat .spack/packages.yaml 
packages:
  cmake:
    externals:
    - spec: cmake@3.18.1
      prefix: /
    - spec: cmake@3.18.1
      prefix: /usr/bin
    buildable: false
```
and also
```
$ rm .spack/packages.yaml
$ spack external find
$ cat .spack/packages.yaml 
packages:
  automake:
    externals:
    - spec: automake@1.16.2
      prefix: /
  cmake:
    externals:
    - spec: cmake@3.18.1
      prefix: /
  gcc:
    externals:
    - spec: gcc@9.3.0 languages=c,c++
      prefix: /
      extra_attributes:
        compilers:
          c: /bin/x86_64-pc-linux-gnu-gcc-9
          cxx: /bin/g++-9
    - spec: gcc@10.1.0 languages=c,c++,fortran
      prefix: /
      extra_attributes:
        compilers:
          c: /bin/x86_64-pc-linux-gnu-gcc
          cxx: /bin/x86_64-pc-linux-gnu-g++
          fortran: /bin/x86_64-pc-linux-gnu-gfortran
```
Why isn't it finding the many other packages in my path?

**Comment by becker33** [comment]
It's only finding the ones with detection mechanisms in Spack. It will take time for people to contribute detection mechanisms for everything you care about. The feature was initially released with support for cmake and automake, and anyone can contribute support for another package.

**Comment by jedbrown** [comment]
Okay, so it hasn't been implemented for `openssl`. Can you snarf up the needed information from pkg-config?
Also, why is this not idempotent (see above)?
```
$ spack external find --not-buildable cmake
```

**Comment by alalazo** [comment]
> Okay, so it hasn't been implemented for openssl

We got https://github.com/spack/spack/commit/30dc0baa3493076f3eddcdb731763eec42a46044 merged today.

**Comment by jedbrown** [comment]
I see. It may need to learn to handle symlinks from `/bin` to `/usr/bin` so it can find headers and libraries under `/usr`.
```
$ cat ~/.spack/packages.yaml 
packages:
  openssl:
    externals:
    - spec: openssl@1.0.2u
      prefix: /
    - spec: openssl@1.1.1g
      prefix: /
    buildable: false
```

**Pull request merged**
