### PR TITLE
add zstr package

### PR DESCRIPTION
**Pull request by bvanessen**
Add a package for the Zstr header only library.  Add it as adependency for LBANN.

### CODE REVIEW

**Comment by alalazo** [comment]
@bvanessen Can you please rebase and push?

**Review by tldahlgren — DISMISSED** [review]
Confirmed versions available on the provided site.

**Comment by bvanessen** [comment]
@alalazo I have rebased and pushed

**Comment by alalazo** [comment]
@bvanessen Thanks. Hope this will bring CI notifications to a saner state.

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
There are issues with style:
```
==> Error: Flake8 style checks found errors
var/spack/repos/builtin/packages/zstr/package.py:27: [W291] trailing whitespace
var/spack/repos/builtin/packages/zstr/package.py:31: [W391] blank line at end of file
```

**Comment by bvanessen** [comment]
> There are issues with style:
> 
> ```
> ==> Error: Flake8 style checks found errors
> var/spack/repos/builtin/packages/zstr/package.py:27: [W291] trailing whitespace
> var/spack/repos/builtin/packages/zstr/package.py:31: [W391] blank line at end of file
> ```

@alalazo Fixed.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
