### PR TITLE
Update documentation for use on Cray

### PR DESCRIPTION
**Pull request by mamelara**
Updating how to use compilers.yaml on Cray as well as setting up
external packages. Also includes what needs to be set up for usage on
Cray. Explain the architecture spec and what it does.

### CODE REVIEW

**Comment by mamelara** [comment]
This is kinda a first draft. Please let me know if anything is unclear or if more information is added. Thanks!

**Comment by tgamblin** [comment]
@mamelara: `linux-x86_64-debian7` is backwards, isn't it?  It's `platform-os-target`, right?

**Comment by tgamblin** [comment]
@mamelara: this looks pretty good overall, but do you think you could bundle more of the text into the "spack on cray" section, and add cross-references?  Right now it's kind of hard to find the cray specifics mixed in with the other text.  I think it would be better if thing like the Cray `compilers.yaml` description, etc. were under the Spack on Cray section, and the compiler section just linked to it.  What do you think?

**Comment by mamelara** [comment]
You're right it is backwards, I'll fix that. 

Yeah that makes sense. Makes it easier for someone just trying to learn how to get started on Cray to not look through the whole doc and search for the Cray specifics. I am unfamiliar with rst. Is there a way to check whether everything appears correctly?

**Comment by tgamblin** [comment]
Just typing make in the docs directory should build
the html.  You'll need Sphinx and pygments.

**Comment by mamelara** [comment]
2nd draft is completed. I added more information to Spack on Cray including how compilers are detected and how the arch spec can be used to build either with front-end or back-end compilers/processors. 

One thing I noticed is that the digraph in Virtual Dependencies looks broken, though I haven't changed anything. I'm not entirely sure if it's just something on my end or not.

**Pull request merged**
