### PR TITLE
Revert "Use Python's urllib to fetch if curl missing"

### PR DESCRIPTION
**Pull request by haampie**
See #24589, https://github.com/spack/spack/pull/24609#issuecomment-871282816, https://github.com/spack/spack/pull/21398#issuecomment-870096685.

- It fails to download files larger than 2GB;
- There are apparently certificate verification issues.

### CODE REVIEW

**Comment by becker33** [comment]
@haampie instead of reverting, we should put a version guard around the option for using internal urllib methods. We can restrict it to using python 3.10.1 or later. That will also allow the folks working on getting Spack working on windows to keep progressing, since the PR you're trying to revert was a prereq for their work (no curl on windows).

**Comment by haampie** [comment]
Ok, wasn't aware. Do note that Python 3.10 is still expected to be released in October, so not sure making it conditional on the python version makes sense for now.

Alternatively we can fix https://github.com/spack/spack/pull/21398#pullrequestreview-696380467. Not sure if we can quickly fix the issue reported by @adamjstewart

**Comment by adamjstewart** [comment]
Yeah, my issue is more complex. Basically, the system Python and all of the bwpy installs on BW don't have urllib working correctly. Not sure if there is a way to check that. Could do a try-except and fallback on curl if urllib doesn't work...

**Comment by haampie** [comment]
Why don't we use curl by default and fall back to urllib?

**Comment by adamjstewart** [comment]
urllib will simplify things when we merge Windows support. But yes, some kind of fallback scheme would be nice to add.

**Comment by eugeneswalker** [comment]
https://github.com/spack/spack/pull/24622 resolved the issue for me. Thank you!

**Comment by becker33** [comment]
@eugeneswalker does #24623 also resolve the issue for you?

**Comment by eugeneswalker** [comment]
> @eugeneswalker does #24623 also resolve the issue for you?

Yes! Thank you!

**Comment by haampie** [comment]
Closing in favor of #24623

**Pull request closed without merging**
