### PR TITLE
podio: Add the new datasource variant once it is available

### PR DESCRIPTION
**Pull request by tmadlener**
Add a variant `datasource` that allows to toggle the newly added `ENABLE_DATASOURCE` cmake flag, see https://github.com/AIDASoft/podio/pull/593

### CODE REVIEW

**Review by jmcarcell — APPROVED** [review]

**Review by wdconinc — COMMENTED** [review]
Just want to verify that when I attempt to install `podio ~rntuple +datasource ^root ~root7`, I will I not encounter build issues here. A really quick look seems to indicate that RDataSource only requires ROOT with `-Ddataframe=ON` which is default for all `root` installs in spack, but you might be aware of possible other constraints.

**Comment by tmadlener** [comment]
Checking the ROOT variants and cmake options and dependencies for `RDataSource`, I came to the same conclusions as you, so no `+root7` should be necessary. However, I didn't explicitly check against such a root build to verify it. AFAICT effectively `root@6.14:` should be enough to get `RDataSource`.

**Comment by wdconinc** [comment]
> effectively `root@6.14:` should be enough to get `RDataSource`

Has the public interface you use in `podio` been stable since then? Right now the dependencies are specified such that with `cxxstd=17` you can get as old as `root@6.08` with `+datasource` . I think adding a `depends_on("root@6.14:", when="+datasource")` would be acceptable to me, or even a newer version that you have tested (I don't think anyone on the bleeding edge of podio development is realistically using pre-6.28 ROOT versions).

**Comment by tmadlener** [comment]
> Has the public interface you use in podio been stable since then?

Yes, I do think so. I had a brief look at the git history, and it hasn't seem too many changes.  There were some documentation updates, but nothing that changes the interface as far as I saw.

> with `cxxstd=17` you can get as old as `root@6.08` with `+datasource`

We actually haven't tried building podio with below 6.20 for years by now probably. The `root@6.14` is mainly in there because prior to that ROOT didn't have the `RDataSource` option. I need to put that constraint into podio as well. Ideally, this would be a variant of `root` and the proper constraints there.

**Review by wdconinc — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
