### PR TITLE
Update TensorFlow ecosystem

### LINKED ISSUE #42942: Installation issue: `py-tensorflow` needs `patchelf`?
### Steps to reproduce the issue

```console
$ spack spec -I py-tensorflow
Input spec                                                                                                                                                                                                        
--------------------------------                                                                                                                                                                                  
 -   py-tensorflow                                                                                                                                                                                                
                                                                                                                                                                                                                  
Concretized                                                                                                                                                                                                       
--------------------------------                                                                                                                                                                                  
 -   py-tensorflow@2.14.0%gcc@12.3.0~android~aws~computecpp~cuda+dynamic_kernels~gcp~gdr~hdfs~ignite~ios~jemalloc~kafka~mkl~monolithic~mpi~nccl~ngraph~numa~opencl~rocm~tensorrt~verbs+xla build_system=generic pa
tches=2017b3e arch=linux-rhel7-skylake_avx512                                                                                                                                                                     
[+]      ^bazel@6.1.0%gcc@12.3.0+nodepfail build_system=generic patches=0f6940d,3e6448a,53ca269,604423c,dbbf38b arch=linux-rhel7-skylake_avx512                                                                   
[+]          ^openjdk@11.0.20.1_1%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512                                                                                                                 
[+]          ^zip@3.0%gcc@12.3.0 build_system=makefile patches=14dc880,3bc30ba,5068e7c,51f48db,66ab4ce,a92fc4e,a95ed93,eb83fc8,f7d0bc4,fa8312c arch=linux-rhel7-skylake_avx512                                    
 -       ^hdf5@1.14.3%gcc@12.3.0~cxx~fortran+hl~ipo~java~map~mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512                    
[+]          ^cmake@3.27.7%gcc@12.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel7-skylake_avx512                                                                                 
[+]              ^curl@8.4.0%gcc@12.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel7-skylake_avx512                                  
[+]                  ^nghttp2@1.57.0%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                            
[+]          ^gmake@4.4.1%gcc@12.3.0~guile build_system=generic arch=linux-rhel7-skylake_avx512                                                                                                                   
[+]          ^pkgconf@1.9.5%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                                     
[+]          ^zlib-ng@2.1.4%gcc@12.3.0+compat+opt build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                          
[+]      ^py-absl-py@1.4.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                     
[+]      ^py-astunparse@1.6.3%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                  
[+]      ^py-flatbuffers@23.5.26%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                               
[+]      ^py-gast@0.5.4%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                        
[+]      ^py-google-pasta@0.2.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                
[+]      ^py-grpcio@1.52.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                     
[+]          ^c-ares@1.15.0%gcc@12.3.0~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512                                                                                   
[+]          ^openssl@3.1.3%gcc@12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel7-skylake_avx512                                                                                             
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512                                                                                              
[+]              ^perl@5.38.0%gcc@12.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel7-skylake_avx512                                                                    
[+]                  ^berkeley-db@18.1.40%gcc@12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel7-skylake_avx512                                                                  
[+]          ^py-cython@0.29.36%gcc@12.3.0 build_system=python_pip patches=c4369ad arch=linux-rhel7-skylake_avx512                                                                                                
[+]          ^re2@2023-09-01%gcc@12.3.0~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-rhel7-skylake_avx512                                                                       
[+]              ^abseil-cpp@20230125.3%gcc@12.3.0~ipo+shared build_system=cmake build_type=Release cxxstd=14 generator=make arch=linux-rhel7-skylake_avx512                                                      
 -       ^py-h5py@3.8.0%gcc@12.3.0~mpi build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                    
[+]          ^py-pkgconfig@1.5.5%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                               
[+]              ^py-poetry-core@1.6.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                         
[+]      ^py-libclang@14.0.6%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512                                                                                                                   
[+]          ^llvm@14.0.6%gcc@12.3.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3 build_system=cmake build_type=Release comp
iler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime patches=1f42874,25bc503,6379168,8248141,b216cff,cb8e645 shlib_symbol_version=none targets=all version_suffix=none arch=linux-rhel7
-skylake_avx512                                                                                                                                                                                                   
[+]              ^binutils@2.41%gcc@12.3.0~gas+gold~gprofng+headers~interwork+ld~libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-rhel7-skylake_avx
512                                                                                                                                                                                                               
[+]                  ^zstd@1.5.5%gcc@12.3.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel7-skylake_avx512                                                                    
[+]              ^elfutils@0.189%gcc@12.3.0~debuginfod+exeprefix+nls build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                       
[+]              ^hwloc@2.9.1%gcc@12.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512                    
[+]                  ^libpciaccess@0.17%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                         
[+]                      ^util-macros@1.19.3%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                    
[+]              ^libedit@3.1-20210216%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512                                                                                                          
[+]              ^libxml2@2.10.3%gcc@12.3.0+pic~python+shared build_system=autotools arch=linux-rhel7-skylake_avx512
[+]              ^lua@5.3.6%gcc@12.3.0~pcfile+shared build_system=makefile fetcher=curl arch=linux-rhel7-skylake_avx512                                                                                           
[+]                  ^unzip@6.0%gcc@12.3.0 build_system=makefile arch=linux-rhel7-skylake_avx512
[+]              ^ninja@1.11.1%gcc@12.3.0+re2c build_system=generic arch=linux-rhel7-skylake_avx512
[+]                  ^re2c@2.2%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512
[+]              ^perl-data-dumper@2.173%gcc@12.3.0 build_system=perl arch=linux-rhel7-skylake_avx512
[+]      ^py-ml-dtypes@0.2.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-pybind11@2.11.0%gcc@12.3.0~ipo build_system=cmake build_type=Release generator=ninja arch=linux-rhel7-skylake_avx512
[+]      ^py-numpy@1.24.3%gcc@12.3.0 build_system=python_pip patches=873745d arch=linux-rhel7-skylake_avx512
[+]          ^openblas@0.3.24%gcc@12.3.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-rhel7-skylake_avx512
[+]      ^py-opt-einsum@3.3.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-packaging@23.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-flit-core@3.9.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-pip@23.1.2%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512
[+]      ^py-protobuf@4.24.3%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-requests@2.31.0%gcc@12.3.0~socks build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-certifi@2023.7.22%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-charset-normalizer@3.3.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-idna@3.4%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-urllib3@2.0.6%gcc@12.3.0~brotli~secure~socks build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-hatchling@1.18.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-editables@0.3%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-pathspec@0.11.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-pluggy@1.0.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                      ^py-setuptools-scm@7.1.0%gcc@12.3.0+toml build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                          ^git@2.42.0%gcc@12.3.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                              ^libidn2@2.3.4%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                                  ^libunistring@1.1%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                              ^openssh@9.5p1%gcc@12.3.0+gssapi build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                                  ^krb5@1.20.1%gcc@12.3.0+shared build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                                      ^findutils@4.9.0%gcc@12.3.0 build_system=autotools patches=440b954 arch=linux-rhel7-skylake_avx512
[+]                              ^pcre2@10.42%gcc@12.3.0~jit+multibyte build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                          ^py-tomli@2.0.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-trove-classifiers@2023.8.7%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                      ^py-calver@2022.6.26%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-setuptools@63.4.3%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512
[+]      ^py-six@1.16.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-tensorboard@2.14.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-google-auth@2.16.2%gcc@12.3.0~aiohttp build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-cachetools@5.2.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-pyasn1-modules@0.2.8%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-pyasn1@0.4.8%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-rsa@4.9%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-google-auth-oauthlib@0.5.2%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-requests-oauthlib@1.3.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]                  ^py-oauthlib@3.2.1%gcc@12.3.0~rsa~signals~signedtoken build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-markdown@3.4.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]          ^py-tensorboard-data-server@0.7.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^rust@1.70.0%gcc@12.3.0~analysis+clippy~docs+rustfmt+src build_system=generic arch=linux-rhel7-skylake_avx512
[+]                  ^libgit2@1.7.0%gcc@12.3.0~curl~ipo+mmap+ssh build_system=cmake build_type=Release generator=make https=system arch=linux-rhel7-skylake_avx512
[+]                      ^libssh2@1.11.0%gcc@12.3.0+shared build_system=autotools crypto=openssl patches=011d926 arch=linux-rhel7-skylake_avx512
[+]                  ^rust-bootstrap@1.70.0%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512
[+]          ^py-werkzeug@3.0.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]              ^py-markupsafe@2.1.3%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-termcolor@1.1.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-typing-extensions@4.8.0%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^py-wheel@0.41.2%gcc@12.3.0 build_system=generic arch=linux-rhel7-skylake_avx512
[+]      ^py-wrapt@1.14.1%gcc@12.3.0 build_system=python_pip arch=linux-rhel7-skylake_avx512
[+]      ^python@3.11.6%gcc@12.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdc
a64,f2fd060 arch=linux-rhel7-skylake_avx512
[+]          ^bzip2@1.0.8%gcc@12.3.0~debug~pic+shared build_system=generic arch=linux-rhel7-skylake_avx512
[+]              ^diffutils@3.9%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^expat@2.5.0%gcc@12.3.0+libbsd build_system=autotools arch=linux-rhel7-skylake_avx512
[+]              ^libbsd@0.11.7%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]                  ^libmd@1.0.4%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^gdbm@1.23%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^gettext@0.22.3%gcc@12.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel7-skylake_avx512
[+]              ^libiconv@1.17%gcc@12.3.0 build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512
[+]              ^tar@1.34%gcc@12.3.0 build_system=autotools zip=pigz arch=linux-rhel7-skylake_avx512
[+]                  ^pigz@2.7%gcc@12.3.0 build_system=makefile arch=linux-rhel7-skylake_avx512
[+]          ^libffi@3.4.4%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^libxcrypt@4.4.35%gcc@12.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel7-skylake_avx512
[+]          ^ncurses@6.4%gcc@12.3.0~symlinks+termlib abi=none build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^readline@8.2%gcc@12.3.0 build_system=autotools patches=bbf97f1 arch=linux-rhel7-skylake_avx512
[+]          ^sqlite@3.43.2%gcc@12.3.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^util-linux-uuid@2.38.1%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^xz@5.4.1%gcc@12.3.0~pic build_system=autotools libs=shared,static arch=linux-rhel7-skylake_avx512
[+]      ^swig@4.0.2-fortran%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^autoconf@2.69%gcc@12.3.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel7-skylake_avx512
[+]              ^m4@1.4.19%gcc@12.3.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel7-skylake_avx512
[+]                  ^libsigsegv@2.14%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^automake@1.16.5%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^bison@3.8.2%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^libtool@2.4.7%gcc@12.3.0 build_system=autotools arch=linux-rhel7-skylake_avx512
[+]          ^pcre@8.45%gcc@12.3.0~jit+multibyte+utf build_system=autotools arch=linux-rhel7-skylake_avx512
```


### Error message

I'm not entirely sure of what's the problem, but perhaps the last line of `spack-build-out.txt` (full log below)
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 254: patchelf: command not found
```
is suggesting that `patchelf` is a needed dependency, not currently listed?  @haampie pointed out `patchelf` is available in `PATH` in CI, so that may explain why this was never caught.  Unfortunately I can't test this soon myself, so I'm opening an issue with the hope someone can spot the issue.

### Information on your system

* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/14464251/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14464252/spack-build-out.txt)
@adamjstewart @aweits

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by adamjstewart**
* TensorFlow: https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0
* Keras: https://github.com/keras-team/keras/releases/tag/v2.15.0
* TensorBoard: https://github.com/tensorflow/tensorboard/releases/tag/2.15.0

Fixes #42942

### CODE REVIEW

**Comment by adamjstewart** [comment]
CPU and ROCm error doesn't make sense to me:
```
/usr/bin/env: 'python3': No such file or directory
```

**Comment by adamjstewart** [comment]
CUDA error looks fixable, although not by me:
```
ERROR: /tmp/root/spack-stage/spack-stage-py-tensorflow-2.15.0-z2t4dqadctymw2b6tlxulwkanlmmfege/spack-src/tensorflow/tools/pip_package/BUILD:203:10: error loading package '@local_config_nccl//': Label '//tensorflow/platform/default:cuda_build_defs.bzl' is invalid because 'tensorflow/platform/default' is not a package; perhaps you meant to put the colon here: '//tensorflow:platform/default/cuda_build_defs.bzl'? and referenced by '//tensorflow/tools/pip_package:licenses'
```

**Comment by adamjstewart** [comment]
Will add Keras 3.0.0 in a separate PR after this is merged.

**Comment by adamjstewart** [comment]
https://github.com/tensorflow/tensorflow/issues/62500

**Comment by adamjstewart** [comment]
https://github.com/tensorflow/tensorflow/issues/62497

**Comment by adamjstewart** [comment]
Bleh, now we have a new build issue...

**Comment by adamjstewart** [comment]
Opened a bug report: https://github.com/tensorflow/tensorflow/issues/62930

**Comment by adamjstewart** [comment]
Different bug for newer version: https://github.com/tensorflow/tensorflow/issues/63356

**Review by alalazo — APPROVED** [review]

**Pull request merged**
