### PR TITLE
snakemake: add new version + update plugins

### PR DESCRIPTION
**Pull request by w8jcik**

### CODE REVIEW

**Comment by w8jcik** [comment]
@spackbot fix style

**Comment by w8jcik** [comment]
@marcusboden Could you take a look at this Pull Request? (since you are listed as a maintainer of Snakemake package)

The changes are simple version updates, but the Pull Request is left without any feedback for more than a month.

**Comment by w8jcik** [comment]
@adamjstewart I know that you no longer review Python packages, but could you take a quick, one minute look at this MR? The maintainer of this package didn't bother to reply since five months.

**Review by bernhardkaindl — APPROVED** [review]
Built on Ubuntu 22.04

**Pull request merged**
