### PR TITLE
Remove deprecated versions from packages

### PR DESCRIPTION
**Pull request by adamjstewart**
Only removed versions from packages I maintain.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot fix style

**Review by jonas-eschle — COMMENTED** [review]
I had a glance over it, seems fine (can have a detailed look at a later point if you want), just wondering if the removed packages, i.e. geopm, aren't dependencies of other packages?

**Comment by adamjstewart** [comment]
`geopm` was deprecated in favor of `geopm-runtime` and `geopm-server`. Spack CI ensures that all dependencies listed in packages actually exist.

**Comment by alalazo** [comment]
@eugeneswalker Can you check this one? There are many packages tagged `e4s` removed. If it's fine with you, it's fine with me.

**Comment by alalazo** [comment]
Why are you removing ~`geopm` and~ `candle-benchmarks` completely?[^1]

[^1]: For `geopm` see https://github.com/spack/spack/pull/44157#issuecomment-2108666836

**Comment by adamjstewart** [comment]
Candle-benchmarks requires matplotlib 2, which was deprecated for a full release cycle and is now being removed. It has no recipe maintainer, and hasn't had a new commit in over 2 years, so I'm guessing it's abandoned.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
