### PR TITLE
macOS build tests: external find opengl

### PR DESCRIPTION
**Pull request by adamjstewart**
Test to see if this fixes our failing nightly tests.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Well, unfortunately this doesn't fix the tests, but it does seem to work properly, so this should probably still be merged.

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
I checked the raw logs and I see:
```
2020-08-18T01:39:25.8666770Z ==> No new external packages detected
```
I think this should not be merged yet

**Comment by adamjstewart** [comment]
I tried adding debug statements but I don't even see the output in the log. Might just give up on this.

**Comment by alalazo** [comment]
@adamjstewart I downloaded the raw logs and inspected them :slightly_smiling_face:

**Comment by adamjstewart** [comment]
Same, but the current logs don't have any output.

**Pull request closed without merging**
