### PR TITLE
(r-rcpp)ensmallen: new package

### PR DESCRIPTION
**Pull request by wdconinc**
ensmallen is a high-quality C++ library for non-linear numerical optimization.

```console
==> Installing ensmallen-2.19.1-56z4nfysjrut4y4nh5wkow4nv43ikeax
==> No binary for ensmallen-2.19.1-56z4nfysjrut4y4nh5wkow4nv43ikeax found: installing from source
==> Fetching https://github.com/mlpack/ensmallen/archive/refs/tags/2.19.1.tar.gz
==> No patches needed for ensmallen
==> ensmallen: Executing phase: 'cmake'
==> ensmallen: Executing phase: 'build'
==> ensmallen: Executing phase: 'install'
==> ensmallen: Successfully installed ensmallen-2.19.1-56z4nfysjrut4y4nh5wkow4nv43ikeax
  Stage: 2.98s.  Cmake: 1.34s.  Build: 0.04s.  Install: 0.18s.  Post-install: 0.17s.  Total: 5.07s
[+] /opt/software/linux-ubuntu23.04-skylake/gcc-12.2.0/ensmallen-2.19.1-56z4nfysjrut4y4nh5wkow4nv43ikea
```

### CODE REVIEW

**Comment by wdconinc** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage of `ensmallen` and all version sha256.

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage of `ensmallen` and all version sha256.

**Comment by tldahlgren** [comment]
`spack spec` succeeds.

**Pull request merged**
