### PR TITLE
gcc: add v14.1.0

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Review by michaelkuhn — APPROVED** [review]
Works for me (tested on RL9)

**Comment by michaelkuhn** [comment]
Should we wait for a macOS user to try this before merging?

**Comment by alalazo** [comment]
Yeah, no rush on my side

**Comment by haampie** [comment]
unlikely that people will try it out until it's merged ;p let's get this in and let the darwin people fix it

**Pull request merged**
