### PR TITLE
Add libiconv dependency for git

### PR DESCRIPTION
**Pull request by eschnett**
Also remove "--without-pcre" flag that git does not understand any more.

### CODE REVIEW

**Comment by becker33** [comment]
Please rebase this on the most recent develop. The git package has changed recently to have a dependency on pcre.

**Comment by citibeth** [comment]
> Also remove "--without-pcre" flag that git does not understand any more.

Do we wish to preserve older versions of `git`?

**Comment by adamjstewart** [comment]
See #1345. `--with-pcre` has been renamed to `--with-libpcre`. If we want to support older versions, that can be done in another PR. @eschnett If you rebase you won't have to deal with PCRE.

**Comment by tgamblin** [comment]
I'm not sure `--with-pcre` was ever correct.  I looked at the history of `configure.ac` in the actual `git` source, and it looks like it was always `--with-libpcre`.  No git version from a `version` directive actually takes `--with-pcre`, and none take `--with-libpcre`, so I think we can just stick with the change from #1345

**Comment by eschnett** [comment]
Rebased.

Now there's no modification to handling `pcre` any more.

**Comment by eschnett** [comment]
Ping

**Pull request merged**
