### PR TITLE
e4s ci stacks: add exago specs

### PR DESCRIPTION
**Pull request by eugeneswalker**
Adding `exago` to E4S CI stack here so we can flesh out any build issues and lock in a functioning build.

@cameronrutherford

### CODE REVIEW

**Comment by cameronrutherford** [comment]
@eugeneswalker perhaps https://github.com/spack/spack/pull/40614 should be merged first?

**Comment by eugeneswalker** [comment]
> @eugeneswalker perhaps #40614 should be merged first?

Yes let us wait for that!

**Comment by eugeneswalker** [comment]
> @eugeneswalker perhaps #40614 should be merged first?

Ahh yes, I hadn't seen this. Let us have that one go through and this one will be amended to simply add the appropriate `exago` specs to E4S CI stacks.

**Comment by eugeneswalker** [comment]
I've updated this PR so that it now only adds `exago` builds to the various E4S CI stacks.

**Comment by eugeneswalker** [comment]
@cameronrutherford `exago@5-18-2022-snapshot` is treated as a newer version than `exago@1.6.0`  because `5>1`. So as it stands now, `exago@5-18-2022-snapshot` is the default version if someone tries to install `exago` without specifying a version. Can we rename that version to `snapshot.5-18-2022` all else equal so that `1.6.0` is treated as the latest version ? Or, is there a different way we could rename it so that it is treated with proper consideration?

**Comment by cameronrutherford** [comment]
> @cameronrutherford `exago@5-18-2022-snapshot` is treated as a newer version than `exago@1.6.0` because `5>1`. So as it stands now, `exago@5-18-2022-snapshot` is the default version if someone tries to install `exago` without specifying a version. Can we rename that version to `snapshot.5-18-2022` all else equal so that `1.6.0` is treated as the latest version ? Or, is there a different way we could rename it so that it is treated with proper consideration?

Your suggestion is logical and I approve :)

**Review by cameronrutherford — APPROVED** [review]

**Review by wspear — APPROVED** [review]

**Comment by cameronrutherford** [comment]
@eugeneswalker did you capture the HiOp bug where spack is building ROCm, or is that more of a spack-based bug since there are no issues deploying at OLCF / PNNL and other machines?

**Comment by eugeneswalker** [comment]
> @eugeneswalker did you capture the HiOp bug where spack is building ROCm, or is that more of a spack-based bug since there are no issues deploying at OLCF / PNNL and other machines?

I didn't have a chance to dig into why it wasn't able to find the ROCm libraries it wants when Spack builds them versus when they are installed to standard location with system package manager (i.e. `/opt/rocm`). Do you know? I assume it will take a bit of digging and I just didn't have time. What do you think the best way to proceed is?

**Comment by cameronrutherford** [comment]
> > @eugeneswalker did you capture the HiOp bug where spack is building ROCm, or is that more of a spack-based bug since there are no issues deploying at OLCF / PNNL and other machines?
> 
> I didn't have a chance to dig into why it wasn't able to find the ROCm libraries it wants when Spack builds them versus when they are installed to standard location with system package manager (i.e. `/opt/rocm`). Do you know? I assume it will take a bit of digging and I just didn't have time. What do you think the best way to proceed is?

Well I have no error logs, so not too sure ;)

I was planning on trying my own spack-based ROCm install on a system that isn't supported through pre-built distributions, so I will be testing this myself soon. Is there anything in particular that I should be building here? I assume just `rocm-core` along with all the other dependents? Plenty of experience building CUDA from scratch, but this is my first time trying a ROCm build

**Pull request merged**
