### PR TITLE
Travis CI: speed-up build tests and increase coverage

### LINKED ISSUE #5049: Build timeouts in Travis
Our build tests have been timing out at 50 minutes quite frequently lately. I've been restarting Travis jobs for around a third of new PRs. Perhaps we should build fewer packages, or remove the build tests altogether.

### PR DESCRIPTION
**Pull request by alalazo**
Fixes #5049 

This PR speeds-up build tests - and increases coverage doing it. The idea is to remove the build of `hypre ^mpich` (which was taking a long time to build, causing Travis timeouts) and substitute it with builds of more packages, chosen according to:

- their build system
- their build time

Currently we cover all build-systems apart from `QMakePackage` and `SconsPackage`. `cmake` and `r` are installed via `apt-get` and configured as externals. More details about the coverage deltas in the red crosses or green ticks below.

### CODE REVIEW

**Comment by alalazo** [comment]
@davydden Yes, I am trying to experiment with this to find possible solutions to the excessive build time, that makes Travis time out.

**Comment by alalazo** [comment]
For the record: only `mpich` is -0.29% on the project and -0.4% on core. The build time drops down to ~10 minutes. We are getting worse coverage from `MakefilePackage` and `build_system` (because we miss `openblas`?).

I'll try adding a few additional and simple packages as separate builds.

**Comment by alalazo** [comment]
`openblas` is a 30 min. build alone. Using `mpich` + `openblas` is a -0.1% coverage (-0.14% on core).

**Comment by adamjstewart** [comment]
I think we could (and should) find a single package from each build system that builds in a minute or less.

**Comment by alalazo** [comment]
@adamjstewart That's what I am trying to do, without complicating a lot the configuration for Travis. The fact is, for instance, that any `CMakePackage` will trigger a build of `cmake` (which fails with an internal compiler error btw). Otherwise we need to set up the environment properly and configure `cmake` as an external.

In this case `astyle` (MakefilePackage) + `mpich` (AutotoolsPackage) is -0.24% (-0.35% on core). Being a simple package probably means it hits less lines of the build system logic.

**Comment by adamjstewart** [comment]
> Otherwise we need to set up the environment properly and configure cmake as an external.

:+1: We would have to do the same thing with `qt` and other build system dependencies, but I like this idea.

There's a ton of logic in `AutotoolsPackage` that only gets hit for packages that run `autoreconf` or `patch_config_guess`. We should choose a package that runs those steps.

**Comment by alalazo** [comment]
Any suggestion for packages is welcome

**Comment by adamjstewart** [comment]
Here are a few suggestions. Anyone can edit this if they want to add more.

- [ ] MakefilePackage - ?
- [ ] AutotoolsPackage - ?
- [ ] CMakePackage - ?
- [ ] QMakePackage - I'm unable to build Qt so I can't test these, but choose from `qt-creator`, `qwt`, and `qtgraph`
- [ ] PythonPackage - `py-setuptools`
- [ ] RPackage - `r-rcpp` (no dependencies, most popular R module: http://www.kdnuggets.com/2015/06/top-20-r-packages.html)
- [ ] PerlPackage - `perl-dbi` (no dependencies, most popular Perl module: https://perlmaven.com/most-popular-perl-modules)
- [ ] SConsPackage - choose from `cantera`, `kahip`, and `serf`, but all 3 have big dependencies
- [ ] WafPackage - `tut` has no dependencies
- [ ] Package - `zlib` (no dependencies, really fast to build)

**Comment by adamjstewart** [comment]
Yeah, you'll definitely want externals for `python`, `perl`, `r`, `cmake`, `scons`, and `qt`. Otherwise those will take up most of the build time.

**Comment by alalazo** [comment]
@adamjstewart For `cmake` and `qt` yes, for `python` and `perl` I think the build time is acceptable (at least for a first iteration on this) no?

**Comment by adamjstewart** [comment]
I guess if they are all in separate Travis instances, this is fine.

**Comment by adamjstewart** [comment]
Wanna add a separate codecov section for `projects/build_systems`?

**Comment by alalazo** [comment]
@adamjstewart Sure, why not!

**Comment by adamjstewart** [comment]
If you want coverage of `autoreconf` for `AutotoolsPackage`, the following packages have no dependencies aside from `automake`, `autoconf`, `libtool`, and `m4`:

* adol-c
* gmp
* hunspell
* idba
* libbson
* libconfig
* libuv
* singularity
* sst-dumpi
* vsearch

Unfortunately, most of `AutotoolsPackage` is the `_do_patch_config_guess` method, which is only run when on PowerPC. Not sure if we can get coverage for that.

**Comment by alalazo** [comment]
I just noticed that `r-*` extensions would benefit from a custom `url_for_version` method that searches in `https://cran.r-project.org/src/contrib/Archive` instead of `https://cran.r-project.org/src/contrib` if the latter fails. Most outdated packages  are currently not downloading.

**Comment by adamjstewart** [comment]
@alalazo This is fixed by #4516. I accidentally removed all of the `list_url`s.

**Comment by alalazo** [comment]
@adamjstewart @davydden @tgamblin I think this is ready to merge. We can improve on `autoreconf` and the two missing build systems in another PR. Waiting for reviews.

**Comment by adamjstewart** [comment]
Can you put comments next to each build test to explain which build system it covers?

It would be nice to see SCons and QMake covered. I would add IntelPackage but unfortunately I think it takes too long to fetch.

**Comment by alalazo** [comment]
Closed in favor of #5104

**Pull request closed without merging**
