### PR TITLE
Spackbot style fix test PR

### PR DESCRIPTION
**Pull request by adamjstewart**
@scottwittenburg @tgamblin this PR introduces black/isort issues, should help to debug spackbot.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
Thanks for the test case @adamjstewart

**Comment by scottwittenburg** [comment]
@spackbot hello

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Comment by tgamblin** [comment]
Hm so did this get fixed, or is @adamjstewart just privileged?  Maybe we do need to test on the other PR?

**Comment by scottwittenburg** [comment]
> Hm so did this get fixed, or is @adamjstewart just privileged? Maybe we do need to test on the other PR?

If it got fixed, it wasn't anything I did.  It just worked on this PR.  So yes, it may require testing on PRs from unprivileged users.  Which is how I tested it in my [PR](https://github.com/spack-test/spack/pull/19) on the development repo, and it worked there, fwiw.

**Comment by adamjstewart** [comment]
Guessing this is no longer relevant.

**Pull request closed without merging**
