### PR TITLE
Add pika 0.10.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by albestro — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

not sure why it didn't trigger

**Comment by haampie** [comment]
now we know, there was a problem!

**Review by teonnik — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha256.

**Comment by msimberg** [comment]
@spackbot run pipeline

**Pull request merged**
