### PR TITLE
Add dependency changes to R packages

### PR DESCRIPTION
**Pull request by glennpj**
This PR adds dependency changes that were missed with some recent merges of R package updates.

### CODE REVIEW

**Comment by glennpj** [comment]
Setting this to draft status as I want to double check my script output.

**Comment by alecbcs** [comment]
@glennpj apologies for merging in these new versions without properly checking all of the updated dependency requirements. I'd forgotten r is an interpreted language so these mismatches wouldn't be caught in simply attempting to install the package.

**Review by alalazo — APPROVED** [review]
Thanks @glennpj ! Let me know if in the future you'd like me to wait for your review on R package updates before merging.

**Comment by glennpj** [comment]
@alecbcs No worries; I wish the rate of dependency changes was not so rapid with R packages.
@alalazo It is probably best to wait for me, or someone, to check for changes in dependencies.

Thanks!

**Comment by alecbcs** [comment]
@glennpj do you think it would be possible to write a cran dependency parser as a CI test? That way we'd fail the PR tests when someone doesn't add the correct dependencies in the package.

**Comment by glennpj** [comment]
I suppose so. I have a pair of scripts that I use to bulk update R CRAN and BioConductor packages. (Actually, I will be running those soon as Bioconductor 3.17 is coming soon.) I would like to make those scripts available even though some packages still need intervention. An editor will pop up in those cases. I suppose parts of those scripts could be extracted out for a CI test.

**Comment by alecbcs** [comment]
Cool! When you're ready to share your scripts I'd be happy to take a stab at turning them into a PR check.

**Pull request merged**
