### PR TITLE
add atompaw package

### PR DESCRIPTION
**Pull request by simonpintarelli**
Add a package for atompaw: https://users.wfu.edu/natalie/papers/pwpaw/man.html

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Comment by trws** [comment]
@alalazo, @simonpintarelli, this package is up one level too high, it's under builtin instead of packages.

**Comment by alalazo** [comment]
Arrgh, and that was not caught by CI!

**Comment by alalazo** [comment]
I'll revert the PR apologies.

**Comment by trws** [comment]
No worries, I probably only noticed because of the pkgkit PR, I was running a command to add the import and noticed the path.

**Comment by alalazo** [comment]
We may need a CI audit of some sort for these kind of issues. I'll check what can be done tomorrow.

**Pull request merged**
