### PR TITLE
[Octopus] Update hash for new release 12.2

### PR DESCRIPTION
**Pull request by iamashwin99**
Octopus 12.2 is released: https://www.octopus-code.org/documentation/12/releases/changes/#octopus-12
This MR adds the hash for the new version.

### CODE REVIEW

**Comment by RemiLacroix-IDRIS** [comment]
It seems like I cannot download any Octopus version right now. I guess their website might have an issue.

**Comment by iamashwin99** [comment]
@RemiLacroix-IDRIS , the server hosting the octopus tarballs were unreliable for the past month or so, now the server has be migrated so the downloads should now be stable.

**Review by fangohr — APPROVED** [review]
This looks good. I have double checked the sha256 (it is correct).

The merge request has been around for some time because the Octopus webpage (serving the octopus source code) was broken, and thus the downloads failed. That's all working again now, so it would be good to merge this.

**Comment by fangohr** [comment]
Ping :). Could this be reviewed by one of the code Spack team, please? (@tldahlgren has looked at other Octopus updates before). Many thanks!

**Review by tldahlgren — COMMENTED** [review]
Very odd.  I'm getting the same sha for the top 3 listed versions:

```
$ spack checksum octopus 12.2 12.1 12.0
==> Found 3 versions of octopus:
  
  12.2  https://octopus-code.org/down.php?file=12.2/octopus-12.2.tar.gz
  12.1  https://octopus-code.org/down.php?file=12.1/octopus-12.1.tar.gz
  12.0  https://octopus-code.org/down.php?file=12.0/octopus-12.0.tar.gz

==> Fetching https://octopus-code.org/down.php?file=12.2/octopus-12.2.tar.gz
==> Fetching https://octopus-code.org/down.php?file=12.1/octopus-12.1.tar.gz
==> Fetching https://octopus-code.org/down.php?file=12.0/octopus-12.0.tar.gz

    version("12.2", sha256="0945bd38829a1098eace6d99fa42bd8df9e581fee82c0ba7eaddd4deb92d23dc")
    version("12.1", sha256="0945bd38829a1098eace6d99fa42bd8df9e581fee82c0ba7eaddd4deb92d23dc")
    version("12.0", sha256="0945bd38829a1098eace6d99fa42bd8df9e581fee82c0ba7eaddd4deb92d23dc")
```

**Comment by iamashwin99** [comment]
Looks like the new octopus webpage dosent use the PHP links  (https://octopus-code.org/down.php?file=6.0/octopus-6.0.tar.gz) to download the tar balls but rather link to the file directly (https://octopus-code.org/download/6.0/octopus-6.0.tar.gz). The reason all versions of spack octopus checksum  now have the same wrong hash is that it now just downloads the `.php` file and checks its hash.

Fixing this probably deserves a separate MR

**Comment by iamashwin99** [comment]
Merge request for fixing the link at https://github.com/spack/spack/pull/37081

**Review by alalazo — APPROVED** [review]

**Pull request merged**
