### PR TITLE
gcc: version 12.1.0

### PR DESCRIPTION
**Pull request by haampie**
We could consider adding `mold` as a dependency next to `binutils` `ld`

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Review by michaelkuhn — APPROVED** [review]

**Comment by michaelkuhn** [comment]
Forgot to add earlier: Confirmed variants still work and some important dependents still build (mpich, hdf5 etc.).

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
