### PR TITLE
`openblas` : fix `install_name` on macos

### LINKED ISSUE #45464: Installation issue: `openblas` does not have a correct `install_name` on macos
### Steps to reproduce the issue

_No response_

### Error message

`openblas` has an `install_name` of `libopenblas.0.dylib` which means that some consuming packages struggle to consume libraries linked against openblas.

For example, `py-numpy` links against `openblas`, but when `py-numpy` is used by `py-netcdf4`, `py-netcdf4` fails to build as numpy does not prefix `@rpath/`. 

```
$ otool -L /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so
/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so:
	libopenblas.0.dylib (compatibility version 0.0.0, current version 0.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
``` 

```
[...]
          cmd LC_RPATH
      cmdsize 160
         path /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.27-oecxneqr7e2rdzlmv36r6wq4dn5aac2j/lib (offset 12)
Load command 26
```

```
$ spack install py-netcdf4
[...]

  Traceback (most recent call last):
    File "/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
      from . import multiarray
    File "/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
      from . import overrides
    File "/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: dlopen(/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Library not loaded: libopenblas.0.dylib
    Referenced from: <96301193-7C5B-311E-9A15-E84A444ECE1C> /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/py-numpy-1.26.4-47jedfkjvehucaeawa47zz5xm7vkogjd/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so
    Reason: tried: 'libopenblas.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibopenblas.0.dylib' (no such file), 'libopenblas.0.dylib' (no such file), '/Users/cmarsh/Documents/science/code/spack/stage/spack-stage-py-netcdf4-1.6.5-r52uf346tmcn7fmhko3phfo5vnztmt67/spack-src/libopenblas.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/cmarsh/Documents/science/code/spack/stage/spack-stage-py-netcdf4-1.6.5-r52uf346tmcn7fmhko3phfo5vnztmt67/spack-src/libopenblas.0.dylib' (no such file), '/Users/cmarsh/Documents/science/code/spack/stage/spack-stage-py-netcdf4-1.6.5-r52uf346tmcn7fmhko3phfo5vnztmt67/spack-src/libopenblas.0.dylib' (no such file)
```

/cc @adamjstewart 
Adam, this is the root of the build errors I reported in Slack yesterday.

I think the simplest solution is to ensure openblas has a sane install_name.

### Information on your system

```
spack debug report
* **Spack:** 0.23.0.dev0 (4240748ceac4eafd2e1b34dd98a93db41cbf5796)
* **Python:** 3.12.3
* **Platform:** darwin-sonoma-m1
* **Concretizer:** clingo
```

### Additional information

_No response_

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by Chrismarsh**
Fixes #45464

### CODE REVIEW

**Comment by Chrismarsh** [comment]
@spackbot fix style

**Comment by Chrismarsh** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
Could we apply the patch instead?

**Comment by haampie** [comment]
This should neither require a patch nor a post-install function.

Just add `self.define("CMAKE_POLICY_DEFAULT_CMP0042", "NEW")` to `cmake_args`.

I've submitted https://github.com/OpenMathLib/OpenBLAS/pull/4848 in the meantime.

**Comment by Chrismarsh** [comment]
TIL you can control that with a policy setting. Works as expected
```
otool -D libopenblas.dylib
libopenblas.dylib:
@rpath/libopenblas.0.dylib
```

**Comment by Chrismarsh** [comment]
Is there a reason that policy isn't set in the CMakeBuilder/Package classes by default when `platform=darwin`?

**Comment by haampie** [comment]
I guess because very few packages have `cmake_minimum_required(VERSION 2.*)`. `VERSION 3.0` is where the policy was set to NEW.

**Review by haampie — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
