### PR TITLE
rocm: removal of deprecated versions and redundant patches

### PR DESCRIPTION
**Pull request by haampie**
ROCm versions < 5.1 were deprecated before last release, so might as well remove them.

Note: removes `aomp` entirely since it was completely outdated, and no versions of its deps were available.

### CODE REVIEW

**Comment by haampie** [comment]
@cgmb do you know the status of the `aomp` package in Spack? Was it replaced by smth else?

**Comment by cgmb** [comment]
I'm not very familiar with aomp, but I don't think it's been replaced.

**Review by alalazo — APPROVED** [review]
Waiting to see if there's any objection, but LGTM

**Comment by alalazo** [comment]
@amd-toolchain-support

**Comment by haampie** [comment]
Pinging @afzpatel, @srekolam, @cgmb, @renjithravindrankannath if this is OK.

The controversial bit is removal of the `aomp` package as a whole. But I don't think it's _that_ controversial, since you can currently not even concretize `aomp` without the `--deprecated` flag: it's stuck on old versions of the rocm packages.

**Comment by srekolam** [comment]
> Pinging @afzpatel, @srekolam, @cgmb, @renjithravindrankannath if this is OK.
> 
> The controversial bit is removal of the `aomp` package as a whole. But I don't think it's _that_ controversial, since you can currently not even concretize `aomp` without the `--deprecated` flag: it's stuck on old versions of the rocm packages.

Yeah..aomp can be removed...its not being updated for year or two as far as i remember. other changes are okay with me,

**Review by srekolam — APPROVED** [review]

**Review by afzpatel — APPROVED** [review]

**Pull request merged**
