### PR TITLE
Bugfix/Update Tests That Need Access to /tmp/store

### PR DESCRIPTION
**Pull request by RikkiButler20**
Not everyone can make something in `/tmp/store`. It is throwing a `Permission Denied` error on an LC CZ system.

This PR switches to using a `store` subdirectory off of the unit test's `tmpdir`.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM, thanks.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Looks like flake8 errors need to be corrected before re-running the style fix spackbot command:

```
==> Running flake8 checks
[267](https://github.com/spack/spack/runs/7736460829?check_suite_focus=true#step:6:268)
==> Error: spack style found errors
[268](https://github.com/spack/spack/runs/7736460829?check_suite_focus=true#step:6:269)
lib/spack/spack/test/bootstrap.py:5: [F401] 'os' imported but unused
[269](https://github.com/spack/spack/runs/7736460829?check_suite_focus=true#step:6:270)
lib/spack/spack/test/bootstrap.py:159: [W291] trailing whitespace
[270](https://github.com/spack/spack/runs/7736460829?check_suite_focus=true#step:6:271)
lib/spack/spack/test/cmd/env.py:2746: [F841] local variable 'sep' is assigned to but never used
```

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by RikkiButler20** [comment]
@spackbot fix style

**Comment by RikkiButler20** [comment]
@spackbot fix style

**Comment by RikkiButler20** [comment]
@spackbot fix style

**Review by alalazo — APPROVED** [review]

**Pull request merged**
