### PR TITLE
r: add v4.2.3, v4.3.0

### PR DESCRIPTION
**Pull request by jeis4wpi**
Is this pull request OK to update R version?

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.  Deferring merge decision to @glennpj

**Comment by tldahlgren** [comment]
Looks like there's a configuration issue for one of the CI stacks.  See https://gitlab.spack.io/spack/spack/-/jobs/6908763.

**Comment by alalazo** [comment]
Can you resolve conflicts?

**Comment by alalazo** [comment]
Superseded by #45564 and others

**Pull request closed without merging**
