### PR TITLE
Update survey package file for survey version 9 changes.

### PR DESCRIPTION
**Pull request by jgalarowicz**
These are changes to the dependencies and tweaks to dependency requirements for the survey version 9 code.

### CODE REVIEW

**Comment by jgalarowicz** [comment]
I tried running style prior to submission but got this:
```jgalarowicz@fedora:~/ospack/spack/var/spack/repos/builtin/packages/survey$ spack style
==> Running style checks on spack
  selected: isort, black, flake8, mypy
==> Modified files
  package.py
==> Running isort checks
==> Error: 'NoneType' object is not callable
jgalarowicz@fedora:~/ospack/spack/var/spack/repos/builtin/packages/survey$ 
```
I'm not sure what black is but I see it failed in the checks for this pr.

**Review by tldahlgren — DISMISSED** [review]
I am unable to connect or locate the software repository to confirm the new version tags so am assessing solely based on changes here, which LGTM.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Please fix the style errors.  The tool (`black`) doesn't like single quotes.

**Comment by jgalarowicz** [comment]
@tldahlgren Thank you for your help!   I see that there was a dependency that was using single quotes instead of double.  I changed that.   The source code for survey is protected, so that is why you couldn't push.  Sorry about that.   Hopefully, that is the only complaint from black.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
