### PR TITLE
[py-numpy] Newer versions do not build with `icc`

### PR DESCRIPTION
**Pull request by stephenmsachs**
Workaround until https://github.com/numpy/numpy/issues/22011 is solved.

Flagging maintainers @adamjstewart , @rgommers

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot maintainers

**Comment by adamjstewart** [comment]
LGTM, will let @rgommers comment on whether there is a quick patch we can apply to fix this or whether we should wait for a new release.

**Comment by rgommers** [comment]
There's no patch yet, but I expect it will be solved fairly soon (`1.23.1` or `1.23.2`). It's due to the introduction of C++ in NumPy in 1.23.0, and there's a bunch of issues related to that which need to be addressed.

**Review by rgommers — APPROVED** [review]
LGTM

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
