### PR TITLE
Add/spack diff colored

### PR DESCRIPTION
**Pull request by vsoch**
This pull request is akin to https://github.com/spack/spack/pull/22283, but goes in a different direction to, instead of printing the attributes as lists, just display a colored diff of the spec string, formatted. It also adds a strikeout option to the tty color util. ~I'm opening it separately because I'm not convinced it's really better than the first - showing the attributes, verbatim, that are different has less visual clutter than printing an entire spec string that the user has to make sense of via color. I think it was discussed that this could eventually be a tree, but for the same reasons (namely visual complexity) I'm worried this would be too much for most cases except for very simple ones with mostly the same dependencies. So my suggestion is to first add this version to 1. see how people like it, and 2. not hold back any longer on being able to add a spack diff analyzer (although this also depends on the spack monitor PR for the analyzers) and we can test the tree functionality separately, and try to get feedback if people would want it.~  It looks like the following:

I tried cutting up the strings themselves to find overlap, but I think it's more straight forward to cross out the entire thing and show the new/old. Note that because it's based off of #22283, all the same commits are here.

image

**Update**: I'm going to create a diff.py module with a Diff that can accept two specs, and then hold the facts (for generation of json) or to generate this colored output, and then we can use it also with the spack diff analyzer. Something like:

```python
import spack.diff

# Create a new diff
diff = spack.diff.Diff(spec1, spec2)

# jump json facts
diff.json()

# Get any subset of data values
diff.intersect

# these could have better names
diff.a_not_b
diff.b_not_a

# print the diff colored (what we have now)
print(diff)

# print the diff tree
print(diff.tree())
```
Will do tomorrow!

### CODE REVIEW

**Comment by haampie** [comment]
neat :)

**Comment by vsoch** [comment]
I'm already not happy with it - I really should have added the tree here, and also the differences should be yellow/blue and then deletions / additions in green/red. Let's just consider this a work in progress for now :)

**Comment by vsoch** [comment]
It should theoretically be possible to walk through a spec (beyond the format string) and create one of these diffs for each dependency, and then stack them on top of each other with proper indentation. I'll think about it on my :runner:. What I'm not certain about is if it will be too much for the viewer, but in thinking about this just now I realize I won't be able to convince myself until I actually see it. So I'll work on that tomorrow.

**Comment by vsoch** [comment]
And I'm also kind of thinking that we should have a diff.py module that a command uses functions from, one of which will be a class for a Diff that can hold all this information, and then you can run the same tree() to have it generate the full thing. When we do the diff analyzer it will just use functions for there. Yeah. :)

**Comment by haampie** [comment]
Maybe you can flatten the tree and just show the unique packages? The new specs could be entirely green, removed specs entirely red, and only packages with different versions/variants would have an inline diff. 

It wouldn't show a diff on dependency types, but I wouldn't care a lot about that.

**Comment by vsoch** [comment]
@haampie if we have the logic to generate a colored (diffed) string for just one spec (one line) I think we could do it for each one! It just gets messy, for example, if you diff two completely different packages that have no overlap (then you would have big chunks of red and green.

**Comment by haampie** [comment]
> if you diff two completely different packages that have no overlap (then you would have big chunks of red and green.

but nobody does that ;p it's like using (git) diff on two unrelated files.

**Comment by vsoch** [comment]
@haampie haha true, but theoretically, the diff command can accept any two spec strings, so they could!

**Comment by vsoch** [comment]
Maybe a huge stream of red and green should be the punishment for bad diffing practices anyway :laughing:. It's immediate, direct negative feedback that they should never be so irresponsible to compare totally different packages again! :grin:

**Comment by haampie** [comment]
Also can you diff per variant? e.g. +pic and +shared could be white and not repeated in the first example in your screenshot

**Comment by vsoch** [comment]
@haampie yeah that's what I was referencing with:

> I tried cutting up the strings themselves to find overlap, but I think it's more straight forward to cross out the entire thing and show the new/old. Note that because it's based off of #22283, all the same commits are here.

I definitely will try it, after the tree thing is figured out.

Okay have to go for run - going to be getting dark at this point by the time I get back which is just bad life choices :laughing:

**Comment by vsoch** [comment]
okay I have the class! Still need to write the tree, that will have to wait until tomorrow.
image

**Comment by vsoch** [comment]
Making progress on the tree! (and being incredibly irresponsible not going to sleep, heh). Now we have:

 - a spack.diff module, with a spack.diff.SpecDiff class.
 - ability to create a differ, and then easy show intersect, and diffs (as before), or a json dump
 - now we also have the start of a tree!

We definitely need to think about colors and order for the tree. The logic now is that the first spec provided is considered the spec to diff against (e.g., something new in it will be green) but we could switch this up. As an example, here is a comparison between old and new singularity - the "new stuff" in singularity (Go) is in green, the shared stuff is in white (and not surprisingly, since it's the same spack install we see all overlap, these could have different colors and not be all white), and the stuff in old singularity not in new is in red.

image

and the other way:

image

It's not perfect, but it's a tree, which is what I was going for, so it's a good start! For next steps I probably need to:

 - make sure the extra red (the stuff at the bottom that isn't in one and gets lumped at the end) is in the proper depth, otherwise we don't see the relationship. Not sure the best way to do that yet since we are looping through one. Maybe since it's a dependency that is just totally missing, it's okay to leave down there?
 - add very nice documentation for the user to diff, and for the developer to use a differ
 - discuss if we want hashes, and if so, where and how
 - the spec format is a bit different than the spack spec - I need to compare the two and see if I can ensure they better match.
 - ass @haampie noted, we could get more into detail with diffing the names of the variants.

**Comment by vsoch** [comment]
And a more reasonable diff showing actual differences in a single line (zlib)

image

**Comment by vsoch** [comment]
Okay, updated again! I added the following:

 - a message to the user (and docs) to make it clear the direction of the diff, and what the colors mean
 - developer docs for using the SpecDiff class, and writing a differ (we could have others!)
 - added hashes for the top level specs to the message
 - added a missing space before arch= (when I compared to spack spec I forgot it)
 - added a ``--oneline`` command so the user can ask for a single line diff instead of the tree

Here is comparing singularity-legacy to singularity, meaning singularity is the "new one" with additions in green, removals in red:

image

White lines mean there is no difference. If there were differences in dependencies shared between the specs, they would be printed in the same red/green as we see in the one line view (it's just the case that I'm using the same ones so the lines are entirely white). and the same, but for one line (just comparing top level attributes)

image

And this functionality will be possible to analyze with an analyzer, but we need to get analyzers and this merged before I can reasonably do that.

**Comment by sethrj** [comment]
@vsoch This functionality  would be really cool! I was hoping to figure out what the hell the difference  between the concretized trilinos:
```
 -   cj7t57d  trilinos@13.0.1%gcc@8.3.0~adios2~alloptpkgs+amesos~amesos2~amesos2basker+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~trilinoscouplings~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long arch=linux-rhel6-x86_64
```
and my installed trilinos
```
fcyrpd4 trilinos@13.0.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml~mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
tfk2mms trilinos@13.0.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml~mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
ywyppaq trilinos@13.0.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
b4izrwy trilinos@13.0.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
sivma5d trilinos@13.0.1~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
a6schxv trilinos@13.0.1~adios2~alloptpkgs+amesos+amesos2~amesos2basker+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml~mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~trilinoscouplings~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
453voa2 trilinos@13.0.1~adios2~alloptpkgs+amesos+amesos2~amesos2basker+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~trilinoscouplings~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long
```
are 😂

**Comment by vsoch** [comment]
@sethrj also check out https://github.com/spack/spack/pull/22283! You could try either of these branches locally, but this PR is two and a half moths old and the other one three so I think it's unlikely at this point they will be merged. I think for those specs I'd try the one I linked first, which will show you the differences in atoms (single facts).

**Pull request closed without merging**
