### PR TITLE
[podio] Add new version and fix python unittest environment

### PR DESCRIPTION
**Pull request by tmadlener**
Add latest version for podio

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@tmadlener installl with `spack install --test=root podio`
```py
     465    92% tests passed, 1 tests failed out of 12
     466    
     467    Total Test time (real) =   1.63 sec
     468    
  >> 469    The following tests FAILED:
     470         12 - pyunittest (Failed)
```
LastTest.log:
```
RuntimeError: could not load cppyy_backend library


----------------------------------------------------------------------
Ran 16 tests in 0.004s

FAILED (errors=1)
<end of output>
Test time =   0.27 sec
----------------------------------------------------------
Test Failed.
"pyunittest" end time: Oct 12 14:45 UTC
"pyunittest" time elapsed: 00:00:00
```
You could add `cppyy_backend` as a new package `py-cppyy_backend` (for me it would be ok if added to this PR to keep things simple), or remove the test from the test execution to fix it(maybe simpler).

**Comment by tmadlener** [comment]
Hi @bernhardkaindl that to me looks like potentially `root` is not properly set up in the environment where the tests are run, because the `cppyy_backend` usually comes with that in our case. I will have a look into this.

Is this the complete output from the tests?

**Comment by bernhardkaindl** [comment]
> Hi @bernhardkaindl that to me looks like potentially `root` is not properly set up in the environment where the tests are run, because the `cppyy_backend` usually comes with that in our case. I will have a look into this.
> 
> Is this the complete output from the tests?

It's the only failure, so you could just disable it, but I agree it should be able to use the cppyy_backend which is in `root`, it seems to use it already, just fails to import the backend of it:
```py
Command: "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/python-3.8.11-qh4rt3wnm2rcxqpnxqzfpnktht5d3wmy/bin/python" "-m" "unittest" "discover" "-s" "/home/kaindlb/home/spack/.stage/spack-stage-podio-0.13.2-23f4e7d22sqm5ry5ddvwumu3nwwecdkf/spack-src/python"
Directory: /home/kaindlb/home/spack/.stage/spack-stage-podio-0.13.2-23f4e7d22sqm5ry5ddvwumu3nwwecdkf/spack-build-23f4e7d/tests
ERROR: test_EventStore (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_EventStore
Traceback (most recent call last):
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/python-3.8.11-qh4rt3wnm2rcxqpnxqzfpnktht5d3wmy/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/python-3.8.11-qh4rt3wnm2rcxqpnxqzfpnktht5d3wmy/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/kaindlb/home/spack/.stage/spack-stage-podio-0.13.2-23f4e7d22sqm5ry5ddvwumu3nwwecdkf/spack-src/python/test_EventStore.py", line 5, in <module>
    from EventStore import EventStore
  File "/home/kaindlb/home/spack/.stage/spack-stage-podio-0.13.2-23f4e7d22sqm5ry5ddvwumu3nwwecdkf/spack-src/python/EventStore.py", line 5, in <module>
    from ROOT import gSystem
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/root-6.24.06-65jied6ykiu5a75wug7bm2l254c525h5/lib/ROOT/__init__.py", line 22, in <module>
    import cppyy
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/root-6.24.06-65jied6ykiu5a75wug7bm2l254c525h5/lib/cppyy/__init__.py", line 131, in <module>
    from ._cpython_cppyy import *
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/root-6.24.06-65jied6ykiu5a75wug7bm2l254c525h5/lib/cppyy/_cpython_cppyy.py", line 18, in <module>
    c = loader.load_cpp_backend()
  File "/home/kaindlb/home/spack/.tree1/linux-ubuntu18.04-zen2/gcc-11.2.0/root-6.24.06-65jied6ykiu5a75wug7bm2l254c525h5/lib/cppyy_backend/loader.py", line 74, in load_cpp_backend
    raise RuntimeError("could not load cppyy_backend library")
```

**Comment by tmadlener** [comment]
Should be fixed now. Upstream fixes this in AIDASoft/podio#236

**Review by bernhardkaindl — APPROVED** [review]
Thanks! Looks Great to me!

**Pull request merged**
