### PR TITLE
sst: update core, elements, macro to 14.1.0

### PR DESCRIPTION
**Pull request by jmlapre**
Update `sst-core`, `sst-elements`, and `sst-macro` packages to 14.1.0.
Also add in the 14.0.0 releases that were skipped.

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
.

**Review by bernhardkaindl — APPROVED** [review]
-

**Comment by bernhardkaindl** [comment]
@spackbot maintainers

**Review by bernhardkaindl — APPROVED** [review]
.

**Review by bernhardkaindl — APPROVED** [review]
-

**Review by bernhardkaindl — APPROVED** [review]
Hello @berquist and @naromero77, I generated some build results:<br>
:information_source: `spack install` on the changed recipes of this PR was successful[^1] on Ubuntu 22.04.4 LTS!<details><summary><b>Click here for a summary of the successful builds.</b></summary>
These changed specs were found using [gh pr diff](https://cli.github.com):
- `sst-core@14.1.0`
- `sst-core@14.0.0`
- `sst-elements@14.1.0`
- `sst-elements@14.0.0`
- `sst-macro@14.1.0`
- `sst-macro@14.0.0`


<details><summary><b>Click here to show/hide the report on </b><tt>spack find</tt> for <tt>linux-ubuntu22.04-skylake / gcc@13.1.0</tt>.</summary><ol>

<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-core@14.0.0~hdf5+pdes_mpi~preview~profile~trackevents~trackperf~zlib build_system=autotools
>```
</summary>

>```py
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>			diffutils@3.10
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>		autoconf@2.72
>			m4@1.4.19sigsegv,bfdffa7
>				libsigsegv@2.14
>		automake@1.16.5
>		hwloc@2.11.1-level-zero
>			libpciaccess@0.17
>				util-macros@1.20.1
>		libevent@2.1.12openssl
>		libtool@2.4.7
>			findutils@4.9.0
>		numactl@2.0.18
>		openssh@9.8p1gssapi
>			krb5@1.21.3
>				bison@3.8.2
>			libedit@3.1-20240808
>		perl@5.34.0
>		pkgconf@2.2.0
>		pmix@5.0.3
>		zlib-ng@2.2.1compatnew_strategiesopt
>	python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>		expat@2.6.3libbsd
>			libbsd@0.12.2
>				libmd@1.0.4
>		gdbm@1.24
>		libffi@3.4.6
>		libxcrypt@4.4.35_api
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		readline@8.2
>		sqlite@3.46.0column_metadatadynamic_extensionsfts
>		util-linux-uuid@2.40.2
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-core@14.1.0~hdf5+pdes_mpi~preview~profile~trackevents~trackperf~zlib build_system=autotools
>```
</summary>

>```py
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>			diffutils@3.10
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>		autoconf@2.72
>			m4@1.4.19sigsegv,bfdffa7
>				libsigsegv@2.14
>		automake@1.16.5
>		hwloc@2.11.1-level-zero
>			libpciaccess@0.17
>				util-macros@1.20.1
>		libevent@2.1.12openssl
>		libtool@2.4.7
>			findutils@4.9.0
>		numactl@2.0.18
>		openssh@9.8p1gssapi
>			krb5@1.21.3
>				bison@3.8.2
>			libedit@3.1-20240808
>		perl@5.34.0
>		pkgconf@2.2.0
>		pmix@5.0.3
>		zlib-ng@2.2.1compatnew_strategiesopt
>	python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>		expat@2.6.3libbsd
>			libbsd@0.12.2
>				libmd@1.0.4
>		gdbm@1.24
>		libffi@3.4.6
>		libxcrypt@4.4.35_api
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		readline@8.2
>		sqlite@3.46.0column_metadatadynamic_extensionsfts
>		util-linux-uuid@2.40.2
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-elements@14.0.0~dramsim2~dramsim3~dumpi~flashdimmsim~goblin~hbm~hybridsim~nvdimmsim~otf~otf2~pin~ramulator build_system=autotools
>```
</summary>

>```py
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>			diffutils@3.10
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>		expat@2.6.3libbsd
>			libbsd@0.12.2
>				libmd@1.0.4
>		gdbm@1.24
>		libffi@3.4.6
>		libxcrypt@4.4.35_api
>			perl@5.34.0
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pkgconf@2.2.0
>		readline@8.2
>		sqlite@3.46.0column_metadatadynamic_extensionsfts
>		util-linux-uuid@2.40.2
>	sst-core@14.1.0_mpi
>		openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>			autoconf@2.72
>				m4@1.4.19sigsegv,bfdffa7
>					libsigsegv@2.14
>			automake@1.16.5
>			hwloc@2.11.1-level-zero
>				libpciaccess@0.17
>					util-macros@1.20.1
>			libevent@2.1.12openssl
>			libtool@2.4.7
>				findutils@4.9.0
>			numactl@2.0.18
>			openssh@9.8p1gssapi
>				krb5@1.21.3
>					bison@3.8.2
>				libedit@3.1-20240808
>			pmix@5.0.3
>	zlib-ng@2.2.1compatnew_strategiesopt
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-elements@14.1.0~dramsim2~dramsim3~dumpi~flashdimmsim~goblin~hbm~hybridsim~nvdimmsim~otf~otf2~pin~ramulator build_system=autotools
>```
</summary>

>```py
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>			diffutils@3.10
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>		expat@2.6.3libbsd
>			libbsd@0.12.2
>				libmd@1.0.4
>		gdbm@1.24
>		libffi@3.4.6
>		libxcrypt@4.4.35_api
>			perl@5.34.0
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pkgconf@2.2.0
>		readline@8.2
>		sqlite@3.46.0column_metadatadynamic_extensionsfts
>		util-linux-uuid@2.40.2
>	sst-core@14.1.0_mpi
>		openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>			autoconf@2.72
>				m4@1.4.19sigsegv,bfdffa7
>					libsigsegv@2.14
>			automake@1.16.5
>			hwloc@2.11.1-level-zero
>				libpciaccess@0.17
>					util-macros@1.20.1
>			libevent@2.1.12openssl
>			libtool@2.4.7
>				findutils@4.9.0
>			numactl@2.0.18
>			openssh@9.8p1gssapi
>				krb5@1.21.3
>					bison@3.8.2
>				libedit@3.1-20240808
>			pmix@5.0.3
>	zlib-ng@2.2.1compatnew_strategiesopt
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-macro@14.0.0~core~otf2~pdes_mpi+pdes_threads+shared~skeletonizer+static~warnings~werror build_system=autotools
>```
</summary>

>```py
>	binutils@2.43.1 compress_debug_sections=zlib
>		diffutils@3.10
>		pkgconf@2.2.0
>		zstd@1.5.6
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	zlib-ng@2.2.1compatnew_strategiesopt
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>sst-macro@14.1.0~core~otf2~pdes_mpi+pdes_threads+shared~skeletonizer+static~warnings~werror build_system=autotools
>```
</summary>

>```py
>	binutils@2.43.1 compress_debug_sections=zlib
>		diffutils@3.10
>		pkgconf@2.2.0
>		zstd@1.5.6
>	gcc-runtime@13.1.0
>	gettext@0.22.5bzip2cursesgit
>		bzip2@1.0.8
>		libiconv@1.17
>		libxml2@2.10.3
>		ncurses@6.5
>		tar@1.34 zip=pigz
>		xz@5.4.6
>	glibc@2.35
>	gmake@4.4.1
>	zlib-ng@2.2.1compatnew_strategiesopt
>
>```

</details>



</details>

[^1]: Orchestrated using `spack install` by [github.com/spack/gh-spack-pr](https://github.com/spack/gh-spack-pr) and the [GitHub CLI](https://cli.github.com/)
</details><details><summary>Click here for a disclaimer for the maintainers of the recipes

</summary><br>👍 Hello @naromero77 and @berquist!<br><br>

- We would like to ask you if you could review this PR within 5 days.
- If the PR is not reviewed within 5 days, the PR can be approved and merged by members.
- Please use 👍, Approve, LGTM or Request the comment so we can act accordingly.
- If you like to review but need more time, please add a comment to the PR.
- If you have questions (or would like to be removed as maintainer), please let us know.

Thank you for your time and effort!<br>
You can also join the Spack Slack channel for more information and have a chat:
https://spackpm.slack.com → #pull-requests. Thank you and best regards, @bernhardkaindl</details>

**Review by alalazo — APPROVED** [review]

**Pull request merged**
