### PR TITLE
py-kornia: add v0.6.10

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/kornia/kornia/releases/tag/v0.6.10

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
