### PR TITLE
Remove -g flag by default in binutils

### LINKED ISSUE #18120: Smaller binutils
I'm trying to keep docker images and buildcaches small, and I found that one of the biggest build dependencies (that I actually need) is binutils:

```
$ du -sh binutils-2.34-4hl4mkoryxkvsy6ejglack3x7ygxl7m5/
755M	binutils-2.34-4hl4mkoryxkvsy6ejglack3x7ygxl7m5/
```

There's many exact duplicates of executables:

```
$ cd binutils-2.34-4hl4mkoryxkvsy6ejglack3x7ygxl7m5
$ du -sh x86_64-pc-linux-gnu/bin/
190M	x86_64-pc-linux-gnu/bin/
$ ls x86_64-pc-linux-gnu/bin/
ar  as	dlltool  ld  ld.bfd  ld.gold  nm  objcopy  objdump  ranlib  readelf  strip
$ ls bin/
addr2line  ar  as  c++filt  coffdump  dlltool  dllwrap	dwp  elfedit  gprof  ld  ld.bfd  ld.gold  nm  objcopy  objdump	ranlib	readelf  size  srconv  strings	strip  sysdump	windmc	windres
$ du -sh bin/
262M	bin/
$ for f in x86_64-pc-linux-gnu/bin/*; do diff "bin/$(basename $f)" "$f"; done
$
```

Some binaries are for more than 95% debuginfo:

```
$ cd bin
$ du -sh ld.gold 
131M	ld.gold
$ ./strip --strip-all ld.gold 
$ du -sh ld.gold 
5.2M	ld.gold
```

### Description

Before https://github.com/spack/spack/issues/9388 is a thing, should we just add a patch to drop the `-g` flag from binutils by default? I think #9388 is a bit difficult for the binutils package itself, since binutils provides the `strip` executable...

Further I can check why there's duplicate binaries being installed instead of just symlinks (or maybe we can just drop that x86_64-pc-linux-gnu folder).

### General information

```
$ spack --version
0.15.4-567-632032c02
```

### PR DESCRIPTION
**Pull request by haampie**
Makes binutils 75% smaller. Before:

```
543M    /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-s5r3knl7xrfiklphlgqobkwn242lytin
```
after:
```
142M    /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-t67x54dbrf7yk5t3qaqjifycex3zeiwx
```

Edit: strategy has changed from adding a patch, to setting default optimization flags in `package.py` and making them overridable through `cflags=...`

Closes #18120

### CODE REVIEW

**Comment by mwkrentel** [comment]
I object to this.  Binutils is a fairly well-behaved autotools package
and will respond to CFLAGS.  The default is `-g -O2`, but you can
specify anything you want with CFLAGS and binutils will obey.
Basically, you're saying that you don't like autotools.

If you want to build with `-O2`, then you can specify `cflags='-O2'`,
or possibly add a variant that adds it to the build system flags via a
flags handler.  That would be the cleaner approach.  (Patch is a bad
idea because the patch will change with each version.)

But it MUST be a variant because some people (eg tools writers) need
debug info.

Note: spack and autotools flags don't exactly play nice together.
I made a proposal to overhaul how spack handles this, basically to
treat autotools more like cmake.  That would be the clean way of
handling issues like this.  But it didn't get any traction.

See #14430.  Ping @tgamblin again.

**Comment by haampie** [comment]
@mwkrentel: thanks for your comment.

> Binutils is a fairly well-behaved autotools package and will respond to CFLAGS. The default is -g -O2, but you can specify anything you want with CFLAGS and binutils will obey.

Maybe I'm missing something, but it seems binutils will always append `-g` when it's missing from the cflags:

```
$ spack install binutils cflags='-O2'
...
==> Installing binutils
==> No binary for binutils found: installing from source
==> binutils: Executing phase: 'autoreconf'
==> binutils: Executing phase: 'configure'
==> binutils: Executing phase: 'build'
==> binutils: Executing phase: 'install'
[+] /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-g43epuye2umzxxz7v7ljqan4kbmih3zk

$ du -sh /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-g43epuye2umzxxz7v7ljqan4kbmih3zk
543M    /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-g43epuye2umzxxz7v7ljqan4kbmih3zk

$ grep 'O2' /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.34-g43epuye2umzxxz7v7ljqan4kbmih3zk/.spack/spack-build-out.txt | head -n1
  /home/harmen/spack/lib/spack/env/gcc/gcc -c -DHAVE_CONFIG_H -g -O2  -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE -fpic ./regex.c -o pic/regex.o; \
```

Edit: ah, we have to use `build_system_flags` in the `flag_handler` instead.

> But it MUST be a variant because some people (eg tools writers) need debug info.

Those people can do `spack install binutils cflags='-O0 -g'`

---

Edit: I've removed the patch and made `-O2` without debug flags the default in the `flag_handler`. This way the user can still do `spack install binutils cflags='-O0 -g'` to get a proper debug version, and the majority of the users will simply get a trimmed down non-debug binutils by default. 

@mwkrentel: do you think this is an acceptable solution for now? I know you'd rather have variants `+debug_info` and `opt_level=` s.t. setting flags is more composable, but maybe that's for another PR. Developers of binutils that use spack (if there are any) are probably happy to set `cflags=...` on the command line as wel...

**Comment by mwkrentel** [comment]
@haampie   You're on the right track with flag_handler, but no, I don't quite
agree with the logic.

First, this really needs to be a variant.  Spack's `cflags` propagates
to dependencies and that's not what we want.  (Sorry, I shouldn't have
confused CFLAGS and cflags.)

```
variant('debug-symbols', default=True, description='Enable debug symbols.')
```

Note: `debug-symbols` just means include `-g`, it doesn't imply `-O0`.

Then, for both cflags and cxxflags (binutils is mostly C, but gold is C++),
test for two things:

1. if `not opt_flag_found`, then append `-O2`.

2. if `+debug-symbols in spec`, then append `-g`.

Then return as `(None, None, flags)` as you have done.

This doesn't have to be the full debug/opt framework that I proposed
in #14430, but if you want to disable `-g`, then use a variant for that.

----------

Btw, I think the "default" for debug-symbols should be True.  Both
cases, with and without `-g` are legitimate use cases.  But here, I
don't see a strong 90-10 split for popularity one way or the other.

So in this case, I think the default should fall back to the native
binutils default which is `-g -O2`, same as the cmake default `RelWithDebInfo`.
I think that causes the least shock value to the most users.

**Comment by haampie** [comment]
> First, this really needs to be a variant. Spack's cflags propagates to dependencies and that's not what we want. (Sorry, I shouldn't have confused CFLAGS and cflags.)

Even if you set it in packages.yaml instead of over the CLI?

> But here, I don't see a strong 90-10 split for popularity one way or the other.

Well... I can see there could be users installing binutils for the executables (`strip`, `readelf`, `objdump`, ...), and otherwise it might get installed with a build of `llvm` or maybe `gcc`; I don't see the need for debug symbols in those cases. Also note that `llvm` already builds in release by default because debug symbols make it too big.

Further note that e.g. ubuntu/`apt` ships a tiny version of binutils of 15MB, which is less than 3% of the size that spack gives you.

**Comment by mwkrentel** [comment]
Well first, add a variant for debug-symbols.  Then, we can ask a
reviewer for advice on the default.

I've always set the default for what I think is the best decision for
the most number of users.  It's always been on, no one has
complained before, disk space is cheap, etc.

But go ahead and set it to False.
But please add a variant.

**Comment by haampie** [comment]
@adamjstewart could you remove the `patch` label? Currently it's just adding a new variant, that's changing the default behavior of the package slightly to not add debug flags.

Also this PR is done as far as I am concerned, maybe someone else should review this PR indeed to weigh in on the dispute of having `-g` or not by default. Pinging @alalazo / @becker33 :)

**Comment by mwkrentel** [comment]
Ok, I can live with this.

But I'm not 100% sure about this part of the patch:

```
-        elif name == 'cflags':
-            if self.spec.satisfies('@:2.34 %gcc@10:'):
-                flags.append('-fcommon')

+        if name == 'cflags' and '@:2.34 %gcc@10:' in self.spec:
+            flags.append('-fcommon')
```

My conern is how `in` treats the two-element `@:2.34 %gcc@10:` item
versus `spec.satisfies`.

I don't mean to spread FUD, I'm just not sure how `in` treats two
elements in the string.  For example, is `@:2.34 %gcc@10:` in
`@:2.34 +nls %gcc@10:` ?

Someone above my spack level should check this.

Btw, is `in` in this case a spack question or a pure python question?

**Comment by adamjstewart** [comment]
@mwkrentel this is a Spack question. I believe this works fine, and is more or less equivalent to `spec.satisfies('@:2.34 %gcc@10:')`, but @becker33 can comment if I'm wrong.

**Comment by haampie** [comment]
@mwkrentel: it's fine like it is, I verified it for you.

@adamjstewart: any thoughts on this PR?

**Comment by haampie** [comment]
I'm just gonna close this

**Pull request closed without merging**
