### PR TITLE
qgis: unpin qca, update qca

### PR DESCRIPTION
**Pull request by aweits**
allows compilation with gcc 11

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Will give @Sinan81 a chance to review

**Comment by Sinan81** [comment]
sorry for the late reply. If QGIS builds just fine, this should be ok merge.

**Review by Sinan81 — APPROVED** [review]
@aweits please confirm qgis builds.

**Comment by aweits** [comment]
> @aweits please confirm qgis builds.

Confirmed, this change was necessary to make qgis build with gcc@11.3.1

**Comment by Sinan81** [comment]
please merge!

**Pull request merged**
