### PR TITLE
ambertools: new package

### PR DESCRIPTION
**Pull request by d-beltran**
This package worked properly in a custom spack.
However, I was not able to test it in the current spack due to a known [issue](https://github.com/spack/spack/issues/41146) with the python tkinter variant.

### CODE REVIEW

**Comment by alalazo** [comment]
I think this package is already installed as a resource of `amber`. Does it make sense to have it as a standalone?

**Comment by w8jcik** [comment]
One issue is that Amber requires a license and `amber` Spack package doesn't allow skipping installation of Amber.

In contrast Amber-Tools are available without any license and can be used without Amber.

It would be nice to have it installable through Spack.

**Comment by d-beltran** [comment]
Sorry for my late reply, I don't know why I did not receive a notification for your comments.

As @w8jcik just said it is not possible to install amber without a license you have to buy. We tried already to install amber in out custom spack environment only to use ambertools and we failed, so we ended up creating a separated ambertools package.

**Comment by hseara** [comment]
I think this package could be make part of `amber` package. With an option saying tools only, or something like that. The main problem now with the `amber` package is that the transition to `cmake`, but in a very weird way and I din not have time to make it work. If someone want to help I will very glad.

Also, please note that Amber is now free for academics. It still requires manual download though.

**Comment by alalazo** [comment]
Let me know how you want to proceed (whether with a variant on `amber`, or with a standalone package)

**Comment by hseara** [comment]
> Let me know how you want to proceed (whether with a variant on `amber`, or with a standalone package)

Currently, the logic of `amber` package is that the main download is the non-free part of amber package and the tools are a secondary download. Both nevertheless currently need to be locally download prior installation are there is no link available for the download.  The reality is that one can install ambertools alone, but to install the full amber you need both ambertools and amber (the non free part, free for academics up on request).

After thinking a bit, and in order to reduce the number of packages, and take advantage of the installation machinery that is mostly common between the two, I would make one single package called `amber`.  However, I would make ambertools the default installation and add a variant `+full`, that adds the non free amber part.

What do you think? My only issue is that I have no time to do so until April. So, I will gladly accept any help to start working on this.

I would not mind using the jobe done here as starting point for a completely new refactored `amber` package.

**Comment by d-beltran** [comment]
> Let me know how you want to proceed (whether with a variant on amber, or with a standalone package)

I don't have a strong opinion here. If @hseara prefers to make a single amber package then it works for me. However it may be good having a working ambertools package while we wait for the final implementation.

I'm afraid I won't be able to help with the final implementation. I am not an expert in amber or spack (not even a regular user to be honest). I wouldn't have been able to do this ambertools package if not for the help of @elenimath who is very skilled with spack.

**Comment by hseara** [comment]
A single package makes more sense. I will have time in April; until then, I am afraid I cannot do much. If anyone else wants to step in, they are more than welcome.

:warning:  By the way, after thinking a bit, the variant name could be `+ambertools_only`. Then we can make ambertools as the main update.

**Comment by d-beltran** [comment]
Hey @hseara,

Did you have time to start implementing the new ambertools variant?

Best regards

**Comment by d-beltran** [comment]
Hey @hseara,

Any update?

Regards

**Review by bernhardkaindl — APPROVED** [review]
rebased to develop, fixed to build with it (on Ubuntu 22.04)

**Review by bernhardkaindl — APPROVED** [review]
@d-beltran, @w8jcik, @hseara:

I was able to fix the build with the current `spack` `develop` branch.

It had to be re-based on top of it and `setuptools` was split from python, so it now has to be depended on explicitly.

It uses `longintrepr.h` that was removed in Python 3.11, so it can only be built using Python 3.8 to 3.10.
For further info, see for example: https://github.com/aio-libs/aiohttp/issues/6600

I case you want to try to support 3.11 in a future PR, a possible workaround might be described here:
https://stackoverflow.com/questions/74979674/gensim-install-in-python-3-11-fails-because-of-missing-longintrepr-h-file
- Python 3.12 will need an update to a newer version or patching to replace the used `împort` of `distutils` with `setuptools`

With this, the build was finally successful.

If GitLab CI passes, it should be merged in a few days.

**Pull request merged**
