### PR TITLE
ML CI: Ubuntu 22 -> 24

### PR DESCRIPTION
**Pull request by adamjstewart**
This should provide us with a new enough GCC that we can build the latest version of TF.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Bleh, JAX requires older Bazel that doesn't support GCC 13. Not sure if it can be patched.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Depends on https://github.com/spack/gitlab-runners/pull/56

**Comment by aweits** [comment]
looking at the CI failures now...

**Comment by adamjstewart** [comment]
Here are my thoughts. All issues seem to be due to C++17 support. Also, they are always with vendored dependencies, making them extra fun to patch/fix.

### ~py-torch 2.0.1~

```
  /tmp/root/spack-stage/spack-stage-py-torch-2.0.1-fyryix325emsz7lvkzn6ei32xup47chq/spack-src/third_party/kineto/libkineto/src/SampleListener.h:96:13: error: variable or field 'init' declared void
     96 | inline void SampleValue::init(uint64_t v) {
        |             ^~~~~~~~~~~
```
Looks like an issue with new C++ standards. Might just be able to disable `+kineto` when using this compiler. Ideally, we could figure out which package requires such an old version of PyTorch and update it.

EDIT: This was fixed in kineto in https://github.com/pytorch/kineto/pull/749 and updated in PyTorch in 2.1.0: https://github.com/pytorch/pytorch/pull/106672.

EDIT: torch 2.0.1 is required by horovod due to https://github.com/horovod/horovod/issues/3996. This has been fixed in main, so we could patch horovod or wait for a new release.

### ~py-dm-tree 0.1.8~

```
  /tmp/root/spack-stage/spack-stage-py-dm-tree-0.1.8-3lyfldjg2kb5tvzrczumm3qgnsczcpew/spack-src/tree/abseil-cpp/src/abseil-cpp/absl/strings/internal/str_format/extension.h:34:33: error: found ':' in nested-name-specifier, expected '::'
     34 | enum class FormatConversionChar : uint8_t;
        |                                 ^
        |                                 ::
```
Probably similar. Can't find any open issues. No releases in 2 years.

EDIT: Fixed in https://github.com/abseil/abseil-cpp/pull/1187, we just need to figure out how to build with external absl or patch this.

EDIT: Support for external pybind11/absl was added in https://github.com/google-deepmind/tree/pull/73, but hasn't been released yet.

### ~py-onnx 1.16.1~

```
  /tmp/root/spack-stage/spack-stage-py-onnx-1.16.1-xgzpmim5z7xe75vi466xzpbjzot6hkjm/spack-src/.setuptools-cmake-build/_deps/protobuf-src/src/google/protobuf/port.h:186:67: error: 'uint32_t' was not declared in this scope
    186 |     : absl::disjunction<std::is_same<T, int32_t>, std::is_same<T, uint32_t>,
        |                                                                   ^~~~~~~~
```
https://github.com/onnx/onnx/issues/6295. This is an issue that was fixed in newer versions of protobuf, so we either apply the patch to onnx too, or even better, we figure out how to convince onnx to build using Spack-installed protobuf.

### ~bazel 6.1.0, 6.1.2~

```
ERROR: /tmp/bazel_W8S0mKIf/out/external/com_google_absl/absl/strings/BUILD.bazel:1078:11: Compiling absl/strings/internal/str_format/extension.cc [for tool] failed: (Exit 1): gcc failed: error executing command (from target @com_google_absl//absl/strings:str_format_internal)
...
external/com_google_absl/absl/strings/internal/str_format/extension.h:34:33: error: found ':' in nested-name-specifier, expected '::'
   34 | enum class FormatConversionChar : uint8_t;
      |                                 ^
      |                                 ::
```
Same problem with dm-tree, either patch this package too or figure out how to use and patch externally installed absl. Or, figure out why we're building an older version of bazel instead of 6.5.0.

EDIT: Fixed in https://github.com/abseil/abseil-cpp/pull/1187, we just need to figure out how to build with external absl or patch this.

EDIT: tensorflow 2.14:2.15 (required by tensorflow-probability) requires bazel 6.1.0, jaxlib 0.4.11:0.4.27 (required by keras) requires bazel 6.1.2. So we can't just avoid these older bazel versions, unless we can get newer bazel versions working or add a newer version of tensorflow-probability.

@aweits I have no knowledge of C++ and only limited knowledge of patching things. I'm going to focus on figuring out how to build with newer versions of dependencies. If you can focus on C++ and we can work together on patching, I think we can solve this. Then we can finally get the build working on aarch64.

**Comment by adamjstewart** [comment]
@spackbot maintainers

**Comment by adamjstewart** [comment]
@aweits I've fixed everything except the bazel 6.1 builds. Can you take a look at those?

**Comment by aweits** [comment]
give this a try?

```diff
diff --git a/var/spack/repos/builtin/packages/bazel/abseil-cpp-gcc-13-patch b/var/spack/repos/builtin/packages/bazel/abseil-cpp-gcc-13-patch
new file mode 100644
index 00000000000..ee2e61df596
--- /dev/null
+++ b/var/spack/repos/builtin/packages/bazel/abseil-cpp-gcc-13-patch
@@ -0,0 +1,27 @@
+diff --git a/distdir_deps.bzl b/distdir_deps.bzl
+index 345e8ca985ee..b2e42112aca9 100644
+--- a/distdir_deps.bzl
++++ b/distdir_deps.bzl
+@@ -229,17 +229,17 @@ DIST_DEPS = {
+         ],
+     },
+     "com_google_absl": {
+-        "archive": "20211102.0.tar.gz",
+-        "sha256": "dcf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4",
++        "archive": "20220623.1.tar.gz",
++        "sha256": "91ac87d30cc6d79f9ab974c51874a704de9c2647c40f6932597329a282217ba8",
+         "urls": [
+-            "https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/refs/tags/20211102.0.tar.gz",
+-            "https://github.com/abseil/abseil-cpp/archive/refs/tags/20211102.0.tar.gz",
++            "https://mirror.bazel.build/github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz",
++            "https://github.com/abseil/abseil-cpp/archive/refs/tags/20220623.1.tar.gz",
+         ],
+         "used_in": [
+             "additional_distfiles",
+             "test_WORKSPACE_files",
+         ],
+-        "strip_prefix": "abseil-cpp-20211102.0",
++        "strip_prefix": "abseil-cpp-20220623.1",
+     },
+     "zstd-jni": {
+         "archive": "v1.5.2-3.zip",
diff --git a/var/spack/repos/builtin/packages/bazel/package.py b/var/spack/repos/builtin/packages/bazel/package.py
index 52ba8f74bf1..f01999b668b 100644
--- a/var/spack/repos/builtin/packages/bazel/package.py
+++ b/var/spack/repos/builtin/packages/bazel/package.py
@@ -110,6 +110,8 @@ class Bazel(Package):
         when="@5.0:5.4.0,6.0",
     )
 
+    patch("abseil-cpp-gcc-13-patch", when="@6.1.0:6.1.2 %gcc@13:")
+
     # Fix build with Fujitsu compiler
     patch("blaze_util_posix-0.29.1.patch", when="%fj")
     patch("unix_cc_configure_fj-5.2.patch", when="@5.2:%fj")
@@ -132,7 +134,7 @@ class Bazel(Package):
     # Newer versions of grpc and abseil dependencies are needed but are not in bazel-4.0.0
     conflicts("@4.0.0", when="%gcc@11:")
     # https://github.com/bazelbuild/bazel/issues/18642
-    conflicts("@:6", when="%gcc@13:")
+#    conflicts("@:6", when="%gcc@13:")
 
     executables = ["^bazel$"]
```

**Comment by adamjstewart** [comment]
Your genius led me to https://github.com/bazelbuild/bazel/pull/20785 which I'll try to backport.

**Review by aweits — APPROVED** [review]

**Pull request merged**
