### PR TITLE
charmpp: add conflict with +shared on macOS with GCC

### PR DESCRIPTION
**Pull request by nilsvu**

### CODE REVIEW

**Comment by nilsvu** [comment]
@matthiasdiener A few more issues I'd like to get your opinion on:

- `spack install charmpp@6.10.2 %apple-clang@13:` also fails on my macOS machine, with issues related to the old `VERSION` file interfering with other version files. Should we attempt to patch / fix / disable that as well?
- The same issue occurs with `%clang@13:`, where I have clang 13 installed from `brew install llvm`. However, I'm actually not quite sure if the Charm++ build picks up the correct compiler here, or if the system's apple-clang is used, because it is simply passed as `./build LIBS ARCH clang`. The LLVM clang should be the one in `PATH`, but from the build output I don't immediately see if it's being used correctly.

**Review by matthiasdiener — APPROVED** [review]
Thanks!

**Comment by matthiasdiener** [comment]
> @matthiasdiener A few more issues I'd like to get your opinion on:
> 
> * `spack install charmpp@6.10.2 %apple-clang@13:` also fails on my macOS machine, with issues related to the old `VERSION` file interfering with other version files. Should we attempt to patch / fix / disable that as well?

Not sure, are you interested in running 6.10.2 still? https://github.com/UIUC-PPL/charm/pull/3112 is a pretty complicated patch :-(

> * The same issue occurs with `%clang@13:`, where I have clang 13 installed from `brew install llvm`. However, I'm actually not quite sure if the Charm++ build picks up the correct compiler here, or if the system's apple-clang is used, because it is simply passed as `./build LIBS ARCH clang`. The LLVM clang should be the one in `PATH`, but from the build output I don't immediately see if it's being used correctly.

Does this work correctly if not installing from spack?

**Comment by nilsvu** [comment]
@matthiasdiener For myself it wouldn't be worth the effort to fix versions below charmpp@7.0.0. It would be good to avoid accidentally selecting broken versions though. Would it be too drastic to add `conflict("platform=darwin", when="@:6.10.2 %apple-clang")`, and the same for `clang`, which essentially disables all clang macOS builds below v7.0.0?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Let me know whether you want to add:
```python
conflict("platform=darwin", when="@:6.10.2 %apple-clang")
```
or it is fine to merge this PR as is. Thanks!

**Comment by nilsvu** [comment]
@alalazo Please merge, I'll open separate PRs for the other issues once we make decisions on them.

**Comment by matthiasdiener** [comment]
> @matthiasdiener For myself it wouldn't be worth the effort to fix versions below charmpp@7.0.0. It would be good to avoid accidentally selecting broken versions though. Would it be too drastic to add `conflict("platform=darwin", when="@:6.10.2 %apple-clang")`, and the same for `clang`, which essentially disables all clang macOS builds below v7.0.0?

Imho, this might be too drastic. I think at least some older clang versions might not have the issue with the `VERSION` file, right?

**Pull request merged**
