### PR TITLE
linux-pam: add v1.5.1, v1.5.3, v1.6.0, v1.6.1 and additional variants

### LINKED ISSUE #40419: linux-pam missing build dependency rpc/rpc.h
We are trying to build with the new ubuntu:jammy and running into this issue:

image

It happens with linux-pam and you can see the full log here: https://github.com/converged-computing/flux-views/actions/runs/6464329605/job/17548802780

Also posted here for provenance when that goes away:

```console
#10 2373.6   Stage: 0.87s.  Autoreconf: 5.99s.  Configure: 15.63s.  Build: 44.05s.  Install: 0.61s.  Post-install: 0.06s.  Total: 1m 7.32s
#10 2373.6 [+] /opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/gmp-6.2.1-fgu56ebmxlcvwqldyv4tv6beb4yh2jbd
#10 2373.7 ==> Installing linux-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj [60/99]
#10 2373.7 ==> No binary for linux-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj found: installing from source
#10 2374.2 ==> Fetching https://mirror.spack.io/_source-cache/archive/e4/e4ec7131a91da44512574268f493c6d8ca105c87091691b8e9b56ca685d4f94d.tar.xz
#10 2374.2 ==> No patches needed for linux-pam
#10 2374.3 ==> linux-pam: Executing phase: 'autoreconf'
#10 2374.3 ==> linux-pam: Executing phase: 'configure'
#10 2385.1 ==> linux-pam: Executing phase: 'build'
#10 2401.7 ==> Error: ProcessError: Command exited with status 2:
#10 2401.7     'make' '-j2' 'V=1'
#10 2402.0 
#10 2402.0 5 errors found in build log:
#10 2402.0      925    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H
#10 2402.0              -I. -I../.. -I../../libpam/include -I../../libpamc/include -DCHKPW
#10 2402.0             D_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linux-
#10 2402.0             pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_chkpwd\" -DUPD
#10 2402.0             ATE_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linu
#10 2402.0             x-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_update\" -W 
#10 2402.0             -Wall -Wbad-function-cast -Wcast-align -Wcast-align=strict -Wcast-q
#10 2402.0             ual -Wdeprecated -Winline -Wmain -Wmissing-declarations -Wmissing-f
#10 2402.0             ormat-attribute -Wmissing-prototypes -Wpointer-arith -Wreturn-type 
#10 2402.0             -Wshadow -Wstrict-prototypes -Wuninitialized -Wwrite-strings -g -O2
#10 2402.0              -MT pam_unix_auth.lo -MD -MP -MF .deps/pam_unix_auth.Tpo -c pam_un
#10 2402.0             ix_auth.c  -fPIC -DPIC -o .libs/pam_unix_auth.o
#10 2402.0      926    mv -f .deps/pam_unix_acct.Tpo .deps/pam_unix_acct.Plo
#10 2402.0      927    /bin/bash ../../libtool  --tag=CC   --mode=compile /opt/spack/lib/s
#10 2402.0             pack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I../..    -I../../libpam/incl
#10 2402.0             ude -I../../libpamc/include -DCHKPWD_HELPER=\"/opt/software/linux-u
#10 2402.0             buntu22.04-x86_64/gcc-11.4.0/linux-pam-1.5.2-7hao7wthb4iysy6lliuiim
#10 2402.0             fbdg6tmpkj/sbin/unix_chkpwd\" -DUPDATE_HELPER=\"/opt/software/linux
#10 2402.0             -ubuntu22.04-x86_64/gcc-11.4.0/linux-pam-1.5.2-7hao7wthb4iysy6lliui
#10 2402.0             imfbdg6tmpkj/sbin/unix_update\" -W -Wall -Wbad-function-cast -Wcast
#10 2402.0             -align -Wcast-align=strict -Wcast-qual -Wdeprecated -Winline -Wmain
#10 2402.0              -Wmissing-declarations -Wmissing-format-attribute -Wmissing-protot
#10 2402.0             ypes -Wpointer-arith -Wreturn-type -Wshadow -Wstrict-prototypes -Wu
#10 2402.0             ninitialized -Wwrite-strings -g -O2 -MT pam_unix_passwd.lo -MD -MP 
#10 2402.0             -MF .deps/pam_unix_passwd.Tpo -c -o pam_unix_passwd.lo pam_unix_pas
#10 2402.0             swd.c
#10 2402.0      928    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H
#10 2402.0              -I. -I../.. -I../../libpam/include -I../../libpamc/include -DCHKPW
#10 2402.0             D_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linux-
#10 2402.0             pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_chkpwd\" -DUPD
#10 2402.0             ATE_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linu
#10 2402.0             x-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_update\" -W 
#10 2402.0             -Wall -Wbad-function-cast -Wcast-align -Wcast-align=strict -Wcast-q
#10 2402.0             ual -Wdeprecated -Winline -Wmain -Wmissing-declarations -Wmissing-f
#10 2402.0             ormat-attribute -Wmissing-prototypes -Wpointer-arith -Wreturn-type 
#10 2402.0             -Wshadow -Wstrict-prototypes -Wuninitialized -Wwrite-strings -g -O2
#10 2402.0              -MT pam_unix_passwd.lo -MD -MP -MF .deps/pam_unix_passwd.Tpo -c pa
#10 2402.0             m_unix_passwd.c  -fPIC -DPIC -o .libs/pam_unix_passwd.o
#10 2402.0      929    mv -f .deps/pam_unix_auth.Tpo .deps/pam_unix_auth.Plo
#10 2402.0      930    /bin/bash ../../libtool  --tag=CC   --mode=compile /opt/spack/lib/s
#10 2402.0             pack/env/gcc/gcc -DHAVE_CONFIG_H -I. -I../..    -I../../libpam/incl
#10 2402.0             ude -I../../libpamc/include -DCHKPWD_HELPER=\"/opt/software/linux-u
#10 2402.0             buntu22.04-x86_64/gcc-11.4.0/linux-pam-1.5.2-7hao7wthb4iysy6lliuiim
#10 2402.0             fbdg6tmpkj/sbin/unix_chkpwd\" -DUPDATE_HELPER=\"/opt/software/linux
#10 2402.0             -ubuntu22.04-x86_64/gcc-11.4.0/linux-pam-1.5.2-7hao7wthb4iysy6lliui
#10 2402.0             imfbdg6tmpkj/sbin/unix_update\" -W -Wall -Wbad-function-cast -Wcast
#10 2402.0             -align -Wcast-align=strict -Wcast-qual -Wdeprecated -Winline -Wmain
#10 2402.0              -Wmissing-declarations -Wmissing-format-attribute -Wmissing-protot
#10 2402.0             ypes -Wpointer-arith -Wreturn-type -Wshadow -Wstrict-prototypes -Wu
#10 2402.0             ninitialized -Wwrite-strings -g -O2 -MT pam_unix_sess.lo -MD -MP -M
#10 2402.0             F .deps/pam_unix_sess.Tpo -c -o pam_unix_sess.lo pam_unix_sess.c
#10 2402.0   >> 931    pam_unix_passwd.c:80:11: fatal error: rpc/rpc.h: No such file or di
#10 2402.0             rectory
#10 2402.0      932       80 | # include <rpc/rpc.h>
#10 2402.0      933          |           ^~~~~~~~~~~
#10 2402.0      934    compilation terminated.
#10 2402.0      935    libtool: compile:  /opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H
#10 2402.0              -I. -I../.. -I../../libpam/include -I../../libpamc/include -DCHKPW
#10 2402.0             D_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linux-
#10 2402.0             pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_chkpwd\" -DUPD
#10 2402.0             ATE_HELPER=\"/opt/software/linux-ubuntu22.04-x86_64/gcc-11.4.0/linu
#10 2402.0             x-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/sbin/unix_update\" -W 
#10 2402.0             -Wall -Wbad-function-cast -Wcast-align -Wcast-align=strict -Wcast-q
#10 2402.0             ual -Wdeprecated -Winline -Wmain -Wmissing-declarations -Wmissing-f
#10 2402.0             ormat-attribute -Wmissing-prototypes -Wpointer-arith -Wreturn-type 
#10 2402.0             -Wshadow -Wstrict-prototypes -Wuninitialized -Wwrite-strings -g -O2
#10 2402.0              -MT pam_unix_sess.lo -MD -MP -MF .deps/pam_unix_sess.Tpo -c pam_un
#10 2402.0             ix_sess.c  -fPIC -DPIC -o .libs/pam_unix_sess.o
#10 2402.0   >> 936    make[3]: *** [Makefile:879: pam_unix_passwd.lo] Error 1
#10 2402.0      937    make[3]: *** Waiting for unfinished jobs....
#10 2402.0      938    mv -f .deps/pam_unix_sess.Tpo .deps/pam_unix_sess.Plo
#10 2402.0      939    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-linux
#10 2402.0             -pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/spack-src/modules/pam_u
#10 2402.0             nix'
#10 2402.0   >> 940    make[2]: *** [Makefile:495: all-recursive] Error 1
#10 2402.0      941    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-linux
#10 2402.0             -pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/spack-src/modules'
#10 2402.0   >> 942    make[1]: *** [Makefile:496: all-recursive] Error 1
#10 2402.0      943    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-linux
#10 2402.0             -pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/spack-src'
#10 2402.0   >> 944    make: *** [Makefile:426: all] Error 2
#10 2402.0 
#10 2402.0 See build log for details:
#10 2402.0   /tmp/root/spack-stage/spack-stage-linux-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj/spack-build-out.txt
#10 2402.0 
#10 2402.0 ==> Warning: Skipping build of libpam-1.09-vkrf6x6qcrxliit27afjfiuezrl4gc4l since linux-pam-1.5.2-7hao7wthb4iysy6lliuiimfbdg6tmpkj failed
#10 2402.0 ==> Warning: Skipping build of flux-security-0.10.0-3rubbxdztabgjf2l6cggef4afzkwpfa4 since libpam-1.09-vkrf6x6qcrxliit27afjfiuezrl4gc4l failed
#10 2404.8 ==> Error: Terminating after first install failure: ProcessError: Command exited with status 2:
#10 2404.8     'make' '-j2' 'V=1'
#10 2404.8 ==> Updating view at /opt/views/view
#10 ERROR: process "docker-shell cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y" did not complete successfully: exit code: 1
```

This is for the version of spack on develop yesterday evening, and the ubuntu jammy base image at the same time.

### LINKED ISSUE #45353: Installation issue: libpam
### Steps to reproduce the issue

```console
$ spack spec -I libpam
Input spec
--------------------------------
 -   libpam

Concretized
--------------------------------
 -   libpam@1.09%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]      ^autoconf@2.72%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]          ^perl@5.38.2%gcc@13.2.1+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-alpine3-zen3
[+]              ^berkeley-db@18.1.40%gcc@13.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-alpine3-zen3
[+]              ^bzip2@1.0.8%gcc@13.2.1~debug~pic+shared build_system=generic arch=linux-alpine3-zen3
[+]              ^gdbm@1.23%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]                  ^readline@8.2%gcc@13.2.1 build_system=autotools patches=bbf97f1 arch=linux-alpine3-zen3
[+]                      ^ncurses@6.5%gcc@13.2.1~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-alpine3-zen3
[+]                          ^pkgconf@2.2.0%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]              ^zlib-ng@2.2.1%gcc@13.2.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-alpine3-zen3
[+]      ^automake@1.16.5%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]      ^gcc-runtime@13.2.1%gcc@13.2.1 build_system=generic arch=linux-alpine3-zen3
[+]      ^gmake@4.4.1%gcc@13.2.1~guile build_system=generic arch=linux-alpine3-zen3
[+]      ^libtool@2.4.7%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]          ^findutils@4.9.0%gcc@13.2.1 build_system=autotools patches=440b954 arch=linux-alpine3-zen3
[+]      ^linux-pam@1.6.1%gcc@13.2.1~lastlog~nls~openssl~regenerate-docu~selinux+unix~xauth build_system=autotools arch=linux-alpine3-zen3
[+]          ^libtirpc@1.3.3%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]              ^krb5@1.21.2%gcc@13.2.1+shared build_system=autotools arch=linux-alpine3-zen3
[+]                  ^bison@3.8.2%gcc@13.2.1~color build_system=autotools arch=linux-alpine3-zen3
[+]                  ^gettext@0.22.5%gcc@13.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-alpine3-zen3
[+]                      ^libxml2@2.10.3%gcc@13.2.1+pic~python+shared build_system=autotools arch=linux-alpine3-zen3
[+]                      ^tar@1.34%gcc@13.2.1 build_system=autotools zip=pigz arch=linux-alpine3-zen3
[+]                          ^pigz@2.8%gcc@13.2.1 build_system=makefile arch=linux-alpine3-zen3
[+]                          ^zstd@1.5.6%gcc@13.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-alpine3-zen3
[+]                      ^xz@5.4.6%gcc@13.2.1~pic build_system=autotools libs=shared,static arch=linux-alpine3-zen3
[+]                  ^openssl@3.3.1%gcc@13.2.1~docs+shared build_system=generic certs=mozilla arch=linux-alpine3-zen3
[+]                      ^ca-certificates-mozilla@2023-05-30%gcc@13.2.1 build_system=generic arch=linux-alpine3-zen3
[+]          ^libxcrypt@4.4.35%gcc@13.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-alpine3-zen3
[+]      ^m4@1.4.19%gcc@13.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-alpine3-zen3
[+]          ^diffutils@3.10%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[+]              ^libiconv@1.17%gcc@13.2.1 build_system=autotools libs=shared,static arch=linux-alpine3-zen3
[+]          ^libsigsegv@2.14%gcc@13.2.1 build_system=autotools arch=linux-alpine3-zen3
[e]      ^musl@1.2.5%gcc@13.2.1 build_system=makefile arch=linux-alpine3-zen3


```

### Error message

<details><summary>Error message</summary>

<pre>
=> Installing libpam-1.09-7kfs3oedxkm2qztynuefdwz2mnaf2d3v [36/37]
==> No binary for libpam-1.09-7kfs3oedxkm2qztynuefdwz2mnaf2d3v found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/ab/ab1d7983413dc2f11de2efa903e5c326af8cb9ea37765dacb39949417f7cd037.tar.gz
==> No patches needed for libpam
==> libpam: Executing phase: 'autoreconf'
==> Error: TypeError: 'NoneType' object is not callable

/opt/spack/var/spack/repos/builtin/packages/libpam/package.py:32, in autoreconf:
         30    def autoreconf(self, spec, prefix):
         31        bash = which("bash")
  >>     32        bash("./bootstrap.sh")

See build log for details:
  /tmp/root/spack-stage/spack-stage-libpam-1.09-7kfs3oedxkm2qztynuefdwz2mnaf2d3v/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (45e85532ac79ade76944b58ee09d32ccdf2a7718)
* **Python:** 3.12.3
* **Platform:** linux-alpine3-zen3
* **Concretizer:** clingo

### Additional information

It seems like libpam is missing a Bash dependency (or should be modified to not require bash)

[spack-build-env.txt](https://github.com/user-attachments/files/16327826/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/16327827/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by teaguesterling**
This revisits #44678 by adding some variants and new versions of `linux-pam`, specifically:
 - 4 New versions: v1.5.1, v1.5.3, v1.6.0, v1.6.1
 - An optional variant to re-enable `nls` (and thus add the dependency on `gettext` discussed in the original issue)
 - A couple of variants for the default modules (selinux, and unix)
 - An optional variant to compile with openssl support
 - An optional variant to compile with xauth support
 - An optional variant to compile with lastlog support
 - An optional variant to build the documentation (and all dependencies that incurs)
 
This shouldn't be merged until @vsoch is also able to confirm it doesn't break `flux-security` again.

### CODE REVIEW

**Comment by vsoch** [comment]
Did you try installing flux-security on the PR branch?

**Comment by teaguesterling** [comment]
I was able to build `flux-security` on my machine, but would prefer to also test it in a docker container. Do you happen to know which base image the flux CI process uses so I can make sure it's getting tested properly?

**Comment by vsoch** [comment]
@teaguesterling for our official Flux docker images, we don't use spack. For the builds that were failing (that led to the issue here), we build on the GitHub action running VM, and here is an example: https://github.com/sciworks/spack-updater/blob/main/build/action.yaml and then it grabs flux-security from here: https://github.com/flux-framework/spack/blob/main/packages/flux-security/package.py which should be in sync with upstream.

**Comment by teaguesterling** [comment]
> @teaguesterling for our official Flux docker images, we don't use spack. For the builds that were failing (that led to the issue here), we build on the GitHub action running VM, and here is an example: https://github.com/sciworks/spack-updater/blob/main/build/action.yaml and then it grabs flux-security from here: https://github.com/flux-framework/spack/blob/main/packages/flux-security/package.py which should be in sync with upstream.

Thanks! I'll test in this context as well.

**Comment by vsoch** [comment]
Thanks @teaguesterling I really appreciate it!

**Comment by teaguesterling** [comment]
@vsoch, I used the latest Alpine Linux  docker image and installed a minimal set of packages to get Spack to bootstrap and other packages to build successfully (see below). After testing this, I changed the `selinux` variant to off by default, as the appropriate headers were not present in Alpine by default. I filed  #45353 due to the undocumented bash dependency  for libpam (a different package).
```
# linux-headers was needed for `linux/mman.h` in `openssl`
# bsd-compat-headers was needed for `sys/queue.h` in `libtirpc`
# bash was needed for libpam
# python3-dev was needed for clingo in bootstrapping
# gpg was needed for npth-1.7
apk add gcc git python3 file gfortran autoconf automake make libtool g++ patch linux-headers python3-dev gpg bsd-compat-headers
git clone http://github.com/teaguesterling/spack /opt/spack
source /opt/spack/share/spack/setup-env.sh
spack cd -r
git checkout -t origin/packages/linux-pam_variants
spack bootstrap disable github-actions-v0.5  # this failed in alpine
spack bootstrap disable github-actions-v0.4  # this failed in alpine 
spack compiler find
spack install flux-security
```

**Comment by teaguesterling** [comment]
@spackbot rerun pipeline

**Review by bernhardkaindl — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256, rest LGTM.

**Pull request merged**
