### PR TITLE
suite-sparse: add versions 5.8.0 and 5.8.1

### PR DESCRIPTION
**Pull request by siko1056**
Update homepage URL and see release notes:
- https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v5.8.1
- https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v5.8.0

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by siko1056** [comment]
Thank you :+1:

**Comment by balay** [comment]
`gmp` dependency not set correctly?

```
In file included from ../Source/slip_ref_triangular_solve.c:70:
In file included from ../Source/slip_internal.h:106:
../Include/SLIP_LU.h:153:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
```
[spack-build-out.txt](https://github.com/spack/spack/files/5532409/spack-build-out.txt)

**Comment by adamjstewart** [comment]
Also see #19880

**Comment by adamjstewart** [comment]
Fixed by #19883

**Comment by siko1056** [comment]
Sorry for breaking the build and thank you for the quick fix :sweat:  GMP and MPFR were installed by the OS package manager on my system, thus I did not notice a problem.

**Pull request merged**
