### PR TITLE
mpich: add new releases

### PR DESCRIPTION
**Pull request by raffenet**
Add MPICH 3.4.3 and 4.0 releases.

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
There seem to be a legitimate error building `mpich` in the Gitlab pipeline.

**Comment by raffenet** [comment]
> There seem to be a legitimate error building `mpich` in the Gitlab pipeline.

Looks like configure script bug when building cuda support in yaksa. I’ve got a patch in main that I’ll cherry pick back to 4.0.x.

**Review by yfguo — APPROVED** [review]

**Comment by alalazo** [comment]
Feel free to ping me when this is ready.

**Review by yfguo — DISMISSED** [review]

**Comment by raffenet** [comment]
> > There seem to be a legitimate error building `mpich` in the Gitlab pipeline.
> 
> Looks like configure script bug when building cuda support in yaksa. I’ve got a patch in main that I’ll cherry pick back to 4.0.x.

This commit (https://github.com/pmodels/mpich/pull/5770/commits/abf7ae7766f5bd33438b9260500e6794bd3d80e7) should fix the specific build issue you were seeing. Is it possible to apply it in the Spack build for 4.0? I'm beginning to prepare 4.0.1, but it will probably take a week or two to finish up.

**Comment by alalazo** [comment]
No worries, if it is fine with you we can have this PR for just v3.4.3 and wait a week or two for v4.0.1

**Comment by hyviquel** [comment]
@raffenet I suppose this can be merged now that 4.0.1 is out :wink:

**Comment by raffenet** [comment]
> @raffenet I suppose this can be merged now that 4.0.1 is out 😉

I'll add a commit with 4.0.1 to the PR branch.

**Review by alalazo — DISMISSED** [review]

**Comment by hyviquel** [comment]
https://gitlab.spack.io/spack/spack/-/jobs/1847460/artifacts/file/jobs_scratch_dir/logs/spack-build-out.txt
```
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking for cudaStreamSynchronize in -lcudart... yes
checking whether nvcc works... no
configure: error: CUDA was not functional with provided host compiler (CC)
configure: error: YAKSA configure failed
```

Any idea of what can cause this error?

**Comment by raffenet** [comment]
> https://gitlab.spack.io/spack/spack/-/jobs/1847460/artifacts/file/jobs_scratch_dir/logs/spack-build-out.txt
> 
> ```
> checking cuda_runtime_api.h usability... yes
> checking cuda_runtime_api.h presence... yes
> checking for cuda_runtime_api.h... yes
> checking for cudaStreamSynchronize in -lcudart... yes
> checking whether nvcc works... no
> configure: error: CUDA was not functional with provided host compiler (CC)
> configure: error: YAKSA configure failed
> ```
> 
> Any idea of what can cause this error?

Is there any way to see the config.log file?

**Comment by hyviquel** [comment]
> Is there any way to see the config.log file?

I don't know, maybe @alalazo can help for this?

**Comment by raffenet** [comment]
> > Is there any way to see the config.log file?
> 
> I don't know, maybe @alalazo can help for this?

Or is there a container image I can download to replicate the build environment?

My best guess is that the CUDA runtime is discovered by the yaksa configure script, but there is no `nvcc` in the PATH that is needed to build the CUDA kernels. If that's the case, we should probably make it so the CUDA extensions are only built if both the CUDA runtime and compiler are found.

**Comment by alalazo** [comment]
> Or is there a container image I can download to replicate the build environment?

@raffenet It's a bit buried in the logs, so not super easy to see, but looking at the `mpich` failure reports the following:
```console
To reproduce this build locally, run:
    spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/1847460/artifacts [--working-dir <dir>]
If this project does not have public pipelines, you will need to first:
    export GITLAB_PRIVATE_TOKEN=<generated_token>
then follow the printed instructions.
```
With that you should be able to debug the failure. Let me know if you have issues.

**Comment by raffenet** [comment]
> > Or is there a container image I can download to replicate the build environment?
> 
> @raffenet It's a bit buried in the logs, so not super easy to see, but looking at the `mpich` failure reports the following:
> 
> ```
> To reproduce this build locally, run:
>     spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/1847460/artifacts [--working-dir <dir>]
> If this project does not have public pipelines, you will need to first:
>     export GITLAB_PRIVATE_TOKEN=<generated_token>
> then follow the printed instructions.
> ```
> 
> With that you should be able to debug the failure. Let me know if you have issues.

The install script gets stuck here. I don't know what's going on, since I can download the 4.0.1 tarball from the www.mpich.org location to the container just fine with wget.
```
==> [2022-03-14-17:22:20.701736] Checking existence of https://mirror.spack.io/mpich/mpich-4.0.1.tar.gz
==> [2022-03-14-17:22:20.999447] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/mpich/mpich-4.0.1.tar.gz
    Urllib fetch failed to verify url https://mirror.spack.io/mpich/mpich-4.0.1.tar.gz
==> [2022-03-14-17:22:21.000817] Checking existence of https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz
==> [2022-03-14-17:22:21.036795] FailedDownloadError: Failed to fetch file from URL: https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz
    Urllib fetch failed to verify url https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz
==> [2022-03-14-17:22:21.062423] SPIDER: [depth=0, max_depth=1, urls=3]
==> [2022-03-14-17:22:21.105403] HTTP Error 403: Forbidden
==> [2022-03-14-17:22:21.106157] SPIDER: [url=ParseResult(scheme='https', netloc='www.mpich.org', path='/static/downloads/3.0.4/', params='', query='', fragment=None)]
==> [2022-03-14-17:22:21.107907] HTTP Error 403: Forbidden
==> [2022-03-14-17:22:21.108343] SPIDER: [url=ParseResult(scheme='https', netloc='www.mpich.org', path='/static/downloads/3.0.4', params='', query='', fragment=None)]
==> [2022-03-14-17:22:21.130663] HTTP Error 403: Forbidden
==> [2022-03-14-17:22:21.130888] SPIDER: [url=ParseResult(scheme='https', netloc='www.mpich.org', path='/static/downloads/', params='', query='', fragment=None)]
==> [2022-03-14-17:22:21.131722] SPIDER: [depth=1, max_depth=1, urls=0]
==> [2022-03-14-17:22:21.164586] KeyError: Version('4.0.1')
==> [2022-03-14-17:22:21.164716] Cannot find version 4.0.1 in url_list
==> [2022-03-14-17:22:21.164794] Fetching from s3://spack-binaries-prs/shared_pr_mirror/_source-cache/archive/66/66a1fe8052734af2eb52f47808c4dfef4010ceac461cb93c42b99acfb1a43687.tar.gz failed.
==> [2022-03-14-17:22:21.165037] Fetching from s3://spack-binaries-prs/shared_pr_mirror/mpich/mpich-4.0.1.tar.gz failed.
==> [2022-03-14-17:22:21.165167] Fetching from s3://spack-binaries-prs/github/pr28573_new-mpich/_source-cache/archive/66/66a1fe8052734af2eb52f47808c4dfef4010ceac461cb93c42b99acfb1a43687.tar.gz failed.
==> [2022-03-14-17:22:21.165378] Fetching from s3://spack-binaries-prs/github/pr28573_new-mpich/mpich/mpich-4.0.1.tar.gz failed.
==> [2022-03-14-17:22:21.165596] Fetching from s3://spack-binaries-develop/e4s/_source-cache/archive/66/66a1fe8052734af2eb52f47808c4dfef4010ceac461cb93c42b99acfb1a43687.tar.gz failed.
==> [2022-03-14-17:22:21.165920] Fetching from s3://spack-binaries-develop/e4s/mpich/mpich-4.0.1.tar.gz failed.
==> [2022-03-14-17:22:21.166171] Fetching from https://mirror.spack.io/_source-cache/archive/66/66a1fe8052734af2eb52f47808c4dfef4010ceac461cb93c42b99acfb1a43687.tar.gz failed.
==> [2022-03-14-17:22:21.166532] Fetching from https://mirror.spack.io/mpich/mpich-4.0.1.tar.gz failed.
==> [2022-03-14-17:22:21.166672] Fetching from https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz failed.
==> [2022-03-14-17:22:21.196652] Error: FetchError: All fetchers failed for spack-stage-mpich-4.0.1-7jfb6j6ovlsyeonmpdnoeyzyqcyo3ccs
```

**Comment by alalazo** [comment]
@raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.

**Comment by raffenet** [comment]
> My best guess is that the CUDA runtime is discovered by the yaksa configure script, but there is no `nvcc` in the PATH that is needed to build the CUDA kernels. If that's the case, we should probably make it so the CUDA extensions are only built if both the CUDA runtime and compiler are found.

FWIW, I'm fairly certain that this is the issue. The Yaksa configure output looks to find libcudart.so, then error out when it fails to compile a test with `nvcc`. IMO, unless the user supplied `--with-cuda[=path/to/install]`, we should not treat this as an error. I have created pmodels/yaksa#215 to address this issue. Hopefully it can be included in a MPICH release soon.

Is there any way we can adjust the CI environment to workaround this issue for now? Either by making it so the CUDA runtime won't be discovered by configure, or making sure both the runtime and nvcc are both available?

**Comment by haampie** [comment]
It'd be easier if mpich wouldn't vendor dependencies with git submodules so we can simply add a small patch... Does your build system support external deps? Then we could do something along the lines of

```python
class Mpich(AutotoolsPackage):
    depends_on('yaksa@...', when='@...')
```

and add a patch to yaksa:

```python
class Yaksa(...):
    patch('https://github.com/pmodels/yaksa/pull/215.patch', when='@...', sha256=...)
```

**Comment by haampie** [comment]
And for next time it may be worth submitting release candidates so we can act as a CI for mpich too?

**Comment by teojgo** [comment]
> @raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.

I get the same behavior with Python 3.8

**Comment by raffenet** [comment]
> It'd be easier if mpich wouldn't vendor dependencies with git submodules so we can simply add a small patch... Does your build system support external deps? Then we could do something along the lines of
> 
> ```python
> class Mpich(AutotoolsPackage):
>     depends_on('yaksa@...', when='@...')
> ```
> 
> and add a patch to yaksa:
> 
> ```python
> class Yaksa(...):
>     patch('https://github.com/pmodels/yaksa/pull/215.patch', when='@...', sha256=...)
> ```

We can submit a separate Yaksa package.

**Comment by raffenet** [comment]
> And for next time it may be worth submitting release candidates so we can act as a CI for mpich too?

Noted. We don't usually do RCs for bug-fix releases, but we're in a special case now I suppose. I'm planning to do a 4.0.2 ASAP to remedy this issue.

**Comment by raffenet** [comment]
BTW is there any standard way to pull in `nvcc` in Spack? Grepping thru the repo reveals a variety of ways different packages handle it.

**Comment by teojgo** [comment]
> > @raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.
> 
> I get the same behavior with Python 3.8

In fact it's rather trivial to reproduce:

```
from urllib.request import Request, urlopen
req = Request('https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz')
urlopen(req)
```
It will throw an HTTP 403 error

while adding a header to the `Request` object works fine.

**Comment by raffenet** [comment]
> > > @raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.
> > 
> > 
> > I get the same behavior with Python 3.8
> 
> In fact it's rather trivial to reproduce:
> 
> ```
> from urllib.request import Request, urlopen
> req = Request('https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz')
> urlopen(req)
> ```
> 
> It will throw an HTTP 403 error
> 
> while adding a header to the `Request` object works fine.

Do you want to submit a bug report or should I? Having a working CI container image would help a lot.

**Comment by teojgo** [comment]
> > > > @raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.
> > > 
> > > 
> > > I get the same behavior with Python 3.8
> > 
> > 
> > In fact it's rather trivial to reproduce:
> > ```
> > from urllib.request import Request, urlopen
> > req = Request('https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz')
> > urlopen(req)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will throw an HTTP 403 error
> > while adding a header to the `Request` object works fine.
> 
> Do you want to submit a bug report or should I? Having a working CI container image would help a lot.

Please do, if this can be fixed on the mpich side it would be great.

**Comment by raffenet** [comment]
> > > > > @raffenet I verified and get the same result as yours. I need to double check if this is due to using `urllib` with Python 3.6 to fetch the tarball.
> > > > 
> > > > 
> > > > I get the same behavior with Python 3.8
> > > 
> > > 
> > > In fact it's rather trivial to reproduce:
> > > ```
> > > from urllib.request import Request, urlopen
> > > req = Request('https://www.mpich.org/static/downloads/4.0.1/mpich-4.0.1.tar.gz')
> > > urlopen(req)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It will throw an HTTP 403 error
> > > while adding a header to the `Request` object works fine.
> > 
> > 
> > Do you want to submit a bug report or should I? Having a working CI container image would help a lot.
> 
> Please do, if this can be fixed on the mpich side it would be great.

Oh, I guess it's the User-Agent filtering on our server? I don't have control over that, but we did start hosting new tarballs on our Github page, as well. It looks like if use that location it should work OK. I'll add a patch to this branch.

**Comment by teojgo** [comment]
Would it be possible to add also the nvidia hpc sdk patch for 3.4.3?

**Review by haampie — DISMISSED** [review]

**Review by haampie — APPROVED** [review]
I've reverted the `deprecated=True` commit, since _possibly_ people are stuck on old versions, and Spack is a bit annoying to use with deprecated versions (for example: mark mpich@3.3.2 as externally installed, and Spack stops picking it up).

It's not a rule, but usually `deprecated=True` is only added when there's a known security issue.

BTW: should `--with[out]-cuda` be mapped to a variant in a future PR?

**Comment by raffenet** [comment]
> I've reverted the `deprecated=True` commit, since _possibly_ people are stuck on old versions, and Spack is a bit annoying to use with deprecated versions (for example: mark mpich@3.3.2 as externally installed, and Spack stops picking it up).
> 
> It's not a rule, but usually `deprecated=True` is only added when there's a known security issue.

That's odd. I was just following the documentation. We are not supporting these versions any longer and I would really like to discourage anyone from installing them.

> 
> BTW: should `--with[out]-cuda` be mapped to a variant in a future PR?

Yes, I'll submit it today.

**Comment by haampie** [comment]
> That's odd. I was just following the documentation. We are not supporting these versions any longer and I would really like to discourage anyone from installing them.

I tend to agree, but it's making life a bit more difficult for people using for instance ubuntu 20.04 docker images in CI, relying on `apt install libmpich-dev` (which defaults to version 3.3.2) + `spack external find mpich` to speed up setting up dependencies. Spack will try to avoid using the system version when it's deprecated, unless that version is explicitly asked for, and then it's hard to write a generic script since you have to know what system version is in what docker image.

**Comment by raffenet** [comment]
> Would it be possible to add also the nvidia hpc sdk patch for 3.4.3?

I'll have to go back and see how easy it is to apply those patches. Supporting NVHPC took patches to MPICH and one of its dependencies. I have submitted yaksa as a separate package so it can be upgraded without touching this recipe #29877, so that might get us most of the way there.

However, this PR is _months_ old now. I am happy to make additional changes, but I want to avoid continually updating this branch.

**Comment by haampie** [comment]
Honestly I think the libtool related patch is beyond MPICH, I've created an issue: https://github.com/spack/spack/issues/29899. As I understand it, MPICH patches its own build tool, which seems like a hack you can't expect every autotools package to do...

**Comment by hyviquel** [comment]
@raffenet Disabling cuda on all MPICH installation seems a bit extreme to me.  

> BTW: should `--with[out]-cuda` be mapped to a variant in a future PR?

Does the CI usually test every possible variants? If not, one way to fix the current issue (until we get the next mpich release) would be to create a variant that is disable by default.

I can make a PR if that would work.

**Comment by raffenet** [comment]
> @raffenet Disabling cuda on all MPICH installation seems a bit extreme to me.
> 
> > BTW: should `--with[out]-cuda` be mapped to a variant in a future PR?
> 
> Does the CI usually test every possible variants? If not, one way to fix the current issue (until we get the next mpich release) would be to create a variant that is disable by default.
> 
> I can make a PR if that would work.

I just submitted #29901.

**Pull request merged**
