### PR TITLE
py-onnx: use out of source tree build for CMake part

### PR DESCRIPTION
**Pull request by wdconinc**
I spent the last two months, off and on, banging my head against the wall with strange behavior in my `spack develop` builds of `py-onnx`: references to non-existent environments, mysterious old dependency versions that appear out of nothing.

Ultimately it seems the same develop build was simply always reusing the same `.setuptools-cmake-build` build directory, hardcoded under the source tree path, and never refreshed with `cmake --fresh`...

This PR adds an out-of-source build for the CMake part of the `py-onnx` build. The `spack-build-{self.spec.dag_hash(7)}` pattern for the build directory comes from the CMakePackage definition.

With this:
```console
==> Installing py-onnx-1.16.1-bwcsm4kqtwg7l6ailmwkmwurgpgq7abw [38/38]
==> No binary for py-onnx-1.16.1-bwcsm4kqtwg7l6ailmwkmwurgpgq7abw found: installing from source
==> Ran patch() for py-onnx
==> py-onnx: Executing phase: 'install'
==> Warning: Module file /home/wdconinc/git/spack/share/spack/lmod/linux-ubuntu24.04-x86_64/Core/py-onnx/1.16.1-bwcsm4k.lua exists and will not be overwritten
==> py-onnx: Successfully installed py-onnx-1.16.1-bwcsm4kqtwg7l6ailmwkmwurgpgq7abw
  Stage: 0.00s.  Install: 16.30s.  Post-install: 1.70s.  Total: 18.14s
[+] /opt/software/linux-ubuntu24.04-skylake/gcc-13.2.0/py-onnx-1.16.1-bwcsm4kqtwg7l6ailmwkmwurgpgq7abw
```
and only `onnx.egg-info` ends up in source tree, with everything else in the (linked) stage directory:
```console
20:41:07 wdconinc@menelaos ~/git/onnx ((tags/v1.16.1) *$%) $ ls -atlr | tail -n 5
drwxrwxr-x   8 wdconinc wdconinc    4096 Jul 16 20:29 .git
-rwxrwxr-x   1 wdconinc wdconinc       0 Jul 16 20:29 .spack_patched
-rw-rw-r--   1 wdconinc wdconinc   11866 Jul 16 20:29 setup.py
drwxrwxr-x  18 wdconinc wdconinc    4096 Jul 16 20:29 .
drwxrwxr-x   2 wdconinc wdconinc    4096 Jul 16 20:29 onnx.egg-info
20:41:12 wdconinc@menelaos ~/git/onnx ((tags/v1.16.1) *$%) $ ls build-linux-ubuntu24.04-skylake-bwcsm4k
spack-build-01-install-out.txt  spack-build-bwcsm4k  spack-build-env-mods.txt  spack-build-env.txt  spack-build-out.txt
```

With this change, the same develop source instance can be used for builds without having cached variables causing unpredictable effects.

### CODE REVIEW

**Comment by wdconinc** [comment]
@spackbot fix style

**Comment by wdconinc** [comment]
FYI, the hardcoded `.setuptools-cmake-build` directory under the source path was [introduced](https://github.com/onnx/onnx/commit/2af45df08182f26c2279c8177e3f736fc66e77ae) in v1.2.1.

**Comment by adamjstewart** [comment]
I'm not maintaining this package, I'll let someone else review.

**Review by bernhardkaindl — DISMISSED** [review]
Built on Ubuntu 22.04

**Comment by bernhardkaindl** [comment]
@spackbot fix style

**Review by bernhardkaindl — APPROVED** [review]
Built on Ubuntu 22.04

**Pull request merged**
