### PR TITLE
py-sip: fix for missing flex/bison

### PR DESCRIPTION
**Pull request by robert-mijakovic**
Flex/Bison are necessary independently of the develop branch.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@Sinan81 do you want to review?

**Comment by Sinan81** [comment]
> Flex/Bison are necessary independently of the develop branch.

@robert-mijakovic Thanks for this PR. Could you please point to a reference regarding why flex/bison is not just a dependency for `development` variant or provide a bit more explanation.

**Comment by robert-mijakovic** [comment]
> > Flex/Bison are necessary independently of the develop branch.
> 
> @robert-mijakovic Thanks for this PR. Could you please point to a reference regarding why flex/bison is not just a dependency for `development` variant or provide a bit more explanation.

I tried to install the latest release of py-sip on freshly installed CentOS using spack and I got an error saying that it couldn't find flex/bison. I  removed the when='@develop' and the installation worked flawesly. I haven't searched for an online reference but could try to install it and upload the build log if you want to check it.

**Comment by Sinan81** [comment]
> > > Flex/Bison are necessary independently of the develop branch.
> > 
> > 
> > @robert-mijakovic Thanks for this PR. Could you please point to a reference regarding why flex/bison is not just a dependency for `development` variant or provide a bit more explanation.
> 
> I tried to install the latest release of py-sip on freshly installed CentOS using spack and I got an error saying that it couldn't find flex/bison. I removed the when='@develop' and the installation worked flawesly. I haven't searched for an online reference but could try to install it and upload the build log if you want to check it.

I am also using centos too. Let me reproduce the build error by making sure flex/bison is not installed within the system.

**Comment by Sinan81** [comment]
I can reproduce the build error. It seems `flex/bison` is necessary for building `py-sip`.

**Comment by Sinan81** [comment]
PR can be merged as is. Thanks @robert-mijakovic  for reporting this.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
