### PR TITLE
refactoring : removed explicits `os.fork()`, exceptions are propagated from child process to parent

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications
- [x] removed explicit `os.fork()` in favor of `multiprocessing.Process`
- [x] `log_output` logic has been modified and does not require calls to `sys.settrace` anymore
- [x] we can throw from `Package.do_install.build_process` and the exceptions are propagated to parent process

##### Changes in `log_ouput`
In `develop` : 
- on `__enter__` the parent process forks , set his frame explicitly to avoid executing twice the same code (quite fragile to re-positioning of the `with` statement) ,  reads from a pipe and writes to file
- on `__enter__` the child does the necessary to write to a pipe and then returns for execution

In the PR:
- a "daemonic" child is spawned in the `acquire` method and is set to read from the pipe
- the context manager just changes where the parent writes when needed
- everything is cleaned in the `release` method

##### Notes
In #1186 I wanted to be able to forward exceptions to parent to have a neater workflow in `do_install`. As I saw a couple of `TODOs` referring to the same issue, I extracted this PR. This has also the great advantage of not tweaking with `sys.settrace` and frames (which is a major pain for the debugger sometimes).

### CODE REVIEW

**Comment by alalazo** [comment]
Ready to be reviewed and tested

**Comment by tgamblin** [comment]
@alalazo: this is awesome!  I haven't had a chance to look at it in detail but will.  This also removes one of the obstacles to getting Spack working on Windows.

@goxberry Does this work for you on Windows?

**Comment by alalazo** [comment]
@tgamblin I would really like this to be merged, but to be fair I have to tell you that in #1186 [spurious fails](https://travis-ci.org/LLNL/spack/jobs/144400821)  in `test/install.py` appeared possibly due to this change-set. I was not able to reproduce them outside `Travis` and I have the impression that the tests themselves may be flawed somehow, but it is worth a double check before merging.

**Comment by alalazo** [comment]
@tgamblin I got the point failing spuriously here : I'll write a fix a ping you when done.

**Comment by alalazo** [comment]
@tgamblin Done : now it should be 99,9% safe :smile:

**Comment by alalazo** [comment]
@tgamblin I pushed [some cosmetic changes](https://github.com/LLNL/spack/pull/1186/commits/1ecea4c2f12f3f70bcfcdc46dc01acbf6d285f09) to this in #1186 , let me know if you want them ported here

**Comment by tgamblin** [comment]
@goxberry: I looked into this.  There are a couple more things that probably need to happen:

1. Set `use_tmp_stage` to `False` in `__init__.py`.
1. In `lib/spack/env`, there is really only one file with code in it: `cc`.  The other files in `lib/spack/env` and its subdirectories are symlinks to that.  You probably need to overwrite every file that is *not* cc with the contents of `cc`.  Apparently by default if you clone on windows, a symlink comes down as a file with the path to its target in it, which is not really what we want.  Not sure how best to get around that right now, but this could be a potential workaround.

**Comment by alalazo** [comment]
Closing as it will be difficult to maintain this alongside #1186

**Comment by tgamblin** [comment]
If it were merged would it be easy or is it a fundamental incompatibility?

**Comment by alalazo** [comment]
@tgamblin No fundamental incompatibility : all the features here are also in #1186 except that maintaining both will create conflicts (due to synchronization with `develop`) that needs to be managed. 

In the end I think it will be easier to re-create something like #1228 if you need just that rather than continue with this PR.

**Comment by tgamblin** [comment]
@alalazo: ok -- sounds good.  Sorry for being slow!

**Comment by alalazo** [comment]
@tgamblin No worries. I closed it as leaving as it was was just adding noise to the list of PRs

**Pull request closed without merging**
