### PR TITLE
Update uqfoundation/{dill,multiprocess,pathos,pox,ppft}

### PR DESCRIPTION
**Pull request by schmitts**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you submit a separate PR for each package? That would make it much easier for me to review.

**Comment by schmitts** [comment]
> Can you submit a separate PR for each package? That would make it much easier for me to review.

How would that look in detail? The updates depend on each other.

**Comment by adamjstewart** [comment]
You could add a "depends on #pr" comment to each PR. Then I won't merge a PR unless its dependencies are merged first. If that's too much work, I can just review this PR since they're all interdependent.

**Comment by schmitts** [comment]
> You could add a "depends on #pr" comment to each PR. Then I won't merge a PR unless its dependencies are merged first. If that's too much work, I can just review this PR since they're all interdependent.

Will do!

**Pull request closed without merging**
