### PR TITLE
qthreads: New version 1.16

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
0.16 still includes a configure script, why is autoreconf necessary?

**Comment by eschnett** [comment]
When I ran `configure`, it complained about `aclocal-1.13` not being found. I added `automake` as build dependency, but this didn't help. Google sounded as if running `autoreconf` would help, and indeed it did. The package comes with a respective `autogen.sh` script.

Do you think I should report this upstream instead?

**Comment by adamjstewart** [comment]
I would definitely report that upstream. We can still merge in the meantime while waiting for a response if you want.

**Comment by eschnett** [comment]
Let's wait. Last time the qthreads developers updated the tarball in place, which would break the Spack recipe.

**Comment by eschnett** [comment]
Reported as https://github.com/Qthreads/qthreads/issues/79 .

**Comment by eschnett** [comment]
Resolved. This version is now ready to be applied.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
