### PR TITLE
Add --with-mpi=spec['mpi'].name at configure step to avoid error when…

### PR DESCRIPTION
**Pull request by XL64**
… finding 2 MPI implementations

### CODE REVIEW

**Comment by pramodskumbhar** [comment]
@XL64 : we need some extra checks/updates to properly compile with scorep with multiple compilers and mpi implementations. I didn't get time to finalize my changes but you can have look at [here](https://github.com/pramodskumbhar/spack/blob/bbprh69/var/spack/repos/builtin/packages/scorep/package.py). We typically need something like below:

```
        if spec.satisfies('%gcc'):
            config_args.append('--with-nocross-compiler-suite=gcc')
        elif spec.satisfies('%intel'):
            config_args.append('--with-nocross-compiler-suite=intel')
        elif spec.satisfies('%pgi'):
        ......

        if spec.satisfies('^intel-mpi'):
            config_args.append('--with-mpi=intel3')
        elif spec.satisfies('^mpich') or spec.satisfies('^mvapich2'):
            config_args.append('--with-mpi=mpich3')
        elif spec.satisfies('^openmpi'):
        ......
```
and some additional changes are needed for cross-compiling build. I will try to update this later.

**Comment by becker33** [comment]
@pramodskumbhar Do you want to update here or in a separate PR? Deciding whether to merge this.

Also, for 
```
if spec.satisfies('%gcc'):
            config_args.append('--with-nocross-compiler-suite=gcc')
        elif spec.satisfies('%intel'):
            config_args.append('--with-nocross-compiler-suite=intel')
        elif spec.satisfies('%pgi'):
        ......
```
you should be able to replace that with
`config_args.append('--with-nocross-compiler-suite={0}'.format(spec.compiler.name))`

**Comment by pramodskumbhar** [comment]
@becker33 : done (#5386)

**Comment by XL64** [comment]
@pramodskumbhar Thanks your solution is far more portable. I close this PR.

**Pull request closed without merging**
