### PR TITLE
Create Spack packaging cheatsheet

### PR DESCRIPTION
**Pull request by iarspider**
As promised: https://github.com/spack/spack/pull/33971#issuecomment-1319634148

This is my personal cheatsheet that I have built over the last few years while working on Spack - basically the things I always have to `grep` for.

Pinging also @adamjstewart @haampie @tgamblin @alalazo - feel free to add your own cheats to this sheet or correct outdated/invalid cheats

### CODE REVIEW

**Comment by adamjstewart** [comment]
This cheatsheet feels a bit too random and hyper-specific. If we added all possible "things someone might need to do" at this level of specificity, we would eventually reach the Packaging Guide.

**Comment by iarspider** [comment]
@adamjstewart it is a cheatsheet, it's not a guide/manual, so it is hyper-specific by design, I'd say. And randomnes... Well, if I needed to look something up more than three times, that information was added to the cheatsheet. So yes, it is kind of random.

**Comment by bernhardkaindl** [comment]
Thanks, basically I was interested in the new multiple-build systems feature:

I see https://spack.readthedocs.io/en/latest/build_systems.html does not have a section on it.

@alalazo sent these links in response to me and iarspider not being able to find the documentation on it:
- https://spack.readthedocs.io/en/latest/packaging_guide.html#multiple-build-systems
  This looks like randomly sprinkled in there, this should be moved to a common place (below the build systems link above)
- https://spack.readthedocs.io/en/latest/packaging_guide.html#package-class-architecture
  likewise, it has nothing to do with the `spack location` commands above it.
- https://spack-tutorial.readthedocs.io/en/latest/tutorial_packaging.html#multiple-build-systems
  and again, no releation to querying information about a package.

They should be moved and merged below the build_systems documentation link above so people can find it and have one place where they can find out everything about it.

I am sorry that this feedback does not sound positive, but I hope that we can agree to improve it.

What I see also missing is that `build_system=cmake` can be selected on the `spack install` command line to select the build system to use from the command line.

@adamjstewart, would you agree?

**Comment by adamjstewart** [comment]
Yes, multi-build system stuff is brand new so docs are not yet amazing. I would also personally put it under the Build Systems docs, but I'm biased because I wrote those. This is where the docs used to be in the last release: https://spack.readthedocs.io/en/v0.18.1/build_systems/multiplepackage.html

I'm very open to improving the docs on multi-build systems. I'm less open to hosting personal cheat sheets for packaging. The reason the packaging docs are so long is because there's a million things someone might want to do.

**Comment by bernhardkaindl** [comment]
> Yes, multi-build system stuff is brand new so docs are not yet amazing. I would also personally put it under the Build Systems docs, but I'm biased because I wrote those. This is where the docs used to be in the last release: https://spack.readthedocs.io/en/v0.18.1/build_systems/multiplepackage.html
> 
> I'm very open to improving the docs on multi-build systems. I'm less open to hosting personal cheat sheets for packaging. The reason the packaging docs are so long is because there's a million things someone might want to do.

@alalazo, Adam: Thank you, what we have now is already a big improvement and quite amazing in comparison! I'm also not open to lots of cheat sheets, and well said on the million of things someone might want to do.

I really like the current state of the docs on the multiple build_systems docs, it deserves it's own page with one example like https://github.com/spack/spack/pull/33971/files which I think can be minimized to give a good complete example to make it truly amazing!

**Pull request closed without merging**
