### PR TITLE
vtk-m: bump vtk-m 2.1.0

### PR DESCRIPTION
**Pull request by vicentebolea**
🎉 🎉 🎉

Finally! VTK-m v2.1.0 final release is out.

This bring exiting new features and bugfixes. Find the release notes at https://gitlab.kitware.com/vtk/vtk-m/-/blob/master/docs/changelog/2.1/release-notes.md

Let me know if we need to change anything else in the package

ViB

🎉 🎉 🎉

### CODE REVIEW

**Comment by vicentebolea** [comment]
@spackbot fix style

**Review by kmorel — APPROVED** [review]
Looks good to me.

**Comment by eugeneswalker** [comment]
CI failing here:

1. [ vtk-m@2.1.0 /y6ooafr %gcc@11.4.0 arch=linux-ubuntu20.04-x86_64_v3 E4S ](https://gitlab.spack.io/spack/spack/-/jobs/9310072)
```
...
  >> 147    /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcx
            mz5enjmmsbe/spack-src/vtkm/cont/kokkos/internal/DeviceAdapterAlgori
            thmKokkos.h:47:10: fatal error: 'thrust/device_ptr.h' file not foun
            d
     148    #include <thrust/device_ptr.h>
     149             ^~~~~~~~~~~~~~~~~~~~~
     150    1 error generated when compiling for gfx908.
  >> 151    make[2]: *** [vtkm/cont/CMakeFiles/vtkm_cont.dir/build.make:232: vt
            km/cont/CMakeFiles/vtkm_cont.dir/CellLocatorUniformBins.cxx.o] Erro
            r 1
     152    make[2]: *** Waiting for unfinished jobs....
     153    [  6%] Building CXX object vtkm/cont/CMakeFiles/vtkm_cont.dir/CellS
            et.cxx.o
     154    cd /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifc
            rcxmz5enjmmsbe/spack-build-y6ooafr/vtkm/cont && /builds/spack/spack
            /lib/spack/env/gcc/g++ -DVTKMDIY_MPI_AS_LIB -DVTKMDIY_NO_THREADS -D
            vtkm_cont_EXPORTS -I/tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y
            6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-src/vtkm/thirdparty/optionpar
            ser -I/tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kew
            ifcrcxmz5enjmmsbe/spack-src/vtkm/thirdparty/diy -I/tmp/root/spack-s
            tage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack
            -src/vtkm/thirdparty/lcl/vtkmlcl -I/tmp/root/spack-stage/spack-stag
            e-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-src -I/tmp/roo
            t/spack-stage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmm
            sbe/spack-build-y6ooafr/include -isystem /tmp/root/spack-stage/spac
            k-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-src/vtkm
            /thirdparty/diy/vtkmdiy/include -isystem /tmp/root/spack-stage/spac
            k-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-build-y6
            ooafr/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi -isystem /hom
            e/software/spack/__spack_path_placeholder__/__spack_path_placeholde
            r__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
            ath_placeholder__/__spack_path_placeholder__/__spack_path_placehold
            er__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.
            04-x86_64_v3/gcc-11.4.0/kokkos-3.7.01-3is7m42nmmptmyp5onrxq2lkzjnqw
            jb3/include -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -Wall
             -Wcast-align -Wextra -Wpointer-arith -Wformat -Wformat-security -W
            shadow -Wunused -fno-common -Wno-unused-function -Wchar-subscripts 
            -Wfloat-conversion -Wodr -ffunction-sections -pthread -MD -MT vtkm/
            cont/CMakeFiles/vtkm_cont.dir/CellSet.cxx.o -MF CMakeFiles/vtkm_con
            t.dir/CellSet.cxx.o.d -o CMakeFiles/vtkm_cont.dir/CellSet.cxx.o -c 
            /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y6ooafrkb6f4kewifcrcx
            mz5enjmmsbe/spack-src/vtkm/cont/CellSet.cxx
     155    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-m
            -2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-build-y6ooafr'
  >> 156    make[1]: *** [CMakeFiles/Makefile2:2820: vtkm/cont/CMakeFiles/vtkm_
            cont.dir/all] Error 2
     157    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-m
            -2.1.0-y6ooafrkb6f4kewifcrcxmz5enjmmsbe/spack-build-y6ooafr'
  >> 158    make: *** [Makefile:159: all] Error 2
```

2. [ vtk-m@2.1.0 /ybtwkbe %gcc@11.4.0 arch=linux-ubuntu20.04-x86_64_v3 E4S ](https://gitlab.spack.io/spack/spack/-/jobs/9310073)
```
...
  >> 147    /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc
            6jozvbnrfda/spack-src/vtkm/cont/kokkos/internal/DeviceAdapterAlgori
            thmKokkos.h:47:10: fatal error: 'thrust/device_ptr.h' file not foun
            d
     148    #include <thrust/device_ptr.h>
     149             ^~~~~~~~~~~~~~~~~~~~~
     150    1 error generated when compiling for gfx90a.
  >> 151    make[2]: *** [vtkm/cont/CMakeFiles/vtkm_cont.dir/build.make:232: vt
            km/cont/CMakeFiles/vtkm_cont.dir/CellLocatorUniformBins.cxx.o] Erro
            r 1
     152    make[2]: *** Waiting for unfinished jobs....
     153    [  6%] Building CXX object vtkm/cont/CMakeFiles/vtkm_cont.dir/CellS
            et.cxx.o
     154    cd /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4b
            vuc6jozvbnrfda/spack-build-ybtwkbe/vtkm/cont && /builds/spack/spack
            /lib/spack/env/gcc/g++ -DVTKMDIY_MPI_AS_LIB -DVTKMDIY_NO_THREADS -D
            vtkm_cont_EXPORTS -I/tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-y
            btwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-src/vtkm/thirdparty/optionpar
            ser -I/tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ff
            r4bvuc6jozvbnrfda/spack-src/vtkm/thirdparty/diy -I/tmp/root/spack-s
            tage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack
            -src/vtkm/thirdparty/lcl/vtkmlcl -I/tmp/root/spack-stage/spack-stag
            e-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-src -I/tmp/roo
            t/spack-stage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnr
            fda/spack-build-ybtwkbe/include -isystem /tmp/root/spack-stage/spac
            k-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-src/vtkm
            /thirdparty/diy/vtkmdiy/include -isystem /tmp/root/spack-stage/spac
            k-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-build-yb
            twkbe/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi -isystem /hom
            e/software/spack/__spack_path_placeholder__/__spack_path_placeholde
            r__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
            ath_placeholder__/__spack_path_placeholder__/__spack_path_placehold
            er__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.
            04-x86_64_v3/gcc-11.4.0/kokkos-3.7.01-zuovofah5eeosjceg6e7ktvc457fk
            z72/include -O3 -DNDEBUG -std=c++17 -fPIC -fvisibility=hidden -Wall
             -Wcast-align -Wextra -Wpointer-arith -Wformat -Wformat-security -W
            shadow -Wunused -fno-common -Wno-unused-function -Wchar-subscripts 
            -Wfloat-conversion -Wodr -ffunction-sections -pthread -MD -MT vtkm/
            cont/CMakeFiles/vtkm_cont.dir/CellSet.cxx.o -MF CMakeFiles/vtkm_con
            t.dir/CellSet.cxx.o.d -o CMakeFiles/vtkm_cont.dir/CellSet.cxx.o -c 
            /tmp/root/spack-stage/spack-stage-vtk-m-2.1.0-ybtwkbeqyjwg4ffr4bvuc
            6jozvbnrfda/spack-src/vtkm/cont/CellSet.cxx
     155    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-m
            -2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-build-ybtwkbe'
  >> 156    make[1]: *** [CMakeFiles/Makefile2:2820: vtkm/cont/CMakeFiles/vtkm_
            cont.dir/all] Error 2
     157    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-m
            -2.1.0-ybtwkbeqyjwg4ffr4bvuc6jozvbnrfda/spack-build-ybtwkbe'
  >> 158    make: *** [Makefile:159: all] Error 2
```

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256, rest LGTM.

**Comment by vicentebolea** [comment]
Gitlab CI error is fixed and we have already merged in upstream the fix.

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Should we wait for more review or proceed w merge now?

**Comment by vicentebolea** [comment]
It is ready to merge from my side

**Pull request merged**
