### PR TITLE
Add Caliper 2.9.1 release and sha256

### PR DESCRIPTION
**Pull request by tepperly**
Add latest Caliper release version and its sha256.

### CODE REVIEW

**Review by eugeneswalker — APPROVED** [review]
Verified checksum. Thanks!

**Review by eugeneswalker — DISMISSED** [review]

**Review by daboehme — DISMISSED** [review]

**Review by alalazo — DISMISSED** [review]
The pipeline failure seems legit: https://gitlab.spack.io/spack/spack/-/jobs/7012691

**Comment by eugeneswalker** [comment]
> The pipeline failure seems legit: https://gitlab.spack.io/spack/spack/-/jobs/7012691

```
  >> 427    /tmp/root/spack-stage/spack-stage-caliper-2.9.1-vd3tv4iq7geqi5jfyuv
            nckiaokejv4ci/spack-src/src/services/sampler/Sampler.cpp:31:10: fat
            al error: 'libunwind.h' file not found
     428    #include <libunwind.h>
     429             ^~~~~~~~~~~~~
     430    1 error generated when compiling for gfx90a.
  >> 431    make[2]: *** [src/services/sampler/CMakeFiles/caliper-sampler.dir/b
            uild.make:79: src/services/sampler/CMakeFiles/caliper-sampler.dir/S
            ampler.cpp.o] Error 1
     432    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-calip
            er-2.9.1-vd3tv4iq7geqi5jfyuvnckiaokejv4ci/spack-build-vd3tv4i'
  >> 433    make[1]: *** [CMakeFiles/Makefile2:1349: src/services/sampler/CMake
            Files/caliper-sampler.dir/all] Error 2
```

Do we need an explicit dependency on `libunwind` for caliper?
EDIT: Sorry, I see the dependency is already explicit. Perhaps this patch needs to be extended to cover the new version?
* https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/caliper/package.py#L86
```
    patch("sampler-service-missing-libunwind-include-dir.patch", when="@2.9.0 +libunwind +sampler")
```

**Comment by daboehme** [comment]
> Perhaps this patch needs to be extended to cover the new version?

Yes that should fix it.

**Review by eugeneswalker — DISMISSED** [review]

**Review by daboehme — DISMISSED** [review]
Looks good to me! Not sure if there's a better way to say "all of 2.9.x". But there probably won't be a 2.9.2+

**Comment by eugeneswalker** [comment]
@spackbot fix style

**Comment by alecbcs** [comment]
@tepperly @daboehme it looks like v2.10.0 is now in develop. Would you all still like to add v2.9.1?

**Comment by tepperly** [comment]
> @tepperly @daboehme it looks like v2.10.0 is now in develop. Would you all still like to add v2.9.1?

It seems to take more than 3 months to get a PR merged, so might as well get this one done while waiting out the clock for a PR for v2.10.0.

**Comment by eugeneswalker** [comment]
> > @tepperly @daboehme it looks like v2.10.0 is now in develop. Would you all still like to add v2.9.1?
> 
> It seems to take more than 3 months to get a PR merged, so might as well get this one done while waiting out the clock for a PR for v2.10.0.

@tepperly please ping me for any PRs you are trying to get RE caliper. As an E4S package we want to make sure things *do not take 3 months* , especially PRs bringing in new versions.

**Comment by daboehme** [comment]
> @tepperly @daboehme it looks like v2.10.0 is now in develop. Would you all still like to add v2.9.1?

Yeah I don't know where this PR got stuck. Doesn't hurt to have v2.9.1 I guess, but it's not critical now that we have v2.10.

**Review by eugeneswalker — DISMISSED** [review]

**Comment by alalazo** [comment]
There is a conflict to be fixed to merge this one into `develop`

**Comment by alecbcs** [comment]
@tepperly went ahead and fixed the conflicts so that we can finally get this merged.

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
