### PR TITLE
Quote path so spaces in Python install path don't break invocation of command on Windows

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you clarify why this is needed? Also, `f"'{path}'"` would be simpler.

**Comment by johnwparent** [comment]
> Can you clarify why this is needed? Also, `f"'{path}'"` would be simpler.

If there is a space in the path to Python.exe, the `Exectuable` class' call method will break trying to execute `python.exe` as it will end up trying to execute something like `C:\\Program ` rather than `C:\\Program Files\\Python\\Python.exe`. This is a common issue on Windows, due to the systems inability to properly parse paths with spaces. In order to execute such paths, it is required to quote them with double quotes. Single quotes are not sufficient from what I understand.

Edit: formatting

**Comment by adamjstewart** [comment]
That sounds like something we should fix in `Executable` so it applies to all packages, not just Python.

**Comment by johnwparent** [comment]
> That sounds like something we should fix in `Executable` so it applies to all packages, not just Python.

I thought about that, however that would require either a hard change in the usage of the `Executable` class or some very tricky parsing.
The `Executable` class constructor: 
```
 # necesary here for the shlex call to succeed
 name = format_os_path(name, mode=Path.unix)
 self.exe = shlex.split(str(name))
 # filter back to platform dependent path
 self.exe = path_to_os_path(*self.exe)
```
Basically the way the `Executable` class is currently set up, while not particularly common, the constructor can take a string, which is either the path to, or name of, an executable, or that executable, and some arguments. This is evidenced by the usage in this manner in the Spack code base (more common in package.py files than Spack core) and by the content of the executable class itself, both by the call to `shlex.split` and by the fact that accessing the `command` attribute returns `self.exe[0]`, meaning the rest of `self.exe` is arguments other otherwise NOT the executable. 
If we want to disallow this behavior, the problem becomes trivial, and your suggestion to handle this from the `Executable` class is easily done. However, if we want to continue allowing it, the problem becomes a little trickier, as determining where the executable name starts and the arguments begin is not straightforward. For example `Executable("C:\\Program Files\\Python Install\\Python test.py")` would be a perfectly valid invocation, but shlex would parse it into `["C:/Program", "Files/Python", "Install/Python", "test.py"]`. Clearly this would be difficult to stitch back together programmatically in a way that is not very fragile. 

Edit: formatting, spelling

**Comment by adamjstewart** [comment]
I would personally be fine with requiring `Executable("C:\\Program Files\\Python Install\\Python test.py")` to be written as `Executable("C:\\Program Files\\Python Install\\Python", "test.py")`. I'm unsure how common the former is, can you give me any examples? Curious what @scheibelp thinks.

**Comment by scheibelp** [comment]
> I would personally be fine with requiring `Executable("C:\\Program Files\\Python Install\\Python test.py")` to be written as `Executable("C:\\Program Files\\Python Install\\Python", "test.py")`

I agree with that. I think the PR modifying `Executable` in this way should also modify the packages accordingly.

That being said, I don't think that needs to hold up this PR (unless @johnwparent you would prefer to do it that way without this as an intermediate step).

**Comment by johnwparent** [comment]
> > I would personally be fine with requiring `Executable("C:\\Program Files\\Python Install\\Python test.py")` to be written as `Executable("C:\\Program Files\\Python Install\\Python", "test.py")`
> 
> I agree with that. I think the PR modifying `Executable` in this way should also modify the packages accordingly.
> 
> That being said, I don't think that needs to hold up this PR (unless @johnwparent you would prefer to do it that way without this as an intermediate step).

Thank you both @scheibelp and @adamjstewart for your thoughts and review.

@adamjstewart It's almost non existent within Spack core, but it's semi-prevalent throughout the packages and tests, for example the package `oommf` and the util test.

Generally, I like to do things correctly once, but this one is a blocker for Windows Gitlab CI running on develop. That said the Windows docker images are also currently fighting with us a bit and I think I could probably have the larger refactor done before Windows CI is ready for a real test, and this smaller change in present on the Windows CI feature branch anyway. 
Let's close this in favor of a larger refactor and worst case we just reopen if the CI demand forces us to.

**Pull request closed without merging**
