### PR TITLE
Enable oneapi CMake preset for lammps if building with oneapi compiler

### PR DESCRIPTION
**Pull request by Andrey1994**
Changes in this PR:

* Enable oneapi CMake preset for lammps if building with oneapi compiler

### CODE REVIEW

**Comment by rbberger** [comment]
@Andrey1994 does the preset actually improve anything when building inside of Spack? Also, how does this relate to #29?

**Comment by Andrey1994** [comment]
Yes, it sets correct flags for oneapi compiler and it leads to better performance

**Comment by rbberger** [comment]
@Andrey1994 Spack already sets `icx` and such as compilers when using `%oneapi`. OpenMP is enabled properly via CMake. And `-qopenmp-simd` is enabled by default with `-O2` and higher. So, again, what specifically does the preset change that supposetly makes a difference? (we created the LAMMPS presets for local development, but I fail to see the value in the Spack case). Please correct me if I'm missing something.

**Comment by Andrey1994** [comment]
This preset is a recommended option at docs for lammps https://docs.lammps.org/Build_basics.html#choice-of-compiler-and-compile-link-options and this way any further optimizations(in terms of compilation flags) for oneapi compiler will be propagated into spack automatically. 

And I am not sure that **all** of these options and variables https://github.com/lammps/lammps/blob/develop/cmake/presets/oneapi.cmake are enabled in spack as is if you write smth like `spack install lammps%oneapi`

**Comment by rbberger** [comment]
@Andrey1994 Sorry, but I will not approve this.

I introduced "presets" to the LAMMPS CMake build. So I'm well aware of their purpose.

Originally I created them to collect options for common build scenarios. It was part of the selling point of making it an alternative to the traditional make-based build system. Eventually, this included setting the necessary compilers, some compiler flags, and other advanced options.

They are the result of testing by LAMMPS core developers using containers, which typically install compilers via the distribution-specific standard installation method. But they are a starting point and by no means production-ready. Optimal compiler flags are machine specific.

Spack has much more information to configure and optimize a LAMMPS build. I won't claim that the current recipe has achieved production grade. With the help of vendors and others, it has the potential to evolve into it. Much more than a simple static preset that only defines some tested defaults.

Given the already machine-specific optimizations and default optimization flags added by Spack/CMake, I don't see the added value. On the one hand, the file doesn't change much, as it has to stay generic enough.
On the other hand, adding a build dependency to that specific file gives away control over some options from Spack. We might even have to work against it.

If a specific Intel option is missing, I would add it directly to the Spack recipe. That's why I was asking whether the preset resolves particular deficiencies. Based on my local testing and looking at the verbose CMake output during Spack installs, I don't expect any difference.

Anyway, if you or anyone else at Intel has recommendations on optimizing LAMMPS for specific architectures and some versions of their compiler (backed by actual data and benchmarks), I would gladly accept them to this Spack recipe.

**Pull request closed without merging**
