### PR TITLE
qt-base: add qmake attribute

### PR DESCRIPTION
**Pull request by adamjstewart**
@wdconinc @Sinan81

### CODE REVIEW

**Comment by Sinan81** [comment]
Great!

**Review by wdconinc — APPROVED** [review]
I verified that `qt-base` continues to build fine, as well as its `qt-*` dependencies.

I did not recompile `qt`.

**Comment by adamjstewart** [comment]
This attribute only affects packages that depend on qt/qt-base, it doesn't affect the qt/qt-base installation process.

**Comment by wdconinc** [comment]
> only affects packages that depend on qt/qt-base

I just wanted to make sure that qt-declarative etc don't suddenly start behaving differently because qmake is somehow available. And they don't :)

**Review by sethrj — APPROVED** [review]

**Review by sethrj — APPROVED** [review]
LGTM but the gitlab-ci qt pipeline failed, and since the log is so long I can't see why...

**Comment by sethrj** [comment]
@spackbot run ci

**Comment by sethrj** [comment]
@spackbot run pipeline

**Pull request merged**
