### PR TITLE
WIP: buildcache re-sign: new cmd for re-signing local build cache, stripping spack-build-env.txt

### PR DESCRIPTION
**Pull request by eugeneswalker**
`spack buildcache re-sign` initial attempt adding a command for re-signing local build cache.

Optionally allows `spack-build-env.txt` to be stripped from existing `.spack` archives.

### CODE REVIEW

**Comment by haampie** [comment]
Hey @eugeneswalker let me revive the #24081 pr so you don't have to add this new flag

**Comment by haampie** [comment]
I've rebased #24081, would that make this PR a bit simpler?

**Comment by eugeneswalker** [comment]
> I've rebased #24081, would that make this PR a bit simpler?

The idea being that w/ #24081 it won't be necessary to have `--strip-build-env` ? What about people who have an existing binary cache that they want to keep, that have `spack-build-env.txt` with leaked credentials and/or keys? Obv you'd want to change keys and expire any credentials you suspect were leaked, and if you do that I *guess* there isn't a need to strip the spack-build-env files from the existing binaries? What do you think?

**Comment by haampie** [comment]
> The idea being that w/ #24081 it won't be necessary to have --strip-build-env ?

Yes, I'd be a fan of keeping the spack api simple and stable. The point of `--strip-build-env` will be somewhat unclear after #24081 for new users, and when we add this flag, we will discuss removing it again after current build caches have been processed.

> What about people who have an existing binary cache that they want to keep, that have spack-build-env.txt with leaked credentials and/or keys? Obv you'd want to change keys and expire any credentials you suspect were leaked, and if you do that I guess there isn't a need to strip the spack-build-env files from the existing binaries? What do you think?

Hm, apart from secrets they may also contain personal details that people would like to see removed. So there may still be a need to process current build caches...

---

Alternatively, we could consider distributing the `<prefix>/.spack` folder separately so that users can opt out of distributing it altogether? So split up the tarballs into:

```
<target>-<compiler>-<package>-<hash>.spack
<target>-<compiler>-<package>-<hash>.logs.spack
```

That would solve a couple other problems:

1. build logs may contain sensitive information too, we don't control what goes in there
2. reproducible tarballs: even if software is perfectly binary reproducible, our tarballs have different checksums every build, because they contains these logs

**Comment by eugeneswalker** [comment]
Splitting logs off into their own archive seems like a good precaution against the potential for secret leakage. Other then introducing a bit more logic into the archival process, not sure what downsides this change could bring that would outweigh the benefits. Perhaps others could comment.

**Pull request closed without merging**
