### PR TITLE
Paraview fixes

### PR DESCRIPTION
**Pull request by mathstuf**
---
@dhandeo

### CODE REVIEW

**Comment by dhandeo** [comment]
+1 My branch https://github.com/dhandeo/spack/tree/qt-osx-5.6.0 has similar commits  , but now I will make separae pr for qt and another one for paraview+qt

**Comment by tgamblin** [comment]
@mathstuf @dhandeo Could Paraview just depend on specific versions of HDF/netcdf?

**Comment by mathstuf** [comment]
NetCDF? No. VTK wants the C++ bindings to live in the same prefix (it's on my list to fix so that we can stop using this heavily patched setup, but has been low priority). For HDF5, yeah, probably, but I'd rather not force an old version on anyone else in the ParaView hierarchy (it'd just be limited to VTK's readers and writers).

**Comment by tgamblin** [comment]
@mathstuf: ok, sounds good to me. Paraview's up to you guys... the old version of HDF5 could likely happily coexist with others, though.  The only thing would be once the #311 stuff gets added, Spack may try to actually use the old version for other builds if it is the only thing installed.

**Comment by adamjstewart** [comment]
@mathstuf: I've actually been working with some of the guys from the ACME project and they also have the problem that their build system expects the NetCDF-Fortran libraries to be installed in the same location as the NetCDF-C libraries. Their working on patching their CMake macros, but in the meantime I just hacked Spack to install in the same prefix as NetCDF-C.

**Pull request merged**
