### PR TITLE
sleef: add v3.7.0

### PR DESCRIPTION
**Pull request by blapie**
Update preferred package to SLEEF 3.7

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
Passed:
sleef@3.7.0%clang@15.0.7 sleef@3.7.0%clang@14.0.0 sleef@3.7.0%gcc@9.5.0 sleef@3.7.0%gcc@8.4.0 sleef@3.7.0%gcc@13.1.0 sleef@3.7.0%gcc@12.3.0 sleef@3.7.0%gcc@11.4.0 sleef@3.7.0%gcc@10.5.0 sleef@3.6.1%clang@15.0.7 sleef@3.6.1%clang@14.0.0 sleef@3.6.1%gcc@9.5.0 sleef@3.6.1%gcc@8.4.0 sleef@3.6.1%gcc@13.1.0 sleef@3.6.1%gcc@12.3.0 sleef@3.6.1%gcc@11.4.0 sleef@3.6.1%gcc@10.5.0
-- linux-ubuntu22.04-skylake / clang@14.0.0 ---------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / clang@15.0.7 ---------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@8.4.0 ------------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
sleef@3.6.1~ipo build_system=cmake build_type=Release generator=ninja
sleef@3.7.0~ipo build_system=cmake build_type=Release generator=ninja
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
build-quality-tools/build_pr_changes.py -may -c all
```

**Comment by blapie** [comment]
Thank you @bernhardkaindl ! 
Are any of these tests ran on Arm?

**Comment by bernhardkaindl** [comment]
> Thank you @bernhardkaindl ! Are any of these tests ran on Arm?

No, not yet, but anyone can run them and submit the results! (with `gh` even automatically)

Nothing would prevent anybody from running
`git clone` [https://github.com/spack/build-quality-tools](https://github.com/spack/build-quality-tools) and use it:
```py
cd spack
gh pr checkout <Any PR's PR number> (or otherwise have a checkout of the PR's branch)
git clone https://github.com/spack/build-quality-tools
build-quality-tools/build_pr_changes.py --approve --compiler all --build sleef@3.7.0
```
For getting the diff of a PR (with `--build <spec>` is not given) and for submitting an approval (--approve), it uses the GitHub CLI (https://cli.github.com), but you can also submit the results per cut-and-paste using your regular web browser.

As this script is simple, it should be possible to run it on any platform, in theory even on Windows.

Of course, ideas, suggestions and pull requests are always welcome at https://github.com/spack/build-quality-tools.

**Comment by blapie** [comment]
Brilliant, thanks. Will give that a go.

**Pull request merged**
