### PR TITLE
umpire: Add 2022.10.0

### PR DESCRIPTION
**Pull request by msimberg**
`blt` requirement bumped up to `0.5.2:` due to https://github.com/LLNL/Umpire/pull/784.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version tag, deferring to @davidbeckingsale for merge decision.

**Comment by tldahlgren** [comment]
A number of cache-only-related failures for stacks.

@spackbot run pipeline

**Comment by msimberg** [comment]
Ok, looks like the new version breaks stuff. Failures are at least:

- https://gitlab.spack.io/spack/spack/-/jobs/7262404#L398 (axom is failing, @white238 any ideas?)
- https://gitlab.spack.io/spack/spack/-/jobs/7262277#L557 (ascent is failing, @cyrush any ideas?)

These could also of course be blt-related.

**Comment by white238** [comment]
We ran into this before. Did this creep back in?

https://github.com/LLNL/Umpire/pull/805

**Comment by davidbeckingsale** [comment]
Your PR was merged in January. This is for the October 2022 release, so I assume that's the problem.

**Comment by msimberg** [comment]
Thanks @white238 and @davidbeckingsale. It seems like that PR applies cleanly also to the 2022.10.0 release so I've added that as a patch. Let's see if that helps.

Edit: I've also applied https://github.com/LLNL/Umpire/pull/816.

Are you planning to make a patch release of 2022.10.0 (or a full new release) at some point?

**Comment by msimberg** [comment]
@white238 is this something you've seen before or fixed on master/develop already: https://gitlab.spack.io/spack/spack/-/jobs/7273965#L424?

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by adrienbernede** [comment]
@msimberg Thank you for your work. I think your patch makes sense in the absence of a patch release for 2022.10.

@tldahlgren What do you think about the CI failure ? It looks like it expects a Spack update. Should we hit that "update branch" button ?

@davidbeckingsale There was some recent activity reporting that this error is impacting users:
https://github.com/LLNL/Umpire/pull/805#issuecomment-1613882842

My interest is to see this merged sooner than later if this is approved. It would avoid conflicts when pushing our local packages upstream.

**Comment by msimberg** [comment]
> @msimberg Thank you for your work. I think your patch makes sense in the absence of a patch release for 2022.10.

Thanks for having a look!
 
> @tldahlgren What do you think about the CI failure ? It looks like it expects a Spack update. Should we hit that "update branch" button ?

I'll start off by rebasing. IIRC there was still some other legit build failure, but the build log from above is already purged so I don't remember what it was.

**Comment by msimberg** [comment]
Axom was still failing, e.g. here: https://gitlab.spack.io/spack/spack/-/jobs/8040084#L435. I've blindly added axom 0.8.0 and 0.8.1 in the hope that the problems may have been fixed there (I didn't find that particular issue mentioned on the axom issue tracker, but there were a few other fmt-related issues that seem to have been fixed so maybe we get lucky). @white238 do you know more about the axom failures?

**Comment by msimberg** [comment]
It looks like the new versions of axom fixed all the remaining issues. It may be worth adding conflicts and/or deprecating versions, but I don't know exactly what those would look like. Ignoring that, this would actually be ready to be merged now.

**Review by tldahlgren — DISMISSED** [review]
LGTM

Ping me when you're ready for this PR to be merged.

**Comment by msimberg** [comment]
> LGTM
> 
> Ping me when you're ready for this PR to be merged.

@tldahlgren from my perspective this is ready. I'll leave it up to the package maintainers to decide if/what version conflicts to add.

**Comment by msimberg** [comment]
Rebased once more because of conflicts. @tldahlgren assuming this passes CI again, I don't think there's any point in waiting any longer. If there are further changes needed we can always update the packages later.

**Comment by msimberg** [comment]
It was worth a try to add umpire 2023.06.0, but turns out it was a bad idea. It seems to fail on a GPU-enabled build: https://cdash.spack.io/viewBuildError.php?buildid=3465091. I'm leaving it out of this PR.

**Comment by msimberg** [comment]
@spackbot run pipeline

**Comment by adrienbernede** [comment]
@msimberg I am going to take care of adding 2023.06 in https://github.com/spack/spack/pull/39613.

**Comment by msimberg** [comment]
This is once again ready to be merged.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
