### PR TITLE
e4s: add omega-h +cuda

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `omega-h +cuda` to E4S stack

@wspear @cwsmith

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by cwsmith — DISMISSED** [review]
LGTM

**Review by tldahlgren — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Pipeline is failing (https://gitlab.spack.io/spack/spack/-/jobs/3087286):

```
==> Error: Thrust is broken in CUDA >= 11.2.* see https://github.com/sandialabs/omega_h/issues/366
```

**Comment by eugeneswalker** [comment]
Just rebased on develop. Hoping that will resolve the Thrust conflict since this was merged recently:
* https://github.com/spack/spack/pull/32963

**Review by wspear — APPROVED** [review]

**Pull request merged**
