### PR TITLE
Update FMS: apply patch for fms@2023.03, add variant shared and patch for fms@2024.02

### PR DESCRIPTION
**Pull request by climbfuji**
This PR updates the FMS package with two changes from https://github.com/jcsda/spack, branch spack-stack-dev:
1. For `fms@2023.03`, add patch to fix bug in setting compiler options in `CMakeLists.txt` - see https://github.com/NOAA-GFDL/FMS/pull/1418
2. For `fms@2024.02` and later, define variant `shared` (off by default to keep the current status quo). For `fms@2024.02`, this requires a patch (https://github.com/NOAA-GFDL/FMS/pull/1559), later versions don't need it.

I tested this on my laptop running Oracle Linux 9.1 with `gcc@11.4.1`: built both versions `+shared` and `~shared`. JCSDA tested this on macOS (where the shared version is needed for `fms@2024.02` and later).

### CODE REVIEW

**Comment by climbfuji** [comment]
@rem1776 FYI

**Review by rem1776 — COMMENTED** [review]
I tested this on our rhel 8 system with gcc 13.3 and didn't run into any issues with 2024.02 + the shared option, but when I installed 2023.03 I ran into this checksum error:
```
==> Error: ChecksumError: sha256 checksum failed for /tmp/Ryan.Mulhall/spack-stage/spack-stage-patch-f835c54b2898c980a4cc2a9786134af91a8b1e8b1f11b1734227c6dea26c3b79/c9bba516ba1115d4a7660fba92f9d67cf3fd32ad.patch?full_index=1
    Expected f835c54b2898c980a4cc2a9786134af91a8b1e8b1f11b1734227c6dea26c3b79 but got 07d5b68838bba61ee547bd4cd7c12d81228c91a80a966b8693694fa236d0ac30. File size = 1010 bytes. Contents = b'From c9bba516ba1...()\n   endif()\n \n'
```

**Comment by climbfuji** [comment]
> I tested this on our rhel 8 system with gcc 13.3 and didn't run into any issues with 2024.02 + the shared option, but when I installed 2023.03 I ran into this checksum error:
> 
> ```
> ==> Error: ChecksumError: sha256 checksum failed for /tmp/Ryan.Mulhall/spack-stage/spack-stage-patch-f835c54b2898c980a4cc2a9786134af91a8b1e8b1f11b1734227c6dea26c3b79/c9bba516ba1115d4a7660fba92f9d67cf3fd32ad.patch?full_index=1
>     Expected f835c54b2898c980a4cc2a9786134af91a8b1e8b1f11b1734227c6dea26c3b79 but got 07d5b68838bba61ee547bd4cd7c12d81228c91a80a966b8693694fa236d0ac30. File size = 1010 bytes. Contents = b'From c9bba516ba1...()\n   endif()\n \n'
> ```

I am pretty sure this is because spack audit forced me to change the patch url from a PR commit to the final commit in the main development branch - my apologies. I updated the hash, do you want to try again?

**Review by rem1776 — APPROVED** [review]
@climbfuji Yeah looks like its working now, thanks for adding this!

**Review by srherbener — APPROVED** [review]
Looks great! Thanks for making this change.

**Review by tldahlgren — APPROVED** [review]
Confirmed patches, LGTM.

**Comment by climbfuji** [comment]
Thanks very much @tldahlgren !

**Pull request merged**
