### PR TITLE
iconv: from libiconv, not libc

### PR DESCRIPTION
**Pull request by haampie**
`glibc` and `musl` provide a basic implementation of `iconv` (`iconv`,
`iconv_open`, `iconv_close`), but in practice the installation may be
missing the character encoding methods to make them usable at runtime.
On Fedora for example, users need to

```
yum install glibc-gconv-extra
```

to get the character encodings that `gettext` requires during configure,
such as `EUC-JP` (whatever that is). Users may not have permissions to
install the missing parts of glibc.

Since Spack can install `libiconv`, it seems simpler to me to always use
that.

The alternative is that Spack figures out if glibc / musl provide a
complete implementation of iconv, and if so set `glibc +iconv` as
external. I think it's easier to use `libiconv` instead of doing that
extensive validation.

### what could possibly go wrong

libc and libconv provide the same API. Both have an `iconv.h` header.
The difference is that libiconv uses

```c
#⁠define iconv_open libiconv_open
```

etc so libc and libiconv have a different set of symbols. That means
you can use `libc` and `libiconv` together just fine in an executable
or library.

The only thing that can go wrong is when a configure script merely
checks whether `iconv.h` exists, but forgets to check whether
`-liconv` is required. Forgetting `-liconv` causes linking failure, but
that sounds easy to fix.

### CODE REVIEW

**Review by sethrj — DISMISSED** [review]

**Review by adamjstewart — DISMISSED** [review]
GDAL/Grass/OpenCV look good. I wonder if we should backport this to a patch release since it fixes a bug that may affect many users. I know we don't normally backport package changes, but this is a bug fix, not new versions.

**Review by alalazo — DISMISSED** [review]

**Review by michaelkuhn — DISMISSED** [review]

**Comment by trws** [comment]
Sounds like a good idea.  As an implementation thought, do we need to continue to provide the virtual or can we make iconv _only_ libiconv where one is a bundle package or alias or something for the other?

**Comment by adamjstewart** [comment]
Ah, good point. @tgamblin this is going to result in basically every single person who updates Spack needing to run `spack clean -m` because we removed a virtual. Now might be a good time to prioritize fixing that...

For now, I would either do what @trws said or wait until virtuals can be removed without trouble.

**Comment by greenc-FNAL** [comment]
https://github.com/spack/spack/issues/44320#issuecomment-2127398784

**Comment by haampie** [comment]
@adamjstewart that issue should be fixed already

and @trws yeah, I think that's be much better, especially if we aim to backport this.

**Comment by haampie** [comment]
Simplified it so it's easier to backport.

**Comment by trws** [comment]
Wow, yeah, that simplifies it greatly. Maybe worth keeping the previous version of the patch for a larger version bump, or do you think we should leave it plumbed like this?

**Comment by haampie** [comment]
Yeah, i could submit a follow up pr

**Comment by knoepfel** [comment]
@haampie, why not just provide a (e.g.) `provides_iconv` variant that could be specified for those who know their external install of `glibc` provides sufficient `iconv` symbols?

**Comment by greenc-FNAL** [comment]
@haampie I still have concerns, but I am currently attempting to build our stack after applying this PR. I'd appreciate your holding off on merging until we have an answer.

**Comment by haampie** [comment]
I relaxed the PR even more: `libiconv` is now the preferred provider, and that's all.

There was an issue where Spack would continue to reuse link deps that depend on glibc for iconv after deleting `provides("iconv")` from glibc, leading to both glibc and libiconv in the link sub-dag providing iconv. That should not really be a problem for the software due to different symbols, but breaks invariants in Spack.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
