### PR TITLE
embree: checksum 3.12.2 & 3.13.1

### PR DESCRIPTION
**Pull request by aumuell**
also checked that these versions build fine

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@aumuell I always get this error, independent with LLVM13, 12 and 11 when buiding the `ispc` dependency
```
 cd spack-stage-ispc-1.16.1-bj6yak4574yzkxi2ice6wia2fgnuhgaf/spack-src && ubuntu18.04-zen/gcc-7.5.0/m4-1.4.19-mfwutewkfi26kb6hwkxvrxwwrlw4wkno/bin/m4 -Ibuiltins -DLLVM_VERSION=LLVM_11_1 -DBUILD_OS=UNIX -DRUNTIME=32 
            builtins/target-sse4-i32x8.ll | ".../gcc-7.5.0/python-3.8.11-j47s6ghlntdvuntyspm7vcn7mupgc3a
            a/bin/python3.8" bitcode2cpp.py builtins/target-sse4-i32x8.ll --type=ispc-target --runtime=32 --os=UNIX --llvm_as .../gcc-7.5.0/llvm-11.1.0-3mxxrtsn5pnoajmyh3lxc4shk632yndr/bin/llvm-as > /home/kaindlb/home/spack/.stage/spack-stage-isp
            c-1.16.1-bj6yak4574yzkxi2ice6wia2fgnuhgaf/spack-build-bj6yak4/./builtins-target-sse4-i32x8-32bit-unix.cpp
     146    In file included from builtins/builtins-c-cpu.cpp:69:
     147    In file included from /usr/include/unistd.h:25:
  >> 148    /usr/include/features.h:424:12: fatal error: 'sys/cdefs.h' file not found
     149    #  include <sys/cdefs.h>
     150               ^~~~~~~~~~~~~
```

**Comment by aumuell** [comment]
As far as I am aware, this is a problem specific to 64 bit Ubuntu and probably also other Debian derivatives. There you need libc-dev-i386 for <sys/cdefs.h>: https://stackoverflow.com/questions/51765069/fatal-error-sys-cdefs-h-no-such-file-or-directory-while-compiling-openssl-1-1

Is there a way to add this as a dependency?

**Comment by bernhardkaindl** [comment]
> libc-dev-i386 - Is there a way to add this as a dependency?

No, spack does not have a glibc package so far, and in addition not one as a stand-in for the 32-bit glibc, that would involve bootstrapping a complete 32+64-bit bit glibc+gcc toolchain.

But now that I recognize that the issue is attempting to build the 32-bit target of the compiler, it's easy to skip the 32-bit targets (in this case IA32/i386), which I'd guess are normally never needed. This fixes it:
```py
-- a/var/spack/repos/builtin/packages/ispc/package.py
+++ b/var/spack/repos/builtin/packages/ispc/package.py
@@ -51,6 +51,9 @@ class Ispc(CMakePackage):
     patch('fix-linking-against-llvm-10.patch', when='@1.13.0:1.13',
           sha256='d3ccf547d3ba59779fd375e10417a436318f2200d160febb9f830a26f0daefdc')
 
+    def patch(self):
+        filter_file('bit 32 64', 'bit 64', 'cmake/GenerateBuiltins.cmake')
+
     def cmake_args(self):
         args = []
         args.append('-DARM_ENABLED=FALSE')
```
Would it be needed to support compiling for IA32 (32-bit Pentium instructions) with `ispc` and `embree`, etc?

If not, I'd submit this patch as a new PR, otherwise we could agree on adding a check where the patch() function checks if the compiler supports `-m32`, and disable IA32 only if that fails.

**Comment by aumuell** [comment]
> ```python
> -- a/var/spack/repos/builtin/packages/ispc/package.py
> +++ b/var/spack/repos/builtin/packages/ispc/package.py
> @@ -51,6 +51,9 @@ class Ispc(CMakePackage):
>      patch('fix-linking-against-llvm-10.patch', when='@1.13.0:1.13',
>            sha256='d3ccf547d3ba59779fd375e10417a436318f2200d160febb9f830a26f0daefdc')
>  
> +    def patch(self):
> +        filter_file('bit 32 64', 'bit 64', 'cmake/GenerateBuiltins.cmake')
> +
>      def cmake_args(self):
>          args = []
>          args.append('-DARM_ENABLED=FALSE')
> ```
> 
> Would it be needed to support compiling for IA32 (32-bit Pentium instructions) with `ispc` and `embree`, etc?

I cannot really check whether this works on IA32, but the proposed solution definitely fits my needs, as the 64bit-only ispc is enough to compile embree and my software that depends on it.
> 
> If not, I'd submit this patch as a new PR, otherwise we could agree on adding a check where the patch() function checks if the compiler supports `-m32`, and disable IA32 only if that fails.

That is perhaps the most general approach, but probably it is sufficient to not filter out the 32 bit branch on IA32?

**Review by bernhardkaindl — APPROVED** [review]
Because I saw this comment from @aumuell on this commit, I think we can approve and merge this PR:
> Thank you, this worked beautifully while I met the same issue on a 64 bit RHEL 8 installation.

**Pull request merged**
