### PR TITLE
mpich: undefined variable dso_suffix

### PR DESCRIPTION
**Pull request by heerener**
I had some failures due to an undefined variable. Other packages seem to import it from here (e.g. `trilinos`, `python`, `gcc`, ...) so I figure it's a safe default.

### CODE REVIEW

**Comment by heerener** [comment]
I'm not sure https://gitlab.spack.io/spack/spack/-/jobs/6845529 and https://gitlab.spack.io/spack/spack/-/jobs/6845527 are related to my change... can I rebuild those somehow?

**Comment by haampie** [comment]
Can you share where you're getting this problem? Cause those should be defined in the module

**Comment by heerener** [comment]
> Can you share where you're getting this problem? Cause those should be defined in the module

Sure!

While installing https://github.com/BlueBrain/spack/blob/develop/bluebrain/repo-bluebrain/packages/neurodamus-neocortex/package.py on Ubuntu 22.04 I run into this:  (`spack -d install -v` to actually show the stacktrace)

```
Traceback (most recent call last):
  File "/home/heeren/source/github/bluebrain/spack/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/cmd/install.py", line 522, in install
    install_all_specs_from_active_environment(
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/cmd/install.py", line 430, in install_all_specs_from_active_environment
    env.write()
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/environment/environment.py", line 2091, in write
    spack.hooks.post_env_write(self)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/hooks/__init__.py", line 74, in __call__
    hook(*args, **kwargs)
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/hooks/module_file_generation.py", line 57, in post_env_write
    _for_each_enabled(spec, "write")
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/hooks/module_file_generation.py", line 32, in _for_each_enabled
    getattr(generator, method_name)()
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/modules/common.py", line 924, in write
    context = self.context.to_dict()
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/tengine.py", line 67, in to_dict
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/tengine.py", line 67, in <listcomp>
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/home/heeren/source/github/bluebrain/spack/lib/spack/spack/modules/common.py", line 767, in environment_modifications
    dep.package.setup_dependent_package(spec.package.module, spec)
  File "/home/heeren/source/github/bluebrain/spack/var/spack/repos/builtin/packages/mpich/package.py", line 449, in setup_dependent_package
    join_path(self.prefix.lib, "libmpi.{0}".format(dso_suffix)),
NameError: name 'dso_suffix' is not defined
```

`neurodamus-neocortex` inherits from `neurodamus-model`, which depends on mpi.

I'm using spack from the BlueBrain fork, which has been updated to 0.19.1. 

Maybe something in that package inheriting tree screwed up the availability of `dso_suffix`?

**Comment by naromero77** [comment]
@raffenet Can you take a look?

**Comment by raffenet** [comment]
> @raffenet Can you take a look?

This change looks to be Spack internal stuff not related to MPICH. I'm afraid I don't really understand the issue.

**Review by naromero77 — APPROVED** [review]

**Comment by naromero77** [comment]
@heerener Can you confirm whether or not the new commits pushed by @alalazo resolve your issue?

**Comment by zackgalbreath** [comment]
@spackbot run pipeline

**Comment by naromero77** [comment]
Failures seem to be caused by: https://github.com/spack/spack/pull/34821 Going to update the branch and then re-run the pipeline.

**Comment by naromero77** [comment]
@spackbot run pipeline

**Comment by naromero77** [comment]
I am merging this in because it looks like the right fix and the tests have passed.

**Pull request merged**
