### PR TITLE
Conduit: require hdf5+hl

### PR DESCRIPTION
**Pull request by bvanessen**

### CODE REVIEW

**Comment by cyrush** [comment]
So this is related to the problem with cmake 3.18.x right? (Now fixed in 3.18.2)

Conduit doesn't use hdf5+hl. In fact it filters it out of any linking it propgates if HDF5 was built with it. 

More details:

https://github.com/spack/spack/issues/17846

**Comment by bvanessen** [comment]
Okay, thanks @cyrush.

**Comment by cyrush** [comment]
@bvanessen while it is a CMake issue -- if this is causing pain, I am open to merge to prevent pain.  Let me know your thoughts.

**Comment by bvanessen** [comment]
It is fine.  It just means to to use 3.18.x on LC we have to build it ourselves, since they don’t have an updated version.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Pull request closed without merging**
