### PR TITLE
Perl: Fix issues when compiling 5.34 with nvhpc compilers

### PR DESCRIPTION
**Pull request by samcmill**
Fix the issue reported in https://github.com/spack/spack/pull/29854.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
Is there some plan to be able to compile `perl` with `nvhpc` without maintaining a patch for stable series?

**Comment by samcmill** [comment]
> Is there some plan to be able to compile `perl` with `nvhpc` without maintaining a patch for stable series?

Not at the moment.  I am unable to submit patches upstream to Perl.  

Part of the patch will become unnecessary if / when the nvhpc compilers are updated to support src from stdin.

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeilne

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
