### PR TITLE
e4s ci: add sundials +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
FYI @balos1 @cswoodard @gardner48 @wspear

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
It looks like `sundials` doesn't build with `+rocm` (see https://gitlab.spack.io/spack/spack/-/jobs/2802229).

**Comment by eugeneswalker** [comment]
> It looks like `sundials` doesn't build with `+rocm` (see https://gitlab.spack.io/spack/spack/-/jobs/2802229).

The issue is described here:
* https://github.com/spack/spack/issues/29526

**Comment by eugeneswalker** [comment]
Closing this as it is obsolete following https://github.com/spack/spack/commit/2b04c4f8409de38b706792aa2749139be4ff27f8

**Pull request closed without merging**
