### PR TITLE
frontier-client: fix build with clang

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Review by iarspider — DISMISSED** [review]

**Comment by iarspider** [comment]
What is the exact error that you see? I don't see CC being overridden in cmsdist or lcgcmake.

**Comment by vvolkl** [comment]
```
  >> 11    make[1]: gcc: Permission denied
```
I guess gcc is available in those build environments?

**Comment by alalazo** [comment]
What was this PR solving exactly? Why are we using the generic name `cc`?

**Comment by vvolkl** [comment]
@alalazo The Makefile of this package hardcodes `CC    = gcc` so in a clang build this will either fail if gcc is not available or use gcc instead of the intended clang. `cc` is provided by spack and points to the right compiler so this seems the best fix.

**Comment by alalazo** [comment]
Spack also provides the same compiler wrapper under different names via symlinks, including `clang`. Was wondering if there is any reason not to use them.

**Comment by vvolkl** [comment]
> Spack also provides the same compiler wrapper under different names via symlinks, including `clang`. Was wondering if there is any reason not to use them.

I could do a `if %clang: CC =clang elif %gcc: CC =  gcc`. Is that better in any way?

**Comment by vvolkl** [comment]
@alalazo updated

**Review by alalazo — APPROVED** [review]

**Comment by vvolkl** [comment]
@alalazo Thanks!

**Pull request merged**
