### PR TITLE
Oneapi add compiler

### PR DESCRIPTION
**Pull request by frankwillmore**
This adds a compiler class to recognize oneapi as distinct from retro Intel compilers. Example compiler stanza:
```- compiler:
    spec: oneapi@2020.09.15.001
    paths:
      cc: icx 
      cxx: icpx
      f77: ifx
      fc: ifx
    flags: {}
    operating_system: opensuse_leap15
    target: x86_64
    modules:
    - /hidden/because/of/NDA
    environment:
      prepend_path:
        LD_LIBRARY_PATH:  /hidden/because/of/NDA 
      unset: []
    extra_rpaths: [] ```

### CODE REVIEW

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Needs tests for both detection and flags, see `lib/spack/spack/test/compilers/*.py`

**Comment by rscohn2** [comment]
@scheibelp asked me too look at it. It looks fine to me. You may want to delete the code that deals with old versions:
`if self.real_version < ver('13'):`
because oneapi versions start at 2021.

**Comment by frankwillmore** [comment]
I will clear the cruft of old versions and work in the tests, once ALCF power is back.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Flake8:
```
lib/spack/spack/compilers/oneapi.py:6: [F401] 'spack.compiler.UnsupportedCompilerFlag' imported but unused
lib/spack/spack/compilers/oneapi.py:7: [F401] 'spack.version.ver' imported but unused
lib/spack/spack/compilers/oneapi.py:58: [E501] line too long (118 > 79 characters)
lib/spack/spack/compilers/oneapi.py:60: [E501] line too long (165 > 79 characters)
lib/spack/spack/compilers/oneapi.py:63: [E501] line too long (80 > 79 characters)
lib/spack/spack/compilers/oneapi.py:69: [E303] too many blank lines (2)
lib/spack/spack/test/compilers/detection.py:155: [E261] at least two spaces before inline comment
lib/spack/spack/test/compilers/detection.py:159: [E501] line too long (100 > 79 characters)
lib/spack/spack/test/compilers/detection.py:162: [E261] at least two spaces before inline comment
lib/spack/spack/test/compilers/detection.py:166: [E501] line too long (99 > 79 characters)
lib/spack/spack/test/compilers/detection.py:169: [E261] at least two spaces before inline comment
lib/spack/spack/test/compilers/detection.py:174: [E123] closing bracket does not match indentation of opening bracket's line
lib/spack/spack/test/compilers/detection.py:174: [E202] whitespace before ')'
```

**Comment by adamjstewart** [comment]
More flake8:
```
lib/spack/spack/test/compilers/detection.py:159: [W291] trailing whitespace
lib/spack/spack/test/compilers/detection.py:164: [E121] continuation line under-indented for hanging indent
lib/spack/spack/test/compilers/detection.py:168: [E131] continuation line unaligned for hanging indent
lib/spack/spack/test/compilers/detection.py:172: [E121] continuation line under-indented for hanging indent
lib/spack/spack/test/compilers/detection.py:294: [E122] continuation line missing indentation or outdented
lib/spack/spack/test/compilers/detection.py:295: [E122] continuation line missing indentation or outdented
```
You can use `# noqa` on some of those testing lines so that you don't have to worry about the continuation line errors, that's what we do for other compiler tests.

**Comment by adamjstewart** [comment]
More more flake8:
```
lib/spack/spack/test/compilers/detection.py:294: [E122] continuation line missing indentation or outdented
lib/spack/spack/test/compilers/detection.py:295: [E122] continuation line missing indentation or outdented
```
If you have `flake8` installed locally, you can run `spack flake8` to check before committing. You can also use an auto-formatter like `black` or `autopep8` to do everything for you.

**Comment by frankwillmore** [comment]
I backed out the ifx self-identification test because the output differs considerably and a version number couldn't be parsed out. Also, removed checks for -std={c++0x,c++1y} since the versioning of oneapi is new and all functionality is >= std=c++17.

**Review by adamjstewart — APPROVED** [review]

**Comment by frankwillmore** [comment]
Adding a note on falling back to ifort instead of ifx. Spack looks not to support having two fortran compilers in the same Compiler class. In order to use ifort, I needed to change ifx to ifort here in: .../spack/compilers/oneapi.py: 
``` 
 22     # Named wrapper links within build_env_path
 23     link_paths = {'cc': 'oneapi/icx',
 24                   'cxx': 'oneapi/icpx',
 25                   'f77': 'oneapi/ifort',
 26                   'fc': 'oneapi/ifort'}

``` 
As the ifx compiler matures, the need to fall back to ifort should vanish, but this may help some builds. 
This came up in the context of building mpich+fortran. The mpifort wrapper was not being generated correctly, presumably because it was discovering flags using the fortran compiler.

**Pull request merged**
