### PR TITLE
Using fPIC in PERL when using an Intel compiler.

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Continuation of #3081.

**Comment by becker33** [comment]
@mmpozulp does this solve your perl issue?

**Comment by kserradell** [comment]
Hello, I'm having the same problem with perl and Intel 16.0.3

**Comment by adamjstewart** [comment]
The same problem as #2930 or #3081?

**Comment by kserradell** [comment]
#2930 

`ld: cannot find -lcilkrts`

when

`spack install perl%intel@16.0.3`

**Comment by adamjstewart** [comment]
Glad I'm not the only one. I would recommend sending a bug report to the Perl developers. I also sent one but haven't heard back from them in a while. If they know that multiple users are experiencing this problem it might bump it up in terms of priority.

**Comment by kserradell** [comment]
They have a bug tracker to use the same as you or a post in a forum?

**Comment by adamjstewart** [comment]
I think they had a bug tracker but I remember having trouble signing up for an account. I just sent an email to perlbug@perl.org. You're better off going through their bug tracker if you can.

**Comment by mgsternberg** [comment]
`-fPIC` is not the problem – `ld -r` might be.

I just built Perl-5.24.1 perfectly fine outside of spack (and on CentOS-6.9), as follows:

    module purge
    module load intel/18

    sh Configure -de \
            -Dprefix=$prefix    \
            -Dinc_version_list=none     \
            -DEBUGGING=none     \
            -Dcc=icc            \
            -Duseshrplib        \
            -Accflags=-fPIC     \
            ;

Within spack, though, all goes well for `perl@5.24.1%intel@18.0.1+cpanm+shared arch=linux-centos6-x86_64` until trying to link `libperl.sa`:

> cc -o libperl.sa -r  -L/opt/spack/linux-centos6-x86_64/gdbm/1.14.1-intel-16.0.3/Hqzuvja/lib op.o     perl.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o doop.o doio.o regexec.o utf8.o taint.o deb.o universal.o globals.o perlio.o perlapi.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o   DynaLoader.o -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
> **ld: cannot find -lcilkrts**

For comparison, my build uses:

**Comment by adamjstewart** [comment]
If you want to link to `perl%gcc` for a temporary workaround, you can use:
```
$ spack install foo%intel ^perl%gcc
```
But yes, a long term fix for building `perl%intel` would be amazing!

**Pull request merged**
