### PR TITLE
fix MUMPS build on OSX (set parallel=False)

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by tgamblin** [comment]
if this is broken on darwin isn't it probably broken elsewhere too?

**Comment by davydden** [comment]
i did not test that. Do you want me to disable parallel build unconditionally until someone confirms that it works in parallel, say, with gcc?

**Comment by tgamblin** [comment]
I think that's reasonable -- I can test the change on Linux if you want.  I think for this particular change a race on Mac OS X indicates that it at least is likely to be broken on Linux, and parallel=False is safer...

**Comment by tgamblin** [comment]
FYI: I'm still working on better CI for Spack internally at LLNL.  I hope to have some Mac test machines soon, in addition to more local build testing on our RHEL clusters.

**Comment by davydden** [comment]
@tgamblin sounds good!

**Comment by nrichart** [comment]
I confirm it needs `parallel = False`
In fact I was sure it was already in there.
There is a dependency problem between the different libraries and the executables.

**Comment by davydden** [comment]
could we please merge this?

**Comment by tgamblin** [comment]
done

**Pull request merged**
