### PR TITLE
cuda: add v12.5.1

### PR DESCRIPTION
**Pull request by pauleonix**
Add download links and hashes (12.5 is the first version not to support PowerPC anymore).

Update host compiler conflicts for gcc and clang.

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by pauleonix** [comment]
The CI failure seems to be related to an incompatibility between CCCL 2.5 and VTK-m (I wrote an [issue](https://gitlab.kitware.com/vtk/vtk-m/-/issues/818) for them).

**Review by kmorel — COMMENTED** [review]
Thanks for pointing out the issue with VTK-m. It looks like one of our patches has outlived its usefulness.

The changes to the VTK-m package look OK to me. I cannot comment on the changes to the cuda packages.

It would be great if you could help verify the fix at https://gitlab.kitware.com/vtk/vtk-m/-/merge_requests/3230 is correct so the problem does not reemerge in 2.1.1 or later versions.

**Comment by pauleonix** [comment]
Sorry, I made a copy-paste error when adding the conflict (`+cuda@12.5:` instead of `^cuda@12.5:`).

**Comment by wyphan** [comment]
@pauleonix Would you mind also addressing this stuff from the [release notes][rel]?

> - NVIDIA CUDA support for the PowerPC architecture is removed in CUDA 12.5.
> - CUDA Toolkit 12.4 deprecated support for the following host compilers:
>   - Microsoft Visual C/C++ (MSVC) 2017
>   - All GCC versions prior to GCC 7.3

There might be more in that page, but I think these in particular can break stuff.

[rel]: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/#deprecated-or-dropped-architectures

**Comment by pauleonix** [comment]
@wyphan Huh, regarding GCC 6.x I was looking at [this table](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#id15) which Nvidia might have forgotten to update.

**Comment by pauleonix** [comment]
@wyphan Those are just deprecations. Support is not removed yet for `gcc@6:7.2` and MSVC 2017. See also [this table](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#id15).

**Comment by wyphan** [comment]
My bad, I guess I shouldn't have lumped them together. But it would be nice if we can warn users about these deprecations.

**Comment by pauleonix** [comment]
@wyphan Would you have any example or documentation pointer for such a deprecation? I only know about deprecating versions of the package itself and not its dependencies.

**Comment by wyphan** [comment]
@pauleonix I guess you're right, I can't find anything either. Either we can just add a warning message using `tty.msg` or `tty.info` from `llnl.util` module, or we just ignore it until support actually gets dropped?

**Comment by pauleonix** [comment]
@wyphan I think I'm in favor of ignoring it, but I have no strong opinion either way.

**Comment by pauleonix** [comment]
Part of this PR was superseded by #44971. I have merged develop and cleaned up here s.t. this PR is just about adding CUDA 12.5.1 and adding missing build system conflicts. ~~I have also added myself as maintainer of the cuda package as discussed with @alalazo on Slack.~~ (Edit: moved this change to another PR).

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@pauleonix This is pending Gitlab. In case there are errors to be fixed, please submit a PR just to add yourself as a maintainer :slightly_smiling_face:

**Comment by alalazo** [comment]
@pauleonix Can you submit a separate PR? We have issues with Gitlab, but I can force-merge a PR that just adds a maintainer. Ping me in there if you submit.

**Review by alalazo — APPROVED** [review]
Finally!

**Pull request merged**
