### PR TITLE
packages/med: review med and salome-med packages

### PR DESCRIPTION
**Pull request by mthcrts**
The `med` package is currently based on CMakePackage but its README recommends to use autotools.
Actually, it is not possible to build med library with 64 bits integers with the Fortran support using cmake.

The `salome-med` package is using the upstream tarballs. I do not understand why 2 packages would be necessary.
I removed `salome-med`.
So, I changed its unique dependent: `salome-medcoupling`.

This branch proposes for `med`:
- to use the AutoToolsPackage base,
- add int64 variant (64 bits integer in fortran interface),
- add python variant (add python bindings),
- add mesgerr variant (show/hide some messages).

and for `salome-medcoupling`:
- now `depends_on("med")`,
- rename `in64` to `int64`,
- enable ptscotch if +scotch+mpi or scotch if +scotch~mpi.

### CODE REVIEW

**Comment by franciskloss** [comment]
Hello,

Thank's to use med library and MEDCoupling tools.

I am an engineer from CEA compagny and I am in a strong relation with SALOME team.
Notice that med and MEDCoupling are part of SALOME platform see https://www.salome-platform.org

I add salome-med and salome-medcoupling to be compliant with different constraints issue from SALOME platform.
Despite the README of med, it is legacy to use cmake to build it and this way to build is maintained by med team.

My point of view:
1) use salome-XXX (med, configuration, medcoupling)
2) if there are some lacks, it is better to add them in salome-med and salome-medcoupling
3) and respect the principal constraint: a version of med is strongly based on a specific version of hfd5
(in some cases, it is important for ascendant compatibility and for interoperability )

       Regards,

Francis Kloss

**Comment by mthcrts** [comment]
Hello,

> Thank's to use med library and MEDCoupling tools.

I'm working on code_aster and salome_meca... ;-)

> I am an engineer from CEA compagny and I am in a strong relation with SALOME team. Notice that med and MEDCoupling are part of SALOME platform see https://www.salome-platform.org
> 
> I add salome-med and salome-medcoupling to be compliant with different constraints issue from SALOME platform. Despite the README of med, it is legacy to use cmake to build it and this way to build is maintained by med team.

I will try again to build libmed with *med_int* as *long*. `MED_MEDINT_TYPE` is unuseful. `FCFLAGS` should be sufficient... Re-reading the CMake files, I probably did a mistake.

> My point of view:
> 
>     1. use salome-XXX (med, configuration, medcoupling)
> 
>     2. if there are some lacks, it is better to add them in salome-med and salome-medcoupling

I think that's not a good idea to have 2 packages for the same library. For example, `gmsh` depends on `med`, if I want to build code_aster with `medcoupling` and `gmsh`, I need `med` and `salome-med`, and they may conflict in the same environment...

>     3. and respect the principal constraint: a version of med is strongly based on a specific version of hfd5
>        (in some cases, it is important for ascendant compatibility and for interoperability )
>        ```

I'm new to spack but `med@4.1.0 ^hdf5@1.10.3` in your environment (or in `salome-medcoupling`) should do the job.

Mathieu

**Comment by franciskloss** [comment]
Bonjour,

Dans ces conditions, je vous propose que vous vous entreteniez avec votre collègue d'EDF
qui est le responsable de med-fichier et il est joinable via l'équipe SALOME d'EDF.

Pour info complémentaire, la deuxième idée sous-jancente est d'utiliser le préfixe "salome-"
afin de construire à terme d'autres packages spack correspondant à d'autres modules ou d'autres outils de SALOME ...

Francis

**Comment by mthcrts** [comment]
ok, I forget salome-med and will work with med package.

**Pull request closed without merging**
