### PR TITLE
mkl: add provide blas/lapack

### PR DESCRIPTION
**Pull request by davydden**
@adamjstewart ping.

tested with Arpack on macOS with external MKL.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Looks like a good start. This will also need to be in the intel-parallel-studio package. Unfortunately, I don't have much experience with linking to MKL yet (since Spack has never supported it before), but I often see several MKL-related flags being passed to packages. These will need to be added to this package in a way that other packages can pick up the appropriate flags depending on if they are using MKL, OpenBLAS, or Atlas. For example, we build HPL with `-mkl=cluster`. [This webpage](https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-for-linux-linking-applications-with-intel-mkl-version-100) lists some of the various linking options.

**Comment by davydden** [comment]
@adamjstewart i only have access to MKL alone on macOS, thus i will modify only this package for now. W.r.t. linking, it has indeed a lot of options, hopefully `mkl_rt` works 99% of cases, otherwise one has to link against several different libs within MKL (see notes in this PR).

**Comment by alalazo** [comment]
I think [this](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) is the definitive resource on linking with MKL :blush:

**Comment by mwilliammyers** [comment]
In my experience `mkl_rt` is good enough for our clusters. We also have `MKLROOT` exported as an environment variable in our modulefile... I seem to remember *needing* that for certain things that I can't remember off the top of my head.

**Comment by davydden** [comment]
@mwilliammyers will add `MKLROOT`, can't harm.

**Comment by mwilliammyers** [comment]
@davydden Thanks for this PR! I have been meaning to do this myself...

**Comment by Rombur** [comment]
@davydden since the threading layer and the interface layer are set at runtime, I think it would be useful to copy part of the documentation that you wrote for ```setup_dependent_package``` in the package docstring. This way it will appears with ```spack info```

**Comment by davydden** [comment]
@Rombur i added this info to the docstring.

**Comment by Rombur** [comment]
@davydden Thanks

**Comment by tgamblin** [comment]
So is this ready?  @lee218llnl, any additions?

**Comment by davydden** [comment]
from my side it is.

**Comment by lee218llnl** [comment]
FWIW now that this has been merged, this looks good to me. I trust someone has actually tried building something that uses the MKL blas/lapack. I will need to do something similar for the parallel-studio packages.

**Pull request merged**
