### PR TITLE
dealii - add two new versions

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Comment by hppritcha** [comment]
hmmm i can't grok the ci/gitlab-ci failure.

**Comment by eugeneswalker** [comment]
From:
* [(specs) dealii/bwjtkcs 9.4.2 gcc@11.1.0 linux-ubuntu20.04-x86_64_v3 E4S](https://gitlab.spack.io/spack/spack/-/jobs/6706087)
```
...
1 error found in build log:
     343    -- GINKGO_LIBRARY_MPI::MPI_CXX not found! The call was:
     344    --     FIND_LIBRARY(GINKGO_LIBRARY_MPI::MPI_CXX NAMES MPI::MPI_CXX 
            HINTS /home/software/spack/__spack_path_placeholder__/__spack_path_
            placeholder__/__spack_path_placeholder__/__spack_path_placeholder__
            /__spack_path_placeholder__/__spack_path_placeholder__/__spack_path
            _placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux
            -ubuntu20.04-x86_64_v3/gcc-11.1.0/ginkgo-1.5.0-klwaqix5iovcw2kicdl3
            7ww3amknz6du//lib NO_DEFAULT_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAK
            E_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_CMAKE_FIN
            D_ROOT_PATH)
     345    --   GINKGO_VERSION: 1.5.0
     346    --   GINKGO_LIBRARIES: *** Required variable "GINKGO_LIBRARY_MPI::M
            PI_CXX" set to NOTFOUND ***
     347    -- Could NOT find GINKGO
     348    -- DEAL_II_WITH_GINKGO has unmet external dependencies.
  >> 349    CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESS
            AGE):
     350    
     351    
     352      Could not find the ginkgo library!
     353    
     354      Please ensure that a suitable ginkgo library is installed on your
             computer.
     355    
See build log for details:
  /tmp/root/spack-stage/spack-stage-dealii-9.4.2-bwjtkcspzqzf4ouzrfjlqwwnjtal7jnp/spack-build-out.txt
```

Does this help?

**Comment by hppritcha** [comment]
thanks.  i think there's a straightforward fix for that.  wonder if its something about ginkgo.  i don't see any mpi looking thing in the ginkgo install path even though the cmake args requested MPI.

I think this package has aged by the way.  at least on a rhel8 system using gcc 8.5.0 just installing ```dealii``` didn't work.
I had to use ~cgal cxxstd=17 in the spec.

I'm needing this package for a rather complex DFT code I'm trying to build in a way that's reproducible.

**Comment by eugeneswalker** [comment]
> I think this package has aged by the way. at least on a rhel8 system using gcc 8.5.0 just installing `dealii` didn't work. I had to use ~cgal cxxstd=17 in the spec.

I just pushed a change to the E4S CI Spack environment that so that the dealii spec has `~cgal cxxstd=17` -- hopefully this resolves.

**Comment by hppritcha** [comment]
my branch is way out of date with head of develop.  that's probably causing problems. rebasing.

**Comment by hppritcha** [comment]
turns out the conditions for applying patches for ginkgo and python weren't general enough.  one still needs to build with
```
spack install dealii cxxstd=17

**Comment by luca-heltai** [comment]
I'm trying now to workaround the cxx17 issue. Sorry for being slow on getting back to this.

I've pushed 24c2498b85 on the other PR. This should fix the issue of cxx17.

gcc8.5 does not expose c++17 capabilities unless explicitly asked to do so, therefore setting `cxx=default` results in a conflict with CGAL that needs c++17 capabilities (i.e., one has to specify CMAKE_CXX_FLAGS="std=c++17").

I've changed the default behavior of the dealii package to be incompatible with "default" for 9.4 onwards.

**Review by luca-heltai — DISMISSED** [review]

**Comment by luca-heltai** [comment]
The other changes here seem ok to me.

**Comment by luca-heltai** [comment]
This is now a duplicate of #36627.

**Comment by eugeneswalker** [comment]
Had to re-push update to E4S CI stack so that `dealii +cuda` is built with `~cgal cxxstd=17` following forced update. Hopefully CI passes now!

**Comment by luca-heltai** [comment]
Why ~cgal? If you add cxxstd=17, dealii should compile.

**Comment by eugeneswalker** [comment]
> Why ~cgal? If you add cxxstd=17, dealii should compile.

Oh, ok. @hppritcha commented earlier he thought that was necessary— happy to turn cgal back on!

**Review by eugeneswalker — DISMISSED** [review]

**Comment by mvandenburgh** [comment]
@spackbot run pipeline

**Review by luca-heltai — CHANGES_REQUESTED** [review]
The only required change is now to the e4s/spack.yaml file. The other have been merged already.

**Comment by eugeneswalker** [comment]
> The only required change is now to the e4s/spack.yaml file. The other have been merged already.

The E4S spack.yaml has already been updated to specify `cxxstd=17` for `dealii +cuda` as part of this PR:
* https://github.com/spack/spack/pull/37229/files#diff-06db581b14f7c17b8d47557deb8e729aef9902bba4ed1127a3be845288036869R165

Are there other changes you are suggesting?

**Comment by hppritcha** [comment]
closing this as a dup of #36627

**Pull request closed without merging**
