### PR TITLE
Backports v0.21.1

### PR DESCRIPTION
**Pull request by alalazo**
- [x] Set version to 0.21.1.dev0
- [x] #41061
- [x] #41085 
- [x] #41107
- [x] #41075
- [x] #41070
- [x] #41205
- [x] #41218
- [x] #41215
- [x] #41185
- [ ] #41133 (this is a package change we cannot backport?)
- [x] #41126
- [x] #41138
- [x] #41240
- [x] #41213
- [x] #41294
- [x] #41290
- [x] #41389
- [x] #41574
- [x] #41404
- [x] #41369
- [x] #41718
- [x] #41495
- [x] #41359
- [x] #41361
- [x] #41345
- [x] #41342
- [x] #41308
- [x] #41226
- [x] #41934
- [x] #38218
- [x] #41986
- [x] #41773
- [x] #41990 
- [x] #41989 
- [x] Update CHANGELOG and set version number to 0.21.1

### CODE REVIEW

**Comment by michaelkuhn** [comment]
It would be nice if we could also backport #41126 since the aliases example in the release notes is currently broken.

**Comment by alalazo** [comment]
@michaelkuhn Feel free to add to the list above!

**Comment by wdconinc** [comment]
Thoughts on backporting https://github.com/spack/spack/pull/41404 from people here? What's the past record of backporting security issues in packages? Does that rise to the level of concern that we want it backported? If no concern here, I'll add it to the list and merge that PR.

**Comment by becker33** [comment]
@wdconinc yes we should backport that sort of security fix.

**Pull request merged**
