### PR TITLE
Add patch for libunwind to allow building with -Wpedantic

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by haampie** [comment]
It's not built with `-Wpedantic` by default, can you explain why you need this patch?

Did you submit a PR with this fix upstream too?

**Comment by iarspider** [comment]
There is a package `igprof` (not yet in spack, I will create a MR for it once this patch is merged) that depends on `libunwind` and is built by default with `-Werror -Wpedantic`. The patch fixes warnings about "comma at the end of enum", and also fixes `error: duplicate symbol: _U_dyn_info_list`. I didn't MR this fix upstream yet.

**Comment by iarspider** [comment]
The last part of the patch (that changes the definition of `_U_dyn_info_list` from `HIDDEN` to `extern HIDDEN`) is actually fixed upstream, but in a different way (https://github.com/libunwind/libunwind/pull/166), and is actually only needed for `@:1.4.0`. I will split the patch now.

**Comment by mwkrentel** [comment]
Blech.  Can you simply turn off `-Werror` or `-Wpedantic` in igprof?
How are you able to build it now if libunwind breaks -Wpedantic?

Anyway, this seems like one example of a larger, common problem and
I'd like some guidance from spack/slack about how to handle this case.
I don't know if it's feasible to expect that every spack package
should necessarily build with -Werror.

**Comment by haampie** [comment]
I think `-Werror` is generally a mistake for release versions, since you never test all (future versions of all) compilers. So it's fine to just drop it in spack.

But it can never hurt to create an upstream PR to improve `libunwind` with the patches you've added here.

**Comment by haampie** [comment]
@iarspider can you actually use the commit (https://github.com/libunwind/libunwind/pull/166/commits/29e17d8d2ccbca07c423e3089a6d5ae8a1c9cb6e) from that PR since that's reviewed thoroughly by the libunwind people (considering the long write up there...)?

Edit: I see that it has landed in 1.5.0, is there any reason you can't use that version?

Edit 2: try `spack install -v libunwind cflags=-Wpedantic`, it gives 400 warnings because of this flag; this library is really not meant to be build with it. So I think the issue is with `igprof` not `libunwind`.

**Comment by mwkrentel** [comment]
I asked about this on spack slack general.  The feeling (including
thumbs up from Todd) is that the better solution is to remove -Werror
from igprof.  I agreee, I'd rather handle it that way.

**Pull request closed without merging**
