### PR TITLE
ascent: add patch for gcc 10 + 11

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@kwryankrattiger following up from https://github.com/Alpine-DAV/ascent/issues/860,  this patch should help with building `0.7.1`

**Comment by cyrush** [comment]
It looks like the style check is failing while installing prereqs for style check?

```
==> Error: cannot bootstrap any of the isort executables from spec "py-isort@4.3.5: %gcc target=x86_64"
```

https://github.com/spack/spack/runs/4941780887?check_suite_focus=true#step:6:11

**Comment by kwryankrattiger** [comment]
Two things I found.
 1. You have a space at the end of the patch in the package.py, so it can't be found.
 2. you need a space between the `,` and the `when` in the patch line

**Comment by cyrush** [comment]
@kwryankrattiger thanks -- I fixed these typos.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
