### PR TITLE
cuDNN: fix hashes, add v8.4.0

### LINKED ISSUE #31041: Checksum of cudnn package seems wrong or out-of-date
### Steps to reproduce

Install `cudnn@8.3.3.40-11.5` or `cudnn@8.3.2.44-11.5` on `arch=linux-debian11-zen2`.

### Error message

It reports

```
==> Fetching https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.3/local_installers/11.5/cudnn-linux-x86_64-8.3.3.40_cuda11.5-archive.tar.xz
==> Error: ChecksumError: sha256 checksum failed for /tmp/spack/spack-stage/spack-stage-cudnn-8.3.3.40-11.5-aeelev24bb4ek2q3og3n4d3cpqexjiwg/cudnn-linux-x86_64-8.3.3.40_cuda11.5-archive.tar.xz
    Expected d6ef2f6b5f3be625a7f5fba5c01bcb77902aa45e6ac068ac5a1df3fcae3a668a but got eabe96c75cf03ea4f5379894d914f1f8ae14ceab121989e84b0836d927fb7731
```

for `cudnn@8.3.3.40-11.5`, and

```
==> Fetching https://developer.download.nvidia.com/compute/redist/cudnn/v8.3.2/local_installers/11.5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz
==> Error: ChecksumError: sha256 checksum failed for /tmp/spack/spack-stage/spack-stage-cudnn-8.3.2.44-11.5-lhf3dtoyj3ctymm6q3emlvwo5wyu7ze5/cudnn-linux-x86_64-8.3.2.44_cuda11.5-archive.tar.xz
    Expected df11c96415f96d8eb6276d5593c811616342ce06eb29a83e13b503df766e5677 but got 5500953c08c5e5d1dddcfda234f9efbddcdbe43a53b26dc0a82c723fa170c457
```

for `cudnn@8.3.2.44-11.5`.

I downloaded from the URL manually and found the checksum is truly different from what is expect by Spack, and the package downloaded by myself is complete.

### Information on your system

```
* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.9.2
* **Platform:** linux-debian11-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by bvanessen**
Fixes #31041

### CODE REVIEW

**Comment by adamjstewart** [comment]
Any explanation for the hash change?

**Comment by bvanessen** [comment]
@adamjstewart No. I just tried to use a recent package and it had a bad hash.  I then downloaded the file directly from Nvidia and got a different has.  I recently ran into a situation where `spack checksum` gave me bad hashes.

**Comment by adamjstewart** [comment]
> I recently ran into a situation where spack checksum gave me bad hashes.

I don't think that's the case here since `spack checksum` doesn't work for this package. Can you reach out to NVIDIA just to make sure their servers didn't get hacked? And maybe admonish them a little if this was an intentional re-release and hash change...

**Comment by bvanessen** [comment]
@romerojosh do you have any idea of if / why the cudnn hash values have changed recently?  I pulled the ones in the PR from the Nvidia website, but presumably the ones that were there before also came from the same website.  Was there a silent re-release, or update to the tarballs?

**Comment by bvanessen** [comment]
@adamjstewart I have reached out to contacts and Nvidia to address this.

**Comment by alalazo** [comment]
Pinging also @samcmill and @fspiga for their information

**Comment by tldahlgren** [comment]
Oops.  I just caused the conflict by adding @adamjstewart 's #31034 that only has the new v8.4.0.27-11.6 version change.

**Comment by bvanessen** [comment]
> Oops. I just caused the conflict by adding @adamjstewart 's #31034 that only has the new v8.4.0.27-11.6 version change.

@tldahlgren I just fixed the conflict.

**Comment by bvanessen** [comment]
@adamjstewart @tldahlgren Can we get this merged?

**Comment by adamjstewart** [comment]
Did you get any response from NVIDIA about the hash change?

**Comment by bvanessen** [comment]
No, but it seems to be supported by other’s experiences as well.

Brian C. Van Essen
***@***.***
(w) 925-422-9300
(c) 925-290-5470

**Comment by adamjstewart** [comment]
I usually wait at least a week for a response to see why the checksums changed. Obviously we can't wait forever, but trying to avoid security vulnerabilities is always good.

**Comment by fspiga** [comment]
I will try to track down the information this week, I was OOTO the last 7 days.

**Comment by romerojosh** [comment]
Hi all,
Apologies for the slow response here. I got in contact with the right people here at NVIDIA and verified that the updated SHA256 hashes for cuDNN 8.3.2 and 8.3.3 in this PR match what was originally posted on the website. The initial set of hashes added for these cuDNN versions were not correct.

Is there a way to get some kind of automated testing of these additions in place to be sure that incorrect hashes are not added in the future?

**Review by romerojosh — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
