### PR TITLE
e4s: add hypre +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
add `hypre +rocm` to E4S stack

FYI @wspear @balay @osborn9 @ulrikeyang

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.  Hopefully it builds successfully.

**Comment by adamjstewart** [comment]
Probably worth merging all E4S CI PRs into a single PR. Btw, doc tests are broken on develop, so you'll need to rebase all PRs after those are fixed.

**Comment by tldahlgren** [comment]
> Probably worth merging all E4S CI PRs into a single PR. Btw, doc tests are broken on develop, so you'll need to rebase all PRs after those are fixed.

FWIW. If there's a chance that any of these fail I think there's value in having them in separate PRs in the sense that it is a way to allow maintainers to know that it is *their* package that has issues in the stack, at least when it is first added.

**Comment by adamjstewart** [comment]
Def makes it simpler to debug, although it's going to be fun to resolve merge constraints in all PRs since they all touch the same file. Also creates a lot of redundant CI runs...

**Comment by eugeneswalker** [comment]
> > Probably worth merging all E4S CI PRs into a single PR. Btw, doc tests are broken on develop, so you'll need to rebase all PRs after those are fixed.
> 
> FWIW. If there's a chance that any of these fail I think there's value in having them in separate PRs in the sense that it is a way to allow maintainers to know that it is _their_ package that has issues in the stack, at least when it is first added.

This was my thought. I'd rather have them all in one, but having them individually will leave a record of the failures that we can reference with maintainers and other stakeholders while allowing us to merge others.

**Comment by eugeneswalker** [comment]
> Also creates a lot of redundant CI runs...

Are you talking about the GitLab pipeline builds? Why would it create redundant runs? It should only build the affected package, in this case the package being uncommented.

**Review by tldahlgren — DISMISSED** [review]

**Comment by tldahlgren** [comment]
Looks like the package fails to build.  See https://gitlab.spack.io/spack/spack/-/jobs/3028886.

**Comment by eugeneswalker** [comment]
> Looks like the package fails to build. See https://gitlab.spack.io/spack/spack/-/jobs/3028886.

```
...
     191    In file included from device_utils.c:10:
  >> 192    ./_hypre_utilities.hpp:116:10: fatal error: 'rocsparse.h' file not 
            found
     193    #include <rocsparse.h>
     194             ^~~~~~~~~~~~~
     195    1 error generated when compiling for gfx90a.
...
```

**Comment by eugeneswalker** [comment]
Issue created here:
* https://github.com/spack/spack/issues/32194

**Comment by eugeneswalker** [comment]
Rebased on develop following resolution of https://github.com/spack/spack/issues/32194#event-7554291848 via merge of PR https://github.com/spack/spack/pull/33073#event-7554291636

**Review by wspear — APPROVED** [review]

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Pull request merged**
