### PR TITLE
hdf5: use external zlib - installed by spack

### LINKED ISSUE #46610: Installation issue: hdf5 failure with zlib - its looking for /usr/lib64/libz.a [and not the one installed by spack?]
### Steps to reproduce the issue

```console
balay@al:~/spack$ ./bin/spack spec -I hdf5
Input spec
--------------------------------
 -   hdf5

Concretized
--------------------------------
 -   hdf5@1.14.3%gcc@14.2.1~cxx~fortran~hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8 arch=linux-fedora40-aarch64
[+]      ^cmake@3.30.2%gcc@14.2.1~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-fedora40-aarch64
[+]          ^curl@8.8.0%gcc@14.2.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-fedora40-aarch64
[+]              ^nghttp2@1.63.0%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^diffutils@3.10%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^openssl@3.3.1%gcc@14.2.1~docs+shared build_system=generic certs=mozilla arch=linux-fedora40-aarch64
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[+]          ^ncurses@6.5%gcc@14.2.1~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-fedora40-aarch64
[+]      ^gcc-runtime@14.2.1%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[e]      ^glibc@2.39%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]      ^gmake@4.4.1%gcc@14.2.1~guile build_system=generic arch=linux-fedora40-aarch64
[+]      ^openmpi@5.0.5%gcc@14.2.1+atomics~cuda~debug~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~lustre~memchecker~openshmem~romio+rsh~static+vt+wrapper-rpath build_system=autotools fabrics=none romio-filesystem=none schedulers=none arch=linux-fedora40-aarch64
[+]          ^autoconf@2.72%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^m4@1.4.19%gcc@14.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-fedora40-aarch64
[+]                  ^libsigsegv@2.14%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^automake@1.16.5%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^gnuconfig@2022-09-17%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[+]          ^hwloc@2.11.1%gcc@14.2.1~cairo~cuda~gl~libudev+libxml2~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]              ^libpciaccess@0.17%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^util-macros@1.20.1%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^libxml2@2.10.3%gcc@14.2.1+pic~python+shared build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^libiconv@1.17%gcc@14.2.1 build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]                  ^xz@5.4.6%gcc@14.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]          ^libevent@2.1.12%gcc@14.2.1+openssl build_system=autotools arch=linux-fedora40-aarch64
[+]          ^libtool@2.4.7%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^findutils@4.9.0%gcc@14.2.1 build_system=autotools patches=440b954 arch=linux-fedora40-aarch64
[+]          ^numactl@2.0.18%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^openssh@9.8p1%gcc@14.2.1+gssapi build_system=autotools arch=linux-fedora40-aarch64
[+]              ^krb5@1.21.2%gcc@14.2.1+shared build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^bison@3.8.2%gcc@14.2.1~color build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^gettext@0.22.5%gcc@14.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-fedora40-aarch64
[+]                      ^tar@1.34%gcc@14.2.1 build_system=autotools zip=pigz arch=linux-fedora40-aarch64
[+]                          ^pigz@2.8%gcc@14.2.1 build_system=makefile arch=linux-fedora40-aarch64
[+]                          ^zstd@1.5.6%gcc@14.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-fedora40-aarch64
[+]              ^libedit@3.1-20240808%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^libxcrypt@4.4.35%gcc@14.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-fedora40-aarch64
[+]          ^perl@5.40.0%gcc@14.2.1+cpanm+opcode+open+shared+threads build_system=generic arch=linux-fedora40-aarch64
[+]              ^berkeley-db@18.1.40%gcc@14.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora40-aarch64
[+]              ^bzip2@1.0.8%gcc@14.2.1~debug~pic+shared build_system=generic arch=linux-fedora40-aarch64
[+]              ^gdbm@1.23%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^readline@8.2%gcc@14.2.1 build_system=autotools patches=bbf97f1 arch=linux-fedora40-aarch64
[+]          ^pmix@5.0.3%gcc@14.2.1~munge~python~restful build_system=autotools arch=linux-fedora40-aarch64
[+]      ^pkgconf@2.2.0%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]      ^zlib-ng@2.2.1%gcc@14.2.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-fedora40-aarch64

```

### Error message

<details><summary>Error message</summary>

<pre>
-- Looking for MPI_Type_size_x - found
CMake Error at /usr/lib64/cmake/ZLIB/ZLIB.cmake:81 (message):
  The imported target "ZLIB::zlibstatic" references the file

     "/usr/lib64/libz.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/ZLIB/ZLIB.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
  CMakeFilters.cmake:77 (find_package)
  CMakeLists.txt:852 (include)

-- Configuring incomplete, errors occurred!

</pre></details>

### Information on your system

```console
balay@al:~/spack$ ./bin/spack debug report
* **Spack:** 0.23.0.dev0 (00fae6dd79f40dc322b3c1149f7460f527f83d44)
* **Python:** 3.12.6
* **Platform:** linux-fedora40-aarch64
```

### Additional information

[spack-build-env.txt](https://github.com/user-attachments/files/17166464/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/17166465/spack-build-out.txt)

cc: @brtnfld  @byrnHDF  @gheber @hyoklee  @lkurz  @lrknox

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by balay**
Fixes:
```
CMake Error at /usr/lib64/cmake/ZLIB/ZLIB.cmake:81 (message):
  The imported target "ZLIB::zlibstatic" references the file

     "/usr/lib64/libz.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/ZLIB/ZLIB.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
  CMakeFilters.cmake:77 (find_package)
  CMakeLists.txt:852 (include)
```
Fixes: https://github.com/spack/spack/issues/46610

### CODE REVIEW

**Review by hyoklee — APPROVED** [review]

**Comment by balay** [comment]
https://gitlab.spack.io/spack/spack/-/jobs/12694063

```
>> 340    configure: error: HDF5 was not built with zlib, which is required. 
            Rebuild HDF5 with zlib.
```

Ah - so this change is not really the fix for the current failure :(

**Comment by haampie** [comment]
I think they're not using https://cmake.org/cmake/help/latest/module/FindZLIB.html but expect cmake config files, which zlib-ng does not have (but the system does have).

Would be inclined to think it's a mistake by hdf5.

**Comment by hyoklee** [comment]
Hi,
 
 Upcoming release has two new options [1] related to zlib-ng:
 
```
 option (HDF5_USE_ZLIB_NG "Use zlib-ng library as zlib library" OFF)
 option (HDF5_USE_ZLIB_STATIC "Find static zlib library" OFF)
```

I haven't tested them yet but I hope they can improve zlib-ng integration experience.

[1] https://github.com/HDFGroup/hdf5/blob/hdf5_1_14_5/CMakeFilters.cmake#L12

**Comment by haampie** [comment]
Still have not checked in detail, but they use `find_package (ZLIB ... COMPONENTS ...)`, and builtin [`FindZLIB`](https://cmake.org/cmake/help/latest/module/FindZLIB.html) does [not have any `COMPONENTS`](https://github.com/Kitware/CMake/blob/80d16018fa909ff5713f292fc8baba7510c2a3ee/Modules/FindZLIB.cmake#L90-L96), so it will always look for a CMake config file that does define those components.

Given that zlib has multiple build systems, it's a mistake on HDF5's side to expect it to exist.

**Comment by haampie** [comment]
I've commented on an existing issue: https://github.com/HDFGroup/hdf5/issues/4614#issuecomment-2383937218

@balay would you wanna submit a patch that removes the `COMPONENTS ...` bit from the `find_package` call here:

https://github.com/HDFGroup/hdf5/blob/hdf5_1_14_5/CMakeFilters.cmake#L12

could see if that solves the issue.

**Comment by balay** [comment]
> @balay would you wanna submit a patch that removes the COMPONENTS ... bit 

Thanks! This change gets my build working!

**Review by haampie — APPROVED** [review]
Thanks! I've updated the range (issue exists already for a decade). Surfaces only now because Fedora 40 started using zlib-ng built with CMake.

**Review by hyoklee — APPROVED** [review]

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by jrood-nrel** [comment]
Doesn't this mean `hdf5` should now depend on `zlib`?

**Comment by jrood-nrel** [comment]
I do not have `zlib` in my DAG and I see this error now:
```
-- Configuring done (10.5s)
CMake Error at /whatever/linux-rocky8-zen2/gcc-12.3.0/hdf5-1.14.5-fbemdibpua5saohafdyarebawy2wchwl/cmake/hdf5-targets.cmake:59 (set_target_properties):
  The link interface of target "hdf5-static" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /whatever/linux-rocky8-zen2/gcc-12.3.0/hdf5-1.14.5-fbemdibpua5saohafdyarebawy2wchwl/cmake/hdf5-config.cmake:174 (include)
  /whatever/linux-rocky8-zen2/gcc-12.3.0/cmake-3.30.5-evin3st3pg5fu3lxk2i6mm3n6idldh6l/share/cmake-3.30/Modules/FindHDF5.cmake:513 (find_package)
  /whatever/linux-rocky8-zen2/gcc-12.3.0/h5z-zfp-1.1.1-hgb2kh2qvnjt466k7rcmefvqqmsrbqlg/lib/cmake/h5z_zfp/h5z_zfp-config.cmake:40 (find_package)
  submods/amrex/Tools/CMake/AMReXThirdPartyLibraries.cmake:54 (find_package)
  submods/amrex/Src/CMakeLists.txt:49 (include)
```

**Comment by balay** [comment]
@jrood-nrel are you sure your failure is related to this PR change [does your build work with the spack snapshot prior to this change?]

> Doesn't this mean hdf5 should now depend on zlib?

This dependency always existed - this PR didn't change this. Currently its listed in hdf5/package.py as:
```
    depends_on("zlib-api")
```
> I do not have zlib in my DAG
```
$ git grep provides var/spack/repos/builtin/packages |grep zlib-api
var/spack/repos/builtin/packages/zlib-ng/package.py:    provides("zlib-api", when="+compat")
var/spack/repos/builtin/packages/zlib/package.py:    provides("zlib-api")
```
Are you sure neither of these packages are in your DAG?

And is this error with `amrex+hdf5`? This works for me  though..
```
balay@pj01:~/spack.x$ ./bin/spack spec amrex+hdf5 |grep zlib
 -           ^zlib-ng@2.2.1%gcc@14.2.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-fedora40-skylake
```

**Comment by jrood-nrel** [comment]
Ah, you're right. I was able to spend some more time on this and I jumped to a conclusion. It looks like I have hdf5@1.14.5 anyway which doesn't even use the patch. So I will have to do some more research on how this error has appeared. Thanks for the detailed reply. Sorry about that.

**Comment by jrood-nrel** [comment]
It works with `hdf5@1.14.3`, so `1.14.5` is doing something to cause this issue for me.

**Pull request merged**
