### PR TITLE
petsc,py-petsc4py,slepc,py-slepc4py: add version 3.20.0

### PR DESCRIPTION
**Pull request by balay**
Update petsc, petsc4py download URL

Simplify dependencies

### CODE REVIEW

**Review by joseeroman — APPROVED** [review]

**Review by eugeneswalker — APPROVED** [review]

**Comment by haampie** [comment]
@balay / @barrysmith / @jedbrown looks like this PR was merged while rocm was bumped here #39673, so we missed a breaking change (yes we could use a merge queue...).

There's a breaking change in hipsparse 5.6.1 (well, it's a ton of reverts of reverts to the point I'm not sure what is considered correct API...), see https://github.com/ROCmSoftwarePlatform/hipSPARSE/commit/2582c397a24f12314abf3e0c709aea4c996e88e7


Bottom-line is the signature of `hipsparseSpSV_solve` changed in rocm 5.6.1.

So, that means petsc is (only?) compatible with the incorrect signature of that function?

What should we do? Add a conflict? Is there a patch?

**Comment by balay** [comment]
petsc@3.20.0 has this this fix https://gitlab.com/petsc/petsc/-/merge_requests/6896/diffs - it still fails?

cc: @jczhang07

**Comment by haampie** [comment]
Looks like that should fix it

**Comment by haampie** [comment]
Looks like petsc detects rocm 5.6.1 as 5.6.0

**Comment by balay** [comment]
```
balay@petsc-gpu-02:/opt$ cat ./rocm-5.6.0/include/hip/hip_version.h
// Auto-generated by cmake

#ifndef HIP_VERSION_H
#define HIP_VERSION_H

#define HIP_VERSION_MAJOR 5
#define HIP_VERSION_MINOR 6
#define HIP_VERSION_PATCH 31061
#define HIP_VERSION_GITHASH "8c743ae5d"
#define HIP_VERSION_BUILD_ID 0
#define HIP_VERSION_BUILD_NAME ""
#define HIP_VERSION    (HIP_VERSION_MAJOR * 10000000 + HIP_VERSION_MINOR * 100000 + HIP_VERSION_PATCH)

#define __HIP_HAS_GET_PCH 1

#endif

```

API changes in a patch release :( 

and the patch release numbers don't match [between the includes and the releases] :(

**Comment by haampie** [comment]
:)

**Comment by balay** [comment]
perhaps limit the conflict to `5.6.1`?

Also add in `rocm@5.7.0` to spack?

**Comment by jczhang07** [comment]
@balay @haampie 
rocm-5.6.0 (hipsparse-2.3.6) introduced an incorrect `hipsparseSpSV_solve` API,  and then rocm-5.6.1 (hipsparse-2.3.7) corrected it, see https://github.com/ROCmSoftwarePlatform/hipSPARSE/releases/tag/rocm-5.6.1

In petsc, we need to somehow map the HIP version in the following format to 5.6.0.  My observation is we can do it via `HIP_VERSION_PATCH%10 -1`  to get the canonical patch number. At least, it is true for all rocm versions on Frontier.
```
#define HIP_VERSION_MAJOR 5
#define HIP_VERSION_MINOR 6
#define HIP_VERSION_PATCH 31061
```

**Pull request merged**
