### PR TITLE
Ibm magma changes

### PR DESCRIPTION
**Pull request by serbanmaerean**
New package file for MAGMA.  Built it on ppc64le with XL and gcc compilers.  I don't have an x86 machine.

### CODE REVIEW

**Comment by adamjstewart** [comment]
See comments on #3273. Most of them still apply.

**Comment by alalazo** [comment]
@serbanmaerean Do you mind if we close this branch and reopen #3273 ? In that way we don't have to chase comment among multiple PRs :smile:

**Comment by serbanmaerean** [comment]
@alalazo The other PR for magma that was closed is not mine, I don't seem to be able to reopen it.

**Comment by alalazo** [comment]
@serbanmaerean I am only guessing, so please correct me if I am wrong on that. From what I can infer you, @eklee15 and @muffgaga are part of the same group and you are contributing back (thanks!) recipes for a few packages you have modified / added.

What you guys can do is to create a public "organization" and be all part of it. Then you can start a PR from your organization fork, instead of your "personal" fork. In this way you will have a global view of what you as a group have submitted (because you will have an organization dashboard), and any of you can in principle push modifications on PR branches.

**Comment by eklee15** [comment]
@serbanmaerean I reopend #3297

**Comment by serbanmaerean** [comment]
@eklee15 How can I merge this PR with #3273?  Can we keep this for now and maybe create an organization and use a single fork?

**Comment by eklee15** [comment]
@serbanmaerean I have incorporated all of your changes in #3273. Please check it and close this PR. 
@alalazo and @serbanmaerean Yes, we can use an organization repository from next PR.

**Comment by adamjstewart** [comment]
Closing in favor of #3273.

**Pull request closed without merging**
