### PR TITLE
fix config.guess patch for ppc64le

### PR DESCRIPTION
**Pull request by lee218llnl**
The _do_patch_config_guess() function will already throw an exception upon error.

### CODE REVIEW

**Comment by tgamblin** [comment]
@adamjstewart @lee218llnl: I think you need both.  `config.guess` is only invoked when `configure` runs, so you need it as a normal part of `patch()`, because `autoreconf` is not always run.  But `autoreconf` also *overwrites* `config.guess`, so you may need a refresh there, as well.

@lee218llnl: It might make sense to note a min version of `autoconf` beyond which we wouldn't replace `config.guess`.  If we're running `autoreconf`, the package needs to depend on `autoconf`, so you can check this.  Is that possible or is `ppc64le` still too special?

**Comment by adamjstewart** [comment]
`autoreconf` is always run, but sometimes it exits immediately. Right now we're always running it twice. Does `config.guess` influence `autoreconf`? If not, then we can get rid of the patch.

**Comment by lee218llnl** [comment]
@tgamblin It looks like the PPC64LE fix for config.guess came in automake 1.13.4. `config.guess -v` shows a 2013-06-10 build date. Did you just want me to note that as a comment?

@adamjstewart I'm not well versed in how autoconf/autoreconf works, so I don't think I'm qualified to answer your question. Is there someone else we should consult about this?

**Comment by tgamblin** [comment]
> autoreconf is always run, but sometimes it exits immediately.

Given this, I guess we do not need the `patch()`.  As long as it's always run after the `autoreconf` build step.  So @lee218llnl I think you can remove the call in `patch()`.

@lee218llnl:
> It looks like the PPC64LE fix for config.guess came in automake 1.13.4. config.guess -v shows a 2013-06-10 build date. Did you just want me to note that as a comment?

I think it's worth at least noting.  The thing I was worried about is that our `config.guess` ends up being older than what's provided by `autotools` and fails, so I was inclined to say we should put in a newer one than 2013.  But you *do* only replace it if it fails, so it should at least not cause any problems.

**Comment by lee218llnl** [comment]
@tgamblin @adamjstewart let me know if the latest commit addresses your concerns.

**Comment by lee218llnl** [comment]
@tgamblin does this look good to merge? Richard H. just tripped on this and it would be nice to just have him do a pull of develop to resolve it. I had him hand modify his source in the meantime.

**Comment by becker33** [comment]
We may eventually want to only patch for versions that require it, but this works for now.

**Pull request merged**
