### PR TITLE
e4s ci: add hdf5-vol-daos

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `hdf5-vol-daos` to E4S CI stacks

CC @hyoklee @wspear

### CODE REVIEW

**Review by hyoklee — APPROVED** [review]

**Review by wspear — DISMISSED** [review]

**Comment by hyoklee** [comment]
@eugeneswalker , I finished patching in Spack to address GitLab CI failures.
I'd appreciate if you could merge the Spack PRs and run the test again.

**Comment by eugeneswalker** [comment]
> @eugeneswalker , I finished patching in Spack to address GitLab CI failures. I'd appreciate if you could merge the Spack PRs and run the test again.

Just approved all your patches, merged one, and turned on auto-merge on the others. I will shepherd those across the finish line. Once those go through I will rebase this PR on that and we will be set. Thanks!

**Comment by hyoklee** [comment]
@eugeneswalker , I just realized that dpdk fails to build although I tried the latest version. In this case, what are the available options for E4S and hdf5-vol-daos? 

1. Merge despite failure.
2. Wait until DPDK team fixes something and make another release.
...

See also: https://github.com/DPDK/dpdk/pull/58

P.S. Intel OneAPI works fine.

**Comment by eugeneswalker** [comment]
> @eugeneswalker , I just realized that dpdk fails to build although I tried the latest version. In this case, what are the available options for E4S and hdf5-vol-daos?

Usually in this situation we would:
1. Consider `hdf5-vol-daos` a part of E4S, albeit one that has build issues in the CI environment for the time being
2. Keep this PR open until the build issue is resolved, at which point we incorporate the fixes into this PR and merge

I just re-based this PR on all the now-merged PRs you made this morning, so let us see if we have better results on the next CI run.

**Comment by eugeneswalker** [comment]
It looks like the only failing package is `dpdk` as you point out above:
* [(specs) dpdk/yaklmmf 23.03 gcc@=11.1.0 linux-ubuntu20.04-x86_64_v3 E4S](https://gitlab.spack.io/spack/spack/-/jobs/7133383)
```
...
 >> 2745    FAILED: lib/librte_vhost.a.p/vhost_vhost_user.c.o
     2746    /builds/spack/spack/lib/spack/env/gcc/gcc -Ilib/librte_vhost.a.p -
             Ilib -I../spack-src/lib -Ilib/vhost -I../spack-src/lib/vhost -I. -
             I../spack-src -Iconfig -I../spack-src/config -Ilib/eal/include -I.
             ./spack-src/lib/eal/include -Ilib/eal/linux/include -I../spack-src
             /lib/eal/linux/include -Ilib/eal/x86/include -I../spack-src/lib/ea
             l/x86/include -Ilib/eal/common -I../spack-src/lib/eal/common -Ilib
             /eal -I../spack-src/lib/eal -Ilib/kvargs -I../spack-src/lib/kvargs
              -Ilib/metrics -I../spack-src/lib/metrics -Ilib/telemetry -I../spa
             ck-src/lib/telemetry -Ilib/ethdev -I../spack-src/lib/ethdev -Ilib/
             net -I../spack-src/lib/net -Ilib/mbuf -I../spack-src/lib/mbuf -Ili
             b/mempool -I../spack-src/lib/mempool -Ilib/ring -I../spack-src/lib
             /ring -Ilib/meter -I../spack-src/lib/meter -Ilib/cryptodev -I../sp
             ack-src/lib/cryptodev -Ilib/rcu -I../spack-src/lib/rcu -Ilib/hash 
             -I../spack-src/lib/hash -Ilib/pci -I../spack-src/lib/pci -Ilib/dma
             dev -I../spack-src/lib/dmadev -fdiagnostics-color=always -D_FILE_O
             FFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O3 -include 
             rte_config.h -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral
              -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wn
             ested-externs -Wold-style-definition -Wpointer-arith -Wsign-compar
             e -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-pack
             ed-member -Wno-packed-not-aligned -Wno-missing-field-initializers 
             -Wno-zero-length-bounds -D_GNU_SOURCE -fPIC -march=native -DALLOW_
             EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -DVHO
             ST_GCC_UNROLL_PRAGMA -fno-strict-aliasing -DRTE_LOG_DEFAULT_LOGTYP
             E=lib.vhost -MD -MQ lib/librte_vhost.a.p/vhost_vhost_user.c.o -MF 
             lib/librte_vhost.a.p/vhost_vhost_user.c.o.d -o lib/librte_vhost.a.
             p/vhost_vhost_user.c.o -c ../spack-src/lib/vhost/vhost_user.c
     2747    In file included from ../spack-src/lib/vhost/iotlb.h:10,
     2748                     from ../spack-src/lib/vhost/vhost_user.c:49:
     2749    ../spack-src/lib/vhost/vhost.h:652:50: warning: ISO C does not per
             mit named variadic macros [-Wvariadic-macros]
     2750      652 | #define VHOST_LOG_CONFIG(prefix, level, fmt, args...)     
                   \
     2751          |                                                  ^~~
     2752    ../spack-src/lib/vhost/vhost.h:656:48: warning: ISO C does not per
             mit named variadic macros [-Wvariadic-macros]
     2753      656 | #define VHOST_LOG_DATA(prefix, level, fmt, args...)       
                   \
     2754          |                                                ^~~
  >> 2755    ../spack-src/lib/vhost/vhost_user.c:65:32: error: array size missi
             ng in 'vhost_message_handlers'
     2756       65 | static vhost_message_handler_t vhost_message_handlers[];
     2757          |                                ^~~~~~~~~~~~~~~~~~~~~~
     2758    In file included from ../spack-src/lib/vhost/iotlb.h:10,
     2759                     from ../spack-src/lib/vhost/vhost_user.c:49:
```

Do you know what the issue is here? Is there no version that will work? You said it builds with OneAPI -- what other compilers does it build with? Maybe we can patch it ourselves here, with Spack.

**Comment by hyoklee** [comment]
@eugeneswalker , thank you so much for your reply.

The issue is that gcc doesn't allow `array[]` without real size.

Please see my quick hack to make it pass:

https://github.com/DPDK/dpdk/pull/58/files

However, I don't think we can use the above for a quick Spack patch.

Today, I was looking for a way to specify gcc compiler options to allow [] but couldn't find.
Do you know any compiler option to relax gcc to allow `array[]`?

**Comment by eugeneswalker** [comment]
> https://github.com/DPDK/dpdk/pull/58/files
> 
> However, I don't think we can use the above for a quick Spack patch.

You say you think we can't use this for a quick patch -- is that because it impairs the function of the code? I.e. it will let it compile but won't work properly? Or, some other reason? If the code functions properly, we could tell Spack to apply your fix to the source before it performs the build -- we've done this before. But if you think this is not a good idea, we can wait for a better option.

> Do you know any compiler option to relax gcc to allow array[]?

I will check with a colleague who may know.

**Comment by hyoklee** [comment]
@eugeneswalker, exactly! I could build DAOS and hdf5-vol-daos using this hack but I'm not 100% sure that it will work at the HPC scale. I'm still intrigued why DPDK team neither merges the PR nor gives comments on it.

If we can't find a compiler option, let's make a quick patch and move on. 

Again, thank you for your help by asking your colleagues!

**Comment by hyoklee** [comment]
@eugeneswalker , if your colleague can't figure out the right gcc compiler option, let's just push into E4S as is. That is, the option 1:

```
1. Consider hdf5-vol-daos a part of E4S, albeit one that has build issues in the CI environment for the time being
```

@brtnfld , please let us know if you don't like this option.

**Comment by eugeneswalker** [comment]
> Again, thank you for your help by asking your colleagues!

I asked around and was not able to find an option that would allow this. My casual impression is that someone who knows this code region should be able to update it to work with GCC without compromising functionality -- can someone on your team who knows this region take a look?

**Comment by hyoklee** [comment]
@eugeneswalker , I'm pinging the original hdf5-daos-vol developer @soumagne and the current developer @jhendersonHDF to see if they can take a look at it. If they don't respond to this GH PR within a week, please merge as broken.

**Comment by jhendersonHDF** [comment]
Hi all,

since I don't work on DPDK, I'm not familiar enough with it to make much of a comment on a good fix for this issue. That said, it looks like the code in question has a bit of an ordering issue. Starting at https://git.dpdk.org/dpdk/tree/lib/vhost/vhost_user.c#n2831 and following down to line 2867, the `vhost_message_handlers` array would get declared with a correct and non-empty size at that point. Since those macros appear to depend on previous functions having been already declared, the variable doesn't get declared until after the declarations for all those functions. However, some of those functions appear to use the `validate_msg_fds` function at https://git.dpdk.org/dpdk/tree/lib/vhost/vhost_user.c#n91 which makes use of the `vhost_message_handlers` array. I'm guessing that declaring the array early on with an empty size acts as a forward declaration for some compilers as long as certain compiler flags aren't used.

It's probably worth filing an issue against DPDK or creating a PR to fix the issue, but patching in a random fixed size for the array variable may cause functionality issues if that size doesn't match the number of entries that the array variable is actually created with further down in the code.

**Review by hyoklee — APPROVED** [review]

**Review by hyoklee — APPROVED** [review]

**Review by wspear — APPROVED** [review]

**Comment by hyoklee** [comment]
Thank you so much, @eugeneswalker !

**Pull request merged**
