### PR TITLE
New package: py-bitshuffle

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot maintainers

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@scottwittenburg Here's a case where @spackbot couldn't push, but the PR submitter gave maintainers permissions to edit the branch

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by adamjstewart** [comment]
@qwertos idk why spackbot isn't working, can you run `spack style --fix` locally and push the changes?

**Comment by alalazo** [comment]
@spackbot fix style

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
