### PR TITLE
ML CI: variants are now required

### PR DESCRIPTION
**Pull request by adamjstewart**
Thanks @alalazo for informing me that this feature works now. See #34302 for motivation.

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Two build issues:
- A patch cannot be applied: https://gitlab.spack.io/spack/spack/-/jobs/10151745
- A timeout :cry: https://gitlab.spack.io/spack/spack/-/jobs/10150662

**Comment by adamjstewart** [comment]
@renjithravindrankannath  @srekolam can you take a look at the miopen-hip patch issue?

**Comment by srekolam** [comment]
> @renjithravindrankannath @srekolam can you take a look at the miopen-hip patch issue?

i think this PR will solve the issue with respect to miopen-hip. 
https://github.com/spack/spack/pull/42637

**Comment by adamjstewart** [comment]
Composable kernel is now failing to build for unknown reasons @srekolam @afzpatel

**Comment by afzpatel** [comment]
> Composable kernel is now failing to build for unknown reasons @srekolam @afzpatel

I submitted a pr to fix an issue with the GPU_TARGETS cmake arg. I think this might fix the issue with composable-kernel.
https://github.com/spack/spack/pull/42924

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Next bug fixed by #42938. Can't believe how many bugs are discovered just by running the entire pipeline. Not sure why CI doesn't catch them earlier.

**Comment by adamjstewart** [comment]
This PR has already uncovered one issue. I was under the impression that we were testing `py-tensorflow+rocm` in CI but we are actually not. If we do, we find that it doesn't actually build correctly.

**Comment by srekolam** [comment]
Adam, can 

> This PR has already uncovered one issue. I was under the impression that we were testing `py-tensorflow+rocm` in CI but we are actually not. If we do, we find that it doesn't actually build correctly.

Adam, if you remember I had submitted  this PR https://github.com/spack/spack/pull/38520 . It worked with rocm in central location but the CI failed ..so it was not merged.
.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
