### PR TITLE
CI: add coverage on Windows

### PR DESCRIPTION
**Pull request by alalazo**
Modifications:
- [x] Add and upload coverage data for unit-tests on Windows

### CODE REVIEW

**Comment by alalazo** [comment]
@johnwparent @scheibelp Am I doing something clearly wrong here for Windows (I am trying to generate a coverage file and upload it to `codecov`)? I have no experience with that platform, and currently no access to it, so I am even wondering how can I check what is on the filesystem after the unit-tests finished.

**Comment by trws** [comment]
Perhaps we still need the `coverage combine -a` and `coverage xml`?

**Comment by alalazo** [comment]
> Perhaps we still need the coverage combine -a and coverage xml?

Maybe we need only `coverage.xml`? I can try to have a look at that, thanks for spotting that difference!

**Comment by trws** [comment]
I'll try to find some time to poke at this, my windows box at home is back up so I can probably test it.

**Comment by trws** [comment]
I hope you don't mind my popping in a commit, but since everything just worked locally, and I noticed the odd up a directory positioning of the shell on windows I thought this was worth a shot.

**Comment by alalazo** [comment]
@trws Thanks for the fix, I think we're almost there. Now we just need to remove the recursive link we have in the docs before using `codecov` actions.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
