### PR TITLE
r-wru: Add `R` package `wru`

### PR DESCRIPTION
**Pull request by jgaeb**
Note: This package depends on `r-piggyback` (#39932) and `r-pl94171` (#39926), and currently contains commits from both of them. Once those commits have been merged, I'll rewrite the history on this branch so that it branches directly off of `develop` instead of containing commits from those branches as well.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage and 16 version sha256 for `r-wru`.

**Comment by tldahlgren** [comment]
I can install the software for this PR but it did re-install `r-piggyback` (but not `r-pl94171`) even though I'd already installed it for the same clone.

Please update the branch.

**Comment by jgaeb** [comment]
@tldahlgren Just confirming that I rewrote the branch history so that it does not include the commits adding `r-piggyback` and `r-pl94171`. I think this should fix the issue? (Although, I'm a novice with `spack`, so my understanding of when / how it rebuilds packages could be wrong.)

**Comment by tldahlgren** [comment]
> @tldahlgren Just confirming that I rewrote the branch history so that it does not include the commits adding `r-piggyback` and `r-pl94171`. I think this should fix the issue? (Although, I'm a novice with `spack`, so my understanding of when / how it rebuilds packages could be wrong.)

Yes, the gist was to not include the other two packages in this PR.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
