### PR TITLE
[do not merge] absolute sonames ci test

### PR DESCRIPTION
**Pull request by haampie**
Build the universe for #31948.

- hook: absolutify_elf_sonames
- poke gitlab/aws to build the world

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
Can you link the PR this is building for in case people want to look at it?

**Comment by haampie** [comment]
https://github.com/spack/spack/pull/31948

**Comment by haampie** [comment]
Pretty confident that this "just works", since rpaths are not removed, relocation of dt_needed and dt_soname is covered by find & replace, and libdl does not expose any info about shared libraries other than symbols.

Only issue is stub libs, we might need a mechanism to exclude those.

**Pull request closed without merging**
