### PR TITLE
python: fix patch issue for 2.7.X, 3.7.X

### PR DESCRIPTION
**Pull request by xjrc**
The changes in this pull request fix the `python` package patching issues documented in  #17128. I've verified that the following variants install using `%clang@9.0.0 cflags="-std=gnu11 -fPIC" cxxflags="std=c++11 -fPIC" cppflags= "-fPIC"` in build environment `arch=linux-rhel7-broadwell`:

- `py-kiwisolver ^py-setuptools@41.4.0 ^python@2.7.8`
- `py-kiwisolver ^py-setuptools@41.4.0 ^python@2.7.16`
- `py-kiwisolver ^py-setuptools@41.4.0 ^python@2.7.17`
- `py-kiwisolver ^py-setuptools@41.4.0 ^python@2.7.18`
- `py-kiwisolver ^python@3.6.8`
- `py-kiwisolver ^python@3.7.2`
- `py-kiwisolver ^python@3.7.3`
- `py-kiwisolver ^python@3.7.4`
- `py-kiwisolver ^python@3.7.7`
- `py-kiwisolver ^python@3.8.3`

### CODE REVIEW

**Comment by xjrc** [comment]
Tagging @eugeneswalker, @scottwittenburg.

**Comment by eugeneswalker** [comment]
I am testing this now. Will report results back when complete. Thanks!

**Comment by adamjstewart** [comment]
If you really want to be thorough you can do something like:
```bash
for version in $(spack versions -s python)
do
    spack patch python@version
done
```

**Comment by eugeneswalker** [comment]
The variant of `python@3.7.3` that was failing yesterday is now building fine on all the platforms I can test (amd64 and ppc64le):
* RHEL 7
* Ubuntu 18.04
* Ubuntu 20.04
* CentOS 7

**Comment by scottwittenburg** [comment]
Thanks to @xjrc for tackling this so quickly and to @eugeneswalker for verifying the fix so thoroughly across platforms!

**Comment by xjrc** [comment]
@adamjstewart: I did what you suggested and found two more uncovered versions: `@3.7.0` and `@3.7.1` (the `@3.7.2` patch covers `@6.8.3` but not the versions in between, which is probably a product of backports). I've excluded these versions from patching with my most recent commit and all the Python versions can be patched now using your test script in my environment.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
