### PR TITLE
test oneapi 2024.1.2

### PR DESCRIPTION
**Pull request by rscohn2**
For testing only, no need to review.

### CODE REVIEW

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
@spackbot help

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
@eugeneswalker: The container was built with: https://github.com/UO-OACISS/e4s/pull/4
I am using apt to install oneapi instead of relying on a base container. I don't understand the error, can you look?
https://gitlab.spack.io/spack/spack/-/jobs/11456109
The hpckit container might have more ubuntu packages pre-installed, but it looks like the e4s Dockerfile already uses apt to install everything it needs.

**Comment by eugeneswalker** [comment]
CI failing because `spack compiler find` doesn't discover OneAPI compiler in the new container. 
* [ e4s-oneapi-generate ](https://gitlab.spack.io/spack/spack/-/jobs/11456109)


```
$> docker run -it --rm rscohn2/ubuntu22.04-runner-amd64-oneapi-2024.1.0:2024.05.31

root@7f27cc771831:/# git clone https://github.com/spack/spack
Cloning into 'spack'...
remote: Enumerating objects: 551583, done.
remote: Counting objects: 100% (837/837), done.
remote: Compressing objects: 100% (487/487), done.
remote: Total 551583 (delta 365), reused 608 (delta 229), pack-reused 550746
Receiving objects: 100% (551583/551583), 183.16 MiB | 38.23 MiB/s, done.
Resolving deltas: 100% (259506/259506), done.

root@7f27cc771831:/# which icx

root@7f27cc771831:/# . spack/share/spack/setup-env.sh

root@7f27cc771831:/# spack compiler find
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    gcc@11.4.0
==> Compilers are defined in the following files:
    /root/.spack/linux/compilers.yaml
```

The way the old image was made, deriving it from the hpckit image, the environment was already set up so that Spack could discover OneAPI compiler automatically.

Should we update the new iteration container so that effectively this is by default:
```
root@7f27cc771831:/# . /opt/intel/oneapi/setvars.sh

:: initializing oneAPI environment ...
   bash: BASH_VERSION = 5.1.16(1)-release
   args: Using "$@" for setvars.sh arguments:
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dpl -- latest
:: mpi -- latest
:: tbb -- latest
:: oneAPI environment initialized ::

root@7f27cc771831:/# spack compiler find
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    oneapi@2024.1.2
==> Compilers are defined in the following files:
    /root/.spack/linux/compilers.yaml
```

What do you think? At minimum it seems we need to make sure icx/icpx/ifx are in the default PATH for our CI image.

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
Closing. gitlab tests are passing now.

**Pull request closed without merging**
