### PR TITLE
Cray support: use linux platform for newer craype versions

### PR DESCRIPTION
**Pull request by becker33**
Newer versions of the CrayPE for EX systems have standalone compiler executables for CCE and compiler wrappers for Cray MPICH. With those, we can treat the cray systems as part of the linux platform rather than having a separate cray platform.

This PR:
- [x] Changes cray platform detection to ignore EX systems with Craype version 21.10 or later
- [x] Changes the cce compiler to be detectable via paths
- [x] Changes the spack compiler wrapper to understand the executable names for the standalone cce compiler (`craycc`, `crayCC`, `crayftn`).

### CODE REVIEW

**Comment by haampie** [comment]
FWIW, there are still many issues and unresolved tickets with Cray PE's without modules. 

<details>

<summary>This is 21.12:</summary>

```
$ ./libtree_x86_64 /opt/cray/pe/mpich/8.1.13/ofi/gnu/9.1/lib/libmpich.so /opt/cray/pe/mpich/8.1.13/ofi/nvidia/20.7/lib/libmpich.so /opt/cray/pe/mpich/8.1.13/ofi/cray/10.0/lib/libmpich.so /opt/cray/pe/mpich/8.1.13/ofi/aocc/3.0/lib/libmpich.so /opt/cray/pe/mpich/8.1.13/ofi/intel/19.0/lib/libmpich.so
libmpi_gnu_91.so.12 
├── libatomic.so.1 [runpath]
├── libquadmath.so.0 [runpath]
├── libgfortran.so.5 [runpath]
│   └── libquadmath.so.0 [runpath]
├── libpmi.so.0 [ld.so.conf]
│   └── libpmi2.so.0 [ld.so.conf]
│       └── libpals.so.0 [ld.so.conf]
├── libpmi2.so.0 [ld.so.conf]
├── librt.so.1 [default path]
└── libfabric.so.1 not found
    ┊ Paths considered in this order:
    ┊ 1. rpath is skipped because runpath was set
    ┊ 2. LD_LIBRARY_PATH was not set
    ┊ 3. runpath:
    ┊    /opt/cray/pe/gcc-libs
    ┊    /opt/cray/gcc-libs
    ┊ 4. ld config files:
    ┊    /usr/local/lib64
    ┊    /usr/local/lib
    ┊    /opt/cray/pe/lib64
    ┊    /opt/cray/pe/lib64/cce
    ┊    /opt/cray/xpmem/default/lib64
    ┊ 5. Standard paths:
    ┊    /lib
    ┊    /lib64
    ┊    /usr/lib
    ┊    /usr/lib64
Error [/opt/cray/pe/mpich/8.1.13/ofi/gnu/9.1/lib/libmpich.so]: Not all dependencies were found
libmpi_nvidia.so.12 
├── libatomic.so.1 [runpath]
├── libpmi2.so.0 [runpath]
│   └── libresolv.so.2 [default path]
├── libpmi.so.0 [runpath]
│   ├── libslurm_pmi.so [runpath]
│   │   └── libresolv.so.2 [default path]
│   └── libresolv.so.2 [default path]
├── librt.so.1 [default path]
├── libfabric.so.1 not found
├── libnvomp.so not found
├── libnvc.so not found
├── libnvcpumath.so not found
└── libnvf.so not found
    ┊ Paths considered in this order:
    ┊ 1. rpath is skipped because runpath was set
    ┊ 2. LD_LIBRARY_PATH was not set
    ┊ 3. runpath:
    ┊    /opt/cray/pe/gcc-libs
    ┊    /opt/cray/gcc-libs
    ┊    /workspace/pebuildenv/opt/nvidia/Linux_x86_64/20.7/compilers/lib
    ┊    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64
    ┊ 4. ld config files:
    ┊    /usr/local/lib64
    ┊    /usr/local/lib
    ┊    /opt/cray/pe/lib64
    ┊    /opt/cray/pe/lib64/cce
    ┊    /opt/cray/xpmem/default/lib64
    ┊ 5. Standard paths:
    ┊    /lib
    ┊    /lib64
    ┊    /usr/lib
    ┊    /usr/lib64
Error [/opt/cray/pe/mpich/8.1.13/ofi/nvidia/20.7/lib/libmpich.so]: Not all dependencies were found
libmpi_cray.so.12 
├── libpmi2.so.0 [ld.so.conf]
├── libpmi.so.0 [ld.so.conf]
├── libcsup.so.1 [ld.so.conf]
│   └── librt.so.1 [default path]
├── libfi.so.1 [ld.so.conf]
│   ├── libmodules.so.1 [runpath]
│   │   ├── libfi.so.1 [runpath]
│   │   ├── libu.so.1 [runpath]
│   │   │   ├── libcsup.so.1 [runpath]
│   │   │   ├── libquadmath.so.0 [runpath]
│   │   │   └── librt.so.1 [default path]
│   │   ├── libf.so.1 [runpath]
│   │   │   ├── libu.so.1 [runpath]
│   │   │   ├── libcsup.so.1 [runpath]
│   │   │   └── librt.so.1 [default path]
│   │   └── librt.so.1 [default path]
│   ├── libquadmath.so.0 [runpath]
│   ├── libcraymath.so.1 [runpath]
│   │   ├── libquadmath.so.0 [runpath]
│   │   ├── libu.so.1 [runpath]
│   │   ├── libgfortran.so.5 [runpath]
│   │   └── librt.so.1 [default path]
│   ├── libu.so.1 [runpath]
│   ├── libf.so.1 [runpath]
│   └── librt.so.1 [default path]
├── libmodules.so.1 [ld.so.conf]
├── libquadmath.so.0 [ld.so.conf]
├── libcraymath.so.1 [ld.so.conf]
├── libf.so.1 [ld.so.conf]
├── libu.so.1 [ld.so.conf]
├── librt.so.1 [default path]
├── libatomic.so.1 [default path]
└── libfabric.so.1 not found
    ┊ Paths considered in this order:
    ┊ 1. rpath:
    ┊ 2. LD_LIBRARY_PATH was not set
    ┊ 3. runpath was not set
    ┊ 4. ld config files:
    ┊    /usr/local/lib64
    ┊    /usr/local/lib
    ┊    /opt/cray/pe/lib64
    ┊    /opt/cray/pe/lib64/cce
    ┊    /opt/cray/xpmem/default/lib64
    ┊ 5. Standard paths:
    ┊    /lib
    ┊    /lib64
    ┊    /usr/lib
    ┊    /usr/lib64
Error [/opt/cray/pe/mpich/8.1.13/ofi/cray/10.0/lib/libmpich.so]: Not all dependencies were found
libmpi_aocc.so.12 
├── libatomic.so.1 [runpath]
├── libquadmath.so.0 [runpath]
├── libpgmath.so [runpath]
├── libflang.so [runpath]
│   ├── libquadmath.so.0 [ld.so.conf]
│   ├── librt.so.1 [default path]
│   └── libflangrti.so not found
│       ┊ Paths considered in this order:
│       ┊ 1. rpath:
│       ┊ 2. LD_LIBRARY_PATH was not set
│       ┊ 3. runpath was not set
│       ┊ 4. ld config files:
│       ┊    /usr/local/lib64
│       ┊    /usr/local/lib
│       ┊    /opt/cray/pe/lib64
│       ┊    /opt/cray/pe/lib64/cce
│       ┊    /opt/cray/xpmem/default/lib64
│       ┊ 5. Standard paths:
│       ┊    /lib
│       ┊    /lib64
│       ┊    /usr/lib
│       ┊    /usr/lib64
├── libompstub.so [runpath]
│   └── libquadmath.so.0 [ld.so.conf]
├── libflangrti.so [runpath]
│   ├── libquadmath.so.0 [ld.so.conf]
│   ├── libomp.so not found
│   └── libpgmath.so not found
│       ┊ Paths considered in this order:
│       ┊ 1. rpath:
│       ┊ 2. LD_LIBRARY_PATH was not set
│       ┊ 3. runpath was not set
│       ┊ 4. ld config files:
│       ┊    /usr/local/lib64
│       ┊    /usr/local/lib
│       ┊    /opt/cray/pe/lib64
│       ┊    /opt/cray/pe/lib64/cce
│       ┊    /opt/cray/xpmem/default/lib64
│       ┊ 5. Standard paths:
│       ┊    /lib
│       ┊    /lib64
│       ┊    /usr/lib
│       ┊    /usr/lib64
├── libpmi.so.0 [ld.so.conf]
├── libpmi2.so.0 [ld.so.conf]
├── librt.so.1 [default path]
└── libfabric.so.1 not found
    ┊ Paths considered in this order:
    ┊ 1. rpath is skipped because runpath was set
    ┊ 2. LD_LIBRARY_PATH was not set
    ┊ 3. runpath:
    ┊    /opt/cray/pe/gcc-libs
    ┊    /opt/cray/gcc-libs
    ┊    /opt/AMD/aocc-compiler-3.0.0/bin/../lib
    ┊ 4. ld config files:
    ┊    /usr/local/lib64
    ┊    /usr/local/lib
    ┊    /opt/cray/pe/lib64
    ┊    /opt/cray/pe/lib64/cce
    ┊    /opt/cray/xpmem/default/lib64
    ┊ 5. Standard paths:
    ┊    /lib
    ┊    /lib64
    ┊    /usr/lib
    ┊    /usr/lib64
Error [/opt/cray/pe/mpich/8.1.13/ofi/aocc/3.0/lib/libmpich.so]: Not all dependencies were found
libmpi_intel.so.12 
├── libpmi2.so.0 [ld.so.conf]
├── libpmi.so.0 [ld.so.conf]
├── librt.so.1 [default path]
├── libatomic.so.1 [default path]
├── libfabric.so.1 not found
├── libifcoremt.so.5 not found
├── libintlc.so.5 not found
├── libsvml.so not found
├── libifport.so.5 not found
└── libimf.so not found
    ┊ Paths considered in this order:
    ┊ 1. rpath:
    ┊ 2. LD_LIBRARY_PATH was not set
    ┊ 3. runpath was not set
    ┊ 4. ld config files:
    ┊    /usr/local/lib64
    ┊    /usr/local/lib
    ┊    /opt/cray/pe/lib64
    ┊    /opt/cray/pe/lib64/cce
    ┊    /opt/cray/xpmem/default/lib64
    ┊ 5. Standard paths:
    ┊    /lib
    ┊    /lib64
    ┊    /usr/lib
    ┊    /usr/lib64
Error [/opt/cray/pe/mpich/8.1.13/ofi/intel/19.0/lib/libmpich.so]: Not all dependencies were found
```

</details>
Any clue if they are being resolved?

**Comment by becker33** [comment]
@spackbot fix style

**Comment by becker33** [comment]
@spackbot fix style

**Review by tgamblin — DISMISSED** [review]

**Comment by becker33** [comment]
@spackbot fix style

**Comment by becker33** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
Pipeline failure is spurious and this PR doesn't affect that part of the pipeline.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
