### PR TITLE
py-tensorflow: add v2.18.0

### PR DESCRIPTION
**Pull request by adamjstewart**
* https://github.com/tensorflow/tensorflow/releases/tag/v2.18.0
* https://github.com/tensorflow/tensorflow/releases/tag/v2.17.1

### CODE REVIEW

**Review by bernhardkaindl — COMMENTED** [review]
This command failed: `bin/spack install -v --fail-fast py-tensorflow@2.18.0`
<details><summary>Failed spec: py-tensorflow@2.18.0</summary>

### `py-tensorflow@2.18.0`:
<details><summary>Head of the raw log for py-tensorflow@2.18.0</summary>

```py
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
==> [2024-10-25-13:52:04.744833] FILTER FILE: tensorflow/tools/pip_package/build_pip_package.py [replacing "patchelf"]
==> [2024-10-25-13:52:04.747086] FILTER FILE: configure.py [replacing "if workspace_has_any_android_rule\(\)"]
==> [2024-10-25-13:52:04.749585] FILTER FILE: .tf_configure.bazelrc [replacing "--define with_gcp_support=true"]
==> [2024-10-25-13:52:04.750684] FILTER FILE: .tf_configure.bazelrc [replacing "build:opt --copt=-march=native"]
==> [2024-10-25-13:52:04.751306] FILTER FILE: .tf_configure.bazelrc [replacing "build:opt --host_copt=-march=native"]
==> py-tensorflow: Executing phase: 'build'
==> [2024-10-25-13:52:04.801119] '/home/bkaindl/spack.2/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/bazel-6.5.0-gcnvfwyfq6xqbrtjj6rev3dw5b2zb34z/bin/bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spackdq7kg7dg' 'build' '--color=no' '--jobs=32' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=nonccl' '--define=with_numa_support=False' '--config=v2' '//tensorflow/tools/pip_package:wheel'
$TEST_TMPDIR defined: output root default is '/tmp/spackdq7kg7dg' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Config value 'noaws' is not defined in any .rc file

```
</details>

```py
    Compiling src/core/lib/iomgr/resolve_address_posix.cc; 1s local
    .../build/lib/analysis:view_creation_failed_exception; 1s multiplex-worker
    Compiling src/core/lib/iomgr/socket_factory_posix.cc; 1s local
    //src/main/protobuf:action_cache_proto; 0s multiplex-worker ...
ERROR: Config value 'noaws' is not defined in any .rc file
==> Error: ProcessError: Command exited with status 2:
    opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/bazel-6.5.0-gcnvfwyfq6xqbrtjj6rev3dw5b2zb34z/bin/bazel --nohome_rc --nosystem_rc --output_user_root=/tmp/spackdq7kg7dg build --color=no --jobs=32 --config=opt --verbose_failures --config=dynamic_kernels --config=noaws --config=nogcp --config=nohdfs --config=nonccl --define=with_numa_support=False --config=v2 //tensorflow/tools/pip_package:wheel
```

</details>



<details><summary>Expand the spec output `spack spec py-tensorflow@2.18.0`</summary>

```yaml
Input spec
--------------------------------
 -   py-tensorflow@2.18.0

Concretized
--------------------------------
 -   py-tensorflow@2.18.0%gcc@13.1.0~android~aws~computecpp~cuda+dynamic_kernels~gcp~gdr~hdfs~ios~jemalloc~mkl~monolithic~mpi~nccl~ngraph~numa~opencl~rocm~tensorrt~verbs+xla patches=2017b3e
[+]      ^bazel@6.5.0%gcc@13.1.0+nodepfail patches=0f6940d,3e6448a,604423c,dbbf38b
[+]          ^openjdk@11.0.23_9%gcc@13.1.0
[+]          ^zip@3.0%gcc@13.1.0 patches=14dc880,3bc30ba,5068e7c,51f48db,66ab4ce,a92fc4e,a95ed93,b930b69,eb83fc8,f7d0bc4,fa8312c
[+]      ^gcc-runtime@13.1.0%gcc@13.1.0
[e]      ^glibc@2.35%gcc@13.1.0
[+]      ^hdf5@1.14.5%gcc@13.1.0~cxx~fortran+hl~ipo~java~map~mpi+shared~szip~threadsafe+tools api=default
[+]          ^cmake@3.30.5%gcc@13.1.0~doc+ncurses+ownlibs~qtgui patches=dbc3892
[e]              ^curl@7.81.0%gcc@13.1.0+gssapi+ldap+libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl
[+]          ^gmake@4.4.1%gcc@13.1.0~guile
[+]          ^pkgconf@2.2.0%gcc@13.1.0
[+]          ^zlib-ng@2.2.1%gcc@13.1.0+compat+new_strategies+opt+pic+shared
[+]      ^patchelf@0.17.2%gcc@13.1.0
[+]      ^py-absl-py@1.4.0%gcc@13.1.0_pip
[+]      ^py-astunparse@1.6.3%gcc@13.1.0_pip
[+]      ^py-flatbuffers@24.3.25%gcc@13.1.0_pip
[+]      ^py-gast@0.5.4%gcc@13.1.0_pip
[+]      ^py-google-pasta@0.2.0%gcc@13.1.0_pip
[+]      ^py-grpcio@1.64.0%gcc@13.1.0_pip
[+]          ^c-ares@1.28.1%gcc@13.1.0~ipo
[+]          ^openssl@3.3.1%gcc@13.1.0~docs+shared certs=mozilla
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0
[e]              ^perl@5.34.0%gcc@13.1.0~cpanm+opcode+open+shared+threads
[+]          ^py-coverage@7.2.6%gcc@13.1.0~toml_pip
[+]          ^py-cython@3.0.11%gcc@13.1.0_pip
[+]          ^re2@2024-07-02%gcc@13.1.0~icu~ipo+pic+shared
[+]              ^abseil-cpp@20240722.0%gcc@13.1.0~ipo+shared cxxstd=14
[+]                  ^googletest@1.12.1%gcc@13.1.0+gmock~ipo+pthreads+shared cxxstd=11
[+]      ^py-h5py@3.12.1%gcc@13.1.0~mpi_pip
[+]          ^py-pkgconfig@1.5.5%gcc@13.1.0_pip
[+]              ^py-poetry-core@1.8.1%gcc@13.1.0_pip
[+]      ^py-libclang@14.0.6%gcc@13.1.0_pip
[e]          ^llvm@14.0.0%gcc@13.1.0+clang~cuda~flang+gold+libomptarget~libomptarget_debug~link_llvm_dylib~lld~lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3 compiler-rt=runtime libcxx=runtime libunwind=runtime openmp=runtime patches=1f42874,25bc503,6379168,8248141,b216cff,cb8e645 shlib_symbol_version=none targets=all version_suffix=none
[+]      ^py-ml-dtypes@0.4.0%gcc@13.1.0_pip
[+]      ^py-numpy@1.26.4%gcc@13.1.0_pip patches=873745d
[+]          ^openblas@0.3.28%gcc@13.1.0~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared patches=d0b9276 symbol_suffix=none threads=none
[+]          ^py-cython@0.29.36%gcc@13.1.0_pip patches=c4369ad
[+]          ^py-meson-python@0.16.0%gcc@13.1.0_pip
[+]              ^meson@1.5.1%gcc@13.1.0_pip patches=0f0b1bd
[+]                  ^ninja@1.12.1%gcc@13.1.0+re2c
[+]                      ^re2c@3.1%gcc@13.1.0
[+]              ^py-pyproject-metadata@0.7.1%gcc@13.1.0_pip
[+]      ^py-opt-einsum@3.3.0%gcc@13.1.0_pip
[+]      ^py-packaging@24.1%gcc@13.1.0_pip
[+]          ^py-flit-core@3.9.0%gcc@13.1.0_pip
[+]      ^py-pip@23.1.2%gcc@13.1.0
[+]      ^py-protobuf@5.28.2%gcc@13.1.0_pip
[+]          ^protobuf@3.28.2%gcc@13.1.0~ipo+shared
[+]      ^py-requests@2.32.3%gcc@13.1.0~socks_pip
[+]          ^py-certifi@2023.7.22%gcc@13.1.0_pip
[+]          ^py-charset-normalizer@3.3.0%gcc@13.1.0_pip
[+]          ^py-idna@3.4%gcc@13.1.0_pip
[+]          ^py-urllib3@2.1.0%gcc@13.1.0~brotli~socks_pip
[+]              ^py-hatchling@1.25.0%gcc@13.1.0_pip
[+]                  ^py-editables@0.5%gcc@13.1.0_pip
[+]                  ^py-pathspec@0.11.1%gcc@13.1.0_pip
[+]                  ^py-pluggy@1.5.0%gcc@13.1.0_pip
[+]                      ^py-setuptools-scm@8.0.4%gcc@13.1.0+toml_pip
[+]                          ^git@2.45.2%gcc@13.1.0+man+nls+perl+subtree~svn~tcltk
[+]                              ^autoconf@2.72%gcc@13.1.0
[+]                              ^automake@1.16.5%gcc@13.1.0
[+]                              ^libidn2@2.3.7%gcc@13.1.0
[+]                                  ^libunistring@1.2%gcc@13.1.0
[+]                              ^libtool@2.4.7%gcc@13.1.0
[+]                                  ^findutils@4.9.0%gcc@13.1.0 patches=440b954
[+]                              ^m4@1.4.19%gcc@13.1.0+sigsegv patches=9dc5fbd,bfdffa7
[+]                                  ^libsigsegv@2.14%gcc@13.1.0
[+]                              ^openssh@9.8p1%gcc@13.1.0+gssapi
[+]                                  ^krb5@1.21.2%gcc@13.1.0+shared
[e]                                      ^bison@3.8.2%gcc@13.1.0~color
[+]                                  ^libedit@3.1-20240808%gcc@13.1.0
[+]                          ^py-tomli@2.0.1%gcc@13.1.0_pip
[+]                  ^py-trove-classifiers@2023.8.7%gcc@13.1.0_pip
[+]                      ^py-calver@2022.6.26%gcc@13.1.0_pip
[+]      ^py-setuptools@69.2.0%gcc@13.1.0
[+]      ^py-six@1.16.0%gcc@13.1.0_pip
[+]      ^py-tensorboard@2.18.0%gcc@13.1.0_pip
[+]          ^py-markdown@3.4.1%gcc@13.1.0_pip
[+]          ^py-tensorboard-data-server@0.7.0%gcc@13.1.0_pip
[+]              ^rust@1.81.0%gcc@13.1.0+dev~docs+src
[+]                  ^libgit2@1.8.0%gcc@13.1.0~curl~ipo+mmap+ssh https=system
[+]                      ^pcre@8.45%gcc@13.1.0~jit+multibyte+pic+shared+static+utf
[+]                  ^libssh2@1.11.0%gcc@13.1.0+shared crypto=openssl patches=011d926
[+]                  ^rust-bootstrap@1.81.0%gcc@13.1.0
[+]          ^py-werkzeug@3.0.4%gcc@13.1.0_pip
[+]              ^py-markupsafe@2.1.3%gcc@13.1.0_pip
[+]      ^py-termcolor@1.1.0%gcc@13.1.0_pip
[+]      ^py-typing-extensions@4.12.2%gcc@13.1.0_pip
[+]      ^py-wheel@0.41.2%gcc@13.1.0
[+]      ^py-wrapt@1.15.0%gcc@13.1.0_pip
[+]      ^python@3.11.9%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib patches=13fa8bf,b0615b2,ebdca64,f2fd060
[+]          ^bzip2@1.0.8%gcc@13.1.0~debug~pic+shared
[+]              ^diffutils@3.10%gcc@13.1.0
[+]          ^expat@2.6.3%gcc@13.1.0+libbsd
[+]              ^libbsd@0.12.2%gcc@13.1.0
[+]                  ^libmd@1.0.4%gcc@13.1.0
[+]          ^gdbm@1.24%gcc@13.1.0
[+]          ^gettext@0.22.5%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz
[+]              ^libiconv@1.17%gcc@13.1.0 libs=shared,static
[+]              ^libxml2@2.10.3%gcc@13.1.0+pic~python+shared
[e]              ^tar@1.34%gcc@13.1.0 zip=pigz
[+]          ^libffi@3.4.6%gcc@13.1.0
[+]          ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api patches=4885da3
[+]          ^ncurses@6.5%gcc@13.1.0~symlinks+termlib abi=none patches=7a351bc
[+]          ^readline@8.2%gcc@13.1.0 patches=bbf97f1
[+]          ^sqlite@3.46.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree
[+]          ^util-linux-uuid@2.40.2%gcc@13.1.0
[+]          ^xz@5.4.6%gcc@13.1.0~pic libs=shared,static
[+]      ^python-venv@1.0%gcc@13.1.0
[+]      ^swig@4.1.1%gcc@13.1.0
[+]          ^pcre2@10.44%gcc@13.1.0~jit+multibyte


```

</details>

**Comment by adamjstewart** [comment]
https://github.com/tensorflow/tensorflow/issues/78846

**Review by bernhardkaindl — COMMENTED** [review]
@adamjstewart, as far as I understood, you did not welcome the personal use of scripts to build PRs outside of CI as I did, and other reviews are outside of my area of experience for py-tensorflow, I unassign myself from your PR. Please correct me if I misunderstood.

**Comment by adamjstewart** [comment]
Nah, I'm one of the fans of your build scripts. Would love to see them even more tightly integrated into CI some day.

This PR builds now, but has issues with CUDA + GCC. @aweits is attempting to fix these now. Once CI passes, this should be fine to merge. TF is one of the few well-tested packages in our CI.

**Review by bernhardkaindl — APPROVED** [review]
> Nah, I'm one of the fans of your build scripts. Would love to see them even more tightly integrated into CI some day.

Thanks, that makes my day! I'd love that!

> This PR builds now, but has issues with CUDA + GCC. @aweits is attempting to fix these now. Once CI passes, this should be fine to merge. TF is one of the few well-tested packages in our CI.

Acked, good to know! Perfect, of course pending passing GitLab CI I ack your statement.

**Pull request merged**
