### PR TITLE
Add new packages for using MEDCoupling from SALOME platform

### PR DESCRIPTION
**Pull request by franciskloss**
See: https://salome-platform.org
Theses packages follow SALOME build constraints.
We recommand to use "salome-med" instead of "med" package.

Sur la branche salome_fkl
	nouveau fichier : var/spack/repos/builtin/packages/salome-configuration/FindSalomeHDF5.patch
	nouveau fichier : var/spack/repos/builtin/packages/salome-configuration/SalomeMacros.patch
	nouveau fichier : var/spack/repos/builtin/packages/salome-configuration/package.py
	nouveau fichier : var/spack/repos/builtin/packages/salome-med/MAJ_400_410_champs.patch
	nouveau fichier : var/spack/repos/builtin/packages/salome-med/package.py
	nouveau fichier : var/spack/repos/builtin/packages/salome-medcoupling/package.py

### CODE REVIEW

**Comment by franciskloss** [comment]
Hi, this is my first PR and I see some much more old PR and also some new PR that are merged before the mine.
Please, what do I have to do ? How to find a reviewer ? If the process is to wait, have you an idea how many time ?
Thank's in advance for your answer.
Francis Kloss

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
Sorry it took so long to start a review, but I'd kindly like to ask you if you have the capacity to collaborate with the upstream developers to fix the failing test cases from `spack install -v --test=root salome-medcoupling`:
```py
  >> 751    The following tests FAILED:
     752          2 - MEDCouplingBasicsTest1 (Failed)
     753          3 - MEDCouplingBasicsTest2 (Failed)
     754          5 - MEDCouplingBasicsTest4 (Failed)
     755          6 - MEDCouplingBasicsTest5 (Failed)
```
Example from the test `LastTest.log`
```yaml
...............E........./tmp/kaindlb/spack-stage/spack-stage-salome-medcoupling-9.7.0-izsysncisd5xpxpeyxcg2ks7k5tkn24r/spack-src/src/MEDCoupling_Swig/MEDCouplingBasicsTest5.py:1429: PendingDeprecationWarning: the matrix subclass is not the recomm
ended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  m0=m.toNumPyArray() ; m0=m0.reshape(3,nbCols) ; m0=np.matrix(m0)
/tmp/kaindlb/spack-stage/spack-stage-salome-medcoupling-9.7.0-izsysncisd5xpxpeyxcg2ks7k5tkn24r/spack-src/src/MEDCoupling_Swig/MEDCouplingBasicsTest5.py:1431: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent ma
trices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  n0=srcFieldValsOnPoints2.toNumPyArray() ; n0=n0.reshape(4,2) ; n0=np.matrix(n0)
/home/kaindlb/spack/spack/opt/spack/linux-ubuntu18.04-zen/gcc-8.4.0/py-numpy-1.21.2-lqh5g52roogcmsoohcahs5iqjrwdjomo/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended
 way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  return matrix(data, dtype=dtype, copy=False)
.....................................................................................................................
======================================================================
ERROR: testDualMesh3D1 (__main__.MEDCouplingBasicsTest5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/kaindlb/spack-stage/spack-stage-salome-medcoupling-9.7.0-izsysncisd5xpxpeyxcg2ks7k5tkn24r/spack-src/src/MEDCoupling_Swig/MEDCouplingBasicsTest5.py", line 1357, in testDualMesh3D1
    self.assertAlmostEqual(1.,d.getMeasureField(False).accumulate()[0],1e-13)
  File "/home/kaindlb/spack/spack/opt/spack/linux-ubuntu18.04-zen/gcc-8.4.0/python-3.8.11-3uwlldorpbj3p3kkyjiqob4yzr6ppfql/lib/python3.8/unittest/case.py", line 957, in assertAlmostEqual
    if round(diff, places) == 0:
TypeError: 'float' object cannot be interpreted as an integer
```
If the 4 failing tests are ok to fail, then I'd think that they should be commented out to not run (e.g.remove the test cases from the `CMakeLists.txt` using `filter_file()`)
Note: When you rebase this to develop, you also need to cherry-pick or apply the diff from #26363 unless it is merged already.

**Comment by franciskloss** [comment]
Hi, thanks to review my PR.
Now all tests run for the 2 packages salome-med and salome-medcoupling
Regards

**Comment by bernhardkaindl** [comment]
@franciskloss Your change to serialize the test didn't change the testresult for my environment:

```py
     665    22/22 Test #22: MEDLoaderCouplingTrainingSession ...   Passed    0.44 sec
     666    
     667    82% tests passed, 4 tests failed out of 22
     668    
     669    Total Test time (real) =  16.96 sec
     670    
  >> 671    The following tests FAILED:
     672          2 - MEDCouplingBasicsTest1 (Failed)
     673          3 - MEDCouplingBasicsTest2 (Failed)
     674          5 - MEDCouplingBasicsTest4 (Failed)
     675          6 - MEDCouplingBasicsTest5 (Failed)
```
This error and the others are still unchanged, they are not due to parallel build:
`TypeError: 'float' object cannot be interpreted as an integer`
In this case, my compiler was gcc@11.2.0 built by spack, before it was the gcc-8.4.0 of Ubuntu 18.04.

But this error is from python-3.8.11, so if you use a different python version, this could explain that you don't see that error, this line triggers it:
```py
src/MEDCoupling_Swig/MEDCouplingBasicsTest5.py
self.assertAlmostEqual(1.,d.getMeasureField(False).accumulate()[0],1e-13)
```
Since you don't get those error's I guess it would be ok to mask or disable the failing tests in the CPPUNIT source file which adds them using `#ifdef SPACK_TEST` or so (or not run the testsuite) using:
```py
def check(self):
    pass
```

**Comment by franciskloss** [comment]
You are right and thanks for your advice.

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
