### PR TITLE
re2c: add v3.0, v3.1

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the new version sha256s.

**Comment by tldahlgren** [comment]
@johnwparent Are you interested in reviewing this PR as someone who made significant changes to the package within the last year?

**Comment by johnwparent** [comment]
> @johnwparent Are you interested in reviewing this PR as someone who made significant changes to the package within the last year?

Yes, thanks, re2c is critical for Windows in order to bootstrap clingo without issue (since we have no cached clingo ATM) so it'll be good to review this, thanks for the ping!

**Comment by johnwparent** [comment]
Gitlab failure is legit:
```
==> Error: ProcessError: Command exited with status 1:
    './configure' '--prefix=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/morepadding/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/re2c-3.1-sawnuiochwi5a6sthukqnjzk5vwq6grb' '--disable-benchmarks' '--disable-debug' '--disable-dependency-tracking' '--disable-docs' '--disable-lexers' '--disable-libs' '--enable-golang'
1 error found in build log:
     6     checking for gawk... no
     7     checking for mawk... mawk
     8     checking whether make sets $(MAKE)... yes
     9     checking whether make supports nested variables... yes
     10    checking whether make supports nested variables... (cached) yes
     11    checking for a Python interpreter with version >= 3.7... none
  >> 12    configure: error: no suitable Python interpreter found
```

Looks like the new versions require some additional logic re: python. 

Once the Gitlab pipeline passes I'll validate Windows by hand.

**Review by alalazo — CHANGES_REQUESTED** [review]
See here: https://gitlab.spack.io/spack/spack/-/jobs/10998949

It seems `re2c` also requires a Python interpreter now. Can you check upstream if any more request is made on the new version of the tool?

**Comment by alalazo** [comment]
Any comment on this https://github.com/spack/spack/pull/43924#pullrequestreview-2064633135 @jrood-nrel ?

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@jrood-nrel We need further constraints to bootstrap `clingo` on old python versions. I can look into that next week, if you don't have bandwidth.

**Comment by alalazo** [comment]
Superseded by #46748

**Pull request closed without merging**
