### PR TITLE
cmake: add v3.29.5

### PR DESCRIPTION
**Pull request by johnwparent**
Add 3.29.5
Deprecate 3.29.4

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
Why deprecate? That makes it inconvenient to try the second latest version if the latest has new regressions. I would suggest to wait with that until just before 0.23

**Review by alalazo — COMMENTED** [review]
I agree with @haampie We can move versions to deprecated around the November release

**Comment by johnwparent** [comment]
> I agree with @haampie We can move versions to deprecated around the November release

Sounds good, wasn't sure what the deprecation policy was, seemed to me we were deprecating everything except the latest of each minor series to reduce cruft but I think I just caught Harmen's work for this last release and assumed too much. 
Addressed the request and added 3.29.6 as well. Thanks!

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by johnwparent** [comment]
Re-ran the individual failing GL job after second full pipeline run failed as it was failing due to resource starvation. Seems to have made everything work as expected. 
Thanks @alalazo

**Pull request merged**
