### PR TITLE
vtk-m: update latest release

### PR DESCRIPTION
**Pull request by vicentebolea**
Finally! After a quite summer, VTK-m v1.8.0-rc1 is finally out :tada: :tada: :tada:

This bring exiting new features, and bugfixes, find the tentative release notes at https://gitlab.kitware.com/vtk/vtk-m/-/blob/master/docs/changelog/1.8/release-notes.md

Let me know if we need to change anything else in the package

ViB

### CODE REVIEW

**Comment by kmorel** [comment]
Looks good, but can you update the `maintainers` array?

**Comment by vicentebolea** [comment]
@kmorel updated

**Review by kmorel — APPROVED** [review]

**Comment by kmorel** [comment]
I approve. It looks like the bot is still putting @robertmaynard as a reviewer. That is probably not necessary.

**Comment by vicentebolea** [comment]
@kmorel yes, closing/opening this did not fix it. Anyways, only one review is required

**Comment by kmorel** [comment]
Is that true? I approved the changes, but the PR is still saying merging is blocked because it needs an approving review.

**Comment by vicentebolea** [comment]
@kmorel
Screenshot from 2022-04-22 11-33-03

**Comment by vicentebolea** [comment]
@kmorel it seems that automatic merge needs all the reviewers to approve this, but manual merge (an admin clicking the merge button) needs only one reviewer.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
