### PR TITLE
arborx: add 1.6

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
Some tests in pipelines are taking longer than (or hanging for) 6hrs:
- https://gitlab.spack.io/spack/spack/-/jobs/10707188

**Comment by aprokop** [comment]
> Some tests in pipelines are taking longer than (or hanging for) 6hrs:

@alalazo This is weird. I think the distributed KNN test is hanging somehow in Spack CI when run with 192 ranks. `MPIEXEC_MAX_NUM_PROCS` results in 192 which should be ok.
On my local machine, I can easily do
```
$ mpirun --host $(hostname):192 -np 192 ./ArborX_Example_DistributedTree_KNN.exe
```
The log contains this line:
```
8: srun: Requested partition configuration not available now
```
So I wonder if somehow one cannot use `MPIEXEC_MAX_NUM_PROCS` detected by MPI when running in this CI. This is the first time we added a distributed example that is getting triggered in smoke tests.

**Comment by alalazo** [comment]
I'll let @tldahlgren comment on that, but if I recall correctly it's not encouraged to have MPI tests in CI. Please, @tldahlgren let me know if I'm wrong.

**Comment by aprokop** [comment]
I see the following line in the heffte testing: https://github.com/spack/spack/blob/afcfd56ae5e0788af173b0e4dd07e67234c9a963/var/spack/repos/builtin/packages/heffte/package.py#L159-L160

Not sure if it matters.

**Comment by aprokop** [comment]
@tldahlgren Any advice?

**Review by alalazo — APPROVED** [review]

**Comment by aprokop** [comment]
@alalazo I am trying to see the tests results. However, all build in ci/gitlab-ci show `no-specs-to-rebuild`. Did it actually pass?

**Comment by alalazo** [comment]
@aprokop I saw CI :heavy_check_mark: and assumed the test was passing, but you're right the second time it wasn't re-run :sweat: I'll open an issue about this one but fyi @scottwittenburg @kwryankrattiger

**Comment by tldahlgren** [comment]
> > Some tests in pipelines are taking longer than (or hanging for) 6hrs:
> 
> @alalazo This is weird. I think the distributed KNN test is hanging somehow in Spack CI when run with 192 ranks. `MPIEXEC_MAX_NUM_PROCS` results in 192 which should be ok. On my local machine, I can easily do
> 
> ```
> $ mpirun --host $(hostname):192 -np 192 ./ArborX_Example_DistributedTree_KNN.exe
> ```
> 
> The log contains this line:
> 
> ```
> 8: srun: Requested partition configuration not available now
> ```
> 
> So I wonder if somehow one cannot use `MPIEXEC_MAX_NUM_PROCS` detected by MPI when running in this CI. This is the first time we added a distributed example that is getting triggered in smoke tests.

Apologies for missing this.  A quick check leads me to the conclusion I need to update this in the documentation.

Not only should the stand-alone tests that run be completed on the order of minutes (https://spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-tests), they should NOT try to to use more processes than are available on any of the CI machines.  This usually means no more than a single process.

**Comment by kwryankrattiger** [comment]
Ci will only rebuild projects if the hash changes. Adding a new version does not imply that the new version is used, even if the project is used in the stack.

When reviewing new versions, it is important for reviewers, especially maintainers, to look at the gitlab CI and make sure we are running tests before merging.

You likely will need to look at all of the CI run for the gitlab branch for the PR, it is possible that a package is built and then cached in the PR mirror and not built again even if there are more changes. If that happens, then closing and reopening the PR will delete the s3 bucket for the PR and force rebuilding all of the touched packages in the PR and their direct dependents. This is more efficient than `@spackbot rebuild everything`.

**Comment by tldahlgren** [comment]
> @alalazo I am trying to see the tests results. However, all build in ci/gitlab-ci show `no-specs-to-rebuild`. Did it actually pass?

CI is set up to only run the stand-alone tests if the spec has changed enough to result in it being rebuilt.

**Comment by tldahlgren** [comment]
> When reviewing new versions, it is important for reviewers, especially maintainers, to look at the gitlab CI and make sure we are running tests before merging.

Hmmm.  I'll have to be more careful.

**Comment by aprokop** [comment]
> Not only should the stand-alone tests that run be completed on the order of minutes ([spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-tests](https://spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-tests)), they should NOT try to to use more processes than are available on any of the CI machines. This usually means no more than a single process.

How would a user know the max number of processes available on the CI machines? I would expect CMake to figure it out during finding MPI package. If that does not work, does it mean that anything more than 1 process cannot be relied on? In that case, there does not seem a way to test actual MPI communication, as you would need at least 2.

**Comment by tldahlgren** [comment]
>... if I recall correctly it's not encouraged to have MPI tests in CI. Please, @tldahlgren let me know if I'm wrong.

We do allow some testing.  You can see an example of `openmpi` testing in the "Inheriting a Test" section of https://spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-tests.  But we can't guarantee the CI runners have the resources to run tests involving more than one process.

**Comment by tldahlgren** [comment]
If a package has tests that cause runners to hang, either the tests need to be changed or the package can have stand-alone tests skipped by adding the package name to the CI configuration (see https://spack.readthedocs.io/en/latest/pipelines.html#spack-ci-rebuild) in the list under `ci:broken-tests-packages:`.

**Comment by scottwittenburg** [comment]
What I noticed is that the two failures of `arborx` on the first pipeline happened *after* the buildcache had been pushed, due to testing timeout.  As a result, the subsequent pipelines detected the target hash built on the mirror, and decided not to rebuild, which is expected.  One way I can think of to prevent this (without adding a lot of extra CI infrastructure) is to run the tests before we push the buildcache, but that may cause other issues.

**Comment by aprokop** [comment]
If I create a PR that removes a deprecated version, would that retrigger the tests?

> If a package has tests that cause runners to hang

I still have no understanding why it hanged. I don't even know if it launched, given that srun reported "Requested partition configuration not available now". Even way oversubscribed local machines run fine.

**Comment by tldahlgren** [comment]
> ... One way I can think of to prevent this (without adding a lot of extra CI infrastructure) is to run the tests before we push the buildcache, but that may cause other issues.

That is not the desired solution.  Todd was very explicit that the build cache is more important than the tests.

I have a back burner task to separate the stand-alone tests from the build.  We would still update the build cache on a successful build (since that is critical).  I'd have to review my notes and talk to Todd about whether we would still run stand-alone tests if the package is not built in that case.

**Comment by alalazo** [comment]
> I have a back burner task to separate the stand-alone tests from the build.

That would be good, cause in that case:
1. The Github notification can be based on the build alone (if that's what we want)
2. The test job can be given a much lower max time

What is confusing here, is that CI was :rotating_light: and then on the next commit it decided to not run the test that blocked it before.

**Comment by scottwittenburg** [comment]
> What is confusing here, is that CI was 🚨 and then on the next commit it decided to not run the test that blocked it before.

See my comment above, hopefully that explained it, even though I agree on the surface it's pretty unclear.  In general, test failures weren't supposed to cause gitlab jobs to fail (which I believe is still true), but this case was kind of special because of the timeout.

**Comment by tldahlgren** [comment]
> I still have no understanding why it hanged. I don't even know if it launched, given that srun reported "Requested partition configuration not available now". Even way oversubscribed local machines run fine.

I'm not familiar with arbors testing.  As you note, the test that was being run (https://gitlab.spack.io/spack/spack/-/jobs/10707188/raw) has the following output:

```
8: Test command: /opt/slurm/current/bin/srun "-n" "192" "/tmp/gitlab-runner-0/spack-stage/spack-standalone-tests/l4jynyplz6ltmssug7vmr5p3dxzprl3e/arborx-1.6-sxqlt5g/cache/arborx/examples/distributed_tree/ArborX_Example_DistributedTree_KNN.exe"
8: Working Directory: /tmp/gitlab-runner-0/spack-stage/spack-standalone-tests/l4jynyplz6ltmssug7vmr5p3dxzprl3e/arborx-1.6-sxqlt5g/cache/arborx/examples/distributed_tree
8: Test timeout computed to be: 10000000
8: srun: Requested partition configuration not available now
```

Unfortunately there are limited timestamps and none that I can see in the tests to gauge how long each test took or when it started.

CI has a 6 hour limit for a job, which currently means 6 hours to setup, build *and* test the package.  

Historically we tenedd to suggest using `-n 1` to be safe since tests can run be run in a variety of containers.

In this case, as you mention, `run` does detect partition not available.  How long does it take to make that determination?  What are the units of the computed `test timeout`?

**Pull request merged**
