### PR TITLE
CMake: add version 3.26.3

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
I am able to successfully build the package.

**Comment by tldahlgren** [comment]
Seeing a range of CI issues, some of which have been resolved by re-running CI.  So let's give that a shot.

@spackbot run pipeline

**Comment by johnwparent** [comment]
Gitlab CI issues seem wholly unrelated, rerunning.
@spackbot run pipeline

**Comment by johnwparent** [comment]
Thanks @tldahlgren!

**Pull request merged**
