### PR TITLE
VTKm: introduce new release

### PR DESCRIPTION
**Pull request by vicentebolea**
Finally! VTK-m v1.7.0 final release is finally out :tada: :tada: :tada:

This bring exiting new features, and bugfixes. Find the release notes at https://gitlab.kitware.com/vtk/vtk-m/-/blob/master/docs/changelog/1.7/release-notes.md

Let me know if we need to change anything else in the package

ViB

### CODE REVIEW

**Comment by kmorel** [comment]
I notice that the ci/gitlab-ci pipeline failed. What is up with that?

**Comment by vicentebolea** [comment]
Apparently some VTK-h does creates a shared library from the VTKm static library and fails since the static library obviously does not use PIC addresses. This could be possibly addressed by VTK-h depending in shared VTK-m.

```
/usr/bin/ld: /home/software/radiuss/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-fquud4xf2xg73gqhgywmgh73ngcpanz2/lib/libvtkm_cont-1.7.a(Buffer.cxx.o): relocation R_X86_64_PC32 against symbol `_ZTVN4vtkm4cont5Token19ObjectReferenceImplISt10shared_ptrINS0_8internal6Buffer15InternalsStructEEEE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
vtkh/utils/CMakeFiles/vtkh_utils.dir/build.make:145: recipe for target 'lib/libvtkh_utils.so' failed
make[2]: *** [lib/libvtkh_utils.so] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-vh2n24wzjy66xntr75b4yiopoz6r2plr/spack-src/spack-build'
CMakeFiles/Makefile2:473: recipe for target 'vtkh/utils/CMakeFiles/vtkh_utils.dir/all' failed
make[1]: *** [vtkh/utils/CMakeFiles/vtkh_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /home/software/radiuss/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-fquud4xf2xg73gqhgywmgh73ngcpanz2/lib/libvtkm_cont-1.7.a(RuntimeDeviceTracker.cxx.o): relocation R_X86_64_TPOFF32 against `_ZGVZN4vtkm4cont23GetRuntimeDeviceTrackerEvE20runtimeDeviceTracker' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/software/radiuss/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-fquud4xf2xg73gqhgywmgh73ngcpanz2/lib/libvtkm_cont-1.7.a(Buffer.cxx.o): relocation R_X86_64_PC32 against symbol `_ZTVN4vtkm4cont5Token19ObjectReferenceImplISt10shared_ptrINS0_8internal6Buffer15InternalsStructEEEE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
vtkh/utils/CMakeFiles/vtkh_utils_mpi.dir/build.make:147: recipe for target 'lib/libvtkh_utils_mpi.so' failed
make[2]: *** [lib/libvtkh_utils_mpi.so] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-vh2n24wzjy66xntr75b4yiopoz6r2plr/spack-src/spack-build'
CMakeFiles/Makefile2:447: recipe for target 'vtkh/utils/CMakeFiles/vtkh_utils_mpi.dir/all' failed
make[1]: *** [vtkh/utils/CMakeFiles/vtkh_utils_mpi.dir/all] Error 2
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-vh2n24wzjy66xntr75b4yiopoz6r2plr/spack-src/spack-build'
[ 19%] Built target vtkm_compiled_filters
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-vh2n24wzjy66xntr75b4yiopoz6r2plr/spack-src/spack-build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

@kmorel

**Comment by kmorel** [comment]
I don't know of any reason not to use shared libraries with VTK-m now. Should this be fixed before merging this code in?

**Comment by vicentebolea** [comment]
@kmorel yes, lets address this at the VTK-h package.

**Comment by vicentebolea** [comment]
@cyrush it seems that the we are having issues with VTK-h when updating VTK-m to 1.7.0. I could figure out some issues so far but remains another error in which It appears to be something with including the deprecated `DeviceAdapterListTag.h` header file instead of `DeviceAdapterList.h`


```
[ 26%] Building CXX object vtkh/CMakeFiles/vtkh_core_mpi.dir/vtkh.cpp.o
cd /tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/spack-build/vtkh && /builds/spack/spack/lib/spack/env/gcc/g++ -DVTKH_COMPILING_FLAG -DVTKH_PARALLEL -DVTKMDIY_MPI_AS_LIB -DVTKMDIY_NO_THREADS -Dvtkh_core_mpi_EXPORTS -I/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/src -I/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/spack-build -I/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/src/vtkh/thirdparty_builtin/lodepng -I/tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/src/vtk.thirdparty_builtin/diy/include -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/thirdparty/lcl/vtkmlcl -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/thirdparty/diy/vtkmdiy/include -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/openmpi-4.1.2-rgqsfvi6ozylzlwgl3h5zkdxlhygq7wd/include -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7 -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/thirdparty/optionparser -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/thirdparty/diy -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/thirdparty/diy/vtkmdiy/include/vtkmdiy/mpi -O3 -DNDEBUG -fPIC -fvisibility=hidden -pthread -ffunction-sections -fopenmp -std=c++14 -MD -MT vtkh/CMakeFiles/vtkh_core_mpi.dir/vtkh.cpp.o -MF CMakeFiles/vtkh_core_mpi.dir/vtkh.cpp.o.d -o CMakeFiles/vtkh_core_mpi.dir/vtkh.cpp.o -c /tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/src/vtkh/vtkh.cpp
In file included from /tmp/root/spack-stage/spack-stage-vtk-h-0.7.1-y2ahoidc4arktdl7qw7lx35rtgsnynaa/spack-src/src/vtkh/vtkh.cpp:7:0:
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/cont/DeviceAdapterListTag.h:32:61: error: expected template-name before '<' token
   DeviceAdapterListTagCommon : vtkm::internal::ListAsListTag<DeviceAdapterListCommon>
                                                             ^
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/cont/DeviceAdapterListTag.h:32:61: error: expected '{' before '<' token
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/cont/DeviceAdapterListTag.h:32:61: error: expected unqualified-id before '<' token
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/vtk-m-1.7.0-xfhqylwfi4hjrai7wiqb2a5rs3sp3sj2/include/vtkm-1.7/vtkm/cont/DeviceAdapterListTag.h:45:62: error: expected template-name before '<' token
   DeviceAdapterListTagDefault : vtkm::internal::ListAsListTag<VTKM_DEFAULT_DEVICE_ADAPTER_LIST>
```

**Comment by cyrush** [comment]
@vicentebolea yes, VTK-h 0.7.1 will not build with new VTK-m due to API changes. 

We plan to merge:  https://github.com/Alpine-DAV/vtk-h/pull/229
And then after that point we will require VTK-m 1.7.0

**Comment by cyrush** [comment]
For the other VTK-h issue ( static vs shared)

 only modes in production are all shared or all static libs (with respect to vtk-m + vtk-h)

**Comment by vicentebolea** [comment]
@cyrush the current changes to the vtk-h package does resolve this by depending on a VTK-m < 1.7. This can be removed on the MR that you mentioned above gets merged and makes its way to the VTK-h spack package.

**Comment by cyrush** [comment]
@vicentebolea sounds good!

**Comment by cyrush** [comment]
@spackbot run pipeline

**Comment by cyrush** [comment]
@spackbot run pipeline

continue the pod battle: (llvm build failed due to resource issue)

```
Unschedulable: "0/25 nodes are available: 16 node(s) didn't match Pod's node affinity/selector, 9 Insufficient cpu, 9 Insufficient memory.
```

**Comment by cyrush** [comment]
CI == green.

**Comment by eugeneswalker** [comment]
Should we merge?
EDIT: I see the requested reviewers haven't approved yet, sorry!

**Comment by cyrush** [comment]
ken can approve, but @vicentebolea should probably be added as a maintainer as well

**Review by kmorel — APPROVED** [review]

**Comment by kmorel** [comment]
Yes, @vicentebolea would be a better review, but this looks good to me.

Out of curiosity, how do you look up the SHA-256 hash for the commits? I went to verify what you had, but I was only able to get the SHA1 from git and GitLab.

**Comment by kmorel** [comment]
I also noted that @robertmaynard is listed as a pending reviewer for this PR. He should probably be removed as he has changed jobs, and I doubt he has time to do reviews.

**Comment by cyrush** [comment]
@kmorel thanks for approving! 

The sha-256 in this case is the sha of the release tarball, not the git sha.

**Review by alalazo — APPROVED** [review]
Maintainers approved

**Pull request merged**
