### PR TITLE
freeglut: add v3.6.0

### PR DESCRIPTION
**Pull request by jmcarcell**

### CODE REVIEW

**Comment by wdconinc** [comment]
Does the patch need to continue to be applied?

**Comment by jmcarcell** [comment]
I think not. I built it with GCC 14 without the patch and the build went fine.

**Comment by wdconinc** [comment]
Thanks. I see the patch is https://github.com/freeglut/freeglut/commit/412dc0b70402bb4e974287672335c1b6b7758b77. It needs to apply for all versions in spack until 3.2.1, so `@3:3.2.1`. Could you change that while we're anyway editing this?

**Comment by jmcarcell** [comment]
Yes, done.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
