### PR TITLE
changing site_packages_dir to python_platlib for gptune

### PR DESCRIPTION
**Pull request by liuyangzhuan**
See https://github.com/spack/spack/commit/e0f044561e9b3cb384bfb0f364555e5875b1a492#diff-b128f4139b9a5b47d81d8fc1364e7c8eb0c7add254b8de66076e5cb787cb528a

### CODE REVIEW

**Review by wspear — CHANGES_REQUESTED** [review]
I'm not sure if the other instances matter, but there are four occurrences of site_packages_dir that I replaced when I did my local fix. Should they all be changed for consistency?

**Review by wspear — APPROVED** [review]
This looks good to me! You might want to consider nudging the python version restriction to py-gpy since that is the source of the issue.

**Comment by eugeneswalker** [comment]
Should we merge this now? Anything else to be done? Happy to hit merge!

**Comment by wspear** [comment]
@eugeneswalker I'm running into some breakage with the spack test for this package, but I don't think it's directly related to this commit. I'll submit another issue if it doesn't turn out to be a local configuration problem.

**Pull request merged**
