### PR TITLE
seqfu: add v1.22.3

### PR DESCRIPTION
**Pull request by georgiastuart**
Adds seqfu@1.22.3

### CODE REVIEW

**Comment by georgiastuart** [comment]
@dialvarezs this looks like you!

**Comment by dialvarezs** [comment]
Great! One minor suggestion: the patch should not be necessary for versions 1.22.0 and above (see details [here](https://github.com/telatin/seqfu2/pull/25)), so you can limit the application to the v1.20.3 version.

**Comment by georgiastuart** [comment]
Thanks @dialvarezs ! Adding that now. While I'm at it, do you want me to set you as the maintainer?

**Comment by dialvarezs** [comment]
No problem @georgiastuart ! Sure, you can put me as the maintainer, thanks!

**Review by dialvarezs — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
