### PR TITLE
tau: add version 2.30.2

### PR DESCRIPTION
**Pull request by eugeneswalker**
@sameershende @khuck @wspear

### CODE REVIEW

**Review by khuck — COMMENTED** [review]
Looks OK to me...

**Review by khuck — DISMISSED** [review]

**Review by wspear — DISMISSED** [review]
The extra space between the version and the hash might bug someone eventually. Otherwise no worries.

**Comment by eugeneswalker** [comment]
> The extra space between the version and the hash might bug someone eventually. Otherwise no worries.

Good catch. Fixed.

**Review by wspear — APPROVED** [review]
Looks good!

**Review by sethrj — APPROVED** [review]

**Pull request merged**
