### PR TITLE
openfoam-org: add v11

### PR DESCRIPTION
**Pull request by kjrstory**

### CODE REVIEW

**Comment by wdconinc** [comment]
Apologies for the delay. This is still a valid new version to add (i.e. this version hasn't been added yet).

Could you please rebase this branch to check whether the build failures in the gitlab-ci pipeline are still present (unlikely to be caused by this PR since openfoam-org is not part of these CI pipelines)? Can you also re-verify that this builds for you with the current develop branch?

I verified that the checksum is correct.

**Review by wdconinc — APPROVED** [review]

**Comment by wdconinc** [comment]
This failed the readthedocs build, but probably a simple rebase/update should get it unstuck. I'm marking as auto-merge.

**Comment by kjrstory** [comment]
@wdconinc  Could you please review this again?

**Comment by wdconinc** [comment]
This still needs a rebase.

**Pull request merged**
