### PR TITLE
add versions 2.2rc2 and 2.1 to the mvapich2 package

### PR DESCRIPTION
**Pull request by bhatele**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Not sure how I feel about adding alpha, beta, and release candidate versions to the package. If we do, we should set the latest stable release as preferred and remove the a/b/rc versions as soon as the next version is released. Thoughts?

**Comment by bhatele** [comment]
I agree. I was considering removing the a/b versions when I added the release candidate but I thought someone might be testing their codes against them. Once the next version is released, we should remove those versions.

**Comment by adamjstewart** [comment]
Actually, now that I think about it, 2.2b was already the default, so making 2.1 the default would be a step backwards. Still, Spack doesn't usually include alpha/beta/release candidate versions. Was there some important feature added in 2.2 that forced us to include it? Do others have opinions about this?

**Comment by tgamblin** [comment]
I would actually lean towards leaving an RC version default over the beta.  If we want to mark 2.2 preferred when it comes out, that would make sense, and then we can bump the preferred version at major releases afterwards.  But given that we're already in beta it seems more stable to move to RC.  @adamjstewart: thoughts?

**Pull request merged**
