### PR TITLE
Avoid building @main/@master/@develop etc in CI

### PR DESCRIPTION
**Pull request by haampie**
Currently it's possible that we build a moving target in CI, which leads to reproducibility problems, security issues, etc.

We don't have better syntax than @:[many nines] for this unfortunately.

### CODE REVIEW

**Comment by haampie** [comment]
So, we have 8 packages on arbitrary commits that we may need to fix:

```
snap
tycho2
sse2neon
amg2013
cosp2
snbone
vpfft
vpic
```

**Comment by haampie** [comment]
@rspavel @ktsai7 @rbberger any clue what the deal is with the flecsi@1.4.2 failing here?

```
CMake Error at CMakeLists.txt:41 (include):
  include could not find requested file:
    /tmp/root/spack-stage/spack-stage-flecsi-1.4.2-23r5clgxqf5ipzlg67v3lgbs54jal7tr/spack-src/cinch/cmake/ProjectLists.txt
```

**Comment by haampie** [comment]
Ah, the issue is probably:

```python
depends_on("cinch@1.01:", type="build", when="+external_cinch @:1.9")
```

but there's no cinch version > 1 in Spack.

@junghans would it be possible to tag a > 1 release of cinch and register it in Spack so that we don't have a moving target in our CI? Alternatively I can comment flecsi out.

**Comment by junghans** [comment]
@tuxfan is the master of cinch these days!

**Comment by tldahlgren** [comment]
Added @junghans to reflect commenting on this PR.

**Comment by haampie** [comment]
We need @tuxfan ;)

**Comment by haampie** [comment]
We've got #39611, closing this.

**Pull request closed without merging**
