### PR TITLE
geant4: enable building against spack-built geant outside of spack

### PR DESCRIPTION
**Pull request by sethrj**
Following up on [a thread about exporting CMake dependencies](https://github.com/celeritas-project/celeritas/pull/432#discussion_r885477622): allow me to try to convince you that exporting the cache variables is the proper behavior for Geant4.

To recap, here's what happens when you build a package against Geant4 either by setting `Geant4_ROOT`, `CMAKE_PREFIX_PATH`, or by loading the Geant4 module (when `autoload` is `none`):
```console
$ cat CMakeLists.txt
project(find_my_geant LANGUAGES CXX)
cmake_minimum_required(VERSION 3.23)
find_package(Geant4)
$ cmake -DGeant4_ROOT=/rnsdhpc/code/spack/opt/spack/apple-clang-13.0.0/geant4/u3srvfj/ .
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CLHEP (missing: CLHEP_DIR)
CMake Warning at CMakeLists.txt:3 (find_package):
  Found package configuration file:

    /rnsdhpc/code/spack/opt/spack/apple-clang-13.0.0/geant4/u3srvfj/lib/Geant4-11.0.0/Geant4Config.cmake

  but it set Geant4_FOUND to FALSE so package "Geant4" is considered to be
  NOT FOUND.  Reason given by package:

  Geant4 could not be found because dependency CLHEP could not be found.



-- Configuring done
-- Generating done
-- Build files have been written to: /Users/s3j/test-geant4-find
```

The packages CLHEP, XercesC, and Expat are all dependencies of Geant4, but I argue that unless your downstream app *directly* accesses those libraries, you should *not* need to explicitly load or provide info about those dependencies.  Although CLHEP is going to have to be a PUBLIC CMake dependency because of its universal header usage in Geant4, it's possible to use Geant4 and only access headers from Geant4 alone -- e.g. the `G4RunManager`. (It's rarely the case that one has to directly access XercesC or Expat, so those those should both be PRIVATE CMake dependencies, I think.) It's not necessary to provide `LD_RUN_PATH` or `LD_LIBRARY_PATH` info to correctly link against a spack-installed Geant4 because Spack builds the RPATHs into Geant4 already, so I don't think it should be necessary to load those downstream modules.

I also think a self-defining Geant4 is also the correct approach because when users build Geant4 themselves, the upstream dependencies might be auto-download "for free" by Geant4 and included alongside the package. The decision to drop the "package cache" file is effectively requiring users to know who built Geant4 and how.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Adding @vvolkl and @gartung for the CERN/FNAL perspectives!

The context to the "package cache" file was to try and cover two requested use cases:

1. As @sethrj notes, to provide a completely self consistent install so finding Geant4 finds the exact build/install deps with no need to set/know `CMAKE_PREFIX_PATH` or similar.
2. Not installing the package cache file removes all hard-coded paths in the install, making it completely relocatable _provided_ end build consumers have `CMAKE_PREFIX_PATH` set up appropriately.

I think we can install the package cache file as proposed, _if_ Spack can patch this file at **binary package** install time to adjust the prefixes (basically `$SPACK_ROOT`) and give the relocatability. I haven't kept up with the binary packaging and patching so am not sure if this kind of operation is already implemented. At least this is text only patching. If so then I think we're good to go.

The only other, maybe corner case, problem I can think of is in environments with non-unified concretization. It feels like that could lead to some mixed/inconsistent linking to, e.g. clhep/expat, but perhaps that's up to the environment creator to sort out.

So I'm fine with this change, modulo answering the questions above.

**Review by gartung — APPROVED** [review]
As long as the dependencies are inside the spack install tree that path should be relocated in the binary cache file.

**Comment by drbenmorgan** [comment]
Thanks @gartung, then I think we're good to go! I think the case of dependencies outside the Spack install tree is a real outside case for binary packaging given that it should be installing all of the requirements consistently via hashes

**Review by drbenmorgan — APPROVED** [review]

**Comment by gartung** [comment]
@drbenmorgan You should be able to merge since you are listed as maintainer.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
