### PR TITLE
py-scipy: add v1.10.1

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/scipy/scipy/releases/tag/v1.10.1

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256, dependency changes LGTM

**Review by rgommers — APPROVED** [review]
LGTM, thanks @adamjstewart

**Comment by adamjstewart** [comment]
@rgommers let me know if you ever want to take over and be the person to add new versions to numpy/scipy. I only indirectly use these through PyTorch so having the latest and greatest version isn't as important to me.

**Comment by rgommers** [comment]
> @rgommers let me know if you ever want to take over and be the person to add new versions to numpy/scipy. I only indirectly use these through PyTorch so having the latest and greatest version isn't as important to me.

I will - but I'd rather not say yes now, since I'm already heavily oversubscribed. I'm not a direct user either, I only occasionally use Spack to work _on_ numpy and scipy. I'm more using this packaging effort to learn more about Spack and fix Python build system problems at the same time.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
