### PR TITLE
DDD bugfix

### PR DESCRIPTION
**Pull request by DarylGrunau**
This PR addresses an issue with DDD where, when it queries the initial settings from GDB, it does not handle properly the setting for `extended-prompt` and a bogus value is injected into one's own `~/.ddd/init` file.  This bug is instigated when the user attempts to `Edit -> GDB Settings`.  Then, upon subsequent invocation of DDD, it hangs attempting to initialize GDB with a bogus setting.  See the commentary at https://stackoverflow.com/questions/2914003/ddd-hangs-on-start.  The advanced GDB user may still make use of the `extended-prompt` in their own `~/.gdbinit` file.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Has this patch been submitted upstream?

**Comment by DarylGrunau** [comment]
This patch has not been submitted upstream; I wasn't sure that there would be anyone to receive it as development on DDD appears to have ended for some years now.

**Comment by adamjstewart** [comment]
The homepage has a link to their bug tracker, it looks like people are still submitting bugs as of 2020: https://savannah.gnu.org/bugs/?group=ddd

**Comment by DarylGrunau** [comment]
I'll submit this upstream.  See https://savannah.gnu.org/bugs/index.php?58191

**Comment by DarylGrunau** [comment]
@adamjstewart is there anything else here you need from me before you'll merge?  I think it's ready but perhaps you're looking for something additional.  Thanks.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
