### PR TITLE
visit: enable ADIOS2 support when +adios2 in spec

### PR DESCRIPTION
**Pull request by BenWibking**
This enables ADIOS2 support by setting the appropriate CMake variable with the path to the ADIOS2 package prefix when `+adios2` is specified in the spec. For some reason, this was previously missing and ADIOS2 support was not built even when `+adios2` was included.

With the patch in https://github.com/spack/spack/pull/41753, this spec builds and runs successfully on a Linux ARM64 workstation:
```
spack install visit@3.3.3~mfem~conduit%gcc@11.4.0 ^llvm~gold ^adios2@2.7.1
```

### CODE REVIEW

**Comment by BenWibking** [comment]
The build still fails, due to this bug in `adios2@2.7.1`: https://github.com/spack/spack/issues/23643

**Comment by alalazo** [comment]
Visit is failing to build in CI pipelines

**Comment by BenWibking** [comment]
There is an API break in ADIOS2 with 2.9, so it should require ADIOS2 < 2.9 or Visit needs a patch when >= 2.9.

The prebuilt VisIt binaries ship with ADIOS2 v2.7.1, ~which is waiting on this PR: https://github.com/spack/spack/pull/41753.~

**Comment by BenWibking** [comment]
I've set it to require ADIOS2 v2.7.1 when `+adios2` is set. We will see if that fixes the CI build.

**Comment by BenWibking** [comment]
@alalazo Visit now builds in CI pipelines.

Fides fails to build with adios2@2.7.1 (https://gitlab.spack.io/spack/spack/-/pipelines/583611 and https://gitlab.spack.io/spack/spack/-/pipelines/583552), but that's a fides packaging problem, since it doesn't provide a version requirement for adios2 (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fides/package.py).

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
> so it should require ADIOS2 < 2.9

@BenWibking @alalazo  why was adios2 fixed to a single version? This is overly restrictive and makes concretization elsewhere fail.

**Comment by BenWibking** [comment]
> > so it should require ADIOS2 < 2.9
> 
> @BenWibking @alalazo why was adios2 fixed to a single version? This is overly restrictive and makes concretization elsewhere fail.

I had originally proposed fixing it to 2.7.1 because that's what the offical binary release of VisIt currently uses.

**Comment by haampie** [comment]
Is there some compat table somewhere? Currently #41908 is a whac-a-mole with compat bounds, if they can be a bit looser that'd help.

**Comment by BenWibking** [comment]
> Is there some compat table somewhere? Currently #41908 is a whac-a-mole with compat bounds, if they can be a bit looser that'd help.

Not that I know of. @cyrush ?

**Comment by haampie** [comment]
Let's move the discussion to #41908, I've pushed a commit there that at least allows ascent 2.8.

**Pull request merged**
