### PR TITLE
cabana: add +all, with new package "all"(A Load Balancing Library)

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by streeve — APPROVED** [review]

**Comment by junghans** [comment]
@spackbot fix style

**Comment by junghans** [comment]
@alalazo could you review this?

**Review by bernhardkaindl — APPROVED** [review]
To: @junghans @streeve:
Cc: @patrickb314 @sslattery 

I pushed 8 commits to fix issues that appear when attempting to use CMake-3.26 or newer and other variants:

1) I built `cabana` with different CMake versions and as noted in the cabana recipe, the CMakeLists.txt allows to disable HDF5 when the CMake version is less than 3.26. The version constraint `cmake@:3.26` used in the conflict for `~hdf5` was inverted. The conflict for `~hdf5` is `cmake@2.26:` (3.26 and newer).

2) MPI requires C: Add `depends_on("c", type="build", when="+mpi")`
3) `+mpi` requires `C`, but at least for some CMake versions, the location where the `CMakeLists.txt` tries to enable the C language is not acted on and these versions warn/error that the C language is missing. Add to at the top level language list. It costs (essentially) nothing, so enable `C` always (except for the probing of the compiler)

4) Simplify / modernize disabling find_package's for disabled options.

5. `+grid` of `0.6.0` does not compile with gcc-13: It misses `iostream` includes.

6. `+test` requires `googletest` at `build` time: `gtest` is a linked library, not a plugin or tool.
7. `0.6.0+cuda` requires `kokkos@3.7:`, see the releases page on of cabana for the GitHub repo

8. As `0.6.0+grid` does not support `gcc-13` and newer, I think it is good to add cabana@0.6.1 and cabana@0.7.0.
   (`0.7.0+cuda` needs `kokkus@4.1:`, which is mentioned on https://github.com/ECP-copa/Cabana/releases and is added in commit 7 as a preparation for when 0.7.0 is added.

Notes:

Cabana has `tags = ["e4s", "ecp"]` - I guess these use tagged versions and should still use the version they used before?

Is `cabana@0.7.0` by default fine for you?

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants cabana all
-- linux-ubuntu22.04-skylake / clang@14.0.0 ---------------------
all@0.9.2~fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2~fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.1~all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0~all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0~all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
all@0.9.2+fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2+fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.0~all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
all@0.9.2~fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2+fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
all@0.9.2~fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2+fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.0~all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
all@0.9.2~fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2+fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.0~all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1~all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples+grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0~all~arborx~cajita~cuda~examples+grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
all@0.9.2~fortran~ipo+shared~vtk build_system=cmake build_type=Release generator=make
all@0.9.2+fortran~ipo+shared+vtk build_system=cmake build_type=Release generator=make
cabana@0.6.0~all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all~arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.0+all+arborx~cajita~cuda~examples~grid+hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared+silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.6.1+all~arborx~cajita~cuda~examples~grid~hdf5~heffte~hypre~ipo+mpi~openmp~openmptarget~performance_testing~rocm+serial+shared~silo~sycl~testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid+hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid+hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples~grid+hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid~hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
cabana@0.7.0+all+arborx+cajita~cuda+examples+grid+hdf5~heffte+hypre~ipo+mpi~openmp~openmptarget+performance_testing~rocm+serial+shared+silo~sycl+testing~threads build_system=cmake build_type=Release generator=make
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
build-quality-tools/build_pr_changes.py -b cabana,all -ay
```

**Review by junghans — COMMENTED** [review]
@bernhardkaindl thanks!

**Comment by junghans** [comment]
I guess you could to the same testing for `ALL`, but I will leave that for another time.

**Comment by alalazo** [comment]
We need to rename the package, `all:` is reserved under `packages:` for default settings :sob: I discovered this PR while debugging https://gitlab.spack.io/spack/spack/-/jobs/13700600

**Pull request merged**
