### PR TITLE
Remove last two remaining from external imports

### PR DESCRIPTION
**Pull request by opoplawski**

### CODE REVIEW

**Comment by mathstuf** [comment]
Fine with me, but I think there may be sites which expect 2.6 to work which is why these are there. Not sure though.

**Comment by mathstuf** [comment]
Oh, `external` is put into `PYTHONPATH` and should make them available on those systems.

**Comment by opoplawski** [comment]
RIght, once upon a time there was "from external import ..." everywhere, but now external is added to the path and that was removed in most places except for these.

I'll also note that the newer argparse is needed with python 2.7 due to missing support for the keyword "aliases" to add_parser()

**Comment by tgamblin** [comment]
@opoplawski: thanks!

**Pull request merged**
