### PR TITLE
Added entry to support rocky8

### PR DESCRIPTION
**Pull request by fspiga**
Added entry to support rocky8 OS explicitly (which is better!)

This committ superseed #31942.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Removing the `ncurses` variant means the statement that checks and updates the `LD_LIBRARY_PATH` at line 153-154 are no longer relevant.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Highlighting need to make `ncurses` dependency and library path changes consistent.

**Review by OliverPerks — APPROVED** [review]
Ah ok, if this is sufficient then that is a much easier way of doing things.

**Comment by tldahlgren** [comment]
@fspiga @OliverPerks Apologies.  I had variants on my mind at the time I associated the dependency with the library path change.  

How would `ncurses` appear as part of the spec for the package?  Is there an expectation it would be provided as an explicit dependency when needed?

**Comment by fspiga** [comment]
By making sure the right package for the target OS is used (or the right proxy if Arm Ltd does not provide a native binary built), the `ncurses` dependency is no longer needed. My first fix worked as well but it was not generic enough and it could introduce an unnecessary dependency carried forward on packaged built with Arm compiler using spack.

The current default is set for RHEL7. Maybe too old (?) for many OS that are originated/forked from RHEL/CentOS. Maybe worth bumping to RHEL8? @OliverPerks

**Comment by tldahlgren** [comment]
> By making sure the right package for the target OS is used (or the right proxy if Arm Ltd does not provide a native binary built), the `ncurses` dependency is no longer needed. My first fix worked as well but it was not generic enough and it could introduce an unnecessary dependency carried forward on packaged built with Arm compiler using spack.
> 
> The current default is set for RHEL7. Maybe too old (?) for many OS that are originated/forked from RHEL/CentOS. Maybe worth bumping to RHEL8? @OliverPerks

Just so I'm clear.  Does NOT explicitly adding `ncurses` to the `LD_LIBRARY_PATH` work properly?  If so, I'll approve and merge this PR.

**Comment by alalazo** [comment]
The package is now called `armpl-gcc` and supports rocky8, so this was incorporated at some point.

**Pull request closed without merging**
