### PR TITLE
Boost: add version 1.81.0

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — DISMISSED** [review]

**Comment by hainest** [comment]
@alalazo The change here didn't break the pipeline. I need to try to fix that PCH issue with %oneapi so we don't have to keep dealing with it on all of the Boost changes.

**Comment by alalazo** [comment]
Can we work around that PCH issue for oneapi, until a proper fix is ready?

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by hainest** [comment]
@alalazo The Dyninst build failure in ci/gitlab-ci is a known issue and has been fixed in dyninst/master. We can merge here.

**Comment by alalazo** [comment]
Ok, can you constrain the version of boost that `dyninst` can use in this PR, so that pipelines pass? After that this is mergeable.

**Comment by hainest** [comment]
>Ok, can you constrain the version of boost that dyninst can use in this PR, so that pipelines pass? After that this is mergeable.

It's not a Boost issue, it's an STL one. Newer versions of gcc and clang have cleaned up the transitive includes of their STL headers. There are a couple of places in Dyninst that were affected by this.

**Comment by alalazo** [comment]
> It's not a Boost issue, it's an STL one. Newer versions of gcc and clang have cleaned up the transitive includes of their STL headers. There are a couple of places in Dyninst that were affected by this.

Do we know why this built in the first place then?[^1] I'd like to double check why dyninst was :heavy_check_mark: at some point, before force merging something that will break CI on `develop`.

[^1]: I didn't look at the logs in the previous comment, and thought it was a known incompatibility between recent boost and dyninst

**Comment by hainest** [comment]
@alalazo The pipeline stall here will be fixed by #35630

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by hainest** [comment]
@alalazo Boost 1.82.0 is coming out next week. This is working now, so we can merge. Thanks for the help!

**Comment by alalazo** [comment]
Thanks @hainest !

**Pull request merged**
