### PR TITLE
llvm: use ninja by default

### PR DESCRIPTION
**Pull request by haampie**
Now that we don't invoke `make` by hand anymore, we can switch to ninja

### CODE REVIEW

**Comment by trws** [comment]
I want this too, but you missed the `make()` calls in the `post_install` hook to build the `libomptarget` runtime libraries when cuda is enabled.  It works fine if you switch those two to ninja calls.  Would be better if we used `cmake --build` instead, but we currently don't require a high enough cmake version to be sure that's available, so up to you, but one of those two things needs to happen before we can merge this.

**Comment by haampie** [comment]
@trws actually the cmake invocation doesn't work for me because it finds system cmake :(

```
-- Found LLVM 12.0.0
-- Using LLVM in: /opt/cray/pe/cce/12.0.2/cce-clang/x86_64/lib/cmake/llvm
```

**Review by trws — DISMISSED** [review]
Oof... that's... I'm not sure if that's a bug or just a problem, but we should find a solution to that.  Especially in a cmake package shouldn't it resolve to the dependency? Either way, I'm happy with your update here, I'll set auto-merge in a second.

**Comment by haampie** [comment]
I've pushed another commit I'm testing right now

**Comment by haampie** [comment]
@trws it's better than it used to be albeit not working, should we get this change in to enable ninja and solve the openmp-not-as-rutnime problem elsewhere?

The issue I'm hitting is likely that AddLLVM defines openmp interface targets, and they can't be overridden during the build of openmp with clang.

**Review by trws — APPROVED** [review]
LGTM

**Pull request merged**
