### PR TITLE
iq-tree: add new version delete duplicate package

### PR DESCRIPTION
**Pull request by snehring**
Version bump for iq-tree.

Following up on what I briefly talked about in #43442 I'd like to get us down to one iqtree package to avoid confusion.

### CODE REVIEW

**Comment by snehring** [comment]
I need to add auditing to my prehook in addition to style

**Comment by tldahlgren** [comment]
@A-N-Other Are you on board with this change (as a significant contributor within the last year to `orthofinder`?

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version commit and that no other built-in packages are using the soon-to-be-removed `iqtree2`.

I am hoping to hear from @luke-dt and @A-N-Other as well as @ilbiondo before merging.

**Comment by A-N-Other** [comment]
@tldahlgren Perfectly fine with the merger - doesn't make sense to have duplicates

**Comment by tldahlgren** [comment]
I'm going to go ahead and merge.

**Pull request merged**
