### PR TITLE
fix automatic mixing of clang with gfortran 6.3.0 on macOS

### PR DESCRIPTION
**Pull request by davydden**
that is still a terribly ad hoc, but at least it fixes https://github.com/LLNL/spack/issues/3426

### CODE REVIEW

**Comment by adamjstewart** [comment]
Correct me if I'm wrong, but when Spack searches for compilers, it only groups compilers that have matching version numbers, right? Was that the point of #2192 @BarrySmith?

This dictionary is one way to do it, but as you mentioned in [#2192 (comment)](https://github.com/LLNL/spack/pull/2192/files#r85836852), I wonder if it would just be easier to match "anything to anything". What if `fc_version` and `f77_version` just called `default_version` but passed `clang` instead of `gfortran`? Would that work?

As it is now, the code only works if you are using the latest version of clang and GCC 6.2.0 or GCC 6.3.0.

**Comment by davydden** [comment]
> Would that work?

I guess it would and this would be a more robust way of doing it, I will give it a try tomorrow...

**Comment by davydden** [comment]
> to match "anything to anything"

i updated the PR to do this on macOS. Works fine with `gcc6.3` and `clang8.0.0-apple`

**Comment by davydden** [comment]
@BarrySmith could you please check that this does not break your Homebrew usage, if you use a single `clang` on macOS, you could do:
```
spack compiler remove clang
spack compiler find
```

**Comment by davydden** [comment]
this breaks the test:
```
____________________ TestCompilerCommand.test_compiler_add _____________________
self = <spack.test.cmd.test_compiler_cmd.TestCompilerCommand object at 0x115863090>
mock_compiler_dir = '/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pytest-of-travis/pytest-0/test_compiler_add0'
    def test_compiler_add(self, mock_compiler_dir):
        # Compilers available by default.
        old_compilers = set(spack.compilers.all_compiler_specs())
    
        args = spack.util.pattern.Bunch(
            all=None,
            compiler_spec=None,
            add_paths=[mock_compiler_dir],
            scope=None
        )
        spack.cmd.compiler.compiler_find(args)
    
        # Ensure new compiler is in there
        new_compilers = set(spack.compilers.all_compiler_specs())
        new_compiler = new_compilers - old_compilers
        assert new_compiler
        c = new_compiler.pop()
>       assert c.version == Version(test_version)
E       assert Version('7.3.0-apple') == Version('4.5-spacktest')
E         Use -v to get the full diff
```

**Comment by BarrySmith** [comment]
> @BarrySmith could you please check that this does not break your Homebrew usage,

@davydden Unfortunately it does not even detect the clang compilers period! I used git bisect and found

`e727f56d89ccd2aa9aabc14cf4efb471f32341dc is the first bad commit`

In other words before this bad commit I would get 

```
==> Added 3 new compilers to /Users/barrysmith/.spack/darwin/compilers.yaml
    gcc@6.3.0  gcc@4.2.1  clang@8.0.0-apple
```

Afterwards I get 

```
==> Added 3 new compilers to /Users/barrysmith/.spack/darwin/compilers.yaml
    gcc@6.3.0  gcc@4.2.1
```

The "bad" commit it is pretty big so I don't know where to start in determining how the commit made clang unfindable.

**Comment by adamjstewart** [comment]
@scheibelp

**Comment by scheibelp** [comment]
@BarrySmith 

I want to be 100% sure, does your output in fact look exactly like:

```
==> Added 3 new compilers to /Users/barrysmith/.spack/darwin/compilers.yaml
    gcc@6.3.0  gcc@4.2.1
```

I would have expected it to look like:

```
==> Added 2 new compilers to /Users/barrysmith/.spack/darwin/compilers.yaml
    gcc@6.3.0  gcc@4.2.1
```

Also: is there an entry for clang in ```/Users/barrysmith/.spack/compilers.yaml``` (which omits the ```darwin``` prefix)? If so, can you try manually removing it and check whether ```spack compiler find``` finds clang for you?

Thanks

**Comment by scheibelp** [comment]
> I can drop the last commit and keep the current stage. Or feel free to do that when merging...

@davydden from examining the test I think it's more of an issue with the test than your commit: the logic in the test is adding compilers from system paths in addition to the mocked-up paths; ```new_compiler``` consists of multiple compilers but the test expects that whatever one it happens to pull off will be the mocked-up one. If you replace:

```
        c = new_compiler.pop()
        assert c.version == Version(test_version)
```

with

```
assert len(x for x in new_compiler if str(x.spec) == "gcc@%s" % test_version)
```

then I think the test would succeed.

**Comment by davydden** [comment]
@scheibelp  thanks for reply, i will try to adjust the unit test.

**Comment by davydden** [comment]
the tests pass locally for me, this should be ready.

**Comment by tgamblin** [comment]
@davydden: did they pass?

**Comment by davydden** [comment]
@tgamblin yes:
```
$ spack test compiler_cmd
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 2.7.10, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/davydden/spack, inifile: pytest.ini
collected 525 items

lib/spack/spack/test/cmd/test_compiler_cmd.py ..

========================================================================================================================= slowest 20 test durations ==========================================================================================================================
0.46s call     lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_add
0.26s call     lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_remove
0.03s setup    lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_remove
0.01s setup    lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_add
0.00s teardown lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_add
0.00s teardown lib/spack/spack/test/cmd/test_compiler_cmd.py::TestCompilerCommand::test_compiler_remove
============================================================================================================================ 523 tests deselected ============================================================================================================================
================================================================================================================== 2 passed, 523 deselected in 2.88 seconds ==================================================================================================================
```
but most of them appears to be de-selected on macOS. Anyway, the problematic one is selected as it was failing originally.

**Pull request merged**
