### PR TITLE
Golang new

### PR DESCRIPTION
**Pull request by trws**
This PR includes:
* a new go package that uses gccgo to bootstrap the go toolchain
* env support added to Executable
* a new Go fetch strategy that uses `go get` to fetch a package and all
  of its deps
* A platinum searcher package that leverages the new go package and
  fetch strategy

### CODE REVIEW

**Comment by trws** [comment]
@tgamblin @alalazo: Coveralls is killing me for introducing line-breaks in core packages, specifically line-breaks that exist only to appease flake8.  Is this intentional?

**Comment by tgamblin** [comment]
@trws: The coveralls check isn't mandatory.  Though everyone is getting confused b/c it still appears as a big red X.  I'm not concerned about -0.2% coverage.

**Comment by tgamblin** [comment]
@trws: I have relaxed the coveralls requirements.

**Comment by trws** [comment]
Unless there are travis issues, or comments to address, this one should be good to go.  It's not ideal, in that it really should depend on an external go compiler, but for now go can bootstrap itself by compiling go 1.4 as the go-bootstrap package then build an actual current version.  Comes with two useful packages, pt and hub.

**Pull request merged**
