### PR TITLE
Add Code QL to the analysis we perform on code

### PR DESCRIPTION
**Pull request by alalazo**
This new workflow provides checks and static analysis for our codebase. See [here](https://github.com/spack/spack/security/code-scanning?query=ref%3Arefs%2Fpull%2F25129%2Fmerge+tool%3ACodeQL) an example of the results.

### CODE REVIEW

**Comment by tgamblin** [comment]
A lot of these results look really helpful. Some of them are in externals though so I think we should make the scanner ignore those directories.

**Comment by tgamblin** [comment]
Seems like we should use this, but I’m assuming we need to fix everything before merging, right?  @adamjstewart should check this out.

**Comment by alalazo** [comment]
I agree it's really helpful. There are a lot of false positives too related to package directives. I think the static analyzer can't cope with out use of metafunction in that area.

**Comment by alalazo** [comment]
Converted to draft until I check how to configure the analysis to skip certain things e.g. directives in packages.

**Comment by adamjstewart** [comment]
Is Code QL a wrapper around bandit or a competitor of bandit? I played around with bandit a bit and reported a bunch of issues on Slack, but no one seemed interested.

**Comment by alalazo** [comment]
@adamjstewart It's a competitor, see [here](https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) and [here](https://securitylab.github.com/tools/codeql/)

**Pull request closed without merging**
