### PR TITLE
CloverLeaf: Package updates

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
This PR updates the CloverLeaf recipe and adds AOCC related fixes

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
I see that https://github.com/UK-MAC/CloverLeaf is the master repository, that drives the build of all the others. I would keep that as the only one we're using and clone it recursing on submodules. Instead of encoding features in the version name, let's use variants. :slightly_smiling_face:

**Comment by amd-toolchain-support** [comment]
The old `package.py` logic was not accurate since Cloverleaf main page is a place holder pointing to other repositories. 

Submodules are able to downlead only a specific version of each repository, which is hardcoded to an outdated version (i.e., 3 years old "hashed" version for _ref) in Cloverleaf main page. Moreover, more recent versions have been implemented (e.g, v1.3 and master). 

Since the Cloverleaf main page is just a place holder for the real repos (e.g. https://github.com/UK-MAC/CloverLeaf_ref) we'd be inclined to split the packages each of them referring to a specific case. A prototype could be: `spack install cloverleaf_<type>@<version>`

where type is: ref, mpi, cuda, .... and with a package.py header as following:
```
git= "https://github.com/UK-MAC/CloverLeaf_ref"
version("master", branch="master")
version("1.3", commit="0ddf495cf21cc59f84e274617522a1383e2c328c")
version(....)
```

**Comment by alalazo** [comment]
@amd-toolchain-support Thanks for the additional information. It would be good to put that in the description of the PR at some point.

> Since the Cloverleaf main page is just a place holder for the real repos (e.g. https://github.com/UK-MAC/CloverLeaf_ref) we'd be inclined to split the packages each of them referring to a specific case.

That would be fine with me, please ping for another review when done. If in the future we add the ability to have spec dependent sources, we can think of unifying the recipes again.

**Comment by amd-toolchain-support** [comment]
Following the feedback above, a new package for Cloverleaf-ref has been proposed and 
 accepted: https://github.com/spack/spack/pull/39894  
 
The Status of this PR can be updated.

**Comment by alalazo** [comment]
> The Status of this PR can be updated.

Not sure I understand what you mean. In any case, feel free to update the status of the PR.

**Pull request closed without merging**
