### PR TITLE
adios2: correct c-blosc dependency

### PR DESCRIPTION
**Pull request by vicentebolea**
ADIOS2 2.9.0 changed dependency from c-blocs -> c-blosc2.

### CODE REVIEW

**Comment by vicentebolea** [comment]
https://github.com/ornladios/ADIOS2/pull/3715

**Comment by vicentebolea** [comment]
@ax3l it appears that cblosc2 does not build in the openapi spec as shown here: https://gitlab.spack.io/spack/spack/-/jobs/7957954

I added the conflict in the c-blosc2 spec, let me know

**Comment by eugeneswalker** [comment]
Thanks for updating this. Can we merge this today?

**Comment by ax3l** [comment]
C-Blosc2 v.2.10.2 coming via #39537

**Review by ax3l — APPROVED** [review]
LGTM. What is the issue with oneapi and C-Blosc2?

**Comment by ax3l** [comment]
C-Blosc issues w/ OneAPI compilers: https://github.com/Blosc/c-blosc2/issues/546

Looks like a compiler flag to activate SSE3 is missing. Does Spack add `-msse3`?

**Comment by vicentebolea** [comment]
@ax3l Thanks for following up with this issue, I guess that it is good to add this conflict() to the c-blosc2 pkg so that other user do not run into this issues (until it gets resolved)

**Review by bernhardkaindl — APPROVED** [review]
Yeah, until someone can test with -msse3 added, it may be better to add this conflict for `%oneapi`

**Pull request merged**
