### PR TITLE
Add py-geomdl package

### PR DESCRIPTION
**Pull request by adrien-berchet**
This PR adds the geomdl package (https://pypi.org/project/geomdl/).

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Hi @orbingol, as you are the main author of geomdl (or NURBS-python), are you interested in being the official maintainer of this spack package? (it's just the recipe to make your package work in Spack, so there is not much work and it should happen only when you release a new version of your package)

**Review by tldahlgren — COMMENTED** [review]
Confirmed the home page and version sha256.

**Review by adamjstewart — APPROVED** [review]

**Comment by orbingol** [comment]
@adrien-berchet thanks for adding geomdl to spack. I'd prefer someone actively using spack to be the maintainer of the package. It feels like that would be the best. Feel free to contact me if you have any other questions.

**Comment by adrien-berchet** [comment]
> @adrien-berchet thanks for adding geomdl to spack. I'd prefer someone actively using spack to be the maintainer of the package. It feels like that would be the best. Feel free to contact me if you have any other questions.

Ok, no problem, thanks for your answer!

**Pull request merged**
