### PR TITLE
py-s3cmd: Add new versions

### PR DESCRIPTION
**Pull request by Pandapip1**

### CODE REVIEW

**Review by manuelakuhn — COMMENTED** [review]
~~The sha256 are the ones from PyPI and not the ones matching the github url.~~
For spack using the sources fom PyPI is preferred ~~anyway~~, see https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github
Can you convert the package to get the sources from PyPI, please?

(Edit: Sorry, did not see your newest changes when I did the review)

**Review by adamjstewart — APPROVED** [review]
PyPI is preferred, but the package isn't exactly broken by using GitHub, so I don't want to let that conversion hold up this PR. We can always convert in a separate/future PR.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by Pandapip1** [comment]
@spackbot run pipeline

**Pull request merged**
