### PR TITLE
Add fismahigh variant for netcdf-c

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a `fismahigh` variant for the netcdf-c package. This option, which is off by default, is needed to comply with FISMA standards for NOAA/NWS operational forecasting.

### CODE REVIEW

**Comment by skosukhin** [comment]
I would like to hear from the core developers that `FISMA-high compliance` is something that Spack should be concerned with before I agree to this.

My personal opinion is that this can and should be solved with either a site-specific `packages.yaml` file (see [here](https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements)) or a custom package repo (i.e. a package in a custom repo inherits the built-in one and adds extra variants and/or patches) or simply a fork of Spack.

Another option, of course, is to make the upstream developers recognize and address the issue in the package's build system.

**Comment by AlexanderRichert-NOAA** [comment]
Tagging @tgamblin @adamjstewart. I discussed this a bit on Slack with I believe Adam, and I think where we landed is that we want this functionality ultimately to come through the upstream packages. I'll look into submitting feature requests for the various packages.

**Comment by AlexanderRichert-NOAA** [comment]
I'll also add that in this instance, it's less critical to have the fismahigh variant and is more of a convenience; we could just add the `nczarr` and `byterange` variants. For other packages, there's more specific patching/file removal, so I partly did it this way for consistency.

**Comment by adamjstewart** [comment]
I don't know anything about FISMA so I'll let others comment.

**Comment by AlexanderRichert-NOAA** [comment]
I don't think a specific fismahigh variant is needed for this particular package, so I'll create a PR with only the other variants added.

**Pull request closed without merging**
