### PR TITLE
magma: add version 2.7.0

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Review by G-Ragghianti — DISMISSED** [review]

**Review by stomov — DISMISSED** [review]

**Comment by balay** [comment]
@stomov @G-Ragghianti - there is a CI failure with the build of magma@2.7.0 at https://github.com/spack/spack/pull/33794

https://gitlab.spack.io/spack/spack/-/jobs/4282129

Looks like its build errors with magma sources
```
/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/sparse_hip/blas/magma_c_blaswrapper.cpp:175:65: error: use of undeclared identifier 'hipblasFloatComplex'
                                A.num_rows, A.num_cols, A.nnz, (hipblasFloatComplex*)&alpha, descr,
                                                                ^

...
```

[spack-build-out.txt](https://github.com/spack/spack/files/9983028/spack-build-out.txt)

**Comment by G-Ragghianti** [comment]
I believe the error is here:
<code>
hip-5.2.3-clenobypq54ejye3oq64deguukskd7cb/bin/hipcc -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -Dmagma_sparse_EXPORTS -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-build-t2aeaxp/include -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/include -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/control -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/magmablas_hip -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/sparse_hip/include -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/sparse_hip/control -I/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/testing -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/hipblas-5.2.3-cj4xf7ymuzbktrwsq3tjpsluwzn2r2mh/include -isystem /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/hipsparse-5.2.3-rvc4mokvj4vl6ui2q33pcd7x6y52lde2/include -std=c++11 -Wall -Wno-unused-function -O2 -g -DNDEBUG -fPIC -x hip --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 -MD -MT CMakeFiles/magma_sparse.dir/sparse_hip/blas/magma_c_blaswrapper.cpp.o -MF CMakeFiles/magma_sparse.dir/sparse_hip/blas/magma_c_blaswrapper.cpp.o.d -o CMakeFiles/magma_sparse.dir/sparse_hip/blas/magma_c_blaswrapper.cpp.o -c /tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/sparse_hip/blas/magma_c_blaswrapper.cpp
/tmp/root/spack-stage/spack-stage-magma-2.7.0-t2aeaxpcx3bkk4qlvwejt2c4uymgrkjc/spack-src/sparse_hip/blas/magma_c_blaswrapper.cpp:175:65: error: use of undeclared identifier 'hipblasFloatComplex'
                                A.num_rows, A.num_cols, A.nnz, (hipblasFloatComplex*)&alpha, descr,
</code>

**Review by tldahlgren — DISMISSED** [review]
Confirmed the new sha256.

**Comment by tldahlgren** [comment]
Noticing over 6 hours to concretize one of the stacks.

@spackbot run pipeline

**Comment by G-Ragghianti** [comment]
@balay The numerous "spack_path_placeholder" in the path to hipblas look suspicious.  Surely that is not the correct path for your installation?

**Comment by balay** [comment]
> @balay The numerous "spack_path_placeholder" in the path to hipblas look suspicious. Surely that is not the correct path for your installation?

This job is part of spack CI. perhaps this query is for @scottwittenburg 

Note: The same failure is on this PR CI (its still retrying - and not yet marked completed)

https://gitlab.spack.io/spack/spack/-/jobs/4284005

**Comment by scottwittenburg** [comment]
> The numerous "spack_path_placeholder" in the path to hipblas look suspicious

This is deliberate.  The software gets installed into a path with all of those placeholders because we make a binary package from the installation, and want to maximize the probability that when someone relocates it onto their system later, it will really work.  Binary packages can be relocated into a shorter path than it was originally installed to, but not a longer one.

**Comment by G-Ragghianti** [comment]
It appears that a new tar file needs to be created.

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
https://gitlab.spack.io/spack/spack/-/jobs/4321508

```
fatal: unable to access 'https://gitlab.spack.io/spack/spack.git/': Failed to connect to gitlab.spack.io port 443 after 4118 ms: Host is unreachable
```

I guess CI issue

@spackbot run pipeline

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by v-dobrev** [comment]
The updated v2.7.0 (from 25d89d7) worked for me with HIP enabled on LLNL's Tioga machine.

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
This PR is ready for approval and then merge

**Review by stomov — APPROVED** [review]

**Comment by balay** [comment]
Ah - the CI was successful and there was a green check-mark earlier. Now its reset to red  cross :( 
(due an earlier pipeline that just took loner and eventually failed)

And there is one more pipeline  that's hung - I guess we'll have to wait for that to timeout - before starting a new one..

**Review by luszczek — APPROVED** [review]

**Pull request merged**
