### PR TITLE
Updated version of sz3

### PR DESCRIPTION
**Pull request by robertu94**
Supercedes #46128

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the commit.  @disheng222 Do you want to confirm the version directive is all that is needed for the PR?

**Comment by robertu94** [comment]
@tldahlgren I also help maintain SZ3. This is all that is needed

**Comment by tldahlgren** [comment]
> @tldahlgren I also help maintain SZ3. This is all that is needed

Would be good to get you added on the list of maintainers for the package.

**Comment by robertu94** [comment]
Will do.

**Pull request merged**
