### PR TITLE
Implement fish completion

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
This pull request tries to implement completion generation script for `fish`.

https://user-images.githubusercontent.com/65301509/158671430-d3e63fcf-f912-4ad2-a8e8-6c9b16437047.mp4

Because `fish` supports command descriptions, `argparsewriter.py` is changed to add help message to `Command` class.

To-do:
- [x] Remove `'spack'` from `_dest_to_fish_complete` to avoid duplication.
- [x] Check compatibility with old versions of `python`.
- [x] Check compatibility with old versions of `fish`.
- [x] Add comments for new code and scripts.
- [x] `spack activate` should only show installed packages that *have extensions*.

However, it's still hard to implement more detailed completion for specs.
Further improvements may consider use `spack` itself to provide complete results.
For example, `spack complete "spack -v --color" "a"` give results `always auto` .

### CODE REVIEW

**Comment by KiruyaMomochi** [comment]
It finally works...

- However, spec completion looks like a mess. If I have more time, I will consider implementing this feature in python instead, it will be not only cleaner but also easier to test.
- `_dest_to_fish_complete` dict in `commands.py` also looks a bit creepy, but make it a class maybe too completed?
- Also, we may need to refactor `ArgparseWriter` since tuples like `optional` now have 5 elements.

**Comment by adamjstewart** [comment]
I just switched to fish and am very interested in this. What can I do to help?

**Comment by adamjstewart** [comment]
@KiruyaMomochi apologies for taking over your PR. I'm going to start hacking on this and get it to a mergeable state. Trying to wrap my head around all of the stuff @tgamblin and I wrote originally for bash, it's been so long that I barely remember why we designed things this way. I may ask you for help with fish-specific stuff at some point.

**Comment by adamjstewart** [comment]
@tgamblin Design question for you. Fish lets you display a description of each command/flag in the tab-complete menu (see video above). Here, we grab this description from the help string. However, a small number of Spack commands have very long or stylized help strings. For example:
```console
> spack help buildcache
...
    check               Check specs (either a single spec from --spec, or else the full set
                            of release specs) against remote binary mirror(s) to see if any need
                            to be rebuilt.  This command uses the process exit code to indicate
                            its result, specifically, if the exit code is non-zero, then at least
                            one of the indicated specs needs to be rebuilt.
...
> spack help solve
...
  --show SHOW           select outputs: comma-separated list of: 
                          asp          asp program text
                          opt          optimization criteria for best model
                          output       raw clingo output
                          solutions    models found by asp program
                          all          all of the above
```
Some of these even include documentation meant for Sphinx:
```console
> spack help buildcache
...
    sync                Syncs binaries (and associated metadata) from one mirror to another.
                            Requires an active environment in order to know which specs to sync.
                        
                            Args:
                                src (str): Source mirror URL
                                dest (str): Destination mirror URL
```
What would be the best way to support fish completion descriptions without losing help text? We could force all help strings to be at most 1 line long (no newline char). Alternatively, we could do something similar to our package/module support where the first line is (supposed to be) a single standalone sentence and any additional text follows a blank line. Then the description (and maybe even the help string) could be only the first line of the docstring. Thoughts?

**Comment by adamjstewart** [comment]
The tests currently fail because the scripts differ when generated on darwin vs. linux. This is because `--scope` includes platform-specific options. Specifically, lines like this in the completion script are the issue:
```fish
# ['--scope'] -> ['_builtin', 'defaults', 'defaults/darwin', 'system', 'system/darwin', 'site', 'site/darwin', 'user', 'user/darwin', 'command_line']: None
complete -c spack -n "__fish_spack_using_command compiler add" -l scope -r -f -a "_builtin defaults defaults/darwin system system/darwin site site/darwin user user/darwin command_line"
complete -c spack -n "__fish_spack_using_command compiler add" -l scope -r -d "configuration scope to modify"
```
Any ideas how we could avoid this? I can think of some hacky solutions but nothing good. 

EDIT: I ended up removing platform-specific choices from the completion list, but a better solution would be to generate these dynamically. This would require adding a new command/flag to list possible values.

**Comment by adamjstewart** [comment]
@KiruyaMomochi found a bug I could use help in fixing. This works fine:
```console
> spack checksum py-numpy [TAB]
...
```
This results in an error:
```console
> spack checksum [TAB]
usage: spack versions [-h] [-s | --safe-only | -r | -n] [-c CONCURRENCY]
                      package
spack versions: error: the following arguments are required: package
```
The fix is to use:
```fish
complete -c spack -n '__fish_spack_using_command_pos 1 checksum' -f -a '(__fish_spack_package_versions $__fish_spack_argparse_argv[1])'
```
Now I just need to figure out how to do that.

EDIT: that only works for the first positional, it doesn't work past that. A better solution would be to use `__fish_spack_package_versions` for 1+ (not 0) and `__fish_spack_packages` for 0, but I'm not sure if that's possible with the current framework.

**Comment by adamjstewart** [comment]
Trying to use the tab completions in my day-to-day routine. Next issue I noticed:
```console
> spack edit [TAB]
```
suggests packages as expected, but
```console
> spack edit -c [TAB]
```
should suggest paths instead of packages. Same for all other `spack edit` flags. Not sure if it's possible to override things to such a specific level, as each flag needs a different base path.

At this point we're probably good enough for a first implementation. I'd rather get this in soon instead of waiting for perfection. Once #38804 is merged, I'll rebase one last time and start bugging people for review.

**Comment by tgamblin** [comment]
@adamjstewart: 

>  However, a small number of Spack commands have very long or stylized help strings. 

I think this is an artifact of people making functions for subcommands and using the doc strings as argparse help. I think sometimes the functions evolve and people forget that their doctoring is supposed to help argparse.

So, honestly, I would refactor either the way those commands generate their subcommand help text (i.e., don't use the docstring), or change the docstring.  I think you went with the former in #38804 -- I'm fine w/that.

**Comment by adamjstewart** [comment]
I actually went with the latter in #38804. The `spack help` output is still extremely verbose, but it's on a separate line, so I use line breaks to only show the first line in fish tab completion. But I'm open to other suggestions for how to handle them.

**Review by adamjstewart — APPROVED** [review]
I think this is good enough for a first implementation, but want to get a second set of eyes on the code to make sure there isn't an obvious better way to do things.

**Comment by adamjstewart** [comment]
Thanks for the hard work on this @KiruyaMomochi!

**Pull request merged**
