### PR TITLE
py-neptune-client and missing deps: new package

### PR DESCRIPTION
**Pull request by alex391**

### CODE REVIEW

**Comment by alex391** [comment]
@spackbot fix style

**Comment by alex391** [comment]
@spackbot re-run pipeline

**Comment by alex391** [comment]
@spackbot fix style

**Review by tldahlgren — COMMENTED** [review]
Confirmed the homepages and version sha256s for all four new packages.

**Comment by tldahlgren** [comment]
@adamjstewart Do you have time to review this PR?

**Review by bernhardkaindl — APPROVED** [review]
Built successfully on Linux-x86_64.

Beause it does not change existing packages, it is a safe PR to merge.

**Pull request merged**
