### PR TITLE
flecsi: depend on legion@24.03.0: moving forward

### PR DESCRIPTION
**Pull request by rbberger**
Prior FleCSI releases relied on the control-replication branch `cr` of Legion, which got merged into `master`. Each released version was tested up to a certain commit of that branch.

All released versions of FleCSI are now using the last tested commit of Legion cr for that particular version. Moving forward, FleCSI will now depend on Legion releases that contain control-replication, starting with 24.03.0.

People who try to install any of the current FleCSI releases will get a concretization errors unless they specify the exact legion commit via the `^legion@git.<commit>=master` syntax. It's ugly, but that's what we get for relying on unreleased software.

We're planning to get out `flecsi@2.3.0` soon :tm: which will be the first to depend on legion 24.03.0. In the meantime we need this change for our own CI.

### CODE REVIEW

**Comment by rbberger** [comment]
@tldahlgren any idea how I can get it through the audit? it is kind of a special case.

**Comment by rbberger** [comment]
If there is no easy way around it, I'll keep the versions pointing at `master` for now and move the `git.<commit>` parts into its own MR. I can continue working with just 11fb2ce.

**Comment by tldahlgren** [comment]
> If there is no easy way around it, I'll keep the versions pointing at `master` for now and move the `git.<commit>` parts into its own MR.

Since the solver is requiring that the dependency match one of the versions in the package, I suspect the only option is to create the directives in `legion` to correspond to what you need here.

**Comment by tldahlgren** [comment]
Perhaps @alalazo or one of the other core team members can provide better guidance on this one.

**Comment by alalazo** [comment]
I agree with @tldahlgren that a way to fix this is to add ad-hoc versions to `legion`, and depending on those versions in `flexi`. Alternatively we could exclude `git` versions from the audit, but imo we shouldn't encourage using the `git.` syntax in directives.

**Comment by rbberger** [comment]
@tldahlgren @alalazo ok, I've reverted it back to the minimal change moving forward. We'll talk to the Legion folks and see if they're ok adding the "cr" versions for us. That would be its own MR then.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
