### PR TITLE
Multiple package repositories

### PR DESCRIPTION
**Pull request by tgamblin**
@mplegendre: can you review this implementation of package repositories?  I closed your old pull request.

This version builds on your PR and adds a few things:

1. Changed repository layout to look like this:

    ```
        repo_root/
            repo.yaml
            packages/
    ```
    The additional top-level wrapper directory makes a natural place for `repo.yaml` and should leave room for per-repo settings, files, and such later.

2. `repo.yaml` currently contains only a namespace for packages, e.g. for the builtin repo:
    ```yaml
    repo:
        namespace: 'builtin'
    ```
    Namespaces can be nested, e.g. we could use namespaces like `gov.llnl.bdiv` or `gov.nersc.bio`.

3. The loading logic is simpler and it's all consolidated in `repository.py`.  There is `RepoPath`, which implements a list of repositories to search for packages, and there is `Repo`, which is pretty much what `PackageDB` used to be.  Both `Repo` and `RepoPath` are valid Python class importers, so you can stick them in `sys.meta_path`.  

4.`RepoPath` implements an overlay namespace, rooted at `spack.pkg`, so you can import your packages directly from `spack.pkg.<namespace>.  So if you want to extend, say, the builtin `mpich` package, you can do this:
    ```
    import spack.pkg.builtin.mpich
    class Mpich(spack.pkg.builtin.mpich.Mpich):
        ...
    ```
    You can actually play around with this using `spack python` and importing the class.

5. Package namespaces are integrated with `Spec` parsing and concretization.  You can be very specific about what you want to install, e.g. if you have a repo that overlays its own `mpich` on the default one, you can still link to the default one like with an explicit namespace on the command line:
    ```bash
    $ spack install mpileaks ^builtin.mpich
    ```
    Specs without namespaces are bound at the end of concretization based on repo precedence.  Likewise you can do `depends_on('builtin.mpich')` in the package if you want to be specific there.  A spec is unsatisfiable if it contains `mpich` from two different namespaces.

7. `~/.spack/repos.yaml` and `$spack/etc/spack/repos.yaml` determine what repositories are configured.  `$spack/etc/spack/repos.yaml` looks like this by default:

    ```
    repos:
      - $spack/var/spack/repos/builtin
    ```

    That points at the builtin spack package repo.  You can add your own in your `~/.spack/repos.yaml` like this:

    ```
    repos:
      - ~/spack-repos/myrepo
    ```
    This repo will be searched before the default one.  If you want to override **all** settings in the site `repos.yaml`, you can use two `:`'s like this:
    ```
    repos::
      - ~/spack-repos/myrepo
    ```

    And the builtins will not be searched at all.  I expect this case to be rare.

6. `spack repo list` will list configured repositories.
6. `spack repo create` will create an empty repository.

Ok, that is about it.  The only issue I really have is that I am not sure the logic in `config.py` is robust enough to handle adding a `spack repo add` and `spack repo remove` commands with scope arguments.  I can't figure out how to remove stuff just from one scope or another without mnemonics.  I thought not having mnemonics would make repos simpler, but maybe they need them after all, for consistency.  It would be easy enough to always refer to them by root or namespace, though.  Thoughts?

### CODE REVIEW

**Comment by sjtbham** [comment]
I did some basic testing of this and it works as I'd expect. I had to resolve some conflicts to my local merge from develop (config.py - from external import yaml and from external.yaml.error import MarkedYAMLError).

Once I'd done this, I was able to configure a local package repo and override packages in there as well as add a new local package.

**Comment by tgamblin** [comment]
@sjtbham: Thanks!

**Comment by mplegendre** [comment]
This is working for me.

For config scoping in Spack commands, I'd previously had Spack just modify the config files in ~/.spack/ by default.  I figured that was the safest default, as you wouldn't accidentally set config options for other users.

**Comment by tgamblin** [comment]
@mplegendre: That makes sense.  A few things:

1. I think you actually do something a little smarter (maybe too smart?) -- your code looks like it iterates through the config files that contributed to a merged dict, and it modifies the first one it can write, starting with the user dir and moving to higher scopes -- am I understanding that correctly?  I was proposing that we modify this and modify the user home directory by default, and add an arg to the various config commands to set the scope if desired.  e.g. `--user` or `--site`.

2. I am not sure that the way the config merging is done is the easiest way to support this.  It seems to me that we lose the state of individual config files in the current implementation, which makes it hard to tweak one value and write it out.  I was thinking of changing the config logic so that it keeps separate config caches in memory and searches them in precedence order when needed.  Is there a reason this wouldn't work?  The config stuff is pretty sophisticated so I wanted to check with you.

3. Things like `add_to_config` currently want a mnemonic.  Are you ok with not having mnemonics for repos?  Or do you think this simplification is shortsighted?  This affects the config syntax -- it allows me to just list paths or URLs in the config, but it might prevent me from having separate config sections for repos later (e.g. if i wanted to make a repo fetchable from a git URL *and* specify a branch or commit).

**Comment by tgamblin** [comment]
I will merge this after adding better config file logic and the ability to add/remove repos from different scopes on the command line.  That requires some refactoring of `config.py`

**Comment by tgamblin** [comment]
Refactored configuration logic -- now will implement repo add, repo rm, etc.

**Comment by tgamblin** [comment]
@mplegendre This is finally merged!  Sorry it took so long.

**Pull request merged**
