### PR TITLE
crosstool-ng: add new package

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by haampie** [comment]
Do we really want this as a package? Feels like the wrong direction to me

**Comment by alalazo** [comment]
It's just a package... I'm checking the project, so I made a Spack recipe...

**Comment by haampie** [comment]
Sure, but it downloads the same tarballs for packages we have in Spack.

**Comment by alalazo** [comment]
So does `py-pip` or `poetry`? I mean, I not attached to this, but I don't understand the argument on refusing a package...

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage and version sha256, rest LGTM.

**Comment by mwkrentel** [comment]
I'm Ok with the elfutils change, if that was what you were asking.

**Review by mwkrentel — APPROVED** [review]

**Pull request merged**
