### PR TITLE
py-metpy: add version 1.6.2

### PR DESCRIPTION
**Pull request by Chrismarsh**
Add version 1.6.2. Requires many more package version differences, so restructured the depends on for clarity. This also adds the variant to allow for xarray support.

### CODE REVIEW

**Comment by Chrismarsh** [comment]
@spackbot fix style

**Comment by Chrismarsh** [comment]
@spackbot fix style

**Comment by wdconinc** [comment]
`mypy` error in CI is fixed in develop. You may want to rebase to get CI checks to succeed.

**Comment by psakievich** [comment]
@Chrismarsh seeing zero changes on this one?

**Comment by wdconinc** [comment]
> @Chrismarsh seeing zero changes on this one?

Seems like this PR was a duplicate? #46990. @Chrismarsh Please close if this is now redundant.

**Comment by Chrismarsh** [comment]
I don't quite understand how did I that 😬

**Pull request closed without merging**
