### PR TITLE
xsdk: remove 0.2.0 and custom package versions

### PR DESCRIPTION
**Pull request by sethrj**
@balay I would like to remove xsdk 0.2.0 because the existence of special "xsdk" versions complicates version specifications for packages that expect a linear progression of version numbers. (For instance, `trilinos@:11.0` concretizes on develop to `trilinos@xsdk-0.2.0`.) Currently xsdk@0.2.0 won't even install due to missing hypre packages and disabled xsdktrilinos.

This also removes the unused `xsdktrilinos` package -- referenced only in a commented-out line in xsdk, and an inactive github project for four years.

See https://github.com/spack/spack/issues/17145 .

### CODE REVIEW

**Comment by balay** [comment]
> I would like to remove xsdk 0.2.0 

Yeah - these old versions are not tested and don't work anymore - and I think its good to remove. But I think the xsdk group would have to make this decision.

cc: @ulrikeyang @luszczek @jwillenbring

**Review by luszczek — DISMISSED** [review]

**Comment by sethrj** [comment]
OK since this is cool with y'all I'll make sure this works and mark it as non-draft. Thanks!

**Comment by sethrj** [comment]
Ping @balay for reapproval? It looks like the xsdk team has signed off.

**Comment by balay** [comment]
@luszczek is ok with this change - but the group has not discussed this yet. Perhaps in the next meeting (next thu).

**Comment by sethrj** [comment]
> @luszczek is ok with this change - but the group has not discussed this yet. Perhaps in the next meeting (next thu).

OK perfect. Thanks for the update!

**Review by adamjstewart — DISMISSED** [review]
Spack's new semi-official policy is not to remove package versions without first deprecating them. See https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions. I would suggest adding `deprecated=True` to the versions you want to remove, then remove them after Spack 0.17 is released.

**Comment by sethrj** [comment]
> Spack's new semi-official policy is not to remove package versions without first deprecating them. See https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions. I would suggest adding `deprecated=True` to the versions you want to remove, then remove them after Spack 0.17 is released.

The existing versions literally break package version concretization though. The tags don't correspond to actual versions for most packages, and the version of xsdk won't build. Can we leave the old version in just the xsdk package and remove the unusual versions from the other packages?

**Comment by adamjstewart** [comment]
> The existing versions literally break package version concretization though.

If this is the case, then that's not a bad reason to just remove it.

> For instance, `trilinos@:12.1` concretizes on develop to `trilinos@xsdk-0.2.0`

Shouldn't it concretize to `trilinos@12.0.1`? I agree that `@xsdk-0.2.0` _satisfies_ `@:12.1`, although we could modify the package to be `@0:12.1` if needed.

**Comment by sethrj** [comment]
> > For instance, `trilinos@:12.1` concretizes on develop to `trilinos@xsdk-0.2.0`
> 
> Shouldn't it concretize to `trilinos@12.0.1`? I agree that `@xsdk-0.2.0` _satisfies_ `@:12.1`, although we could modify the package to be `@0:12.1` if needed.

Whoops, that was a typo in my description (the git commit message is correct). `spack spec trilinos@:10` does concretize to `trilinos@xsdk-0.2.0` even though the `xsdk` tag is somewhere between `12.10.1` and `12.12.1` I think. I have updated the description, also adding a link to the weird behavior of Version https://github.com/spack/spack/issues/17145 .

The presence of the `xsdk-0.2.0` in `superlu-dist` *also* breaks concretization for older versions of petsc: see https://github.com/spack/spack/pull/9445#issuecomment-645681419 .

**Comment by sethrj** [comment]
@adamjstewart merging this will close #17145, which is still a problem on `develop`:

```console
$ spack solve petsc@3.6.4
petsc@3.6.4%apple-clang@12.0.5~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw~giflib+hdf5~hwloc+hypre~int64~jpeg~knl~libpng~libyaml~memkind+metis~mkl-pardiso~moab~mpfr+mpi~mumps~openmp~p4est~ptscotch~random123~rocm~saws+shared~suite-sparse+superlu-dist~trilinos~valgrind amdgpu_target=none clanguage=C cuda_arch=none patches=da9420ccaeb5f3e9be5fdc87c0fb9544a7629cb2986e01e3f1d9e0156aa38986 arch=darwin-bigsur-x86_64
    ^diffutils@3.7%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
        ^libiconv@1.16%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
    ^hdf5@1.10.7%apple-clang@12.0.5+cxx+fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=darwin-bigsur-x86_64
        ^cmake@3.20.5%apple-clang@12.0.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=darwin-bigsur-x86_64
            ^ncurses@6.2%apple-clang@12.0.5~symlinks+termlib abi=none arch=darwin-bigsur-x86_64
                ^pkgconf@1.7.4%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
            ^openssl@1.1.1k%apple-clang@12.0.5~docs+systemcerts arch=darwin-bigsur-x86_64
                ^perl@5.34.0%apple-clang@12.0.5+cpanm+shared+threads arch=darwin-bigsur-x86_64
                    ^berkeley-db@18.1.40%apple-clang@12.0.5+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=darwin-bigsur-x86_64
                    ^bzip2@1.0.8%apple-clang@12.0.5~debug~pic+shared arch=darwin-bigsur-x86_64
                    ^gdbm@1.19%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
                        ^readline@8.1%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
                    ^zlib@1.2.11%apple-clang@12.0.5+optimize+pic+shared arch=darwin-bigsur-x86_64
        ^openmpi@4.1.1%apple-clang@12.0.5~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=darwin-bigsur-x86_64
            ^hwloc@2.5.0%apple-clang@12.0.5~cairo~cuda~gl~libudev+libxml2~netloc~nvml~pci+shared arch=darwin-bigsur-x86_64
                ^libxml2@2.9.10%apple-clang@12.0.5~python arch=darwin-bigsur-x86_64
                    ^xz@5.2.5%apple-clang@12.0.5~pic libs=shared,static arch=darwin-bigsur-x86_64
            ^libevent@2.1.12%apple-clang@12.0.5+openssl arch=darwin-bigsur-x86_64
            ^openssh@8.1p1%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
    ^hypre@2.13.0%apple-clang@12.0.5~complex~cuda~debug~int64~internal-superlu~mixedint+mpi~openmp~shared~superlu-dist~unified-memory cuda_arch=none arch=darwin-bigsur-x86_64
        ^openblas@0.3.17%apple-clang@12.0.5~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=none arch=darwin-bigsur-x86_64
    ^metis@5.1.0%apple-clang@12.0.5~gdb~int64+real64+shared build_type=Release patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 arch=darwin-bigsur-x86_64
    ^parmetis@4.0.3%apple-clang@12.0.5~gdb~int64~ipo+shared build_type=RelWithDebInfo patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d arch=darwin-bigsur-x86_64
    ^python@2.7.18%apple-clang@12.0.5+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=210df3f28cde02a8135b58cc4168e70ab91dbf9097359d05938f1e2843875e57,7e1bd91333263e2a03e91bcc87bf476d81dae56092903974c1580a78cd9e3411 arch=darwin-bigsur-x86_64
        ^apple-libuuid@1353.100.2%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
        ^expat@2.4.1%apple-clang@12.0.5~libbsd arch=darwin-bigsur-x86_64
        ^gettext@0.21%apple-clang@12.0.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-bigsur-x86_64
            ^tar@1.34%apple-clang@12.0.5 arch=darwin-bigsur-x86_64
        ^libffi@3.3%apple-clang@12.0.5 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-bigsur-x86_64
        ^sqlite@3.35.5%apple-clang@12.0.5+column_metadata+fts~functions~rtree arch=darwin-bigsur-x86_64
    ^superlu-dist@xsdk-0.2.0%apple-clang@12.0.5~cuda~int64~ipo~openmp+shared build_type=RelWithDebInfo cuda_arch=none arch=darwin-bigsur-x86_64
```

**Comment by balay** [comment]
>>   The existing versions literally break package version concretization though.

> If this is the case, then that's not a bad reason to just remove it.

xsdk group discussed this issue and we are in favor of removing this old release.

Also in favor of deprecating other older releases 0.3.0, 0.4.0

cc: @ulrikeyang @luszczek @jwillenbring @balos1

**Review by balay — APPROVED** [review]

**Comment by sethrj** [comment]
@adamjstewart Can you please allow this merge by updating your approval? Thanks!

**Comment by adamjstewart** [comment]
Unfortunately I can't approve unless the versions that are removed are deprecated instead. This is the policy we came up with in https://github.com/spack/spack/discussions/15896 and I'm sticking to it. As for concretization, the clingo concretizer takes deprecations into account, so that shouldn't be an issue. If someone else wants to merge without my approval, go ahead.

**Comment by tgamblin** [comment]
I agree with @adamjstewart in general but xSDK has always been a special case because the maintainers and members are learning how best to maintain their packages’ compatibility over time.  I don’t think there are people actively using the `xsdk-x.y.z` versions — they were always namespaced away from other versions, and you wouldn’t think to use them unless you were familiar with xsdk.

I’m curious if we can learn from the compatibility of xsdk packages going forward to come up with better ways to tie sets of packages together in spack, but given that xsdk is a meta-package and that the versions here are really intended to allow the meta-package to certify a set of working configurations, I’m inclined to remove them if xsdk maintainers want that to happen.

I probably wouldn’t say the same thing for other old versions of packages.

**Pull request merged**
