### PR TITLE
py-numpy: add v1.25.0

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/numpy/numpy/releases/tag/v1.25.0

It looks like 1.26 will switch to meson and 2.0 will follow that. Excited to see what changes in 2.0!

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks @adamjstewart.

This may not be mergeable yet due to the many CI failures. Not sure though, I checked a couple and they were all due to:
```
Error: Failed to install intel-tbb due to SystemExit: 1
```
which must be unrelated. May need to fix that though and then re-run the failed jobs?

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by mvandenburgh** [comment]
@spackbot run pipeline

**Pull request merged**
