### PR TITLE
Fix tesseract package

### PR DESCRIPTION
**Pull request by glennpj**
Depends on #24302 
Depends on #24300 

This PR fixes the tesseract package
- add missing dependencies
- build documentation
- build and install java component
- build and install training component

### CODE REVIEW

**Comment by tldahlgren** [comment]
@darmac As the package contributor, would you care to provide feedback on this PR?

**Comment by darmac** [comment]
> @darmac As the package contributor, would you care to provide feedback on this PR?

OK, I'm stun in another project now, I'll find someone to check this patch.

**Comment by glennpj** [comment]
@tldahlgren This has been sitting for a while now.

**Review by alalazo — APPROVED** [review]

**Comment by fubingting** [comment]
> > @darmac As the package contributor, would you care to provide feedback on this PR?
> 
@tldahlgren We are members of the darmac project team, and thanks for the changes to tesseract, we have successfully verified the installation.

**Pull request merged**
