### PR TITLE
neovim: add v0.9.(0|1)

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Comment by albestro** [comment]
Checksums verified ✅

However, few days ago I was going to add this as you proposed, but I ended up with a linking problem:

```bash
undefined reference to `ts_tree_included_ranges'
```

After a small investigation, I found in `tree-sitter` changelog (https://github.com/tree-sitter/tree-sitter/compare/v0.20.7...v0.20.8) that on Nov 4th they added to the public API the above mentioned function (see https://github.com/tree-sitter/tree-sitter/commit/1848d0bc3632ef128d70736695a3fb969f6e0c69).

I was not able to find anything in the release notes of neovim, and apparently this constraint is not enforced by the CMake project.

**My experiments says that `neovim@0.9:` requires `tree-sitter@0.20.8:`.**

Did you experienced anything similar @vmiheer? which version of `tree-sitter` do you have as dependency?

**Review by albestro — CHANGES_REQUESTED** [review]
Actually it seems that from `neovim@0.9:` it requires `tree-sitter@0.20.8`

https://github.com/neovim/neovim/blob/v0.9.0/src/nvim/CMakeLists.txt#L24

In `neovim@0.9.0` release note it is actually reported as

```
deps: Bump tree-sitter to v0.20.8 (https://github.com/neovim/neovim/pull/22663)
```

So, @vmiheer I would ask you to update this PR with this constraint (probably it is not the only one, but for the moment I think it might be ok 😉 ).

(For the records, I don't know why CMake does not complain about it and it just ends up complaining at linking time).

**Comment by vmiheer** [comment]
Updated to depend on new tree sitter. For some reason the build passed for me with older tree sitter. But maybe I wasn't using tree sitter (hadn't configured in vim?).

**Comment by vmiheer** [comment]
> (For the records, I don't know why CMake does not complain about it and it just ends up complaining at linking time).

Because tree sitter seems to create [package-config](https://github.com/tree-sitter/tree-sitter/blob/v0.20.8/tree-sitter.pc.in) and neovim is [not using it](https://github.com/neovim/neovim/blob/release-0.9/cmake/FindTreesitter.cmake) in `FindTreeSitter.cmake`.

**Review by albestro — APPROVED** [review]

**Review by albestro — APPROVED** [review]

**Pull request merged**
