### PR TITLE
Added py-sqlalchemy-stubs package.

### PR DESCRIPTION
**Pull request by hategan**

### CODE REVIEW

**Comment by hategan** [comment]
Thanks @bernhardkaindl

**Comment by bernhardkaindl** [comment]
Hello @hategan, I hope you have no problem from me (force - I squashed your commits) pushing an update to your PR and branch: I've found using `spack install --test=root` that mypy is of course a dependency.

From my own reviews by Adam, spacks python maintainer, I know that you also have to look at the package itself for more dependencies. Added the other one as well, with the indicated versions. (Thanks for your response, just saw it)

**Comment by hategan** [comment]
> Hello @hategan, I hope you have no problem from me (force - I squashed your commits) pushing an update to your PR and branch: I've found using `spack install --test=root` that mypy is of course a dependency.
> 
> From my own reviews by Adam, spacks python maintainer, I know that you also have to look at the package itself for more dependencies. Added the other one as well, with the indicated versions. (Thanks for your response, just saw it)

No problem. Thanks for the help. I just realized I also need to be careful with this WRT two other packages I submitted.

**Review by bernhardkaindl — APPROVED** [review]
LGTM, dependencies and versions checked from setup.py and libraries.io

**Pull request merged**
