### PR TITLE
scotch: default to not installing vendored metis/parmetis

### PR DESCRIPTION
**Pull request by sethrj**
By request of a colleague @sphamil trying to get Scotch working with trilinos and hitting a conflict between its vendored METIS version and an actual external METIS. Another good use case for https://github.com/spack/spack/issues/23616 .

I did verify that no metis/parmetis symbols or headers are installed.

CC @BerengerBerthoul @olesenm

### CODE REVIEW

**Comment by alalazo** [comment]
Is it possible to completely remove vendoring in this package i.e. always require to have `metis` etc. as another package in the DAG? Would it break some workflow if we go that way?

**Comment by sethrj** [comment]
@alalazo i think what scotch needs is an actual build system (cmake or the like) rather than a handwritten makefile... unfortunately I can't be the one to write it and submit upstream 😒

The scotch developers also by default hack Metis to be 64-bit so can't technically rely on a real external by default. Spack has an option to also patch Metis but scotch can't know that...

**Review by alalazo — APPROVED** [review]
Thanks for the explanation on vendoring `metis`. Feel free to merge as soon as you receive the reviews you asked for.

**Comment by sethrj** [comment]
I'm not sure who else is actively involved in maintaining this recipe, so I just pinged a couple of folks in the git history. I'll merge soon if I don't hear from any of them.

**Pull request merged**
