### PR TITLE
shapemapper: adding new version 2.2.0

### PR DESCRIPTION
**Pull request by snehring**
Version update

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
FYI. Confirmed the new version sha256.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by snehring** [comment]
@tldahlgren anything else you'd like to see before merging?

**Comment by tldahlgren** [comment]
> @tldahlgren anything else you'd like to see before merging?

No.

**Pull request merged**
