### PR TITLE
[WIP] Feature/spack clone

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
Hey all:

https://github.com/LLNL/spack/issues/1136

My simple test as of yet is "spack clone --url=https://www.github.com/DavidPoliakoff/trivial"

The methodology:

shallow clone (using GitFetchStrategy) the target repo.
If I don't have a spack repo with a "git" namespace make one (and add it to my list of spack repos)
make a directory with the name of the git repository containing the package I am downloading (1) and put package.py in it
install the package with that name

Things to fix

1) I need to find out how to extract the name of the package from a package.py file rather than using the repo name
2) "spack clone" phrasing makes @tgamblin unhappy. While that brings _me_ joy, I'm still willing to rename the command
3) Versioning. We log that the version is from git, but there's no sign that the package file itself is from git. Should there be?
4-inifinity) the things I'm not thinking of

### CODE REVIEW

**Comment by citibeth** [comment]
I'm confused about a few things here:

1. Does `git clone` create a new package a la `git create`?  Or does it create a new package and then immediately install it?  If the latter, is the package it created supposed to be kept around?

2. When you say "repo", please differentiate between a Spack repo and a git repo --- which I believe  corresponds to a Spack package?  That will make it easier to understand the docs and conversation.  (Or... without this, I don't understand the explanation above).

**Comment by DavidPoliakoff** [comment]
Updated for clarity in "repo."

The intended action is "fetch the package from the given gitrepo, add it to a spackrepo we're reserving for packages obtained this way, then install that package." The package.py stays in the spackrepo in this implementation, I was under the impression that if it didn't that might cause grief for other spack commands.

**Comment by citibeth** [comment]
What does `spack clone` do if the package is already created?  What about
`spack install`?

**Comment by DavidPoliakoff** [comment]
"Spack clone" is going to be "spack install," the name just hasn't changed yet. In the event the package already exists, a new package is pulled down, and install is run on the new package. There's a fair debate as to whether we want to automatically tear down the existing install if the package has changed.

@tgamblin ? My intuition is that we'll want to download, check if the package is already installed, if it has been installed, check if the package file has changed, if it hasn't leave stuff intact, if the package file has changed do a purge and reinstall.

**Comment by tgamblin** [comment]
@citibeth: the packages are namespaced.  So if the package is already created in `builtin` it doesn't matter; all the remotely fetched packages will go in a reserved namespace.  `builtin.foo` is different from `remoterepo.foo`, and that's stored in the provenance for the package.  See the description in #1136... i think it's more clear.

**Comment by DavidPoliakoff** [comment]
Don't have time to do this, closing. Feel free to reopen if anybody else wants to push on it

**Pull request closed without merging**
