### PR TITLE
curl: conflict with gcc on osx

### PR DESCRIPTION
**Pull request by ashermancinelli**
I'm unable to build curl with gcc on osx, [and based on this issue it seems like it's discouraged by the developers](https://github.com/curl/curl/issues/8846).

CC @adamjstewart

### CODE REVIEW

**Comment by adamjstewart** [comment]
What happens if you build `curl tls=openssl %gcc`? From the GitHub issue you link to it seems like `tls=secure_transport` doesn't work with GCC on macOS but other TLS may work.

**Comment by ashermancinelli** [comment]
`tls=openssl` does work - what do you suggest the conflict should be? Something like
```python
conflicts('platform=darwin', when='tls=secure_transport %gcc')
```

**Comment by adamjstewart** [comment]
I would phrase it as:
```python
conflicts('tls=secure_transport', when='%gcc platform=darwin')
```
but all variations of this are equivalent, I think the only thing that changes is the error message format.

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by barracuda156** [comment]
> What happens if you build `curl tls=openssl %gcc`? From the GitHub issue you like to it seems like `tls=secure_transport` doesn't work with GCC on macOS but other TLS may work.

`gnutls` backend will also work. Only Apple one is broken.

**Comment by adamjstewart** [comment]
@ashermancinelli it looks like this PR fell through the cracks. Can you resolve the merge conflicts, or just open a new PR with the one-line change (plus comment)?

**Pull request closed without merging**
