### PR TITLE
intel-oneapi 2024.2.0: added new version to packages

### PR DESCRIPTION
**Pull request by prstrnn**

### CODE REVIEW

**Review by rscohn2 — DISMISSED** [review]
Thanks!

**Comment by rscohn2** [comment]
@eugeneswalker :
I don't think gitlab-ci will pass until e4s moves forward to 2024.2 compilers

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
> I don't think gitlab-ci will pass until e4s moves forward to 2024.2 compilers

After looking some more, it should be ok. MKL 2024.0 has `preferred=true`  so e4s will test that version, not 2024.2.0. We still need to update the compiler in e4s so we can remove the preferred=true and test latest MKL.

**Comment by eugeneswalker** [comment]
> > I don't think gitlab-ci will pass until e4s moves forward to 2024.2 compilers
> 
> We still need to update the compiler in e4s so we can remove the preferred=true and test latest MKL.

Just pushed commit here to upgrade to new 2024.2 CI image. Let's see how it goes.

**Review by rscohn2 — DISMISSED** [review]

**Comment by rscohn2** [comment]
gitlab passed with the old 2024.0 docker image and mkl 2024.0. Now we are using 2024.2 docker and mkl. If it does not work, I will back out so we can merge the 2024.2 release.

**Comment by rscohn2** [comment]
* plasma, internal compiler error: https://gitlab.spack.io/spack/spack/-/jobs/11655092
* lban, internal compiler error: https://gitlab.spack.io/spack/spack/-/jobs/11655123
* charliecloud, ssl timeout, probably transient error: https://gitlab.spack.io/spack/spack/-/jobs/11655124

**Review by rscohn2 — APPROVED** [review]

**Comment by rscohn2** [comment]
I filed internal tickets for lbann and plasma, and disabled them in e4s

**Review by eugeneswalker — APPROVED** [review]
Thanks!

**Pull request merged**
