### PR TITLE
e4s external rocm ci: upgrade rocm stack to v6.0.2

### PR DESCRIPTION
**Pull request by eugeneswalker**
E4S External ROCm CI stack: Upgrade from ROCm 5.7.1 to 6.0.2

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
Looks like there are CI problems.

**Comment by eugeneswalker** [comment]
Closing this in favor of https://github.com/spack/spack/pull/44449

**Pull request closed without merging**
