### PR TITLE
simulationio: New version 9.0.3

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
FYI. I am unable to build with `spack install simulationio@9.0.3`:

```
...
     172    [ 33%] Building CXX object CMakeFiles/SimulationIO.dir/Field.cpp.o
     173    /usr/WS1/dahlgren/releases/spack/lib/spack/env/gcc/g++  -I/usr/WS1/
            dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/h
            df5-1.12.2-7gnnqissoozb5u2wbfpx4brh3iuam77l/include -I/usr/WS1/dahl
            gren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/openm
            pi-4.1.4-ltteffmymmvurth2rzo6pgs3a6mz6mua/include -I/usr/WS1/dahlgr
            en/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/python-
            3.10.8-ilzdwnyddk5jhoiyfx7x4occjnxjpdbr/include/python3.10 -I/var/t
            mp/dahlgren/spack-stage/spack-stage-simulationio-9.0.3-dzza5xp5lwoc
            m7beb2vobjjzjjsznue2/spack-src -I/tmp/dahlgren/spack-stage/spack-st
            age-simulationio-9.0.3-dzza5xp5lwocm7beb2vobjjzjjsznue2/spack-build
            -dzza5xp -I/var/tmp/dahlgren/spack-stage/spack-stage-simulationio-9
            .0.3-dzza5xp5lwocm7beb2vobjjzjjsznue2/spack-src/googletest-release-
            1.8.0/googletest/include -I/var/tmp/dahlgren/spack-stage/spack-stag
            e-simulationio-9.0.3-dzza5xp5lwocm7beb2vobjjzjjsznue2/spack-src/goo
            gletest-release-1.8.0/googletest -O2 -g  -std=gnu++11 -fPIC -MD -MT
             CMakeFiles/SimulationIO.dir/Field.cpp.o -MF CMakeFiles/SimulationI
            O.dir/Field.cpp.o.d -o CMakeFiles/SimulationIO.dir/Field.cpp.o -c /
            var/tmp/dahlgren/spack-stage/spack-stage-simulationio-9.0.3-dzza5xp
            5lwocm7beb2vobjjzjjsznue2/spack-src/Field.cpp
  >> 174    /var/tmp/dahlgren/spack-stage/spack-stage-simulationio-9.0.3-dzza5x
            p5lwocm7beb2vobjjzjjsznue2/spack-src/SimulationIO.i:306: Error: Syn
            tax error in input(3).
  >> 175    make[2]: *** [CMakeFiles/_SimulationIO.dir/SimulationIOPYTHON.stamp
            ] Error 1
  ...
$ spack debug report
* **Spack:** 0.20.0.dev0 (c4923fe3b3ee28ac47311411a631b228aaefef38)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
```

**Comment by eschnett** [comment]
That looks like an error from `swig`. Maybe your version is too new? I'll have a look, and I'll add a version constraint on swig if necessary.

**Comment by eschnett** [comment]
Yes, I am accidentally building with `swig @3` because of some other package's constraints. swig 4 won't work.

**Comment by tldahlgren** [comment]
> Yes, I am accidentally building with `swig @3` because of some other package's constraints. swig 4 won't work.

I was able  to successfully build the package. 🎉 

BTW Just a nit about the space in `swig @3`.  It works but there usually isn't one between the package and sigil.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
