### PR TITLE
Bugfix/compiler find and gfortran fix.

### PR DESCRIPTION
**Pull request by mamelara**
Fix for #1071 Should now tell you when compilers are added when config is empty using compiler add/find and should also find gfortran compilers.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Hmm, this is odd:
```
$ spack config get compilers
compilers: {}
$ spack compiler add /usr/bin
==> Added 1 new compiler to /home/ajstewart/.spack/compilers.yaml
    gcc@5.3.1
$ spack config get compilers
compilers:
- compiler:
    modules: []
    operating_system: fedora23
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@5.3.1
- compiler:
    modules: []
    operating_system: fedora23
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@5.3.1
```

**Comment by mamelara** [comment]
try now @adamjstewart. Hopefully this will be it. Thanks for helping with this!

-Mario

**Comment by adamjstewart** [comment]
I think you forgot the function definition:
```
$ spack compiler find
Traceback (most recent call last):
  File "/home/ajstewart/spack/bin/spack", line 179, in <module>
    main()
  File "/home/ajstewart/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/ajstewart/spack/lib/spack/spack/cmd/compiler.py", line 150, in compiler
    action[args.compiler_command](args)
  File "/home/ajstewart/spack/lib/spack/spack/cmd/compiler.py", line 88, in compiler_find
    init_config=False)
TypeError: add_compilers_to_config() got an unexpected keyword argument 'init_config'
```

**Comment by mamelara** [comment]
d'oh indeed I did

**Comment by adamjstewart** [comment]
Looks much better now. I can't find a way to break it yet, although I only have one compiler installed on my laptop. This is probably safe to merge. Thanks for the fix!

**Comment by tgamblin** [comment]
This is a little hacky, and I'm not quite sure I understand what the bug was, but it works for me.  I'm merging b/c I think this fix needs to get in.  Thanks @mamelara!

**Pull request merged**
