### PR TITLE
[bowtie] added version 1.3.0

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
I can build version `1.2.3` **but not** `1.3.0`.  

Do you have any ideas why the patch for `1.3.0` might fail for `gcc@8.1.0` on `rhel7` `broadwell`?  The output I get is:

```
==> Installing bowtie
==> No binary for bowtie found: installing from source
1 out of 1 hunk FAILED -- saving rejects to file alphabet.cpp.rej
==> Patch $HOME/spack/clean/spack/var/spack/repos/builtin/packages/   bowtie/fix_narrowing_err_1.3.0.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '$HOME/spack/clean/spack/var/ spack/repos/builtin/packages/bowtie/fix_narrowing_err_1.3.0.patch' '-d' '.'
```

**Comment by adamjstewart** [comment]
I don't think the issue has anything to do with the compiler or OS, it's the patch that doesn't apply correctly.

**Review by tldahlgren — APPROVED** [review]
LGTM. I am able to build `1.3.0`.

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Pull request merged**
