### PR TITLE
zlib, openssl: return to `http` URLs

### PR DESCRIPTION
**Pull request by mathstuf**
In #3113, `https` was removed to ensure that `curl` can be bootstrapped without SSL being present. This was lost in #25672 which aimed to use `https` where possible.

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
LGTM, we still have the sha256 to ensure no unverified source gets built.

**Comment by haampie** [comment]
```
> GET /source/openssl-1.1.1d.tar.gz HTTP/1.1
< HTTP/1.1 301 Moved Permanently
< Location: https://www.openssl.org/source/openssl-1.1.1d.tar.gz
```

It doesn't help :man_shrugging:

**Comment by mathstuf** [comment]
Bleh. Not much to be done then :/ . Are there any known deployments with busted SSL pre-bootstrap?

**Comment by haampie** [comment]
We can ask @tgamblin to make `http://mirror.spack.io` a thing, it's OK to use http when we the shasum method is strong enough.

**Pull request merged**
