### PR TITLE
singularity-ce: new package

### PR DESCRIPTION
**Pull request by robert-mijakovic**

### CODE REVIEW

**Comment by robert-mijakovic** [comment]
@alalazo What does the error on documentation mean?
What do I have to add?
I grepped the code but didn't understand what has to be added.
```Warning, treated as error:
Unexpected return code 1 from command Command(command=('spack', 'list'), shell=False, hide_standard_error=False, working_directory='/home/runner/work/spack/spack/lib/spack/docs') (output="==> Error: module 'spack.pkg.builtin.singularityce' has no attribute 'Singularityce'")
make: *** [Makefile:90: html] Error 2
Error: Process completed with exit code 2.```

**Comment by alalazo** [comment]
@robert-mijakovic Apologies, it seems I lost track of this PR. There's #24066 that is talking care of both `singularity` and `singularityce`. Would you mind if we continue the discussion there?

**Comment by robert-mijakovic** [comment]
> @robert-mijakovic Apologies, it seems I lost track of this PR. There's #24066 that is talking care of both `singularity` and `singularityce`. Would you mind if we continue the discussion there?

I think that is fine. This one should then be closed.

**Comment by alalazo** [comment]
> I think that is fine. This one should then be closed.

Thank you.

**Pull request closed without merging**
