### PR TITLE
Build developer-tools pipeline only on manylinux2014

### PR DESCRIPTION
**Pull request by alalazo**
This removes the original developer-tools pipeline built on ubuntu, in favor of the other pipeline built on manylinux. Since now `--reuse` works across OSes, as long as libcs are compatible, there is no need to maintain a duplicate.

### CODE REVIEW

**Comment by trws** [comment]
That sounds right, do you have a pointer to how I can pull in the binary cache to test the current behavior? I want to test a couple specific cases I'm worried about before approving.

**Comment by alalazo** [comment]
Using the latest `develop` 
```console
$ spack mirror add develop-developer-tools-manylinux2014 https://binaries.spack.io/develop/developer-tools-manylinux2014
$ spack buildcache keys --install --trust
```
At that point you should be hitting the buildcache for things like:
```console
$ spack install gcc
```
if you have `glibc` >= 2.17 and at least a `x86_64_v3` uarch.

**Comment by trws** [comment]
Ok, so, I'm not sure this is ready to happen yet.  I wouldn't fight it, but we need to start looking at how to fix the remaining issues here. @tgamblin, @haampie 

I can pull in the bincache, and I can run `gcc --version` and it works.  That's awesome.  The downside is it doesn't actually work to compile anything on Ubuntu 22.04, Arch current, Fedora 40, **Centos 7, Almalinux 8**, or anything else I've yet tried.

Errors:
```console
# Arch current:
 [root@4a240a879a47 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
# Ubuntu 22.04 (my dev workstation)
❯ ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
# Fedora 40
[root@442d631d8418 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
# Centos 7
[root@05056290e549 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
# Centos and almalinux 8
[root@7be1d8f590db curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
```

One of these is different from the others, my ubuntu system had the libmpc it needed to let it actually run `cc1`, and then failed to find the c runtime object files.  Turns out these are in widely varied locations, unlike the loader and libc themselves.  Locations:

* Ubuntu:
  * x32 -> /usr/libx32
  * x86 -> /usr/lib32
  * x86_64 -> /usr/lib/x86_64-linux-gnu
* fedora:
  * x86_64 -> /usr/lib64
* arch:
  * x86_64 -> /usr/lib

Ok, so if I install gcc (which pulls in libmpc and libmpfr on most of these except centos and alma where it doesn't pull in libmpfr and it still wont run) then the load error goes away.  If I then add on `-B <path to crt files>` _then_ it will work and compile something, and the result runs.  On centos 7 and almalinux 8, if I manually install the mpfr-devel package to get the library, it _still_ doesn't work because it's too old by two major versions:

```
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory
[root@f184b5f66fcc curdir]# find / -name 'libmpfr.so*'
/usr/lib64/libmpfr.so.4.1.6
/usr/lib64/libmpfr.so.4
```

To be as close to sure as I can about how TOSS4 would behave without directly running it there, here's my UBI8 session:

```console
❯ dkrit registry.access.redhat.com/ubi8/ubi
[root@e50a5417e2a8 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
[root@e50a5417e2a8 curdir]# dnf install gcc

--- snip
Installed:
  binutils-2.30-123.el8.x86_64                   cpp-8.5.0-20.el8.x86_64                   gcc-8.5.0-20.el8.x86_64
  glibc-devel-2.28-236.el8_9.12.x86_64           glibc-headers-2.28-236.el8_9.12.x86_64    isl-0.16.1-6.el8.x86_64
  kernel-headers-4.18.0-513.24.1.el8_9.x86_64    libgomp-8.5.0-20.el8.x86_64               libmpc-1.1.0-9.1.el8.x86_64
  libpkgconf-1.4.2-1.el8.x86_64                  libxcrypt-devel-4.1.1-6.el8.x86_64        pkgconf-1.4.2-1.el8.x86_64
  pkgconf-m4-1.4.2-1.el8.noarch                  pkgconf-pkg-config-1.4.2-1.el8.x86_64

Complete!
[root@e50a5417e2a8 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory
[root@e50a5417e2a8 curdir]# dnf install mpfr
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:01:54 ago on Wed Apr 24 18:25:47 2024.
Package mpfr-3.1.6-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@e50a5417e2a8 curdir]# ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/gcc test.c
/curdir/opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/bin/../libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory
```

Now, that's a compiler, and it's clearly missing library dependencies we should be including, and needs logic to find the right CRT directory somehow if we want it to work like this rather than distributing the libc.  How does it work for other things? Here are some other tests:

* gh: go binary, works _flawlessly_, love it
* neovim: starts right up on my ubuntu box, dies in a fedora container because libluv is missing, probably need to fix the package, also dies looking for libiconv.so.2 which is probably being provided by glibc on this platform, we'll have to figure out a solve for that because it's not exactly a packaging problem
* fd: seems to work flawlessly everywhere

**Comment by trws** [comment]
More info, if I use patchelf to remove the needed entries for libiconv and libintl from the neovim binary, get the iconv symbols from libc and preload the libintl preloadable lib from arch, then it will start.  These are likely to need some slightly odd special handling.

**Comment by alalazo** [comment]
@trws My bad, I didn't try to compile anything with that. I built myself an `almalinux8` stack and tried it on ubuntu20.04 with success (`cmake`, `gcc`, etc.). For this buildcache I just tried `gcc --version` :grimacing: Will look into these issues asap.

**Comment by haampie** [comment]
didn't read up yet, but for `crt1.o` you need `libc-dev` from the system still (ah, you have that.)

**Comment by alalazo** [comment]
@trws I kind of see the issue, this is one of the cases we decided to postpone in https://github.com/spack/spack/pull/43190#issuecomment-2068185737 I guess. I'm not frequently using redhat devtoolset, but from what I can see in the `ld` we are using is:
```
/opt/rh/devtoolset-10/root/etc/alternatives/ld
```

**Comment by alalazo** [comment]
> and needs logic to find the right CRT directory somehow if we want it to work like this rather than distributing the libc

Wondering if we can solve this with some package specific callback called during relocation? Specifically I'm wondering if we can adjust the specfile according to the location of the C runtime object files.

**Comment by haampie** [comment]
I don't get why you have issues with mpfr, since:

image

With regard to multiarch distros: what doesn't work is using `bash`'s `$MACHTYPE`, since that's `x86_64-pc-linux-gnu` on Ubuntu while the multiarch dir is `x86_64-linux-gnu` (from `gcc -print-multiarch`).

Maybe "easiest" to do a depth 2 scan of glibc's `$prefix` for `crt1.o` and find the elf file with `(EI_CLASS, EI_DATA, e_machine)` matching the current Python process or something, and then replace `crt1.o%s` in the specs file with an absolute path to it.

I vaguely remember that adding a search path with `-B` in a specs file was not possible.

**Comment by alalazo** [comment]
> I vaguely remember that adding a search path with -B in a specs file was not possible.

That would make sense, or at least it is consistent with my current understanding that this option is used by the `driver` to locate other executables etc.

**Comment by haampie** [comment]
Alternatives: `gcc -B ...` on the command line (not spec file) and `LIBRARY_PATH` / `LPATH` as env variables add to `startfile_prefixes`. There are not other options as far as I can see.

So, sounds like the most robust option is to have a post-install-from-cache hook that regenerates the specs files, replacing all libc's startup `crt*%s` bits with their absolute paths :)

**Comment by alalazo** [comment]
Can we come up with a shortlist of abs paths and use `if-exist`:
```
The if-exists spec function takes one argument, an absolute pathname to a file. If the file exists, if-exists returns the pathname. Here is a small example of its usage:
```
?

**Comment by haampie** [comment]
You'd have to exhaustively list all /usr/lib/* dirs which sounds backwards to me.

**Comment by haampie** [comment]
This should solve issues mostly: https://github.com/spack/spack/pull/43839

However, note that the build cache has no `binutils`, and even if it had, gcc would not know where to find it.

**Comment by alalazo** [comment]
I found a way to inject options to the driver, so we can possibly use `-B`:
```
*self_spec:
-isystem /usr/include/x86_64-linux-gnu -B /usr/lib/x86_64-linux-gnu
```
I think we can also simplify a lot our specfile by using tricks like:
```
%rename asm old_asm

*asm:
--special-option %(old_asm)
```
to prepend and the `+` syntax to append

**Comment by haampie** [comment]
Should also add `-B <prefix binutils>/bin` :) edit: that actually works :+1:

**Comment by trws** [comment]
Gcc should include a distribution of binutils if we want it to work properly, if it had it as a build and run dep it should get relocated properly and just go.

**Comment by trws** [comment]
> I don't get why you have issues with mpfr, since:
> 
> image
> 
> With regard to multiarch distros: what doesn't work is using `bash`'s `$MACHTYPE`, since that's `x86_64-pc-linux-gnu` on Ubuntu while the multiarch dir is `x86_64-linux-gnu` (from `gcc -print-multiarch`).
> 
> Maybe "easiest" to do a depth 2 scan of glibc's `$prefix` for `crt1.o` and find the elf file with `(EI_CLASS, EI_DATA, e_machine)` matching the current Python process or something, and then replace `crt1.o%s` in the specs file with an absolute path to it.
> 
> I vaguely remember that adding a search path with `-B` in a specs file was not possible.

I'm not sure how I end up with the mpfr issue, but I certainly do.  Can't get back onto the machine where I installed the stack this instant but I can check later. 

I've been chewing on the crt file thing, and I think we can get the paths to crts based on the path to the libc.  There's no reason that _has_ to hold, but I tried doing `ldd /usr/bin/ls` on a few of the distros, and each of them showed the `libc.so.6` in the same directory where the `crti` and similar files are located.  It might be good enough.

**Comment by trws** [comment]
And just as I send that I get back in.  Here's libtree on the cc1 on my ubuntu machine:

```console
❯ libtree ./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1
./opt/spack/linux-centos7-x86_64_v3/gcc-10.2.1/gcc-13.2.0-bkii2hax6stvitrm2p35eqmwtelasbik/libexec/gcc/x86_64-pc-linux-gnu/13.2.0/cc1
├── libgmp.so.10 [rpath]
├── libmpc.so.3 [rpath]
│   ├── libmpfr.so.6 [rpath]
│   │   └── libgmp.so.10 [rpath]
│   └── libgmp.so.10 [rpath]
├── libmpfr.so.6 [rpath]
├── libz.so.1 [rpath]
└── libzstd.so.1 [rpath]
```

**Comment by haampie** [comment]
looks normal

**Comment by trws** [comment]
It does, but it has a direct dependency on libmpfr.so.6, when RHEL and company only provide .so.4.

**Pull request merged**
