### PR TITLE
intel-tbb add 2021.4, 2021.5, and master branch

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by rscohn2** [comment]
@eugeneswalker : This PR will make TBB build for e4s. It will be difficult to provide a patch for the earlier versions.
```
spack install intel-tbb@2021.6.0-rc1%oneapi
```

**Review by eugeneswalker — DISMISSED** [review]

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
gitlab failures are a problem downloading assets and is not related to the PR.
I will trigger again later in the day.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
There does seem to be some cmake related problem with the new tbb. Investigating

**Comment by mwkrentel** [comment]
@hainest For me, dyninst won't build with anything after 2020.3, which
is getting kinda old.  For example, with intel-tbb 2021.1.1, I get:

```
1 error found in build log:
     157        See the License for the specific language governing permissions and
     158        limitations under the License.
     159    */
     160    
     161    #include "../oneapi/tbb/version.h"
     162    ", but required is at least "2018.6" (found /scratch/krentel/tbb/install/linux-rhel8-zen/gc
            c-8.5.0/intel-tbb-2021.1.1-p745mwghxsw2aktxaigmk32zh44msqdy/include, found components: tbb 
            tbbmalloc)
  >> 163    CMake Error at cmake/ThreadingBuildingBlocks.cmake:116 (message):
     164      TBB not found and cannot be downloaded because build is sterile.
     165    Call Stack (most recent call first):
     166      CMakeLists.txt:39 (include)
     167    
     168    
     169    -- Configuring incomplete, errors occurred!
```

Do you know what's up with this?  IIRC, dyninst also doesn't build
with the oneapi tbb.  You may want to prioritize this.

**Comment by mwkrentel** [comment]
@rscohn2 I'm curious, what does hwloc add to TBB?
Is it necessary, or could there be a variant to turn it off?
It adds a lot of dependencies.

**Comment by rscohn2** [comment]
@spackbot run pipeline

**Comment by rscohn2** [comment]
@hainest : dyninst does not work with newer TBB because dyninst has a findtbb.cmake in its repo that uses a regular expression to extract the version number from a header file. The location of the macros changed and now findtbb is broken. It is possible to update the findtbb for the new location https://github.com/dyninst/dyninst/pull/1292/commits/9407610a6454a577e0b6adcb5733bb3cf12e7643, but a better solution is to delete the ```findtbb.cmake``` from the dyninst repo and rely on the configuration that comes with tbb. You just need to set: ```CMAKE_PREFIX_PATH=/opt/intel/oneapi/tbb/2021.1.1/env/..:```.. and then findtbb will work. If you are sourcing ```setvars.sh```, then it is setting the ```CMAKE_PREFIX_PATH``` for you. I submitted a PR for this: https://github.com/dyninst/dyninst/pull/1292

dyninst and others are holding me back from making the latest onetbb easily available to everyone in spack, so hoping for your help in resolving the issue.

**Comment by rscohn2** [comment]
> @rscohn2 I'm curious, what does hwloc add to TBB?
> Is it necessary, or could there be a variant to turn it off?
> It adds a lot of dependencies.

I expect it is needed for NUMA support. @vossmjp might know if there is a way to avoid the dependence.

**Comment by rscohn2** [comment]
Everything passes now and @eugeneswalker has approved so hoping someone can merge.

**Review by eugeneswalker — APPROVED** [review]

**Comment by hainest** [comment]
@mwkrentel 

>Do you know what's up with this? IIRC, dyninst also doesn't build with the oneapi tbb. You may want to prioritize this.

We don't support newer TBB implementations yet. It's on our TODO list. We're in the process of updating our CMake this month.

@rscohn2 

>dyninst and others are holding me back from making the latest onetbb easily available to everyone in spack, so hoping for your help in resolving the issue.

We're working on updating this as a part of a larger CMake update. Don't let this stop you from updating the tbb* packages.

**Pull request merged**
