### PR TITLE
Make --backtrace show non-SpackError backtraces

### PR DESCRIPTION
**Pull request by haampie**
Currently `--backtrace` only dumps backtraces for `SpackError`s, but that doesn't help with debugging the  LockTimeoutError (which is just an Exception) seen in CI.

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Would it not be sufficient to change line 578 from `if args.debug:` to `if args.debug or args.backtrace:`?  Or pull the setting of `config:debug` out of that if-statement to set if either argument is True.

**Comment by haampie** [comment]
I checked `register_interrupt_handler`, it's dropping you in a Python shell on Ctrl+C which shouldn't happen; I don't really know what the environment tracing is to be honest, but it seems like I don't need that. I was hoping to just get backtraces on all errors with `--backtrace` s.t. Gitlab CI is not too noisy with debug messages, yet does give context when errors happen

**Comment by tldahlgren** [comment]
> I checked `register_interrupt_handler`, it's dropping you in a Python shell on Ctrl+C which shouldn't happen; I don't really know what the environment tracing is to be honest, but it seems like I don't need that. I was hoping to just get backtraces on all errors with `--backtrace` s.t. Gitlab CI is not too noisy with debug messages, yet does give context when errors happen

Yeah, I was afraid of that when I looked up the line, which is why I modified my comment to include pulling out setting `config.debug` based on the args. 

Also, I'm not seeing any obvious place where `spack.error.debug` (line 574) is being used but I didn't do a lot of digging.

**Comment by tldahlgren** [comment]
> > I checked `register_interrupt_handler`, it's dropping you in a Python shell on Ctrl+C which shouldn't happen; I don't really know what the environment tracing is to be honest, but it seems like I don't need that. I was hoping to just get backtraces on all errors with `--backtrace` s.t. Gitlab CI is not too noisy with debug messages, yet does give context when errors happen
> 
> Yeah, I was afraid of that when I looked up the line, which is why I modified my comment to include pulling out setting `config.debug` based on the args.
> 
> Also, I'm not seeing any obvious place where `spack.error.debug` (line 574) is being used but I didn't do a lot of digging.

My only point was that maybe you could skip the global in favor of leveraging `config:debug` as is already being done with `args.debug`.

**Comment by haampie** [comment]
`spack.error.debug` is used to print stacktraces of `SpackError`

> My only point was that maybe you could skip the global in favor of leveraging config:debug as is already being done with args.debug.

It would require a dedicated config value, I think that's not really necessary unless someone asks for that specifically

**Comment by haampie** [comment]
@spackbot help

**Comment by haampie** [comment]
@spackbot rebuild everything

**Review by alalazo — APPROVED** [review]
I'll merge this for now, we can improve it later

**Pull request merged**
