### PR TITLE
gdb: add versions 13.2 and 14.1

### PR DESCRIPTION
**Pull request by wyphan**
SHA sums computed using `spack checksum -a`.

### CODE REVIEW

**Comment by wyphan** [comment]
Tested locally on `linux-ubuntu20.04-zen2`. Both versions confirmed working just fine.

**Comment by robertu94** [comment]
I usually test on CentOS as well. You can do that or I will when I get home.

**Review by alalazo — DISMISSED** [review]
Can you fix the conflict?

**Comment by wyphan** [comment]
@spackbot fix style

**Comment by robertu94** [comment]
@wyphan I tested on CentOS, and everything works fine.  LGTM :)

**Review by robertu94 — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
