### PR TITLE
Add required dependency versions

### PR DESCRIPTION
**Pull request by adamjstewart**
The GCC installation prerequisites state that GCC should be built with certain versions of its dependencies:
https://gcc.gnu.org/install/prerequisites.html

### CODE REVIEW

**Comment by eschnett** [comment]
The required versions of these dependencies changes with the gcc version. Did you choose the minimum of all current gcc versions?

This might better be handled with version-dependent if statement in the `install` function.

**Comment by adamjstewart** [comment]
I just chose the current dependency versions. I'm not even sure how to find dependencies for older versions.

A version-dependent if statement in the `install` function sounds messy to me. I would rather back out this change than add dozens of lines of code for this.

This also affects #339, #343, and #344

**Comment by eschnett** [comment]
The dependencies for each gcc version are documented in the documentation that comes with the compiler's tarball. If you looked at the web, then you might have picked up the dependencies for gcc 6.0, which might be different from gcc 5. (IIRC, in the past there were cases where the allowed version ranges did not overlap.) In particular, newer versions of the dependencies don't always work with older versions of gcc.

**Comment by adamjstewart** [comment]
Looking at the documentation, it appears that the oldest gcc version that's been checksummed (4.5.4) has the same dependency versions as what I used. But if we know that these dependency versions are going to change, I'm not sure how I feel about specifying them. Thoughts?

**Comment by tgamblin** [comment]
Since Spack will use the newest available version when you install, I'm not sure it makes sense to restrict the deps here.  It actually prevents someone from building with older mpfr versions.  I've thought about allowing spec constraints to be recommended or mandatory, but we don't have that feature yet.

I would say that you can just remove the constraints here and keep it flexible for now.  If you want to add a little stability to the versions of the deps themselves, you can add `preferred=True` to `version()` directives in the dependencies.  This will cause Spack to prioritize them *over* the latest version.

**Comment by adamjstewart** [comment]
Alright, I value simplicity and flexibility over making everything bulletproof. Someone would actually have to go out of his/her way to install gcc with non-compatible versions of its dependencies. I'll close this pull request and change any other pull requests in which I constrained the dependency version.

**Pull request closed without merging**
