### PR TITLE
openssl: Update to 1.1.1o

### PR DESCRIPTION
**Pull request by eschnett**
This is a security update.

### CODE REVIEW

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Pull request merged**
