### PR TITLE
Adding OpenMPI CUDA fix requested by Sajid Ali in issue 17322

### PR DESCRIPTION
**Pull request by chchang6**

### CODE REVIEW

**Comment by alalazo** [comment]
@s-sajid-ali

**Comment by s-sajid-ali** [comment]
@hppritcha : This PR adds the functionality described in the https://github.com/spack/spack/pull/15724#issuecomment-606794140

@chchang6 : Apologies for overlooking the above as this might mean some more changes are needed before this PR is accepted.

**Comment by s-sajid-ali** [comment]
Ping @hppritcha

**Comment by alalazo** [comment]
@hppritcha Is this change fine with you?

**Comment by s-sajid-ali** [comment]
This PR solved an issue another user was facing and posted about in the general-slack channel yesterday. Without it spack was complaining about `==> Error: Cannot provide a unique, readable id when the spec is not concretized` when the user tried to install `openmpi` with `ucx+cuda`.

**Comment by alalazo** [comment]
@hppritcha

**Comment by alalazo** [comment]
@hppritcha  @naughtont3 Could you please have a look at this old 1 line PR and check whether it should be merged or closed?

**Comment by hppritcha** [comment]
@alalazo I'm okay with merging this.

**Comment by alalazo** [comment]
@chchang6 If you could rebase, that will help retriggering tests. I will merge as soon as tests are passing.

**Pull request closed without merging**
