### PR TITLE
Fix coreutils configure_args

### LINKED ISSUE #16381: Installation issue: coreutils
coreutils package build failed.
It can be done in earlier spack version ( also coreutils@8.31 )

Error log:
```
$ spack install -v coreutils
==> 8159: Installing coreutils
==> Using cached archive: /home/xiaojun/spack/var/spack/cache/_source-cache/archive/ff/ff7a9c918edce6b4f4b2725e3f9b37b0c4d193531cac49a48b56c4d0d3a9e9fd.tar.xz
==> Staging archive: /tmp/root/spack-stage/spack-stage-coreutils-8.31-4c64dtxsmpap6qqootwwoaq4rlb6pmb4/coreutils-8.31.tar.xz
==> Created stage in /tmp/root/spack-stage/spack-stage-coreutils-8.31-4c64dtxsmpap6qqootwwoaq4rlb6pmb4
==> No patches needed for coreutils
==> 8159: coreutils: Building coreutils [AutotoolsPackage]
==> 8159: coreutils: Executing phase: 'autoreconf'
==> 8159: coreutils: Executing phase: 'configure'
==> Error: TypeError: 'NoneType' object is not iterable

/home/xiaojun/spack/lib/spack/spack/build_systems/autotools.py:294, in configure:
        291        and an appropriately set prefix.
        292        """
        293        options = getattr(self, 'configure_flag_args', [])
  >>    294        options += ['--prefix={0}'.format(prefix)]
        295        options += self.configure_args()
        296
        297        with working_dir(self.build_directory, create=True):

See build log for details:
  /tmp/root/spack-stage/spack-stage-coreutils-8.31-4c64dtxsmpap6qqootwwoaq4rlb6pmb4/spack-build-out.txt

==> Error: Failed to install coreutils due to ChildError: TypeError: 'NoneType' object is not iterable
/home/xiaojun/spack/lib/spack/spack/build_systems/autotools.py:294, in configure:
        291        and an appropriately set prefix.
        292        """
        293        options = getattr(self, 'configure_flag_args', [])
  >>    294        options += ['--prefix={0}'.format(prefix)]
        295        options += self.configure_args()
        296
        297        with working_dir(self.build_directory, create=True):

See build log for details:
  /tmp/root/spack-stage/spack-stage-coreutils-8.31-4c64dtxsmpap6qqootwwoaq4rlb6pmb4/spack-build-out.txt
Traceback (most recent call last):
  File "/home/xiaojun/spack/lib/spack/spack/build_environment.py", line 802, in child_process
    return_value = function()
  File "/home/xiaojun/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/xiaojun/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/xiaojun/spack/lib/spack/spack/build_systems/autotools.py", line 295, in configure
    options += self.configure_args()
TypeError: 'NoneType' object is not iterable
```

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #16381

@darmac @DiegoMagdaleno

### CODE REVIEW

**Comment by DiegoMagdaleno** [comment]
Oh, did I broke it, I am sorry. 

I remember it worked for me, the return function was fine.

**Comment by adamjstewart** [comment]
@DiegoMagdaleno it worked for you because you are on macOS, so the function hits the return statement. For non-macOS users, there is no return statement, so the function returns None, which is not a list, hence the error seen in #16381

**Comment by DiegoMagdaleno** [comment]
Oh I am sorry, I am not new to development, but I am kind of new to open source contributions, I really like Spack, I will make sure to also test on Linux the next time I commit.

You should look into doing what brew does that is testing the formula automatically

**Comment by adamjstewart** [comment]
Yeah, we have plans for package PR testing in the near future, stay tuned!

**Pull request merged**
