### PR TITLE
config:terminal_title:true by default

### PR DESCRIPTION
**Pull request by haampie**
This is a nice feature and people who don't like it are free to disable it

### CODE REVIEW

**Comment by michaelkuhn** [comment]
I'm obviously all for enabling this by default but I'm not sure whether I should review since it's my feature. :smile:

I just finally fixed a cosmetic problem with the feature in #29070, which should probably be merged before enabling it by default.

**Comment by tgamblin** [comment]
Does this work in dash, busy box, etc.?  I'd rather not enable it by default if it spews control characters into the more primitive (but still used) shells.  Also what happens when this is enabled in CI (where I believe the output device presents as a tty but is not actually interactive or in a window)?

**Comment by haampie** [comment]
It's only printing when `sys.stdout.isatty()`, works for me in `sh`.

**Comment by michaelkuhn** [comment]
It should be independent of the shell since the terminal interprets those characters, as far as I know. It also uses the same condition for printing those characters as `TermStatusLine`, which seems to be enabled unconditionally.

**Comment by alalazo** [comment]
Superseded by #37903

**Pull request closed without merging**
