### PR TITLE
FastJet: add optional patch to make random generator thread-local

### PR DESCRIPTION
**Pull request by iarspider**
Requested by the ATLAS experiment

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM.  Contingent on maintainer's concurrence.

**Comment by tldahlgren** [comment]
@vvolkl Just a quick check to make sure you are fine with this change.

**Comment by vvolkl** [comment]
@tdahlgren thanks, looks good to me as well.

**Review by vvolkl — APPROVED** [review]

**Comment by tldahlgren** [comment]
> @tdahlgren thanks, looks good to me as well.

Thanks for checking.

**Comment by tldahlgren** [comment]
Thank you for your contribution!

**Pull request merged**
