### PR TITLE
add some more documentation for non-inclusive version ranges

### PR DESCRIPTION
**Pull request by cosmicexplorer**
### Problem

#26422 removes the `\.99+` suffix many packages append to version strings in order to support non-inclusive range bounds e.g. `1.2 <= v < 2`: previously we had recommended the use of `@1.2:1.2.999` for this, but we now recommend using `@1.2:1`. However, some packages still contain this `\.99+` workaround, and our documentation doesn't explicitly describe the new recommendation.

### Solution
- Fix some `\.99+` bounds that remained after #26422.
- Clarify in documentation how this works, and explicitly say that `\.99+` is deprecated.

### Result
We should be able to reserve `.99` components for actual versions named `.99` instead of using it as a workaround.

### CODE REVIEW

**Comment by cosmicexplorer** [comment]
As mentioned in the linked comment at https://github.com/spack/spack/pull/20258#issuecomment-851217460:

> Still working on this, but no longer have access to push to spack/spack, so will open up a new draft PR! I've made great progress in reducing the implementation logic, but have run into another conundrum, where Version('1.6') < Version('1.6.5'), but Version('1.6') is not also greater than Version('1.6.5'). I now believe this is incorrect, since a Version('1.6') can resolve to e.g. Version('1.6.8'), which is clearly greater than Version('1.6.5'). I will attempt to succinctly describe why this is now a concern in the new PR.

Currently considering the ramifications of making `Version('1.6') > Version('1.6.5')` true -- I believe this is actually necessary to support strict inequalities at all, as well as being the right thing to do, and can be implemented somewhat succinctly -- but I have to verify that first.

**Comment by michaelkuhn** [comment]
> Currently considering the ramifications of making `Version('1.6') > Version('1.6.5')` true -- I believe this is actually necessary to support strict inequalities at all, as well as being the right thing to do, and can be implemented somewhat succinctly -- but I have to verify that first.

The problem with this are packages that do not follow semver. For instance, cube has releases for 4.4, 4.4.2 etc., where 4.4 < 4.4.2. I guess we could also map those to 4.4.0 even though that is not the correct upstream version.

**Comment by haampie** [comment]
We may have to discriminate between `1.6` being the closed-open range `[1.6.0..., 1.7.0...)` and being the closed-closed "range" `[1.6.0..., 1.6.0...]` --  `Version('1.6')` is ambiguous, you'd need something like `Version('1.6', singleton/exact=True/False)` to ensure that the version is really a singleton or a range. (Maybe we should just almost always represent a version as a closed-closed, closed-open, open-closed or open-open range? :thinking:)

**Comment by cosmicexplorer** [comment]
Just redid this PR entirely to completely avoid modifying spec syntax or any logic in `version.py`!

**Comment by cosmicexplorer** [comment]
Just moved a paragraph about version ranges from `version-specifier` to `version-ranges`. @haampie do you think this is good to go?

**Comment by cosmicexplorer** [comment]
This is now largely obviated by the work to make e.g. `spack install python@3.11` work now. Thanks to whoever did that!

**Pull request closed without merging**
