### PR TITLE
enabling test for rccl hsakmt-roct and rocm-opencl

### PR DESCRIPTION
**Pull request by afzpatel**
Installation Commands:
```
spack install rccl 
spack install hsakmt-roct
spack install rocm-opencl
```

Command for running tests:
```
spack test run rccl
spack test run hsakmt-roct
spack test run rocm-opencl
```

Logs:
[rccl-5.4.0-hnv5jvw-test-out.txt](https://github.com/spack/spack/files/10795955/rccl-5.4.0-hnv5jvw-test-out.txt)
[hsakmt-roct-5.4.0-ixttela-test-out.txt](https://github.com/spack/spack/files/10795958/hsakmt-roct-5.4.0-ixttela-test-out.txt)
[rocm-opencl-5.4.0-dubsr2w-test-out.txt](https://github.com/spack/spack/files/10795959/rocm-opencl-5.4.0-dubsr2w-test-out.txt)

Edit:
Hsakmt-roct has been modified to run right after installation in order to prevent llvm-amdgpu dependecy in regular installation.

Command to run installation and test:
`spack install --verbose --test=root hsakmt-roct `

Updated install and test log:
[spack-build-03-install-out.txt](https://github.com/spack/spack/files/10971212/spack-build-03-install-out.txt)

### CODE REVIEW

**Review by srekolam — APPROVED** [review]

**Review by renjithravindrankannath — APPROVED** [review]
LGTM

**Comment by afzpatel** [comment]
Hi @tldahlgren  this pull request is ready to be reviewed by your team

**Comment by afzpatel** [comment]
@tldahlgren

**Review by tldahlgren — APPROVED** [review]
LGTM.  The syntax is changing (hopefully) soon.

**Pull request merged**
