### PR TITLE
easi: add v1.3.0 and master

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
easi package: add new version, update maintainers, change develop version to master to fit with the branch name, add python variant for bindings.

### CODE REVIEW

**Comment by alecbcs** [comment]
@ravil-mobile @krenzland @ThrudPrimrose can you all confirm you'd like to removed as maintainers of the package?

**Comment by Thomas-Ulrich** [comment]
@ravil-mobile @krenzland @ThrudPrimrose Sorry for not asking beforehand, but I supposed that you may not want to get notified for reviewing the package now that you are off to new projects (actually I don't know about  @ThrudPrimrose). Let me know if I should put you back.

**Comment by ravil-mobile** [comment]
> @ravil-mobile @krenzland @ThrudPrimrose can you all confirm you'd like to removed as maintainers of the package?

Hi @alecbcs and @Thomas-Ulrich. Yes. Please, remove me from the maintainers list.

**Comment by Thomas-Ulrich** [comment]
Hi, Could we consider merging?

**Review by bernhardkaindl — APPROVED** [review]
Built on x86_64-linux-gnu

**Pull request merged**
