### PR TITLE
various fixes for macOS high sierra

### PR DESCRIPTION
**Pull request by davydden**
~~it's WIP as I will probably push more fixes (currently building the stack...)~~ I built everything I wanted on High Sierra (`dealii` stack with everything turned on).

~~p.s. Github does not show the last commit here, which is however visible in the "Commits" section as well as in "Files changed".~~

### CODE REVIEW

**Comment by deOliveira-R** [comment]
@davydden I got a:

`==> Warning: Patch file did not exist: /Users/rodrigo/opt/spack/var/spack/stage/spack-stage-xDaGOZ/secure_snprintf.patch`

Is this expected?

**Comment by davydden** [comment]
Hm, looks like an unrelated bug because I copy-pasted the patch from your PR verbatim (modulo “when” part)

**Comment by deOliveira-R** [comment]
True, seems to come from somewhere else. I recloned my fork and reinstalled spack and get the same warning, even though it builds fine.

**Comment by deOliveira-R** [comment]
Thanks for the fix @davydden and all the help @tgamblin. It was great collaborating with you and I learned a lot about spack in the process.

**Comment by davydden** [comment]
@tgamblin ping.

**Comment by davydden** [comment]
@tgamblin @scheibelp  @becker33 ping.

**Pull request merged**
