### PR TITLE
Bugfix: install-time test outputs

### LINKED ISSUE #31920: Verbose option is not working for the install test in math libraries
### Steps to reproduce

After introducing the file install-time-test-log.txt with the test result logs under below commit it is doesn't show the test result with the build logs when we use --verbose in the install command.
https://github.com/spack/spack/commit/0c31ab87c9940465a529a92b9a9fcb6194b7619d
For example with the below command for hipblas@5.1.0 build on the target Mi50 we are not able to see any result for install 
test as below.
`spack install --verbose --test=root hipblas@5.1.0 ^rocsolver@5.1.0 amdgpu_target=gfx906:xnack-`

`
==> Testing package hipblas-5.1.0-ypz3exc
Running build-time tests
('RUN-TESTS: build-time tests [check]',)
==> hipblas: Executing phase: 'install'

`
However we have the result in the file install-time-test-log.txt

### Error message

No error shows indicating the failure if printing in tty

### Information on your system

Mi50 GPUs

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### LINKED ISSUE #32603: Build-time tests aren't visible
### Steps to reproduce

Choose any package for which the build-time tests fail. An easy way to reproduce this is to choose any Python package with minimal dependencies and override `import_modules` to be a list of fake modules:
```python
import_modules = ["foo", "bar"]
```
Then, try to run the build-time tests:
```console
$ spack install -v --test=root foo
```

### Error message

You'll see the full build log, but no build-time tests. All you'll see if that _something_ failed, but there's no way to tell _what_ failed. This is not specific to Python's import tests, it affects all packages. For example, here is the output from an Autotools package:
```
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all-am'.
make[2]: Nothing to be done for `all-am'.
==> Testing package gnutls-3.6.15-xbt76kt
==> [2022-09-11-10:59:24.365028] Running build-time tests
==> [2022-09-11-10:59:24.365144] ('RUN-TESTS: build-time tests [check]',)
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'check'
```
I don't know _why_ `make check` failed, and I don't see any way to find out this information since it isn't visible in the terminal or in the build log. This is not the way things used to be. I would have to do a git bisect to figure out exactly when it changed, but I'm guessing it is related to recent post-install test refactors.

### Information on your system

* **Spack:** 0.19.0.dev0 (16655f1be20ef001851cb5998b0f3e9b3df33147)
* **Python:** 3.9.13
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by tldahlgren**
Fixes #31920 
Fixes #32603 

FYI. @adamjstewart @renjithravindrankannath 

This PR ensures install-time test outputs are more visible by outputting the path to the test log file if the tests fail and ensuring the outputs from the test parts are displayed.

TODO:
- [ ] Add unit tests as needed

An example of a failing test run:

```
$ spack install -v --test=root py-wget
[+] /usr/tce (external python-3.7.2-bsjfnuyca6ktrsoqn2lvh6nbnfhapp4g)
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-pip-22.2.2-apdjyntlfn7axws5ikq3k5hjbha6fefk
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-wheel-0.37.1-56m62hkgf4dshavlsfxpbxfxic5apynq
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-setuptools-65.5.0-rpcafnypsdpwsqmnomixoajk6qu5vxmq
==> Installing py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b
==> No binary for py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b found: installing from source
==> Using cached archive: /usr/WS1/dahlgren/releases/spack/var/spack/cache/_source-cache/archive/35/35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061.zip
==> No patches needed for py-wget
==> py-wget: Executing phase: 'install'
...
Successfully installed wget-3.2
Removed build tracker: '/tmp/dahlgren/pip-build-tracker-zjz2zgcx'
==> Testing package py-wget-3.2-smjdyen
==> [2022-11-08-18:46:29.110297] Running install-time tests
==> [2022-11-08-18:46:29.110461] ('RUN-TESTS: install-time tests [test]',)
==> Error: TestFailure: 2 tests failed.


Command exited with status 1:
    '/usr/tce/bin/python3.7' '-c' 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'



1 error found in test log:
     3    ==> [2022-11-08-18:46:29.110461] ('RUN-TESTS: install-time tests [tes
          t]',)
     4    ==> [2022-11-08-18:46:29.111529] checking import of foo
     5    ==> [2022-11-08-18:46:29.112163] '/usr/tce/bin/python3.7' '-c' 'impor
          t foo'
     6    Traceback (most recent call last):
     7      File "<string>", line 1, in <module>
     8    ModuleNotFoundError: No module named 'foo'
  >> 9    FAILED: Command exited with status 1:
     10       '/usr/tce/bin/python3.7' '-c' 'import foo'
     11   Traceback (most recent call last):
     12     File "<string>", line 1, in <module>
     13   ModuleNotFoundError: No module named 'foo'
     14   
     15     File "/usr/WS1/dahlgren/releases/spack/bin/spack", line 56, in <mod
          ule>



Command exited with status 1:
    '/usr/tce/bin/python3.7' '-c' 'import bar'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bar'



1 error found in test log:
     70        work_dir="spack-test",
     71    ==> [2022-11-08-18:46:29.249450] checking import of bar
     72    ==> [2022-11-08-18:46:29.249973] '/usr/tce/bin/python3.7' '-c' 'impo
           rt bar'
     73    Traceback (most recent call last):
     74      File "<string>", line 1, in <module>
     75    ModuleNotFoundError: No module named 'bar'
  >> 76    FAILED: Command exited with status 1:



/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py:1086, in _setup_pkg_and_run:
       1083        tb_string = traceback.format_exc()
       1084
       1085        # build up some context from the offending package so we can
  >>   1086        # show that, too.
       1087        package_context = get_package_context(tb)
       1088
       1089        logfile = None

See build log for details:
  /var/tmp/dahlgren/spack-stage/spack-stage-py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b/spack-build-out.txt

See install test log for details:
  /var/tmp/dahlgren/spack-stage/spack-stage-py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b/install-time-test-log.txt

23.511u 3.119s 0:40.35 65.9%	0+0k 24+984io 0pf+0w

$ cat   /var/tmp/dahlgren/spack-stage/spack-stage-py-wget-3.2-smjdyen2dyro3cfzsxwvmswmkznibq5b/install-time-test-log.txt
==> Testing package py-wget-3.2-smjdyen
==> [2022-11-08-18:46:29.110297] Running install-time tests
==> [2022-11-08-18:46:29.110461] ('RUN-TESTS: install-time tests [test]',)
==> [2022-11-08-18:46:29.111529] checking import of foo
==> [2022-11-08-18:46:29.112163] '/usr/tce/bin/python3.7' '-c' 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
FAILED: Command exited with status 1:
    '/usr/tce/bin/python3.7' '-c' 'import foo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'

  File "/usr/WS1/dahlgren/releases/spack/bin/spack", line 56, in <module>
    sys.exit(main())
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack_installable/main.py", line 59, in main
    sys.exit(spack.main.main(argv))
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 549, in install
    install_specs(zip(abstract_specs, concrete_specs), install_kwargs, args)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 270, in install_specs
    install_specs_outside_environment(specs, install_kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/cmd/install.py", line 346, in install_specs_outside_environment
    builder.install()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1757, in install
    self._install_task(task)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1291, in _install_task
    pkg, build_process, install_args
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py", line 1209, in start_build_process
    p.start()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_environment.py", line 1070, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 2088, in build_process
    return installer.run()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 1950, in run
    self._real_install()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/installer.py", line 2049, in _real_install
    phase_fn.execute()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/builder.py", line 426, in execute
    callback(self.builder)
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_systems/_checks.py", line 117, in execute_install_time_tests
    builder.pkg.run_test_callbacks(builder, builder.install_time_test_callbacks, "install")
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/package_base.py", line 2661, in run_test_callbacks
    fn()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/builder.py", line 315, in _adapter
    return bind_method()
  File "/usr/WS1/dahlgren/releases/spack/lib/spack/spack/build_systems/python.py", line 171, in test
    work_dir="spack-test",
...
```

And an example from a successful test run:
```
$ spack install -v --test=root py-wget
[+] /usr/tce (external python-3.7.2-bsjfnuyca6ktrsoqn2lvh6nbnfhapp4g)
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-pip-22.2.2-apdjyntlfn7axws5ikq3k5hjbha6fefk
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-wheel-0.37.1-56m62hkgf4dshavlsfxpbxfxic5apynq
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-setuptools-65.5.0-rpcafnypsdpwsqmnomixoajk6qu5vxmq
==> Installing py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b
==> No binary for py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b found: installing from source
==> Using cached archive: /usr/WS1/dahlgren/releases/spack/var/spack/cache/_source-cache/archive/35/35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061.zip
==> No patches needed for py-wget
==> py-wget: Executing phase: 'install'
...
==> Testing package py-wget-3.2-db5npju
==> [2022-11-08-18:48:51.874246] Running install-time tests
==> [2022-11-08-18:48:51.874414] ('RUN-TESTS: install-time tests [test]',)
==> py-wget: Successfully installed py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b
  Fetch: 0.01s.  Build: 7.38s.  Total: 7.39s.
[+] /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b

$ cat /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-wget-3.2-db5npjuvlwvgg34fbiu27sp7psr5pc2b/.spack/install-time-test-log.txt
==> Testing package py-wget-3.2-db5npju
==> [2022-11-08-18:48:51.874246] Running install-time tests
==> [2022-11-08-18:48:51.874414] ('RUN-TESTS: install-time tests [test]',)
==> [2022-11-08-18:48:51.885346] Detected the following modules: ['wget']
==> [2022-11-08-18:48:51.886029] checking import of wget
==> [2022-11-08-18:48:51.886549] '/usr/tce/bin/python3.7' '-c' 'import wget'
PASSED
```

### CODE REVIEW

**Comment by adamjstewart** [comment]
This doesn't seem to be what I want. If I'm reading the output correctly, all this PR does is:

1. Print the name of the file containing the test logs (if the tests fail)
2. Allow ctest_log_parser to run on this file and display errors (if the tests fail)

I also want to see:

3. A live output of the tests as they run (regardless of whether they pass or fail)

This is how we handle the build. We don't just concatenate `spack-build-out.txt` after the build finishes or parse it for errors when things fail, we print it line by line as it's running so devs can see what is working and what isn't.

**Comment by tldahlgren** [comment]
> I also want to see:
> 
> 3. A live output of the tests as they run (regardless of whether they pass or fail)
> 
> This is how we handle the build. We don't just concatenate `spack-build-out.txt` after the build finishes or parse it for errors when things fail, we print it line by line as it's running so devs can see what is working and what isn't.

IIRC There was push-back with doing that for stand-alone tests originally and or after the fact (too much information) but I will revisit that part of the code.

I'm also not sure that one error per test log is right.  There's an extra layer of complexity with the new multi-build system support that I'm still working through.

**Comment by adamjstewart** [comment]
I could understand the pushback if you're running `spack test run` for every package you've ever installed, but for a single package, that's exactly what `--verbose` is intended for. The tests are unlikely to be longer than the actual build.

**Comment by adamjstewart** [comment]
This also relates to #20375 where I requested a `spack test run --verbose` flag.

**Comment by tldahlgren** [comment]
@adamjstewart Is this PR now obsolete with the latest stand-alone test work?

**Comment by adamjstewart** [comment]
Unfortunately the situation is even worse than it was before. `spack install --test=root ...` no longer runs any tests for Python packages. You can confirm this by running `spack install -v --test=root py-wget`. Even if you set `import_modules = ["nonexistent"]`, the install still passes. So I have no way of testing whether or not the verbosity bug was fixed.

**Comment by tldahlgren** [comment]
> @adamjstewart Is this PR now obsolete with the latest stand-alone test work?

Yes.

**Comment by tldahlgren** [comment]
> Unfortunately the situation is even worse than it was before. `spack install --test=root ...` no longer runs any tests for Python packages. You can confirm this by running `spack install -v --test=root py-wget`. Even if you set `import_modules = ["nonexistent"]`, the install still passes. So I have no way of testing whether or not the verbosity bug was fixed.

I worked on and resolved this problem at one point.  I have not found the PR so will dig into my notes more and all the comments in the test refactor PR to see if there is something there.

**Comment by tldahlgren** [comment]
Closing as obsolete after #34236

**Pull request closed without merging**
