### PR TITLE
Add new vtk 9.2.2 release

### PR DESCRIPTION
**Pull request by MicK7**

### CODE REVIEW

**Comment by haampie** [comment]
From the 9.2 release notes

> Python 3.10 is now supported by vtkpython.

That means we need a Python upperbound `@:3.9` for VTK < 9.2, let me add in a separate PR.

**Review by haampie — DISMISSED** [review]

**Comment by MicK7** [comment]
@haampie I integrated your python fix in this PR

**Review by haampie — APPROVED** [review]

**Comment by MicK7** [comment]
@chuckatkins @danlipsa would you have any idea why the ci is failing ?

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
