### PR TITLE
Add cuda 12.4.0 to packages

### PR DESCRIPTION
**Pull request by LiquidPT**
Adding Cuda 12.4.0

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed one of the platform sha256s.

**Comment by tldahlgren** [comment]
Will defer to @Rombur and or @ax3l in case there are other changes that may be needed.

**Comment by LiquidPT** [comment]
Our development cycle is dependent on this updated Cuda version. It's not clear to me what's happening with the gitlab-ci, and in trying to fix that I seem to have cleared the one review I had.

**Comment by fspiga** [comment]
I was looking into https://gitlab.spack.io/spack/spack/-/pipelines/650078, the e4s builds failed. 

But I am confused as
* https://gitlab.spack.io/spack/spack/-/jobs/10313159 fails
* https://gitlab.spack.io/spack/spack/-/jobs/10313055 succeed
But based on names, they seem identical ...

**Comment by LiquidPT** [comment]
This PR seems stuck on build so opening a new one

**Pull request closed without merging**
