### PR TITLE
perl: add 5.36.0

### PR DESCRIPTION
**Pull request by michaelkuhn**
Let's hope this doesn't break anything. :grimacing: (Tested by building git and libfuse@2, which both use autotools, which rely heavily on perl.)

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.  Fingers crossed doesn't break builds.

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
Does perl%nvhpc build? There's been a series of patches to make that work in the past (which i believe were never upstreamed)

**Comment by michaelkuhn** [comment]
> Does perl%nvhpc build? There's been a series of patches to make that work in the past (which i believe were never upstreamed)

I'm not sure. Do you see any failures related to that? CI looks like the usual spurious failures to me.

**Comment by haampie** [comment]
it's not tested in CI ;p

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
> Let's hope this doesn't break anything.

By now you should be more worried CI is breaking *you*

**Comment by michaelkuhn** [comment]
In the last run, I found an actual CI failure since perl doesn't seem to compile on Mac for some reason (I previously missed it due to the spurious failures). Let's see whether the latest version fixes this.

**Comment by haampie** [comment]
mac CI is allowed to fail, there's some very basic packages failing already. I think it's due to rpaths/install_name issues.

**Comment by michaelkuhn** [comment]
This finally passed CI and can be merged. :partying_face:

**Comment by michaelkuhn** [comment]
@tldahlgren @haampie ping :slightly_smiling_face:

**Review by tldahlgren — APPROVED** [review]
The pipeline finally passed.  Yay!

(Re-confirmed the sha256.)

**Pull request merged**
