### PR TITLE
modfiy hip-rocclr references for 4.1.0 and 4.2.0 releases

### PR DESCRIPTION
**Pull request by srekolam**
I found the addition of hip-rocclr is not required for some of the recipes. only rocrand is requiring it .
i built these changes for rocm-4.1.0 and rocm-4.2.0 to check if there are any failures and did not encounter them.
any inputs for additional testing i am okay to do and confirm.
rocm-opencl-runtime is not required as there is another recipe rocm-opencl.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Ping @haampie @arjun-raj-kuppala

**Review by haampie — APPROVED** [review]

**Comment by arjun-raj-kuppala** [comment]
Actually rocclr is a dependency for hip to build. So i guess it will be available in the spec whereever hip is a dependency for any component/recipe. whats the error you are getting for rocrand

**Comment by haampie** [comment]
Yeah, I think this changed after my pr making most rocm packages use the default dependency type (link and build) instead of just build. Spack passes the prefix paths of transient link deps to cmake for you, so this PR should be fine.

**Comment by adamjstewart** [comment]
>  Spack passes the prefix paths of transient link deps to cmake for you, so this PR should be fine.

We should not rely on transient dependencies being linked in. In fact, we've tried changing this in the past, although it had to be reverted. If the package requires a certain dependency, that dependency should be made explicit.

**Comment by haampie** [comment]
> We should not rely on transient dependencies being linked in. In fact, we've tried changing this in the past, although it had to be reverted. If the package requires a certain dependency, that dependency should be made explicit.

Hm, I think the way it works is packages require hip, then they use find_package(hip required) in cmake, which will locate hip's config file, which in turn will look for its own dependencies (hip-rocclr, hsakmt-roct, hsa-rocr-dev, comgr, llvm-amdgpu, rocminfo) using cmake find commands. I'm not sure if any of this is actually linked in or if it's just looking for header files.

Previously all packages would have to depend on internals of the rocm ecosystem with hard to understand names, currently they just depend on `hip`, which looks better.

**Pull request merged**
