### PR TITLE
suite-sparse: Add version 7.3.1

### PR DESCRIPTION
**Pull request by davidedelvento**
@DrTimothyAldenDavis @becker33 (sorry for the false start on the other repo, sigh)

After lots of banging my head on the keyboard I was able to get this version of SuiteSparse to compile in spack. It's not the latest and it's a bit hacky, but still much better than before, and this is the best I can do given my limited understanding of SuiteSparse, its build system and spack.

If either of you have time to improve it, I'd be delighted, but otherwise this should be an improvement compared to current unmaintained state of the affairs.

### CODE REVIEW

**Comment by davidedelvento** [comment]
Pinging the ones who worked most recently and with most relevant contributions (since there is no maintainer)
@alalazo @siko1056 @haampie @eugeneswalker @v-dobrev 

PS: I would address the black style issues, if it said what they were, rather than a blankfaced "black found errors" :(

**Comment by bernhardkaindl** [comment]
@spackbot fix style

**Review by bernhardkaindl — APPROVED** [review]
Built the added version 7.3.1 and the previously latest 5.13 & 5.12 successfully on Ubuntu 22.04.

Did not test with the Intel `tbb` virtual, are there some instructions how to build it with +tbb ?

**Review by bernhardkaindl — APPROVED** [review]
Enabling auto-merge:

Tested it to build the old and new versions, and it is only a minor update compared to the large change with #41738 (convert it to CMake, which needs a lot more changes). Makes working on the update of Julia with #43329 or #41151 easier.

**Comment by davidedelvento** [comment]
Should I create a different PR for https://github.com/davidedelvento/spack/commit/711bd4fac7e79cfda93ebb40e9f38ca9c3c41a66 or can this be updated for it? See https://github.com/spack/spack/pull/43329#issuecomment-2016530442 for details.

@giordano  my tests with 7.2.1 were successful.

**Comment by kuberry** [comment]
These changes break proper linking for clang/gfortran MacOS builds. 

```sh
[100%] Built target CHOLMOD_static
Undefined symbols for architecture arm64:
  "_dgemm_", referenced from:
      _r_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _r_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_numeric in cholmod_super_numeric.c.o
      _r_cholmod_super_lsolve in cholmod_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_super_solve.c.o
  "_dgemv_", referenced from:
      _r_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_lsolve in cholmod_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_super_solve.c.o
  "_dpotrf_", referenced from:
      _r_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _r_cholmod_super_numeric in cholmod_super_numeric.c.o
  "_dsyrk_", referenced from:
      _r_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _r_cholmod_super_numeric in cholmod_super_numeric.c.o
  "_dtrsm_", referenced from:
      _r_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _r_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_numeric in cholmod_super_numeric.c.o
      _r_cholmod_super_lsolve in cholmod_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_super_solve.c.o
  "_dtrsv_", referenced from:
      _r_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _r_cholmod_super_lsolve in cholmod_super_solve.c.o
      _r_cholmod_super_ltsolve in cholmod_super_solve.c.o
  "_zgemm_", referenced from:
      _c_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _c_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_numeric in cholmod_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_super_numeric.c.o
      _c_cholmod_super_lsolve in cholmod_super_solve.c.o
      ...
  "_zgemv_", referenced from:
      _c_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_lsolve in cholmod_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_super_solve.c.o
  "_zherk_", referenced from:
      _c_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _c_cholmod_super_numeric in cholmod_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_super_numeric.c.o
  "_zpotrf_", referenced from:
      _c_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _c_cholmod_super_numeric in cholmod_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_super_numeric.c.o
  "_ztrsm_", referenced from:
      _c_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_l_super_numeric.c.o
      _c_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_numeric in cholmod_super_numeric.c.o
      _z_cholmod_super_numeric in cholmod_super_numeric.c.o
      _c_cholmod_super_lsolve in cholmod_super_solve.c.o
      ...
  "_ztrsv_", referenced from:
      _c_cholmod_super_lsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_l_super_solve.c.o
      _c_cholmod_super_lsolve in cholmod_super_solve.c.o
      _c_cholmod_super_ltsolve in cholmod_super_solve.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libcholmod.5.0.1.dylib] Error 1
make[2]: *** [CMakeFiles/CHOLMOD.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [library] Error 2
==> [2024-03-26-08:34:25.725139] Error: ProcessError: Command exited with status 2:
    'make' '-j10' '-C' 'CHOLMOD' 'library' 'AUTOCC=no' 'CUDA=no' 'CUDA_PATH=' 'CFOPENMP=' 'CFLAGS=-O3 -fPIC' 'FFLAGS=-fPIC' 'F77FLAGS=-fPIC' 'MY_METIS_LIB=-L/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/metis-5.1.0-3oh5yqkkzdjxejh4pxw4ucrwzipy7jyg/lib -lmetis' 'MY_METIS_INC=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/metis-5.1.0-3oh5yqkkzdjxejh4pxw4ucrwzipy7jyg/include' 'BLAS=-L/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/lib -lopenblas' 'LAPACK=-L/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/lib -lopenblas' 'CFLAGS+=-fno-common -fexceptions' 'CMAKE_OPTIONS=-DCMAKE_INSTALL_PREFIX=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/suite-sparse-7.3.1-n4mmsdbdw3susz2conjlzykxboswy2hk -DCMAKE_LIBRARY_PATH=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/suite-sparse-7.3.1-n4mmsdbdw3susz2conjlzykxboswy2hk/lib -DBLA_VENDOR=OpenBLAS -DBLAS_INCLUDE_DIRS=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/include -DLAPACK_INCLUDE_DIRS=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/include -DBLAS_LIBRARIES=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/include -DLAPACK_LIBRARIES=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/openblas-0.3.26-rpu4wfpp54su2w7vxtdanwhjezssv7xg/include' 'INSTALL=/Users/user/spack_latest/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/suite-sparse-7.3.1-n4mmsdbdw3susz2conjlzykxboswy2hk'
```

**Comment by davidedelvento** [comment]
@kuberry thanks for reporting, but can you please be more specific about what are "these" changes? I assume it's not the last one that I made, but the ones that were merged? Was it working before that?

I have no access to ARM or MacOS, so I could not test them, but I was hoping that the CI would have caught anything breaking?

**Comment by kuberry** [comment]
Hi @davidedelvento, I'm currently investigating whether it is changes in the version added or in the Spack recipe configuration.

**Comment by kuberry** [comment]
Looks like `BLAS_LIBRARIES` and `LAPACK_LIBRARIES`, which should be set to library locations, are instead set to the include directory for blas/lapack. 

https://github.com/davidedelvento/spack/blob/70a180c03c94fe0b205b3f3161733c52b852ebdb/var/spack/repos/builtin/packages/suite-sparse/package.py#L241-L242

I'm also concerned that `-DBLA_VENDOR=OpenBLAS`, when blas/lapack are not necessarily provided by that vendor.

I'm able to get it to compile with something like:
```
-DBLAS_LIBRARIES=%s" % (join_path(spec["blas"].prefix.lib, "libopenblas.a"))
```
However, this requires "*_LIBRARIES" requires providing a library location (name included), which differs based on vendor as well as static/shared library.

**Comment by kuberry** [comment]
Alternatively, just not providing `-DBLAS_LIBRARIES` or `-DLAPACK_LIBRARIES` also fixes the issue.

**Comment by kuberry** [comment]
Alternatively, just not providing `-DBLAS_LIBRARIES` or `-DLAPACK_LIBRARIES` also fixes the issue.

@davidedelvento Could you verify whether you are still able to build while removing the `-DBLAS_LIBRARIES` and `-DLAPACK_LIBRARIES`, as well as `-DBLA_VENDOR`? Hopefully we can go back to not providing these pieces of information that are possibly over-specialized and/or break certain builds.

**Comment by davidedelvento** [comment]
Will test this right now.

**Comment by davidedelvento** [comment]
@kuberry -- Thanks! Even without those three lines it seems to compile fine on a fresh Linux_x86_64 spack install, so I updated my branch accordingly. 

However this PR is not reporting that update, let me know if you want me to open a new one, so the CI will trigger, or if you prefer to proceed in other ways.  

Please preserve the 7.2.1 (also not included in the merged PR) you prefer to proceed in other ways, as described in my earlier comment quoted below

> Should I create a different PR for [davidedelvento@711bd4f](https://github.com/davidedelvento/spack/commit/711bd4fac7e79cfda93ebb40e9f38ca9c3c41a66) or can this be updated for it? See [#43329 (comment)](https://github.com/spack/spack/pull/43329#issuecomment-2016530442) for details.
> 
> @giordano my tests with 7.2.1 were successful.

**Comment by kuberry** [comment]
Great, then let's plan to remove those CMake arguments in a PR (I can make it).  What are you referring to with regard to preserving the 7.2.1? I didn't see that version in the recipe.

We can also change `if spec.satisfies("@5.8.0:")` to `if spec.satisfies("@5.8.0:6")` and bring it back.

What about 
```
-        make("-C", "SuiteSparse_config", "config", *make_args)
+        make("-C", "SuiteSparse_config", *make_args)
+        #       make("-C", "SuiteSparse_config", "config", *make_args)
```
?
Did this not compile for you with the "config" argument?

**Comment by davidedelvento** [comment]
@kuberry thanks for offering to make a follow-up PR. That works great for me. Happy to test it in my environment.

Regarding 7.2.1 it's the line https://github.com/davidedelvento/spack/blob/suitesparse/var/spack/repos/builtin/packages/suite-sparse/package.py#L26 which for some reasons github hid from this PR, sigh.

The "config" target is not present anymore in the `SuiteSparse_config` directory at version 7.2.1 and subsequent (and I speculate also other versions), so that needs to stay out for the newer releases (or have some version if-conditions).

I am not sure if you are referring to this config or something else with the 

> We can also change if spec.satisfies("@5.8.0:") to if spec.satisfies("@5.8.0:6") and bring it back.

but sure, avoiding breaking older version sounds the best thing to do. Frankly I was hoping that TimothyAldenDavis would chime in with the exact versions where things changed, because reverse engineering these things is a pain and error prone. But will do the best we can.

**Comment by kuberry** [comment]
7.2.1 hasn't made it into the `develop` branch of Spack yet, but it is in your fork of Spack. Would you like it to also be added to the PR?

**Comment by davidedelvento** [comment]
> 7.2.1 hasn't made it into the `develop` branch of Spack yet, but it is in your fork of Spack. Would you like it to also be added to the PR?

Yes please. That was my complaint, that my pushing to the branch happened a little bit after the PR was merged and therefore that change got "lost" in github's no man land.

**Pull request merged**
