### PR TITLE
sz: fix for external python sitelib

### LINKED ISSUE #25973: Installation issue: sz+python when using external python
### Steps to reproduce the issue

packages.yaml
```
packages:
  python:
    externals:
    - spec: 'python@3.8'
      # configure for module/path to system python paths not writable by user
    buildable: false
```

Install `sz+python` with spack
```
spack install sz+python
```

Error paraphrased
```
Cannot install sz python to <path/to/system/python/modules>, no write permissions
```

### Information on your system

ORNL Spock

* **Spack:** 0.16.2-4028-d27e0bff5a
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information

maintainers: @disheng222 @robertu94 

[spack-build-env.txt](https://github.com/spack/spack/files/7172102/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7172103/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by robertu94**
fixes #25973  Note that currently only sz@master is effected.  A new release will be made at a later date.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by robertu94** [comment]
@adamjstewart this seems to be hung.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by robertu94** [comment]
@tldahlgren is something going on with the gitlab CI. It still seems to be hung

**Comment by robertu94** [comment]
@tldahlgren Gitlab CI still seems to be backlogged.  Is this a CI system failure?

**Comment by tldahlgren** [comment]
> @tldahlgren Gitlab CI still seems to be backlogged. Is this a CI system failure?

Not sure.  We're still having CI failures even when they aren't backlogged so I merged anyway.

**Pull request merged**
