### PR TITLE
make untar remove its input file (like gunzip)

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@scheibelp Please review. A follow up from the uncompress PR. Addresses a difference between untar (leaves the archive unchanged) and gunzip (deletes the compressed file).

**Comment by danlipsa** [comment]
@johnwparent Please review

**Comment by haampie** [comment]
What's the advantage of deleting the archive? If the file cannot be extracted in-place (zipped folders, tarballs) you always pay the price of storing both the archive and its expanded version.

**Comment by danlipsa** [comment]
> What's the advantage of deleting the archive? If the file cannot be extracted in-place (zipped folders, tarballs) you always pay the price of storing both the archive and its expanded version.

On windows, untar can be used as unzip. This option will give unzip an uniform behavior (removing its input file) on all platforms. Removing the input file was already done outside this function, but because of the rename we have to do it inside.

**Comment by johnwparent** [comment]
@scheibelp Current test failures are due to an the `exploding_tarball_handler` treating the intermediate archive as an "exploded tarball" and handling it unexpectedly w.r.t. the test. I can either add a handler to the exploding archive handler, or re-introduce the remove. IMO I'd rather re-introduce the remove as whitelisting feels fragile and the remove is pretty cheap/we're not that worried about performance here AFAIK, but it's your call.

**Comment by scheibelp** [comment]
> I'd rather re-introduce the remove

That sounds sensible to me as well. It would be useful to add a comment explaining why the remove is done.

**Comment by johnwparent** [comment]
> > I'd rather re-introduce the remove
> 
> That sounds sensible to me as well. It would be useful to add a comment explaining why the remove is done.

Pushed

**Review by scheibelp — APPROVED** [review]

**Pull request merged**
