### PR TITLE
spiner: update dependencies

### PR DESCRIPTION
**Pull request by rbberger**
should be merged after #37366

### CODE REVIEW

**Comment by rbberger** [comment]
@spackbot fix style!

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by rbberger** [comment]
@tldahlgren Ping.

**Comment by rbberger** [comment]
@tldahlgren Rebased this now on top of the current develop and added some newer changes.

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
