### PR TITLE
pflotran: tweak for building with xsdk rocm/hip

### PR DESCRIPTION
**Pull request by balos1**

### CODE REVIEW

**Review by balay — APPROVED** [review]

**Comment by balay** [comment]
@ghammond86 perhaps this change can be added to pflotran sources aswell

**Comment by balay** [comment]
@ghammond86 a reminder!

**Comment by ghammond86** [comment]
@balay Do you want this in v5.0.0 or is a patched release sufficient (e.g., v5.0.1)?

**Comment by balay** [comment]
@ghammond86 - here is the suggested fix as a patch
```patch
--- pflotran/src/pflotran/hdf5_aux.F90  2023-11-20 00:11:14.000000000 -0600
+++ spack-src/src/pflotran/hdf5_aux.F90 2023-11-20 12:57:03.607091482 -0600
@@ -1,7 +1,7 @@
 module HDF5_Aux_module
 
 #include "petsc/finclude/petscsys.h"
-  use iso_c_binding
+  use, intrinsic :: iso_c_binding
   use petscsys
   use hdf5
   use h5lt
```

For now this is fixed in spack for 5.0.0 [and xsdk-1.0.0]. 

So will be useful to have it for  future pflotran release [and future xsdk releases. i.e v5.0.0 should be unchanged - and  xsdk doesn't really need 5.0.1 - for now]

[I noticed we had this fix in prior xsdk release - but didn't added it upstream - so it came up again in the current release. Hence trying to make sure the fix is also in upstream sources]

**Comment by ghammond86** [comment]
@balay Done. https://bitbucket.org/pflotran/pflotran/pull-requests/882

**Pull request merged**
