### PR TITLE
veccore: add v0.8.2

### PR DESCRIPTION
**Pull request by wdconinc**
This PR adds `veccore`, v0.8.2 ([release notes](https://github.com/root-project/veccore/releases/tag/v0.8.2)).

### CODE REVIEW

**Review by drbenmorgan — COMMENTED** [review]
SHA fine, so I think good to go once you mark as ready @wdconinc.

**Review by sethrj — DISMISSED** [review]

**Comment by wdconinc** [comment]
I was still wondering about adding the CMake requirements.

**Comment by sethrj** [comment]
```python
    depends_on("cmake@3.16:", type="build", when="0.8.2:")
```
? We have similar for Celeritas.

**Comment by wdconinc** [comment]
> ```python
>     depends_on("cmake@3.16:", type="build", when="0.8.2:")
> ```
> 
> ? We have similar for Celeritas.

Yeah, but the release notes were wrong about 0.8.2 adding the cmake requirement. It was there earlier. That's what I wanted to dig in: why did this get added to these release notes if it was already there? and if it was already there, why didn't we add it to the spack package yet?

**Comment by sethrj** [comment]
@wdconinc :
```
$ git log -S 3.16 CMakeLists.txt
commit 0e991cbef4110370a95927f78cace8456607d21d
Author: Guilherme Amadio <amadio@cern.ch>
Date:   Fri Mar 17 11:01:24 2023 +0100

    Update minimum required CMake version to 3.16

$ git describe 0e991cbef4110370a95927f78cace8456607d21d
v0.8.0-6-g0e991cb
```
so this was a requirement as of 0.8.1. Before that the requirement was CMake 3.9. I'm pushing the update :)

**Review by sethrj — APPROVED** [review]

**Review by sethrj — DISMISSED** [review]

**Review by sethrj — APPROVED** [review]

**Pull request merged**
