### PR TITLE
mesa-glu: add -Wno-register for clang >= 16 to prevent build failure

### PR DESCRIPTION
**Pull request by jbigot**

### CODE REVIEW

**Comment by boomanaiden154** [comment]
This is not an issue with clang 16 specifically. The commit introducing this error came into LLVM in https://github.com/llvm/llvm-project/commit/291027692fe7b10dd8bbafb02750cbed268ddf5f which I believe made it into clang 4. It has to do with the c++ standard version that the project asks for with everything below `-std=c++17` being fine, but you start to get errors once you set `-std=c++17`. The proper way to do this as a compiler flag/version conflict would be to find out which version started selecting c++17 (I wasn't able to find anything though from a quick glance). The other (probably more proper) way to do this is to just patch out the `register` keyword since it is essentially meaningless and causes errors (as done in https://gitlab.freedesktop.org/mesa/glu/-/commit/b6c308172993dfd0f76ee9f4fe083cff8c51ced8 and https://gitlab.freedesktop.org/mesa/glu/-/commit/f9a08d7a10e2ff37cd0424f4bcf9155b116e84cd) and I've written up a similar patch in https://github.com/spack/spack/pull/38833.

**Comment by jbigot** [comment]
I totally agree with you. However I've selected clang>=16 because I don't know of any other compiler that uses C++17+ by default.

It would clearly be better to fix the code, but is it the role of the packaging to introduce code changes in a patch when a simple compiler flag (disabling a warning) can do the trick. Following https://www.debian.org/security/2008/dsa-1571 I was thinking, the less patches in packaging, the better, but I don't know what spack policy is.

**Comment by jbigot** [comment]
another option would be to specify `std=c++14`, but I thought this would be more intrusive and could conflict with user-specified flags.

**Comment by boomanaiden154** [comment]
Ah, true. I should've looked into the default C++ standard revisions by compiler version a bit closer. I'd be interested to know the spack policy as well. The previous package ecosystem I've worked in (Alpine) was fairly liberal with patches, but they still needed to have a purpose. I guess we'll see what the maintainers think the best approach is.

**Comment by boomanaiden154** [comment]
This got pushed to upstream in https://github.com/spack/spack/pull/38833.

**Comment by jbigot** [comment]
no need anymore then

**Pull request closed without merging**
