### PR TITLE
darshan-runtime,darshan-util,py-darshan: add darshan-3.4.5 packages

### PR DESCRIPTION
**Pull request by shanedsnyder**
This PR updates Darshan Spack packages (darshan-runtime, darshan-util, py-darshan) for the Darshan 3.4.5 release.

Note that the location of Darshan release tarballs has also been updated.

### CODE REVIEW

**Review by jeanbez — APPROVED** [review]

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new sha256s and, for the packages with modified `url`s, all of the sha256s.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
According to `pyproject.toml` the setup tools needs to be newer for the latest version (i.e., `py-setuptools@65:`).  See the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#conditional-dependencies for setting up a conditional dependency.

**Review by tldahlgren — COMMENTED** [review]
There appear to be additional test dependencies from `pyproject.toml`.  The full list from that file is:

```
[project.optional-dependencies]
test = [
    "packaging",
    "pytest",
    "lxml",
    "matplotlib",
    "importlib_resources;python_version<'3.9'",
    "humanize"
]
```

**Comment by shanedsnyder** [comment]
@tldahlgren thanks for the review, I think I fixed the issues you found related to dependencies.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
