### PR TITLE
Revert "do out of source builds in hashed directories"

### PR DESCRIPTION
**Pull request by haampie**
Reverts spack/spack#18574

I've been using `spack dev-build` in CI to do multistage docker builds. #18574 breaks this setup without providing a convenient alternative.

My setup (simplified a bit) looks like this:

```Dockerfile
FROM some_base_image AS builder

WORKDIR /sources

RUN spack dev-build [spec]

FROM ubuntu:18.04

COPY --from=builder /sources/spack-build /sources/spack-build # <-- this fails now.
```

where the image is deployed to some cluster, and some MPI tests are run using `ctest`.

I can't easily rename the `spack-build=[hash]` folder to `spack-build`, since that breaks ctest (it uses absolute paths which won't resolve afterwards). Also I can't do globbing in `COPY --from=builder /sources/spack-build* <dest>`, since I have to specify the destination folder explicitly, and I don't know the hash here.

### CODE REVIEW

**Comment by haampie** [comment]
Also note that https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html#building-out-of-source has not been updated to reflect the change from #18574; the docs still read:

> By default, Spack builds every CMakePackage in a spack-build sub-directory.

**Comment by HadrienG2** [comment]
Another problem with this patch is that it is generally dangerous to put an `=` sign in a file name in the Unix world. If a file name containing this character gets pasted into an automatically generated command based on a tool that handles the `=` character specially, as in the common `<cmd> <opt> <key>[=<value>]` CLI argument grammar, then the execution of that command will not proceed normally.

I observed precisely this problem with an `env` command. The syntax for that command is `env [<var>=<value> ...] <cmd> <args>`, so if the path to the inner `<cmd>` contains an `=` sign, it gets misinterpreted as an environment variable to be set.

Of course, this can be worked around with enough layers of quotes, but let's not go there unless we truly need to.

**Comment by becker33** [comment]
@HadrienG2 yeah the `=` sign is because I accidentally clicked "resolve conversation" instead of "merge suggestion" on the original PR. That should definitely be fixed!

**Comment by haampie** [comment]
@becker33, so what landed is `=` replaced by `-`, but that does not address the issue raised above... Can we at least get some discussion on that part? I still consider #18574 breaking :(.

~Also note that there are 115 packages that set `build_dir = ...` overriding this `spack-build-[hash]` name already, so it doesn't work for some packages anyways.~ Ok, just a handful of them are actually cmake packages. But still.

**Pull request closed without merging**
