### PR TITLE
cmake: Add new versions

### PR DESCRIPTION
**Pull request by jrood-nrel**
It doesn't seem like these have been updated in a bit. I also elected to not change the current default version.

### CODE REVIEW

**Comment by alalazo** [comment]
See #43349 and #43723

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by jrood-nrel** [comment]
Ah, I assumed CMake would have more activity so that makes sense. I should have searched PRs. Feel free to close this.

**Comment by johnwparent** [comment]
> Ah, I assumed CMake would have more activity so that makes sense. I should have searched PRs. Feel free to close this.

Closing in favor of the other linked PRs here, but thanks for staying on top of the CMake updates!

**Pull request closed without merging**
