### PR TITLE
Add RHEL8 Universal Base Image with platform-python to CI unit tests

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Review by tgamblin — APPROVED** [review]

**Comment by adamjstewart** [comment]
Do we want to add `platform-python` to `bin/spack` while we're at it?

**Comment by chuckatkins** [comment]
> Do we want to add `platform-python` to `bin/spack` while we're at it?

I wanted to get a little cycle time with this CI job first.  If this continues to look okay after a week or two then I'll add it in the default search path.

**Comment by adamjstewart** [comment]
If it's last in the search path it should be pretty safe.

**Comment by tgamblin** [comment]
Since it'll be the only think in the search path in a UBI image, I think we should test it out.  I'm not sure what kind of errors to expect (if any), but it would be extremely cool to be able to run natively in UBI without any installation.

**Pull request merged**
