### PR TITLE
Fix: setuptools is a runtime dependency for pudb

### LINKED ISSUE #3501: Incorrect dependency handling on spack load --dependencies
I wanted to take a shot at #3374 (now fixed by #3492) but I ran into dependency tracking issues when I wanted to use ```py-pudb```

```
$ spack load --dependencies py-pudb
$ pudb
Traceback (most recent call last):
  File "/Users/healther/Documents/git/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/py-pudb-2016.2-lqp42db6v3o3pzkzeyf4fgpc46mjtpsp/bin/pudb", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

spack, for some reason, decided that it should load ```py-setuptools```, ```py-six```, ```py-packaging```, ```py-pyparsing``` and ```py-appdirs``` even though it concretizes the spec as follows: 

```
Concretized
--------------------------------
[   ]  py-pudb@2016.2%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]      ^py-pygments@2.1.3%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b  ]          ^py-setuptools@34.2.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]              ^py-appdirs@1.4.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                  ^python@2.7.13%clang@8.0.0-apple~tk~ucs4 arch=darwin-sierra-x86_64 
[bl ]                      ^bzip2@1.0.6%clang@8.0.0-apple+shared arch=darwin-sierra-x86_64 
[bl ]                      ^ncurses@6.0%clang@8.0.0-apple~symlinks arch=darwin-sierra-x86_64 
[b  ]                          ^gawk@4.1.4%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                      ^openssl@1.0.2k%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b  ]                          ^perl@5.24.1%clang@8.0.0-apple+cpanm arch=darwin-sierra-x86_64 
[bl ]                          ^zlib@1.2.11%clang@8.0.0-apple+pic+shared arch=darwin-sierra-x86_64 
[bl ]                      ^readline@7.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                      ^sqlite@3.8.5%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]              ^py-packaging@16.8%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[  r]                  ^py-pyparsing@2.1.10%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[  r]                  ^py-six@1.10.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]      ^py-urwid@1.3.0%clang@8.0.0-apple arch=darwin-sierra-x86_64
```

If I'm reading this correctly the missing packages should have been loaded according to the spec, but for some reason aren't. I haven't had time to track this down, but I think spack fails to load the dependencies of dependencies, even though it correctly concretises the spec.

I hope that I can give it a shot tomorrow or the day after.... If someone could give me a pointer where to start looking I'd appreciate it.

### PR DESCRIPTION
**Pull request by adamjstewart**
UPDATE:

Was supposed to help with #3501 but doesn't solve the real problem.

### CODE REVIEW

**Comment by adamjstewart** [comment]
By the way, the spec still looks like:
```
$ spack spec --types py-pudb
...
[   ]  py-pudb
[b r]      ^py-pygments@1.0:
[b  ]          ^py-setuptools
[bl ]              ^python@2.6:2.7.99,3.3:
[bl ]                  ^bzip2
[bl ]                  ^ncurses
[b  ]                      ^mawk
[b  ]                      ^pkg-config
[bl ]                  ^openssl
[b  ]                      ^perl@5.14.0:
[bl ]                      ^zlib
[bl ]                  ^readline
[bl ]                  ^sqlite
[b r]      ^py-urwid@1.1.1:
```
The way that things currently work is the package is only printed a single time, even if it is a dependency of multiple packages. So even though the deptype from `py-pudb` is `[b r]`, it is printed as `[b  ]` because that's the deptype from `py-pygments`.

@tgamblin I wonder if we should have a flag that doesn't combine all copies of the same package so you can see what the deptype really is.

**Comment by healther** [comment]
This does not solve my problem #3501, for the record: I'm not sure where the run-dependency originates

**Comment by adamjstewart** [comment]
You're saying that when you run `spack load --dependencies py-pudb` it doesn't load `py-setuptools` even when the deptype is build/run?

**Comment by adamjstewart** [comment]
What about when you run `spack activate py-pudb`. Does it activate `py-setuptools` as well?

**Comment by healther** [comment]
yep, see the ```module list``` output in #3501

**Comment by healther** [comment]
```
$ spack activate py-pudb
==> Activated extension py-pygments@2.1.3%clang@8.0.0-apple arch=darwin-sierra-x86_64 /cllzy4u for python@2.7.13~tk~ucs4%clang@8.0.0-apple
==> Activated extension py-urwid@1.3.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 /zmdraae for python@2.7.13~tk~ucs4%clang@8.0.0-apple
==> Activated extension py-pudb@2016.2%clang@8.0.0-apple arch=darwin-sierra-x86_64 /lqp42db for python@2.7.13~tk~ucs4%clang@8.0.0-apple
```

**Comment by adamjstewart** [comment]
@tgamblin I think this is a case where we are incorrectly merging the deptypes of dependencies. This PR should definitely still be merged, but we'll need to hack the deptype merging to solve the real issue.

**Comment by healther** [comment]
That's what I was thinking, I would like to take a look at it (even if just to get a feeling for the internal workings of spack). If you have a pointer as to where I should start looking, I might get to it tomorrow.

**Comment by adamjstewart** [comment]
Hmm, I've never hacked on that particular part of the codebase. I would search for PRs containing words like "deptype" or find the PR where @tgamblin added the `spack spec --types` option.

**Comment by adamjstewart** [comment]
@alalazo or @mathstuf would probably know where to look.

**Comment by tgamblin** [comment]
> @tgamblin I wonder if we should have a flag that doesn't combine all copies of the same package so you can see what the deptype really is.

@adamjstewart: does `spack spec --cover edges` not work?

**Comment by tgamblin** [comment]
@adamjstewart @healther here is the output of `spack spec -tc edges py-pudb`:

```
Concretized
--------------------------------
[   ]  py-pudb@2017.1.1%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b r]      ^py-pygments@2.1.3%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b  ]          ^py-setuptools@34.2.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b r]              ^py-appdirs@1.4.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]                  ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[bl ]                      ^bzip2@1.0.6%clang@7.0.2-apple+shared arch=darwin-elcapitan-x86_64 
[bl ]                      ^ncurses@6.0%clang@7.0.2-apple~symlinks arch=darwin-elcapitan-x86_64 
[b  ]                          ^mawk@1.3.4%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b  ]                          ^pkg-config@0.29.1%clang@7.0.2-apple+internal_glib arch=darwin-elcapitan-x86_64 
[bl ]                      ^openssl@1.0.2k%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b  ]                          ^perl@5.24.1%clang@7.0.2-apple+cpanm arch=darwin-elcapitan-x86_64 
[bl ]                          ^zlib@1.2.11%clang@7.0.2-apple+pic+shared arch=darwin-elcapitan-x86_64 
[bl ]                      ^readline@7.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]                          ^ncurses@6.0%clang@7.0.2-apple~symlinks arch=darwin-elcapitan-x86_64 
[bl ]                      ^sqlite@3.8.5%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]                      ^zlib@1.2.11%clang@7.0.2-apple+pic+shared arch=darwin-elcapitan-x86_64 
[b r]              ^py-packaging@16.8%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[  r]                  ^py-pyparsing@2.1.10%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]                      ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[  r]                  ^py-six@1.10.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]                      ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[bl ]                  ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[b r]              ^py-six@1.10.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]              ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[bl ]          ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[b r]      ^py-setuptools@34.2.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b r]      ^py-urwid@1.3.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[b  ]          ^py-setuptools@34.2.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64 
[bl ]          ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
[bl ]      ^python@2.7.13%clang@7.0.2-apple~tk~ucs4 arch=darwin-elcapitan-x86_64 
```

Note that the only `setuptools` runtime dep there is the first one, from `py-pudb`.  The others are just build deps.

If you use the default `--cover nodes` (which is really just a space saver) you'll get the deptype from the first edge traversed to reach each node, and subsequent visits to the same node are not printed.

**Comment by adamjstewart** [comment]
I think we determined that you have to uninstall and reinstall the package to get the deptypes working, so all of these concerns can be ignored as everything is fixed with pudb.

**Comment by tgamblin** [comment]
> I think we determined that you have to uninstall and reinstall the package to get the deptypes working.

For thsoe wondering: this is intentional.  Even if you change a package, existing package installations should still behave the way the package worked when it was built.  So we do definitely remember the deptypes from build time when printing output for already installed specs.

Suppose you install `foo`, then a new version of `foo`'s `package.py` comes out, where it's missing a former runtime dependency.  If newly generated modules modules for the old version of `foo` drop that dependency as a prereq, the old version won't work.  The module generation code may do this wrong at the moment -- I forget (@alalazo?) but we've discussed this for `module refresh` in the past.

**Pull request merged**
