### PR TITLE
grib-util: fix self-referential dependencies

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Thanks @alalazo - Fair to say the general idea is that we need to use `requires` and not `depends_on` when the package depended on is part of the `when` condition?

**Comment by alalazo** [comment]
> Fair to say the general idea is that we need to use requires and not depends_on when the package depended on is part of the when condition?

Kind of. In this case, to be fair, this wasn't much of an issue. There are cases though where this can lead to "wrong" concretizations, see https://github.com/spack/spack/issues/42427#issuecomment-1924256905  So, I am trying to fix all the directives reported by the WIP audit in #42456 and merge the audit PR so issues like that will be caught in CI.

**Comment by edwardhartnett** [comment]
OK, but as the maintainers for a large number of NOAA packages, we would benefit from a clearer explanation of when we should use "depends_on" and when "requires"...

**Comment by alalazo** [comment]
@edwardhartnett I'd say the bottomline is that directives of the kind:
```python
depends_on("foo ...", when="^foo ...")
```
may be problematic _sometimes_, and they can _always_ be expressed as `requires`[^1]. There aren't many directives like that, but what I'm trying to do is fix cases similar to #42427 in the whole builtin repo. The idea is that, once the repo is fixed, we can merge an audit like #42456 to detect possibly problematic directives in CI.

Let me know if anything is still unclear.

[^1]: In most cases there are even simpler forms of `depends_on` that are semantically equivalent.

**Pull request merged**
