### PR TITLE
openjdk: Add ppc64le package

### PR DESCRIPTION
**Pull request by jonglezb**

### CODE REVIEW

**Comment by jonglezb** [comment]
This allows to build bazel on ppc64le (which in turns allows to build py-tensorflow)

**Review by adamjstewart — APPROVED** [review]

**Comment by pramodk** [comment]
@jonglezb @adamjstewart  : A stupid question: could you tell me how to look for OpenJDK releases in https://github.com/AdoptOpenJDK/openjdk16-binaries/releases ?  I am trying to add openjdk versions (11 series) for MacOS platform but couldn't figure out how releases are tagged there.

**Comment by adamjstewart** [comment]
I'm guessing this is what you want?
https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk16u-2021-04-15-14-12/OpenJDK16U-jdk_x64_mac_hotspot_2021-04-15-14-12.tar.gz

I'm not familiar with the naming scheme used by this repo.

**Comment by pramodk** [comment]
Thanks! As you can see, the above link is for jdk v16 and I didn't understand how to easily extract the version links.

But I  just come across : https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=hotspot
This provide the necessary links that people are using to update spack recipes. For OSX they provide `.pkg` files instead of tarball. So like old versions in the spack recipe, I used https://openjdk.java.net/install/.

 I updated existing releases in #23054.

**Pull request merged**
