### PR TITLE
Override partial installs by default - part two

### LINKED ISSUE #2634: Killed a build, now Spack thinks it is installed
I just tried building a package, noticed something was wrong during configure, and killed it with <kbd>Ctrl</kbd>+<kbd>C</kbd>. When I ran `spack purge` and tried installing it again, I saw:
```
==> parallel-netcdf is already installed in /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.0/parallel-netcdf-1.6.1-fq2r43zk2wcbpl3hrc5h6sfz2dwajbk7
Traceback (most recent call last):
  File "/soft/spack-0.10.0/bin/spack", line 198, in <module>
    main()
  File "/soft/spack-0.10.0/bin/spack", line 175, in main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/cmd/install.py", line 346, in install
    package.do_install(**kwargs)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/package.py", line 1161, in do_install
    rec = spack.store.db.get_record(self.spec)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/database.py", line 81, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/database.py", line 554, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/blues/gpfs/home/software/spack-0.10.0/lib/spack/spack/database.py", line 549, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! parallel-netcdf@1.6.1%intel@17.0.0 cflags="-axCORE-AVX2,AVX" cxxflags="-axCORE-AVX2,AVX" fflags="-axCORE-AVX2,AVX"+cxx+fortran+fpic arch=linux-centos6-x86_64^bison@3.0.4%intel@17.0.0 cflags="-axCORE-AVX2,AVX" cxxflags="-axCORE-AVX2,AVX" fflags="-axCORE-AVX2,AVX" arch=linux-centos6-x86_64^libpciaccess@0.13.4%intel@17.0.0 cflags="-axCORE-AVX2,AVX" cxxflags="-axCORE-AVX2,AVX" fflags="-axCORE-AVX2,AVX" arch=linux-centos6-x86_64^libsigsegv@2.10%gcc@6.1.0 arch=linux-centos6-x86_64^libtool@2.4.6%gcc@6.1.0 arch=linux-centos6-x86_64^m4@1.4.17%gcc@6.1.0+sigsegv arch=linux-centos6-x86_64^mvapich2@2.2%intel@17.0.0 cflags="-axCORE-AVX2,AVX" cxxflags="-axCORE-AVX2,AVX" fflags="-axCORE-AVX2,AVX"~debug~gforker+hydra+mrail~nemesis~nemesisib~nemesisibtcp~psm~remshell~slurm~sock arch=linux-centos6-x86_64^pkg-config@0.29.1%gcc@6.1.0+internal_glib arch=linux-centos6-x86_64^util-macros@1.19.0%gcc@6.1.0 arch=linux-centos6-x86_64'
```
When I ran `spack reindex` and tried installing again, I saw:
```
==> parallel-netcdf is already installed in /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/intel-17.0.0/parallel-netcdf-1.6.1-fq2r43zk2wcbpl3hrc5h6sfz2dwajbk7
```
Of course, that directory is empty except for `.spack/spec.yaml`.

### LINKED ISSUE #2794: spack unable to resume interrupted trilinos build
@BarrySmith @tgamblin 

I'm testing the xsdk install using the barry/xsdk branch on NERSC's edison and ran into the following issue.  My connection to edison died during the trilinos build, so I logged back in and tried to resume.

```
amklinv@edison10:~/edison/spack/bin> ./spack -vd install xsdk arch=cray-CNL-ivybridge
==> Reading config file /global/u1/a/amklinv/edison/spack/etc/spack/defaults/packages.yaml
==> Reading config file /global/homes/a/amklinv/.spack/cray/packages.yaml
==> READ LOCK: /global/homes/a/amklinv/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /global/homes/a/amklinv/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> '/usr/bin/ibv_devices'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-hdf5-parallel/1.8.12'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-hdf5-parallel/1.8.12'
==> Reading config file /global/homes/a/amklinv/.spack/cray/compilers.yaml
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-hdf5-parallel/1.8.12'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-hdf5-parallel/1.8.12'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-pgi'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-pathscale'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'load' 'PrgEnv-gnu'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'gcc/6.1.0'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'gcc'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'gcc-cross-aarch64'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'load' 'gcc/6.1.0'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-mpich/7.4.1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-pgi'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'PrgEnv-pathscale'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'load' 'PrgEnv-gnu'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'gcc/6.1.0'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'gcc'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'unload' 'gcc-cross-aarch64'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'load' 'gcc/6.1.0'
==> '/opt/modules/3.2.10.4/bin/modulecmd' 'python' 'show' 'cray-hdf5-parallel/1.8.12'
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[6653323931864697468:1] [Acquiring]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[6653323931864697468:1] [Released]
==> Installing xsdk
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[2794471412757580533:1] [Acquiring]
==> hypre is already installed in /global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/hypre-develop-jwh6ty3izsk6ukytgs2i23qxgo3i4lrq
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[2794471412757580533:1] [Released]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[840206737987988608:1] [Acquiring]
==> superlu-dist is already installed in /global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/superlu-dist-develop-c5jaojzxkpmqdyxz7xts4crqshkhaxd4
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[840206737987988608:1] [Released]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[4617400482960019937:1] [Acquiring]
==> trilinos is already installed in /global/u1/a/amklinv/edison/spack/opt/spack/cray-CNL-ivybridge/gcc-6.1.0/trilinos-develop-qaujvdhjder4h77x3td7z7jkfi27rcop
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /global/u1/a/amklinv/edison/spack/opt/spack/.spack-db/prefix_lock[4617400482960019937:1] [Released]
Traceback (most recent call last):
  File "./spack", line 212, in <module>
    main(sys.argv)
  File "./spack", line 208, in main
    _main(args, unknown)
  File "./spack", line 174, in _main
    return_val = command(parser, args)
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/cmd/install.py", line 346, in install
    package.do_install(**kwargs)
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/package.py", line 1185, in do_install
    **kwargs
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/package.py", line 1157, in do_install
    rec = spack.store.db.get_record(self.spec)
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/database.py", line 81, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/database.py", line 554, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/global/u1/a/amklinv/edison/spack/lib/spack/spack/database.py", line 549, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! trilinos@develop%gcc@6.1.0+boost~debug+hdf5+hypre+metis~mumps~python+shared~suite-sparse~superlu+superlu-dist+xsdkflags arch=cray-CNL-ivybridge^boost@1.63.0%gcc@6.1.0+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=cray-CNL-ivybridge^bzip2@1.0.6%gcc@6.1.0 arch=cray-CNL-ivybridge^cmake@3.7.1%gcc@6.1.0~doc+ncurses+openssl+ownlibs~qt arch=cray-CNL-ivybridge^glm@0.9.7.1%gcc@6.1.0 arch=cray-CNL-ivybridge^hdf5@1.8.12%gcc@6.1.0+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=cray-CNL-ivybridge^hypre@develop%gcc@6.1.0~internal-superlu+shared arch=cray-CNL-ivybridge^libsigsegv@2.10%gcc@6.1.0 arch=cray-CNL-ivybridge^m4@1.4.17%gcc@6.1.0+sigsegv arch=cray-CNL-ivybridge^matio@1.5.9%gcc@6.1.0+hdf5+zlib arch=cray-CNL-ivybridge^metis@5.1.0%gcc@6.1.0~debug~gdb~idx64~real64+shared arch=cray-CNL-ivybridge^mpich@7.4.1%gcc@6.1.0+hydra+pmi+romio~verbs arch=cray-CNL-ivybridge^ncurses@6.0%gcc@6.1.0 arch=cray-CNL-ivybridge^netcdf@4.4.1%gcc@6.1.0~cdmremote~dap~hdf4 maxdims=1024 maxvars=8192+mpi~parallel-netcdf+shared arch=cray-CNL-ivybridge^openblas@0.2.19%gcc@6.1.0~openmp+pic+shared arch=cray-CNL-ivybridge^openssl@1.0.2j%gcc@6.1.0 arch=cray-CNL-ivybridge^parmetis@4.0.3%gcc@6.1.0~debug~gdb+shared arch=cray-CNL-ivybridge^superlu-dist@develop%gcc@6.1.0 arch=cray-CNL-ivybridge^zlib@1.2.10%gcc@6.1.0+pic arch=cray-CNL-ivybridge'
```

spack thinks trilinos is already installed.  But if I try to uninstall it...
```
amklinv@edison10:~/edison/spack/bin> ./spack uninstall trilinos
==> Error: trilinos does not match any installed packages.
==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
```

Or if I do spack find...
```
amklinv@edison10:~/edison/spack/bin> ./spack find
==> 16 installed packages.
-- cray-CNL-ivybridge / gcc@6.1.0 -------------------------------
boost@1.63.0  cmake@3.7.1  hypre@develop    m4@1.4.17    metis@5.1.0  netcdf@4.4.1     openssl@1.0.2j  superlu-dist@develop
bzip2@1.0.6   glm@0.9.7.1  libsigsegv@2.10  matio@1.5.9  ncurses@6.0  openblas@0.2.19  parmetis@4.0.3  zlib@1.2.10
```

This wouldn't be a big deal for most packages, but trilinos is big and takes a while to install, so the chance of that getting interrupted is non-negligible.

### PR DESCRIPTION
**Pull request by scheibelp**
Fixes #2794. 
Fixes #2634.

See #3530.  This does everything there, and for packages that were installed prior to this PR, it makes sure not to overwrite them if the DB says they were installed.

The first two commits are a rebase of the original PR commits. The ~~last two~~ remainder add in the functionality described here.

I want to check a couple things before removing the WIP tag.

### CODE REVIEW

**Comment by scheibelp** [comment]
@tgamblin this is good to go now. If you agree with the changes I can rebase this to clean up the messages. Also: IIRC you mentioned having a quick fix, I'm curious if that is preferable since the changes here are substantial (that is, if you think this can be done more simply I'm interested to know that).

**Comment by tgamblin** [comment]
@scheibelp: can you resolve the conflicts in this one?  I believe #1167 conflicted with this one.

**Comment by scheibelp** [comment]
> @scheibelp: can you resolve the conflicts in this one? I believe #1167 conflicted with this.

Whoops didn't realize that had happened. I'll be able to resolve this tomorrow morning

**Comment by scheibelp** [comment]
Added WIP tag, trying to track something unexpected down

**Comment by scheibelp** [comment]
> Added WIP tag, trying to track something unexpected down

I noticed that my PR was removing installs after #1167 when I executed a ```reindex```. In this case the issue was that the hashes changed on account of that PR. This also left the old package records in the DB even after the repair removed the prefix (normally it would also remove the DB record but the same spec no longer had the same hash so it couldn't find the record).

Not sure what there is to do about this state (since the specs are not installed according to the db or according to the state file added by this PR. Come to think of it though the specs read from yaml should be find-able in the DB.

**Comment by tgamblin** [comment]
@scheibelp: is the issue above fixed by #4027?

`reindex` shouldn't end up removing things -- I'm on the fence about whether it should do any cleanup at all.  It would probably be ok if it just left stale install directories around.

Also, if a spec is read in from the directory layout, Spack should respect the existing hash -- `dag_hash()` should return a value cached from the previous install, so how do the hashes change here?

**Comment by scheibelp** [comment]
> @scheibelp: is the issue above fixed by #4027?

No - #1167 has another intended effect which has an unintended consequence when combined with this PR: namely reindex does not use old install records if the DB version has changed. So if a user goes from a commit that is pre-this-pr-and-1167 to a commit that is post-this-pr-and-1167, all packages will be considered invalid *both* from the DB perspective and from the completion-file perspective and will be removed. My strategy is to attempt to use old DB records when possible (at least when checking whether a package is installed)

While I'd be happy to leave ```reindex``` unchanged, I don't think that will be possible, since part of reindex is checking whether packages are actually installed, which this PR affects.

(This outlines an alternative, FWIW I'd like to try the above first) A simpler PR could omit the completion-file concept, consider a package installed when the directory exists, and remove it during an install if there is no DB installation record. As far as I can tell this would be simpler logic but would also mean that reindex would consider partial installs to be complete.

**Comment by scheibelp** [comment]
As it is this will fail for DIYStage since ```repair_partial``` calls ```Stage.create``` which is not defined by this stage implementation. Should be an easy fix but I won't be able to get to it until tomorrow.

**Comment by scheibelp** [comment]
I've thought of a simpler/cleaner way to do this, so I'm going to try that. It should be ready by the end of 5/22

**Pull request closed without merging**
