### PR TITLE
Add the HPX-5 package to spack.

### PR DESCRIPTION
**Pull request by adk9**

### CODE REVIEW

**Comment by tgamblin** [comment]
@adk9: thanks!  Does it make sense to name this package `hpx5` instead of `hpx`?  `spack create` just goes by the URL, which says `hpx`, but it seems like the CREST HPX is always called `HPX-5` and the LSU one is called `HPX` -- is that accurate?

**Comment by eschnett** [comment]
Do the packages conflict? I think both e.g. use an "hpx" prefix for include files. Is there a mechanism in Spack to prevent conflicting dependencies?

`hpx5` reads like a version number. What about `crest-hpx` and `lsu-hpx` instead?

**Comment by adk9** [comment]
@tgamblin Yes, that is accurate—we consistently refer to our implementation as HPX-5. I have renamed the package to hpx5 and added more variants.

@eschnett Both use the "hpx" prefix for headers, which probably makes them mutually exclusive at this point. As far as I can tell, resolving package conflicts is up to the package creators. It would be nice though if spack could warn about conflicting dependencies.

**Comment by tgamblin** [comment]
@eschnett: they call it hpx-5, but it's not the actual version, kind of like hdf5. 

@adk9: Thanks!. Indolent be tooinherentmade a conflicts() directive to spack, which could be checked.  It's infrequently needed though, since everything except activated extensions (python modules) gets a unique prefix. 

If this and hpx provide the same interface, we could make a virtual dependency for hpx. But as I remember, this is C and hpx is C++.

**Pull request merged**
