### PR TITLE
py-torchaudio, py-torchtext: rpath fixup

### PR DESCRIPTION
**Pull request by haampie**
extracted from #47365 

also add missing dependency on Spack ffmpeg to torchaudio.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is this the same issue I saw with PyTorch/torchvision: https://github.com/pytorch/vision/issues/8653

This required me to add `-Wl,-ld_classic` on macOS in order to avoid linker failure. I wonder if you can track down why this is required, I suspect the issue is in PyTorch itself.

**Comment by haampie** [comment]
no, yours is apparently about repeated rpaths, this is about lack of rpaths.

**Comment by haampie** [comment]
sigh, still issues with libtorio_ffmpeg.so not being located.

maybe iteration 5 will work...

**Comment by haampie** [comment]
Now it is fine according to #47365

**Review by alalazo — APPROVED** [review]

**Pull request merged**
