### PR TITLE
Remove unnecessary URLs

### PR DESCRIPTION
**Pull request by adamjstewart**
This package does not need to specify URLs for each version since they all have the same naming convention.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Any reason why this can't be merged? It doesn't impact me; I'm just trying to close out old pull requests.

**Comment by tgamblin** [comment]
nope -- thanks!

**Comment by tgamblin** [comment]
Trying to get to all the PRs.  In particular @eschnett has a lot that need merging

**Comment by adamjstewart** [comment]
Yeah, I noticed haha. I've been trying to help out and clean things up where I can. Let me know if there's anything else I can do to help!

**Pull request merged**
