### PR TITLE
aws-parallelcluster: add v2.11.0

### PR DESCRIPTION
**Pull request by enrico-usai**
Replaces https://github.com/spack/spack/pull/24646

### CODE REVIEW

**Review by demartinofra — DISMISSED** [review]

**Review by lukeseawalker — DISMISSED** [review]

**Review by adamjstewart — DISMISSED** [review]

**Comment by enrico-usai** [comment]
@adamjstewart do you know why the ci/gitlab-ci check is still pending?

**Comment by adamjstewart** [comment]
The queue seems to be very backed up. We're looking into this now.

**Comment by tilne** [comment]
What can I do to get this PR unstuck?

**Comment by adamjstewart** [comment]
Can you try rebasing and force-pushing to kick of the CI again? @scottwittenburg may also be able to help.

**Comment by enrico-usai** [comment]
@adamjstewart @scottwittenburg rebase done, ci/gitlab-ci is passing now, thanks!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
