### PR TITLE
tree-sitter: add versions up to 0.22.2

### PR DESCRIPTION
**Pull request by berquist**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed all six new version sha256s. @albestro Are there any dependency or build changes needed for any of these versions?

**Comment by berquist** [comment]
FWIW I compiled Emacs against tree-sitter 0.22.2 without issue.

**Review by alecbcs — APPROVED** [review]
@tldahlgren tree-sitter is a pretty minimal self contained package. I believe that these versions require no additional modifications to successfully compile.

**Comment by albestro** [comment]
> Confirmed all six new version sha256s. @albestro Are there any dependency or build changes needed for any of these versions?

I'm sorry but I don't follow the project closely, hence I don't know.

**Pull request merged**
