### PR TITLE
Updates to support clingo-cffi

### PR DESCRIPTION
**Pull request by joshessman-llnl**
Clingo recently merged in a new Python module option based on `cffi`.  

Compatibility with this module requires a few changes to spack - it does not automatically convert strings/ints/etc to `Symbol` and `clingo.Symbol.string` throws on failure.

### CODE REVIEW

**Comment by joshessman-llnl** [comment]
Testing locally with the clingo-cffi package identified a regression introduced after merging in develop:

```sh
$ spack spec -I libxml2+python
Traceback (most recent call last):
  File "./bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "spack/lib/spack/spack/spec.py", line 2528, in concretize
    self._new_concretize(tests)
  File "spack/lib/spack/spack/spec.py", line 2498, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "spack/lib/spack/spack/solver/asp.py", line 1625, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "spack/lib/spack/spack/solver/asp.py", line 362, in solve
    answers = builder.build_specs(tuples)
  File "spack/lib/spack/spack/solver/asp.py", line 1549, in build_specs
    action(*args)
  File "spack/lib/spack/spack/solver/asp.py", line 1429, in version
    self._specs[pkg].versions = spack.version.ver([version])
KeyError: 'sqlite'
```

`packages.yml`:
```yml
  python:
    version: [3.8.2]
    buildable: false
    externals:
    - spec: python@3.8.2
      prefix: /usr
```

This appears to have originated in https://github.com/spack/spack/commit/0ce08640e08de8f7313a4b3974131e2efa5249e0 and also appears to affect the "regular" `clingo` package.

**Comment by tgamblin** [comment]
@joshessman-llnl I don't see that behavior -- is that with latest `clingo@master`?

**Comment by becker33** [comment]
@tgamblin I believe it's with external clingo -- clingo recently added an option to build with cffi instead of the C interface, but it makes some aspects of the python interface stricter. See https://github.com/potassco/clingo/commit/26a81aa15b928dfd0821a565cd1554ffbd529d76 and https://github.com/potassco/clingo/commit/70d4ac950dcdb7f824db99a38929654f7688214f or https://github.com/potassco/clingo/pull/253

**Comment by joshessman-llnl** [comment]
> 
> 
> @joshessman-llnl I don't see that behavior -- is that with latest `clingo@master`?

Yes, this is `clingo@master` with the standard (i.e., non-CFFI) Python module:

```sh
$ python3 -c "import clingo; print(hasattr(clingo.Symbol, '_rep'), clingo.__version__)" 
False 5.5.0 # False means non-CFFI
$ git checkout 49ac3471cf97f5308c648a78a9fd7b0c3a083e90
$ ./bin/spack spec -I libxml2+python
# concretizes....
$ git checkout 0ce08640e08de8f7313a4b3974131e2efa5249e0 
$ ./bin/spack spec -I libxml2+python
Input spec
--------------------------------
-   libxml2+python
Concretized
--------------------------------
==> Error: 'sqlite'
```

Result of `git diff` in the spack repo:
```diff
diff --git a/etc/spack/defaults/config.yaml b/etc/spack/defaults/config.yaml
index d1a7f35a6d..e8147838b6 100644
--- a/etc/spack/defaults/config.yaml
+++ b/etc/spack/defaults/config.yaml
@@ -160,7 +160,7 @@ config:
   #
   # 'clingo' currently requires the clingo ASP solver to be installed and
   # built with python bindings. 'original' is built in.
-  concretizer: original
+  concretizer: clingo


   # How long to wait to lock the Spack installation database. This lock is used
diff --git a/etc/spack/defaults/packages.yaml b/etc/spack/defaults/packages.yaml
index bf9148315b..9eacff87c6 100644
--- a/etc/spack/defaults/packages.yaml
+++ b/etc/spack/defaults/packages.yaml
@@ -53,3 +53,9 @@ packages:
    permissions:
      read: world
      write: user
+  python:
+    version: [3.8.2]
+    buildable: false
+    externals:
+    - spec: python@3.8.2
+      prefix: /usr 
```

**Comment by becker33** [comment]
@tgamblin the issue resolved here dates to https://github.com/spack/spack/commit/0ce08640e08de8f7313a4b3974131e2efa5249e0

**Comment by joshessman-llnl** [comment]
The regression I ran into appears to be unrelated to this PR, so I have reported it as #20736

**Review by becker33 — APPROVED** [review]

**Comment by alalazo** [comment]
Ugh, the `clingo-cffi` runner is testing the original concretizer...

**Pull request merged**
