### PR TITLE
Add directives for removing patches, conflicts and dependencies

### PR DESCRIPTION
**Pull request by iarspider**
As proposed here: https://github.com/spack/spack/discussions/33057, this is useful for changing recipes via inheritance. I have decided not to touch original directives, since their code is quite complicated

### CODE REVIEW

**Comment by iarspider** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
Why not just extracting the base class somewhere, like in `fftw`?

**Comment by iarspider** [comment]
In some cases (*) we don't want to push changes upstream, since we can't guarantee that every function of the affected package will work - "our tests pass + no one complains = it just works" approach. 

(*) Mostly for Python packages we remove version restrictions set by package authors, so some functionality not used by CMS _could be_ affected; also for many packages we remove `gettext` dependency since we don't need other languages and we need to save on image size

**Comment by iarspider** [comment]
@spackbot fix style

**Comment by iarspider** [comment]
> In some cases (*) we don't want to push changes upstream, since we can't guarantee that every function of the affected package will work - "our tests pass + no one complains = it just works" approach.
> 
> (*) Mostly for Python packages we remove version restrictions set by package authors, so some functionality not used by CMS _could be_ affected; also for many packages we remove `gettext` dependency since we don't need other languages and we need to save on image size

So, TLDR, a different use case: crude hacking of recipe vs special implementation of a common package.

**Comment by alalazo** [comment]
Superseded by #35045

**Pull request closed without merging**
