### PR TITLE
Add new package: solr

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Review by tldahlgren — CHANGES_REQUESTED** [review]
The convention is to list versions in descending order (i.e., newest at the top) so please move `7.7.3` to after `8.4.1`.

**Comment by tldahlgren** [comment]
I should note that I was able to successfully install versions `7.7.3`, `8.4.1`, and `8.6.0`.

**Comment by darmac** [comment]
> I should note that I was able to successfully install versions `7.7.3`, `8.4.1`, and `8.6.0`.

I fixed this order in patch: https://github.com/spack/spack/pull/17597/commits/cc4dcd35e9c705fba0e7a2a7ba9e9834908d6ca4
Thanks for your checking.

**Review by tldahlgren — APPROVED** [review]
LGTM.  Thanks for the fix.

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Comment by darmac** [comment]
> Thank you for your contribution.

Emm, I think `spack` is a greate project and giving us a easier way to use kinds of softwares.

**Pull request merged**
