### PR TITLE
use glyphs for spec status

### PR DESCRIPTION
**Pull request by Paul-Ferrell**
I had to recreate this from scratch, I had deleted the original branch a while back apparently. 

See #16490 for the original discussion.

### CODE REVIEW

**Comment by Paul-Ferrell** [comment]
Just to re-iterate what this does:
 - Changes the symbols used by several commands when displaying a concretized spec tree. 
 - All symbols are now consistently in square brackets.
 - Each symbol uses a distinct color.
 - Added symbols for errors (missing packages that are in the db), and externals.
 - Changed 'not-installed' symbol from a minus to an empty bracket set `[ ]`
 - Added help text to related commands that displays these symbols and what they mean.

**Comment by Paul-Ferrell** [comment]
The only failing test seems to be because it was auto-cancelled due to redundancy, at least according to it's own logs.

**Comment by Paul-Ferrell** [comment]
Everything is passing. I had to disable one part of my tests because of a [bug in clingo,](https://github.com/spack/spack/issues/24506) but that bug is with generating the data to test rather than anything that will effect my changes themselves.

**Comment by alecbcs** [comment]
@Paul-Ferrell is this PR still something you're interested in merging or has this since been fixed elsewhere?

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
