### PR TITLE
openmpi: add patch fixing MPI_MIN for unsigned long

### PR DESCRIPTION
**Pull request by skosukhin**
The latest `4.0.x` and `4.1.x` versions of the library produce incorrect results for minimum value reductions of `unsinged long` (see https://github.com/open-mpi/ompi/issues/10648).

This PR applies a patch from the upstream (see https://github.com/open-mpi/ompi/pull/10527), which does not seem to be in any release yet.

It's interesting that the same simple program fails when built against the latest versions of two major MPI implementations (see https://github.com/spack/spack/pull/32188).

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed patch URL exists.

**Comment by tldahlgren** [comment]
Looks like a number of CI stacks are failing but have not investigated.

Regardless, will defer merge decision until at least one maintainer has a chance to comment (as well).

**Review by hppritcha — DISMISSED** [review]

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@skosukhin Apologies for losing track of this. Do you still need this patch? If so, please rebase and I'll try to shepherd the PR to merge.

**Comment by hppritcha** [comment]
i'll approve if 

- rebased 
- passes CI

**Comment by alalazo** [comment]
@hppritcha

**Review by hppritcha — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
