### PR TITLE
py-sip: add v6.6.2

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 12.6 (arm64) with Python 3.9.13 and Apple Clang 14.0.0.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Ooops.  I jumped the gun.  Just noticed @Sinan81 was asked to review.

**Comment by adamjstewart** [comment]
No worries, I just figured he might be interested in this

**Comment by Sinan81** [comment]
> Ooops. I jumped the gun. Just noticed @Sinan81 was asked to review.

No worries. the PR looks good!

**Pull request merged**
