### PR TITLE
cuda: new version 11.8.0

### PR DESCRIPTION
**Pull request by aweits**
probably not all the way there, but it's a start @ax3l @Rombur @davidbeckingsale

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM. Confirmed cuda sha256 (on `Linux-x86_64`).

**Comment by tldahlgren** [comment]
Giving @ax3l @Rombur @davidbeckingsale a chance to comment (and the PR a chance to settle) before merging.

**Comment by davidbeckingsale** [comment]
Do any host compiler conflicts be updated?

**Review by ax3l — DISMISSED** [review]
Nice, thanks a lot!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
