### PR TITLE
fix --reuse w/ upstreams in env

### LINKED ISSUE #29112: upstreams config not picked up in env
```console
$ spack env create -d derp
$ spack -e derp add llvm
$ spack -e derp -c upstreams:derp:install_tree:/my/upstream concretize --force --reuse
[^]  pqezotj  llvm@12.0.1%gcc@7.5.0~clang~...
...
$ spack -e derp config add upstreams:derp:install_tree:/my/upstream
$ spack -e derp concretize --force --reuse
 -   m2jpox5  llvm@13.0.0%gcc@7.5.0+clang~...
...
```

### PR DESCRIPTION
**Pull request by haampie**
This should really be fixed properly, cause the current code is absolute madness. But for 0.17 I think yet another hack suffices.

### CODE REVIEW

**Comment by alalazo** [comment]
> This should really be fixed properly, cause the current code is absolute madness. But for 0.17 I think yet another hack suffices.

I agree with that, see https://github.com/spack/spack/pull/26560#issue-1018550393, and upstream is one of the things we didn't catch that I was mentioning in the original PR description. I also agree that we'd need to remove a lot of the global state we have for configs https://github.com/spack/spack/pull/26560#issuecomment-936486963 but that is deeply entrenched and might require time to rework + impact on other big changes that are in flight.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Non necessary to have in this PR, but it would be good to have a test like:

https://github.com/spack/spack/blob/f41c3a0fe96df09e3d6887dbeda6cb822e32e7f5/lib/spack/spack/test/cmd/env.py#L2706-L2725

for #29112 too

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Pull request merged**
