### PR TITLE
Add list_url for packages from http://ab-initio.mit.edu/

### PR DESCRIPTION
**Pull request by adamjstewart**
I discovered a "secret" `list_url` shared by all software from [this research group](http://ab-initio.mit.edu/) and I couldn't help but share it.

Also converts these packages to `AutotoolsPackage`.

### CODE REVIEW

**Comment by alalazo** [comment]
After this PR the coverage in `develop` has dropped by 1.7% (clearly not due to the content of the PR). I am also experiencing similar issues in my production branch at epfl-scitas#84 .

It seems to me that codecov produces results before all the Travis jobs are completed, and that causes the drop in coverage. Does anybody know if something changed in the the way Travis and `codecov` works? @tgamblin @adamjstewart

**Comment by alalazo** [comment]
@adamjstewart Did you restart the Travis job? It seems fixed now.

**Comment by tgamblin** [comment]
The full 70% coverage number comes from multiple Travis runs, so you may not see it until the CI has completely finished.  Codecov puts a checkmark next to things if the CI completed fully.  If the builds *haven't* all completed, there can be missing coverage from either a Linux (Python 2.x or 3.x)  run, or from the Mac OS run -- usually ~1.7%.  It should update once all the runs are done.

I messaged the codecov folks about this and they said they'd look into only updating the badge when all runs have completed, but I guess it hasn't happened yet.

**Comment by alalazo** [comment]
> The full 70% coverage number comes from multiple Travis runs, so you may not see it until the CI has completely finished. Codecov puts a checkmark next to things if the CI completed fully. If the builds haven't all completed, there can be missing coverage from either a Linux (Python 2.x or 3.x) run, or from the Mac OS run -- usually ~1.7%. It should update once all the runs are done.

I noticed the issue on my branch more or less at the same time I noticed the coverage drop in `develop`. What happened in my branch was codecov reporting all the coverage failing with Travis still running the build tests. Now things seem to be back to a normal state... well weird...

**Pull request merged**
