### PR TITLE
New package: py-contextvars

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Comment by qwertos** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
I was  able to successfully build the package.

**Review by adamjstewart — APPROVED** [review]
Out of curiosity, why do you want a package that backports features of Python 3.7 to older versions? Spack doesn't support Python 3.6 and older anymore.

**Comment by alecbcs** [comment]
ping @qwertos

**Comment by alecbcs** [comment]
Going to go ahead and close this PR due to the lack of a response. 
@qwertos happy to reopen it if you still need this package.

**Pull request closed without merging**
