### PR TITLE
add trompeloeil package

### PR DESCRIPTION
**Pull request by Billae**
We need this package in our workflow so we made a spack recipe for it. I do not own this project , so I  wrote @rollbear (the true owner) as maintener.

Maybe someone need this package too and will be glad to see there is already a spack recipe =)

### CODE REVIEW

**Comment by rollbear** [comment]
Please do not add me as maintainer. I know nothing about spack and have no idea of what maintaining the package would mean.

**Review by tldahlgren — DISMISSED** [review]
Confirmed the home page, branch, and three version sha256.

Needs style corrections.

**Comment by tldahlgren** [comment]
> Needs style corrections.

Need to remove the blank line at 25 (or 26) and split line 10:

```
==> Running flake8 checks
var/spack/repos/builtin/packages/trompeloeil/package.py:10: [E501] line too long (103 > 99 characters)
var/spack/repos/builtin/packages/trompeloeil/package.py:17: [E303] too many blank lines (2)
  flake8 found errors
```

**Review by tldahlgren — APPROVED** [review]
Re-confirmed the branch and three version sha256.  Able to successfully install the package.

**Pull request merged**
