### PR TITLE
libquo: Update default version from 1.3.1 to 1.4.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.  

(Note that the change you made to the `url` isn't necessary since Spack will automatically replace the version.  That said I know a number of maintainers who prefer to keep it up-to-date.)

**Comment by samuelkgutierrez** [comment]
Thank you, @tldahlgren!

**Comment by samuelkgutierrez** [comment]
It looks like `radiuss-build` is taking a while to complete, @tldahlgren. I'm not sure if that's expected or it needs poking.

**Comment by samuelkgutierrez** [comment]
Hello, @tldahlgren. I had to poke at the CI the only way I could, so automerge was disabled. I didn't want this to get buried. Thank you.

**Pull request merged**
