### PR TITLE
Flang libstdc++ fix

### PR DESCRIPTION
**Pull request by owainkenwayucl**
Currently the way the flang `package.py` build process works, it uses the `clang++` from llvm-flang which was built in the previous step by whichever compiler the user is using (presumably GCC although possibly LLVM or other).  In the instance where this has a newer version of libstdc++ than the system one, `cmake` fails to tell the llvm-flang version of `clang++` the right path to `libstdc++` which results in it failing at the `cmake` stage complaining that your C++ comiler can't produce binaries.

*Interestingly, outside of this process, the compiler works fine which makes me suspect that there's some cmake funkiness going on.*

This patch pulls the path the lib64 directory from `self.compiler.implicit_rpaths()[1]` (which is somewhat ugly and I'm open to better suggestions) explicitly to `CMAKE_CXX_FLAGS` which allows the llvm-flang `clang++` to find it and the build to proceed.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@naromero77 can you review this?

**Comment by naromero77** [comment]
Give me some time to figure out if there is a better way to do this. Can you provide a specific spack command invocation that triggers this issue? (a formal github issue would be even better).

**Comment by owainkenwayucl** [comment]
On our systems we have RHEL 7 with an install of GCC 4.9.2 (old I know) in /shared/ucl/apps/... which I use as the starting compiler for spack.

This is too old to build flang directly so I do:

spack install gcc@9.3.0
(load the gcc module)
spack compiler find
spack install flang%gcc@9.3.0

I'll try to gather all the info for a proper bug report. (it takes time obviously to rebuild all this stuff!)

**Comment by owainkenwayucl** [comment]
I've added a full bug report with config files etc https://github.com/spack/spack/issues/17557

**Comment by owainkenwayucl** [comment]
@naromero77: As per our discussion on #17557 I've adjusted this to instead patch the `package.py` for flang and llvm-flang to set `GCC_INSTALL_PREFIX` appropriately.

**Comment by naromero77** [comment]
@adamjstewart I am OK with this getting merged in. 

Not sure I understand the tests that is failing.

**Review by alalazo — APPROVED** [review]
Got a positive review from maintainer, so going to merge this.

**Pull request merged**
