### PR TITLE
move rpath from ALL to other sections of site.cfg

### PR DESCRIPTION
**Pull request by krafczyk**
If you move the `rpath` variable in `site.cfg` numpy no longer has an import error as reported in #3007.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@davydden Could that be an else at the end? Do we need special handling for macOS? I'll have to look back and see why that was necessary.

**Comment by krafczyk** [comment]
I can write the `rpath` entry to the `ALL` section, but I'm not sure what good it'll do. It seems that `rpath` entries in the `ALL` section are ignored. I guess it might be a bug in numpy I'm not sure.

As far as evaluating the conditional once, I assume you're saying that when the conditional is true we don't need `rpath` at all, is that right?

**Comment by davydden** [comment]
> As far as evaluating the conditional once, I assume you're saying that when the conditional is true we don't need rpath at all, is that right?

not, exactly. I just though  not to copy the complicated condition in many places but have a variable. 

But on a second though, the whole thing cam be refactored more consisely as
````
if openblas
   ...
elif mkl
  ...
elif atlas
  ...
else
  #default
  ...

# common to all:
library_dirs=...
if ()
   rpath =...
```

**Comment by davydden** [comment]
@adamjstewart 

> I'll have to look back and see why that was necessary.

i think it was me who added it as there was some compilation/linking issue on Sierra.

**Comment by krafczyk** [comment]
@davydden, I've added the mac condition back in, but I left the `ALL` case at the top. I think aesthetically `ALL` belongs at the top, but I can move it down if you want.

**Comment by davydden** [comment]
@krafczyk see my last comment. Library_dirs and rpath **is the same** regardless of blas. Please factor those out of ifs. Since rpath goes inside each blas, ALL is not used with mkl/openblas/atlas. Please move it at the end as it naturally fits into if-elif-else (see my last comment)

**Comment by davydden** [comment]
Ps. By "the same", I mean python code to write those fields in site.cfg

**Comment by davydden** [comment]
You would also not need to introduce mac_cond variable.

**Comment by krafczyk** [comment]
@davydden Okay, I think I get what you're saying. I've changed it again. Anything I missed?

**Comment by krafczyk** [comment]
If everything is good, can we get this merged?

**Pull request merged**
