### PR TITLE
Adding new package: py-distribute

### PR DESCRIPTION
**Pull request by JavierCVilla**
Easily download, build, install, upgrade, and uninstall Python packages

### CODE REVIEW

**Comment by adamjstewart** [comment]
This package looks good, but I'm not sure if it's something we want in Spack. The way that it works is to remove any existing setuptools installation in your site-packages directory and install a "fake" setuptools installation itself.

**Comment by JavierCVilla** [comment]
@adamjstewart Thanks for the feedback. To be honest, I don't know the use that the team makes for every single package. I have a list of required packages that are provided by the current tool in use and the proposal is to have the same behaviour but using Spack. Now, some of these packages may have some *conflicts* with Spack or to not fit exactly with the Spack philosophy due to it provides mechanisms or behaviours that we didn't have before. 

In case that you feel that it doesn't provide any value in this official repo, feel free to reject the PR. We use a private repo for these cases and I just share those I think that could be valuable for others.

**Comment by adamjstewart** [comment]
I'll let others comment on whether or not this package should make it into Spack. I would vote for "yes", but maybe add some comments in the docstring or in the package that say that it could cause unexpected results. I would be interested in tests to see whether or not it completely deletes a concurrent `py-setuptools` installation when installed. We don't normally allow packages that affect the installation directory of a different package unless there is no other way to use it. Spack's installation technique is very different from `pip`. Whereas `pip` will install everything into a single directory, Spack uses separate directories for each package. The result of this is that the build system is "purified": only the packages that you explicitly declare as dependencies will show up. So if installing `distribute` causes the `setuptools` installation to be deleted and a new "fake" setuptools installation under the `distribute` installation prefix, Spack installations will no longer work. The deleted `setuptools` prefix will be in the `PYTHONPATH`, not the "fake" setuptools `distribute` prefix.

**Comment by tgamblin** [comment]
@JavierCVilla: Is this a needed dependency of something in particular?  I'd be curious what project uses it and why it's needed instead of `setuptools`.

My main issue with this is the same as @adamjstewart's.  The docs claim that this modifies an existing `setuptools` installation.  @JavierCVilla: do you know whether it will do that even if `setuptools` is in a separate location?  I would *like* it if we could treat existing installation directories as read-only, and I think Spack should really mark them that way someday.  This violates that rule.

The other question I have about this is whether it's actually necessary in Spack.  Is it needed when the package manager uses completely separate directories for different installations?

**Comment by adamjstewart** [comment]
From what I can tell, `distribute` is a drop-in replacement for `setuptools`. The only reason it deletes the `setuptools` installation is so that it can overwrite it with its own "fake" `setuptools`. Perhaps we could make `setuptools` a virtual dependency and "break" `distribute` so that it doesn't try to uninstall `setuptools`.

**Comment by JavierCVilla** [comment]
Hi @adamjstewart @tgamblin 

I've been looking into. The origin of this package in our stack is in `matplotlib` and `coverage`, they both suggest to use `distribute` OR `setuptools` or similar tools to install their dependencies. So this seems to be the reason why in the past we added it. 

Having said this, from my side there is no really need to use it given that both `matplotlib` and `coverage` are already provided by Spack without using `distribute` so I won't need it either.

Now, what do you think? Should we add it to Spack or not? I don't really know what can `distribute` do with `setuptools` also installed, because when we build `matplotlib` and `coverage` they really use `setuptools` instead of `distribute`. 

> Perhaps we could make setuptools a virtual dependency and "break" distribute so that it doesn't try to uninstall setuptools.

I think that we could just close this PR, and just think on this solution if in a future there is any real need to use distribute.

**Comment by adamjstewart** [comment]
> I think that we could just close this PR, and just think on this solution if in a future there is any real need to use distribute.

I agree. It's not like it was particularly challenging to package this PR. But to use it safely, a lot of additional work would need to be involved.

**Pull request closed without merging**
