### PR TITLE
libfabric: add version 1.16.0

### PR DESCRIPTION
**Pull request by snehring**
Just a version update

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]
Checksum verified. Thanks!

**Comment by snehring** [comment]
CI fails are legit. I thought I had tested with verbs. Per https://github.com/ofiwg/libfabric/issues/8052 the release tarball is missing some files, so we'll need to wait for 1.16.1.

**Review by alalazo — CHANGES_REQUESTED** [review]
Feel free to ping me when https://github.com/ofiwg/libfabric/issues/8052 is fixed

**Comment by shefty** [comment]
Missing file should be in updated package.  https://github.com/ofiwg/libfabric/releases/tag/v1.16.1

**Comment by snehring** [comment]
Thanks for that!

**Review by haampie — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
