### PR TITLE
Containerize: accommodate nested or pre-existing spack-env paths

### LINKED ISSUE #41656: containerize: issues with custom repos in the environment directory
### Steps to reproduce

`spack containerize` generates a Dockerfile that, among other things, makes a new dir for the spack environment ([see this line in the Dockerfile template](https://github.com/spack/spack/blob/80f31829a8aaa6cd71b62e3926c9336f239204ac/share/spack/templates/container/Dockerfile#L19)).

However, this command will generate an error during Docker build, if the dir already exists in the base image.

To reproduce:  Create a docker image that already has a dir named `/opt/spack-environment`, and use that docker image for `container.images.build`.

### Error message

```
mkdir: cannot create directory '/opt/spack-environment': File exists
```

### Information on your system

Mostly not relevant.  I am using Spack 0.21.0.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by odoublewen**
fixes #41656

The current `mkdir {{ paths.environment }}` will generate an error if:
* `{{ paths.environment }}` already exists, or
* `{{ paths.environment }}` is nested in non-existing dirs.

Adding `-p` to the command will make this robust to both possibilities.

Why would `{{ paths.environment }}` pre-exist?  Sometimes I need to copy a custom spack package repo into my spack environment, to provide spack packages for proprietary software.  I like the custom repo to stay relative to the `spack.yaml` file for portability (i.e. so that the `spack.yaml` file can work both inside and outside of the containerize command.)

cc: @hartzell

### CODE REVIEW

**Comment by wdconinc** [comment]
Isn't a pre-existing directory more likely an indication of unexpected behavior? I'd be worried that this will silently overwrite a `spack.yaml` file already in `/opt/spack-environments` since containerize uses a shell redirect.

**Comment by odoublewen** [comment]
Thank you @wdconinc for your comment.  A valid concern.  I've proposed an alternative change (https://github.com/spack/spack/pull/41746)  that would be a different (and better) way to address the issue I'm facing.

**Comment by alalazo** [comment]
On the other hand, how likely it is that a `spack.yaml` file is in the `build.image` in the `/opt/spack-environment` directory "accidentally" ? @wdconinc Which use case do you see as potentially problematic with this PR ?

**Comment by wdconinc** [comment]
One use case that I can imagine is that someone uses a base image that is itself the outcome of a spack containerize run. This could fit in a strategy of layering containers: env1 installs core dependencies, env2 uses env1 image as base and installs dependent packages (reusing what's in /opt/software), env3 uses env1 as well to install other dependent packages (also reusing /opt/software), etc. This would cause the env1 spack.yaml to be overwritten by the env2 and env3 spack.yamls.

Yes, maybe this is a bit contrived, and maybe the 'damage' is minimal in this case.

**Comment by alalazo** [comment]
> Yes, maybe this is a bit contrived, and maybe the 'damage' is minimal in this case.

Yeah, if you don't strong oppose to this solution, I would be for merging this PR.

**Comment by odoublewen** [comment]
> This would cause the env1 spack.yaml to be overwritten by the env2 and env3 spack.yamls

@wdconinc Just out of curiosity, in this scenario, which spack.yaml would be the right one to keep?  

In any case, if we believe it is important to protect against silently overwriting an existing spack.yaml file, we could do something like:

```
RUN mkdir -p {{ paths.environment }} \
{{ manifest }} > /tmp/spack.yaml && \
mv -n /tmp/spack.yaml {{ paths.environment }}/spack.yaml
```

At least that would preserve the behavior of throwing an error during build, if the environment dir pre-exists and contains a spack.yaml file.

**Comment by wdconinc** [comment]
> which spack.yaml would be the right one to keep?

I would just want spack to error out instead of picking one over the other in that case :-)

Maybe `set -o noclobber` is sufficient too, rather than doing the tmp and mv.

**Comment by odoublewen** [comment]
> Maybe set -o noclobber is sufficient too, rather than doing the tmp and mv.

Oh, nice.  I didn't know about that bash option.

So then how about (edited to correct path):

```
RUN mkdir -p {{ paths.environment }} && \
set -o noclobber \
{{ manifest }} > {{ paths.environment }}/spack.yaml
```

(btw I think it's odd that the `{{ manifest }}` string includes the `&&` but maybe there's a subtle reasons for this that I don't see... anyway we don't need to go down that path right now...)

If you both agre with the above, I will update my PR and rebase with develop.

**Comment by wdconinc** [comment]
Sounds good to me.

**Comment by odoublewen** [comment]
I don't have the ability to add a reviewer to the PR. Could one of you maybe add yourself (and approve it if you think it's ready?)

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks @odoublewen !

**Pull request merged**
