### PR TITLE
transrate: new package at 1.0.3

### PR DESCRIPTION
**Pull request by codeandkey**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is it possible to install this package from source? https://hibberdlab.com/transrate/installation.html makes it seem like it's possible to install as a Ruby gem. We now have a RubyPackage base class in Spack to make this easier.

If not, it might be a good idea to also add the macOS binary and install depending on the value of `sys.platform`.

**Comment by codeandkey** [comment]
There is a source installation available, but building it is a bit trickier as it requires binaries from a seperate tools repository hosted here: https://github.com/cboursnell/transrate-tools.

The macOS binary distribution is provided in a different tarball. I've added a url_for_version which detects the darwin platform and adjusts the URL accordingly, but I'm not sure how to adjust the checksum as that will be changed with the different distribution.

**Comment by adamjstewart** [comment]
I would instead do:
```python
if sys.platform == 'darwin':
    version('1.2.3', 'hash', url='...')
else:
    version('1.2.3', 'hash', url='...')
```

**Comment by codeandkey** [comment]
Added!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
