### PR TITLE
masurca: Version update to 4.0.5

### PR DESCRIPTION
**Pull request by dorton21**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by dorton21** [comment]
Any updates on this?

**Comment by tldahlgren** [comment]
> Any updates on this?

Looks like we're still waiting for the required pipeline checks to finish.  If they pass then the PR will be automatically merged.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
