### PR TITLE
Add AMD MIGraphX recipe for rocm 3.5

### PR DESCRIPTION
**Pull request by pfultz2**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@bvanessen @srekolam @arjun-raj-kuppala @haampie can you review this?

**Comment by arjun-raj-kuppala** [comment]
@adamjstewart 
Need your inputs here. This errors out when i run 'spack install migraphx'
==> Error: Multiple providers found for 'pkgconfig': ['pkg-config@0.29.2%gcc@7.3.1+internal_glib arch=linux-centos7-zen', 'pkgconf@1.7.3%gcc@7.3.1 arch=linux-centos7-zen']

This goes through fine when i run 'spack install migraphx ^pkg-config'

What is the best solution for this kind of errors?

**Comment by adamjstewart** [comment]
> What is the best solution for this kind of errors?

```console
$ spack clean -m
```

**Comment by srekolam** [comment]
@adamjstewart , can you please let us know if there is any thing pending on our side ?

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Can you resolve the merge conflict with `hip`?

**Comment by srekolam** [comment]
@adamjstewart , i submitted a PR 19300 that resolves this conflict and updates the checksum for rocm3.7.0 and rocm-3.8.0 .

**Pull request closed without merging**
