### PR TITLE
Downloading zlib tarballs from github release page.

### PR DESCRIPTION
**Pull request by weijianwen**
Fix donwloading failures due to invalid zlib tarball URL discussed in #2730 .

### CODE REVIEW

**Comment by alalazo** [comment]
@citibeth *needs to* seems a bit to hard to me. I understand the concerns on security, but given the number of stars the repository has, I would consider it pretty safe. If we really want to dig to the bottom of it, we can compare the sources to see where are the differences for a given version.

**Comment by tgamblin** [comment]
@citibeth: the hash changes here are because github auto-generates its tarballs.  I've seen this issue with other repos before -- github releases often have different hashes from whatever is posted on a project's webpage.

I do think the link @citibeth posted in #2732 is a better way to do his, though.  @weijianwen: do you want to take that change on?  Sorry for all the confusion.

**Comment by weijianwen** [comment]
@tgamblin Rahter than SourceForge or other places, I think both http://zlib.net/fossils/ and github release pages are sound places to host the tarballs -- `spack checksum` works well on these URLs. Since zlib tarball is downloaded from the project site at the very beginning, I prefer to keep this convention. 

```
$ spack checksum zlib
==> Found 69 versions of zlib
  1.2.10   http://zlib.net/fossils/zlib-1.2.10.tar.gz
  1.2.9    http://zlib.net/fossils/zlib-1.2.9.tar.gz
  1.2.8    http://zlib.net/fossils/zlib-1.2.8.tar.gz
  1.2.7.3  http://zlib.net/fossils/zlib-1.2.7.3.tar.gz
  1.2.7.2  http://zlib.net/fossils/zlib-1.2.7.2.tar.gz
  1.2.7.1  http://zlib.net/fossils/zlib-1.2.7.1.tar.gz
  1.2.7    http://zlib.net/fossils/zlib-1.2.7.tar.gz
  1.2.6.1  http://zlib.net/fossils/zlib-1.2.6.1.tar.gz
  1.2.6    http://zlib.net/fossils/zlib-1.2.6.tar.gz
  ...
  0.8      http://zlib.net/fossils/zlib-0.8.tar.gz

How many would you like to checksum? (default is 5, q to abort)
```

**Comment by citibeth** [comment]
>
> @citibeth <https://github.com/citibeth>: the hash changes here are
> because github auto-generates its tarballs. I've seen this issue with other
> repos before -- github releases often have different hashes from whatever
> is posted on a project's webpage.


Yes, that is not unexpected.  For Autotools-based packages, the `configure`
script is often not available when downloading directly from GitHub.

BUT... I still firmly believe that if hashes change, we need to verify the
change.  Otherwise, the hashes aren't worth a hill of beans.

In this case, someone would need to download the new and the old tarballs,
unpack them and diff them.  Then we use our judgement.

It's a lot easier if we don't change hashes, then nobody has to spend time
on this.

**Pull request closed without merging**
