### PR TITLE
Bugfix: glvis new builder interface

### PR DESCRIPTION
**Pull request by becker33**
Take two.

### CODE REVIEW

**Comment by becker33** [comment]
@lee218llnl @tgamblin This should fix the bug

**Comment by alalazo** [comment]
@becker33 @lee218llnl https://github.com/spack/spack/pull/33704/commits/3c19dd691db55376984f826cbbf3625142a6a1ca is all this PR needed to have a correct package. I took some time to do a minimal refactor and pushed that too, but feel free to discard that if it seems unneeded.

Note that the recipe seems broken, as it has issues with `sdl2`:
```
[ ... ]
In file included from lib/sdl.cpp:26:
lib/sdl_x11.hpp:30:26: error: expected ')' before '*' token
   30 |    SdlX11Platform(Display* xdisplay, Window xwindow)
      |                  ~       ^
      |                          )
lib/sdl_x11.hpp:99:4: error: 'Display' does not name a type
   99 |    Display* disp;
      |    ^~~~~~~
lib/sdl_x11.hpp:100:4: error: 'Window' does not name a type; did you mean 'SdlWindow'?
  100 |    Window wnd;
      |    ^~~~~~
      |    SdlWindow
lib/sdl_x11.hpp: In member function 'virtual void SdlX11Platform::WaitEvent()':
[ ... ]
```

**Comment by lee218llnl** [comment]
FWIW, this built OK for me.

**Comment by alalazo** [comment]
@lee218llnl Fine with me to merge if it fixes your issue.

**Review by lee218llnl — APPROVED** [review]

**Comment by v-dobrev** [comment]
@alalazo, I'll try to reproduce the error you got and fix it a new PR. Also, GLVis has newer versions that I can add.

**Comment by v-dobrev** [comment]
Hi @alalazo, I tried various `glvis` builds on Linux but could not reproduce the issue you reported above. If you have some time, can you try #33728? Thanks!

**Pull request merged**
