### PR TITLE
gh: add v2.49.2

### PR DESCRIPTION
**Pull request by mathomp4**
This PR adds gh 2.49.2 to spack. The last version here was 2.43.1 which is a bit old.

Note: I am a *user* of gh but not a developer. So, the one thing I don't know is if the go version for gh should be upped. In the package I see:

```python
    depends_on("go@1.16:", type="build")
    depends_on("go@1.18:", type="build", when="@2.10.0:")
    depends_on("go@1.19:", type="build", when="@2.21.0:")
    depends_on("go@1.21:", type="build", when="@2.33.0:")
```

I was able to `spack install gh@2.49.2` and it used `go@1.22.2` during build. But I have no idea if or when that is *required*. Perhaps @andyfeller or @williammartin could comment here and let us know if go 1.22 is a build req for gh after a certain version.

### CODE REVIEW

**Comment by lcnzg** [comment]
@mathomp4 The go 1.22 has introduced in gh 2.47.0 https://github.com/cli/cli/releases/tag/v2.47.0

**Review by alalazo — CHANGES_REQUESTED** [review]
See @lcnzg comment

**Comment by mathomp4** [comment]
> See @lcnzg comment

@alalazo I've added a new requirement for `go@1.22`.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
If @lcnzg is fine with the PR I'd merge

**Comment by andyfeller** [comment]
👋 nice to meet everyone!

As someone already chimed in on `gh` and Go 1.22 version, I wanted to ask if `spack` community has thought about a scheduled workflow similar to https://github.com/Homebrew/formulae.brew.sh/blob/master/.github/workflows/scheduled.yml which is used to pick up updates to brew formulae and publish them in the index.

_My thought was seeing how the spack community might reduce manual management of versions like this in the future.  Just an idea._

Thanks for being users and supporters of the GitHub CLI!

heart-twocats

**Comment by alalazo** [comment]
@andyfeller Thanks for the pointer. We have something similar here: 
- https://github.com/spack/packages.spack.io/blob/main/.github/workflows/update-ui.yaml

which updates this website: https://packages.spack.io/ What we'd need, and iirc @alecbcs was working on that, is something like `homebrew` autobump of formulae (the `package.py` you see in PRs are our formulae)

**Review by lcnzg — APPROVED** [review]

**Pull request merged**
