### PR TITLE
document blas and lapack usage in packages

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/LLNL/spack/issues/894

### CODE REVIEW

**Comment by davydden** [comment]
@tgamblin ping (docu update on blas/lapack).

**Comment by adamjstewart** [comment]
Unless this is already part of another PR, can you add blas_shared_lib/blas_static_lib/lapack_shared_lib/lapack_static_lib for atlas?

**Comment by davydden** [comment]
@adamjstewart that's a bit outside of the scope of this PR :smile: Seriously speaking, I don't use Atlas and I am not sure about its libraries structure.

**Comment by adamjstewart** [comment]
Fair enough. I don't actually use it either, I just know it's been requested.

**Comment by adamjstewart** [comment]
In that case, LGTM

**Pull request merged**
