### PR TITLE
binutils: add version 2.35.1

### PR DESCRIPTION
**Pull request by hainest**
@mwkrentel

### CODE REVIEW

**Comment by mwkrentel** [comment]
There's a bug in libbfd in binutils 2.35 that spews errors.  This is
not fixed in 2.35.1.  You haven't seen this?  It should be visible in
a Symtab app, like hpcstruct.

I sent this to my (hpctoolkit) team.

>    Don't use binutils 2.35 (or 2.35.1).  There's a bug in libbfd that
>    spews errors from hpcprof from struct-simple for some files.
>    
>    BFD: DWARF error: could not find variable specification at offset 13df
>    BFD: DWARF error: could not find variable specification at offset 1455
>    BFD: DWARF error: could not find variable specification at offset 291f
>    
>    This is fixed in binutils master, but not yet in a release.  So, until
>    2.36 (or maybe 2.35.2) comes out, stick to binutils 2.34.
>    I've updated the sample packages.yaml file in master with a note
>    about this.
>    
>    https://sourceware.org/bugzilla/show_bug.cgi?id=26520

So, my reaction is eh.  Add it if you really want, but I'm waiting for
2.36 or 2.35.2.

Maybe you want to look at how large a path would be necessary to fix
2.35.  I took a quick glance and decided to wait until 2.36.

**Comment by hainest** [comment]
@mwkrentel All of my environments are using 2.33. I was planning on doing tests with more recent versions when I noticed 2.35.1 was out- hence the PR. I'll do some tests after I'm done chasing some other bugs and let you know what I find.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Is this still a WIP?

**Comment by hainest** [comment]
@adamjstewart This latest version has a bug in it, but it's still an official version. Unless @mwkrentel outright objects, I think we should still include it. It's no more or less broken that 2.35.

**Comment by mwkrentel** [comment]
@hainest I think you got the wrong sha256 sum for binutils 2.35.1.
You added the GZ version, but the spack recipe uses BZ.
Sigh

```
320e7a1d0f46fcd9f413f1046e216cbe23bb2bce6deb6c6a63304425e48b1942  binutils-2.35.1.tar.bz2
a8dfaae8cbbbc260fc1737a326adca97b5d4f3c95a82f0af1f7455ed1da5e77b  binutils-2.35.1.tar.gz
```

**Comment by adamjstewart** [comment]
Can someone submit a PR?

**Pull request merged**
