### PR TITLE
package cuda: fix for chmod error

### PR DESCRIPTION
**Pull request by g-mathias**
chmod throws an error if cached cuda installer has only rx permissions but not w

### CODE REVIEW

**Comment by adamjstewart** [comment]
@svenevs and @ax3l are our CUDA package experts, but they're both really busy right now. I'll let them know to take a look at this when they get a chance. Sorry for the delay!

**Comment by svenevs** [comment]
Thanks for ping, this is very odd. `chmod` should be ok with adding `+x` indefinitely. If set it should just set it again.

That said the change looks fine, but I'd like to add a `# NOTE:` with a better explanation or link to this PR. Initially I'd see that code and want to remove it, so it's good to explain why :slightly_smiling_face:

Other option could be just `chmod 777` blindly, it sounds to me like this is distro specific. I'd like to try and recreate the issue in a docker container, what OS? Steps to reproduce would be

1. `spack install cuda`
2. `spack uninstall cuda`
3. `spack install cuda`

right?  I'm in an internet deficient situation so it may take a few days to test (I have to walk for internet, but do so at ~3am usually every other night because it's otherwise too congested / not safe to go to during the day).

P.S. Do you happen to be using an NFS or shared filesystem? That could be the underlying cause?  The same fix can still be incorporated, just very curious.

Please excuse any phone typing errors :heart:

**Comment by g-mathias** [comment]
Hi @svenevs ,
thanks for your kind request
here's some more info and details:
> spack debug report
* **Spack:** 0.15.0-290-494b5a126
* **Python:** 3.6.10
* **Platform:** linux-sles15-haswell

The file system is a spectrum scale (gpfs) mount, but I think it does not matter.

We use a common default cache `/path/to/spack/cache/_source-cache/` and generate links with e.g. `spack mirror create cuda`. This yields
```
ll /path/to/spack/cache/cuda/
total 267
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-9.0.176 -> ../_source-cache/archive/96/96863423feaa50b5c1c5e1b9ec537ef7ba77576a3986652351ae43e66bcd080c
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-9.1.85 -> ../_source-cache/archive/84/8496c72b16fee61889f9281449b5d633d0b358b46579175c275d85c9205fe953
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-9.2.88 -> ../_source-cache/archive/8d/8d02cc2a82f35b456d447df463148ac4cc823891be8820948109ad6186f2667c
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-10.0.130 -> ../_source-cache/archive/92/92351f0e4346694d0fcb4ea1539856c9eb82060c25654463bfd8574ec35ee39a
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-10.1.243 -> ../_source-cache/archive/e7/e7c22dc21278eb1b82f34a60ad7640b41ad3943d929bebda3008b72536855d31
lrwxrwxrwx   1 someone mygroup     92 Jul 22 11:28 cuda-10.2.89 -> ../_source-cache/archive/56/560d07fdcf4a46717f2242948cd4f92c5f9b6fc7eae10dd996614da913d5ca11
```
The link targets look like
```
ll -L /path/to/spack/cache/cuda/*
-rwxr-xr-x 1 smoelse mygroup 2572375299 May 12 16:44 /path/to/spack/cache/cuda/cuda-10.1.243
-rwxr-xr-x 1 smoelse mygroup 2645419389 Jun  3 16:54 /path/to/spack/cache/cuda/cuda-10.2.89
-rwxr-xr-x 1 smoelse mygroup 1758421686 Jun  3 16:58 /path/to/spack/cache/cuda/cuda-9.2.88
-rw-r--r-- 1 smoelse mygroup 1465528129 Jun 25 01:05 /path/to/spack/cache/cuda/cuda-8.0.61
-rw-r--r-- 1 smoelse mygroup 1643293725 Jun 25 01:05 /path/to/spack/cache/cuda/cuda-9.0.176
-rw-r--r-- 1 smoelse mygroup  1639829845 Jun 25 01:06 /path/to/spack/cache/cuda/cuda-9.1.85
-rw-r--r-- 1 smoelse mygroup  2020126691 Jun 25 01:06 /path/to/spack/cache/cuda/cuda-10.0.130
```

So there seem to be two issues

- if I run 
```
> chmod a+x /path/to/spack/cache/cuda/cuda-10.1.243
chmod: changing permissions of '/path/to/spack/cache/cuda/cuda-10.1.243': Operation not permitted
```
I get an error although the `x` bit is set for `all` already; this is because I don't have write permissions for the target file. This situation is fixed by the change
- If `x` is not set in the first place (e.g. cuda-10.0.130), the fix doesn't help. Here, I think the cleaner solution would be to copy the installer tar ball to the staging directory and run the `chmod` there. I would assume a mirror to be readable but not necessarily writeable. 

Don't worry, if you are out of office. The fix is not urgent.

Best,
Gerald

**Comment by svenevs** [comment]
Great, thank you for the detailed report! I see, yes I think your diagnosis of the permissions / ownership issue is correct.  While there are site-specific fixes you could institute (fix permissions of your symlinked archives to allow `mygroup` modifications), this is something we should be able to circumvent for all sites. I wasn't even considering group spack use, there are probably a lot of variants that result in the same issue.

I think running `chmod` during the `stage` phase is what we want but will have to look more closely. I remember the Intel installers getting symlinked under `/tmp` in the stage directory and running out of space so my assumption is something similar does (or could / should) happen for CUDA.

**Comment by ax3l** [comment]
Can we just change the logic to run the runfile with `sh`? Works without `chmod` and is the recommended way to install things with [Nvidia's instructions](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Debian&target_version=10&target_type=runfilelocal):
e.g.:
```sh
wget https://developer.download.nvidia.com/compute/cuda/11.1.0/local_installers/cuda_11.1.0_455.23.05_linux.run
sudo sh cuda_11.1.0_455.23.05_linux.run
```

**Review by adamjstewart — APPROVED** [review]

**Review by svenevs — APPROVED** [review]
Good call on using `sh`, sorry for letting this one fall off my radar :confused:

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/cuda/package.py:120: [W293] blank line contains whitespace
```

**Comment by ax3l** [comment]
Thanks, looks great!

**Pull request merged**
