### PR TITLE
py-mpi4py: create mpi.cfg file, this file is  removed since v4.0.0, but API is retained

### PR DESCRIPTION
**Pull request by tech-91**
Is it possible to merge this PR?

It creates a mpi.cfg file which has been introduced since version 4.0.0 (see  [here](https://mpi4py.readthedocs.io/en/stable/mpi4py.html#mpi4py.get_config))

### CODE REVIEW

**Comment by balay** [comment]
```console
balay@pj01:~/spack$ cat /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/py-mpi4py-4.0.1-wstoqejuaoxr7apzlbvkvhjzm2rqs4mq/lib/python3.11/site-packages/mpi4py/mpi.cfg
[mpi]
mpi_dir              = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej
mpicc                = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/bin/mpicc
mpicxx               = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/bin/mpic++
## define_macros        =
## undef_macros         =
include_dirs         = ['/home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/include']
## libraries            = mpilibrary_dirs         = ['/home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/lib']
## runtime_library_dirs = %(mpi_dir)s/lib## extra_compile_args   =
## extra_link_args      =
## extra_objects        =
```

Missing a few line breaks?

**Comment by dalcinl** [comment]
I'm not opposed in principle, although I would recommend any consumer of this to follow what it is done in PETSc:
https://gitlab.com/petsc/petsc/-/blob/main/setup.py?ref_type=heads#L116

**Comment by tech-91** [comment]
> ```
> balay@pj01:~/spack$ cat /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/py-mpi4py-4.0.1-wstoqejuaoxr7apzlbvkvhjzm2rqs4mq/lib/python3.11/site-packages/mpi4py/mpi.cfg
> [mpi]
> mpi_dir              = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej
> mpicc                = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/bin/mpicc
> mpicxx               = /home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/bin/mpic++
> ## define_macros        =
> ## undef_macros         =
> include_dirs         = ['/home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/include']
> ## libraries            = mpilibrary_dirs         = ['/home/balay/spack/opt/spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.3-lzkqexcq4zcixxhayn67jhdilplfyeej/lib']
> ## runtime_library_dirs = %(mpi_dir)s/lib## extra_compile_args   =
> ## extra_link_args      =
> ## extra_objects        =
> ```
> 
> Missing a few line breaks?

My mistake. It should be ok now.

**Comment by tech-91** [comment]
> I'm not opposed in principle, although I would recommend any consumer of this to follow what it is done in PETSc: https://gitlab.com/petsc/petsc/-/blob/main/setup.py?ref_type=heads#L116

Thanks for pointing out this example @dalcinl.
Yet, for what I understand, this doesn't fixe the runtime behavior of mpi4py.get_config().
This is why I chose to create a dedicated mpi.cfg file.

**Comment by tech-91** [comment]
@dalcinl, @balay @adamjstewart  any update?

**Review by dalcinl — APPROVED** [review]

**Review by balay — APPROVED** [review]

**Review by dalcinl — APPROVED** [review]

**Comment by dalcinl** [comment]
Can someome please updage the title of this PR to reflect what really happening in mpi4py? mpi4py 4.0.0 **removed** the `mpi.cfg` file in 4.0.0, but keept the API related to it, such that downstream distributors of mpi4py builds could choose to keep supporting it so store MPI build information. Therefore, I think replacing "introduced" -> "removed" in this PR title is more accurate of what's going on.

**Comment by balay** [comment]
Updated the PR title. Is this OK? [if so - will merge in]

**Review by dalcinl — APPROVED** [review]

**Pull request merged**
