### PR TITLE
texinfo: add dependence on gettext for 6.7.0:

### PR DESCRIPTION
**Pull request by kuberry**
Version 6.7 onward of texinfo relies on gettext, https://lists.gnu.org/archive/html/info-gnu/2019-09/msg00007.html, but this dependency is not captured in the package.py.

Failing to configure with gettext causes missing `libintl.h` file when building like:
```sh
make: *** [all] Error 2
==> [2022-12-13-14:24:34.954233] Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

7 errors found in build log:
     3759    #define XSRETURN_EMPTY STMT_START {                XSRETURN(0); } STMT_END
     3760                                      ^
     3761    parsetexi/Parsetexi.c:571:5: warning: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Wcompound-token-spl
             it-by-macro]
     3762        XSRETURN_EMPTY;
     3763        ^~~~~~~~~~~~~~
     3764    /Users/pakuber/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/perl-5.36.0-gnvi5nl74soq36uxjvi2h6dhyuhsipae/lib/5.36.0/darwin-thread-multi-2level/CORE
             /XSUB.h:340:52: note: expanded from macro 'XSRETURN_EMPTY'
  >> 3765    parsetexi/api.c:28:10: fatal error: 'libintl.h' file not found
     3766    #define XSRETURN_EMPTY STMT_START {                XSRETURN(0); } STMT_END
     3767                                                       ^~~~~~~~~~~
     3768    /Users/pakuber/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/perl-5.36.0-gnvi5nl74soq36uxjvi2h6dhyuhsipae/lib/5.36.0/darwin-thread-multi-2level/CORE
             /XSUB.h:325:5: note: expanded from macro 'XSRETURN'
     3769        STMT_START {                                        \
     3770        ^~~~~~~~~~
     3771    ./ppport.h:4001:28: note: expanded from macro 'STMT_START'

     ...

     4033                                                                      ^~~~~~~~
```

### CODE REVIEW

**Comment by kuberry** [comment]
@spackbot re-run pipeline

**Comment by kuberry** [comment]
@spackbot re-run pipeline

**Review by bernhardkaindl — APPROVED** [review]
LGTM (Not an issue on glibc systems as libintl is in glibc there, but likely needed for non-glibc)

**Comment by kuberry** [comment]
> LGTM (Not an issue on glibc systems as libintl is in glibc there, but likely needed for non-glibc)

The only failure in the pipeline is `libzmq` in the `e4s-mac-pr-build`, which has to do with `libzmq`'s dependence on `libsodium` (unrelated to texinfo). Neither of these are touched by this PR. Also a new PR https://github.com/spack/spack/pull/34553 has been opened to deal with the `libsodium`/`libzmq` issue.

**Comment by eugeneswalker** [comment]
> > LGTM (Not an issue on glibc systems as libintl is in glibc there, but likely needed for non-glibc)
> 
> The only failure in the pipeline is `libzmq` in the `e4s-mac-pr-build`, which has to do with `libzmq`'s dependence on `libsodium` (unrelated to texinfo). Neither of these are touched by this PR. Also a new PR #34553 has been opened to deal with the `libsodium`/`libzmq` issue.

The `e4s-mac` pipeline is optional. It can fail, and it won't hold up a PR or cause the overall pipeline to be marked as a failure. It is failing on all PR's (not just yours) beacuse of a relocation issue affecting Spack generally on macOS. 

I think the cause of the ultimate pipeline failure here is actually shown here:
* https://gitlab.spack.io/spack/spack/-/pipelines/239679

Which is the `tutorial-pr` pipeline.

**Comment by kuberry** [comment]
@spackbot re-run pipeline

**Comment by bernhardkaindl** [comment]
One if the errors in the Tutorial pipeline is:
```py
> @spackbot re-run pipeline

==> Error: NoHeadersError: Unable to locate zstd headers in /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/zstd-1.5.2-fprmzmoubdjdr663rprctp2tuqiv5apu

/builds/spack/spack/var/spack/repos/builtin/packages/gcc/package.py:740, in configure_args:

737 options.append("--with-system-zlib")

738

739 if "zstd" in spec:

>> 740 options.append("--with-zstd-include={0}".format(spec["zstd"].headers.directories[0]))
```
Hm, very strange, especially in the gcc/package.py

**Comment by kuberry** [comment]
@bernhardkaindl Yes, it looks like `zstd` is found in the spec, but 

```py
options.append("--with-zstd-include={0}".format(spec["zstd"].headers.directories[0]))
```

has `directories` which isn't a list (for what reason, I do not know). I'm guessing most people don't hit this in testing because `gcc` doesn't depend on the package they are modifying.

**Comment by kuberry** [comment]
@bernhardkaindl @tldahlgren Do you think this PR is actually related to the failed test or can it be merged? This PR is holding up all `apple-clang` builds on mac (The new default Texinfo version fails to build on mac because of the missing file).

**Comment by bernhardkaindl** [comment]
> @bernhardkaindl @tldahlgren Do you think this PR is actually related to the failed test or can it be merged? This PR is holding up all `apple-clang` builds on mac (The new default Texinfo version fails to build on mac because of the missing file).

We are not able to merge any PR until all checks have passed. The failing MacOS pipeline has been disabled now in develop so this should not disturb anymore, but as said above, this was the problem:

> I think the cause of the ultimate pipeline failure here is actually shown here:
    https://gitlab.spack.io/spack/spack/-/pipelines/239679
Which is the tutorial-pr pipeline.

Hopefully that problem where `gcc@8.4.0+zstd` could not find the zstd headers which I mentioned above could be solved by some other change in develop meanwhile, so I merged the latest develop now and this also triggered a complete re-run of all pipelines. Have a look at the ci/glibc-ci pipelines.

If they fail, it must be investigated.

I currently do not have the capacity to dig so deep into it at the moment, so I have to step down as Assingee of this PR.
Assigning @tldahlgren because she assigned me to it.

**Comment by adamjstewart** [comment]
Duplicate of #34312. Can you review that PR and see if it solves your issue?

**Comment by kuberry** [comment]
> Duplicate of #34312. Can you review that PR and see if it solves your issue?

I will be able to check tomorrow early in the AM. The approach seems correct, but I'm not sure this was necessary before 6.7 or would be used correctly before that version. It was going from 6.6 to 6.7 of Texinfo that the developers ensured building the XS subpackage in Texinfo could have a compiler completely independent of the one used to build Texinfo (but consistent with Perl).

**Comment by kuberry** [comment]
https://github.com/spack/spack/pull/34312 fixes the same issue. I mentioned this on that PR as well, but #34312 works with `texinfo@6.5:`.

**Comment by tgamblin** [comment]
Superseded by #34507 -- I'm going to integrate @kuberry's version constraint from this PR there.

**Pull request closed without merging**
