### PR TITLE
lammps: version bump, switch to cmake

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@davydden: lammps/lammps#573

**Comment by davydden** [comment]
WoW! :+1:

**Comment by tgamblin** [comment]
@junghans: is it worth preserving the old version?  i.e., will LAMMPS users want to reproduce anything with that?

**Comment by junghans** [comment]
@tgamblin: If somebody asks for an old version assign it to me ;-)

**Pull request merged**
