### PR TITLE
py-msgpack: add 1.0.3

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://github.com/msgpack/msgpack-python/tree/v1.0.3

The `py-cython` dependency for the older version can be found in `requirements.txt`

### CODE REVIEW

**Comment by adamjstewart** [comment]
It seems like the setuptools and cython version requirements are present in main but not in 1.0.3. There is no `pyproject.toml`or `requirements.txt` in 1.0.3.

**Comment by manuelakuhn** [comment]
I got the requirements from <https://github.com/msgpack/msgpack-python/blob/v1.0.3/pyproject.toml>. The `py-cython` requirement you can also find in <https://github.com/msgpack/msgpack-python/blob/v1.0.3/requirements.txt>. The latter also exists for older versions on github.

But I think I see what you mean: After double checking, the tarball on pypi seems to be different and these files are not present there.

**Comment by adamjstewart** [comment]
Many tarballs on PyPI come pre-cythonized so cython is often only needed to build a git checkout.

**Comment by manuelakuhn** [comment]
Ok, I have removed the dependencies again.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
