### PR TITLE
Fix recipe for evtgen 2.0; add variant for hepmc3

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
Ping @vvolkl, who is the maintainer of evtgen

**Review by vvolkl — DISMISSED** [review]

**Review by vvolkl — DISMISSED** [review]

**Comment by adamjstewart** [comment]
Now that we can [deprecate versions](https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions), why don't we simply deprecate the old version and remove it in the next release?

**Comment by iarspider** [comment]
For me, it's ok. @vvolkl ?

**Comment by vvolkl** [comment]
The deprecation functionality is very nice! But I still know of some people doing studies with evtgen 1.7.0 in our group, let me ask them first if they are ok with upgrading.

**Review by adamjstewart — DISMISSED** [review]

**Comment by vvolkl** [comment]
@iarspider For key4hep we are fine with v2.0, so no problem to deprecate v1.7

**Comment by iarspider** [comment]
> @iarspider For key4hep we are fine with v2.0, so no problem to deprecate v1.7

Thanks for the confirmation!

**Review by vvolkl — APPROVED** [review]

**Review by alalazo — APPROVED** [review]
:+1: from maintainer, merging

**Pull request merged**
