### PR TITLE
docutils > 0.17 issue with rendering list items in sphinx

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
This PR will address issue with rendered list items in sphinx we must use 0.16.x in order for this to work for time being until this is fixed in docutils.

This is an issue where list dont show up correctly. I can confirm this change fix the issue.

Screen Shot 2021-09-29 at 4 53 25 PM

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
This LGTM. Can you also update `lib/spack/docs/spack.yaml` with the same change?

**Comment by bernhardkaindl** [comment]
> This LGTM. Can you also update `lib/spack/docs/spack.yaml` with the same change?

@shahzebsiddiqui ping - can you also do the requested change?

**Comment by shahzebsiddiqui** [comment]
@bernhardkaindl @adamjstewart  i have updated the spack.yaml with the restriction though i noticed the latest version we have is 0.15.2 however on pypi we have more newer versions up to 0.18b1 see https://pypi.org/project/docutils/#history. I am not sure if spack will work considering there is no `0.17` version in the package.py recipe.

**Comment by bernhardkaindl** [comment]
> @bernhardkaindl @adamjstewart i have updated the spack.yaml with the restriction though i noticed the latest version we have is 0.15.2 however on pypi we have more newer versions up to 0.18b1 see https://pypi.org/project/docutils/#history. I am not sure if spack will work considering there is no `0.17` version in the package.py recipe.

Hi @shahzebsiddiqui, I understood that `docutils < 0.17` (specifially you wrote 0.16.x in the desciption of this PR) was the requirement for correct rendering of spack's documentation.

And the `requirements.txt` you propose has:
```py
# Restrict to docutils <0.17 to workaround a list rendering issue in sphinx.
# https://stackoverflow.com/questions/67542699
docutils <0.17
```

But in the `lib/spack/docs/spack.yaml`, you'd add `py-docutils@0.17:` - this does not match your description:

`py-docutils@0.17:` refers to needing version 0.17 or newer. I was guessing that would add  `py-docutils@:0.16` (this should match any 0.16.x  version and below now), or if it is just 0.16.x, the `py-docutils@0.16` (without the `:`).

For "`py-docutils@0.16`", or "`py-docutils@0.17:`" 

For these, You'd also need to add a checksum for a working build of docutils in the `0.16.x` range (for the former case) or the `>=0.17` range (for the latter case).

But I guess you ment lower than 0.17, so `@:0.16`, right?

**Comment by shahzebsiddiqui** [comment]
you are right @bernhardkaindl i do mean any version less than `0.17` so i did `py-docutils@:0.16` which should be any version maximum of 0.16

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
