### PR TITLE
dealii: set DEAL_II_DIR when loading a module

### PR DESCRIPTION
**Pull request by davydden**
see https://github.com/LLNL/spack/issues/815
thanks to @alalazo for pointing me to the solution.

@tgamblin that should be a no-brainer PR :smile:

### CODE REVIEW

**Comment by mathstuf** [comment]
Hrm. The deal.ii package should instead install a CMake configuration file and then everything should Just Work™ since `CMAKE_PREFIX_PATH` will contain the deal.ii prefix already. This also means that projects can drop any `Finddeal.ii.cmake` modules they may have as well (if they bump requirements to deal.ii packages containing the config file).

**Comment by mathstuf** [comment]
But, if this environment variable is the current state of things, it can't hurt :) .

**Comment by davydden** [comment]
if you look at any of the tutorials here https://www.dealii.org/8.4.1/doxygen/deal.II/Tutorial.html , they all use by default `DEAL_II_DIR` as a hint in CMakeList.txt. Note that the user program are already configured using deal.ii's Cmake extra machinery to get proper linking flags with lots of dependencies etc. 

So the user case here is different and one does not need a `Finddeal.ii.cmake` at all.

**Comment by davydden** [comment]
p.s. you would see it from tutorials, but here is an example https://github.com/dealii/dealii/blob/master/examples/step-1/CMakeLists.txt

**Comment by davydden** [comment]
for completeness

> After finding the deal.II project, we fetch a set of cached variables with the DEAL_II_INITIALIZE_CACHED_VARIABLES macro. You can inspect these for instance with ccmake.
>
>Every CMakeLists.txt must contain a project definition, which we do next.
>
>Finally, the last two lines define the executable that is to be produced and its source code. The DEAL_II_SETUP_TARGET macro will set up necessary include directories, compile flags, compile definitions, link flags and the link interface.

from here https://www.dealii.org/developer/users/cmakelists.html

**Comment by mathstuf** [comment]
Hrm. Seems like they've reinvented things which CMake does for you (though to be fair, at 2.8.8, they were probably contemporary with the features being introduced). If you install the right files, `find_package(deal.II)` should work just fine, `deal_ii_setup_target(tgt)` can probably just be a `target_link_libraries(tgt deal.ii)` these days. Not a fan of how it hijacks the dependent project's `CMAKE_BUILD_TYPE` and forces you to match deal.II's settings (I can debug my app separately from deal.II or vice versa).

Since this is how deal.II documents how it is supposed to be used, it should work as long as the dependent libraries have done the right things, but it'd be really nice if deal.II would use more modern CMake facilities so that it isn't such a special snowflake :) .

**Comment by mathstuf** [comment]
Hmm, looking at a deal.II install, they *do* install things properly. Their code could probably do with some `target_compile_definitions` and `target_include_directories` to make all of this simpler :) . Looking at `deal.IIConfig.cmake` itself, it does indeed look like it could use with some modernization and chunks of code could just go away.

**Comment by mathstuf** [comment]
I guess to be clear: +1 for this PR given the current situation.

**Comment by tgamblin** [comment]
@davydden: have you guys looked at using `CMAKE_PREFIX_PATH` in your docs for users?  We used to use the `*_DIR` convention at LLNL based on the conventions circa CMake 2.8, but I find it much easier now to tell everyone to set `CMAKE_PREFIX_PATH` because you can use one variable for everything, and users won't misspell or mis-capitalize package names in env vars.

**Comment by davydden** [comment]
@mathstuf thanks for your suggestions.

@tgamblin i personally have not, but i will pass your suggestion to other guys who are more experienced in CMake.

**Comment by tamiko** [comment]
@tgamblin @davydden ```CMAKE_PREFIX_PATH``` will automatically be considered in just about any ```FIND_*``` macro in cmake. I have included feature specific hints via ```*_DIR``` in deal.II to allow for a more fine grained configuration. Both work just fine.

**Comment by tgamblin** [comment]
@tamiko: out of curiosity, what more specific hints do you add for the `*_DIR` variants that will be ambiguous or are not possible when using `CMAKE_PREFIX_PATH`?

**Comment by tamiko** [comment]
@mathstuf If you do not want to use ```DEAL_II_SETUP_TARGET```, then just

```
FIND_PACKAGE(deal.II) # Find and include deal.IIConfig.cmake
INCLUDE(${DEAL_II_TARGET_CONFIG}) # include deal.IITargets.cmake
TARGET_LINK_LIBRARIES(target ${DEAL_II_TARGET})
```

**Comment by tamiko** [comment]
@tgamblin The big problem with ```CMAKE_PREFIX_PATH``` is that it specifies a generic preference for everything. If you happen to have multiple libraries installed at the same location and just want a cmake configuration to pick up one specific then you cannot do this with ```CMAKE_PREFIX_PATH```.

The question whether to support fine-grained hints, or not, is a bit of a personal taste. But judging from the last 2 years with CMake in deal.II I have seen just about any use case or setup you can imagine and fine grained hints via ```*_DIR``` helped a bit. :-]

**Comment by tamiko** [comment]
@mathstuf 
> Not a fan of how it hijacks the dependent project's CMAKE_BUILD_TYPE and forces you to match deal.II's settings (I can debug my app separately from deal.II or vice versa).

Please **don't** use ```DEAL_II_INITIALIZE_CACHED_VARIABLES```, or ```DEAL_II_INVOKE_AUTOPILOT``` for anything else than a very simple user program. Then, there is also no hijacking.

**Comment by tgamblin** [comment]
@tamiko: ok I get it... sounds scary.  Say `deal_ii` depends on `foo`, `bar`, and `baz`.  

I can see this being useful.  Say you want foo at the "newest" version:
```
FOO_DIR=/software/prefix-a
BAR_DIR=/software/prefix-b
BAZ_DIR=/software/prefix-a

/software/prefix-a/lib/
    libfoo.so        # newest foo
    libbaz.so
/software/prefix-b/lib/
    libfoo.so        # old foo
    libbar.so
```

Do you actually figure out how to order the `RPATH`s to correctly handle the case above?

How about this one, if you want the newest versions of each lib?

```
FOO_DIR=/software/prefix-a
BAR_DIR=/software/prefix-b
BAZ_DIR=/software/prefix-b

/software/prefix-a/lib/
    libfoo.so        # newest foo
    libbaz.so        # old baz
/software/prefix-b/lib/
    libfoo.so        # old foo
    libbar.so
    libbaz.so        # newest baz
```

Depending on the DAG you *could* actually make this work too but it depends on how your deps were built and what their `RPATH`s were... do you detect this?  Does `deal.ii` warn if it finds conflicting libraries in the various prefixes?

**Comment by tamiko** [comment]
> Do you actually figure out how to order the RPATHs to correctly handle the case above?

We try to make sure to find the correct (and reasonably complete) link interface for external dependencies (have a look at ```detailed.log```). So, we would find:
```
  FOO_LIBRARIES=/software/prefix-a/lib/libfoo.s
  BAR_LIBRARIES=/software/prefix-b/lib/libbar.so
  BAZ_LIBRARIES=/software/prefix-b/lib/libbaz.so
```
and handle this information over to CMake that does the gory RPATH handling. If there is an issue CMake usually warns very verbosely:
```
CMake Warning at [...] (add_library):
  Cannot generate a safe linker search path for target [...] because
  files in some directories may conflict with libraries in implicit directories:

  [...]
```

But there are countless other ways you could shoot yourself in the foot in above scenario. If, for example, there is any other library dynamically loading the old libfoo variant (and the latter doesn't do complete symbol versioning) you're screwed (independently of the build system).

**Comment by mathstuf** [comment]
@tamiko FYI, CMake already assumes things about the `_DIR` variables (though not environment variables). `find_package(foo)` will use `FOO_DIR` to look for a `fooConfig.cmake` or `foo-config.cmake` file, though I'm not sure how the `.` in `deal.II` gets treated (whether literally or turned into an underscore), it should point to `<prefix>/lib/cmake/deal.II`. I'd recommend using `DEAL_II_ROOT` if you want to use it for specifying the install prefix of `deal.II` so that a user can use the `_DIR` functionality of `find_package`.

> FIND_PACKAGE(deal.II) # Find and include deal.IIConfig.cmake
> INCLUDE(${DEAL_II_TARGET_CONFIG}) # include deal.IITargets.cmake

Hmm, I've mostly seen the config files automatically including the targets file so that you can just use the imported targets directly, but maybe that's just an "ism".

**Pull request merged**
