### PR TITLE
libjpeg-turbo fix SHA256 value for 2.0.4 tar ball.

### PR DESCRIPTION
**Pull request by ikitayama**

### CODE REVIEW

**Review by scheibelp — APPROVED** [review]

**Review by scheibelp — COMMENTED** [review]
I didn't realize it but there is a merge issue: to resolve it you can merge from the develop branch into this branch, or rebase this branch on develop.

**Comment by ikitayama** [comment]
I get ```$ git merge origin/develop
Already up to date.```

**Comment by scheibelp** [comment]
It looks like https://github.com/spack/spack/pull/17154 adjusted the SHA of `libjpeg-turbo@2.0.4` and was merged into Spack as commit 6d9f026

**Comment by ikitayama** [comment]
I've updated my local develop branch.

**Comment by adamjstewart** [comment]
Closing this PR as it has been superseded by #17154

**Pull request closed without merging**
