### PR TITLE
rocfft ,rocrand changes for rocm-3.8.0

### PR DESCRIPTION
**Pull request by srekolam**

### CODE REVIEW

**Comment by srekolam** [comment]
@adamjstewart  can you review and approve

**Comment by srekolam** [comment]
@haampie  , for 3.8.0 ,can youlet us know if you can update the rocblas, a few recipes are dependent on it

**Comment by haampie** [comment]
Sure, let me try the whole stack tomorrow with SIRIUS and spfft

**Comment by srekolam** [comment]
@haampie  @adamjstewart  can you please approve

**Review by adamjstewart — APPROVED** [review]

**Review by haampie — APPROVED** [review]
Yeah, tested with spfft and works

**Pull request merged**
