### PR TITLE
elfutils: add version 0.187

### PR DESCRIPTION
**Pull request by mwkrentel**
Move conflict for debuginfod to variant when clause.

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Comment by mwkrentel** [comment]
@spackbot run pipeline

**Comment by hainest** [comment]
They are both failing to find a binary for papi. This is from the tau log, but they are identical outputs.

```
==> [2022-10-19-22:05:10.041932] Processing papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat: task=priority=0, status=dequeued, start=0, #dependencies=0
==> [2022-10-19-22:05:10.042307] Acquiring a write lock on papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat with timeout 1e-09
==> [2022-10-19-22:05:10.042409] papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat is now write locked
==> [2022-10-19-22:05:10.044105] Creating stage lock spack-stage-papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat
==> [2022-10-19-22:05:10.044830] Searching for binary cache of papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat
==> [2022-10-19-22:05:10.045115] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2022-10-19-22:05:10.061379] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2022-10-19-22:05:12.331355] Error: No binary for papi-6.0.0.1-x5jjipbu4pgdemvlzqlea72tjjajiaat found when cache-only specified
```

**Comment by mwkrentel** [comment]
How's this for irony.  Spackbot says to cut-n-paste this into `package.py`
to add myself as maintainer (see above).

```
maintainers = ['mwkrentel']
```

The problem is that the above fails flake due to single vs double quotes !
Grrrr.

**Comment by mwkrentel** [comment]
@spackbot run pipeline

**Comment by mwkrentel** [comment]
Close/reopen in an attempt to restart the docs/read-the-docs test.
It worked !!

**Comment by mwkrentel** [comment]
@eugeneswalker @tldahlgren 
I now have all the green checks and the only extra change I made
was to add myself as maintainer.

Could someone re-approve and merge?
Thanks

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Rest LGTM

**Pull request merged**
