### PR TITLE
Fix exit of command "spack patch" 

### PR DESCRIPTION
**Pull request by luigi-calori**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Looks good to me. What was the actual problem that was occurring for you?

**Comment by tgamblin** [comment]
I think he means this:

```
$ spack patch
Traceback (most recent call last):
  File "/Users/gamblin2/src/spack/bin/spack", line 176, in <module>
    main()
  File "/Users/gamblin2/src/spack/bin/spack", line 154, in main
    return_val = command(parser, args)
  File "/Users/gamblin2/src/spack/lib/spack/spack/cmd/patch.py", line 43, in patch
    tty.die("patch requires at least one package argument")
NameError: global name 'tty' is not defined
```

**Comment by tgamblin** [comment]
Trying to avoid extra merge commits, so I just cherry picked 016978b onto develop. This is merged.

**Comment by luigi-calori** [comment]
On 09/03/2016 18:22, Adam J. Stewart wrote:
>
> Looks good to me. What was the actual problem that was occurring for you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LLNL/spack/pull/516#issuecomment-194410542>.
>
I just noticed there was an untrapped error instead of the usual 
suggestion when doing "spack patch"
It's not blocking, just a small simple bug.
Maybe a PR is not appropriate for that. Is there a better workflow for 
simple things?


-- 
Luigi Calori
SuperComputing Applications and Innovation Department
CINECA - via Magnanelli, 6/3, 40033 Casalecchio di Reno (Bologna) - ITALY
Tel: +39 051 6171509  Fax: +39 051 6132198
hpc.cineca.it

**Comment by tgamblin** [comment]
A PR is the right way to do it -- there's just an extra merge commit here that has nothing to do with the really simple change.  I think if i merge this, I end up pulling in a lot of history from your repository in addition to the one-line fix.

Ideally you would base the PR branch on the current develop, so, e.g., make a small branch off of current upstream develop, and send *that* as a PR.  Then the PR only contains the one small change that can be fast-forwarded:

```
git checkout -b bugfix/patch-tty-error
<change>
git add patch.py
git commit -m 'fix error on exit...'
git push github HEAD
```

Then you can merge upstream/develop into your branch with the change after the PR is merged.  You can also merge the bug fix branch into your own branch before the PR is merged, if you need to, and superfluous merge commits stay off the main develop branch.

**Comment by luigi-calori** [comment]
Thanks. I' ve done the patch in the wrong order.

Just to ask, how best way to contribute to other currently open PR, like 
the openmpi with intel?

thanks

Luigi

On 09/03/2016 18:39, Todd Gamblin wrote:
>
> A PR is the right way to do it -- there's just an extra merge commit 
> here that has nothing to do with the really simple change. I think if 
> i merge this, I end up pulling in a lot of history from your 
> repository in addition to the one-line fix.
>
> Ideally you would base the PR branch on the current develop, so, e.g., 
> make a small branch off of current upstream develop, and send /that/ 
> as a PR. Then the PR only contains the one small change that can be 
> fast-forwarded:
>
> |git checkout -b bugfix/patch-tty-error
> <change>
> git add patch.py
> git commit -m 'fix error on exit...'
> git push github HEAD
> |
>
> Then you can merge upstream/develop into your branch with the change 
> after the PR is merged. You can also merge the bug fix branch into 
> your own branch before the PR is merged, if you need to, and 
> superfluous merge commits stay off the main develop branch.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LLNL/spack/pull/516#issuecomment-194417488>.
>


-- 
Luigi Calori
SuperComputing Applications and Innovation Department
CINECA - via Magnanelli, 6/3, 40033 Casalecchio di Reno (Bologna) - ITALY
Tel: +39 051 6171509  Fax: +39 051 6132198
hpc.cineca.it

**Comment by tgamblin** [comment]
The PR will auto-update when you push to the source branch.  So if you have write permission on the source repo, you can contribute to the PR.  I'm not sure how easy that is for you.

I would like to have better permission management on github so that collaborators could just push long-lived branches to the main repo and work on them together.  Unfortunately, github doesn't have branch permissions like bitbucket -- I have to give people write access to the whole repository and can't disallow them from merging to develop or master. If i can sort that out I can probably open up the main Spack repo a bit more.

**Pull request closed without merging**
