### PR TITLE
[WRF] Version update to 4.4

### PR DESCRIPTION
**Pull request by t-brown**
Updating the patches needed to compile WRF version 4.4.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
@spackbot fix style

**Review by tldahlgren — COMMENTED** [review]
Confirmed sha256.

Is there any reason these patches can't be integrated upstream and referenced as patches here?

**Comment by t-brown** [comment]
I'll ask, however upstream tends to always install `netcdf-c` and `netcdf-fortran` into the same `prefix` and hence do not need the extra `NETCDFF*` variables.

**Review by tldahlgren — APPROVED** [review]

**Comment by MichaelLaufer** [comment]
> I'll ask, however upstream tends to always install `netcdf-c` and `netcdf-fortran` into the same `prefix` and hence do not need the extra `NETCDFF*` variables.

For what it is worth, there is a two year old PR (https://github.com/wrf-model/WRF/pull/1269) that fixes the netcdf-c and netcdf-fortran split problem upstream, but the WRF devs are still deliberating if to merge it.

**Pull request merged**
