### PR TITLE
Add applications to aws-pcluster-* stacks

### PR DESCRIPTION
**Pull request by stephenmsachs**
First test to add more applications into the builcache stacks

### CODE REVIEW

**Comment by stephenmsachs** [comment]
Close and re-open to clean out the pipeline cache.

**Comment by stephenmsachs** [comment]
Now running gromacs, openfoam, wrf, mpas-model, quantum-espresso, palace & lammps.

**Review by kwryankrattiger — DISMISSED** [review]
LGTM!

**Comment by stephenmsachs** [comment]
Is there anything else is necessary to have this merged?

**Comment by haampie** [comment]
Your toolchain is broken. The oneapi compiler doesn't work as it uses `libgcc_s.so` from gcc@12, but system binutils, which is too old.

```
/usr/bin/ld: warning: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/usr/bin/ld: warning: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: unable to initialize decompress status for section .debug_aranges
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: file not recognized: File format not recognized
```

Also I still don't get why you cannot just provide a container image that includes the full toolchain. The current setup is incredibly slow and convoluted

**Comment by stephenmsachs** [comment]
> Your toolchain is broken. The oneapi compiler doesn't work as it uses `libgcc_s.so` from gcc@12, but system binutils, which is too old.
> 
> ```
> /usr/bin/ld: warning: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
> /usr/bin/ld: warning: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
> /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
> /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/libgcc.a(_muldi3.o): unable to initialize decompress status for section .debug_info
> /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: unable to initialize decompress status for section .debug_aranges
> /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: unable to initialize decompress status for section .debug_aranges
> /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.3.0-vxlibl3ubl5ptwzb3zydgksfa5osdea6/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64/libgcc_s.so.1: file not recognized: File format not recognized
> ```

Can you please point me to the pipeline or job where this happened? The intel compiler configuration should include an additional `PATH` entry pointing to the gcc@12 `ld`.

> Also I still don't get why you cannot just provide a container image that includes the full toolchain. The current setup is incredibly slow and convoluted

I am eager to know if there is a better way to achieve this. These are the requirements I am working with:
* This build cache will be consumed by AWS ParallelCluster users. Their clusters do not have a predefined shared directory path or pre-installed Intel compiler, so there needs to be some relocation of compiler library dependencies when packages are installed from cache.
* AFAIK the spack pipeline needs to consume a public container and we are not allowed to publish a container that redistributes the Intel compiler. That is why we are installing it on the fly.

If you are aware of a better way to work within these limits, I would be happy to learn.

**Comment by haampie** [comment]
It's currently broken on the `generate` jobs on develop. This PR doesn't seem to add anything to the PATH? See for example https://gitlab.spack.io/spack/spack/-/jobs/10895808:

```
==> Warning: cannot detect libc from oneapi@=2023.2.0. The compiler will not be used during concretization.
==> Warning: cannot detect libc from oneapi@=2023.2.0. The compiler will not be used during concretization.
```

Maybe @kwryankrattiger can comment on how to use a private container image.

**Comment by stephenmsachs** [comment]
> It's currently broken on the `generate` jobs on develop. This PR doesn't seem to add anything to the PATH? See for example https://gitlab.spack.io/spack/spack/-/jobs/10895808:
> 
> ```
> ==> Warning: cannot detect libc from oneapi@=2023.2.0. The compiler will not be used during concretization.
> ==> Warning: cannot detect libc from oneapi@=2023.2.0. The compiler will not be used during concretization.
> ```

Thanks, I'll look into that. Yes, this PR does not address that. It should already happen in `develop` [here](https://github.com/spack/spack/blob/4a40a76291f05fdd76e12497b1891c5ad1705ebe/share/spack/gitlab/cloud_pipelines/scripts/pcluster/setup-pcluster.sh#L53).

**Comment by stephenmsachs** [comment]
It seem this `libc` warning appeared after https://github.com/spack/spack/pull/43190. Before that the pipeline was able to build with `%oneapi`.

**Comment by haampie** [comment]
that pr just exposes the issue

**Comment by kwryankrattiger** [comment]
I think we ignore the system scope configs in CI now to avoid cross-contamination between CI runs, and you are dumping the modified configs to `/etc/spack`. Try sending them to the spack root or the environment root directly?

**Comment by stephenmsachs** [comment]
> I think we ignore the system scope configs in CI now to avoid cross-contamination between CI runs, and you are dumping the modified configs to `/etc/spack`. Try sending them to the spack root or the environment root directly?

Are you referring to https://github.com/spack/spack/pull/40727 ?
I am using `site` scope and it seems to be able to pick up all the comfig files I need.

**Comment by stephenmsachs** [comment]
> that pr just exposes the issue

I think this may not be be true. I opened https://github.com/spack/spack/issues/43895 to discuss that part.

**Comment by stephenmsachs** [comment]
https://github.com/spack/spack/pull/43898 needs to get merged before this one as we need to build with `oneapi` in the aws-pcluster-x86_64_v4 stack.

**Comment by stephenmsachs** [comment]
Rebase broke.

**Pull request closed without merging**
