### PR TITLE
Ncbi blast

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Comment by glennpj** [comment]
This replicates the `blast-plus` package.
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/blast-plus/package.py

**Review by alalazo — CHANGES_REQUESTED** [review]
See @glennpj comment

**Comment by darmac** [comment]
Got it.

**Comment by darmac** [comment]
> See @glennpj comment

@alalazo  @glennpj 
I found this code will cause building fail in blast-plus.
```
         config_args = [
            '--with-bin-release',
```
Maybe, at least, we should supply a variant to close this `args` (`--with-bin-release`)

**Comment by hartzell** [comment]
@darmac -- Can you open up a separate Issue describing the failure you're seeing?

**Comment by darmac** [comment]
@hartzell  FYI https://github.com/spack/spack/issues/16196

**Pull request closed without merging**
