### PR TITLE
podio, edm4hep: new versions

### PR DESCRIPTION
**Pull request by wdconinc**
New versions (interrelated updates):
- podio: https://github.com/AIDASoft/podio/compare/v00-14...v00-15
- edm4hep: https://github.com/key4hep/EDM4hep/compare/v00-05...v00-06

Maintainer tags: @vvolkl @drbenmorgan

### CODE REVIEW

**Comment by vvolkl** [comment]
The tests for edm4hep v0.6 now require podio v0.15, right?

**Comment by wdconinc** [comment]
> The tests for edm4hep v0.6 now require podio v0.15, right?

Yes, I'm just using the draft for visibility and I'll add podio@0.15 as dependency for edm4hep@0.6.

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256

**Comment by tldahlgren** [comment]
Will defer merge until maintainers have a chance to comment.

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
