### PR TITLE
must: add versions 1.8.0 and 1.9.0

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]
Can we also remove the release candidate version, now that we have v1.8.0?

**Comment by hainest** [comment]
> Can we also remove the release candidate version, now that we have v1.8.0?

Probably. I would leave that decision to the maintainers (@jgalarowicz @dmont). `must` has no dependents (as of 65ffd0dd63), so it shouldn't directly break any packages.

**Comment by alecbcs** [comment]
Going to go ahead and merge this PR. Will follow up with another to pull out the release candidates as discussed with @alalazo.

**Pull request merged**
