### PR TITLE
jdk: Remove Oracle JDK package

### LINKED ISSUE #21991: Installation issue: JDK
I believe this error is coming from the licensing side of JDK where to install a package you must first accept the license. 

### Steps to reproduce the issue
```
# spack install jdk@11.0.2_9
==> Installing jdk
==> No binary for jdk found: installing from source
==> Error: FetchError: All fetchers failed

/opt/ohpc/pub/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265


# spack install jdk@14_36
==> Installing jdk
==> No binary for jdk found: installing from source
==> Error: FetchError: All fetchers failed

/opt/ohpc/pub/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
```

I have also downloaded jdk-11.0.10_linux-x64_bin.tar.gz, jdk-14.0.2_linux-x64_bin.tar.gz, and jdk-15.0.2_linux-x64_bin.tar.gz. Then added this to the spack package installer, i.e spack edit jdk. However, when I try to have spack install them it just goes for the website download instead of grabbing the tar file thats already downloaded. 

### Information on your system
* **Spack:** 0.15.4-1446-08e30a2
* **Python:** 3.6.8
* **Platform:** linux-centos7-sandybridge

### Additional information
example of added tar to spack edit jdk 

```
version('15.0.2', sha256='54b29a3756671fcb4b6116931e03e86645632ec39361bc16ad1aaa67332c7c61',
            url='https://download.oracle.com/otn-pub/java/jdk/15.0.2%2B7/0d1cfde4252546c6931946de8db48ee2/jdk-15.0.2_linux-x64_bin.tar.gz')
```

### General information
@justintoo 

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

### LINKED ISSUE #26938: Installation issue: jdk can't download directly
### Steps to reproduce the issue

```console
$ spack install jdk
==> Installing jdk-14_36-a2wws5elorqs3dhhuy4uplhmkzfahcv6
==> No binary for jdk-14_36-a2wws5elorqs3dhhuy4uplhmkzfahcv6 found: installing from source
/rnsdhpc/code/spack/lib/spack/spack/target.py:137: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@13.0.0 for further details]
  warnings.warn(msg.format(compiler))
==> Fetching https://download.oracle.com/otn-pub/java/jdk/14+36/076bab302c7b4508975440c56f6cc26a/jdk-14_linux-x64_bin.tar.gz
==> Warning: The contents of /var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/s3j/spack-stage/spack-stage-jdk-14_36-a2wws5elorqs3dhhuy4uplhmkzfahcv6/jdk-14_linux-x64_bin.tar.gz look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: ChecksumError: sha256 checksum failed for /var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/s3j/spack-stage/spack-stage-jdk-14_36-a2wws5elorqs3dhhuy4uplhmkzfahcv6/jdk-14_linux-x64_bin.tar.gz
    Expected 4639bbaecc9cc606f1a4b99fda1efcaefcbf57a7025b3828b095093a6c866afd but got 80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd

/rnsdhpc/code/spack/lib/spack/spack/package.py:1392, in do_fetch:
       1389        self.stage.fetch(mirror_only, err_msg=err_msg)
       1390        self._fetch_time = time.time() - start_time
       1391
  >>   1392        if checksum and self.version in self.versions:
       1393            self.stage.check()
       1394
       1395        self.stage.cache_local()
```

The gzip file is HTML that reads:
```
Sorry!
 
In order to download products from Oracle Technology Network you must agree to the OTN license terms.
  
Be sure that...
- Your browser has "cookies" and JavaScript enabled.
- You clicked on "Accept License" for the product you wish to download.
- You attempt the download within 30 minutes of accepting the license.
```

### Information on your system

* **Spack:** 0.16.3-4967-3720d06e26
* **Python:** 3.8.8
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### Additional information

not applicable

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### LINKED ISSUE #27666: checksum error jdk
### Steps to reproduce

```console
spack install bowtie
```

### Error message

```console
==> Error: ChecksumError: sha256 checksum failed for /tmp/runner/spack-stage/spack-stage-jdk-14_36-j2k4e757xfunfadrcvs7z7hgsrcxygbp/jdk-14_linux-x64_bin.tar.gz
    Expected 4639bbaecc9cc606f1a4b99fda1efcaefcbf57a7025b3828b095093a6c866afd but got 80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd

/opt/spack/lib/spack/spack/package.py:1390, in do_fetch:
       1387        self.stage.fetch(mirror_only, err_msg=err_msg)
       1388        self._fetch_time = time.time() - start_time
       1389
  >>   1390        if checksum and self.version in self.versions:
       1391            self.stage.check()
       1392
       1393        self.stage.cache_local()
```

### Information on your system

Github workflow failure

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by Pandapip1**
Supercedes https://github.com/spack/spack/pull/43220
Closes https://github.com/spack/spack/issues/21991 - should be solved by #43264 now
Closes https://github.com/spack/spack/issues/26938 - should be solved by #43264 now
Closes https://github.com/spack/spack/issues/27666 - should be solved by #43264 now

The Oracle JDK is now proprietary and requires the acceptance of an external EULA to install. This causes a bunch of programs that depend on `java` (which tries to default to installing `jdk`) to fail to install or the `jdk` package directly.

This removes the bad `jdk` package.

### CODE REVIEW

**Comment by Pandapip1** [comment]
CC @haampie

**Comment by haampie** [comment]
Actually it looks like something has regressed in Spack itself, the download works with the cookie header set, we're apparently not passing it.

**Comment by haampie** [comment]
Sorry, but download seem to work fine and in the lines of code you've touched there's stuff to accept the terms anyways.

The issue is just that old versions are no longer available for download.

Can you remove those, and instead add v17 and v21? These downloads work fine:

```
https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
```

In fact you can also remove the cookie / term agreement stuff, you can download fine from above URL w/o any headers set?

**Comment by haampie** [comment]
I've submitted #43264, let's leave this PR to fixing a few other issues you noticed like `depends_on("java")` / homepage / etc.

**Comment by Pandapip1** [comment]
Is there any good reason to use the Oracle JDK over OpenJDK? Keeping this around when there is a perfectly good open-source alternative just seems like it would add maintenance burden.

**Comment by bernhardkaindl** [comment]
Haampie wrote:
> I've submitted https://github.com/spack/spack/pull/43264, let's leave this PR to fixing a few other issues you noticed like depends_on("java") / homepage / etc.

Converting to draft until CI passes and haapmie approved it, can be changed back by clicking the button "Ready for review"

**Review by bernhardkaindl — COMMENTED** [review]
Haampie wrote:
> I've submitted https://github.com/spack/spack/pull/43264, let's leave this PR to fixing a few other issues you noticed like depends_on("java") / homepage / etc.

Converting to draft until CI passes and haapmie approved it, can be changed back by clicking the button "Ready for review"

**Comment by bernhardkaindl** [comment]
@spackbot run pipeline

**Pull request closed without merging**
