### PR TITLE
petsc, petsc4py: add version 3.15.2

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Just waiting for @dalcinl to review

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Being just two new versions added I'll merge this

**Comment by dalcinl** [comment]
Folks, I was on a much needed weekend break and I missed all these notifications. I have zero knowledge of spack's rules and procedures. @balay knows this business much much better than I, so anything he submits here has my implicit full support. You should not depend on me or wait for me with anything not strictly related to technical issues with the software itself. Perhaps you should consider removing me from the maintainer list to avoid future confusion.

**Comment by tgamblin** [comment]
@dalcinl: we've had the `maintainers` field in Spack packages for a while, but we've had a lot of maintainers tell us that they'd like to be notified when there are changes to packages they're maintaining.  We've added a bot to notify them of these changes -- there's no obligation to actually do anything (as we can't obligate you to do things :) ).

The bot pinged you because you're listed as a maintainer in `petsc`'s `package.py`:

```
    maintainers = ['dalcinl', 'balay']
```

It will also invite you (once) to the Spack organization.  If you accept the invite the bot will add you as a (again, optional) reviewer to these PRs in the future. Otherwise it'll just keep pinging you.

If you don't want to be notified of PETSc PRs, you or @balay can submit a PR to remove your name from the package.

**Comment by balay** [comment]
Ok - here is the PR https://github.com/spack/spack/pull/24991

**Pull request merged**
