### PR TITLE
Require +plugins when building binutils with +gold

### PR DESCRIPTION
**Pull request by haampie**
Ping @nsccap

### CODE REVIEW

**Comment by haampie** [comment]
ping @trws @naromero77, llvm needs gold with plugin support, @nsccap argues the gold linker is unusable without +plugins anways, so i fixed it in binutils with a conflict. you can still build ld.gold without plugins though, so maybe the proper solution is to make llvm depend on `binutils +gold +plugins` explicitly and leave the `binutils` package unchanged?

**Comment by trws** [comment]
That seems reasonable.  It's less of an issue than it used to be since lld has grown as much as it has, but if someone wants gold for LLVM they need plugin support.  They're also the main reason I've used gold anyway, since not only llvm but gcc needs gold plugins for certain things like LTO.

**Comment by dev-zero** [comment]
As I wrote on Slack: technically `ld.gold` does not need plugins support by itself (LTO-support on the other hand does), only when invoked by LLVM.

**Comment by haampie** [comment]
Yeah, I'm thinking about closing this in favor of #22988 and #22989

**Pull request closed without merging**
