### PR TITLE
gobject-introspection 1.7.2 also requires libffi@:3.3

### PR DESCRIPTION
**Pull request by lee218llnl**
As reported in https://github.com/LLNL/STAT/issues/44, STAT was seg faulting when built against libffi@3.4.2 and gobject-introspection@1.72.0. This is a continuation of #30595. The fix for gobject introspection to use the new libffi 3.4 interface did not make it in to the gobject introspection 1.72 release.

### CODE REVIEW

**Comment by lee218llnl** [comment]
can someone please review this PR?

**Comment by michaelkuhn** [comment]
I checked the upstream issue again and the fixes seem to be in 1.72 (https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/301). However, it seems that this requires new API to be used?

**Comment by bernhardkaindl** [comment]
@michaelkuhn What shall happen with this PR?

**Comment by alalazo** [comment]
@lee218llnl Can you rebase this PR and ping me or @michaelkuhn ?

**Comment by lee218llnl** [comment]
uh oh, looks like my Git-Fu is not very good... Should I close this one and create a new PR?

**Comment by lee218llnl** [comment]
closing in favor of #35606

**Pull request closed without merging**
