### PR TITLE
Added version2.2.1 for butterflypack which fixes a compiling issue with gcc<5

### PR DESCRIPTION
**Pull request by liuyangzhuan**

### CODE REVIEW

**Review by eugeneswalker — APPROVED** [review]
Checksum verified

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
@liuyangzhuan, fyi:
```
SRC_SINGLE/sMISC_utilities.f90:1021:10:

       if (myisnan(fnorm(mat, M, N))) then
          1
Error: Type mismatch in argument 'a' at (1); passed REAL(8) to REAL(4)
```

**Comment by alalazo** [comment]
@liuyangzhuan Can you please resubmit the PR and fix the build? If you do please pester me, I'd like to give the next PR of yours a fast track. Thanks!

**Comment by liuyangzhuan** [comment]
Sorry about that, I tagged a wrong commit by mistake. Can you take a look at this
https://github.com/spack/spack/pull/29343

**Pull request merged**
