### PR TITLE
Add new versions of Aluminum

### PR DESCRIPTION
**Pull request by bvanessen**
Deprecate old versions of Aluminum andLBANN packages.

### CODE REVIEW

**Comment by bvanessen** [comment]
@spackbot help

**Comment by bvanessen** [comment]
@spackbot fix style

**Review by tldahlgren — DISMISSED** [review]
Confirmed all new (and reconfirmed modified) sha256, rest LGTM

**Comment by bvanessen** [comment]
@tldahlgren Can you please re-review.  Just realized that we had a bad CMake that caused the CI failure, and it is now fixed.

**Comment by bvanessen** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Pull request merged**
