### PR TITLE
diffutils: add v3.9

### PR DESCRIPTION
**Pull request by alecbcs**
Add diffutils v3.9.

**Changelog:**
https://lists.gnu.org/archive/html/info-gnu/2023-01/msg00006.html

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by alecbcs** [comment]
@spackbot run pipeline

**Comment by alecbcs** [comment]
@haampie looks like we're getting an invalid checksum error on this pipeline pretty consistently. Should I rebase after your merge?

**Review by alalazo — DISMISSED** [review]

**Comment by alecbcs** [comment]
@spackbot run pipeline 😭

**Review by alalazo — APPROVED** [review]

**Pull request merged**
