### PR TITLE
sirius: bump, fix building with CUDA, fix consistency with cray-libsci

### PR DESCRIPTION
**Pull request by dev-zero**
- sirius: add version 7.3.1, ensure consistency with cray-libsci, fix building with CUDA in v7.3.0

### CODE REVIEW

**Review by simonpintarelli — DISMISSED** [review]
Thanks! Lgtm.

**Comment by haampie** [comment]
~The patch should just be part of SIRIUS itself, we can just do a quick 7.3.2 release and then drop the patch.~

Edit: that was already done... checked the wrong branch :see_no_evil: 

- Still I think the patch can be dropped for 7.3.0 since it was fixed in 7.3.1.

- Can you also add a `depends_on('cmake@3.18:', type='build', when='@7.3.1:')`?

**Comment by dev-zero** [comment]
>     * Still I think the patch can be dropped for 7.3.0 since it was fixed in 7.3.1.

As it is now, building 7.3.0 with some versions of CUDA is broken, this patch unbreaks it. Other options:

* drop 7.3.0 from Spack (has the drawback of not being able to build CP2K v9.1 as it was shipped ... with SIRIUS 7.3.0)
* restrict the CUDA version (if someone figures out which version of CUDA has the change)

>     * Can you also add a `depends_on('cmake@3.18:', type='build', when='@7.3.1:')`?

done

**Comment by haampie** [comment]
Hm, I would just leave 7.3.0 as is, since 7.3.1 fixes multiple bugs, so it's a bit arbitrary to pick one bug fix and apply it to a previous patch release.

**Comment by dev-zero** [comment]
> Hm, I would just leave 7.3.0 as is, since 7.3.1 fixes multiple bugs, so it's a bit arbitrary to pick one bug fix and apply it to a previous patch release.

Well, if you want to reproduce what CP2K v9.1 delivered, it is not so arbitrary ;-)

**Comment by yizeyi18** [comment]
Since sirius v7.3.1 (and versions much later) and cmake-drive building had been added elsewhere, should this PR be closed directly?

**Comment by simonpintarelli** [comment]
Thanks @yizeyi18 for bringing this up. I'm closing this PR, for the unlikely case there is a need to add a patch to SIRIUS 7.3, it can be reopened on the basis of the current recipe.

**Pull request closed without merging**
