### PR TITLE
Adding new package: py-jpype

### PR DESCRIPTION
**Pull request by JavierCVilla**
JPype is an effort to allow python programs full access to java class libraries

### CODE REVIEW

**Comment by adamjstewart** [comment]
Trying to restart Travis...

**Comment by adamjstewart** [comment]
Here goes nothing!

**Comment by JavierCVilla** [comment]
@adamjstewart  Is there any to change or was it just a travis matter?

**Comment by adamjstewart** [comment]
Just Travis. Looks good to me!

**Pull request merged**
