### PR TITLE
LAMMPS: Package KIM requires CURL after version 20190329

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
Deferring merge to give @rbberger time to review.

**Review by rbberger — DISMISSED** [review]

**Comment by rbberger** [comment]
LGTM

**Comment by RemiLacroix-IDRIS** [comment]
@tldahlgren : Sorry I repushed a rebased version of my branch to trigger again the pipeline since some tests failed for unknown reasons but that means the PR lost the "auto-merge".

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by RemiLacroix-IDRIS** [comment]
@haampie : Seems like it broke again.

**Comment by zackgalbreath** [comment]
@spackbot run pipeline

**Comment by RemiLacroix-IDRIS** [comment]
@spackbot run pipeline

**Pull request merged**
