### PR TITLE
windows_establish_runtime_linkage: post install hook

### PR DESCRIPTION
**Pull request by haampie**
ping @johnwparent

### CODE REVIEW

**Comment by johnwparent** [comment]
Please provide a proper PR description. ~Also please make a package modification to a package in VTK's dependency graph so we can actually test this (I'm 99% sure this is fine but we should still test it).~ Tested it locally since I thought that would be easier and I was building anyway, confirmed this works.

I _think_ I know why you're doing this (these calls are redundant because of the post install hook) and if that's the reason, this is good, LGTM.

**Review by johnwparent — APPROVED** [review]

**Comment by haampie** [comment]
Maybe I misremember but I thought we discussed this a while ago. In any case, these little function calls shouldn't be sprinkled all around ;)

**Comment by johnwparent** [comment]
> Maybe I misremember but I thought we discussed this a while ago. In any case, these little function calls shouldn't be sprinkled all around ;)

I do have some incredibly vague recollection of this discussion but I couldn't find it in slack/GH so I figured I'd just confirm. 
This change makes sense, LGTM!

**Comment by haampie** [comment]
I also don't know where it was, maybe in the python venv pr.

**Pull request merged**
