### PR TITLE
fix ci reproduce reliance on directory name

### PR DESCRIPTION
**Pull request by trws**
It, and at least one of its tests, relied on git clone creating a directory named "spack" from cloning the local working copy.  That only happens if the directory it is stored in is named spack, this makes it deterministic.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Nice catch.

**Comment by trws** [comment]
@spackbot rerun pipeline

**Comment by haampie** [comment]
i think it's stuck.

**Comment by trws** [comment]
@spackbot rerun pipeline

Yeah, I had this on my other PR too, it seems to be non-deterministic.

**Comment by trws** [comment]
@spackbot rerun pipeline

**Comment by trws** [comment]
Closing and reopening to poke CI.

**Comment by trws** [comment]
@spackbot re-run pipeline

**Comment by haampie** [comment]
pretty sure it's stuck again

**Comment by trws** [comment]
And now we are just waiting for a couple of massive packages to build in gitlab for some reason, and the windows runner to pick it up...

**Comment by haampie** [comment]
i thought by updating this branch it would reduce the number of packages... instead it's 500+ :exploding_head:

**Comment by trws** [comment]
Wow... I have no idea what's going on there.

**Comment by trws** [comment]
@spackbot re-run pipeline

**Comment by haampie** [comment]
what a fight

**Pull request merged**
