### PR TITLE
[toml11] Adds new versions

### PR DESCRIPTION
**Pull request by mdorier**
This PR adds 3 new versions to toml11.

### CODE REVIEW

**Comment by ashermancinelli** [comment]
The checksums look right, but why do we not need to define the c++ standard version via cmake anymore?
```shell
; echo 'f3dc3095f22e38745a5d448ac629f69b7ee76d2b3e6d653e4ce021deb7f7266e v4.0.0.tar.gz' | sha256sum --check
v4.0.0.tar.gz: OK
; echo '96965cb00ca7757c611c169cd5a6fb15736eab1cd1c1a88aaa62ad9851d926aa v4.0.1.tar.gz' | sha256sum --check
v4.0.1.tar.gz: OK
; echo 'd1bec1970d562d328065f2667b23f9745a271bf3900ca78e92b71a324b126070 v4.0.2.tar.gz' | sha256sum --check
v4.0.2.tar.gz: OK
```

**Comment by mdorier** [comment]
> why do we not need to define the c++ standard version via cmake anymore?

I didn't change the way this package handle the C++ standard, apart from changing `@when("@3.8.0:3.8.1")` into `@when("@3.8.0:")` to account for the new versions. Is that not correct?

**Comment by ashermancinelli** [comment]
Ah I misread that.

**Review by ashermancinelli — APPROVED** [review]
Thank you!

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
Didn't check pipelines. There are a lot of failures in pipelines: https://gitlab.spack.io/spack/spack/-/jobs/11823713 It seems that package requires a pinned version of `toml11`?

**Comment by mdorier** [comment]
No idea what openpmd-api is, but I went ahead and pinned the version to what toml11 provided prior to the PR. @ax3l or @franzpoeschel feel free to update if needed.

**Comment by franzpoeschel** [comment]
Thanks for notifying, I'll have a look. We don't pin toml11, at least not on purpose, so something else went wrong here.

**Comment by mdorier** [comment]
From the error message, I think openpmd-api's cmake file requests toml11 a version of toml11 that is ABI-compatible with 3.7.1, and toml11's cmake file probably indicates that 4.x versions are not compatible with older 3.x versions. 

```
 >> 19    CMake Error at CMakeLists.txt:284 (find_package):
     20      Could not find a configuration file for package "toml11" that is c
           ompatible
     21      with requested version "3.7.1".
     22    
     23      The following configuration files were considered but not accepted
           :
     24    
     25        /home/software/spack/__spack_path_placeholder__/__spack_path_pla
           ceholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s
           pack_path_placeholder__/__spack_path_placeholder__/__spack_path_plac
           eholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubunt
           u22.04-x86_64_v3/gcc-11.4.0/toml11-4.0.2-el6docezo7jh32qkppomi6geqzb
           mzb26/lib/cmake/toml11/toml11Config.cmake, version: 4.0.2
```

**Comment by franzpoeschel** [comment]
The intent here in our CMake script was to specify a minimum version. I just tested this locally and can reproduce the same error.
The intended behavior can *theoretically* be restored by:
```cmake
    if(${toml11_VERSION} VERSION_LESS 3.7.1)
        message(FATAL_ERROR "toml11: Found version '${toml11_VERSION}', but requires version '3.7.1' at least.")
    else()
        message(STATUS "toml11: Found version '${toml11_VERSION}'")
    endif()
```
But as you pointed out, toml11 4.* is not compatible with toml11 3.* and indeed our code does not compile against toml11 4.0.3. 
So for the moment, this CI run failure is justified as we will need to solve these compatibility issues first. Until then, we'll need to pin the version.

I can do that tomorrow.

**Comment by franzpoeschel** [comment]
I've added a fix for this on https://github.com/spack/spack/commit/b23594edeb84c49b7edae1128a7ce18409c61426.
For the current release 0.15, this lets Spack pick the internally shipped version of toml11.
For the upcoming release 0.16, https://github.com/openPMD/openPMD-api/pull/1645 will fix this compatibility issue, so the toml11 version shipped by Spack can be used again.

I'll not open a PR, I think it's easier if you just cherry-pick the commit.

**Comment by mdorier** [comment]
I propagated the change to my branch/PR (easier to copy/past than to cherry-pick, I wouldn't know how to do the latter across forks).

**Comment by mdorier** [comment]
The new changes make CI complain, for instance:

```
1. openpmd-api: dependency on toml11@4.0.3: cannot be satisfied by known versions of toml11
    happening in /Users/runner/work/spack/spack/var/spack/repos/builtin/packages/openpmd-api/package.py
    known versions of toml11 are 4.0.2, 4.0.1, 4.0.0, 3.8.1, 3.8.0, 3.7.1, 3.7.0, 3.6.1, 3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.0
```

Because toml11 doesn't have a 4.0.3 version (even in this PR). My previous commit, which simply pinned the version of toml11, was working fine. @franzpoeschel any reason for using internal toml11 rather than just pinning the version number in the spack package like I did before?

**Comment by franzpoeschel** [comment]
> @franzpoeschel any reason for using internal toml11 rather than just pinning the version number in the spack package like I did before?

If that's easier, then let's do that and revert the commit I provided.
The reason for using the internal version was that this reduces the chance for dependency conflicts from pinning. toml11 is header-only and we don't re-export it, so I attempted to keep it purely internal.

**Comment by mdorier** [comment]
Ok I reverted the previous commit.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
