### PR TITLE
 Cray XK7 support with multiple Target modules.

### PR DESCRIPTION
**Pull request by mpbelhorn**
This pull request:

1. Adds a platform for Cray XK7 which changes `Platform.detect` for Cray systems to use an environment variable as opposed to the existence of the path `/opt/cray/craype` which is not platform-unique.

1. Allows `Target`s to specify multiple environment modules so that Cray compiler wrapper options (linking style, target architecture, etc) can be modified when using the Cray compiler wrapper to target service nodes vs compute nodes.

### CODE REVIEW

**Comment by becker33** [comment]
Is there any way to detect whether you are on a Cray XK platform without resorting to an environment variable? We want Spack to work out of the box, and this PR requires an environment change to be able to use it on Cray XC

**Comment by mpbelhorn** [comment]
The only thing I know of that comes close is if the compiler wrapper is called
with the '-craype-verbose' flag, the output can slightly distinguish the
platform. For instance the string 'D__CRAYXT_COMPUTE' from:

```
$ cc -craype-verbose --version 
pgcc -tp=bulldozer -Bdynamic -D__CRAYXE -D__CRAY_INTERLAGOS
-D__CRAYXT_COMPUTE_LINUX_TARGET -pgf90libs --version
-I/opt/cray/mpt/7.2.5/gni/mpich2-pgi/15.3/include
-I/opt/cray/libsci/13.2.0/PGI/15.3/x86_64/include -I/opt/cray/rca/1.0.0-2.05
02.60530.1.63.gem/include -I/opt/cray/alps/5.2.4-2.0502.9774.31.12.gem/include
-I/opt/cray/xpmem/0.1-2.0502.64982.5.3.gem/include -I/opt/cray/gni-headers/4.0-
1.0502.10859.7.8.gem/include -I/opt/cray/pmi/5.0.9-
1.0000.10911.175.4.gem/include -I/opt/cray/ugni/6.0-
1.0502.10863.8.28.gem/include -I/opt/cray/udreg/2.3.2-
1.0502.10518.2.17.gem/include -I/opt/cray/wlm_detect/1.0-
1.0502.64649.2.2.gem/include -I/opt/cray/krca/1.0.0-
2.0502.63139.4.30.gem/include -I/opt/cray-hss-devel/7.2.0/include
-L/opt/cray/dmapp/default/lib64 -L/opt/cray/mpt/7.2.5/gni/mpich2-pgi/15.3/lib
-L/opt/cray/libsci/13.2.0/PGI/15.3/x86_64/lib -L/opt/cray/rca/1.0.0-
2.0502.60530.1.63.gem/lib64 -L/opt/cray/atp/1.8.3/libApp -Wl,--no-as-needed,-
lAtpSigHandler,-lAtpSigHCommData -Wl,--undefined=_ATP_Data_Globals -Wl,
--undefined=__atpHandlerInstall -lrca -Wl,--as-needed,-lmpich_pgi,--no-as-needed 
-Wl,--as-needed,-lsci_pgi_mpi_mp,--no-as-needed -Wl,--as-needed,-lsci_pgi_mp,
--no-as-needed                                           
```

but that's not very accurate. For instance, I called the above from an XK7, not
an XT. I've asked our Cray liason for some ideas and will see what can be done.
However, just looking for '/opt/cray/craype' is not sufficient to distinguish
Cray platforms with different architectures.

One option that came up (jokingly) was to just keep a mapping in the platform
file of all the know Crays and match against hostname...

Best,
Matt

-- 
Matt Belhorn
OLCF Support Consultant
Oak Ridge National Laboratory

**Comment by KineticTheory** [comment]
Here's another data point:  On Trinity (Cray XC40), spack's compiler detection appears to be broken. Spack does not detect that the machine is running a Cray PrgEnv and neither the Cray compile environment or wrappers are identified.  Similar to the above issue, `/opt/cray/craype` does not exist on this machine, but `/opt/cray/pe/craype` does. Additionally, the compile wrapper has the following information:

```
cc -craype-verbose --version

icc -xCORE-AVX2 -D__CRAYXC -D__CRAY_HASWELL -D__CRAYXT_COMPUTE_LINUX_TARGET --version \
-Wl,-rpath=/opt/intel/2016.3.067/compilers_and_libraries_2016/linux/../compiler/lib/intel64 \
-lintlc -I/opt/cray/pe/libsci/16.03.1/INTEL/15.0/x86_64/include \
-I/opt/cray/pe/mpt/7.3.3/gni/mpich-intel/15.0/include \
-I/opt/cray/rca/1.0.0-4.70/include -I/opt/cray/alps/6.0.0-22.11/include \
-I/opt/cray/xpmem/0.1-4.4/include -I/opt/cray/gni-headers/5.0-2.3/include \
-I/opt/cray/pe/pmi/5.0.10-1.0000.11050.0.0.ari/include -I/opt/cray/ugni/6.0-2.3/include \
-I/opt/cray/udreg/2.3.2-3.10/include -I/opt/cray/wlm_detect/1.0-4.4/include \
-I/opt/cray/krca/1.0.0-4.56/include -I/opt/cray-hss-devel/8.0.0/include \
-L/opt/cray/pe/libsci/16.03.1/INTEL/15.0/x86_64/lib -L/opt/cray/dmapp/default/lib64 \
-L/opt/cray/pe/mpt/7.3.3/gni/mpich-intel/15.0/lib -L/opt/cray/rca/1.0.0-4.70/lib64 \
-L/opt/cray/pe/atp/2.0.1/libApp -Wl,--no-as-needed,-lAtpSigHandler,-lAtpSigHCommData \
-Wl,--undefined=_ATP_Data_Globals -Wl,--undefined=__atpHandlerInstall -lrca \
-Wl,--as-needed,-lmpich_intel,--no-as-needed -Wl,--as-needed,-lsci_intel_mpi,--no-as-needed \
-Wl,--as-needed,-lsci_intel,--no-as-needed -Wl,--as-needed,-limf,--no-as-needed \
-Wl,--as-needed,-lm,--no-as-needed -Wl,--as-needed,-lifcore,--no-as-needed \
-Wl,--as-needed,-lifport,--no-as-needed -Wl,--as-needed,-lpthread,--no-as-needed 
```

**Comment by KineticTheory** [comment]
I'm working on a prototype Cray XC with KNL's this week, here are the defines from the compile wrapper:

```
CC -craype-verbose --version

icpc -xmic-avx512 -D__CRAYXC -D__CRAY_MIC_KNL -D__CRAYXT_COMPUTE_LINUX_TARGET ...

<-I, -L and -Wl options removed>

icpc (ICC) 16.0.3 20160415
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
```

**Comment by mpbelhorn** [comment]
This topic is superseded by PR #1376.

**Pull request closed without merging**
