### PR TITLE
petsc: add variant +sycl

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Only one CI build test failing, unclear why:
* [slepc@3.20.0 /ojpwfbp %gcc@11.4.0 arch=linux-ubuntu20.04-neoverse_v1 E4S ARM Neoverse V1](https://gitlab.spack.io/spack/spack/-/jobs/8726207)

```
...
=> Installing slepc-3.20.0-ojpwfbps3zinopucl3amdxfae5cafab3 [1/1]
==> Fetching https://slepc.upv.es/download/distrib/slepc-3.20.0.tar.gz
==> No patches needed for slepc
==> slepc: Executing phase: 'install'
==> [2023-10-16-22:01:09.403636] Find (not recursive): /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib ['libparpack.so', 'libarpack.so']
==> [2023-10-16-22:01:09.404001] Find complete: /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib ['libparpack.so', 'libarpack.so']
==> [2023-10-16-22:01:09.404840] '/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/python-3.11.6-doqfukswac7w7amh75ti6w56mr4ngjst/bin/python3.11' 'configure' '--prefix=/home/software/spack/[padded-to-256-chars]/morepadding/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/slepc-3.20.0-ojpwfbps3zinopucl3amdxfae5cafab3' '--with-arpack-include=/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/include' '--with-arpack-lib=/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libparpack.so /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libarpack.so'
Checking environment... done
Checking PETSc installation... 
ERROR: Unable to link with PETSc
ERROR: See "installed-arch-linux2-c-opt/lib/slepc/conf/configure.log" file for details
==> Error: ProcessError: Command exited with status 1:
    '/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/python-3.11.6-doqfukswac7w7amh75ti6w56mr4ngjst/bin/python3.11' 'configure' '--prefix=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/morepadding/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/slepc-3.20.0-ojpwfbps3zinopucl3amdxfae5cafab3' '--with-arpack-include=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/include' '--with-arpack-lib=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libparpack.so /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libarpack.so'
See build log for details:
  /tmp/root/spack-stage/spack-stage-slepc-3.20.0-ojpwfbps3zinopucl3amdxfae5cafab3/spack-build-out.txt
Traceback (most recent call last):
  File "/builds/spack/spack/lib/spack/spack/build_environment.py", line 1017, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 2496, in build_process
    return installer.run()
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 2361, in run
    self._real_install()
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 2456, in _real_install
    phase_fn.execute()
  File "/builds/spack/spack/lib/spack/spack/builder.py", line 433, in execute
    self.phase_fn(pkg, pkg.spec, pkg.prefix)
  File "/builds/spack/spack/lib/spack/spack/builder.py", line 309, in _adapter
    return phase_fn(spec, prefix)
  File "/builds/spack/spack/var/spack/repos/builtin/packages/slepc/package.py", line 158, in install
  File "/builds/spack/spack/lib/spack/spack/util/executable.py", line 238, in __call__
    raise ProcessError("Command exited with status %d:" % proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    '/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/python-3.11.6-doqfukswac7w7amh75ti6w56mr4ngjst/bin/python3.11' 'configure' '--prefix=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/morepadding/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/slepc-3.20.0-ojpwfbps3zinopucl3amdxfae5cafab3' '--with-arpack-include=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/include' '--with-arpack-lib=/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libparpack.so /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/arpack-ng-3.9.0-zzqdmczqjkaygygv4wahi4brmukgcseq/lib/libarpack.so'
```

**Comment by balay** [comment]
That stage worked before for this PR at https://gitlab.spack.io/spack/spack/-/jobs/8723688

but now this failure came up on a rerun. 

Is it possible to disable usage of petsc from "binary cache" for slepc CI builds? [i.e build petsc - before building  slepc]

**Comment by eugeneswalker** [comment]
> Is it possible to disable usage of petsc from "binary cache" for slepc CI builds? [i.e build petsc - before building slepc]

I don't think this is possible the way things are now. @scottwittenburg Do you know?

**Comment by scottwittenburg** [comment]
> I don't think this is possible the way things are now. @scottwittenburg Do you know?

No, that's not possible now, and it's hard to imagine adding support for something like that.  Part of the design of the gitlab ci builds is that each package minimally tests that its dependencies can be installed from binary and relocated into a different path (different than the path it was originally installed to).  

But I'm curious why would it help to build the petsc dependency from source when building slepc?  

I notice that the earlier failure linked by @balay (where at least "checking petsc installation" worked correctly, but the build failed later on) happened on Cray, but the more recent failure (where "checking petsc installation" seemed to fail with "error: unable to link with petsc") happened on arm neoverse v1.  Just pointing that out in case it wasn't already obvious.

**Comment by balay** [comment]
> But I'm curious why would it help to build the petsc dependency from source when building slepc?

slepc uses some of the config from petsc - so when petsc is relocated - some of the paths won't match.

Building both pkgs on the target machine will keep these paths correct for both the builds.

> ERROR: See "installed-arch-linux2-c-opt/lib/slepc/conf/configure.log" file for details

Also if we can access this log file - it might confirm - if this is indeed the issue..

**Comment by balay** [comment]
Note: this issue is coming up now - and never in the past - so some recent change in the CI process must be the trigger.

**Comment by scottwittenburg** [comment]
> Also if we can access this log file - it might confirm - if this is indeed the issue..

I think that file can be found in the logs directory of the artifacts for the job, [here](https://gitlab.spack.io/spack/spack/-/jobs/8726207/artifacts/browse/jobs_scratch_dir/logs/).  But let me know if that's not the right one.

**Comment by balay** [comment]
>  Part of the design of the gitlab ci builds is that each package minimally tests that its dependencies can be installed from binary and relocated into a different path (different than the path it was originally installed to).

And I guess this is a new requirement. 

PETSc is not really designed to be relocatable.. So spack won't support such pacakges anymre?

cc: @jedbrown @BarrySmith @joseeroman

**Comment by scottwittenburg** [comment]
> And I guess this is a new requirement.

No, this has been the case from the beginning.

**Comment by balay** [comment]
> I think that file can be found in the logs directory of the artifacts for the job, [here](https://gitlab.spack.io/spack/spack/-/jobs/8726207/artifacts/browse/jobs_scratch_dir/logs/). But let me know if that's not the right one.

Thanks! I was assuming the wrong issue.


```
make: /opt/bootstrap/view/bin/make

Running command:
cd /tmp/slepc-ouyg5gp9;/opt/bootstrap/view/bin/make checklink LINKFLAGS=""
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Output:
/bin/sh: 1: /opt/bootstrap/view/bin/make: not found

```

Looks like its primarily one config info - 'make'

I tried changing that at 'make' step. But looks like 'configure' step also needs this change. I'll have to see if this can be done.

**Comment by eugeneswalker** [comment]
> Thanks! I was assuming the wrong issue.
> 
> ```
> make: /opt/bootstrap/view/bin/make
> 
> Running command:
> cd /tmp/slepc-ouyg5gp9;/opt/bootstrap/view/bin/make checklink LINKFLAGS=""
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> Output:
> /bin/sh: 1: /opt/bootstrap/view/bin/make: not found
> ```

I know why this failed! @scottwittenburg Look at the ARM runner that was used-- it is a `pcluster` runner and thus is mounting in `/opt` which overwrites the `/opt/bootstrap/view/bin/make` PATH embedded in `petsc`. Since this path to `make` was by `petsc`  having been run on a non-pcluster runner, and then `slepc` build is attempted on the pcluster runner where `/opt/bootstrap/view/bin/make` is overwritten, that's how we get here.

@kwryankrattiger How can we make sure E4S ARM CI jobs never end up on `*pcluster*arm*` runners?  Could we tag these pcluster runners with a new tag that the `pcluster` CI stack could rely on to schedule its jobs, such that then other ARM jobs won't match? New tag = `pcluster-arm`? 

* [slepc@3.20.0 /ojpwfbp %gcc@11.4.0 arch=linux-ubuntu20.04-neoverse_v1 E4S ARM Neoverse V1](https://gitlab.spack.io/spack/spack/-/jobs/8726207)
Screenshot 2023-10-18 at 11 00 45 AM

**Comment by eugeneswalker** [comment]
And FYI I re-triggered the failed `slepc` build and this time it was scheduled onto a non-pcluster ARM runner. It should pass this time, see:
* https://gitlab.spack.io/spack/spack/-/jobs/8747043

**Comment by balay** [comment]
If spack is handling the relocation of PATHs in config files - then it might handle this for `make` if its listed explicitly as a dependency.

Pushed this change to give it a try..

**Comment by balay** [comment]
>  see:

>    https://gitlab.spack.io/spack/spack/-/jobs/8747043

```
[+] /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/libmd-1.0.4-ercvfsbp4uzhhs7nmxyy5pzlvlkdwkiw
==> Error: No binary for openblas-0.3.24-faia46aechom57vw4fugunjvbnblvo3d found when cache-only specified
==> Error: Failed to install openblas due to SystemExit: 1
==> Error: openblas-0.3.24-faia46aechom57vw4fugunjvbnblvo3d: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```
Perhaps some other issue with CI?

**Comment by eugeneswalker** [comment]
> > see:
> 
> > https://gitlab.spack.io/spack/spack/-/jobs/8747043
> 
> ```
> [+] /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-neoverse_v1/gcc-11.4.0/libmd-1.0.4-ercvfsbp4uzhhs7nmxyy5pzlvlkdwkiw
> ==> Error: No binary for openblas-0.3.24-faia46aechom57vw4fugunjvbnblvo3d found when cache-only specified
> ==> Error: Failed to install openblas due to SystemExit: 1
> ==> Error: openblas-0.3.24-faia46aechom57vw4fugunjvbnblvo3d: Package was not installed
> ==> Error: Installation request failed.  Refer to reported errors for failing package(s).
> ```
> 
> Perhaps some other issue with CI?

Also `libfabric` was not found in binary cache -- @scottwittenburg binaries expired perhaps? Do you know why these dependencies weren't found?

**Comment by jedbrown** [comment]
What is the relocation requirement? PETSc installs support `DESTDIR`, but not raw copying files to an arbitrary directory.

**Comment by scottwittenburg** [comment]
> Also `libfabric` was not found in binary cache -- @scottwittenburg binaries expired perhaps? Do you know why these dependencies weren't found?

No, I'm looking into that now.  

The generation log says e.g. openblas was found in the shared pr mirror, and while it is mentioned in the index there, it's listed as `in_buildcache: False`, so that should have essentially turned into "not found".

**Comment by scottwittenburg** [comment]
> The generation log says e.g. openblas was found in the shared pr mirror, and while it is mentioned in the index there, it's listed as in_buildcache: False, so that should have essentially turned into "not found".

I regenerated the index of the shared pr mirror for the `e4s-neoverse_v1` stack, and now it generated jobs for `openblas`, `libfabric`, etc.  I'm still looking into what's going on there.

**Comment by scottwittenburg** [comment]
Now the pipelines for this PR look like they might pass, except some jobs on `uo-omnia` look like they might be stuck.  For example, while the database shows most recent `slepc` builds take around 10 minutes, this one has been running for almost an hour: 

https://gitlab.spack.io/spack/spack/-/jobs/8747421

I wonder if this `dealii` job is stuck too:

https://gitlab.spack.io/spack/spack/-/jobs/8747423

@eugeneswalker Can you see anything wrong with that runner?

**Comment by eugeneswalker** [comment]
All CI is green here finally! Glad that was all figured out.

**Comment by eugeneswalker** [comment]
Should we proceed with merge? Any final changes or need for others to review? If no, I will merge it.

**Comment by balay** [comment]
Its ready for merge! Thanks!

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
