### PR TITLE
libhio: package update for new sha256 checksum for v1.4.1.5

### PR DESCRIPTION
**Pull request by jennfshr**
The checksum that is present for libhio@1.4.1.5 supplied a broken autotools configuration.  The release has since been updated to address the issue, but the Spack package is still checking against the old checksum, and therefore fails to fetch.  

This PR supplies the new correct checksum for the corrected package source.

### CODE REVIEW

**Review by alecbcs — APPROVED** [review]
Confirmed SHA. Looks good to me. Thanks for the fix @jennfshr!

**Comment by alecbcs** [comment]
On second glance it looks like all of the previous checksums are invalid. @jennfshr could you do me a huge favor and could we update all of the versions with the fixed checksums in this PR?

```
> spack checksum libhio 1.4.1.0 1.4.1.1 1.4.1.2 1.4.1.3 1.4.1.4 1.4.1.5 1.4.1.6

==> Found 7 versions of libhio:

  1.4.1.6  https://github.com/hpc/libhio/releases/download/hio.1.4.1.6/libhio-1.4.1.6.tar.bz2
  1.4.1.5  https://github.com/hpc/libhio/releases/download/hio.1.4.1.5/libhio-1.4.1.5.tar.bz2
  1.4.1.4  https://github.com/hpc/libhio/releases/download/hio.1.4.1.4/libhio-1.4.1.4.tar.bz2
  1.4.1.3  https://github.com/hpc/libhio/releases/download/hio.1.4.1.3/libhio-1.4.1.3.tar.bz2
  1.4.1.2  https://github.com/hpc/libhio/releases/download/hio.1.4.1.2/libhio-1.4.1.2.tar.bz2
  1.4.1.1  https://github.com/hpc/libhio/releases/download/hio.1.4.1.1/libhio-1.4.1.1.tar.bz2
  1.4.1.0  https://github.com/hpc/libhio/releases/download/hio.1.4.1.0/libhio-1.4.1.0.tar.bz2

==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.6/libhio-1.4.1.6.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.5/libhio-1.4.1.5.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.4/libhio-1.4.1.4.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.3/libhio-1.4.1.3.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.2/libhio-1.4.1.2.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.1/libhio-1.4.1.1.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.0/libhio-1.4.1.0.tar.bz2

    version("1.4.1.6", sha256="863e7274f9e32d97bd5d9e6745ad9449735bdc8bd5623f152a32be45e6f3a212")
    version("1.4.1.5", sha256="76f5a0eb306e9596cdef558586ed2ba47bf50a9cc7782beb1a8b37115c00b1ee")
    version("1.4.1.4", sha256="b06d6041bd846ec358f933b3665a81296a663490c05124e5ff96aab355ef5a00")
    version("1.4.1.3", sha256="b3539039f55e2c2b8ec9584d668f693e50876b48dd1440e33bb64088141f7e9e")
    version("1.4.1.2", sha256="87a0f9b72b7aa69485c40d9bd36f02af653b70e8eed3eb0b50eaeb02ff0a9049")
    version("1.4.1.1", sha256="0b42541701ee92e6715c1c222588473e8cafea98527733de1fd6b8fb8c8a11d7")
    version("1.4.1.0", sha256="d2758a5a09ec0a420de5a9c1d3849ea07a3c431a10ebd5277f950639ff872768")
```

**Comment by alecbcs** [comment]
ping @jennfshr

**Comment by jennfshr** [comment]
I’m not seeing the disparity that you are – but will spend a little more time investigating in the morning.


From: Alec Scott ***@***.***>
Reply-To: spack/spack ***@***.***>
Date: Friday, July 7, 2023 at 5:19 PM
To: spack/spack ***@***.***>
Cc: jgreen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [spack/spack] libhio: package update for new sha256 checksum for v1.4.1.5 (PR #38696)


ping @jennfshr<https://urldefense.com/v3/__https:/github.com/jennfshr__;!!Bt8fGhp8LhKGRg!H8AjZu1luL1c4u013AXV975DbrcfmpY4H9u2MW_pJ5LS8SeKZo1SLHj0O1uS6irU0rptI8skCsq8jrX_FWbn6bAk$>

**Comment by alecbcs** [comment]
Thanks @jennfshr specifically v1.4.1.0, v1.4.1.1, v1.4.1.3, and v1.4.1.4 all appear to have different hashes now for me.

**Comment by alecbcs** [comment]
@jennfshr ping

**Comment by Paul-Ferrell** [comment]
All the hashes look correct to me except the 1.4.1.5, as per @jennfshr's PR. I downloaded and verified the hash on each of them.
Note the hashes are all for the `tar.bz2` release tarballs.

**Comment by Paul-Ferrell** [comment]
@alecbcs  ^^^

**Comment by alecbcs** [comment]
```
> spack checksum --verify -b libhio

==> Found 9 versions of libhio:

  1.4.1.6      https://github.com/hpc/libhio/releases/download/hio.1.4.1.6/libhio-1.4.1.6.tar.bz2
  1.4.1.5      https://github.com/hpc/libhio/releases/download/hio.1.4.1.5/libhio-1.4.1.5.tar.bz2
  1.4.1.4      https://github.com/hpc/libhio/releases/download/hio.1.4.1.4/libhio-1.4.1.4.tar.bz2
  1.4.1.3      https://github.com/hpc/libhio/releases/download/hio.1.4.1.3/libhio-1.4.1.3.tar.bz2
  1.4.1.2      https://github.com/hpc/libhio/releases/download/hio.1.4.1.2/libhio-1.4.1.2.tar.bz2
  1.4.1.1      https://github.com/hpc/libhio/releases/download/hio.1.4.1.1/libhio-1.4.1.1.tar.bz2
  1.4.1.0-rc3  https://github.com/hpc/libhio/releases/download/hio.1.4.1.0-rc3/libhio-1.4.1.0-rc3.tar.bz2
  1.4.1.0-rc2  https://github.com/hpc/libhio/releases/download/hio.1.4.1.0-rc2/libhio-1.4.1.0-rc2.tar.bz2
  1.4.1.0      https://github.com/hpc/libhio/releases/download/hio.1.4.1.0/libhio-1.4.1.0.tar.bz2

==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.6/libhio-1.4.1.6.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.5/libhio-1.4.1.5.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.4/libhio-1.4.1.4.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.3/libhio-1.4.1.3.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.2/libhio-1.4.1.2.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.1/libhio-1.4.1.1.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.0-rc3/libhio-1.4.1.0-rc3.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.0-rc2/libhio-1.4.1.0-rc2.tar.bz2
==> Fetching https://github.com/hpc/libhio/releases/download/hio.1.4.1.0/libhio-1.4.1.0.tar.bz2
==> Verified 6 of 9

  1.4.1.6      [=] Correct
  1.4.1.5      [x] 76f5a0eb306e9596cdef558586ed2ba47bf50a9cc7782beb1a8b37115c00b1ee
  1.4.1.4      [=] Correct
  1.4.1.3      [=] Correct
  1.4.1.2      [=] Correct
  1.4.1.1      [=] Correct
  1.4.1.0-rc3  [-] No previous checksum
  1.4.1.0-rc2  [-] No previous checksum
  1.4.1.0      [=] Correct


==> Error: Invalid checksums found.
```

Strange, @Paul-Ferrell I can confirm I'm now getting the original checksums for all of the previous versions minus v1.4.1.5. I wonder why I'd gotten previously gotten different checksums for the releases?

**Review by alecbcs — APPROVED** [review]
This fix looks good to me. Thanks for the PR @jennfshr!

**Pull request merged**
