### PR TITLE
hssp: Fix checksum for 3.0.10

### PR DESCRIPTION
**Pull request by t-nojiri**

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like the checksum changed for all the previous versions too. Can you contact the developers and find out why that is the case? Just want to make sure they didn't get hacked.

**Comment by t-nojiri** [comment]
I am doing confirmation.
https://github.com/cmbi/hssp/issues/125

**Comment by t-nojiri** [comment]
I got an answer from the person in charge.
The person in charge doesn't seem to know the value of checksum used in spack.

What should I look for next?

**Comment by adamjstewart** [comment]
I figured it out. The previous checksum came from https://github.com/cmbi/hssp/releases/download/3.0.10/xssp-3.0.10.tar.gz, not https://github.com/cmbi/hssp/archive/3.0.10.tar.gz. So I think it's safe to update all the checksums. Thanks for checking!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
