### PR TITLE
Travi CI groups jobs in stages

### PR DESCRIPTION
**Pull request by alalazo**
This PR builds on #5068 and tries the new 'Build stage' feature of Travis.

### CODE REVIEW

**Comment by alalazo** [comment]
I think this is ready to go if we want to use Travis stages. If we want to go instead with #5068 we need to check if the failure for `perl-dbi` is still there.

**Comment by tgamblin** [comment]
Merged!  

@alalazo @adamjstewart: Here's another proposal, maybe for a separate PR.

Some observations:

1. These particular build tests are only present to cover more of core.  They're not actually intended to check packages.
    - So, we should only run the build tests if something changed in core.
    - Flake8 and unit tests should always be re-run 

2. Currently we look for changes by comparing against `develop`
    - We should probably compare against the *last good Travis CI commit* on the PR branch
    - This would allow us to skip build tests when someone's finishing up a PR, e.g.:
        - doing some final iterations to make `flake8` happy (though this is mostly covered by the new test structure)
        - adding tests after core functionality is working.

I think you can get the last good commit on the PR branch with the Travis API... looks like you can grab the [branch info](https://docs.travis-ci.com/api/#branches) then look at `job_ids` and find the last [job info](https://docs.travis-ci.com/api/#jobs) with a successful state.

Thoughts?  Any holes in this plan?

**Comment by adamjstewart** [comment]
@tgamblin You're way behind, I proposed that a long time ago. Unit tests and build tests should only be run when something in core changes. Flake8 and doc tests should always be run. That will speed up Travis for the majority of PRs. We could also run tests for the particular package that is being modified, although I'm not sure which tests we can reliably run.

**Comment by tgamblin** [comment]
@adamjstewart unit tests should run if something in the tests changed, as well.  For the per-package tests, I have something else in the works for that...

**Pull request merged**
