### PR TITLE
Update aws-ofi-nccl to use the hwloc option

### PR DESCRIPTION
**Pull request by aurianer**

### CODE REVIEW

**Review by msimberg — APPROVED** [review]
From what I can tell from https://github.com/aws/aws-ofi-nccl `hwloc` is a hard dependency that was simply missing, is that right @aurianer?

**Comment by aurianer** [comment]
> From what I can tell from https://github.com/aws/aws-ofi-nccl `hwloc` is a hard dependency that was simply missing, is that right @aurianer?

Since this spack package only proposes master, yes it's a missing dependency. In case this question is more broad, the dependency was not needed in 1.6.0 but is needed in 1.7.x

**Review by bvanessen — APPROVED** [review]

**Comment by bvanessen** [comment]
> > From what I can tell from https://github.com/aws/aws-ofi-nccl `hwloc` is a hard dependency that was simply missing, is that right @aurianer?
> 
> Since this spack package only proposes master, yes it's a missing dependency. In case this question is more broad, the dependency was not needed in 1.6.0 but is needed in 1.7.x

I know that this only has a reference to master in it, but we should add some versions and then make the dependency specific on the version.

**Comment by msimberg** [comment]
> I know that this only has a reference to master in it, but we should add some versions and then make the dependency specific on the version.

I take it from your approval that you'd be happy to have this merged as-is, and the released versions (and constraints) added in a separate PR?

**Pull request merged**
