### PR TITLE
Boost: fix recipe for Intel compilers.

### PR DESCRIPTION
**Pull request by KineticTheory**
This is the same patch provided by PR #550, but rebased against the current develop branch. It also passes the flake8 checks.

Tested with intel/16.0.3 and gcc/4.8.5 on RHEL.

### CODE REVIEW

**Comment by tgamblin** [comment]
Thanks!

**Comment by woodard** [comment]
Still not working for me:

[ben@upgrade2:spack]$ git log | head
commit 848299ba38595a78f1a6f589ddc59c1a275e6acd
Merge: 062ff13 2ddaabe
Author: Todd Gamblin <tgamblin@llnl.gov>
Date:   Wed Aug 24 15:23:29 2016 -0700

    Merge pull request #1621 from KineticTheory/boost-intel
    
    Boost: fix recipe for Intel compilers.

commit 2ddaabed257e04c292b8e6e3954fff675b35907e
[ben@upgrade2:spack]$ spack clean boost %intel
[ben@upgrade2:spack]$ spack install boost %intel
==> Installing boost
==> bzip2 is already installed in /g/g0/ben/spack/opt/spack/linux-redhat7-x86_64/intel-16.0.3/bzip2-1.0.6-lms6b6dyngipmozcwc6thfqodto7gija
==> zlib is already installed in /g/g0/ben/spack/opt/spack/linux-redhat7-x86_64/intel-16.0.3/zlib-1.2.8-dsahmxr4g32txs5dbtk4km2mqmo4dqhw
==> Can not find version 1_61_0 in url_list
==> Trying to fetch from file:///g/g0/ben/spack/var/spack/cache/boost/boost-1.61.0.tar.bz2
######################################################################## 100.0%
==> Staging archive: /g/g0/ben/spack/var/spack/stage/boost-1.61.0-ge5ftdxa7p3jgw4pq4gnv5dt4lajwyxh/boost-1.61.0.tar.bz2
bzip2: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
/usr/bin/tar: Child returned status 127
/usr/bin/tar: Error is not recoverable: exiting now
==> Error: Command exited with status 2:
'/usr/bin/tar' '-xf' '/g/g0/ben/spack/var/spack/stage/boost-1.61.0-ge5ftdxa7p3jgw4pq4gnv5dt4lajwyxh/boost-1.61.0.tar.bz2'



/g/g0/ben/spack/lib/spack/spack/package.py:735, in do_stage:
     728      def do_stage(self, mirror_only=False):
     729          """Unpacks the fetched tarball, then changes into the expanded tarball
     730             directory."""
     731          if not self.spec.concrete:
     732              raise ValueError("Can only stage concrete packages.")
     733  
     734          self.do_fetch(mirror_only)
  >> 735          self.stage.expand_archive()
     736          self.stage.chdir_to_source()
==> Error: Installation process had nonzero exit code : 256

**Comment by woodard** [comment]
BTW

[ben@upgrade2:spack]$ spack compilers
==> Available compilers
-- gcc ----------------------------------------------------------
gcc@6.1.0  gcc@4.8.5

-- intel --------------------------------------------------------
intel@16.0.3

-- clang --------------------------------------------------------
clang@3.8.0

and the intel compiler is the one that is installed on the TOSS3 systems.

**Comment by KineticTheory** [comment]
@woodard I don't think that error is directly related to the boost recipe.  On Toss systems, I get those types of errors because LD_LIBRARY_PATH is cleared when spack is running, but Intel required it's runtime libraries to be available at link time.  Load the modulefile for the compiler that you want to use (intel/16.0.3) and then try:

```
spack install --dirty boost%intel
```

**Comment by woodard** [comment]
Shouldn't the compiler definition pick up that kind of thing when it adds the compiler? Compiler language runtimes are very common thing?

**Comment by tgamblin** [comment]
@woodard: yes but we haven't added the auto-detection for it.  For intel compilers, we'd need to source the `icc` startup scripts automatically and deduce what directories we should `RPATH` in, but currently we don't do that.  This is admittedly an LLNL thing -- we install our compilers to automatically RPATH things and to automatically find their runtime libs, but having to source something to run the compiler is becoming more and more common.

**Pull request merged**
