### PR TITLE
mgard: add version 2023-12-09 (1.5.2)

### PR DESCRIPTION
**Pull request by scottwittenburg**
Update mgard package so spack users have version `1.5.2`

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@robertu94 Does that look like the commit we want from your fork for `1.5.2`?

@eugeneswalker Any suggestion whether this should be the preferred version from the E4S perspective?

**Comment by robertu94** [comment]
@scottwittenburg this works for me. 👍🏻

**Comment by eugeneswalker** [comment]
> @robertu94 Does that look like the commit we want from your fork for `1.5.2`?
> 
> @eugeneswalker Any suggestion whether this should be the preferred version from the E4S perspective?

I'd defer to @robertu94 on what version of mgard is best to use. Thoughts?

**Comment by scottwittenburg** [comment]
Let's see what happens in gitlab pipelines if we make the preferred version.

**Comment by robertu94** [comment]
> > @robertu94 Does that look like the commit we want from your fork for `1.5.2`?
> > @eugeneswalker Any suggestion whether this should be the preferred version from the E4S perspective?
> 
> I'd defer to @robertu94 on what version of mgard is best to use. Thoughts?

I'd prefer that the newest version is preferred.

**Comment by scottwittenburg** [comment]
A bunch of stacks built the new version of `mgard` and dependents including `adios2`, here's a [link](https://gitlab.spack.io/spack/spack/-/pipelines/571686) to the `e4s` one.

Any objections to merging this?

**Comment by eugeneswalker** [comment]
> A bunch of stacks built the new version of `mgard` and dependents including `adios2`, here's a [link](https://gitlab.spack.io/spack/spack/-/pipelines/571686) to the `e4s` one.
> 
> Any objections to merging this?

No objections from me! Thanks Scott!

**Review by robertu94 — APPROVED** [review]
I thought this was approved and merged a while ago.  Sorry.,

**Comment by robertu94** [comment]
We need a review with write access for this to go in @eugeneswalker  I think you can merge.

**Comment by scottwittenburg** [comment]
Look like there are conflicts now, I'll resolve them and push so the pipelines run again.

**Review by eugeneswalker — APPROVED** [review]
Thank you!

**Pull request merged**
