### PR TITLE
occa: new version 1.2.0

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Review by sethrj — COMMENTED** [review]
I see that none of the other tags have git commit hashes attached, but that's the only secure and reproducible way to tag versions through git/spack. Can you add a `commit='abcdef'` for the tag here?

**Comment by cyrush** [comment]
@sethrj I added this for 1.2.0 release, I did not yet go back and do the others, should we do those as well?

**Comment by sethrj** [comment]
@cyrush It would be great if you could do that, but not an absolute must for this PR. I think you can also specify both a tag and a commit, which will make it easier to check that the tag matches the commit. Since all the commit SHAs can be pulled from the [tags page](https://github.com/libocca/occa/tags) it shouldn't be a big lift if you do want to add them.

**Comment by cyrush** [comment]
@sethrj update with commits + tags for all releases that were already in the package

**Review by sethrj — DISMISSED** [review]
Thanks @cyrush !

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
Can you rebase to run Gitlab pipelines on a new merge commit?

**Comment by cyrush** [comment]
@alalazo  I updated my fork's develop to the latest and then tried to rebase my branch off of that, but the result was a no-op.  Can you suggest how I should approach the rebase?

**Comment by cyrush** [comment]
@alalazo never mind, I fumbled part of the rebase process first time. I think we are in good shape now.

**Comment by cyrush** [comment]
Yikes, or not :-(

Looks like we are in worse shape now. 

I'll just create a new branch and start over.

**Pull request closed without merging**
