### PR TITLE
Docs: environment update

### PR DESCRIPTION
**Pull request by tldahlgren**
Working on hopefully improving the flow of the environments section of the docs.

UPDATE:
- Use the same terminology as the tutorial for different environment types;
- Other tweaks and elaborations.

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@tldahlgren Is this documentation update still a draft?

**Comment by tldahlgren** [comment]
> @tldahlgren Is this documentation update still a draft?

Yes, I'll need to update and revisit.

**Comment by haampie** [comment]
The change `anonymous` -> `independent` surprises me a bit, I always call it anonymous environment.

That's also in the CLI help text:

```
$ spack env create --help | grep anonymous
  env                   name of managed environment or directory of the anonymous env (when using --dir/-d) to activate
```

**Comment by tldahlgren** [comment]
> The change `anonymous` -> `independent` surprises me a bit, I always call it anonymous environment.
> 
> That's also in the CLI help text:
> 
> ```
> $ spack env create --help | grep anonymous
>   env                   name of managed environment or directory of the anonymous env (when using --dir/-d) to activate
> ```

There was a discussion amongst the core team 3 years ago about this and it was decided that `independent` was the better term (see https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html#managed-versus-independent-environments).  The change was made to the tutorial in https://github.com/spack/spack-tutorial/pull/127 though it looks like the rush up to ISC'21 didn't include renaming a couple of associated files.

That's a good catch w.r.t. the commands.  (I thought I'd fixed that recently but maybe it was lost in a rebase or something.)

**Comment by tldahlgren** [comment]
The most recent rebase and cleanup did not go as planned. While I successfully dropped the develop commits that had been added, I was concerned the motivation for a number of the post-rebase cleanup changes might be lost.

Will link the new PR shortly.

**Pull request closed without merging**
