### PR TITLE
Platform-specific config scopes

### PR DESCRIPTION
**Pull request by tgamblin**
Adds the ability to have platform-specific configuration scopes.  This allows Spack to know about things like default Blue Gene/Q compiler locations and default modules to load for Cray compilers out of the box.  In particular, this helps with #1980 - where we'd like to get @pramodk's settings into the mainline so that users don't have to do much of anything to configure Spack on BG/Q.

The platform config scopes go in subdirectories of a normal Spack config scopes.  The precedence looks like this:

1. `defaults`, in `etc/spack/defaults`: default configs that ship with Spack (e.g. `packages.yaml`)
1. `defaults/bgq`, in `etc/spack/defaults/bgq`: platform-specific overrides of defaults.
1. `site`, in `etc/spack`: spack-instance-specific settings.
1. `site/bgq`, in `etc/spack/bgq`: platform-specific overrides of site settings.
1. `user`, in `~/.spack`: user-specific settings.
1. `user/bgq`, in `~/.spack/bgq`: platform-specific overrides of user settings.

All of these are merged the same way the current `defaults`, `site`, and `user` scopes are merged.

@alalazo @adamjstewart @pramodk

### CODE REVIEW

**Comment by tgamblin** [comment]
@pramodk: if this works for you, I'll merge it to develop, then you can rebase #1980 and put the various bgq configs in `etc/spack/defaults/bgq`

**Comment by pramodk** [comment]
@tgamblin : I am testing this now on bg-q with #1980. I haven't changed site/defaults settings in the past, so correct me if I am missing anything below :

With this PR, `spack compilers` now creates ~/.spack/bgq/compilers.yaml and populates compilers, looks good:

```bash
compilers:
- compiler:
    modules: []
    operating_system: redhat6
    paths:
      cc: /usr/lib64/ccache/gcc
……….
    spec: gcc@4.4.7
- compiler:
    modules: []
    operating_system: CNK
    paths:
      cc: /usr/lib64/ccache/gcc
……
```
I added bg-q specific compiler setting in etc/spack/defaults/bgq/compilers.yaml:

```bash
compilers:

- compiler:
    modules: []
    operating_system: CNK
    paths:
      cc: /usr/bin/bgxlc_r
      cxx: /usr/bin/bgxlc++
      f77: /usr/bin/bgxlf_r
      fc: /usr/bin/bgxlf2008
    spec: xl@12.1
```

`spack compilers` shows xl compiler available, looks good:

```bash
==> Available compilers
-- gcc ----------------------------------------------------------
gcc@4.4.7  gcc@4.4.7

-- xl -----------------------------------------------------------
xl@12.1
```

XL has added for CNK,  so below looks goods:
```bash
$ spack spec mpich %xl
….
Concretized
------------------------------
  mpich@3.2%xl@12.1+hydra+pmi+romio~verbs arch=bgq-CNK-powerpc
```
I didn't add XL for front-end but tried below:
```bash
$ spack spec mpich %xl os=redhat6

Input spec
------------------------------
  mpich%xl arch=bgq-redhat6-None

Normalized
------------------------------
  mpich%xl arch=bgq-redhat6-None

Concretized
------------------------------
Traceback (most recent call last):
  File "/home/kumbhar/spack/bin/spack", line 192, in <module>
    main()
  File "/home/kumbhar/spack/bin/spack", line 169, in main
    return_val = command(parser, args)
  File "/home/kumbhar/spack/lib/spack/spack/cmd/spec.py", line 57, in spec
    spec.concretize()
  File "/home/kumbhar/spack/lib/spack/spack/spec.py", line 1327, in concretize
    self._concretize_helper())
  File "/home/kumbhar/spack/lib/spack/spack/spec.py", line 1159, in _concretize_helper
    spack.concretizer.concretize_compiler(self),
  File "/home/kumbhar/spack/lib/spack/spack/concretize.py", line 385, in concretize_compiler
    while not _proper_compiler_style(matches[index], spec.architecture):
IndexError: list index out of range
```
(once I add correct XL entry for front-end, above error goes away)

**Comment by tgamblin** [comment]
@pramodk: it looks like the configuration works fine.  The compiler issue is a separate issue with the concretizer -- that should be fixed but can you file it as a separate issue?

**Comment by tgamblin** [comment]
@pramodk: ok merged; can you rebase #1980?

**Comment by tgamblin** [comment]
I've got a few issues I'm working on (#1992, #1377, #1178) and then I can get on to fixing the various concretization issues.

**Comment by pramodk** [comment]
rebased #1980.

**Pull request merged**
