### PR TITLE
Add aocc support to ESMF

### PR DESCRIPTION
**Pull request by alexrichert**
This PR includes aocc as a supported compiler for ESMF.

### CODE REVIEW

**Review by theurich — APPROVED** [review]

**Review by jedwards4b — APPROVED** [review]
Are there any esmf version restrictions that should be included with this change?

**Comment by theurich** [comment]
> Are there any esmf version restrictions that should be included with this change?

I think the `ESMF_COMPILER=aocc` option became available with v8.4.0. However, notice also that it still isn't "officially" a supported compiler option. What that means in ESMF lingo is that we do not currently have 100% clean results with it on any of our test platforms. In fact, the only place we current test AOCC nightly right now is on my laptop. So it is "experimental", but as far as Spack is concerned, this PR *is* the way to tell ESMF to build with AOCC.

**Comment by alexrichert** [comment]
I added in a conflict for pre-8.4. For what it's worth it might be worth adding conflicts for other compilers, e.g., nvhpc which I'm assuming was added relatively recently.

**Comment by theurich** [comment]
Yes, the `ESMF_COMPILER=nvhpc` also came in with v8.4.0. However, it is an "officially" supported compiler option since v8.6.0. We definitely consider it stable.

**Review by uturuncoglu — APPROVED** [review]
It looks good to me. Thanks.

**Review by climbfuji — APPROVED** [review]
Happy to see this! Noting from the conversation that aocc isn't fully supported yet (i.e. is experimental), but I believe @theurich and I may be working on the same machine and want to build a stack with aocc ;-)

**Review by alecbcs — APPROVED** [review]
Looks good to me. Thanks to all of the maintainers for the lively discussion and quick turn around on this PR!

**Pull request merged**
