### PR TITLE
py-nltk: add v3.9.1

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Comment by meyersbs** [comment]
Builds and runs for me.

```
==> Installing py-nltk-3.9.1-lghnq6j2zaxsm5g27o5kxfr632x7w7uc [59/59]
==> No binary for py-nltk-3.9.1-lghnq6j2zaxsm5g27o5kxfr632x7w7uc found: installing from source
==> Fetching https://pypi.io/packages/source/n/nltk/nltk-3.9.1.tar.gz
==> No patches needed for py-nltk
==> py-nltk: Executing phase: 'install'
==> py-nltk: Successfully installed py-nltk-3.9.1-lghnq6j2zaxsm5g27o5kxfr632x7w7uc
  Stage: 0.64s.  Install: 2.37s.  Post-install: 0.36s.  Total: 3.87s
[+] /home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-lghnq6j2zaxsm5g27o5kxfr632x7w7uc
$ spack load py-nltk@3.9.1
$ python3
Python 3.12.5 (main, Sep 11 2024, 07:53:57) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> 
```

**Review by meyersbs — CHANGES_REQUESTED** [review]
sha256 matches. Builds and installs, but `+data` is missing a resource called `punkt_tab`.

```
$ python3
Python 3.12.5 (main, Sep 11 2024, 07:53:57) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> sentence = """At eight o'clock on Thursday morning Arthur didn't feel very good."""
>>> tokens = nltk.word_tokenize(sentence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize
    tokenizer = _get_punkt_tokenizer(language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer
    return PunktTokenizer(language)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/py-nltk-3.9.1-mgnhahrnlmv5wak4mk67vn3nh7cslwte/nltk_data'
    - '/home/bsmits/nltk_data'
    - '/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/python-venv-1.0-647rleqhijzc43lf7dvu3iiiro6bfayw/nltk_data'
    - '/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/python-venv-1.0-647rleqhijzc43lf7dvu3iiiro6bfayw/share/nltk_data'
    - '/home/bsmits/spack/opt/spack/linux-rhel9-skylake_avx512/gcc-13.2.0/python-venv-1.0-647rleqhijzc43lf7dvu3iiiro6bfayw/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by meyersbs** [comment]
https://github.com/nltk/nltk/issues/3293

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
@qwertos : See the comments from @meyersbs and the bug on missing `nltk.download('punkt_tab')`

**Review by bernhardkaindl — APPROVED** [review]
Thanks @qwertos for the update! I see punkt_tab is added and punkt is changed to `when="+data@:3.8.1"`

@meyersbs Giving my approval to cancel my block on the merge, but as you are the maintainer of `py-nltk`, we should give you a week for comment or approve!

**Review by meyersbs — APPROVED** [review]
Looks good to me

**Pull request merged**
