### PR TITLE
sz: version bump, cmake bug-fix, add maintainer

### PR DESCRIPTION
**Pull request by robertu94**
+ Added version 2.1.9
+ Previously the SZ package incorrectly depended on CMake without a
  version dependancy, but actually version 3.13 or newer is required
+ Added myself as a maintainer for the SZ spack package

@disheng222 Could you please approve this?

### CODE REVIEW

**Comment by disheng222** [comment]
I here approve Robert's all changes. I am glad to add Robert as the maintainer of the sz-spack. Thanks!

**Comment by disheng222** [comment]
I here approve Robert's all changes. I am glad to add Robert as the maintainer of the sz-spack. Thanks!

**Comment by disheng222** [comment]
I here approve Robert's all changes. I am glad to add Robert as the maintainer of the sz-spack. Thanks!

**Comment by disheng222** [comment]
I here approve Robert's all changes. I am glad to add Robert as the maintainer of the sz-spack. Thanks!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
