### PR TITLE
Paraview catalyst support

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by tldahlgren** [comment]
Will defer merge decision to give at least one maintainer a chance to comment.

**Review by vicentebolea — APPROVED** [review]

**Comment by mathstuf** [comment]
Vicente has approved it. Is it good to merge now?

**Comment by tldahlgren** [comment]
Required pipeline check failed.  Looks like at least one of the stacks had problems with a pod.

@spackbot run pipeline

**Review by vicentebolea — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]

**Comment by mathstuf** [comment]
The failing AWS pipeline in the gitlab-ci link seems infra-related to me.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
