### PR TITLE
namd: add v3.0

### PR DESCRIPTION
**Pull request by RMeli**
* Add `3.0`
* Deprecate all alpha and beta releases

https://www.ks.uiuc.edu/Research/namd/3.0/announce.html

### CODE REVIEW

**Comment by RMeli** [comment]
@spackbot fix style

**Review by jcphill — CHANGES_REQUESTED** [review]
Content looks good but please squash and rebase to clean up history (https://spack.readthedocs.io/en/latest/contribution_guide.html#rebasing)

**Comment by RMeli** [comment]
Will do, but for Spack squash-merge is always used.

**Comment by RMeli** [comment]
@jcphill history should be clean now, sorry about that.

**Review by jcphill — APPROVED** [review]

**Review by tldahlgren — DISMISSED** [review]

**Comment by alecbcs** [comment]
@spackbot fix style

**Review by msimberg — APPROVED** [review]
Hash confirmed.

**Pull request merged**
