### PR TITLE
tfel: Add CalculiX  variant

### PR DESCRIPTION
**Pull request by thelfer**
Support for CalculiX was missing. This PR fixes this issue.

### CODE REVIEW

**Comment by sethrj** [comment]
@thelfer Are you sure this PR is correct, and that your submission branch didn't get messed up with merges/rebases? According to the diff the only thing this changes is a new variant that doesn't in anyway alter  the behavior of the package. If this PR is in error,  please close it.

**Comment by thelfer** [comment]
@sethrj Well, I merged my fork with the upstream develop branch using:

~~~~{.bash}
$ git pull https://github.com/spack/spack.git -b develop
~~~~

Then made my changes and made the PR. Let me know if I shall use another workflow.

Concerning the PR, the proposed change add a variant and enables it by default. If the variant is enabled, then the appropriate flag is passed to `cmake` enabling the `calculix` interface. Before this PR, spack users did not have a mean to enable the `calculix` interface.

I tested it. It works as expected.

**Comment by sethrj** [comment]
OK @thelfer I see the problem  -- the existing package recipe *calls* for a variant named `calculix` but it doesn't exist. I've force-pushed to update your branch -- something went wrong in your rebasing, so please `git fetch origin && git reset --hard origin/develop`.

If you're up for  making some changes to the recipe, the use of the [define_from_variant](https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html#adding-flags-to-cmake) will simplify your script *and* prevent this sort of error from occurring in the future. For example:
```python
        if '+castem' in self.spec:
            args.append("-Dlocal-castem-header=ON")
        else:
            args.append("-Dlocal-castem-header=OFF")
```
simplifies to
```python
        args.append(self.define_from_variant('local-castem-header', 'castem'))
```
and checks that the variant `castem` actually exists.

**Comment by thelfer** [comment]
@sethrj I try to merge from the official develop branch as follows:

~~~~
$ git remote add upstream https://github.com/spack/spack
$ git fetch upstream
$ git merge upstream/develop
~~~~

Hope it's better now.

Thanks for the `define_from_variant` tip. I'll update the package after this PR.

**Comment by sethrj** [comment]
> @sethrj I try to merge from the official develop branch as follows:
> 
> ```
> $ git remote add upstream https://github.com/spack/spack
> $ git fetch upstream
> $ git merge upstream/develop
> ```
> 
> Hope it's better now.

Unfortunately not; I'm not sure why the upstream commits are showing up as part of this PR, but in the Spack repository (not all repos) it's best to *rebase* instead of merge. I've updated your "develop" branch to make this easier to review. I recommend for future PRs that you create a non-develop branch on your local checkout with `git fetch upstream && git checkout -b my-branch-name upstream/develop`.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
