### PR TITLE
openblas: New version 0.3.23

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
@spackbot help

**Comment by eschnett** [comment]
@spackbot run pipeline

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Lets see if updating the branch helps.

**Comment by haampie** [comment]
The last test of openblas is stuck, @eugeneswalker figured that out.

Apparently not particularly CPU specific

**Comment by haampie** [comment]
So, it looks like it's stuck in OpenMP builds in `test_post_fork.c`, see for example here:

https://gitlab.spack.io/spack/spack/-/jobs/6650547

which does the following:

```c
#ifdef USE_OPENMP
    nthreads_omp = omp_get_max_threads();
    // Run with half the max OMP threads, the max threads and twice that
    for(i = (nthreads_omp + 1) / 2; i <= nthreads_omp * 2; i *= 2) {
        omp_set_num_threads(i);
#endif
```

The only thing that stands out is `nthreads_omp * 2`.

I can't really reproduce the problem locally, so just pushed a change that sets NUM_THREADS to something large to see if it has an effect.

**Comment by haampie** [comment]
More likely explanation is that the build job is only allocated a single CPU, but the tests run something that needs `$(nproc) * 2` threads. Let's try again...

**Comment by haampie** [comment]
TEST 37/37 fork:safety_after_fork_in_parent [OK] 🎉

**Review by haampie — APPROVED** [review]

**Pull request merged**
