### PR TITLE
armpl: New package added for ArmPL

### PR DESCRIPTION
**Pull request by OliverPerks**
New package added for the Arm Performance Libraries (ArmPL) implementation of BLAS, LAPACK and FFTW.

Only works on Arm hardware - and depends upon the `Arm` package install, no source code install, just wraps the existing 'arm' install to provide multiple variants. 

Designed to replicate the style of OpenBLAS.

### CODE REVIEW

**Review by srinathv — APPROVED** [review]
Looks good.

**Review by srinathv — APPROVED** [review]

**Review by srinathv — DISMISSED** [review]

**Comment by srinathv** [comment]
I reviewed this PR but still not merged.  Can I get an explanation as to why?

**Comment by scheibelp** [comment]
It looks like the style checker failed: https://github.com/spack/spack/pull/25461/checks?check_run_id=3686591185

All CI checks have to pass for us to merge. If you think a CI check failed erroneously then feel free to ping us. Otherwise we sometimes assume the user will resolve the failing check themselves.

**Comment by OliverPerks** [comment]
Right, so the isort style checker was added between the original commit (which was passing mypy and flake8) and now. Hopefully this latest push should fix this.

**Review by srinathv — APPROVED** [review]
The changes are compliant.  Incorrectly asked for self-review

**Comment by OliverPerks** [comment]
@alalazo I think this should be good to go. I will do another PR to do a version bump, but that is tied in to a few other packages too, for now I'm happy with  just getting this in.

**Review by srinathv — APPROVED** [review]
This changes are approved

**Comment by srinathv** [comment]
> It looks like the style checker failed: https://github.com/spack/spack/pull/25461/checks?check_run_id=3686591185
> 
> All CI checks have to pass for us to merge. If you think a CI check failed erroneously then feel free to ping us. Otherwise we sometimes assume the user will resolve the failing check themselves.

The CI is stating a reviewer "with write privileges" is required for the merge. @scheibelp, can this be done my you?

**Review by srinathv — APPROVED** [review]
Latest changes are good.

**Comment by srinathv** [comment]
I need someone with write privileges to approve.

**Comment by srinathv** [comment]
oh...just saw the "docs/readthedocs.org:spack " requirement.  What is this? 
I'm learning here so please be patient.

**Comment by alalazo** [comment]
@srinathv The required and pending check means that a required check was added on Spack side after CI was last run on this PR. If you rebase the PR CI will run again and that will be solved.

**Comment by tomgreen66** [comment]
I have done some work to try and replicate the same behaviour as found in other compiler and Blas providers (e.g. Intel MKL, Intel Compiler vs Intel Parallel Studio).  I will put a pull request in with the change and others can consider it.

**Comment by tomgreen66** [comment]
> I have done some work to try and replicate the same behaviour as found in other compiler and Blas providers (e.g. Intel MKL, Intel Compiler vs Intel Parallel Studio). I will put a pull request in with the change and others can consider it.

See: #27750

**Comment by OliverPerks** [comment]
Deleting this PR to start a fresh one.

**Pull request closed without merging**
