### PR TITLE
Changed https -> http

### PR DESCRIPTION
**Pull request by eklee15**
Can we relax https to http? It seems I cannot access the https server directly from my machine due to the firewall issue. It would be great if we can relax it a bit to http if it is not a serious concern. I've seen many packages are using http.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@citibeth @tgamblin?

**Comment by tgamblin** [comment]
@eklee15: does running `spack -k` not work for you?

**Comment by eklee15** [comment]
It still does not work. 

-bash-4.2$ spack -k install libsigsegv
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Installing libsigsegv
==> Fetching https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz

curl: (35) Encountered end of file
==> Fetching from https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz failed.
==> Error: FetchError: All fetchers failed for libsigsegv-2.11-jz72ujpo6i6rjfadjntfrhuymodm67si
/home/eklee/spack/lib/spack/spack/package.py:923, in do_fetch:
     896      def do_fetch(self, mirror_only=False):
     897          """
     898          Creates a stage directory and downloads the tarball for this package.
     899          Working directory will be set to the stage directory.
     900          """
     901          if not self.spec.concrete:
     902              raise ValueError("Can only fetch concrete packages.")
     903  
     904          start_time = time.time()
     905          if spack.do_checksum and self.version not in self.versions:
     906              tty.warn("There is no checksum on file to fetch %s safely." %
     907                       self.spec.format('$_$@'))
     908  
     909              # Ask the user whether to skip the checksum if we're
     910              # interactive, but just fail if non-interactive.
     911              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     912              ignore_checksum = False
     913              if sys.stdout.isatty():
     914                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     915                                                      default=False)
     916                  if ignore_checksum:
     917                      tty.msg("Fetching with no checksum.", ck_msg)
     918  
     919              if not ignore_checksum:
     920                  raise FetchError("Will not fetch %s" %
     921                                   self.spec.format('$_$@'), ck_msg)
     922  
  >> 923          self.stage.fetch(mirror_only)
     924  
     925          self._fetch_time = time.time() - start_time
     926  
     927          if spack.do_checksum and self.version in self.versions:
     928              self.stage.check()
     929  
     930          self.stage.cache_local()

**Comment by ax3l** [comment]
To be honest, I find that change a bit weird. Not allowing TCP on 443 is a very local problem and should not influence our general package sources. Also, where should be stop? Just those two packages?

I also wonder which sane firewall policy would actually prefer unencrypted traffic, but that's an other story. If such corporate environments exist, I would recommend them to set up local http-only mirrors. Keep the main sources by default on TLS based protocols where possible, for simple privacy reasons (no-one needs to know what I am fetching exactly from gnu.org or debian.org).

**Comment by eklee15** [comment]
Sorry that I forgot to close this issue, it was a local problem due to the SSL authentication. I will close this issue. Thanks.

**Pull request closed without merging**
