### PR TITLE
Add cuda 12.4.0 to packages

### PR DESCRIPTION
**Pull request by LiquidPT**
Adding Cuda 12.4.0. Created new PR as the last one seemed to have a failed build that wouldn't reset

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
This seems to fail on a specific CUDA header:
```
instantiation of "void gko::kernels::cuda::components::sum_duplicates(std::shared_ptr<const gko::CudaExecutor>, gko::size_type, gko::array<ValueType> &, gko::array<IndexType> &, gko::array<IndexType> &) [with ValueType=std::complex<double>, IndexType=gko::int64]" at line 112 of /tmp/root/spack-stage/spack-stage-ginkgo-1.7.0-ouzmj6eauwr4hqjtt5odserx4hncdcft/spack-src/common/cuda_hip/base/device_matrix_data_kernels.hpp.inc
/home/software/spack/[padded-to-256-chars]/linux-ubuntu22.04-neoverse_v1/gcc-11.4.0/cuda-12.4.0-zwnhyvpld62qj25pom64djygn5wvqde5/include/thrust/system/cuda/detail/reduce_by_key.h(692): error: ambiguous "?" operation: second operand of type "thrust::THRUST_200301_900_NS::detail::tuple_of_iterator_references<const std::ptrdiff_t &, const std::ptrdiff_t &>" can be converted to third operand type "cuda::std::__4::tuple<std::ptrdiff_t, std::ptrdiff_t>", and vice versa
                                       : key_type();
```
See https://gitlab.spack.io/spack/spack/-/jobs/10330136

**Comment by alalazo** [comment]
@fspiga FYI

**Comment by LiquidPT** [comment]
> This seems to fail on a specific CUDA header:
> 
> ```
> instantiation of "void gko::kernels::cuda::components::sum_duplicates(std::shared_ptr<const gko::CudaExecutor>, gko::size_type, gko::array<ValueType> &, gko::array<IndexType> &, gko::array<IndexType> &) [with ValueType=std::complex<double>, IndexType=gko::int64]" at line 112 of /tmp/root/spack-stage/spack-stage-ginkgo-1.7.0-ouzmj6eauwr4hqjtt5odserx4hncdcft/spack-src/common/cuda_hip/base/device_matrix_data_kernels.hpp.inc
> /home/software/spack/[padded-to-256-chars]/linux-ubuntu22.04-neoverse_v1/gcc-11.4.0/cuda-12.4.0-zwnhyvpld62qj25pom64djygn5wvqde5/include/thrust/system/cuda/detail/reduce_by_key.h(692): error: ambiguous "?" operation: second operand of type "thrust::THRUST_200301_900_NS::detail::tuple_of_iterator_references<const std::ptrdiff_t &, const std::ptrdiff_t &>" can be converted to third operand type "cuda::std::__4::tuple<std::ptrdiff_t, std::ptrdiff_t>", and vice versa
>                                        : key_type();
> ```
> 
> See https://gitlab.spack.io/spack/spack/-/jobs/10330136

Thanks for showing me where/what the error is. I've installed 12.4 on a clean (other than build-essential) Ubuntu 22.04 VM and it installed fine. I also compared this header file between Cuda 12.2.1 and 12.4 installs, and 12.4 only added some pragma headers. Otherwise the files are identical.

I'm not sure what tests the pipeline is doing. Is there a way I can replicate this locally? Maybe then I could go back to NVIDIA support with an issue, but I don't know what to do for now. I need Cuda 12.4 to upgrade the video drivers in our buildout, and we've just recently switched to having Spack as a dependency (which has recently been painful with the GNU FTP mirror acting up as well)

**Comment by LiquidPT** [comment]
Sorry @fspiga , I didn't see your comment in the other PR and figured I'd gotten into some sort of dead end pipeline.

**Comment by alalazo** [comment]
One way to move this forward would be to pin the CUDA deps in the pipelines, merge this PR, and then try to fix the build in another PR. Otherwise we need to understand why the builds on `power` and `aarch64` machines are failing.

**Comment by alalazo** [comment]
> Is there a way I can replicate this locally?

It should be possible. If you look at the bottom of the log in e.g. https://gitlab.spack.io/spack/spack/-/jobs/10330136 you'll see:

> To reproduce this build locally, run:
>    spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/10330136/artifacts [--working-dir <dir>] [--autostart]
If this project does not have public pipelines, you will need to first:
    export GITLAB_PRIVATE_TOKEN=<generated_token>
... then follow the printed instructions.

If you are running on the right host (neoverse in this case), then you should be able to reproduce this. Otherwise you can emulate the host, but that is terribly slow.

**Comment by LiquidPT** [comment]
@alalazo , would it be possible to only check in the x86_64 for cuda 12.4? That's the one we need, and I'm not in any position to debug NVIDIA's code on arm or ppc. 

Otherwise I'm stuck at 12.2. (the samples for 12.3 have a bug in them that won't compile and are fixed in the 12.4 samples)

**Comment by alalazo** [comment]
@LiquidPT I think it would be better to add all of them, but constrain our builds to the older version where they are failing. I can do that if you revert the last commit, and you're ok with me pushing to this PR.

**Comment by LiquidPT** [comment]
> I can do that if you revert the last commit, and you're ok with me pushing to this PR.

@alalazo, done and yes, please do this when possible

**Comment by LiquidPT** [comment]
> @LiquidPT I think it would be better to add all of them, but constrain our builds to the older version where they are failing. I can do that if you revert the last commit, and you're ok with me pushing to this PR.

@alalazo ?

**Comment by LiquidPT** [comment]
We've abandoned our use of Spack in our build process, at least in part because of the difficulties and hurdles here to update one of the packages we're critically dependent on.

**Comment by alalazo** [comment]
@LiquidPT I'm sorry to hear that. With the PR inflow we have it's not unusual to have a few days between interactions. In any case, see https://github.com/spack/spack/pull/42748 which adds conflicts to `petsc` and `ginkgo`. That should hopefully fix the build failures in our pipelines.

**Comment by alalazo** [comment]
For what is worth #42748 is merged

**Pull request closed without merging**
