### PR TITLE
add Intel TBB package

### PR DESCRIPTION
**Pull request by davydden**
work-in-progress. Funny enough download fails in Spack, but it works with the same link manually or with homebrew.

### CODE REVIEW

**Comment by davydden** [comment]
oh well, the download issues seems to be known https://groups.google.com/forum/?fromgroups#!topic/spack/fQM7LRTaNtM

**Comment by davydden** [comment]
regarding the download issue, i guess something got redirected as
```
$ curl -LO https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2982k  100 2982k    0     0  1855k      0  0:00:01  0:00:01 --:--:-- 1855k
iwtm51nb:spack davydden$ spack install tbb
==> Installing tbb
==> Trying to fetch from https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_4.4.3.tgz

curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_4.4.3.tgz failed.
==> Error: All fetchers failed for tbb-4.4.3-l47q4h3t7wdtkj32ik2h3kvyv6qbkj5m
==> Error: Installation process had nonzero exit code.
```
(note that ` Trying to fetch from` is a different URL than that which is in python script).

**Comment by davydden** [comment]
hmm, even `Macports` mirror does not work: http://distfiles.macports.org/tbb/tbb44_20150728oss_src.tgz 
any ideas?

**Comment by adamjstewart** [comment]
Hmm, this sounds eerily familiar to #544. Both involve a URL that works with wget/curl but not within Spack. Can you try the suggestion from #51 and add the url directly to `version()`?

**Comment by davydden** [comment]
that worked, @adamjstewart ! I will test the PR and update it soon...

**Comment by adamjstewart** [comment]
Awesome! I believe you are right in your assumption. The global url variable stores the url for a single version. You can add as many other versions as you want. If there is not a url argument to `version()`, Spack will take whatever version number it detects in the global url and replace it with this version. In your case, Spack thinks the version is 0 and replaces it with 4.4.3.

I don't see any easy workarounds to solve this problem aside from specifying the url with every version that gets added. Normally, you could implement `url_for_version` to calculate what the url path should look like based on the version number, but since the url includes things like dates, this is impossible. It's not a limitation of Spack so much as a idiotic file naming convention on their part.

**Comment by adamjstewart** [comment]
Just saw your updated code. You will still probably need to keep a global url to keep Spack happy. Otherwise, I think `spack spec tbb` will crash.

**Comment by davydden** [comment]
`spack spec tbb` seems to work
```
$ spack spec tbb
Input spec
------------------------------
  tbb

Normalized
------------------------------
  tbb

Concretized
------------------------------
  tbb@4.4.3%clang@7.0.2-apple=darwin-x86_64
```

**Comment by davydden** [comment]
@adamjstewart  thanks for explanation. Makes perfect sense.

**Comment by adamjstewart** [comment]
Hmm, I took a look at the build log and a completely unrelated test failed (libelf failed to download). I don't know if there's any other way to rerun the test build without pushing a new commit.

**Comment by davydden** [comment]
i did `push --force` with some dummy changes...

**Pull request merged**
