### PR TITLE
py-folium: add new package with version 0.16.0

### PR DESCRIPTION
**Pull request by ChristopherChristofi**
PyFolium - 0.16.0: [release notes](https://github.com/python-visualization/folium/releases/tag/v0.16.0)

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage and version sha256.

**Comment by tldahlgren** [comment]
'spack spec' succeeds but I cannot build it due to `py-cython` problems (I suspect on my end).

**Review by bernhardkaindl — APPROVED** [review]
I was able to build it successfully.

**Review by bernhardkaindl — APPROVED** [review]
Checked the dependencies by comparing with https://github.com/conda/grayskull and https://github.com/conda-forge/folium-feedstock/blob/main/recipe/meta.yaml:

100% match, ready to merge.

**Pull request merged**
