### PR TITLE
New package: py-inflect

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Comment by qwertos** [comment]
@spackbot fix style

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256; however, it fails to install for me:

```
...
     63      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 64    error: metadata-generation-failed
     65    
     66    × Encountered error while generating package metadata.
     67    ╰─> See above for output.
     68    
     69    note: This is an issue with the package mentioned above, not pip.
...

$ cat <build log>
...
      items = working_set.resolve(reqs, env, installer, extras=self.extras)
    File "/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/py-setuptools-65.5.0-rpcafnypsdpwsqmnomixoajk6qu5vxmq/lib/python3.7/site-packages/pkg_resources/__init__.py", line 800, in resolve
      raise VersionConflict(dist, req).with_context(dependent_req)
  pkg_resources.VersionConflict: (packaging 17.1 (/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-packaging-17.1-dvtqkhw64kssdzm7fsb4wpmgzzarv3tq/lib/python3.7/site-packages/packaging-17.1-py3.7.egg), Requirement.parse('packaging>=20.0'))
  error: subprocess-exited-with-error

  ?~W Preparing metadata (pyproject.toml) did not run successfully.
  ?~T~B exit code: 1
  ?~U??~T~@> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
...
```

**Review by adamjstewart — APPROVED** [review]
Package deps look correct, can't help with @tldahlgren's build error without seeing the full build log.

**Review by bernhardkaindl — APPROVED** [review]
Adam J. Steward already reviewed and approved.
I built it on a fresh install of Ubuntu 22.04/Skylake.
This means there is no problem with this package itself and the error observed by Tamara has another source. Merging.

**Pull request merged**
