### PR TITLE
fixes to get python extensions to build properly

### PR DESCRIPTION
**Pull request by lee218llnl**
the cairo, freetype, and harfbuzz modifications were required to get py-rpy2 installed on a TOSS 3 (RHEL 7) system. I also threw in some additional ignores within python's package.py to handle py-pygments pygmentize duplication and py-numpy f2py3.

### CODE REVIEW

**Comment by adamjstewart** [comment]
If you rebase it should take care of all of the python flake8 complaints.

**Comment by tgamblin** [comment]
@lee218llnl can you rebase/merge?

**Comment by adamjstewart** [comment]
Oops, that's a lot of commits. I don't know git very well, but maybe you can try the following:
```
git reset --hard 06cc2d6
git fetch origin develop
git rebase develop
```
You might want to wait for @tgamblin to confirm whether or not my commands actually work.

**Comment by tgamblin** [comment]
@lee218llnl: I'm not sure where you're pulling all the superfluous commits from but if @adamjstewart's suggestion doesn't work could you just cherry-pick your changes on top of a branch based on develop?

**Comment by lee218llnl** [comment]
@tgamblin I think it got it rebased properly and it appears to be passing all checks.

**Comment by tgamblin** [comment]
@lee218llnl: It looks like there are still 250 different commits from develop in this.  I think you pulled in something based on the `newarch` branch from NERSC, which we rebased before merging (so you have some of the pre-rebased commits).

Are these the only commits you care about?
1. 06cc2d62fd
2. f7f9f9becd4

It looks like this one (also merged) is a duplicate of 06cc2d62fd:
3. af98e27f16

I think you just want to do this:
```
<make a fresh clone (I think your develop branch includes stuff from NERSC)>
git fetch github
git checkout -b bugfix/new-harfbuzz-fix
git cherry-pick 06cc2d62fd
git cherry-pick f7f9f9becd4
```

I tried this but 06cc2d62fd has conflicts, and I don't know immediately how you want them resolved.

**Comment by tgamblin** [comment]
Looks good.  Merged #1087.

**Pull request closed without merging**
