### PR TITLE
adding new rpp package

### PR DESCRIPTION
**Pull request by afzpatel**

### CODE REVIEW

**Review by srekolam — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed the home page and version sha256s.  Deferring to give @bvanessen time to comment on the changes to the `half` package.

**Comment by afzpatel** [comment]
Hi @bvanessen this pr is ready to be reviewed. The only change made to the half recipe is adding a symlink because the rpp header files contain `#include <half/half.hpp>`

**Comment by afzpatel** [comment]
@tldahlgren @bvanessen

**Comment by afzpatel** [comment]
@tldahlgren @bvanessen

**Comment by tldahlgren** [comment]
@bvanessen It's been two weeks so I merged the PR.

**Pull request merged**
