### PR TITLE
Testing fix for lock on github runners

### PR DESCRIPTION
**Pull request by vsoch**
The previous issue with lock/hostnames is reported to be resolved, e.g., see https://github.com/actions/virtual-environments/issues/3185 and I want to test if it indeed is.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by tgamblin** [comment]
Should we merge this?

**Comment by vsoch** [comment]
If you have preference for the previous method to derive hostnames, then yes. otherwise, safe to close. I said I would follow up on tracking this issue and do this PR when it was fixed so that's why I opened this PR. I can't say I have an opinion either way - both seem to work ok!

**Comment by tgamblin** [comment]
Given that this is just for lock debugging, let's leave it as-is. I think `gethostname()` differentiates the nodes well enough, and here's another reason we might want to leave it:

```console
(spackle):~> cat hostname.py
#!/usr/bin/env python
import socket
for i in range(10000):
    socket.gethostname()
(spackle):~> cat fqdn.py    
#!/usr/bin/env python
import socket
for i in range(10000):
    socket.getfqdn()
(spackle):~> time ./hostname.py
        0.07 real         0.02 user         0.03 sys
(spackle):~> time ./fqdn.py    
        4.73 real         0.53 user         1.25 sys
```

`getfqdn()` uses DNS, while `gethostname()` is, I think entirely local.  I think on most of the systems where we'd care about this, `gethostname()` is fine and also very much faster.

**Comment by vsoch** [comment]
That's what we call a bug that turned into a blessing!

**Pull request closed without merging**
