### PR TITLE
Build Cube pckage with parallel make (only install phase serial)

### PR DESCRIPTION
**Pull request by pramodskumbhar**
Tested on Ubuntu 16.04 with gcc
(parallel build support documented in official [instructions](https://apps.fz-juelich.de/scalasca/releases/cube/4.3/docs/install/install.html))

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you see if the test pass in parallel?

**Comment by pramodskumbhar** [comment]
> Can you see if the test pass in parallel?

you mean `make test` ? I don't think there are tests : 

```
==> 'make' '-j8' 'test'
make: Nothing to be done for 'test'.
```

**Comment by adamjstewart** [comment]
I mean `make check`. It's listed on the CUBE Installation Guide, so it must have unit tests of some kind.

**Comment by pramodskumbhar** [comment]
I see following : 

```
==> 'make' '-j8' 'make check'
make: *** No rule to make target 'make check'.  Stop.
```

I think this can be merged?

**Pull request merged**
