### PR TITLE
Fix pkgconfig dependencies

### PR DESCRIPTION
**Pull request by michaelkuhn**
Packages should depend on the virtual provider, pkgconfig, not on its implementations pkg-config or pkgconf.

### CODE REVIEW

**Comment by robertu94** [comment]
This looks good to me. I should be a maintainer for LibPressio and Speer, but I forgot to add myself.

**Comment by perarnau** [comment]
That's a no for me on aml. Building master requires pkgconf-specific m4 rules for autoconf.

**Comment by michaelkuhn** [comment]
> That's a no for me on aml. Building master requires pkgconf-specific m4 rules for autoconf.

Thanks for the hint! I reverted the change and added a comment about the incompatibility.

**Comment by shaomeng** [comment]
This looks good to me too. Thanks to everyone!

**Review by tldahlgren — APPROVED** [review]
LGTM.  I appreciate the switch to the virtual `pkgconfig` provided by both `pkgconf` and `pkg-config` when allowed.

**Review by wanlinwang — APPROVED** [review]
It looks also ok for me. Thank you！

**Pull request merged**
