### PR TITLE
Update ACFL include paths in package definitions

### PR DESCRIPTION
**Pull request by paolotricerri**
Some time ago, an issue was highlighted from internal pipelines when installing gromacs with armpl-gcc@24.04 that was related to the include path of the armpl-gcc package (see https://github.com/spack/spack/pull/43553#issuecomment-2058774985)

The same problem was undetected for acfl which, from version 24.04, will have its include in `include` and not in an include folder specifying the length for integer type, e.g. `include_ilp64`.

This PR aims at preventing the same problem from happening with acfl.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM.  Curious though.  Does this change also need to be applied to `blas_libs`?  I ask only because you're using `lib_suffix()` here and in that property.

**Comment by paolotricerri** [comment]
@tldahlgren I would say no. 

The change here is to make sure that the include path is correct by using (or not using) the lib_suffix correctly. 

If I understand correctly `blas_libs` is the function that looks for the libraries in the appropriate folder root). In that case, the libraries do still have the suffix, also from 24.04, so using the lib_suffix always if correct.

Please, do let me know if I have answered your question fully. Thanks

**Comment by paolotricerri** [comment]
@alalazo  @tldahlgren , I just noticed this is still open and was wondering if it can be merged, if I have addressed all points of the review and there is no more remarks? Thanks

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks @paolotricerri

**Pull request merged**
