### PR TITLE
Vtkm kokkos variant

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Add a kokkos backend variant

Notes:

vtk-m +cuda is not compatible with  kokkos +cuda
vtk-m +rocm requires +kokkos. kokkos is the ROCm backend.

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
I think this is going to obsolete #28180

**Comment by kwryankrattiger** [comment]
@chuckatkins

**Comment by eugeneswalker** [comment]
Mesa18 requires python 2?

We have this also where we were able to build with Python 3.8.12: https://github.com/spack/spack/pull/28345

**Comment by kwryankrattiger** [comment]
> Mesa18 requires python 2?

I see it was only deprecated, I must have misread deprecated as deleted. I will rebase and remove that change in favor of #28345

**Review by chuckatkins — APPROVED** [review]

**Pull request merged**
