### PR TITLE
py-mccabe: don't require pytest-runner for install

### LINKED ISSUE #5420: can't build py-mccabe (and py-flake8) on osx
On OSX (10.11.6), I can't use spack to install `py-flake8` b/c `py-mccabe` (one of flake8's dependencies) fails.

Issue looks like a problem with `pytest-runner` being needed.

I tried adding `pytest-runner`, but it failed to build & thats as far down as the rabbit hole I had time to explore.

Full Details Below.

**spack install py-flake8**
```
==> python is already installed in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-5vxw6f2k4hjdnk7fi6tulhtrasixblki
==> py-enum34 is already installed in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-enum34-1.1.6-hdwea3dsqtekcgnnwje3sg6m7zvqvss3
==> python is already installed in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-5vxw6f2k4hjdnk7fi6tulhtrasixblki
==> py-pytest is already installed in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-pytest-3.0.7-jk7mvh7cjoj4ii4uj57aeud3bwg2b737
==> py-setuptools is already installed in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275
==> Installing py-mccabe
==> Using cached archive: /Users/harrison37/Work/2017_09_conduit_spack_update/spack/var/spack/cache/py-mccabe/py-mccabe-0.5.2.tar.gz
==> Already staged py-mccabe-0.5.2-2svvfdbb5hhuzqydx37fmodrxcr47a64 in /Users/harrison37/Work/2017_09_conduit_spack_update/spack/var/spack/stage/py-mccabe-0.5.2-2svvfdbb5hhuzqydx37fmodrxcr47a64
==> No patches needed for py-mccabe
==> Building py-mccabe [PythonPackage]
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-5vxw6f2k4hjdnk7fi6tulhtrasixblki/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /Users/harrison37/Work/2017_09_conduit_spack_update/spack/var/spack/stage/py-mccabe-0.5.2-2svvfdbb5hhuzqydx37fmodrxcr47a64/mccabe-0.5.2/spack-build.out
```

**log with py-mccabe build error (w/o pytest-runner)**

```
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    'Topic :: Software Development :: Quality Assurance',
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-5vxw6f2k4hjdnk7fi6tulhtrasixblki/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 443, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
```

**log of pytest-runner build error**
```
No local packages or working download links found for setuptools_scm>=1.15.0
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    setuptools.setup(**params)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-5vxw6f2k4hjdnk7fi6tulhtrasixblki/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/dist.py", line 443, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/harrison37/Work/2017_09_conduit_spack_update/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-2jxxsgfojlrnbs52bshmraxsjbhzt275/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm>=1.15.0')

```

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #5420.

@cyrush: can you try this out and see whether it fixes your issue?

### CODE REVIEW

**Comment by cyrush** [comment]
Almost,` py-mccabe` builds -- but then` py-flake8` fails w/ the same error.

But I now understand why its hitting me. It's an https cert interception problem issue. 

`pytest-runner` isn't listed a spack dependency in `py-flake8`, but it is in its `setup.py.`

Since spack  doesn't install it, `distutils` tries to fetch from pypi, but i am behind a firewall that intercepts https. 

Even though I am running spack with `-k`, that doesn't help me get around the cert issue when `distutils` tries to fetch. 

Not sure if there is a similar patch for flake8, or if installing `pytest-runner` (and its rabbit hole of deps) via spack is a better solution. 

Here are the bread crumbs that let me to to understand the pypi / distutils issue>

```
==> Executing phase: 'build'
==> '/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-frcr4updt5dzrooqpunptcwhc6oh4rxd/bin/python2.7' 'setup.py' '--no-user-cfg' 'build'
Download error on https://pypi.python.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 129, in <module>
    setup_requires=['pytest-runner'],
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/python-2.7.14-frcr4updt5dzrooqpunptcwhc6oh4rxd/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/setuptools/dist.py", line 375, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/setuptools/dist.py", line 443, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/harrison37/Work/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/py-setuptools-35.0.2-mmcm675lflix3tetm3u66whp7lj2yco4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
```

**Comment by tgamblin** [comment]
@cyrush: try the version I just pushed.

**Comment by tgamblin** [comment]
@cyrush: this could probably be simplified by not even using the upstream patch and doing what I did with `flake8` for `mccabe`.

**Comment by cyrush** [comment]
@tgamblin, Thanks! Yes I can now build py-flake8.  

I agree not using the upstream patch seems a bit better (especially if there are potential issues with mirroring patches)

**Comment by tgamblin** [comment]
@cyrush: ok I pushed a version that does that.  If it works for you, we can merge this.

**Comment by cyrush** [comment]
yes, also works.

I pulled, executed:

`bin/spack uninstall --dependents py-mccabe `

and then re installed py-flake8.

Looked like it used new stages for everything, and flake8 worked after activating.

**Pull request merged**
