### PR TITLE
py-pytorch-lightning: add v1.9.3

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/Lightning-AI/lightning/releases/tag/1.9.3

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
