### PR TITLE
nest: Support 3.0 and 2.20.1 releases in Spack.

### PR DESCRIPTION
**Pull request by ikitayama**
Rewrite PR based upon #24326

### CODE REVIEW

**Comment by ikitayama** [comment]
Both built fine on JURECA, for the record.

**Comment by ikitayama** [comment]
@heplesser I'd like you to take over this as a co-maintainer as I believe this is, like EasyBuild, a suite flexible package manager for everyone, but it's up to you to limit support effort against only distros only.

**Review by alalazo — CHANGES_REQUESTED** [review]
This PR changes the `url` without changing the sha256, exactly as #24326 was doing. For instance:
```console
$ spack checksum nest 2.14.0
==> Found 1 version of nest:
  
  2.14.0  https://github.com/nest/nest-simulator/archive/refs/tags/v2.14.0.tar.gz

[ ... ]

    version('2.14.0', sha256='afaf7d53c2d5305fac1257759cc0ea6d62c3cebf7d5cc4a07d4739af4dbb9caf')
```
Why did you open a second PR for this additional sha?

**Comment by alalazo** [comment]
Duplicate of #24326

**Comment by ikitayama** [comment]
I'd like in the updated package.py, only 3.0 and 2.20.1 releases are supported.

**Comment by ikitayama** [comment]
As not, all the releases managed at the same `url` location

**Comment by ikitayama** [comment]
`git grep "url[ ]\+=[ ]\+" |grep github` gives some patterns, though can we use both the "archive" and "releases/download" forms?

**Comment by ikitayama** [comment]
JURECA is offline today their time; I'll come back tomorrow for discussion.

**Comment by ikitayama** [comment]
@alalazo could you merge this PR? Thanks!

**Comment by ikitayama** [comment]
Can someone review this PR and merge if it looks fine?

**Comment by ikitayama** [comment]
I think it's ready to go.

**Review by alalazo — APPROVED** [review]

**Comment by ikitayama** [comment]
Thanks @alalazo !

**Pull request merged**
