### PR TITLE
e4s: add vtk-m +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `vtk-m +rocm` to E4S stack

FYI @wspear @kmorel @vicentebolea

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.  Hopefully the package builds successfully.

**Review by tldahlgren — DISMISSED** [review]

**Comment by tldahlgren** [comment]
Looks like the package build fails.  See https://gitlab.spack.io/spack/spack/-/jobs/3028833.

**Comment by eugeneswalker** [comment]
> Looks like the package build fails. See https://gitlab.spack.io/spack/spack/-/jobs/3028833.

```
...
  >> 240    /tmp/root/spack-stage/spack-stage-vtk-m-1.8.0-rgf5uhrv3eksplpyp2jvv
            h2ienwhvvdx/spack-src/vtkm/cont/openmp/internal/FunctorsOpenMP.h:25
            :10: fatal error: 'omp.h' file not found
     241    #include <omp.h>
     242             ^~~~~~~
     243    1 error generated when compiling for gfx90a.
  >> 244    make[2]: *** [vtkm/cont/CMakeFiles/vtkm_cont.dir/build.make:678: vt
            km/cont/CMakeFiles/vtkm_cont.dir/ArrayRangeCompute.cxx.o] Error 1
...
```

**Comment by eugeneswalker** [comment]
Issue logged here:
* https://github.com/spack/spack/issues/32197

**Comment by eugeneswalker** [comment]
Amending this PR now to build `vtk-m ~openmp +rocm` until this issue is resolved:
* https://github.com/spack/spack/issues/32197
* See PR https://github.com/spack/spack/pull/32250

**Comment by eugeneswalker** [comment]
All checks green!

**Review by wspear — APPROVED** [review]
Looks good!

**Pull request merged**
