### PR TITLE
[WRF] Adding new versions

### PR DESCRIPTION
**Pull request by t-brown**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
I confirmed the sha256 for `4.4.2` and `4.4` BUT `spack checksum` is yielding different sha256 for all of the other listed versions.  Any idea why?

**Comment by tldahlgren** [comment]
> I confirmed the sha256 for `4.4.2` and `4.4` BUT `spack checksum` is yielding different sha256 for all of the other listed versions. Any idea why?

Heard GitHub reverted their hash algorithm change that caused these issues.

**Review by tldahlgren — APPROVED** [review]
Confirmed new (and re-confirmed existing) sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to give @MichaelLaufer and or @ptooley a chance to review.

**Comment by tldahlgren** [comment]
For future reference, we would appreciate PRs from branches (see https://spack.readthedocs.io/en/latest/contribution_guide.html#git-workflows).

**Review by MichaelLaufer — APPROVED** [review]
LGTM

**Pull request merged**
