### PR TITLE
sherpa: fix build of recola interface

### PR DESCRIPTION
**Pull request by vvolkl**
See https://gitlab.com/sherpa-team/sherpa/-/issues/356

Adding a new recola version as well, builds fine with the new patch.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
LGTM from a packaging perspective. Feel free to ping me for a merge when ready.

**Comment by wdconinc** [comment]
Confirmed that `sherpa +recola ^recola@2.2.3` and `sherpa +recola ^recola@2.2.4` both build fine on gcc@11.

**Review by wdconinc — DISMISSED** [review]

**Comment by tldahlgren** [comment]
@alalazo ping .. ready for merge

**Comment by vvolkl** [comment]
Actually, I still  took the opportunity to updated this to reflect this comment by the developers: https://gitlab.com/sherpa-team/sherpa/-/issues/356#note_909984021 while sherpa builds with recola2, they  have only validated and tested sherpa with recola1.

**Review by wdconinc — APPROVED** [review]
Builds fine with recola@1. Still, I wish there was something like this...
```
depends_on('recola')
depends_on('recola@1', preferred=True)
```

**Review by alalazo — APPROVED** [review]

**Pull request merged**
