### PR TITLE
py-gast: add 0.5.4

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://github.com/serge-sans-paille/gast/tree/0.5.4

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
This is not a problem of the pipeline, I can reproduce the error locally. It seems that `py-scipy` does not build when `py-gast` is updated (although it is only one patch level up). The error is
```
meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs
```
`py-gast` is not even a direct dependency of `py-scipy` but comes indirectly from `py-pythran`.

**Comment by manuelakuhn** [comment]
According to <https://github.com/scipy/scipy/issues/18390> the solution of the `py-pythran` maintainers is to restrict `py-gast <= 0.5.3`. Done that now as well.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
@rgommers FYI

**Pull request merged**
