### PR TITLE
foam-extend: add 4.1 (released Oct 2019)

### PR DESCRIPTION
**Pull request by simonflood**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by tldahlgren** [comment]
@olesenm Would you be interested, as a significant contributor to this package, in commenting on this PR?

**Comment by olesenm** [comment]
@simonflood - would make sense to also include version 5.0 too into the same commit, if things are being modified anyhow.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by simonflood** [comment]
@olesenm I wasn't quite sure whether 5.0 was released or still beta

**Comment by olesenm** [comment]
Looks official:
https://www.cfd-online.com/Forums/openfoam-news-announcements-other/245191-foam-extend-5-0-release.html

**Comment by hoehnp** [comment]
if @simonflood is not interested, I would be interested in maintaining the foam-extend package. Making it install successful again and including 5.0 is part of my next goals.

**Pull request merged**
