### PR TITLE
Avoid best-effort expansion of stacks

### LINKED ISSUE #40791: Best effort enforcement of constraints in matrices result in inconsistent environments
### Steps to reproduce

**TL;DR** The approach we adopted since we added stacks to soft-enforce constraints in matrices result in the highly inconsistent behavior below. I think we should get rid of it to:
1. Have a more consistent behavior in environments
2. Avoid having lockfiles where user specs that don't intersect map to the same concrete spec

## The good

If we try to concretize the following `spack.yaml`:
```yaml
spack:
  specs:
  - zlib +shrd
  - zlib ~shrd
  unify: false
  view: false
```
we get the following error:
```console
$ spack concretize
==> Starting concretization pool with 2 processes
==> Error: trying to set variant "shrd" in package "zlib", but the package has no such variant [happened during concretization of zlib+shrd]
```
which seems sensible: `zlib` has in fact no variant `shrd`.

## The bad

If we apply this transformation, which should be equivalent:
```yaml
spack:
  specs:
  - matrix:
    - [zlib]
    - [+shrd, ~shrd]
  unify: false
  view: false
```
we get instead:
```console
$ spack concretize -f
==> Starting concretization pool with 2 processes
==> Environment concretized in 3.04 seconds
==> Concretized zlib+shrd
 -   ctm7p7o  zlib@1.3%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake
 -   3wudxnw      ^gmake@4.4.1%gcc@9.4.0~guile build_system=generic arch=linux-ubuntu20.04-icelake

==> Concretized zlib~shrd
 -   ctm7p7o  zlib@1.3%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake
 -   3wudxnw      ^gmake@4.4.1%gcc@9.4.0~guile build_system=generic arch=linux-ubuntu20.04-icelake
```
This is utterly confusing: the two specs result in the same concrete spec. The lockfile starts with:
```json
"roots": [
    {
      "hash": "ctm7p7opscnjqbtptefifmthqm74x2gf",
      "spec": "zlib+shrd"
    },
    {
      "hash": "ctm7p7opscnjqbtptefifmthqm74x2gf",
      "spec": "zlib~shrd"
    }
  ],
```
so we effectively map two incompatible user specs to the same concrete spec that **does not** contain a required variant.

## The ugly

Since the concrete spec is the same, one would expect the same behavior for:
```yaml
spack:
  specs:
  - matrix:
    - [zlib]
    - [+shrd, ~shrd]
  unify: true
  view: false
```
but this one instead fails with:
```console
$ spack concretize -f
==> Error: trying to set variant "shrd" in package "zlib", but the package has no such variant [happened during concretization of zlib~shrd]
```

### Error message

See cases above. I think that:
1. All three cases should error consistently
2. We should enforce the requirement in a strict way, and avoid special casing `unify:false` + matrices

### Information on your system

* **Spack:** 0.21.0.dev0 (3e517781fa4449e9b2c1ece80aa09d82f335d5c2)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes #40791

Currently, stacks behave differently if used in unify:false environments, which leads to inconsistencies during concretization. 

For instance, we might have two abstract user specs that do not intersect with each other map to the same concrete spec in the environment. This is clearly wrong.

This PR removes the best effort expansion, so that user specs are always applied strictly.

### CODE REVIEW

**Comment by tgamblin** [comment]
I don't think we should remove best-effort expansion, because people are actually using it.  If I look at the original issue, it seems like to me that the env should emit a warning (or maybe an error? I don't really care) if a variant couldn't apply to *any* spec in the matrix, but I wouldn't remove best-effort expansion.

That said, I agree that the current way we handle this is somewhat inconsistent.  In particular I think we *could* adopt the change in this PR if we still had a way to do best-effort. Something like:

```yaml
spack:
    specs:
    - zstd
    - prefer: +shrd
```

Where `prefer:` indicates it should be best-effort.  This would be consistent with introducing a `prefer:` syntax that is symmetric with `require:`, and we could just say the default for matrices is `require:`.  Until we have that, though, I think we should keep allowing best-effort, because not having it makes variants in matrices much less useful.

**Comment by alalazo** [comment]
> I don't think we should remove best-effort expansion, because people are actually using it. If I look at the original issue, it seems like to me that the env should emit a warning (or maybe an error? I don't really care) if a variant couldn't apply to any spec in the matrix, but I wouldn't remove best-effort expansion.

For what is worth, best-effort expansion is only used with `unify:false`. Both `unify:when_possible` and `unify:true` will not use it. It can result in abstract user specs that do not intersect being mapped to the same concrete spec. This is logically a big inconsistency imo.

**Comment by alalazo** [comment]
> If I look at the original issue, it seems like to me that the env should emit a warning (or maybe an error? I don't really care) if a variant couldn't apply to any spec in the matrix, but I wouldn't remove best-effort expansion.

There are a couple of things I want to note. The behavior is not only inconsistent across different unification modes, it's just wrong, and the issue is not only about variants but about _everything_:
```yaml
spack:
  specs:
  - matrix:
    - [zlib]
    - ["^trilinos", "~shrd"]
  concretizer:
    unify: false
  view: false
```
Here we concretize a `zlib` that depends on `trilinos`, except it does not:
Screenshot from 2023-12-06 10-08-12

The corresponding lockfile is:

<details><summary>spack.lock</summary>
<p>

```json
{
  "_meta": {
    "file-type": "spack-lockfile",
    "lockfile-version": 5,
    "specfile-version": 4
  },
  "spack": {
    "version": "0.22.0.dev0",
    "type": "git",
    "commit": "84999b699682f8505908e7c5f7e767f9d3be6c79"
  },
  "roots": [
    {
      "hash": "qnzaxw3i5na6hu4fr23buxys7ht74w2v",
      "spec": "zlib ^trilinos"
    },
    {
      "hash": "qnzaxw3i5na6hu4fr23buxys7ht74w2v",
      "spec": "zlib~shrd"
    }
  ],
  "concrete_specs": {
    "qnzaxw3i5na6hu4fr23buxys7ht74w2v": {
      "name": "zlib",
      "version": "1.3",
      "arch": {
        "platform": "linux",
        "platform_os": "ubuntu20.04",
        "target": {
          "name": "icelake",
          "vendor": "GenuineIntel",
          "features": [
            "adx",
            "aes",
            "avx",
            "avx2",
            "avx512_bitalg",
            "avx512_vbmi2",
            "avx512_vnni",
            "avx512_vpopcntdq",
            "avx512bw",
            "avx512cd",
            "avx512dq",
            "avx512f",
            "avx512ifma",
            "avx512vbmi",
            "avx512vl",
            "bmi1",
            "bmi2",
            "clflushopt",
            "clwb",
            "f16c",
            "fma",
            "gfni",
            "mmx",
            "movbe",
            "pclmulqdq",
            "popcnt",
            "rdpid",
            "rdrand",
            "rdseed",
            "sha_ni",
            "sse",
            "sse2",
            "sse4_1",
            "sse4_2",
            "ssse3",
            "vaes",
            "vpclmulqdq",
            "xsavec",
            "xsaveopt"
          ],
          "generation": 0,
          "parents": [
            "cascadelake",
            "cannonlake"
          ]
        }
      },
      "compiler": {
        "name": "gcc",
        "version": "9.4.0"
      },
      "namespace": "builtin",
      "parameters": {
        "build_system": "makefile",
        "optimize": true,
        "pic": true,
        "shared": true,
        "cflags": [],
        "cppflags": [],
        "cxxflags": [],
        "fflags": [],
        "ldflags": [],
        "ldlibs": []
      },
      "package_hash": "u7vqvwmacj5j7zngg2evhytlxmzhad35mxlxna6tmr4bjyeisgsa====",
      "dependencies": [
        {
          "name": "gmake",
          "hash": "li5apiwbiexfsusfyv73rualbl6q35wt",
          "parameters": {
            "deptypes": [
              "build"
            ],
            "virtuals": []
          }
        }
      ],
      "hash": "qnzaxw3i5na6hu4fr23buxys7ht74w2v"
    },
    "li5apiwbiexfsusfyv73rualbl6q35wt": {
      "name": "gmake",
      "version": "4.4.1",
      "arch": {
        "platform": "linux",
        "platform_os": "ubuntu20.04",
        "target": {
          "name": "icelake",
          "vendor": "GenuineIntel",
          "features": [
            "adx",
            "aes",
            "avx",
            "avx2",
            "avx512_bitalg",
            "avx512_vbmi2",
            "avx512_vnni",
            "avx512_vpopcntdq",
            "avx512bw",
            "avx512cd",
            "avx512dq",
            "avx512f",
            "avx512ifma",
            "avx512vbmi",
            "avx512vl",
            "bmi1",
            "bmi2",
            "clflushopt",
            "clwb",
            "f16c",
            "fma",
            "gfni",
            "mmx",
            "movbe",
            "pclmulqdq",
            "popcnt",
            "rdpid",
            "rdrand",
            "rdseed",
            "sha_ni",
            "sse",
            "sse2",
            "sse4_1",
            "sse4_2",
            "ssse3",
            "vaes",
            "vpclmulqdq",
            "xsavec",
            "xsaveopt"
          ],
          "generation": 0,
          "parents": [
            "cascadelake",
            "cannonlake"
          ]
        }
      },
      "compiler": {
        "name": "gcc",
        "version": "9.4.0"
      },
      "namespace": "builtin",
      "parameters": {
        "build_system": "generic",
        "guile": false,
        "cflags": [],
        "cppflags": [],
        "cxxflags": [],
        "fflags": [],
        "ldflags": [],
        "ldlibs": []
      },
      "package_hash": "ghstvqlc3r7kgiikwx24xhcxdxcqdk5viinrzgm2mssqigfonika====",
      "hash": "li5apiwbiexfsusfyv73rualbl6q35wt"
    }
  }
}

```

</p>
</details> 

Neither of the roots satisfies the concrete spec they point to, which is in my opinion a severe breakage of the invariants that are supposed to hold for concretization.

**Comment by alalazo** [comment]
@tgamblin We have a `prefer:` semantic in `packages.yaml` since #41832 Is there anything else needed to consider merging this fix? The issue described in https://github.com/spack/spack/pull/40792#issuecomment-1842497483 is pretty bad imo.

**Comment by alalazo** [comment]
Ping @tgamblin

**Comment by alalazo** [comment]
@tgamblin

**Comment by alalazo** [comment]
Since #45215 it doesn't make much sense to keep best-effort expansion. It was never supported by the new concretizer.

**Review by haampie — APPROVED** [review]

**Pull request merged**
