### PR TITLE
Add new package: alsa-firmware

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Comment by michaelkuhn** [comment]
Does it make sense to have firmware in Spack? It usually needs to be installed system-wide to be usable, right?

**Comment by adamjstewart** [comment]
We also have packages for things like CUDA and OpenGL. I'm not opposed to adding packages for firmware if something depends on it. Users can always add it as an external package. @darmac does the package actually build?

**Comment by darmac** [comment]
Yes, some souce code will be build in this package, e.g.
```
make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-alsa-firmware-1.2.1-ukrykkajmc7szebxblljzce6lazhr434/spack-src/hdsploader'
/home/xiaojun/spack/lib/spack/env/gcc/gcc -DPACKAGE_NAME=\"alsa-firmware\" -DPACKAGE_TARNAME=\"alsa-firmware\" -DPACKAGE_VERSION=\"1.2.1\" -DPACKAGE_STRING=\"alsa-firmware\ 1.2.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DPACKAGE=\"alsa-firmware\" -DVERSION=\"1.2.1\" -I.     -g -O2 -MT tobin.o -MD -MP -MF .deps/tobin.Tpo -c -o tobin.o tobin.c
mv -f .deps/tobin.Tpo .deps/tobin.Po
/home/xiaojun/spack/lib/spack/env/gcc/gcc  -g -O2   -o tobin tobin.o
```

But I think it's OK to close this PR.

**Comment by alalazo** [comment]
@darmac Closing this PR per your latest comment. Feel free to reopen if you have a second thought.

**Pull request closed without merging**
