### PR TITLE
likwid: remote root from INSTALL_CHOWN

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Want to kick off Travis again? Looks like it timed out for some reason.

**Comment by davydden** [comment]
@adamjstewart how do i do that?

**Comment by adamjstewart** [comment]
You can force push a rebase, close and reopen the job, or on the travis page you should be able to restart the build, or even a single job with the refresh button on the top left.

**Comment by davydden** [comment]
@tgamblin ping.

**Pull request merged**
