### PR TITLE
[WIP]: Diffs for efischer/develop

### PR DESCRIPTION
**Pull request by citibeth**
Ignore...

### CODE REVIEW

**Comment by tgamblin** [comment]
@citibeth: You know you can keep pushing to the same PR right?  If you update the branch the changes should show up (even if you force push).  So you shouldn't have to resubmit.

**Comment by citibeth** [comment]
Todd,

Thanks, I do know that.  Problem is, I pushed a bad commit to
efischer/develop.  I fixed it by deleting and re-creating the branch :(.
Then I had to create a new PR.

-- Elizabeth

**Comment by tgamblin** [comment]
Would this work?

```bash
$ git reset --hard HEAD^
$ git push -f origin HEAD
```

**Comment by citibeth** [comment]
No, because I'd already pushed it to GitHub :(

**Comment by tgamblin** [comment]
That's what `-f` (`--force`) is for.  It'll overwrite the previous state on github (and it can lose history).  You generally do not want to force push public branches like `develop` or `master`, but for a feature branch that's just for you, or for a pull request you're iterating on, it can be nice.  See [this article](http://blog.adamspiers.org/2015/03/24/why-and-how-to-correctly-amend-github-pull-requests/) to avoid [this](https://xkcd.com/1597/) :smile:.

**Pull request closed without merging**
