### PR TITLE
update chapel package for v2.1

### PR DESCRIPTION
**Pull request by arezaii**
Updates the Chapel package for the version 2.1 release.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Are there any changes needed for the newer version akin to the existing python version conflict for `@:2.1.0`, the `llvm` dependency, or the `gasnet` dependency?

**Comment by bradcray** [comment]
@tldahlgren : Thanks for the quick review!  I'm afraid @arezaii had to step away for ~50 minutes and that I don't know the answers to your questions offhand.  He should be back in ~45 minutes.

**Comment by arezaii** [comment]
Thanks for taking this on @tldahlgren! 

There aren't any dependency versions or conflicts to change for this version bump.

**Comment by bradcray** [comment]
Thanks, @tldahlgren!

**Pull request merged**
