### PR TITLE
Adds nvhpc 24.1

### PR DESCRIPTION
**Pull request by Julius-Plehn**

### CODE REVIEW

**Comment by Try2Code** [comment]
go @Julius-Plehn !!

**Comment by samcmill** [comment]
@jmuddnv

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256 on my machine.  Will wait to give @samcmill time to comment/approve.

**Comment by jmuddnv** [comment]
I also verified the sha256 checksums.
It looks OK to me.

**Review by samcmill — APPROVED** [review]

**Pull request merged**
