### PR TITLE
Added version 1.49.2 to gobject-introspection

### PR DESCRIPTION
**Pull request by healther**

### CODE REVIEW

**Comment by healther** [comment]
I'm not sure what you are looking for:
1.49.2 does not build against glib@2.48.1, therefore a newer glib was used. It is not a clean cut, i.e. older versions than 2.49.2 may work, but it is one working solution.

**Comment by citibeth** [comment]
> 1.49.2 does not build against glib@2.48.1, therefore a newer glib was used. It is not a clean cut, i.e. older versions than 2.49.2 may work, but it is one working solution.

Great!  Can you add that to `package.py` as a comment?  Remember that others who have no idea what you're doing might monkey with your package.  The more documentation you can provide in the package for what you're doing, the better chances they have of surviving others' edits.

**Comment by healther** [comment]
Maybe I'm missing something but:

>      # version 1.48.0 build fails with glib 2.49.4

is already there, I can add a comment regarding it only being a working solution and not necessarily the working solution, but I don't think that helps all too much

**Comment by citibeth** [comment]
Ok then all is ok

**Pull request merged**
