### PR TITLE
py-iterative-stats: Change maintainer, add new version

### PR DESCRIPTION
**Pull request by mschouler**

### CODE REVIEW

**Comment by mschouler** [comment]
> @Frobinou can you review this PR?
> 
> This PR modifies the following package(s), for which you are listed as a maintainer:
> 
>     * py-iterative-stats

For the record, @Frobinou won't be following this project anymore which is why @robcaulk was declared as maintainer.

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new sha256.

**Comment by tldahlgren** [comment]
@frobinou @robcaulk Are you okay with the maintainer changes in this PR?

**Review by adamjstewart — DISMISSED** [review]
Changes look fine, will give the old and new maintainers a chance to respond just to confirm the change.

We don't normally deprecate and remove older versions unless there is some issue (security vulnerability) or maintenance burden (package becomes too complicated). Are you sure you want to deprecate the older version?

**Review by robcaulk — APPROVED** [review]
LGTM

**Comment by mschouler** [comment]
> Changes look fine, will give the old and new maintainers a chance to respond just to confirm the change.
> 
> We don't normally deprecate and remove older versions unless there is some issue (security vulnerability) or maintenance burden (package becomes too complicated). Are you sure you want to deprecate the older version?

Thank you for your review.

Regarding the deprecation, I see your point so I left it as it initially was.

**Comment by Frobinou** [comment]
> @Frobinou @robcaulk Are you okay with the maintainer changes in this PR?
I'm agree with that!

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
