### PR TITLE
fix oneapi compilers runtime environment for classic compilers

### PR DESCRIPTION
**Pull request by rscohn2**
Address #21698 

@glennpj: please let me know if this works

if you do: `spack load intel-oneapi-compilers`

It will put icc on your path, and configure so you can find man pages and compiler can find icc static libraries

### CODE REVIEW

**Comment by rscohn2** [comment]
@frankwillmore @scheibelp Please review

**Comment by frankwillmore** [comment]
These changes look fine. Noting that this touches on a greater issue, which I've documented here:

https://github.com/spack/spack/issues/21704

**Comment by glennpj** [comment]
That is better but still does not catch everything that sourcing that script would set. Here is what would be set on my system:
```
setenv("ACL_BOARD_VENDOR_PATH","/opt/Intel/OpenCLFPGA/oneAPI/Boards")
prepend_path("CPATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/include")
setenv("INTELFPGAOCLSDKROOT","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/oclfpga")
prepend_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/oclfpga/host/linux64/lib")
prepend_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/emu")
prepend_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/x64")
prepend_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib")
append_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/expat-2.2.10-nbkrhn74dg2l7d72mucazjerwhryrin5/lib")
append_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/libbsd-0.10.0-b2bfuf3bkhxdcthi4tclgwzki274skm3/lib")
append_path("LD_LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/bzip2-1.0.8-fd4makldi4brmfgno42janitlitewtpt/lib")
prepend_path("LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib")
prepend_path("LIBRARY_PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/compiler/lib/intel64_lin")
append_path("MANPATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/documentation/en/man/common")
setenv("OCL_ICD_FILENAMES","libintelocl_emu.so:libalteracl.so:/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/x64/libintelocl.so")
prepend_path("PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/bin")
prepend_path("PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/bin/intel64")
prepend_path("PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/oclfpga/bin")
prepend_path("PATH","/opt/packages/gpjohnsn/spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/intel-oneapi-compilers-2021.1.0-h2lddoim6zpxmjan6vbn2ednbdarmhgo/compiler/2021.1.1/linux/lib/oclfpga/llvm/aocl-bin")
```

**Comment by rscohn2** [comment]
I left out all the FPGA related configuration. It would be difficult to test, I don't think anyone will use it, and there is an unresolved issue where it overrides the libz on your system.

**Comment by glennpj** [comment]
> I left out all the FPGA related configuration. It would be difficult to test, I don't think anyone will use it, and there is an unresolved issue where it overrides the libz on your system.

We have people at our site who are interested in FPGA and would want to test this at some point. The libz issue is a problem, although, in theory, the spack built libz should be RPATH'd into the binary.

**Comment by rscohn2** [comment]
I will add the FPGA directories and test the emulator. Please let me know if you find that it doesn't work.

**Comment by rscohn2** [comment]
I am finding that installing compilers from hpckit doesn't have all the bits for FPGA. I am going to try the compiler standalone.  It might mean that we should have separate spack packages for c & fortran, instead of an intel compilers package.

**Comment by rscohn2** [comment]
@scheibelp Another possibility is a single compilers package that requires 2 downloads. Can you remind me of the best way to have a 2nd download? Maybe some package as an example?

**Comment by scheibelp** [comment]
> Can you remind me of the best way to have a 2nd download? Maybe some package as an example?

Right now the easiest multi-download case supported by Spack is to add a `resource`: Spack assumes that this resource is supposed to be added to the main download directory before the installation. I think the idea here is that you want to download two of these installers and have them install to the same prefix? I think resources could be used for that (although that wasn't their initial intent).

Examples of packages using resources are `lua` and `trilinos`. I think you can use `placement='foo'` to ensure that the unpacked-and-downloaded resource is placed in a directory called `foo` inside of the CWD for the `install` method (you may have to experiment with that though).

**Comment by glennpj** [comment]
> I am finding that installing compilers from hpckit doesn't have all the bits for FPGA.

I _think_ the FPGA add-on kit is needed, which is actually an optional component in the Base Toolkit, which the HPC Toolkit depends on. It also looks like there are several options for different FPGA hardware when downloading the FPGA toolkit. The FPGA packages are probably going to have to be left out for now.

**Comment by rscohn2** [comment]
Problem was solved in another PR

**Pull request closed without merging**
