### PR TITLE
parallel-netcdf: add v1.13.0, mark conflict on macOS

### PR DESCRIPTION
**Pull request by adamjstewart**
Can't get this to build on macOS with Xcode 16, and possibly with Xcode 15. Opened an issue upstream. Let's add a conflict for now.

### CODE REVIEW

**Comment by skosukhin** [comment]
#45919

**Comment by adamjstewart** [comment]
@Chrismarsh 

May be superseded by #46264, but we should merge one of these 2 PRs soon.

**Comment by Chrismarsh** [comment]
In my testing, @tgamblin's integration of my 'cc' PR here https://github.com/spack/spack/pull/46598 lets me build parallel-netcdf without issue. I think getting https://github.com/spack/spack/pull/46598 merged is the priority as my PR needs to be rebased on all the new cc changes anyway.

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by Chrismarsh** [comment]
I'll admit I don't love this being conflicted as it immediately breaks much of the macOS workflow. Is 46598 not close to being merged?

**Comment by tldahlgren** [comment]
> I'll admit I don't love this being conflicted as it immediately breaks much of the macOS workflow. Is 46598 not close to being merged?

@tgamblin Thoughts regarding @46598 status?

**Comment by skosukhin** [comment]
To be clear, the conflict must be removed. I have no problem building the package on macOS because there are no extra rpaths in my compiler configuration file.

**Comment by adamjstewart** [comment]
Closing in favor of the other PR.

**Pull request closed without merging**
