### PR TITLE
Make zstd a multi-buildsystem package

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by haampie** [comment]
Thank you, this can be useful! The reason to have a makefile was because zstd is also a dependency of cmake~ownlibs, but now the concretizer can actually choose `cmake~ownlibs ^zstd buildsystem=makefile` vs `something ^zstd buildsystem=cmake ^cmake+ownlibs`  :upside_down_face:

**Comment by iarspider** [comment]
@haampie  Should I open a PR to update `py-python-multipart`? The `develop` version is compatible with python 3.7+.

**Comment by haampie** [comment]
It was something that slipped through CI... reverted it and merged develop into your branch

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@spackbot run pipeline

**Pull request closed without merging**
