### PR TITLE
py-m2r: constrain py-mistune to version 0.8.1

### PR DESCRIPTION
**Pull request by glennpj**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Where do these version requirements come from?

**Comment by glennpj** [comment]
> Where do these version requirements come from?

The build fails with newer `mistune`.
```
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```
https://github.com/miyakogi/m2r/issues/66

**Comment by adamjstewart** [comment]
That explains the upper bound, but where does the lower bound come from?

**Comment by glennpj** [comment]
Right, I think there are three reasons.

1. That is consistent with how the dependency was handled in `py-nbconvert`, which has the same issue.
2. As I was looking through bug reports the consensus seemed to be to use >=0.8.
3. Since this is "out of spec" relative to the official listing, it seemed reasonable to use the latest version known to work.

I gave a little more weight to being consistent with `py-nbconvert`, and so went with 0.8.1. I suppose older versions could work and I can test them is you think that is necessary.

**Comment by adamjstewart** [comment]
I just built `py-m2r` with `py-mistune@0.5` and it passed its import tests at least. I would remove the lower bound unless we know for sure that it doesn't work for older `py-mistune`.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
