### PR TITLE
Add the ability to limit the number of versions checksummed.

### PR DESCRIPTION
**Pull request by greenc-FNAL**
* New command option `spack create --limit #`.

* Corresponding functionality in
  `spack.stage.get_checksums_for_versions()`.

### CODE REVIEW

**Comment by adamjstewart** [comment]
`spack checksum` and `spack create` should already ask you how many versions you would like to checksum. Are you looking for a command line flag to control this to make scripting easier?

**Comment by greenc-FNAL** [comment]
Exactly. I'm working on a script to generate trees of Perl packages with dependencies, _etc._ Some Perl packages have dozens of extant versions.

**Comment by adamjstewart** [comment]
We'll probably also want to add this feature for `spack checksum`. Need to add tests too.

**Comment by greenc-FNAL** [comment]
> We'll probably also want to add this feature for `spack checksum`. Need to add tests too.

Happy to. Didn't see a test to add to, though. Did I miss it, or do I need to test the whole of `spack.stage.get_checksums_for_versions()`?

**Comment by adamjstewart** [comment]
You can add tests to `lib/spack/spack/test/cmd/(checksum|create).py`

**Comment by alalazo** [comment]
Superseded by the prompt we have now for:
```
$ spack checksum zlib-ng
==> Selected 11 versions. 5 new versions
  2.2.2  https://github.com/zlib-ng/zlib-ng/archive/2.2.2.tar.gz
  2.2.1  https://github.com/zlib-ng/zlib-ng/archive/2.2.1.tar.gz
  2.2.0  https://github.com/zlib-ng/zlib-ng/archive/2.2.0.tar.gz
  2.1.8  https://github.com/zlib-ng/zlib-ng/archive/2.1.8.tar.gz
  2.1.7  https://github.com/zlib-ng/zlib-ng/archive/2.1.7.tar.gz
  2.1.6  https://github.com/zlib-ng/zlib-ng/archive/2.1.6.tar.gz
  2.1.5  https://github.com/zlib-ng/zlib-ng/archive/2.1.5.tar.gz
  2.1.4  https://github.com/zlib-ng/zlib-ng/archive/2.1.4.tar.gz
  2.1.3  https://github.com/zlib-ng/zlib-ng/archive/2.1.3.tar.gz
  ...
  2.0.0  https://github.com/zlib-ng/zlib-ng/archive/2.0.0.tar.gz

==> Enter number of versions to take, or use a command:
    [c]hecksum  [e]dit  [f]ilter  [a]sk each  [n]ew only  [r]estart  [q]uit

```

**Comment by alalazo** [comment]
@greenc-FNAL Let me know if you disagree. Feel free to ping me for a review in case you submit a new one.

**Pull request closed without merging**
