### PR TITLE
netcdf: Turn off DAP support by deafult.

### PR DESCRIPTION
**Pull request by citibeth**
Removes another unnecessary dependency not needed by 95% of users.  DAP support requires `curl`, for which there are currently circular dependency issues.

### CODE REVIEW

**Comment by glennpj** [comment]
You would have to specify `--disable-dap` when `~dap` to prevent dap support being built when a suitable system curl is present.

**Comment by citibeth** [comment]
Thanks, look like this needs a little more work cleaning it up.

**Comment by aprokop** [comment]
I think a similar thing should be done to `cdmremote` as it also depends on `curl` I believe.

**Comment by alalazo** [comment]
Is this superseeded by #2377 ?

**Comment by aprokop** [comment]
@alalazo It may be unless @citibeth has more improvements coming

**Comment by citibeth** [comment]
I agree, I'm happy to let this come to fruition through #2377

**Pull request closed without merging**
