### PR TITLE
Add ilp64 variant of OpenBLAS

### PR DESCRIPTION
**Pull request by eschnett**
Standard BLAS routines expect 32-bit integers, which is insufficient on some modern 64-bit systems with large amounts of memory. This variant builds a 64-bit version of OpenBLAS as well, which expects 64-bit integers (and adds a suffix "64_" to function names).

This variant requires a tool "objconv" that is also packaged.

### CODE REVIEW

**Comment by nrichart** [comment]
@eschnett why do you prefix the symbols, you could have an install of `openblas~lp64` in one folder and one `openblas+lp64` in a different folder with the same symbols. I guess the you are not linking your code with both interfaces. I asked this since I don't know how standard it is to have blas calls prefixed with `64_`. In the case of `mkl` they have the same symbols names but in 2 different files `libmkl_*_lp64` and `libmkl_*_ilp64`

**Comment by eschnett** [comment]
@nrichart The APIs are incompatible; without a suffix, the linker will not report an error, but the code would segfault at run time. In C++, name mangling would avoid this, but this is a Fortran 77 / C-style interface where one needs to explicitly rename functions if the API changes.

You can compare this to the `fseek` and `fseek64` functions, where switching to 64-bit integers to denote a position in a file required renaming the function.

Or you can compare to FFTW; there are variants for both single and double precision, and it's rolled into the same library.

It is also conceivable that the same code calls both the 32-bit and 64-bit interfaces. A single code probably wouldn't, but libraries depend on each other, and it should be fine if two independently developed libraries both call BLAS (but in different ways), and both libraries are used by the same application.

**Comment by nrichart** [comment]
Thank you for the explanation but, I think I understand why you need to split in different libraries or to change the symbol names.
My question was why did you choose to prefix the names with a prefix that I think is not standard instead of building a library with only one version and let spack handle the install directories at different locations.

What make me say that it is not standard is that the only blas I used up to now proposing the ilp64 interface are the netlib compiled with -i8, so no prefix and the mkl that have two libraries with the same symbol names.

**Comment by eschnett** [comment]
I am interested in OpenBLAS since the language Julia uses it. Julia uses the 64-bit version, and already uses the `64_` suffix. Today I learned that Fedora adopted this convention as well, and is shipping a version of OpenBLAS with this suffix that is used by their Julia package. So it's not a widely used standard yet, but it's not just my idea either.

I don't quite understand what you said. There are two name changes -- the symbol names, and the library names.

Regarding the symbol names: In Julia, we used to keep library name and symbol names the same when switching to 64-bit integers. The result were segfaults and crashes that were difficult to diagnose for the end user, since the linker cannot distinguish between the different conventions. I think you are trying to say that you understand this, and approve.

Regarding the library names: I want to be able to use the 32-bit and the 64-bit versions at the same time, in the same application. There is no technical reason why this doesn't work, so giving the 32-bit and the 64-bit libraries the same names "artificially" makes it impossible to use them simultaneously.

This is akin to handling the single precision and the double precision FFTW versions: You could say that an application will either use single or double precision, and should choose at install time. However, there is no reason to do so, and hence Spack can install FFTW with both single precision and double precision available simultaneously.

**Comment by nrichart** [comment]
My worries in the solution where you prefix the symbols is that you have to adapt the code. And there are lots of codes that are either fortran which mean that it should be doable to change the precision or the size of integers with just compilation options, or code that have a simple typedef or macro to define the real type and integer type. In this cases without the prefix you can "easily" link with a ilp64 blas.

And the other worry I have is that it is harder to prefix other blas libraries. So in the idea of having a common interface to switch one blas to another become more complicated, with a directive like `provides('blas + ilp64')` (I'm not sure it is doable yet)
This would allow for example to have the `julia` package to have a `depends_on('blas + ilp64')` instead of `depends_on('openblas + ilp64')`.

But ok perhaps I'm dragging this discussion to far for a PR comment.

**Comment by eschnett** [comment]
@nrichart "Using 64-bit integers" corresponds to the following in C: To change a function like
```C
void dostuff(int *status);
```
to
```C
void dostuff(long long *status);
```
Clearly, if you compile the code with one of the prototypes (e.g. because you're using K&R C) and then link against the other version, the code will crash. The same is the case in Fortran 77 if there's a mismatch between integer*4 and integer*8. In the absence of name mangling (as is available in C++), the linker will not detect the mismatch, and the user will not even receive a warning.

C89 and Fortran 90 introduce prototypes and interfaces/modules, respectively, to remedy the situation. This means that the compiler will refuse to compile the code. This is the kind of safety one wants.

To be able to make the change described above, the usual mechanism (in C) is to define a new function with a different name, e.g. `dostuff64`. In Fortran, one would then define an interface (my syntax may be wrong):
```Fortran
interface dostuff
   subroutine dostuff(status)
      integer*4 status
   end
   subroutine dostuff64(status)
      integer*8 status
   end
end
```
This allows the user to call a subroutine `dostuff`, and the compiler will automatically select the right version, based on the argument types used.

What you suggest instead -- making it easy to change the integer size for Fortran 77 programs, without using any Fortran 90 features, and foregoing type safety -- looks tempting at first, but our experience in Julia was that this really does lead to crashes, and people really have difficulties finding out what causes them.

Mind that many programs will employ BLAS/LAPACK in the background, and people are not always aware of all the details. A typical example is a Python programmer, who uses a particular Python module, which happens to use PETSc, which uses BLAS -- tracking down that (a) there is such a thing as a distinction between 32-bit and 64-bit versions of BLAS, and keeping track of which module and library expect which of the two, and manually (!) ensuring that all the build and install flags are consistent, is a large burden (no compiler nor linker warnings).

Thus I favour a solution where the linker reports an error if there is a mismatch, and where 32-bit and 64-bit versions can easily be used together (as they don't conflict). The "disadvantage" is that one has to use interfaces in Fortran (or manually change the code, but that's often too inconvenient), but as interfaces have been around for 25 years I'm happy to accept that.

**Comment by eschnett** [comment]
Ping?

**Comment by davydden** [comment]
As a proposition to debug this idea, @eschnett could you try compiling `petsc` and `trilinos` with `64` bit and the modified `openblas` to check if there are any pitfalls with this approach? For `petsc` it is `--with-64-bit-indices`, i could not find how to do it with `trilinos` though. Another option is to try `mumps`.

**Comment by eschnett** [comment]
Since the 32-bit and 64-bit interfaces are incompatible, it seems to me that switching between them via a variant isn't a good idea. Otherwise, any package that uses `blas` must be changed to explicitly choose `blas ~int64`.

- If we don't change the function names, then the packages should have different names, such as `blas` and `blas64`.
- If we do change the function names, then a `+int64` variant should install the 64-bit interface in addition to the original 32-bit interface.

How does a new virtual `blas64` package sound?

**Comment by davydden** [comment]
if there are different virtual packages for `blas`, what happens when
```
    A->B->blas64
      \
        \ -> C -> blas
```
? Probably nothing good as it will still build but one may expect run-time hard-to-debug errors.

Then if you add on top `threaded` and `no-threaded` option, then one would probably need 4 different virtual packages.

I agree that theoretically there is no need to limit the user to either 64bit integers or 32bit, but in the whole infrastructure of spack i would say the safest bet is to have a single `blas` used in the whole DAG, be it 32 or 64, threaded or non-treaded.

And then at some point inside `def setup_dependent_package(self, module, dspec):` (see https://github.com/LLNL/spack/pull/657#issuecomment-202125009),  one could give back the correct library (64bit or 32bit). 

If you also consider MKL single dynamic library, it is also restricted to choose 32/64 or threaded/serial using environment

> Using the Single Dynamic Library
You can simplify your link line through the use of the Intel MKL Single Dynamic Library (SDL). To use SDL, place libmkl_rt.so on your link line. For example:
icс application.c -lmkl_rt
SDL enables you to select the interface and threading library for Intel MKL at run time. By default, linking with SDL provides:
• Intel LP64 interface on systems based on the Intel® 64 architecture
• Intel interface on systems based on the IA-32 architecture
• Intel threading

something along the lines:

> mkl_set_interface_layer(MKL_INTERFACE_LP64)
mkl_set_threading_layer(MKL_THREADING_SEQUENTIAL);

**Comment by davydden** [comment]
FYI https://software.intel.com/en-us/articles/a-new-linking-model-single-dynamic-library-mkl_rt-since-intel-mkl-103

**Comment by eschnett** [comment]
@davydden In the case you describe above, everything will be fine if the 32-bit and 64-bit libraries use different symbol names. For example, there might be `dgemm` and ` dgemm64` routines. It doesn't matter which library provides what, or how this is mapped onto the metal via variants etc. This is exactly the reason why I strongly favour this approach (using different symbol names).

There's an alternative suggestion of using the same symbol names for convenience; in this case, one needs to remember e.g. which Fortran compiler options one used (e.g. using `-i8` to switch to 64-bit integers). This easily leads to crashes. In fact, the Julia language tried this approach, but it was just too difficult to keep track of all dependencies and their requirements, and if there's a long chain of dependencies pulling in Python and matplotlib and numpy, then suddenly there's a mismatch and a crash.

It's very difficult to enforce using a single BLAS in the whole Spack stack. For example, there just might be a package that auto-detects BLAS and uses it if available -- it's impossible for Spack to prevent that. Also, the 64-bit interface is non-standard, and most packages won't be able to use it.

Remember also that this is a C / Fortran interface, and the number of bits in an integer is not mangled into the symbol names.

So, if we make a 64-bit BLAS interface available, it should be
- backward compatible
- not clashing with other package that use a 32-bit interface
- an opt-in mechanism for some packages

The status quo is that Spack simply doesn't support a 64-bit BLAS, forcing all packages that want to use it to build it themselves. That works fine for my purposes. It's also perfectly backward compatible -- if there's another package that uses a 32-bit BLAS, things will work just fine.

**Comment by davydden** [comment]
> In the case you describe above, everything will be fine if the 32-bit and 64-bit libraries use different symbol names. For example, there might be dgemm and dgemm64 routines. It doesn't matter which library provides what, or how this is mapped onto the metal via variants etc. This is exactly the reason why I strongly favour this approach (using different symbol names).

agree. I am just not sure that we

(i) can do this consistently for some basic blas/lapack packages (`openblas`,`mkl`,`netlib-blas`)
(ii) make the majority of important packages which support 64bit integers work (`trilinos`,`petsc`,`mumps`,`superlu_dist`, `metis` and alike).

So i think the decision on how to do it should be based on these two factors. It is certainly not a trivial issue.

> It's very difficult to enforce using a single BLAS in the whole Spack stack. For example, there just might be a package that auto-detects BLAS and uses it if available -- it's impossible for Spack to prevent that. Also, the 64-bit interface is non-standard, and most packages won't be able to use it.

if a package may use `blas`, it should have it as a dependency anyhow. Then it should be possible to make it use `blas` from spack. I don't think the scenario you describe is an issue, perhaps i don't see other complications.

**Comment by eschnett** [comment]
If you install Python (or Julia, or Lua) via Spack, then it's not really possible to limit what add-on packages (modules) people can install. You might say "sorry, you can't call BLAS from a Lua module unless the Spack Lua package lists BLAS as dependency", but there's virtually no way to enforce this. You also can't prevent people from installing Python (or Julia, or Lua) packages themselves, via one of their package managers, as opposed to using Spack's mechanism for this (which doesn't even exist for Julia or Lua).

Thus it is a real problem; it's not that I think it would be real, this has actually caused much trouble for Julia in the past. Julia's package manager runs the equivalent of `configure` or `ldopen`, and there's a priori no mechanism to force it to always use Spack's BLAS. (There's also no mechanism to auto-detect whether a given BLAS uses 32-bit or 64-bit integers.)

**Comment by tgamblin** [comment]
@eschnett: sorry for missing this PR, and thanks for the interesting discussion.

Honestly, @eschnett's position here sounds like the most reasonable one if we want to be able to do sane linking.  I like the idea of using the `64_` suffix and am pretty keen on the fact that Fedora is adopting the convention.  I don't really like the `-i8` madness that Fortran imposes on you, and wish that Fortran and BLAS folks would realize that changing the types *actually changes the interface* and that this should be represented in the `API` and `ABI` 😱 .  I also don't really want to repeat the situation he described with Julia where they tried to use `-i8` with symbol-changing libraries.

Virtual deps in Spack are supposed to represent different ABI interfaces.  We could introduce a `blas64` vdep to handle it (and maybe rename `bias` to `blas32`?).  I guess threading also affects the interface here and whether we need four vdeps, so would we need vdeps for that too?  If you use vdeps for the different interfaces, you're free to link two libs into the same application, or one package with both vdeps if it provides both interfaces.

I also share @davydden's concern about making this interoperate with other BLAS implementations like MKL, but I'm curious whether that stuff can be shoved into spec attributes, e.g. `spec['bias'].blas_shared_lib` or maybe some more elaborate taxonomy.  That seems like a topic for another PR/issue, though.  @davydden: do you have any objections to merging this ilp64 variant assuming it does use separate symbols?  Adding a variant that adds a new interface via renamed symbols shouldn't affect the existing interface, as @eschnett points out.

**Comment by tgamblin** [comment]
@eschnett: RE: custom language-level package managers, Spack obviously can't prevent people from using them, but I'm not sure Spack should have to *support* them.  There's generally no way, or no good way, to ensure a consistent native stack when you use the language package manager, because it does' know enough details outside the language.  Spack is supposed to at least help solve that problem.  The solution would be to make Julia and Lua extendable, like Python.  R just became extendable thanks to @glennpj, and I believe @trws has looked at Lua.  You're the Julia expert -- how hard do you think it would be?

RE: BLAS consistency, assuming that extension modules properly `depend_on` BLAS, you shouldn't be ablate get inconsistent BLAS installations activated in the same Python installation.  Spack only allows one configuration of each extension to be live at once, and if the extension DAG hash includes BLAS, this assures that there aren't two BLASes.  As you say, a package can bring in or dlopen BLAS from somewhere else.  The `dlopen` case doesn't scare me that much because it's relatively contained -- `dlopened` libs actually get their own sandboxed namespace in the dynamic linker so there may not even be symbol conflicts in this case.

If the package actually links in its own BLAS implementation and exposes its symbols, I claim that's an interoperability issue for the package. We don't currently have a `conflicts` directive in Spack but I might consider adding one to allow packages to say when they conflict with BLAS.  In general I think it would be nice to work towards exposing internal dependencies like that, or at least changing or masking the symbols so that an internal BLAS doesn't conflict with an external one.

What do you think?

**Comment by davydden** [comment]
i certainly **do not object** merging this PR and I am interested in 64bit integers as well because `dealii` supports it and so do `trilinos` and `petsc` for linear algebra. And I also like the idea of having a single library with non-conflicting separate symbols via `64_` suffix.

**Comment by tgamblin** [comment]
@eschnett: if yo want to rebase to current develop (an probably resolve some flake8 tweaks) I'll merge

**Comment by trws** [comment]
RE: lua package management, now that environment variable setup for modules exists, I'm planning to resurrect my beefed-up lua package shortly that integrates the luarocks builder as a command for lua packages in spack.  Rather than using luarocks to download and manage packages, it will let spack download, stage, and leverage luarocks to build then install, lua packages in its own controlled paths.  How practical that is for julia, perl, python... etc. I'm not sure.  Go should be capable of the same thing as well if I ever get the time to finish updating that package.

**Comment by lee218llnl** [comment]
FYI #796 has mkl packaged up.

**Comment by tgamblin** [comment]
@eschnett: ping

**Comment by eschnett** [comment]
My original plan -- installing the `-ilp64` and` +ilp64` versions simultaneously -- does not work. I'm thus giving up on this patch.

**Pull request closed without merging**
