### PR TITLE
e4s ci: expand +cuda specs

### PR DESCRIPTION
**Pull request by eugeneswalker**
Expand the list of `+cuda` specs built as part of E4S CI

### CODE REVIEW

**Comment by alalazo** [comment]
@eugeneswalker Feel free to ping me when this PR passes tests

**Comment by eugeneswalker** [comment]
What is the protocol for PRs whose pipelines fail because of a spec known to be broken in develop?

```
...
==> Error: Pipeline generation failed due to the presence of the following specs that are known to be broken in develop:
* nrm@0.1.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu18.04-x86_64 ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared arch=linux-ubuntu18.04-x86_64 ^cmake@3.21.4%gcc@7.5.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu18.04-x86_64 ^diffutils@3.8%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^docbook-xml@4.5%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^docbook-xsl@1.79.2%gcc@7.5.0 patches=a92c39715c54949ba9369add1809527b8f155b7e2a2b2e30cb4b39ee715f2e30 arch=linux-ubuntu18.04-x86_64 ^expat@2.4.1%gcc@7.5.0+libbsd arch=linux-ubuntu18.04-x86_64 ^gdbm@1.19%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^gettext@0.21%gcc@7.5.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-x86_64 ^libbsd@0.11.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libffi@3.3%gcc@7.5.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu18.04-x86_64 ^libiconv@1.16%gcc@7.5.0 libs=shared,static arch=linux-ubuntu18.04-x86_64 ^libmd@1.0.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libsodium@1.0.18%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libxml2@2.9.12%gcc@7.5.0~python arch=linux-ubuntu18.04-x86_64 ^libyaml@0.2.5%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^libzmq@4.3.4%gcc@7.5.0~drafts+libsodium arch=linux-ubuntu18.04-x86_64 ^ncurses@6.2%gcc@7.5.0~symlinks+termlib abi=none arch=linux-ubuntu18.04-x86_64 ^openblas@0.3.18%gcc@7.5.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=openmp arch=linux-ubuntu18.04-x86_64 ^openssl@1.1.1l%gcc@7.5.0~docs certs=system arch=linux-ubuntu18.04-x86_64 ^perl@5.34.0%gcc@7.5.0+cpanm+shared+threads arch=linux-ubuntu18.04-x86_64 ^pkgconf@1.8.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-beniget@0.4.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-cffi@1.15.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-cython@0.29.24%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-gast@0.5.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-gevent@1.5.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-greenlet@1.1.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-jsonpatch@1.23%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-jsonpointer@1.9%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-jsonschema@2.6.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-numpy@1.21.4%gcc@7.5.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-ubuntu18.04-x86_64 ^py-packaging@21.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-pip@21.1.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-ply@3.11%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-py@1.11.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-pybind11@2.7.1%gcc@7.5.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 ^py-pycparser@2.20%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-pyparsing@3.0.6%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-pytest-runner@5.3.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-pythran@0.9.12%gcc@7.5.0 patches=b427dcaaa74ed4dfa39c58819e446e86055b65648826a101c08634d3c0be1f95 arch=linux-ubuntu18.04-x86_64 ^py-pyyaml@6.0%gcc@7.5.0+libyaml arch=linux-ubuntu18.04-x86_64 ^py-pyzmq@17.1.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-scipy@1.7.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-setuptools@57.4.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-setuptools-scm@6.3.2%gcc@7.5.0+toml arch=linux-ubuntu18.04-x86_64 ^py-six@1.16.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-tomli@1.2.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-tornado@5.1.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-vcversioner@2.16.0.0%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^py-warlock@1.3.3%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^python@3.8.12%gcc@7.5.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu18.04-x86_64 ^readline@8.1%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^sqlite@3.36.0%gcc@7.5.0+column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-x86_64 ^tar@1.34%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^util-linux-uuid@2.36.2%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64 ^xz@5.2.5%gcc@7.5.0+pic libs=shared,static arch=linux-ubuntu18.04-x86_64 ^zlib@1.2.11%gcc@7.5.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 (gg4cldgs3vknqf6gus2h4sgti3cnt7rr)
```

**Comment by eugeneswalker** [comment]
@alalazo all tests passed!

**Comment by scottwittenburg** [comment]
Any idea how many specs this adds to the e4s stack?  Just curious really, the pr mirror for this has three pages of specs, but maybe a lot of those aren't new but just changed.

**Review by scottwittenburg — APPROVED** [review]

**Pull request merged**
