### PR TITLE
Cache extra test sources update: old to new API

### PR DESCRIPTION
**Pull request by AcriusWinter**
Get rid of depreciated way to call `cache_extra_test_sources`. Packages that still have the method are having it addressed in their new test API conversion (Gptune,hypre-cmake,magma,libpressio,mptensor,n2p2,parallel-netcdf,parsec,raja)

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
This is a straightforward change that brings us one step closer to being able to deprecate the old stand-alone test API.

**Review by balay — APPROVED** [review]
[checked petsc]

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Odd.  A bunch of CI stacks are once again having numerous `vtk-m` failures with timeouts (e.g., https://gitlab.spack.io/spack/spack/-/jobs/12175508):

```
==> Installing vtk-m-2.2.0-2jom46kjjgoh7bqw6y2rph45fsulinb4 [1/1]
==> Error: TimeoutError: The read operation timed out
...
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by tldahlgren** [comment]
Updated branch to pick up #45683

**Comment by tldahlgren** [comment]
One stack had trouble getting a pod so a job timed out.

@spackbot run pipeline

**Comment by tldahlgren** [comment]
Unfortunately one of the CI stacks suffered a problem:

```
...
Reinitialized existing Git repository in /home/gitlab-runner-4/builds/builds/1QhdDUZt9/0/spack/spack/.git/
Checking out d3e44ecb as detached HEAD (ref is pr45493_cache_extra_test_sources_update)...
fatal: sha1 file '/home/gitlab-runner-4/builds/builds/1QhdDUZt9/0/spack/spack/.git/index.lock' write error. Out of diskspace.
...
```

**Comment by tldahlgren** [comment]
Trying again:

@spackbot run pipeline

**Comment by tldahlgren** [comment]
Wow. `vtk-m` failed again for one stack:

```
==> Installing vtk-m-2.2.0-vktyeu7hjt75refmi4nrddg34sakjc3m [1/1]
==> Error: FetchError: All fetchers failed for spack-stage-vtk-m-2.2.0-vktyeu7hjt75refmi4nrddg34sakjc3m
```

and a rebuild index (same stack) failed:

```
...
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
...
```

@spackbot run pipeline

**Comment by tldahlgren** [comment]
Seems there's no disk space left for one stack (again): https://github.com/spack/spack/pull/45493#issuecomment-2290000710

**Comment by tldahlgren** [comment]
Trying again:

@spackbot run pipeline

**Pull request merged**
