### PR TITLE
Drop Python 2 object subclassing

### PR DESCRIPTION
**Pull request by adamjstewart**
We no longer support Python 2, so there's no reason to use the old syntax.

Just did a simple sed call, might be bugs.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by mthcrts — APPROVED** [review]
no question, trivial changes

**Review by mthcrts — COMMENTED** [review]
forget to check boxes...

**Review by olesenm — APPROVED** [review]
I am unfortunately the wrong person to be reviewing any python changes (I'm only involuntary user of python), so will approve and defer to everyone else.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
