### PR TITLE
libblastrampoline: use tarballs and add maintainer

### PR DESCRIPTION
**Pull request by haampie**
- Use tarballs for libblastrampoline
- Add myself as maintainer

### CODE REVIEW

**Review by tgamblin — APPROVED** [review]
Approved -- but why doesn't this provide `blas`?

**Comment by haampie** [comment]
Because it could equally well depend on blas... but I tend to agree that at least providing blas/lapack is best for now.

Edit: nope, I'm not going to make that change, cause in the julia package I have to depend on libblastrampoline, but also on some actual provider of blas, and I can't make it depend on two providers. And making libblastrampoline _depend_ on blas makes it difficult for other packages to actually use libblastrampoline as blas.

**Review by alalazo — APPROVED** [review]
Changes in the PR are good, but I also think this should provide `blas`. How does this library work? Does it compile wrappers for multiple real providers that are dlopened when needed?

**Comment by giordano** [comment]
> How does this library work?

Quoting from [Julia 1.7 Highlights](https://julialang.netlify.app/previews/pr1419/blog/2021/11/julia-1.7-highlights/#libblastrampoline_mkljl)

> Because the BLAS/LAPACK API is "pure" (e.g. each BLAS/LAPACK invocation is separate from any other; there is no carryover state from one API call to another) it is possible to switch which BLAS backend actually services a particular client API call, such as a [DGEMM](http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html) call for a `Float64` `Matrix`-`Matrix` multiplication.
> This statelessness enables us to easily switch from one BLAS backend to another without needing to modify client code, and combining this with a flexible wrapper implementation, we are able to provide a single, coherent API that automatically adjusts for a variety of BLAS/LAPACK providers across all the platforms that Julia itself supports.
>
> The wrapper itself consists of assembly routines to jump to a stored function pointer, using the same assembly chunks that the [Procedure Linkage Table (PLT)](https://www.technovelty.org/linux/plt-and-got-the-key-to-code-sharing-and-dynamic-libraries.html) uses in every dynamic library on your operating system.
> These small, efficient assembly routines act as a "trampoline", bouncing a call to its true destination within OpenBLAS, MKL, etc...
>
> The story doesn't end with just writing high-performance forwarding routines, however; we also must deal with the complexity of differing BLAS/LAPACK ABIs.
> The most user-visible ABI difference is that of BLAS libraries that are built to use 64-bit indices (ILP64) rather than 32-bit indices (LP64).
> Mixing and matching client libraries that pass an index to a BLAS backend that expects indices of a different bitwidth can have disastrous consequences, from silently computing the wrong result to outright segfaulting.
> The Julia project has long been a proponent of namespacing these two ABIs separately, by suffixing ILP64 BLAS symbols to differentiate them from the rest of the world and thereby avoid fatal confusion, renaming e.g. `dgemm_` to `dgemm_64_` (note the trailing underscore is a `gfortran` convention that we follow to maintain ABI compatibility).
> To deal with this, LBT exports two sets of symbols; an LP64 set with the names that most software expects, and an ILP64 set with the names that many pieces of software in the Julia world already expect (e.g. suffixed with `64_`).
> Internally, LBT maintains forwarding tables for the LP64 and ILP64 exported functions separately, allowing for a great degree of flexibility in managing BLAS/LAPACK backends.
>
> Another possible ABI difference is the naming of the symbols themselves (`dgemm`, `dgemm_`, `dgemm__`, `_dgemm_` and `myblas_dgemm` are all BLAS symbol names that have been seen in the wild) and so LBT performs a simple search over different possible manglings when loading a BLAS/LAPACK backend.
> Apple's Accelerate backend uses a slightly different ABI than the default `gfortran` ABI as related to passing character arguments (such as the `'U'` parameter to certain LAPACK routines marking something as an "upper" triangular matrix), and LBT automatically converts to/from this other ABI.
> Finally, LBT manages some vendor-specific APIs such as setting the number of threads of the backend libraries through a single entry-point.
>
> [...]
>
> For more information you can watch the talk "[Runtime-switchable BLAS/LAPACK backends via libblastrampoline](https://www.youtube.com/watch?v=t6hptekOR7s)" from JuliaCon 2021.

**Comment by tgamblin** [comment]
If the backend blas is dynamically loaded, then it probably shouldn't depend on `blas` as @haampie suggested.  I am actually not sure how best to represent that type of dependency -- it's really something that should be resolved at env activation time or on `spack load`, and we current leave that type of thing mostly to the user.

It could provide blas, but it looks like we should add some variants to the `blas` virtual to represent the different BLAS APIs -- i.e., we probably need `blas width=32`, `blas width=64`, etc, and we might consider adding the name-shifted Julia ILP64 `blas` to the list as well.  We would need to support virtuals with variants to do that right so I think the package is fine for now.

**Comment by haampie** [comment]
> If the backend blas is dynamically loaded, then it probably shouldn't depend on blas

Don't python packages dlopen shared libs too, and specify dependencies as run-type? Also note that there are multiple "api unifying" blas packages around, like `blaspp`, which actually links to a blas provider, and is a blas provider itself (edit: okay, they don't provide a C interface, but I could still see them providing blas in spack-sense) 

> It could provide blas, but it looks like we should add some variants to the blas virtual to represent the different BLAS APIs -- i.e., we probably need blas width=32, blas width=64, etc, and we might consider adding the name-shifted Julia ILP64 blas to the list as well. We would need to support virtuals with variants to do that right so I think the package is fine for now.

openblas already had a `+ilp64`/`~ilp64` variant. I recently added `symbol_suffix=...` too, which is openblas's way of working around C's lack of function overloading. That also allows stuff like `depends_on('openblas version_suffix=64_', '^openblas +ilp64')` for packages that actually require the API to reflect the size of the integer.

**Comment by tgamblin** [comment]
> Don't python packages dlopen shared libs too, and specify dependencies as run-type?

The ones that have native dependencies should also have link dependencies.

> Also note that there are multiple "api unifying" blas packages around, like blaspp, which actually links to a blas provider, and is a blas provider itself (edit: okay, they don't provide a C interface, but I could still see them providing blas in spack-sense)

I think the distinction here is that the intent of `blastrampoline` is to allow the user to configure the loaded library at runtime. For Python packages or a wrapper that's really only supposed to load one thing, I would add the RPATH to avoid confusion. For something where you're *supposed* to configure it, the RPATH actually gets in the way of the intended functionality.  Of course, you could just use `blastrampoline` as a front-end to some other blas implementation, in which case maybe the RPATH makes sense.

**Pull request merged**
