### PR TITLE
expat: Add latest release 2.4.6 with a regression fix

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
> deprecate release 2.4.5 because of a regression

that's the point of patch releases, please don't deprecate.

**Comment by hartwork** [comment]
@haampie could you elaborate? The problem is that 2.4.5 fixed a security issue but also introduced a regression, so on one hand people need the security fix but on the other it will make some things worse. That conflict is only resolved by using >=2.4.6 and hence I would argue deprecation in the sense of "no one should be using this release today" makes sense to me.

**Comment by hartwork** [comment]
PS: @haampie in the same sense, in my book, we should add 2.4.7 and 2.4.8 and then (only) deprecated 2.4.6 after because 2.4.7 is "okay to use" today.

**Comment by haampie** [comment]
Hm, how likely is it to hit the bugs when using expat through python/cmake? It's a tradeoff between stability and many rebuilds. `deprecated=True` is rather annoying when you update spack and reconcretize an environment, and end up rebuilding a bunch of packages, even when maximizing reuse of installed packages.

**Comment by hartwork** [comment]
@haampie I'm not sure I understand. Why do reverse dependencies need a rebuild when Expat releases are ABI compatible with each opther? I would not expect rebuilds of anything (other than Expat) from updating Expat (say) 2.4.5 to 2.4.8 (expect in NixOS maybe). Am I missing something specific to Spack?

**Comment by haampie** [comment]
Spack fixes dependencies by hash, and the version number is used to compute the hash. And the hash is computed ahead of the build, so making sure two versions providing the same library&abi have the same hash is currently not possible.

**Comment by hartwork** [comment]
@haampie that explains what you meant by stability versus rebuilds. I don't know much about your environment, but getting off 2.4.5 is worth rebuilds _to me_, and so will getting off 2.4.6 be. Why not to you?

**Pull request merged**
