### PR TITLE
Fix dbcsr checksums

### PR DESCRIPTION
**Pull request by mtaillefumier**
Fix my previous mistake. linked to PR #35131

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed all 8 versions' sha256 are (now) correct.  Any idea why `2.4.0`, `2.4.1` and `2.5.0` changed?

**Comment by tldahlgren** [comment]
Deferring merge decision to give @dev-zero a chance to comment.

**Comment by haampie** [comment]
Merged it early as a hotfix for the wrong checksums

**Comment by dev-zero** [comment]
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/
Let's hope GH rolling back the change does not mean there will be another change.

**Comment by tldahlgren** [comment]
> https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/
> Let's hope GH rolling back the change does not mean there will be another change.

🤞

**Pull request merged**
