### PR TITLE
cernlib: 'new' package

### PR DESCRIPTION
**Pull request by wdconinc**
> cernlib: it just won't die.

Here is a spack package for cernlib, but it definitely needs more testing on some different platforms (and shouldn't be assumed to work on a wide range of platforms to begin with). It is a dependency of sherpa, e.g. https://github.com/spack/spack/pull/29338#issuecomment-1059974411.

```console
==> Installing cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz
==> No binary for cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz found: installing from source
==> Using cached archive: /home/wdconinc/.spack/cache/_source-cache/archive/25/25bda7271dce6e7d199039e46bd044e7eb97fd9c1287ccbf6d7b5772749e78a9.tgz
==> Using cached archive: /home/wdconinc/.spack/cache/_source-cache/archive/99/99486b6dbfb3a93803420719e0ea74a15735ee817277b0be0695b075ea136714
==> Using cached archive: /home/wdconinc/.spack/cache/_source-cache/archive/99/991cc960bf90f1a8f7d61279554bedaae9c17737d5862607414f193953db6384
==> Moving resource stage
        source: /home/wdconinc/.spack/stage/resource-cernlib.2005.corr.2020.12.11.tgz-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz/spack-src/
        destination: /home/wdconinc/.spack/stage/spack-stage-cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz/spack-src/resources/corr
==> Moving resource stage
        source: /home/wdconinc/.spack/stage/resource-cernlib.2005.install.2020.12.11.tgz-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz/spack-src/
        destination: /home/wdconinc/.spack/stage/spack-stage-cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz/spack-src/resources/install
==> No patches needed for cernlib
==> cernlib: Executing phase: 'unpack'
==> cernlib: Executing phase: 'build'
==> cernlib: Executing phase: 'install'
==> cernlib: Successfully installed cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz
  Fetch: 0.09s.  Build: 6m 10.24s.  Total: 6m 10.34s.
[+] /opt/software/linux-ubuntu21.10-skylake/gcc-10.3.0/cernlib-2020.12.11-ysjpq6ydbe7yqzqkifojxwxkf4yiudrz
==> Updating view at /home/wdconinc/git/spack/var/spack/environments/cernlib/.spack-env/view
01:41:10 wdconinc@menelaos ~ $ paw
paw      paw++    pawserv  pawX11   
01:41:14 wdconinc@menelaos ~ $ pawX11 
 ******************************************************
 *                                                    *
 *            W E L C O M E    to   P A W             *
 *                                                    *
 *       Version 2.14/04      12 January 2004         *
 *                                                    *
 ******************************************************
 Workstation type (?=HELP) <CR>=1 : 1
 Version 1.29/04 of HIGZ started
 *** No default PAWLOGON file "/home/wdconinc/.pawlogon.kumac" found

PAW > exit
 Exiting from PAW.
```

@vvolkl @iarspider: the reason I hadn't tried to upstream this is because I don't want to set anyone's expectations that cernlib, which was last released in 2005, is at all going to be maintained into the 2020s. I have gotten complaints that paw doesn't work with this spack package, but I'm not about to divert too many cycles into fixing that :-) But, with those caveats, and since it is a dependency for some other tools, I think it's probably fine to upstream. Every new compiler version will continue to result in stuff breaking... There are likely also a number of remaining hardcoded /cern paths lurking.

(Possible alternative with a better build system and unnecessary stuff stripped out: https://github.com/sly2j/nanocernlib)

### CODE REVIEW

**Comment by wdconinc** [comment]
Also builds on gcc-11. I'm not going to even try on clang since no fortran compiler anyway.

**Comment by wdconinc** [comment]
@vvolkl Do you see a use for this? Any chance you can give it a spin on one of your systems?

**Comment by vvolkl** [comment]
Thanks @wdconinc - I think for completeness this is nice to have, even if some bitrot is to be expected and nanocernlib seems a great alternative where possible. I tried this with gcc 9.4.0 (ubuntu) and gcc 11 (arch) and can confirm it builds.

There seems to be a directory loop going on with `2005`:
```console
k4-arch-01: /opt/spackages/spack (key4hep)$ ls /opt/spackages/spack/opt/spack/linux-archrolling-broadwell/clang-13.0.0/cernlib-2020.12.11-3pc3dhtfbfrbtijw2buhbokvsuoe3xgl/2005/2005/2005/2005/2005/2005/2005/2005/2005/2005
2005  bin  include  lib
```
and my installation was missing `pawX11`, but I think it's ok to merge as is - it will definitely already help someone setting out to actually use this.

**Review by vvolkl — DISMISSED** [review]

**Comment by wdconinc** [comment]
Rebased for new black style.

**Comment by wdconinc** [comment]
Resolved by https://github.com/spack/spack/pull/33911

**Pull request closed without merging**
