### PR TITLE
Update GASNet package.py to include version 2021.9.0

### PR DESCRIPTION
**Pull request by scothalverson**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Feel free to ping me when the PR is ready (it's currently a draft)

**Review by PHHargrove — APPROVED** [review]
As one of the maintainers of GASNet-EX, I can confirm that 2021.9.0 is our most recent release and that the sha256 matches the source tarball we uploaded.

**Review by alalazo — APPROVED** [review]

**Review by bonachea — APPROVED** [review]
Hi @scothalverson , looks good, thanks for your contribution.

FWIW I'm working on a more significant upgrade to the closely related upcxx spackage to accompany this release, so if your interest is actually UPC++ we should probably coordinate.

**Comment by scothalverson** [comment]
> Hi @scothalverson , looks good, thanks for your contribution.
> 
> FWIW I'm working on a more significant upgrade to the closely related upcxx spackage to accompany this release, so if your interest is actually UPC++ we should probably coordinate.

Thanks Dan!  My interest is primarily driven by Legion.  I will have to check out UPC++ though.

**Pull request merged**
