### PR TITLE
SZ: add variant for profiling statistics

### PR DESCRIPTION
**Pull request by robertu94**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
@disheng222 can you review?

**Comment by robertu94** [comment]
@adamjstewart I am also listed as a maintainer for this package as of the previous PR.  Sheng can obviously still review the change, but I thought he wouldn’t need to explicitly review it since I am now a maintainer. Could you please explain/link to the policy so I can understand it going forward?

**Comment by adamjstewart** [comment]
To be honest, there isn't really an official policy. My unofficial policy is that for any change, I like to notify all maintainers listed. If the change is extremely simple, like a 1-line change to add a new version, I'll usually merge without all maintainers approving. For more complex changes, I like to wait up to a week for all maintainers to get a chance to review. I highly doubt @disheng222 will have a problem with this change, but I just want to make sure they are aware and have a chance to review.

**Comment by disheng222** [comment]
Hi Adam, 
I checked Robert's commits, which is very good. Robert added the necessary changes to Package.py to support sz2.1.10's new functionality. Thanks.

**Pull request merged**
