### PR TITLE
sz: smoke, unit, version updates, and more oh my

### PR DESCRIPTION
**Pull request by robertu94**
@tldahlgren this is an updated and cleaned up version of #26129

@disheng222 FYI

Please let met know if you need any more changes.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Was able to install and successfully run the stand-alone tests.

(FWIW.  Running `spack install --test root sz` failed with a configuration issue for `cunit`, which may just be a configuration issue on my system.)

**Comment by robertu94** [comment]
@tldahlgren I ran the tests locally and didn’t have an issue, and I didn’t have CUnit installed at the time. I’m guessing something local happened. 

Could you post a log so I can double check?

**Comment by tldahlgren** [comment]
> @tldahlgren I ran the tests locally and didn’t have an issue, and I didn’t have CUnit installed at the time. I’m guessing something local happened.
> 
> Could you post a log so I can double check?

Sure.  I saved the `cunit` output below but can re-run if needed.

```
==> Installing cunit-2.1-3-t6w2ztgvbezt7z5qccqajnxl2woo6zmu
==> No binary for cunit-2.1-3-t6w2ztgvbezt7z5qccqajnxl2woo6zmu found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/f5/f5b29137f845bb08b77ec60584fdb728b4e58f1023e6f249a464efa49a40f214.tar.bz2
==> No patches needed for cunit
==> cunit: Executing phase: 'autoreconf'
==> cunit: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/var/tmp/dahlgren/spack-stage/spack-stage-cunit-2.1-3-t6w2ztgvbezt7z5qccqajnxl2woo6zmu/spack-src/configure' '--prefix=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cunit-2.1-3-t6w2ztgvbezt7z5qccqajnxl2woo6zmu'

4 errors found in build log:
     23    aclocal: warning: autoconf input should be named 'configure.ac', not
            'configure.in'
     24    autoreconf: running: /usr/bin/autoconf --include=/usr/share/aclocal
           --include=/usr/share/aclocal --include=/usr/WS1/dahlgren/releases/sp
           ack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/libtool-2.4.7-emzaj47m
           a7kskmsg4ecadff7a53r53cr/share/aclocal --include=/usr/share/aclocal
           --force
     25    autoreconf: running: /usr/bin/autoheader --include=/usr/share/acloca
           l --include=/usr/share/aclocal --include=/usr/WS1/dahlgren/releases/
           spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/libtool-2.4.7-emzaj4
           7ma7kskmsg4ecadff7a53r53cr/share/aclocal --include=/usr/share/acloca
           l --force
     26    autoreconf: running: automake --add-missing --copy --force-missing
     27    automake: warning: autoconf input should be named 'configure.ac', no
           t 'configure.in'
     28    configure.in:4: warning: AM_INIT_AUTOMAKE: two- and three-arguments
           forms are deprecated.  For more info, see:
  >> 29    configure.in:4: http://www.gnu.org/software/automake/manual/automake
           .html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
  >> 30    configure.in:4: installing './install-sh'
  >> 31    configure.in:4: installing './missing'
     32    automake: warning: autoconf input should be named 'configure.ac', no
           t 'configure.in'
     33    CUnit/Sources/Automated/Makefile.am: installing './depcomp'
     34    CUnit/Sources/Framework/Makefile.am:20: warning: '%'-style pattern r
           ules are a GNU make extension
     35    CUnit/Sources/Test/Makefile.am:12: warning: 'INCLUDES' is the old na
           me for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
     36    Examples/AutomatedTest/Makefile.am:13: warning: 'INCLUDES' is the ol
           d name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
     37    Examples/BasicTest/Makefile.am:13: warning: 'INCLUDES' is the old na
           me for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

     ...

     43    checking for a BSD-compatible install... /usr/bin/install -c
     44    checking whether build environment is sane... yes
     45    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
     46    checking for gawk... gawk
     47    checking whether make sets $(MAKE)... yes
     48    checking whether make supports nested variables... yes
  >> 49    configure: error: source directory already configured; run "make dis
           tclean" there first
```

FWIW I had issues with an external package that I had to address to build `sz`, which is why I suspected it is a local issue for me.

**Comment by robertu94** [comment]
Ah! CUnit failed; not sz’s usage of CUnit. I think unfortunately this log
cut out the critical part. It still be would be good take a look so this
doesn’t cause issues for users. Can you send me the typical files  needed
for a spack package bug report, and I’ll try to reproduce it if I can
quickly?

**Comment by tldahlgren** [comment]
[spack-build-env.txt](https://github.com/spack/spack/files/8781651/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8781652/spack-build-out.txt)

**Comment by robertu94** [comment]
@tldahlgren  looking at the diff between my build log and yours, the only section that sticks out is that you have an output that I don't have:

```console
libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/libtool-2.4.7-emzaj47ma7kskmsg4ecadff7a53r53cr/share/aclocal/libtool.m4'
libtoolize:   '/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/libtool-2.4.7-emzaj47ma7kskmsg4ecadff7a53r53cr/share/aclocal/ltoptions.m4'
libtoolize:   '/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/libtool-2.4.7-emzaj47ma7kskmsg4ecadff7a53r53cr/share/aclocal/ltversion.m4'
```
and

```console
configure.in:4: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:158: installing './compile'
```

My guess is that you need a different (probably newer) version of either m4, autoconf, or libtool than what CUnit is supporting.

Here is how spack concretized things for me

```console
cunit@2.1-3%gcc@11.2.1 arch=linux-fedora35-icelake
    ^autoconf@2.69%gcc@11.2.1 patches=35c4492,7793209,a49dd5b arch=linux-fedora35-icelake
        ^m4@1.4.19%gcc@11.2.1+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-fedora35-icelake
            ^libsigsegv@2.13%gcc@11.2.1 arch=linux-fedora35-icelake
        ^perl@5.34.1%gcc@11.2.1+cpanm+shared+threads arch=linux-fedora35-icelake
            ^berkeley-db@18.1.40%gcc@11.2.1+cxx~docs+stl patches=b231fcc arch=linux-fedora35-icelake
            ^bzip2@1.0.8%gcc@11.2.1~debug~pic+shared arch=linux-fedora35-icelake
            ^gdbm@1.19%gcc@11.2.1 arch=linux-fedora35-icelake
                ^readline@8.1%gcc@11.2.1 arch=linux-fedora35-icelake
                    ^ncurses@6.2%gcc@11.2.1~symlinks+termlib abi=none arch=linux-fedora35-icelake
            ^zlib@1.2.12%gcc@11.2.1+optimize+pic+shared patches=0d38234 arch=linux-fedora35-icelake
    ^automake@1.16.5%gcc@11.2.1 arch=linux-fedora35-icelake
    ^libtool@2.4.7%gcc@11.2.1 arch=linux-fedora35-icelake
```
Do you have the same versions, or did you get different ones?

**Comment by tldahlgren** [comment]
> 

You're probably right.  I have system-installed autotools as externals.  Looks like my `automake` is several minor versions behind and `libtool` is several patch versions behind.

**Comment by robertu94** [comment]
@tldahlgren I'm fine to leave it at that for now if you are.

**Comment by tldahlgren** [comment]
> @tldahlgren I'm fine to leave it at that for now if you are.

At this point, if you can build it with tests successfully, I'm happy to merge the PR (assuming it passes all the checks).  I actually thought I'd already enabled auto-merge.

**Comment by tldahlgren** [comment]
Looks like the pipeline completed successfully but didn't report results.  Will restart it.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by robertu94** [comment]
@tldahlgren ping this is still open

**Comment by alalazo** [comment]
@robertu94 Paraview build failed for some reason not in the logs. I'm restarted only that check, to see if it passes this time. Might need some time though.

**Comment by tldahlgren** [comment]
> @robertu94 Paraview build failed for some reason not in the logs. I'm restarted only that check, to see if it passes this time. Might need some time though.

Looks like `paraview` is still failing but the log is too long and there are no artifacts.

**Comment by robertu94** [comment]
@tldahlgren @alalazo the failure of paraview seems to be a time limited exceeded when building some dependencies. Should the limit be increased or does this indicate some other issue?

**Comment by alalazo** [comment]
> the failure of paraview seems to be a time limited exceeded when building some dependencies. Should the limit be increased or does this indicate some other issue?

@zackgalbreath @scottwittenburg are probably the best people to answer this

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
