### PR TITLE
Updating package file for osu-micro-benchmarks for the 6.2 release

### PR DESCRIPTION
**Pull request by MatthewLieber**
Updating the package file for the osu-micro-benchmarks 6.2 release.  Released 10/25/2022

### CODE REVIEW

**Review by natshineman — DISMISSED** [review]
Good to go.

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by natshineman** [comment]
Fixed a few missing autoreconf files in the tarball, all builds are passing now.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Reconfirmed sha256.

**Pull request merged**
