### PR TITLE
highfive: add newer versions + add git repo

### PR DESCRIPTION
**Pull request by albestro**

### CODE REVIEW

**Review by alkino — APPROVED** [review]

**Comment by alkino** [comment]
What's next?

**Comment by albestro** [comment]
@spackbot rerun pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by alkino** [comment]
@alalazo relaunch failed job, please?

**Comment by alkino** [comment]
@spackbot relaunch pipeline

**Comment by alkino** [comment]
@spackbot rerun pipeline

**Comment by alalazo** [comment]
@alkino Why are you restarting pipelines when others have just been launched?

**Comment by alkino** [comment]
One failed with: "cannot reach spack gitlab"

**Comment by alalazo** [comment]
Just wait a bit, they restart up to 3 times on spurious failures :slightly_smiling_face:

**Pull request merged**
