### PR TITLE
Add dependencies for R documentation building

### LINKED ISSUE #31567: Installation issue: r@4.2.0 missing some latex file
### Steps to reproduce the issue

download the checksum for r@4.2.0 from [the latest package file](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/r/package.py) and insert it into the current package file
`spack install r@4.2.0`

### Error message

<details><summary>Error message</summary><pre>
     1862    l.132 \RequirePackage{letltxmacro}[2008/06/13]
     1863                                                  ^^M
     1864    !  ==> Fatal error occurred, no output PDF file produced!
     1865    Calls: <Anonymous> -> texi2pdf -> texi2dvi
     1866    Execution halted
  >> 1867    make[1]: *** [Makefile:74: NEWS.pdf] Error 1
     1868    make[1]: *** Waiting for unfinished jobs....
     1869    make[1]: Leaving directory '/scratch/astroth-gpu001/3152565/simonl
             eary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkkm
             amhmu5n4yl7dx/spack-src/doc'
  >> 1870    make: [Makefile:72: docs] Error 2 (ignored)
     1871    make[1]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1872    make[2]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1873    installing parsed Rd
     1874    make[3]: Entering directory '/scratch/astroth-gpu001/3152565/simon
             leary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkk
             mamhmu5n4yl7dx/spack-src/src/library'
     1875      methods
     1876      grDevices

See build log for details:
  /scratch/astroth-gpu001/3152565/simonleary_umass_edu/spack-stage/spack-stage-r-4.2.0-m2qq55cstgtcivkmkkmamhmu5n4yl7dx/spack-build-out.txt

Traceback (most recent call last):
  File "/modules/spack/lib/spack/spack/build_environment.py", line 1060, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/modules/spack/lib/spack/spack/installer.py", line 2012, in build_process
    return installer.run()
  File "/modules/spack/lib/spack/spack/installer.py", line 1866, in run
    self._real_install()
  File "/modules/spack/lib/spack/spack/installer.py", line 1973, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/modules/spack/lib/spack/spack/package.py", line 139, in phase_wrapper
    phase(spec, prefix)
  File "/modules/spack/lib/spack/spack/build_systems/autotools.py", line 439, in build
    inspect.getmodule(self).make(*params)
  File "/modules/spack/lib/spack/spack/build_environment.py", line 158, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/modules/spack/lib/spack/spack/util/executable.py", line 239, in __call__
    raise ProcessError('Command exited with status %d:' %
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'
==> [2022-07-13-20:41:39.310053] Flagging r-4.2.0-m2qq55cstgtcivkmkkmamhmu5n4yl7dx as failed: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'
==> [2022-07-13-20:41:39.396021] ChildError: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'

</pre></details>

### Information on your system

```
* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** clingo
```

### Additional information

I know this hasn't been released yet, I was trying a hacky solution, I just want to contribute if I can.

maintainers:
@glennpj

[spack-build-env.txt](https://github.com/spack/spack/files/9105962/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9105963/spack-build-out.txt)

My attempt at a workaround:

> ! LaTeX Error: File `letltxmacro.sty' not found.
```
$ apt-file search letltxmacro.sty
texlive-latex-base: /usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty
```
I tried adding `depends_on('texlive')` but the build for that failed. Here's the build-out:
```
==> [2022-07-13-21:06:00.099469] texlive: Executing phase: 'autoreconf'
==> [2022-07-13-21:06:00.131093] texlive: Executing phase: 'configure'
==> [2022-07-13-21:06:00.162441] texlive: Executing phase: 'build'
==> [2022-07-13-21:06:00.192170] texlive: Executing phase: 'install'
==> [2022-07-13-21:06:00.200282] '/modules/spack/opt/spack/linux-ubuntu20.04-zen/gcc-9.4.0/perl-5.34.0-pamkqpwy6gmcgudpk454p2htq4so2dsc/bin/perl' './install-tl' '-scheme' 'small' '-repository' 'https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/' '-portable' '-profile' '/scratch/astroth-gpu001/3152599/tmpsuh8rhzb'
Automated TeX Live installation using profile: /scratch/astroth-gpu001/3152599/tmpsuh8rhzb
Loading https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb

=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2021
 repository: 2022
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
```

I was able to get around this by building texlive from source.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by glennpj**
Add dependencies to ensure that documentation building for R is handled
by spack built tools.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by glennpj** [comment]
@alalazo Do you have any idea why the CI pipeline fails with this PR?

**Comment by alalazo** [comment]
Hmm, not really. It seems to fail when building the `build-systems` pipeline. To reproduce the error one can:
```
To reproduce this build locally, run:
    spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/2832223/artifacts [--working-dir <dir>]
If this project does not have public pipelines, you will need to first:
    export GITLAB_PRIVATE_TOKEN=<generated_token>
... then follow the printed instructions.
```
I don't see though why we'd need to rebuild `zziplib` with this PR.

**Comment by alalazo** [comment]
@glennpj I posted a way to reproduce the failure above. You can also find it if you skim through the logs in the failed pipelines. Let me know if you need any help with that.

**Comment by glennpj** [comment]
I added missing `zip` and `unzip` dependencies for zziplib.

**Comment by glennpj** [comment]
Well, CI gets past `zziplib` but fails with `texlive`, after an exceptionally long time running. I cannot tell what failed because it apparently stopped reporting.
```
==> [2022-07-26-04:36:04.731123] '/usr/bin/file' '-b' '-h' '--mime-type' '/home/software/spack/[padded-to-512-chars]/linux-ubuntu18.04-x86_64/gcc-7.5.0/llvm-12.0.1-
Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected.
```

**Comment by glennpj** [comment]
@spackbot run pipeline

**Comment by glennpj** [comment]
I am not sure what to do about the pipeline failure. I launched the container image locally to verify there were no more missing dependencies. Everything built fine so I have no idea what is failing in the CI pipeline.

**Comment by becker33** [comment]
Should these really be unconditioned dependencies on tex? I'm just surprised we hadn't encountered this before if it applies to all versions of R

**Comment by glennpj** [comment]
> Should these really be unconditioned dependencies on tex? I'm just surprised we hadn't encountered this before if it applies to all versions of R

I am not sure. The original purpose of this PR was to see if it addressed #31567. I can not reproduce that issue on my build system, which does not have a tex install. The idea was to see if a spack installed tex would solve that issue. Looking back at that issue though, that question was never answered. This sort of morphed into, why is CI not working for this? Otherwise, if this does solve #31567, I was going to try to  make using tex a variant. I never got that far because CI was taking a really long time, and failing.

**Comment by glennpj** [comment]
What the R configure script does is it checks for tex and builds extra documentation if it finds it. There is no toggle for configure, if it finds tex it uses it, if not, it skips the extra documentation builds.

I just committed a change that removed the texlive dependency. That means this PR can not address #31567 but it does add the missing texinfo dependency. I will work on making extra documentation building a variant. I assume that setting that to false by default will allow CI to pass.

**Comment by glennpj** [comment]
Closing this as the zziplib changes are already done in #32833 and the texlive dependency is also in #32993.

**Pull request closed without merging**
