### PR TITLE
mpich: add support for Mellanox HCOLL

### PR DESCRIPTION
**Pull request by nazavode**
This PR exposes explicit HCOLL support available upstream starting from 3.2.x. 

CC maintainers: @raffenet @yfguo

### CODE REVIEW

**Comment by nazavode** [comment]
Asking the maintainers here just to be uber sure (CC @alalazo): can you confirm that HCOLL support is actually orthogonal WRT `netmod=ucx`?

**Review by alalazo — APPROVED** [review]
LGTM. Waiting for a maintainer to chime in before merging.

**Comment by raffenet** [comment]
The HCOLL integration has changed over the course of releases. In the most recent release, it is tied to UCX support. I need to go back and put together a list of releases and dependencies.

**Comment by nazavode** [comment]
@raffenet thank you so much for looking into this. So if I understand it correctly, for the latest version HCOLL without UCX makes no sense while for older ones could.

@alalazo @tldahlgren can this PR be marked as Draft pls? It looks like I don't have enough privileges for that.

**Comment by raffenet** [comment]
> @raffenet thank you so much for looking into this. So if I understand it correctly, for the latest version HCOLL without UCX makes no sense while for older ones could.

That's right.

**Comment by alalazo** [comment]
> can this PR be marked as Draft pls? It looks like I don't have enough privileges for that.

@nazavode done

**Comment by alalazo** [comment]
Hi @nazavode Is this PR still something you want?

**Comment by raffenet** [comment]
> Hi @nazavode Is this PR still something you want?

FWIW, I think this is a worthwhile variant to have for MPICH. If @nazavode doesn't respond, I can take over and submit a PR to add it.

**Comment by alalazo** [comment]
Thanks @raffenet

**Comment by alalazo** [comment]
Superseded by #30662 Thanks @nazavode and @raffenet !

**Pull request closed without merging**
