### PR TITLE
GSI-ncdiag: add version 1.1.0 and 1.1.1.

### LINKED ISSUE #38195: GSI-ncdiag: new version 1.1.0
### Summary

A new version of the GSI-ncdiag library was developed to support changes to the GSI, primarily a new subroutine that converts input doubles to singles and screens for `NaN` in the process.

### Rationale

This version of ncdiag helps to fix problems with the GSI wherein an attempt to convert double `NaN`s to singles cause `floating-invalid` errors and unpredictable behavior.

### Description

_No response_

### Additional information

_No response_

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This adds the sha256 checksum for GSI-ncdiag version 1.1.0 and fixes #38195.

### CODE REVIEW

**Review by ulmononian — APPROVED** [review]
checksum verified. approved.

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you rearrange the versions from most recent to least recent (opposite order than it is now)? Asking since all other packages do that.

**Comment by DavidHuber-NOAA** [comment]
@alalazo Yes, done.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
