### PR TITLE
Add MADIS package

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a new package, MADIS (Meteorological Assimilation Data Ingest System). It is an observational database and delivery system which integrates real-time observations for use in numerical weather prediction models and nowcasting. These changes support NOAA/National Weather Service R&D and operational forecasting applications.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the homepage and version sha256; however, I am unable to build the software.  Any ideas why I'm getting the following during the build phase?

```
...
$SPACK_ROOT/lib/spack/env/gcc/gfortran -fPIC -c mgetsatwnd.f
mgetsatwnd.f:296:40:

  206 |             CALL MSATWNDLT(VCN,DSN,FNUM,OBTMP,QCDTMP,QCATMP,QCRTMP,
      |                                        2
......
  296 |             CALL MSATWNDLT(VCN,DSN,FNUM,DUMMY,CDUMMY,DUMMY,DUMMY,STATUS)
      |                                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(4)).
```

[spack-build-out.txt](https://github.com/spack/spack/files/11655559/spack-build-out.txt)

**Comment by tldahlgren** [comment]
Also looks like there's a style issue reported by `black`:

```
==> Running black checks
--- var/spack/repos/builtin/packages/madis/package.py	2023-06-03 01:23:19.496732 +0000
+++ var/spack/repos/builtin/packages/madis/package.py	2023-06-03 01:23:35.505586 +0000
@@ -65,6 +65,6 @@
             copy_tree("src", prefix.src)
             copy_tree("static", prefix.static)
 
     def patch(self):
         for pattern in ["NETCDF_LIB", "NETCDF_INC", "FC", "FFLAGS", "LDFLAGS"]:
-            filter_file(pattern+"=", "#"+pattern+"=", "src/makefile")
+            filter_file(pattern + "=", "#" + pattern + "=", "src/makefile")
would reformat var/spack/repos/builtin/packages/madis/package.py
Oh no! 💥 💔 💥
1 file would be reformatted.
  black found errors
```

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot fix style

**Comment by AlexanderRichert-NOAA** [comment]
gcc 10 implemented strict checking for argument mismatches; this isn't the first package where we've encountered it. I just added a fix which allows arg mismatches for `^gcc@10:`.

**Review by tldahlgren — APPROVED** [review]
Builds for me now.  Thanks!

**Pull request merged**
