### PR TITLE
e4s ci: add mfem +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
FYI @acfisher @goxberry @markcmiller86 @tzanio @v-dobrev @wspear

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
Looks like `mfem` has issues building with `+rocm` per https://gitlab.spack.io/spack/spack/-/jobs/2802186:

```
config/defaults.mk:184: *** Unable to determine HIP_DIR. Please set it manually..  Stop.
```

**Comment by eugeneswalker** [comment]
> Looks like `mfem` has issues building with `+rocm` per https://gitlab.spack.io/spack/spack/-/jobs/2802186:
> 
> ```
> config/defaults.mk:184: *** Unable to determine HIP_DIR. Please set it manually..  Stop.
> ```

There is an issue description here:
* https://github.com/spack/spack/issues/30483

**Comment by v-dobrev** [comment]
Just FYI: I'm trying to resolve the build issue observed here (and documented in #30483) in the MFEM update PR #33480.

**Comment by eugeneswalker** [comment]
Just re-based onto PR https://github.com/spack/spack/pull/33480 as that has fixes needed to get this to build right.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by wspear — APPROVED** [review]

**Pull request merged**
