### PR TITLE
e4s %oneapi: add aml +ze (level zero)

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `aml +ze` to E4S OneAPI stack

@wspear @perarnau

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by tldahlgren — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
All tests are passing! Just need approval

**Review by tldahlgren — DISMISSED** [review]

**Comment by tldahlgren** [comment]
Looks like `test_checksum_interactive` is being problematic.

**Review by wspear — DISMISSED** [review]

**Comment by tldahlgren** [comment]
Required unit test checks need to pass PLUS there are conflicts that need to be resolved.

**Comment by eugeneswalker** [comment]
> Required unit test checks need to pass PLUS there are conflicts that need to be resolved.

OK, sorry about that. All checks have passed this time, I promise. It is totally ready, just pending final approval.

**Review by wspear — APPROVED** [review]

**Pull request merged**
