### PR TITLE
tinker: Remove CMake

### PR DESCRIPTION
**Pull request by OliverPerks**
Previous version used a patch file to inject a CMake build file.
This CMake file didn't handle the OpenMP support, nor the handling of the FFTW dependency.

This moves to using the shipped Makefile, however it requires some heavy modification to integrate with Spack, I think I have hit them all.

This now enables the package to be used with multiple compilers and FFTW implementations.
Tested with GCC, ACfL and NVHPC and FFTW and ArmPL (for `fftw-api`).

### CODE REVIEW

**Comment by OliverPerks** [comment]
@alalazo This is where we are seeing the issue with the concretizer for ArmPL package (https://github.com/spack/spack/pull/25461)

The package uses `fftw_init_threads` which we can resolve with `armpl.so` but we would rather use `armpl_mp.so` which would require `^armpl threads=openmp`, however with the new concretizer this is still adding in `fftw` as a dependency.

It doesn't change the application behavior so the PR is still valid but we see about a 25% speedup in some of the OpenMP tests when built with:
`tinker ^armpl threads=openmp` rather than `tinker ^armpl`, hence wanting to force the dependency.

**Comment by junghans** [comment]
I think it would be better to fix their cmake.

Also their cmake handles OpenMP (see https://github.com/TinkerTools/tinker/blob/3a6318cb2e2d2e8ad6ba28c8907c19623f76978a/cmake/CMakeLists.txt#L37) and fftw3 now (see https://github.com/TinkerTools/tinker/blob/3a6318cb2e2d2e8ad6ba28c8907c19623f76978a/cmake/CMakeLists.txt#L41)

**Comment by OliverPerks** [comment]
> I think it would be better to fix their cmake.
> 
> Also their cmake handles OpenMP (see https://github.com/TinkerTools/tinker/blob/3a6318cb2e2d2e8ad6ba28c8907c19623f76978a/cmake/CMakeLists.txt#L37) and fftw3 now (see https://github.com/TinkerTools/tinker/blob/3a6318cb2e2d2e8ad6ba28c8907c19623f76978a/cmake/CMakeLists.txt#L41)

Unfortunately, I can not commit to upstream packages. I agree with your position, but I would need to find a 3rd party to do the work.
The OpenMP work looks good, however their CMake method of FFTW3 would need to updated to allow other library names.
Is that your preference over using their `Makefile` as done in this PR?
How best to proceed?

**Comment by srinathv** [comment]
Is there progress on this?  @OliverPerks questioned the use of Makefile and/or other contribute to CMake? Can we bring someone from Kitware into this discussion?

**Comment by junghans** [comment]
> Unfortunately, I can not commit to upstream packages. I agree with your position, but I would need to find a 3rd party to do the work. The OpenMP work looks good, however their CMake method of FFTW3 would need to updated to allow other library names. Is that your preference over using their `Makefile` as done in this PR? How best to proceed?

Me neither, but they are open to pull requests.

**Comment by jayponder** [comment]
Not sure I follow what is going on here... If you need some change to our cmake files for Tinker, and it doesn't break any existing stuff on our end, then I'm happy to help.

**Comment by junghans** [comment]
@OliverPerks could you make a PR for @jayponder regarding the FFTW detection issue in CMake?

**Comment by srinathv** [comment]
I think the idea is to have Spack use the knowledge that Armpl replaces fftw.  Not sure that Cmake needs the change .

**Comment by srinathv** [comment]
also, what is this "docs/readthedocs.org:spack "

**Comment by alalazo** [comment]
Has there been any progress here?

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
