### PR TITLE
CI: E4S: enable full E4S

### PR DESCRIPTION
**Pull request by eugeneswalker**
Bring CI `spack.yaml` up-to-date with current state of E4S.

Follow-up to https://github.com/spack/spack/pull/24006 with concretization issues fixed and with complete sync w/ current E4S.

@scottwittenburg @tgamblin

### CODE REVIEW

**Comment by tgamblin** [comment]
Looking mostly good so far -- Qt is failing but the rest LGTM.  Should also reuse build caches if you push a fix for qt.

**Comment by eugeneswalker** [comment]
> Qt is failing

There's definitely something odd about Qt -- it regularly fails in my pipelines, but after a number of job retries it will eventually succeed. Perhaps it's a build parallelism issue, I don't know. For now I will comment it out.

**Comment by eugeneswalker** [comment]
This is ready to go.

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
Merging since things seems pretty quiet right now -- hoping `develop` will build and be ready before a lot of PRs start coming in.

**Pull request merged**
