### PR TITLE
Fix linking for python with external ncurses 

### PR DESCRIPTION
**Pull request by s-sajid-ali**
Trimmed down version of https://github.com/spack/spack/pull/44226

### CODE REVIEW

**Comment by teaguesterling** [comment]
FYI this solution fixed the issue as it presented in #45083. I've modified that PR to utilize this fix (and thus shouldn't be merged until this is).

**Review by alalazo — CHANGES_REQUESTED** [review]
There is a failure in pipelines: https://gitlab.spack.io/spack/spack/-/jobs/12268196

**Comment by s-sajid-ali** [comment]
The failure for `gloo` build in the pipeline is coming from the `-- Detecting C compiler ABI info` cmake phase (https://gitlab.spack.io/spack/spack/-/jobs/12268196#L156). 

Unsure how a Python recipe is affecting `gloo` since `python` is not a dependency of `gloo` per: https://packages.spack.io/package.html?name=gloo

**Comment by teaguesterling** [comment]
Might just be worth rerunning the pipeline. Occasionally, these sorts of errors seem to pop up and can be fixed by asking spackbot to try again.

**Comment by teaguesterling** [comment]
@spackbot rerun pipeline

**Review by alalazo — APPROVED** [review]

**Pull request merged**
