### PR TITLE
E4S: Conservatively add ecp-data-vis-sdk

### PR DESCRIPTION
**Pull request by kwryankrattiger**
More conservative effort than #32764 but enough to get the SDK building in the e4s environment.

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]
Thank you!

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by eugeneswalker — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
Repushing new commit to force credentials to update on gitlab

**Comment by kwryankrattiger** [comment]
put dray on a bigger runner now that a cuda version is being built..?

**Comment by kwryankrattiger** [comment]
okay...I am just going to drop ascent now so it doesn't build dray and call it a day.

@cyrush FYI, I am not sure why this is the case, but I am hoping that in the next update this can be resolved.

**Comment by eugeneswalker** [comment]
> okay...I am just going to drop ascent now so it doesn't build dray and call it a day.

Can you add `ascent` back in as a root spec until we figure out what the issue with `dray` is? I didn't inspect the CI logs but I know when I tried building `ecp-data-vis-sdk` manually, with `ascent`, `dray` was just hanging forever.

**Comment by kwryankrattiger** [comment]
I am tentative to re-add it because the likely cause is an issue with an integration the SDK added (and ascent needs) and E4S was skipping previously because it didn't specify the features wanted in the spec.

I am double checking, but I just realized that this is also occurring in the CUDA build only, not the CPU version. If that is the case, then I will turn back on the CPU one. The build is running now with full ascent integration, so I should know shortly.

**Comment by kwryankrattiger** [comment]
restarting CI because tutorials timed out. Looks like the build went through for e4s though so hopefully it can pull everything from the PR mirror this time 🤞🏽

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
This change is finding a bunch of instabilities in spack recipes that shouldn't be related to the PR at all. The latest fix, update the hint for the Python location in Adios2.

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
