### PR TITLE
su2: add version 7.0.4-7.2.0

### PR DESCRIPTION
**Pull request by kjrstory**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256s.

**Comment by tldahlgren** [comment]
@darmac As the package contributor, do you want to be included as a maintainer so you can be notified if someone changes it?

**Comment by darmac** [comment]
Sorry, my work is changed now, so maybe I have no time and resrouces to concern about this.
Maybe the `su` comunity can receive the maintainer role?

**Comment by tldahlgren** [comment]
> Sorry, my work is changed now, so maybe I have no time and resrouces to concern about this.
> Maybe the `su` comunity can receive the maintainer role?

Apologies for asking, especially since I think I've asked this before.  Unfortunately, I don't maintain a "don't contact" list.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
