### PR TITLE
ginkgo add version 1.5.0

### PR DESCRIPTION
**Pull request by balay**
Marking this PR as `don't-merge-yet` - for now used for testing only

### CODE REVIEW

**Comment by balay** [comment]
@tcojean the dealii+gingo failure comes up here as well [without xsdk]

https://gitlab.spack.io/spack/spack/-/jobs/4289832

Not sure if this is CI related. cc: @scottwittenburg 

There is also a failure with rocm

https://gitlab.spack.io/spack/spack/-/jobs/4289822

**Comment by scottwittenburg** [comment]
1. Regarding the `dealii` failure: Looking at the change which mentions `GINKGO_LIBRARY_MPI` and the error which mentions `GINKGO_LIBRARY_MPI::MPI_CXX not found!`, I'm guessing the problem is not CI related.  However, I'm not sure what's going on there.  Does it seem like `dealii` is expecting `ginkgo` to be a provider of `mpi`?  :shrug: 

2. Regarding the ginkgo/rocm failure, it sounds like something I heard about from @kwryankrattiger earlier today, maybe he can confirm or deny with a brief explanation.  Here's the error message:

```>> 914     /home/software/spack/__spack_path_placeholder__/__spack_path_place
             holder__/__spack_path_placeholder__/__spack_path_placeholder__/__s
             pack_path_placeholder__/__spack_path_placeholder__/__spack_path_pl
             aceholder__/__spack_path_placeholder__/__spack_path_placeholder__/
             __spack_path_placeholder__/__spack_path_placeholder__/__spack_path
             _placeholder__/__spack_path_placeholder__/__spack_path_placeholder
             __/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
             ath_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.
             04-x86_64/gcc-11.1.0/rocthrust-5.2.3-jnph4cxyigk4dxs7ouj5fnfjwij6w
             fr3/include/thrust/system/hip/detail/scan.h:48:10: fatal error: 'r
             ocprim/rocprim.hpp' file not found
     915     #include <rocprim/rocprim.hpp>
     916              ^~~~~~~~~~~~~~~~~~~~~
     917     1 error generated when compiling for host.
  >> 918     CMake Error at ginkgo_hip_generated_device_matrix_data_kernels.hip
             .cpp.o.cmake:146 (message):
     919       Error generating
     920       /tmp/root/spack-stage/spack-stage-ginkgo-1.5.0-44v3f2zkrnxczchzn
             2deviihiisgq4dz/spack-build-44v3f2z/hip/CMakeFiles/ginkgo_hip.dir/
             base/./ginkgo_hip_generated_device_matrix_data_kernels.hip.cpp.o
     921     
     922     
  >> 923     make[2]: *** [hip/CMakeFiles/ginkgo_hip.dir/build.make:80: hip/CMa
             keFiles/ginkgo_hip.dir/base/ginkgo_hip_generated_device_matrix_dat
             a_kernels.hip.cpp.o] Error 1
```

**Comment by tcojean** [comment]
It seems that rocthrust has a transitive dependency to rocprim, and that is somehow not propagated. I'll try to see how to fix this here.

For deal.II, they wrap our `GinkgoConfig.cmake` by doing a `FindPackage` and then going through all our dependencies and trying to find them. I assume they are looking for our sub-libraries here and do not care for MPI? I'll try to submit a small patch to this finder for deal.II to see if that's the case.
https://github.com/dealii/dealii/blob/master/cmake/modules/FindGINKGO.cmake#L53

**Comment by balay** [comment]
closing in favor of https://github.com/spack/spack/pull/33838

**Pull request closed without merging**
