### PR TITLE
Add argcomplete python package

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Comment by mathstuf** [comment]
Does this require python-setuptools? It should be added as a `depends_on`.

**Comment by adamjstewart** [comment]
Not sure, it installed fine for me. Did you find some evidence that it depends on setuptools?

**Comment by mathstuf** [comment]
I've seen packages fail because setuptools wasn't available. IIRC, usually on OS X, but it has been a while.

**Comment by adamjstewart** [comment]
I don't have OS X to test on but feel free to test it if you want. A lot of our current Python packages don't depend_on py-setuptools, so I don't want to blindly add it unless it's needed.

**Comment by adamjstewart** [comment]
ping @tgamblin

**Pull request merged**
