### PR TITLE
Python: remove maintainer

### PR DESCRIPTION
**Pull request by adamjstewart**
@pradyunsg gets thousands of notifications per week and requested to only get notifications when he's actually needed.

You're still listed on the `py-pip` package. Let me know if there are any other of the many packages you develop that you would like to receive notifications for. Otherwise I'll just ping you when I have questions I can't answer on my own.

I'm planning on bringing in @manuelakuhn in the future to help triage Python PRs.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
Thanks for the contributions so far @pradyunsg !

**Comment by alalazo** [comment]
@adamjstewart There's one unit test that needs update as well

**Comment by adamjstewart** [comment]
Removed that test entirely, our tests shouldn't depend on builtin packages/base classes.

**Review by alalazo — APPROVED** [review]

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
> Otherwise I'll just ping you when I have questions I can't answer on my own.

Let's do this. If we end up needing this more often than ad-hoc, we can revisit this at that point. :)

**Pull request merged**
