### PR TITLE
Replace py-setuptools version 20.5 by version 20.6.7

### PR DESCRIPTION
**Pull request by Rombur**
The url for version 20.5 is dead (older versions work). Replace 20.5 by 20.6.7.

### CODE REVIEW

**Comment by glennpj** [comment]
The URL for py-setuptools 20.5 works fine for me. The convention is to add a new version of a package rather than replace.

**Comment by Rombur** [comment]
That's very strange. I have tried again and I can't download py-setuprools 20.5 Anyway, I have added it back.

**Comment by adamjstewart** [comment]
The URL for py-setuptools 20.5 doesn't work for me either:
```bash
$ spack fetch py-setuptools@20.5
==> Trying to fetch from https://pypi.python.org/packages/source/s/setuptools/setuptools-20.5.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://pypi.python.org/packages/source/s/setuptools/setuptools-20.5.tar.gz failed.
==> Error: All fetchers failed for py-setuptools-20.5-hyiipnxjrmscwwk7fewohnyxgnuhsvez
```

**Comment by tgamblin** [comment]
For me, 20.6.7 works but 20.5 fails and gives an html file like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>source/s/setuptools/setuptools-20.5.tar.gz</Key><RequestId>82AD1D98E6D3C82D</RequestId><HostId>+hFOzO53qwgM9DHXmTVgWSDvKna0sKryTDiVSrf9sbv6v2LBouTSA7wOmnkYIJlWD+iCMn2/RRM=</HostId></Error>
```

**Comment by Rombur** [comment]
So what do you want me to do? Should I remove version 20.5 or not?

**Comment by tgamblin** [comment]
i think we can keep it.  if the newer version is there, it will be selected by default.

**Comment by glennpj** [comment]
Strange; this continues to work fine for me.
```
spack install py-setuptools@20.5
==> Installing py-setuptools
==> python is already installed in /home/gjohnson/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-zowdyyxtbfjheerrhpvewuri34noptxf
==> Trying to fetch from https://pypi.python.org/packages/source/s/setuptools/setuptools-20.5.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/gjohnson/spack/var/spack/stage/py-setuptools-20.5-hyiipnxjrmscwwk7fewohnyxgnuhsvez/setuptools-20.5.tar.gz
==> Created stage in /home/gjohnson/spack/var/spack/stage/py-setuptools-20.5-hyiipnxjrmscwwk7fewohnyxgnuhsvez
==> No patches needed for py-setuptools
==> Building py-setuptools
==> Successfully installed py-setuptools
  Fetch: 0.44s.  Build: 3.31s.  Total: 3.75s.
[+] /home/gjohnson/spack/opt/spack/linux-x86_64/gcc-5.3.0/py-setuptools-20.5-hyiipnxjrmscwwk7fewohnyxgnuhsvez
```

**Pull request merged**
