### PR TITLE
Features/new concretize tests

### PR DESCRIPTION
**Pull request by mplegendre**
Adds two new concretization regression tests for recent bugs.  Also fixes a bug in preferences for virtual/satisfies packages that was found by the new tests.

### CODE REVIEW

**Comment by mplegendre** [comment]
One of the new tests is failing when run in travis-ci, but not when run manually.  Will investigate.

**Comment by becker33** [comment]
@mplegendre Were you ever able to resolve this issue?

**Comment by mplegendre** [comment]
I recall that this was some issue with compiler handling, but I didn't get it fixed.

**Comment by becker33** [comment]
Any objection to closing it if it’s abandoned?

**Comment by tgamblin** [comment]
Closing for now.  @mplegendre: reopen if you're inclined to pick this back up.

**Pull request closed without merging**
