### PR TITLE
openmpi: add v5.0.4 and v5.0.5

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the new sha256.

**Comment by hppritcha** [comment]
5.0.4 had a problem on MAC os - https://github.com/open-mpi/ompi/issues/12693

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
(Oops.  Looking at wrong diff when previously changed the title.)

**Comment by tldahlgren** [comment]
> 5.0.4 had a problem on MAC os - [open-mpi/ompi#12693](https://github.com/open-mpi/ompi/issues/12693)

Do you want me to hold off merging this PR until you ping me?

**Comment by hppritcha** [comment]
this PR is ready to go.  5.0.4 was released with the MAC OS build problem using clang, so hence a ~2 day turnaround of the 5.0.5 release - which is the fix.  Should we just not support 5.0.4 in spack?

**Comment by tldahlgren** [comment]
> this PR is ready to go. 5.0.4 was released with the MAC OS build problem using clang, so hence a ~2 day turnaround of the 5.0.5 release - which is the fix. Should we just not support 5.0.4 in spack?

I'm fine merging this PR as-is but I thought I'd asked since you pointed out the issue.

**Pull request merged**
