### PR TITLE
Don't run GitHub Actions in users' forks

### PR DESCRIPTION
**Pull request by maxim-belkin**
Currently, Spack's GitHub Actions run in users' forks. In this PR I add a condition to every "job" in every workflow that requires GitHub repository name to start with `spack/` in order for the job to execute (unfortunately, there are no per-workflow conditions).

### CODE REVIEW

**Comment by alalazo** [comment]
Can't you disable actions in the settings of your fork?

**Comment by tgamblin** [comment]
Wouldn't a user with an active fork typically want this enabled?

**Comment by haampie** [comment]
I think they want everything except container image builds, which are run on a schedule and fail because of missing credentials, and then people get an email, which is annoying. So only fixing that one if it hasn't been fixed already seems sensible to me.

**Comment by maxim-belkin** [comment]
> Can't you disable actions in the settings of your fork?

I can disable Actions in my fork but that's not the point on this PR. Currently, "Bootstrapping", "Containers", and "macOS builds nightly" run daily in forks and these runs are not useful because they repeat steps performed by GH Actions in spack/spack. 

> Wouldn't a user with an active fork typically want this enabled?

Unless Spack adds a workflow for non-standard (user) branches, the ones active now repeat what is done in spack/spack.

Homebrew, for example, safe-guards its workflows this way (`if: startsWith(github.repository, 'Homebrew/')`)
https://github.com/Homebrew/brew/blob/master/.github/workflows/docker.yml#L16
https://github.com/Homebrew/brew/blob/master/.github/workflows/triage.yml#L22
https://github.com/Homebrew/brew/blob/master/.github/workflows/vendor-gems.yml#L18
https://github.com/Homebrew/brew/blob/master/.github/workflows/tests.yml#L22
https://github.com/Homebrew/brew/blob/master/.github/workflows/sorbet.yml#L18

**Comment by adamjstewart** [comment]
> Wouldn't a user with an active fork typically want this enabled?

I definitely wouldn't. It adds a lot of unnecessary CI as well.

I think @svenevs had an issue/PR for something like this too.

**Comment by svenevs** [comment]
#25901 (now stale).

**Comment by alalazo** [comment]
superseded by #30729

**Pull request closed without merging**
