### PR TITLE
Update various Jupyter packages

### PR DESCRIPTION
**Pull request by adamjstewart**
Trying to get Jupyter working on M1/M2 but no luck so far. Newer versions didn't help, but might as well add them to Spack.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256, rest LGTM

**Comment by alalazo** [comment]
I think this broke `rhel8` unit tests by discarding information on how to build for Python 3.6

**Comment by tldahlgren** [comment]
> I think this broke `rhel8` unit tests by discarding information on how to build for Python 3.6

Apologies. I wondered about their removal.

**Comment by alalazo** [comment]
> Apologies. I wondered about their removal.

Meh, when CI is :heavy_check_mark: it's CI being broken :sweat:

**Pull request merged**
