### PR TITLE
py-torchaudio: upperbound on cuda

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
The upperbound makes sense. The other changes make less sense. Note that this package only started to contain CUDA code starting with v0.10.0, and has never contained ROCm code.

**Comment by haampie** [comment]
Let's say the package itself makes least sense :) why does it care about USE_ROCM then. I'll remove the rocm bits, but it remains a cuda package.

**Comment by adamjstewart** [comment]
I'm just not a fan of variant forwarding. Why do we need additional `+cuda` and `cuda_arch` variants if they aren't allowed to differ from `py-torch`?

**Comment by haampie** [comment]
CudaPackage also sets compiler compat

**Review by adamjstewart — APPROVED** [review]
Not opposed to further changes, but let's merge this quickly to fix CI and discuss those elsewhere if needed.

**Comment by scheibelp** [comment]
@haampie 

* Do we have a label to indicate that PRs address widespread CI failures? If not, we should have that, and this PR should have that label. Or perhaps we should have a project that tracks PRs like this, since labels can be hard to track.
* Do you know which changes led to the widespread CI failures in this case (and why those changes didn't trigger a rebuild of `py-torchaudio` in the first place)? If so, can you link that change here?

**Comment by scheibelp** [comment]
Regarding the second point

> Do you know which changes led to the widespread CI failures in this case

I missed an explanation you sent me (in slack):

> two prs tested that are green independently but not together

Do you know if there is any ongoing work to address this?

**Pull request merged**
