### PR TITLE
Add regression test for parsing multiple specs 

### PR DESCRIPTION
**Pull request by alalazo**
See #1956

### CODE REVIEW

**Comment by alalazo** [comment]
@tgamblin Side question : how long do you think we'll need to support python 2.6 ? It's being deprecated everywhere, including official python.org docs...

**Comment by tgamblin** [comment]
This is only an expected failure right now b/c the bug hasn't been fixed.  So we should switch it back when it's fixed...

I'm sad about Python 2.6.  The easy build guys recently did a [poll](http://doodle.com/poll/ir67d2hfhkefxfcp#table) that showed many centers still have it as their default.  I'm tempted to drop it sometime in the next year, as I think most sites do offer a 2.7 side install, but who knows.  Maybe we could drop it if we can guarantee that Spack can bootstrap Python 2.7 from a 2.6 install... not sure how much work it would be to keep that code path clean.

**Comment by alalazo** [comment]
> This is only an expected failure right now b/c the bug hasn't been fixed. So we should switch it back when it's fixed...

Yes, that was a bad try by my side to insert a failing regression test in the code base without having Travis CI complaining. The next step would have been reporting expected failures as 'Expected failures [bug not yet fixed]' or something like that. 

The problem obviously is that 2.6 doesn't know what an `expectedFailure` is...

**Comment by adamjstewart** [comment]
For what it's worth, our _newest_ cluster runs CentOS 6 and comes with Python 2.6.6 by default. Our _old_ cluster runs CentOS 5 and comes with Python 2.4.3 by default. So I don't think it's uncommon to find 2.6 (or older) in production.

Sometime this winter we're replacing our old cluster with a new one running CentOS 7. Once development on that stabilizes, we'll be updating the other cluster to CentOS 7 as well.

**Comment by tgamblin** [comment]
Ok let's keep this open and resolve it when spec parsing is fixed (by removing the expected failure)

**Comment by alalazo** [comment]
@tgamblin I added this as an expected failure in #2502 . If you agree I'll close this.

**Comment by alalazo** [comment]
Closing as this is part of #2502

**Pull request closed without merging**
