### PR TITLE
Osu/mv2 hwloc2

### PR DESCRIPTION
**Pull request by MatthewLieber**
Adds a variant that allows users to build mvapich2 with hwlocv2

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
Deferring merge decision to @harisubramoni, @natshineman , and or @ndcontini.

**Review by natshineman — APPROVED** [review]
This is good to go.

**Comment by tldahlgren** [comment]
There was a runner system failure on one of the stacks.

@spackbot run pipeline

**Pull request merged**
