### PR TITLE
mold: Add 2.30.0 and 2.31.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256s.

**Comment by tldahlgren** [comment]
@jabcross Are there any other changes needed besides the version directives before this PR is merged?

**Comment by haampie** [comment]
We should make `spack install gcc +mold` a thing... since a few weeks Spack actually puts `$binutils/bin` in GCCs program search path. So if you feel like doing the same for mold in another pr that'd be excellent :D

**Comment by jabcross** [comment]
Can I get removed as maintainer of the package? I can't dedicate any time to it at the moment.

I remember it being quite a straightforward package, so it shouldn't be difficult to maintain by those who are interested in using it.

**Comment by tldahlgren** [comment]
> Can I get removed as maintainer of the package? I can't dedicate any time to it at the moment.
> 
> I remember it being quite a straightforward package, so it shouldn't be difficult to maintain by those who are interested in using it.

This (https://github.com/spack/spack/pull/44047) should do it.

**Comment by msimberg** [comment]
> We should make `spack install gcc +mold` a thing... since a few weeks Spack actually puts `$binutils/bin` in GCCs program search path. So if you feel like doing the same for mold in another pr that'd be excellent :D

No promises, but I'd love to have that as well! Using mold is a bit awkward now... Is this the change you're talking about: https://github.com/spack/spack/blob/0a353abc42e5bd67ce0401a58b327c2d84d9eab9/var/spack/repos/builtin/packages/gcc/package.py#L972-L973?

**Comment by haampie** [comment]
Yeah, should be two things:

1. Inform the compiler about the default linker flavor (ld, lld, mold, gold, etc). That's different from telling it where the linker is. It lets the compiler determine what flags to pass as different linkers potentially have different command line arguments.
2. Inform the compiler where to find the linker (that's the -B flag you're pointing out).

In the past we added something like `--with-ld=/path/to/bin/ld` during configure of GCC, but that is wrong. That flag was meant for setting the default linker flavor, so item 1 only.

**Pull request merged**
