### PR TITLE
libluv: update to the latest release

### LINKED ISSUE #26673: Installation issue: libluv
### Steps to reproduce the issue

```console
$ spack install neovim
```

### Information on your system

* **Spack:** 0.16.3-4806-532ba03d60
* **Python:** 3.8.2
* **Platform:** darwin-bigsur-m1
* **Concretizer:** clingo

### Additional information

```
==> Installing libluv-1.36.0-0-d4tbvgqbrm27bvnluo4u7mbbfkmfofgi
==> No binary for libluv-1.36.0-0-d4tbvgqbrm27bvnluo4u7mbbfkmfofgi found: installing from source
==> Using cached archive: /Users/certik/repos/spack/var/spack/cache/_source-cache/archive/f2/f2e7eb372574f25c6978c1dc74280d22efdcd7df2dda4a286c7fe7dceda26445.tar.gz
==> No patches needed for libluv
==> libluv: Executing phase: 'cmake'
==> libluv: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

4 errors found in build log:
     82     /Users/certik/repos/spack/opt/spack/darwin-bigsur-m1/apple-clang-12
            .0.5/cmake-3.21.3-gkfoksq2k2e7znnilapooa5jsili7ag3/bin/cmake -E cma
            ke_link_script CMakeFiles/libluv_a.dir/link.txt --verbose=1
     83     /Users/certik/repos/spack/lib/spack/env/clang/clang -O2 -g -DNDEBUG
             -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/Mac
            OSX.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility
            _version 1.0.0 -current_version 1.36.0 -o libluv.1.36.0.dylib -inst
            all_name /private/var/folders/43/nspmtcpj5r589x58n_spl6jm000fsc/T/c
            ertik/spack-stage/spack-stage-libluv-1.36.0-0-d4tbvgqbrm27bvnluo4u7
            mbbfkmfofgi/spack-build-d4tbvgq/libluv.1.dylib CMakeFiles/libluv.di
            r/src/luv.c.o  /Users/certik/repos/spack/opt/spack/darwin-bigsur-m1
            /apple-clang-12.0.5/libuv-1.42.0-h4obvdsf3c3s4k467tfgicahwwpdejlt/l
            ib/libuv.dylib
     84     /usr/bin/ar qc libluv_a.a CMakeFiles/libluv_a.dir/src/luv.c.o
     85     /usr/bin/ranlib libluv_a.a
     86     make[2]: Leaving directory '/private/var/folders/43/nspmtcpj5r589x5
            8n_spl6jm000fsc/T/certik/spack-stage/spack-stage-libluv-1.36.0-0-d4
            tbvgqbrm27bvnluo4u7mbbfkmfofgi/spack-build-d4tbvgq'
     87     make[2]: Leaving directory '/private/var/folders/43/nspmtcpj5r589x5
            8n_spl6jm000fsc/T/certik/spack-stage/spack-stage-libluv-1.36.0-0-d4
            tbvgqbrm27bvnluo4u7mbbfkmfofgi/spack-build-d4tbvgq'
  >> 88     Undefined symbols for architecture arm64:
     89       "_luaL_argerror", referenced from:
     90           _luv_cancel in luv.c.o
     91           _luv_timer_start in luv.c.o
     92           _luv_timer_stop in luv.c.o
     93           _luv_timer_again in luv.c.o
     94           _luv_timer_set_repeat in luv.c.o

     ...

     480          _luv_thread_arg_set in luv.c.o
     481          _luv_check_bufs in luv.c.o
     482          _luv_prep_bufs in luv.c.o
     483          _luv_check_bufs_noref in luv.c.o
     484          ...
     485    ld: symbol(s) not found for architecture arm64
  >> 486    clang: error: linker command failed with exit code 1 (use -v to see
             invocation)
  >> 487    make[2]: *** [CMakeFiles/libluv.dir/build.make:101: libluv.1.36.0.d
            ylib] Error 1
     488    make[2]: Leaving directory '/private/var/folders/43/nspmtcpj5r589x5
            8n_spl6jm000fsc/T/certik/spack-stage/spack-stage-libluv-1.36.0-0-d4
            tbvgqbrm27bvnluo4u7mbbfkmfofgi/spack-build-d4tbvgq'
  >> 489    make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/libluv.dir/all] E
            rror 2
     490    make[1]: *** Waiting for unfinished jobs....
     491    [100%] Built target libluv_a
     492    [100%] Built target luv
     493    make[1]: Leaving directory '/private/var/folders/43/nspmtcpj5r589x5
            8n_spl6jm000fsc/T/certik/spack-stage/spack-stage-libluv-1.36.0-0-d4
            tbvgqbrm27bvnluo4u7mbbfkmfofgi/spack-build-d4tbvgq'
     494    make: *** [Makefile:139: all] Error 2

See build log for details:
  /var/folders/43/nspmtcpj5r589x58n_spl6jm000fsc/T/certik/spack-stage/spack-stage-libluv-1.36.0-0-d4tbvgqbrm27bvnluo4u7mbbfkmfofgi/spack-build-out.txt

==> Error: neovim-0.4.4-x46l5tptdaqrfscympfl7artkpfpyncf: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by certik**
Fixes #26673.

Many thanks to @sethrj for helping me debug it.

### CODE REVIEW

**Review by sethrj — DISMISSED** [review]

**Comment by certik** [comment]
@sethrj thanks for reviewing it. Is the ci/gitlab-ci failure related to this PR? It seems unrelated. What should we do?

**Comment by sethrj** [comment]
> @sethrj thanks for reviewing it. Is the ci/gitlab-ci failure related to this PR? It seems unrelated. What should we do?

No it's a problem stemming from a CI glitch upstream -- I'll ask spackbot to restart the pipe tomorrow to get this merged.

**Comment by sethrj** [comment]
@spackbot re-run pipeline

**Comment by sethrj** [comment]
@certik Unfortunately the `develop` CI was broken for a day or two, so can you rebase on upstream/develop and force-push? Thanks.

**Comment by certik** [comment]
Done!

**Review by sethrj — APPROVED** [review]

**Comment by certik** [comment]
Thanks @sethrj for your help with the MRs, reviewing them and merging them.

**Comment by certik** [comment]
Thanks @sethrj for your help with the MRs, reviewing them and merging them.

**Pull request merged**
