### PR TITLE
Renames 'std' kokkos variant to 'cxxstd'.

### PR DESCRIPTION
**Pull request by dipietrantonio**
Renames the kokkos `std` variant to `cxxstd`. Here is how I determined what other packages were using kokkos with that variant:

```
cdipietrantonio:spack/var/spack/repos/builtin/packages> grep -R . -e 'depends_on("kokkos' | grep "std"
./ascent/package.py:    depends_on("kokkos std=11", when="+vtkh ^vtk-m +kokkos")
./hpx-kokkos/package.py:        depends_on("kokkos std={0}".format(cxxstd), when="cxxstd={0}".format(cxxstd))
```

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
Waiting for maintainer comments, but LGTM (all other packages use `cxxstd`)

**Review by msimberg — DISMISSED** [review]

**Comment by alalazo** [comment]
@dipietrantonio This is good to go as soon as you fix style

**Comment by alalazo** [comment]
Funny: no conflicting files are listed, but apparently this branch "has conflicts that must be resolved"

**Comment by dipietrantonio** [comment]
Merged `develop` branch into this (sorry for the force push, did not merge properly at first). There was an addition to the `variant` command (the `description` attribute).

**Review by alalazo — DISMISSED** [review]

**Comment by dipietrantonio** [comment]
Hi @alalazo , not sure why tests failed here.

**Comment by alalazo** [comment]
@dipietrantonio I'd advise to avoid merging or rebasing with develop multiple times. If you do so, you'll just delay the starting of pipelines, per https://github.com/spack/spack-infrastructure/blob/main/docs/deferred_pipelines.md

**Comment by dipietrantonio** [comment]
Hi @alalazo , I thought the merging was blocked because I hadn't merged `develop`, as pointed out by `ci/gitlab-ci` check. So I will leave it alone then.

**Comment by alalazo** [comment]
@dipietrantonio No, what `ci/gitlab-ci` points out is that the check is on hold until the `develop` commit this PR is based on finishes. If that advances, the PR will be delayed until the new, more recent, commit finishes too.

**Comment by dipietrantonio** [comment]
Oh thanks for the explanation, I misread!

**Comment by alalazo** [comment]
@dipietrantonio There's a legit issue with pipelines. Can you update [this file](https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml) to use `cxxstd` instead of `std` for kokkos?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
