### PR TITLE
change PrgEnv-nvhpc to PrgEnv-nvidia for NVHPC compiler detection

### LINKED ISSUE #28275: spack compiler find for nvhpc is not correct
@lukebroskop @samcmill 

cc: @wspear @eugeneswalker @sameershende 

There is an issue when running `spack compiler find` for detecting nvhpc compilers. According to this line it will create module `PrgEnv-nvhpc` 

https://github.com/spack/spack/blob/a43ed9286fc99f5e9127744d914b7c09a4021836/lib/spack/spack/compilers/nvhpc.py#L28

I think this was the case some time back but now Cray has decided to change this to `PrgEnv-nvidia` according to Perlmutter we get the following modules

```
(spack-pyenv) siddiq90@login06> ml -t av PrgEnv
/opt/cray/pe/lmod/modulefiles/core:
PrgEnv-aocc/8.2.0
PrgEnv-cray/8.2.0
PrgEnv-gnu/8.2.0
PrgEnv-nvidia/8.2.0
```

If i load `PrgEnv-nvidia` i should get spack to detect the compiler but in this case i dont get this

```
(spack-pyenv) siddiq90@login06> ml PrgEnv-nvidia
(spack-pyenv) siddiq90@login06> spack compiler find
==> Found no new compilers
==> Compilers are defined in the following files:
    /global/homes/s/siddiq90/software.nersc.gov/spack-infrastructure/spack-configs/perlmutter-systemlayer/ci/spack.yaml
```

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@samcmill can you please review this PR.

**Review by samcmill — APPROVED** [review]
The change is fine to get you unstuck right now.  We are discussing longer term solutions with Cray/HPE.

**Comment by alalazo** [comment]
Is this something that works across all Cray systems (and therefore we want merged) or is it a workaround for some systems only?

**Comment by lukebroskop** [comment]
I see that the standard going forward is to use `PrgEnv-nvhpc` and `nvhpc`.


**Future Change for Prgenv-nvidia and Nvidia Module Files**
The purpose of this note is to give advance notice that in an upcoming CPE release, possibly as early as CPE 22.03 (March 2022), the PrgEnv-nvidia and nvidia module files will be deprecated in favor of PrgEnv-nvhpc and nvhpc, respectively.

The above is from: https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=a00120811en_us

**Comment by alalazo** [comment]
Thanks for the pointer @lukebroskop

**Comment by shahzebsiddiqui** [comment]
@lukebroskop if i understand correctly, we should close this PR since we will be going back to `PrgEnv-nvhpc` which is reflected in the spack codebase

**Comment by lukebroskop** [comment]
@shahzebsiddiqui , yes this is correct -- close this PR.

**Pull request closed without merging**
