### PR TITLE
osu-micro-benchmarks: adding sha for 7.1 release

### PR DESCRIPTION
**Pull request by MatthewLieber**
Adds the sha for 7.1 release to package.py

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by natshineman** [comment]
Looks like there were some compile errors when building with OMPI, we are investigating these and will try to push a quick fix today. Let's hold off on the merge temporarily until we can get that fixed. Should be a small patch.

**Comment by tldahlgren** [comment]
Looks like a couple of stacks are having problems building the package (e.g., https://gitlab.spack.io/spack/spack/-/jobs/6477375/raw):

```
...
depbase=`echo ../../../util/osu_util_mpi.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
/home/software/spack/[padded-to-256-chars]/linux-amzn2-x86_64_v3/gcc-7.3.1/openmpi-4.1.5-unpm7pwne6dfnwhjowiiviip3wpirtcy/bin/mpicc -DPACKAGE_NAME=\"OSU-Micro-Benchmarks\" -DPACKAGE_TARNAME=\"osu-micro-benchmarks\" -DPACKAGE_VERSION=\"7.1\" -DPACKAGE_STRING=\"OSU-Micro-Benchmarks\ 7.1\" -DPACKAGE_BUGREPORT=\"mvapich-discuss@cse.ohio-state.edu\" -DPACKAGE_URL=\"\" -DPACKAGE=\"osu-micro-benchmarks\" -DVERSION=\"7.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_MATH_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMSET=1 -DHAVE_SQRT=1 -DFIELD_WIDTH=18 -DFLOAT_PRECISION=2 -I.    -I../../../../c/util  -g -O2 -MT ../../../util/osu_util_mpi.o -MD -MP -MF $depbase.Tpo -c -o ../../../util/osu_util_mpi.o ../../../util/osu_util_mpi.c &&\
mv -f $depbase.Tpo $depbase.Po
../../../util/osu_util_mpi.c: In function 'omb_assign_to_type':
../../../util/osu_util_mpi.c:1411:13: error: switch quantity not an integer
     switch (dtype) {
             ^~~~~
../../../util/osu_util_mpi.c:1412:9: error: pointers are not permitted as case values
         case MPI_CHAR:
         ^~~~
../../../util/osu_util_mpi.c:1416:9: error: pointers are not permitted as case values
         case MPI_INT:
         ^~~~
../../../util/osu_util_mpi.c:1419:9: error: pointers are not permitted as case values
         case MPI_FLOAT:
         ^~~~
../../../util/osu_util_mpi.c: In function 'omb_get_num_elements':
../../../util/osu_util_mpi.c:1430:13: error: switch quantity not an integer
     switch (dtype) {
             ^~~~~
../../../util/osu_util_mpi.c:1431:9: error: pointers are not permitted as case values
         case MPI_CHAR:
         ^~~~
../../../util/osu_util_mpi.c:1434:9: error: pointers are not permitted as case values
         case MPI_FLOAT:
         ^~~~
../../../util/osu_util_mpi.c:1437:9: error: pointers are not permitted as case values
         case MPI_INT:
         ^~~~
../../../util/osu_util_mpi.c: In function 'omb_validate_neighbour_col':
../../../util/osu_util_mpi.c:1970:21: error: switch quantity not an integer
             switch (dtype) {
                     ^~~~~
../../../util/osu_util_mpi.c:1971:17: error: pointers are not permitted as case values
                 case MPI_CHAR:
                 ^~~~
../../../util/osu_util_mpi.c:1980:17: error: pointers are not permitted as case values
                 case MPI_INT:
                 ^~~~
../../../util/osu_util_mpi.c:1988:17: error: pointers are not permitted as case values
                 case MPI_FLOAT:
                 ^~~~
../../../util/osu_util_mpi.c: In function 'validate_reduce_scatter':
../../../util/osu_util_mpi.c:2039:17: error: switch quantity not an integer
         switch (dtype) {
                 ^~~~~
../../../util/osu_util_mpi.c:2040:13: error: pointers are not permitted as case values
             case MPI_CHAR:
             ^~~~
../../../util/osu_util_mpi.c:2046:13: error: pointers are not permitted as case values
             case MPI_INT:
             ^~~~
../../../util/osu_util_mpi.c:2052:13: error: pointers are not permitted as case values
             case MPI_FLOAT:
             ^~~~
make[4]: *** [Makefile:582: ../../../util/osu_util_mpi.o] Error 1
...
```

**Comment by MatthewLieber** [comment]
@tldahlgren can you tell us what could have made it fail the package audits?  From the error code it looks like a pip command is failing.

**Review by natshineman — APPROVED** [review]
This version should build with OpenMPI as well as MPICH derivatives

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
