### PR TITLE
nag: add new version

### PR DESCRIPTION
**Pull request by skosukhin**

### CODE REVIEW

**Comment by ThemosTsikas** [comment]
> @ThemosTsikas can you review this PR?
> 
> This PR modifies the following package(s), for which you are listed as a maintainer:
> 
> * nag

Hello, I am no longer employed at NAG. Please direct queries to support@nag.co.uk.

**Comment by skosukhin** [comment]
I don't think one has to be employed at NAG to be a maintainer of the package. Anyway, I have updated the list of maintainers too.

**Comment by adamjstewart** [comment]
@ThemosTsikas sad to see you leave. Thanks for all of your help with Spack + NAG support over the years!

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
