### PR TITLE
vtk-m: add v2.2.0

### PR DESCRIPTION
**Pull request by vicentebolea**
:tada: :tada: :tada: 

Finally! VTK-m v2.2.0 release is out.

This bring exiting new features and bugfixes. Find the release notes at https://gitlab.kitware.com/vtk/vtk-m/-/blob/master/docs/changelog/2.2/release-notes.md

Let me know if we need to change anything else in the package

ViB

:tada: :tada: :tada:

### CODE REVIEW

**Review by kmorel — APPROVED** [review]
Looks good to me.

**Review by alecbcs — DISMISSED** [review]
Verified checksums. Looks good to me. Thanks @vicentebolea!

**Review by alecbcs — DISMISSED** [review]
Looks good to me. Thanks @vicentebolea

**Comment by vicentebolea** [comment]
@alecbcs CI is finally passing (we had issues in kitware with our network), can you re-review this?

**Comment by alecbcs** [comment]
Will do! @kmorel does this PR still look good to you?

**Comment by kmorel** [comment]
This still looks good. I just compiled 2.2.0 on Perlmutter and it built successfully.

**Comment by vicentebolea** [comment]
@alecbcs can you merge this? Thanks

**Review by alecbcs — APPROVED** [review]
Changes look good to me. Thanks @vicentebolea

**Pull request merged**
