### PR TITLE
Damaris package file updated - latest v1.5.0 tag and build allows ins…

### PR DESCRIPTION
**Pull request by jcbowden**
…tall of examples

### CODE REVIEW

**Comment by jcbowden** [comment]
okay, i'll try again!

**Comment by jcbowden** [comment]
The issue looks to be a bug with gitlab: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27887

**Comment by jcbowden** [comment]
This is the issue:
WARNING: Uploading artifacts as "archive" to coordinator... failed  id=1059196 responseStatus=500 Internal Server Error status=500 token=A2Ehhxi2
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
WARNING: Uploading artifacts as "archive" to coordinator... failed  id=1059196 responseStatus=500 Internal Server Error status=500 token=A2Ehhxi2
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
WARNING: Uploading artifacts as "archive" to coordinator... failed  id=1059196 responseStatus=500 Internal Server Error status=500 token=A2Ehhxi2
FATAL: invalid argument                            
Cleaning up file based variables
ERROR: Failed to cleanup volumes
ERROR: Job failed: exit code 1

**Review by bernhardkaindl — APPROVED** [review]
passed `spack install -v --test=root damaris`, LGTM

**Pull request merged**
