### PR TITLE
gmsh: add v4.11.1

### PR DESCRIPTION
**Pull request by isaachyw**

### CODE REVIEW

**Review by tldahlgren — CHANGES_REQUESTED** [review]
I'm not getting that value for the sha256.

How did you calculate it?  Are you using `spack checksum` (see https://spack.readthedocs.io/en/latest/packaging_guide.html#cmd-spack-checksum).

**Comment by tldahlgren** [comment]
Also, we highly recommend creating a PR-specific branch (see https://spack.readthedocs.io/en/latest/contribution_guide.html#branching).

**Comment by tldahlgren** [comment]
The package fails the CI build due to the sha256 (see https://gitlab.spack.io/spack/spack/-/jobs/7749116).

**Comment by tldahlgren** [comment]
@isaachyw Did you mean to close this PR?

**Comment by alalazo** [comment]
Outdated by #41320

**Pull request closed without merging**
