### PR TITLE
Intel compiler workaround suggested by Ilya Zhukov of JSC.

### PR DESCRIPTION
**Pull request by ikitayama**
Suggested-by: i.zhukov@fz-juelich.de

Built fine on JURECA-DC login node.

### CODE REVIEW

**Comment by ikitayama** [comment]
@pramodk , can you review my PR?

**Comment by ikitayama** [comment]
This should not be merged.

**Comment by ikitayama** [comment]
I'll make another PR from the bread branch.

**Comment by pramodk** [comment]
Oops..I received email on some other account so couldn't look at this earlier.

**Comment by ikitayama** [comment]
@pramodk , actually, `perl` maintainers think the real issue is somewhere else.

**Pull request closed without merging**
