### PR TITLE
ci: add mimimal gpu testing stack for power

### PR DESCRIPTION
**Pull request by eugeneswalker**
@wspear

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by wspear — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline because of broken specs on develop in other stacks, unrelated to this PR

**Review by scottwittenburg — DISMISSED** [review]
LGTM, I see the child pipeline for this particular stack passed several iterations ago, but it's the unrelated broken specs on develop that are causing the gitlab pipeline failure.

**Comment by eugeneswalker** [comment]
Putting this in draft mode as we are going to upgrade the NVIDIA Stack on the GPU runners this stack needs before we merge. Will bring it out of draft when ready again.

**Comment by eugeneswalker** [comment]
The GPU runners that will be used by this stack have been and are working well!

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
GitLab CI failing because of specs known to be broken in develop.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
I think this is ready for merge!

**Pull request closed without merging**
