### PR TITLE
SCR: fix depends on versioning

### PR DESCRIPTION
**Pull request by white238**
The `depends_on` had version conflicts for `3.0.0` and `3.0.1`.

Error prior to fix:

```
==> Error: No version for 'axl' satisfies '@0.6.0' and '@0.7.1'
```

### CODE REVIEW

**Comment by white238** [comment]
Not sure why it said i removed @CamStan... The UI might have been not refreshed or something but when i started adding noone was listed as a reviewer. Feel free to ignore if you don't want to be involved.

**Review by tldahlgren — APPROVED** [review]
Tested manually (before and after fix).  LGTM.

**Comment by tldahlgren** [comment]
Will defer merge to give at least one maintainer a chance to comment.

**Comment by tldahlgren** [comment]
@gonsie @CamStan Any objections to merging this PR?

**Review by CamStan — APPROVED** [review]
No objections

**Pull request merged**
