### PR TITLE
setup-env.sh: filter preceding - on OSX

### PR DESCRIPTION
**Pull request by junghans**
```bash
$ ps -p $$
  PID TTY           TIME CMD
98195 ttys004    0:00.02 -bash
```

### CODE REVIEW

**Comment by krafczyk** [comment]
@junghans I ran this fix on my setups and LGTM, thanks for pointing this out.
@scheibelp Can we get this merged when the tests finish?

**Comment by junghans** [comment]
@krafczyk: Was there are reason to not use `${SHELL}` as a guess?

**Comment by krafczyk** [comment]
I've found `${SHELL}` doesn't give consistent results. For instance, if I
start a bash subshell from `zsh`, `${SHELL}` still says `/bin/zsh`. I
wanted to be sure that I could get the name of the shell currently
interpreting the `setup-env.sh` file.

**Comment by scheibelp** [comment]
Thanks @junghans for the fix. LGTM and I'll merge it when the tests complete

**Pull request merged**
