### PR TITLE
Sleak/hotfix/spec short spec

### PR DESCRIPTION
**Pull request by sleak-lbl**
git comment covers most of if I think .. we were getting error messages, especially with "spack -vd install", because of "/" and " " characters in file paths, these came mostly from the hash component of Spec.short_spec. There was some inconsistency in the character used  to indicate a hash ("/", "-" and "#")

In this patch I've selected "#" as the hash prefix on the basis that "-" was already overloaded and "/"  was difficult for the filesystem - and us commonwealth speakers pronounce "#" as "hash" ;)

So throughout the code I've made "#" consistently the hash prefix. The parsers still recognize "/" as well as "#" though, for backwards compatibility and in case I missed any.

It now passes all of the tests it passed before and a few more

cheers,
Steve

### CODE REVIEW

**Comment by tgamblin** [comment]
@sleak-lbl @mamelara: Can I convince you to  to go with something else if I get you a quick fix for `spack -d install`?  We can fix that by making the filenames use a short hash with no `/`.

The reason we went with `/` is because it works ok on the command line, and if we print `/` back out, you can re-parse a printed `spec`.  I think that is a good property to keep, mainly because it's consistent, and the users don't have lots of different ways of knowing about hashes.  

`-` is vestigial -- we tried to get rid of it for `/`, but we use `-` instead of *any* of the sigils in installation directory names because there are various installs that don't deal well with special characters outside `[A-Za-z0-9_-]`.  For example, Spack originally had `@` in its install directory names, but packages like TAU couldn't handle this because they used `@` in their sed (e.g., in `s@@@`) scripts.  Witness the vestigial [`change_sed_delimeter`](https://github.com/LLNL/spack/blob/develop/lib/spack/llnl/util/filesystem.py#L139) routine we had to write to handle that.

I think `#` is going to have similar issues, mainly because it is the shell comment character.  So I'd rather not see that one go too far.  It's definitely not typeable without quotes on the command line, and I think if you substitute it into the wrong place in a script you'll end up with half a line where you had a full one.

**Comment by mamelara** [comment]
I'm okay with that. I just wasn't sure how necessary "/" was until your explanation. Is the space after architecture also required?

**Comment by tgamblin** [comment]
@mamelara: I'm not sure how best to deal with the kvps.  I like the spaces, but I would also like a spaceless form.  I was thinking about using `,`, but it can be ambiguous with version.

Are there other cases besides the filenames in `spack -d` that you need?  The filenames there don't need to be anything in particular -- in fact, they should probably go in the build stage and be copied to the install prefix on success, like `spack-build.out`/`build.out`.  We could just call them `spack-compiler.in` and `spack-compiler.out` in the build area and `compiler.in` and `compiler.out` in the install location.

We could also suffix all of those with `.txt` since they're actually text files.

What do you think?

**Comment by sleak-lbl** [comment]
I'm on board with making it "/" consistently, and I've updated the PR to make that change and to include a small change to lib/spack/env/cc to replace all non-"[A-Za-z0-9_-]" to "-" in $SPACK_SHORT_SPEC when generating the logfile name

Re: space after architecture (incidentally, what is "kvps"?) I'd be inclined to say "add the space in the sigil version but not the named version" - that was the named version is always a clean, user-must-fully-specify-exactly-what-they-want option, and the sigils are a shortcut proving chosen conventions

Semi-related: On another branch I'm tinkering with a refactor to make the format "rules" more declarative, rather than being explicitly re-implemented in a few places (eg the named vs sigil formats vs the parser), so it might prove better to drop this PR and use that one instead, once it's at a ready stage

Github tells me I have some conflicts in this PR, most are from files I haven't altered, I guess the branch I started from has PRs incorporated that the main develop branch does not, so it might also be worth separating this PR out (start it from the main develop branch instead)

more soon...

**Comment by alalazo** [comment]
@sleak-lbl Can this be closed or are you still working on it?

**Comment by sleak-lbl** [comment]
the base version this PR modified has changed too much to be a simple fix anymore, let's close this and I'll make a separate PR eventually for whatever parts still don't work...

**Pull request closed without merging**
