### PR TITLE
ADIOS2: Constrain HDF5 API to v1.12 

### PR DESCRIPTION
**Pull request by kwryankrattiger**
@chuckatkins

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
Test building on perlmutter was successful after this change

**Comment by alalazo** [comment]
There are failures in the pipeline building [adios2](https://gitlab.spack.io/spack/spack/-/jobs/1467601)

**Review by alalazo — CHANGES_REQUESTED** [review]
See pipeline failures

**Comment by ax3l** [comment]
cc @guj @chuckatkins : One pipeline error reads
```
source/h5vol/H5VolReadWrite.h:57:5: error:
              initializer element is not computable at load time
```

**Comment by kwryankrattiger** [comment]
It is interesting, the conduit errors are the inverse of the errors I got for adios2 due to calling a HDF5v1.12 API but the macros were mapped to the HDF5v1.8 API.

The ADIOS2 errors are new, I am getting this to build elsewhere, but I may move this to another environment to see if there is something else going on if forcing `hdf5 api=default` doesn't work.

**Comment by ax3l** [comment]
X-ref: https://github.com/ornladios/ADIOS2/issues/2991

No response from upstream yet. cc @pnorbert

**Comment by kwryankrattiger** [comment]
This was fixed in #28735

**Pull request closed without merging**
