### PR TITLE
SublimeText: add Sublime Text 4, build 4143

### PR DESCRIPTION
**Pull request by LRWeber**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed all version sha256 given the url-related changes.

**Comment by tldahlgren** [comment]
I am unable to install the package due to `librsvg@2.51.0 failures` (`cargo: error while loading shared libraries: libgit2.so.1.5: cannot open shared object file: No such file or directory`).

**Comment by tldahlgren** [comment]
`spack spec` works so I'll merge and let someone else report a build problem IF it occurs for them.

**Comment by LRWeber** [comment]
> I am unable to install the package due to `librsvg@2.51.0 failures` (`cargo: error while loading shared libraries: libgit2.so.1.5: cannot open shared object file: No such file or directory`).

I'm seeing the same issue now with a clean install.
We may be able to remove the listed runtime dependencies for the most recent versions of Sublime Text 3 and 4. Those versions appear to install (*much* faster) and run fine without them (unless other installations on my system are silently fulfilling those requirements).
Trying to run Sublime Text 2 without them generates errors.

**Pull request merged**
