### PR TITLE
gitlab ci: do not prune changed stacks

### PR DESCRIPTION
**Pull request by scottwittenburg**
If one of the spack stacks tested in gitlab changes in a PR, we should not do pruning on the specs in that stack.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
The WIP commit is there to demonstrate that this works, I'll link the pipeline here when it runs.  In that pipeline we should see the e4s stack actually build things because the stack itself was touched.  Once we see that it worked, I'll remove the WIP commit from the history.

As we hoped, nothing to rebuild in any stack except the touched one (pipeline [link](https://gitlab.spack.io/spack/spack/-/pipelines/110495)).

**Comment by scottwittenburg** [comment]
Not sure if gitlab will keep around the scheduled jobs for a pending pipeline if i cancel with another push now, or if I should wait a little longer before removing the WIP commit.

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Thank you!

**Comment by scottwittenburg** [comment]
Once the WIP commit touching the e4s stack was removed from the history, no jobs were scheduled in the resulting [pipeline](https://gitlab.spack.io/spack/spack/-/pipelines/111641).

**Pull request merged**
