### PR TITLE
Speed-up parsing specs and accessing their attributes

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by trws** [comment]
I see all good here.  As far as I can tell from traces, shlex is where we spend most of our parsing time (that and versions, but version is in progress).  If we could do something about the number of temporary sets and expensive sorts per operation that might be good too, but neither really shows up on a trace so probably best to do something simple and leave it until it shows up.

**Comment by tgamblin** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
@alalazo can you rebase this one?

**Comment by alalazo** [comment]
Rebased

**Review by trws — APPROVED** [review]

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
oops accidentally rebased this instead of squashing.  Oh well

**Pull request merged**
