### PR TITLE
BLT: new release v0.5.2

### PR DESCRIPTION
**Pull request by white238**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Review by davidbeckingsale — APPROVED** [review]

**Comment by tldahlgren** [comment]
Just noticed explicit request of @wspear so removed auto-merge.

**Comment by white238** [comment]
> Just noticed explicit request of @wspear so removed auto-merge.

Was this supposed to be @eugeneswalker ? I added him more for notification purposes. He was waiting for this to fix an Umpire issue.

Sorry I should have just mentioned him in the summary.

**Comment by tldahlgren** [comment]
> > Just noticed explicit request of @wspear so removed auto-merge.
> 
> Was this supposed to be @eugeneswalker ? I added him more for notification purposes. He was waiting for this to fix an Umpire issue.

Hmm.. yes.  My bad.  Must've confused this with the list for another PR I was reviewing earlier.  Apologies @eugeneswalker @wspear .

> 
> Sorry I should have just mentioned him in the summary.

Np.

**Review by eugeneswalker — APPROVED** [review]
Thank you!

**Pull request merged**
