### PR TITLE
Molden: Add new versions

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**
/cc @dev-zero

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed new versions available from the new site.

**Comment by tldahlgren** [comment]
@dev-zero Did you want to comment on this PR?

**Comment by dev-zero** [comment]
LGTM. Thanks!

**Comment by tldahlgren** [comment]
> LGTM. Thanks!

Thanks!

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Comment by RemiLacroix-IDRIS** [comment]
> Thank you for your contribution.

You're welcome. Thanks for reviewing and merging!

**Pull request merged**
