### PR TITLE
fix hip tests and bump hip-examples to 5.6.1

### PR DESCRIPTION
**Pull request by afzpatel**
To run tests:

`spack test run hip-examples`
`spack test run hip`

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the four new sha256 for `hip-examples`.

**Comment by tldahlgren** [comment]
I am unable to build the packages so cannot run the stand-alone tests.  Trying again.

**Comment by tldahlgren** [comment]
> I am unable to build the packages so cannot run the stand-alone tests. Trying again.

Nope.  I still can't install `hip-examples` even when using `--fresh` option.

**Comment by afzpatel** [comment]
> > I am unable to build the packages so cannot run the stand-alone tests. Trying again.
> 
> Nope. I still can't install `hip-examples` even when using `--fresh` option.

Which OS are you using and which version of hip-examples are you trying to install?

**Review by srekolam — APPROVED** [review]

**Review by renjithravindrankannath — APPROVED** [review]

**Pull request merged**
