### PR TITLE
python: detect Python from custom Xcode installations

### LINKED ISSUE #27017: Installation issue: clingo-bootstrap-spack
### Steps to reproduce the issue

Compile on macOS arm64 with `DEVELOPER_DIR=/Applications/Xcode-x.y.app/Contents/Developer` (modify as needed). `clingo-bootstrap-spack` fails with:

```
==> Installing clingo-bootstrap-spack-62s5iidrm32mm3u4ccoprwigg7ye2d77
==> No binary for clingo-bootstrap-spack-62s5iidrm32mm3u4ccoprwigg7ye2d77 found: installing from source
==> Error: RuntimeError: Unable to locate Python3.framework/Versions/3.8/Python3 libraries in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
/opt/glr/vtk/vtk-remoting-ci/.gitlab/spack/src/var/spack/repos/builtin/packages/python/package.py:811, in libs:
        808                return LibraryList(os.path.join(frameworkprefix, ldlibrary))
        809            else:
        810                msg = 'Unable to locate {0} libraries in {1}'
  >>    811                raise RuntimeError(msg.format(ldlibrary, libdir))
        812        else:
        813            library = self.config_vars['LIBRARY']
        814
```

There is no `/Applications/Xcode.app` on the machine because there are many such versions installed, so they all get renamed to not conflict. Our x86_64 machines are set up the same way and do not fail.

Build logs from CI: https://gitlab.kitware.com/vtk/remoting/-/jobs/6291139 (I don't see any log files around)

### Information on your system

```
% bin/spack debug report                                              
objc[87342]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f4ceec10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1187d42c8). One of the two will be
 used. Which one is undefined.
objc[87342]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f4ceec60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1187d4318). One of the two will be used. Whic
h one is undefined.
* **Spack:** 0.16.3-5064-8fd94e3114
* **Python:** 3.8.2
* **Platform:** darwin-bigsur-m1
* **Concretizer:** clingo
```

### Additional information

Cc: @alalazo @tgamblin 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by mathstuf**
Fixes: #27017

---
Cc: @alalazo

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
This env var isn't set for me on my macOS system. Is this something you expect to be present on all macOS systems? Or is this a random variable name that users are supposed to define themselves?

**Comment by mathstuf** [comment]
> This env var isn't set for me on my macOS system. Is this something you expect to be present on all macOS systems? Or is this a random variable name that users are supposed to define themselves?

If one does not install the command line tools or use `/Applications/Xcode.app/` as the Xcode installation, the stubs in `/usr/bin` require `DEVELOPER_DIR` to be set for them to work. Here are the docs: https://support.macincloud.com/support/solutions/articles/8000042681-how-to-utilize-a-different-xcode-version-for-build-process-on-mac

**Comment by mathstuf** [comment]
Ugh. Is it too much to ask the style CI check to output a diff of what it wants to see? I really don't like playing guessing games. A local `flake8` is fine now at least.

**Comment by adamjstewart** [comment]
> Ugh. Is it too much to ask the style CI check to output a diff of what it wants to see? I really don't like playing guessing games. A local `flake8` is fine now at least.

I would suggest using `black`, we'll be adding that to the style tests to auto-format things in the near future.

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Will wait a few more days to give @skosukhin a chance to review. Ping me again if it's been more than a week and I'll merge.

**Review by skosukhin — APPROVED** [review]

**Pull request merged**
