### PR TITLE
Permit packages that depend on Intel oneAPI packages to access sdk

### PR DESCRIPTION
**Pull request by mabraham**

### CODE REVIEW

**Comment by mabraham** [comment]
I'm not sure this is the right way to do this, but some oneAPI components have headers in `include` and others have some also in `sdk/include` (including Advisor, VTune, and Inspector). I would like to be able to have a Spack package X depend on e.g. VTune and let X `#include <ittnotify.h>` by teaching it how to build using the output of `spec["intel-oneapi-vtune"].package.sdk_include` with its build system and `-I`.

**Comment by mabraham** [comment]
@rscohn2 Can you review this please?

**Comment by rscohn2** [comment]
I did not consider the possibility that vtune would be used as a library. If you change it's package.py from IntelOneApiPackage to IntelOneApiLibraryPackage,  https://github.com/spack/spack/blob/1927ca1f3504468f072573e90db0f12c58306098/var/spack/repos/builtin/packages/intel-oneapi-vtune/package.py#L10

you will get default definition for headers and libraries:
https://github.com/spack/spack/blob/1927ca1f3504468f072573e90db0f12c58306098/lib/spack/spack/build_systems/oneapi.py#L161

If those defintions are not appropriate, you can override them in the vtune package.py, similar to way it was done for mpi: https://github.com/spack/spack/blob/1927ca1f3504468f072573e90db0f12c58306098/var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py#L157

Then your package can have a dependency on vtune and find header/libraries the same way it works for other spack packages.

**Comment by mabraham** [comment]
Thanks for the suggestions. As vtune, advisor, and inspector all have a common pattern, I implemented that in a new class and used that as their base. Further suggestions are welcome!

**Comment by mabraham** [comment]
I assume the CI error means it's looking at an older cached `oneapi.py` because the name `IntelOneApiLibraryVersionWithSdk` matches correctly. Or do we need to add the class to the core in an initial PR, then start to use it? **Edit** it seems to need to be added to another set of declarations

**Comment by rscohn2** [comment]
From reading the vtune documentation (https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2024-0/configuring-your-build-system.html), the application should use header files and libraries from the sdk directories. I don't know what the top level include/lib are used for. They seem to be almost the same as sdk. Based on that libs/headers should point at the sdk directory, and you would not need extra sdk_* variants in spack. I may be misunderstanding how you intend to use this so can you give me some more background?

**Comment by mabraham** [comment]
Good thought. I see in 2023.2 and 2022.3 that `include/ittnotify.h` merely includes `sdk/include/ittnotify.h` and as you have noted the documentation refers the user to `sdk/include/`. So probably `include/` is merely backward-compatibility support and we should do as you suggest and implement these `include` methods (and friends) to point to `sdk/include/` for these tools. I'll do that.

**Review by rscohn2 — APPROVED** [review]
Looks good. Thanks for adding support for analyzers API.

**Comment by mabraham** [comment]
I see code coverage CI tests are failing, but we have no tests at all to extend, and frankly don't really need them. How do we move forward?

**Comment by rscohn2** [comment]
The CI runs many things, but only a subset are required to pass. There is a required label when you view the CI results in the PR. codecov is not required. I set it to automerge so it will merge when all required tests have passed.

**Comment by mabraham** [comment]
I recalled that I never replied describing the use case. There is an `ittnotify` package distributed by all three tools that provides an API for applications to inform analysis tools about the state of the application, e.g. which timing region or task is starting or stopping. Then e.g. VTune can plot those events and regions as part of the trace and it is easier to understand what is happening.

One links a stub static library from the `sdk/lib64` and sets an environment variable at run time to point to another library to dlopen if you actually want such data collection. If you don't set the variable, then overhead is extremely low, so in many cases you can just build the app with such support and use it only when you want it.

**Comment by rscohn2** [comment]
Is there another spack package that links against ittnotify? Is it coming in another PR?

**Comment by mabraham** [comment]
> Is there another spack package that links against ittnotify? Is it coming in another PR?

For now, my development version of GROMACS uses ittnotify, but in future the upstream version will likely depend on it also, once they iron out how they want to support a range of such things.

**Pull request merged**
