### PR TITLE
gobject-introspection 1.7.2 also requires libffi@:3.3

### PR DESCRIPTION
**Pull request by lee218llnl**
My attempt to rebase #31349 blew up, so this is a replacement PR.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by tldahlgren** [comment]
Will defer merge decision to give @michaelkuhn another chance to comment.

**Comment by lee218llnl** [comment]
@spackbot run pipeline

**Comment by lee218llnl** [comment]
@alalazo @michaelkuhn Let me know if this looks good or if there are any changes required. Thanks.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by lee218llnl** [comment]
ping @alalazo not sure what to do when the pipeline fails

**Comment by tgamblin** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by lee218llnl** [comment]
pipeline failed again. What needs to be done to get this fixed? Sorry for the naive question, but is there any documentation on the workflow of when a PR gets merged? I'm worried that if this takes much longer I'm going to be asked to rebase again and I'll blow things up with git!

**Comment by alalazo** [comment]
@lee218llnl No worries, CI is a bit unstable these days. Let me rebase this one and see if it finally passes.

**Review by alalazo — APPROVED** [review]

**Comment by tgamblin** [comment]
The builds for `gobject-introspection` and all dependents *except* VisIt are working here.  VisIt failed with a pipeline error:

```
==> Installing xextproto-7.3.0-n7ya3ym55csqyx5t72anxluq57ods6qu
==> Removing failure mark on xextproto-7.3.0-n7ya3ym55csqyx5t72anxluq57ods6qu
==> Error: No binary for xextproto-7.3.0-n7ya3ym55csqyx5t72anxluq57ods6qu found when cache-only specified
==> Error: Failed to install xextproto due to SystemExit: 1
==> Error: xextproto-7.3.0-n7ya3ym55csqyx5t72anxluq57ods6qu: Package was not installed
```

But that is unrelated to the PR. I'm going to merge this b/c I'm pretty sure *this* package is working.

**Comment by lee218llnl** [comment]
thanks all!

**Pull request merged**
