### PR TITLE
dealii: add new version v9.6.0 and variant `complex`

### PR DESCRIPTION
**Pull request by adamqc**

### CODE REVIEW

**Comment by luca-heltai** [comment]
<s>Duplicate of #45554</s>

**Comment by luca-heltai** [comment]
Can you then please remove the 9.6.0 addition, change the title of the PR, and make this only about the complex variant?

Thanks.

**Comment by luca-heltai** [comment]
Never mind. Added to the other PR.

**Comment by adamqc** [comment]
Thanks.

**Pull request closed without merging**
