### PR TITLE
superlu-dist:  -std=c99 prevents usage of putenv()

### PR DESCRIPTION
**Pull request by balay**
cc: @xiaoyeli

### CODE REVIEW

**Review by liuyangzhuan — APPROVED** [review]

**Comment by haampie** [comment]
What compiler fails with this? I suppose someone added this flag to solve another problem: superlu-dist doesn't set a C standard themselves, and the compiler default standard is too old?

For `putenv` see https://man7.org/linux/man-pages/man3/putenv.3.html, they should add a missing define `_XOPEN_SOURCE`. Maybe contribute that upstream?

**Comment by balay** [comment]
You mean `#define _XOPEN_SOURCE`?

I think the preferred fix here is to not force `c99` [I believe this option is  not needed]

**Comment by haampie** [comment]
> You mean `#define _XOPEN_SOURCE`?

Yes, or `CFLAGS=-D_XOPEN_SOURCE` on the command line (should really be `CPPFLAGS`, but CMake doesn't respect that). You can also add this in `flag_handler`.

> I think the preferred fix here is to not force `c99` [I believe this option is not needed]

Specifying the C standard is always needed because it's a property of the source code. Package developers are responsible for setting this in the first place (through `CMAKE_C_STANDARD`). I'll make [an issue upstream](https://github.com/xiaoyeli/superlu_dist/issues/152). 

Assuming the flag was added in Spack to ensure `superlu-dist` builds with older compilers that default to `-std=c89` if not specified, removing the flag will fix your issue [but bring back the original problem](https://github.com/xiaoyeli/superlu_dist/issues/46).

**Comment by balay** [comment]
Now that the issue is resolved upstream - perhaps we can merge this PR into spack?

**Comment by liuyangzhuan** [comment]
Sure, could you setup a PR?

**Comment by xiaoyeli** [comment]
I implemented the suggestion in the commit today:
https://github.com/xiaoyeli/superlu_dist/commit/e2076918152efa9a6d44bf87e4c7fef9efd6d5d2

**Comment by balay** [comment]
> Sure, could you setup a PR?

I'm not sure what you mean. This is the PR change for superlu-dist [remove -std=c99 flag] to spack.

Perhaps @haampie can approve and merge this in.

**Comment by liuyangzhuan** [comment]
> > Sure, could you setup a PR?
> 
> I'm not sure what you mean. This is the PR change for superlu-dist [remove -std=c99 flag] to spack.
> 
> Perhaps @haampie can approve and merge this in.

My bad, never mind.

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
