### PR TITLE
isl: add v0.25

### PR DESCRIPTION
**Pull request by alecbcs**
Add ISL v0.25.

### CODE REVIEW

**Comment by alecbcs** [comment]
@iarspider are you interested in signing up as a maintainer for ISL?

**Comment by iarspider** [comment]
@alecbcs no. I'm not doing spack anymore.

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by alecbcs** [comment]
> @iarspider are you interested in signing up as a maintainer for ISL?

No worries, thank you for your reply!

**Pull request merged**
