### PR TITLE
py-tensorflow: disable h5py/hdf5 mpi variant(s) if tensorflow is ~mpi

### PR DESCRIPTION
**Pull request by aweits**
Also allow h5py to actually turn off mpi support in hdf5.
This fixes some crash-on-init type problems for me.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by adamjstewart** [comment]
In the past we've been hesitant to propagate variant restrictions unless they were absolutely required. It sounds like they are required here, so this change looks good to me. It might be good to add a comment specifying that this is not just a preference but a requirement.

**Review by adamjstewart — APPROVED** [review]

**Comment by sethrj** [comment]
@aweits Can you please provide more information on how `py-h5py~mpi ^hdf5+mpi` crashes? The change from this PR breaks an environment I've got that works as expected. As @adamjstewart says, variant propagation has been discussed repeatedly, *and* this is more than just variant propagation at play.

I'm opening a PR to revert this change. I think if the crash is specific to py-tensorflow then the restriction on py-h5py should be present there as `depends_on('py-h5py~mpi', when='~mpi')`.

**Comment by aweits** [comment]
Crashes were as apparent as build errors like the following, or more subtle as in random runtime crashes during a non-MPI run referencing MPI-related calls.

```shell
ERROR: /dev/shm/aweits/spack-stage/spack-stage-py-tensorflow-2.4.1-mdi7qlt7ddtw77iz6uzl63qg5fom27mz/spack-src/tensorflow/python/tools/BUILD:226:10 Executing genrule //tensorflow/p
ython/keras/api:keras_python_api_gen failed (Segmentation fault): bash failed: error executing command 
  (cd /tmp/spackuhzzd6_h/e65b9905e462d101ae50cd7e99c0dd6c/execroot/org_tensorflow && \
```
```shell
[skl-a-00:19619:0:19619] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x20)
==== backtrace (tid:  19619) ====
 0 0x0000000000052dce ucs_debug_print_backtrace()  /dev/shm/aweits/spack-stage/spack-stage-ucx-1.9.0-qxswn4w2wz25oqfwqx7i7w63qxusnvv7/spack-src/src/ucs/debug/debug.c:656
 1 0x00000000000040fc component_open()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/mca/ptl/tcp/ptl_tcp_component.c:270
 2 0x00000000000e0683 open_components()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/mca/base/pmix_mca_base_components_open.c:120
 3 0x00000000000e0683 pmix_mca_base_framework_components_open()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/mca/base/pmix_mca_base_components_open.c:67
 4 0x000000000010402d pmix_ptl_open()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/mca/ptl/base/ptl_base_frame.c:119
 5 0x00000000000e82b5 pmix_mca_base_framework_open()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/mca/base/pmix_mca_base_framework.c:180
 6 0x000000000009a9c9 pmix_rte_init()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/runtime/pmix_init.c:360
 7 0x000000000004e6a3 PMIx_Init()  /home/jchits/rpmbuild/BUILD/pmix-3.2.1/src/client/pmix_client.c:560
 8 0x00000000000b446b ext3x_client_init()  ???:0
 9 0x000000000006757e rte_init.part.0()  ess_singleton_module.c:0
10 0x00000000000daf94 orte_init()  ???:0
11 0x0000000000213806 ompi_mpi_init()  ???:0
12 0x00000000000a9329 MPI_Init_thread()  ???:0
13 0x000000000003407c __pyx_f_6mpi4py_3MPI_bootstrap()  /dev/shm/aweits/spack-stage/spack-stage-py-mpi4py-3.0.3-nuvuokmouqqmagg7pvnwe4y6jdnjjlpt/spack-src/src/mpi4py.MPI.c:7158
14 0x000000000003407c __pyx_pymod_exec_MPI()  /dev/shm/aweits/spack-stage/spack-stage-py-mpi4py-3.0.3-nuvuokmouqqmagg7pvnwe4y6jdnjjlpt/spack-src/src/mpi4py.MPI.c:161911
15 0x00000000000e1b1a PyModule_ExecDef()  /tmp/aweits/spack-stage/spack-stage-python-3.8.7-6httncpid2cd7gre5cpxcxswvrq5qrlc/spack-src/Objects/moduleobject.c:414
16 0x000000000019dd0b _imp_exec_dynamic()  /tmp/aweits/spack-stage/spack-stage-python-3.8.7-6httncpid2cd7gre5cpxcxswvrq5qrlc/spack-src/Python/import.c:2169
```

**Comment by sethrj** [comment]
@aweits those backtraces show the crash occurring from within a call to `mpi4py`. Does TensorFlow independently import `mpi4py`? Because our use particular  case is such that `mpi4py` *cannot* be imported, and disabling parallel h5py is what allows us to do that.

Maybe we need to add `conflicts('py-mpi4py', when='~mpi')` to py-h5py?

**Comment by aweits** [comment]
> @aweits those backtraces show the crash occurring from within a call to `mpi4py`. Does TensorFlow independently import `mpi4py`? Because our use particular case is such that `mpi4py` _cannot_ be imported, and disabling parallel h5py is what allows us to do that.
> 
> Maybe we need to add `conflicts('py-mpi4py', when='~mpi')` to py-h5py?

AFAIK tensorflow does not pull in mpi4py directly, and these problems appeared once tensorflow started depending on h5py. I need to poke at why I needed to disable mpi on hdf5 as well as h5py to succeed here.

**Pull request merged**
