### PR TITLE
qt+webkit: fix missing dependencies and gcc11 compatibility

### LINKED ISSUE #24254: qt+webkit does not build
I wanted to build qt+webkit but ran into multiple problems. I need version 5.12.10 as a dependency for a package I want to build.

I tried to build 
```
$ spack install qt+webkit@5.12.10 %gcc@10.3.0
```
the first problem is that the python2 requirement is not set. This can easily be fixed by

```diff
-    depends_on("python@2.7.5:2.999", when='@5.14: +webkit', type='build')
+    depends_on("python@2.7.5:2.999", when='+webkit', type='build')
```

Then qt builds but webengine does not due to a missing mesa dependency
```
khronos development headers appear to be missing (mesa/libegl1-mesa-dev)
QtWebEngine will not be built.
```

When building `qt+webkit+opengl@5.12.10 %gcc10.3.0` (since gl has a mesa dependency), now nss is missing
```
A suitable version of nss could not be found.
QtWebEngine will not be built.
```
but nss is not in spack

Also the following combinations build qt (with the fix above) but do not build webengine
- `qt+webkit@5.14.2 %gcc@9.3.0` -> missing mesa
- `qt+webkit@5.15.2 %gcc@9.3.0` -> missing nss

I tried these combinations because I found them in #17270

Then I tried the most current combination `qt+webkit@5.15.2 %gcc@11.1.0` but here qt does not build.

@sethrj maybe you can help

### Information on your system

* **Spack:** 0.13.4-8281-849943c63d
* **Python:** 3.5.3
* **Platform:** linux-debian9-piledriver
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by manuelakuhn**
This depends on #24363 and #24364 to be merged to work.
Fixes #24254

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Review by sethrj — DISMISSED** [review]
Nice, looks great! Thanks for the patch.

**Comment by sethrj** [comment]
Even though this requires the other merges to completely work, it doesn't look like merging this one first will break anything.

**Comment by manuelakuhn** [comment]
Sorry, the patch for gcc11 only fixes webkit for the newest version (5.15.2). It seems that something went wrong on my initial tests. I have updated the version restriction.

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@manuelakuhn Apologies for the repeatedly failing CI. Can you please fix the new style checks (import order) and push again to this branch?

**Comment by manuelakuhn** [comment]
@alalazo No problem :-) Here you go. Thanks for keeping an eye on this!

**Review by alalazo — DISMISSED** [review]

**Comment by manuelakuhn** [comment]
Sorry, I always updated my fork via the github interface (by pushing "fetch upstream") und then did a `git pull` in my local repo. This seems to produce problems because not everything is updated (e.g. release tags were missing) and this also resulted in different `spack style` results than the pipeline.

**Comment by manuelakuhn** [comment]
Sorry forgot to rebase my branch resulting in different `spack style` results than the pipeline. This is fixed now.

**Review by sethrj — APPROVED** [review]

**Review by alalazo — APPROVED** [review]
This appear to change just the `+webkit` flavor of qt, which is not selected by default, so force merging it since Gitlab failed to run too many times.

**Pull request merged**
