### PR TITLE
gaudi: upstream patch when @38.1 for missing #include <list>

### PR DESCRIPTION
**Pull request by wdconinc**
This PR adds the `<list>` include, per https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1587.

### CODE REVIEW

**Review by jmcarcell — APPROVED** [review]

**Comment by wdconinc** [comment]
@tmadlener Can you comment on whether you identified if this missing `<list>` header became apparent due to any specific change between 38.0 and 38.1, or if it was related to changing indirect includes through boost? Basically, is this `when=@38.1 ^boost@1.85:` or much broader?

I'm also going to add the removal of the boost header, but that will likely need a propagation backwards in versions, or a conflicts between boost-1.85 and anything older than gaudi-38.

**Comment by tmadlener** [comment]
I am not entirely sure what exactly triggered this as I rebuilt the complete stack so there might be other dependencies that changed as well. Another possible reason could be switching to c++20 with gcc12.3, which might also have an influence on the internal organization of the STL and transient includes.

**Comment by andresailer** [comment]
For the LCG stacks (dev3 with Gaudi-master) Gaudi started failing when moving from boost 1.84 to 1.85, same compiler etc, no other change I would consider relevant there.

**Review by tmadlener — APPROVED** [review]

**Comment by wdconinc** [comment]
Thanks for the feedback. I've enabled the patch for all versions, since this is a missing header bug in all versions since 29 (at least). It was just surfaced by boost but not caused by it.

**Comment by wdconinc** [comment]
Then this just need a review by either @vvolkl or @drbenmorgan, as maintainers.

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
