### PR TITLE
adding option for spack to install all versions of a package

### PR DESCRIPTION
**Pull request by vsoch**
This adds an option to install all versions of a package. I don't expect this PR to be merged - I made it for myself and am putting here if anyone is interested.  

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
It makes no sense how merging develop into mine and tests fail? Oy vey.

**Comment by tldahlgren** [comment]
> It makes no sense how merging develop into mine and tests fail? Oy vey.

Looks like you need to run `spack commands --update-completion` and merge the update.

**Comment by vsoch** [comment]
I tried doing this locally and there was no update to the change file - not sure if my branch is wonky now.

**Comment by vsoch** [comment]
It worked! My local clone was wonky but when I cloned the branch fresh it updated. phew.

**Comment by tldahlgren** [comment]
This PR needs to rebase to a newer develop to get the `hpx` fix for the pipeline.  It also needs to have the conflicts resolved.

**Comment by vsoch** [comment]
Yeah it's okay I can just do this at some point in the future when somebody wants/needs it - just using for research now. Thanks!

**Pull request closed without merging**
