### PR TITLE
Fix opengl and mesa handling of +glvnd

### PR DESCRIPTION
**Pull request by opadron**
If `opengl` is acting as the underlying implementation that `libglvnd` dispatches `gl` calls to, then `opengl` does not provide `gl`, not directly at least; `libglvnd-fe` takes on this role.

### CODE REVIEW

**Comment by opadron** [comment]
@chuckatkins fyi, looks like an oversight when I was rebasing #14572.

**Comment by opadron** [comment]
As mentioned in my last commit, I'm finding more issues that I'm pretty sure were introduced when I botched the rebase from #14572.

**Comment by xjrc** [comment]
@opadron: Let me know when this is ready and I'll give it a review (things look to be in development at present).

**Comment by chuckatkins** [comment]
Closing in favor of #17682

**Pull request closed without merging**
