### PR TITLE
numactl: no-op needed if configure can't find TLS

### PR DESCRIPTION
**Pull request by rblake-llnl**

### CODE REVIEW

**Review by becker33 — DISMISSED** [review]

**Review by bvanessen — DISMISSED** [review]
@rblake-llnl Thanks this works great.

**Comment by rblake-llnl** [comment]
Also submitted upstream:

https://github.com/numactl/numactl/pull/103

When the above PR gets merged into a numbered revision, the `when` clause on the patch here will need to be fixed.

**Comment by tldahlgren** [comment]
@rblake @becker33 Quick check before this PR gets merged.  Is this approach preferable to the one provided in #20319 ?

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Is a patch-based approach preferable to forcing `autoreconf`?  (See reference above, i.e., #20319 .)

**Comment by rblake-llnl** [comment]
The `autogen.sh` just calls autoreconf with --install and --symlink.  No care is taken to make sure that you're using a system autoreconf that spack knows about.  I don't think this will fix the issue on all build systems.

This patch fixes the underlying issue: there's a bug in the configure.ac.  Upstream has already accepted the pull request to fix this.

https://github.com/numactl/numactl/pull/103

Now that upstream has the fix, I'm changing the PR to properly guard the application of the patch.

**Comment by tldahlgren** [comment]
> The `autogen.sh` just calls autoreconf with --install and --symlink. No care is taken to make sure that you're using a system autoreconf that spack knows about. I don't think this will fix the issue on all build systems.

I can see your point.  The PR I pointed you to fixed the issue I've been having on one of the LC machines for at least the last couple of weeks, which is why I merged it earlier today.

> 
> This patch fixes the underlying issue: there's a bug in the configure.ac. Upstream has already accepted the pull request to fix this.

I noticed your comment about the upstream bugfix so clearly preferred.

**Comment by tldahlgren** [comment]
@rblake-llnl @becker33 Since this is the preferred solution, should the other PR be reverted?

**Review by tldahlgren — APPROVED** [review]
LGTM.

**Pull request merged**
