### PR TITLE
Add checksum for py-sniffio 1.3.0

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@spackbot run pipeline

**Pull request merged**
