### PR TITLE
IQ-TREE: Add version 2.2.2.7

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version tag exists.  Will defer merge to give @ilbiondo time to comment.

**Review by ilbiondo — APPROVED** [review]
Looks good to me.

**Comment by tldahlgren** [comment]
Not clear why we're getting a pending on the CI job. Let's see if this frees it up.

@spackbot run pipeline

**Comment by tldahlgren** [comment]
That didn't work so I'm going to try Update branch.

**Comment by RemiLacroix-IDRIS** [comment]
> That didn't work so I'm going to try Update branch.

This seems to have made the trick, thanks @tldahlgren and @ilbiondo!

**Pull request merged**
