### PR TITLE
crmc: add v2.0.1

### PR DESCRIPTION
**Pull request by alecbcs**
Add crmc v2.0.1.

**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Comment by tldahlgren** [comment]
@alecbcs Any idea why the entire file is flagged as changed instead of just the changes you made?

**Comment by alecbcs** [comment]
I noticed that as well. Perhaps an encoding difference between Unix and Windows? I tried this multiple times but opening the file and recommitting it ended up with the same diff in git.

**Comment by alecbcs** [comment]
@adamjstewart have you seen something like this in a git diff before? Could this be an encoding error with the previous file?

**Review by bernhardkaindl — APPROVED** [review]
@alecbcs The diff is because the file had DOS (CR+LF) line endings when it was initially merged in 2022, and your commit fixes the file to have UNIX line endings (just LF).

You see this in the `git log` for this file.

Checked using `diff -w` which ignores white space,
I confirm that you only added the new version.

We should preferably add a check for this in spack style or our CI checks,
but the problem is thankfully not wide-spread. Only one other spack recipe has the same problem (can be checked with `file  ....|grep CRLF`)

**Comment by adamjstewart** [comment]
That's probably something we would want to configure in git: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Review by bernhardkaindl — APPROVED** [review]
@adamjstewart Good idea, opened @36677 to enforce this thru `.gitattributes` as documented on the page you referred to.

**Pull request merged**
