### PR TITLE
+ Add version 5.0 download for SuperLU_DIST.

### PR DESCRIPTION
**Pull request by KineticTheory**
SuperLU_DIST version 5.0.0 was released April 8.  Add option to download and build.

### CODE REVIEW

**Comment by davydden** [comment]
could you please check if `petsc` and `trilinos` build with `5.0.0` and if not, declare their dependencies as `:4.3`? Otherwise as soon as this PR is merged, the two main linear algebra packages might become broken.

**Comment by davydden** [comment]
also related to the discussion here https://github.com/LLNL/spack/issues/753

**Comment by davydden** [comment]
alternatively mark the old version as 
```
version('4.3', 'ee66c84e37b4f7cc557771ccc3dc43ae',, preferred=True)
```` 
with a comment that `petsc` and `trilinos` are not tested with `5.0.0`.

**Comment by KineticTheory** [comment]
@davydden Marked superlu-dist 4.3 as preferred and added a note about petsc and trilinos.

**Comment by davydden** [comment]
thanks!

**Comment by tgamblin** [comment]
@davydden: does it make sense to mark petsc and trilinos with more specific `depends_on()` constraints?  Seems like they need to say:

```
    depends_on('SuperLU_DIST@:4.3', when='@:<some version>')
    depends_on('SuperLU_DIST@5:', when='@<some version++>:')
```

Do you know the compatibility rules here?

**Comment by davydden** [comment]
@tgamblin no, i don't. But i created an issue for that https://github.com/LLNL/spack/issues/901  I will have a look next time i install them.

**Comment by tgamblin** [comment]
Thanks!

**Pull request merged**
