### PR TITLE
hpctoolkit: Add `build_system=meson`

### PR DESCRIPTION
**Pull request by blue42u**
HPCToolkit `@develop` now can optionally be built via Meson. This PR adds the `build_system=(autotools|meson)` variant and splits the build-system-dependent pieces into `AutotoolsBuilder` and `MesonBuilder`. The default is to build with `autotools`.

As of writing, the Meson is simply a wrapper around the original Autotools build, hence the build requires a native file listing install prefixes of all dependencies (which are internally mapped to `--with-{pkg}={prefix}` arguments for `./configure`). This is an unconventional but temporary state of affairs until the build system is fully ported to Meson and conventional dependency acquisition techniques like `pkg-config` and `cmake` are practically available.

Maintainer: @mwkrentel

### CODE REVIEW

**Comment by blue42u** [comment]
@spackbot fix style

**Review by alalazo — COMMENTED** [review]
Can we move the `Builder`s below the `Package` (not technically required, but all other packages do like that)?

**Review by mwkrentel — APPROVED** [review]
I'm not fully sold on the usefulness of this approach as an
intermediate step towards a full meson build, but whatever.
However, I approve.    @alalazo you may merge.

**Comment by mwkrentel** [comment]
There was a change to `hpctoolkit@develop` and now the meson recipe
here fails for `dyninst@master`.
```
$ spack install hpctoolkit@develop build_system=meson ^dyninst@master
...
WARNING: Could not find and exact match for the CMake dependency Dyninst.

However, Meson found the following partial matches:

    ['Dyninst::Boost', 'Dyninst::Boost_headers', 'Dyninst::ElfUtils',
    'Dyninst::TBB', 'Dyninst::common', 'Dyninst::dynElf',
    'Dyninst::dynDwarf', 'Dyninst::instructionAPI',
    'Dyninst::symtabAPI', 'Dyninst::parseAPI', 'Dyninst::pcontrol',
    'Dyninst::stackwalk', 'Dyninst::patchAPI', 'Dyninst::dyninstAPI',
    'Dyninst::dynC_API', 'Dyninst::dyninstAPI_RT',
    'Dyninst::dyninstAPI_RT_static']

Using imported is recommended, since this approach is less error prone
and better supported by Meson. Consider explicitly specifying one of
these in the dependency call with:

    dependency('Dyninst', modules: ['Dyninst::<name>', ...])

Meson will now continue to use the old-style Dyninst_LIBRARIES CMake
variables to extract the dependency information since no explicit
target is currently specified.

Run-time dependency dyninst found: NO (tried pkgconfig)

../spack-src/meson.build:64:14: ERROR: Dependency "Dyninst" not found, tried pkgconfig
```

So, the `meson` build section should be updated to handle dyninst either at 12.3.0 or master.

**Comment by blue42u** [comment]
@mwkrentel This is a bug in HPCToolkit('s new build system), not in the Spack recipe changes here. Once a fix lands in HPCToolkit `develop` this Spack recipe will operate as intended with either `dyninst@master` or `dyninst@12.3.0`.

EDIT: This has been fixed on the HPCToolkit side now, both `^dyninst@12.3` and `^dyninst@master` build successfully with the recipe given here.

**Review by tgamblin — APPROVED** [review]

**Comment by mwkrentel** [comment]
@tgamblin Thanks!

**Pull request merged**
