### PR TITLE
py-torchgeo: kornia backwards-incompatible change

### PR DESCRIPTION
**Pull request by adamjstewart**
Latest Kornia release contained a backwards-incompatible change that broke TorchGeo: https://github.com/microsoft/torchgeo/pull/1123

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
