### PR TITLE
Provide new package: MOAB

### PR DESCRIPTION
**Pull request by KineticTheory**
This commit provides a basic MOAB installation.  MOAB has many optional features that I did not setup or test.  I will leave the addition of those variants to someone who is actually using them.

Information on MOAB: https://bitbucket.org/fathomteam/moab

MOAB is a component for representing and evaluating mesh data. MOAB can store structured and unstructured mesh, consisting of elements in the finite element 'zoo.' The functional interface to MOAB is simple yet powerful, allowing the representation of many types of metadata commonly found on the mesh. MOAB is optimized for efficiency in space and time, based on access to mesh in chunks rather than through individual entities, while also versatile enough to support individual entity access

### CODE REVIEW

**Comment by tgamblin** [comment]
@KineticTheory: Thanks!

We added `flake8` checking to Spack recently -- this one is hitting some `pep8` checks.  From the Travis output:
```
var/spack/repos/builtin/packages/moab/package.py:5: [E302] expected 2 blank lines, found 1
var/spack/repos/builtin/packages/moab/package.py:6: [E501] line too long (504 > 79 characters)
var/spack/repos/builtin/packages/moab/package.py:14: [E501] line too long (98 > 79 characters)
var/spack/repos/builtin/packages/moab/package.py:15: [E501] line too long (88 > 79 characters)
var/spack/repos/builtin/packages/moab/package.py:27: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/moab/package.py:29: [E261] at least two spaces before inline comment
var/spack/repos/builtin/packages/moab/package.py:45: [E202] whitespace before ']'
var/spack/repos/builtin/packages/moab/package.py:50: [E202] whitespace before ')'
```

**Comment by KineticTheory** [comment]
@tgamblin Can you point me to a formatting guide or a properly formatted package.py? How do I run flake8 locally before pushing my files to github?

**Comment by tgamblin** [comment]
Oh, sorry -- it's in the README but onyx since yesterday.  There is a script (`share/spack/qa/run-flake8`), which will do the same thing as Travis, only locally.  It must be run from the top-level repo directory. Working on a spack command, but not there yet.

**Comment by adamjstewart** [comment]
You can see further comments left for me by @alalazo and @tgamblin [here](https://github.com/adamjstewart/spack/pull/1)

But yeah, this should definitely be in the documentation...

**Comment by adamjstewart** [comment]
Ah, just saw the README. That may be sufficient?

**Comment by KineticTheory** [comment]
@adamjstewart Thanks for the pointer to the README.  I haven't looked at that recently, but I will be sure to follow the recommendations in the Contributions section from now on.

Also - Since I don't have an easy way to install flake8 on my target system (I don't have root), I added it as a spack package.

**Comment by tgamblin** [comment]
@KineticTheory: thanks for doing that!  I was hoping someone would 😄

**Pull request merged**
