### PR TITLE
change mode to ccld for loopopt edit

### PR DESCRIPTION
**Pull request by frankwillmore**
For configure (e.g. for hdf5) to pass, this option needs to be pulled out when invoked in ccld mode. It's not clear whether it also still needs to be done in ld mode.

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]
Thank you!

**Review by tgamblin — CHANGES_REQUESTED** [review]
I thought the previous version fixed something too?  Are you sure we shouldn't do it in `ld` mode?  Can you confirm?

**Comment by frankwillmore** [comment]
I thought it had fixed the issue but I still saw it after that. After some digging, my guess is that I was able to get hdf5 to build with ifort instead of ifx. Lot of overlapping changes occurring at the time, as it were. There are still outstanding issues building hdf5 with ifx, and Intel is looking into what appears to be a compiler bug, but this manifests during build and is likely a separate issue. 

I have verified that the making the edit in 'ccld' mode removes the -loopopt=0 and enables hdf5 to pass configure. It should be fine to make the edit in 'ld' mode as well, but I have not tested that and didn't include an -or- condition for it.  

If this makes sense, I can revise the tests to fit.

**Review by frankwillmore — COMMENTED** [review]
I've re-worked the tests to reflect the desired behavior for the prescribed modes of detection. It was necessary to add a "-c" flag to the test_args in order for cc to be detected in cc mode (default is ccld mode) while insuring that the edit is still performed in ccld mode. I believe all tests are correct now, that the modification gives the desired outcome (removal of -loopopt for ld and ccld modes), and all tests are passing. Should be ready to merge.

**Review by eugeneswalker — APPROVED** [review]

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
