### PR TITLE
VisIt: Add conduit and mfem variants.

### PR DESCRIPTION
**Pull request by brugger1**
Added conduit and mfem variants to the VisIt package.

This was tested on crusher.olcf.ornl.gov.

### CODE REVIEW

**Comment by brugger1** [comment]
The failure is expected. My mfem PR needs to go in before this change. My hope was that making it a draft PR it wouldn't run the tests, but it did.

**Review by cyrush — DISMISSED** [review]

**Review by cyrush — DISMISSED** [review]

**Comment by brugger1** [comment]
@spackbot run pipeline

**Comment by brugger1** [comment]
I think this is ready to go. The only failure was the readthedocs.org:spack test and I didn't change anything that would impact that test.

**Comment by brugger1** [comment]
Updating the branch fixed the test suite failure. Of course now it shows lots of bogus changes because of all the changes that happened on develop.

**Comment by brugger1** [comment]
My changes are to `var/spack/repos/builtin/packages/visit/package.py`.

**Comment by cyrush** [comment]
Looks like there was some sort issue when you merged develop into your branch. 
Might have to try a clean PR with just visit package.

**Comment by brugger1** [comment]
Closing and opening a new one.

**Pull request closed without merging**
