### PR TITLE
zlib: add 1.2.12, 1.2.13

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed 2 new sha256.

**Comment by tldahlgren** [comment]
Looks like pod issues for at least one of the two pipeline stacks.

@spackbot run pipeline

**Comment by haampie** [comment]
Hopefully not *too* confusing: tensorflow packages failed to build here because they couldn't download zlib, but that has nothing to do with this zlib PR, it's rather you need #33349, already on develop.

**Comment by tldahlgren** [comment]
> Hopefully not _too_ confusing: tensorflow packages failed to build here because they couldn't download zlib, but that has nothing to do with this zlib PR, it's rather you need #33349, already on develop.

I should've looked more closely at the other pipelines.

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Pull request merged**
