### PR TITLE
py-anuga: add new package

### LINKED ISSUE #246: Using SPACK for supporting wider architecture support
Can we add this package to spack packages to use it on multiple hardware.

https://github.com/spack/spack

### LINKED ISSUE #19877: Porting of Anuga code
Dear Team,

Wanted to integrate Anuga code to spack list.
https://github.com/GeoscienceAustralia/anuga_core

### PR DESCRIPTION
**Pull request by adamjstewart**
Closes #19877 
Closes https://github.com/GeoscienceAustralia/anuga_core/issues/246

Unable to test this on macOS due to https://github.com/GeoscienceAustralia/anuga_core/issues/247

@samcom12 can you test this?

### CODE REVIEW

**Review by samcom12 — CHANGES_REQUESTED** [review]
Anuga also supports MPI.
https://anuga.anu.edu.au/wiki/AnugaParallel

**Review by samcom12 — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Comment by samcom12** [comment]
@adamjstewart how can we use the 2to3 tool to build/install py-anuga with Python3?

**Comment by adamjstewart** [comment]
You would likely need to run `2to3` on all of the source code for anuga, then manually fix a few things, then submit the code upstream and get it reviewed. You could also add a massive patch to the package to do this.

**Comment by samcom12** [comment]
Actually, there is a separate git branch for Python3 support, **anuga_py3** which compiles fine with python3.8. Can we add that in py-anuga package?

**Comment by adamjstewart** [comment]
Yes, that should be easy to add. Want to open a PR?

**Comment by samcom12** [comment]
@adamjstewart  For enabling MPI support in py-anuga we need to export-
**_export ANUGA_PARALLEL="mpich2"_**
or
**_export ANUGA_PARALLEL="openmpi"_**

How can we add an export statement in py-anuga? I have tried it hard but couldn't get it working.

Reference link- 
_https://anuga.anu.edu.au/wiki/AnugaParallel_

**Comment by samcom12** [comment]
> Yes, that should be easy to add. Want to open a PR?

I have tried it but couldn't get it working. Can you please try it out?

Link- https://github.com/GeoscienceAustralia/anuga_core/tree/anuga_py3

**Comment by adamjstewart** [comment]
For exporting environment variables, you can do something like:
```python
def setup_build_environment(self, env):
    if self.spec['mpi'].name == 'mpich':
        env.set('ANUGA_PARALLEL', 'mpich2')
    elif self.spec['mpi'].name == 'openmpi':
        env.set('ANUGA_PARALLEL', 'openmpi'
```
For adding a new version for the Python 3 branch, see https://spack.readthedocs.io/en/latest/packaging_guide.html#fetching-from-code-repositories

**Pull request merged**
