### PR TITLE
[kripke] Fix OpenMP flags

### PR DESCRIPTION
**Pull request by stephenmsachs**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by stephenmsachs** [comment]
@vsrana01 can you please review.

**Comment by alalazo** [comment]
@stephenmsachs Is this something you still want? If so, can you resolve conflicts and ping me?

**Comment by stephenmsachs** [comment]
I am no longer working on Kripke. I'll open a new PR if I revisit this.

**Pull request closed without merging**
