### PR TITLE
Pkg graphviz

### PR DESCRIPTION
**Pull request by KineticTheory**
I had trouble installing graphviz because Perl development headers were not installed.  This PR provides a variant ~perl that disables building Perl bindings.  Default behavior remains unchanged.

Another option is to provide Perl and support extensions like we do for Python.

### CODE REVIEW

**Comment by adamjstewart** [comment]
#105 is an ancient PR that no one has touched. It seems to provide some Perl support. We may want to take another look at it.

**Comment by tgamblin** [comment]
I like this but honestly I'd make the default be to build without perl, and allow the `perl` flag to enable it.  Can you change that?  We can add an optional dependency when the perl stuff gets a bit more robust.

**Comment by KineticTheory** [comment]
@tgamblin I changed the package to make `--disable-perl` the default. 

For my test machine, attempting to build `graphviz+perl` will fail unless `perl-devel` and `perl-ExtUtils-Embed` are installed. There maybe other dependencies, but those are the two that I had to install to get `graphviz+perl` working.

**Comment by tgamblin** [comment]
@KineticTheory: thanks!

Technically there should be better perl support in Spack, but I don't think I should make you package perl to get this in, especially if the default is no perl :).  As @adamjstewart mentioned, there is *some* perl support in #105  but I believe the PR had some issues that I did not get around to addressing (sorry everyone!).  I can revisit that later.

**Pull request merged**
