### PR TITLE
Use satisfies instead of if ... in spec in b* and c* packages

### PR DESCRIPTION
**Pull request by aurianer**

### CODE REVIEW

**Comment by hainest** [comment]
The changes to the Boost package look good.

A general question:

Would it be better/equivalent to translate `"+a" in self.spec and "+b" in self.spec` to `self.spec.satisfies("+a+b")` instead of `self.spec.satisfies("+a") and self.spec.satisfies("+b")`? I don't know if there is a way to combine specs for a logical 'or' (i.e., `if "+a" .. or "+b" ...`), so this could introduce an asymmetric check style.

**Comment by aurianer** [comment]
> The changes to the Boost package look good.
> 
> A general question:
> 
> Would it be better/equivalent to translate `"+a" in self.spec and "+b" in self.spec` to `self.spec.satisfies("+a+b")` instead of `self.spec.satisfies("+a") and self.spec.satisfies("+b")`? I don't know if there is a way to combine specs for a logical 'or' (i.e., `if "+a" .. or "+b" ...`), so this could introduce an asymmetric check style.

I don't have strong opinions apart from the fact that this is done through a script and it would require me to update it to check that particular case so I slightly am in favour of keeping it like this for now.
I'll let others answer and if there is a strong opinion in favour of ` self.spec.satisfies("+a+b")`, I'll update my script accordingly

**Review by matthiasdiener — APPROVED** [review]

**Review by wdconinc — APPROVED** [review]
Thanks. This looks good.

Only `cp2k` has the type of non-trivial change from `"superlu-dist@4.3" in spec` to `spec.satisfies("^superlu-dist@4.3")` which is one of the reasons for this change: it expresses the dependency relationship better. (This is more a note to maintainers wondering about the motivation here.)

**Comment by wdconinc** [comment]
> I slightly am in favour of keeping it like this for now.

I'd indeed keep this for a future PR (maybe opportunistically when the packages where this occurs are getting new versions or other changes).

**Review by daboehme — APPROVED** [review]
Looks good to me

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by wdconinc** [comment]
Needs #45574 for pipelines to succeed.

**Review by alexrobomind — APPROVED** [review]
Cap'n'proto changes look good to me

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by adrienbernede** [comment]
@aurianer,
In `chai/package.py` at line 247, does this logic need to be updated too:
```python
        entries.append(cmake_cache_option("ENABLE_MPI", "+mpi" in spec))
```

**Comment by wdconinc** [comment]
Good catch. Another usage pattern that can be searched for. I'm sure the regex looks monstrous by now :-)

**Review by ilectra — COMMENTED** [review]
Looks fine for conquest

**Comment by aurianer** [comment]
> Good catch. Another usage pattern that can be searched for. I'm sure the regex looks monstrous by now :-)

indeed x)

**Pull request merged**
