### PR TITLE
plasma: add v23.8.2

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Review by alecbcs — DISMISSED** [review]
Confirmed SHA. @balay thanks for the new version! 

Could you quickly add a space between the git url and the maintainers directive just to keep in with the formatting conventions of most packages?

**Comment by balay** [comment]
done

**Review by alecbcs — APPROVED** [review]
@balay looks great! Thanks!

**Review by luszczek — APPROVED** [review]
It seems that `maintainers` attribute is put all over the `package.py` files and it may be a worthwhile to sweep them all for consistency at some point. Anyways, `plasma` package looks good now.

**Pull request merged**
