### PR TITLE
Major version of pip 22 fails to bootstrap on Win

### PR DESCRIPTION
**Pull request by johnwparent**
Conflict with this version until a fix is determined or a patch is backported

### CODE REVIEW

**Comment by adamjstewart** [comment]
@pradyunsg can you confirm?

**Comment by johnwparent** [comment]
@adamjstewart I'm happy to provide steps/a script to reproduce locally if that's something you're interested in. Behavior occurs from spack installed pip and just trying to bootstrap in my local setup, or an isolated python env.

**Comment by adamjstewart** [comment]
Has this issue been reported to the pip developers? @pradyunsg is the lead pip developer so I just want to make sure they're aware.

**Comment by johnwparent** [comment]
I have not yet, I wanted to get a sense of what was going wrong to make sure it wasn't something I was doing or had misunderstood before I sounded any alarms for the pip folks.

**Comment by pradyunsg** [comment]
Got more details for me to understand?

I'm pretty sure that the release was made from a Windows machine this time around, and it's not clear to me what the failure is here.

**Pull request closed without merging**
