### PR TITLE
mpiwrapper: New version 2.10.1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
*ping* I'm looking for a reviewer.

**Comment by giordano** [comment]
Checksum looks good:
```console
% wget -qO - 'https://github.com/eschnett/MPIwrapper/archive/refs/tags/v2.10.1.tar.gz' | sha256sum -                                             
54b57642b14b7b2dc257f7066eec8639133e4a4d5c351b8d689e31816b872b0d  -
```

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
> Checksum looks good:
> 
> ```
> % wget -qO - 'https://github.com/eschnett/MPIwrapper/archive/refs/tags/v2.10.1.tar.gz' | sha256sum -                                             
> 54b57642b14b7b2dc257f7066eec8639133e4a4d5c351b8d689e31816b872b0d  -
> ```

You can also run `spack checksum mpiwrapper 2.10.1`.

**Pull request merged**
