### PR TITLE
dealii: fix config for Netcdf with lib64

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/LLNL/spack/issues/2615

tested on macOS Sierra.

@cpraveen please check on your system where the problem occurred.

### CODE REVIEW

**Comment by davydden** [comment]
WIP until it's confirmed that the issues is fixed.

**Comment by cpraveen** [comment]
@davydden How do I get this fix ?

Also, my original issue in #2615 was with dealii@develop. I also tried to compile dealii git version on my own using filesystem view but it gets stuck at
```
-- Performing Test DEAL_II_HAVE_USABLE_FLAGS_DEBUG
```

**Comment by davydden** [comment]
@cpraveen the simplest way is to copy-paste/download the _raw_ `deal.II` file form this PR https://raw.githubusercontent.com/davydden/spack/cb162005b1afb2b71473ce8e91c07ac58d0e03d9/var/spack/repos/builtin/packages/dealii/package.py

> I also tried to compile dealii git version on my own using filesystem view but it gets stuck at

Let's fix one issue at a time. I would prefer to keep discussion of `DEAL_II_HAVE_USABLE_FLAGS_DEBUG` in the deal.II group, where first reported it https://groups.google.com/forum/?fromgroups#!topic/dealii/eG75p2TVNNQ
As I said there, one possibility is that your system's MPI is being picked up instead of the one compiled by Spack. 

In order to set the same environment you can also do 
`spack env dealii@develop bash` before running `cmake`.

But it's also possible that something is wrong with CMake scripts which do this test, so the issue may not be related to Spack at all.

**Comment by cpraveen** [comment]
@davydden I can confirm that with your fix, I can now successfully do
```
spack install dealii@8.4.2
```
Regarding the issue with dealii@develop, I have only one mpi on my computer which is installed by spack.

**Comment by davydden** [comment]
> I can now successfully

good! Thanks for checking.


> Regarding the issue with dealii@develop, I have only one mpi on my computer which is installed by spack.

looks like there is some issue with CMake script, let's continue discussion on the deal.II forum.

**Comment by davydden** [comment]
@tgamblin @becker33 ping.

**Comment by davydden** [comment]
> Thats a bit unfortunate to have to do. Is this deal.II specific, or will it affect all packages that depend on netcdf?

that depends on their config system and how they pick up `netcdf` and `netcdf-cxx`. 

For deal.II we currently have to specify the location of libs manually because internal Cmake script to find the netcdf and netcdf-cxx libs only work when they have the same prefix.

**Comment by tgamblin** [comment]
We may want to have spack packages standardize on either lib or lib64.  Each package builds for one architecture so there isn't really a reason to have both.  Also, with views people symlink packages into a common prefix.  I'd like to make views more common/automatic but it's awkward to load views into the environment if different packages in the same view have different lib directories.  I'm trying to think of a reason we wouldn't want to force one or the other of lib/lib64.

**Pull request merged**
