### PR TITLE
Fix symlink in concretize command

### PR DESCRIPTION
**Pull request by loulawrence**
Copy file instead of symlinking; uninstall will correctly remove this file

### CODE REVIEW

**Comment by tgamblin** [comment]
We should ask @becker33 about the best way to handle this.

If you look at how views work currently, there are several options:

```console
(spackle):~> spack view -h 
usage: spack view [-hv] [-e EXCLUDE] [-d {true,false,yes,no}] ACTION ...

project packages to a compact naming scheme on the filesystem.

positional arguments:
  ACTION
    symlink (add, soft)
                        add package files to a filesystem view via symbolic links
    hardlink (hard)     add packages files to a filesystem view via hard links
    copy (relocate)     add package files to a filesystem view via copy/relocate
    remove (rm)         remove packages from a filesystem view
    statlink (status, check)
                        check status of packages in a filesystem view

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         If not verbose only warnings/errors will be printed.
  -e EXCLUDE, --exclude EXCLUDE
                        exclude packages with names matching the given regex pattern
  -d {true,false,yes,no}, --dependencies {true,false,yes,no}
                        Link/remove/list dependencies.
```

And you can set a property in the view to control whether it symlinks, hardlinks, or relocates (I'm not seeing that documented anywhere -- @becker33 is it?).  I am kind of thinking that instead of swapping in copying for symlinking, that we should just set the preference for the environment differently on windows.

So, if you do not specify `link:` in your view settings on windows, the default would be either copy or hardlink (not sure which is better -- I believe Conda hardlinks by default so maybe that).  That would be better IMO than swapping out the mechanism under the `view_symlink` command.

Likewise, if an environment *requires* symlinks (because it has specified `link: symlink` explicitly) then we would just fail on windows (or, maybe, succeed on versions that support symlinks -- I thought they were sort of becoming a thing in more recent windows versions).

Thoughts?

**Comment by BetsyMcPhail** [comment]
@billhoffman had some thoughts about using junctions instead of symlinks.  I believe they had some limitations - they can't go across disks, for one.

**Comment by BetsyMcPhail** [comment]
Let's try using junctions instead of copy and see if it works --> https://github.com/Erotemic/ubelt/blob/master/ubelt/_win32_links.py

**Comment by BetsyMcPhail** [comment]
Replaced by #22583

**Pull request closed without merging**
