### PR TITLE
CP2K: various AOCC compatibility fixes

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
PR to fix various AOCC compatibility issues and make life easier when building older versions with newer, stricter compilers

* Patch several old versions for new compilers with strict C99 checks
* Work around a broken ELPA/CP2K version combo
* Fix for GCC 13 promoting argument mismatch to error
* Conflict out older AOCC compilers and enable -O2 optimisation level

### CODE REVIEW

**Comment by dev-zero** [comment]
please submit patches to CP2K to CP2K directly, I am unwilling to carry them only here.

**Comment by dev-zero** [comment]
Ok, I've checked, and those patches are actually backports?
Please document/name them as such.

For the ELPA enablement change: I am reluctant to support combinations of CP2K and ELPA within Spack which have not been tested by CP2K developers.

**Comment by amd-toolchain-support** [comment]
@dev-zero is there a more in depth list/matrix of supported CP2K x ELPA versions anywhere that you are aware of?  It's something we have looked for and been unable to find beyond a note on the minimum supported version in the CP2K install docs.   The version combos we are fixing here are supported per the current version conflicts in the recipe and we can't find evidence to say it shouldn't work.   Would you prefer that specific ELPA version is conflicted out instead?

re backports, yes, I'll do that sorry.  I'm not the original internal dev who dealt with this and the nature of the patches got lost somewhere along the chain.

**Comment by dev-zero** [comment]
@amd-toolchain-support there is no real compat matrix, it is basically defined by the toolchain scripts released together with a cp2k version (`tools/toolchain`). Unfortunately this will get you a very narrow list of matching components.
The version ranges specified are usually based on what was available at that time of adding a version of CP2K to the recipe. Hence, often only a lower bound gets specified and people forget to specify an upper bound as newer versions get released.

**Comment by dev-zero** [comment]
@amd-toolchain-support thanks for following up on properly declaring patches as backports, and to your devs for the backports.

**Review by mtaillefumier — APPROVED** [review]

**Review by scheibelp — APPROVED** [review]

**Pull request merged**
