### PR TITLE
Document how to handle changing build systems

### LINKED ISSUE #20364: Package build system changed
The `nsimd` package just released version 2.0. It completely changed the build system from `cmake` to `nsconfig`. How should I handle that in Spack? Is it possible to have two separate `Nsimd` functions, one deriving from `CMakePackage`, the other not?

### LINKED ISSUE #22287: Documentation: add section on changing build systems
We should document the recommended approach for packages that change from one build system to another.

### Rationale

I get asked this question almost weekly (#13466, #19298, #20364, #22209, #25111). There have been several attempts to better handle packages with multiple build systems (#10411, #12941, #15420), but we have yet to reach a consensus on any of them. We might as well document the currently recommended approach.

### Description

We should add a table similar to https://github.com/spack/spack/pull/12941#issuecomment-538105434 showing good examples of packages that have changed build systems. The current recommended approach is to inherit from the new build system and override phases using `@when` decorators as needed, then deprecating the old versions so they can be removed in a future Spack release.

### LINKED ISSUE #25111: Recommended approach when a package changes build system (KaHIP)?
Is there a recommend approach for when a package changes build system? The package in question is `kahip` [1], which has changed from SCons (v.2) to CMake (v.3). The current Spack package is for KaHIP version 2.0 and uses SCons. The latest KaHIP release series is v.3.

[1] https://github.com/spack/spack/blob/e5bbb6e5b4a1af25dd46101bfc044d04deb10cb5/var/spack/repos/builtin/packages/kahip/package.py

### PR DESCRIPTION
**Pull request by adamjstewart**
See #22287 for background and rationale.

Closes #22287 
Closes #25111 
Closes #20364

### CODE REVIEW

**Comment by adamjstewart** [comment]
Ping

**Comment by adamjstewart** [comment]
Ping ping

**Comment by adamjstewart** [comment]
Ping ping ping

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
Just merging this as-is. We can document a better way when there is one.

**Comment by tgamblin** [comment]
Also, these docs are really good!

**Pull request merged**
