### PR TITLE
highway: add v1.2.0

### PR DESCRIPTION
**Pull request by pranav-sivaraman**

### CODE REVIEW

**Comment by pranav-sivaraman** [comment]
@spackbot fix style

**Review by bernhardkaindl — APPROVED** [review]
@robertu94 This is ready to merge if you don't object. Looks good to me.

**Comment by robertu94** [comment]
Assuming it passes tests it's good with me.

**Review by bernhardkaindl — APPROVED** [review]
> Assuming it passes tests it's good with me.

The version built on Ubuntu 22.04, but `spack install --test=root` failed in parallel build: I had to specify `-j1` in addition.

@pranav-sivaraman: I think you may have to disable parallel build when self.run_tests is set or work on fixing the parallel build when tests are enabled.

**Comment by pranav-sivaraman** [comment]
@bernhardkaindl 

Ill try to reproduce this and see if I can fix it. I'm bit hesitant to set `parallel=False` since it seems to ignore conditionals.

**Comment by pranav-sivaraman** [comment]
@bernhardkaindl What is the error that you get when doing `spack install --test=root`? I was able to get an error, but that was due to OOM.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@bernhardkaindl I merged, since this seems an improvement over develop. We can investigate the issue with:
```
spack install --test=root
```
separately and fix it in a separate PR.

**Pull request merged**
