### PR TITLE
New package yaml-cpp

### PR DESCRIPTION
**Pull request by jrood-nrel**
A new package for building yaml-cpp (https://github.com/jbeder/yaml-cpp).

### CODE REVIEW

**Comment by alalazo** [comment]
Just out of curiosity: did you create the package with `spack create` ?

**Comment by jrood-nrel** [comment]
I think I usually do `spack edit -f <name>` and then manually create it.

**Comment by tgamblin** [comment]
@jrood-nrel: good to see you back on Spack!

**Comment by adamjstewart** [comment]
I still need to remove `spack edit -f`...

**Comment by alalazo** [comment]
@jrood-nrel Thanks, that may explain why it's not deriving from `CMakePackage`, I thought I introduced a bug in `spack create` in #1186

**Comment by jrood-nrel** [comment]
@tgamblin Thanks! My time in Switzerland is over, but it was awesome. Glad to see Spack has gotten more popular! The people on my new project already knew about it.

**Comment by tgamblin** [comment]
@alalazo are the different build systems documented?

**Comment by alalazo** [comment]
@tgamblin Not in the docs 😊 But they have a pretty extensive docstrings

**Pull request merged**
