### PR TITLE
parallelio: new version

### PR DESCRIPTION
**Pull request by theurich**
Adding latest PIO version 2.5.10.

### CODE REVIEW

**Comment by theurich** [comment]
@jedwards4b - just curious, since I am very new to Spack... when I opened this PR, did you get notified automatically since you are mentioned as maintainer in the parallelio package? Or how does this mechanism work? I figured this simple change was a good way for me to learn the Spack work-flow of how to contribute. Thanks!

**Review by jedwards4b — APPROVED** [review]
I think that you need to add me as a reviewer to notify me.

**Comment by theurich** [comment]
Somehow I could not add any reviewers. This is strange. Now I just requested a re-review from you, because I had to  rebase my branch to the current develop. Nothing else changed.

**Review by jedwards4b — DISMISSED** [review]

**Comment by jedwards4b** [comment]
merge will be blocked until one of the spack reviewers looks at it.

**Comment by theurich** [comment]
Okay maybe what I should have done is mention you in the PR when I first opened it. Again, I don't think I was able to add you as a reviewer, but I could have mentioned you. Then you can review and this kicks things off on the Spack side? I sayu this b/c I see spack-bot app active after we had some action on the PR. .... still learning ...

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by theurich** [comment]
@tldahlgren - I see it says that the branch is out-of-date with the base branch. Should I manually hit the "Update branch" button, or is this going to happen automatically? Thank you for your guidance.

**Comment by tldahlgren** [comment]
> @tldahlgren - I see it says that the branch is out-of-date with the base branch. Should I manually hit the "Update branch" button, or is this going to happen automatically? Thank you for your guidance.

Either is fine.  I still get an error trying to look at the pipeline results so an update may help.

**Comment by theurich** [comment]
Okay, updated the branch against develop. Let's hope it helps to move it forward.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
> Okay, updated the branch against develop. Let's hope it helps to move it forward.

🤞

**Review by jedwards4b — APPROVED** [review]

**Comment by theurich** [comment]
@jedwards4b @tldahlgren @alalazo - is it normal for a small change in a package to take this long to be merged? I am just curious because this is my first contribution to Spack, and I am wondering if I am missing something on my end I should be doing to move it forward. But if this is normal, then all good. Thanks!

**Comment by jedwards4b** [comment]
It's normal - consider that the repo currently has over 600 open PRs.

**Comment by alalazo** [comment]
@theurich You have also been unlucky, in that we are currently resolving an issue with our gitlab builders that prevented many PRs to pass CI in the last 2-3 days.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by theurich** [comment]
Thanks everyone... I am learning.
@tldahlgren - should/could I have given the request to run the pipeline?

**Comment by tldahlgren** [comment]
> Thanks everyone... I am learning.

You're welcome.

> @tldahlgren - should/could I have given the request to run the pipeline?

Yes, you should be able to use that spackbot command.

BTW. I'm told re-running the pipeline isn't going to work until those working on the gitlab issues finish resolving the problem.

**Comment by tldahlgren** [comment]
This PR has its approval and auto-merge enabled so we're just waiting on being able to run through the pipeline checks (and their success) to merge it.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by theurich** [comment]
@spackbot run pipeline

**Pull request merged**
