### PR TITLE
py-pythran: add 0.16 and fix compat bounds

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by rgommers — CHANGES_REQUESTED** [review]
This does not look correct to me. Pythran can be used as a `.py` to C++ transpiler just fine, that does not depend on `distutils`. SciPy uses Pythran like that.

**Comment by rgommers** [comment]
AFAIK the "build an extension module" mode of Pythran works fine with Python 3.12 too by the way. `distutils` can be provided by `setuptools`.

**Comment by haampie** [comment]
> SciPy uses Pythran like that.

It runs `pythran --version` during meson configure, which fails:

https://github.com/scipy/scipy/blob/7dcd8c59933524986923cde8e9126f5fc2e6b30b/meson.build#L138

due to `find_program`:

```meson
pythran = find_program('pythran', native: true, version: '>=0.14.0')
```

> `distutils` can be provided by `setuptools`.

It seems to be a  persistent misconception among python devs that you can use distutils by adding setuptools as a dep without further code changes. See my comment here https://github.com/cython/cython/pull/5754#issuecomment-1752102480 for why more is required.

**Comment by rgommers** [comment]
> It runs `pythran --version` during meson configure, which fails:

I don't think I have seen any bug report about it failing. If it has started to do so now in Spack, patching out `, version: '>=0.14.0'` should fix the problem temporarily, and I can fix it upstream properly.

> It seems to be a persistent misconception among python devs that you can use distutils by adding setuptools as a dep without further code changes

Haven't seen that either, but yes I can believe that. But again, that's a one line patch to add `import setuptools` or `from setuptools import distutils`. Surely that's preferably that declaring a conflict with Python 3.12?

**Comment by haampie** [comment]
> I don't think I have seen any bug report about it failing.

https://github.com/serge-sans-paille/pythran/issues/2204

**Comment by haampie** [comment]
ping @rgommers, new versions I've added support 3.12

**Review by rgommers — APPROVED** [review]
Great, thank you!

**Pull request merged**
