### PR TITLE
sqlite: New version 3.38.5

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Pull request merged**
