### PR TITLE
py-netcdf4: add v1.5.8

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 10.15.7 with Python 3.9.12 and Apple Clang 12.0.0.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.  Will defer merge to maintainer input.

**Comment by skosukhin** [comment]
@adamjstewart given the additional constraints on the dependencies, could you, please, confirm that versions `1.2.7` and `1.2.3.1` get installed correctly without `py-cftime` and `py-cython`? If yes, LGTM, otherwise, we probably should deprecate them.

**Comment by adamjstewart** [comment]
@skosukhin I can confirm that 1.2.3.1 and 1.2.7 build correctly on my system. The build logs show that the package does not use cython during compilation, and cftime isn't imported anywhere until recent versions of netcdf4.

I noticed that python/numpy should be type=build/link/run so I fixed that. It seems like netcdf4 1.2.7 and older come with pre-cythonized sources which are incompatible with Python 3.7+, so I added an upper version range for those releases. 

For the lower bounds, I took them from the tags in the `setup.py`. These aren't enforced in any way, so it's possible that older versions of Python could work, but since we know there are issues with Python version compatibility I think it's better to stay on the safe side. If you want me to revert the lower bounds let me know.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
@skosukhin Any objections to merging this PR?

**Comment by skosukhin** [comment]
LGTM

**Pull request merged**
