### PR TITLE
add external opengl support in doc

### PR DESCRIPTION
**Pull request by Billae**
@haampie  @kwryankrattiger   Here is what I have understood about my openGL problem  and what i can say  =)
Feel free to improve this doc

### CODE REVIEW

**Comment by haampie** [comment]
@kwryankrattiger can this be improved with external detection of the relevant system package?

**Comment by kwryankrattiger** [comment]
I think that would be awesome to add if possible. The less users have to interact with GPU tools the better. Ideally external detection would work for all of the GPU acceleration packages, but just for GL is a great start.

**Comment by Billae** [comment]
in my case, the ```spack external find``` did not find it

**Comment by Billae** [comment]
Is this doc ok to be pushed ? =)

**Review by kwryankrattiger — APPROVED** [review]

**Comment by alalazo** [comment]
Merging, let's leave the external detection for a following PR.

**Pull request merged**
