### PR TITLE
hip: Patch to handle file reorg changes for the tests

### PR DESCRIPTION
**Pull request by renjithravindrankannath**
File reorganization changes in 5.4 was implemented in tests as part of 5.6 release.
This patch is to apply those changes on to 5.4 and 5.5.

### CODE REVIEW

**Review by srekolam — DISMISSED** [review]
LTGM.. This changes are part of 5.6.0 release

**Comment by renjithravindrankannath** [comment]
@tldahlgren , Can you please review.

**Review by srekolam — APPROVED** [review]

**Comment by renjithravindrankannath** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
