### PR TITLE
Modify info print of ESMF_CPP due to permission denied errors in spack on MSU Hercules

### LINKED ISSUE #35957: Installation issue: esmf on MSU Hercules
### Steps to reproduce the issue

**Describe the bug**
On MSU Hercules, using intel@2022.1.0 with OS gcc@11.3.1 as backend. For both esmf@8.3.0b09 and esmf@8.4.1:
```
==> Installing esmf-8.3.0b09-54ceq7uaqwv5jpxcxsvwdbxiov226473
==> esmf exists in binary cache but with different hash
==> No binary for esmf-8.3.0b09-54ceq7uaqwv5jpxcxsvwdbxiov226473 found: installing from source
==> Fetching file:///work/noaa/da/role-da/spack-stack/source-cache/_source-cache/git/esmf-org/esmf.git/5b7e546c4b.tar.gz
==> No patches needed for esmf
==> esmf: Executing phase: 'edit'
==> esmf: Executing phase: 'build'
==> [2023-03-07-18:38:44.551844] '/usr/bin/chmod' '+x' 'scripts/libs.mvapich2f90'
==> [2023-03-07-18:38:44.554890] 'make' '-j6'

--------------------------------------------------------------
ESMF_VERSION_STRING:    8.3.0 beta snapshot
Not a Git repository
--------------------------------------------------------------

--------------------------------------------------------------
Make version:
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

--------------------------------------------------------------
Fortran Compiler version:
mpiifort for the Intel(R) MPI Library 2021.7 for Linux*
Copyright Intel Corporation.
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.

ifort version 2021.7.1

--------------------------------------------------------------
C++ Compiler version:
mpiicpc for the Intel(R) MPI Library 2021.7 for Linux*
Copyright Intel Corporation.
Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.

icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icpc version 2021.7.1 (gcc version 11.3.1 compatibility)

--------------------------------------------------------------
Preprocessor version:
make: gcc: Permission denied
make: *** [makefile:88: script_info] Error 127
==> Error: ProcessError: Command exited with status 2:
    'make' '-j6'

2 errors found in build log:
     35
     36    icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the re
           commended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
     37    icpc version 2021.7.1 (gcc version 11.3.1 compatibility)
     38
     39    --------------------------------------------------------------
     40    Preprocessor version:
  >> 41    make: gcc: Permission denied
  >> 42    make: *** [makefile:88: script_info] Error 127

See build log for details:
  /work2/noaa/da/dheinzel-new/spack-stack-hercules/spack-stack-hercules/cache/build_stage/spack-stage-esmf-8.3.0b09-54ceq7uaqwv5jpxcxsvwdbxiov226473/spack-build-out.txt

==> Warning: Skipping build of mapl-2.22.0-3cq4r7q3zu4q4snyulrcxzmsklay367w since esmf-8.3.0b09-54ceq7uaqwv5jpxcxsvwdbxiov226473 failed
==> Warning: Skipping build of ufs-weather-model-env-1.0.0-3bhdzw5nsc4hqoxfapww2wwxd2vw37bb since mapl-2.22.0-3cq4r7q3zu4q4snyulrcxzmsklay367w failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 2:
    'make' '-j6'
```
The offending lines are in the top-level `makefile`:
```
        -@echo "Preprocessor version:"
        @$(ESMF_CPP) --version $(ESMF_DIR)/scripts/empty.C
```
If I run a spack interactive build via
```
spack build-env esmf@8.3.0 snapshot=b09 -- bash
```
then I don't get the error, I only get it when I run `spack install ...`.

A `which gcc` in both cases says `/usr/bin/gcc` - which is correct - but in the interactive case this just works, whereas in the `spack install` case it doesn’t. Even though the environment is or at least should be the same (that’s what the `spack build-env …` command is for).

If I replace `gcc` with the full path `/usr/bin/gcc` then it works. Very annoying and I still don’t understand why. Maybe some dependency not using `set_dependent_build_environment` correctly, so that there is a difference between `spack install` and `spack build-env` (similar to what @AlexanderRichert-NOAA fixed for esmf recently).

In any case, this call in the top-level `makefile` is unnecessary, it’s just an info print. We might as well patch that makefile in spack and comment out/remove/replace the offending line with a comment that says `this has been removed because it’s not working`.

**To Reproduce**
See above.

**Expected behavior**
No more build errors for esmf.

**System:**
MSU Hercules

**Additional context**

### Error message

See above

### Information on your system

```
* **Spack:** 0.20.0.dev0 (fd9199495939855c22cc94cf5e815d208b772414)
* **Python:** 3.9.14
* **Platform:** linux-rocky9-icelake
* **Concretizer:** clingo
```

### Additional information

Attached here:

[spack-logs.tar.gz](https://github.com/spack/spack/files/10927552/spack-logs.tar.gz)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by climbfuji**
Fixes https://github.com/spack/spack/issues/35957

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
It's been a while since I encountered this problem... Would it work to set ESMF_CPP to the output of "which gcc" or something like that?

**Review by jedwards4b — COMMENTED** [review]
You have one machine with a permission denied error so you want to change this for all machines?  I'm not sure that that makes sense.

**Comment by AlexanderRichert-NOAA** [comment]
In fairness this isn't the first machine where we've encountered this, I ran into this on at least Acorn and maybe one other machine once upon a time. I now remember what the exact issue was: Spack adds `$SPACK_ROOT/lib/spack/env` to `$PATH`, and that directory has a subdirectory called 'gcc' with links to the various gcc compilers. Meanwhile, there's a bug in Make where when it scans `$PATH` to run an executable, it does not distinguish directories and will try to execute one if the name matches. It's possible that it can be fixed by using sufficiently a recent version of Make, but I don't remember for sure.

**Comment by theurich** [comment]
What I don't understand here is that `ESMF_CPP` is used by the ESMF build system to do some pre-processing of templated Fortran code. That is why it is there in the first place. This happens downstream from where the version of `ESMF_CPP` is printed out. So wouldn't the same "permission denied" issue break the build once we are hitting those places where `ESMF_CPP` is actually used?

**Comment by AlexanderRichert-NOAA** [comment]
I don't _think_ so, because in the build itself, the shell will search `$PATH` for `gcc` (which will be smart enough to skip directories), whereas in this instance, it's Make's internal functionality for doing so (which is where the bug is).

**Comment by theurich** [comment]
@AlexanderRichert-NOAA - I see, that makes sense, also after re-reading your previous post now. Thanks!

**Comment by climbfuji** [comment]
> @AlexanderRichert-NOAA - I see, that makes sense, also after re-reading your previous post now. Thanks!

I am happy to replace this with a better solution if we have one, don't like what I proposed here either (but I didn't have time to dive deeply into this, thankfully Alex did beforehand and so we know what's happening).

**Comment by climbfuji** [comment]
> I don't _think_ so, because in the build itself, the shell will search `$PATH` for `gcc` (which will be smart enough to skip directories), whereas in this instance, it's Make's internal functionality for doing so (which is where the bug is).

@AlexanderRichert-NOAA I didn't check yet, do you think we can use the same approach in the top-level `makefile`?

**Comment by theurich** [comment]
I wonder if the following change would work:
```
@@ -97,7 +97,7 @@ endif
        -@echo "C Compiler version:"; $(ESMF_CCOMPILER_VERSION); echo ""
        -@echo "--------------------------------------------------------------"
        -@echo "Preprocessor version:"
-       @$(ESMF_CPP) --version $(ESMF_DIR)/scripts/empty.C
+       -@echo `$(ESMF_CPP) --version $(ESMF_DIR)/scripts/empty.C`
 ifeq ($(pathtype),abs)
        -@echo "--------------------------------------------------------------"
        -@echo "NetCDF library version: `$(ESMF_NETCDF) --version`"
```
This should call through a shell to get the version information printed. The unfortunate side-effect is that the entire `--version` output shows up in a single line, which is ugly, but at least it is there, and hopefully not run into the Make bug. 

Could someone test this on the machine that is causing issues?

**Comment by climbfuji** [comment]
> I wonder if the following change would work:
> 
> ```
> @@ -97,7 +97,7 @@ endif
>         -@echo "C Compiler version:"; $(ESMF_CCOMPILER_VERSION); echo ""
>         -@echo "--------------------------------------------------------------"
>         -@echo "Preprocessor version:"
> -       @$(ESMF_CPP) --version $(ESMF_DIR)/scripts/empty.C
> +       -@echo `$(ESMF_CPP) --version $(ESMF_DIR)/scripts/empty.C`
>  ifeq ($(pathtype),abs)
>         -@echo "--------------------------------------------------------------"
>         -@echo "NetCDF library version: `$(ESMF_NETCDF) --version`"
> ```
> 
> This should call through a shell to get the version information printed. The unfortunate side-effect is that the entire `--version` output shows up in a single line, which is ugly, but at least it is there, and hopefully not run into the Make bug.
> 
> Could someone test this on the machine that is causing issues?

Let me try!

**Comment by climbfuji** [comment]
> 

Yes, that seems to work!

**Comment by climbfuji** [comment]
PR updated, thanks @theurich !

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@jedwards4b Can you please approve this PR in the authoritative repo, too? We merged it in our fork already, commits are cherry-picked to avoid merge conflicts. Thanks!

**Review by jedwards4b — APPROVED** [review]

**Comment by climbfuji** [comment]
@tldahlgren Can you help merge this PR, please? Thanks!

**Comment by climbfuji** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
