### PR TITLE
Add superlu-dist@7.1.1 butterflypack@2.0.0 tasmanian@7.7 pflotran@3.0.2 alquimia@1.0.9

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Comment by balay** [comment]
cc: @mkstoyanov @liuyangzhuan @ghammond86 @smolins @xiaoye

**Comment by mkstoyanov** [comment]
Looks good to me.

**Comment by ghammond86** [comment]
Technically, PFLOTRAN v3.0.x depends on PETSc 3.13.x, but I know that it is compatible with the latest version; so I am not concerned.

**Comment by balay** [comment]
petsc-3.16 is the version we are using in upcoming xsdk@0.7.0 - hence the extra dependency [as I'm  doing builds using only this combination]

**Comment by smolins** [comment]
Looks good

**Review by sethrj — APPROVED** [review]
Checksums appear good.

**Pull request merged**
