### PR TITLE
openssl: New version 1.1.1t

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
Note: OpenSSL 1.1.1 is supported until September 11, 2023. That's just a few months. One should start testing with OpenSSL 3.

**Review by haampie — APPROVED** [review]

**Comment by eschnett** [comment]
@spackbot help

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
CI fails because of an error in the test `pfunit/mi4ouei 3.3.3 gcc@11.1.0 linux-ubuntu20.04-ppc64le E4S Power`. This error looks unrelated to the OpenSSL changes; there's a confusion about which overloaded Fortran function to call. If that is correct, then others should see the same error as well. I tried "update branch" before, and this did not make this error go away.

**Comment by haampie** [comment]
I think we're better off force merging this if CI doesn't pass soon.

**Comment by adamjstewart** [comment]
I have the same pfunit failure holding up my PRs as well. Is anyone planning to fix it or is this the new norm?

**Comment by haampie** [comment]
See https://github.com/spack/spack/pull/35510 (just merged)

**Comment by adamjstewart** [comment]
@alalazo is my hero

**Pull request merged**
