### PR TITLE
Add rocm-openmp-extras package as a dependency for +openmp for +rocm 

### PR DESCRIPTION
**Pull request by srekolam**
modify the llvm-amdgpu package to remove openmp variant.
Add rocm-openmp-extras package as a dependency for +openmp for rocm

### CODE REVIEW

**Comment by bgoglin** [comment]
I don't see anything wrong in the hwloc part but I don't know enough to confirm it's correct.

**Review by rbberger — APPROVED** [review]
lammps changes look ok.

**Review by renjithravindrankannath — APPROVED** [review]

**Comment by srekolam** [comment]
Can i get this merged. From the CI pipeline , i saw paraview failed waiting for docker containers.
ContainersNotReady: "containers with unready status: [build helper]"
Waiting for pod pipeline/runner-me59981k-project-2-concurrent-7-7rjpixux to be running, status is Pending

**Comment by alalazo** [comment]
@srekolam You can re-run a pipeline that failed that way by posting:

@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by G-Ragghianti** [comment]
It looks like this doesn't work with rocm-openmp-extras@5.4.3: https://github.com/spack/spack/issues/43021

This just happened to be the version that was selected in my most recent attempt to install papi+rocm

**Pull request merged**
