### PR TITLE
remove another Python 3.7 requirement & preference, since it was deprecated

### PR DESCRIPTION
**Pull request by haampie**
Python 3.7 was deprecated in Spack

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by haampie** [comment]
So, after an infinity of debugging this awful python setuptools madness, it looks like `python %oneapi` has issues with timezones.

With `-g -O2`:

```c
0x00007ff6f9653a4d in timezone_fromutc (self=0x7ff6f988e740, dt=0x7ff6f987ae80) at Modules/_datetimemodule.c:4008
4008	    return add_datetime_timedelta(dt, (PyDateTime_Delta *)self->offset, 1);

(gdb) p self->offset 
$1 = 0x0
```

also with `-g -O1` where that function is not inlined:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f303942ef0c in add_datetime_timedelta (date=0x7f30394d7000, delta=0x0, factor=1) at Modules/_datetimemodule.c:5373
5373	    int day = GET_DAY(date) + GET_TD_DAYS(delta) * factor;
```

where

```c
#define GET_TD_DAYS(o)          (((PyDateTime_Delta *)(o))->days)
```

so the date time delta pointer thing is a null pointer, great :+1: 

```python
from datetime import datetime, timezone
datetime.now(timezone.utc)
```

---

With -O0 things run fine... Maybe that's the best default for %oneapi :smirk:

**Comment by haampie** [comment]
@eugeneswalker what do we do with this? Looks like intel compilers are just broken

**Comment by haampie** [comment]
I've actually bisected it to this commit in Python https://github.com/python/cpython/commit/37fcbb65d4589fbb5a72153e9338cf8e6495f64f

```
37fcbb65d4589fbb5a72153e9338cf8e6495f64f is the first bad commit
commit 37fcbb65d4589fbb5a72153e9338cf8e6495f64f
Author: Dong-hee Na <donghee.na92@gmail.com>
Date:   Wed Mar 25 07:08:51 2020 +0900

    bpo-40024: Update C extension modules to use PyModule_AddType() (GH-19119)
    
    Update _asyncio, _bz2, _csv, _curses, _datetime,
    _io, _operator, _pickle, _queue, blake2,
    multibytecodec and overlapped C extension modules
    to use PyModule_AddType().

 Modules/_asynciomodule.c           | 15 +++----------
 Modules/_blake2/blake2module.c     | 10 ++-------
 Modules/_bz2module.c               | 17 ++------------
 Modules/_csv.c                     |  8 ++-----
 Modules/_cursesmodule.c            |  5 +++--
 Modules/_datetimemodule.c          | 45 ++++++++++++--------------------------
 Modules/_io/_iomodule.c            | 36 ++++++++++++++----------------
 Modules/_operator.c                | 24 ++++++++++----------
 Modules/_pickle.c                  | 17 +++++---------
 Modules/_queuemodule.c             |  6 ++---
 Modules/cjkcodecs/multibytecodec.c | 12 ++++------
 Modules/overlapped.c               |  6 ++---
 12 files changed, 67 insertions(+), 134 deletions(-)
```

**Comment by haampie** [comment]
Created an issue here: https://github.com/python/cpython/issues/106424

**Comment by eugeneswalker** [comment]
@rscohn2  any thoughts here?

**Comment by haampie** [comment]
So in short:

Python from commit https://github.com/python/cpython/commit/37fcbb65d4589fbb5a72153e9338cf8e6495f64f (i.e. Python 3.9 and above) is broken compiled with the Intel oneAPI compilers 2022.2.1 and above. The following snippet simply segfaults:

```python
from datetime import datetime, timezone
datetime.now(timezone.utc)
```

Given that it regressed from a certain Intel compiler version suggests it's a compiler bug.

I've added a conflict for now.

**Review by alalazo — APPROVED** [review]

**Comment by rscohn2** [comment]
It could be a compiler bug, but this type of problem is usually a latent bug in the source program that is unmasked by optimization. Filing an issue upstream and inserting a conflict is all that can be done.

**Comment by haampie** [comment]
That's not very helpful. I've created an issue upstream, they say it's likely a compiler bug. I've done all the work for you to figure out the minimal diff that broke Python, which is very manageable for compiler devs to look at, see: https://github.com/python/cpython/commit/37fcbb65d4589fbb5a72153e9338cf8e6495f64f That one fails, the parent is fine. The Python code that fails is a oneliner.

Saying "inserting a conflict is all that can be done" means no Python 3.9, 3.10, and 3.11. That's not just any package...

**Comment by rscohn2** [comment]
I was responding to @eugeneswalker question, which I took to mean what to do about the failure in spack. In the upstream issue you filed, I asked @oleksandr-pavlyk for help. He is in the Intel team that produces a python distribution.

**Pull request merged**
