### PR TITLE
Updating udunits version.

### PR DESCRIPTION
**Pull request by t-brown**
Udunits 2.2.21 is no longer on the unidata ftp site.
The latest is 2.2.23, adding that and it's md5sum.

### CODE REVIEW

**Comment by citibeth** [comment]
Can you either (a) remove the old version that's no longer there, or (b) switch it to a URL that still works?  Maybe this...
https://www.gfd-dennou.org/arch/ucar/unidata/pub/udunits/SIGEN.htm

**Comment by adamjstewart** [comment]
Looks like it has a different checksum, meaning it likely doesn't come with a configure script.

**Comment by adamjstewart** [comment]
Also, it looks like `2.2.23` is already unavailable for download as well.

**Comment by adamjstewart** [comment]
We'll either need to keep updating the URL for the old URL, or switch to the GitHub URL and add an autoreconf method.

**Comment by tgamblin** [comment]
I think github + autoreconf is the way to go.

**Pull request merged**
