### PR TITLE
adios2: add catalyst variant

### PR DESCRIPTION
**Pull request by vicentebolea**
This was added in ADIOS 2.9.0

### CODE REVIEW

**Comment by vicentebolea** [comment]
@pnorbert

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by vicentebolea** [comment]
@eugeneswalker CI is passing :)

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
