### PR TITLE
Add shared and pic variants for zlib-ng

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds `shared` and `pic` variants for `zlib-ng`. By default, it builds shared and static.

As it is difficult to control which one is used by downstream packages (and some systems don't want/allow shared libraries), I'm adding the variant to disable the shared lib.

I [checked](https://github.com/zlib-ng/zlib-ng/issues/1680) with the `zlib-ng` developers:

They don't want to add these options to the `./configure` script because they want to move away from using `autotools` (not sure how that'll work with the circular dependency with `cmake`, but ...).

So I think the only solution for the `autotools` build is to add the `pic` flag in the recipe itself (which we need on at least one or two of our systems, i.e., `static+pic`).

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot fix style

**Review by bernhardkaindl — COMMENTED** [review]
@AlexanderRichert-NOAA: Would you resolve the conflict and ping a another maintainer or me afterwards in this PR?

**Comment by AlexanderRichert-NOAA** [comment]
@bernhardkaindl done, thanks

**Review by bernhardkaindl — APPROVED** [review]
The changes look good to me, approving.

@haampie, do you want to review?

@AlexanderRichert-NOAA: I'll give @haampie some more time in case he wants to review it.

Please ping me (or other maintainers) again in case I forget to come back to it!

**Comment by skosukhin** [comment]
By the way, `zlib-ng` doesn't use Autotools but a custom configure script (like in `zlib`, which makes things more complicated than it should be :(

**Pull request merged**
