### PR TITLE
Revert "Ci generate on change"

### PR DESCRIPTION
**Pull request by haampie**
Reverts spack/spack#47318

The commit that's being reverted does not seem to account for changes to the concretizer itself (at any level), nor to changes in config (requirements, preferences, providers, etc).

I would hold off with this until after releases/v0.23 branches off.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@scottwittenburg @kwryankrattiger Fyi

**Comment by kwryankrattiger** [comment]
This intentionally does not consider the concretizer, that is the entire point. Can you share an example of how that is not expected behavior?

As far as the configs, that is easily added, I seem to have forgotten that check down below.

**Comment by alalazo** [comment]
@kwryankrattiger 

> This intentionally does not consider the concretizer, that is the entire point. 

_Changes_ in the concretizer. We should monitor at least files in `spack/solver`, but a more defensive choice would probably be if anything changes under `lib/` then run generate (PR touching core Spack).

This was reverted because:
1. We are close to release
2. The previous state made some PR pass while they should have not, and merging them was causing failures on `develop`

**Comment by kwryankrattiger** [comment]
If we monitor changes to anything under lib and any package change, then I would say this is probably not worth having as that covers basically everything that might change in Spack, the remaining files are much much less frequently updated in isolation, pretty much documentation only changes, and those are so rare it is almost not worth it.

To be clear I am fine with the revert. There was a bug not considering changes to the configs and leaving it and continuing to not test relevant changes wasn't really an option.

What I want to know is, was not running on config change the only issue with a concrete example of causing error? Is there some kind of concretization or generate we should be doing in  GitHub actions CI?

The goal here is to save a non-trivial amount of resources, but not at the expense of necessary coverage..

**Comment by alalazo** [comment]
> If we monitor changes to anything under lib and any package change [ ... ] that covers basically everything that might change in Spack

Why do you say "any package change"? :thinking: By `lib/` I really mean core Spack.[^1]

Wasn't the original idea that modifying a package that couldn't possibly enter the pipelines wouldn't trigger concretization?

[^1]: Think of changes to any `.satisfies` or `.constrain` method, or to `asp.py`, or `concretize.lp`. Those can potentially give different concretizations.

**Pull request merged**
