### PR TITLE
python: add 3.10.8, 3.9.15, 3.8.15, 3.7.15

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Let's merge #32623 first.

**Review by adamjstewart — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
incredible, the progress in CI here.

**Comment by adamjstewart** [comment]
If this is the new norm I'm no longer going to add new versions to packages @tgamblin @scottwittenburg @zackgalbreath

**Comment by haampie** [comment]
Spack is turning into ubuntu where you get updates only every so many months, except you don't get the security updates

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Omg it actually passed!

**Comment by haampie** [comment]
Just 12 attempts, it's not a big deal!

**Comment by michaelkuhn** [comment]
My two remaining PRs are up to 15+. :smiling_face_with_tear:

**Pull request merged**
