### PR TITLE
Backport updates from release branch

### PR DESCRIPTION
**Pull request by alalazo**
These commits are better rebased and merged rather  than squashed.

Modifications:
- [x] Bump the version number on develop
- [x] Cherry-pick the CHANGELOG update from the release branch
- [x] Cherry-pick the SECURITY update from the release branch

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
This one’s already passing:

https://github.com/spack/spack/pull/33830

want to rebase it?

**Comment by alalazo** [comment]
> This one’s already passing:

Sure, my bad! I didn't see that!

**Comment by alalazo** [comment]
Clearly I didn't _remember_ that, since I approved :laughing:

**Pull request closed without merging**
