### PR TITLE
update Spack Bioconductor packages to Bioconductor 3.15

### PR DESCRIPTION
**Pull request by glennpj**
There is one new package but for the most part this is just adding new versions of R Bioconductor packages to correspond with the release of Bioconductor 3.15. This is submitted as a set because there are a lot of cross dependencies.

### CODE REVIEW

**Comment by glennpj** [comment]
Looks like I got burned by `--reuse` versus `--fresh` and had some newer packages built that got used in test builds. Based on the failed audit test, this will depend on some updated CRAN packages. That PR is coming soon.

**Review by alalazo — CHANGES_REQUESTED** [review]
Feel free to ping me back when the audit test is passing

**Comment by glennpj** [comment]
This PR depends on #31004 to get the dependencies that are causing the audit test to fail.

**Comment by alalazo** [comment]
@glennpj Can you rebase this branch, now that #31004 has been merged?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
