### PR TITLE
Fix "build systems" Gitlab pipeline

### PR DESCRIPTION
**Pull request by alalazo**
Modifications:
- [x] Remove tut since it requires deprecated Python 3.6

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Review by scottwittenburg — APPROVED** [review]
Approve, thanks!  I expect this to survive the "naughty list" check since it removes the spec known to be broken on develop.

**Comment by alalazo** [comment]
@scottwittenburg Yeah, let's see if there is anything else to evict from the list :smiling_imp:

**Comment by scottwittenburg** [comment]
> @scottwittenburg Yeah, let's see if there is anything else to evict from the list 😈

You're right, since there are two pythons in the build_systems concretization report (or staging report, whatever I call it), I guess there may be something else bringing in that other python.

**Comment by alalazo** [comment]
Hmm, this is weird. I checked and I think:
1. The only spec to be removed is `tut`
2. Pipelines in this branch are __still__ concretizing `tut`

:thinking:

**Comment by scottwittenburg** [comment]
> 2\. Pipelines in this branch are **still** concretizing `tut`

Where are you seeing that?  To me it appears this PR hasn't triggered a pipeline yet because its merge commit contains a develop that is currently being tested in a running pipeline.

Screen Shot 2022-01-11 at 10 13 12 AM

**Comment by alalazo** [comment]
If I look here https://gitlab.spack.io/spack/spack/-/jobs/1562820 I see this:

**Comment by alalazo** [comment]
@scottwittenburg I got the link above by just clicking "Details"

EDIT: Ugh, it's not from this PR!

**Comment by scottwittenburg** [comment]
That ☝️ is from the `develop` pipeline that is currently running and blocking this PR from running a pipeline.

**Comment by alalazo** [comment]
Yeah, the misleading point is that if I click "Details" in this PR I get redirected to the pipeline I posted, which is confusing...

**Comment by scottwittenburg** [comment]
> I got the link above by just clicking "Details"

Yeah, maybe it's confusing that the details in that case links to the pipeline that is *blocking* this one, when normally details links to the running pipeline for this PR.

What do you think @zackgalbreath?

**Comment by scottwittenburg** [comment]
Sorry for repeated cross-posting.

**Comment by zackgalbreath** [comment]
> Yeah, maybe it's confusing that the details in that case links to the pipeline that is _blocking_ this one, when normally details links to the running pipeline for this PR.
> 
> What do you think @zackgalbreath?

That was the motivation, yes. I thought it would be helpful to have a link to the currently running develop pipeline that's blocking this PR as the status message indicates. But we can remove it if you think that's not a good idea.

**Comment by adamjstewart** [comment]
The check still says "Pending - waiting for base develop commit pipeline to succeed" but the develop pipeline finished already.

**Comment by scottwittenburg** [comment]
We're trying to keep track of these PRs where we push a branch to gitlab but it doesn't a pipeline.  I added this one to the list.  Now that we had a chance to look into why this one didn't run, I'll ask spackbot to do it.

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Comment by scottwittenburg** [comment]
Looks like the `build_systems` stack generated fine, with only `python@3.9.9` in it, so it seems like `tut` was all we needed to remove.

**Comment by adamjstewart** [comment]
@alalazo is this still a draft?

**Pull request merged**
