### PR TITLE
unifyfs: new release v1.0.1

### PR DESCRIPTION
**Pull request by CamStan**
## Description

Add 1.0.1 release
Add new variant for new configure time option

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256, rest LGTM.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by CamStan** [comment]
Ooh, fancy style fixer! I had a feeling that one was going to be a problem.

**Comment by tldahlgren** [comment]
Looks like a pod issue for one CI stack and two other stacks with issues:

```
==> Starting concretization pool with 16 processes
==> Warning: 'target=graviton2' is deprecated, use 'target=neoverse_n1' instead
ERROR: Job failed: execution took longer than 6h0m0s seconds
```

**Comment by tldahlgren** [comment]
Let's see if re-running the pipeline is sufficient.

spackbot run pipeline

**Comment by CamStan** [comment]
@tldahlgren, I don't think the re-run was triggered. Was "spackbot" missing an "@" before it?

**Comment by tldahlgren** [comment]
> @tldahlgren, I don't think the re-run was triggered. Was "spackbot" missing an "@" before it?

🤦 You are correct.  I thought I'd typed it but I was also in a meeting.

@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]

**Comment by CamStan** [comment]
Thank you @tldahlgren!

**Pull request merged**
