### PR TITLE
add a path argument to the stage command

### PR DESCRIPTION
**Pull request by trws**
Allow users to use spack to stage a, potentially complex, package into a
given path.  This is nice for packages with multiple resources that must
be placed, for example LLVM with all sub-projects.

This may not be the preferred way to do this, but seemed to be the least impact change.

### CODE REVIEW

**Comment by mathstuf** [comment]
+1 I like this, but it needs a rebase.

**Comment by tgamblin** [comment]
@trws: sorry I didn't merge this.

**Comment by trws** [comment]
It's rebased, and due to StageComposite somewhat reworked.  Assuming it passes, which it seems to based on my local testing, glance over it and it should be good to go.

**Comment by mathstuf** [comment]
LGTM.

**Pull request merged**
