### PR TITLE
New versions for the `tfel` and `mgis` packages

### PR DESCRIPTION
**Pull request by thelfer**
This PR adds support for the latests versions of the `tfel` and `mgis` packages.

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
Hi @thelfer! It would be nice if you could approve my pull request to your branch for this PR: https://github.com/thelfer/spack/pull/12 Thanks!

**Comment by bernhardkaindl** [comment]
@thelfer Reproducible with
* the standard gcc-11.2.0 of Ubuntu 21.10,
* the gcc-11.1 of Arch Linux and
* the gcc-11.1 from `add-apt-repository ppa:ubuntu-toolchain-r/test` on Ubuntu 18.04 on an AMD EPYC Rome CPU:

I can reproduce a test fail of `tfel@4.0.0`, is the a bug of gcc-11.1.0 and and gcc-11.2.0 or maybe an issue in the SW/tests?
```py
10930 - crossed2deltachaboche_mtest (Failed)
```
Manual execution of the test case with verbose enabled (excerpt):
```py
...
cd /tmp/$USER/spack-stage/spack-stage-tfel-4.0.0-pma6uz32atkqqv6jvl7jqaydph3snlaz/spack-build-pma6uz3/mtest/src/
resolution from 1.2625 to 1.34875
iteration 1 : 0.000109113 12.1871 (0.0541281 -0.026879 -0.0268775 0.114553 0 0)
iteration 2 : 0.000108783 12.1502 (0.0541794 -0.0269047 -0.0269032 0.114662 0 0)
CrossedSecant acceleration convergence
iteration 3 : 0.000108371 12.1042 (0.0542435 -0.0269367 -0.0269352 0.114798 0 0)
Crossed2Delta acceleration convergence
iteration 4 : 9.06824e-06 1.01285 (0.0711146 -0.0353723 -0.0353708 0.150582 0 0)
CrossedSecant acceleration convergence
iteration 5 : 8.2335e-07 0.0919619 (0.0726553 -0.0361427 -0.036141 0.15385 0 0)
CrossedSecant acceleration convergence
iteration 6 : 1.74212e-07 0.0191781 (0.0728155 -0.0362218 -0.0362221 0.154177 0 0)
convergence, after 6 iterations, order 0.647358

resolution from 1.34875 to 1.435
iteration 1 : 0.000109324 12.2107 (0.0728747 -0.0362396 -0.0362398 0.154287 0 0)
iteration 2 : 0.000108934 12.1671 (0.0729261 -0.0362653 -0.0362655 0.154395 0 0)
CrossedSecant acceleration convergence
iteration 3 : 0.000108604 12.1303 (0.072988 -0.0362963 -0.0362964 0.154527 0 0)
Crossed2Delta acceleration convergence
iteration 4 : 1.05406e-05 1.17731 (0.093516 -0.046561 -0.0465597 0.198076 0 0)
CrossedSecant acceleration convergence
iteration 5 : 2.50852e-06 0.280183 (0.0958002 -0.0476918 -0.0477132 0.202764 0 0)
Crossed2Delta acceleration convergence
iteration 6 : 1.53076e-07 0.017153 (0.0959923 -0.0477984 -0.0477986 0.203319 0 0)
convergence, after 6 iterations, order 1.94806

Execution succeeded
-number of period:     13
-number of iterations: 128
-number of sub-steps:  0
Result of test 'unit behaviour test' of group 'MTest'            : FAILED
*                                                                : FAILED
* *ReferenceFileComparisonTest::check : comparison for variable ': FAILED
* ReferenceFileComparisonTest::check : comparison for variable 'E: SUCCESS
* ReferenceFileComparisonTest::check : comparison for variable 'S: SUCCESS
End of Test Suite                                                : FAILED
```

**Comment by bernhardkaindl** [comment]
I can reproduce a test fail of `tfel@4.0.0`.@thelfer I can reproduce a test fail of `tfel@4.0.0` - It is reproducible (each time) with
* the standard gcc-11.2.0 of Ubuntu 21.10,
* the gcc-11.1 of Arch Linux and
* the gcc-11.1 from `add-apt-repository ppa:ubuntu-toolchain-r/test` on Ubuntu 18.04 on an AMD EPYC Rome CPU:

No test fail in an Ubuntu-18.04 container on the same server with gcc-8.4.0, gcc-9.4.0, gcc-10.3.0 (from ppa above).
Is this a bug of `gcc-11.1.0` and and `gcc-11.2.0` or maybe an issue in the SW/tests?
```py
10930 - crossed2deltachaboche_mtest (Failed)
```
Manual execution of the test case with verbose enabled (excerpt):
```py
cd /tmp/$USER/spack-stage/spack-stage-tfel-4.0.0-pma6uz32atkqqv6jvl7jqaydph3snlaz/spack-build-pma6uz3/mtest/src/
./mtest --xml-output=true --result-file-output=true --verbose=level1 ../../mfront/tests/behaviours/crossed2delta/crossed2deltachaboche.mtest
...
resolution from 1.2625 to 1.34875
iteration 1 : 0.000109113 12.1871 (0.0541281 -0.026879 -0.0268775 0.114553 0 0)
iteration 2 : 0.000108783 12.1502 (0.0541794 -0.0269047 -0.0269032 0.114662 0 0)
CrossedSecant acceleration convergence
iteration 3 : 0.000108371 12.1042 (0.0542435 -0.0269367 -0.0269352 0.114798 0 0)
Crossed2Delta acceleration convergence
iteration 4 : 9.06824e-06 1.01285 (0.0711146 -0.0353723 -0.0353708 0.150582 0 0)
CrossedSecant acceleration convergence
iteration 5 : 8.2335e-07 0.0919619 (0.0726553 -0.0361427 -0.036141 0.15385 0 0)
CrossedSecant acceleration convergence
iteration 6 : 1.74212e-07 0.0191781 (0.0728155 -0.0362218 -0.0362221 0.154177 0 0)
convergence, after 6 iterations, order 0.647358

resolution from 1.34875 to 1.435
iteration 1 : 0.000109324 12.2107 (0.0728747 -0.0362396 -0.0362398 0.154287 0 0)
iteration 2 : 0.000108934 12.1671 (0.0729261 -0.0362653 -0.0362655 0.154395 0 0)
CrossedSecant acceleration convergence
iteration 3 : 0.000108604 12.1303 (0.072988 -0.0362963 -0.0362964 0.154527 0 0)
Crossed2Delta acceleration convergence
iteration 4 : 1.05406e-05 1.17731 (0.093516 -0.046561 -0.0465597 0.198076 0 0)
CrossedSecant acceleration convergence
iteration 5 : 2.50852e-06 0.280183 (0.0958002 -0.0476918 -0.0477132 0.202764 0 0)
Crossed2Delta acceleration convergence
iteration 6 : 1.53076e-07 0.017153 (0.0959923 -0.0477984 -0.0477986 0.203319 0 0)
convergence, after 6 iterations, order 1.94806

Execution succeeded
-number of period:     13
-number of iterations: 128
-number of sub-steps:  0
Result of test 'unit behaviour test' of group 'MTest'            : FAILED
*                                                                : FAILED
* *ReferenceFileComparisonTest::check : comparison for variable ': FAILED
* ReferenceFileComparisonTest::check : comparison for variable 'E: SUCCESS
* ReferenceFileComparisonTest::check : comparison for variable 'S: SUCCESS
End of Test Suite                                                : FAILED
```

**Comment by bernhardkaindl** [comment]
@thelfer Thanks for the merge of my fixes for the testsuite, waiting for your remark on new infos on https://github.com/thelfer/tfel/issues/19.

To let spack's prepended `-march=` flags (and other for other compilers) take effect(many other packages do it likewise by removing `march=native` by filtering/patching), have a look at this PR, I hope you can just click merge/rebase into your develop branch: https://github.com/thelfer/spack/pull/13

**Comment by thelfer** [comment]
@bernhardkaindl I just closed https://github.com/thelfer/spack/pull/13. I hope it's ok for you. As the test failure is not really meaningful, could we finalize this PR ?

**Review by bernhardkaindl — APPROVED** [review]
Looks good, so the used -O3 is quite optimal for now:
https://github.com/thelfer/tfel/issues/19#issuecomment-960066563

**Pull request merged**
