### PR TITLE
py-tensorflow: fixing vector conversion error on aarch64

### PR DESCRIPTION
**Pull request by 0luhancheng0**
I recently encountered this error while building py-tensorflow https://stackoverflow.com/questions/56055359/tensorflow-lite-arm64-error-cannot-convert-const-int8x8-t , hope this pull request can fix it.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
I don't have aarch64 to test this on, but it looks good to me. Waiting a bit for @aweits to get a chance to review before merging.

**Comment by 0luhancheng0** [comment]
@adamjstewart im testing it right now, will convert the draft to an actual pull request once i finish it

**Comment by 0luhancheng0** [comment]
sorry i don't think i can test it anymore as i have lost access to the arm machine (it is provided by the hackathon https://github.com/arm-hpc-user-group/Cloud-HPC-Hackathon-2021). 
I don't think the last commit fixed the issue, the vector conversion error still pops up, maybe i mis-understood inject_flags function?

**Comment by adamjstewart** [comment]
Can anyone else with access to an ARM machine help debug this? @alalazo @becker33?

**Comment by adamjstewart** [comment]
This PR is pretty outdated, the original contributor can no longer test it, and it sounds like it never worked anyway. I'm going to close this, but if anyone wants to revive it feel free to reopen.

**Pull request closed without merging**
