### PR TITLE
Removes package mpix-launch-swift

### PR DESCRIPTION
**Pull request by kshitij-v-mehta**
Removing package, as it has been merged with the Turbine package (addresses #27163)

@j-woz

### CODE REVIEW

**Comment by eugeneswalker** [comment]
This reference will also need to be removed:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/exaworks/package.py#L21

**Review by alalazo — CHANGES_REQUESTED** [review]
See @eugeneswalker request

**Comment by eugeneswalker** [comment]
I tested locally removing the `depends_on(mpix-launch-swift)` from ExaWorks, and ExaWorks is now building in our E4S environments. FYI. Thank you.

**Comment by andre-merzky** [comment]
> This reference will also need to be removed:
> https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/exaworks/package.py#L21

Thanks!  This should be addressed now in #27216.

**Comment by kshitij-v-mehta** [comment]
Can this PR proceed and be merged? I see that dependencies in #27216 have been addressed.

**Comment by eugeneswalker** [comment]
I think this needs rebasing on develop in order for tests to pass. As soon as tests pass I will merge

**Comment by alalazo** [comment]
@kshitij-v-mehta Can you rebase the PR, so to proceed with merging?

**Comment by kshitij-v-mehta** [comment]
I have updated this PR. Let me know if it looks OK.

**Review by alalazo — CHANGES_REQUESTED** [review]
It seems `savanna` still references this.
```
PKG-DIRECTIVES: 2 issues found
1. savanna: unknown package 'mpix-launch-swift' in 'depends_on' directive
     in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/savanna/package.py
2. savanna: dependency on mpix-launch-swift cannot be satisfied by known versions of mpix-launch-swift
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/savanna/package.py
```

**Comment by kshitij-v-mehta** [comment]
I have removed Savanna as it is now part of the codar-cheetah package.

**Comment by alecbcs** [comment]
@kshitij-v-mehta Is this PR still something you'd like to pursue? It looks like there are a number of merge conflicts that need to be fixed.

**Comment by kshitij-v-mehta** [comment]
No, this PR is no longer necessary.

**Pull request closed without merging**
