### PR TITLE
Automated git version fixes

### PR DESCRIPTION
**Pull request by haampie**
This change is necessary to ensure that Spack doesn't build moving targets in
CI, and also improves reproducibilty and security in general.

Abbreviated commit shas are expanded to full length, to guard against future
clashes on short hash. It also guards against compromised repos and
man in the middle attacks, where attackers can easily fabricate a malicious
commit with a shasum prefix collision.

Versions with just tags now also get a commit sha, which can later be used to
check for retagged commits.

Spack by default fetches by commit sha if both tag and commit sha are provided,
git verifies the shasum.

This commit is [generated with a script](https://gist.github.com/haampie/3441e8608409732a6d3cb7841f524aab)

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot help

**Comment by haampie** [comment]
@spackbot maintainers

**Comment by haampie** [comment]
@tgamblin would you agree to merge this _without_ manually making "look prettier" on a per package basis, I trust this automated commit more than me manually fixing up 150+ packages. And Gitlab CI won't catch issues because it only tests 1 or 2 versions per package.

Notice that Gitlab CI is failing for the same reason it is failing on develop: it still concretizes to `dihydrogen@develop`.

**Review by alalazo — COMMENTED** [review]
> Versions with just tags now also get a commit sha, which can later be used to check for retagged commits.

Can we add an audit to packages to enforce that? Otherwise we'll get tags without an associated commit again with time

**Comment by haampie** [comment]
> Can we add an audit to packages to enforce that? Otherwise we'll get tags without an associated commit again with time

I think @alecbcs could potentially add this to his ci check that validates checksums, I won't do it here since it has overlap.

**Review by alalazo — APPROVED** [review]
Adding a commit sha to each and every tag is good reproducibility, but without a mechanism to prevent a tag to slip in the package without a commit sha we'll need to do PRs like this periodically...

**Pull request merged**
