### PR TITLE
Add proper distribution detection for Arch and Amazon Linux

### LINKED ISSUE #2155: Not including the architecture in the hashing causes hash collision on Arch
Just for fun, I tried to install an older version of gcc on my Arch machine. I was greated with the following error message:

```
spack install gcc@5.4.0
==> Installing gcc
==> Error: Specs gmp@6.1.1%gcc@6.2.1 arch=linux--x86_64^libsigsegv@2.10%gcc@6.2.1 arch=linux--x86_64^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux--x86_64 and gmp@6.1.1%gcc@6.2.1 arch=linux-None-x86_64 have the same SHA-1 prefix!
```

I suspect this is really happening because spack isn't detecting my architecture or OS correctly, but however it happened, you can see that both packages different arch properties. The manual leads me to believe that this should cause their hashes to differ, but apparently not.

### LINKED ISSUE #2156: Os or architecture for Arch is not properly detected
I tried to install an older gcc on my arch machine for fun, and I ran into this nice problem:

```
spack install gcc@5.4.0
==> Installing gcc
==> Error: Specs gmp@6.1.1%gcc@6.2.1 arch=linux--x86_64^libsigsegv@2.10%gcc@6.2.1 arch=linux--x86_64^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux--x86_64 and gmp@6.1.1%gcc@6.2.1 arch=linux-None-x86_64 have the same SHA-1 prefix!
```

You can clearly see that the os part of the triplet isn't detected properly. I have two triplets here, 'linux--x86_64' and 'linux-None-x86_64'.

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #2155, fixes #2156

Python 2 doesn't properly detect Arch Linux. This has been fixed in Python 3.3+, but was never backported to Python 2. This PR hopefully fixes that. See the following posts for details:

@krafczyk Can you test this out?

### CODE REVIEW

**Comment by krafczyk** [comment]
Building gcc 5.4.0 is currently proceeding normally. my `compilers.yaml` file gives the correct output for operating system:

```
compilers:
- compiler:
    flags: {}
    modules: []
    operating_system: arch
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@6.2.1
```

**Comment by adamjstewart** [comment]
I wonder if this could be extended to provide solutions for #1560 (Amazon Linux isn't detected). @hartzell Can you try this out? Maybe try adding:
```python
supported_dists=py_platform._supported_dists + ('arch', 'system'),
```
Might as well kill two birds with one stone.

**Comment by adamjstewart** [comment]
Support for Amazon Linux would also solve the problems in #1899 and #1792.

**Comment by adamjstewart** [comment]
The fix for Amazon Linux is documented as well:
https://bugs.python.org/issue18872

**Comment by adamjstewart** [comment]
For the record, on Python 2.7.12, I'm seeing the following list for `platform._supported_dists`:
```python
('SuSE', 'debian', 'fedora', 'redhat', 'centos', 'mandrake', 'mandriva', 'rocks', 'slackware', 'yellowdog', 'gentoo', 'UnitedLinux', 'turbolinux')
```
On Python 3.5.1, I'm seeing:
```python
('SuSE', 'debian', 'fedora', 'redhat', 'centos', 'mandrake', 'mandriva', 'rocks', 'slackware', 'yellowdog', 'gentoo', 'UnitedLinux', 'turbolinux', 'arch', 'mageia')
```
The difference is that `arch` and `mageia` were added. Mageia seems pretty new, it's a 2010 fork of Mandriva, so we could probably add support for that if we wanted. I'm not sure how popular it is, but I don't want to add it to Spack unless we test it first.

**Comment by js947** [comment]
My attempt at fixing this problem is in #1629 and would also solve #2155 and #2156 - this approach looks rather more straightforward though...

**Comment by adamjstewart** [comment]
I think this PR is definitely a simpler workaround for the problem (and it won't change the hashes again!). But when we add support for Python 3 we may have to go down your route. Is the platform module really deprecated in Python 3? I take it the distro package isn't standard in Python 2. Also, I love that your PR documents all of the possible values for distro id. That saves a lot of confusion.

**Comment by adamjstewart** [comment]
@tgamblin Can you take a look at this PR and at #1629? I think this should probably make it into `0.10`, as right now Spack doesn't work at all on Arch and Amazon Linux, and this simple fix should allow us to close 4 issues.

**Comment by tgamblin** [comment]
@adamjstewart @js947: I actually think I like #1629 the best, and I think `amazon` is better than `system` for identifying Amazon linux.

My only worry about #1629 is that it can be overly specific, something that @gartung does not want.  Or, perhaps more accurately, @gartung wants to be able to accept `rhel` binary packages on a `centos` system and vice versa.  

I would like to err on the side of more detailed build provenance, so when there *are* differences in builds, we can detect them.  I think that to handle @gartung's concerns we can add some compatibility rules to the binary packaging system, so that people can specify what they're willing to accept when downloading binary packages.  To be more concrete, I think we can add a setting that would tell the binary packaging system what's compatible with what and how specific to be about distros, and allow people who want to be more strict to do it.  @gartung: is that ok with you?

@adamjstewart @js947: thoughts?

**Comment by gartung** [comment]
OK by me.

**Comment by tgamblin** [comment]
Closed in favor of #1629.

**Pull request closed without merging**
