### PR TITLE
py-pandas: add v2.2.3

### PR DESCRIPTION
**Pull request by adamjstewart**
https://pandas.pydata.org/pandas-docs/version/2.2.3/whatsnew/v2.2.3.html

### CODE REVIEW

**Review by wdconinc — COMMENTED** [review]
Checksum verified. Leaving the rest up to maintainer.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by zackgalbreath** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by bernhardkaindl — APPROVED** [review]
Built in Ubuntu 22.04.

@rgommers Will merge, as I haven't found a response from you since Adam opened this a week ago.

**Comment by rgommers** [comment]
> @rgommers Will merge, as I haven't found a response from you since Adam opened this a week ago.

No worries. @adamjstewart FYI, I expect to be on low-availability mode until the middle of October at least.

**Pull request merged**
