### PR TITLE
boost: fix a bug which broke it on macOS with clang+gfortran

### PR DESCRIPTION
**Pull request by davydden**
fix a bug introduced in https://github.com/LLNL/spack/pull/1621 which made boost broken on macOS with clang+gfortran.

Prior to this PR boost used gcc
```
$ otool -L ~/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.61.0-q23jffr3h2hg5hmpfyv6ual75r7ucwqz/lib/libboost_python-mt.dylib
/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.61.0-q23jffr3h2hg5hmpfyv6ual75r7ucwqz/lib/libboost_python-mt.dylib:
    /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.61.0-q23jffr3h2hg5hmpfyv6ual75r7ucwqz/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-thrupxvh7uemrmwdmo372dxk4vxgh2bt/lib64/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.22.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
    /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-thrupxvh7uemrmwdmo372dxk4vxgh2bt/lib64/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
even with
```
compilers:
- compiler:
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-thrupxvh7uemrmwdmo372dxk4vxgh2bt/bin/gfortran
      fc: /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-thrupxvh7uemrmwdmo372dxk4vxgh2bt/bin/gfortran
    spec: clang@8.0.0-apple
```
This PR fixes it back to 
```
$ otool -L ~/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.60.0-fqoy5kmitv5o2fomtopkmcn36upcpxdg/lib/libboost_python-mt.dylib
/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.60.0-fqoy5kmitv5o2fomtopkmcn36upcpxdg/lib/libboost_python-mt.dylib:
	/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/boost-1.60.0-fqoy5kmitv5o2fomtopkmcn36upcpxdg/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
and more importantly resolves cryptic linking errors like 
```
Undefined symbols for architecture x86_64:
  "boost::python::objects::function_object(boost::python::objects::py_function const&, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&)", referenced from:
      void boost::python::detail::def_init_aux<boost::python::class_<dealii::python::CellAccessorWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::default_call_policies, boost::mpl::vector3<dealii::python::TriangulationWrapper&, int const, int const>, boost::mpl::size<boost::mpl::vector3<dealii::python::TriangulationWrapper&, int const, int const> > >(boost::python::class_<dealii::python::CellAccessorWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>&, boost::mpl::vector3<dealii::python::TriangulationWrapper&, int const, int const> const&, boost::mpl::size<boost::mpl::vector3<dealii::python::TriangulationWrapper&, int const, int const> >, boost::python::default_call_policies const&, char const*, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&) in export_cell_accessor.cc.o
      void boost::python::class_<dealii::python::CellAccessorWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<dealii::python::CellAccessorWrapper, dealii::python::PointWrapper (dealii::python::CellAccessorWrapper::*)() const, boost::python::detail::def_helper<char [69], boost::python::detail::keywords<1ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> >(dealii::python::CellAccessorWrapper*, char const*, dealii::python::PointWrapper (dealii::python::CellAccessorWrapper::*)() const, boost::python::detail::def_helper<char [69], boost::python::detail::keywords<1ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in export_cell_accessor.cc.o
      void boost::python::class_<dealii::python::CellAccessorWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<dealii::python::CellAccessorWrapper, void (dealii::python::CellAccessorWrapper::*)(int, dealii::python::PointWrapper&), boost::python::detail::def_helper<char [69], boost::python::detail::keywords<3ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> >(dealii::python::CellAccessorWrapper*, char const*, void (dealii::python::CellAccessorWrapper::*)(int, dealii::python::PointWrapper&), boost::python::detail::def_helper<char [69], boost::python::detail::keywords<3ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in export_cell_accessor.cc.o
      void boost::python::class_<dealii::python::CellAccessorWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<dealii::python::CellAccessorWrapper, dealii::python::PointWrapper (dealii::python::CellAccessorWrapper::*)(int) const, boost::python::detail::def_helper<char [69], boost::python::detail::keywords<2ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> >(dealii::python::CellAccessorWrapper*, char const*, dealii::python::PointWrapper (dealii::python::CellAccessorWrapper::*)(int) const, boost::python::detail::def_helper<char [69], boost::python::detail::keywords<2ul>, boost::python::detail::not_specified, boost::python::detail::not_specified> const&, ...) in export_cell_accessor.cc.o
      void boost::python::detail::def_init_aux<boost::python::class_<dealii::python::PointWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::default_call_policies, boost::mpl::vector1<boost::python::list>, boost::mpl::size<boost::mpl::vector1<boost::python::list> > >(boost::python::class_<dealii::python::PointWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>&, boost::mpl::vector1<boost::python::list> const&, boost::mpl::size<boost::mpl::vector1<boost::python::list> >, boost::python::default_call_policies const&, char const*, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&) in export_point.cc.o
      void boost::python::detail::def_init_aux<boost::python::class_<dealii::python::TriangulationWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::default_call_policies, boost::mpl::vector1<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, boost::mpl::size<boost::mpl::vector1<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> > >(boost::python::class_<dealii::python::TriangulationWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>&, boost::mpl::vector1<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> const&, boost::mpl::size<boost::mpl::vector1<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> >, boost::python::default_call_policies const&, char const*, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&) in export_triangulation.cc.o
      void boost::python::detail::def_init_aux<boost::python::class_<dealii::python::TriangulationWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, boost::python::default_call_policies, boost::mpl::vector2<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, boost::mpl::size<boost::mpl::vector2<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> > >(boost::python::class_<dealii::python::TriangulationWrapper, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>&, boost::mpl::vector2<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> const&, boost::mpl::size<boost::mpl::vector2<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&> >, boost::python::default_call_policies const&, char const*, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&) in export_triangulation.cc.o
      ...
  "boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::__1::pair<void*, boost::python::type_info> (*)(void*))", referenced from:
      dealii::python::export_cell_accessor() in export_cell_accessor.cc.o
      dealii::python::export_point() in export_point.cc.o
      dealii::python::export_triangulation() in export_triangulation.cc.o
  "boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::text_iarchive_impl(std::__1::basic_istream<char, std::__1::char_traits<char> >&, unsigned int)", referenced from:
      dealii::python::TriangulationWrapper::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in triangulation_wrapper.cc.o
  "boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      boost::archive::basic_text_oarchive<boost::archive::text_oarchive>::save_override(boost::archive::class_name_type const&) in triangulation_wrapper.cc.o
  "boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::text_oarchive_impl(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, unsigned int)", referenced from:
      dealii::python::TriangulationWrapper::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in triangulation_wrapper.cc.o
  "boost::archive::basic_text_iprimitive<std::__1::basic_istream<char, std::__1::char_traits<char> > >::~basic_text_iprimitive()", referenced from:
      dealii::python::TriangulationWrapper::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in triangulation_wrapper.cc.o
      boost::archive::text_iarchive::~text_iarchive() in triangulation_wrapper.cc.o
      boost::archive::text_iarchive::~text_iarchive() in triangulation_wrapper.cc.o
  "boost::archive::basic_text_oprimitive<std::__1::basic_ostream<char, std::__1::char_traits<char> > >::~basic_text_oprimitive()", referenced from:
      dealii::python::TriangulationWrapper::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in triangulation_wrapper.cc.o
      boost::archive::text_oarchive::~text_oarchive() in triangulation_wrapper.cc.o
      boost::archive::text_oarchive::~text_oarchive() in triangulation_wrapper.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
See https://github.com/dealii/dealii/issues/3057.

@KineticTheory please check if it still works with Intel compilers. Otherwise we need to find a way to keep both cases working.

TODO:

- [x] check that `spack install dealii@develop~oce` builds fine without those linking errors.

### CODE REVIEW

**Comment by tgamblin** [comment]
@scheibelp: LGTM.  Any objections?

**Comment by scheibelp** [comment]
I definitely like this since it looks like the previous commit stripped out some changes that were important for customizing compilers and this adds it back (for boost package.py a lot of this is restoring previous logic). I'm guessing that @KineticTheory changed that though because they ran into some issue with this logic. It would be useful to know what the issue was.

**Comment by KineticTheory** [comment]
This PR breaks my ability to build boost with the Intel compiler.

```
==> './b2' 'install' 'threading=multi' '-j' '16' 'variant=release' '-s' 'BZIP2_INCLUDE=/yellow/usr/projects/jayenne/devs/kellyt/build/ml/vendors/spack/opt/spack/linux-redhat6-x86_64/intel-16.0.3/bzip2-1.0.6-os4zyxn7pvxqnw6bicrlppg3vcolyy5j/include' '-s' 'BZIP2_LIBPATH=/yellow/usr/projects/jayenne/devs/kellyt/build/ml/vendors/spack/opt/spack/linux-redhat6-x86_64/intel-16.0.3/bzip2-1.0.6-os4zyxn7pvxqnw6bicrlppg3vcolyy5j/lib' '-s' 'ZLIB_INCLUDE=/yellow/usr/projects/jayenne/devs/kellyt/build/ml/vendors/spack/opt/spack/linux-redhat6-x86_64/intel-16.0.3/zlib-1.2.8-iestlxjr7lvuuh3rxigtsp7clprlfitv/include' '-s' 'ZLIB_LIBPATH=/yellow/usr/projects/jayenne/devs/kellyt/build/ml/vendors/spack/opt/spack/linux-redhat6-x86_64/intel-16.0.3/zlib-1.2.8-iestlxjr7lvuuh3rxigtsp7clprlfitv/lib' 'toolset=intel-linux' 'link=static,shared' '--layout=tagged'
error: at project-config.jam:12
error: duplicate initialization of intel-linux with the following parameters: 
error: version = <unspecified>
error: previous initialization at ./user-config.jam:1
```

Essentially, the term `toolset=intel-linux` must not appear as an option given to `./b2`. However, it must be listed as an argument to `bootstrap.sh`.

**Comment by davydden** [comment]
@KineticTheory does it work if you remove this? (i will test now if boost works fine on my side without toolset specified)...

**Comment by davydden** [comment]
@KineticTheory removing toolset from b2 does not brake anything on my side (`clang` is correctly used). I updated the PR.

**Comment by KineticTheory** [comment]
@davydden After playing with this a bit, it seems that I also had to remove lines 168-170 to make it work with intel.

```
-  compiler_wrapper = join_path(spack.build_env_path, 'c++')
-           f.write("using {0} : : {1} ;\n".format(boostToolsetId,
-                                                  compiler_wrapper))
```

**Comment by davydden** [comment]
@KineticTheory what's the error? what if you use `spack_cxx` for `compiler_wrapper`?

**Comment by davydden** [comment]
namely, do
```
f.write("using {0} : : {1} ;\n".format(boostToolsetId,
                                                   spack_cxx))
```

**Comment by KineticTheory** [comment]
It's the same error as before:

```
error: at project-config.jam:12
error: duplicate initialization of intel-linux with the following parameters: 
error: version = <unspecified>
error: previous initialization at ./user-config.jam:1
```

I'm not an expert in boost build, but I think that the problem isn't the compile wrapper name, it is the appearance of `using intel-linux` in `user-config.jam.`

**Comment by davydden** [comment]
Ok, i am trying with now with
```
def determine_toolset(self, spec):
        # Note:
        # do not use darwin on macOS as this does not play nice with
        # mixed compilers (clang+gfortran). Go the same route as Linux.

        toolsets = {'g++': 'gcc',
                    'icpc': 'intel',
                    'clang++': 'clang'}

        if spec.satisfies('@1.47:'):
            toolsets['icpc'] += '-linux'
        for cc, toolset in toolsets.iteritems():
            if cc in self.compiler.cxx_names:
                return toolset

        # fallback to gcc if no toolset found
        return 'gcc'
```

**Comment by davydden** [comment]
@KineticTheory the current version of PR seems to be ok on macOS with `clang+gfortran`. It should also be fine for Intel on Linux.

@tgamblin @scheibelp give this a second look, please.

**Comment by davydden** [comment]
FYI, [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb#L69-L72) specify toolset and compiler in `user-config.jam`. Maybe the current state is not a proper solution...

**Comment by KineticTheory** [comment]
@davydden LGTM.  cdedf6d works for intel on my system.

**Comment by scheibelp** [comment]
The reason I originally modified user-config.jam to refer to spack's compiler wrappers was to get boost to use the right *version* of the compiler (e.g. if I have two versions of gcc). IMO it may be better to just omit the setting from user-config.jam when the toolset is intel-linux.

**Comment by davydden** [comment]
>  IMO it may be better to just omit the setting from user-config.jam when the toolset is intel-linux (but still do it otherwise).

makes sense, will update. 

What about toolset for b2? shall I also keep it unless toolset is intel-linux?

**Comment by scheibelp** [comment]
IMO yes (admittedly an opinion, I don't have time at the moment to check if it's required)

**Comment by davydden** [comment]
@scheibelp btw, for `compiler_wrapper`, i guess i can just use `spack_cxx` instead of `join_path(spack.build_env_path, 'c++')`?

**Comment by tgamblin** [comment]
@davydden: yes, and `spack_cxx` is better as it is set to an appropriately named symlink in the various subdirectories of `spack.build_env_path`.  i.e., it points to a symlink called `g++` or `icpc` and not just `c++`.  For autotools and other systems that are sensitive to the compiler name, this often makes the difference of getting correct flags or not.

**Comment by davydden** [comment]
@KineticTheory please check the boost PR again. Essentially i wrapped offending things into `if not spec.satisfies('%intel'):`, should work for you AFAICT.

**Comment by KineticTheory** [comment]
@davydden LGTM. I was able to build with intel@16.0.3.

**Comment by tgamblin** [comment]
WIP no more, then?

**Comment by davydden** [comment]
> WIP no more, then?

just double checking that linking error is gone. I will ping you as soon as it's ready.

**Comment by davydden** [comment]
@tgamblin good to merge from my side.

**Pull request merged**
