### PR TITLE
Make install directory a config option

### PR DESCRIPTION
**Pull request by hegner**
This PR refactors the settings for the install area into a separate install_area.py and makes the location of this area a configurable. Even though there is only one layout currently, the directory_layout has been made a config option as well.

### CODE REVIEW

**Comment by hegner** [comment]
@tgamblin - what would be needed to finish this one?
As I was touching plenty of files in this PR, I was flooded with warnings. Used some waiting time to tackle a few of those. Obviously this increases the risk for merge conflicts. But probably unavoidable quickly after introducing checks.

**Comment by mathstuf** [comment]
@hegner I'd recommend splitting out the style fixes. The conflict resolution train is always longer than you think :) .

**Comment by mamelara** [comment]
Any word on the status of this PR? NERSC would be very interested changing the install path.

**Comment by hegner** [comment]
@mamelara - I think @tgamblin should comment on the style fix issues. I could then do the necessary changes - if any - in no time.

**Comment by adamjstewart** [comment]
Out of curiosity, what happens when two users install Spack in their home directories and both set their installation directory to the same directory. Are the install database and locks stored in the installation directory or should I expect to see lots of "spack find: not installed, spack install: already installed, spack uninstall: not installed" kind of confusion?

Someday I hope to have multiple system admins capable of installing software with Spack at the same time. Since at least one of us would be actively developing Spack and changing git branches, we would need to have multiple Spack installations. But it would be annoying to have to have multiple installation directories.

**Comment by tgamblin** [comment]
The DB and its lock live in the installation directory (`$root/.spack-db/index.yaml`, `$root/.spack-db/lock`).  And when we change to finer-grained locking and parallel installs, locks will be per-prefix.

**Comment by alalazo** [comment]
> And when we change to finer-grained locking and parallel installs, locks will be per-prefix.

@tgamblin OT, just to share the experience. Beware of : 
```python
remove_dead_links(spack.stage_path)
```
in `stage.py`. It is bound to break things when you go parallel if multiple processes are using local storage on different nodes.

**Comment by tgamblin** [comment]
@hegner: I rebased this on develop and am adding some updates to make `install.yaml` into a top-level `config.yaml`.  Can you check the box on this PR that says [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so that I can push updates here?

**Comment by adamjstewart** [comment]
`install.yaml` -> `config.yaml` sounds great to me! I'm very excited about moving towards generic Spack configurability.

**Comment by tgamblin** [comment]
You're going to like these modifications 😄

**Comment by hegner** [comment]
@tgamblin - here you have it

**Comment by tgamblin** [comment]
Thanks!

**Comment by justintoo** [comment]
@tgamblin  @hegner Is the install directory self-contained? i.e. space is also installed with no dependency on the space source directory?

**Comment by tgamblin** [comment]
@justintoo: Once the install is done, it doesn't depend on the `package.py` files or the build stage at all.  The build stage is actually removed by default after a successful install.

**Comment by tgamblin** [comment]
@hegner: are you sure you checked the box here?  I can't seem to push.  Maybe I'm doing something wrong.

**Comment by tgamblin** [comment]
Just closing and moving to #2152.

**Comment by hegner** [comment]
@tgamblin - I enabled it. Maybe the problem is that my repo isn't a direct fork of yours. But let's follow up on the new PR.

**Pull request closed without merging**
