### PR TITLE
pika: Add 0.28.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
Note, I've added a conflict with hwloc which is fixed by this new version of pika. The specific conflict would be `conflicts("^hwloc@2.11:", when="@:0.27 target=<grace-hopper>")` but I suppose there's no way to restrict it to a Grace-Hopper system only? I've stuck with a `target=aarch64` conflict to make it a bit more specific at least.

**Review by albestro — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by albestro** [comment]
@msimberg would you go for adding a conflict in `dla-future` like this?

```python
conflict("pika@0.28:", when="@:0.6.0")
```

- https://gitlab.spack.io/spack/spack/-/jobs/12405552#L410
- https://github.com/eth-cscs/DLA-Future/blob/c98e3343ff5e32f8c3ec87608b260fbc75d29dde/src/init.cpp#L401

**Comment by msimberg** [comment]
> @msimberg would you go for adding a conflict in `dla-future` like this?
> 
> ```python
> conflict("pika@0.28:", when="@:0.6.0")
> ```
> 
>     * https://gitlab.spack.io/spack/spack/-/jobs/12405552#L410
> 
>     * https://github.com/eth-cscs/DLA-Future/blob/c98e3343ff5e32f8c3ec87608b260fbc75d29dde/src/init.cpp#L401

Ah yes, thanks for noticing that! I completely forgot about that breaking change... Yes, that conflict sounds sane to me. I'll push a change.

**Comment by msimberg** [comment]
@albestro I've added a few more constraints in https://github.com/eth-cscs/DLA-Future/pull/1180/files#diff-4ae831b914b16acdcddf955a71fcbf934d89e0cb929ed6acf161fde7f5ff41db. Do you think it makes sense to bring those over here already now? The 0.7 constraint would be helpful for building `dla-future@master` already now, right?

**Comment by albestro** [comment]
> @albestro I've added a few more constraints in https://github.com/eth-cscs/DLA-Future/pull/1180/files#diff-4ae831b914b16acdcddf955a71fcbf934d89e0cb929ed6acf161fde7f5ff41db. Do you think it makes sense to bring those over here already now? The 0.7 constraint would be helpful for building `dla-future@master` already now, right?

not sure...adding in `dla-future`

```python
depends_on("pika@0.28:", when="@0.7:")
```

would make `dla-future@master` build with at least `pika@0.28`, and until https://github.com/eth-cscs/DLA-Future/pull/1180 is not merged, we will still have in the code a reference to `numa_domains`. isn't it?

**Comment by msimberg** [comment]
> not sure...adding in `dla-future`
> 
> ```python
> depends_on("pika@0.28:", when="@0.7:")
> ```
> 
> would make `dla-future@master` build with at least `pika@0.28`, and until [eth-cscs/DLA-Future#1180](https://github.com/eth-cscs/DLA-Future/pull/1180) is not merged, we will still have in the code a reference to `numa_domains`. isn't it?

Right, the intention is to have https://github.com/eth-cscs/DLA-Future/pull/1180 merged as soon as possible of course (possibly even before this PR).

However, thinking about it a bit more, I conditionally adapted https://github.com/eth-cscs/DLA-Future/pull/1180 so that won't be a hard requirement to use `pika@0.28:` but that it'll again work with older versions of pika. So I take back my suggestion, and leave the conflict as you originally suggested.

**Review by albestro — APPROVED** [review]
As discussed with @msimberg offline, we'd like to merge this as it is now.

This won't work for a short period for `dla-future@master` because it needs https://github.com/eth-cscs/DLA-Future/pull/1180, which will be merged hopefully as soon as this PR gets merged.

**Pull request merged**
