### PR TITLE
new package: heasoft

### PR DESCRIPTION
**Pull request by glennpj**

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
Is there any way to fetch the patches from a url?

**Comment by glennpj** [comment]
Unfortunately, no. I may have to wordsmith the comment in the recipe, but "patches" are actually full replacement files that are dropped in. They provide a "patch" utility that tracks what versions of these files have been put in place, and triggers a rebuild. I created actual patches by diffing those files in series to keep the naming consistent with the heasoft site. I thought that was the best way to indicate what patch level heasoft, actually xspec, is at. This scheme also means that new patches may need to be added over time, with all of the previous files still being valid. Just using the latest file updates would mean that file would be different over time and would be hard to manage. I am open to other ideas but creating patches to correspond with what the heasoft project says is a patch level seemed to be the best way to go.

**Comment by glennpj** [comment]
Actually, I should be a little more pedantic. There is a tarball that can be downloaded that contains the set of replacement files. For spack though, that would mean downloading new tarballs for each patch level update, which would replicate all of the previous files each time. It seemed more efficient to generate and use actual patches.

**Review by alalazo — APPROVED** [review]
Distributing software this way is kind of weird, but I agree that if patches stay the same we can just keep on adding them, rather than downloading new tarballs or relying of their tool at build time (that would be problematic on air-gapped systems)

**Pull request merged**
