### PR TITLE
[py-tensorflow-hub] applied patch for newer version of zlib

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
Looks like we have an audit check failure that is required to be fixed before this package can be merged.  

```
PKG-DIRECTIVES: 1 issue found
[9](https://github.com/spack/spack/runs/6428707165?check_suite_focus=true#step:6:9)
1. patch URL in package py-tensorflow-hub must end with ?full_index=1
[10](https://github.com/spack/spack/runs/6428707165?check_suite_focus=true#step:6:10)
    https://github.com/tensorflow/hub/commit/049192a7edd3e80eebf1735b93f57c7965381bdb.patch
 ```

**Comment by tldahlgren** [comment]
@aweits Did you want to comment on this PR before it is merged?

**Comment by aweits** [comment]
> @aweits Did you want to comment on this PR before it is merged?

I trust @qwertos

**Comment by tldahlgren** [comment]
> > @aweits Did you want to comment on this PR before it is merged?
> 
> I trust @qwertos

Didn't intend to imply you didn't.  Just wanted to make sure you had an opportunity to comment if you wanted to.

**Review by tldahlgren — APPROVED** [review]

**Comment by aweits** [comment]
> Didn't intend to imply you didn't. Just wanted to make sure you had an opportunity to comment if you wanted to.

Thank you, and I did not take it that way fwiw.

**Pull request merged**
