### PR TITLE
autoconf: update to 2.70

### PR DESCRIPTION
**Pull request by nightlark**
Got some build errors about help2man not being found for 2.70

### CODE REVIEW

**Comment by nightlark** [comment]
What’s the meaning of the failed doc error for the spack graph command? I’m not seeing how it relates to the changes made.

**Review by ChristianTackeGSI — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
Closing and re-opening the PR to trigger tests to see if doing so resolves the check failure.

**Review by tldahlgren — COMMENTED** [review]
Confirmed the version is available on the specified site as of December 8th.  Also noted `spack graph autoconf@2.70` does *not* error out.

Update:  I get the same issue when I run `make` within the `$SPACK_ROOT/lib/spack/docs` except I'm also getting `gpgconf: invalid option "--create-socketdir"`.

**Review by adamjstewart — APPROVED** [review]

**Comment by tldahlgren** [comment]
Let's try to force the checks again.

**Comment by alalazo** [comment]
> What’s the meaning of the failed doc error for the spack graph command? I’m not seeing how it relates to the changes made.

Producing a graph of `hdf5` involves looking at which `autoconf` to use for the package itself or any of the transitive dependencies. I suspect this may have to do with the added `help2man` dependency, but didn't investigate it further.

**Comment by nightlark** [comment]
Hm okay. When the machine I was using is back up I'll poke at it some.

**Comment by alalazo** [comment]
Closing since in the meanwhile v2.70 and v2.71 have been added upstream. Apologies for the delayed reply and thanks for the PR!

**Pull request closed without merging**
