### PR TITLE
Fix compiler version issues (concrete vs range)

### PR DESCRIPTION
**Pull request by haampie**
Fix some issues where compiler detection creates CompilerSpec instances with non-concrete versions

### CODE REVIEW

**Review by albestro — DISMISSED** [review]
Thanks! It works!

**Comment by toxa81** [comment]
Just for personal education, what is @= syntax?

**Comment by toxa81** [comment]
Just for personal education, what is @= syntax?

**Comment by haampie** [comment]
> Just for personal education, what is @= syntax?

It's to distinguish between ranges and specific versions, so `mpich@4.1` matches `4.1` and `4.1.1` etc, while `mpich@=4.1` matches only version `4.1` exactly (not `4.1.1`).

**Comment by haampie** [comment]
See https://spack.readthedocs.io/en/latest/basic_usage.html#version-specifier for docs

**Review by alalazo — APPROVED** [review]

**Review by albestro — APPROVED** [review]

**Pull request merged**
