### PR TITLE
caffe: Use MPI compiler when using HDF5 with MPI.

### PR DESCRIPTION
**Pull request by t-karatsu**
Modified to compile with mpicc and mpicxx If hdf5 was compiled with MPI.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@bvanessen

**Comment by alalazo** [comment]
@t-karatsu Ping me again for a merge if you don't get any reply in a few days, thanks!

**Comment by t-karatsu** [comment]
@alalazo Thanks for comment! This pull request doesn't seem to be checked yet.
Could you confirm it?

**Comment by alalazo** [comment]
@t-karatsu You're completely right. Since we don't have high traffic on the package I'll merge this. @bvanessen Feel free to follow up, if needed, in another PR.

**Comment by bvanessen** [comment]
Okay, if I run into issues, I will follow up.

**Pull request merged**
