### PR TITLE
e4s ci: py-libensemble: activate variants

### PR DESCRIPTION
**Pull request by eugeneswalker**
E4S CI: explicitly turn on `py-libensemble` variants

@jlnav @shuds13

### CODE REVIEW

**Comment by shuds13** [comment]
Looks good to me.

**Review by ax3l — DISMISSED** [review]

**Comment by ax3l** [comment]
Oh, general comment: per Spack convention, the `mpi` variant of a package should default to `True`:
https://spack.readthedocs.io/en/latest/packaging_guide.html#variant-names

Maybe something we can also change in the package itself @shuds13 ?

**Comment by eugeneswalker** [comment]
> Oh, general comment: per Spack convention, the `mpi` variant of a package should default to `True`: https://spack.readthedocs.io/en/latest/packaging_guide.html#variant-names
> 
> Maybe something we can also change in the package itself @shuds13 ?

Happy to push this change to `py-libensemble` package.py here if you would like @shuds13

**Comment by shuds13** [comment]
> Happy to push this change to `py-libensemble` package.py here if you would like @shuds13

Yes, I'm okay with this.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
