### PR TITLE
petsc, py-petsc4py: add v3.21.3

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Does this include the fix for ROCm 6 ?
* https://gitlab.com/petsc/petsc/-/merge_requests/7523

**Review by eugeneswalker — DISMISSED** [review]

**Comment by balay** [comment]
No - those changes are in `main` branch - so they will be in the next major release 3.22 - due in Sept

3.21.x are (monthly) minor bug fix updates(off release branch), and major release (off main branch) are on 6month cycle..

**Comment by eugeneswalker** [comment]
> No - those changes are in `main` branch - so they will be in the next major release 3.22 - due in Sept
> 
> 3.21.x are (monthly) minor bug fix updates(off release branch), and major release (off main branch) are on 6month cycle..

Gotcha. Are all the edits in the ROCm PR needed for ROCm 6? Or just some? Would you object to me patching them in for 3.21 so we can include petsc+rocm in next E4S release where we plan to use ROCm 6+?

**Comment by balay** [comment]
> Would you object to me patching them in for 3.21 so we can include petsc+rocm in next E4S release where we plan to use ROCm 6+?

with a conditional on rocm 6+ - I guess only the first commit is needed (can perhaps  also remove X.py change from it)

cc: @jczhang07

**Comment by jczhang07** [comment]
> > Would you object to me patching them in for 3.21 so we can include petsc+rocm in next E4S release where we plan to use ROCm 6+?
> 
> with a conditional on rocm 6+ - I guess only the first commit is needed (can perhaps also remove X.py change from it)
> 
> cc: @jczhang07

It looks to me all three commits are needed (could remove the X.py change).

**Review by tldahlgren — CHANGES_REQUESTED** [review]
According to `pyproject.toml`, `py-petsc4py` should have the `py-cython` dependency more constrained for the new version:

```
requires = [
  "cython >= 3",
  "numpy",
  "setuptools",
]
```

**Comment by balay** [comment]
> requires = [  "cython >= 3", ..

@tldahlgren please check my update on this PR

**Review by tldahlgren — APPROVED** [review]
LGTM.  Thanks.

**Pull request merged**
