### PR TITLE
llvm-doe: incorporate updates to official llvm Spack package

### PR DESCRIPTION
**Pull request by eugeneswalker**
Update `llvm-doe` package, incorporating changes from the official LLVM Spack package.

Add `llvm-doe @13.0.0` version

@shintaro-iwasaki

### CODE REVIEW

**Review by shintaro-iwasaki — APPROVED** [review]
Thanks. It looks good to me.

**Comment by shintaro-iwasaki** [comment]
Regarding this package, I would like to recommend @vlkale (see #20719) for a maintainer since I am no longer working for LLVM DOE efforts. @vlkale: if you have anyone in your mind, please leave a comment.

**Comment by vlkale** [comment]
> Regarding this package, I would like to recommend @vlkale (see #20719) for a maintainer since I am no longer working for LLVM DOE efforts. @vlkale: if you have anyone in your mind, please leave a comment.

@shintaro-iwasaki Yes, I will be the maintainer.

**Review by wspear — APPROVED** [review]
I don't see any issues.

**Pull request merged**
