### PR TITLE
[tutorials] match object syntax.

### PR DESCRIPTION
**Pull request by stephenmsachs**
self.compiler doe not have attribute pic_flag, instead
self.compiler.{cc,cxx,fc}_pic_flag exist.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed change matches the current package wrt pic flags.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Please resolve the style issues:

```
Note: Some files had incompatible versions so the results might not be correct!
424  Minimum required versions: 2.6
425  Incompatible versions:     3
426  Target versions not met:   2.6-, 3.5-
427  Error: Process completed with exit code 1.
```

I recommend using string formatting for each arg.

**Comment by stephenmsachs** [comment]
Seems like the style issues comes from lib/spack/spack/util/crypto.py . I did not touch that file.

**Comment by stephenmsachs** [comment]
I guess the code base has moved on so this is no longer relevant.

**Pull request closed without merging**
