### PR TITLE
ucx: new version, 1.10.1

### PR DESCRIPTION
**Pull request by robert-mijakovic**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]
@hppritcha FYI

**Comment by romerojosh** [comment]
Is the 1.10.1 SHA correct? I get something different:
```
$ wget https://github.com/openucx/ucx/releases/download/v1.10.1/ucx-1.10.1.tar.gz
$ sha256sum ucx-1.10.1.tar.gz
ae9a108af6842ca135e7ec9b6131469adf9f1e50f899349fafcc69a215368bc9  ucx-1.10.1.tar.gz
```

**Comment by hppritcha** [comment]
hmm...I get the ae9.... too.

**Comment by hppritcha** [comment]
i'll open a PR to fix this

**Comment by robert-mijakovic** [comment]
Sorry guys, it seems the script took the wrong one.
It took the archive from the tags and not releases.
```
$ wget https://github.com/openucx/ucx/archive/refs/tags/v1.10.1.tar.gz
$ sha256sum v1.10.1.tar.gz 
80a0abb7123cc8e49978078f88614f6ba9fc767bf4193850ceefcf1ef4b0a50f  v1.10.1.tar.gz
```

**Pull request merged**
