### PR TITLE
openssl: New version 1.1.1q

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
This update breaks on MacOS for me

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/2701014979

Previously openssl-1.1.1p worked

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/2695975437

For now forcing  openssl-1.1.1p usage for this job

**Comment by zinphi** [comment]
As openssl is needed for clingo, bootstrapping is broken for now on MacOS. Seems to be a problem within openssl and strict compilation flags (-Werror) together with the current Apple clang version. As user I was not able to tell the bootstrapper to use a different version. Only solution for me was to change to v0.18 for bootstrapping and to change back afterwards.

**Comment by tgamblin** [comment]
I am going to try to get #30882 merged soon, which would strip `-Werror` from all builds by default.  We had tried to get universal `-Werror` stripping into Spack with #30284, but we had to revert it because some packages were actually sensitive to `-Werror` *not* being there 🤯.

**Comment by kuberry** [comment]
Same, this breaks on MacOSX for me as well. Can we get a reversion back to 1.1.1p until the -Werror gets sorted out? Or, perhaps a patch on 1.1.1q to fix what -Werror is complaining about, namely:

```make
/Users/pakuber/test_spack_xyce/spack/opt/spack/darwin-monterey-skylake/apple-clang-13.1.6/perl-5.34.1-ejtg25ys7hc5xvrsonxj7gkgtanxobb5/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" tools/c_rehash.in > "tools/c_rehash"
chmod a+x apps/CA.pl
chmod a+x tools/c_rehash
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
chmod a+x apps/tsget.pl
1 error generated.
make[1]: *** [test/v3ext.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
==> [2022-07-14-05:28:53.125266] Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 errors found in build log:
     961    /Users/pakuber/test_spack_xyce/spack/opt/spack/darwin-monterey-skylake/apple-clang-13.1.6/perl-5.34.1-ejtg25ys7hc5xvrsonxj7gkgtanxobb5/bin/perl "-I." -Mcon
            figdata "util/dofile.pl" \
     962    	    "-oMakefile" apps/tsget.in > "apps/tsget.pl"
     963    /Users/pakuber/test_spack_xyce/spack/opt/spack/darwin-monterey-skylake/apple-clang-13.1.6/perl-5.34.1-ejtg25ys7hc5xvrsonxj7gkgtanxobb5/bin/perl "-I." -Mcon
            figdata "util/dofile.pl" \
     964    	    "-oMakefile" tools/c_rehash.in > "tools/c_rehash"
     965    chmod a+x apps/CA.pl
     966    chmod a+x tools/c_rehash
  >> 967    test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-
            function-declaration]
     968            if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
     969                           ^
     970    test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
     971    chmod a+x apps/tsget.pl
     972    1 error generated.
  >> 973    make[1]: *** [test/v3ext.o] Error 1
     974    make[1]: *** Waiting for unfinished jobs....
  >> 975    make: *** [all] Error 2
```

**Pull request merged**
