### PR TITLE
py-jsonschema: add v4.18.6 -> v4.22.0

### PR DESCRIPTION
**Pull request by tristan0x**
This change adds the latest minor versions of py-jsonschema since 4.17, and removes 3.0.1 to benefit 3.0.2. This change also updates the GitHub homepage of the project.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the homepage and new version sha256s.

**Review by tldahlgren — COMMENTED** [review]
We have guidelines on when to deprecate (versus remove) old versions.  Is "temporarily" deprecating (https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions) `3.0.1` a suitable alternative?

**Comment by tristan0x** [comment]
Thank you very @tldahlgren for your review.

> We have guidelines on when to deprecate (versus remove) old versions. Is "temporarily" deprecating (https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions) `3.0.1` a suitable alternative?

I don't have the expertise to decide whether 3.0.1 should be removed. I reverted this change in [d951b4f](https://github.com/spack/spack/pull/44025/commits/d951b4f499f6fc15e2c688ae0e4a1239b36b7392)

Thank you

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Not sure why `flux-sched` is affecting CI.

**Comment by tldahlgren** [comment]
🤦 

@spackbot run pipeline

**Comment by tristan0x** [comment]
> Not sure why `flux-sched` is affecting CI.

The CMake phase of package `flux-sched` finds py-jsonschema but seems unable to extract its version https://gitlab.spack.io/spack/spack/-/jobs/11204452#L674

I will try to reproduce the issue later on.

**Comment by alalazo** [comment]
Superseded by #46585

**Pull request closed without merging**
