### PR TITLE
legion: Add 23.09.0 and 23.12.0, remove control_replication.

### PR DESCRIPTION
**Pull request by elliottslaughter**
Adds two new versions of Legion, and removes `control_replication` branch, which has been merged to `master`.

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Pinging @rbberger to check the FleCSI change here.

**Review by rbberger — APPROVED** [review]

**Comment by rbberger** [comment]
LGTM

**Comment by rbberger** [comment]
@elliottslaughter one blocker for this one is that https://github.com/StanfordLegion/legion/commits/master/ still needs to be updated (the mirroring from Gitlab needs to push the change).

**Comment by elliottslaughter** [comment]
You are correct. Our CI is backed up but the mirror should hopefully go through in the next 24 hours or so. I'll come back here and comment when it does.

**Comment by elliottslaughter** [comment]
Legion `master` has now synced to GitHub, so this PR is now ready to go: https://github.com/StanfordLegion/legion/tree/master

Is there a Spack maintainer who can merge this?

**Review by alecbcs — APPROVED** [review]

**Pull request merged**
