### PR TITLE
compilers: aocc is now also available as a Cray PrgEnv

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by dev-zero** [comment]
What I wonder is why I also get the `PrgEnv` version in the specific compilers?
The problem is that `...@8.0.0` compilers are unusable. For Intel it doesn't matter much since the highest version takes precedence, but for `aocc` this means one has to specify the compiler version when installing things.

```
$ ./bin/spack compiler list
==> Available compilers
-- aocc sles15-any ----------------------------------------------
aocc@8.0.0  aocc@2.2.0.1  aocc@2.2.0.1

-- cce sles15-any -----------------------------------------------
cce@11.0.4

-- gcc sles15-any -----------------------------------------------
gcc@10.2.0  gcc@10.2.0  gcc@9.3.0  gcc@9.3.0  gcc@8.1.0

-- intel sles15-any ---------------------------------------------
intel@19.1.3.304  intel@19.1.3.304  intel@8.0.0
```

**Comment by tldahlgren** [comment]
@amd-toolchain-support @GaneshPrasadMA  Would you like to comment on this PR?

**Comment by dev-zero** [comment]
ping?

**Comment by dev-zero** [comment]
note, the problem with the invalid versions (and duplicated modules) is now tracked in #23398

**Review by alalazo — APPROVED** [review]

**Pull request merged**
