### PR TITLE
Added Environment Modules

### PR DESCRIPTION
**Pull request by citibeth**
For systems running Spack that don't have Environment Modules provided already, there's no need to build it manually (eg. Ubuntu 12.04)...

1. Added an environment-modules/package.py
2. Added documentation showing how to use the Spack-installed Environment Modules with Spack.

### CODE REVIEW

**Comment by tgamblin** [comment]
@citibeth: @gartung recently [added this](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/modules/package.py)

**Comment by citibeth** [comment]
Yes, we were working on it at the same time, parallel efforts.  This PR
incorporates what I believe to be the best coming from both efforts.

I DID suggest the name be changed from "modules" to "environment-modules."
 This would be consistent with RedHat and Ubuntu package naming.  But if
Spack wants to call it "modules," I won't press the issue.

**Comment by tgamblin** [comment]
@gartung: preferences on the name?

**Comment by gartung** [comment]
I agree that the module should be name "environment-modules". I created mine in a hurry and did not consider that.

**Comment by tgamblin** [comment]
ok i can merge this.  can someone remove modules?

**Pull request merged**
