### PR TITLE
Add support for raco pkgs

### PR DESCRIPTION
**Pull request by elfprince13**
This should be merged after #27506.

Still WIP - need some help figuring out how to handle uninstalls.

### CODE REVIEW

**Comment by elfprince13** [comment]
@arjunguha - Can you take a look at this? =)

**Review by arjunguha — DISMISSED** [review]
Sorry for the delay, I'm getting back to things after the winter. This looks good to me. I'll admit that @elfprince13 is clearly more familiar than me with the Racket ecosystem. He should also be a maintainer of the racket package, IMO. :)

**Comment by elfprince13** [comment]
@arjunguha - this is blocked until you actually use the Github UI to apply an "Approve" review so that there's a green check next to your name in the reviewers list.

(or I guess unless @alalazo manually approves in some way)

**Comment by alalazo** [comment]
@elfprince13 Is this ready? I didn't merge this because of:

> Still WIP - need some help figuring out how to handle uninstalls.

in the PR description

**Review by alalazo — DISMISSED** [review]

**Comment by elfprince13** [comment]
@alalazo Right now the story is basically you need to manually run `raco pkg remove` in conjunction with `spack uninstall` because Racket appears to only have two installation scopes (system or user), rather than a full path-based system like Python, and Spack doesn't appear to have a way to handle more complex uninstalls. A better solution will depend on upstream patches to Racket, and it seems better to get this in place for now.

**Review by alalazo — CHANGES_REQUESTED** [review]
Thanks for the explanation. The code looks good and I think getting this PR merged is fine as long as the limitations are documented. Can you add a doc page similar to the one other build systems have? Here's for instance [cmake](https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html)

You need to add a file under `lib/spack/docs/build_systems` and an entry under `build_systems.rst`.

**Review by arjunguha — DISMISSED** [review]

**Comment by elfprince13** [comment]
@alalazo - should be good to go now.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks!

**Pull request merged**
