### PR TITLE
Fix HDF5+mpi~fortran

### LINKED ISSUE #35377: Installation issue: HDF5+mpi~fortran requires a fortran compiler
### Steps to reproduce the issue

`spack` currently requires an MPI fortran wrapper for `hdf5+mpi` builds even with the `fortran` variant disabled :

https://github.com/spack/spack/blob/b52d4b8abf9720f7161697cc2e62823da3195d9b/var/spack/repos/builtin/packages/hdf5/package.py#L610-L618

This causes anyone trying to build `hdf5+mpi~fortran` with an installation of MPI without fortran wrappers to crash. 

### Error message

```
sasyed@MAC-140753 ~> spack install hdf5@1.12.1+mpi+hl~fortran ^mpich@4.1~fortran
...
==> Installing hdf5-1.12.1-tj3u7vhy7yyct563jfygmkdcdjr76kk6
==> No binary for hdf5-1.12.1-tj3u7vhy7yyct563jfygmkdcdjr76kk6 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/79/79c66ff67e666665369396e9c90b32e238e501f345afd2234186bfb8331081ca.tar.gz
==> Applied patch /Users/sasyed/Documents/packages/spack/var/spack/repos/builtin/packages/hdf5/fortran-kinds-2.patch
==> Ran patch() for hdf5
==> hdf5: Executing phase: 'cmake'
==> Error: AttributeError: 'Spec' object has no attribute 'mpifc'

The 'hdf5' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/Users/sasyed/Documents/packages/spack/var/spack/repos/builtin/packages/hdf5/package.py:615, in cmake_args:
        612                [
        613                    "-DMPI_CXX_COMPILER:PATH=%s" % spec["mpi"].mpicxx,
        614                    "-DMPI_C_COMPILER:PATH=%s" % spec["mpi"].mpicc,
  >>    615                    "-DMPI_Fortran_COMPILER:PATH=%s" % spec["mpi"].mpifc,
        616                ]
        617            )
        618

See build log for details:
...
```

### Information on your system

```
sasyed@MAC-140753 ~> spack debug report
* **Spack:** 0.20.0.dev0 (7fe2039b0144ff38850f1a34069bd61bec4db74b)
* **Python:** 3.10.8
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo
sasyed@MAC-140753 ~> 
```

### Additional information

For the HDF5 maintainers (@brtnfld @byrnHDF  @gheber  @hyoklee  @lkurz  @lrknox): Should the CMake argument `DMPI_Fortran_COMPILER` be set only when the `fortran` variant is enabled or is it always required even when one does not build the `fortran` wrappers?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by s-sajid-ali**
Fixes https://github.com/spack/spack/issues/35377

### CODE REVIEW

**Review by byrnHDF — DISMISSED** [review]

**Review by hyoklee — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Review by lrknox — DISMISSED** [review]

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by hyoklee** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
Pipeline errors seem to be related to WRF checksums that should have been fixed by #35401.

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
The latest pipeline still has `wrf` errors and an unrelated `pfunit` error.

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
@tldahlgren : Rebasing onto `develop` fixed the `wrf` errors, but now there are new errors pertaining to `meson/py-docutils/parmets/vtk-m/...`. While there are some build errors labelled as `hdf5` build errors, the logs show that the errors occurred when building `cmake` ([log](https://gitlab.spack.io/spack/spack/-/jobs/5600032)).

**Comment by tldahlgren** [comment]
We're having problems with the pipeline builds.  Hopefully this gets resolved soon as the `ci/gitlab-ci` checks are required.

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by lrknox** [comment]
> We're having problems with the pipeline builds. Hopefully this gets resolved soon as the `ci/gitlab-ci` checks are required.

I saw this warning and error in an HDF5-1.14.0 build for 

> We're having problems with the pipeline builds. Hopefully this gets resolved soon as the `ci/gitlab-ci` checks are required.

I saw this warning and error in an HDF5 1.14.0 build for radius-aws-aarch64-build:
==> Warning: 'target=graviton2' is deprecated, use 'target=neoverse_n1' instead
==> Error: Unable to copy files (/tmp/root/spack-stage/spack-stage-hdf5-1.14.0-753ppmfvdqa6dcskvcahonprbmjp3ytj/spack-build-out.txt) to artifacts /builds/spack/spack/jobs_scratch_dir/logs due to exception: No such file or directory: '/tmp/root/spack-stage/spack-stage-hdf5-1.14.0-753ppmfvdqa6dcskvcahonprbmjp3ytj/spack-build-out.txt'

The warning message seems to appear in many of the failing builds in the pipeline.  I also noticed in some recent builds on one of our local machines that spack install --keep-stage doesn't seem to be putting anything in the stage directory lately.  I don't know what should be doen to change from graviton2 to neovers_n1, though.

**Comment by s-sajid-ali** [comment]
The issue with that particular CI run seems to be a build error for `cmake` : https://gitlab.spack.io/spack/spack/-/jobs/5732974#L220.

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Review by hyoklee — DISMISSED** [review]

**Review by brtnfld — DISMISSED** [review]
LGTM

**Review by tldahlgren — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
CI should pass, ping me if it doesn't

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
The only CI failure is due to a timeout for `e4s-power-pr-build`.

**Comment by kwryankrattiger** [comment]
I think the fix to that is to add paraview and visit to the "huge" group for the e4s stack @eugeneswalker. Some of those failures are due to this being scheduled to small-medium runners.

You can likely fix this issue by adding `visit` and `paraview to huge mapping in `share/spack/gitlab/cloud_pipelines/stacks/e4s-power/spack.yaml` but I would rather just force merge this and fix that in another PR (#35787).

@tgamblin can you merge this?

**Review by eugeneswalker — DISMISSED** [review]

**Review by alalazo — APPROVED** [review]

**Review by hyoklee — APPROVED** [review]

**Review by eugeneswalker — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Comment by s-sajid-ali** [comment]
Can this be merged now @alalazo / @eugeneswalker ?

**Comment by alalazo** [comment]
@s-sajid-ali I think this PR is just waiting for CI to finish successfully. Then it'll be auto-merged.

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@s-sajid-ali Just so you know: by restarting an ongoing CI, you probably gained a longer waiting time :grimacing: (every pipeline that wasn't finished restarted the same builds from scratch).

**Comment by s-sajid-ali** [comment]
@alalazo Thanks for the information. 

The new CI pipeline has errors for `ml-linux-x86_64-cpu-pr-build/ml-linux-x86_64-cuda-pr-build
`, for `py-tensorflow` which seems unrelated to this PR. Is this a known issue?

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
Current CI failures are (per [this run](https://gitlab.spack.io/spack/spack/-/pipelines/297409)):
- `e4s-power-pr-build`:
  - `h5bench/iygcoon 1.3 gcc@11.1.0 linux-ubuntu20.04-ppc64le E4S Power`
  Reason: 
  ```
    Created fresh repository.
    fatal: unable to access 'https://gitlab.spack.io/spack/spack.git/': Could not resolve host: gitlab.spack.io
    Uploading artifacts for failed job 00:02 
    Uploading artifacts...
    WARNING: jobs_scratch_dir/logs: no matching files   
    WARNING: jobs_scratch_dir/reproduction: no matching files 
    WARNING: jobs_scratch_dir/tests: no matching files 
    WARNING: jobs_scratch_dir/user_data: no matching files 
    ERROR: No files to upload                          
    Cleaning up project directory and file based variables 00:01
    ERROR: Job failed: exit code 1
  ```
  - `warpx/yi62tyc 23.03 gcc@11.1.0 linux-ubuntu20.04-ppc64le E4S Power`
  Reason:  Same as above
  - `dray/eg4gdf4 0.1.8 gcc@11.1.0 linux-ubuntu20.04-ppc64le E4S Power `
    Reason:  Same as above
    
 - `ml-linux-x86_64-cpu-pr-build`:
   -  `py-tensorflow/sbcleax 2.10.1 gcc@7.3.1 linux-amzn2-x86_64_v3 Machine Learning`
   Reason:
   ```
   # Configuration: 70d5859fdef852abbc7e778d3e97b9f1bece7a530d593fd25d634060c4c992fa
   # Execution platform: @local_execution_config_platform//:platform
   gcc: internal compiler error: Killed (program cc1plus)
   Please submit a full bug report,
   with preprocessed source if appropriate.
   See <http://bugzilla.redhat.com/bugzilla> for instructions.
   Target //tensorflow/tools/pip_package:build_pip_package failed to build
   INFO: Elapsed time: 2342.864s, Critical Path: 334.01s
   INFO: 9650 processes: 1140 internal, 8510 local.
   FAILED: Build did NOT complete successfully
   ```
 - `ml-linux-x86_64-cuda-pr-build`:
   - ` py-tensorflow/7rm7vw4 2.10.1 gcc@7.3.1 linux-amzn2-x86_64_v3 Machine Learning`
   Reason:
   ```
   # Configuration: d236e8123202fbb1dc3edda1c1dfc704400c275ba451bbe641d3e897f49f1c21
   # Execution platform: @local_execution_config_platform//:platform

    Server terminated abruptly (error code: 14, error message: 'Connection reset by peer', log file: '/tmp/spackq_v06wxb/b79c0385198eb909c6e134607174ccf8/server/jvm.out')

   ```
   
 The `py-tensorflow` builds are being repeated in the CI after the first set of failures.

**Comment by eugeneswalker** [comment]
The power failures were a node issue, it has been fixed now. Re-running pipeline and they will finish: @spackbot run pipeline

**Comment by s-sajid-ali** [comment]
Thanks @eugeneswalker ! 

The following failures with `py-tensorflow` remain ( from the [latest run](https://gitlab.spack.io//spack/spack/-/pipelines/297532)):
- `ml-linux-x86_64-cpu-pr-build`:
  - `py-tensorflow/sbcleax 2.10.1 gcc@7.3.1 linux-amzn2-x86_64_v3 Machine Learning`
      Reason:
      ```
      # Configuration: f8b41c6b368834d97a9badbd57c6bd2ce355775d99d313e59e55944349742ade
     # Execution platform: @local_execution_config_platform//:platform
     gcc: internal compiler error: Killed (program cc1plus) 
     Please submit a full bug report,
     with preprocessed source if appropriate.
     See <http://bugzilla.redhat.com/bugzilla> for instructions.
     Target //tensorflow/tools/pip_package:build_pip_package failed to build
     INFO: Elapsed time: 2220.264s, Critical Path: 707.33s
     INFO: 8251 processes: 1132 internal, 7119 local.
     FAILED: Build did NOT complete successfully
      ```

- `ml-linux-x86_64-cuda-pr-build`:
  - `py-tensorflow/7rm7vw4 2.10.1 gcc@7.3.1 linux-amzn2-x86_64_v3 Machine Learning` 
      Reason:
      ```
      # Configuration: 93b58564f565042f4c7209d19a3417f306b5df5b1d476b814880e5058b3e09e2
      # Execution platform: @local_execution_config_platform//:platform
     gcc: internal compiler error: Killed (program cc1plus)
     Please submit a full bug report,
     with preprocessed source if appropriate.
     See <http://bugzilla.redhat.com/bugzilla> for instructions.
     Target //tensorflow/tools/pip_package:build_pip_package failed to build
     INFO: Elapsed time: 4797.839s, Critical Path: 771.12s
     INFO: 29045 processes: 9590 internal, 19455 local.
     FAILED: Build did NOT complete successfully
      ```

Pinging `py-tensorflow` maintainers regarding the CI failures: @adamjstewart / @aweits / @pradyunsg

**Comment by kwryankrattiger** [comment]
These should be fixed with #35996

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Comment by s-sajid-ali** [comment]
@spackbot run pipeline

**Pull request merged**
