### PR TITLE
Help cscope find ncursesw library

### LINKED ISSUE #3783: cscope build errors on Centos 7
cscope fails to build on Centos 7. The configure script output says it can't find curses. As a shot-in-the-dark I tried adding ```depends_on('ncurses')``` and get the same result

``` bash
$ spack install -j1 cscope
==> Installing cscope
==> ncurses is already installed in spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/ncurses-6.0-75hnzrecoib5eqdvfchl6n2jgcxc6dgo
==> Using cached archive: spack/var/spack/cache/cscope/cscope-15.8b.tar.gz
==> Staging archive: spack/var/spack/stage/cscope-15.8b-prz66vexnihyvq54as3ry3f6fucox2rk/cscope-15.8b.tar.gz
==> Created stage in spack/var/spack/stage/cscope-15.8b-prz66vexnihyvq54as3ry3f6fucox2rk
==> Ran patch() for cscope
==> Building cscope [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 2:
    'make'
spack/lib/spack/spack/build_systems/autotools.py:273, in build:
     268      def build(self, spec, prefix):
     269          """Makes the build targets specified by
     270          :py:attr:``~.AutotoolsPackage.build_targets``
     271          """
     272          with working_dir(self.build_directory):
  >> 273              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /tmp/spack-stage/spack-stage-RqIblB/cscope-15.8b/spack-build.out
```

From spack-build.out
``` bash
spack/lib/spack/env/gcc/gcc  -g -O2   -o cscope fscanner.o egrep.o alloc.o basename.o build.o command.o compath.o crossref.o dir.o display.o edit.o exec.o find.o help.o history.o input.o invlib.o logdir.o lookup.o main.o mouse.o mygetenv.o mypopen.o vpaccess.o vpfopen.o vpinit.o vpopen.o -lcurses
/bin/ld: cannot find -lcurses
collect2: error: ld returned 1 exit status
make[2]: *** [cscope] Error 1
make[2]: Leaving directory `/tmp/spack-stage/spack-stage-RqIblB/cscope-15.8b/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/spack-stage/spack-stage-RqIblB/cscope-15.8b'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by adamjstewart**
@sknigh Can you see if this fixes #3783?

### CODE REVIEW

**Comment by sknigh** [comment]
I still get an error 

``` bash
spack/lib/spack/env/gcc/gcc  -g -O2   -o cscope fscanner.o egrep.o alloc.o basename.o build.o command.o compath.o crossref.odir.o display.o edit.o exec.o find.o help.o history.o input.o invlib.o logdir.o lookup.o main.o mouse.o mygetenv.o mypopen.o vpaccess.o vpfopen.o vpinit.o vpopen.o -lncursesw -Lspack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/ncurses-6.0-75hnzrecoib5eqdvfchl6n2jgcxc6dgo/lib -lncurses   -lncursesw
/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
make[2]: *** [cscope] Error 1
make[2]: Leaving directory `/tmp/gitlab-runner/spack-stage/spack-stage-6E7S8n/cscope-15.8b/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/gitlab-runner/spack-stage/spack-stage-6E7S8n/cscope-15.8b'
make: *** [all] Error 2
```

I notice the configure args contain both -lncurses and -lncursesw

**Comment by adamjstewart** [comment]
Hmm, we may have to hack the `configure` script to not search for `-lncurses`. Or add a `wide` variant to `ncurses` to allow building of `libncurses.so` or `libncursesw.so`.

**Comment by adamjstewart** [comment]
Well that was significantly harder than it should have been. @sknigh Can you try again? I think I've got everything figured out now. It built for me on Fedora 25 where I don't have ncurses installed. It seems to only be linking to `ncursesw` this time:
```
$ ldd -r cscope 
	linux-vdso.so.1 (0x00007ffe66dfa000)
	libncursesw.so.6 => /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/ncurses-6.0-ybsic3iw357ybnc3wr6zpvfo2t25zzxk/lib/libncursesw.so.6 (0x00007f2996b3a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2996756000)
	/lib64/ld-linux-x86-64.so.2 (0x000055cf26eb8000)
```

**Comment by sknigh** [comment]
@adamjstewart That worked, thank you.

**Pull request merged**
