### PR TITLE
Add first version of real cdash logging

### PR DESCRIPTION
**Pull request by hegner**
I implemented some explicit CDash reporting as a new config option for --log-format.  Unfortunately I had to create 3 independent files for the configure, build, test steps. The actual content to upload is not entirely clear to me yet, thus a few TODO's scattered around the code still.

@alalazo @tgamblin - ping

### CODE REVIEW

**Comment by hegner** [comment]
Essential pieces done for now. There is one cdash bug I couldn't resolve yet - the upload order of the created xml files counts. the build one has to come first. There must be some implicit assumption in CDash I am violating/not aware of.

Depending on which direction you'd like to go I could factor the junit and cdash features out of install.py and put it into e.g. lib/spack/spack/dashboards.py

**Comment by hegner** [comment]
@tgamblin - what would be a good section in the docs for that feature?

**Comment by tgamblin** [comment]
@hegner: what if we add a new top-level section on testing?  I think there will end up being a lot of stuff in this section.

**Comment by hegner** [comment]
@tgamblin - sounds good. It may have quite an overlap with the contribution guide though.

**Comment by tgamblin** [comment]
@hegner: I was thinking about that.  I think the sections in the contribution guide on testing could be moved into a common testing section in the reference guide, then cross-referenced from where they are now.

@adamjstewart: what do you think?

**Comment by adamjstewart** [comment]
I don't know much about this, but it seems different than the Contribution Guide. The Contribution Guide is everything you need to know to contribute code to Spack. This seems like it's for release testing. I would be fine with that going under a new top-level section.

> Depending on which direction you'd like to go I could factor the junit and cdash features out of install.py and put it into e.g. lib/spack/spack/dashboards.py

Maybe that's something that would go under `lib/spack/spack/hooks`?

**Comment by hegner** [comment]
@adamjstewart - those look like build hooks, which serve a slightly different purpose.

**Comment by hegner** [comment]
@tgamblin - preliminary docs are there now. I'd be delighted if someone could give it an independent try on our cdash instance.

**Comment by hegner** [comment]
Refactored into place @adamjstewart suggested.

**Comment by tgamblin** [comment]
Hi all - we now have `cdash` set up at https://spack.io/cdash.  So we can start getting this set up.

@kielfriedt has a YAML test suite format set up, so once that is done we can start having sites run tests of their choosing, and submit results to CDash.

**Comment by davydden** [comment]
@hegner could you please resolve the merge conflict?

**Comment by tgamblin** [comment]
This is superseded by (and included in) #2917.

**Pull request closed without merging**
