### PR TITLE
Pipelines: Make signing key easier to use

### PR DESCRIPTION
**Pull request by scottwittenburg**
This PR removes the need to base64-encode the key(s) placed in the `SPACK_SIGNING_KEY` CI environment variable.  This has the affect that you can no longer "mask" the variable because it no longer meets the regular expression requirements for masked variables.

This PR also improves the pipelines documentation as it pertains to the use of the `SPACK_SIGNING_KEY` and `SPACK_GNUPGHOME` environment variables.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
FYI @eugeneswalker

**Comment by opadron** [comment]
Quick clarification question:

Would this change make base64-encoded signing keys optional, or unsupported, entirely?

I ask because we might still care about being able to mask it in the job output.

**Comment by scottwittenburg** [comment]
> Would this change make base64-encoded signing keys optional, or unsupported, entirely?

This change makes it unsupported entirely.  My thinking was that masking isn't really any kind of security, since I've verified I can write masked secrets to a file in the artifacts and post them to an arbitrary endpoint using `curl`, and be able to see them in the clear.  I think limiting secrets to protected branches is the only way to keep them secret.  

But I'm willing to consider keeping support for both if you or others think it could be important.

**Comment by opadron** [comment]
@scottwittenburg that's a good point.  I think it's fine to drop support and we can reconsider it in the future if the need to mask becomes more apparent. :+1:

**Review by opadron — APPROVED** [review]

**Comment by eugeneswalker** [comment]
> > Would this change make base64-encoded signing keys optional, or unsupported, entirely?
> 
> This change makes it unsupported entirely. My thinking was that masking isn't really any kind of security, since I've verified I can write masked secrets to a file in the artifacts and post them to an arbitrary endpoint using `curl`, and be able to see them in the clear. I think limiting secrets to protected branches is the only way to keep them secret.
> 
> But I'm willing to consider keeping support for both if you or others think it could be important.

LGTM!

**Comment by alalazo** [comment]
Is this PR outdated?

**Comment by scottwittenburg** [comment]
> Is this PR outdated?

Yes for sure.

**Pull request closed without merging**
