### PR TITLE
assimp: new version 5.2.3

### PR DESCRIPTION
**Pull request by wdconinc**
This version indeed includes the fix for which the PR 4203 patch range ends at 5.2.2. No other changes. This builds fine, and qt downstream builds fine too.

As for the remaining TODO introduced by #28623, I don't actually think this package should depend on boost, or at least not anymore. Maybe @davydden remembers why boost was included as a dependency early on. I can build all versions just fine without boost.

### CODE REVIEW

**Comment by wdconinc** [comment]
Confirmed that all versions of assimp in spack build fine without boost as dependency. In the .spack/spack-build-* files there is no mention of (case-insensitive) "boost", not even indicating a package not found message.

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
@davydden Did you want to comment on the removal of the `boost` dependencies in this PR?

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
I'm going to go ahead and approve this but will defer the merge until @davydden has a chance to respond.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
