### PR TITLE
gromacs: remove 'rdtscp' variant, deduce the flag from the target

### PR DESCRIPTION
**Pull request by alalazo**
refers #18858

### CODE REVIEW

**Comment by alalazo** [comment]
@marvinbernhardt

**Review by junghans — APPROVED** [review]

**Comment by marvinbernhardt** [comment]
I think this will not cover all edge cases. On a node with Intel(R) Xeon(R) L5420  @ 2.50GHz I get:
```
$ lscpu | grep rdtscp
```
```
$ ./spack arch
linux-fedora29-core2
```
And core2 is in the x86_64 family, correct?
However, given how old the hardware I am talking about it is, possibly no-one else cares.

**Comment by alalazo** [comment]
> And core2 is in the x86_64 family, correct?

You're correct. I was looking for references to understand when this instruction was introduced and could only find the following sentence [here](https://www.intel.it/content/www/it/it/architecture-and-technology/64-ia-32-architectures-software-developer-vol-2b-manual.html):
```
This instruction was introduced by the Pentium processor.
```
@marvinbernhardt EDIT: Double checking the reference I see I looked at `rdtsc`, not `rdtscp`. Are you aware of any authorative place where to get this information?

**Comment by marvinbernhardt** [comment]
Not really, sorry. From [this Stackoverflow post](https://stackoverflow.com/questions/37682939/what-is-the-gcc-cpu-type-that-includes-support-for-rdtscp) it seems it is not simple.

**Comment by ggouaillardet** [comment]
FWIW, `rdtscp` handling has been "fixed" in GROMACS 2020.4 (see https://gitlab.com/gromacs/gromacs/-/merge_requests/556).

Previously, gromacs failed on an ARM system if built with `-DGMX_RDTSCP=ON` (since ARM obviously does not support this x86 specific feature).
Since 2020.4, the `GMX_RDTSCP` macro is (basically) ignored on non x86 platform.

From a pragmatic point of view, the `rdtscp` variant could be reintroduced for GROMACS >= 2020.4, and hence give the option to manually disable it so GROMACS via spack can be used on x86 systems that do not support this feature.

Please let me know if you want me to issue a PR for that.

**Pull request merged**
