### PR TITLE
WarpX: 22.06

### PR DESCRIPTION
**Pull request by ax3l**
Update `warpx` & `py-warpx` to the latest release, `22.06`.

### CODE REVIEW

**Review by dpgrote — DISMISSED** [review]
Looks good to me!

**Comment by ax3l** [comment]
Added patch: https://github.com/ECP-WarpX/WarpX/pull/3162

**Review by tldahlgren — APPROVED** [review]
Confirmed new versions' sha256.

**Review by dpgrote — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
