### PR TITLE
gchp: add versions 13.1.0, 13.1.1, 13.1.2

### PR DESCRIPTION
**Pull request by lizziel**

### CODE REVIEW

**Review by WilliamDowns — APPROVED** [review]

**Review by WilliamDowns — DISMISSED** [review]

**Review by alalazo — DISMISSED** [review]

**Comment by WilliamDowns** [comment]
I guess Flake8 recently made some style changes? Those import statements have been there for awhile now with no issues.

**Comment by alalazo** [comment]
@WilliamDowns Can you rebase on the tip of develop?

**Comment by lizziel** [comment]
Hmm, strange. I'll do a rebase when I get back at work next week.

**Comment by alalazo** [comment]
> Hmm, strange. I'll do a rebase when I get back at work next week.

We had a few PRs recently that changed style, that's the reason a rebase is required :grimacing: Feel free to ping me as soon as you do it.

**Comment by lizziel** [comment]
Done. Sorry for the delay!

**Review by WilliamDowns — APPROVED** [review]

**Comment by lizziel** [comment]
@alalazo, pinging you in case you didn't see the update.

**Review by haampie — APPROVED** [review]

**Pull request merged**
