### PR TITLE
Modules: Fix configuration overriding

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**
This got broken some times ago but nobody noticed.

### CODE REVIEW

**Comment by RemiLacroix-IDRIS** [comment]
The unitttests are failing because commit e743726 from PR #18351 is required to have the same behavior as main Spack.

I can either push this commit to this PR or wait for the first PR to be merge before rebasing this one.

**Comment by alalazo** [comment]
@RemiLacroix-IDRIS Let's wait for #18315 to go in and then rebase this PR.

**Comment by RemiLacroix-IDRIS** [comment]
> @RemiLacroix-IDRIS Let's wait for #18351 to go in and then rebase this PR.

Done. The unittests passed as expected (except for the MacOS ones but for an unrelated reason).

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks!

**Comment by RemiLacroix-IDRIS** [comment]
You're welcome. :)

**Pull request merged**
