### PR TITLE
nwchem: add NO_NWPWXC_VDW3A as suggested by error message

### PR DESCRIPTION
**Pull request by alalazo**
Extracted from #45189 

Build failure: https://gitlab.spack.io/spack/spack/-/jobs/13978736

Any better way to deal with this error is welcome.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM  What do you think @jeffhammond ?

**Comment by jeffhammond** [comment]
I don't know why we need to disable this.  I suspect the Fedora people disable it because of https://github.com/nwchemgit/nwchem/pull/1054, which will be fixed shortly.  In the absence of some rationale for why this should be disabled, I don't think it should be done.

**Comment by alalazo** [comment]
Yes, it's the same underlying issue.

**Comment by haampie** [comment]
See #47892

**Pull request closed without merging**
