### PR TITLE
Python: add v3.8.13 and v3.7.13

### PR DESCRIPTION
**Pull request by adamjstewart**
Security bugfix releases

### CODE REVIEW

**Comment by adamjstewart** [comment]
@alalazo never seen this one before:
```
fatal: unsafe repository ('/__w/spack/spack' is owned by someone else)
```

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
That's an unfortunate fix for a CVE in `git`, see:
- https://github.blog/2022-04-12-git-security-vulnerability-announced/
- https://github.com/actions/checkout/issues/760
- http://changelogs.ubuntu.com/changelogs/pool/main/g/git/git_2.25.1-1ubuntu3.3/changelog

**Comment by alalazo** [comment]
Fix is https://github.com/spack/spack/pull/30559

**Review by alalazo — APPROVED** [review]

**Pull request merged**
