### PR TITLE
GNINA: add cuDNN variant and make RDKit optional

### PR DESCRIPTION
**Pull request by RMeli**
* Add `cudnn` variant
* Add `gninavis` variant
  * `rdkit` is only needed to build the `gninavis` executable

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
FWIW. I am unable to build the package due to an `openbabel` issue I noted at https://github.com/spack/spack/pull/34631#issuecomment-1478362959.

**Comment by tldahlgren** [comment]
Looks like the docs is having a python-related issue that has nothing to do with this PR:

```
python3.7 -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
/bin/bash: python3.7: command not found
```

**Comment by RMeli** [comment]
@tldahlgren, I replied in the other thread but for future reference someone else reported ~the same issue~ [an issue] when trying to build `gnina`: https://github.com/spack/spack/pull/34631#issuecomment-1478362959

**Comment by RMeli** [comment]
@tldahlgren I managed to reproduce the issue in https://github.com/gnina/gnina/pull/184#issuecomment-1476782086 locally on a new system, and it is related to https://github.com/rdkit/rdkit/issues/5089. I added a new version of RDKit to this PR, which solves the issue.

However, I was unable to reproduce the issue you encountered in https://github.com/spack/spack/pull/34631#issuecomment-1478362959. In my installation, Spack's version of SWIG is found correctly.

**Comment by tldahlgren** [comment]
Adding @bvanessen since this PR includes a new version in `rdkit`.

**Comment by tldahlgren** [comment]
I've tried a few things to resolve my issue but I don't think it should be a blocker for this PR.  If someone else has a problem they can report an issue.

**Review by tldahlgren — APPROVED** [review]
Confirmed the new `rdkit` sha256.  Rest LGTM.

**Comment by tldahlgren** [comment]
Deferring merge in case @bvanessen wants to comment.

**Comment by RMeli** [comment]
> I've tried a few things to resolve my issue but I don't think it should be a blocker for this PR. If someone else has a problem they can report an issue.

Thanks for your investigation @tldahlgren ! I had another person reporting successful compilation. I can try to convince a few other people to test this recipe, if needed?

**Comment by tldahlgren** [comment]
> > I've tried a few things to resolve my issue but I don't think it should be a blocker for this PR. If someone else has a problem they can report an issue.
> 
> Thanks for your investigation @tldahlgren ! I had another person reporting successful compilation. I can try to convince a few other people to test this recipe, if needed?

Only if you want.  Since this is only a version change for `RDKit` and there are people who have successfully installed the software, I'm debating how much longer to wait for @bvanessen.  We usually give maintainers about a week to respond.

**Comment by RMeli** [comment]
@tldahlgren I had a few other successful installations reported. Is there anything else holding this up?

**Comment by tldahlgren** [comment]
> @tldahlgren I had a few other successful installations reported. Is there anything else holding this up?

I was waiting for @bvanessen to comment on the `RDKit` changes but it has been over a week.

**Pull request merged**
