### PR TITLE
Update fpm to version 0.6.0

### PR DESCRIPTION
**Pull request by awvwgk**
Update for release at https://github.com/fortran-lang/fpm/releases/tag/v0.6.0

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by beddalumia** [comment]
Is this not included in the last release (of spack)?

My fresh install of spack apparently can only install fpm up to 0.5.0:

```
$ spack --version
0.18.1

$ spack info fpm
Package:   fpm

Description:
     Fortran Package Manager (fpm) is a package manager and build system for
    Fortran. Its key goal is to improve the user experience of Fortran
    programmers. It does so by making it easier to build your Fortran
    program or library, run the executables, tests, and examples, and
    distribute it as a dependency to other Fortran projects.

Homepage: https://github.com/fortran-lang/fpm

Preferred version:  
    0.5.0    https://github.com/fortran-lang/fpm/releases/download/v0.5.0/fpm-0.5.0.zip

Safe versions:  
    0.5.0    https://github.com/fortran-lang/fpm/releases/download/v0.5.0/fpm-0.5.0.zip
    0.4.0    https://github.com/fortran-lang/fpm/releases/download/v0.4.0/fpm-0.4.0.zip
    0.3.0    https://github.com/fortran-lang/fpm/releases/download/v0.3.0/fpm-0.3.0.zip

Deprecated versions:  
    None

Variants:
    Name [Default]    When    Allowed values    Description
    ==============    ====    ==============    ==========================

    openmp [on]       --      on, off           Use OpenMP parallelisation

Build Dependencies:
    curl  git

Link Dependencies:
    None

Run Dependencies:
    None

```

Do I need to activate some special "channel" to see what's on the develop branch (which is the default branch here, right?)?

**Comment by awvwgk** [comment]
You might be on a specific release of spack which doesn't include this fpm version yet or you are on develop but haven't pulled in the latest changes from this repository yet.

**Comment by beddalumia** [comment]
I am on the v0.18.1, that as far as I understand is the latest and has been released on Jul 20 2022

https://github.com/spack/spack/releases/tag/v0.18.1

I thought it would include this PR since it has been merged one month earlier.

**Comment by beddalumia** [comment]
I can confirm that cloning current master (or at least what was current master 15 minutes ago :D) fpm 0.6.0 is indeed available:

```
$ spack info fpm
Package:   fpm

Description:
     Fortran Package Manager (fpm) is a package manager and build system for
    Fortran. Its key goal is to improve the user experience of Fortran
    programmers. It does so by making it easier to build your Fortran
    program or library, run the executables, tests, and examples, and
    distribute it as a dependency to other Fortran projects.

Homepage: https://github.com/fortran-lang/fpm

Preferred version:  
    0.6.0    https://github.com/fortran-lang/fpm/releases/download/v0.6.0/fpm-0.6.0.zip

Safe versions:  
    0.6.0    https://github.com/fortran-lang/fpm/releases/download/v0.6.0/fpm-0.6.0.zip
    0.5.0    https://github.com/fortran-lang/fpm/releases/download/v0.5.0/fpm-0.5.0.zip
    0.4.0    https://github.com/fortran-lang/fpm/releases/download/v0.4.0/fpm-0.4.0.zip
    0.3.0    https://github.com/fortran-lang/fpm/releases/download/v0.3.0/fpm-0.3.0.zip

Deprecated versions:  
    None

Variants:
    Name [Default]    When    Allowed values    Description
    ==============    ====    ==============    ==========================

    openmp [on]       --      on, off           Use OpenMP parallelisation

Build Dependencies:
    curl  git

Link Dependencies:
    None

Run Dependencies:
    None

$ spack --version
0.19.0.dev0 (0fee3095e145bccddc047f4209d28a1033bff74d)
```

In the previous try I got spack from homebrew, which gives not the master but the latest release. I still think that somehow latest fpm is not included in the release (then of course you could argue that if I have access to homebrew I could get fpm from there already, but spack comes with the very nice commodity of easy managing multiple versions...).

**Pull request merged**
