### PR TITLE
Kokkos Kernels: adding release 3.7.1 and 4.0.0

### PR DESCRIPTION
**Pull request by lucbv**
Following PR #36532 updating the Kokkos Kernels package now.
Not too much going on here just adding new sha256 and versions

### CODE REVIEW

**Review by brian-kelley — APPROVED** [review]

**Review by eugeneswalker — DISMISSED** [review]

**Comment by jgfouca** [comment]
Looks like this build's Spack recipe is turning off cuda lambda support explicitly (the ~cuda_lambda):

```
kokkos@4.0.00%gcc@11.1.0~aggressive_vectorization~compiler_warnings+cuda~cuda_constexpr \
~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug \
~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation \
~hpx~hpx_async_dispatch~hwloc~ipo~memkind~numactl~openmp~openmptarget~pic+profiling \
~profiling_load_print~pthread~qthread~rocm+serial+shared~sycl~tests~tuning+wrapper \
build_system=cmake build_type=RelWithDebInfo cuda_arch=70
```

We don't support building without that anymore. Kokkos turns it on by default in 4.0, but the [package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/kokkos/package.py) for Kokkos still defaults it to off.

**Comment by eugeneswalker** [comment]
> Looks like this build's Spack recipe is turning off cuda lambda support explicitly (the ~cuda_lambda):

I think we need to make these changes to the E4S and E4S-Power CI stack:
```
diff --git a/share/spack/gitlab/cloud_pipelines/stacks/e4s-power/spack.yaml b/share/spack/gitlab/cloud_pipelines/stacks/e4s-power/spack.yaml
index a575d82a60..1935afb756 100644
--- a/share/spack/gitlab/cloud_pipelines/stacks/e4s-power/spack.yaml
+++ b/share/spack/gitlab/cloud_pipelines/stacks/e4s-power/spack.yaml
@@ -160,8 +160,8 @@ spack:
   - hpctoolkit +cuda
   - hpx max_cpu_count=512 +cuda
   - hypre +cuda
-  - kokkos +wrapper +cuda
-  - kokkos-kernels +cuda ^kokkos +wrapper +cuda
+  - kokkos +wrapper +cuda_lambda +cuda
+  - kokkos-kernels +cuda ^kokkos +wrapper +cuda_lambda +cuda
   - magma +cuda
   - mfem +cuda
   - mgard +serial +openmp +timing +unstructured +cuda


diff --git a/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml b/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml
index 8bca38b472..db2da1babd 100644
--- a/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml
+++ b/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml
@@ -171,8 +171,8 @@ spack:
   - hpctoolkit +cuda
   - hpx max_cpu_count=512 +cuda
   - hypre +cuda
-  - kokkos +wrapper +cuda
-  - kokkos-kernels +cuda ^kokkos +wrapper +cuda
+  - kokkos +wrapper +cuda_lambda +cuda
+  - kokkos-kernels +cuda ^kokkos +wrapper +cuda_lambda +cuda
   - magma +cuda
   - mfem +cuda
   - mgard +serial +openmp +timing +unstructured +cuda
```

Do you want to push these changes here?

**Comment by brian-kelley** [comment]
@eugeneswalker I'm talking with @lucbv and we're going to try to fix this in the Kokkos and KokkosKernels package definitions. That would fix the issue without having to change the CI recipes.

**Comment by eugeneswalker** [comment]
> @eugeneswalker I'm talking with @lucbv and we're going to try to fix this in the Kokkos and KokkosKernels package definitions. That would fix the issue without having to change the CI recipes.

How extensive are the required changes? We would like to include `kokkos-kernels` built for `cuda_arch=90` in our May release of E4S.

**Comment by brian-kelley** [comment]
@lucbv @eugeneswalker #38565 fixes the default enabling of +cuda_lambda in kokkos, and #38568 makes kokkos-kernels depend on +cuda_lambda on version 4+ with cuda enabled. So either of these would fix the error in the E4S CI, because now building kokkos-kernels will automatically turn on cuda_lambda when it's needed.

**Comment by eugeneswalker** [comment]
Just pushed a commit here that should resole the only outstanding CI errors. Hope to merge this ASAP.

**Review by brian-kelley — APPROVED** [review]

**Review by eugeneswalker — APPROVED** [review]

**Comment by lucbv** [comment]
@eugeneswalker thanks for the update, this should make it smoother for the next releases

**Pull request merged**
