### PR TITLE
Spack version: 0.16.1 -> 0.16.2

### PR DESCRIPTION
**Pull request by adamjstewart**
Do we have a document somewhere that describes the process of how to release a new version of Spack? Something like https://github.com/adamjstewart/fiscalyear/wiki/Releasing-Instructions? If we do, we should add bumping the Spack version to that document.

### CODE REVIEW

**Comment by alalazo** [comment]
We have [this](https://spack.readthedocs.io/en/latest/developer_guide.html#releases) thorough guide to release major and minor versions.

**Comment by adamjstewart** [comment]
Ah, so it's already documented, it just isn't being done 😆

**Comment by tgamblin** [comment]
looks like I forgot to do the last merge.  I'll do it -- let's close this PR when I do.

**Comment by tgamblin** [comment]
Actually no I did do it -- it just looks like the version bump didn't happen.  That may be because I do `-X theirs` when merging these.  It would be nice to automate that step better.

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
FWIW, `spack -V` was still reporting the right number of commits since v0.16.2, it just said it was v0.16.1 b/c of this.

**Comment by adamjstewart** [comment]
`spack -V` only reports the right version if your tags are up-to-date. If you don't run `git fetch --tags upstream` after every release, this version is incorrect. Also, if you install Spack from tarball instead of with git, the version here is used. Also, this version is used in the docs (which is how I discovered it).

**Comment by tgamblin** [comment]
if you do a fresh clone or a pull, you get tags right?

**Comment by adamjstewart** [comment]
I believe so.

**Pull request merged**
