### PR TITLE
Add static and pic options to gettext

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds static and pic options to gettext. These changes support NOAA/National Weather Service R&D and operational forecasting applications.

### CODE REVIEW

**Review by michaelkuhn — CHANGES_REQUESTED** [review]
`+shared~pic` fails, so we should probably add a conflict/requires for that.

**Comment by AlexanderRichert-NOAA** [comment]
@michaelkuhn fixed

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
FYI. Have not checked if this is the reason for the `KeyError: shared` failure I mention at https://github.com/spack/spack/pull/40454#issuecomment-1758238262, but it appears that installing a package with `gettext` as a dependency where it needs to be built fails BUT if I install `gettext` then the package that depends on it the build of the dependent package succeeds.

**Comment by bernhardkaindl** [comment]
@michaelkuhn Building packages with `spack` after a `git pull` when `gettext` was already installed using `spack` before this PR was merged, (which Tamara and I experienced) is fixed with #39423.

**Pull request merged**
