### PR TITLE
Remove Fedora 37 and 38, Ubuntu 18 from CI in v0.22

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by wdconinc** [comment]
Do we want to remove these from https://github.com/alalazo/spack/blob/deprecation/container-images/lib/spack/spack/container/images.json as well? If we are not testing builds, are we still willing to guarantee that containerize works?

**Comment by alalazo** [comment]
They won't be in the documentation, so I guess we're not supporting them, but the Dockerfile that gets generated might be a good starting point if they are not working? Also, as long as we guarantee that Spack works with Python 3.6 I don't see why they should effectively break...

**Comment by wdconinc** [comment]
I guess the failure scenario I'm imagining is someone running `spack containerize --list-os`, seeing `fedora:38` (since parsed from images.json), and using that to start their container build from. `FROM spack/fedore38 as builder` will still work, but it won't be an updated image anymore.

**Comment by alalazo** [comment]
@wdconinc Fair, removed the three images in the last commit.

**Review by wdconinc — APPROVED** [review]

**Comment by alalazo** [comment]
@wdconinc I'll force merge, since we are on a kind of tight cycle to branch the release :slightly_smiling_face: The PR shouldn't affect Gitlab anyhow.

**Pull request merged**
