### PR TITLE
PAPI: updating git URL

### PR DESCRIPTION
**Pull request by usivakum**
PAPI has moved its git location to https://github.com/icl-utk-edu/papi.git

### CODE REVIEW

**Comment by mwkrentel** [comment]
@usivakum  Did you try building `papi@master` ?

The `git` location is only used for `master`, the tar files for the
releases come from somewhere else.  I think you'll find that
`papi@master` won't build unless you also add the following lines to
the depends.

```
    depends_on("autoconf", type="build", when="@master build_system=autotools")
    depends_on("automake", type="build", when="@master build_system=autotools")
    depends_on("libtool", type="build", when="@master build_system=autotools")
```

Also, could you look at #33940 ?
I'm not sure what they're hung up on, but could you see if papi 7.0.0
or 7.0.1 now builds cleanly?  If it does, then add it, if not, don't
feel obligated to fix it.

Thanks!

**Comment by usivakum** [comment]
@mwkrentel I did notice that papi@master complains about the dependency on autoconf, automake, and libtool. However, once I updated the git repository link, it does not seem to complain about it. Not sure if this is due to the old git link. 

I also got to successfully building papi@7.0.1, so I'd be happy to include that too in this PR!

**Comment by mwkrentel** [comment]
Ah yes, sorry about that.

I had tried building `papi@master` and ran into the autotools message,
"fixed" that and then saw the redirection URL and fixed that, not
realizing that the first message is not needed.

I guess the failure in #33940 is from `+cuda` and `+rocm`.
Blech.

**Comment by naromero77** [comment]
could @G-Ragghianti please review?

**Review by G-Ragghianti — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
