### PR TITLE
[WIP] Speed up with targeted memoization

### PR DESCRIPTION
**Pull request by citibeth**
I added a few memoizations to avoid re-doing work again and again.  Not that this is how things should be in the end... but it DOES speed me up from 30 seconds to 15 for a simple "spack spec" command.

On my run...

It's true, virtual dependencies are taking a lot of time.  _expand_virtual_packages() is only called 3 times.  But then ProviderIndex() is instantiated 738 (!) times.  Overall, 6838 specs are created --- FAR MORE than there are specs in the entire repo!

I suspect that speedup will happen through some more targeted re-use of objects.  Among other things, it looks like the same Spec is being instantiated multiple times.  And we shouldn't have to instantiate ProviderIndex 738 times.

In the meantime, I've shaved down the pain for myself somewhat.

### CODE REVIEW

**Comment by citibeth** [comment]
Here is the profile I'm talking about above.
[profile.txt](https://github.com/LLNL/spack/files/258450/profile.txt)

**Comment by tgamblin** [comment]
@citibeth: I'm a little worried about the correctness of this -- the concretization tests are failing in the Travis output above.

**Comment by citibeth** [comment]
See what that does to it... I noticed the bug as soon as I started using
Spack and things stopped working.  Haven't noticed problems since.

Frankly, I doubt that this PR should be merge.  It's more of a starting
point to think about how to speed up Spack by avoiding re-computation of
the same thing.

**Comment by citibeth** [comment]
@tgamblin, has this Travis check gotten stuck?

**Comment by tgamblin** [comment]
I kicked it off again

**Comment by citibeth** [comment]
I found another bug, and reverted this entire PR in my own rpo.  This PR needs to die.

**Pull request closed without merging**
