### PR TITLE
orca: new version 5.0.3

### PR DESCRIPTION
**Pull request by snehring**
They changed from zstd to xz for the archives, so that simplifies the install process a bit for newer versions. Strictly speaking the openmpi version specified in the release is 4.1.1, but I was having build issues with openmpi@4.1.1 with +pmi from slurm. It'd probably work with anything in 4.1 though. Some of the binaries link against a few libraries included in the bundle, hence the environment modification.

### CODE REVIEW

**Comment by RemiLacroix-IDRIS** [comment]
@snehring : Just double checking, they put the libraries in the `bin` subdir?

**Comment by snehring** [comment]
@RemiLacroix-IDRIS In the distributed archive they're in the root with everything else, but given we install everything in prefix.bin they end up there.

**Comment by RemiLacroix-IDRIS** [comment]
@snehring Ok, got it!

**Comment by RemiLacroix-IDRIS** [comment]
> I was having build issues with openmpi@4.1.1 with +pmi from slurm

I'm able to compil OpenMPI 4.1.1 with +pmi and schedulers=slurm. Not sure if you should try to get this fixed and use 4.1.1 or if it useless as 4.1.2 will indeed probably work anyway... I leave that to @tldahlgren.

**Comment by snehring** [comment]
Does it still work if you do fabrics=ofi? The actual issue seems to be in common_ofi.c with pmix.

**Comment by RemiLacroix-IDRIS** [comment]
> Does it still work if you do fabrics=ofi? The actual issue seems to be in common_ofi.c with pmix.

Hmm, I'm able to build with OFI (but it's not what I usually use).

**Comment by snehring** [comment]
Specifically the spec that fails for me is `openmpi@4.1.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java+legacylaunchers~lustre~memchecker+pmi+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=ofi schedulers=slurm`.

**Comment by RemiLacroix-IDRIS** [comment]
I don't have the latest version of Spack installed so I don't have the `build_system` variant but apart from that it is basically what I used (with GCC 8.4.1 in my case).

**Review by alalazo — APPROVED** [review]

**Pull request merged**
