### PR TITLE
Bump Arbor package to v0.5.2

### PR DESCRIPTION
**Pull request by brenthuisman**
Plus some minor other updates (website, maintainers, dependencies, compiler check).

### CODE REVIEW

**Review by haampie — DISMISSED** [review]

**Comment by haampie** [comment]
Can you fix:
```
var/spack/repos/builtin/packages/arbor/package.py:76: [E501] line too long (108 > 88 characters)
var/spack/repos/builtin/packages/arbor/package.py:77: [E226] missing whitespace around arithmetic operator
```

**Comment by brenthuisman** [comment]
Flake8 is now passing. My bad!

**Comment by brenthuisman** [comment]
What is the status of this PR? I see a check failed, but I think it's not related to Arbor. If it is, please let me know what I can do to get this update up.

**Comment by haampie** [comment]
The PR was created when gitlab ci was flaky, I've rebased it for you

**Review by haampie — APPROVED** [review]

**Pull request merged**
