### PR TITLE
fortrilinos: release 2.3.0 compatible with trilinos@14

### PR DESCRIPTION
**Pull request by sethrj**
This version is fully compatible with Trilinos 14.0, and at least partly compatible with 14.4.

### CODE REVIEW

**Comment by eugeneswalker** [comment]
`fortrilinos@2.3.0` build is failing in all E4S CI stacks:

For example here is the OneAPI build failure:
* [fortrilinos/yau5bkq 2.3.0 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8001577)
```
==> Installing fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu [1/1]
==> Fetching https://github.com/trilinos/ForTrilinos/releases/download/v2.3.0/ForTrilinos-2.3.0.tar.gz
==> No patches needed for fortrilinos
==> fortrilinos: Executing phase: 'cmake'
...
In file included from /tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-src/src/fortpetra/generated/fortpetraFORTRAN_wrap.cxx:357:
/tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-src/src/fortpetra/ForTrilinos_DefaultNodeType.hpp:4:10: fatal error: 'KokkosCompat_DefaultNode.hpp' file not found
#include <KokkosCompat_DefaultNode.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/fortpetra.dir/build.make:92: src/CMakeFiles/fortpetra.dir/fortpetra/generated/fortpetraFORTRAN_wrap.cxx.o] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-build-yau5bkq'
make[1]: *** [CMakeFiles/Makefile2:162: src/CMakeFiles/fortpetra.dir/all] Error 2
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-build-yau5bkq'
make: *** [Makefile:139: all] Error 2
==> Error: ProcessError: Command exited with status 2:
...
...
 >> 101    /tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2
            z7f5ghaxpsttmayeu/spack-src/src/fortpetra/ForTrilinos_DefaultNodeTy
            pe.hpp:4:10: fatal error: 'KokkosCompat_DefaultNode.hpp' file not f
            ound
     102    #include <KokkosCompat_DefaultNode.hpp>
     103             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     104    1 error generated.
  >> 105    make[2]: *** [src/CMakeFiles/fortpetra.dir/build.make:92: src/CMake
            Files/fortpetra.dir/fortpetra/generated/fortpetraFORTRAN_wrap.cxx.o
            ] Error 1
     106    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-fortr
            ilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-build-yau5bkq'
  >> 107    make[1]: *** [CMakeFiles/Makefile2:162: src/CMakeFiles/fortpetra.di
            r/all] Error 2
     108    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-fortr
            ilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-build-yau5bkq'
  >> 109    make: *** [Makefile:139: all] Error 2
See build log for details:
  /tmp/root/spack-stage/spack-stage-fortrilinos-2.3.0-yau5bkqpn7pwqe2z7f5ghaxpsttmayeu/spack-build-out.txt
```

**Comment by sethrj** [comment]
Thanks @eugeneswalker , I don't know how I didn't notice that next breaking change in trilinos@14.4 . I've updated the spec accordingly and may take a shot at releasing a fortrilinos compatible with 14.4.  Though this may be the last fortrilinos release...

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Should we merge now or wait for @aprokop to review?

**Comment by sethrj** [comment]
It's good to merge. Andrey approved the original fortrilinos PR and I'm the primary maintainer  of this package.

**Review by aprokop — APPROVED** [review]
Looks fine to me.

**Pull request merged**
