### PR TITLE
julia: 1.6.6

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by glennpj** [comment]
This does not build for me.
```console
$ spack install julia @1.6.6
...
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

2 errors found in build log:
     1074     [3] run
     1075       @ ./process.jl:451 [inlined]
     1076     [4] (::Main.anonymous.var"#1#5"{Set{String}, String})(prec_path::String)
     1077       @ Main.anonymous /tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/contrib/gener
             ate_precompile.jl:218
     1078    in expression starting at /tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/contrib
             /generate_precompile.jl:3
     1079    *** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
  >> 1080    make[1]: *** [/tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/usr/lib/julia/sys-o
             .a] Error 1
     1081    make[1]: Leaving directory `/tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src'
  >> 1082    make: *** [julia-sysimg-release] Error 2
```
That is with gcc-12, target=x86_64

**Comment by tldahlgren** [comment]
> This does not build for me.
> 
> ```
> $ spack install julia @1.6.6
> ...
> ==> Error: ProcessError: Command exited with status 2:
>     'make' '-j16'
> 
> 2 errors found in build log:
>      1074     [3] run
>      1075       @ ./process.jl:451 [inlined]
>      1076     [4] (::Main.anonymous.var"#1#5"{Set{String}, String})(prec_path::String)
>      1077       @ Main.anonymous /tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/contrib/gener
>              ate_precompile.jl:218
>      1078    in expression starting at /tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/contrib
>              /generate_precompile.jl:3
>      1079    *** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
>   >> 1080    make[1]: *** [/tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src/usr/lib/julia/sys-o
>              .a] Error 1
>      1081    make[1]: Leaving directory `/tmp/gpjohnsn/spack-stage/spack-stage-julia-1.6.6-ouynpcg3djg5onzq235k3fiykcwliwn5/spack-src'
>   >> 1082    make: *** [julia-sysimg-release] Error 2
> ```
> 
> That is with gcc-12, target=x86_64

Apologies for jumping the gun.  Do you want this PR reverted or, perhaps, the submitter can post a new PR?

**Comment by glennpj** [comment]
@tldahlgren No worries. This is an "older" version so probably not that critical in the short term. I will let @haampie decide how to handle it. It is also possible this is something unique to my spack tree.

**Comment by haampie** [comment]
Hm, it builds fine for me. I didn't use GCC12. Your build log is not showing the error though

**Comment by glennpj** [comment]
It did not build with gcc-11 either.

**Comment by glennpj** [comment]
I can build it fine with GCC-10 so there seems to be a problem with newer GCC versions. I guess that is for another PR.

**Pull request merged**
