### PR TITLE
sqlite: add 3.39.4

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Review by tldahlgren — APPROVED** [review]
Re-confirmed sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Pull request merged**
