### PR TITLE
lua package: added -nostartfiles to arguments

### PR DESCRIPTION
**Pull request by francinelapid**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@trws is currently overhauling our Lua support in #28854, we'll probably want to merge that first and rebase this after.

**Comment by alalazo** [comment]
#28854 has been merged

**Comment by trws** [comment]
As long as everything builds after this is applied, it's probably fine, but why do you want this @francinelapid?  Is linking to default system libraries causing an issue for you?

**Comment by francinelapid** [comment]
We’re going to try building it without the flag and see what happens. I’ll mark this pull request as a draft for now.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
