### PR TITLE
Packages/py jupyterlab

### PR DESCRIPTION
**Pull request by ghost**
New package:jupyterlab

### CODE REVIEW

**Comment by ghost** [comment]
py-jupyterlab depends on py-jupyterlab-server and py-json5.
Pull request of py-jupyterlab-server and py-json5 are not merged yet.

Pull request of py-jupyterlab-server and py-json5 are as follows.

py-jupyterlab-server : https://github.com/spack/spack/pull/16164
py-json5 : https://github.com/spack/spack/pull/16163

**Comment by adamjstewart** [comment]
It's better to have a single package per PR, makes things easier to review.

**Comment by ghost** [comment]
The cause of the error is that py-pytest-check-links does not exist.
py-jupyterlab depends on py-pytest-check-links.
Therefore,I add package.py of py-pytest-check-link.

**Comment by adamjstewart** [comment]
The way I recommend doing things is to open a single PR for each package, then once the dependencies are merged, you can rebase the PR that depends on them. Alternatively, you can only open PRs for the packages that aren't missing dependencies, and wait until they are merged before opening additional PRs.

**Comment by ghost** [comment]
Thank you for your comment.

I will wait the dependencies (py-json5 : #16163, py-jupyterlab-server : #16164) are merged, then I will rebase this PR.
Please check #16163 and #16164 before this PR.

Please let me ask one more question.
I added package.py of py-pytest-check-links on this PR.
Should I delete package.py of py-pytest-check-links from this PR and add it on new PR ?

**Comment by adamjstewart** [comment]
Those other PRs have 2 and 3 packages modified, can you make PRs with only 1 package per PR?

**Comment by ghost** [comment]
Once close this PR to resolve dependencies.

**Pull request closed without merging**
