### PR TITLE
py-pyliblzma: remove python2 package

### PR DESCRIPTION
**Pull request by wdconinc**
Last release 13 years ago, before python 3.2 was released. No dependents or next of kin could be located. Originally added by @Sinan81.

My motivation is going through and verifying whether all dependents of `lzma` can simply be upgraded to use `xz`, since `lzma` has now been unmaintained for 15 years and is replaced by `xz`...

### CODE REVIEW

**Comment by wdconinc** [comment]
The `setup.py` has a for loop over an xrange.

**Comment by wdconinc** [comment]
https://bazaar.launchpad.net/~proyvind/pyliblzma/trunk/files/485 for reference, that's the revision at which point 0.5.3 was released.

**Comment by Sinan81** [comment]
yes, let's remove it.

**Review by Sinan81 — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]
Normally we deprecate first before removing but it's impossible to build this package and has been since we dropped Python 2 so I'm fine with just deleting.

**Pull request merged**
