### PR TITLE
Add rccl variant to cosma

### PR DESCRIPTION
**Pull request by mtaillefumier**
minor changes in the cosma ~and cp2k~ recipe to build cosma with rccl ~and nccl~ supports. Can also be achieved with the ^cosma+r(n)ccl.

### CODE REVIEW

**Comment by mtaillefumier** [comment]
question is it better to explicitly do 

`spack install cp2k+cosma+nccl ....` 

or 

`spack install cp2k+cosma ^cosma+nccl`

**Comment by gsitaram** [comment]
> question is it better to explicitly do
> 
> `spack install cp2k+cosma+nccl ....`
> 
> or
> 
> `spack install cp2k+cosma ^cosma+nccl`

The latter fits better.

**Comment by simonpintarelli** [comment]
I also tend to the latter and avoid forwarding +nccl/rccl to cp2k.

Otherwise `cp2k+cosma+nccl` and `cp2k+cosma ^cosma+nccl` would be the same configuration, but a different spec for spack.

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by mtaillefumier** [comment]
renamed the PR as I do not touch cp2k recipe

**Review by tldahlgren — APPROVED** [review]
Looks like the only change for THIS PR is the `rccl` variant. LGTM.

**Pull request merged**
