### PR TITLE
Bugfix: Kokkos stand alone test

### LINKED ISSUE #27976: spack test run kokkos fails (possible compiler version needs pinning)
```bash
 spack test run kokkos
==> Spack test gqrsnwuo3spdzujvssfpekm4lrazskgn
==> Testing package kokkos-3.4.01-l4tyn6y
==> Error: ProcessError: Command exited with status 1:
    'cmake' '/home/vanessa/Desktop/Code/spack-vsoch/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/kokkos-3.4.01-l4tyn6ymtuyz5v6wu7pvuftveykpw725/.spack/test/scripts/spack_test/out' '-DEXECUTABLE_OUTPUT_PATH=/home/vanessa/Desktop/Code/spack-vsoch/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/kokkos-3.4.01-l4tyn6ymtuyz5v6wu7pvuftveykpw725/.spack/test/scripts/spack_test/out'

4 errors found in test log:
     7     -- Detecting CXX compiler ABI info
     8     -- Detecting CXX compiler ABI info - done
     9     -- Detecting CXX compile features
     10    -- Detecting CXX compile features - done
     11    -- Enabled Kokkos devices: SERIAL
     12    -- Configuring done
  >> 13    CMake Error at CMakeLists.txt:18 (target_link_libraries):
     14      Error evaluating generator expression:
     15    
     16        $<LINK_LANGUAGE:CXX>
     17    
     18      Expression did not evaluate to a known generator expression
     19    
     20    
  >> 21    CMake Error at CMakeLists.txt:18 (target_link_libraries):
     22      Error evaluating generator expression:
     23    
     24        $<LINK_LANGUAGE:CXX>
     25    
     26      Expression did not evaluate to a known generator expression
     27    
     28    
  >> 29    CMake Error at CMakeLists.txt:18 (target_link_libraries):
     30      Error evaluating generator expression:
     31    
     32        $<LINK_LANGUAGE:CXX>
     33    
     34      Expression did not evaluate to a known generator expression
     35    
     36    
  >> 37    CMake Error at CMakeLists.txt:18 (target_link_libraries):
     38      Error evaluating generator expression:
     39    
     40        $<LINK_LANGUAGE:CXX>
     41    
     42      Expression did not evaluate to a known generator expression
     43    

See test log for details:
  /home/vanessa/.spack/test/gqrsnwuo3spdzujvssfpekm4lrazskgn/kokkos-3.4.01-l4tyn6y-test-out.txt

==> Error: 1 test(s) in the suite failed.
```

### PR DESCRIPTION
**Pull request by RikkiButler20**
Fixes [27976](https://github.com/spack/spack/issues/27976)

Test fails when the `cmake` in the user's path is not the one used to build `kokkos`

### CODE REVIEW

**Comment by RikkiButler20** [comment]
@vsoch Can you make sure the test succeeds for you please?

**Comment by vsoch** [comment]
yep (testing now)!

**Comment by vsoch** [comment]
Looks good!
```
$ bin/spack test run kokkos
==> Spack test echght3uevlcrbdrqarzbddg5oijqvx7
==> Testing package kokkos-3.5.00-7oaupzb
============================= 1 passed of 1 specs ==============================
```

**Comment by janciesko** [comment]
Feel free to add me as reviewer.

**Review by janciesko — APPROVED** [review]
LGTM

**Review by tldahlgren — APPROVED** [review]
Works for me

**Pull request merged**
