### PR TITLE
Caliper: Add new release 2.6.0

### PR DESCRIPTION
**Pull request by quellyn**
This PR adds the latest Caliper release (2.6.0).

### CODE REVIEW

**Comment by alalazo** [comment]
Just a curiosity: why do we have some versions by git tag and some by Github archive with the corresponding sha?

**Comment by quellyn** [comment]
> Just a curiosity: why do we have some versions by git tag and some by Github archive with the corresponding sha?

Good question! I was going to change the `2.5.0` line so that it referenced the appropriate tag, but decided I'd better limit my changes to just adding `2.6.0`. Maybe we could ask the maintainer, @daboehme ? If he approves I could make that change as well (and also update the description URL to point to `2.6.0`).

I'm probably jumping the gun here anyway; David is the official maintainer and I should probably have waited for him.

**Comment by daboehme** [comment]
Hi @quellyn , I appreciate the initiative! As for sha vs. tag, I think providing the archive link + sha is preferred over using a github tag in Spack (?), so I used this starting with v2.5.0. I didn't want to go back and change it for all the older versions though. I'd say it's better to continue using the link+sha. Might also want to update the url line to refer to v2.6.0 now.

**Review by alalazo — APPROVED** [review]

**Review by daboehme — COMMENTED** [review]
Looks good to me!

**Pull request merged**
