### PR TITLE
Add netcdf-c 4.9.0 and netcdf-fortran 4.6.0 (supersedes #31953)

### PR DESCRIPTION
**Pull request by climbfuji**
This PR supersedes https://github.com/spack/spack/pull/31953/files. It includes all of @kgerheiser's contributions in https://github.com/spack/spack/pull/31953, but in addition it:
- resolves the conflicts when updating from the latest develop branch
- turns on the `zstd` variant by default, as requested in the review process of https://github.com/spack/spack/pull/31953

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha256.  Rest LGTM

**Comment by tldahlgren** [comment]
Deferring merge to give @skosukhin and or @WardF a chance to commit.

**Comment by skosukhin** [comment]
I don't want to hold this effort back any longer, so I say LGTM. However, `netcdf-c` needs some more work. For example, we build the package without any optimization flags because we set `CFLAGS` on the command line for the configure script. The flags should be set the way it's done in `netcdf-fortran` with `flag_handler`.

**Comment by WardF** [comment]
Looks good to me!

**Review by WardF — APPROVED** [review]

**Pull request merged**
