### PR TITLE
cgal: add v6.0.1

### PR DESCRIPTION
**Pull request by lang-m**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
There are pipeline failures, not sure if related:
- https://gitlab.spack.io/spack/spack/-/jobs/13158395

Let me know if you need any help looking at those. Also, I wish we already implemented this feature request https://github.com/spack/spackbot/issues/96 :melting_face:

**Comment by lang-m** [comment]
@alalazo I had a look at the test failure: after compiling the new cgal, the CI also tries to build two packages that need cgal. For one of the two, dealii, this fails with the new cgal version.

Two questions:
1. Why are some dependent packages build as part of the cgal CI? How is the decision made which packages are required to work with cgal before a new cgal version is accepted? The choice to me looks arbitrary (there are likely other packages that need cgal but are not compatible with the new version).
2. How do I best move forward with this? One solution would be to set the preferred version to 5.2 so that cgal@6 is not picked up by default. The other option would be to first pin the maximum cgal version in dealii (in a separate PR?) and rebase this PR afterwards.

Ping also @jppelteret and @luca-heltai , who are listed as dealii maintainers.

**Comment by alalazo** [comment]
> The choice to me looks arbitrary

The choice _is_ arbitrary, in some sense, but it is determined by a set of builds that we use to provide ready-to-go buildcaches for releases. You can check https://cache.spack.io/ The definitions for these stacks are in:
```
share/spack/gitlab/cloud_pipelines/stacks
```

> How do I best move forward with this?

I would check if `dealii` needs a bound on `cgal`, and if that is simple enough add it in this PR. If the modifications on `dealii` seem complicated we can find another way to go.

**Comment by luca-heltai** [comment]
@fdrmrc, do you know what fails with cgal@6.0? Is that a quick fix for dealii?

**Comment by fdrmrc** [comment]
@luca-heltai In cgal@6.0 all instances of `boost::variant/optional` have been replaced with `std::variant/optional` (cfr. "breaking changes" in https://www.cgal.org/2024/09/27/cgal60/), while in dealii we still assume that boost types are used.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
