### PR TITLE
gettext: add 0.21.1

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Review by tldahlgren — APPROVED** [review]
Re-confirmed sha256.

**Comment by tldahlgren** [comment]
Interesting.  No build failures reported on the CDash link and no build log in the pipeline artifacts, yet building `gettext` from source is failing.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Pull request merged**
