### PR TITLE
qt-*: add v6.5.3 & v6.6.0

### PR DESCRIPTION
**Pull request by aumuell**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed all of the new version sha256.

**Comment by tldahlgren** [comment]
@sethrj @wdconinc Did you want to comment on this PR though it is only adding new version directives?

**Comment by wdconinc** [comment]
I am trying to build the versions, just in case there's something that doesn't work on my system. But it's Qt, so it takes a while...

I didn't see anything specific in the diff between the v6.6.0 and v6.5.3 CMakeLists.txt (`find . -name CMakeLists.txt | xargs git diff v6.5.3 --`), but I was going to look into more detail in the openssl requirement. It is possible that the requirement is now for openssl3 (since the `QT_FEATURE_opensslv30` was removed).

**Review by wdconinc — APPROVED** [review]
Both v6.6.0 and v6.5.3 packages build fine on my test system (with openssl@3). Even though all openssl@1 versions are deprecated in spack, I tested with openssl@1.1.1w and v6.6.0 builds fine as well.

**Pull request merged**
