### PR TITLE
py-torchvision: fix typo in version restriction for ffmpeg

### PR DESCRIPTION
**Pull request by snehring**
Was looking through my semi-recent PRs incidentally and spotted a typo.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Good catch!

**Comment by snehring** [comment]
@spackbot re-run pipeline

**Comment by snehring** [comment]
I don't think these failures are the result of my changes, but I'll let sit a while before kicking it again.

**Comment by snehring** [comment]
@spackbot re-run pipeline

**Pull request merged**
