### PR TITLE
py-mako-1.1.6

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://github.com/sqlalchemy/mako/tree/rel_1_1_6

### CODE REVIEW

**Review by adamjstewart — COMMENTED** [review]
I'm guessing the Python dep should be type=build/run

**Comment by manuelakuhn** [comment]
Yep, fixed it.

**Review by adamjstewart — DISMISSED** [review]

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
Rebase to fix pipeline

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
