### PR TITLE
perl: ignore perllocal.pod files during package activation

### PR DESCRIPTION
**Pull request by mjwoods**
The perllocal.pod files list and describe non-core packages installed by users; they are not used by perl itself. In a normal perl installation, the perllocal.pod files are appended when new packages are installed. Under spack, perl packages each create their own perllocal.pod file. During package activation, the multiple perllocal.pod files conflict with each other, so that only one perl package can be activated at any time.

The solution proposed here ignores the perllocal.pod files during package activation, using code derived from the python package. We choose not to merge the files, as is done for some files in python packages, because they are not required for correct operation of perl and ignoring them is much simpler.

### CODE REVIEW

**Comment by mjwoods** [comment]
Hi @lee218llnl and @hartzell , would you mind reviewing this PR for me?

**Comment by mjwoods** [comment]
@tgamblin , would you be able to review this PR and merge if you are satisfied with it? It would be nice to have the `spack activate` feature working properly for perl packages.

**Comment by mjwoods** [comment]
@lee218llnl - thanks for your review. This PR has been sitting in the "approved" state for over a month now. Who can we ask to merge it? Maybe @hartzell ?

**Comment by tgamblin** [comment]
Merged!  Maybe @hartzell would be interested in being our perl person.  We currently don't have (or at least I don't know of anyone who has) perl expertise among the core committers.  @hartzell: are you interested in merge privs for perl?

**Pull request merged**
