### PR TITLE
GDB: Fix for GMP and Python

### LINKED ISSUE #26354: Installation issue: gdb@11.1
### Steps to reproduce the issue

```console
$ spack install gdb@11.1
[+] /usr (external python-3.6.8-42zz3vk7tj5ooiq2s33wqd4zx2njlxqj)
[+] /usr (external texinfo-6.5-uzihy7vowlztilxfy6wrzmos226rgcqn)
[+] /usr (external xz-5.2.4-aznlbqrcwv5pwolhte6xmvjwtvjrduaq)
==> Installing gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy
==> No binary for gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/cc/cc2903474e965a43d09c3b263952d48ced39dd22ce2d01968f3aa181335fcb9c.tar.gz
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/gdb-libintl-11.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> gdb: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

1 error found in build log:
     5318    checking size of unsigned __int128... 16
     5319    checking for library containing dlopen... none required
     5320    checking whether to use expat... auto
     5321    checking for libexpat... no
     5322    configure: WARNING: expat is missing or unusable; some features may be unavailable.
     5323    checking for libgmp... no
  >> 5324    configure: error: GMP is missing or unusable
     5325    make[1]: *** [Makefile:10420: configure-gdb] Error 1
     5326    make[1]: Leaving directory '/tmp/bc/spack-stage/spack-stage-gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy/sp
             ack-src/spack-build'
     5327    make: *** [Makefile:903: all] Error 2

See build log for details:
  /tmp/bc/spack-stage/spack-stage-gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-4399-cdcecda9d0
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### Additional information

gdb requires GMP to build since version 11.1. (https://www.gnu.org/software/gdb/download/ANNOUNCEMENT)

@robertu94

[spack-build-out.txt](https://github.com/spack/spack/files/7254919/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7254920/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### LINKED ISSUE #26358: Installation issue: gdb +python
### Steps to reproduce the issue

```console
$ spack install gdb@10.2 +python
[+] /usr (external python-3.6.8-42zz3vk7tj5ooiq2s33wqd4zx2njlxqj)
[+] /usr (external texinfo-6.5-uzihy7vowlztilxfy6wrzmos226rgcqn)
[+] /usr (external xz-5.2.4-aznlbqrcwv5pwolhte6xmvjwtvjrduaq)
==> Installing gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj
==> No binary for gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/b3/b33ad58d687487a821ec8d878daab0f716be60d0936f2e3ac5cf08419ce70350.tar.gz
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/gdb-libintl-10.patch
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/importlib.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> gdb: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

1 error found in build log:
     4954    checking for libmpfr... no
     4955    configure: WARNING: MPFR is missing or unusable; some features may be unavailable.
     4956    checking whether to use python... yes
     4957    checking for python... missing
     4958    checking for python... no
     4959    checking for python... no
  >> 4960    configure: error: python is missing or unusable
     4961    make[1]: *** [Makefile:10370: configure-gdb] Error 1
     4962    make[1]: Leaving directory '/tmp/bc/spack-stage/spack-stage-gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj/sp
             ack-src/spack-build'
     4963    make: *** [Makefile:854: all] Error 2

See build log for details:
  /tmp/bc/spack-stage/spack-stage-gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-4399-cdcecda9d0
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

The relevant part of packages.yaml is that we're using EL8 python as an external, which doesn't include a /usr/bin/python symlink.
```
  python:
    externals:
    - spec: python@3.6.8+bz2+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
```

### Additional information

gdb looks for a `python` binary to execute, but it isn't present when spack selects a `python~pythoncmd` package for the dependency.

@robertu94

[spack-build-out.txt](https://github.com/spack/spack/files/7255146/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7255149/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by robertu94**
@zzzoom it took less time than I thought to find a fix for these.  Can you please test if these work for you? 

closes  #26354 and closes #26358

Previously we did not pass paths for GDB or GMP and ./configure would
get confused about which one to pull from.  Be more specific about how to find them when needed.

### CODE REVIEW

**Comment by robertu94** [comment]
Marking this PR as a draft until I have time to test for backwards compatibility with older GDB versions, and/or I get feedback from @zzzoom that it works for him.

**Comment by zzzoom** [comment]
So I got this error:
```console
checking whether to use python... /usr/bin/python3.6
checking for python... no
configure: error: no usable python found at /usr/bin/python3.6
```

But it was because the test program couldn't include `Python.h`, and that was because the `platform-python-devel` package wasn't installed. I wonder if that's worth reporting to the python package maintainers. (the external had been detected automatically)

After installing that package, gdb built without problems. Thanks for the quick response.

**Review by zzzoom — DISMISSED** [review]
LGTM

**Comment by bernhardkaindl** [comment]
@robertu94 
One of the checks were failing: https://github.com/spack/spack/pull/26366/checks?check_run_id=3751258100
```py
2.7, 3.0     /home/runner/work/spack/spack/var/spack/repos/builtin/packages/gdb/package.py
  L78: `"..{}..".format(..)` requires 2.7, 3.0
  L81: `"..{}..".format(..)` requires 2.7, 3.0

Minimum required versions: 2.7, 3.0
Target versions not met:   2.6-, 3.5-
```
I replaced `{}` for format with `{0}` like it is done everywhere. I think this should fix that failure.
I also added to skip the huge gdb testsuite which had >700 fails. Fixing it for spack would be an immense project I guess,
so until somebody has time for that, this fixes builds running `spack install --test=all` where `gdb` is a common dependency.

**Comment by robertu94** [comment]
@bernhardkaindl I’d personally rather handle the build test problem with in a separate PR when I have time to investigate the failures (IE do they fail in upstream GDB, are they all tied to the same thing which is packaging related, is there a meaningful subset of tests to run instead). 

So unless we actively have CI that runs GDB with unit tests (I didn’t  think that is the default). I don’t see see the harm in waiting on that since failing conveys the intended message that it may not work 100%. Also I don’t think GDB is a common dependency for many things (it may have a handful). However I do agree it is an important dev tool and should eventually have passing tests. 

Before this gets merged, I still want to test the older GDB packages still build +python, or do I need to version gate adding the path.

**Comment by bernhardkaindl** [comment]
Hi Robert, thanks for caring about the `gdb` package!

Yes, spack doesn't have a CI pipeline which builds using --test=all or --test=root.

But. at least --test=all is not usable for developer and review use (to check if the changed package and it's dependencies are test-wise ok), when packages which are standard dependency lots of them don't pass their tests suite.

If fixed the test suites almost all packages to pass in spack: python, perl, all the GNU autotools, and so on. All the core.

Python packages, when built with --test=all, also pull `gdb` into the build (as far as I understood as python is then built in a debug variant, that seems to add `gdb` somehow - at least AFAICS). If then gdb fails in --test=all (and it also take a very long time to fail), the only option for verifying test suites that I had found so far is using --test=root, which only runs the test suite of the current package, making the tests far less comprehensive.

Therefore, to be able to use --test=all when test-building packages for a deeper review, I'd like to be able to not have gdb as hurdle which prevents me from using --test=all.

It is very cool that you might be looking into that, it just wasn't in reach for me. I think `dejagnu` needs to be updated to have the new Go and Rust language support that the testsuite seems to complain about added as an initial step. We we could have the "pass" of the testsuite (either this PR or another) merged in the meantime so --test=all could be done on py-* packages, that would be nice. Thanks Bernhard

**Comment by robertu94** [comment]
@bernhardkaindl if that is case, I'm happy to merge the empty `check()` function, but let's open an issue to fix it before we merge.  I hope to have time to run the backwards regression tests "soon".

**Comment by bernhardkaindl** [comment]
That's very nice, yes good! Thanks. The readme of the testsuite looks good, maybe it is good to enable a stable subset of the tests as shown in it.
https://fossies.org/linux/gdb/gdb/testsuite/README

**Comment by robertu94** [comment]
@bernhardkaindl Thanks for doing this testing and fixing the back-ports.  The fixes you made look good to me.  Can you merge the PR? -- I'm just a maintainer and don't have merge rights.

**Comment by bernhardkaindl** [comment]
@robertu94 to have the installation error fixed soon, I've started two tests:

Building all versions using gdb@$v+python and all versions with the other variants enabled:
```bash
for v in `spack versions -s gdb`;do spack install gdb@$v+python &sleep 10;done
V=source-highlight+lto+quad+gold+tui
for v in `spack versions -s gdb`;do spack install gdb@$v+$V &sleep 5;done
```    
The verdict isn't too bad, so I pushed the result for you to check:
```
@:8.1 were fixable by limiting python versions for these to @:3.6.
    
7.10.1 and 7.11(.1) were fixable to build with glibc-2.25 and newer using two long patches.
    
gdb 7.8 and 7.9 weren't fixable as there is no backport if the fix to build these with glibc-2.25 and newer:
http://lists.busybox.net/pipermail/buildroot/2017-March/188055.html
```
> @bernhardkaindl Thanks for doing this testing and fixing the back-ports. The fixes you made look good to me. Can you merge the PR?

Yes, we are good to merge from my view.

**Review by bernhardkaindl — APPROVED** [review]

**Comment by bernhardkaindl** [comment]
Enabling auto-merge, so if these tests are still good, github is free to merge:

**Pull request merged**
