### PR TITLE
amdlibflame: fix build with gcc from CrayPE

### PR DESCRIPTION
**Pull request by dev-zero**

### CODE REVIEW

**Comment by dev-zero** [comment]
@tldahlgren 🙏

**Review by tldahlgren — APPROVED** [review]
LGTM.  Would like feedback from a maintainer.

**Comment by tldahlgren** [comment]
@amd-toolchain-support Would you like to comment on this PR?

**Comment by alalazo** [comment]
@amd-toolchain-support

**Review by vkallesh — APPROVED** [review]
Approved

Thanks,
Vijay Teekinavar Kallesh

**Pull request merged**
