### PR TITLE
py-pyfr: add v2.0.3

### PR DESCRIPTION
**Pull request by MichaelLaufer**
Adds PyFR v2.0.3

### CODE REVIEW

**Comment by MichaelLaufer** [comment]
@spackbot fix style

**Review by tldahlgren — COMMENTED** [review]
Confirmed the version sha256.

**Review by tldahlgren — APPROVED** [review]
Confirmed requirements.

**Comment by MichaelLaufer** [comment]
@alecbcs regarding the PR name, this is indeed adding v2.0.3.

**Comment by alecbcs** [comment]
Apologies, our script misread the diff

**Pull request merged**
