### PR TITLE
Add new package py-protobuf

### PR DESCRIPTION
**Pull request by mwilliammyers**

### CODE REVIEW

**Comment by adamjstewart** [comment]
You should be able to use a url like: https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0b2.tar.gz

That way you don't need to specify the url for every different version. It doesn't seem to be working for 3.0.0b3 though. Maybe that version is down.

**Comment by mwilliammyers** [comment]
I was hoping I didn't need the hashes in the URLs. I updated it and squashed the commits.

**Comment by adamjstewart** [comment]
Looks great, thanks! I wonder if we can hack `spack create` to automatically try this URL...

**Comment by mwilliammyers** [comment]
Yeah I thought about adding that logic. I will look into it after I finish my [libc changes](https://groups.google.com/forum/#!topic/spack/xO4YhgKvOZs) which this is a *small* part of. haha

**Pull request merged**
