### PR TITLE
Hdf5 1.10.7

### PR DESCRIPTION
**Pull request by lrknox**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by lkurz** [comment]
Larry we need to reconsider the url change.

**Comment by lrknox** [comment]
ok, let's discuss the url change.

**Comment by lkurz** [comment]
Larry,  
The 'url' for the download is fine.
The 'homepage' can just simply be "https://portal.hdfgroup.org".
Les

**Comment by lrknox** [comment]
@lkurz 
@byrnHDF

**Comment by adamjstewart** [comment]
Would anyone else like to be added as maintainers of these packages?

**Comment by adamjstewart** [comment]
Good timing, this patch release fixes a bug with implicit declarations in Apple Clang 12.0.0 (LLVM Clang 10.0.0) which was released a couple of days ago.

**Comment by lrknox** [comment]
Great!

**Pull request merged**
