### PR TITLE
Add strumpack v5.1.0, add support for ROCm/HIP

### PR DESCRIPTION
**Pull request by pghysels**

### CODE REVIEW

**Comment by pghysels** [comment]
Suggested labels: e4s, xsdk, ecp, AMD, new-version

**Comment by haampie** [comment]
Hi @pghysels, I quickly looked at the project on github, and it seems as if you're only using a few source files that have device code, is that correct? And it seems like they are rather standalone source files, not public header files.

In that case, it'd be better to not use the hip compiler for the full project (so not setting CMAKE_CXX_COMPILER), but rather only for the sources that have device code. One way to do it is use `HIP_ADD_LIBRARY` from `FindHIP` in CMake which will automatically pick the host compiler for cpp files, and the device compiler (hipcc) for cu files (and you have some control over this behavior too). See https://github.com/eth-cscs/SpFFT/blob/master/src/CMakeLists.txt#L54-L65 for an example.

This is in particular useful in these Fortran+Cxx+OpenMP kinds of projects, since Fortran compiled with gfortran uses GNU's libgomp, and the C++ side would use clang's libomp thanks to hipcc. If you compile host code with gcc though, you end up with just libgomp.

**Comment by pghysels** [comment]
I have tried this before but I cannot get `HIP_ADD_LIBRARY` to work.
I get this error: `c++: error: unrecognized command line option ‘--amdgpu-target=gfx906'`
(similar to this issue I have: https://github.com/ROCmSoftwarePlatform/rocThrust/issues/149)

Are you suggesting I rename my HIP files to .cu?

I'm also confused about which cmake modules to use. If I add /opt/rocm-4.0.0/lib/cmake/hip to the CMAKE_MODULE_PATH, then I get `Unknown CMake command "hip_add_library"`

If I use the modules in /opt/rocm-4.0.0/hip/cmake/ it does include `hip_add_library`.
I see SpFFT includes copies of the cmake modules.

**Comment by haampie** [comment]
There's hip-config.cmake and there's FindHIP.cmake, one is a config file and the other a module. What you can try is `find_package(HIP MODULE REQUIRED HINTS ${HIP_PATH})` where `-DHIP_PATH` should be passed on the command line if you don't copy the module to your local sources module folder (probably default it to /opt/rocm for ease of use). 

If you need the `hip::*` targets then use `find_package(hip CONFIG REQUIRED HINTS /opt/rocm/..)` which doesn't need this HIP_PATH, cause it respects CMAKE_PREFIX_PATH (which spack sets for you).

hip_add_library has two mechanisms to use the host or device compiler for certain source files: https://github.com/ROCm-Developer-Tools/HIP/blob/main/cmake/FindHIP.cmake#L519 either the extension is .cu, or the source file is annotated with `HIP_SOURCE_PROPERTY_FORMAT`.

So if you replace `add_library` with `hip_add_library` it should not change anything for fortran and cpp sources, and if you want to maintain the .cpp filename for your hip device code, you should do smth like `set_source_files_properties(path/to/device/code.cpp PROPERTIES HIP_SOURCE_PROPERTY_FORMAT 1)` before calling `hip_add_library`.

I don't immediately see how those `amdgpu-target` flags are propagated to gfortran... and i don't see either how the link in that issue is a solution to the problem tbh :p. can you see what target is causing these flags to be propagated to fortran sources?

**Comment by pghysels** [comment]
Thank you. This is very helpful.
I will try this and make a new release, then update the spack script.

**Comment by pghysels** [comment]
I think I figured it out. `hip_add_library` does not work when you add the sources later with `target_sources`.
And I was manually adding `--amdgpu-target` using `target_compile_options`, which I removed now.

**Review by haampie — APPROVED** [review]
Thanks! Looks great

**Pull request merged**
