### PR TITLE
cuda: add 12.4.0, 12.3.2, 12.3.1 and 12.2.2

### PR DESCRIPTION
**Pull request by pauleonix**
Add cuda versions released since last summer

### CODE REVIEW

**Review by bernhardkaindl — DISMISSED** [review]
Rebased to the current develop for a fresh CI base (the base commit was about one week old and CI failed). CI should then be ready to run the GitLab pipeline tomorrow.

@ax3l @Rombur - Does this look good to you?

**Comment by pauleonix** [comment]
The CI failures are contained to neoverse platforms and seem to be related to CCCLs `cuda::std::tuple`. In the context of https://github.com/NVIDIA/cccl/issues/1519 , I would think that PETSc and Ginkgo are just using the non-standard interface (`t.get<n>()` instead of `thrust::get<n>(t)`) which got removed. In that case I don't understand why it seems to be fine on other platforms though...

**Comment by pauleonix** [comment]
According to release notes the change replacing the old `thrust::tuple` implementation with `cuda::std::tuple` came with CCCL 2.3.0. So this issue should only affect CUDA 12.4.0. CUDA 12.3.x ships with CCCL 2.2. 

PETSc seems to have fixed this issue recently (future release) in https://gitlab.com/petsc/petsc/-/merge_requests/7354

While the Ginkgo issue is somewhat related in that it is caused by the change of `thrust::tuple`, it is not related to Ginkgos usage of it, but actually a bug in CCCL that I think got fixed in https://github.com/NVIDIA/cccl/pull/1528 (future release).

So all in all it seems like the Ginkgo and PETSc packages need to be marked as incompatible with CUDA 12.4.0

**Comment by pauleonix** [comment]
@spackbot fix style

**Comment by pauleonix** [comment]
@balay @tcojean Do the introduced conflicts on PETSc and Ginkgo look good to you?

**Review by balay — APPROVED** [review]
Change is fine for PETSc

**Review by alalazo — APPROVED** [review]

**Pull request merged**
