### PR TITLE
e4s cray sles ci: expand spec list

### PR DESCRIPTION
**Pull request by eugeneswalker**
Taking advantage of unused Cray SLES cycles by expanding the `E4S Cray SLES` CI stack.

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline because some jobs failed due to missing dependency binaries

**Comment by eugeneswalker** [comment]
@spackbot run pipeline now that index.json has been updated to reflect the absence of all specs (post deleting the unsigned specs)

**Comment by eugeneswalker** [comment]
`py-pip` build is failing
* [py-pip/npe7l3c 23.1.2 gcc@=10.3.0 linux-sle_hpc15-x86_64_v4 E4S Cray SLES](https://gitlab.spack.io/spack/spack/-/jobs/7959257)

```
==> Installing py-pip-23.1.2-npe7l3cq75khbsijy62iqoq3mpxmrpxw [1/1]
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
==> Fetching https://mirror.spack.io/_source-cache/archive/3e/3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
==> No patches needed for py-pip
==> py-pip: Executing phase: 'install'
==> [2023-08-11-12:08:14.512161] '/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/python-3.10.12-yfzbv3xwlfi6rxcvwxptkaxsubodimwj/bin/python3.10' '/tmp/gitlab-runner-1/spack-stage/spack-stage-py-pip-23.1.2-npe7l3cq75khbsijy62iqoq3mpxmrpxw/spack-src/pip-23.1.2-py3-none-any.whl/pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/morepadding/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/py-pip-23.1.2-npe7l3cq75khbsijy62iqoq3mpxmrpxw' '/tmp/gitlab-runner-1/spack-stage/spack-stage-py-pip-23.1.2-npe7l3cq75khbsijy62iqoq3mpxmrpxw/spack-src/pip-23.1.2-py3-none-any.whl'
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "<frozen zipimport>", line 577, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen zipimport>", line 625, in _get_data
  File "<frozen zipimport>", line 580, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/python-3.10.12-yfzbv3xwlfi6rxcvwxptkaxsubodimwj/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen zipimport>", line 196, in get_code
  File "<frozen zipimport>", line 759, in _get_module_code
  File "<frozen zipimport>", line 627, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/python-3.10.12-yfzbv3xwlfi6rxcvwxptkaxsubodimwj/lib/python3.10/runpy.py", line 189, in _run_module_as_main
    mod_name, mod_spec, code = _get_main_module_details(_Error)
  File "/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/python-3.10.12-yfzbv3xwlfi6rxcvwxptkaxsubodimwj/lib/python3.10/runpy.py", line 238, in _get_main_module_details
    return _get_module_details(main_name)
  File "/home/gitlab-runner-1/builds/builds/vgV6LF2S6/0/spack/spack/opt/spack/[padded-to-256-chars]/linux-sle_hpc15-x86_64_v4/gcc-10.3.0/python-3.10.12-yfzbv3xwlfi6rxcvwxptkaxsubodimwj/lib/python3.10/runpy.py", line 159, in _get_module_details
    raise error(format(e)) from e
ImportError: can't decompress data; zlib not available
```

**Comment by eugeneswalker** [comment]
Just commented out `flux-core` until we can figure out why `python` is being built defectively on cray-sles

**Review by scottwittenburg — APPROVED** [review]

**Pull request merged**
