### PR TITLE
hdf5: fix showconfig

### PR DESCRIPTION
**Pull request by skosukhin**
This fixes the `Extra libraries` section of the `h5cc -showconfig` command so it looks as if the package was installed with Autotools: a space-separated list of linker flags instead of a semicolon-separated list of library names.

### CODE REVIEW

**Comment by naromero77** [comment]
Could one of the maintainers please review this PR?

**Review by hyoklee — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Comment by naromero77** [comment]
Do we have consensus from the maintainers?

**Comment by hyoklee** [comment]
@naromero77 , yes.

**Review by naromero77 — APPROVED** [review]
LGTM

**Comment by haampie** [comment]
This is wrong, causes

```
-l<path to>/libmpi.so
```

to be added, currently [failing on develop](https://gitlab.spack.io/spack/spack/-/jobs/6990446)

**Comment by hyoklee** [comment]
@haampie , isn't it failing on 1.8.22, not develop?

**Comment by haampie** [comment]
Yeah, I meant Spack's develop branch ^^

Gitlab CI ran Jan 17th on this PR, so although it's ✅ here, it probably wouldn't have been if it was rebased once more

**Comment by hyoklee** [comment]
I see. By the way, HDF5 1.8 is no longer supported.
@lrknox , would you please remove 1.8 from hdf5 package?

**Comment by naromero77** [comment]
> Yeah, I meant Spack's develop branch ^^
> 
> Gitlab CI ran Jan 17th on this PR, so although it's ✅ here, it probably wouldn't have been if it was rebased once more

I am new at merging things. What should I have done differently? Just trigger the @spackbot pipeline a second time right before the merge?

**Pull request merged**
