### PR TITLE
Added tau@2.33.2

### PR DESCRIPTION
**Pull request by wspear**

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
CI for TAU failed because the job never finished. It looks like a test of some kind hung forever:
* [ tau@2.33.2 /juuac74 %gcc@11.4.0 arch=linux-ubuntu22.04-x86_64_v3 E4S ](https://gitlab.spack.io/spack/spack/-/jobs/10755230)
```
...

NODE 3;CONTEXT 0;THREAD 2:
---------------------------------------------------------------------------------------
%Time    Exclusive    Inclusive       #Call      #Subrs  Inclusive Name
              msec   total msec                          usec/call 
---------------------------------------------------------------------------------------
100.0            8       15,176           1           1   15176453 .TAU application
 99.9        0.007       15,168           1           1   15168425 [PTHREAD] threaded_func 
 99.9        0.002       15,168           1           1   15168418 void *threaded_func(void *) C 
 99.9            8       15,168           1          12   15168416 double do_work(void) C 
 79.4       12,051       12,051           1           0   12051982 void compute(double **, double **, double **, int, int, int) C 
 19.2        2,908        2,908           1           0    2908076 void compute_interchange(double **, double **, double **, int, int, int) C 
  1.1          169          169           3           0      56591 double **allocateMatrix(int, int) C 
  0.2           30           30           3           0      10111 void initialize(double **, int, int) C 
  0.0        0.196        0.196           3           0         65 void freeMatrix(double **, int, int) C 
  0.0        0.003        0.003           1           0          3 MPI_Comm_rank() 

NODE 3;CONTEXT 0;THREAD 3:
---------------------------------------------------------------------------------------
%Time    Exclusive    Inclusive       #Call      #Subrs  Inclusive Name
              msec   total msec                          usec/call 
---------------------------------------------------------------------------------------
100.0            8       16,287           1           1   16287734 .TAU application
100.0        0.004       16,279           1           1   16279715 [PTHREAD] threaded_func 
100.0        0.002       16,279           1           1   16279711 void *threaded_func(void *) C 
100.0            8       16,279           1          12   16279709 double do_work(void) C 
 72.7       11,846       11,846           1           0   11846584 void compute(double **, double **, double **, int, int, int) C 
 26.1        4,257        4,257           1           0    4257242 void compute_interchange(double **, double **, double **, int, int, int) C 
  1.0          165          165           3           0      55019 double **allocateMatrix(int, int) C 
  0.0            2            2           3           0        870 void initialize(double **, int, int) C 
  0.0        0.183        0.183           3           0         61 void freeMatrix(double **, int, int) C 
  0.0        0.022        0.022           1           0         22 MPI_Comm_rank() 

FUNCTION SUMMARY (total):
---------------------------------------------------------------------------------------
%Time    Exclusive    Inclusive       #Call      #Subrs  Inclusive Name
              msec   total msec                          usec/call 
---------------------------------------------------------------------------------------
100.0          117     4:13.324          16          16   15832786 .TAU application
section_end:1713314817:step_script
[0K[0;33mWARNING: step_script could not run to completion because the timeout was exceeded. For more control over job and script timeouts see: https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts[0;m
[31;1mERROR: Job failed: execution took longer than 6h0m0s seconds
[0;m
```

@jordialcaraz Any ideas?

Should we disable the test run here?

**Comment by jordialcaraz** [comment]
The test that run into the timeout is the one that was there before I touched the tests and that example should be very fast, and the times that are shown (), prove it.

2024-04-16-18:51:52.201061] test: test_mpirun_n_4_matmult: Run matrix multiplication test with mpi
[2024-04-16-18:52:09.283757] test: test_pprof: Run pprof profile analysis tool on profile output

 Could it be that there was a problem with the node when configuring/building TAU and it took too long?

**Comment by eugeneswalker** [comment]
The timeout is 6 hours though… That’s pretty long even for a normally long running test, yes? It could be node issue, but, failed jobs get re run automatically and only fail ultimately after 3x total tries- each re run is pushed to the next available runner and is unlikely to go to same node more than once. Seems improbably that each node would be having an issue if that were the cause

**Comment by jordialcaraz** [comment]
I didn´t know that there were three tries. Try to disable it and see what happens. 

The tests, except the dyninst one, are very short. But if you don´t configure with dyninst, it should´t be used.

**Comment by eugeneswalker** [comment]
> I didn´t know that there were three tries. Try to disable it and see what happens.
> 
> The tests, except the dyninst one, are very short. But if you don´t configure with dyninst, it should´t be used.

How do we disable these tests?

**Comment by jordialcaraz** [comment]
There is a line with "@run_after("install")"

Comment that line and the tests shouldn't run.   I will check the tests locally.

Or comment all tests and I will be updating them to the new test function.

**Review by jordialcaraz — CHANGES_REQUESTED** [review]
Try to comment line 417 (@run_after("install")).
Edit: we also need to disable _def test(self)_

I opened an issue, as the test part is not working as expected:
https://github.com/spack/spack/issues/43714

Maybe the best would be to disable the tests until this issue is fixed or there is a workaround.

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
