### PR TITLE
Add defaults to spack.config.get("config:...")

### PR DESCRIPTION
**Pull request by haampie**
Sometimes there is no default config scope, for instance when

```python
with spack.config.use_config(tmp_config):
  install('xyz')
```
and spack.config.config_defaults is not used in tmp_config. It's easy to
forget.

This might inadvertently result in security issues, such as fetching
without ssl:

```python
if not spack.config.get('config:verify_ssl'):
   curl_args.append('-k')
```

This branch is followed when config:verify_ssl is not set and the get
function returns None.

### CODE REVIEW

**Comment by haampie** [comment]
personally i'd like to have getters for `spack.config.verify_ssl()` so that it can return a sensible default there instead of scattered around in the code base or in a `_builtin` scope that might not always be present

**Comment by becker33** [comment]
@haampie another way to improve security for this: should we make the default a required argument to `spack.config.get`? That way new development can't write this sort of bug.

**Review by becker33 — APPROVED** [review]

**Comment by haampie** [comment]
Hm yeah, what I don't like is repeating defaults on the call-site, cause defaults might potentially end up different in different places, or they are annoying to repeat, like `min(16, spack.util.cpu.cpus_available())`, and it's harder to maintain. That's why I suggested adding getters `spack.config.verify_ssl()` that ensure no None is returned.

**Comment by haampie** [comment]
I'm thinking about closing this @becker33, or do you still want this in?

**Comment by haampie** [comment]
Let me just close

**Pull request closed without merging**
