### PR TITLE
Rust seems to require z3.

### PR DESCRIPTION
**Pull request by KineticTheory**
Ping @AndrewGaspar

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
Hm... does it? Do you know which component is using z3? https://github.com/rust-lang/rust/blob/d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02/src/bootstrap/native.rs#L176

**Comment by KineticTheory** [comment]
> Hm... does it? Do you know which component is using z3? https://github.com/rust-lang/rust/blob/d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02/src/bootstrap/native.rs#L176

I really don't know anything about building `rust`.  I was trying to install `librsvg` that requires `rust`.  It wouldn't build on snow unless I added the z3 dependency.  I didn't try disabling any of the variants.

**Comment by AndrewGaspar** [comment]
I've definitely built this package on Snow before. Could you share the spack-build-out.txt?

**Comment by KineticTheory** [comment]
> I've definitely built this package on Snow before. Could you share the spack-build-out.txt?

Sure, but I'll need to regenerate the failing build.  In my current builds, I made the update and continued.

**Comment by adamjstewart** [comment]
Ping @KineticTheory, can you share those build logs?

**Comment by KineticTheory** [comment]
I can't reproduce the error.  @AndrewGaspar is vindicated!  Sorry for the noise on this PR.

**Pull request closed without merging**
