### PR TITLE
Cutlang: Create package.py

### PR DESCRIPTION
**Pull request by sabrivatansever**
This is an additional builtin package request for Cutlang.

### CODE REVIEW

**Comment by tldahlgren** [comment]
Please create non-`develop` branches for submissions in the future.  It makes it easier for us to pull and test contributions.

**Comment by tldahlgren** [comment]
In case you're unable to see results, the following style errors need to be corrected:

```
var/spack/repos/builtin/packages/cutlang/package.py:11: [E501] line too long (210 > 88 characters)
[145](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:145)
  var/spack/repos/builtin/packages/cutlang/package.py:12: [W293] blank line contains whitespace
[146](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:146)
  var/spack/repos/builtin/packages/cutlang/package.py:27: [W293] blank line contains whitespace
[147](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:147)
  var/spack/repos/builtin/packages/cutlang/package.py:31: [W293] blank line contains whitespace
[148](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:148)
  var/spack/repos/builtin/packages/cutlang/package.py:33: [W191] indentation contains tabs
[149](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:149)
  var/spack/repos/builtin/packages/cutlang/package.py:33: [E101] indentation contains mixed spaces and tabs
[150](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:150)
  var/spack/repos/builtin/packages/cutlang/package.py:34: [W191] indentation contains tabs
[151](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:151)
  var/spack/repos/builtin/packages/cutlang/package.py:34: [E101] indentation contains mixed spaces and tabs
[152](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:152)
  var/spack/repos/builtin/packages/cutlang/package.py:35: [W191] indentation contains tabs
[153](https://github.com/spack/spack/runs/6327622870?check_suite_focus=true#step:6:153)
  var/spack/repos/builtin/packages/cutlang/package.py:35: [E101] indentation contains mixed spaces and tabs
  ```

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Confirmed sha256.  Please fix the style errors.

**Comment by sabrivatansever** [comment]
I can't find how the error is caused in the latest version. I have to leave a blank line, but when I do, the whitespace error occurs.

**Comment by sabrivatansever** [comment]
> Confirmed sha256. Please fix the style errors.

I can't find how the error is caused in the latest version. I have to leave a blank line, but when I do, the whitespace error occurs.

**Comment by tldahlgren** [comment]
> > Confirmed sha256. Please fix the style errors.
> 
> I can't find how the error is caused in the latest version. I have to leave a blank line, but when I do, the whitespace error occurs.

Looks like you solved it.  The only check remaining ATM is the CI pipeline.

**Review by tldahlgren — APPROVED** [review]
LGTM.  Approved though final pipeline check still pending.

**Pull request merged**
