### PR TITLE
Added list_url to r-dt package

### PR DESCRIPTION
**Pull request by sknigh**

### CODE REVIEW

**Comment by adamjstewart** [comment]
I tested this PR to see what the effect is.

Before:
```
$ spack versions r-dt
==> Safe versions (already checksummed):
  0.1
==> Remote versions (not yet checksummed):
  3.0  1.0  0.9-1  0.2.3  0.2
$ spack checksum r-dt
==> Found 5 versions of r-dt
  3.0       https://cran.r-project.org/src/contrib/rvHPDT_3.0.tar.gz
  1.0       https://cran.r-project.org/src/contrib/rvTDT_1.0.tar.gz
  0.9-1     https://cran.r-project.org/src/contrib/SPODT_0.9-1.tar.gz
  0.2.3     https://cran.r-project.org/src/contrib/RcppBDT_0.2.3.tar.gz
  0.2       https://cran.r-project.org/src/contrib/DT_0.2.tar.gz

How many would you like to checksum? (default is 5, q to abort)
```
After:
```
$ spack versions r-dt
==> Safe versions (already checksummed):
  0.1
==> Remote versions (not yet checksummed):
  3.0  1.0  0.9-1  0.2.3  0.2
[02:39:02] ajstewart@mcswl143:~/spack (develop *)
$ spack checksum r-dt
==> Found 6 versions of r-dt
  3.0       https://cran.r-project.org/src/contrib/rvHPDT_3.0.tar.gz
  1.0       https://cran.r-project.org/src/contrib/rvTDT_1.0.tar.gz
  0.9-1     https://cran.r-project.org/src/contrib/SPODT_0.9-1.tar.gz
  0.2.3     https://cran.r-project.org/src/contrib/RcppBDT_0.2.3.tar.gz
  0.2       https://cran.r-project.org/src/contrib/DT_0.2.tar.gz
  0.1       https://cran.r-project.org/src/contrib/Archive/DT/DT_0.1.tar.gz

How many would you like to checksum? (default is 5, q to abort)
```
So not much of a change really. There is only one version available at that location, and it's still incorrectly picking up versions of other packages.

**Comment by becker33** [comment]
@sknigh @adamjstewart Can you confirm that this still applies? I tried it and still get only one version of r-dt.

**Comment by adamjstewart** [comment]
Ah, I finally figured out the intent of this PR. Before:
```
$ spack fetch r-dt
==> Fetching https://cran.r-project.org/src/contrib/DT_0.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://cran.r-project.org/src/contrib/DT_0.1.tar.gz failed.
==> Error: All fetchers failed for r-dt-0.1-adk73hqttb4qhuewjye2tm56p4sdneyt
```
After:
```
$ spack fetch r-dt
==> Fetching https://cran.r-project.org/src/contrib/DT_0.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
==> Fetching from https://cran.r-project.org/src/contrib/DT_0.1.tar.gz failed.
==> Fetching https://cran.r-project.org/src/contrib/Archive/DT/DT_0.1.tar.gz
######################################################################## 100.0%
```
@sknigh Please include an explanation for your change next time.

P.S. It looks like things were no longer working because version 0.2 was released and 0.1 was moved to the list_url. So if you want to add 0.2, go ahead. Regardless, this PR should be merged.

**Comment by adamjstewart** [comment]
Ping @tgamblin @becker33

**Pull request merged**
