### PR TITLE
Remove deprecated versions and packages

### PR DESCRIPTION
**Pull request by adamjstewart**
This PR removes deprecated versions for all packages that I'm maintaining. In future Spack releases, I'm planning to do this on a much larger scale, but @tgamblin wants me to hold off until we have better reproducibility.

I'm hoping that this will improve the maintainability of these packages. If any other maintainers of these recipes would like to retain any of these deprecated versions, or add new versions, speak now or forever hold your peace 😄

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot fix style

**Comment by stephenmsachs** [comment]
Can you explain why you are removing this? I would like to keep `py-devito` and possibly update it to newer versions with newer dependencies. But I cannot find out which versions/packages you want to remove and which are impacted as dependents.

**Comment by adamjstewart** [comment]
> Can you explain why you are removing this? I would like to keep py-devito and possibly update it to newer versions with newer dependencies.

py-devito was removed because it depends on py-codecov which was deprecated and removed. It might actually be able to keep this. Can you install codecov (no py-) and make sure it still installs a Python API (should be something in `lib/pythonX.Y/site-packages/codecov`)? Alternatively, if there's a newer version that no longer depends on codecov, we can add that.

**Comment by adamjstewart** [comment]
> But I cannot find out which versions/packages you want to remove and which are impacted as dependents.

If it has `deprecated=True` it was removed because that was always the plan. If it doesn't, it was removed because it either directly or indirectly required something that was deprecated and removed.

**Review by mlxd — DISMISSED** [review]
Thanks @adamjstewart 
No issue from me on removing the deprecated PennyLane versions.

**Review by thomas-bouvier — DISMISSED** [review]
No issue from me on removing deprecated `py-wandb`, thanks!

**Comment by adamjstewart** [comment]
Changes to GMT and py-devito have been removed. Only remaining packages that had to be removed due to deprecated dependencies are py-spyder and the packages that depend on it. We could theoretically try adding a newer version of spyder that no longer requires codecov, but I'll wait to see if anyone complains about removing it first.

**Review by AmintorDusko — APPROVED** [review]
Hi @adamjstewart, you have our OK to proceed with the changes in the `py-pennylane-lightning` and `py-pennylane` packages.

**Review by BoboTiG — APPROVED** [review]

**Review by tgamblin — APPROVED** [review]
Ok, I've looked at all these packages and I'm ok with *these particular* removals.  These are all things I suspect we do not have long-term users relying on and that I don't think people are going to be trying to use an old version of where they *need* the `package.py` to support the version.

I also think there are some things we can do in the future to make deprecations like this easier -- basically I don't want to lose reproducibility but I also don't want the mainline packages to have to drag everything along forever.  I think we can do a better job of separating/storing packages and lockfiles from mainline Spack to address that, and it doesn't need to hold up this PR.

Thanks @adamjstewart.

**Pull request merged**
