### PR TITLE
Remove support for PGI compilers

### PR DESCRIPTION
**Pull request by alalazo**
PGI compilers turned into the NVIDIA HPC SDK in 2020. The last community edition of PGI is from 2019 so it might be time to remove them. Possibly the best time frame is immediately after v0.23 branched-off, and before #45189 is merged.

We can also consider adding a warning in v0.23 that `pgi` compilers will be removed in the next version of Spack.

### CODE REVIEW

**Comment by alalazo** [comment]
@becker33 @tgamblin As we discussed on Monday, here's a PR that removes `pgi` compilers. I think the best time frame for this would be **after** v0.23. In case, let me know if I should submit another PR warning about `pgi` being removed.

**Review by hainest — COMMENTED** [review]
Boost changes look good.

**Review by hppritcha — APPROVED** [review]

**Review by bonachea — APPROVED** [review]
Chapel changes LGTM

**Review by snehring — APPROVED** [review]
dock change should be fine

**Review by t-brown — APPROVED** [review]

**Review by arezaii — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Pull request merged**
