### PR TITLE
Add /opt/homebrew to SYSTEM_PATHS in lib/spack/spack/util/environment.py

### LINKED ISSUE #39046: Modules: /opt/homebrew should be in list of system paths on macOS - or not?
### Steps to reproduce

On macOS, specifically on the M1 architecture, `/opt/homebrew` should be in the system paths:
```
diff --git a/lib/spack/spack/util/environment.py b/lib/spack/spack/util/environment.py
index da6832e4dd..8d60f108e8 100644
--- a/lib/spack/spack/util/environment.py
+++ b/lib/spack/spack/util/environment.py
@@ -36,7 +36,7 @@
     ]
     SUFFIXES = []
 else:
-    SYSTEM_PATHS = ["/", "/usr", "/usr/local"]
+    SYSTEM_PATHS = ["/", "/usr", "/usr/local", "/opt/homebrew"]
     SUFFIXES = ["bin", "bin64", "include", "lib", "lib64"]

 SYSTEM_DIRS = [os.path.join(p, s) for s in SUFFIXES for p in SYSTEM_PATHS] + SYSTEM_PATHS
```
The reason is that if you have things like `git-lfs`, `mysql` installed there (which are a nightmare to build on macOS in spack), then the current spack develop code puts the path `/opt/homebrew/bin` in front of  other paths when the spack-generated modules are loaded. If one has a `python3` in `/opt/homebrew/bin`, then suddenly that `python3` gets found again, even though the spack python3 module was loaded (first). The above change fixes that.

### Error message

See description above

### Information on your system

```
* **Spack:** 0.21.0.dev0 (98957cf32aa809e831bee4af2bf642e2bd038c04)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by climbfuji**
Closes https://github.com/spack/spack/issues/39046.

### CODE REVIEW

**Comment by climbfuji** [comment]
@srherbener FYI

**Comment by srherbener** [comment]
> @srherbener FYI

@climbfuji thanks for the pointer. Does this help resolve RPATH issues or the "_iconv missing symbol" issue? Thanks!

**Comment by climbfuji** [comment]
> > @srherbener FYI
> 
> @climbfuji thanks for the pointer. Does this help resolve RPATH issues or the "_iconv missing symbol" issue? Thanks!

No, but the one described in the issue.

**Comment by climbfuji** [comment]
@becker33 Don't merge this yet. I'll put it back in draft, because with this change I get tons of duplicates in the concretizer step!

**Comment by climbfuji** [comment]
> @becker33 Don't merge this yet. I'll put it back in draft, because with this change I get tons of duplicates in the concretizer step!

Scrap that. It's not this, it's the presence of the build cache. I'll make this PR ready for review again and open an issue for the buildcache.

**Comment by climbfuji** [comment]
Putting it back in draft again ... because basic tools like libevent don't build anymore. homebrew includes etc are not found. The issue connected to this PR is clearly a bug, but this (alone) is not the right solution ...

**Comment by climbfuji** [comment]
Closing this, since it is not the solution. We can continue the discussion in https://github.com/spack/spack/issues/39046

**Pull request closed without merging**
