### PR TITLE
sirius: inherit from ROCmPackage

### PR DESCRIPTION
**Pull request by albestro**
I admit I didn't test this...so I would kindly ask maintainers who may have a ready build environment for `sirius` if they can check it works correctly...sorry for that.

It is not expected to change (much) the overall behavior: ROCmPackage privides `hip` dependency, together with the variants `rocm` and `amdgpu_target` (with a centralised set of existing architectures).

For what concerns `amdgpu_target` variant:
- there would be **no default** anymore,
- the values supported should still support multiple values, but also `none` see [any_combination_of](https://spack.readthedocs.io/en/latest/spack.html#spack.variant.any_combination_of)

These changes may requires some additional fix either in the package itself (is none supported by the CMake logic?) and/or in the user workflow (no defaults, may require the user to specify actual architecture).

Looking forward for your reviews.

### CODE REVIEW

**Comment by toxa81** [comment]
We can merge it as-is and then test on our build farm. @AdhocMan do you need to introduce similar changes to SpFFT and SPLA?

**Comment by albestro** [comment]
> We can merge it as-is and then test on our build farm. @AdhocMan do you need to introduce similar changes to SpFFT and SPLA?

I just gave a look: `spfft` probably yes, `spla` may benefit from it (currently has `rocm` variant but it does not take into account `amdgpu_target`).

**Review by simonpintarelli — DISMISSED** [review]
Thank you @albestro. It compiled successfully for me.

**Review by AdhocMan — CHANGES_REQUESTED** [review]
If `None` is a possible value of `amdgpu_target`, then this is currently not properly handled, because the values will be used to define `HIP_HCC_FLAGS` and I think `--amdgpu-target=None` is not a valid flag. So I'd suggest to just not define this CMake argument it in this case, which will let SIRIUS make the choice.

**Comment by AdhocMan** [comment]
> > We can merge it as-is and then test on our build farm. @AdhocMan do you need to introduce similar changes to SpFFT and SPLA?
> 
> I just gave a look: `spfft` probably yes, `spla` may benefit from it (currently has `rocm` variant but it does not take into account `amdgpu_target`).

SPLA does not have any GPU kernels, so it should not require these changes. But yes, SpFFT should be similar to SIRIUS and could benefit from it.

**Comment by albestro** [comment]
> If `None` is a possible value of `amdgpu_target`, then this is currently not properly handled, because the values will be used to define `HIP_HCC_FLAGS` and I think `--amdgpu-target=None` is not a valid flag. So I'd suggest to just not define this CMake argument it in this case, which will let SIRIUS make the choice.

@AdhocMan, I've just checked and it is already managed in `ROCmPackage` 😉 
https://github.com/spack/spack/blob/35d07a6f18fecdde687a677334d3795999442e0c/lib/spack/spack/build_systems/rocm.py#L112-L113

**Review by AdhocMan — DISMISSED** [review]
> @AdhocMan, I've just checked and it is already managed in `ROCmPackage` 😉
> 
> https://github.com/spack/spack/blob/35d07a6f18fecdde687a677334d3795999442e0c/lib/spack/spack/build_systems/rocm.py#L112-L113

Great, this looks good to me then.

**Comment by simonpintarelli** [comment]
Can we merge this?

**Review by dev-zero — DISMISSED** [review]

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
There's a conflict to be solved before merging

**Comment by albestro** [comment]
sorry, I didn't see the conflict after the merge. I just solved the conflicts, can @simonpintarelli have a look if everything is correct?

thanks!

**Comment by simonpintarelli** [comment]
Thank you @albestro, this looks good to me!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
