### PR TITLE
ascent: add optional occa dep

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@spackbot style

**Comment by cyrush** [comment]
@spackbot do style

**Comment by cyrush** [comment]
@spackbot run style

**Comment by cyrush** [comment]
@spackbot fix style

**Comment by cyrush** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by cyrush** [comment]
Looks like there is some unrelated issue with embree and openimagedenoise in the data vis sdk.
Ascent doesn't leverage either of those.

**Comment by cyrush** [comment]
thanks @alalazo !

**Pull request merged**
