### PR TITLE
Update zlib to work with other compilers

### PR DESCRIPTION
**Pull request by krafczyk**
Add a patch which removes '-include' from `zlib` build script which causes build failures with `intel`, `pgi`, and `cce`.
Add a patch which removes '-w' from `zlib` build script which causes build failures with `cce`.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I plan on testing this out today. I also need the zlib build working for Intel and PGI, although I don't think I've had any problems in the past. But if it means less warning messages for invalid compiler flags, then that's good too.

**Comment by adamjstewart** [comment]
Ok, I tested this PR out a bit. I tried building zlib on the current develop branch but didn't see any problems. The build succeeded and there weren't even warning messages being displayed. I also tried building zlib from your branch and it worked as well, no difference. So I guess I'm curious what error message you were seeing, on what platform, with what compiler versions, and why I can't reproduce it.

Tested with GCC 6.1.0, Intel 17.0.2, and PGI 16.10 on CentOS 6.8.

**Comment by krafczyk** [comment]
So, my platform was the bluewaters supercomputer which is a cray machine.

I was using intel 16.0.3, pgi 16.9.0, and cce 8.5.5.

I'd have to try to reproduce the problem, but I remember that zlib building
crashed because it doesn't recognize `-w`, and it also crashed saying it
didn't recognize `-include` with intel, pgi, and cce.

**Comment by aprokop** [comment]
Sorry, I won't have time to look at this in the near future.

**Comment by adamjstewart** [comment]
@krafczyk How recent was this? There was one point at which we used `AutotoolsPackage` and the package failed to build because it ran `/path/to/configure` instead of `./configure`. But that was fixed a while ago.

**Comment by krafczyk** [comment]
@adamjstewart, Ah yes this was the reason for the include patch. I'll give another try to see whether it works now.

As far as how recent, What happened was I created a separate branch to work on since big changes sometimes take a while to be merged into the mainline. The series of PRs I've made in the past few days are an attempt to bring those changes into the mainline. In this case, the old branch is based on develop as of Feb 24 2017.

**Comment by krafczyk** [comment]
@adamjstewart, Okay I've re-checked this, and the include patch is now no longer needed. the `-w` patch is though. I've changed the commit accordingly.

**Comment by krafczyk** [comment]
And just so people are aware, without the `-w` patch, the shared library is not built.

**Comment by krafczyk** [comment]
@adamjstewart If you merge this, please also merge #4086 as well for zlib to be built with cray, otherwise spack crashes when asking for a pic variant because the pic flag is not currently defined for cray compilers, and #4086 fixers this.

**Comment by adamjstewart** [comment]
Ask and you shall receive.

**Pull request merged**
