### PR TITLE
atmi: add v5.4.4

### PR DESCRIPTION
**Pull request by alecbcs**
Add atmi v5.4.4. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

### CODE REVIEW

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Confirmed the sha256.  There is a version for-loop below that needs the new version added.

**Review by srekolam — COMMENTED** [review]
We don't intend to update the rocm recipes for 5..4.4 release. Instead we plan to update the rocm recipes for 5.5 release.

**Comment by alecbcs** [comment]
> We don't intend to update the rocm recipes for 5..4.4 release. Instead we plan to update the rocm recipes for 5.5 release.

@srekolam in that case, would you recommend skipping this version or just not adding the version to the secondary version list for the dependencies?

**Comment by srekolam** [comment]
> > We don't intend to update the rocm recipes for 5..4.4 release. Instead we plan to update the rocm recipes for 5.5 release.
> 
> @srekolam in that case, would you recommend skipping this version or just not adding the version to the secondary version list for the dependencies?

Yes.. please skip this version and wait for 5.5.0 release updates for the rocm recipes .

**Pull request closed without merging**
