### PR TITLE
plasma: add v24.8.7

### PR DESCRIPTION
**Pull request by luszczek**

### CODE REVIEW

**Review by RMeli — DISMISSED** [review]
SHA256 verified.

**Review by bernhardkaindl — APPROVED** [review]
Built the new version on Ubuntu 22.04

**Comment by bernhardkaindl** [comment]
@luszczek is the maintainer of the package, so we would be free to merge.

@balay: @luszczek invited you for review nonetheless: 

This is a simple change to add v24.8.7.

@balay - While you are not added as maintainer, do you want to weigh in before the merge?

**Review by bernhardkaindl — DISMISSED** [review]
@luszczek is the maintainer of the package, so we would be free to merge.

@balay: @luszczek invited you for review nonetheless: 

This is a simple change to add v24.8.7.

@balay - While you are not added as maintainer, do you want to weigh in before the merge?

**Review by balay — DISMISSED** [review]

**Comment by balay** [comment]
@luszczek to trigger the CI [and avoid the "Pending — This branch's merge-base with develop is newer than the latest commit ..." issue]  - I rebase my changes over latest `develop-date` tag. In this case:

```
$ git fetch
<check for latest develop tag>
$ git tag |grep develop |sort -n |tail -1
develop-2024-08-04
$ git rebase --onto develop-2024-08-04 origin/develop 
$ git push -f
```

**Comment by luszczek** [comment]
It seems that the branches are always out of date. The time of CI checks now exceeds the time between commits to `develop` branch. My commit cannot be merged even if I have *auto-update branch* enabled. I've been trying for a few days now so I'm assuming this is the new normal now.

**Comment by balay** [comment]
@luszczek for CI to run - the PR branch should *not* be merged with latest `develop` changes. It should be on an old snapshot of develop branch (that CI recognizes as tested)

So when you rebase over [or merge in] latest `develop` the CI is unlikely to run [as the latest develop is rarely matches `latest commit tested` - as indicated in the above CI message].

Hence my earlier suggestion:
```
$ git rebase --onto develop-2024-08-04 origin/develop 
```

I pushed this rebase now.

**Comment by luszczek** [comment]
I don't know what all these new changes are about. It's safer to close it and do it clean.

**Comment by balay** [comment]
@luszczek there was only one commit after my rebase [as this PR shows].

**Comment by luszczek** [comment]
The clean PR is in #45656 now. Let's see what happens.

**Pull request closed without merging**
