### PR TITLE
PMIx: master depends on munge

### PR DESCRIPTION
**Pull request by hppritcha**

### CODE REVIEW

**Comment by rhc54** [comment]
Ummm...all release branches of PMIx have a dependency on `munge` in that they will use it if the library is available. Has nothing to do with the `master` branch specifically.

**Comment by hppritcha** [comment]
okay.   I could swear with master i hit some kind of link issue on a system that didn't have munge installed.  i wasn't testing release tarballs.  so would it be better to include the dependency on munge unconditionally?

**Comment by rhc54** [comment]
It shouldn't be conditional as it spans releases. It also isn't a mandatory dependency - we just use it when running against Slurm and if the PMIx Slurm is using was built with munge. We recently had a contact from someone who built PMIx on a head node where munge was installed, but then ran on compute nodes where it was not installed. You get a warning that the `psec` munge component couldn't be loaded, and so I told them how to turn that warning off. Perhaps you hit a similar issue?

**Comment by hppritcha** [comment]
okay i think it doesn't make sense to pull in this dependency then.

**Pull request closed without merging**
