### PR TITLE
hdf5: source directory already configured

### PR DESCRIPTION
**Pull request by davydden**
p.s. probably something changed in Autotools package as I did not have this with 1124bdc99ee84c26201c40536d9b04dac74d7f6a

p.p.s.  the stage was clean, i was not rebuilding a failing build.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I just tried building it from develop and had no problems...

**Comment by davydden** [comment]
i also had no problems on linux PC, but suddenly I have problems on Centos7 cluster...

**Comment by adamjstewart** [comment]
Also just tried on our CentOS 7 cluster, no problems. Weird... You're building `hdf5@1.10.0-patch1`?

**Comment by davydden** [comment]
> You're building hdf5@1.10.0-patch1?

correct. Funny enough, i just tried to reproduce it and I can't... I am closing this PR for now

**Comment by tgamblin** [comment]
Do you have the log from the failed build?

**Comment by davydden** [comment]
> Do you have the log from the failed build?

not anymore because I went on and built the package with the original patch.

**Comment by davydden** [comment]
@tgamblin the build log was essentially a few lines and then

> error: source directory already configured. Bla-blah, try make distclean

**Pull request closed without merging**
