### PR TITLE
slurm: new versions

### PR DESCRIPTION
**Pull request by robert-mijakovic**

### CODE REVIEW

**Comment by haampie** [comment]
Can you rebase to `develop` and remove the redundant commits?

**Comment by robert-mijakovic** [comment]
> Can you rebase to `develop` and remove the redundant commits?

I have now rebased and squashed the previous commits. @haampie How should I remove the redundant commit?

**Comment by haampie** [comment]
I'm afraid the commit went missing :sweat_smile: sometimes this helps:

```
$ git checkout -b my-slurm-pr
$ git fetch upstream # assuming upstream == spack/spack, if not do `git remote add upstream https://github.com/spack/spack.git` first
$ git reset --hard upstream/develop
$ git cherry-pick [sha of your commit that adds slurm]
$ gh pr create
```

**Comment by robert-mijakovic** [comment]
I think the new one I created will be better.

**Pull request closed without merging**
