### PR TITLE
umpire: add v2023.06.0

### PR DESCRIPTION
**Pull request by rbberger**

### CODE REVIEW

**Review by alecbcs — APPROVED** [review]
Confirmed git commit. Looks good to me.

**Comment by alecbcs** [comment]
@rbberger does this new version of umpire require new versions of dependencies or a newer C++ std? 
Looks like it is failing in CI.

**Comment by rbberger** [comment]
@alecbcs Might be CUDA/ROCm failures. Haven't looked at the GPU builds so far. I'll take a look next week.

**Comment by pranav-sivaraman** [comment]
It seems like this [PR](https://github.com/spack/spack/pull/39613) updates the whole RAJA suite? Although that has a lot of changes and it might be better to get a newer version of Umpire in develop now.

**Comment by rbberger** [comment]
@pranav-sivaraman good catch! I have no preference either way. If that PR goes in first I'll just close this one.

**Comment by adrienbernede** [comment]
@pranav-sivaraman Thank you for spotting my PR. The packages there are much more appropriate to build recent versions of RAJA, Umpire, and such. Those packages are also the ones we use in CI on LLNL machines, meaning they are vetted in real-world environments.

However, I am having trouble debugging the Spack CI, especially when rocm is involved. We run with much more recent versions of rocm, which has been a moving target. So debugging the Spack CI (still using rocm@4.3) is painful and hard to prioritize.

Typically one issue seems to be that we moved away from the early hacks consisting, for example, in using hipcc compiler locally to the package.

In the end, we hope to find a path forward soon for #39613, providing our users with next generation Umpire package with support for the latest features and vetted usage on supercomputers.

**Comment by pranav-sivaraman** [comment]
@adrienbernede 

Can't wait for that to be merged in. I do have a suggestion. Would it be possible to use tarballs from the GitHub releases instead of pointing to a particular git commit? Or if you want to continue using git commits and your not using submodules you can get the tarball for that particular hash explained [here](https://spack.readthedocs.io/en/latest/packaging_guide.html).

**Comment by adrienbernede** [comment]
@pranav-sivaraman is there a reason you prefer tarball to git tag + commit hash ?
There was a tentative PR to use tarballs hash for RAJA in #39527. Our conclusion was that it was equivalent security-wise. I am partial to git tags, but maybe I am missing something ?

**Comment by pranav-sivaraman** [comment]
@adrienbernede Actually, I thought git tag + commit hash would not let me create a source cache for offline building, but I just tested and it let me do it. So I guess I have no preference for tarballs.

**Comment by adrienbernede** [comment]
@rbberger @alecbcs Umpire versions 2023.06.0 and 2024.02.0 have been added in https://github.com/spack/spack/pull/41375.

**Comment by rbberger** [comment]
@adrienbernede thx! Closing.

**Pull request closed without merging**
