### PR TITLE
Bazel: new versions, patches, conflicts, and java version contraints

### PR DESCRIPTION
**Pull request by adamjstewart**
This PR involves several improvements to the bazel package:

- [x] Add versions 4.1.0 through 5.2.0
- [x] Update fujitsu patches for compatibility with new source code
- [x] Rename patches to match file being modified
- [x] Mark older versions as incompatible with Apple M1
- [x] Specify required Java versions

The last one in particular was necessary for me to get the build working, OpenJDK 17 did not work.

Successfully builds and passes all tests on macOS 12.4 (Apple M1 Pro) with Apple Clang 13.1.6.

@haralmha closes #29016 

@glennpj @elfprince13 are #28548 and #30655 still necessary, or do you still need support for older bazel and newer GCC?

### CODE REVIEW

**Comment by elfprince13** [comment]
Our team is currently running Tensorflow 2.4 (via https://github.com/FloopCZ/tensorflow_cc) on Ubuntu 22.04 with Clang 14 which requires old-ish Bazel.

**Review by alalazo — APPROVED** [review]
@adamjstewart All the changes LGTM in terms of Spackiness. Feel free to merge at your will.

**Comment by adamjstewart** [comment]
I'll give @glennpj a few more days to review and then merge. Once this is merged, we should rebase one of #28548 or #30655. I'll finally be able to test those PRs now that I've managed to get bazel building!

**Comment by glennpj** [comment]
This looks good to me. I am not able to really test all of the patches but bazel-5.2.0 builds fine with gcc-12 on CentOS-7.

**Pull request merged**
