### PR TITLE
Pipelines: pin importlib-metadata and setuptools-scm versions

### PR DESCRIPTION
**Pull request by alalazo**
This will hopefully be a hotfix for the issue with pipelines in #26813 and #26820

### CODE REVIEW

**Review by scottwittenburg — APPROVED** [review]
If this makes the gitlab pipeline pass, then I agree it's better than reverting #26820.

**Comment by alalazo** [comment]
@scottwittenburg This is green including pipelines. Merge at your will and please make pipelines required again :laughing:

**Review by tgamblin — APPROVED** [review]

**Comment by adamjstewart** [comment]
Have we figured out why the newer version doesn't build?

**Comment by alalazo** [comment]
Need to dig deeper into that, but this seems the error being raised in [this pipeline](https://gitlab.spack.io/spack/spack/-/jobs/1148488):

Screenshot from 2021-10-20 05-20-34

**Comment by adamjstewart** [comment]
Hmm, I can't seem to reproduce this locally...

**Comment by alalazo** [comment]
@adamjstewart I used:
```console
$ spack ci reproduce-build --working-dir=/tmp/pipeline-failure https://gitlab.spack.io/spack/spack/-/jobs/1148711/artifacts/download
```
and followed instructions to reproduce  [this error](https://gitlab.spack.io/spack/spack/-/jobs/1148711). In the container the cause seems different, and reads:
```console
==> [2021-10-20-07:26:42.960795] Adding compiler bin/ paths: /builds/spack/spack/spack/lib/spack/env /builds/spack/spack/spack/lib/spack/env/case-insensitive /builds/spack/spack/spack/lib/spack/env/gcc
==> [2021-10-20-07:26:42.997297] Error: RuntimeError: Unable to locate python command in /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.10-ihtrj5dmjbjmlc2satbke4h4kagkrnq3/bin

/builds/spack/spack/spack/var/spack/repos/builtin/packages/python/package.py:668, in command:
        665                return Executable(path)
        666        else:
        667            msg = 'Unable to locate {0} command in {1}'
  >>    668            raise RuntimeError(msg.format(self.name, self.prefix.bin))


Traceback (most recent call last):
  File "/builds/spack/spack/spack/lib/spack/spack/build_environment.py", line 1027, in _setup_pkg_and_run
    pkg, dirty=kwargs.get('dirty', False), context=context)
[ ... ]
```

**Comment by scottwittenburg** [comment]
> followed instructions to reproduce [this error](https://gitlab.spack.io/spack/spack/-/jobs/1148711). In the container the cause seems different, and reads:

There's some logic missing from the `reproduce-build` code that prevents reproducing builds on `develop` pipelines.  It has to do with the reproducer not taking into account that it needs the gpg key needed to verify the binary dependency packages.  I'll write up an issue.

**Comment by scottwittenburg** [comment]
The issue is written up in #26854.

It includes a note on how to get the reproducer to work (insert `--no-check-signature` in the cli options before the step where you run `install.sh`), in case that's helpful debugging this particular problem while I'm coming up with a fix.

**Pull request merged**
