### PR TITLE
charliecloud: add v0.38

### PR DESCRIPTION
**Pull request by tygoetsch**
Update Charliecloud package.py with Charliecloud/0.38 sha256 checksum.

### CODE REVIEW

**Review by j-ogas — COMMENTED** [review]
Assuming all CI checks pass, LGTM. @reidpr any 0.38 package changes that need to be addressed?

**Review by reidpr — APPROVED** [review]
LGTM.

@j-ogas 0.38 is not very exciting, so not that I can think of.

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Ping me when you decide to take it out of Draft mode.

**Comment by tygoetsch** [comment]
@tldahlgren PR is ready to be merged whenever you're ready.

**Pull request merged**
