### PR TITLE
py-ipykernel: fix bug in phase method

### LINKED ISSUE #19985: py-ipykernel: install_data phase fails
Unable to install `py-ipykernel@5.3.4` due to failure of `install_data` phase.

Using:
* `spack@develop`
* eca1370abc65341421597018cc5b702a3e5ab46e
* `2020-11-18 8:37 AM PST`

```
$> spack install py-ipykernel@5.3.4
...
==> py-ipykernel: Executing phase: 'build'
==> py-ipykernel: Executing phase: 'install'
==> py-ipykernel: Executing phase: 'install_data'
==> Error: TypeError: install_data() takes 1 positional argument but 3 were given
/builds/uo/e4s/spack/lib/spack/spack/build_environment.py:863, in _setup_pkg_and_run:
        860        tb_string = traceback.format_exc()
        861
        862        # build up some context from the offending package so we can
  >>    863        # show that, too.
        864        package_context = get_package_context(tb)
        865
        866        logfile = None
...
```

Introduced via commit 8b431d17742a43aeca06d897dd5889a58df0d259 ?

@ax3l @adamjstewart @scottwittenburg

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #19985 

@eugeneswalker can you test this?

### CODE REVIEW

**Comment by eugeneswalker** [comment]
> @eugeneswalker can you test this?

testing now...

**Comment by eugeneswalker** [comment]
Using this PR:

```
$> spack install py-ipykernel
...
==> Installing py-ipykernel-5.3.4-wyn6znqdqfrlv6wklwntnensz4ycpoy3
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/9b/9b2652af1607986a1b231c62302d070bc0534f564c393a5d9d130db9abbbe89d.tar.gz
==> py-ipykernel: Executing phase: 'build'
==> py-ipykernel: Executing phase: 'install'
==> py-ipykernel: Executing phase: 'install_data'
==> Error: TypeError: expected string or bytes-like object

/opt/spack/var/spack/repos/builtin/packages/py-ipykernel/package.py:48, in install_data:
         46    def install_data(self, spec, prefix):
         47        """ install the Jupyter kernel spec """
  >>     48        self.spec['python'].command('-m ipykernel', ['install'])
...
```

Here's the trace:
```
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/build_environment.py", line 847, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/opt/spack/lib/spack/spack/installer.py", line 1673, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/opt/spack/lib/spack/spack/package.py", line 109, in phase_wrapper
    phase(spec, prefix)
  File "/opt/spack/var/spack/repos/builtin/packages/py-ipykernel/package.py", line 49, in install_data
  File "/opt/spack/lib/spack/spack/util/executable.py", line 147, in __call__
    quoted_args = [arg for arg in args if re.search(r'^"|^\'|"$|\'$', arg)]
  File "/opt/spack/lib/spack/spack/util/executable.py", line 147, in <listcomp>
    quoted_args = [arg for arg in args if re.search(r'^"|^\'|"$|\'$', arg)]
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
==> [2020-11-18-22:20:55.281313] Flagging py-ipykernel-5.3.4-wyn6znqdqfrlv6wklwntnensz4ycpoy3 as failed: TypeError: expected string or bytes-like object
==> [2020-11-18-22:20:55.316126] ChildError: TypeError: expected string or bytes-like object
```

**Comment by adamjstewart** [comment]
Okay, fixed another bug, can you try again? I'm now able to install this on my end, although idk if it knows where to look for its own kernels.

**Comment by eugeneswalker** [comment]
1bd04c74a0d81a8be415c13344b9d3e2b9618327 fixed it. Working now! Thank you!

**Review by eugeneswalker — APPROVED** [review]

**Comment by ax3l** [comment]
What have I done :see_no_evil: Must have tested before my last rebase - sorry for this.
Thank you @adamjstewart @eugeneswalker !

**Pull request merged**
