### PR TITLE
Features/package_test

### PR DESCRIPTION
**Pull request by davydden**
as per discussion in https://github.com/LLNL/spack/pull/812

@tgamblin @eschnett @alalazo ping.

### CODE REVIEW

**Comment by davydden** [comment]
don't understand why coverage decreased as I documented the functions I introduce.

**Comment by alalazo** [comment]
@davydden that's because you added code in `lib/spack/spack/package_test.py` but no unit test for it. 

FYI coverage is computed only on source files under `lib`, packages were left out on purpose.

**Comment by davydden** [comment]
i don't know how to add tests :smile:

**Comment by davydden** [comment]
but I can certainly add a `hallo world` `c` test if guide me how.

**Comment by tgamblin** [comment]
@davydden: I think we'll be ok with a 0.1% loss in coverage 😄.  

If you want to add a test I think it would be ok, but we could also just build openblas or another representative package as part of the travis runs.  That might be an easier way to go.

**Pull request merged**
