### PR TITLE
openblas: Added +fpic variant to package.

### PR DESCRIPTION
**Pull request by citibeth**
See: https://github.com/xianyi/OpenBLAS/wiki/faq#static_link

### CODE REVIEW

**Comment by tgamblin** [comment]
@eschnett @davydden: does this work portably?

**Comment by citibeth** [comment]
I'm mystified how it worked WITHOUT the -lpthread.  My guess is that the
author of was using a compiler (or compiler wrapper) that automatically
included -lpthread, similar to the way that libc is also automatically
included.

libpthread is a very standard low-level Unix library, and it should always
be available in the system.  I can't vouch for what would happen on
Windows.  But if there's no pthread library available SOMEHOW, then the
test will fail and OpenBLAS won't work anyway.

**Comment by citibeth** [comment]
There should probably be a way that the openblas package can ensure that
anyone depending on it includes -lpthread in their link commands.  Don't
know how to do that with Spack.

**Comment by citibeth** [comment]
@davydden As of PR #829, I'm having a lot of problems with openblas.

- **openblas**: works
- **openblas~shared+openmp**:  Doesn't work, since the test case does not link to OpenMP.  Before that problem was encountered, the +fpic stuff in this PR was added to get over another problem.
- **openblas~shared~openmp**: Didn't test

I would suggest that this package would benefit from some thorough testing at this point.  It should be tested with all relevant combinations of variants.  And not just that the package can be built... but also used.  Try building suite-sparse that depends on openmpi.

**Comment by davydden** [comment]
@citibeth 

> My guess is that the
author of was using a compiler (or compiler wrapper) that automatically
included -lpthread

i tested on OSX with Clang + gfortran (`~openmp`) and Ubuntu with GCC. In both case `+shared`.

> And not just that the package can be built... but also used

I am using it quite a lot, namely to build things like `deal.ii` which use `petsc`, `trilinos`, `suite-sparse`, `metis`, `mpi`, etc. And I don't just build it, i actually run the test suite of 8000+ unit tests, so the unit test in `openblas` may be fragile but the openblas itself should be fine.

FIY see the cleaned-up version here https://github.com/LLNL/spack/pull/845/files which runs a small test both for `blas` and `lapack`, if that works then this package indeed should be usable. 

> It should be tested with all relevant combinations of variants

I will try `~shared~openmp` and `~shared+openmp`...

**Comment by davydden** [comment]
@citibeth 

> openblas~shared~openmp: Didn't test

`~openmp~shared` worked on OSX with both `clang+gfortran` and `gcc`, the unit test is certainly run. I am afraid I can't reproduce this part of your observation.

i will test `openmp` variant once I am work with ubuntu nearby...

**Comment by davydden** [comment]
@citibeth 
> openblas~shared+openmp: Doesn't work

Indeed. Fixed in https://github.com/LLNL/spack/pull/845

**Comment by davydden** [comment]
@citibeth i added `-lpthread` to the my PR as it makes sense to do the checks with it. You can drop the first commit in this PR and probabaly also rename it so that it reflects the new variant `fPIC`.

**Comment by citibeth** [comment]
I will make a clean dev-branch Spack on CentOS 7 and post the results of my test.

**Comment by davydden** [comment]
@citibeth please do it from my PR as there are some minor fixes.

**Comment by tgamblin** [comment]
@davydden @citibeth: is this ready to merge?

**Comment by citibeth** [comment]
Yes

**Pull request merged**
