### PR TITLE
fix : swiftsim will set git environment variables in the appropriate hook

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications : 
- [x] prevent a warning due to `swiftsim` to ALWAYS be displayed

@tgamblin My bad for this leftover from #1118

### CODE REVIEW

**Comment by tgamblin** [comment]
@alalazo: I must've missed this the first time. Does this not make the install unsafe?  If the user is cloning a particular commit, you get the assurance of a SHA hash.  However, this clones a tag.  Without SSL, you could be man-in-the-middled here, as git will just trust the tag in the cloned repo...

**Comment by alalazo** [comment]
@tgamblin I see your point. Better now?

**Comment by tgamblin** [comment]
Works for me -- I think longer term we probably want something to audit packages for stuff like this.  Right now it worries me a bit that we don't have anything.

**Comment by alalazo** [comment]
@tgamblin Do you think setting up some automatic tool to inspect for security issues like this one will be feasible? I ask because I just spent the last 10 minutes trying to figure out where I would start should I need to build something like that and realized I have absolutely no clue... :smile:

**Comment by tgamblin** [comment]
@alalazo: I think it has to be kind of custom, as it needs to parse Spack packages, but I think it's a good idea.  I think the first step would be to make sure everything can be fetched and installed securely.  Basically I think for each fetch strategy we need to know what's guarantees are there (basically I think we have SSL and checksum at our disposal) and when a version can be fetched "securely".  For example, these could be considered secure (barring `spack --insecure`):

  - Unencrypted `http` with checksum
  - `git` over `https` without checksum 
  - `svn` over `https`

Whereas this would be insecure:
  - 

We could also talk about how strong the hashes should be.  `md5` is actually fairly weak, so should we require, e.g., SHA-256.

**Pull request merged**
