### PR TITLE
eckit: add v1.19.0

### PR DESCRIPTION
**Pull request by eugeneswalker**
@skosukhin

### CODE REVIEW

**Comment by skosukhin** [comment]
@eugeneswalker could you, please, explain the need for an older version?

**Comment by eugeneswalker** [comment]
> @eugeneswalker could you, please, explain the need for an older version?

We are working with a team from NOAA that specifically requested `@1.19.0`. I don't know anything about the use of this software or the difference in the versions, only that this version is specifically requested by people who I expect know the difference and have a reason for preferring one over the other. What do you think?

**Comment by eugeneswalker** [comment]
> @eugeneswalker could you, please, explain the need for an older version?

Do you object to having this version registered with Spack? Is it OK?

**Comment by skosukhin** [comment]
@eugeneswalker no, I don't. Thank you for the explanation.

**Review by skosukhin — APPROVED** [review]

**Review by wspear — APPROVED** [review]

**Pull request merged**
