### PR TITLE
Add `submodules` option for git fetching.

### LINKED ISSUE #1216: Option to "git submodule update  --init" at pull-time
Some packages will perform this additional git pull step during install. This creates issues when connectivity is limited. An option like this would mean the correct source is available in the mirror.

### PR DESCRIPTION
**Pull request by tgamblin**
Resolves #1216.  Allows user to supply `submodules=True` to git fetch.  e.g.:

```python
    version('develop', git='<git url>', branch='master', submodules=True)
```

@willelm: Can you see if this PR meets your needs?

### CODE REVIEW

**Comment by willelm** [comment]
diff --git a/lib/spack/docs/packaging_guide.rst b/lib/spack/docs/packaging_guide.rst
index e616581..0f549e2 100644
--- a/lib/spack/docs/packaging_guide.rst
+++ b/lib/spack/docs/packaging_guide.rst
@@ -604,6 +604,7 @@ Git fetching is enabled with the following parameters to ``version``:
   * ``tag``: name of a tag to fetch.
   * ``branch``: name of a branch to fetch.
   * ``commit``: SHA hash (or prefix) of a commit to fetch.
+  * ``submodules``: Also fetch submodules when checking out this repository.
 
 Only one of ``tag``, ``branch``, or ``commit`` can be used at a time.
 
@@ -660,6 +661,17 @@ Commits
   could just use the abbreviated commit hash.  It's up to the package
   author to decide what makes the most sense.
 
+Submodules
+
+  You can supply ``submodules=True`` to cause Spack to fetch submodules
+  along with the repository at fetch time.
+
+  .. code-block:: python
+
+     version('1.0.1', git='https://github.com/example-project/example.git',
+             tag='v1.0.1', submdoules=True)
+
+
 Installing
 ^^^^^^^^^^^^^^
 
diff --git a/lib/spack/spack/fetch_strategy.py b/lib/spack/spack/fetch_strategy.py
index bc74448..bcb33bd 100644
--- a/lib/spack/spack/fetch_strategy.py
+++ b/lib/spack/spack/fetch_strategy.py
@@ -598,7 +598,7 @@ class GitFetchStrategy(VCSFetchStrategy):
 
         # Init submodules if the user asked for them.
         if self.submodules:
-            self.git('submodule', '--init')
+            self.git('submodule', 'update', '--init')
 
     def archive(self, destination):
         super(GitFetchStrategy, self).archive(destination, exclude='.git')

**Comment by willelm** [comment]
Just missing the 'update' argument. And it works, yes.

**Comment by willelm** [comment]
I can't push changes.

**Comment by tgamblin** [comment]
Fixed!

**Comment by tgamblin** [comment]
@trws: FYI

**Pull request merged**
