### PR TITLE
adios2: add v2.10.2 release

### PR DESCRIPTION
**Pull request by vicentebolea**
:tada: :tada: :tada: 

Finally! ADIOS2 v2.10.2 patch release is out.

This bring exiting new features and bugfixes. Find the release notes at:
https://github.com/ornladios/ADIOS2/releases/tag/v2.10.2

Let me know if we need to change anything else in the package

ViB

:tada: :tada: :tada:

### CODE REVIEW

**Review by bernhardkaindl — COMMENTED** [review]
<details><summary>@vicentebolea, click here to see a build failure on adios2@2.10.2</summary><br>

Hello @{author}, the installation of `{spec}` failed in an automated build:

This command failed: `bin/spack install -v --fail-fast --deprecated adios2@2.10.2`
<details><summary>Failed spec: adios2@2.10.2</summary>

### `adios2@2.10.2`:
```py
==> Using cached archive: var/spack/cache/_source-cache/archive/14/14cf0bcd94772194bce0f2c0e74dba187965d1cffd12d45f801c32929158579e.tar.gz
1 out of 1 hunk FAILED -- saving rejects to file source/adios2/helper/kokkos/adiosKokkos.cpp.rej
==> Patch var/spack/repos/builtin/packages/adios2/2.10-enable-rocm6.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' 'var/spack/repos/builtin/packages/adios2/2.10-enable-rocm6.patch' '-d' '.'
==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    /usr/bin/patch -s -p 1 -i var/spack/repos/builtin/packages/adios2/2.10-enable-rocm6.patch -d .
```

</details>


</details>

**Comment by bernhardkaindl** [comment]
`spack install` of `adios@2.6.0` and `adios@2.5.0` fail with this error:
```py
1 out of 2 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
==> Patch /home/bkaindl/spack/var/spack/repos/builtin/packages/adios2/2.7-fix-python-test-deps.patch failed.
```

`spack install` of `adios@2.3.0` and `adios@2.4.0` fail with this error:
```py
==> Installing adios2-2.3.1-4zewe7ojh4yqekhycsd257lud7ja5qsl [31/31]
|From 8d04bda12988ac4190780e1d75bedaf3e510d32c Mon Sep 17 00:00:00 2001
|From: Erik Schnetter <schnetter@gmail.com>
|Date: Thu, 20 May 2021 08:55:59 -0400
|Subject: [PATCH] Add missing #include <memory>
|
|Closes https://github.com/ornladios/ADIOS2/issues/2709
|---
| source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h | 1 +
| 1 file changed, 1 insertion(+)
|
|diff --git a/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h b/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h
|index 3648ded1d9571bf8a0fb869274c872f008d84234..a0c381a053d3ced7f9814b3c5baeb229871df7ef 100644
|--- a/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h
|+++ b/source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h
```

If the offending patch is disabled, `spack install adios@2.4.0` fails with this error:
```py
==> Error: InstallError: Source path ('testing/install/C') for the copy does not exist

var/spack/repos/builtin/packages/adios2/package.py:368, in setup_install_tests:
        365        install test subdirectory for use during `spack test run`.
        366        """
        367        extra_install_tests = [join_path("testing", "install", "C")]
  >>    368        cache_extra_test_sources(self, extra_install_tests)
```

If the offending patch is disabled, `spack install adios@2.3.0` fails with this error:
```py
  >> 1315    /usr/bin/ld: ../../lib/libadios2.so.2.3.1: undefined reference to `void adios2::helper::CopyEndianReverse<char>(char const*, unsigned long, char*)'
```
The errors in the range of `adios@2.3:2.6` are recipe errors that are not influenced by external factors.

These errors have existed for years (since 3 years for some) when those patches were added (in part) for newer Python versions or were not properly tested to not break old versions.

Thus, these versions are unsupported and unmaintained in `spack` but also unused, as these errors are proof that nobody cared much for them anymore since years.

I would like to propose removing those versions that have had these recipe errors for years and deprecating those that could be fixed by just fixing the version ranges for the failing patches.

Of course, I'm not against deprecating more, but I think this is the least that should be done.

I'll try to push patches that fix those issues that could be fixed, and deprecate the oldest versions.

**Review by bernhardkaindl — DISMISSED** [review]
`adios+python@2.7.1` (with `python3.8:3.11`) fail to build for me:
```py
const struct pybind11::detail::function_record' has no member named 'nargs_kw_only'
const struct pybind11::detail::function_record' has no member named 'nargs_pos_only'
const struct pybind11::detail::function_record' has no member named 'nargs'; did you mean 'args'?
error: 'uint16_t' is not a member of 'std'; did you mean 'wint_t'?
```
GitLab CI generates it, so I'll try to look at the GitLab CI logs how it does `adios+python@:2.7.1`

**Comment by vicentebolea** [comment]
@bernhardkaindl many thanks for the changes, this looks good to me!

**Review by bernhardkaindl — APPROVED** [review]
Thanks. As @vicentebolea is one of the maintainers and is active in these packages, I see this PR as maintainer-approved.

**Pull request merged**
