### PR TITLE
hwloc: explicitly disable building netloc for ~netloc

### PR DESCRIPTION
**Pull request by koysean**
@bgoglin 

When building from the `master` branch, the build script tries to build netloc even with `hwloc ~netloc`. The updated package explicitly disables netloc by adding the `--disable-netloc` configure flag when `~netloc`.

### CODE REVIEW

**Comment by haampie** [comment]
Can you replace it with 

```python
        args.extend(self.enable_or_disable("netloc")
```
like the rest?

**Comment by bgoglin** [comment]
I'm fine with the idea, I'll let you guys decide what's best on the implementation side.

**Review by bgoglin — DISMISSED** [review]

**Comment by koysean** [comment]
Thanks for the feedback - I've made the requested change.

**Review by haampie — DISMISSED** [review]

**Comment by naromero77** [comment]
One of the CI pipelines is failing. Can you take a look?

**Comment by koysean** [comment]
Merging + rerunning CI cleared the errors. @haampie could you approve this PR? Thank you!

**Review by naromero77 — APPROVED** [review]

**Comment by naromero77** [comment]
I am going to merge since several parties previously approved it.

**Pull request merged**
