### PR TITLE
ParaView: add latest release v5.11.1-RC1

### PR DESCRIPTION
**Pull request by kwryankrattiger**
:tada: :tada: :tada:

ParaView 5.11.1-RC1 is out

This PR updates the ParaView Spack package to include this new release while keeping its last final release ParaView v5.11.0 as the preferred version.

Let me know if we need to change anything else in the package.

:tada: :tada: :tada:

### CODE REVIEW

**Review by vicentebolea — DISMISSED** [review]
LGTM, sha matches tarball's sha

**Comment by alalazo** [comment]
@spackbot fix style

**Review by tldahlgren — COMMENTED** [review]
FWIW.  I am getting `807651fefe2325ae9d136aa1801e27e84984c087cbc22d8ab475d0bd4cdf1986` for the sha256.

Anyone have any ideas why?

**Comment by kwryankrattiger** [comment]
Closing this since the main release came out now #36577

**Pull request closed without merging**
