### PR TITLE
conduit package: avoid issue with subclass case

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@adamjstewart  One of the ways we use spack inherits from this package, but due to the meta-ness of spacks objects, `site_packages_dir` won't be defined in this case.  Luckily, we don't need `site_packages_dir` for this case - but we need to defend against it. Hoping this is a good comprise.

**Review by adamjstewart — APPROVED** [review]
I'm fine with this hack (feel free to merge) but I wonder if we should find a way to fix this for subclasses. @alalazo would be the expert here.

**Comment by cyrush** [comment]
@adamjstewart thanks!  The subclass snag is a long standing thing, it would be great if we could find a fix.  I don't have merge powers, can you merge for me?

**Comment by cyrush** [comment]
thanks!

**Pull request merged**
