### PR TITLE
Add latest version of Sphinx

### PR DESCRIPTION
**Pull request by adamjstewart**
Adds the latest version of Sphinx and all of its dependencies.

Notable changes in this Sphinx release: a couple new dependencies, dropped support for Python 2.6.

All packages pass their unit tests, install, and activate properly.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Tried restarting the Travis builds but that doesn't seem to work. I'll try closing and reopening. If that doesn't work, it may be necessary to rebase every PR.

**Comment by adamjstewart** [comment]
@alalazo Rebased this one on develop. We'll see if it has any better luck.

**Comment by adamjstewart** [comment]
Not sure if Travis has banned me or the queue is exceptionally long today...

**Comment by alalazo** [comment]
@adamjstewart Just a long queue. If you were banned you wouldn't have a job in the queue at all.

**Comment by adamjstewart** [comment]
It's working!

**Pull request merged**
