### PR TITLE
Update CGNS version

### PR DESCRIPTION
**Pull request by MicK7**
Add CGNS 4.3.0 version

### CODE REVIEW

**Comment by MicK7** [comment]
@tgamblin 
@adamjstewart 
please review

**Review by tgamblin — DISMISSED** [review]

**Comment by MicK7** [comment]
The CI seems to be stuck...

**Comment by MicK7** [comment]
@alalazo can you check why the CI is not working ?

**Comment by MicK7** [comment]
@tgamblin could you approve again ?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
