### PR TITLE
[dd4hep]: add variant lcio

### PR DESCRIPTION
**Pull request by andresailer**
This adds a variant for dd4hep to build the LCIO input and output modules for the simulation parts.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@vvolkl @drbenmorgan can you review this?

**Comment by vvolkl** [comment]
I'm just checking that dd4hep works also with `lcio~rootdict` Otherwise, looks good to me!

**Review by vvolkl — APPROVED** [review]
Looks good!

**Comment by drbenmorgan** [comment]
Yep, looks good to me as well!

**Review by drbenmorgan — APPROVED** [review]

**Pull request merged**
