### PR TITLE
patch: add workdir option

### PR DESCRIPTION
**Pull request by junghans**
This was part of #5459, but I will break it out to make it easier to review!

### CODE REVIEW

**Comment by scheibelp** [comment]
I'll try to look at this this week. My only thought at the moment is that `workdir` is a bit terse. I'd prefer `working_dir`.

**Comment by alalazo** [comment]
@junghans I restarted the CI tests (spurious `svn` failure on python 2.7?). Let's see how they go this time

**Comment by junghans** [comment]
@tgamblin

**Comment by junghans** [comment]
@tgamblin @scheibelp I found a slightly more elegant way to do it!

**Comment by junghans** [comment]
Rebased, @tgamblin I am bit confused by the new patch test, can you help adding a test for `working_dir`.

**Comment by junghans** [comment]
@tgamblin, @scheibelp, I think from a test perspective `working_dir='.'` is as good as any other directory.

**Comment by scheibelp** [comment]
> I think from a test perspective working_dir='.' is as good as any other directory.

The way you coded it, I suppose I could agree. Let me think it over.

**Comment by scheibelp** [comment]
Wait what changed that led to a rebase?

**Comment by junghans** [comment]
I had to rebase after #5476 got merged to solve the conflicts.

**Comment by junghans** [comment]
@tgamblin: Done!

**Pull request merged**
