### PR TITLE
Use the `maintainers` directive in all packages

### PR DESCRIPTION
**Pull request by alalazo**
Following #35083

Used a regex to convert all the maintainers lists into directives. @adamjstewart

### CODE REVIEW

**Comment by adamjstewart** [comment]
Still missing a few:
```console
$ spack pkg grep 'maintainers ='
/Users/Adam/spack/var/spack/repos/builtin/packages/frontistr/package.py:    maintainers = ["hiroshi.okuda", "kgoto", "morita", "inagaki", "michioga"]
/Users/Adam/spack/var/spack/repos/builtin/packages/genie/package.py:    maintainers = [
/Users/Adam/spack/var/spack/repos/builtin/packages/py-pennylane/package.py:    maintainers = PythonPackage.maintainers + ["marcodelapierre"]
/Users/Adam/spack/var/spack/repos/builtin/packages/py-strawberryfields/package.py:    maintainers = PythonPackage.maintainers + ["marcodelapierre"]
/Users/Adam/spack/var/spack/repos/builtin/packages/py-xtb/package.py:    maintainers = [
/Users/Adam/spack/var/spack/repos/builtin/packages/revocap-refiner/package.py:    maintainers = ["k-tokunaga", "kgoto", "tuna" "inagaki.kazuhisa"]
```

**Comment by adamjstewart** [comment]
Ping @alalazo, we should try to push this through as quickly as possible

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@adamjstewart

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
