### PR TITLE
xfce4: new packages

### PR DESCRIPTION
**Pull request by teaguesterling**
This add the core packages to run the XFCE4 desktop. 

It depends on a few other libraries PRs to address dependencies in upstream packages: 
 * #44639
 * #44641
 * #44642 
 * #44643
 * #44645 

It adds the following packages:
 * libxfce4util
 * xfconf
 * libxfce4ui
 * garcon
 * exo
 * xfec4-settings
 * thunar
 * xfce4-panel
 * xfce4-session
 * xfdesktop
 * xfwm4
 * xfce4-appfinder
 * thunar-volmon

It may make sense to make a virtual(?) package that installs all of these at the same version, say `xfce4-core`, but I don't know if that'd be the best way to go about it.

Inspired by the Spack OS discussions, this is part of a broader crazy experiment to see if I could get a desktop environment running from Spack. This was the first step, but getting X built and a VNC server would follow this.

Update: Confirmed that this works from within a spack-built VNC server!

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@teaguesterling I looked at the PR description and merged the missing two PRs:
> It depends on a few other libraries PRs to address dependencies in upstream packages:
>
> https://github.com/spack/spack/pull/44639
> https://github.com/spack/spack/pull/44641

But now I see that those have been merged into this PR, and it now conflicts with the merges.

Can you update this PR to no longer add `libgudev` and `libwnck` as I merged them already?

**Comment by teaguesterling** [comment]
Will do! Should have this ready to go soon. Thank you for the review!

**Review by bernhardkaindl — DISMISSED** [review]
> Will do! Should have this ready to go soon. Thank you for the review!

ACK, Please mention me with @bernhardkaindl in a comment when you have an update and re-request my review next by clicking on the reload symbol to the next to of my GitHub handle and the checkmark from me in the list of reviewers in the top-right corner of the PR to alert me when the PR is ready for merge.

In case you don't see a response from me after some days, please try mentioning other maintainers that merged other PRs to-develop recently.

**Comment by teaguesterling** [comment]
@bernhardkaindl, this has been cleaned up and should be ready to go now.

**Review by bernhardkaindl — APPROVED** [review]
I was able to build the xfce4 packages on Ubuntu 22.04, well done! 👍 🥇

**Pull request merged**
