### PR TITLE
Add pic and shared variants to freetype package

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds pic and shared variants to the freetype package. These changes support NOAA/National Weather Service R&D and operational forecasting applications.

### CODE REVIEW

**Comment by michaelkuhn** [comment]
@spackbot fix style

**Review by michaelkuhn — CHANGES_REQUESTED** [review]
This makes the build fail for me when using the Autotools build system using the default configuration (`+shared~pic`):
```
/usr/bin/ld: $SPACK_STAGE/spack-stage-freetype-2.11.1-cgjelwgcwsbzgrdqwq7lbuy7ter4einl/spack-src/objs/.libs/ftsystem.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
```

**Comment by AlexanderRichert-NOAA** [comment]
I'll take a look, I may set the wrong default value.

**Comment by AlexanderRichert-NOAA** [comment]
@michaelkuhn it looks like PIC is on by default in autotools but not cmake... If you install with `build_system=cmake` with the current package.py, would I be right in assuming it also fails?

**Comment by michaelkuhn** [comment]
> it looks like PIC is on by default in autotools but not cmake... If you install with `build_system=cmake` with the current package.py, would I be right in assuming it also fails?

Strangely, `freetype+shared~pic build_system=cmake` does build/install fine. At least for Autotools, we should probably add a conflict: `conflicts("~pic", when="+shared")` (or `requires("+pic", when="+shared")`)

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Pull request merged**
