### PR TITLE
smartdenovo: fix compile error for debian

### PR DESCRIPTION
**Pull request by darmac**
`smartdenovo` compile fail on `Debian`.
The issue is the same as https://github.com/ruanjue/smartdenovo/issues/35
And someone give a fix suggestion on https://github.com/ruanjue/smartdenovo/issues/22

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/smartdenovo/package.py:21: [E128] continuation line under-indented for visual indent
var/spack/repos/builtin/packages/smartdenovo/package.py:24: [E128] continuation line under-indented for visual indent
```

**Comment by darmac** [comment]
> Flake8:
> 
> ```
> var/spack/repos/builtin/packages/smartdenovo/package.py:21: [E128] continuation line under-indented for visual indent
> var/spack/repos/builtin/packages/smartdenovo/package.py:24: [E128] continuation line under-indented for visual indent
> ```

How to resolve this issue? I can't reproduce that log by typing `spack flake8`

**Comment by adamjstewart** [comment]
Just put them all on the same line or indent to the same level as the opening parentheses. You may need to install a newer version of flake8 to reproduce locally.

**Comment by darmac** [comment]
> Just put them all on the same line or indent to the same level as the opening parentheses. You may need to install a newer version of flake8 to reproduce locally.

Fixed this issue in https://github.com/spack/spack/pull/17435/commits/568baf27ccaa7c234c51fa862f02b8988f0e803f

**Review by alalazo — APPROVED** [review]

**Pull request merged**
