### PR TITLE
amrex: use right cmake_args for @develop; depends_on(hypre) for link

### PR DESCRIPTION
**Pull request by eugeneswalker**
* Ensure `amrex@develop` uses the right `cmake_args` 
* Adds explicit `depends_on` `hypre` for `amrex+hypre` 
* Adds explicit `depends_on` `petsc` for `amrex+petsc` 

@mic84 @asalmgren @eschnett

### CODE REVIEW

**Comment by tldahlgren** [comment]
@mic84 Would you care to review this PR?

**Comment by mic84** [comment]
It looks good to me! Thank you!

**Review by tldahlgren — APPROVED** [review]
Approval contingent on all required checks passing.

**Comment by tldahlgren** [comment]
> It looks good to me! Thank you!

Thanks for reviewing this PR!

**Pull request merged**
