### PR TITLE
Fix #254: libtool & distutils want certain compiler names.

### LINKED ISSUE #254: Issues building with libtool
From @kiwifb:

So I was doing some experiments with the IBM xl compiler so I could see if there was any issues.
And it failed miserably building mpich-3.1.4 as part of a chain of dependencies.
I can build mpich-3.1.4 with xlc-13.1/xlf-15.1 fine on that machine outside of spack so it 
warranted further exploration.

The problem is with the generated libtool file. A diff of the config.lt files produced is very
enlightening:
```
frb15@p2n14-c /tmp/spack-stage/spack-stage-5B2T0e/mpich-3.1.4 :diff -u config.lt /hpc/scratch/frb15/work/compilers/test/mpich-3.1.4/build_xl13/config.lt
--- config.lt   2015-12-17 10:47:17.000000000 +1300
+++ /hpc/scratch/frb15/work/compilers/test/mpich-3.1.4/build_xl13/config.lt     2015-12-17 10:37:25.228602129 +1300
@@ -483,9 +483,9 @@
 old_postuninstall_cmds=''
 old_archive_cmds='$AR $AR_FLAGS $oldlib$oldobjs~$RANLIB $tool_oldlib'
 lock_old_archive_extraction='no'
-CC='/hpc/scratch/frb15/git/spack-2015-12-14/lib/spack/env/cc'
+CC='xlc_r'
 CFLAGS='   -O2'
-compiler='/hpc/scratch/frb15/git/spack-2015-12-14/lib/spack/env/f77'
+compiler='xlf_r'
 GCC=''
 lt_cv_sys_global_symbol_pipe='sed -n -e '\''s/^.*[      ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[         ][      ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p'\'' | sed '\''/ __gnu_lto/d'\'''
 lt_cv_sys_global_symbol_to_cdecl='sed -n -e '\''s/^T .* \(.*\)$/extern int \1();/p'\'' -e '\''s/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p'\'''
@@ -499,9 +499,9 @@
 objdir='.libs'
 MAGIC_CMD='file'
 lt_prog_compiler_no_builtin_flag=''
-lt_prog_compiler_pic=' -DPIC'
-lt_prog_compiler_wl=''
-lt_prog_compiler_static=''
+lt_prog_compiler_pic=' -qpic -DPIC'
+lt_prog_compiler_wl='-Wl,'
+lt_prog_compiler_static='-qstaticlink'
 lt_cv_prog_compiler_c_o='yes'
 need_locks='no'
 MANIFEST_TOOL=':'
```

There is more but it is enough for the sake of the argument. The build failed because the libtool
variable `wl` was set to nothing instead of "-Wl,". Failing that other bits would have caused failures
later on.

Why does it happen? The libtool code to set the various variables examine the base name of the
compiler to work things (from configure):
```
    linux* | k*bsd*-gnu | kopensolaris*-gnu | gnu*)
      case $cc_basename in
      # old Intel for x86_64, which still supported -KPIC.
      ecc*)
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='-KPIC'
lt_prog_compiler_static='-static'
        ;;
      # icc used to be incompatible with GCC.
      # ICC 10 doesn't accept -KPIC any more.
      icc* | ifort*)
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='-fPIC'
lt_prog_compiler_static='-static'
        ;;
      # Lahey Fortran 8.1.
      lf95*)
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='--shared'
lt_prog_compiler_static='--static'
;;
      nagfor*)
# NAG Fortran compiler
lt_prog_compiler_wl='-Wl,-Wl,,'
lt_prog_compiler_pic='-PIC'
lt_prog_compiler_static='-Bstatic'
;;
      tcc*)
# Fabrice Bellard et al's Tiny C Compiler
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='-fPIC'
lt_prog_compiler_static='-static'
;;
      pgcc* | pgf77* | pgf90* | pgf95* | pgfortran*)
        # Portland Group compilers (*not* the Pentium gcc compiler,
# which looks to be a dead project)
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='-fpic'
lt_prog_compiler_static='-Bstatic'
        ;;
      ccc*)
        lt_prog_compiler_wl='-Wl,'
        # All Alpha code is PIC.
        lt_prog_compiler_static='-non_shared'
        ;;
      xl* | bgxl* | bgf* | mpixl*)
# IBM XL C 8.0/Fortran 10.1, 11.1 on PPC and BlueGene
lt_prog_compiler_wl='-Wl,'
lt_prog_compiler_pic='-qpic'
lt_prog_compiler_static='-qstaticlink'
;;
      *)
case `$CC -V 2>&1 | sed 5q` in
*Sun\ Ceres\ Fortran* | *Sun*Fortran*\ [1-7].* | *Sun*Fortran*\ 8.[0-3]*)
 # Sun Fortran 8.3 passes all unrecognized flags to the linker
 lt_prog_compiler_pic='-KPIC'
 lt_prog_compiler_static='-Bstatic'
 lt_prog_compiler_wl=''
 ;;
*Sun\ F* | *Sun*Fortran*)
 lt_prog_compiler_pic='-KPIC'
 lt_prog_compiler_static='-Bstatic'
 lt_prog_compiler_wl='-Qoption ld '
 ;;
*Sun\ C*)
 # Sun C 5.9
 lt_prog_compiler_pic='-KPIC'
 lt_prog_compiler_static='-Bstatic'
 lt_prog_compiler_wl='-Wl,'
 ;;
        *Intel*\ [CF]*Compiler*)
 lt_prog_compiler_wl='-Wl,'
 lt_prog_compiler_pic='-fPIC'
 lt_prog_compiler_static='-static'
 ;;
*Portland\ Group*)
 lt_prog_compiler_wl='-Wl,'
 lt_prog_compiler_pic='-fpic'
 lt_prog_compiler_static='-Bstatic'
 ;;
esac
;;
      esac
      ;;
```
And the problem here is that `libtool/configure` never figured out that the wrapper
was the XL compiler. It always stayed at `/hpc/scratch/frb15/git/spack-2015-12-14/lib/spack/env/cc`
and wasn't picked as any of the option and the values are left to the default
which is blank for most things.

### PR DESCRIPTION
**Pull request by tgamblin**
@kiwifb: How does this look?  I was able to build XL, gcc, and Intel versions of mpich with it.

@lee218llnl: can you test this with some of the problematic `distutils` builds?  I think this should fix the issues you were seeing before because compilers will now have detectable names.  You can probably remove your prior patch.

See #254 and [this thread](https://groups.google.com/forum/#!topic/spack/spygC81rbc8) for details.

This changes the compiler wrappers so that they are called by the same
name as the wrapped compiler.  Many builds make assumptions about
compiler names, and we need the spack compilers to be recognizable so
that build systems will get their flags right.

This adds per-compiler subdirectories to lib/spack/spack/env directory
that contain symlinks to cc for the C, C++, F77, and F90
compilers. The build now sets CC, CXX, F77, and F90 to point to these
links instead of to the generically named cc, c++, f77, and f90
wrappers.

### CODE REVIEW

**Comment by kiwifb** [comment]
I'll have a close look in the morning.

**Comment by lee218llnl** [comment]
@tgamblin I could be forgetting, but I don't recall having distutils issues with compiler names. I'm also not sure which patch you are referring to.

**Comment by tgamblin** [comment]
@lee218llnl: here's the commit: bd1cd83d7148
In particular I think the gfortran -> fc patch there is probably not necessary anymore. It'll still work as-is, but you could take it out to avoid breaking if future numpy releases change the patched file.  Also I bet other distutils builds w/other compilers benefit from the new compiler wrapper names.

**Comment by lee218llnl** [comment]
@tgamblin, gotcha. This looks good from the numpy perspective. Once this is merged, I will push the numpy package update. Good work and thanks!

**Comment by tgamblin** [comment]
Thanks!  I'll merge it once François verifies it works ok for him.

**Comment by kiwifb** [comment]
Works OK, it has the same "defects" as an out of spack install, no more no less.

**Comment by tgamblin** [comment]
@kiwifb: Are there some more flags you want on the mpich build for xl?  Which "defects"?

**Comment by kiwifb** [comment]
Nope, no extra flags. Like I said it does the same thing out of spack:
```
ldd -r libmpi.so
	linux-vdso64.so.1 =>  (0x0000040000000000)
	librt.so.1 => /lib64/power7/librt.so.1 (0x0000040000440000)
	libgpfs.so => /usr/lib/libgpfs.so (0x0000040000460000)
	libpthread.so.0 => /lib64/power7/libpthread.so.0 (0x0000040000490000)
	libc.so.6 => /lib64/power7/libc.so.6 (0x00000400004d0000)
	/lib64/ld64.so.1 (0x000000003e6c0000)
undefined symbol: __gcc_qmul	(./libmpi.so)
undefined symbol: __gcc_qadd	(./libmpi.so)
undefined symbol: __gcc_qsub	(./libmpi.so)
```
I don't know if it is a `libtool` problem or a `xl` configuration problem. Both the `C` and `FORTRAN` libraries miss those symbols which are found in `libgcc_s.so`, the `C++` library, funnily enough is OK, probably pulled by `libstdc++`. Works ok to build executables, so it's no big deal, just something I don't like.

**Comment by tgamblin** [comment]
@kiwifb: ok -- that's not a big one so I'll merge this.  I could see later if we could patch something to get around that, but if it builds executables ok I'm inclined to leave it, as every patch is another thing that can break when a new version comes out :)

**Pull request merged**
