### PR TITLE
fetch: add options to fetch missing or all deps

### PR DESCRIPTION
**Pull request by trws**
Small additions to fetch to make it easier to fetch all files necessary for a
build on a system without network connectivity.

### CODE REVIEW

**Comment by trws** [comment]
The `mirror` command now has this capability also.

**Comment by tgamblin** [comment]
Thanks!

@fpruvost: does this fix your issues with mirror?  It looks like Tom has fixed some bugs in this PR.

**Comment by fpruvost** [comment]
@tgamblin: Hi,

no sorry, this does not fix the bug concerning fetching scm (git, svn) tarball from a local mirror.
I have tried with the last state of the develop branch 37db5928b7d77ea6ee7cb398ff7595956031c790.
It still fails:
    $ spack purge
    $ spack -d fetch libmonitor
    $ ==> Trying to fetch from file:///home/pruvost/work/spack-mirrors/updated//libmonitor/libmonitor-20130218.tar.gz
    $ ==> /usr/bin/curl -O -f -D - -L file:///home/pruvost/work/spack-mirrors/updated//libmonitor/libmonitor-20130218.tar.gz -#
    $ ######################################################################## 100,0%
    $ ==> Fetching from file:///home/pruvost/work/spack-mirrors/updated//libmonitor/libmonitor-20130218.tar.gz failed.
    $ ==> Trying to check out svn repository: http://libmonitor.googlecode.com/svn/trunk/

**Comment by trws** [comment]
This is actually the same problem I was having that spawned issue #228, just in this case it's svn rather than git.  The mirror tarball gets created as appropriate, but fetching from the mirror fails.  I seem to recall you saying you thought you had put a patch in for that somewhere, right @tgamblin?

**Pull request merged**
