### PR TITLE
[py-aiosignal] Added new py-aiosignal package

### PR DESCRIPTION
**Pull request by mdorier**
Adds the py-aiosignal package.
Requires the following PR to be merged first: https://github.com/spack/spack/pull/28137

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]

**Comment by mdorier** [comment]
What's the command to restart the tests? I believe this PR can be completed now that py-frozenlist is merged.

**Comment by adamjstewart** [comment]
To re-run the GitLab CI tests, you can use:

@spackbot run pipeline

There's no spackbot command to re-run the GitHub Actions tests, but there are a few other ways:

1. Click "Re-run all jobs" in the "Details" page for the test (I think this requires maintainer privileges?)
2. Close and reopen the PR
3. Add a new commit or rebase

1 only runs the tests you ask for which is nice, but sometimes doesn't update the rest of Spack to upstream. I just did 1 for you, but if that doesn't work, try 2.

**Comment by mdorier** [comment]
I had to rebase it onto develop to get the py-frozenlist package; now all the tests seem to be passing :-)

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
Closing and reopening should also work.

**Pull request merged**
