### PR TITLE
Packages/r ergm

### PR DESCRIPTION
**Pull request by tmerrick1**
This is an integrated set of tools to analyze and simulate networks based on exponential-family random graph models.

### CODE REVIEW

**Comment by tmerrick1** [comment]
There may be a problem, shouldn't the depends_on be 'run' for all of these routines?

**Comment by adamjstewart** [comment]
Ah, yes, good catch. They should all be `type=('build', 'run')`.

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/r-coda/package.py:40: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:39: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:40: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:41: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:42: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:43: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:44: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:45: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-ergm/package.py:46: [E231] missing whitespace after ','
var/spack/repos/builtin/packages/r-robustbase/package.py:40: [E231] missing whitespace after ','
```

**Comment by tmerrick1** [comment]
All flake8 errors fixed.

**Pull request merged**
