### PR TITLE
Blackened filet of spack (apply black formatter and make it default on in `spack style`)

### PR DESCRIPTION
**Pull request by trws**
Warning, this PR may make your browser very, very unhappy. Blackens everything, and makes it default on without removing the `--black` option, to give us a deprecation period. Highly recommend using cli tools to manage this PR.

### CODE REVIEW

**Comment by haampie** [comment]
externals should be excluded

**Comment by tgamblin** [comment]
Closing as this is a dupe of https://github.com/spack/spack/pull/24718 and the discussion is there.

The plan is to merge that once we get changes into Spackbot that will blacken a PR automatically, then `spack style --fix` should only be blackening files that are changed (like we do with other tools).

**Comment by trws** [comment]
`spack style` already only applies to modified files unless `-a` is specified. The tweak here just adds the negative version of the option and makes checking format with black default on.  If you'd rather, feel free to cherry pick a05 or the changes in it to the other one.

**Comment by tgamblin** [comment]
Yeah -- lemme update the other one and cherry-pick your changes.

**Pull request closed without merging**
