### PR TITLE
py-torchmetrics: add v0.11.1

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/Lightning-AI/metrics/releases/tag/v0.11.1

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Two ML stacks are failing to generate due to purportedly broken `py-torchvision`.

**Comment by adamjstewart** [comment]
Reported this on slack, it's a false positive from the temporary GitHub checksum change. This PR is dead in the water until someone removes torchvision from the broken spec list.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
