### PR TITLE
add MKL support

### PR DESCRIPTION
**Pull request by mcuma**
For @alalazo and @mtmiller. New pull request to add MKL support for Octave. 

Sorry for previous confusion, I was comparing the R package not Octave.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot help

**Comment by alalazo** [comment]
@mcuma can you fix style issues (import order)?

**Comment by mcuma** [comment]
Done, thanks @alalazo for the pointer on the style - I did not realize the imports need to be alphabetically ordered.

**Review by alalazo — APPROVED** [review]

**Comment by mtmiller** [comment]
Thanks for persisting and adding this feature @mcuma! And thanks for reviewing and merging @alalazo

**Pull request merged**
