### PR TITLE
expat: Deprecate 2.4.6

### PR DESCRIPTION
**Pull request by hartwork**
Alternative to #29871 by Expat upstream

Related discussion at https://github.com/spack/spack/pull/29100#issuecomment-1088056911

CC @haampie @tldahlgren

### CODE REVIEW

**Review by haampie — DISMISSED** [review]

**Comment by haampie** [comment]
some day spack has to be smart about ABI compat... zlib 1.2.11 -> 1.2.12, rebuild the world, expat 2.4.6 -> 2.4.7, rebuild the world :D

**Review by tldahlgren — APPROVED** [review]
FWIW. Confirmed the (existing :grin:) sha256.

Deferring merge decision to `haampie` since I have not been participating in this discussion.

**Comment by tldahlgren** [comment]
Note the #1 reason in the docs for deprecating a packages is security vulnerabilities.  See the list at https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@haampie Feel free to merge if you are fine with this, or to request changes if you are not.

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@hartwork you might want to follow https://github.com/spack/spack/pull/29973#issuecomment-1093125584 :upside_down_face: then you get notified when people change your package.

**Comment by hartwork** [comment]
> @hartwork you might want to follow [#29973 (comment)](https://github.com/spack/spack/pull/29973#issuecomment-1093125584) upside_down_face then you get notified when people change your package.

@haampie I've been reluctant to add myself because I am not using Spack myself currently and because maintaining Expat packaging at multiple places does not scale well on me while I'm already active with Expat upstream and in other projects and packaging for distro Gentoo. I made the same choice with Expat packaging in NixOS. My Expat updating initiative including Spack and others was driven by user security in particular. I would be more happy to see someone else take the package as a regular maintainer and then team up with with them, and not be the main driver.

**Pull request merged**
