### PR TITLE
Trilinos: fix ^hdf5~mpi

### PR DESCRIPTION
**Pull request by sethrj**
Trilinos epetraext HDF5 output requires HDF5 parallel. Require parallel HDF5 when building `trilinos+hdf5+mpi`.

```
[ 70%] Building CXX object
packages/epetraext/src/CMakeFiles/epetraext.dir/inout/EpetraExt_HDF5.cpp.o
cd
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/epetraext/src
&& /projects/spack/opt/spack/gcc-8.3.0/openmpi/qmjv3wp/bin/mpic++
-Depetraext_EXPORTS
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/epetraext/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/transform
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/coloring
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/model_evaluator
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/block
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/restrict
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/triutils/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/triutils/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/epetra/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetra/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/teuchos/kokkoscomm/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/kokkoscomm/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/teuchos/kokkoscompat/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/kokkoscompat/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/parameterlist/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/parser/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/teuchos/core/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/core/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/kokkos/core/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/kokkos/core/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/comm/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/remainder/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-build/packages/teuchos/remainder/src
-I/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/teuchos/numerics/src
-I/projects/spack/opt/spack/gcc-8.3.0/hdf5/p2mpta5/include  -std=c++11
-O2 -g -DNDEBUG -fPIC   -o
CMakeFiles/epetraext.dir/inout/EpetraExt_HDF5.cpp.o -c
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:
In member function 'void EpetraExt::HDF5::Create(std::__cxx11::string)':
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:347:5:
error: 'H5Pset_fapl_mpio' was not declared in this scope
     H5Pset_fapl_mpio(plist_id_, mpiComm, MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:347:5:
note: suggested alternative: 'H5Pset_fapl_stdio'
     H5Pset_fapl_mpio(plist_id_, mpiComm, MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
     H5Pset_fapl_stdio
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:
In member function 'void EpetraExt::HDF5::Open(std::__cxx11::string,
int)':
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:382:5:
error: 'H5Pset_fapl_mpio' was not declared in this scope
     H5Pset_fapl_mpio(plist_id_, MPI_COMM_WORLD, MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:382:5:
note: suggested alternative: 'H5Pset_fapl_stdio'
     H5Pset_fapl_mpio(plist_id_, MPI_COMM_WORLD, MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
     H5Pset_fapl_stdio
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:384:5:
error: 'H5Pset_fapl_mpio' was not declared in this scope
     H5Pset_fapl_mpio(plist_id_, MpiComm->Comm(), MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:384:5:
note: suggested alternative: 'H5Pset_fapl_stdio'
     H5Pset_fapl_mpio(plist_id_, MpiComm->Comm(), MPI_INFO_NULL);
     ^~~~~~~~~~~~~~~~
     H5Pset_fapl_stdio
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:
In member function 'void EpetraExt::HDF5::Write(const string&, const
Epetra_MultiVector&, bool)':
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1065:3:
error: 'H5Pset_dxpl_mpio' was not declared in this scope
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1065:3:
note: suggested alternative: 'H5Pset_fapl_stdio'
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
   H5Pset_fapl_stdio
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:
In member function 'void EpetraExt::HDF5::Read(const string&,
Epetra_MultiVector*&, bool, const int&)':
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1159:3:
error: 'H5Pset_dxpl_mpio' was not declared in this scope
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1159:3:
note: suggested alternative: 'H5Pset_fapl_stdio'
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
   H5Pset_fapl_stdio
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:
In member function 'void EpetraExt::HDF5::Write(const string&, const
string&, int, int, hid_t, const void*)':
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1704:3:
error: 'H5Pset_dxpl_mpio' was not declared in this scope
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
/tmp/s3j/spack-stage/spack-stage-trilinos-12.18.1-rrecf537l7r4or3ngdprhqzim7tnqjzk/spack-src/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1704:3:
note: suggested alternative: 'H5Pset_fapl_stdio'
   H5Pset_dxpl_mpio(plist_id_, H5FD_MPIO_COLLECTIVE);
   ^~~~~~~~~~~~~~~~
   H5Pset_fapl_stdio
```

### CODE REVIEW

**Comment by alalazo** [comment]
@keitat

**Review by aprokop — COMMENTED** [review]
Why did you decide to silently disable it in the build, rather than adding a conflict of `+epetraext` with `+hdf5~mpi`?

**Comment by sethrj** [comment]
@aprokop Yeah, good question. In our SCALE builds (tribits project, uses Trilinos) we've always relied upon disabling epetra ext HDF5. From [the epetraext docs](https://docs.trilinos.org/dev/packages/epetraext/doc/html/index.html) it looks like HDF5 output is only a very small component of the epetraext capabilities.

I'll try disabling epetraext and see if our code is happy with the result 😬

**Comment by sethrj** [comment]
Nope, we use `EpetraExt::RowMatrixToMatrixMarketFile`. It looks from the CMakeCache file like EpetraExt has a whole grab bag of other options alongside it. I'm conflicted about this one, too. The best solution obviously would be to tweak EpetraExt so that it uses the `H5_HAVE_PARALLEL` macro rather than `HAVE_MPI`.

**Comment by aprokop** [comment]
Probably need to ping somebody from Trilinos team about it. I extract myself from the issue, and fine either way.

**Comment by sethrj** [comment]
@keitat , in e90c229dab42760f9fcf6f72267b35d054dbf606 I removed the requirement on `^hdf5+mpi` when building `trilinos+hdf5+mpi` because I'd successfully built trilinos with serial HDF5. However, that only had worked because I disabled `EpetraExt_USE_HDF5`. Rather than disabling capability based on the trilinos dependencies, I'm restoring the `+hdf5+mpi` requirement. Could you please review? Thanks!

**Comment by keitat** [comment]
@sethrj   @jwillenbring 
I am verifying the fix on generic Linux machine. Should I try it with NERSC or other DOE flagship machines?

**Comment by sethrj** [comment]
I don't think it's necessary -- `+mpi ^hdf5~mpi` has probably never been deployed except on the machines that I use.

**Comment by keitat** [comment]
Does the change of HDF5 setting impact the DTK in xSDK?

**Comment by sethrj** [comment]
Nope, it shouldn't affect xSDK at all.

**Comment by keitat** [comment]
I confirmed that I am able to build with gcc-8.2.

**Comment by keitat** [comment]
Got error message when building xSDK.  Yes, phist wants long_long.
`phist requires trilinos variant gotype=long_long, but spec asked for gotype=int`

**Comment by sethrj** [comment]
@keitat It sounds like this patch builds for you, and the "long long" issues are unrelated to this patch. Can you please approve so this can be merged? Thanks!

**Review by keitat — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Comment by sethrj** [comment]
Thanks!

**Pull request merged**
