### PR TITLE
Use PyYAML in Travis to increase build speeds

### PR DESCRIPTION
**Pull request by adamjstewart**
This is a follow-up to the discussion in #2010. @alalazo suggested using PyYAML/cYAML in the Travis environment if there's a chance it will speed up CI tests.

I'm not sure exactly which combination of `pip install pyyaml` and/or `apt-get install libyaml-dev` will get us what we want, so I'll add them one at a time and record the speeds we get.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Looks like the first results are in. I found a [useful post](http://stackoverflow.com/a/27744056/5828163) on how to speed up yaml parsing. They recommend installing `pyyaml`, `libyaml`, and `yaml-cpp-dev`, so I'll try each of those at a time.

**Comment by alalazo** [comment]
@adamjstewart It was not to speed-up tests, but to check that nothing changes if we choose one or the other...

**Comment by adamjstewart** [comment]
@alalazo Oh. Well... is there even a way to install dependencies for some tests but not others?

**Comment by tgamblin** [comment]
@adamjstewart: I think @alalazo is suggesting we add another build environment variable (see `env` at top).  That's how you multiply out the build matrix.  I think we want to run 2 versions of each unit test -- one with yaml and one without.  We probably do NOT need to run docs or flake8 with different YAMLs.

**Comment by alalazo** [comment]
@tgamblin Exactly that! :smile:

**Comment by adamjstewart** [comment]
Hmm, should we really (almost) double the length of Travis runs because we want to make sure there isn't a bug in PyYAML? It sounds like we're using PyYAML regardless, but sometimes we are using an optimized version that relies on the system libyaml library. Either way, it wouldn't be our fault. That's a lot of testing to make sure there aren't any bugs in PyYAML.

**Comment by tgamblin** [comment]
They can run in parallel if they're in the environment.  Personally I don't see much of a problem.  If we never see breakage due to this after a month or so we can take this out.

**Comment by tgamblin** [comment]
@adamjstewart: I don't think `yaml-cpp-dev` is actually used by PyYAML.  I think PyYAML will only delegate to LibYAML, and then only if it's built with `libyaml` support.

**Comment by adamjstewart** [comment]
Hmm, I'm not sure how to do that withing Travis then.

I'm going to fix up the `py-pyyaml` package to depend on `libyaml`.

**Comment by tgamblin** [comment]
@adamjstewart: If you install `libyaml` with `apt-get` before you `pip install pyyaml` then `pyyaml`'s `setup.py` will pick it up.

**Comment by tgamblin** [comment]
@adamjstewart: I already fixed the py-pyyaml package locally and I'll have it in once I fix a bug from #1992 (which is actually related to #2015).

**Comment by adamjstewart** [comment]
Well, it looks like none of my changes decreased build times in Travis, so I'm going to close this PR. We probably don't have a big enough package stack just from testing to make a difference.

I'm not particularly keen on the idea of adding another dimension to Travis to run with libyaml and without, but if someone wants to open a new PR to make that change I'll voice my opinions there.

**Pull request closed without merging**
