### PR TITLE
Add py-sncosmo package

### PR DESCRIPTION
**Pull request by adamjstewart**
Everything installs and activates just fine. I'm getting errors when importing sncosmo at the moment, but I'll work on those on Monday.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Alright, so the sncosmo developers figured out [what my problem was](https://github.com/sncosmo/sncosmo/issues/137). It turns out that the Python package prevents symlinking of the `py-astropy-1.1.2-3uz5u5vmbmvratieizci3uvy45uxcipq/lib/python2.7/site-packages/astropy-1.1.2-py2.7-linux-x86_64.egg/astropy/coordinates/sites.py` file: [Python package](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py#L174).

@tgamblin, @alalazo: Any thoughts on the best way to deal with this? I could remove the asterisk so that sites.py gets symlinked but site.py doesn't. Why do we even prevent symlinking the same file multiple times? It seems like we could just always symlink and ignore errors if the file already exists.

Btw, we really need to be able to recursively deactivate extensions because it took me half an hour to deactivate and reactivate py-setuptools.

**Comment by adamjstewart** [comment]
Alright, I think I have everything working now. In the Python package, I made sure that all ignore files were more explicit. Specifically, it now only ignores files in bin or in site-packages. That way, packages like py-sncosmo can contain files like sites.py in their egg. With these changes, I was able to activate all 32 Python extensions I had installed. Thanks go to @mathstuf in #1054!

@lee218llnl Can you double check my Python package changes? I noticed you were the last one to play around with the `site[^/]*\.pyc?` ignore.

**Comment by lee218llnl** [comment]
@adamjstewart The python package ignoring regexs look good to me.

**Comment by adamjstewart** [comment]
For some reason when I try to build py-scipy, it complains that it can't find openblas. Not sure which of my flake8 changes broke that.

**Comment by adamjstewart** [comment]
@lee218llnl Yeah I just tried building Python 3 and noticed the __pycache__ thing

**Comment by adamjstewart** [comment]
I definitely broke something in 13f3eb42d4e3d4b16f02b3200ccdad044a8696ba. If anyone can look at it with a fresh set of eyes and figure out where I went wrong, that would be appreciated.

**Comment by adamjstewart** [comment]
I removed all of my flake8 changes because they broke the py-scipy installation. I'll go more slowly this time and make sure everything still works before committing.

**Comment by adamjstewart** [comment]
Alright, everything should be good to go now. I tested it by installing py-scipy for both Python 2 and 3. Everything activates correctly.

@tgamblin: It appears there are multiple PRs out right now that touch the Python package. The sooner we get this merged, the fewer people need to make their own Flake8 changes.

**Pull request merged**
