### PR TITLE
[lerc] added version 4.0.0

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Comment by qwertos** [comment]
@spackbot fix style

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256, rest LGTM.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by tldahlgren** [comment]
Oops.  Suspect the PR was created without allowing maintainers to edit.

The style checks will have to be manually fixed and pushed.

**Comment by tldahlgren** [comment]
@adamjstewart You originally appeared in the reviewer list so I'm adding you back in case you want to comment.

**Review by tldahlgren — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]
Builds for me.

**Pull request merged**
