### PR TITLE
lerc: add libs property

### LINKED ISSUE #31680: Installation issue: gdal+lerc
### Steps to reproduce the issue

```console
spack install -j 16 --verbose --reuse gdal@3.5.1%gcc@11.3.0+python+png+curl+sqlite3 ^python@3.9.13+ssl ^cmake@3.23.2%gcc@11.3.0
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: NoLibrariesError: Unable to recursively locate lerc libraries in /sw/spack/hydrogpu-2022-06/apps/lerc/3.0-gcc-11.3.0-6qfhczi

/mnt/a/sw/spack/spackgpu/develop-20220714/var/spack/repos/builtin/packages/gdal/package.py:398, in setup_run_environment:
        395        libs = []
        396        for dep in self.spec.dependencies(deptype='link'):
        397            query = self.spec[dep.name]
  >>    398            libs.extend(filter_system_paths(query.libs.directories))
        399        if sys.platform == 'darwin':
        400            env.prepend_path('DYLD_FALLBACK_LIBRARY_PATH', ':'.join(libs))
        401        else:

See build log for details:
  /tmp/svcbwswmanage/spack-stage/spack-stage-gdal-3.5.1-s5t4d4w5dzr4y74cohvfpkqg54ohumqf/spack-build-out.txt
</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.19.0.dev0 (875b032151b550001a52a17fe7044116eea20ad7)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-sandybridge
* **Concretizer:** clingo

### Additional information

This seems similar to several other issues related to build problems where a dependency does not have a +shared variant. In this case, gdal depends on the lerc package, which produces apps/lerc/3.0-gcc-11.3.0-6qfhczi/lib64/liblerc.so. My workaround is to build gdal with ~lerc. Another solution is to add a libs() property to the lerc package.py. However, I think the logic in lib/spack/spack/spec.py for ` _libs_default_handler(descriptor, spec, cls)`might be wrong. It seems like it should find liblerc.so for a package named "lerc" without requiring specific code, and I think the case where there is no +shared property is falling through the loop and throwing the NoLibrariesError when it should have found the library.

As I mentioned, this is fixable by changing lerc/package.py, but appears to apply to other packages as well.

[spack-build-out.txt](https://github.com/spack/spack/files/9161287/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/9161288/spack-build-env.txt)

Tagging @adamjstewart who maintains gdal, but this probably is not really a gdal issue. There is no maintainer for lerc listed by `spack maintainers lerc`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #31680 
Closes #31583

@robertkb can you test this?

### CODE REVIEW

**Comment by robertkb** [comment]
It works for me. Thanks.

**Review by alalazo — APPROVED** [review]

**Comment by climbfuji** [comment]
@alalazo @adamjstewart I was having the same problem and pulled in spack develop as of a few days ago. I can see the commit in `git log`, but if I look at https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/lerc/package.py I don't see the actual change. Do you know what happened?

**Comment by climbfuji** [comment]
For now, I cherry-picked your commit https://github.com/spack/spack/commit/77537fab827e2ecf04c23f8b0aac50bb150cce5e again on top of develop (b1e499d009bbf85f90672a776923083a50e1e136) that I pulled in on Aug 15, and now I can see the change in the `lerc` package.

**Comment by adamjstewart** [comment]
It looks like it was removed in 08e75f7a3e02ef697a5b38a692fb0c8282bd9e7d. There are also other new features that were accidentally reverted in that commit. @renjithravindrankannath @cgmb @srekolam I think what happened was that there was a bad rebase of #31591 that pulled in a bunch of changes from develop, then those changes were undone in multiple commits like https://github.com/spack/spack/pull/31591/commits/3bc3c809dd7bcaea1933ae468b3a690e76a30b57. So the PR branch shows no changes, but in reality that PR undoes those changes. @alalazo what's the best thing to do here? Revert 08e75f7a3e02ef697a5b38a692fb0c8282bd9e7d or manually re-add the removed features?

**Comment by climbfuji** [comment]
> It looks like it was removed in [08e75f7](https://github.com/spack/spack/commit/08e75f7a3e02ef697a5b38a692fb0c8282bd9e7d). There are also other new features that were accidentally reverted in that commit. @renjithravindrankannath @cgmb @srekolam I think what happened was that there was a bad rebase of #31591 that pulled in a bunch of changes from develop, then those changes were undone in multiple commits like [3bc3c80](https://github.com/spack/spack/commit/3bc3c809dd7bcaea1933ae468b3a690e76a30b57). So the PR branch shows no changes, but in reality that PR undoes those changes. @alalazo what's the best thing to do here? Revert [08e75f7](https://github.com/spack/spack/commit/08e75f7a3e02ef697a5b38a692fb0c8282bd9e7d) or manually re-add the removed features?

Thanks, @adamjstewart for looking into this so quickly.

**Comment by adamjstewart** [comment]
Honestly this feels like a security vulnerability in GitHub. Contributors shouldn't be able to remove commits from a project in a PR when the diff shows no visible changes. Going to report this to the folks at GitHub.

**Comment by srekolam** [comment]
Apologies!! i think it was all okay when the initial PR #31591 was raised and addressed the review comments but later it was bad rebase that showed changes that was not intended to in that PR . So, it was taken out from that PR.

**Comment by renjithravindrankannath** [comment]
Sorry about that...!! The commit [08e75f7](https://github.com/spack/spack/commit/08e75f7a3e02ef697a5b38a692fb0c8282bd9e7d) was not intended and I reverted the unintended changes manually. But I think it was lost after a rebase and it didn't list in the list of changes before merge.

**Pull request merged**
