### PR TITLE
Add 'ascent' In-situ Library to 'amr-wind'

### PR DESCRIPTION
**Pull request by nicholasbl**
This PR adds Ascent as a dependency to the Amr-wind simulation package. No other functional change is intended.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
I'm not sure I would add all the negated dependencies. I think you might also want a cuda one though. This is how I'm doing it https://github.com/psakievich/spack-manager/blob/3bbf7580abc5397f4ebe59150f5eab695d96f86a/repos/exawind/packages/amr-wind/package.py#L26-L30 . I haven't upstreamed this to Spack yet though.

**Comment by nicholasbl** [comment]
Thanks for the review! I was a little leery about all the negations myself, but apparently there are some spooky interactions with ascent when things don't match exactly (openmp specifically, and that is on by default in ascent for non-mac builds). But I'd be happy to change it; is there a better way of propagating variants to deps than manually like this? I'll get the cuda one in regardless.

**Comment by jrood-nrel** [comment]
Ok, if you feel there are reasons to be explicit with Ascent, let's keep them. I think it looks good then. At some point I will upstream all our custom stuff we've been using to Spack and update this again in the future.

**Review by jrood-nrel — DISMISSED** [review]

**Comment by nicholasbl** [comment]
Just added the CUDA stuff. Thanks!

**Comment by nicholasbl** [comment]
Whoops, looks like my CUDA update cleared out your approval, @jrood-nrel . Sorry about that. Could you re-approve? Thanks!

**Review by jrood-nrel — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
