### PR TITLE
Add rocSPARSE, rocSOLVER, hipSPARSE and hipBLAS

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@srekolam @arjun-raj-kuppala can you review the changes to `rocsparse`?

**Comment by haampie** [comment]
Hm, pinging @srekolam / @arjun-raj-kuppala once more, would be nice to have this in :)

**Comment by srekolam** [comment]
@haampie  , Thanks!!! i have reviewed the changes for existing recipes that are already approved. I am okay for the changes  to rocsparse etc. 
For the new recipes ( rocsolver, hipblas,hipsparse ) i think AMD will want to own it for current and  future revisions etc.. So i am not sure how to go about it. @gkathirv  has these recipes created already and will follow up with you.

**Comment by haampie** [comment]
Thanks! I'm fine with adding other people (and removing me) as maintainers in the package.py too. Either via this pr, or via a follow up pr.

**Comment by srekolam** [comment]
@haampie , thanks then. @gkathirv is okay with this. We will approve this PR and will follow up with a new PR that will likely have new modifications for the next rocm release as well as change to maintainers list.
@adamjstewart , I am approving this change.

**Pull request merged**
