### PR TITLE
py-graphviz: Add version 1.7

### PR DESCRIPTION
**Pull request by haralmha**

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
```diff
     homepage = "https://github.com/xflr6/graphviz"
     pypi = "graphviz/graphviz-0.10.1.zip"
+    url = "https://github.com/pygraphviz/pygraphviz/archive/refs/tags/pygraphviz-1.7.tar.gz"

+    version('1.7', sha256='9dba480cf9b13cf90e7ef43070b1c8445fb52cd7f27a305ab2b6fe0c100fd768')
     version('0.13.2', sha256='60acbeee346e8c14555821eab57dbf68a169e6c10bce40e83c1bf44f63a62a01')
```
results in:
```py
spack checksum py-graphviz@0.13.2
==> Found 1 version of py-graphviz:

  0.13.2  https://github.com/pygraphviz/pygraphviz/archive/refs/tags/pygraphviz-0.13.2.tar.gz

==> Something failed on https://github.com/pygraphviz/pygraphviz/archive/refs/tags/pygraphviz-0.13.2.tar.gz, skipping.  (All fetchers failed 
for spack-stage-gzzjvjlu)
==> Error: Could not fetch any versions for py-graphviz
```
Add the `url` only to the specific new version if it is really not on pypi.

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Is there any reason not to download from PyPI instead of GitHub? See https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

**Comment by haralmha** [comment]
Hi, sorry for a late response. I just raised an issue about version 1.7 on PyPi: https://github.com/spack/spack/issues/26571. This is the reason why I used the github repo for 1.7, but I agree it would be better to rather fetch it from PyPi.
@bernhardkaindl thanks a lot for all your guidelines on this and my earlier PRs recently, and my apologies for the extra work which I caused for you.

**Comment by bernhardkaindl** [comment]
Build of @1.7 fails here with:
```py
lib/spack/lib/spack/env/gcc/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -Iopt/linux-ubuntu18.04-zen/gcc-8.4.0/python-3.8.11-5ubyrfelrqpn7gq533v5b4y6h2nywb6x/include/python3.8 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-3.8/pygraphviz/graphviz_wrap.o
pygraphviz/graphviz_wrap.c:2711:10: fatal error: graphviz/cgraph.h: No such file or directory
 #include "graphviz/cgraph.h"
          ^~~~~~~~~~~~~~~~~~~
```
While the long version line for 1.7 passes `spack style`, please break it into two lines nonetheless.
`homepage =` links to the `graphviz` homepage, not the homepage of `py-graphviz`, please fix it as well, thanks.

**Comment by adamjstewart** [comment]
The issue is that [graphviz](https://pypi.org/project/graphviz/) and [pygraphviz](https://pypi.org/project/pygraphviz/) are two different projects. It sounds like you want to add a new package for `py-pygraphviz` instead of using `py-graphviz`.

**Pull request closed without merging**
