### PR TITLE
intel-oneapi 2024.2.1: added new version to packages

### PR DESCRIPTION
**Pull request by prstrnn**
@rscohn2

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256s.

**Comment by tldahlgren** [comment]
Will give @rscohn2 time to comment.

**Comment by rscohn2** [comment]
Waiting for https://github.com/rscohn2/oneapi-spack-tests/actions/runs/10300829679 to complete

**Comment by prstrnn** [comment]
@rscohn2 How it looks in the pipeline?

**Comment by rscohn2** [comment]
> @rscohn2 How it looks in the pipeline?

The tests do not work with the latest github runner, but it is not related to the oneAPI release. This test on the older runner is looking better: https://github.com/rscohn2/oneapi-spack-tests/pull/47

**Review by rscohn2 — APPROVED** [review]
Thanks!

**Pull request merged**
