### PR TITLE
[py-onnx-runtime] Remove package superseded by py-onnxruntime

### PR DESCRIPTION
**Pull request by greenc-FNAL**
Per @scheibelp suggestion.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM. Confirmed no other uses in other built-in packages and none in any of the CI pipelines.

**Comment by tldahlgren** [comment]
Adding @adamjstewart in case he has opinions on this PR.

**Review by adamjstewart — CHANGES_REQUESTED** [review]
py-onnx-runtime was deprecated in #35121 which hasn't yet made it into a minor release. The [official policy](https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions) is to remove them after the next minor release (should be coming soon). So we should wait a couple weeks.

**Comment by greenc-FNAL** [comment]
@adamjstewart Ready to merge?

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
