### PR TITLE
sz: fix fetch url for SZ for older releases

### LINKED ISSUE #19213: SZ: bad source fetch url for older versions
Unable to fetch older versions of `sz` using `spack@develop` (6b70597271232e442b9e729b45adaee02bccf8c0 from 6-Oct-2020):

* `sz@2.0.2.0`
* `sz@1.4.12.3`

Probably introduced via eabfea2e49f6db473401b29ca80966f41a7e7c23

```
$> spack install sz@2.0.2.0
...
==> Installing sz
==> No binary for sz found: installing from source
==> Error: FetchError: All fetchers failed

/opt/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
```

Same outcome for `sz@1.4.12.3`

@scottwittenburg @disheng222 @robertu94

### PR DESCRIPTION
**Pull request by robertu94**
fixes #19213

### CODE REVIEW

**Comment by robertu94** [comment]
Converting the PR to a draft while I figure out how to preserve download statistics and spack functionailty

**Comment by eugeneswalker** [comment]
@scottwittenburg

**Comment by robertu94** [comment]
The new code works for all releases listed in Spack except 2.1.9;  waiting on @disheng222 to upload a release that matches the checksum.

**Comment by robertu94** [comment]
The issue regarding 2.1.9 has been resolved.  We are ready to merge.

**Review by eugeneswalker — APPROVED** [review]
Thank you for your quick response @robertu94 @disheng222 !

**Pull request merged**
