### PR TITLE
protobuf: add new versions

### PR DESCRIPTION
**Pull request by figroc**
Add versions from 3.11.3 to 3.12.2. I leave 3.12.3 out on purpose.

### CODE REVIEW

**Comment by figroc** [comment]
The commit is mixed with the master branch 😱. I am working on fixing it.

**Comment by figroc** [comment]
done fixing

**Comment by figroc** [comment]
Why did the macos tests get cancelled?

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
> Why did the macos tests get cancelled?

Not sure, maybe they timed out? Restarted the tests.

**Pull request merged**
