### PR TITLE
Raise exception when 1+ stand-alone tests fail

### PR DESCRIPTION
**Pull request by tldahlgren**
This PR ensures an exception is raised if at least one failure is detected in the stand-alone tests of a test suite. 

It has been tested at the command line to confirm a non-zero exit status is returned after printing the following error:

```
==> Error: <#> test(s) in the suite failed.
```

where `<#>` is the number of tests in the suite that failed.

As indicated in `spack test run --help`, you can use the following options to terminate the test suite early:
- `--fail-first` = stop testing and report the error after detecting the first package test failure (one failure per package);
- `--fail-fast` = stop testing and report the error after detecting the first test failure (one failing package per test suite).

### CODE REVIEW

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Note the pipeline error is from `urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable` and the re-run doesn't seem to work.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
@spackbot help

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Interesting.  CI is getting `==> Error: Expected database version 5 but found version 6.`

**Comment by tgamblin** [comment]
@scottwittenburg if we run the pipeline now will it re-merge or not?  I believe the issue @tldahlgren is seeing is due to the fact that the merge commit in `develop` is behind d83f7110d5 (#22845). A rebase should fix this but also curious if re-running would as well.

**Comment by scottwittenburg** [comment]
> @scottwittenburg if we run the pipeline now will it re-merge or not? I believe the issue @tldahlgren is seeing is due to the fact that the merge commit in `develop` is behind [d83f711](https://github.com/spack/spack/commit/d83f7110d56fe565907180616b92330803544936) (#22845). A rebase should fix this but also curious if re-running would as well.

Spackbot just requests to run the pipeline again on the branch.  At the moment, it's the `gh-gl-sync` cron job running in kube that pushes the new merge commit.

**Comment by tgamblin** [comment]
Thanks!  Ok @tldahlgren - try rebasing.

**Comment by tldahlgren** [comment]
The latest CI failure is:

```
ERROR: Job failed (system failure): prepare environment: image pull failed: rpc error: code = Unknown desc = Error response from daemon: 
...
```

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by sethrj — APPROVED** [review]
Looks good to me!

**Pull request merged**
