### PR TITLE
py-furo: add new versions

### PR DESCRIPTION
**Pull request by rbberger**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new version sha256s.

**Review by tldahlgren — COMMENTED** [review]
Confirmed the four new version sha256s; however, `pyproject.toml`s indicate a version constraint on `py-sphinx-basic-ng` for `2024.5.6` and `2024.7.18` not reflected in the dependency directives.

```
dependencies = [
  "beautifulsoup4",
  "sphinx >= 6.0,<8.0",
  "sphinx-basic-ng >= 1.0.0.beta2",
  "pygments >= 2.7",
]
```

**Review by tldahlgren — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by rbberger** [comment]
@tldahlgren Applied the version constraint for `sphinx-basic-ng`. Since the only version in Spack of that package is that version, I applied it uniformly to all existing versions.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
