### PR TITLE
dolfinx: add ADIOS2 variant

### PR DESCRIPTION
**Pull request by adeebkor**
This pull request will enable the usage of ADIOS2Writers in dolfinx.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot maintainers

**Comment by alalazo** [comment]
Feel free to ping me back once this is approved by package maintainers

**Comment by garth-wells** [comment]
Adding ADIOS2 as a variant is fine, but
```
  "-DDOLFINX_ENABLE_ADIOS2=%s" % (
      'ON' if "+adios2" in self.spec else 'OFF'),
```
needs to be added to the `cmake_args`.

Once this has been added I'll test the PR before approving.

**Review by garth-wells — APPROVED** [review]

**Review by chrisrichardson — APPROVED** [review]

**Review by nate-sime — APPROVED** [review]

**Comment by garth-wells** [comment]
@alalazo I'm happy with this PR.

**Comment by alalazo** [comment]
Can you please rebase to trigger the pipeline again on a good merge commit?

**Comment by adeebkor** [comment]
@alalazo 

> Can you please rebase to trigger the pipeline again on a good merge commit?

Done!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
