### PR TITLE
Change Omega_h URL

### PR DESCRIPTION
**Pull request by ibaned**
Omega_h will be moving to a new location (GitHub Organization instead of individual account). I'd like to coordinate this move with the merge of this PR, but if the PR takes too long to merge then Spack will simply be broken until its merged.

@balay

### CODE REVIEW

**Comment by balay** [comment]
I can do the merge in sync with you - after the CI tests are completed.

**Comment by ibaned** [comment]
Thanks @balay !

**Comment by ibaned** [comment]
Are these coverage failures due to the new URL not being up yet? Not sure what to do here...

**Comment by balay** [comment]
https://travis-ci.org/spack/spack/builds/478452398

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
I would trigger a rerun of CI - to see if this error comes up again.

One way to do this is to push a new commit - or modify the existing commit [or rebase etc..]

**Comment by ibaned** [comment]
I just force pushed a slightly different commit message, lets see if it works

**Comment by balay** [comment]
CI went through this time - so I can merge whenever URLs are changed.

**Comment by ibaned** [comment]
@balay I just moved it!

**Pull request merged**
