### PR TITLE
Add new UPC++ release version

### PR DESCRIPTION
**Pull request by bonachea**

### CODE REVIEW

**Comment by bonachea** [comment]
@adamjstewart I appear to lack access to restart the failed ci/gitlab-ci pipeline:

> There has been a runner system failure, please try again

However I believe this PR is ready to merge.

**Review by tldahlgren — APPROVED** [review]
Confirmed each sha256 for the two new versions.

**Comment by tldahlgren** [comment]
Closing and re-opening the PR to force re-running failed `ci/gitlab-ci`.

**Comment by bonachea** [comment]
Thanks @tldahlgren !

**Pull request merged**
