### PR TITLE
libwnck: new package

### PR DESCRIPTION
**Pull request by teaguesterling**
Adding a dependent library for building the XFCE4 desktop core with Spack.

### CODE REVIEW

**Comment by teaguesterling** [comment]
@spackbot rerun pipeline

**Comment by teaguesterling** [comment]
Additional dependencies need to be sorted out due to audit failure. According to Arch (https://archlinux.org/packages/extra/x86_64/libwnck/):

[at-spi2-core](https://archlinux.org/packages/extra/x86_64/at-spi2-core/)
[cairo](https://archlinux.org/packages/extra/x86_64/cairo/)
[fontconfig](https://archlinux.org/packages/extra/x86_64/fontconfig/)
[freetype2](https://archlinux.org/packages/extra/x86_64/freetype2/)
[gdk-pixbuf2](https://archlinux.org/packages/extra/x86_64/gdk-pixbuf2/)
[glib2](https://archlinux.org/packages/core/x86_64/glib2/)
[glibc](https://archlinux.org/packages/core/x86_64/glibc/)
[gtk2](https://archlinux.org/packages/extra/x86_64/gtk2/)
[harfbuzz](https://archlinux.org/packages/extra/x86_64/harfbuzz/)
libatk-1.0.so=0-64 ([at-spi2-core](https://archlinux.org/packages/extra/x86_64/at-spi2-core/))
libcairo.so=2-64 ([cairo](https://archlinux.org/packages/extra/x86_64/cairo/))
libfreetype.so=6-64 ([freetype2](https://archlinux.org/packages/extra/x86_64/freetype2/))
libgdk_pixbuf-2.0.so=0-64 ([gdk-pixbuf2](https://archlinux.org/packages/extra/x86_64/gdk-pixbuf2/))
libgio-2.0.so=0-64 ([glib2](https://archlinux.org/packages/core/x86_64/glib2/), [glib2](https://archlinux.org/packages/core-testing/x86_64/glib2/))
libharfbuzz.so=0-64 ([harfbuzz](https://archlinux.org/packages/extra/x86_64/harfbuzz/))
libpango-1.0.so=0-64 ([pango](https://archlinux.org/packages/extra/x86_64/pango/))
[libx11](https://archlinux.org/packages/extra/x86_64/libx11/)
[libxres](https://archlinux.org/packages/extra/x86_64/libxres/)
[pango](https://archlinux.org/packages/extra/x86_64/pango/)
[startup-notification](https://archlinux.org/packages/extra/x86_64/startup-notification/)
[gobject-introspection](https://archlinux.org/packages/extra/x86_64/gobject-introspection/) (make)
[intltool](https://archlinux.org/packages/extra/any/intltool/) (make)
[libxt](https://archlinux.org/packages/extra/x86_64/libxt/) (make)

**Comment by teaguesterling** [comment]
@spackbot fix style

**Comment by teaguesterling** [comment]
This adds some missing dependencies to `libwnck` and builds successfully in the Focal docker image.
A bug with `startup-notification` was identified during testing and will be patched separately.

**Comment by teaguesterling** [comment]
@spackbot fix style

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
