### PR TITLE
Don't build eggs.

### PR DESCRIPTION
**Pull request by tgamblin**
PythonPackage now builds flat installs instead of egg directories.

@dhmunro noticed that eggs cause extra filesystem operations and more poking around on `sys.path`, which will cause slowdowns on HPC runs.  Yes, you can use [Spindle](http://computation.llnl.gov/projects/spindle) for that, and we do, but there are other good reasons to use a flat layout instead of eggs:

1. Spack doesn't need eggs -- it manages its own directories and symlinks extensions into place.

2. Eggs are deprecated for wheels, and wheels install flat.

3. We don't *have* to do all the `easy-install.pth` merging (#3569, #3583), though we should still support that for packages that want to override this behavior for some reason.

We now supply the --single-version-externally-managed argument to `setup.py install` for setuptools packages and setuptools.

### CODE REVIEW

**Comment by tgamblin** [comment]
@adamjstewart @lee218llnl: care to test this out?

**Comment by dhmunro** [comment]
Wow, that was quick.  It turns out it doesn't solve my immediate performance issue (even with no sys.path search misses, we're still pounding the filesystem too hard), but as you point out, it's unnecessary, obsolete, and plain messy.  I'm glad it's ticked off the list...
Dave

**Comment by lee218llnl** [comment]
@tgamblin, this is breaking py-basemap:

```
==> '/nfs/tmp2/lee218/delete/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.13-mdeplzdkoh5635rrmm4vfeeqagqmcljk/bin/python' 'setup.py' '--no-user-cfg' 'install' '--prefix=/nfs/tmp2/lee218/delete/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/py-basemap-1.0.7-6auw6q62novxuecffpqgmzxiz2onzvtm' '--single-version-externally-managed' '--root=/'
In file included from nad2bin.c:7:0:
src/projects.h:478:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void pj_deallocate_grids();
 ^
nad2bin.c:46:13: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 static void Usage()
             ^
In file included from src/pj_malloc.c:5:0:
src/projects.h:478:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 void pj_deallocate_grids();
 ^
/nfs/tmp2/lee218/delete/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-2.7.13-mdeplzdkoh5635rrmm4vfeeqagqmcljk/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'namespace_packages'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --single-version-externally-managed not recognized
```

Currently the py-basemap packages lists py-setuptools as a dependence, even though it doesn't directly depend on it. Even if we remove that, though, some of py-basemap's dependences do depend on py-setuptools, so py-setuptools appears in py-basemaps spec. Is there anyway to make it so that this arg is only added when py-setuptools is a direct dependence (and then we can separately fix py-basemap)?

**Comment by citibeth** [comment]
Based on @tgamblin's point (3) in the OP, I'm not surprised it breaks `py-basemap`, see #1964.  Can `PythonPackage` optionally do eggs for the few packages that need them (such as `py-basemap`)?

**Comment by tgamblin** [comment]
@citibeth: in this case it's actually what @lee218llnl pointed out -- my check in `PythonPackage` was wrong.  I'll update it to only check *immediate* `setuptools` dependencies.  `py-basemap` also shouldn't depend on `setuptools`.  There are likely other packages like that, which list `setuptools` as a dependency but don't need it.

**Comment by tgamblin** [comment]
@lee218llnl @adamjstewart: ok, I got `py-basemap` working per the fix above.  Removing the setuptools dependency is the right thing to do, and `PythonPackage` now only uses `setuptools` arguments when `setuptools` is an *immediate* dependency (or when it's the package being installed).

I felt adventurous and tried installing `py-jupyter-notebook`, which turned up 15 more packages that don't need `setuptools`.  Most of the IPython stack seems to use distutils *unless* `setup.py` is invoked to make a `bdist`.  We should probably try installing *all* the Python packages that depend on setuptools before merging this, so I am marking it WIP.

@krafczyk: I ended up cleaning up a few dependencies of `py-jupyter-notebook` to make them build.  Can you take a look at those?  Specifically:
* fixed `py-cffi` for Darwin
* Got rid of the problematic css fetch that happens when you install `py-nbconvert`, and bundled `style-min.css` with Spack.

**Comment by krafczyk** [comment]
@tgamblin, I'll have a look.

**Comment by adamjstewart** [comment]
I agree with all of the setuptools dependency changes.

**Comment by lee218llnl** [comment]
@tgamblin looks good for py-basemap, thanks.

**Comment by krafczyk** [comment]
@tgamblin, I had to add a couple of commits for missing dependencies for matplotlib and yt. After these changes I'm good with this PR. I've added the commits to features/no-python-eggs on my spack fork, pull from that branch to get my changes.

**Comment by paulhopkins** [comment]
@tgamblin This PR is great. I have started to install all Python packages, and found some more setuptools dependency problems. The fixes can be found at in [my repo](/paulhopkins/spack/tree/features/no-python-eggs) and listed below:

Add required setuptools dependency:
- py-bottleneck
- py-csvkit
- py-emcee
- py-periodictable
- py-restview
- py-sncosmo
- py-wcsaxes

Remove unneeded setuptools dependency:
- py-joblib
- py-markdown
- py-terminado

**Comment by tgamblin** [comment]
@paulhopkins: thanks!  I added you as a collaborator, so you should be able to push to this branch now.  Do you mind pushing your updates here?

**Comment by tgamblin** [comment]
@paulhopkins: is that the only one you haven't tried yet?

**Comment by paulhopkins** [comment]
@tgamblin I have 'tried' them all, but these are the ones that have failed:

py-pyqt: Fails to find Phonon headers. These should be QT package, but they are not there.
py-guidata, depends on py-pyqt
py-guiqwt, depends on py-pyqt
py-pythonqwt, depends on py-pyqt
py-qtawesome, depends on py-pyqt
py-qtconsole, depends on py-pyqt
py-qtpy, depends on py-pyqt
py-tuiview, depends on py-pyqt

py-yt, Fixed by @krafczyk 

py-meep, Meep did not install
py-mysqldb1, MySQLDB did not install
py-pyfftw, Linking error
py-rpy2, Build error

Fixed in new commit:
py-pysocks, Does not depend on setuptools

**Comment by adamjstewart** [comment]
`py-meep` has known problems. I wrote the original package. It used to work at one time but no longer does, and the package hasn't changed. It was fairly hacky to begin with. I'll take a look at it someday, but it wasn't broken by this PR.

**Comment by scheibelp** [comment]
Would it make sense for this PR to eliminate the ```write_easy_install_pth``` function from the python package?

**Comment by tgamblin** [comment]
I rebased this and included the changes from @paulhopkins and @krafczyk, so it should be ready to go.

**Comment by tgamblin** [comment]
@scheibelp: 

> I'm curious: why would a package want to override this? There aren't currently any python modules in Spack's default repo that do this.

I don't know, but I don't think it's good practice to break the functionality.  I'm almost positive that Python packages wouldn't want to use eggs if building with Spack.  But `.pth` files are one way that Python knows how to do imports, and if there is a package that relies on them, or a site that somehow depends on them, I don't want to make Spack break a Python feature if we don't have to.

**Comment by dhmunro** [comment]
Todd,

Just by the way, the system I've come up with for managing sys.path makes considerable use of .pth files.  It seems much less fragile than relying on PYTHONPATH (although arguably less flexible, since it's harder to override).  I've also used the egg trick of stacking executable python code on an import line in a .pth file, in two distinct use cases:
(1) To put $SYS_TYPE dependent directory names into sys.path (a .pth file seems a very logical place for this).
(2) To start my "import recorder" code.
Number (2) is interesting because the .pth parsing occurs far earlier in the python startup than any other point you can access.  If you need your code to run very early, it's your best option.  It even works for hydra's embedded python, getting in even before the compiled code begins its imports, so it's very useful for embedded python instances as well.

Anyway, please don't do anything that would break the .pth file processing...

Dave

**Comment by healther** [comment]
@adamjstewart in 8d0758fc4cf863ed82d6d4bacd9819e5fd69b3a4 you added the following function to `py-numpy` (besides other stuff)
```
def setup_dependent_package(self, module, dependent_spec):
        python_version = self.spec['python'].version.up_to(2)
        arch = '{0}-{1}'.format(platform.system().lower(), platform.machine())

        self.spec.include = join_path(
            self.prefix.lib,
            'python{0}'.format(python_version),
            'site-packages',
            'numpy-{0}-py{1}-{2}.egg'.format(
                self.spec.version, python_version, arch),
            'numpy/core/include')
```

Doesn't this conflict with this change here? I think we ran into this problem when one of our packages has to link against numpy on a barebone Debian. I fear that we didn't note this prior because we always worked on systems where a non-spack numpy was available.

**Comment by adamjstewart** [comment]
Probably? `py-meep` just needs to know where the `py-numpy` headers live. If they no longer live in this location due to the removal of eggs, we will need to update `py-numpy` with the new header location.

**Comment by healther** [comment]
Okay, I'll have a PR for that in a couple of days, unfortunately I was unable to build `meep` but haven't had the time to investigate why yet

**Comment by adamjstewart** [comment]
Yeah, I noticed that as well. `meep` and `py-meep` were working perfectly for me when I wrote the original packages, but the last time I tested them they didn't build. Not sure what changed, but hopefully you'll figure it out.

**Pull request merged**
