### PR TITLE
py-torchgeo: add v0.4.0

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/microsoft/torchgeo/releases/tag/v0.4.0

Depends on #35121

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Re-confirmed sha256, rest LGTM.

**Pull request merged**
