### PR TITLE
Updating MFEM package with v3.2 info.

### PR DESCRIPTION
**Pull request by tzanio**

### CODE REVIEW

**Comment by tgamblin** [comment]
@tzanio can you keep the old version uncommented as well, in case someone wants to install that one specifically?  The packages can have multiple version directives; by default Spack will pick the newest if the version is unspeciifed. You can also add `preferred=True` to a version to make Spack pick that one by default, even if it's *not* the newest.

**Comment by tzanio** [comment]
Both 3.1 and 3.2 should be available. Added `preferred=True` to 3.2.

**Comment by tgamblin** [comment]
Thanks!

**Comment by adamjstewart** [comment]
Can you remove `preferred=True`? Spack defaults to the newest version of every package anyway. If we start adding `preferred=True` to the newest version, not only is it redundant, but it will need to be moved/removed every time a new version is added.

**Comment by tgamblin** [comment]
I think this is up to the package maintainer.  It might be that Tzanio likes to be explicit, and this reminds him how Spack behaves. Also he might not move it.  E.g. He might put a newer beta in here that shouldn't be the default...

**Comment by adamjstewart** [comment]
This also assumes that Tzanio is the only person who will ever use MFEM. To be fair, I'm not currently using it. Just pointing out that being explicit makes more work for future users who want a newer version.

**Comment by tgamblin** [comment]
I doubt he's the only guy but he *is* the developer and he's updating the package on each release at the moment.

**Comment by adamjstewart** [comment]
Didn't realize he is the developer. It's his package then :smile:

**Comment by tzanio** [comment]
We actually wanted to update this to support some of the new features in 3.2 anyway... we may need some help though. 

Adding @v-dobrev to the discussion.

**Pull request merged**
