### PR TITLE
Patch meson package to work with Intel OneAPI compilers.

### PR DESCRIPTION
**Pull request by nicholas-sly**

### CODE REVIEW

**Review by becker33 — APPROVED** [review]
Solution suggested at https://github.com/mesonbuild/meson/issues/8113

**Comment by becker33** [comment]
Meson PR is here: https://github.com/mesonbuild/meson/pull/9850

**Comment by eli-schwartz** [comment]
This is a byte-for-byte duplicate of #30605 but with the commit message headers stripped off of the patch file.

**Comment by becker33** [comment]
Closed in favor of #30605

**Pull request closed without merging**
