### PR TITLE
goblin-hmc-sim: add main branch, switch maintainer

### PR DESCRIPTION
**Pull request by berquist**

### CODE REVIEW

**Comment by tldahlgren** [comment]
@jjwilke Are you okay with being removed as a maintainer on this package?

**Review by tldahlgren — APPROVED** [review]
Confirmed the branch exists.  Would prefer to hear from @jjwilke about removing him as a maintainer (since there can be multiple maintainers on a PR).

**Comment by berquist** [comment]
To partially speak for him, Jeremy has not been a part of the SST team for several years, and SST is the only consumer and contributor to this package.

**Comment by tldahlgren** [comment]
> To partially speak for him, Jeremy has not been a part of the SST team for several years, and SST is the only consumer and contributor to this package.

Under the circumstances, I will merge and if he wants he can submit a separate PR to add himself back.

**Pull request merged**
