### PR TITLE
New package: r-reams

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
Not an R expert, but what does it mean that the package was removed from the archive because of this: https://cran-archive.r-project.org/web/checks/2021/2021-02-15_check_results_reams.html ? Would it cause troubles with other installed packages?

**Review by glennpj — COMMENTED** [review]
This looks fine but note that this package has been removed from CRAN.
```
Package ‘reams’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2021-02-15 as check problems were not corrected in time.

A summary of the most recent check results can be obtained from the check results archive.

Please use the canonical form https://CRAN.R-project.org/package=reams to link to this page.
```
@qwertos Do you still want to proceed with this?

**Comment by glennpj** [comment]
@alalazo It generally means that the package has been abandoned. That generally means the package is also old, and may not work in newer versions of R, and may not adhere to current packaging guidelines that have changed since release. It is probably best to find an alternative but that is not always possible.

**Comment by qwertos** [comment]
@glennpj It's up to y'all if you want to accept archived packages. It doesn't really make too much of a difference to me one way or another. We had a user ask for it (or something that depends on it) at one point in time, and thus it was created. My goal at the moment is to decrease the differences between our fork and develop, get more eyes validating our work, and hopefully help someone else down the line.

**Review by glennpj — APPROVED** [review]
I think it is fine to have archived R packages as long as they work for people. This package was only recently archived and apparently still works.

**Pull request merged**
