### PR TITLE
hdf5-blosc: Remove commit id from version specification

### PR DESCRIPTION
**Pull request by eschnett**
The respective commit seems to have vanished.
Now using the master branch without specifying a particular commit.

### CODE REVIEW

**Comment by eschnett** [comment]
Ping

**Comment by adamjstewart** [comment]
I'm fine with this change. `hdf5-blosc` has no official releases and literally only has 15 commits in the repository. But can you remove the commented out version? I don't think it's coming back...

**Comment by adamjstewart** [comment]
LGTM

**Comment by eschnett** [comment]
Pull request updated.

**Comment by eschnett** [comment]
Ping

**Pull request merged**
