### PR TITLE
exaca: add version 1.2

### PR DESCRIPTION
**Pull request by streeve**

### CODE REVIEW

**Review by MattRolchigo — APPROVED** [review]

**Comment by MattRolchigo** [comment]
I don't know enough about the CI stuff to know why some checks are failing, but otherwise this change makes sense

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256, rest LGTM.

**Comment by tldahlgren** [comment]
This PR is experiencing a CI issue I've seen on a number of others.  I'm hopeful another PR has the needed fix and will get merged soon.

**Comment by tldahlgren** [comment]
Updating to latest develop since a PR was merged that MAY fix it.

**Pull request merged**
