### PR TITLE
fetch git submodules recursively

### LINKED ISSUE #983: GitFetchStrategy has no direct support for required submodules
This is related to the construction of the rust package in #982, there are no options for handling submodules in the git fetcher at the moment.  I went to create this, but there are enough options for how to handle it as to convince me to start a discussion first.  Options:
1.  Just add `--recursive` to clone when requested
   - This is the simplest, longest supported option, but it means cloning the entirety of all submodules, which is painful when one of them is LLVM or similar
2.  Add an option that causes `git submodule update --init --recursive` to be run after clone
   - Basically equivalent to the first option, but could include `--depth` if it's a new enough git, but `--depth` may fail on some versions and repositories if the commit in question is not within that depth
3. Something else:
   - There could always be per-directory submodule handling, a separate command... whatever, any thoughts?

### LINKED ISSUE #2190: git shallow clone of submodules as well?
Currently the repositories are cloned with `--depth=1` but if I set `submodules=True` then submodules are full clones. For large repos it would be nice to have submodules with `shallow` clones as well.

### PR DESCRIPTION
**Pull request by junghans**
Fixes #983.
Fixes #2190.

This is useful if the submodules have submodules themselves. On
the other hand doing a recursive update doesn't hurt if there
is only one level.

### CODE REVIEW

**Comment by junghans** [comment]
@adamjstewart : how do I satisfy a `diff hit` of 66.78% ?

**Comment by adamjstewart** [comment]
Basically, the codecov message means that our unit tests don't cover the line you modify. This is a little scary because there's really no way of knowing whether or not you introduced a bug (although I doubt it). If you want to be a hero, you can try to add unit tests to cover this, although I'm not sure whether or not we want to introduce unit tests that require internet access. Since this is only a 2 line change and the total coverage isn't changing, I don't think this will hold up the PR though. We don't merge PRs that fail Travis, but we often merge PRs that don't have test coverage. I'll let a few other people approve this PR before merging it.

**Comment by junghans** [comment]
@tgamblin

**Comment by junghans** [comment]
Needed by #3780.

**Comment by junghans** [comment]
@citibeth: Please have a review!

**Comment by citibeth** [comment]
I have never used git submodules, so not sure how useful I can be on this review.  My two thoughts are:

1. More docs (or reference to docs) explaining git submodules, and recursive submodules, might be nice.

2. The diffs look relatively straightforward.  They will clearly ONLY affect packages using submodules.  I expect that's not a large number?  In that case, one could grep for them and know what to test.

**Comment by junghans** [comment]
@citibeth: Good points

> 1. More docs (or reference to docs) explaining git submodules, and recursive submodules, might be nice.

Done, added a sentence about git submodules and added reference to the git sub-manpage.

> 2. The diffs look relatively straightforward. They will clearly ONLY affect packages using submodules. I expect that's not a large number? In that case, one could grep for them and know what to test.

` git grep submodules var/spack/repos/builtin/` only return `rust`, which handles submodules manually at this point and hence will not be affected by that change.

**Comment by junghans** [comment]
@trws: Why did you clone submodules manually in `rust`?

**Comment by trws** [comment]
The only reason I can think of is that either the submodules feature wasn't there yet, or I didn't know about it.  Either way, there's no reason to keep it like that.

**Comment by trws** [comment]
Actually, the other thing might be that the submodules are part of the cargo resource rather than rust itself.  It's possible there was an issue with resources, rather than packages, at the time.

**Comment by junghans** [comment]
Let's merge this and I will port over `rust`.

**Comment by adamjstewart** [comment]
Was scrolling through old issues and found @trws's #983 which this solves.

**Comment by junghans** [comment]
Nice!

**Comment by adamjstewart** [comment]
How does this PR affect #2190?

**Comment by junghans** [comment]
See the fix!

**Comment by adamjstewart** [comment]
Hmm, it looks like the `--depth` option isn't available in git 2.5.0. The default git version on CentOS 6 is 1.7.1, and on CentOS 7 it's 1.8.3.1. We definitely can't use an option that isn't available even on CentOS 7.

**Comment by junghans** [comment]
This option seems to be part of git-1.8.4 (git/git@275cd184d52b5b81cb89e4ec33e540fb2ae61c1f)

**Comment by junghans** [comment]
@tgamblin: I looked at the before, to test submodules one will need an existing repo (with commits) when calling `mock_git_repository()`, so break the "make a repo with a commit" part out would be useful. This is bit more work, so I will leave that change to you guys.

**Comment by tgamblin** [comment]
I'm going to make some more tests for `fetch_strategy` so I'll cover this as well.

**Pull request merged**
