### PR TITLE
Fix homepage for the package libspatialindex

### PR DESCRIPTION
**Pull request by fedepad**
Small fix for the homepage of the package libspatialindex.

### CODE REVIEW

**Comment by aprokop** [comment]
@fedepad Could you please fix this issue in other packages?
```bash
spack (develop) $ git grep 'http://http'
var/spack/repos/builtin/packages/cscope/package.py:    homepage = "http://http://cscope.sourceforge.net/"
var/spack/repos/builtin/packages/libspatialindex/package.py:    homepage = "http://http://libspatialindex.github.io"
var/spack/repos/builtin/packages/sbt/package.py:    homepage = "http://http://www.scala-sbt.org"
var/spack/repos/builtin/packages/sbt/package.py:    url      = "http://http://www.scala-sbt.org/download.html"
```

**Comment by becker33** [comment]
I'll close this. Anyone who wants to take on @aprokop's suggestion, it would be appreciated.

**Comment by fedepad** [comment]
@aprokop Sure! I will open then a separate PR for those other cases you mentioned!

**Comment by adamjstewart** [comment]
I'll do it.

**Pull request merged**
