### PR TITLE
Xorg pkgs: mark protocols as build dependencies where appropriate

### PR DESCRIPTION
**Pull request by wdconinc**
This PR modifies the xorg packages by marking protocols as build dependencies where possible. When a protocol is required at link time per the pkgconfig files, the type is also marked as a link dependency.

Also:
- update bdftopcf to v1.1.1, which moves it from app/ to util/
- update remaining urls from cgit to gitlab
- remove "generated" from c language (cpp was added because of that extensions being used by xorg for config files, and references to cpp as the C preprocessor macro)

And then some more:
- libgl(vnd) versioning has changed away from mesa specific, https://gitlab.freedesktop.org/xorg/xserver/-/commit/e6ef2b12404dfec7f23592a3524d2a63d9d25802

Test builds:
- all modified packages were built in a clean-room environment (github codespaces),
- in particular, this included the environment in the [comment below](https://github.com/spack/spack/pull/45536#issuecomment-2263951790)
- unable to be built were `xts` (inactive by appearance) and `liblbxutil` (archived upstream, as well as its dependencies `lbxproxy` and `proxymngr`), both of which suffered from stricter multiple-defined symbol issues in newer gcc versions, (these are not new issues and don't affect other downstream packages)
- also unable to be built was `xorg-server` (linux headers with minor, major not included), and that's still under investigation

### CODE REVIEW

**Comment by wdconinc** [comment]
@spackbot run pipeline

**Comment by wdconinc** [comment]
Test build environment
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - libepoxy -glx
  - appres
  - bdftopcf
  - bitmap
  - fonttosfnt
  - fslsfonts
  - fstobdf
  - iceauth
  - ico
  - imake
    #- lbxproxy  # archived, unable to build dependency liblbxutil
    #- libapplewm  # unable to build on linux
  - libdmx
  - libfontenc
  - libfs
  - libice
    #- liblbxutil  # archived, unable to build with recent gcc due to duplicate symbol definitions
  - libsm
  - libwindowswm
  - libx11
  - libxau
  - libxaw
  - libxaw3d
  - libxcb
  - libxcomposite
  - libxcursor
  - libxdamage
  - libxdmcp
  - libxevie
  - libxext
  - libxfixes
  - libxfont
  - libxfont2
  - libxfontcache
  - libxi
  - libxinerama
  - libxkbfile
  - libxmu
  - libxp
  - libxpm
  - libxpresent
  - libxprintapputil
  - libxprintutil
  - libxrandr
  - libxrender
  - libxres
  - libxscrnsaver
  - libxshmfence
  - libxt
  - libxtrap
  - libxtst
  - libxv
  - libxvmc
  - libxxf86dga
  - libxxf86misc
  - libxxf86vm
  - listres
  - lndir
  - makedepend
  - mkfontscale
    #- proxymngr  # archived, unable to build dependency liblbxutil
  - rendercheck
  - rgb
  - rstart
  - sessreg
  - transset
  - twm
  - x11perf
  - xauth
  - xcalc
  - xcb-util-errors
  - xcb-util-image
  - xcb-util-keysyms
  - xclipboard
  - xclock
  - xconsole
    #- xdotool
  - xdpyinfo
    #- xdriinfo
  - xev
  - xfd
  - xfindproxy
  - xfs
  - xfsinfo
  - xfwp
  - xgamma
  - xhost
  - xinit
  - xinput
  - xkbcomp
  - xkbprint
  - xkbutils
  - xkeyboard-config
  - xkill
  - xload
  - xlsfonts
  - xman
  - xmodmap
    #- xorg-server
  - xpr
  - xprop
  - xrandr
  - xrdb
  - xrefresh
  - xrx
  - xscope
  - xset
  - xsetpointer
  - xsetroot
  - xstdcmap
    # - xts  # unable to build with recent gcc due to duplicate symbol definitions
  - xvinfo
  - xwd
  - xwininfo
  - xwud
  view: true
  concretizer:
    unify: true
  packages:
    gl:
      require:
      - glx
    libglx:
      require:
      - opengl
    opengl:
      buildable: false
      externals:
      - spec: opengl@4.6
        prefix: /usr
```

**Comment by wdconinc** [comment]
FYI @teaguesterling you may be interested in this (more recent) PR too. With the change to xorg-proto it won't lead to any garbage collection due to the few X libraries that require the protocols as link dependencies, but at least the graph will be expressed more accurately.

**Comment by teaguesterling** [comment]
This is great! Thanks for sharing @wdconinc!

**Comment by wdconinc** [comment]
@spackbot fix style

**Review by bernhardkaindl — APPROVED** [review]
@wdconinc @teaguesterling Looks straight-forward to me, built `xorg-server` and a few xutils on Ubuntu 22.04

**Pull request merged**
