### PR TITLE
`duckdb`: add v1.1.1, remove `@0.7.1:0.8.1`, update variants

### PR DESCRIPTION
**Pull request by teaguesterling**

### CODE REVIEW

**Review by bernhardkaindl — DISMISSED** [review]
JFYI: Built the new version on Ubuntu 22.04
```py
bin/spack find -v duckdb
-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
duckdb@1.1.1+autocomplete+cli+excel+fts+httpfs~icu+inet~jdbc+json+ninjabuild~odbc+parquet~python build_system=makefile
```
`+odbc` will need `depends_on("py-pip@:23.0", type="build")` (adding it)

**Review by bernhardkaindl — DISMISSED** [review]
@glentner / @teaguesterling: Added `depends_on("unixodbc", when="+odbc")` to fix `+odbc`. Built now:
```py
bin/spack find -v duckdb
-- linux-ubuntu22.04-ivybridge / gcc@12.3.0 ---------------------
duckdb@1.0.0+autocomplete+cli+excel+fts+httpfs+icu+inet+jdbc+json+ninjabuild+odbc+parquet~python build_system=makefile
```

**Review by bernhardkaindl — COMMENTED** [review]
@teaguesterling I suggest removing the `python` variant and adding a comment about it that because it uses setuptools_scm and the tarballs don't contain the version directory, it fails to get the package version when attempting the build the weel.

This is the patch that would be needed in order to get to this point:
```py
diff --git a/var/spack/repos/builtin/packages/duckdb/package.py b/var/spack/repos/builtin/packages/duckdb/package.py
index b106bd1e37..3dabe0280e 100644
--- a/var/spack/repos/builtin/packages/duckdb/package.py
+++ b/var/spack/repos/builtin/packages/duckdb/package.py
@@ -67,6 +67,8 @@ class Duckdb(MakefilePackage):
     depends_on("gmake", type="build")
     depends_on("ninja", when="+ninjabuild", type="build")
     depends_on("openssl", when="+httpfs")
+    depends_on("py-pip", when="+python", type="build")
+    depends_on("py-wheel", when="+python", type="build")
     depends_on("unixodbc", when="+odbc")
     depends_on("icu4c", when="~icu")

@@ -95,6 +97,9 @@ class Duckdb(MakefilePackage):
     variant("odbc", default=False, description="Build with ODBC driver (may not work)")
     variant("python", default=False, description="Build with Python driver (may not work)")

+    # +python links httpfs_extension library:
+    conflicts("~httpfs", when="+python")
+
     # Observed failure in an AVX2-specific codeblock on x86_64_v4 target
     conflicts(
         "@1.0.0",
(
```
I tried with 1.1.1, 1.0.0 and 0.10.2, all with the same error that the version information is missing. I assume it might be possible to write the version to some file or the setup.py, but that's unlikely to be reliable over the range of versions.

**Comment by teaguesterling** [comment]
I'll look into the python package version. There was a good deal of work to get that working for the main build. Some of that logic may be able to be patched in to move python forward. 

Thanks for getting the odbc stuff sorted!

**Comment by teaguesterling** [comment]
Actually, it looks like the JDBC and ODBC drivers have been moved out of the main repository as of a recent release. I've fixed the Python build dependencies and added a few additional variants that are easily configurable related to extensions.

**Review by bernhardkaindl — DISMISSED** [review]
@teaguesterling 
Build results on Ubuntu 22.04.4 LTS (default install) with: 
```py
# add-apt-repository ppa:ubuntu-toolchain-r/ppa && apt update
# apt install g{++,fortran}-13 make patch bzip2 unzip python3-pip
```
```py
Passed:
duckdb@1.1.1
duckdb+extension_autoload
duckdb+extension_autoinstall
duckdb+extension_repo
duckdb+autocomplete
duckdb+tpce
duckdb+tpch
duckdb+python

Failed: duckdb+static_openssl (Sorry, the script didn't save the logs yet)

bin/spack find -v openssl
openssl@3.3.1~docs+shared build_system=generic certs=mozilla
                   ^--- ~shared missing when the variant is selected?

spack find -v duckdb
-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce+tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl+tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall+extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel+extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
==> 5 installed packages
```
Generated by:
https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py (WIP)

@teaguesterling I'd be fine to merge with new variant not working, but if it is an easy fix, then it's probably/maybe worth another revision to fix it. If not, I'd be happy to merge.

**Comment by bernhardkaindl** [comment]
That's the failure with just `bin/spack install duckdb+static_openssl` (without `+openssl`)
```py
[782/789] Linking CXX executable duckdb
FAILED: duckdb
: && /home/bkaindl/spack/lib/spack/env/gcc/g++ -O3 -DNDEBUG -O3 -DNDEBUG  tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/highlighting.cpp.o tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/history.cpp.o tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/linenoise.cpp.o tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/linenoise-c.cpp.o tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/rendering.cpp.o tools/shell/linenoise/CMakeFiles/duckdb_linenoise.dir/terminal.cpp.o tools/shell/CMakeFiles/shell.dir/shell.c.o -o duckdb  tools/sqlite3_api_wrapper/libsqlite3_api_wrapper_static.a  third_party/utf8proc/libduckdb_utf8proc.a  src/libduckdb_static.a  extension/autocomplete/libautocomplete_extension.a  extension/fts/libfts_extension.a  extension/httpfs/libhttpfs_extension.a  extension/json/libjson_extension.a  extension/tpcds/libtpcds_extension.a  extension/tpch/libtpch_extension.a  extension/parquet/libparquet_extension.a  extension/icu/libicu_extension.a  extension/jemalloc/libjemalloc_extension.a  src/libduckdb_static.a  extension/autocomplete/libautocomplete_extension.a  extension/fts/libfts_extension.a  extension/httpfs/libhttpfs_extension.a  extension/json/libjson_extension.a  extension/tpcds/libtpcds_extension.a  extension/tpch/libtpch_extension.a  extension/parquet/libparquet_extension.a  extension/icu/libicu_extension.a  extension/jemalloc/libjemalloc_extension.a  third_party/utf8proc/libduckdb_utf8proc.a  third_party/fsst/libduckdb_fsst.a  third_party/fmt/libduckdb_fmt.a  third_party/libpg_query/libduckdb_pg_query.a  third_party/re2/libduckdb_re2.a  third_party/miniz/libduckdb_miniz.a  third_party/hyperloglog/libduckdb_hyperloglog.a  third_party/fastpforlib/libduckdb_fastpforlib.a  third_party/skiplist/libduckdb_skiplistlib.a  third_party/yyjson/libduckdb_yyjson.a  third_party/mbedtls/libduckdb_mbedtls.a  /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libssl.a  /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a  -ldl && :
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x79): undefined reference to `inflate'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0x102): undefined reference to `deflate'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0x13d): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0x146): undefined reference to `deflateEnd'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x224): undefined reference to `inflateInit_'
/usr/bin/ld: c_zlib.c:(.text+0x28d): undefined reference to `deflateInit_'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x490): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x58c): undefined reference to `zError'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x818): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x8ce): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0x949): undefined reference to `deflateInit_'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_read':
c_zlib.c:(.text+0xa11): undefined reference to `inflate'
/usr/bin/ld: c_zlib.c:(.text+0xaa6): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0xaf6): undefined reference to `inflateInit_'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_oneshot_expand_block':
c_zlib.c:(.text+0xb7c): undefined reference to `uncompress'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_oneshot_compress_block':
c_zlib.c:(.text+0xbfc): undefined reference to `compress'
/usr/bin/ld: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/openssl-3.3.1-7sxcoluipecouv7g2zxjpl2clc4d26ey/lib64/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xc5e): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xc85): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
[783/789] Linking CXX shared library src/libduckdb.so
[784/789] Building CXX object test/api/capi/CMakeFiles/test_sql_capi.dir/ub_test_sql_capi.cpp.o
```
----
Verdict, AFAICS:
----
The static `openssl` fails because this `libcrypto.a` needs libz.a but `.a` files have no way to declare inter-library dependencies to the linker, so either `pkgconfig` has to be used to get the needed `libs` from the `ssl.pc` file, or add `-lz` to the library linker flags, and of course, I think a `depends_on("zlib-api", when="+static_openssl")` will be needed in this case too.

**Review by bernhardkaindl — APPROVED** [review]
## Passed building duckdb+static_openssl:
Build results on Ubuntu 22.04.4 LTS:
```py
Passed:
duckdb@1.1.1
duckdb+extension_autoload
duckdb+extension_autoinstall
duckdb+extension_repo
duckdb+autocomplete
duckdb+tpce
duckdb+tpch
duckdb+python
duckdb+static_openssl
spack find -v:
bin/spack find -v duckdb@1.1.1 duckdb+extension_autoload duckdb+extension_autoinstall duckdb+extension_repo duckdb+autocomplete duckdb+tpce duckdb+tpch duckdb+python duckdb+static_openssl
-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce+tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl+tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python+static_openssl~tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel~extension_autoinstall+extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
duckdb@1.1.1+autocomplete+cli+excel+extension_autoinstall~extension_autoload+extension_repo+fts+httpfs~icu+inet+json+ninjabuild+parquet+python~static_openssl~tpce~tpch build_system=makefile
```
Generated by:
https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py

**Pull request merged**
