### PR TITLE
OpenMPI + ssh

### PR DESCRIPTION
**Pull request by haampie**
Adds `openssh` as a runtime dependency to OpenMPI.

I've checked and even when you build with slurm support `ompi_info | grep rsh` lists rsh support (which uses ssh and then rsh from PATH by default according to some docs)

Also bumps some versions of dependencies of all this.

### CODE REVIEW

**Comment by haampie** [comment]
Apparently this hits a bug in spack graph

**Comment by tldahlgren** [comment]
Closing and re-opening in attempt to get past weird documentation error.

**Comment by haampie** [comment]
@tldahlgren tests pass again

**Comment by alalazo** [comment]
@hppritcha Could you please have a quick look?

**Comment by haampie** [comment]
One more ping @hppritcha

**Comment by sethrj** [comment]
This could be improved with an `external` find for `openssh`...

EDIT: https://github.com/spack/spack/pull/22445

**Review by sethrj — APPROVED** [review]
Looks good to me. Do we need an official OpenMPI maintainer approval? @hppritcha

**Comment by hppritcha** [comment]
looks good to me from Open MPI perspective.

**Comment by haampie** [comment]
Thanks! :)

**Pull request merged**
