### PR TITLE
petsc, py-petsc4py: add versions 3.16.3

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Review by eugeneswalker — DISMISSED** [review]
Thank you!

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
Retry..

@spackbot run pipeline

**Comment by balay** [comment]
I guess spackbot doesn't run commands for me.. will just rebase/push this branch to trigger CI [ but this requires re-approval]

**Review by eugeneswalker — APPROVED** [review]

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
