### PR TITLE
Allow py-cryptography to use rust-bootstrap

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a variant to py-cryptography to allow to use rust-bootstrap instead of rust, greatly reducing build time.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@alecbcs would you be able to give some insight here? Basically, we're hoping to find a way of avoiding having to install Rust (which seems to be a pretty substantial installation, esp. in terms of build time) for a couple of packages including py-cryptography. We in turn only want py-cryptography for awscli-v2, so we'd really like to avoid the Rust dependency if possible.

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji FYI

**Review by tldahlgren — APPROVED** [review]
LGTM but will defer to @adamjstewart

**Review by alecbcs — CHANGES_REQUESTED** [review]
Totally agree this'll improve build times, but I'd argue this might be bad for portability. Rust bootstrap really isn't meant to be used as a regular rust toolchain. It vendors in its own openssl and dependencies which won't pick up system preferences and could lead to weird bugs with certs under corporate firewalls.

Could I help you all set up some CI buildcaches instead to solve your build time length concerns?

**Comment by AlexanderRichert-NOAA** [comment]
@alecbcs thanks for your feedback, that's unfortunate but I can see why that's an issue. The problem right now actually is less about the build time and more that I can't get the regular Rust package to build with Intel (https://github.com/spack/spack/issues/41287). We already use build caches (thanks for your offer on that), so if we can get regular Rust working in our Intel stacks, then I think we'll get by.

**Comment by adamjstewart** [comment]
Can you build rust with GCC and then configure Spack to use that instead of installing a new version for each compiler?

**Comment by climbfuji** [comment]
> Can you build rust with GCC and then configure Spack to use that instead of installing a new version for each compiler?

That's a good point. We've yet to explore how to mix compilers in one environment (I simply didn't have the time to look into how to do this the right way). We need something similar for for `ecflow`, too.

**Comment by adamjstewart** [comment]
You can also install Rust without Spack and register it as an external package if you don't care how it was built. That's what I do.

**Comment by climbfuji** [comment]
> You can also install Rust without Spack and register it as an external package if you don't care how it was built. That's what I do.

Hmmm that is what we are trying to avoid. We've got a whole bunch of platforms (see https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html) and every external package we have to maintain means more work. That's why we want to figure out how to build ecflow (and static boost as its build-only dependency) with gcc, regardless of which compiler is used for the entire stack. If we can do the same for rust, then we're good. But if it's too complicated we'll try the external package route (and/or use rust-boostrap in our spack fork for now until we've figured out a solution).

**Comment by AlexanderRichert-NOAA** [comment]
For a number of reasons including what @climbfuji mentioned we want to avoid external packages. I'm working on checking with the Rust developers about the Intel situation. If it turns out that Rust can't be built with Intel, is there some way we could tweak the recipe to use gcc under the hood even though Spack registers the compiler as %intel? Or for that matter, is there some way to build `rust%gcc` in our Intel stack but still ensure that the rest of its dependencies are %intel (assuming that would even work, namely with openssl and any possible intel-specific functions)? The issue I've run into in the past with trying to have an individual package use, say, %gcc in an otherwise %intel stack is that Spack (understandably) tends to want to make the dependencies %gcc as well.

**Comment by adamjstewart** [comment]
Could we add:
```python
conflicts("%intel")
```
to `rust`? I think that would allow you to build `py-cryptography %intel` and get basically everything in the DAG to use Intel except for `rust%gcc`.

**Comment by AlexanderRichert-NOAA** [comment]
@adamjstewart unfortunately that has the effect of making some of the dependencies also use gcc. With a root spec of `py-cryptography%intel` and adding `conflicts("%intel")` (or `requires("%gcc")`), I get:
```console
 -   qkrl3ro      ^rust@1.70.0%gcc@8.5.0~analysis+clippy~docs+rustfmt+src build_system=generic arch=linux-centos8-zen
 -   ks2id2w          ^cmake@3.23.1%intel@2021.10.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-centos8-zen
 -   pp7pk3f          ^libgit2@1.7.0%intel@2021.10.0~curl~ipo+mmap+ssh build_system=cmake build_type=Release generator=make https=system arch=linux-centos8-zen
 -   bpip5ht              ^libssh2@1.11.0%intel@2021.10.0+shared build_system=autotools crypto=openssl patches=011d926 arch=linux-centos8-zen
 -   spvivze              ^pcre@8.45%intel@2021.10.0~jit+multibyte+utf build_system=autotools arch=linux-centos8-zen
 -   j2zf65t          ^ninja@1.11.1%gcc@8.5.0+re2c build_system=generic arch=linux-centos8-zen
 -   icsfgql              ^re2c@2.2%gcc@8.5.0 build_system=generic arch=linux-centos8-zen
 -   3eihuc6          ^rust-bootstrap@1.70.0%gcc@8.5.0 build_system=generic arch=linux-centos8-zen
 ```

**Comment by adamjstewart** [comment]
Is that an issue as long as everything builds?

**Comment by AlexanderRichert-NOAA** [comment]
I think we've navigated these same issues for other packages when it comes to managing our compilers through the use of prefer/require/etc. I have a PR in for creating the appropriate conflicts in the rust package (#46756), so I'm closing this PR.

**Pull request closed without merging**
