### PR TITLE
Emacs: adding dependencies to be able to build without the system libs

### PR DESCRIPTION
**Pull request by nrichart**

### CODE REVIEW

**Comment by tgamblin** [comment]
I think the better way to do this would be to leave the deps and use `packages.yaml` to indicate where the system deps are.  Spack would at least then record where they came from... what do you think?

**Comment by nrichart** [comment]
I agree but I didn't want to break the package for those who already use it.
This also demand to have xpm et gif in spack to be able to compile the same way with external or internal dependencies.

**Comment by adamjstewart** [comment]
It shouldn't be too hard to write packages for those, right? Those packages would probably be useful as dependencies for other packages as well.

**Comment by nrichart** [comment]
In fact after my message I did it I just did not commit since I want to test some part a bit more.

**Comment by tgamblin** [comment]
Thanks!

**Pull request merged**
