### PR TITLE
mysql: add v8.0.35, fix build

### LINKED ISSUE #41131: Installation issue: mysql
### Steps to reproduce the issue

```console
$ spack spec mysql
...
-   mysql@8.0.29%gcc@11.2.0~client_only~ipo build_system=cmake build_type=Release cxxstd=14 generator=make arch=linux-centos7-haswell
[+]      ^bison@3.8.2%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]          ^diffutils@3.9%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]          ^gettext@0.22.3%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-centos7-haswell
[+]              ^libxml2@2.10.3%gcc@11.2.0+pic~python+shared build_system=autotools arch=linux-centos7-haswell
[+]              ^tar@1.34%gcc@11.2.0 build_system=autotools zip=pigz arch=linux-centos7-haswell
[+]                  ^pigz@2.7%gcc@11.2.0 build_system=makefile arch=linux-centos7-haswell
[+]          ^m4@1.4.19%gcc@11.2.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-centos7-haswell
[+]              ^libsigsegv@2.14%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]          ^perl@5.38.0%gcc@11.2.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-centos7-haswell
[+]              ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-haswell
[+]              ^gdbm@1.23%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]      ^boost@1.77.0%gcc@11.2.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~
graph_parallel~icu+iostreams~json+locale+log+math~mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+sign
als~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave build_system=generic cxxstd=14 patches=48496
71,a440f96 visibility=hidden arch=linux-centos7-haswell
[+]          ^bzip2@1.0.8%gcc@11.2.0~debug~pic+shared build_system=generic arch=linux-centos7-haswell
[+]          ^xz@5.4.1%gcc@11.2.0~pic build_system=autotools libs=shared,static arch=linux-centos7-haswell
[+]          ^zlib-ng@2.1.4%gcc@11.2.0+compat+opt build_system=autotools arch=linux-centos7-haswell
[+]          ^zstd@1.5.5%gcc@11.2.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-haswell
[+]      ^cmake@3.27.7%gcc@11.2.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-centos7-haswell
[+]          ^curl@8.4.0%gcc@11.2.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=
linux-centos7-haswell
[+]              ^nghttp2@1.57.0%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]      ^doxygen@1.9.6%gcc@11.2.0~graphviz~ipo~mscgen build_system=cmake build_type=Release generator=make arch=linux-centos7-haswell
[+]          ^flex@2.6.3%gcc@11.2.0+lex~nls build_system=autotools arch=linux-centos7-haswell
[+]              ^findutils@4.9.0%gcc@11.2.0 build_system=autotools patches=440b954 arch=linux-centos7-haswell
[+]          ^libiconv@1.17%gcc@11.2.0 build_system=autotools libs=shared,static arch=linux-centos7-haswell
[+]          ^python@3.11.6%gcc@11.2.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl
~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-centos7-haswell
[+]              ^expat@2.5.0%gcc@11.2.0+libbsd build_system=autotools arch=linux-centos7-haswell
[+]                  ^libbsd@0.11.7%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]                      ^libmd@1.0.4%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]              ^libffi@3.4.4%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]              ^libxcrypt@4.4.35%gcc@11.2.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-centos7-haswell
[+]              ^readline@8.2%gcc@11.2.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-haswell
[+]              ^sqlite@3.43.2%gcc@11.2.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-haswel
l
[+]              ^util-linux-uuid@2.38.1%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]      ^gmake@4.4.1%gcc@11.2.0~guile build_system=generic arch=linux-centos7-haswell
[+]      ^libedit@3.1-20210216%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]      ^libtirpc@1.3.3%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]          ^krb5@1.20.1%gcc@11.2.0+shared build_system=autotools arch=linux-centos7-haswell
[+]      ^ncurses@6.4%gcc@11.2.0~symlinks+termlib abi=none build_system=autotools arch=linux-centos7-haswell
[+]      ^openssl@3.1.3%gcc@11.2.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-haswell
[+]          ^ca-certificates-mozilla@2023-05-30%gcc@11.2.0 build_system=generic arch=linux-centos7-haswell
[+]      ^pkgconf@1.9.5%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
[+]      ^rpcsvc-proto@1.4.3%gcc@11.2.0 build_system=autotools arch=linux-centos7-haswell
```

### Error message

<details><summary>Error message</summary>

<pre>
...
</pre></details>
==> Error: ProcessError: Command exited with status 1:
...
1 error found in build log:
     377    Make sure you have specified a supported SSL version.
     378    Valid options are :
     379    system (use the OS openssl library),
     380    yes (synonym for system),
     381    </path/to/custom/openssl/installation>
     382    
  >> 383    CMake Error at cmake/ssl.cmake:73 (MESSAGE):
     384      Please install the appropriate openssl developer package.
     385    
     386    Call Stack (most recent call first):
     387      cmake/ssl.cmake:331 (FATAL_SSL_NOT_FOUND_ERROR)
     388      CMakeLists.txt:1688 (MYSQL_CHECK_SSL)

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.11.6
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### Additional information

  cmake/boost.cmake:206 (COULD_NOT_FIND_BOOST)
  CMakeLists.txt:1467 (INCLUDE)
-- Configuring incomplete, errors occurred!
(py3.11) -bash-4.2$tail -n35 /tmp/nma8kk/spack-stage/spack-stage-mysql-8.0.29-fv3qxkcg5zwkzet36mfmkdaaqmxadrpz/spack-build-out.txt
-- Performing Test C_LD_LLD_RESULT
-- Performing Test C_LD_LLD_RESULT - Failed
-- Performing Test CXX_LD_LLD_RESULT
-- Performing Test CXX_LD_LLD_RESULT - Failed
-- Performing Test C_LD_GOLD_RESULT
-- Performing Test C_LD_GOLD_RESULT - Success
-- Performing Test CXX_LD_GOLD_RESULT
-- Performing Test CXX_LD_GOLD_RESULT - Success
-- WITH_BOOST=/sfs/qumulo/qhome/nma8kk/libs/spack/opt/spack/linux-centos7-haswell/gcc-11.2.0/boost-1.77.0-gbxkmzaet4guf3ynw3bsunzqiqub5epr
-- BOOST_INCLUDE_DIR 
-- LOCAL_BOOST_DIR LOCAL_BOOST_DIR-NOTFOUND
-- LOCAL_BOOST_ZIP LOCAL_BOOST_ZIP-NOTFOUND
-- Could not find (the correct version of) boost.
-- MySQL currently requires boost_1_77_0
CMake Error at cmake/boost.cmake:108 (MESSAGE):
  You can download it with -DDOWNLOAD_BOOST=1 -DWITH_BOOST=<directory>
  This CMake script will look for boost in <directory>.  If it is not there,
  it will download and unpack it (in that directory) for you.
  You can also download boost manually, from
  https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2
  If you are inside a firewall, you may need to use an https proxy:
  export https_proxy=http://example.com:80
Call Stack (most recent call first):
  cmake/boost.cmake:206 (COULD_NOT_FIND_BOOST)
  CMakeLists.txt:1467 (INCLUDE)
-- Configuring incomplete, errors occurred!

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alalazo**
fixes #41131

- [x] Add support for Spack built zlib, libevent, openssl, lz4, zstd

### CODE REVIEW

**Comment by alalazo** [comment]
@EbiArnie

**Comment by EbiArnie** [comment]
Would you like me to do a review or become maintainer?

As for the change: Looks sensible. Builds and works for me, mysql_config has the right (Spack) dependencies.
Built with linux-ubuntu22.04-x86_64_v3/gcc-11.4.0, mysql 8.0.35.

**Comment by alalazo** [comment]
> Would you like me to do a review or become maintainer?

Sure, feel free to push to the branch

**Review by EbiArnie — APPROVED** [review]
OK

**Review by haampie — APPROVED** [review]

**Pull request merged**
