### PR TITLE
cvise: new package

### PR DESCRIPTION
**Pull request by heerener**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the branch and tag exist.

**Comment by tldahlgren** [comment]
@olupton Are you okay with being tagged as the Spack maintainer (see https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers) of this package?

**Comment by tldahlgren** [comment]
@heerener Not sure if it is relevant to your package, but are you aware of the `extends()` feature related to Python capabilities?

We have documentation at https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pythonpackage-vs-packages-that-use-python.  The discussion of `extends` vs `depends_on` is at https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#extends-vs-depends-on.

**Comment by heerener** [comment]
> @heerener Not sure if it is relevant to your package, but are you aware of the `extends()` feature related to Python capabilities?
> 
> We have documentation at https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pythonpackage-vs-packages-that-use-python. The discussion of `extends` vs `depends_on` is at https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#extends-vs-depends-on.

I was not, so thank you for pointing this out!

I think in this case there's no need to extend - as far as I can tell cvise is a tool that happens to be written in (among others) Python, rather than something that will be imported.

**Comment by heerener** [comment]
> @olupton Are you okay with being tagged as the Spack maintainer (see https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers) of this package?

Apparently the maintainer role was more for internal, so I've removed him.

**Review by tldahlgren — APPROVED** [review]
LGTM.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
