### PR TITLE
FastJet: new versions (3.3.4, 3.4.0), new variants (thread safety, python), allow selecting individual plugins

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Review by vvolkl — DISMISSED** [review]

**Review by vvolkl — APPROVED** [review]

**Comment by vvolkl** [comment]
@iarspider This is not working for me, due to the fetcher failing for the tarballs (see https://github.com/spack/spack/issues/20050). I'm wondering how you even managed to checksum those? What setup were you using when you did it?

**Comment by vvolkl** [comment]
Also, supersedes https://github.com/spack/spack/pull/22667/files

**Comment by iarspider** [comment]
@vvolkl I have downloaded the tarballs outside of Spack

**Review by vvolkl — CHANGES_REQUESTED** [review]
Fetcher fails for the newly added versions

**Comment by vvolkl** [comment]
Ah, so https://github.com/spack/spack/pull/20064 needs  to be merged first. @alalazo @tgamblin @tldahlgren @adamjstewart could I request a review for that?

**Pull request closed without merging**
