### PR TITLE
[libunistring] Latest release needs std=c18 for icc

### PR DESCRIPTION
**Pull request by stephenmsachs**

### CODE REVIEW

**Comment by stephenmsachs** [comment]
Apparently `libunistring@.1.1` installs on aarch64 with `gcc@7.3.1` just fine. This does not have any `c18` support. Need to dig some more.

**Review by bernhardkaindl — COMMENTED** [review]
@stephenmsachs CI/codecov fails because the lines you added are not covered in CI. You'll need to get some help with more knowledge.

Check `git log lib/spack/spack/compilers/intel.py` to see who changed this files and ask them for help by pinging them here with @name or join the Spack slack, you might find them there and you can ask in the Slack.

**Comment by stephenmsachs** [comment]
Thanks @bernhardkaindl . The tests seem straightforward. I added some myself, let's see if this is correct.

**Review by bernhardkaindl — APPROVED** [review]

**Comment by haampie** [comment]
I'm uncomfortable with -std=c18, given that it's rather C17, and it's a minor revision to C11; I believe most compilers include the fixes of C17 in -std=c11. Intel compilers probably as well?

**Review by bernhardkaindl — DISMISSED** [review]
@stephenmsachs 

As c18 is only requested with `icc` and `icc` supports it since `oneapi` 2022, which is classic version 2021.5.0, I see no problem.

However, there is now a conflict in `lib/spack/spack/compilers/intel.py`.

Can you resolve the conflict and them mention me again in a comment with @bernhardkaindl?

**Comment by stephenmsachs** [comment]
Thanks @bernhardkaindl. The conflict stems from Intel adding more C++17 suppport in v19, I was only looking for single argument `static_assert` support. Let's use the version in `develop`.

**Comment by stephenmsachs** [comment]
@bernhardkaindl is there anything left to do before we can merge?

**Review by bernhardkaindl — APPROVED** [review]
@stephenmsachs As I see your affiliation, and it's now 4 months, I assume you tested/used this long enough that I hope that it's fine.

**Comment by haampie** [comment]
@bernhardkaindl

> As I see your affiliation, and it's now 4 months

Neither are arguments for merging this. You should have asked me.

**Pull request merged**
