### PR TITLE
Add `$date` option to the list of config variables

### PR DESCRIPTION
**Pull request by psakievich**
I'm finding I often want the date in my paths and it would be nice if spack had a config variable for this.

### CODE REVIEW

**Comment by tldahlgren** [comment]
Looks like a couple of pipeline stacks and the ubuntu/33.11, clingo, false had connectivity issues.  The unit test's output:

```
...
Run pip install --upgrade pip six setuptools pytest codecov[toml] pytest-xdist 
[21](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:22)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages (22.3)
[22](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:23)
Collecting pip
[23](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:24)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc5f0ab90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl
[24](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:25)
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc6044710>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl
[25](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:26)
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc77c7ad0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl
[26](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:27)
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc5f0d8d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl
[27](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:28)
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc5f0e3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl
[28](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:29)
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7febc5f0ea50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[29](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:30)

[30](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:31)

[31](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:32)
Notice:  A new release of pip available: 22.3 -> 22.3.1
[32](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:33)
Notice:  To update, run: pip install --upgrade pip
[33](https://github.com/spack/spack/actions/runs/3455558512/jobs/5767693486#step:5:34)
Error: Process completed with exit code 1.
...
```

**Comment by tldahlgren** [comment]
Trying `Update branch` button to force re-running the checks.

**Review by tldahlgren — APPROVED** [review]
LGTM.

**Comment by psakievich** [comment]
Thanks for the quick review @tldahlgren!

**Comment by kwryankrattiger** [comment]
@spackbot run pipeline

**Pull request merged**
