### PR TITLE
Create bash-like chmod() method in llnl.util.filesystem

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
Is there any specific reason to have this utility function, i.e. any application of it that will be committed later?

**Comment by iarspider** [comment]
Well, I'd say it is a universally useful function. Also yes, it will be used in a follow-up PR.

**Comment by alalazo** [comment]
> Well, I'd say it is a universally useful function. Also yes, it will be used in a follow-up PR.

@iarspider I have maintainability concerns merging a function in a core Spack module that is never used.  Also, I think many related functions in `llnl.util.filesystem` rely on `os.chmod` to implement more specific actions e.g. see `unset_executable_mode` that are then invoked in other places. This is just to say that at the moment it's difficult to understand where this would be useful. 

Can we turn this into a draft and push the commit of the follow-up PR here? Maybe having more context this will be clear.

**Comment by iarspider** [comment]
Sure. The idea is to have a pre-exitsing recursive chmod function. This is needed for a better tensorflow recipe (better = uses external dependencies instead of bundling them), in which at one stage one needs to rerun `protoc`, and we need to make sure we can write the updated source files.

**Pull request closed without merging**
