### PR TITLE
py-anvio: new package and deps

### PR DESCRIPTION
**Pull request by alex391**
Status of the review by @bernhardkaindl: Looks good, with some suggestions (e.g. add licences)

@alex391: If you add the licences, and you would be fine to get invited for review here when someone opens a PR for these packages, would you be open to add yourself as maintainer for these packages as well (see below - if not could you ask the developers of the package if they are fine with to get invited for review) ?
```py
maintainers("alex391", "meren")
```
@meren?

### CODE REVIEW

**Review by bernhardkaindl — DISMISSED** [review]
@alex391 
Checked with the requirements defined in https://github.com/merenlab/anvio/blob/master/requirements.txt - that looks good to me.

They only added `bulp==2.7.0` because of https://github.com/snakemake/snakemake/issues/2607 when snakemake v7 is used. It's not an anvi'o issue but of `snakemake`. 
According to the 
```py
depends_on("py-pulp@2.3.1:2.8", type=("build", "run"), when="@8.1.2:")
```
in `snakemake/package.py` that is solved in `snakemake` v8.



For this, we could add
```py
depends_on("py-pulp@:2.7", type=("build", "run"), when="@:7")
```
to snakemake's package.py, but this does not have to be added in the PR.

Other than that, https://github.com/merenlab/anvio/issues/2305 suggests that apparently the range for scikit-learn may be scikit-learn@1.1.0:1.2.2, but the fixed scikit-learn@1.2.2 may be safer.

I wonder if pinning the version of panda to a single version is really needed. I assume it should at least be a range of panda versions.

```py
license("GPL-3.0-or-later")
```
could be added to anvio's package.py and also a license for py-rich-argparse.

These are just suggestions. The license flags should be easy to do.

**Review by bernhardkaindl — COMMENTED** [review]
@alex391: If you add the licences, and you would be fine to get invited for review here when someone opens a PR for these packages, would you be open to add yourself as maintainer for these packages as well (see below - if not could you ask the developers of the package if they are fine with to get invited for review) ?
```py
maintainers("alex391", "meren")
```
@meren, fine by you? - Do you know if a range of panda versions works with v8?

**Comment by meren** [comment]
Hi everyone,

I'm sorry that I just saw these exchanges only today, and missed the first message 2 weeks ago that had a question for me.

> @meren, fine by you? - Do you know if a range of panda versions works with v8?

Yes, I'm fine to be included as a maintainer here. I'm not familiar with spack, but this would be a good reason to start getting familiar with it.

I'd say a range of panda versions should work with v8 in theory, but we didn't test them. Hopefully at some point soon we will do it and figure out if there are things need to be changed in anvi'o code for newer versions of it. But to be on the safe side I'd stick with the version mentioned in the requirements.txt.


Best wishes,

**Comment by alex391** [comment]
I'm OK being made maintainer for this, although I don't know *that* much about anvi'o. Should it be GPL-3.0-or-later or GPL-3.0-only? I always struggle to tell the difference.

**Comment by bernhardkaindl** [comment]
> I'm OK being made maintainer for this, although I don't know _that_ much about anvi'o.
Great, and thanks as well to @meren for his kind response.

> Should it be GPL-3.0-or-later or GPL-3.0-only? I always struggle to tell the difference.

With the caveat of IANAL, this is my understanding:
The GPL licence text itself contains the wording "or any later version" (or similar).
Unless the distributed software or source does not mention (or append) a restriction telling that "only" GPL v3 may be used, the "or any later version" from the licence applies.

The only difference of being listed in `maintainers =` is that `spackbot` will invite you for review if someone opens a PR for `py-anvio`. If you use the package, it gives you a heads-up that someone likes to make a modification, and `spack` maintainers are giving you about a week (sometimes even longer, especially if you ask for it) to approve or comment on the change. If someone opens an issue in `spack` for the build of `py-anvio`, you might get assigned to the issue, but this is only informational, you are not obligated to anything.

I'm glad that not just you but also agreed to be mentioned in the recipe, and of course you can submit a PR to remove your GitHub handle anytime. With that, I'm not further nitpicking on the licence setting (it can be added on the next update or anytime later) and I'm going to approve it.

PS: I may try to build the package and see how that goes.

**Comment by meren** [comment]
In the case of anvi'o it is fine to keep GPL-3.0 only.


Best wishes,

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
