### PR TITLE
trinity: adding version 2.15.1

### PR DESCRIPTION
**Pull request by snehring**
New version + a patch to make it compile.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
@downloadico Would you be interested in commenting on this PR since you recently made a significant change to this package?

**Comment by snehring** [comment]
@tldahlgren Can we go ahead and merge this?

**Comment by downloadico** [comment]
> @downloadico Would you be interested in commenting on this PR since you recently made a significant change to this package?

Sure.

I think the changes look good!   

Would it be better to use Spack's file filtering to change "`#include <string.h>`" to "`#include <string>`", should the authors fail to fix the issue the patch addresses?  I think this issue has existed for some time.

Jim

**Comment by snehring** [comment]
They've already patched this upstream, so future versions should be fine wrt this particular patch. It probably is relevant on older versions as well, but I actually couldn't compile them with my compiler to test. Older compilers are less strict about this particular issue (I'm not sure when gcc started grouching about it tbh).

**Comment by snehring** [comment]
Just checked. Weirdly, the version of bamsifter that ships in 2.14.0 (the older version I can build) has string instead of string.h, I guess with the version in 2.15.0 they pulled out cstring and incorrectly replaced string with string.h.

**Comment by downloadico** [comment]
> They've already patched this upstream, so future versions should be fine wrt this particular patch. It probably is relevant on older versions as well, but I actually couldn't compile them with my compiler to test. Older compilers are less strict about this particular issue (I'm not sure when gcc started grouching about it tbh).



> Just checked. Weirdly, the version of bamsifter that ships in 2.14.0 (the older version I can build) has string instead of string.h, I guess with the version in 2.15.0 they pulled out cstring and incorrectly replaced string with string.h.

That makes sense.  ugh, developers ;) .  

I hope this gets merged soonish. :)

**Comment by snehring** [comment]
@tldahlgren I think it's alright to go ahead and merge this

**Pull request merged**
