### PR TITLE
New package: glab

### PR DESCRIPTION
**Pull request by wyphan**
Adds a Spack recipe for building [GitLab CLI](https://gitlab.com/gitlab-org/cli). Spack maintainers wanted!

### CODE REVIEW

**Comment by haampie** [comment]
can you give it a sensible name like `gitlab-cli`.

**Comment by wyphan** [comment]
@haampie The executable is called `glab`, just like GitHub CLI is `gh` (and the package is also named such)

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
> @haampie The executable is called `glab`, just like GitHub CLI is `gh` (and the package is also named such)

That's a good point.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
