### PR TITLE
Fix the general case URL for the zlib tarball

### PR DESCRIPTION
**Pull request by hartzell**
A recent pull request jiggled this around, but now it tries to download 1.2.10 from Canonical, which doesn't work.

@tgamblin -- I'm testing this now.  Will follow up if/when it's ready to go.

### CODE REVIEW

**Comment by hartzell** [comment]
@tgamblin -- this works for 1.2.8 and 1.2.10.  Not sure that it's 'tasteful' however.

**Comment by adamjstewart** [comment]
@tgamblin This looks like a major bug. I've never seen a version-specific `url` override a package-specific `url` for a different version.

**Comment by hartzell** [comment]
By way of documentation (he's from Missouri, you have to *show* him...):

```
==> Installing zlib
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.10.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.10.tar.gz
==> Fetching from http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.10.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.10.tar.gz failed.
==> Error: FetchError: All fetchers failed for zlib-1.2.10-rwkggjpl7lc44azepv6khazzdds3dfbs
Build step 'Execute shell' marked build as failure
```

**Comment by adamjstewart** [comment]
You can also see what URLs Spack will use by running:
```
$ spack info zlib
...
    1.2.10    http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.10.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.10.tar.gz
    1.2.8     http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.8.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.8.tar.gz
```
Btw, I'm not seeing this with other packages:
```
$ spack info py-scipy
...
    0.18.1    https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.18.1.tar.gz
    0.17.0    https://pypi.python.org/packages/source/s/scipy/scipy-0.17.0.tar.gz
    0.15.1    https://pypi.python.org/packages/source/s/scipy/scipy-0.15.1.tar.gz
    0.15.0    https://pypi.python.org/packages/source/s/scipy/scipy-0.15.0.tar.gz
```

**Comment by adamjstewart** [comment]
More debugging info. If you hack `py-scipy` to look like:
```python
    version('0.19.0', 'fake-version-and-hash-0123456789')                                               
    version('0.18.1', '5fb5fb7ccb113ab3a039702b6c2f3327',                       
            url="https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.18.1.tar.gz")
    version('0.17.0', '5ff2971e1ce90e762c59d2cd84837224')                       
    version('0.15.1', 'be56cd8e60591d6332aac792a5880110')                       
    version('0.15.0', '639112f077f0aeb6d80718dc5019dc7a')   
```
you can reproduce this bug:
```
$ spack info py-scipy
...
    0.19.0    https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.19.0.tar.gz
    0.18.1    https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.18.1.tar.gz
    0.17.0    https://pypi.python.org/packages/source/s/scipy/scipy-0.17.0.tar.gz
    0.15.1    https://pypi.python.org/packages/source/s/scipy/scipy-0.15.1.tar.gz
    0.15.0    https://pypi.python.org/packages/source/s/scipy/scipy-0.15.0.tar.gz
```

**Comment by hartzell** [comment]
I'm out of my depth....

**Comment by adamjstewart** [comment]
Btw, reordering:
```python
    version('1.2.10', 'd9794246f853d15ce0fcbf79b9a3cf13')   
    version('1.2.8', '44d667c142d7cda120332623eab69f40',                        
            url='http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.8.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.8.tar.gz'
           )
```
as:
```python
    version('1.2.8', '44d667c142d7cda120332623eab69f40',                        
            url='http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.8.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.8.tar.gz'
           )                                                                    
    version('1.2.10', 'd9794246f853d15ce0fcbf79b9a3cf13')   
```
doesn't help.

**Comment by hartzell** [comment]
> a perfectly fine hack for now

That's a perfect saying for either
- a business card
- a tombstone

:)

**Comment by citibeth** [comment]
I'm wondering if this is related to the impenetrable `FetchStrategy` code.

**Comment by citibeth** [comment]
I think we need to have the general class-wide URL set to the fossils directory, and the latest-version URL specially set for the non-fossil directory.  Is it OK to close this PR?

**Comment by hartzell** [comment]
Yes, close it (I see that you already have...).

In the ongoing search for a local minima for the zlib package, #2735 uses the zlib fossil site....

**Pull request closed without merging**
