### PR TITLE
fixed libxcb deps and added patch to remove pthread-stubs dep

### PR DESCRIPTION
**Pull request by lee218llnl**
These changes were needed to build on a TOSS3 (RHEL7) based system.

### CODE REVIEW

**Comment by nrichart** [comment]
This should also help to build `qt`. I was working on something similar, will trying to install `paraview`

**Comment by davydden** [comment]
something similar is done in https://github.com/LLNL/spack/pull/820, but that PR is inactive for about a month.

**Comment by luigi-calori** [comment]
I had similar problem. I tried to use #820 and found some problems.
I have some patches but not know how to contribute to an open PR, especially now that  seems that PR are accumulating and no merge happen.
Would it make sense to have a branch dedicated to ParaView / Qt  that we keep in sync with  develop and integrate #820 and move on?

I would like to use spack for building different flawors of ParaView: does it make sense to try to contribute here or is better to just use my private copy of packages?

Thanks

**Comment by davydden** [comment]
@luigi-calori you can't contribute to an open PR unless github user grants you write access to his fork. I think it is always better to fix things upstream in Spack. My guess is that this PR will be merged faster than #820 so perhaps one could wait a bit (with a hope that PRs start merging again soon :smile:) and then open a follow up PR with the changes you have.

**Comment by luigi-calori** [comment]
Thanks. I' ll try to work on other stuff... Nevertheless, I' m quite worried about the lack of merging:
I currently already need some PR that I keep integrating locally: #984 #797 #579 #946
They can currently be merged without conflicts now and I can safely use them even if not merged. Unfortunately  #820 would be useful but is not ready to be used as is and I need to patch it, 

If the rate between PR submission / PR merging  keeps increasing, contributing would be harder and more effort should be dedicated to merging.
would make sense to set up an intermediate merging layer?
Could we set up some thematic integration PR where specific feature are addressed and the  mantainer of the PR keeps the PR in sync with develop while accepting PR-PR from contribution? 
I' m a git newbie so maybe this is just nonsense...

**Comment by tgamblin** [comment]
@lee218llnl @luigi-calori can you see if the current `develop` branch works for you?  I actually ended up doing this myself, though I added `pthread-stubs` as a package, which is slightly different.  If it does, this PR may not be needed.  Sorry I didn't track this closely enough

**Comment by lee218llnl** [comment]
@tgamblin The latest develop branch worked for me. I am OK with deleting/closing this PR, but we may want to wait for confirmation from @luigi-calori

**Comment by tgamblin** [comment]
@luigi-calori: I'll close this if the latest dev branch works for you.

**Comment by tgamblin** [comment]
@luigi-calori: please reopen if this issue regresses.

**Pull request closed without merging**
