### PR TITLE
gmake: add v4.4.1

### PR DESCRIPTION
**Pull request by alecbcs**
Add GMake v4.4.1.

**Changelog:**
https://lists.gnu.org/archive/html/info-gnu/2023-02/msg00011.html

### CODE REVIEW

**Comment by haampie** [comment]
I've cherry-picked af8a134828f0db9c772e7446c6b8135fa0bcf499 because it's been stuck in CI forever, let's see if this PR makes it through Gitlab.

**Review by haampie — APPROVED** [review]

**Review by tldahlgren — COMMENTED** [review]
FWIW. Confirmed the sha256.  (Did that before realizing PR already commented on.)

**Comment by haampie** [comment]
@spackbot rerun pipeline

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot rerun pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by alecbcs** [comment]
Merging with latest develop to test @scottwittenburg's latest changes to CI pruning!

**Comment by haampie** [comment]
smart idea :laughing:

**Comment by alecbcs** [comment]
@spackbot run pipeline 🥺

**Comment by alecbcs** [comment]
@spackbot run pipeline 😭

**Pull request merged**
