### PR TITLE
perl: add missing berkeley-db dependency

### PR DESCRIPTION
**Pull request by aweits**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM.

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Comment by AndrewGaspar** [comment]
Hm... does perl always depend on berkeley-db? I'm having issues building berkeley-db on Mac right now with a MacPorts install of clang@9.0.1

**Comment by aweits** [comment]
> Hm... does perl always depend on berkeley-db? I'm having issues building berkeley-db on Mac right now with a MacPorts install of clang@9.0.1

A few things seem to pop out here. gdbm and db should probably be variants (but with the default set to yes). Is the berkeley-db issue this one?

https://trac.macports.org/ticket/53577
fixed by this:
https://github.com/macports/macports-ports/commit/cb92cb90bdc7fb90212e928db32172546eca0f5b

**Comment by AndrewGaspar** [comment]
Yeah, it looks like it.

**Comment by adamjstewart** [comment]
I'm also having issues building berkeley-db on macOS with the system Apple Clang. Do we just need to add a patch to the `berkeley-db` package? Do the variants have to default to True?

**Comment by adamjstewart** [comment]
It looks like there are much newer versions available, going to try adding those and hopefully they won't need any patch.

**Pull request merged**
