### PR TITLE
Remove weird rocm version of BLT

### PR DESCRIPTION
**Pull request by white238**
it was a very broken time in BLT's develop history and cannot be trusted.

### CODE REVIEW

**Comment by white238** [comment]
@eugeneswalker Not only was I able to reproduce your problem. This branch also made it go away for me at least.

**Comment by eugeneswalker** [comment]
I just tried building `axom@0.4.0` and all dependencies from source, in a fresh container, and got a bunch of errors like this during the axom build stage:

```
$> spack install --no-cache -f ./axom.spec.yaml
...
==> Installing axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx
...
     797
     798      * The installation package was faulty and references files it does not
     799      provide.
     800
     801
     802
  >> 803    CMake Error in tools/CMakeLists.txt:
     804      Imported target "conduit::conduit" includes non-existent path
     805
     806        "/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/include/"
     807
     808      in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
     809

     ...

     813
     814      * The installation package was faulty and references files it does not
     815      provide.
     816
     817
     818
  >> 819    CMake Error in tools/CMakeLists.txt:
     820      Imported target "conduit::conduit" includes non-existent path
     821
     822        "/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/include/"
     823
     824      in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
     825
...
```

Container: `ecpe4s/ubuntu20.04-runner-x86_64:2021-03-01` (GCC 9.3.0)
Concrete spec: [axom.spec.yaml.txt](https://github.com/spack/spack/files/6408517/axom.spec.yaml.txt)
Full build log: [axom-build-out.txt](https://github.com/spack/spack/files/6408518/axom-build-out.txt)

Any ideas? I can post this on the corresponding issue page if that's more appropriate. https://github.com/spack/spack/issues/23339

**Comment by white238** [comment]
That's unfortunate. CMake doesn't allow you to have any directories that don't exist in the `INTERFACE_INCLUDE_PROPERTIES` of any imported targets.  Those targets are generated and exported by Conduit and then imported into Axom.  CMake then throws an error in Axom because those directories don't exist.

This is not the first time this has come up (in fact I worked around a very similar issue here: https://github.com/LLNL/serac/pull/456/files)

I can fix this in Axom develop, by stripping any non-existent paths, and create a patch for 0.4.0.

I'd be curious if this went away if you weren't building conduit@develop.  The previous PR i linked though was caused by building on OSX specifically.

**Comment by eugeneswalker** [comment]
> I'd be curious if this went away if you weren't building conduit@develop

Yes! `axom@0.4.0 ^conduit@0.7.1` builds OK!

**Review by becker33 — APPROVED** [review]

**Pull request merged**
