### PR TITLE
zfp: Add version 1.0.0

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Comment by lindstro** [comment]
Coincidentally, we finished our own work on updating the zfp spack package today and will submit a separate PR shortly.  Our PR adds additional variants not included here, so I would suggest closing this PR without merging.

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha256.

**Comment by tldahlgren** [comment]
> Coincidentally, we finished our own work on updating the zfp spack package today and will submit a separate PR shortly. Our PR adds additional variants not included here, so I would suggest closing this PR without merging.

@lindstro So should this PR be closed without merging?

**Comment by lindstro** [comment]
> > Coincidentally, we finished our own work on updating the zfp spack package today and will submit a separate PR shortly. Our PR adds additional variants not included here, so I would suggest closing this PR without merging.
> 
> @lindstro So should this PR be closed without merging?

Yes; please see our own PR, #33452, which needs a round of minor revisions before it's ready to be merged.

**Comment by jrood-nrel** [comment]
Excellent!

**Pull request closed without merging**
