### PR TITLE
Use pcluster-alinux2 container image with pre-installed compilers

### PR DESCRIPTION
**Pull request by stephenmsachs**
Use the intel compiler available under `/bootstrap-compilers/` to speed up the container bootstrap.

### CODE REVIEW

**Comment by alalazo** [comment]
We need to tag the runner image before merging

**Comment by stephenmsachs** [comment]
Re-based to include https://github.com/spack/spack/pull/46712

**Review by alalazo — COMMENTED** [review]
Are there still specs compiled with `%intel`? If not, can we simplify the `packages.yaml`?

**Comment by stephenmsachs** [comment]
> Are there still specs compiled with `%intel`? If not, can we simplify the `packages.yaml`?

There are none in the buildcache. But since this `packages.yaml` is used on the consumer's cluster I leave them. We can remove them later on when there are less people using the classic compilers.

**Comment by stephenmsachs** [comment]
@alalazo do I need to change anything else missing to get this merged?

**Comment by alalazo** [comment]
> But since this packages.yaml is used on the consumer's cluster I leave them. We can remove them later on when there are less people using the classic compilers.

Hmm, I don't 100% agree with this, but let's keep cleaning for another PR. 

The fact is, we are keeping unneeded code in the `spack.yaml` because an external service needs it. The worst part imo is that, if we remove that code, nothing in our CI will fail, since Spack is not affected. There will just be `pcluster` users being affected by that - so the appropriate place for configuration with `%intel` seems external to Spack.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
