### PR TITLE
Add patch to fix bazel build on power9

### LINKED ISSUE #20418: Installation issue: Bazel@0.29
I am trying to build `bazel@0.29.1` on my way to `py-tensorflow@2.1` on `lassen` (`power9`) and running into a lot of issues. First, I ran into [this](https://github.com/bazelbuild/bazel/issues/9263) and ended up creating a patch to fix this. After that, I am running into a linking error -- i think my compiler is set up correctly since this is the only time I see this issue.

Here is the tail of the `spack-build.out` -- also attached
```
ERROR: /var/tmp/bazel_x9NXNCtZ/out/external/bazel_tools/third_party/ijar/BUILD:74:1: Linking of rule '@bazel_tools//third_party/ijar:zipper' failed (Exit 1)
[1,163 / 1,813] 15 actions running
    @com_google_protobuf//:protobuf; 4s local
    @com_google_protobuf//:protobuf; 2s local
    @com_google_protobuf//:protobuf; 2s local
    @com_google_protobuf//:protobuf; 1s local
    @com_google_protobuf//:protobuf; 1s local
    @com_google_protobuf//:protobuf; 1s local
    @com_google_protobuf//:protobuf; 1s local
    @com_google_protobuf//:protobuf; 1s local ...









bazel-out/host/bin/external/bazel_tools/src/main/cpp/util/_objs/filesystem/path_posix.o:path_posix.cc:function blaze_util::SplitPath(std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&, unsigned long, std::allocator<char> const&)'
bazel-out/host/bin/external/bazel_tools/src/main/cpp/util/_objs/filesystem/path_posix.o:path_posix.cc:function blaze_util::SplitPath(std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&, unsigned long, std::allocator<char> const&)'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce the issue

```console
$ spack install -v bazel@0.29.0%gcc@7.3.1
...
```

### Information on your system

```
***Spack:** 0.16.0-2-aed2422ce
***Python:** 3.8.6
***Platform:** linux-rhel7-power9le
```

```
  jdk:
    externals:
    - spec: jdk@1.8 %gcc@7.3.1 arch=linux-rhel7-power9le
      prefix: /usr/lib/jvm/java-1.8.0-openjdk
```

### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/5699656/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/5699657/spack-build-out.txt)

@adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by bhatiaharsh**
@adamjstewart , please take a look at this one.

changes to bazel to make it work on power9 (tested on lassen.llnl)

Fixes #20418

### CODE REVIEW

**Comment by adamjstewart** [comment]
You should be able to remove the changes to `py-tensorflow`. We now create a new unique temporary directory for every install.

**Comment by bhatiaharsh** [comment]
just resolved the conflixt in tf package by removing my changes. should be good to go.

**Comment by adamjstewart** [comment]
Thanks! I'll test the build on macOS to make sure it doesn't break anything.

**Review by adamjstewart — APPROVED** [review]
Builds for me on macOS 10.15.7 with Apple Clang 12.0.0.

**Pull request merged**
