### PR TITLE
Support static case for find_libraries() in xz

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds support for the static case to xz's invocation of `find_library()`. These changes support NOAA/National Weather Service R&D and operational forecasting applications.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot fix style

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot run pipeline

**Comment by AlexanderRichert-NOAA** [comment]
@spackbot run pipeline

**Review by becker33 — APPROVED** [review]

**Comment by becker33** [comment]
@spackbot run pipeline

**Pull request merged**
