### PR TITLE
Scotch fails to build with latest flex

### LINKED ISSUE #2521: flex and scotch conflicts
Hello,

I was trying to install something else that through the chain wanted to install `scotch`.  I originally thought that `scotch` was failing, it had a bunch of `undefined reference to scotchyywrap` stuff going on.  The great google gods led me to [here](http://stackoverflow.com/questions/1811125/undefined-reference-to-yywrap), and I realized it was probably a `flex` conflict.  I really have no idea what these things are doing, but `scotch@6.0.3` could not install using `flex@2.6.2`.  I simply commented out the `2.6.2` version of flex (therefore defaulting to `2.6.1`) and then `scotch@6.0.3` was able to install.

If it means anything, the package that was ultimately installing both of these was `eigen` which came from a complicated `opencv` (test) installation.

If helpful, I am compiling with `gcc 5.3.1`.  Unsure if anybody else is even affected by this, but figured I'd post it in case it's helpful to somebody else somewhere :)

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #2521. Thanks for figuring out the solution @svenevs.

P.S. Somebody should probably file a bug with the Scotch and/or Flex devs...

### CODE REVIEW

**Comment by tgamblin** [comment]
@svenevs: do you mind filing the bug?

**Comment by svenevs** [comment]
@tgamblin I filed a [bug here](https://gforge.inria.fr/tracker/index.php?func=detail&aid=21048&group_id=248&atid=1079) (poorly formatted, but cannot for the life of me figure out how to edit......).  I'm not really sure if that tracker is being monitored, but that was the one linked from Scotch's main page.

Further testing seemed to reveal that Scotch is the culprit, I've "monitored" the bug and will post back if there are new developments / fixes.

During the adventure, I discovered a couple of things that may be relevant:

1. There is a [patch from LFS](http://www.linuxfromscratch.org/lfs/view/development/chapter03/patches.html) for flex 2.6.2.  Not sure what exactly it fixes, but successful application of the patch before installing Scotch still failed with the same problem.

2. There is a newer version that is advertised as the latest from Scotch.

    ```
    version('6.0.4', 'd58b825eb95e1db77efe8c6ff42d329f')
    ```

**Comment by adamjstewart** [comment]
Feel free to add the latest version and submit a PR. I don't usually add patches unless I know what they do/I need them, but those are easy to add too.

**Comment by svenevs** [comment]
A good philosophy wrt patches 🙃 

I guess (2) was more of a question.  Is it preferred to just leave it given that it isn't stable with flex 2.6.2, or since the 2.6.1 version is (for now) always being requested regardless of the version, better to have it?  E.g. there was 6.0.0, then 6.0.3.  I'm not familiar with the `spack` viewpoint versioning.

**Comment by adamjstewart** [comment]
I always add the latest version of a package if I notice a newer version is available. Just because it doesn't fix the problem you have doesn't mean it doesn't patch security vulnerabilities or add new features that will be useful to other users. Of course, newer versions aren't always stable, so I shy away from adding alpha/beta/release candidate versions, but full releases are generally stable enough that the developers would encourage users to choose them. The reason you see jumps between `6.0.0` to `6.0.3` for example is because Spack doesn't have any way of automatically adding newer versions when they are released. If a user notices a newer version is available, they can add it. They don't have to add versions inbetween (like `6.0.1` and `6.0.2`).

**Pull request merged**
