### PR TITLE
gfsio: add NOAA software maintainers 

### PR DESCRIPTION
**Pull request by edwardhartnett**
added NOAA software maintainers to maintainer list for gfsio

### CODE REVIEW

**Review by Hang-Lei-NOAA — DISMISSED** [review]

**Comment by t-brown** [comment]
I don't really see the point of adding the line, however since you have seemed to for all other NCEPLIBS. It would be nice to be consistent.

```
    This is part of the NCEPLIBS project."""
```

**Comment by edwardhartnett** [comment]
My goal in adding that comment was to unify the libraries and give readers of the brief documentation the context. I realize now that I should have been saying:

This is part of the NOAA NCEPLIBS project.

So I will start using that instead. ;-)

**Comment by t-brown** [comment]
> This is part of the NOAA NCEPLIBS project.

When I did the first Spack package, I was torn as to prefixing all packages with `NCEPLIBS-` (as their git repos are labeled). So I can relate!

**Review by t-brown — APPROVED** [review]

**Review by sethrj — APPROVED** [review]

**Comment by sethrj** [comment]
@edwardhartnett If you add similar updates to all of the NOAA packages in the future, I think it's OK to put them all under a single PR so that they can be tested and reviewed together. Thanks!

**Pull request merged**
