### PR TITLE
gcc: add v12.3.0

### PR DESCRIPTION
**Pull request by prckent**

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
FWIW. I was able to confirm the sha256.

**Comment by tldahlgren** [comment]
Deferring merge decision to @alalazo and or @michaelkuhn .

**Comment by alecbcs** [comment]
ping @alalazo and @michaelkuhn

**Review by michaelkuhn — APPROVED** [review]
Works for me (Fedora 38, GCC 13.1)

**Pull request merged**
