### PR TITLE
Fix boost build failures on newer glibc

### LINKED ISSUE #28273: Installation issue: boost@1.70.0 on Fedora 35
### Steps to reproduce the issue

On an installation of fedora 35:
```shell
$ spack install boost@1.70.0 cxxstd=17 %gcc9.4.0
```
The outcome is a variety of error messages like:

```shell
 >> 16215    ./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
     16216       60 | #if PTHREAD_STACK_MIN > 0
...
```

### Information on your system

```shell
$ spack debug report
* **Spack:** 0.17.1-730-a4f0fbafbb
* **Python:** 3.10.1
* **Platform:** linux-fedora35-broadwell
* **Concretizer:** clingo
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7818378/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7818379/spack-build-env.txt)

@hainest 

As far as I can tell this is an issue related to recent changes in glibc.  Here's how they fixed it in other package managers: https://github.com/Ma27/nixpkgs/commit/87a628b1027363e8756c8bef7f6e4b71f190ee54

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by pbrady**
Fixes #28273

### CODE REVIEW

**Comment by hainest** [comment]
LGTM

@tldahlgren spackbot requested my review, but I can't leave one. Do I need elevated privs for that?

**Comment by pbrady** [comment]
It looks like the gitlab-ci is hanging

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
Can you rebase to run Gitlab pipelines on a new merge commit?

**Comment by pbrady** [comment]
rebased.  Thanks @alalazo

**Comment by pbrady** [comment]
Still waiting on that ci...

**Comment by tgamblin** [comment]
@spackbot run pipeline

**Comment by pbrady** [comment]
Thanks @tgamblin.

**Comment by pbrady** [comment]
Looks like all the checks have passed but it needs an official review.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
