### PR TITLE
py-flatbuffers: Add py-flatbuffers package

### PR DESCRIPTION
**Pull request by gperrotta**
Adding Python implementation of [Google Flatbuffers](https://github.com/google/flatbuffers).

@hyviquel

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Duplicate of the `flatbuffers` package

**Comment by gperrotta** [comment]
The Python version is a fully independent port of the C++ version, not really a variant. [source](https://github.com/google/flatbuffers/tree/master/python)

Should I change the `+python` option of `flatbuffers` to install `py-flatbuffers` instead?

**Comment by alalazo** [comment]
@gperrotta  No, in that case it's fine. I just saw that they were both pointing at the same homepage, so maybe add a comment explicitly in this `package.py` to explain the relation between these two packages? Also, if the API of `flatbuffers+python` is the same as `py-flatbuffers` we might want to add a virtual in the future.

**Comment by gperrotta** [comment]
> @gperrotta No, in that case it's fine. I just saw that they were both pointing at the same homepage, so maybe add a comment explicitly in this `package.py` to explain the relation between these two packages? Also, if the API of `flatbuffers+python` is the same as `py-flatbuffers` we might want to add a virtual in the future.

Added a note to the package docstring. About the common API, looks like some languages are still under development: [Feature support per Language](https://google.github.io/flatbuffers/flatbuffers_support.html).

**Review by alalazo — APPROVED** [review]

**Pull request merged**
