### PR TITLE
petsc: Fix Python version number, improve code layout

### PR DESCRIPTION
**Pull request by citibeth**
Error in Python version range.

### CODE REVIEW

**Comment by citibeth** [comment]
@tgamblin

Is this a change?  Last I knew, 2.6:2.7 would give everything UP THROUGH
2.7 --- but not 2.7.1, 2.7.2, etc.

**Comment by tgamblin** [comment]
@citibeth: 2.7 has always been intended to include `2.7.1`, `2.7.2`, etc.

**Comment by adamjstewart** [comment]
You might be thinking about how `python@2.7` only includes `2.7` and not `2.7.1`, etc. And how `python@2.7:2.7` does the same thing, making `python@2.7:2.8` necessary. That's a bug, but doesn't affect this package.

**Comment by citibeth** [comment]
Yes thanks, that was it.

**Comment by tgamblin** [comment]
Yeah, sorry for that.  That is a concretization issue.  The concretizer thinks that if a package has a single version that is not a range or a list, that it's concrete, so if you say `2.7` on the command line it never gets matched against known versions.  But `2.7`, if compared to other versions, will be satisfied by `2.7.1`, `2.7.8.1`, etc.

Probably a version needs to know whether it is `exact`, so the concretizer doesn't have to use a kludgy test like it does.  This would also be useful for users -- I have thought about allowing "exact" version literals like `2.7.` (period at the end) to indicate the version is *exactly* `v2.7` and shouldn't match anything else.

**Pull request closed without merging**
