### PR TITLE
opencl-headers@2.2: Prepend C/CPP include path environment variable when activating view or module load

### PR DESCRIPTION
**Pull request by ExplorerRay**
I recently meet a problem that opencl-headers won't revise environment variables after activating environment or module loading, so I try to fix this refers to [this](https://spack.readthedocs.io/en/latest/module_file_support.html#setting-environment-variables-dynamically-in-package-py). I have tested it after installing opencl-headers@2.2 in a spack environment. Both C_INCLUDE_PATH and CPLUS_INCLUDE_PATH work well.

### CODE REVIEW

**Comment by lorddavidiii** [comment]
So as far as I understand this, this is by design. C_INCLUDE_PATH and CPLUS_INCLUDE_PATH where removed in 0664b907513310b96708e09525bd36fbe37432fe and also in the [tutorial environment example](https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html#building-in-environments) they are adding the includes directly: `mpicc ./mpi-hello.c -I$(spack location -i zlib-ng)/include` I think one can add these to the user modules.yaml file, but I am not very familiar with this.

**Comment by ExplorerRay** [comment]
Okay, I got it. I didn't notice issues about Fortran. Thanks for your response. I'm sure that modules.yaml works in module loading but it is not that convenient. I need to append many lines in modules.yaml to deal with this. And it doesn't affect activating view.
```
^opencl-c-headers:
  environment:
    prepend_path:
      C_INCLUDE_PATH: '{^opencl-c-headers.prefix}/include'
opencl-c-headers:
  environment:
    append_path:
      C_INCLUDE_PATH: '{^opencl-c-headers.prefix}/include'
^opencl-clhpp:
  environment:
    append_path:
      CPLUS_INCLUDE_PATH: '{^opencl-clhpp.prefix}/include'
opencl-clhpp:
  environment:
    append_path:
      CPLUS_INCLUDE_PATH: '{^opencl-clhpp.prefix}/include'
```
So, this kind of issue is now preferred to be solved by user's side? By -I flag or just using my own fork?
If that's it, I will close this PR. Thanks again.

**Comment by lorddavidiii** [comment]
I think you can just do something like this:
```                                                                                                                          ~
modules:
  prefix_inspections:
    ./include:
      - C_INCLUDE_PATH
      - CPLUS_INCLUDE_PATH
 ```
I add this to the `modules.yaml` in the user scope. I did a small test with `module load` and there it worked. In my project we are unfortunately not working environments, so I do not know why it is not working with views.

**Comment by ExplorerRay** [comment]
I have also tried something like this in spack.yaml in my environment and it works with views. But it met [an issue](https://github.com/spack/spack/issues/16343) that seems to be there for years. My original environment variable will disappear after activating and deactivating which is not what I want.
I think it is like doing something set and unset instead of prepending and removing path for environment variable.

**Comment by ExplorerRay** [comment]
Sorry for unfamiliar with contributing, I just pushed something not related to this...

**Pull request closed without merging**
