### PR TITLE
New packages: py-robocrys, py-matminer, py-pubchempy

### PR DESCRIPTION
**Pull request by meyersbs**
py-robocrys depends on the other two packages

### CODE REVIEW

**Comment by meyersbs** [comment]
@spackbot fix style

**Comment by meyersbs** [comment]
Note to self: looks like someone at RIT packaged py-inflect but never upstreamed; will push up soon

**Comment by qwertos** [comment]
Depends on: #35942

**Review by tldahlgren — COMMENTED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
> Depends on: #35942

**Review by adamjstewart — DISMISSED** [review]

**Review by bernhardkaindl — DISMISSED** [review]
With this rebase to the new develop which provides the missing py-inflect recipe,
it builds with this command on fresh Ubuntu 22.10:
```
spack install py-robocrys^python@3.9.15 py-pubchempy^python@3.9.15 %gcc@11.1.0 
```
`^python@3.9.15` is needed because the versions of `pymatgen` provided by the `py-pymatgen` recipes don't build with `python@3.10:`.

You can help to for this by helping to get #36081 approved which adds the missing version conflicts.

**Review by bernhardkaindl — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
