### PR TITLE
butterflypack: add v2.3.1

### PR DESCRIPTION
**Pull request by liuyangzhuan**
Bump butterflypack versions

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Looks like there are package build problems with two of the `e4s` stacks (see https://gitlab.spack.io/spack/spack/-/pipelines/496395).

**Comment by eugeneswalker** [comment]
A couple CI failures look legitimate:

1. [butterflypack/wsqxidj 2.3.1 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8213657)
```
...
12 errors found in build log:
     729                                                                       
                           ^
     730                                                                       
                           std::
     731     /tmp/root/spack-stage/spack-stage-butterflypack-2.3.1-wsqxidjyclu6
             cxf5sfbhfasjlx2yi3tc/spack-src/EXAMPLE/FIO_Driver.cpp:100:100: war
             ning: unqualified call to 'std::move' [-Wunqualified-std-cast-call
             ]
     732         : _m_rand(m_rand), _n_rand(n_rand), _rank_rand(rank_rand), _ke
             r(ker), _MatU(move(MatU)), _MatV(move(MatV)){
     733                                                                       
                                              ^
     734                                                                       
                                              std::
  >> 735     /tmp/root/spack-stage/spack-stage-butterflypack-2.3.1-wsqxidjyclu6
             cxf5sfbhfasjlx2yi3tc/spack-src/EXAMPLE/FIO_Driver.cpp:775:27: erro
             r: no matching constructor for initialization of 'vector<_Complex 
             double>'
     736       vector<_Complex double> xout1((nvec)*(myseg_n),{0.0,0.0});
     737                               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~
     738     /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/s
```

2. [butterflypack/vff3sfp 2.3.1 cce@=15.0.1 linux-rhel8-zen4 E4S Cray](https://gitlab.spack.io/spack/spack/-/jobs/8213665)
```
...
12 errors found in build log:
     9458                                                                      
                             ^
     9459                                                                      
                             std::
     9460     /tmp/gitlab-runner-3/spack-stage/spack-stage-butterflypack-2.3.1-
              vff3sfpxr5vul4qeh57zcgfl7bjjw4dz/spack-src/EXAMPLE/FIO_Driver.cpp
              :100:100: warning: unqualified call to 'std::move' [-Wunqualified
              -std-cast-call]
     9461         : _m_rand(m_rand), _n_rand(n_rand), _rank_rand(rank_rand), _k
              er(ker), _MatU(move(MatU)), _MatV(move(MatV)){
     9462                                                                      
                                                ^
     9463                                                                      
                                                std::
  >> 9464     /tmp/gitlab-runner-3/spack-stage/spack-stage-butterflypack-2.3.1-
              vff3sfpxr5vul4qeh57zcgfl7bjjw4dz/spack-src/EXAMPLE/FIO_Driver.cpp
              :775:27: error: no matching constructor for initialization of 've
              ctor<_Complex double>'
     9465       vector<_Complex double> xout1((nvec)*(myseg_n),{0.0,0.0});
     9466                               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by liuyangzhuan** [comment]
This is in progress at https://github.com/xsdk-project/xsdk-issues/issues/222#issuecomment-1719725895

**Comment by alalazo** [comment]
Superseded by #47462

**Pull request closed without merging**
