### PR TITLE
[WIP] nersc e4s pipeline trigger

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
@adityakavalur @eugeneswalker @tgamblin 

This will trigger e4s pipeline at NERSC using a spack mirror.

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@eugeneswalker if you decide to change the name of the repo we should do it now before this is merged

**Comment by shahzebsiddiqui** [comment]
@scottwittenburg @eugeneswalker @adityakavalur 

We have tested multi-project trigger at NERSC using this MR assuming @eugeneswalker is ok with name of repo, if not we will need to update this MR and get this approved and test again once we sync our spack mirror with upstream.

Screen Shot 2020-11-03 at 12 53 24 PM

**Review by scottwittenburg — APPROVED** [review]
Looks good to me.

**Comment by adityakavalur** [comment]
@shahzebsiddiqui I am not sure if we need the SPACK_REPO to be passed. Since the cloned spack repo is not public, we need to use username@repo, so SPACK_REPO is just being over-written anyway, it may cause unnecessary confusion

**Comment by scottwittenburg** [comment]
> @shahzebsiddiqui I am not sure if we need the SPACK_REPO to be passed. Since the cloned spack repo is not public, we need to use username@repo, so SPACK_REPO is just being over-written anyway.

Not sure about your case, but from what I've seen, passing variables from here overrides almost anything you have in your gitlab ci settings or set as variables in your downstream pipeline.  I assumed you wanted to clone spack from your mirror, but I agree that if it's not public maybe the thing to do is just define `SPACK_REPO` in your downstream `.gitlab-ci.yml` or project variable to be the main spack repo on github.

**Comment by adityakavalur** [comment]
@scottwittenburg Sorry about that, just checked the variable name used for spack repo in the gitlab-ci file. It is something else, so SPACK_REPO is not being overwritten, it is just not being used.

**Comment by shahzebsiddiqui** [comment]
I have updated this PR to **WIP** so that we can test this out again, i agree it may not be necessary to pass in `SPACK_REPO` or `SPACK_REF` this process is slightly different because we dont have pull mirroring. Let us test this out again.

**Comment by adityakavalur** [comment]
So SPACK_REF is needed because I reset to a particular commit for each pipeline. In-case a new commit comes in before the previous build is complete, you dont want your child jobs running on different commits.

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
