### PR TITLE
Drop Python 3.6 again

### PR DESCRIPTION
**Pull request by adamjstewart**
Possible hack to avoid audits complaining

### CODE REVIEW

**Review by alalazo — COMMENTED** [review]
Fine with me, but we probably need to mark a few packages as "core" files, so that we run unit tests on them. Here we see audit passing, but we don't see `rhel8` platform python (since that is not triggered by package only changes so far).

**Comment by adamjstewart** [comment]
Can this be merged?

**Comment by alalazo** [comment]
We still need to run unit tests on it. Right now this is considered a "package only" PR and thus unit tests are skipped

**Comment by adamjstewart** [comment]
What's the easiest way to do that?

**Comment by adamjstewart** [comment]
Fixed a typo in core, hopefully that triggers core tests.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
The two issues with pipelines seems unrelated (`cabana` and `src` broken on `develop`)

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
The tests actually passed! 😮

**Comment by adamjstewart** [comment]
Ping @alalazo

**Review by alalazo — APPROVED** [review]

**Pull request merged**
