### PR TITLE
Pin xdist on macOS to fix broken CI runs

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by haampie** [comment]
The issue was likely with 

```python
def test_which(tmpdir):
    os.environ["PATH"] = str(tmpdir)
```

and xdist changes only uncovered this by test reordering?

Close this in favor of #41215?

**Comment by alalazo** [comment]
Do we want to get this one in, and revert it when we'll merge #41215 ?

**Comment by haampie** [comment]
Let's see if it even passes gha itself ;p

**Comment by haampie** [comment]
Failures are due to https://github.com/spack/spack/pull/38458#issuecomment-1822968031

**Comment by alalazo** [comment]
Failures gone on 4th retry. We can get this one in and have a commit in https://github.com/spack/spack/pull/41215 reverting it.

**Pull request closed without merging**
