### PR TITLE
Add Trilinos 12.6.4

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by adamjstewart** [comment]
That hash looks a little short...

**Comment by davydden** [comment]
that's fine, Spack supports different hashes and decided on the type based on hash length.

**Comment by Rombur** [comment]
It is the same length as the older ones. For some reasons, the last three were longer.

**Comment by davydden** [comment]
LGTM

**Comment by adamjstewart** [comment]
Oh, huh. Alright then.

**Pull request merged**
