### PR TITLE
libint: add v2.7.1

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@dev-zero This was just a first go - I noticed that the 2-stage build with the `generated` folder failed for 2.7.1, and limiting those changes to 2.6.0 let the build run through.

However, I guess I should also check whether the build still runs through with `+fortran`, is that correct?

**Comment by ltalirz** [comment]
Hmm... I now realize this still needs quite a bit of work.

I guess one should use the CMake route now instead of autotools.
Is there an example of how to do that properly, i.e. switch from autotools to cmake in the same spack recipe depending on the package version?

Or should I rather try to fix the issue with the autotools route for 2.7.1?

**Comment by dev-zero** [comment]
@ltalirz welcome to libint packaging ;-)
Wrt supporting multiple build systems: https://github.com/spack/spack/wiki/Telcon:-2022-03-09
Until that is implemented I guess the easiest is to use `@when` for `def install` (etc.) and then do the respective implementation. Wrt which route to take: libint promised for years to switch completely to CMake, but one of the reasons why we didn't update libint to 2.7.0-beta6 in the CP2K toolchain was because the build system and/or the generated Fortran bindings were broken (so, CMake-route not working and autoconf-route broken). Good luck.

**Comment by ltalirz** [comment]
I understand multiple build systems are supported from spack 0.19+ https://spack.readthedocs.io/en/latest/packaging_guide.html#multiple-build-systems so it might be worth trying to revive this process. Any takers? ;-)

**Comment by ltalirz** [comment]
Superseded by https://github.com/spack/spack/pull/36659

**Pull request closed without merging**
