### PR TITLE
libffi: add patch for building with clang on power

### PR DESCRIPTION
**Pull request by xjrc**
The changes in this pull request fix an issue that was causing `%clang` builds on `target=power*` platforms to fail. I've verified that the `libffi@3.2.1` variant compiles in the `clang%9.0.0 arch=linux-rhel7-power9le` build environment.

### CODE REVIEW

**Comment by ax3l** [comment]
Thanks a lot for this! :sparkles: 

Just because I am really unfamiliar with where this is patching what: Can you please share an upstream repo reference or hints on how this patch was conceived? I love how the `nop`s can solve this, but it does look like magic to me :)

**Comment by xjrc** [comment]
When compiling `libffi@3.2.1%clang@9.0.0`, the build step fails with the error:

```
libtool: link: /path/to/spack/lib/spack/env/clang/clang -shared  -fPIC -DPIC  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/powerpc/.libs/ffi.o src/powerpc/.libs/ffi_sysv.o src/powerpc/.libs/ffi_linux64.o src/powerpc/.libs/sysv.o src/powerpc/.libs/ppc_closure.o src/powerpc/.libs/linux64.o src/powerpc/.libs/linux64_closure.o    -O3   -Wl,-soname -Wl,libffi.so.6 -o .libs/libffi.so.6.0.4
/usr/bin/ld: src/powerpc/.libs/linux64.o: In function `ffi_call_LINUX64':
(.text+0x3c): call to `ffi_prep_args64' lacks nop, can't restore toc; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

An [LLVM bug report for a similar error](https://bugs.llvm.org/show_bug.cgi?id=17354) suggests that a "no-op" is required after a function call (or "branch link" in ARM parlance) to give the machine a cycle to restore the local [TOC (table of contents)](https://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi-1.9.html#TOC-SEC). It's unclear to me why `clang` would require this where it appears other compilers do not (`libffi@3.2.1%gcc@4.9.3` works without a patch), but my theory is that `clang` is stricter about branch safety than its contemporaries.

Also, as an aside, it appears as though this bug only affects `@3.2.1` as the new variant `libffi@3.3%clang@9.0.0 arch=linux-rhel7-power9le` builds without any patches, so I'll update the package code accordingly.

**Comment by xjrc** [comment]
Okay, the patch version has been fixed! I've validated that all of the following variants build successfully on `arch=linux-rhel7-power9le`:

- `libffi@3.2.1%clang@9.0.0`
- `libffi@3.2.1%gcc@4.9.3`
- `libffi@3.3%clang@9.0.0`
- `libffi@3.3%gcc@4.9.3`

**Comment by xjrc** [comment]
I think that this PR is ready; pinging @ax3l, @chuckatkins.

**Review by becker33 — APPROVED** [review]

**Comment by ax3l** [comment]
Thanks a lot @xjrc, this is great!

**Pull request merged**
