### PR TITLE
paraview: add v5.13.1

### PR DESCRIPTION
**Pull request by vicentebolea**
🎉 🎉 🎉

ParaView 5.13.1 is out

This PR updates the ParaView Spack package to include this new release and set ParaView v5.13.1 as the preferred version.

Let me know if we need to change anything else in the package.

🎉 🎉 🎉

### CODE REVIEW

**Review by kwryankrattiger — APPROVED** [review]
shas match, LGTM

**Comment by tldahlgren** [comment]
Bummer.  At least one stack failed with a pod issue:

```
429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

**Review by kwryankrattiger — APPROVED** [review]

**Comment by tldahlgren** [comment]
FYI. I used `Update branch` button because of the pod issues I mentioned yesterday.  Hoping doing so will allow CI to pass.

**Review by bernhardkaindl — APPROVED** [review]
JFYI: Built the new version on Ubuntu 22.04

**Comment by tldahlgren** [comment]
Looks like at least one container not ready message

@spackbot run pipeline

**Pull request merged**
