### PR TITLE
py-flit: add versions 3.8 and 3.9

### PR DESCRIPTION
**Pull request by yan-zaretskiy**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Will give @takluyver some time to review, ping me if you haven't heard anything in a week

**Review by takluyver — APPROVED** [review]
Thanks, LGTM

**Comment by yan-zaretskiy** [comment]
@adamjstewart Do I need to do anything else for this PR to be merged?

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
