### PR TITLE
py-cig-pythia: add missing dependency on py-packaging

### PR DESCRIPTION
**Pull request by downloadico**

### CODE REVIEW

**Comment by wdconinc** [comment]
Can you add to the PR description what error this addresses or where this is used? I can't find any imports of packaging. Could it be that this pulls in a transitive dependency that is unspecified (py-setuptools, I would guess in that case)?

**Comment by downloadico** [comment]
> Can you add to the PR description what error this addresses or where this is used? I can't find any imports of packaging. Could it be that this pulls in a transitive dependency that is unspecified (py-setuptools, I would guess in that case)?

I think you're correct here, py-setuptools is probably the right dependency.

**Comment by downloadico** [comment]
I'll re-do this PR with the correct dependency

**Comment by wdconinc** [comment]
Sure. You could have done that in this branch and PR as well.

**Pull request closed without merging**
