### PR TITLE
[AMD][rocm-openmp-extras] - Update versions 5.0.0 through 5.1.0.

### PR DESCRIPTION
**Pull request by estewart08**
- Removed gl dependency.
- Specify clang as cmake compiler as gcc was being
  improperly picked up. As a result, ffi include
  path was needed in C/CXX flags.

### CODE REVIEW

**Comment by alalazo** [comment]
@arjun-raj-kuppala @srekolam @cgmb

**Review by srekolam — APPROVED** [review]

**Comment by tldahlgren** [comment]
FWIW. Package audits, which are required to pass, report the following issues:

```
PKG-DIRECTIVES: 4 issues found
[9](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:9)
1. rocm-openmp-extras: dependency on hsakmt-roct@5.1.0 cannot be satisfied by known versions of hsakmt-roct
[10](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:10)
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
[11](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:11)
    known versions of hsakmt-roct are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
[12](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:12)
2. rocm-openmp-extras: dependency on comgr@5.1.0 cannot be satisfied by known versions of comgr
[13](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:13)
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
[14](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:14)
    known versions of comgr are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
[15](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:15)
3. rocm-openmp-extras: dependency on hsa-rocr-dev@5.1.0 cannot be satisfied by known versions of hsa-rocr-dev
[16](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:16)
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
[17](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:17)
    known versions of hsa-rocr-dev are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
[18](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:18)
4. rocm-openmp-extras: dependency on llvm-amdgpu@5.1.0~openmp cannot be satisfied by known versions of llvm-amdgpu
[19](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:19)
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
[20](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:20)
    known versions of llvm-amdgpu are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
```

**Comment by estewart08** [comment]
> FWIW. Package audits, which are required to pass, report the following issues:
> 
> ```
> PKG-DIRECTIVES: 4 issues found
> [9](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:9)
> 1. rocm-openmp-extras: dependency on hsakmt-roct@5.1.0 cannot be satisfied by known versions of hsakmt-roct
> [10](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:10)
>     happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
> [11](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:11)
>     known versions of hsakmt-roct are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
> [12](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:12)
> 2. rocm-openmp-extras: dependency on comgr@5.1.0 cannot be satisfied by known versions of comgr
> [13](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:13)
>     happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
> [14](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:14)
>     known versions of comgr are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
> [15](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:15)
> 3. rocm-openmp-extras: dependency on hsa-rocr-dev@5.1.0 cannot be satisfied by known versions of hsa-rocr-dev
> [16](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:16)
>     happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
> [17](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:17)
>     known versions of hsa-rocr-dev are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
> [18](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:18)
> 4. rocm-openmp-extras: dependency on llvm-amdgpu@5.1.0~openmp cannot be satisfied by known versions of llvm-amdgpu
> [19](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:19)
>     happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
> [20](https://github.com/spack/spack/runs/6310384186?check_suite_focus=true#step:6:20)
>     known versions of llvm-amdgpu are master, 5.0.2, 5.0.0, 4.5.2, 4.5.0, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.0, 3.10.0, 3.9.0, 3.8.0, 3.7.0, 3.5.0
> ```

Those tests were before https://github.com/spack/spack/pull/30027 was merged, so 5.1.0 did not exist on the other recipes. Probably need to re-run the test.

**Comment by tldahlgren** [comment]
> Those tests were before #30027 was merged, so 5.1.0 did not exist on the other recipes. Probably need to re-run the test.

Just used the web interface to update the branch, will triggered the checks.

(That can cause issues if additional changes are needed to this PR if they are not pulled first.)

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
