### PR TITLE
py-libensemble: add maintainer

### PR DESCRIPTION
**Pull request by balay**
cc: @shuds13

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Just waiting for @shuds13 to review then I'll merge.

**Comment by shuds13** [comment]
I am happy with this.

**Comment by balay** [comment]
I don't understand what the issue is with gitlab-ci failure - and why this PR would trigger this..

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
