### PR TITLE
add path argument to spack external find

### PR DESCRIPTION
**Pull request by becker33**
Fixes a complaint from slack

@mwkrentel @ashermancinelli @alalazo y'all were all involved in the conversation, what do y'all think?

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]
As I said on Slack, I like this. Less guessing on Spack, and more binaries in `bin/intel64`!

**Comment by ashermancinelli** [comment]
I think this is really close, but should passing `--path` mean that `$PATH` and `$LD_LIBRARY_PATH` aren't searched *at all*?

That's what I'm inferring from this and the corresponding line in `libraries_in_ld_library_path`:
```python
# lib/spack/spack/detection/path.py:93
    path_hints = path_hints or spack.util.environment.get_path('PATH')
```

As a user, I would expect `--path` to append/prepend to the env search paths, not replace them.

**Comment by alalazo** [comment]
The infamous:
```console
spack commands --update-completion
```
hits again

**Comment by becker33** [comment]
@ashermancinelli I was trying to match the long-tenured behavior of `spack compiler find`. The find logic can take a while for long PATH variables, I was hoping to make it faster. `spack external find --path $PATH:/path/to/check` would still always be an option.

But I might not be appreciating how hard it is to get the default search path back, since the default is to search different things for different packages depending on the type of detection they do... that's slightly tricky.

**Review by ashermancinelli — APPROVED** [review]

**Comment by mwkrentel** [comment]
My primary use case for this is adding a "nonstandard" location for a
package, eg, a custom build in my home directory and not /usr.
So, I'm Ok with replacing the search path rather than adding to it.

Btw, I tried this a couple ways and I discovered that both of the
following work for an "off to the side" install, and both resulted in
`prefix` as the location (correct).  This is for a package (autoconf)
that looks for an executable in a bin directory.

```
spack external find -p /path/to/prefix autoconf
spack external find -p /path/to/prefix/bin autoconf
```

Both worked and both resulted in `prefix: /path/to/prefix`.
Given some of the discussion in slack, I was suprised but pleased.

I approve.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
