### PR TITLE
py-scikit-image: add v0.20.0

### PR DESCRIPTION
**Pull request by adamjstewart**
@alalazo it is not possible to concretize this versions due to conflicting setuptools requirements in the DAG.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Confirmed all affected version sha256.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
> it is not possible to concretize this versions due to conflicting setuptools requirements in the DAG.

Given this :point_up: do you want to merge the PR?

**Comment by adamjstewart** [comment]
Yeah, the PR is correct, I'm hoping that we'll be able to fix the concretizer someday.

**Pull request merged**
