### PR TITLE
warn about removal of deprecated format strings

### PR DESCRIPTION
**Pull request by becker33**
Removal scheduled for v0.20

Should have been scheduled long ago, but we kept configs in this format for too long.

### CODE REVIEW

**Comment by becker33** [comment]
@spackbot fix style

**Comment by becker33** [comment]
@spackbot help

**Comment by alalazo** [comment]
We should also backport this in v0.19.1 so we can claim the warning was in v0.19 (before removing the support in v0.20)

**Review by alalazo — APPROVED** [review]
I wonder if we can give a hint to users saying where they are using the old format, but not essential if it requires lot of boilerplate code.

**Comment by alalazo** [comment]
@scottwittenburg @zackgalbreath Never seen this one before. The status check for pipelines says "Errored", but the pipeline succeeded. I'm not retriggering it in case you want to inspect better.

**Comment by scottwittenburg** [comment]
I've never seen this before either.  Manually querying the gitlab api for the pipeline status just now, I see:

```
$ curl \
>   --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
>   https://gitlab.spack.io/api/v4/projects/2/pipelines?ref=pr33829_deprecations/deprecated-format-format
[{
    "id":214974,
    "iid":213380,
    "project_id":2,
    "sha":"faff64929cbb8a6241e9b258e0eac7967c2ce65e",
    "ref":"pr33829_deprecations/deprecated-format-format",
    "status":"success",
    "source":"push", 
    "created_at":"2022-11-11T17:51:58.164Z",
    "updated_at":"2022-11-13T20:35:08.921Z",
    "web_url":"https://gitlab.spack.io/spack/spack/-/pipelines/214974"
}]
```

So obviously gitlab thinks the pipeline was successful.  I'm speculating now that one of those spurious "no specs to rebuild" failures was retried 2 days after the pipeline was created (difference between the created and update timestamps) and succeeded at that point.  The only way the sync cron job could have missed it, is if it didn't run for a period of time around that `update_at` time, and then the next time it *did* run, the updated time was outside the normal pipeline query window.  

Any ideas @zackgalbreath?

Thanks for the heads up before re-running @alalazo, that helped to make sure new pipeline status didn't get created before I could take a look.  But I don't think there's anything more to be learned from logs at this point, so I'll just re-trigger.

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Comment by becker33** [comment]
> I wonder if we can give a hint to users saying where they are using the old format, but not essential if it requires lot of boilerplate code.

I don't think most locations preserve the ruamel line-attributions through to where this is called, so I think it would be pretty plumbing-intensive to do

**Comment by alalazo** [comment]
Sorry Greg, I'm going to revert this one. I didn't test drive it, and on `develop` we get:
Screenshot from 2022-11-22 12-29-55

**Pull request merged**
