### PR TITLE
documentation: added an how-to part before reference docs

### LINKED ISSUE #15848: Add an "How to" part in the documentation
I believe that our documentation would increase its effectiveness if we add an "How to" part that deals in a very practical way with specific problems e.g. "How do I install X on the system and set it up as an external in Spack?" or "How can I set environment variables to be used when I build or run a package?"

### Rationale

Spack documentation has already excellent tutorial and reference sections. Tutorials focus on giving a quite in depth tour of Spack capabilities following a path that is viable for somebody that approaches the tool for the first time. The reference guide gives great details on the inner working of Spack and provides many times discussions on why certain choices have been made. What I think might be missing (based on recent discussions with a few users) is a section that is focused on common issues/needs that a user might face when employing Spack and explains how to solve them in a recipe-like style.

### Description

This proposal is basically to start a discussion on adding an "How to" section in the documentation. I think a good starting format might be that of many programming cookbooks, where you have:

1. A brief statement on what is the problem that needs to be solved
2. A solution that explains how to solve it in a series of steps
3. Maybe a few brief notes or references at the end

and it is assumed that the reader is already somewhat familiar with the tool.

### Additional information

In case the proposal is well received there are possibly more details that needs to be fixed, like which categories to use for grouping how to recipes, how to make them searchable in an effective way etc. 

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alalazo**
fixes #15848

The idea of the how-to part of the docs is to provide short and clear examples to specific problems that a user may want to solve with Spack. It assumes the user to be already familiar with Spack terminology, to keep each how-to short, but ideally provides a lot of links to reference documentation for people who need to dig deeper in a topic.

Each how-to item has the following structure:

1. **Problem:** Brief statement of the use case that is going to be solved.
2. **Solution:** Walkthrough for the current problem. 
3. **Discussion:** Comments on the caveats of the solution being proposed

An example of the current layout is:
Screenshot from 2020-11-20 13-59-11

Modifications:

- [x] Add some content to the how to part (mainly grabbed from the "Workflows" section under "Basics")
- [ ] Move the entire Workflows section under "How to" (is there consensus on this?)
- [ ] Add content for the issues linked in #15848

### CODE REVIEW

**Comment by alalazo** [comment]
@adamjstewart

**Comment by adamjstewart** [comment]
I'm trying to decide if this belongs as another top-level section. What other guides might we add in the future?

I'm also concerned about possible overlap with other sections. The Workflows section, and in particular "how to replace homebrew/conda with spack" might belong in the How To section. More documentation is always great, but I fear we're getting to the point that the documentation is so long that no one ever reads it.

Another possible thing to add: we get a lot of questions about how to uninstall Spack, either to do a clean upgrade or to stop using Spack altogether. We should add a list of directories to delete ($SPACK_ROOT, /etc/spack, ~/.spack).

**Comment by alalazo** [comment]
> The Workflows section, and in particular "how to replace homebrew/conda with spack" might belong in the How To section.

I believe so too. I grabbed most of the current content from the "Workflows" section and I think, if there's consensus, we should delete the "Workflows" (and prune outdated content). The Conda/Homebrew section is one of the how-to in this draft PR

**Comment by tgamblin** [comment]
Would this be better labeled as a FAQ?  It's a big long for a FAQ.  Or should we merge this and workflows?  I agree with Adam that we have too many docs.  We should really reduce the number of top-level sections, and it might be nice to have some kind of feature overview in the reference docs.  Something like this, with workflow-oriented sections, is good but I think it should have lots of links to reference documentation...

**Comment by cosmicexplorer** [comment]
> What other guides might we add in the future?

I think guides for exposing packages in specific languages might be useful. For something like rust with our `rust-bindgen` package, it's not extremely clear how the rust project should be using bindgen to consume C libraries. I think we should actually have a build system for rust, but until then, a guide that explicitly says "these are spack's current capabilities with rust" seems like it might be useful.

Similarly for R with Rcpp.

**Comment by tldahlgren** [comment]
> I'm trying to decide if this belongs as another top-level section. What other guides might we add in the future?

IMO Having it at the top under `Basics` is a good place for it.  I see this as a section that would provide a bit more information than a FAQ.

Other guides (not volunteering for all):
- How to add Install (or Smoke) tests to an existing package
- How to add `CudaPackage` and or `ROCmPackage` to an existing package
- How to convert a custom `Package` to use a build system (e.g., `CMakePackage`)
- How to add build- and install-time tests to an existing package (i.e., the call-backs)

**Comment by cosmicexplorer** [comment]
> build- and install-time tests

I agree with the use of the "build-time" and "install-time" nomenclature instead of the current "install tests".

**Comment by tldahlgren** [comment]
> Would this be better labeled as a FAQ? 

Could we have a separate FAQ, perhaps between `BASICS` and `HOW TO GUIDES`?

I could see a FAQ consisting of single sentence-to-short paragraph answers with pointers to places in the docs that have more information.

**Comment by tldahlgren** [comment]
> > build- and install-time tests
> 
> I agree with the use of the "build-time" and "install-time" nomenclature instead of the current "install tests".

Install tests are what we've been calling smoke tests -- short tests that can be run days and weeks *after* the installation -- whereas what I mention here as "build-time" and "install-time" tests are tests that are intended to be run after `spack install` completes the `build` and `install` phases, respectively.  The latter are associated with callbacks in one or more of the following build systems:

- Autotools and Makefile  (`build_time_test_callbacks`, `install_time_test_callbacks`)
- CMake and Meson (`build_time_test_callbacks`)

**Comment by tldahlgren** [comment]
> > > build- and install-time tests
> > 
> > 
> > I agree with the use of the "build-time" and "install-time" nomenclature instead of the current "install tests".
> 
> Install tests are what we've been calling smoke tests -- short tests that can be run days and weeks _after_ the installation -- whereas what I mention here as "build-time" and "install-time" tests are tests that are intended to be run after `spack install` completes the `build` and `install` phases, respectively. The latter are associated with callbacks in one or more of the following build systems:
> 
> * Autotools and Makefile  (`build_time_test_callbacks`, `install_time_test_callbacks`)
> * CMake and Meson (`build_time_test_callbacks`)

I should clarify that those are the test checks that have been uppermost in my mind.

Packages have also added custom build-time tests with different names (e.g., `check`, `check_install`, `test` (to be confused with install/smoke tests ☹️ :),`test_install`) that may or may not be marked with the `run_after` directive.

**Comment by shahzebsiddiqui** [comment]
Would you like me to still work on #22051 or somehow merge these two efforts together

**Comment by alalazo** [comment]
@tldahlgren @shahzebsiddiqui I'll try to have this ready for review by end of this week. If we decide to merge something like this then we can independently add content once it's merged.

**Comment by shahzebsiddiqui** [comment]
sounds good @alalazo, once this is merged and i move my section into the same page, i see your section is a `How To` guide which is more detailed while mine is a `FAQ` style with short answers. I am not sure if you all prefer these be in one page or two sub-pages. I guess we can discuss that in #22051 once this is merged.

**Comment by alalazo** [comment]
@adamjstewart 

> I'm also concerned about possible overlap with other sections. The Workflows section, and in particular "how to replace homebrew/conda with spack" might belong in the How To section. More documentation is always great, but I fear we're getting to the point that the documentation is so long that no one ever reads it

I removed the workflow section entirely, as it has either outdated information or it has been incorporated into the "How to". Your section on Conda is currently "How do I use Spack for single-user installations on my laptop?". Let me know if you have suggestions for more content or better phrasing. There are a couple of points that I may insert back in the How to after having reworked outdated information:
- How to manage filesystem views (but with a focus solely on environments)
- How to upstream patches (much shorter version of what was there before, possibly pointing at Fedora docs which are great in that respect)

**Pull request closed without merging**
