### PR TITLE
binutils: add version of dependent library

### PR DESCRIPTION
**Pull request by m-shunji**

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
The two links below seem to suggest the bug was fixed in v2.40 Can you expand why you needed to bump the upper limit?

**Comment by m-shunji** [comment]
@alalazo 
Two bug fixes are indicated, 
but it seems that the following error is not resolved even when using v2.41 in our system.
 
```
>> 1902    WARNING: 'makeinfo' is missing on your system.
     1903             You should only need it if you modified a '.texi' file, o
             r
     1904             any other file indirectly affecting the aspect of the man
             ual.
     1905             You might want to install the Texinfo package:
     1906             <http://www.gnu.org/software/texinfo/>
     1907             The spurious makeinfo call might also be the consequence
             of
     1908             using a buggy 'make' (AIX, DU, IRIX), in which case you m
             ight
     1909             want to install GNU make:
     1910             <http://www.gnu.org/software/make/>
>> 1911    make[3]: *** [Makefile:1764: doc/bfd.info] Error 127
```
 
Here is the information about our environment.
 ```
$ spack debug report
* **Spack:** 0.21.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-rhel8-a64fx
* **Concretizer:** clingo
```

**Comment by m-shunji** [comment]
@alalazo
Could you please check my last update on the PR when possible? Thanks.

**Comment by alalazo** [comment]
Can you check if this is related to the target, or other aspects of the spec? I was able to build `binutils@2.41` without `makeinfo` in our ubuntu-20.04 image:
```
docker pull ghcr.io/spack/ubuntu-focal:develop
```
Screenshot from 2024-03-08 07-00-14

**Comment by bernhardkaindl** [comment]
@m-shunji: Closing after 3 months of no update from the developer and I and `alalazo` confirm that building `binutils@2.41:` with `spack` works fine without `makeinfo` from `texinfo`.

If you still have issues to build `binutils` with `spack`, open a full bug report, as then the issue needs to be debugged.

As it stands, it looks like there was some misunderstanding that has since not showed up again.

**Pull request closed without merging**
