### PR TITLE
sundials: fix for rocm support

### PR DESCRIPTION
**Pull request by balos1**
... also update order of maintainers so that I am pinged by the spack bot

### CODE REVIEW

**Comment by balos1** [comment]
cc @balay

**Review by gardner48 — APPROVED** [review]

**Comment by haampie** [comment]
I'm a little bit wary of this cause this bypasses the spack compiler wrapper.

**Comment by balos1** [comment]
> I'm a little bit wary of this cause this bypasses the spack compiler wrapper.

It is not ideal, however, this is the only way I was able to get it to build on OLCF spock with rocm. If you have alternative suggestions, I am all ears.

**Review by gardner48 — APPROVED** [review]

**Comment by balay** [comment]
> I'm a little bit wary of this cause this bypasses the spack compiler wrapper.

I'm inclined to add this in for now. If a better way is found later (perhaps spack can detect this - an sundial can query an use it) - sundial can be updated at that time.

**Review by balay — APPROVED** [review]

**Pull request merged**
