### PR TITLE
trilinos: add v16.0.0

### PR DESCRIPTION
**Pull request by jmlapre**
Trilinos 16.0.0 has been released:

https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-16-0-0

### CODE REVIEW

**Comment by sethrj** [comment]
Can you confirm that the new version uses `kokkos@4.3.01`?

**Comment by jmlapre** [comment]
> Can you confirm that the new version uses `kokkos@4.3.01`?

I believe they referencing the same thing but with different versions.  See the links below:

https://github.com/spack/spack/commit/b894f996c0401b32ca12fcbf5362eee7d0c84652
https://github.com/trilinos/Trilinos/pull/12995

**Review by sethrj — APPROVED** [review]
LGTM, maybe another trilinos maintainer should double check.

**Review by achauphan — APPROVED** [review]
Also LGTM, the external kokkos version used matches the latest version of kokkos snapshotted into Trilinos for `16.0.0`

**Comment by jmlapre** [comment]
https://gitlab.spack.io/spack/spack/-/jobs/12015212#L582

```
CMake Error at cmake/Modules/FindTPLROCTHRUST.cmake:11 (FIND_PACKAGE):
  By not providing "Findrocthrust.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "rocthrust", but CMake did not find one.  Could not find a package configuration file provided by "rocthrust" with
  any of the following names:    rocthrustConfig.cmake
    rocthrust-config.cmake  Add the installation prefix of "rocthrust" to CMAKE_PREFIX_PATH or set
  "rocthrust_DIR" to a directory containing one of the above files.  If
  "rocthrust" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake/kokkos_functions.cmake:293 (FIND_PACKAGE)
  cmake/kokkos_tpls.cmake:93 (KOKKOS_IMPORT_TPL)
  cmake/kokkos_tribits.cmake:208 (INCLUDE)
  CMakeLists.txt:226 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

```

This is preventing the last Spack CI job from passing; all the others do.

@ndellingwood @sebrowne

**Comment by ndellingwood** [comment]
@jmlapre I'm not very familiar with spack, but is the build trying to enable rocthrust explicitly? In Kokkos, the default setting is to disable rocthrust in builds of Trilinos, see https://github.com/trilinos/Trilinos/blob/19640f36be2fca0d02ba096dda34b91b5c55878a/packages/kokkos/cmake/kokkos_tpls.cmake#L42-L46 , so I'm not sure why you'd run into this. In particular, none of the changes in the referenced PR https://github.com/trilinos/Trilinos/pull/12995 made changes to rocthrust-related settings

If rocthrust is explicitly being enabled, it needs to be disabled in Trilinos builds with Hip because it is not yet present as a supported TPL by Trilinos. I created a PR to begin the process of adding it to the list here https://github.com/trilinos/Trilinos/pull/12826 , it can be reopened for completion to allow use of rocthrust with Trilinos for a future release

**Comment by ndellingwood** [comment]
@jmlapre also, if the spack build is building and using Kokkos as an external TPL (rather than the internal package) then rocthrust can be disabled by setting `-D Kokkos_ENABLE_ROCTHRUST=OFF`
From the error message, it seems either rocthrust may not be present, or cmake could not find it in the expected place.

Edit: The setting above `-D Kokkos_ENABLE_ROCTHRUST=OFF` can be using in Trilinos builds with Kokkos as package as well, in case my phrasing above mistakenly implied otherwise

**Pull request merged**
