### PR TITLE
build system modules: decorators are now free-standing (and renamed)

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications
- [x] `@run_before` is the substitute for `@*.precondition`
- [x] `@run_after` is the substitute for `@*.sanity_check`
- [x] `@on_package_attributes` is the substitute for `@*.on_package_attributes`
- [x] added in code documentation

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is it still possible to convert:
```python
@AutotoolsPackage.run_after('install')
```
to:
```python
@run_after('install')
```
?

**Comment by alalazo** [comment]
@adamjstewart It's another thing on my `todo` list, but not done here. I wouldn't mind implementing it in this PR we don't want this to be an intermediate step.

**Comment by tgamblin** [comment]
Any reason to keep the old names?

**Comment by tgamblin** [comment]
Also, +1 on converting. I'm still thinking post_ and pre_ methods would be nice for users, but that can wait.

**Comment by alalazo** [comment]
> Any reason to keep the old names?

@tgamblin If they are really sanity checks or precondition checks? But that's really a super minor point, so I wouldn't mind if we decide to delete them.

**Comment by adamjstewart** [comment]
I don't mind keeping the old ones. Sometimes they really are for preconditions and sanity checks. But I also wouldn't be opposed to removing them. KISS principle always wins. I'll let someone else decide.

**Comment by adamjstewart** [comment]
I agree with @tgamblin on adding `pre_` and `post_` methods. Decorators are kind of an advanced topic in Python. We don't want the learning curve to be too high. But I can see why also having the decorators would still be useful, so that you can have multiple pre and post methods, some defined in AutotoolsPackage that you don't want the user to override, like the check for the installation directory.

**Comment by alalazo** [comment]
> I worry that things will get hard to read when we start stacking @when decorators on top of the before and after ones, and more confusing with multiple when/before/after combinations.

On the other hand with a decorator you can separate different actions into different functions and execute them after or before the same phase. This helps maintaining the code clean.

**Comment by tgamblin** [comment]
It'll also help new people read packages and contribute-- one less thing to learn.

**Comment by alalazo** [comment]
> Decorators are kind of an advanced topic in Python

Maybe writing them (and not in this specific case). Using them should be a piece of cake if they are written correctly :smile:

**Comment by alalazo** [comment]
Ok, so I'll try to make them "free-standing" decorators and remove the old names. I'll ping people when done.

**Comment by adamjstewart** [comment]
I know you would have liked to keep the old names, but I think:
```python
@sanity_check('install')
def sanity_check_prefix:
```
is just as explanatory as:
```python
@run_after('install')
def sanity_check_prefix:
```
You can always make it sound like a sanity check in the function name.

**Comment by tgamblin** [comment]
Right, so I think for now let's go with one name for simple decorators and plan to add pre and post.  Sound good?

**Comment by alalazo** [comment]
@tgamblin How do you feel about:

1. doing what we planned for decorators
2. implement *also* a naming mechanism based on appended `_pre_<phase>` or `_post_<phase>`

What I have in mind is that:
```python
@run_after('install')
def foo(self):
    ...
```
should be equivalent to:
```python
def foo_post_install(self):
    ...
```
I don't think it requires a lot more code to do that.

**Comment by tgamblin** [comment]
I was thinking just:

*`post_<phase>`
* `pre_<phase>`

For simplicity. Only challenge: maintain execution order == declaration order if these are mixed with decorators.

**Comment by alalazo** [comment]
> Only challenge: maintain execution order == declaration order if these are mixed with decorators.

That could be difficult without the `__prepare__` hook to grant we use an ordered dict. Do we really need to ensure this ? 

The contract I was thinking was weaker: **no relative order ensured for function in the same pool** (e.g. the ones that executes before a given phase). After all if you need to execute `foo` strictly before `bar` maybe they should go in the same function...

**Comment by davydden** [comment]
> Any reason to keep the old names?

to have less things to remember, i would remove old names completely. Even if it's a sanity check, it still reads fine with `run_after(install)`, package developers can always name the method properly or add a quick documentation string to explain that it's a sanity check.

**Comment by tgamblin** [comment]
Fair enough.  We do guarantee that `when`s are evaluated in order, though that hasn't really been a problem or come up at all.  I suspect most packages will use one or the other of these.  If they want order they can use decorators.

**Comment by davydden** [comment]
> I also think we should add pre_ and post_ methods so we have one more (easier) way to do it.

from a python noob's perspective, i don't know how decorators work, but it's enough to see a single example to adapt it to ones needs. Personally, i would not bother with `pre_` and `post_` to simplify package developer's life.

**Comment by alalazo** [comment]
@davydden You came late to the party :laughing: 

Old names already removed, and decorators are not tied to base classes anymore. So:
```python
@run_before('install')
def foo(self):
    ...
```
is the new
```python
@AutotoolsPackage.precondition('install')
def foo(self):
    ...
```

**Comment by alalazo** [comment]
@tgamblin @adamjstewart Let me know if you want me to proceed further here or in another PR. I am not in a rush to get this in, so any solution is fine with me.

BTW, does the metaclass code look cleaner? I tried to make it less complicated while I was at it.

**Comment by alalazo** [comment]
@adamjstewart you may want to have a look at 6b64146. That's what I intended yesterday when I said in #2869 that I wanted to push the driver function for tests up in the hierarchy

**Comment by alalazo** [comment]
ping

**Comment by tgamblin** [comment]
@alalazo: thanks!  If you want to continue in another PR that is fine, but I don't think there is a rush.

**Comment by alalazo** [comment]
@tgamblin I'll try to fix #2386 first then.

**Pull request merged**
