### PR TITLE
py-soupsieve: fix import tests

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Review by tgamblin — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by tldahlgren — COMMENTED** [review]
I'm also getting `ModuleNotFoundError: No module names 'bs4'` when run using python 3.9.

**Comment by adamjstewart** [comment]
@tldahlgren on develop or on this PR? This PR should fix the issue you describe.

**Comment by tldahlgren** [comment]
> @tldahlgren on develop or on this PR? This PR should fix the issue you describe.

On this PR I thought but will try again.

**Review by tldahlgren — APPROVED** [review]
Made sure to have checked out this PR and it works for me.

**Comment by tldahlgren** [comment]
I perhaps should note that I also uninstalled all of the versions I already had just to be sure I was starting completely fresh.

**Pull request merged**
