### PR TITLE
py-black: add v23.1.0

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/psf/black/releases/tag/23.1.0

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed both sha256, rest LGTM

**Comment by tldahlgren** [comment]
One stack had a timeout for one job.

@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
:cry: This broke rhel8 unit-test (and we didn't notice cause we don't run unit tests on package only PRs)

**Pull request merged**
