### PR TITLE
py-greenlet: add 1.1.2

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://github.com/python-greenlet/greenlet/tree/1.1.2

### CODE REVIEW

**Comment by manuelakuhn** [comment]
ping @adamjstewart

**Review by adamjstewart — DISMISSED** [review]

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
@adamjstewart do you have an idea what to do about the failing pipeline?

**Comment by adamjstewart** [comment]
@scottwittenburg?

**Comment by alalazo** [comment]
The pipeline succeeded. Is it fine to merge this?

**Comment by manuelakuhn** [comment]
I think so. I only rebased to try to fix the pipeline issue.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
