### PR TITLE
kokkos-kernels: add v4.1.00, v4.2.00

### PR DESCRIPTION
**Pull request by balay**
ref: https://github.com/spack/spack/pull/38641

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
We probably also want
```
depends_on("kokkos@4.1.00", when="@4.1.00")
depends_on("kokkos@4.0.01", when="@4.0.01")
```

**Review by tldahlgren — APPROVED** [review]
Confirmed the two new version sha256.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
I agree that the `kokkos` dependencies are missing.

**Comment by balay** [comment]
> We probably also want

Thanks, added!

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by balay** [comment]
```
In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-build-ttbgrze/sparse/eti/generated_specializations_cpp/par_ilut_symbolic/Sparse_par_ilut_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_SYCL_MEMSPACE_SY\
CLSPACE.cpp:21:
In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-src/sparse/impl/KokkosSparse_par_ilut_symbolic_spec.hpp:27:
In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-src/sparse/impl/KokkosSparse_par_ilut_symbolic_impl.hpp:27:
/home/xsdk/spack/opt/spack/linux-fedora39-skylake/oneapi-2023.2.0/kokkos-4.1.00-cw5to7qijrjxg7t3aej2oj66p654nird/include/Kokkos_Sort.hpp:70:10: fatal error: 'oneapi/dpl/execution' file not found
#include <oneapi/dpl/execution>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
[spack-build-out.txt](https://github.com/spack/spack/files/12920427/spack-build-out.txt)
```
xsdk@pj01:~/spack1$ find /software/intel/oneapi -name execution
/software/intel/oneapi/dpl/2022.2.0/linux/include/oneapi/dpl/execution
```
This build goes through fine for me for `kokkos-kernels-4.0.00` though..

**Comment by tldahlgren** [comment]
> ```
> In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-build-ttbgrze/sparse/eti/generated_specializations_cpp/par_ilut_symbolic/Sparse_par_ilut_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_SYCL_MEMSPACE_SY\
> CLSPACE.cpp:21:
> In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-src/sparse/impl/KokkosSparse_par_ilut_symbolic_spec.hpp:27:
> In file included from /home/xsdk/spack/spack-stage/spack-stage-kokkos-kernels-4.1.00-ttbgrzewqhfd6vcm6kiyivgtntcrh4sx/spack-src/sparse/impl/KokkosSparse_par_ilut_symbolic_impl.hpp:27:
> /home/xsdk/spack/opt/spack/linux-fedora39-skylake/oneapi-2023.2.0/kokkos-4.1.00-cw5to7qijrjxg7t3aej2oj66p654nird/include/Kokkos_Sort.hpp:70:10: fatal error: 'oneapi/dpl/execution' file not found
> #include <oneapi/dpl/execution>
>          ^~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> [spack-build-out.txt](https://github.com/spack/spack/files/12920427/spack-build-out.txt)
> 
> ```
> xsdk@pj01:~/spack1$ find /software/intel/oneapi -name execution
> /software/intel/oneapi/dpl/2022.2.0/linux/include/oneapi/dpl/execution
> ```
> 
> This build goes through fine for me for `kokkos-kernels-4.0.00` though..

Thanks.  Disabled auto merge.  Ping me when you're ready.

**Comment by balay** [comment]
Ok - this error is showing up in CI as well. Perhaps a kokkos-kernels build issue?

https://gitlab.spack.io/spack/spack/-/jobs/8724394

Note: my gcc/clang builds are fine.

Also cc: @eugeneswalker

**Comment by lucbv** [comment]
Well this explicitly pulls in a oneapi header so that probably only happens in a sycl build.
This is also a header that resides in Kokkos Core not Kokkos Kernels, I'll dig a bit before I reach out to them with this issue.

**Comment by balay** [comment]
> Well this explicitly pulls in a oneapi header so that probably only happens in a sycl build.

This issue comes up with both: `spack install kokkos-kernels@4.1.00 %oneapi@2023.2.0` i.e with `~sycl` and with `spack install kokkos-kernels@4.1.00 %oneapi@2023.2.0 ^kokkos+sycl`

**Comment by lucbv** [comment]
This should be related to the detection of the `ONEDPL` library in Kokkos Core.

**Comment by masterleinad** [comment]
> This should be related to the detection of the `ONEDPL` library in Kokkos Core.

We try to find `oneDPL` by default in `Kokkos` through `CMake` and error out if it can't be found. If `SYCL` isn't requested, we don't try to include `oneDPL` headers. I'm surprised that this issue only comes up with `KokkosKernels` but not with `Kokkos` itself.

**Review by lucbv — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Is there any consensus in how we should handle the error that came up RE DPL? @masterleinad @balay @rscohn2 
* https://github.com/spack/spack/pull/40565#issuecomment-1765043566

**Comment by lucbv** [comment]
@eugeneswalker this is really an issue with Kokkos Core, Kokkos Kernels cannot fix it by itself since we do not control what oneapi headers Kokkos Core includes in its library. The real question is: if this is still happening, why does it not fail in Kokkos Core directly? They must either not test it or not warn that build options required are incorrect. This is more or less what @masterleinad mentioned earlier

**Comment by lucbv** [comment]
Okay the same error happens in the same spot. Did the Kokkos we build against build its unit-test suite?
If so it is lacking one for Sort with SYCL it would appear...

**Comment by rscohn2** [comment]
I expect this will fix the problem: https://github.com/spack/spack/pull/42128

**Comment by eugeneswalker** [comment]
> I expect this will fix the problem: #42128

Cherry-picked that on this PR and will see if that resolves CI here.

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
> > I expect this will fix the problem: #42128
> 
> Cherry-picked that on this PR and will see if that resolves CI here.

Based on most recent CI run-- it looks like that resolved it!

**Comment by lucbv** [comment]
Agreed, it's building PETSc on top of Kokkos Kernels, this should be good now

**Pull request merged**
