### PR TITLE
py-scipy: fix fujitsu build

### PR DESCRIPTION
**Pull request by adamjstewart**
@tkameyama can you see if this fixes the Fujitsu build? I'll test locally with GCC.

Closes #32142

### CODE REVIEW

**Review by rgommers — DISMISSED** [review]
I like this better than the `numpy.distutils` patching approach, so +1 from me to merge if this is confirmed to solve the problem.

**Comment by tkameyama** [comment]
This fix did not build py-scipy@1.9.1 correctly with the Fujitsu compiler.

In the compiler log:

>   INFO: get_default_fcompiler: matching types: '['arm', 'gnu95', 'intel', 'lahey', 'pg', 'nv', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor', 'fujitsu']'
  INFO: customize ArmFlangCompiler
  INFO: customize Gnu95FCompiler

And installer is selected gnu95.

py-scipy@1.2.3%fj is building correctly。

**Comment by alalazo** [comment]
@adamjstewart @tkameyama Feel free to ping me for a merge when this is ready.

**Comment by adamjstewart** [comment]
Curious to see if @rgommers has any other ideas. I would like to fix this in numpy/scipy instead of carrying around a Spack-only patch forever.

**Comment by adamjstewart** [comment]
Superseded by #32142

**Pull request closed without merging**
