### PR TITLE
Adding LANL/TCE used variants for Paraview

### PR DESCRIPTION
**Pull request by Paul-Ferrell**
- Added +eyedomelighting
- Added +pagosa
- Added +fortran
- Added pandas dependency and min version

### CODE REVIEW

**Comment by EthanS94** [comment]
@Paul-Ferrell There is already a vtkm variant, `use_vtkm=default,on,off`. See #21977 for discussion about why a multi-option variant was used.

**Comment by Paul-Ferrell** [comment]
Ah, missed that. I'll fix it.

**Comment by vicentebolea** [comment]
@Paul-Ferrell great contribution, please squash all of your commits to avoid adding to spack history WIP commits

**Comment by alalazo** [comment]
@vicentebolea Let me know when the PR is fine with you. As for:

> please squash all of your commits to avoid adding to spack history WIP commits

don't worry too much about that. We usually "squash-merge" PRs into `develop` :slightly_smiling_face:

**Review by vicentebolea — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
