### PR TITLE
libfabric: Add versions v1.22.0 and v1.21.1

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Review by wdconinc — COMMENTED** [review]
Checksums verified.

**Comment by wdconinc** [comment]
@rajachan Do you have any comments here? `libfabric` gets built [79 (!) times](https://cache.spack.io/package/develop/libfabric/specs/) in the cloud pipelines (none of which seem to be pinned), and in this PR those builds happened succesfully.

**Review by rajachan — APPROVED** [review]

**Comment by rajachan** [comment]
Nit: I would fixup the whitespace commit into the original commit which added the 1.21.1 entry.

**Comment by wdconinc** [comment]
Thanks, @rajachan!

> fixup the whitespace commit into the original commit

Not as critical since we squash merge anyway. But I agree, and an excellent case for `git commit --amend` for future occurrences.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
