### PR TITLE
hypre: add Umpire variant

### PR DESCRIPTION
**Pull request by osborn9**
Add umpire variant to hypre package

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
Will defer merge to give maintainers a chance to comment.

**Comment by balay** [comment]
@osborn9 is the primary maintainer of this package, so its good to go from me!

**Review by balay — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
