### PR TITLE
SS2NEON transition

### PR DESCRIPTION
**Pull request by jserv**
The current spack refers to [jratcliff63367/sse2neon](https://github.com/jratcliff63367/sse2neon) which is NO LONGER considered the official depot for SSE2NEON. Instead, the official SSE2NEON is now [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon). This pull request attempts to redirect SSE2NEON package to the latest repository, adapt the existing packages depending on SSE2NEON and remove out-of-date copy of SSE2NEON.

### CODE REVIEW

**Comment by tldahlgren** [comment]
@darmac ping

**Comment by darmac** [comment]
Got it, I'll check it later.

**Comment by darmac** [comment]
LGTM @tldahlgren  @jserv 
And thanks for your help, I was stun in other project so that have no more time to support this package.

**Comment by tldahlgren** [comment]
> LGTM @tldahlgren @jserv
> And thanks for your help, I was stun in other project so that have no more time to support this package.

@darmac Thank you for taking the time to review this PR

**Review by tldahlgren — APPROVED** [review]
Approved by original author

**Comment by tldahlgren** [comment]
Thank you for your contribution

**Pull request merged**
