### PR TITLE
dd4hep: Patch cmake regex match that is necessary for some versions

### PR DESCRIPTION
**Pull request by tmadlener**
See accompanying pull request in AIDASoft/DD4hep#876

@vvolkl, @drbenmorgan alternatively I could also extend the conflict range here:

https://github.com/spack/spack/blob/02aa1d5d48f70e12b0423a595583c710b88456c3/var/spack/repos/builtin/packages/dd4hep/package.py#L77-L79

To something like
```python
conflicts(`^cmake@3.16:3.17.2`, when=`@1.15:1.18.1`)
```

That might avoid some of the subtle issues around this whole cmake issue with the python versions. Do you have any preferences on that?

### CODE REVIEW

**Comment by alalazo** [comment]
Can we just add a conflict for those versions instead?

**Comment by tmadlener** [comment]
Yes, I think that would be the easiest. That would essentially boil down to extend the existing `conflicts` statement as suggested in the top level comment (I think, I would have to check the details again).

I will rebase this PR and do that, unless you tell me to do something else.

**Comment by alalazo** [comment]
> I will rebase this PR and do that, 

Please do and ping me after that so I can try to push the PR forward to a merge. Thanks!

**Comment by tmadlener** [comment]
@alalazo done

**Review by alalazo — APPROVED** [review]

**Pull request merged**
