### PR TITLE
spack.yaml: add concretizer.yaml to the schema

### PR DESCRIPTION
**Pull request by alalazo**
@bvanessen

### CODE REVIEW

**Comment by bvanessen** [comment]
@alalazo This works for me and solves the problem of being able to add these concretization commands to a environment.

**Review by becker33 — APPROVED** [review]

**Comment by bvanessen** [comment]
@alalazo Is the CI testing stuck?  It has been pending for over 12 hours.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@bvanessen It seems so, just restarted pipelines

**Pull request merged**
