### PR TITLE
alquimia: apply patch for iso_c_binding to latest version

### PR DESCRIPTION
**Pull request by balos1**
CC @balay

### CODE REVIEW

**Review by v-dobrev — APPROVED** [review]

**Review by balay — APPROVED** [review]

**Comment by balay** [comment]
@ghammond86 perhaps this change can be added to alquimia sources aswell

**Comment by balay** [comment]
@ghammond86 @smolins , a reminder!

**Comment by smolins** [comment]
what would that involve?

**Comment by balay** [comment]
@smolins  Attaching the suggested fix as a patchfile

[alquimia.patch.txt](https://github.com/spack/spack/files/13418536/alquimia.patch.txt)

**Comment by smolins** [comment]
@Balay, Satish ***@***.***> Do you want me to update the release?
Thanks
Sergi

**Comment by balay** [comment]
> Do you want me to update the release?

No - we already have this PR merged to spack - so the fix is now in spack for alquimia-1.1.0 (and xsdk-1.0.0).

So its more of - "have this fix upstream for future releases of alquimia (and future xsdk releases/updates)".

```
-    @when("@1.0.10")
+    @when("@1.0.10:1.1.0")
```
So we have this issue in the last xsdk release cyle and missed adding this upstream - hence had to revisit this issue - in this cycle again. So I'm trying to make sure this fix is in the upstream sources [so it will be available in future alquimia/xsdk releases]

**Comment by smolins** [comment]
Great. Thank you
Sergi

**Pull request merged**
