### PR TITLE
intel-oneapi 2023.2.0: added new version to packages

### PR DESCRIPTION
**Pull request by prstrnn**
@rscohn2

### CODE REVIEW

**Review by rscohn2 — APPROVED** [review]
Looks good. Thanks.

**Comment by rscohn2** [comment]
Looks like Fortran has a bad checksum: https://github.com/rscohn2/oneapi-spack-tests/actions/runs/5578907333/jobs/10193734571

**Review by tldahlgren — APPROVED** [review]
Confirmed the version directive's sha256.

**Comment by rscohn2** [comment]
> Confirmed the version directive's sha256.

Thanks for checking. I reran and it passes now.
https://github.com/rscohn2/oneapi-spack-tests/pull/39

**Pull request merged**
