### PR TITLE
make opengl and spectrum-mpi set has_code = False

### PR DESCRIPTION
**Pull request by opadron**
Fixes multiple issues with opengl and spectrum-mpi packages, which are written to be external-only.

### CODE REVIEW

**Review by chuckatkins — APPROVED** [review]

**Comment by opadron** [comment]
This is ready to merge.

 - The failing macos test is not due to these changes.
 - The failing codecov test doesn't even make sense since this is a two-line change in files that are not even part of the coverage report (it's a wonder to me why codecov considers them, at all).

**Comment by chuckatkins** [comment]
It seems the failing macos tests is a blocker to merging, although it's not due to any changes here.

@adamjstewart ?

**Comment by adamjstewart** [comment]
@tldahlgren is this the current recommended approach? Maybe we should rename BundlePackage if it's also used for non-installable packages.

**Comment by chuckatkins** [comment]
We could just as easily set the `has_code = False` property if that's more suitable.

**Comment by alalazo** [comment]
> We could just as easily set the has_code = False property if that's more suitable.

If that works I think it would improve readability.

**Pull request merged**
