### PR TITLE
fix build to work against depends for modules created by setup.py and…

### PR DESCRIPTION
**Pull request by sjtbham**
… add python3 support

### CODE REVIEW

**Comment by lee218llnl** [comment]
Do we want Python 3 to be the same package as python or a separate python3 package?

**Comment by tgamblin** [comment]
I think it makes sense to have it in the `python` package... packages that only need python 2 should depend on `python@:2`, and ones that work with both can depend on `python`.  

What would be the advantage of having it as a separate package?  I know other systems do this but Spack doesn't have to...

**Comment by lee218llnl** [comment]
I wasn't necessarily advocating for a separation, but merely opening the question since I know others separate them. I think it is OK, so long as we can have a Python 2 and Python 3 installation co-exist. We will need to do some testing of the various site packages for Python 3. A Python 3.5.1 release is imminent, potentially in the next week or so, and I will work on this once that is available.

**Comment by sjtbham** [comment]
So I did do a 2 and 3 test install with this, and they both co existed ok.

One issue I did have was activating modules on 3. This was related to the way they get pre byte compiled. I worked around by setting an env variable python uses to not do this, so it needs looking at carefully.

I'm kinda new into spack, but I thought the site modules extend the base class, so wouldn't you have to replicate the whole python modules tree for python3 variants.

**Comment by tgamblin** [comment]
@lee218llnl Is this one ready to merge?  I'll get it in if so.  Note that currently, since we don't have a way to 'prefer' a version, Spack will take the newest one as the default if you omit it on the command line. Maybe I can use this as motivation to get Matt's PR #120 merged, which adds concretization preferences that would let you set 2.7 as your default even if the newest was 3.5.

**Comment by lee218llnl** [comment]
@tgamblin, yes this looks good to me.

**Pull request merged**
