### PR TITLE
VTK-m: Allow building +shared+cuda_native @1.7:

### PR DESCRIPTION
**Pull request by kwryankrattiger**
@vicentebolea @chuckatkins

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
Rebased on develop, hopefully that fixes the CI issue.

**Comment by kwryankrattiger** [comment]
Partially fixes #26818

**Review by vicentebolea — APPROVED** [review]
+1

**Review by alalazo — APPROVED** [review]
Maintainer approved

**Pull request merged**
