### PR TITLE
Overhaul PyTorch package

### LINKED ISSUE #14518: Installation Issue: py-torch fails to fetch sub-repos when running without networking
This is happening @ Argonne Leadership Computing Facility, for the Theta supercomputer.  I am trying to install py-torch however it can not compile on the login nodes, since they are haswell chips and the compute nodes are KNL (I think this is the cause, AVX512 is missing, but it's not clear).

Installing on the login nodes fails for unclear reasons:
```
==> Error: ProcessError: Command exited with status -4:
    '/soft/interpreters/python/3.6/intel/2019.3.075/bin/python3.6' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/lus/theta-fs0/software/datascience/spack/opt/spack/cray-cnl6-mic_knl/gcc-8.3.0/py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq' '--single-version-externally-managed' '--root=/'
See build log for details:
  /tmp/cadams/spack-stage/spack-stage-py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq/spack-build-out.txt
```

There is no extra information in the file specified.

Installing on the compute nodes ought to satisfy the build requirement, however I think py-torch pulls from sub repositories and we don't have access to networking on compute nodes:

```
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Error: ProcessError: Command exited with status 1:
    '/soft/interpreters/python/3.6/intel/2019.3.075/bin/python3.6' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/lus/theta-fs0/software/datascience/spack/opt/spack/cray-cnl6-mic_knl/gcc-8.3.0/py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq' '--single-version-externally-managed' '--root=/'

2 errors found in build log:
     92     Cloning into 'psimd'...
     93     fatal: unable to access 'https://github.com/Maratyszcza/psimd.git/': Failed to connect to github.com port 443: Connection timed out
     94     Cloning into 'psimd'...
     95     fatal: unable to access 'https://github.com/Maratyszcza/psimd.git/': Failed to connect to github.com port 443: Connection timed out
     96     -- Had to git clone more than once:
     97               3 times.
  >> 98     CMake Error at /tmp/cadams/spack-stage/spack-stage-py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq/spack-src/build/confu-deps/psimd-download/psimd-prefix/tmp/psimd-gitclone.cmake:66 (message):
     99       Failed to clone repository: 'https://github.com/Maratyszcza/psimd.git'
     100
     101
     102    ninja: build stopped: subcommand failed.
  >> 103    CMake Error at third_party/FP16/CMakeLists.txt:94 (ADD_SUBDIRECTORY):
     104      ADD_SUBDIRECTORY given source
     105      "/tmp/cadams/spack-stage/spack-stage-py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq/spack-src/build/confu-srcs/psimd"
     106      which is not an existing directory.
     107
     108
     109    -- Found system Eigen at /lus/theta-fs0/software/datascience/spack/opt/spack/cray-cnl6-mic_knl/gcc-8.3.0/eigen-3.3.7-rnf3w44mxhjijj7ok2yaypcttpa3wy7z/include/eigen3

See build log for details:
  /tmp/cadams/spack-stage/spack-stage-py-torch-1.3.1-hbkhwn36w556jas6nexjb3zkh3id2twq/spack-build-out.txt
```

I tried to fetch all of the packages needed for the build prior to running the build script, however it doesn't seem to have the psimd submodule when it goes to install.  Any ideas how to fetch this so it doesn't need to compile?

### LINKED ISSUE #20810: Installation issue: pytorch@1.4.0
### Steps to reproduce the issue

```console
$ spack install py-torch@1.4.0

==> Installing py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh
==> No binary for py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh found: installing from source
==> Using cached archive: /usr/WS1/aml_user/tools/spack/var/spack/cache/_source-cache/git//pytorch/pytorch.git/v1.4.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
This package is normally checked out from a version control system, but it has been archived on a spack mirror. This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Using cached archive: /usr/WS1/aml_user/tools/spack/var/spack/cache/_source-cache/archive/17/17561b16cd2db22f10c0fe1fdcb428aecb0ac3964ba022a41343a6bb8cba7049
==> py-torch: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
'/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/python-2.7.18-7zkgtan7i7efedgkyqxa3talv7zma5io/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh' '--single-version-externally-managed' '--root=/'

$ cat spack-build-out.txt
....
==> py-torch: Executing phase: 'install'
==> [2021-01-12-12:24:38.627661] '/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/python-2.7.18-7zkgtan7i7efedgkyqxa3talv7zma5io/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh' '--single-version-externally-managed' '--root=/'
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Building wheel torch-1.4.0
-- Building version 1.4.0
Could not find /tmp/cdoutrix/spack-stage/spack-stage-py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh/spack-src/third_party/fbgemm/CMakeLists.txt
Did you run 'git submodule update --init --recursive'?
....

```

Seems to be a bug in 1.4.0, recommended to remove this version.

### Information on your system
* **Spack:** 0.16.0
* **Python:** 3.7.2
* **Platform:** linux-rhel7-haswell

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

@adamjstewart 

Related to #20801

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by adamjstewart**
This PR makes the following changes to the `py-torch` package:

- [x] Add PyTorch 1.9.0, https://github.com/pytorch/pytorch/releases/tag/v1.9.0
- [x] Deprecate PyTorch 0.X and 1.4.0
- [x] Don't use vendored third-party libraries when possible
- [x] Add the following variants: kineto, metal, numa, numpy, valgrind, mpi, tensorpipe, onnx_ml
- [x] Remove the following variants: test, miopen, opencv, ffmpeg, leveldb, lmdb, binary, redis, zstd, tbb
- [x] Use same variant defaults as CMake
- [x] Add conflicts for many variants
- [x] pthread_np patch no longer needed in 1.9+, https://github.com/pytorch/pytorch/pull/55063 has been merged

I tested all versions of this package with the default variants on Ubuntu 18.04 with Python 3.8.10/3.7.10 and GCC 7.5.0:

- [x] master
- [x] 1.9.0
- [x] 1.8.1
- [x] 1.7.1
- [x] 1.6.0
- [x] 1.5.1
- [x] 1.4.1
- [x] 1.3.1
- [x] 1.2.0
- [x] 1.1.0
- [x] 1.0.1

Closes #20810 @rblake-llnl 
Closes #14518 @coreyjadams @eugeneswalker

### CODE REVIEW

**Comment by adamjstewart** [comment]
I believe this is finally ready for review! Successfully builds on macOS 10.15.7 with Apple Clang 12.0.0 and on Ubuntu 18.04 with GCC 7.5.0.

**Review by sethrj — APPROVED** [review]
Nice work, I looked at it in detail and didn't see any obvious issues.

**Comment by dylex** [comment]
After this I'm getting an error in the py-torch build trying to link against libpthreadpool.a (not -fPIC, no shared library). I don't see an obvious way to enable building the shared library in the pthreadpool package to fix this. I'll try to track down more details and open an issue, but just wanted to mention it here.

**Comment by adamjstewart** [comment]
Thanks, yes please open an issue for this. I didn't encounter this on any of my systems but if I can reproduce it I'll try to fix it. Also note that this PR introduced a bug that affects `py-torchvision` which will be fixed once #24624 is merged.

**Pull request merged**
