### PR TITLE
Update SymEngine package to enable build against LLVM

### PR DESCRIPTION
**Pull request by jppelteret**

### CODE REVIEW

**Comment by jppelteret** [comment]
@isuruf ping

**Comment by tgamblin** [comment]
I'm assuming LLVM here means "LLVM used as a library" for jitting or something like that?  Not as the compiler, right?  I'm only asking b/c I would say to use `%clang` for the latter.

**Comment by jppelteret** [comment]
@tgamblin Yes, that's correct. I'll extend the description of this variant to make it more clear.

**Comment by isuruf** [comment]
LLVM package built from spack doesn't work for me on Linux. (shared libs fail due to https://github.com/LLNL/spack/issues/1616, static libs fail with some error about relocation. I'll report this when I have some time.) But if this works for you, that's great.

**Comment by jppelteret** [comment]
@isuruf Thanks for the info - that's annoying. I've just managed to build this on `MacOS` for the first time, so later this morning I'll see if I run into the same troubles as you...

**Pull request merged**
