### PR TITLE
Add CCE support to hipfort

### PR DESCRIPTION
**Pull request by lukebroskop**
Add CCE support to hipfort

### CODE REVIEW

**Comment by cgmb** [comment]
Is this a workaround for a problem in the hipfort build, or is this the normal set of variables that you have to specify to build any library with CCE?

**Comment by lukebroskop** [comment]
This is a normal set of variables that are needed to override the variables set by the hipfort build. Otherwise the build will fail as the Cray fortran compiler does not accept the same flags that are defaulted for the GCC build. 

From:
https://github.com/ROCmSoftwarePlatform/hipfort/blob/6f6ae98ed45df9a66e48121ec7c0cb8f0fbd6137/CMakeLists.txt#L9-L15
```
# Default compiler gfortran, otherwise cmake Fortran package will set it to f95
# You can override the compiler with cmake -DHIPFORT_COMPILER=
set(HIPFORT_COMPILER "/usr/bin/gfortran" CACHE STRING "Fortran Compiler to build HIPFORT")
set(HIPFORT_AR "/usr/bin/gcc-ar" CACHE STRING "Static archive command")
set(HIPFORT_RANLIB "/usr/bin/gcc-ranlib" CACHE STRING "ranlib used to create Static archive")
set(HIPFORT_COMPILER_FLAGS "-ffree-form -cpp -ffree-line-length-none -fmax-errors=5" CACHE STRING "Compiler flags to build HIPFORT")
```

**Review by cgmb — APPROVED** [review]
LGTM. Though, it seems weird to me that hipfort uses `HIPFORT_COMPILER` rather than `CMAKE_Fortran_COMPILER`.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
