### PR TITLE
Update OMB package with latest release

### PR DESCRIPTION
**Pull request by natshineman**
Update OMB source to the latest release 6.0

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]
@harisubramoni  @MatthewLieber can you confirm it is fine with you to be added as maintainers?

**Comment by MatthewLieber** [comment]
Confirming being added as a maintainer.

**Comment by harisubramoni** [comment]
> @harisubramoni @MatthewLieber can you confirm it is fine with you to be added as maintainers?

yes - of course

**Review by harisubramoni — COMMENTED** [review]
The changes look good.

**Pull request merged**
