### PR TITLE
new package: roentdek

### PR DESCRIPTION
**Pull request by eugeneswalker**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]
Waiting for @valmar review before merging

**Comment by valmar** [comment]
@alalazo This looks OK to me. However, I am not sure we have the permission to distribute this, as this is closed source software provided by the manufacturer.

**Comment by eugeneswalker** [comment]
> @alalazo This looks OK to me. However, I am not sure we have the permission to distribute this, as this is closed source software provided by the manufacturer.

Should we revert this ?

**Comment by valmar** [comment]
Let me investigate

**Comment by valmar** [comment]
So we discussed it internally and the situation is unclear. But this recipe pulls in a binary blob, we are not sharing any closed source code here.

**Comment by valmar** [comment]
Let me see if this is a hard dependency

**Comment by valmar** [comment]
It looks like it is not, and it should be possible to build the package without this dependency. I will test things over the weekend. This dependency is only needed when using the software together with the hardware

**Comment by valmar** [comment]
Ok I tested and psalg can definitely be compiled without `roentdek`. So at this point, I would remove this package as a dependency of `psalg` and then remove this package to avoid any legal problems

**Pull request merged**
