### PR TITLE
JAX: add v0.4.28

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Review by jonas-eschle — APPROVED** [review]
Seems good to me! One thing:

> The Windows build is now built with Clang instead of MSVC.

Shouldn't affect us AFAIU, right?

**Comment by adamjstewart** [comment]
Nope, the user can choose both compilers. Not even sure if this builds on Windows yet. We'll likely add Windows CI in the future to test.

**Comment by jonas-eschle** [comment]
> We'll likely add Windows CI in the future to test.

I imagine the use-case for building large scientific stacks on _windows_ to be abithimal small :D

**Comment by adamjstewart** [comment]
You'd be surprised, conda is very popular on Windows.

**Comment by jonas-eschle** [comment]
Yes, conda hardly surprises me (I mean, the fact that many people use windows for coding surprised me, but let's take that fact as given), but I think because that's the only way to _reasonable_ install packages for data analysis as an end-user, spack has AFAIU a very different target audience, i.e. HPC, built by source, and usually on servers rather than desktop (or to setup a VM, which hopefully Windows isn't used a lot). But I may be wrong, curious to see if there is an estimate on the spack usage on windows.
Sorry for the digress ;)

**Review by alalazo — APPROVED** [review]

**Pull request merged**
