### PR TITLE
add ROCmPackage to OSU Micro Benchmarks

### PR DESCRIPTION
**Pull request by paklui**
To add ROCmPackage support for AMD GPU

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by tldahlgren** [comment]
Wil defer merge decision to give at least one maintainer a chance to comment.

**Review by natshineman — DISMISSED** [review]
This looks good to me. The configure flags are correct so we can go ahead and take this in.

**Comment by tldahlgren** [comment]
@spackbot fix style

**Comment by paklui** [comment]
looks like before merging, we still need a review after @spackbot dismissed the earlier review...

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
