### PR TITLE
add conduit 0.8.0 release and change def for parmetis var

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Review by white238 — DISMISSED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
There are legitimate failures in the pipeline e.g. `ascent`

**Comment by cyrush** [comment]
@alalazo having CI testing of builds wired up is good stuff.  Makes me happy to avoid breaking things before they go into spack :-)

ascent@develop can use new conduit, but the prior release cannot due to api changes. 

I pushed a constraint to fix.

**Comment by cyrush** [comment]
There is something in the ecp-viz-sdk that is causing conduit 0.8.0 to be selected. 

How can I make sure the proper constraints are applied there?

**Comment by cyrush** [comment]
I see it's building an older version of ascent than I expected.

**Comment by cyrush** [comment]
@spackbot run pipeline

**Comment by cyrush** [comment]
Looks like with the constraints we are in good shape to merge.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
