### PR TITLE
Eigen upgrade

### PR DESCRIPTION
**Pull request by georgi-mania**
Upgrade eigen library to latest release (3.4.0). @HaoZeke please review the change.

### CODE REVIEW

**Review by HaoZeke — DISMISSED** [review]
LGTM, thanks for this. Could you squash the commits though?

```bash
git reset --soft HEAD~2
git commit -m "eigen: Update to include 3.4.0"
```

Or
```bash
git rebase -i HEAD~2
# Then follow the instructions to merge the commits
```

You will need to force push to the branch after this.

**Comment by georgi-mania** [comment]
@HaoZeke : Thanks for the suggestion. I followed the `reset` than `commit` squash but now I have the merge commit.. so still 2.

**Comment by HaoZeke** [comment]
> @HaoZeke : Thanks for the suggestion. I followed the `reset` than `commit` squash but now I have the merge commit.. so still 2. 

Ack sorry, to remove the merge commit you'd need to rebase onto the common commit.

**Comment by georgi-mania** [comment]
@HaoZeke Should be fixed now.

**Review by HaoZeke — APPROVED** [review]
Excellent, thanks.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
