### PR TITLE
[range-v3] Remove overbroad boost dependence

### PR DESCRIPTION
**Pull request by greenc-FNAL**

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
@spackbot style

**Comment by greenc-FNAL** [comment]
@spackbot help

**Comment by greenc-FNAL** [comment]
@spackbot fix style

**Review by alalazo — APPROVED** [review]
For reference: https://github.com/ericniebler/range-v3/blob/master/example/CMakeLists.txt

**Pull request merged**
