### PR TITLE
Update Kokkos for release 3.4.00 and add SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
This adds the latest release and also allows to build with the SYCL backend to support Intel GPUs.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Standard practice is to make it conflict to enable the sycl variant for versions before we added support

**Comment by masterleinad** [comment]
> Standard practice is to make it conflict to enable the sycl variant for versions before we added support

Sure, I added that. Note that we could already use 3.3.00 but I feel more confident with 3.4.00.

**Comment by DavidPoliakoff** [comment]
That's what I would have suggested. I'll take a more thorough look soon. What compilers do we support with SYCL? I'm curious how Spack tends to integrate those compilers

**Comment by masterleinad** [comment]
`SYCL` means `DPC++` in `Kokkos` so we only really care about `Intel` compilers and `spack` already defines `oneapi` as a compiler.
In general, it's `icpx` and `clang++` from https://github.com/intel/llvm/.

**Comment by DavidPoliakoff** [comment]
I'm curious whether anybody has an comments about best practices for saying "hey, we need to be compiled with DPC++" @becker33, any ideas on standard practice there, or who we should bother?

**Comment by DavidPoliakoff** [comment]
Unless it's literally just some way we say "require oneapi"

**Review by DavidPoliakoff — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Do you want to wait for comment from @becker33 or others before merging? If not, am happy to merge, but I will wait for confirmation before doing so. Thanks!

**Comment by masterleinad** [comment]
I think it's fine to merge as-is. We can always try to detect if a suitable compiler is used later and this should be enough to allow people to use the `SYCL` backend in `Kokkos`.

**Review by eugeneswalker — APPROVED** [review]
Thank you!

**Pull request merged**
