### PR TITLE
ci: add minimal gpu testing stack

### PR DESCRIPTION
**Pull request by eugeneswalker**
Creating a minimal `gpu-tests` CI stack for running `spack test` on AMD and NVIDIA GPU-equipped runners at the University of Oregon.

CC @scottwittenburg @tldahlgren

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
Errors on the `kokkos +cuda` `spack test`
* [(specs) kokkos/4c2qaal 3.7.01 gcc@11.1.0 linux-ubuntu20.04-x86_64 GPU Testing](https://gitlab.spack.io/spack/spack/-/jobs/5376036)
```
...Errors while running CTest
Output from these tests are in: /tmp/root/spack-stage/spack-standalone-tests/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
1 error found in test log:
     232    Unable to find executable: /tmp/root/spack-stage/spack-standalone-t
            ests/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/cache/k
            okkos/scripts/spack_test/out/random_numbers
     233    Unable to find executable: /tmp/root/spack-stage/spack-standalone-t
            ests/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/cache/k
            okkos/scripts/spack_test/out/dual_view
     234    Errors while running CTest
     235    Output from these tests are in: /tmp/root/spack-stage/spack-standal
            one-tests/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/Te
            sting/Temporary/LastTest.log
     236    Use "--rerun-failed --output-on-failure" to re-run the failed cases
             verbosely.
     237    make: *** [Makefile:71: test] Error 8
  >> 238    FAILED: Command exited with status 2:
     239        '/usr/bin/make' '/tmp/root/spack-stage/spack-standalone-tests/t
            mz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/cache/kokkos/
            scripts/spack_test/out' 'test'
     240    Running tests...
     241    Test project /tmp/root/spack-stage/spack-standalone-tests/tmz27bxwr
            7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal
     242        Start 1: hello_world
     243    Could not find executable /tmp/root/spack-stage/spack-standalone-te
            sts/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal/cache/ko
            kkos/scripts/spack_test/out/hello_world
     244    Looked in the following places:
See test log for details:
  /tmp/root/spack-stage/spack-standalone-tests/tmz27bxwr7r67nhqbyeb4cab54e6yk6a/kokkos-3.7.01-4c2qaal-test-out.txt
Traceback (most recent call last):
  File "/builds/spack/spack/lib/spack/spack/build_environment.py", line 1038, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/builds/spack/spack/lib/spack/spack/package_base.py", line 2584, in test_process
    raise TestFailure(pkg.test_failures)
spack.install_test.TestFailure: 2 tests failed.
Command exited with status 2:
    '/usr/bin/make'
[ 12%] Building CXX object CMakeFiles/hello_world.dir/hello_world.cpp.o
/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/kokkos-nvcc-wrapper-3.2.00-l26c3e367eclxzvkcmbjhrjnwat7tjqf/bin/nvcc_wrapper: line 505: nvcc: command not found
```

Cutting through some of the padding text:
```
...gcc-11.1.0/kokkos-nvcc-wrapper-3.2.00-l26c3e367eclxzvkcmbjhrjnwat7tjqf/bin/nvcc_wrapper: line 505: nvcc: command not found
```

Maybe `nvcc` isn't in the PATH because `cuda` isn't being loaded for `spack test`. @wspear is this what you were talking about in one of the other posts today -- on an unrelated test -- that `spack test` doesn't load any dependencies?

**Comment by eugeneswalker** [comment]
Just updated the PR index cache

@spackbot run pipeline

**Comment by eugeneswalker** [comment]
CI runs for this PR identified the following issue with the stand-alone test for `kokkos +cuda +wrapper` 
* CI job log: https://gitlab.spack.io/spack/spack/-/jobs/5376036
 * https://github.com/spack/spack/issues/35291

**Comment by eugeneswalker** [comment]
`raja +cuda` stand-alone test is failing:
* CI job log: [(specs) raja/xho3jxi 2022.03.0 gcc@11.1.0 linux-ubuntu20.04-x86_64 GPU Testing](https://gitlab.spack.io/spack/spack/-/jobs/5400763)
* https://github.com/spack/spack/issues/35310

**Comment by zackgalbreath** [comment]
@spackbot run pipeline

**Comment by zackgalbreath** [comment]
@spackbot run pipeline

**Review by wspear — APPROVED** [review]

**Pull request merged**
