### PR TITLE
Added support for spack external find to HWLOC

### PR DESCRIPTION
**Pull request by bvanessen**

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Currently failing some style checks

**Review by bgoglin — DISMISSED** [review]
I don't know spack enough to understand how this is used, but it looks ok from the hwloc point of view.

**Review by alalazo — DISMISSED** [review]
Can you rebase to re-run Gitlab pipelines on a new merge commit?

**Comment by bvanessen** [comment]
@alalazo Done

**Review by alalazo — APPROVED** [review]

**Pull request merged**
