### PR TITLE
openimagedenoise: add v2.0.1

### PR DESCRIPTION
**Pull request by aumuell**
required by ospray@2.12

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):

```
...
-- Found Embree v3.13.5: /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/embree-3.13.5-lltprmdvufwe5mgh7lsnt4y2g4snydie/lib/libembree3.so.3.13.5
-- Found Open VKL v1.3.1: /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/openvkl-1.3.1-jvgkniftxsdyqipqgwtcw5zdp3kuqw3q/lib/libopenvkl.so.1.3.1
CMake Error at cmake/ospray_options.cmake:44 (find_package):
  Could not find a configuration file for package "OpenImageDenoise" that is
  compatible with requested version "1.2.3".
  The following configuration files were considered but not accepted:
    /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/openimagedenoise-2.0.1-ebvdarbg44wuipt4bp6ktnlkhsk4psnd/lib/cmake/OpenImageDenoise-2.0.1/OpenImageDenoiseConfig.cmake, version: 2.0.1
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)
-- Configuring incomplete, errors occurred!
...
```

**Comment by aumuell** [comment]
Thank you for looking so closely!

> Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):
> ```Could not find a configuration file for package "OpenImageDenoise" that is```
>  ```compatible with requested version "1.2.3".```

This error would be resolved by #40394 by this dependency block:
```
with when("+denoiser"):
        depends_on("openimagedenoise@1.2.3:")
        depends_on("openimagedenoise@1.3:", when="@2.5:")
        depends_on("openimagedenoise@:1", when="@:2.11")
        depends_on("openimagedenoise@2:", when="@2.12:")
```

I don't know very well how to handle that. Merge the PRs into one?

**Comment by tldahlgren** [comment]
> Thank you for looking so closely!
> 
> > Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):
> > `Could not find a configuration file for package "OpenImageDenoise" that is`
> > `compatible with requested version "1.2.3".`
> 
> This error would be resolved by #40394 by this dependency block:
> 
> ```
> with when("+denoiser"):
>         depends_on("openimagedenoise@1.2.3:")
>         depends_on("openimagedenoise@1.3:", when="@2.5:")
>         depends_on("openimagedenoise@:1", when="@:2.11")
>         depends_on("openimagedenoise@2:", when="@2.12:")
> ```
> 
> I don't know very well how to handle that. Merge the PRs into one?

Yes, you can rebase to develop once #40394 is merged, which is roughly equivalent to `Update branch`.

**Comment by tldahlgren** [comment]
> > Thank you for looking so closely!
> > > Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):
> > > `Could not find a configuration file for package "OpenImageDenoise" that is`
> > > `compatible with requested version "1.2.3".`
> > 
> > 
> > This error would be resolved by #40394 by this dependency block:
> > ```
> > with when("+denoiser"):
> >         depends_on("openimagedenoise@1.2.3:")
> >         depends_on("openimagedenoise@1.3:", when="@2.5:")
> >         depends_on("openimagedenoise@:1", when="@:2.11")
> >         depends_on("openimagedenoise@2:", when="@2.12:")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know very well how to handle that. Merge the PRs into one?
> 
> Yes, you can rebase to develop once #40394 is merged, which is roughly equivalent to `Update branch`.

Hmmm.  So a bit of a chicken-and-egg problem perhaps.

**Comment by tldahlgren** [comment]
> Thank you for looking so closely!
> 
> > Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):
> > `Could not find a configuration file for package "OpenImageDenoise" that is`
> > `compatible with requested version "1.2.3".`
> 
> This error would be resolved by #40394 by this dependency block:
> 
> ```
> with when("+denoiser"):
>         depends_on("openimagedenoise@1.2.3:")
>         depends_on("openimagedenoise@1.3:", when="@2.5:")
>         depends_on("openimagedenoise@:1", when="@:2.11")
>         depends_on("openimagedenoise@2:", when="@2.12:")
> ```
> 
> I don't know very well how to handle that. Merge the PRs into one?

> Thank you for looking so closely!
> 
> > Looks like there's a failure for ospray@2.8.0 (https://gitlab.spack.io/spack/spack/-/jobs/8595379):
> > `Could not find a configuration file for package "OpenImageDenoise" that is`
> > `compatible with requested version "1.2.3".`
> 
> This error would be resolved by #40394 by this dependency block:
> 
> ```
> with when("+denoiser"):
>         depends_on("openimagedenoise@1.2.3:")
>         depends_on("openimagedenoise@1.3:", when="@2.5:")
>         depends_on("openimagedenoise@:1", when="@:2.11")
>         depends_on("openimagedenoise@2:", when="@2.12:")
> ```
> 
> I don't know very well how to handle that. Merge the PRs into one?

That's probably the easiest approach.

**Comment by aumuell** [comment]
Now included in #40394.

**Pull request closed without merging**
