### PR TITLE
OpenCV: disable variants by default

### PR DESCRIPTION
**Pull request by adamjstewart**
Previously, almost all of the optional variants in the OpenCV package were enabled by default. This results in long build times and a ton of dependencies:
```console
$ spack spec opencv
Input spec
--------------------------------
opencv

Concretized
--------------------------------
opencv@4.2.0%apple-clang@12.0.0+calib3d~contrib+core~cuda~cudacodec+dnn+eigen~fast-math+features2d+flann+gtk+highgui+imgproc~ipo+ipp+ipp_iw+jasper+java+jpeg+lapack+ml+opencl+opencl_svm+openclamdblas+openclamdfft+openmp+png~powerpc+pthreads_pf+python~qt+shared+stitching+superres+tiff+ts+video+videoio+videostab~vsx+vtk+zlib build_type=RelWithDebInfo cuda_arch=none arch=darwin-catalina-x86_64
    ^ant@1.10.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^jdk@12.0.1_12%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^cmake@3.19.1%apple-clang@12.0.0~doc+ncurses+openssl+ownlibs~qt arch=darwin-catalina-x86_64
        ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
            ^pkgconf@1.7.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^openssl@1.1.1h%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
            ^perl@5.32.0%apple-clang@12.0.0+cpanm+shared+threads patches=517afe8ca1cb12f798f20b21583d91463fe3f4fa9244c6c8e054a92c8135da8f arch=darwin-catalina-x86_64
                ^berkeley-db@18.1.40%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
    ^eigen@3.3.8%apple-clang@12.0.0~ipo build_type=RelWithDebInfo patches=62590e9b33a8f72b608a72b87147a306e7cb20766ea53c6b8e0a183fa6cb7635 arch=darwin-catalina-x86_64
    ^ffmpeg@4.2.2%apple-clang@12.0.0~X~avresample+bzlib~drawtext+gpl~libaom~libmp3lame~libopenjpeg~libopus~libsnappy~libspeex~libssh~libvorbis~libwebp~libzmq~lzma~nonfree~openssl~sdl2+shared+version3 arch=darwin-catalina-x86_64
        ^bzip2@1.0.8%apple-clang@12.0.0+shared arch=darwin-catalina-x86_64
            ^diffutils@3.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libiconv@1.16%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^yasm@1.3.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^gtkplus@3.20.10%apple-clang@12.0.0~cups arch=darwin-catalina-x86_64
        ^at-spi2-atk@2.34.2%apple-clang@12.0.0 buildtype=release arch=darwin-catalina-x86_64
            ^at-spi2-core@2.38.0%apple-clang@12.0.0 buildtype=release arch=darwin-catalina-x86_64
                ^dbus@1.12.8%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^expat@2.2.10%apple-clang@12.0.0~libbsd arch=darwin-catalina-x86_64
                    ^glib@2.66.2%apple-clang@12.0.0~libmount patches=b3fd45063a19c871048aa1f28692293ab8971a871bdcbe65f06f17fdd79db9e2 tracing=none arch=darwin-catalina-x86_64
                        ^gettext@0.21%apple-clang@12.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64
                            ^libxml2@2.9.10%apple-clang@12.0.0~python arch=darwin-catalina-x86_64
                                ^xz@5.2.5%apple-clang@12.0.0~pic arch=darwin-catalina-x86_64
                            ^tar@1.32%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libffi@3.3%apple-clang@12.0.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-catalina-x86_64
                        ^meson@0.56.0%apple-clang@12.0.0 patches=7a7ff3bffb5c1996faf178da6765d578394624edb96fe9297bf21f2e3cd9ebda arch=darwin-catalina-x86_64
                            ^ninja@1.10.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^python@3.8.6%apple-clang@12.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=darwin-catalina-x86_64
                                    ^sqlite@3.33.0%apple-clang@12.0.0+column_metadata+fts~functions~rtree arch=darwin-catalina-x86_64
                            ^py-setuptools@50.3.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^pcre@8.44%apple-clang@12.0.0~jit+multibyte+utf arch=darwin-catalina-x86_64
                    ^libsm@1.2.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libice@1.0.9%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^util-macros@1.19.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^xproto@7.0.31%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^xtrans@1.3.5%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libuuid@1.0.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^fixesproto@5.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^gobject-introspection@1.56.1%apple-clang@12.0.0 patches=6f90bb267efa043ed70b900b4b8e2faf9e8133afae311893b01060356ea81bba arch=darwin-catalina-x86_64
                    ^bison@3.6.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^help2man@1.47.11%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^m4@1.4.18%apple-clang@12.0.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=darwin-catalina-x86_64
                            ^libsigsegv@2.12%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^cairo@1.16.0%apple-clang@12.0.0+X+fc+ft+gobject+pdf~png~svg patches=7c4da77767fe9feb03f8051def0832f0c67f99162913275cfa127a88df19cf51 arch=darwin-catalina-x86_64
                        ^autoconf@2.69%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^automake@1.16.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^fontconfig@2.13.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^font-util@1.3.2%apple-clang@12.0.0 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-ttf,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1 arch=darwin-catalina-x86_64
                                ^bdftopcf@1.0.5%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                    ^fontsproto@2.1.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                    ^libxfont@1.5.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                        ^freetype@2.10.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                            ^libpng@1.6.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                        ^libfontenc@1.1.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^mkfontdir@1.0.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                    ^mkfontscale@1.1.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^gperf@3.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libtool@2.4.6%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libx11@1.7.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^inputproto@2.3.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^kbproto@1.0.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^libxcb@1.14%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^libpthread-stubs@0.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^libxau@1.0.8%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^libxdmcp@1.1.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^xcb-proto@1.14.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^xextproto@7.3.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libxext@1.3.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libxrender@0.9.10%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^renderproto@0.11.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^pixman@0.40.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^flex@2.6.4%apple-clang@12.0.0+lex patches=09c22e5c6fef327d3e48eb23f0d610dcd3a35ab9207f12e0f875701c677978d3 arch=darwin-catalina-x86_64
                        ^findutils@4.6.0%apple-clang@12.0.0 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=darwin-catalina-x86_64
                            ^texinfo@6.5%apple-clang@12.0.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=darwin-catalina-x86_64
                    ^sed@4.2.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxi@1.7.6%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libxfixes@5.0.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxtst@1.2.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^recordproto@1.14.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^atk@2.36.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^gdk-pixbuf@2.40.0%apple-clang@12.0.0~x11 patches=6f6e6411051846f0e99e5f46e07c78428c4a2a88f51c202b3122972d91452f4c arch=darwin-catalina-x86_64
            ^docbook-xsl@1.79.2%apple-clang@12.0.0 patches=a92c39715c54949ba9369add1809527b8f155b7e2a2b2e30cb4b39ee715f2e30 arch=darwin-catalina-x86_64
                ^docbook-xml@4.5%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libjpeg-turbo@2.0.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^nasm@2.15.05%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libtiff@4.1.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libxslt@1.1.33%apple-clang@12.0.0+crypto~python arch=darwin-catalina-x86_64
                ^libgcrypt@1.8.5%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libgpg-error@1.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^gawk@5.0.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^gmp@6.1.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^mpfr@4.0.2%apple-clang@12.0.0 patches=3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0 arch=darwin-catalina-x86_64
                                ^autoconf-archive@2019.01.06%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^libepoxy@1.4.3%apple-clang@12.0.0+glx arch=darwin-catalina-x86_64
            ^opengl@2.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^pango@1.41.0%apple-clang@12.0.0+X arch=darwin-catalina-x86_64
            ^harfbuzz@2.6.8%apple-clang@12.0.0~graphite2 arch=darwin-catalina-x86_64
                ^icu4c@67.1%apple-clang@12.0.0 cxxstd=11 arch=darwin-catalina-x86_64
            ^libxft@2.3.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^shared-mime-info@1.9%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^intltool@0.51.0%apple-clang@12.0.0 patches=ca9d6562f29f06c64150f50369a24402b7aa01a3a0dc73dce55106f3224330a1 arch=darwin-catalina-x86_64
                ^perl-xml-parser@2.44%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^perl-libwww-perl@6.33%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-encode-locale@1.05%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-file-listing@6.04%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^perl-http-date@6.02%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-html-parser@3.72%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^perl-html-tagset@3.20%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-http-cookies@6.04%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^perl-http-message@6.13%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-io-html@1.001%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-lwp-mediatypes@6.02%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-try-tiny@0.28%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-uri@1.72%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                    ^perl-test-needs@0.002005%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-http-daemon@6.01%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^perl-module-build-tiny@0.039%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-extutils-config@0.008%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-extutils-helpers@0.026%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-extutils-installpaths@0.012%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                                ^perl-module-build@0.4224%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-http-negotiate@6.01%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-net-http@6.17%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^perl-www-robotrules@6.02%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^intel-mkl@2020.0.166%apple-clang@12.0.0~ilp64+shared threads=none arch=darwin-catalina-x86_64
    ^jasper@2.0.16%apple-clang@12.0.0+jpeg~opengl+shared build_type=Release arch=darwin-catalina-x86_64
    ^openmpi@3.1.6%apple-clang@12.0.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=darwin-catalina-x86_64
        ^hwloc@1.11.11%apple-clang@12.0.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~pci+shared arch=darwin-catalina-x86_64
    ^protobuf@3.12.2%apple-clang@12.0.0+shared build_type=Release arch=darwin-catalina-x86_64
    ^py-numpy@1.19.4%apple-clang@12.0.0+blas+lapack arch=darwin-catalina-x86_64
        ^py-cython@0.29.21%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^vtk@9.0.0%apple-clang@12.0.0~ffmpeg~ipo~mpi+opengl2~osmesa~python~qt~xdmf build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^double-conversion@2.0.1%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^glew@2.1.0%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^hdf5@1.10.7%apple-clang@12.0.0~cxx~debug~fortran+hl~java~mpi+pic+shared~szip~threadsafe api=none arch=darwin-catalina-x86_64
        ^jsoncpp@1.9.2%apple-clang@12.0.0~ipo build_type=RelWithDebInfo cxxstd=default arch=darwin-catalina-x86_64
        ^lz4@1.9.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^netcdf-c@4.7.4%apple-clang@12.0.0~dap~hdf4~jna~mpi~parallel-netcdf+pic+shared arch=darwin-catalina-x86_64
        ^netcdf-cxx@4.2%apple-clang@12.0.0+netcdf4 arch=darwin-catalina-x86_64
```
By setting the default to False, we have way fewer deps:
```console
$ spack spec opencv
Input spec
--------------------------------
opencv

Concretized
--------------------------------
opencv@4.2.0%apple-clang@12.0.0~calib3d~contrib+core~cuda~cudacodec~dnn~eigen~fast-math~features2d~flann~gtk~highgui~imgproc~ipo~ipp~ipp_iw~jasper~java~jpeg~lapack~ml~opencl~opencl_svm~openclamdblas~openclamdfft~openmp~png~powerpc~pthreads_pf~python~qt+shared~stitching~superres~tiff~ts~video~videoio~videostab~vsx~vtk~zlib build_type=RelWithDebInfo cuda_arch=none arch=darwin-catalina-x86_64
    ^cmake@3.19.1%apple-clang@12.0.0~doc+ncurses+openssl+ownlibs~qt arch=darwin-catalina-x86_64
        ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
            ^pkgconf@1.7.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^openssl@1.1.1h%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
            ^perl@5.32.0%apple-clang@12.0.0+cpanm+shared+threads patches=517afe8ca1cb12f798f20b21583d91463fe3f4fa9244c6c8e054a92c8135da8f arch=darwin-catalina-x86_64
                ^berkeley-db@18.1.40%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
```
I've confirmed that this builds on macOS 10.15.6 with Apple Clang 12.0.0 and on Ubuntu 18.04 with GCC 7.5.0.

It would be good to check if this breaks any packages that depend on OpenCV:
```console
$ spack dependents opencv
bohrium  caffe  candle-benchmarks  cntk  lbann  mivisionx  mxnet  py-cinema-lib  py-mmcv  py-torch  saga-gis
```
The following people are listed as maintainers for those packages:
@EthanS94  @arjun-raj-kuppala  @bvanessen  @mfherbst  @srekolam

If any of your packages require specific OpenCV components, these should be explicitly specified in the `depends_on`.

### CODE REVIEW

**Comment by aweits** [comment]
This feels like it would really surprise someone who was installing opencv - to have to manually turn on image/media codecs. Is there some middle ground between where the flags are now and all off?

**Comment by adamjstewart** [comment]
There's definitely room for middle ground. What would be great is if someone who uses the package offers to be a maintainer and makes that decision for us. I've only ever installed OpenCV as a dependency.

My general philosophy with packages is to set all variants that add dependencies to False. For example, the GDAL package has support for hundreds of obscure file formats, but they are all disabled by default.

**Comment by bvanessen** [comment]
@adamjstewart When I added a lot of those variants a long time ago, I set their defaults to the standard cmake defaults in their code.  However, I agree they should be off by default.

**Comment by adamjstewart** [comment]
@bvanessen want to be a maintainer?

**Comment by bvanessen** [comment]
@adamjstewart Sure.

**Comment by aweits** [comment]
excuse the diff-shorthand, but would this be an acceptable compromise?
```diff
+    variant('python', default=True,
+    variant('video', default=True, description='video module')
+    variant('videoio', default=True, description='videoio module')
+    variant('jpeg', default=True, description='Include JPEG support')
+    variant('png', default=True, description='Include PNG support')
+    variant('mpi', default=False, description='Include MPI support for videoio')
+    variant('tiff', default=True, description='Include TIFF support')
+    variant('zlib', default=True, description='Build zlib from source')
-    depends_on('mpi', when='+videoio')
+    depends_on('mpi', when='+mpi')
```

**Comment by adamjstewart** [comment]
I'll let @bvanessen decide if those defaults sound good to him. I'm happy as long as the default dependencies are as few as possible.

**Comment by bvanessen** [comment]
> excuse the diff-shorthand, but would this be an acceptable compromise?
> 
> ```diff
> +    variant('python', default=True,
> +    variant('video', default=True, description='video module')
> +    variant('videoio', default=True, description='videoio module')
> +    variant('jpeg', default=True, description='Include JPEG support')
> +    variant('png', default=True, description='Include PNG support')
> +    variant('mpi', default=False, description='Include MPI support for videoio')
> +    variant('tiff', default=True, description='Include TIFF support')
> +    variant('zlib', default=True, description='Build zlib from source')
> -    depends_on('mpi', when='+videoio')
> +    depends_on('mpi', when='+mpi')
> ```

I would actually be fully in favor of going to everything off and only turn on what a user needs.  I don't know that we can universally say that both jpeg and png are needed by everyone.

**Review by aweits — APPROVED** [review]
builds on linux-centos8-skylake_avx512 / gcc@9.3.0

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks @bvanessen for volunteering on OpenCV!

**Pull request merged**
