### PR TITLE
concretizer: update `reuse:` default to True

### PR DESCRIPTION
**Pull request by becker33**
We've seen a rash of issues with the default reuse parameters for the concretizer.

Specifically, many users have the following workflow:

1. Install spec foo+bar
2. Push foo to buildcache
3. Spack install foo

In that workflow, `foo` should install as `foo+bar` from binary. That will not necessarily happen with the current defaults.

This gets even worse in the case of a shared binary cache (like the spack public caches) that may have newer versions of the dependencies. In that case, the install may not work from binary even without specifying a variant or without any non-default aspects for the package in the buildcache.

@tgamblin and I have come to the belief that the current default is less intuitive than pure reuse. The `reuse: dependencies` config options and the `--reuse-deps` flags are still available for users who want the fresh concretization of roots.

### CODE REVIEW

**Comment by haampie** [comment]
I think it's pretty ambiguous which default is better.

Iterating with `spack edit x` `spack install x` is more convenient with current defaults.

So is `spack checksum --add-to-package x` `spack install x`.

**Review by tgamblin — DISMISSED** [review]

**Comment by tgamblin** [comment]
please add to #30634

**Comment by michaelkuhn** [comment]
I agree with @haampie, the usual development workflows are pretty annoying with `reuse: True`.

Moreover, this breaks the upgrade workflow:
```
$ spack install xyz
# Update Spack
$ spack mark -ai
$ spack install xyz
$ spack gc
```
With `reuse: True`, the second `install` will usually simply reuse the old version.

**Comment by tgamblin** [comment]
Ok given the lack of consensus, I'm proposing we move this to a more detailed discussion.  I started one here:

* https://github.com/spack/spack/discussions/41882

The gist of it is that I think *both* consumer workflows and dev/upgrade/iterative workflows are important, so we should have command that serve them both.  So I'm proposing to split some of this out to `spack upgrade`.

Please throw your thoughts over there.

**Comment by becker33** [comment]
@spackbot fix style

**Comment by becker33** [comment]
@tgamblin finally tracked down all the tests that relied on the old behavior and fixed them.

**Comment by tgamblin** [comment]
Based on the conflicting view here, I think we should wait to merge this for an upgrade command, so please weigh in on the discussion.  It seems like we're pretty close to a consensus over there -- there is a debate about how aggressive `upgrade` should be.

https://github.com/spack/spack/discussions/41882

**Comment by haampie** [comment]
I changed my mind about this after #43190.

Build caches are much more useful, and the experience is more `apt-get install ...` like. But only if roots are reused.

I would say let's change this default for 0.22

**Comment by alalazo** [comment]
With `libc` merged in #43190, and other improvements that make it possible to install specs without having their compiler configured locally, it makes more sense to have `--reuse` as a default. This would allow, for instance:
```console
$ spack install gcc
```
to work without a compiler currently configured, if a binary is in a registered buildcache.

**Review by haampie — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Since the consensus changed, I'm going to merge this one. Checked with @michaelkuhn in DM

**Pull request merged**
