### PR TITLE
draco: add v7.15.0, v7.16.0

### PR DESCRIPTION
**Pull request by clevelam**
+ Add draco-7_15_0 release
+ Add draco-7_16_0 release
+ Update some minor syntax for GPU compiler flags
+ Update package.py formating

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the two version sha256. 

The style checker doesn't like use of single quotes so those will have to be fixed for lines 117-120, 122-123, and 129.  And the prior indentation will need to be restored.

**Comment by tldahlgren** [comment]
> Confirmed the two version sha256.
> 
> The style checker doesn't like use of single quotes so those will have to be fixed for lines 117-120, 122-123, and 129. And the prior indentation will need to be restored.

The easiest way to fix this is to add a comment (sans quotes): "@spackbot fix style".

**Comment by tldahlgren** [comment]
Oops.  I was hoping the style checker wouldn't run if I quoted it.  I guess I was wrong.

**Comment by tldahlgren** [comment]
> Oops. I was hoping the style checker wouldn't run if I quoted it. I guess I was wrong.

Doesn't matter.  It can't push the fixes unless you run it.

**Comment by alalazo** [comment]
Superseded by #47032

**Pull request closed without merging**
