### PR TITLE
celeritas: update checksum for git describe difference

### PR DESCRIPTION
**Pull request by sethrj**
Using `$Format:%h$` and the export-subst gitattribute property mean that
the release checksum can change post release. I verified this by diffing fresh spack stage directories for the original (spack-cached) version and a freshly downloaded version.

```
$ diff -ru spack-stage-celeritas-0.1.0-hv7ewpjouekqws2y5iaql2cnp6tn76iz/ spack-stage-celeritas-0.1.0.wtf-ynyck3df2a7kkgkqrpwapgz3l2i62omz/
diff -ru spack-stage-celeritas-0.1.0-hv7ewpjouekqws2y5iaql2cnp6tn76iz/spack-src/cmake/CgvFindVersion.cmake spack-stage-celeritas-0.1.0.wtf-ynyck3df2a7kkgkqrpwapgz3l2i62omz/spack-src/cmake/CgvFindVersion.cmake
--- spack-stage-celeritas-0.1.0-hv7ewpjouekqws2y5iaql2cnp6tn76iz/spack-src/cmake/CgvFindVersion.cmake	2022-07-31 19:45:03.000000000 -0400
+++ spack-stage-celeritas-0.1.0.wtf-ynyck3df2a7kkgkqrpwapgz3l2i62omz/spack-src/cmake/CgvFindVersion.cmake	2022-07-31 19:45:03.000000000 -0400
@@ -75,7 +75,7 @@

   # Get a possible Git version generated using git-archive (see the
   # .gitattributes file)
-  set(_ARCHIVE_TAG "HEAD -> master, tag: v0.1.0")
+  set(_ARCHIVE_TAG "tag: v0.1.0")
   set(_ARCHIVE_HASH "04fe945d9")

   set(_TAG_REGEX "v([0-9.]+)(-dev[0-9.]+)?")
Binary files spack-stage-celeritas-0.1.0-hv7ewpjouekqws2y5iaql2cnp6tn76iz/v0.1.0.tar.gz and spack-stage-celeritas-0.1.0.wtf-ynyck3df2a7kkgkqrpwapgz3l2i62omz/v0.1.0.tar.gz differ
```

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the new sha256.

Under the circumstances, would it be better to use `tag="v0.1.0"` instead of the checksum?  Otherwise, perhaps it's worth adding a comment about the checksum changing.

**Comment by sethrj** [comment]
@tldahlgren when I posted something about this issue on Slack, @tgamblin said he uploads an artifact of the source tar.gz so it's consistent over time. That's what I've done, and I've updated the URL to match. The hash didn't change in the last patch because it's a copy of the same .tar.gz file, just a different URL.

**Review by tldahlgren — APPROVED** [review]
Confirmed sha25 unchanged by URL change.

**Comment by sethrj** [comment]
Closed and reopened and updated to try to get around the doc failure issues...

**Pull request merged**
