### PR TITLE
petsc, py-petsc4py: add 3.17.1

### PR DESCRIPTION
**Pull request by balay**

### CODE REVIEW

**Review by eugeneswalker — APPROVED** [review]
Checksums verified. Thanks!

**Review by tldahlgren — APPROVED** [review]
Confirmed both new sha256.

**Comment by tldahlgren** [comment]
@balay @alalazo  Oops.  I just see you requested a review from alalazo .  Let me know if I should revert/restore.

**Comment by balay** [comment]
Any one additional review/approval was good enough. Thanks for merging!

**Pull request merged**
