### PR TITLE
Add CUDA 12.0

### PR DESCRIPTION
**Pull request by wyphan**
SHA256 sums from @fspiga

### CODE REVIEW

**Comment by wyphan** [comment]
@ax3l @Rombur does `lib/spack/spack/build_systems/cuda.py` need to be updated too?

**Comment by wyphan** [comment]
@spackbot fix style

**Review by alalazo — DISMISSED** [review]

**Review by haampie — DISMISSED** [review]

**Comment by haampie** [comment]
I've added the conflicts (clang 15+ still not supported, gcc supported up to 12)

**Review by haampie — DISMISSED** [review]

**Comment by haampie** [comment]
@ulrikeyang @osborn9 @balay i've added an upperbound on cuda for hypre

**Comment by balay** [comment]
@haampie - many pkgs fail to build  with cuda-12 [from what I tried  - petsc, hypre, kokkos, magma, amgx]

Perhaps its beter to set 11.8 as default?

**Comment by wyphan** [comment]
@balay I think Spack automatically picks the newest version, as no version has been marked as the preferred version in the `cuda` recipe.

**Comment by balay** [comment]
> @balay I think Spack automatically picks the newest version, as no version has been marked as the preferred version in the cuda recipe.

Yeah - and I was suggesting - perhaps  version '11.8' should now be marked as 'preferred'.

But I don't know how one would do this in cuda/package.py - where the version()  is indirectly called here.. [and preferred=True is usually set via version()]

**Review by balay — APPROVED** [review]

**Comment by haampie** [comment]
If those packages are failing they should set an upperbound. Setting a preferred=... either delays the problem or we end up with new versions of those packages with support for newer cuda, and are simply missing upperbounds on older versions cause they were never built. Both are equally bad.

**Pull request merged**
