### PR TITLE
apptainer: new versions 1.1.6, 1.1.7

### PR DESCRIPTION
**Pull request by wdconinc**
No changes to build system required. https://github.com/apptainer/apptainer/compare/v1.1.5...v1.1.7

Release notes:
- https://github.com/apptainer/apptainer/releases/tag/v1.1.7
- https://github.com/apptainer/apptainer/releases/tag/v1.1.6

### CODE REVIEW

**Comment by wdconinc** [comment]
Security question: Do we have a policy to mark versions affected by CVEs as deprecated?

**Comment by wdconinc** [comment]
Builds without issues on my system:
```console
==> Installing apptainer-1.1.7-gbu76ngpmmg3mqxrqy2jt7y4xutdhhkp
==> No binary for apptainer-1.1.7-gbu76ngpmmg3mqxrqy2jt7y4xutdhhkp found: installing from source
==> Fetching https://github.com/apptainer/apptainer/releases/download/v1.1.7/apptainer-1.1.7.tar.gz
==> No patches needed for apptainer
==> apptainer: Executing phase: 'edit'
==> apptainer: Executing phase: 'build'
==> apptainer: Executing phase: 'install'
==> apptainer: Successfully installed apptainer-1.1.7-gbu76ngpmmg3mqxrqy2jt7y4xutdhhkp
  Stage: 3.80s.  Edit: 1.54s.  Build: 1m 45.60s.  Install: 2.19s.  Total: 1m 53.23s
[+] /opt/software/linux-ubuntu23.04-skylake/gcc-12.2.0/apptainer-1.1.7-gbu76ngpmmg3mqxrqy2jt7y4xutdhhkp
```

**Comment by alecbcs** [comment]
> Security question: Do we have a policy to mark versions affected by CVEs as deprecated?

There isn't an official policy as of yet. So far it's mostly been up to the maintainers to deprecate versions as they see fit. I generally recommend deprecating a package version when there's a known CVE with a high or critical threat level.

**Comment by wdconinc** [comment]
>with a high or critical threat level

Ok, then I'll leave this as is. 1.1.5 and before are affected by a moderate CVE.

**Review by alecbcs — APPROVED** [review]
Gotcha. In that case these additions look good to me!

**Pull request merged**
