### PR TITLE
openrasmol: new package

### PR DESCRIPTION
**Pull request by ketsubouchi**
- rasmol_help.patch
Full path of "rasmol.hlp" is stored in  `HelpFileBuf`
The full path is very long in Spack and causes SIGSEGV

- rasmol_noqa.patch
`rasmol_install.sh` confirms install. This patch skip confirmation.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
FWIW. Confirmed the version of the package is available on the download site.

**Comment by ketsubouchi** [comment]
`IMakefile` of openrasmol has option to "download and build dependent modules".

    depends_on('cbflib@0.9.2', type='link')
    depends_on('cqrlib@1.1.2', type='link')
    depends_on('cvector@1.0.3', type='link')
    depends_on('neartree@3.1', type='link')
    depends_on('xforms@1.0.91', type='link')

These module and versions are specified in the `IMakefile`.
So these version are available and needed by openrasmol.

**Comment by ketsubouchi** [comment]
What should I do to merge this PR?

**Comment by tldahlgren** [comment]
> What should I do to merge this PR?

You have the dependencies as 'link' but should they be ('build', 'link') dependencies?

**Comment by ketsubouchi** [comment]
I updated test function. (From discussion in https://github.com/spack/spack/pull/21667 )

> You have the dependencies as 'link' but should they be ('build', 'link') dependencies?

In our environment(x86 VM, Fujitsu a64fx), 'link' only dependencies worked well.
And build script does not execute dependency programs.
So 'link' only seems enough.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
