### PR TITLE
Add Ascent version requirements for Conduit

### PR DESCRIPTION
**Pull request by adrienbernede**
Ascent version 0.6+ requires conduit version 0.6+.

@cyrush could you please confirm?

### CODE REVIEW

**Comment by cyrush** [comment]
@adrienbernede I believe so, however I am trying to get away from historical explosion of variant forwarding. 

Did you have a case when conduit 0.5.1 was built instead of the newer versions (0.6.0 --> 0.7.1) ?

**Comment by cyrush** [comment]
Also, we are releasing Ascent 0.7.0 right now, so I will be updating the spack packages very soon.

**Comment by adrienbernede** [comment]
I had such a case because I had conduit@0.5.1 enforced somewhere, and it is basically failing with the develop axom, and with 0.6.0 too. So basically, conduit@0.5.1 cannot be built anymore if axom is also in the spec.

I agree that in the vast majority of cases, we would expect axom to determine conduit version, right? But the situation I describe seem pathological because one need to compile those to find the compatibility issue.

Finally, it is true that the syntax to express those (in)compatibilities is quite verbose, but there must be some way to make it acceptable. For example I could instead have said that axom is not compatible (conflicts) with conduit 5.1.0 and older.

**Comment by cyrush** [comment]
I understand -- but our plan is to try to reduce variant forwarding in packages files b/c its not sustainable. 

The hope is we can provide `packages.yaml` files, constrain with the spec on the command line, or use environments to show folks the proper version constraints, vs having them directly in the `package.py` where that over constrains us.

This is a big change from how I have tried to attack this by being super explicit in the, `package.py` as a means to try to make sure things will install out of the box, but as things grow its been really hard to keep everything bottled up.

Since its been a bit since I tried, is there now a way in spack to just do :

depends_on("conduit@0.6:",when="@0.6:") and not touch all the other options?

That would be fine.

Otherwise, we have to forward the variants for every version we want to support.  Honesty that's a key reason why we have only tended to supported one version of ascent in spack. Also, while I think develop is special, I get confused as to how statements like  "@0.6:" apply to develop. You may need to add `,develop` to avoid breaking the current forwarding. 

What about setting a conflict? That doesn't change the variants but still encodes the info.

Is there a way to do: 

conflicts("conduit@:0.6.0',when="@0.6.0:")

or something?

(honestly not sure if that will tangle the concertizer) 


> I agree that in the vast majority of cases, we would expect axom to determine conduit version, right? But the situation I describe seem pathological because one need to compile those to find the compatibility issue.

For now -- in the majority of the spack installed cases that ascent will support - I don't think axom is installed.

**Comment by adrienbernede** [comment]
Oops, confusion between Axom and Ascent...

**Comment by alalazo** [comment]
I think this has been superseded by #25551 and #28102, but feel free to reopen if I'm wrong.

**Comment by cyrush** [comment]
@alalazo  -- I agree, I think we are good now.

**Pull request closed without merging**
