### PR TITLE
gmsh: add v4.12.0

### PR DESCRIPTION
**Pull request by bfovet**
https://gitlab.onelab.info/gmsh/gmsh/-/releases/gmsh_4_12_0

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Unfortunately the package doesn't build in CI stack(s) (e.g., see https://gitlab.spack.io/spack/spack/-/jobs/9668385).

**Comment by bfovet** [comment]
This happens because gmsh in the e4s stack is built with `oce` instead of `opencascade`, which is actually maintained. There are at least a couple of headers missing in `GModelIO_OCC.cpp` but even when adding those, there is still an error:
`gmsh-4.12.0-source/src/geo/GModelIO_OCC.cpp:4305:52: error: « class Handle_StepData_StepModel » n'a pas de membre nommé « get »
   Handle_StepData_StepModel model = writer.Model().get();
` i.e. the class `Handle_StepData_StepModel` has no member function `get`.

I suspect [#41320](https://github.com/spack/spack/pull/41320) hits the same problem.

All versions build fine with `opencascade`. So, as long as gmsh is built with the `oce` dependency instead of `opencascade` in the e4s stack, we can't update gmsh recipe versions.

**Comment by bernhardkaindl** [comment]
@bfovet Maybe could you get in touch with them for changing the e4s stack to make the change?

**Comment by alalazo** [comment]
> So, as long as gmsh is built with the oce dependency instead of opencascade in the e4s stack, we can't update gmsh recipe versions.

If `oce` is not supported, can you add more constraints to `gmsh` so that the failing configuration is not allowed on recent versions?

**Comment by bfovet** [comment]
> > So, as long as gmsh is built with the oce dependency instead of opencascade in the e4s stack, we can't update gmsh recipe versions.
> 
> If `oce` is not supported, can you add more constraints to `gmsh` so that the failing configuration is not allowed on recent versions?

Yes I guess I could do that.

**Review by bernhardkaindl — APPROVED** [review]
Looks fine to me.

Because I have no competency for gmsh/oce,
I like to give others some more chance to review it.

If another maintainer, alalazo or someone else more knowledgeable or more near to the topic does not comment or merge within the next week, please ping tldahlgren or me to merge it.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
