### PR TITLE
py-torchvision: fix build with Apple Clang 16

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
May not be necessary if we can get #46536 working

**Comment by adamjstewart** [comment]
We could not get #46536 working for PyTorch, this is still necessary.

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
