### PR TITLE
git: 2.37.0

### PR DESCRIPTION
**Pull request by haampie**
almost but not entirely dropping perl...

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Deferring merge until maintainer has a chance to comment.

**Comment by jennfshr** [comment]
LGTM!

Thanks, @tldahlgren for the heads up... I need to determine how to get notified of the initial PR for git pull requests, so you don't need to run interference for me.  Guidance is welcomed!

**Review by jennfshr — COMMENTED** [review]
This all looks good.

**Comment by tldahlgren** [comment]
> LGTM!
> 
> Thanks, @tldahlgren for the heads up... I need to determine how to get notified of the initial PR for git pull requests, so you don't need to run interference for me. Guidance is welcomed!

No worries.  I often don't know who has write permissions and or I get on a roll.  If the submitter isn't a maintainer, then I (now) defer the merge decision to the maintainer since I have had complaints if I don't. 🤷‍♀️

**Pull request merged**
