### PR TITLE
e4s oneapi: use oneapi@2023.0.0

### PR DESCRIPTION
**Pull request by eugeneswalker**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Looks like the OneAPI E4S stack is having some failures: https://gitlab.spack.io/spack/spack/-/pipelines/252476/failures

**Comment by eugeneswalker** [comment]
> Looks like the OneAPI E4S stack is having some failures: https://gitlab.spack.io/spack/spack/-/pipelines/252476/failures

Yes, will investigate and update here, as needed. Thank you.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
All CI relating to this PR is GREEN! The only failure in GitLab is unrelated to the content of this PR:
* [aws-ahug-aarch64-pr-generate](https://gitlab.spack.io/spack/spack/-/jobs/5294304)
* Specs known to be broken on develop...

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by wspear — APPROVED** [review]

**Pull request merged**
