### PR TITLE
C-Blosc2: 2.15.1

### PR DESCRIPTION
**Pull request by ax3l**
Add the latest c-blosc2 release.

Related to #45253

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by ax3l** [comment]
Thanks @alalazo!

Can we include this in `0.22.2`? :pray:

**Comment by ax3l** [comment]
@haampie @alalazo just checking, did we ship this in v0.22.2? :pray: 

The bugs in older c-blosc2 releases break my CI in https://github.com/openPMD/openPMD-api/pull/1597

**Comment by ax3l** [comment]
It looks like @haampie removed my backport fix from the `v0.22.2` MS :sweat_smile: oh nooo :sweat_smile:

**Comment by haampie** [comment]
It will be part of 0.23.0 which will be released along with 0.22.3

**Pull request merged**
