### PR TITLE
boost: call_once_variadic.patch is already part of 1.56.0

### LINKED ISSUE #5692: boost@1.56.0^gcc@5.4.0 complains about reversed patch.
When I build boost@1.56.0 with gcc@5.4.0 I get a complaint about the call_once_variadic patch already having been applied and etc....

#5691 fixes it by changing the patch's constraint from `:1.56.0` to `:1.55.0`, but I do not know if that is actually appropriate.

### PR DESCRIPTION
**Pull request by junghans**
Fix #5692

### CODE REVIEW

**Comment by aprokop** [comment]
A lot more work is needed, see #5325.

**Comment by junghans** [comment]
@aprokop feel free to add to the PR.

**Comment by scheibelp** [comment]
It looks like what @aprokop is saying is that `boost_10125.patch` and `call_once_variadic.patch` are the same, so you can remove `call_once_variadic` although it would be great to update the declaration for `boost_10125.patch` like

`patch('boost_10125.patch', when='@1.55.0:1.55.999%gcc@5.0:5.9')`

https://github.com/LLNL/spack/issues/5325#issuecomment-328298419 also highlights another boost bug but this doesn't necessarily need to address that (although the comment also suggests the fix which appears good).

**Comment by aprokop** [comment]
@scheibelp is exactly right. Get rid of one of the patches, and fix the `when=` for the remaining one. Otherwise, somebody would still hit the `patch does not apply` problem.

**Comment by scheibelp** [comment]
@junghans: do you have any interest in dealing with https://github.com/LLNL/spack/pull/5341#issuecomment-329934008? I could take a crack at it myself.

**Comment by junghans** [comment]
@scheibelp: Please go ahead, I didn't had time to think about this yet.

**Pull request merged**
