### PR TITLE
Fix infinite recursion in swig build

### LINKED ISSUE #3000: swig 3.0.11 failed to build while taking 40Gb of space
subj. 

```
==> Installing swig
==> pcre is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/pcre-8.39-nhyefptcom4ey5zjjnyot7no7f6gx67z
==> Fetching http://prdownloads.sourceforge.net/swig/swig-3.0.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/davydden/spack/var/spack/stage/swig-3.0.11-iynexulzro2dthcxcsuum3fscpjucvi5/swig-3.0.11.tar.gz
==> Created stage in /Users/davydden/spack/var/spack/stage/swig-3.0.11-iynexulzro2dthcxcsuum3fscpjucvi5
==> Ran patch() for swig
==> Building swig [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
Process logger_daemon:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davydden/spack/lib/spack/llnl/util/tty/log.py", line 199, in _spawn_writing_daemon
    log_file.flush()
IOError: [Errno 28] No space left on device
```

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #3000. This is an alternate solution to #3248.

Ping @eschnett @davydden @alalazo @jppelteret

### CODE REVIEW

**Comment by davydden** [comment]
if that works, this is a much cleaner approach.  @eschnett @jppelteret could you please check if it fixes the issue for you?

**Comment by eschnett** [comment]
I confirm that this works.

**Comment by jppelteret** [comment]
> I confirm that this works.

Ditto. Can/should this be a default setting for `AutotoolsPackage`s?

**Comment by alalazo** [comment]
@jppelteret 

> Can/should this be a default setting for AutotoolsPackages

In principle I would agree, but based on my experience I think that doing so will break a lot of packages. Many times `configure.ac` & friends are written assuming in source build and won't compile if configured / built out of source.

**Comment by jppelteret** [comment]
Ok, thanks! In that case, perhaps a note in the documentation would be helpful in case we hit this issue again?

**Pull request merged**
