### PR TITLE
eckit: update versions

### PR DESCRIPTION
**Pull request by dominichofer**
Updates versions and SHAs of eckit.

### CODE REVIEW

**Comment by skosukhin** [comment]
This removes version `1.16.0` without a deprecation period. Is there a reason to even deprecate it? I'm also not sure about `YYYY.MM.X` versions. I have no idea what they mean. For example, [`2021.12.0`](https://github.com/ecmwf/eckit/releases/tag/2021.12.0) is annotated with `1.18.2` but there is a separate tag [`1.18.2`](https://github.com/ecmwf/eckit/releases/tag/1.18.2). Until we figure it out, I suggest we use only `1.XX.Y` versions.

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you take care of @skosukhin review?

**Comment by bernhardkaindl** [comment]
@skosukhin, [alalazo](https://github.com/alalazo) wrote:
> Can you take care of @skosukhin review?

Would you approve (this needs to be merged before #33289) and notify alalazo to approve as well then?

**Comment by bernhardkaindl** [comment]
@skosukhin ping?

**Comment by skosukhin** [comment]
@bernhardkaindl my https://github.com/spack/spack/pull/33200#issuecomment-1274668677 is not addressed yet.

**Comment by bernhardkaindl** [comment]
@PanicSheep: I looked up the linked PR which prompted you to add the new versions and only add the 0.16.3 and 1.20.2:

I'd propose that unless you'd need all those versions have a checksum: When asked, spack can build any of these versions even without a checksum.

Specially we should not add the 2021.x.x versions because they take precedence over newer versions such as 1.20.2.

@PanicSheep Because you didn't respond you [skosukhin](https://github.com/skosukhin) (the maintainer)'s change request so far I hope it's ok if we merge this soon even if you didn't respond, because none of these versions appear to be needed by the PR which prompted this PR.

**Comment by bernhardkaindl** [comment]
[skosukhin](https://github.com/skosukhin) reviewed:
> This removes version `1.16.0` without a deprecation period. Is there a reason to even deprecate it? I'm also not sure about `YYYY.MM.X` versions. I have no idea what they mean. For example, [`2021.12.0`](https://github.com/ecmwf/eckit/releases/tag/2021.12.0) is annotated with `1.18.2` but there is a separate tag [`1.18.2`](https://github.com/ecmwf/eckit/releases/tag/1.18.2). Until we figure it out, I suggest we use only `1.XX.Y` versions.

Thanks, I've addressed your review and removed the 2021.x.x versions because they took precedence over 1.20.2 and I'd also skip the other intermediate versions, maybe except for 1.16.3 but otherwise as @PanicSheep noted in the linked PR that they appear compatible, I'd my commit just leaves 1.16.3 and 1.20.2 to be added.

**Comment by skosukhin** [comment]
LGTM

**Comment by bernhardkaindl** [comment]
@alalazo: skosukhin sent a "LGTM" now, can you select that your requested changes were adressed? Thanks!

**Review by alalazo — APPROVED** [review]

**Pull request merged**
