### PR TITLE
[WIP] Make `insecure` option work with curl AND git.

### LINKED ISSUE #1779: Cannot access git repo (SSL problem) -- option "-k" not working?
I cannot access the Julia Github repo with Spack. Even with the `-k` option there is an error:
```
$ spack -k install cactusext +funhpc +julia +simulationio %gcc@6.2.0-spack
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Installing cactusext
==> hwloc is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/hwloc-1.11.3-jziezilob6sn62lo4z5nr6lvfazkhqcv
==> git is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/git-2.9.3-bqbazmbhqyissgywj6uqo3dwr73myb7n
==> papi is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/papi-5.4.3-x74i62f42477nwp7qodthulcrldcgi4s
==> hdf5-blosc is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/hdf5-blosc-master-xy4bgc6e3zjfx4dhky4znvhz4ibihox5
==> lmod is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/lmod-6.4.5-csvkg2zq2apsva676aii2wawh7722ouh
==> hdf5 is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/hdf5-1.10.0-patch1-4u7h4j767zqtafpry7jfybpfpiujs27s
==> python is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.12-gnfxact332zur4u3iyhfbmezqcfydnqn
==> lua is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/lua-5.3.2-6s4yhhtfq2udz3kycnq2tigyli3bszak
==> fftw is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/fftw-3.3.5-5qk7yvlcwqj5ghfsghdva6rkv3zazoch
==> openssl is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/openssl-1.0.2h-oenxals2xeigns2quaekrmk4sbeexf76
==> Installing julia
==> git is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/git-2.9.3-bqbazmbhqyissgywj6uqo3dwr73myb7n
==> cmake is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/cmake-3.6.1-deo6vqjasyxs7f4h2fkucyls7ae4vnre
==> hdf5 is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/hdf5-1.10.0-patch1-4u7h4j767zqtafpry7jfybpfpiujs27s
==> python is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/python-2.7.12-gnfxact332zur4u3iyhfbmezqcfydnqn
==> openssl is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/openssl-1.0.2h-oenxals2xeigns2quaekrmk4sbeexf76
==> m4 is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/m4-1.4.17-jdrcx3wss47p7bek26tiamn246w36f2i
==> openmpi is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/openmpi-2.0.0-agko567o3x3ooop2zrg2e2vgmypbcls6
==> curl is already installed in /Users/eschnett/src/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0-spack/curl-7.50.1-m5z7w3s3phi3antwbtbzfchotbbfptyx
==> Trying to fetch from file:///Users/eschnett/src/spack/var/spack/cache/julia/julia-master.tar.gz
curl: (37) Couldn't open file /Users/eschnett/src/spack/var/spack/cache/julia/julia-master.tar.gz
==> Fetching from file:///Users/eschnett/src/spack/var/spack/cache/julia/julia-master.tar.gz failed.
==> Trying to clone git repository:
  https://github.com/JuliaLang/julia.git
  on branch master
Cloning into 'julia'...
fatal: unable to access 'https://github.com/JuliaLang/julia.git/': SSL certificate problem: unable to get local issuer certificate
Cloning into 'julia'...
fatal: unable to access 'https://github.com/JuliaLang/julia.git/': SSL certificate problem: unable to get local issuer certificate
==> Fetching from [git] https://github.com/JuliaLang/julia.git failed.
==> Error: All fetchers failed for julia-master-q2sehvsw7l745zu4r43t7l4aq6gl7lmd
==> Error: Installation process had nonzero exit code : 256
```

It seems that the Spack option `-k` is not working?

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #1779. 

@eschnett: I haven't tested this extensively yet but feel free to try it out.  This makes `-k` work with `git`.

### CODE REVIEW

**Comment by citibeth** [comment]
I think this is a low-value project to work on.  The `insecure` option is dangerous because it turns off all security indiscriminately.  Also, @eschnett found a workaround.

**Comment by eschnett** [comment]
That work-around switches all `git` operations on my system into insecure mode. (And thanks for reminding me, I actually forgot to undo that setting.) A one-time `-k` option in Spack would have been much more local, and much preferred.

**Comment by tgamblin** [comment]
@eschnett: so does this work for you?

**Comment by tgamblin** [comment]
@eschnett: ping -- did you test this?

**Pull request merged**
