### PR TITLE
Fix intel-oneapi-compilers-classic bin path

### PR DESCRIPTION
**Pull request by OfirGan**

### CODE REVIEW

**Comment by rscohn2** [comment]
Thanks! Apparently I did not do any testing for this.

**Review by rscohn2 — APPROVED** [review]

**Comment by rscohn2** [comment]
@OfirGan: thanks for the change. I fixed the style issues in #32305, so closing this one. If you do:
```
spack style
```
It will run the checks locally so it is quicker to fix problems.

**Comment by OfirGan** [comment]
there is another problem white the "MODULEPATH",
as for version 2022.1.0 the compiler version is "intel\2021.6.0" so when you load the module it doesn't automatically use the 
the correct path to the compiler modules.
i dont know how to fix it

**Comment by rscohn2** [comment]
I think https://github.com/spack/spack/pull/31285 will fix it.

**Pull request closed without merging**
