### PR TITLE
AMReX: SYCL support

### PR DESCRIPTION
**Pull request by etpalmer63**
I am working on enabling the AMReX install with SYCL Intel GPU support via Spack. On the same machine, I load some module files and can manually install and run AMReX with Intel GPUs. When I try to install with Spack, I ran into a few errors. I found that adding the lines,
```
            args.append('-DSYCL_INCLUDE_DIR=/oneapi/compiler/linux/include')
            args.append('-DSYCL_LIBRARY_DIR=/oneapi/compiler/linux/lib')
            args.append('-DCMAKE_CXX_FLAGS=-I/oneapi/mkl/include')
```
allows for successful install and run tests. (The paths listed here are not exact, just for example.)  

Any ideas on how I should go about attacking this issue? Are these details that should be left to the compiler configuration? Or should I be trying to do something more in the build section in `package.py`? Maybe depending on some other intel packages? Any suggestions are appreciated! 

Thank you!
Erik

### CODE REVIEW

**Comment by etpalmer63** [comment]
I was able to configure the intel compiler to make this work without adding any custom commands to the CMake build.

**Comment by etpalmer63** [comment]
Tested and running. Also, compiles on a machine without intel GPUs.

**Review by WeiqunZhang — DISMISSED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
Can you fix the conflicts (they are very likely due to style issues, after we blackened the entire codebase)? Otherwise this LGTM

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by alalazo** [comment]
@spackbot fix style

**Review by alalazo — APPROVED** [review]

**Pull request merged**
