### PR TITLE
Update cmake dep for tau

### PR DESCRIPTION
**Pull request by alexrichert**
This PR adds cmake as a dependency for tau%aocc (build fails if cmake not in $PATH).

### CODE REVIEW

**Comment by wspear** [comment]
@alexrichert Do you have a spec that works for you with tau%aocc (with this change)? It fails to build for me in spack, I believe because spack is being stingy with compiler access in its build environment.

```
     721    gcc -c -fPIC  -O2 -g -Wl,-rpath,/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu22.04-westmere/aocc-4.2.0/tau-2.33.2-lwjf33up7pg32fqhsbzesn3fq3ivuvp5/lib -Wl,-rpath,/home/wspear/bin/SP
            ACK/spack/opt/spack/linux-ubuntu22.04-westmere/aocc-4.2.0/tau-2.33.2-lwjf33up7pg32fqhsbzesn3fq3ivuvp5/lib64 -Wl,-rpath,/usr/lib -Wl,-rpath,/home/wspear/bin/SPACK/spack/opt/spack/linux-ubu
            ntu22.04-westmere/gcc-11.4.0/hwloc-2.9.1-d7hdo2dmnfmtjv2amyukdgr2dobrsv67/lib -Wl,-rpath,/home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu22.04-westmere/gcc-11.4.0/zlib-ng-2.1.6-7qe4vke
            pdiuhhp7n7wyk2fbtieit32gd/lib -Wl,-rpath,/usr/lib64 TauLinuxTimers.c
  >> 722    make[1]: gcc: Permission denied
  >> 723    make[1]: *** [Makefile:898: TauLinuxTimers.o] Error 127
```

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Do any other reviewers object to this change? Looks good to me.

**Comment by alexrichert** [comment]
@wspear what does `spack build-env tau -- bash -c "which gcc"` give you?
I'm installing:
```
-- linux-rocky9-zen4 / aocc@4.1.0 -------------------------------
tau@2.33.1~adios2+binutils~comm~craycnl~cuda~dyninst+elf+fortran~gasnet+io~level_zero+libdwarf+libunwind~likwid~mpi~ompt~opari~opencl~openmp+otf2+papi+pdt~phase~ppc64le~profileparam+pthreads~python~rocm~rocprofiler~roctracer~scorep~shmem~sqlite~syscall~x86_64 build_system=generic
```

**Comment by wspear** [comment]
There's something weird going on here. In the build-env gcc is /usr/bin/gcc which gives the correct version. When I try to build tau with aocc in the build-env I see the same error (it works fine outside the build-env), but when I run the gcc command directly in the build-env it works.  It's unrelated to this PR anyway so I think we're good to merge.

**Comment by alexrichert** [comment]
Sounds good, thanks. It's a bit of a long shot, but you might try renaming the 'gcc' directory associated with Spack's compilers and see if that makes the error go away. Some time ago with a different package I ran into a weird gmake bug where it was trying to execute that directory as an executable... :upside_down_face:

**Review by wspear — APPROVED** [review]

**Comment by wspear** [comment]
@alexrichert Good call! If I give tau a dependency on gmake it works. Must have been an issue with the system gmake. PR inbound.

**Comment by alexrichert** [comment]
Nice! Yeah basically in older versions of gmake, when it searches $PATH, it doesn't bother to distinguish between executables and directories...

**Pull request merged**
