### PR TITLE
py-scipy: link with OpenMP version of armpl-gcc when requested

### PR DESCRIPTION
**Pull request by annop-w**

### CODE REVIEW

**Comment by rgommers** [comment]
This seems reasonable. What are the actual `blas` and `lapack` strings that are being parsed here though?

**Comment by annop-w** [comment]
> This seems reasonable. What are the actual `blas` and `lapack` strings that are being parsed here though?

It's "armpl" or "armpl_mp", I think.

**Review by rgommers — APPROVED** [review]
Thanks, then this LGTM. 

In the future this will be more automatic, for now this can be merged as is I think, when CI comes back green.

For completeness, here are my notes on ArmPL:

Pkg-config file names for ArmPL to use (from https://github.com/spack/spack/pull/34979#discussion_r1073213319):

```
    armpl-dynamic-ilp64-omp             armpl-Fortran-static-ilp64-omp
    armpl-dynamic-ilp64-omp.pc          armpl-Fortran-static-ilp64-omp.pc
    armpl-dynamic-ilp64-seq             armpl-Fortran-static-ilp64-seq
    armpl-dynamic-ilp64-seq.pc          armpl-Fortran-static-ilp64-seq.pc
    armpl-dynamic-lp64-omp              armpl-Fortran-static-lp64-omp
    armpl-dynamic-lp64-omp.pc           armpl-Fortran-static-lp64-omp.pc
    armpl-dynamic-lp64-seq              armpl-Fortran-static-lp64-seq
    armpl-dynamic-lp64-seq.pc           armpl-Fortran-static-lp64-seq.pc
    armpl-Fortran-dynamic-ilp64-omp     armpl-static-ilp64-omp
    armpl-Fortran-dynamic-ilp64-omp.pc  armpl-static-ilp64-omp.pc
    armpl-Fortran-dynamic-ilp64-seq     armpl-static-ilp64-seq
    armpl-Fortran-dynamic-ilp64-seq.pc  armpl-static-ilp64-seq.pc
    armpl-Fortran-dynamic-lp64-omp      armpl-static-lp64-omp
    armpl-Fortran-dynamic-lp64-omp.pc   armpl-static-lp64-omp.pc
    armpl-Fortran-dynamic-lp64-seq      armpl-static-lp64-seq
    armpl-Fortran-dynamic-lp64-seq.pc   armpl-static-lp64-seq.pc
```
Note that as of Jan'23, ArmPL ships the files without a `.pc` extension (that
will hopefully be fixed), and Spack renames then so adds the `.pc` copies of
the original files.

**Comment by annop-w** [comment]
Thanks @rgommers . The package files naming are fixed in 23.04 release last month and the `pkgconfig` directory got moved into `lib`. Still, the package files are not found automatically and I need to set `PKG_CONFIG_PATH`. Hence, I put another patch here https://github.com/spack/spack/pull/37001

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
