### PR TITLE
Detect Apple M1 system when using Rosetta2 emulator

### LINKED ISSUE #30076: Apple M1 processor not detected correctly in Rosetta 2 emulator mode
### Summary

When using the Rosetta 2 emulator to work in a `x86_64` environment on an Apple M1 system, `spack` complains about not being able to detect the CPU:
```
...
==> Ran patch() for m4
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
==> m4: Executing phase: 'autoreconf'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
==> m4: Executing phase: 'configure'
...
```
This doesn't seem to hurt, but the messages are annoying.

### Rationale

`spack` should be able to detect an Apple M1 processor in Rosetta 2 emulator mode.

### Description

_No response_

### Additional information

```
> spack --version
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
0.18.0.dev0 (44f631d7161e0715ff121ffe3ba3368c2c5b130f)
```

```
> spack debug report
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
* **Spack:** 0.18.0.dev0 (44f631d7161e0715ff121ffe3ba3368c2c5b130f)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by climbfuji**
Fixes https://github.com/spack/spack/issues/30076. I have been using this for three months without problems.

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Not sure this is a general fix. It seems to say "if the brand string is Apple on x86_64 then it's M1"

**Comment by climbfuji** [comment]
> Not sure this is a general fix. It seems to say "if the brand string is Apple on x86_64 then it's M1"

I think one could change that if test to
```
if "Apple M1" in sysctl("-n", "machdep.cpu.brand_string"):
```
or
```
if "apple m1" in sysctl("-n", "machdep.cpu.brand_string").lower():
```
Note also that the existing logic in line 128 isn't any different, it basically says "If it's not x64_64 and the brand string is Apple then it's M1". Maybe that one should also be changed to
```
"m1" if "Apple M1" in sysctl("-n", "machdep.cpu.brand_string") else "unknown"
```

The whole point is to avoid querying non-existent parameters:
```
> sysctl -n machdep.cpu.brand_string
Apple M1 Pro
> sysctl -n machdep.cpu.features
FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTSE64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 AES SEGLIM64
> sysctl -n machdep.cpu.model
sysctl: unknown oid 'machdep.cpu.model'
> sysctl -n machdep.cpu.leaf7_features
sysctl: unknown oid 'machdep.cpu.leaf7_features'
> sysctl -n machdep.cpu.vendor
sysctl: unknown oid 'machdep.cpu.vendor'
```

**Comment by alalazo** [comment]
Can you please reopen both issue and PR in https://github.com/archspec/archspec ? We consider `archspec` a vendored dependency, so we'll fix it upstream and then port a new version here.

**Comment by climbfuji** [comment]
> Can you please reopen both issue and PR in https://github.com/archspec/archspec ? We consider `archspec` a vendored dependency, so we'll fix it upstream and then port a new version here.

Yes, will do - I wasn't aware that this code was coming from elsewhere. Thanks!

**Comment by climbfuji** [comment]
Replaced by https://github.com/archspec/archspec/pull/77.

**Pull request closed without merging**
