### PR TITLE
Blast plus

### PR DESCRIPTION
**Pull request by dorton21**

### CODE REVIEW

**Comment by alalazo** [comment]
Can you solve the conflict?

**Comment by hartzell** [comment]
Is it necessary to update the `url`?  I believe that adding the new version should be sufficient.

**Comment by adamjstewart** [comment]
It's not necessary to update the URL, but it also doesn't hurt.

**Comment by dorton21** [comment]
I don't understand the conflict. Would somebody point me in the right direction?

**Comment by adamjstewart** [comment]
The `blast-plus` package has been updated since your fork branched off. You'll need to merge or rebase develop into this branch.

**Comment by adamjstewart** [comment]
There are some duplicate versions now.

**Review by adamjstewart — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Comment by dorton21** [comment]
What's the hold up on merging this pull request?

**Pull request merged**
