### PR TITLE
e4s ci environment: packages: update to newer versions

### PR DESCRIPTION
**Pull request by eugeneswalker**
E4S CI Spack environment: update package preferences:
* `binutils` 2.33.1 -> **2.36.1**
* `boost` 1.75.0 -> **1.76.0**
* `cmake` 3.20.2 -> **3.20.3**
* `elfutils` 0.182 -> **0.185**
* `expat` 2.2.10 ->**2.3.0**
* `gdbm` 1.18.1 -> **1.19**

@scottwittenburg

### CODE REVIEW

**Comment by sethrj** [comment]
@eugeneswalker Out of curiosity, do `spack.lock`  files get generated and committed for any of the build platforms (such as the spack CI)? I ask because I encountered a "surprise" E4S  failure in https://github.com/spack/spack/pull/24290 and wanted to see  if I could just  grep through a lockfile to  see if any other packages might implicitly  depend on googletest.

**Review by sethrj — APPROVED** [review]

**Comment by scottwittenburg** [comment]
@sethrj When your PR experiences a failure on gitlab ci, you can navigate to the failed job and either browse or download artifacts that contain the `spack.lock` file corresponding to the concrete environment that contained the spec that failed.  Is that what you're looking for?

**Comment by sethrj** [comment]
> @sethrj When your PR experiences a failure on gitlab ci, you can navigate to the failed job and either browse or download artifacts that contain the `spack.lock` file corresponding to the concrete environment that contained the spec that failed. Is that what you're looking for?

Exactly! I also thought it might be interesting to have a lock file (on a standardized system) under version control to see how  `spack blame` or the like could detect how the concrete environment changes as a result of spack core updates or dependency changes.

**Comment by eugeneswalker** [comment]
The Gitlab pipeline was canceled, and I don't see a new one running. All the jobs were green when I looked... ??

@scottwittenburg

**Pull request merged**
