### PR TITLE
e4s ci: add raja +rocm

### PR DESCRIPTION
**Pull request by eugeneswalker**
Hoping the merge of https://github.com/spack/spack/pull/32469 has fixed issue with `raja +rocm` in our CI environment.

FYI @wspear @davidbeckingsale

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
`raja` is failing to build https://gitlab.spack.io/spack/spack/-/jobs/3188510

**Comment by eugeneswalker** [comment]
> `raja` is failing to build https://gitlab.spack.io/spack/spack/-/jobs/3188510

Issue is that `camp.hip_repair_option` method is not safe for CachedCMakePackage:
* https://github.com/spack/spack/pull/32504#issuecomment-1240978644

Will submit PR and once merged, rebase this on develop.

**Comment by eugeneswalker** [comment]
Replacing `camp.hip_repair_option` in `raja`'s package.py:
* https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/raja/package.py#L128

with:
```
import glob
entries.append(cmake_cache_path("HIP_CLANG_INCLUDE_PATH", glob.glob("{}/lib/clang/*/include".format(spec["llvm-amdgpu"].prefix))[0]))
```

... gets me past the CMake issue. 

But then there is this:
```
==> Installing raja-2022.03.0-qaar7rx6sm3ynowczhnpq7ocisbk46ah
==> No binary for raja-2022.03.0-qaar7rx6sm3ynowczhnpq7ocisbk46ah found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/git//LLNL/RAJA.git/v2022.03.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> raja: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'
...
  >> 124    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 125    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 126    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 127    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 128    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 129    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 130    g++: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-bv7urfoqfdriepvm6ytgd3wubhv4smbv'
  >> 131    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 132    make[2]: *** [CMakeFiles/RAJA.dir/build.make:79: CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o] Error 1
     133    make[2]: *** Waiting for unfinished jobs....
  >> 134    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 135    make[2]: *** [CMakeFiles/RAJA.dir/build.make:121: CMakeFiles/RAJA.dir/src/MemUtils_CUDA.cpp.o] Error 1
  >> 136    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 137    make[2]: *** [CMakeFiles/RAJA.dir/build.make:149: CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o] Error 1
  >> 138    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 139    make[2]: *** [CMakeFiles/RAJA.dir/build.make:93: CMakeFiles/RAJA.dir/src/DepGraphNode.cpp.o] Error 1
  >> 140    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 141    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 142    make[2]: *** [CMakeFiles/RAJA.dir/build.make:107: CMakeFiles/RAJA.dir/src/LockFreeIndexSetBuilders.cpp.o] Error 1
  >> 143    make[2]: *** [CMakeFiles/RAJA.dir/build.make:163: CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o] Error 1
  >> 144    g++: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 145    make[2]: *** [CMakeFiles/RAJA.dir/build.make:135: CMakeFiles/RAJA.dir/src/MemUtils_HIP.cpp.o] Error 1
     146    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-raja-2022.03.0-qaar7rx6sm3ynowczhnpq7ocisbk46ah/spack-build-qaar7rx'
  >> 147    make[1]: *** [CMakeFiles/Makefile2:273: CMakeFiles/RAJA.dir/all] Error 2
     148    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-raja-2022.03.0-qaar7rx6sm3ynowczhnpq7ocisbk46ah/spack-build-qaar7rx'
  >> 149    make: *** [Makefile:139: all] Error 2
```

**Comment by eugeneswalker** [comment]
This PR can move forward once https://github.com/spack/spack/issues/33249 is resolved.

**Review by wspear — DISMISSED** [review]

**Review by alalazo — DISMISSED** [review]

**Review by wspear — APPROVED** [review]

**Pull request merged**
