### PR TITLE
butterflypack: add in version 2.2.2 with openmp variant

### PR DESCRIPTION
**Pull request by balay**
- add conflcit with gcc < 7
- fails with MacOS sed - so add in (gnu) sed as build dependency

### CODE REVIEW

**Review by liuyangzhuan — DISMISSED** [review]

**Review by eugeneswalker — DISMISSED** [review]

**Comment by liuyangzhuan** [comment]
After this PR is merged, I will add sha256 for v2.2.2

**Comment by balay** [comment]
> After this PR is merged, I will add sha256 for v2.2.2

I think it makes sense to defer this PR after 2.2.2 is released [or 2.2.2 added to this PR - and update the PR to reflect 2.2.2 [instead of 2.2.1.]

Hence I marked this PR as draft

**Comment by liuyangzhuan** [comment]
@balay 
Can you add 
url = "https://github.com/liuyangzhuan/ButterflyPACK/archive/v2.2.2.tar.gz" 
and
version("2.2.2", sha256="73f67073e4291877f1eee19483a8a7b3c761eaf79a75805d52105ceedead85ea")
to this PR? 
Thank you!

**Comment by balay** [comment]
@liuyangzhuan thanks! I've updated the PR, and I think its ready for merge [after the CI is done]

**Review by eugeneswalker — APPROVED** [review]

**Comment by liuyangzhuan** [comment]
@pghysels there is a v2.2.2 available now.

**Comment by liuyangzhuan** [comment]
@balay Shall I update the xsdk sheet with v2.2.2?

**Comment by balay** [comment]
yes.

 I'll have to check on other pkgs aswell for such updates

**Pull request merged**
