### PR TITLE
gmake: fix, again

### PR DESCRIPTION
**Pull request by haampie**
build.sh is in the source dir in v4.3, it's only symlinked in the build dir from v4.4 it seems.

Introduced in https://github.com/spack/spack/pull/35224 which was trying to avoid a symlink of build.sh to itself, I guess

### CODE REVIEW

**Comment by haampie** [comment]
fyi @alecbcs

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
Superseded by #35872

**Pull request closed without merging**
