### PR TITLE
charmpp: add v8.0.0

### PR DESCRIPTION
**Pull request by RMeli**
Release not at the usual place: https://github.com/charmplusplus/charm/issues/3827

https://github.com/charmplusplus/charm/releases/tag/v8.0.0

### CODE REVIEW

**Comment by RMeli** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.  @matthiasdiener Are there any other changes needed besides adding the new version?

**Review by matthiasdiener — APPROVED** [review]
This looks good, thank you!

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
