### PR TITLE
Back-port a patch for filesystem logic in `gmx` executable.

### PR DESCRIPTION
**Pull request by eirrgang**
Reference: https://gitlab.com/gromacs/gromacs/-/issues/4724

### CODE REVIEW

**Comment by eirrgang** [comment]
Originally reported by @ggouaillardet, but the upstream fix is not yet released (targeted `gromacs@2023.1`). We should let `gromacs@2023` behave better.

**Comment by ggouaillardet** [comment]
I do not think the "relocatable" is appropriate in the context of this patch (it is more of a bug fix)


Anyway, you might also be interested in the last inlined patch from https://gitlab.com/gromacs/gromacs/-/issues/4728

TL;DR make it work with `libstdc++` from RHEL8

**Comment by eirrgang** [comment]
> I do not think the "relocatable" is appropriate in the context of this patch (it is more of a bug fix)

updated PR description

> Anyway, you might also be interested in the last inlined patch from https://gitlab.com/gromacs/gromacs/-/issues/4728

I think that's out of scope for this PR. That issue has not yet been resolved upstream.

**Comment by eirrgang** [comment]
Note: this update is needed also for https://github.com/spack/spack/pull/35738

**Review by junghans — APPROVED** [review]

**Pull request merged**
