### PR TITLE
t8code: new versions

### PR DESCRIPTION
**Pull request by melven**
Add recent t8code release, tested 2.0.0 with variants (except petsc).

### CODE REVIEW

**Comment by melven** [comment]
Ping @Davknapp

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256s.

**Comment by tldahlgren** [comment]
@Davknapp Any objections to merging this PR?

**Comment by tldahlgren** [comment]
Actually, since @melven is a maintainer I'm going to assume it's okay to merge.

**Pull request merged**
