### PR TITLE
python: make 3.12 the preferred version

### PR DESCRIPTION
**Pull request by haampie**
This PR is to detect issues with Python 3.12 in CI.

### CODE REVIEW

**Comment by haampie** [comment]
@adamjstewart so, this works, but also it doesn't really build a lot of stuff because many packages in e4s are stuck at python 3.8 for some reason.

**Comment by adamjstewart** [comment]
If you use:
```console
> spack pkg grep "pip silently replaces distutils with setuptools"
```
you'll find a ton of other packages that probably still try to import distutils. These are worth adding a Python version restriction to. The rest we'll have to catch in CI or when people open bug reports.

**Comment by haampie** [comment]
Will have a look after CI passes on develop. FWIW, `import setuptools` makes `import distutils` available (or hijacks it). Doesn't that mean it's not necessarily problematic?

**Comment by adamjstewart** [comment]
I'm honestly not sure. I also wouldn't be surprised if distutils was removed from setuptools. @pradyunsg would know more.

**Comment by haampie** [comment]
No the 3.12 migration guide says you can still use distutils from setuptools

**Comment by alalazo** [comment]
No need to use the release candidate anymore: https://www.python.org/downloads/release/python-3120/

**Comment by adamjstewart** [comment]
Should we close this since we decided to default to 3.11 for now?

**Comment by haampie** [comment]
No, let's keep it for CI. It still uncovers Python 3.12 compat issues now that meson isn't restricting Python to <= 3.11

**Pull request closed without merging**
