### PR TITLE
MKL linux fixes

### PR DESCRIPTION
**Pull request by davydden**
for now a workaround with MKL is to symlink all libs from `prefix.lib.intel64` to `prefix.lib`. Frankly, i have no idea why by default `prefix.lib` has the following folders:
```
ia32 # symlink to ./ia32_lin
ia32_lin
intel64 # symlink to ./intel64_lin
intel64_lin
intel64_lin_mic # similar to intel64_lin, but somehow fewer number of libs
```

p.s. this is WIP as I am running installation of `deal.II` with MKL and will add fixes if needed.

@lee218llnl ping.

### CODE REVIEW

**Comment by citibeth** [comment]
This is a kind of problem that's come up before: packages that have a "mini-Spack" embedded inside, trying to accommodate more than one architecture.  It never works out so well.

**Comment by davydden** [comment]
probably they stick to distributing libs both for `ia-32` and `intel64` architectures due to historical reasons.

**Comment by davydden** [comment]
`spack install dealii ^mkl@11.3.2.181` compiles fine.

**Comment by lee218llnl** [comment]
@davydden you may want to do something similar to what @glennpj did in #1205. In particular, within setup_environment:

+        if self.spec.satisfies('+all') or self.spec.satisfies('+mkl'):
+            run_env.prepend_path('LD_LIBRARY_PATH',
+                                 join_path(self.prefix, 'mkl', 'lib',
+                                           'intel64'))
+            run_env.prepend_path('LIBRARY_PATH',
+                                 join_path(self.prefix, 'mkl', 'lib',
+                                           'intel64'))
+            run_env.prepend_path('CPATH',
+                                 join_path(self.prefix, 'mkl', 'include'))
+            run_env.prepend_path('MIC_LD_LIBRARY_PATH',
+                                 join_path(self.prefix, 'mkl', 'lib', 'mic'))
+            run_env.set('MKLROOT', join_path(self.prefix, 'mkl'))

That said, I'm not opposed to your symlink solution, as that is what I have historically done when installing MKL at our site outside of Spack.

**Comment by davydden** [comment]
@lee218llnl thanks for the idea. For now i would prefer the current symlink solution as `(DY)LD_LIBRARY_PATH` won't work on OS-X and I very much like that Spack, in general, avoids setting `LD_LIBRARY_PATH`.

**Comment by glennpj** [comment]
The #1205 PR was about getting the environment module set up and so is unrelated to whether there is a symlink or not.

**Comment by citibeth** [comment]
Time to kill the ia-32 beast.  See:

http://www.networkworld.com/article/3091818/linux/linux-distros-look-to-drop-32-bit-support.html

What struck me the most was how they're having trouble even finding 32-bit
hardware to test 32-bit builds.  And in supercomputing land... are there
even any 32-bit supercomputers left?

**Pull request merged**
