### PR TITLE
MFEM: fix some issues with building with ROCm

### PR DESCRIPTION
**Pull request by v-dobrev**
This is a patch for mfem v4.5 that includes the fixes from https://github.com/mfem/mfem/pull/3317.

### CODE REVIEW

**Comment by balay** [comment]
https://gitlab.spack.io/spack/spack/-/jobs/4277448
```
==> Error: No binary for python-3.10.8-xnhyoiiwnllktmylbmznaodqk2kx7j4w found when cache-only specified
==> Error: Failed to install python due to SystemExit: 1
==> Error: python-3.10.8-xnhyoiiwnllktmylbmznaodqk2kx7j4w: Package was not installed
```
https://gitlab.spack.io/spack/spack/-/jobs/4277301
```
Duration: 360 minutes 1 second 
```
random CI errors?

cc: @scottwittenburg

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by scottwittenburg** [comment]
> random CI errors?

That looks like a problem that I fixed last week, but in this case was caused by a different problem.  Some binaries got generated unsigned yesterday due to problems that came up during maintenance.

@zackgalbreath `python-3.10.8-xnhyoi` looks like one that needs to be replaced.

**Comment by zackgalbreath** [comment]
> @zackgalbreath `python-3.10.8-xnhyoi` looks like one that needs to be replaced.

Thanks for the heads up. I just checked, and the unsigned `python-3.10.8-xnhyoi` package has already been removed & replaced in our binary mirror. It also looks like the latest GitLab CI pipeline passed for this PR!

**Review by balay — APPROVED** [review]
The basic xsdk tests I do are without rocm - they are unaffected by this PR

**Comment by balay** [comment]
Perhaps this PR is ready-for-merge?

**Review by tzanio — APPROVED** [review]

**Pull request merged**
