### PR TITLE
Clarify GROMACS relaxed double option

### PR DESCRIPTION
**Pull request by mabraham**
This is only intended for use on the Fujitsu PRIMEHPC platform (ie former K computer, not Fugaku)

### CODE REVIEW

**Comment by mabraham** [comment]
Do I need to merge spack:develop into my branch to keep the code coverage linter happy?

**Comment by haampie** [comment]
> Do I need to merge spack:develop into my branch to keep the code coverage linter happy?

No, there's an issue with the coverage action, it's not a required check, so should be fine.

Pinging @junghans @marvinbernhardt if they are fine with this variant rename

**Comment by marvinbernhardt** [comment]
I'm fine with it. Should be less confusing than current naming.

**Review by junghans — APPROVED** [review]

**Comment by karcaw** [comment]
I get this error when i build gromacs with spec: `gromacs+mpi %gcc@10.2.0 ^cmake@3.18.4%gcc`

```
==> Error: gromacs-2020.4-a2fhp45zfrbhln32um5iciw43qwxp2oq: KeyError: 'relaxed_double_precision'
```

Any Idea why?

**Comment by mabraham** [comment]
> I get this error when i build gromacs with spec: `gromacs+mpi %gcc@10.2.0 ^cmake@3.18.4%gcc`
> 
> ```
> ==> Error: gromacs-2020.4-a2fhp45zfrbhln32um5iciw43qwxp2oq: KeyError: 'relaxed_double_precision'
> ```
> 
> Any Idea why?

Not me. I introduced this key by renaming the old code, so if there's a syntax error somewhere, it was pre-existing. Yet nobody reported that, either...

**Comment by mabraham** [comment]
Any ideas @junghans?

**Comment by alalazo** [comment]
Is it mandatory to use this CMake directive with Fujitsu compilers?

**Comment by mabraham** [comment]
> Is it mandatory to use this CMake directive with Fujitsu compilers?

No: "This is only intended for use on the Fujitsu PRIMEHPC platform (ie former K computer, not Fugaku)"

**Comment by alalazo** [comment]
Thanks, I was wondering if we could get by using:
```python
if '%fj' in spec:
   # Add the option
```
instead of using a variant, but it seems this is even more specific - so probably a variant is well-suited at the moment.

**Comment by mabraham** [comment]
> I get this error when i build gromacs with spec: `gromacs+mpi %gcc@10.2.0 ^cmake@3.18.4%gcc`
> 
> ```
> ==> Error: gromacs-2020.4-a2fhp45zfrbhln32um5iciw43qwxp2oq: KeyError: 'relaxed_double_precision'
> ```
> 
> Any Idea why?

Are you trying to install GROMACS or something that uses it? Or somehow using an old recipe with new package?

**Comment by karcaw** [comment]
I had installed gromacs with that spec on spack 15.4, and was attempting to
upgrade spack the the latest development, and use the same spec and it
fails for the mpi and the single processor versions.

**Comment by mabraham** [comment]
> I had installed gromacs with that spec on spack 15.4, and was attempting to upgrade spack the the latest development, and use the same spec and it fails for the mpi and the single processor versions.

OK. I'm no spack expert, but it seems likely that something has persisted from that old install and uses the `double_precision` variant that no longer works with the develop version. If so, some kind of purge would fix it, but I don't know how to do that!

**Comment by karcaw** [comment]
Yes, it does seem to be leftover, I destroyed the environment .lock file and now it builds fine.

**Pull request merged**
