### PR TITLE
removing feature bloat: monitor and analyzers

### PR DESCRIPTION
**Pull request by vsoch**
We should try to optimize spack to work really well for 80% of use cases, and both of monitor/analyzers don't fall within that. Regardless of the work done they need to be removed! Since I added both of these I want to remove them too :)

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by alalazo** [comment]
@vsoch Would it be worth considering moving them to a separate repository, as a [Spack Python extension]( https://spack.readthedocs.io/en/latest/extensions.html)? Do you know if that can be done now, or if we need further features / hooks in Spack to be able to do that?

**Comment by vsoch** [comment]
Maybe if/when we need to add something like this again, that would be a better approach to take for next time!

**Comment by vsoch** [comment]
@tgamblin pleeeease review!

**Review by tgamblin — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
