### PR TITLE
CUDA: add  v11.6.0

### PR DESCRIPTION
**Pull request by csbnw**
Add CUDA Toolkit 11.6

### CODE REVIEW

**Review by Rombur — DISMISSED** [review]

**Comment by haampie** [comment]
You also have to update the conflicts in build_systems/cuda.py. Can you apply this patch? See https://github.com/spack/spack/pull/25054#issuecomment-885543526 for how this was generated.

```diff
diff --git a/lib/spack/spack/build_systems/cuda.py b/lib/spack/spack/build_systems/cuda.py
index ce622a363c..8200737d76 100644
--- a/lib/spack/spack/build_systems/cuda.py
+++ b/lib/spack/spack/build_systems/cuda.py
@@ -105,10 +105,9 @@ def cuda_flags(arch_list):
     # This implies that the last one in the list has to be updated at
     # each release of a new cuda minor version.
     conflicts('%gcc@10:', when='+cuda ^cuda@:11.0')
-    conflicts('%gcc@11:', when='+cuda ^cuda@:11.4.0')
-    conflicts('%gcc@12:', when='+cuda ^cuda@:11.5.0')
-    conflicts('%clang@12:', when='+cuda ^cuda@:11.4.0')
-    conflicts('%clang@13:', when='+cuda ^cuda@:11.5.0')
+    conflicts('%gcc@12:', when='+cuda ^cuda@:11.6')
+    conflicts('%clang@13:', when='+cuda ^cuda@:11.5')
+    conflicts('%clang@14:', when='+cuda ^cuda@:11.6')
 
     # https://gist.github.com/ax3l/9489132#gistcomment-3860114
     conflicts('%gcc@10', when='+cuda ^cuda@:11.4.0')
```

@ax3l seems like the conflicts were overly strict for 11.4 and 11.5?

```
$  grep unsupported */host_config.h | grep -E '(gcc|clang)' | sort -h
11.4.0-devel-ubuntu18.04/host_config.h:#error -- unsupported clang version! clang version must be less than 13 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
11.4.0-devel-ubuntu18.04/host_config.h:#error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
11.5.0-devel-ubuntu18.04/host_config.h:#error -- unsupported clang version! clang version must be less than 13 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
11.5.0-devel-ubuntu18.04/host_config.h:#error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
11.6.0-devel-ubuntu18.04/host_config.h:#error -- unsupported clang version! clang version must be less than 14 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
11.6.0-devel-ubuntu18.04/host_config.h:#error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```

**Review by haampie — CHANGES_REQUESTED** [review]
Needs updated compiler conflicts

**Review by haampie — DISMISSED** [review]

**Comment by haampie** [comment]
@scottwittenburg trillinos seems to take more than 6h to rebuild, is that expected?

**Comment by alalazo** [comment]
Restarted the job manually to see if we're more lucky this time.

**Comment by scottwittenburg** [comment]
> trillinos seems to take more than 6h to rebuild, is that expected?

I haven't seen it take that long before, so I would say no it's not expected.  I'm looking at the log of the timed out job, if there's any clue there I'll let you know.

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Comment by ax3l** [comment]
> @ax3l seems like the conflicts were overly strict for 11.4 and 11.5?

Thanks for the hint, will update: https://gist.github.com/ax3l/9489132

**Review by ax3l — DISMISSED** [review]

**Comment by scottwittenburg** [comment]
So that trilinos timeout is consistent at least, happening on both UO and AWS runners.  Tomorrow I'll try to reproduce the issue on a dedicated machine.  @sethrj are you or other maintainers of trilinos aware of any recent changes that would significantly increase the build time?

**Comment by haampie** [comment]
Can we merge regardless?

**Comment by sethrj** [comment]
@scottwittenburg Nothing should have changed recently, but this looks like the first time we've built Trilinos with CUDA 11.6, so possibly the compilation is slower for the trilinos use case? One thing we could do is depending on what @eugeneswalker needs for the `cuda_specs` version of Trilinos we could turn off a bunch of packages that are enabled for the "main" trilinos build. It's also a little ridiculous because Trilinos requires its vendored tribits version of Kokkos + KokkosKernels so those are being built twice... @keitat I don't suppose Trilinos 13.2 supports Kokkos as a TPL yet?

BTW we should really consider reducing the verbosity of the `Executable` call: literally half the output (2MB) is useless information about patchelf...

**Comment by Rombur** [comment]
> I don't suppose Trilinos 13.2 supports Kokkos as a TPL yet?

No unfortunately it doesn't :disappointed:

**Comment by sethrj** [comment]
OK, so depending on what else is in the "cuda" e4s pipeline, we could try disabling first-generation trilinos pakages inside `cuda_specs`:
```
    - trilinos@13.2.0 +cuda cuda_arch=70 ~amesos ~aztec +belos +boost ~epetra ~epetraext ~ifpack ~isorropia ~ml ~stk ~trilinoscouplings ~zoltan ~zoltan2
```

Also disabling `explicit_template_instantiation` might help tremendously: it would at least some shift the compile time to downstream packages, which (depending on what parts of Trilinos they actually need and whether those are duplicated across packages) could be a win.

**Comment by keitat** [comment]
@sethrj  We are in the middle of refactoring TriBITS, which aimed at CMake 3.x (use of target) and separation of Kokkos and SEACAS.  It's not ready, yet.

**Comment by scottwittenburg** [comment]
I can reproduce the timeout locally.  On my local machine the build is currently stuck at 76% (the same point it has gotten stuck in the pipeline builds), and this one sub-process of `spack install` has been running for almost 2 hrs now:

```
cicc --c++14 --gnu_version=70500 --diag_warn this_addr_capture_ext_lambda --display_error_number --orig_src_file_name /tmp/root/spack-stage/spack-stage-trilinos-13.2.0-l6w6aoxilfnacg4ch37gzi5o55p7excj/spack-build-l6w6aox/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Cuda.cpp --orig_src_path_name /tmp/root/spack-stage/spack-stage-trilinos-13.2.0-l6w6aoxilfnacg4ch37gzi5o55p7excj/spack-build-l6w6aox/packages/stokhos/src/Tpetra_MultiVector_UQ_PCE_Cuda.cpp --allow_managed --extended-lambda -arch compute_70 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name tmpxft_00001b5e_00000000-3_Tpetra_MultiVector_UQ_PCE_Cuda.fatbin.c -tused --gen_module_id_file --module_id_file_name /tmp/tmpxft_00001b5e_00000000-4_Tpetra_MultiVector_UQ_PCE_Cuda.module_id --gen_c_file_name /tmp/tmpxft_00001b5e_00000000-6_Tpetra_MultiVector_UQ_PCE_Cuda.cudafe1.c --stub_file_name /tmp/tmpxft_00001b5e_00000000-6_Tpetra_MultiVector_UQ_PCE_Cuda.cudafe1.stub.c --gen_device_file_name /tmp/tmpxft_00001b5e_00000000-6_Tpetra_MultiVector_UQ_PCE_Cuda.cudafe1.gpu /tmp/tmpxft_00001b5e_00000000-7_Tpetra_MultiVector_UQ_PCE_Cuda.cpp1.ii -o /tmp/tmpxft_00001b5e_00000000-6_Tpetra_MultiVector_UQ_PCE_Cuda.ptx
```

Here's a snapshot of the process tree:

```
# ps axfo pid,euser,egroup,etime,time,args
  PID EUSER    EGROUP       ELAPSED     TIME COMMAND
    1 root     root        03:03:37 00:00:02 /bin/bash
   17 root     root        03:03:30 00:00:00 /bin/bash /work/repro.sh
   68 root     root        03:03:27 00:00:00  \_ /bin/bash /work/repro.sh
   70 root     root        03:03:27 00:00:01  |   \_ tee jobs_scratch_dir/user_data/pipeline_out.txt
   69 root     root        03:03:27 00:00:00  \_ /bin/bash /work/repro.sh
   71 root     root        03:03:27 00:00:00  |   \_ tee jobs_scratch_dir/user_data/pipeline_err.txt
   72 root     root        03:03:27 00:00:32  \_ /usr/bin/python3 /work/spack/bin/spack -d ci rebuild
  153 root     root        03:02:37 00:00:00      \_ bash -l ./install.sh
  157 root     root        03:02:37 00:03:00          \_ /usr/bin/python3 /work/spack/bin/spack -d -v install --keep-stage --require-full-hash-match --no-check-signature --no-add -f /work/jobs_scratch_dir/reproduction/trilinos.yaml
14914 root     root        02:34:14 00:00:07              \_ /usr/bin/python3 /work/spack/bin/spack -d -v install --keep-stage --require-full-hash-match --no-check-signature --no-add -f /work/jobs_scratch_dir/reproduction/trilinos.y
18651 root     root        02:30:55 00:01:29                  \_ /usr/bin/python3 /work/spack/bin/spack -d -v install --keep-stage --require-full-hash-match --no-check-signature --no-add -f /work/jobs_scratch_dir/reproduction/trilin
18652 root     root        02:30:55 00:00:00                  \_ make -j16
18655 root     root        02:30:55 00:00:00                      \_ make -f CMakeFiles/Makefile2 all
 3062 root     root        01:41:18 00:00:00                          \_ make -f packages/stokhos/src/CMakeFiles/stokhos_tpetra_pce_cuda.dir/build.make packages/stokhos/src/CMakeFiles/stokhos_tpetra_pce_cuda.dir/build
 3095 root     root        01:41:18 00:00:00                              \_ /bin/sh -c cd /tmp/root/spack-stage/spack-stage-trilinos-13.2.0-l6w6aoxilfnacg4ch37gzi5o55p7excj/spack-build-l6w6aox/packages/stokhos/src && /work/software
 3097 root     root        01:41:18 00:00:00                                  \_ /bin/bash /work/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path
 5847 root     root        01:41:18 00:00:00                                      \_ /bin/bash /work/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_
 7006 root     root        01:41:17 00:00:00                                          \_ /work/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_p
 9673 root     root        01:41:13 00:00:00                                              \_ sh -c cicc --c++14 --gnu_version=70500 --diag_warn this_addr_capture_ext_lambda --display_error_number --orig_src_file_name "/tmp/root/spac
 9674 root     root        01:41:13 01:41:13                                                  \_ cicc --c++14 --gnu_version=70500 --diag_warn this_addr_capture_ext_lambda --display_error_number --orig_src_file_name /tmp/root/spack-s
```

Where `cicc` is:

```
# ls -al /proc/9674/exe 
lrwxrwxrwx 1 root root 0 Jan 20 20:11 /proc/9674/exe -> /work/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/cuda-11.6.0-d4ch36zqw4ut4zuxz2bl3q4d7t42gj5q/nvvm/bin/cicc
```

Here's the full output of the hierarchical process list as a file in case it's useful.

[procs.txt](https://github.com/spack/spack/files/7908760/procs.txt)

**Comment by haampie** [comment]
So, can we make trillinos depend on cuda@:11.5 until the problem is fixed so that this PR can be merged?

**Comment by eugeneswalker** [comment]
> So, can we make trillinos depend on cuda@:11.5 until the problem is fixed so that this PR can be merged?

I think this is the way to go

**Comment by eugeneswalker** [comment]
> So, can we make trillinos depend on cuda@:11.5 until the problem is fixed so that this PR can be merged?

Do you have preference for how this should be expressed?
As a constraint expressed in trilinos's package.py? Or, in E4S environment `^cuda@:11.5` ?

This looks like a trilinos issue to me, and if it is, it seems that trilinos' package.py is the best place to express this.

**Comment by sethrj** [comment]
We should be able to add `conflict('+stokhos', when='^cuda@11.6:')` since that seems to be the package that's failing. That package is failing (and indeed apparently doesn't work on the XL compiler) so it should be the one we target. It's off by default so I'm not sure what is enabling it.

**Comment by scottwittenburg** [comment]
> We should be able to add `conflict('+stokhos', when='^cuda@11.6:')` since that seems to be the package that's failing

I just opened #28530 to conflict with `cuda@11.6.0:` since that seems certain to prevent the issue until it can be investigated and fixed.

> It's off by default so I'm not sure what is enabling it.

Looks like it's enabled in the packages section of the E4S PR testing stack, [here](https://github.com/spack/spack/blob/76b7095445264fb02b53616695fc226266f76695/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml#L53).

**Comment by scottwittenburg** [comment]
@csbnw Can you rebase this on `develop` and force-push your branch now that #28530 is merged?  That should allow the gitlab pipeline to pass.

**Review by haampie — APPROVED** [review]

**Comment by kwryankrattiger** [comment]
@eugeneswalker do you know if this was fixed for cuda 11.7? The current spec in e4s wants cuda 11.7, but gets cuda 11.5 because of this.

**Comment by eugeneswalker** [comment]
> @eugeneswalker do you know if this was fixed for cuda 11.7? The current spec in e4s wants cuda 11.7, but gets cuda 11.5 because of this.

I don't know, no, but I will try it and find out.

**Pull request merged**
