### PR TITLE
openblas: fix flags

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/LLNL/spack/issues/3343

### CODE REVIEW

**Comment by adamjstewart** [comment]
That's weird. `spec` and `spec['name']` should be identical when `'name'` is the name of the package.

**Comment by davydden** [comment]
> spec and spec['name'] should be identical when 'name' is the name of the package.

are there unit tests which actually confirm this? 

p.s. I like to think if the feature is not tested, it is not implemented :smile:

**Comment by adamjstewart** [comment]
> p.s. I like to think if the feature is not tested, it is not implemented 😄

I agree, although it's a lot easier to look at existing packages for examples than to look through our test suites. I know I'm guilty of this.

**Comment by alalazo** [comment]
@adamjstewart If you think it like that:
```
if spec.name == 'name':
   assert spec is spec['name']
```
that's not true. But in most contexts they are both "ducks". Another thing that may be surprising (and I still have to understand 100% in all its implications) is that:
```
spec is not spec.package.spec
```
:smile:

**Pull request merged**
