### PR TITLE
CUDA/ROCm conflicts for various packages.

### PR DESCRIPTION
**Pull request by kwryankrattiger**
- ecp-data-vis-sdk, added for better error messages
- heffte
- petsc
- sundials
- trilinos, added propagation to superlu-dist

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
FYI: @eugeneswalker @wspear

There were enough of these I just made one PR. I am sure this isn't a complete list.

**Review by wspear — DISMISSED** [review]

**Comment by kwryankrattiger** [comment]
@spackbot reformat

**Comment by kwryankrattiger** [comment]
style/rebase

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by kwryankrattiger** [comment]
@eugeneswalker do we still need these?

**Comment by eugeneswalker** [comment]
> @eugeneswalker do we still need these?

I don't think so.

**Comment by kwryankrattiger** [comment]
Okay, closing.

**Pull request closed without merging**
