### PR TITLE
jdk: Remove Oracle JDK package

### PR DESCRIPTION
**Pull request by Pandapip1**
Supercedes https://github.com/spack/spack/pull/43250

Created a new PR that *just* removes the JDK, since the other changes were made and my motivation for removing the JDK has changed.

I am of the opinion that there is no good reason to use the Oracle JDK over OpenJDK, and keeping the Oracle JDK around will necessarily cause maintenance burden as the links rot.

### CODE REVIEW

**Comment by haampie** [comment]
The fact that you don't like it is not a reason to remove it.

**Comment by Pandapip1** [comment]
> The fact that you don't like it is not a reason to remove it.

You're putting words into my mouth. My two points were:

a) It's redundant; and
b) It adds a constant maintenance burden due to the fact that the links *will* rot

If *that* isn't enough to warrant a discussion, then fair enough, let me know and keep this PR closed.

**Comment by haampie** [comment]
> You're putting words into my mouth

Sorry for that, but it sounded like you expressed your opinion about the package, which may not be shared by others.

Note that links may not rot because we mirror sources (and fetch by shasum first).

I also don't think the burden is "constant", updates are not that frequent? Just annoying that there's no per version url.

**Comment by Pandapip1** [comment]
> Sorry for that, but it sounded like you expressed your opinion about the package, which may not be shared by others.

No worries.

> Note that links may not rot because we mirror sources (and fetch by shasum first).

Didn't the links for the older versions of the JDK rot? Did the mirror not work in that situation? I'm probably misunderstanding how it works, but to me it looks like link rot will be an issue for this package.

> I also don't think the burden is "constant", updates are not that frequent? Just annoying that there's no per version url.

"Constant" is the wrong word. "Persistent" is a bit better. I guess if you guys are okay maintaining it, I can't complain. 

Anyway, is there a way to tell spack to prefer OpenJDK over the Oracle JDK when installing `java`?

**Pull request closed without merging**
