### PR TITLE
Remove handling of deprecated target names (graviton)

### PR DESCRIPTION
**Pull request by alalazo**
Modification:
- [x] Remove handling of deprecated target names
- [x] Update pipelines accordingly

### CODE REVIEW

**Review by haampie — DISMISSED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
This PR hits the same issue of incorrect checksums

**Comment by alalazo** [comment]
Tried restarting to double check if it was a hiccup of our infrastructure :crossed_fingers:

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Pull request merged**
