### PR TITLE
gitlab ci: more resources for paraview and py-torch

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Review by zackgalbreath — APPROVED** [review]

**Comment by zackgalbreath** [comment]
Somewhat amusing (to me, at least) that paraview was already given extra resources in the data-vis-sdk stack, but not E4S. More motivation for #34272

**Comment by scottwittenburg** [comment]
I doubt a 32 core machine lacks the memory to concretize this aws ahug stack, so maybe this failure was another yanked spot instance?

```
ERROR: Job failed: pod "runner-1-mwcvye-project-2-concurrent-16q4kz2" status is "Failed"
```

**Comment by scottwittenburg** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Out of curiosity, how does one determine whether or not this is needed? I vaguely recall seeing intermittent failures with PyTorch, can't remember if TF was also failing. Do you see OOM errors in the logs, or just attribute all intermittent errors to resource availability?

**Comment by zackgalbreath** [comment]
> Out of curiosity, how does one determine whether or not this is needed? I vaguely recall seeing intermittent failures with PyTorch, can't remember if TF was also failing. Do you see OOM errors in the logs, or just attribute all intermittent errors to resource availability?

This is still a bit of an open question that we're planning to address more thoroughly.

For these two particular packages, I noticed that they were taking a long time to build within the E4S stack for a develop pipeline that was blocking a bunch of PRs. I checked and realized that they did not override the default request of 750m vCPUs, told Scott about it, and he volunteered to improve the situation.

**Comment by adamjstewart** [comment]
TF is prob the only other PR in my ML stacks worth investigating. I know that one can be a beast to build.

**Pull request merged**
