### PR TITLE
Packages/scalasca

### PR DESCRIPTION
**Pull request by alalazo**
Modifications:
- [x] scalasca doesn't build two times per installation anymore
- [x] updated scalasca dependencies
- [x] simplified code of scalasca + dependencies after #255 

Manually tested:
* Ubuntu 14.04 and RHLE 6 with GCC and MPICH

### CODE REVIEW

**Comment by tgamblin** [comment]
@daboehme: it looks like @alalazo implemented the suggestion from yesterday.  Can you take a look at this?  In general I like the fact that this involves a lot less code.  If the scalasca build can auto detect from compiler names, I think that is more reliable.

One question is how this might work on BG/Q -- will having proper compiler names work there?

**Comment by tgamblin** [comment]
@alalazo: I talked to @daboehme and his only worry about this one is that scalasca and the other tools won't recognize the new compilers and will default to `gcc` -- do you know if that's true or are the names in `CC`, `CXX`, etc. sufficient for the build to recognize the new compilers?  I have some other stuff to work on before I can check this out myself.

**Comment by alalazo** [comment]
@tgamblin : the two tests above seem to pick the right compiler (I attached some details below for clarity). On the other hand two is not much of a statistics, so I agree in having this thoroughly tested. I can quite easily try a `clang` and an `intel` based build, but I don't have access to IBM machines for `xl` or to `pgi` compiler. Would a post in the mailing list asking people to test this and report problems be acceptable?

------

##### Ubuntu 14.04 % GCC 5.3.0
```
$ ls /home/mculpo/jetbrains/PyCharmProjects/spack/opt/spack/nuvolari/gcc-5.3.0/scalasca-2.2.2-j7xme5izcsokuucrvhudpyhhzbxquefz/bin
clc_analyze.hyb  clc_analyze.mpi  clc_synchronize.hyb  clc_synchronize.mpi  salsa.mpi  scalasca  scan  scout.hyb  scout.mpi  scout.omp  scout.ser  silas.mpi  skin  square
$ ldd /home/mculpo/jetbrains/PyCharmProjects/spack/opt/spack/nuvolari/gcc-5.3.0/scalasca-2.2.2-j7xme5izcsokuucrvhudpyhhzbxquefz/bin/scan
	linux-vdso.so.1 =>  (0x00007ffc70ba5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3853415000)
	libstdc++.so.6 => /home/mculpo/jetbrains/PyCharmProjects/spack/opt/spack/nuvolari/gcc-4.8/gcc-5.3.0-76iapbti4lxoca5s7o7du4y33vkwfjvi/lib64/libstdc++.so.6 (0x00007f385309a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3852d94000)
	libgcc_s.so.1 => /home/mculpo/jetbrains/PyCharmProjects/spack/opt/spack/nuvolari/gcc-4.8/gcc-5.3.0-76iapbti4lxoca5s7o7du4y33vkwfjvi/lib64/libgcc_s.so.1 (0x00007f3852b7e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38527b8000)
	/lib64/ld-linux-x86-64.so.2 (0x0000564bd7a2d000)
$ module list
No Modulefiles Currently Loaded.
$ which gcc
/usr/bin/gcc
```
-----

##### RHLE 6 % GCC 4.9.3
```
$ ls /home/culpo/github/spack/opt/spack/x86_E5v2_IntelIB/gcc-4.9.3/scalasca-2.2.2-l4dfoc3uvza66cz2iwun5uz6huiv4ymp/bin
clc_analyze.hyb  clc_analyze.mpi  clc_synchronize.hyb  clc_synchronize.mpi  salsa.mpi  scalasca  scan  scout.hyb  scout.mpi  scout.omp  scout.ser  silas.mpi  skin  square
$ ldd /home/culpo/github/spack/opt/spack/x86_E5v2_IntelIB/gcc-4.9.3/scalasca-2.2.2-l4dfoc3uvza66cz2iwun5uz6huiv4ymp/bin/scan
	linux-vdso.so.1 =>  (0x00007fff935ff000)
	libz.so.1 => /lib64/libz.so.1 (0x0000003acbe00000)
	libstdc++.so.6 => /home/culpo/github/spack/opt/spack/x86_E5v2_IntelIB/gcc-4.4.7/gcc-4.9.3-qskr33q77xwb3b72342fz4fjuxj6vlii/lib64/libstdc++.so.6 (0x00007f617b127000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003acaa00000)
	libgcc_s.so.1 => /home/culpo/github/spack/opt/spack/x86_E5v2_IntelIB/gcc-4.4.7/gcc-4.9.3-qskr33q77xwb3b72342fz4fjuxj6vlii/lib64/libgcc_s.so.1 (0x00007f617af10000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003acae00000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003aca600000)
$ which gcc
/usr/bin/gcc
$ module list
No Modulefiles Currently Loaded.
```

**Comment by tgamblin** [comment]
@alalazo I think this is fine for now.  I can merge and perhaps @daboehme can check this on BG.

**Pull request merged**
