### PR TITLE
Fixing provides directive for intel-oneapi-onedal package

### PR DESCRIPTION
**Pull request by napetrov**
Define correct provides directive for onedal package 

daal -> onedal

### CODE REVIEW

**Comment by napetrov** [comment]
@DanVev  @rscohn2  please review

**Comment by rscohn2** [comment]
Provides is used when multiple packages provide the same functionality. All the providers and users must agree on the same name. I used daal because these packages developed by the community are using that name:

https://github.com/spack/spack/blob/6f9a9976a8c8d8b9da61ad187fe6c7759b5b8f51/var/spack/repos/builtin/packages/intel-daal/package.py#L55

https://github.com/spack/spack/blob/6f9a9976a8c8d8b9da61ad187fe6c7759b5b8f51/var/spack/repos/builtin/packages/intel-parallel-studio/package.py#L187

It would be difficult to change now.

If oneapi dal is not compatible with them, then I will delete the provides in this package until a time when there are multiple compatible providers.

**Comment by napetrov** [comment]
Well - we've changed name from daal to onedal with introduction of oneAPI.  So it's ok that intel-daal and parallel studio provides daal. 
but oneapi package actually provides onedal package.  We do have API compatibility but i think it worth defining new package name here.

On removing vs updating - might be good idea would be to use onedal straight away so this would be used as guidance for other package creators. 
Also per reading documentation i see that provides also suppose to match library name - for example libonedal.so and provides directive is only place there we can set "onedal" part of this for package. Not sure if this is required to have or just naming convention.

**Comment by rscohn2** [comment]
There is no requirement that library and provides have the same name. Other examples of provides are BLAS and MPI.  Provides is really  a statement about whether a package implements an interface, which is useful when an interface is implemented by multiple packages.

I suggest you leave the current daal provides and add an additional onedal provides. The package implements the daal interface and the onedal interface. You want users of packages that require the old interface to migrate to the new package.

**Comment by napetrov** [comment]
Done - adding both directives

**Review by rscohn2 — DISMISSED** [review]

**Comment by rscohn2** [comment]
@tldahlgren @alalazo: This PR is ready for merging, assuming testing passes.

**Comment by napetrov** [comment]
Re-basing to resolve "mypy checks" failures

**Comment by napetrov** [comment]
@tldahlgren  could you please trigger workflow for this PR

**Review by alalazo — APPROVED** [review]

**Pull request merged**
