### PR TITLE
perl-fth: add the external find feature for perl-fth and new release

### PR DESCRIPTION
**Pull request by cessenat**
initmak.pl is improved https://sourceforge.net/p/ftagshtml/news/ and there is a new release 0.526.
Moreover, the external find feature is added.

### CODE REVIEW

**Comment by glennpj** [comment]
@alalazo It is not clear to me if there would be any issues with having extensions as externals. Can an external perl extension work properly with a spack built perl? I think the other direction should be fine.

**Comment by alalazo** [comment]
> Can an external perl extension work properly with a spack built perl?

I don't think so at the moment. Externals model a "plugin" system so the dependent needs the dependee (e.g. a Perl package needs Perl to extend its functionality). Right now for externals we trim all the dependencies, so I think they won't have an interpreter associated with them.

**Review by glennpj — CHANGES_REQUESTED** [review]
Based on https://github.com/spack/spack/pull/28886#issuecomment-1041310858, this PR should be limited to just a version update.

**Comment by cessenat** [comment]
> Based on [#28886 (comment)](https://github.com/spack/spack/pull/28886#issuecomment-1041310858), this PR should be limited to just a version update.

It should if it were a perl extension but it is not, it is just merely a perl script.
Maybe the package name is confusing ? Should it be renamed ?

**Comment by glennpj** [comment]
@cessenat I assumed it was a perl extension due to the name. When I look at the full file contents instead of just the diff I see that it uses `Package` and not `PerlPackage`. I know that for python, packages that are python based but deploy scripts as the means to use the package do not have the `py-` prefix. That probably also makes sense for perl based tools, but a name change is up to you.

**Review by glennpj — APPROVED** [review]

**Comment by glennpj** [comment]
@spackbot run pipeline

**Comment by cessenat** [comment]
OK, thanks for reviewing.

**Pull request merged**
