### PR TITLE
Bump up the version for rocm-5.2.1 release

### PR DESCRIPTION
**Pull request by srekolam**
This PR has the version related changes for rocm-5.2.1 release. I corrected the miopen-opencl recipe. depends_on(hip) does not seem correct for the miopen-opencl recipe. so i corrected it.

### CODE REVIEW

**Comment by srekolam** [comment]
Will depend upon the changes in #31667 going in .

**Comment by srekolam** [comment]
can i get the review comments .

**Comment by srekolam** [comment]
can you please review this ..

**Review by renjithravindrankannath — APPROVED** [review]
LGTM

**Comment by srekolam** [comment]
@alalazo @tldahlgren can i get this reviewed pls.

**Review by tldahlgren — APPROVED** [review]
Confirmed all new package sha256.

**Pull request merged**
