### PR TITLE
Add Boost 1.80.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by hainest — DISMISSED** [review]
Confirmed checksum.

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Looks like `boost` is failing for the `e4s-oneapi` pipeline stack (https://gitlab.spack.io/spack/spack/-/jobs/3475109) and `dealii` for the `e4s` stack (https://gitlab.spack.io/spack/spack/-/jobs/3480636).

**Comment by hainest** [comment]
**e4s-oneapi/boost**
```
boost-install.generate-cmake-config- bin.v2/libs/math/build/install/boost_math_tr1-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/math/build/install/boost_math_tr1-config-version.cmake
boost-install.generate-cmake-config- bin.v2/libs/math/build/install/boost_math_tr1f-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/math/build/install/boost_math_tr1f-config-version.cmake
boost-install.generate-cmake-config- bin.v2/libs/math/build/install/boost_math_tr1l-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/math/build/install/boost_math_tr1l-config-version.cmake
intel-linux.compile.c++ bin.v2/libs/graph_parallel/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/local-visibility-global/threading-multi/visibility-hidden/tag_allocator.o
icpx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list: 
	-ip
boost-install.generate-cmake-config- bin.v2/libs/log/build/install/boost_log_setup-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/log/build/install/boost_log_setup-config-version.cmake
intel-linux.compile.c++.pch bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden/pch.pchi
icpx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list: 
	-ip
clang++: error: no such file or directory: 'bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden/pch.pchi'
clang++: error: unsupported argument 'h-create' to option '-pc'

    rm -f "bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden/pch.pchi" &&  "/builds/spack/spack/lib/spack/env/oneapi/icpx" -x c++-header -std=c++17 -fvisibility-inlines-hidden -m64 -pthread -fvisibility=hidden -inline-level=2 -O3 -ip -Wall -fvisibility=hidden -DBOOST_ALL_NO_LIB=1 -DBOOST_BUILD_PCH_ENABLED -DNDEBUG -I"." -I"libs/math/src/tr1" -c -pch-create "bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden/pch.pchi" "libs/math/build/../src/tr1/pch.hpp"

...failed intel-linux.compile.c++.pch bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden/pch.pchi...
...skipped <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>acosh.o for lack of <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>pch.pchi...
...skipped <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>asinh.o for lack of <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>pch.pchi...
...skipped <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>atanh.o for lack of <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>pch.pchi...
...skipped <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>cbrt.o for lack of <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>pch.pchi...
...skipped <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>copysign.o for lack of <pbin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/link-static/threading-multi/visibility-hidden>pch.pchi...
```
I'm not sure here. I never use PCH.

**e4s/dealli**

```
2110-/tmp/root/spack-stage/spack-stage-dealii-9.4.0-wx34uiuli2z77dcxim2jse73obtyxqki/spack-src/examples/step-70/step-70.cc: In function 'void Step70::read_grid_and_cad_files(const string&, const string&, dealii::Triangulation<dim, spacedim>&)':
2111:/tmp/root/spack-stage/spack-stage-dealii-9.4.0-wx34uiuli2z77dcxim2jse73obtyxqki/spack-src/examples/step-70/step-70.cc:838:39: error: 'boost::algorithm' has not been declared
2112-  838 |         const auto extension = boost::algorithm::to_lower_copy(
```
Boost have been cleaning up their headers to remove implicit inclusions.

**Comment by msimberg** [comment]
Could those two problems be added as conflicts for the moment? dealii already seems to have a few Boost-specific restrictions and patches. @jppelteret, @luca-heltai may be able to provide a patch already for this PR? I also have no idea about the PCH error.

**Comment by haampie** [comment]
Yeah, I think it's fine to add (1) a conflict on `boost@1.80` / `boost@1.80:` in `dealii` with a comment linking to this pr, and (2) a conflict on `%oneapi` when `@1.80.0` in `boost` + comment, just so we have the latest boost available in Spack.

**Review by haampie — APPROVED** [review]

**Review by jppelteret — APPROVED** [review]
Thanks for adding the restriction to the deal.II package. I don't recall what the latest supported boost is, so we can come back and adjust this at a later stage.

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Pipeline pod/system failures.

@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by msimberg** [comment]
@spackbot run pipeline

**Comment by msimberg** [comment]
I can't really tell if this is a problem or not: https://gitlab.spack.io/spack/spack/-/jobs/3583597. From what I can tell the job simply takes too long and times out, or is there something else to it?

**Comment by haampie** [comment]
tough day at the office for gitlab pipelines...

@spackbot run pipeline

**Comment by hainest** [comment]
@haampie @alalazo @msimberg I've sent an email to Sameer Shende and Wyatt Spear about the pipeline issues. They will take a look.

**Comment by msimberg** [comment]
@spackbot run pipeline

**Pull request merged**
