### PR TITLE
Add --force flag, re-installs even if package was already installed.

### PR DESCRIPTION
**Pull request by citibeth**
This `--force` flag is useful when using `spack setup`, where "installs" are all fake anyway.  Don't want to have to do a `spack uninstall` every time we just want to generate a new `spconfig.py` file.

### CODE REVIEW

**Comment by tgamblin** [comment]
Can this not be reworked to do a force-uninstall followed by a reinstall, to avoid complicating the already complicated logic in `package.py`?

**Comment by tgamblin** [comment]
Basically I'm thinking this should be handled at the level of the install command, not in the core.

**Comment by citibeth** [comment]
That sounds like a good idea.  Stay tuned...

**Comment by pramodk** [comment]
@citibeth : I started using `spack setup` and saw the same thing. This `--force` flag would be useful!

**Comment by adamjstewart** [comment]
I agree with @tgamblin, this should be handled at the command level. Would be very useful though!

**Comment by citibeth** [comment]
I agree as well.  Just haven't gotten a round toit.

**Comment by alalazo** [comment]
Superseded by #5384

**Pull request closed without merging**
