### PR TITLE
Flux: Latest Releases & Env Var Fixes/Cleanup

### PR DESCRIPTION
**Pull request by SteVwonder**
This PR adds the latest flux versions as well as some fixes/cleanups of the runtime environment variables set.

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
From install of flux-core@0.29 on Ubuntu 18.04:
```yaml
libczmqcontainers/zhashx.h:283:13: error: unknown type name 'zframe_t'; did you mean 'locale_t'?
 CZMQ_EXPORT zframe_t *
```
libzmq version mismatch?
```
pack solve flux-core@0.29|grep zmq
    ^czmq@4.1.1%gcc@7.5.0 arch=linux-ubuntu18.04-zen
        ^libzmq@4.3.3%gcc@7.5.0~drafts+libsodium arch=linux-ubuntu18.04-zen
```
I guess an older of czmq version might be required to build.
Which versions did you use to build?

**Comment by SteVwonder** [comment]
It worked for me with those same versions 🤷 I just did `spack solve -y flux-core > ~/flux-core.solve.yaml` followed by `spack install -f ~/flux-core.solve.yaml`.  Here is the resulting built package spec:

```
❯ spack find -ldv flux-core@0.29.0                                                                                                                                                                                             17:17:34 ()
==> 1 installed package
-- linux-rhel7-x86_64 / gcc@4.9.3 -------------------------------
x3jummj flux-core@0.29.0~cuda~docs
c2rjvus     czmq@4.1.1
sxhktuw         libzmq@4.3.3~drafts+libsodium
utxlyhe             libbsd@0.11.3
md3oyfn                 libmd@1.0.3
3lnhp2y             libsodium@1.0.18
lt3uhcd         util-linux-uuid@2.36.2
4kx6hul     hwloc@2.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared
2ahue7m         libpciaccess@0.16
g2owcxz         libxml2@2.9.12~python
mygdizs             libiconv@1.16 libs=shared,static
ml7pk2i             xz@5.2.2~pic libs=shared,static
wekdy4s             zlib@1.2.11+optimize+pic+shared
kppog4c         ncurses@6.2~symlinks+termlib abi=none
6ppz4l5     jansson@2.13.1~ipo+shared build_type=RelWithDebInfo
vpjtgjo     lua@5.3.5~pcfile+shared
5b2rbe2         readline@8.1
vsh2vhh         unzip@6.0
z3uvyxf     lua-luaposix@35.0
gqycgfb     lz4@1.9.3 libs=shared,static
6zdlzui     pkgconf@1.8.0
g3tf2l4     py-cffi@1.14.3
5r4kyxo         libffi@3.3 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0
jau73ly         py-pycparser@2.20
pp5k6iw             python@3.8.11+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4
cwj2b3p                 bzip2@1.0.6~debug~pic+shared
kf4xmxw                 expat@2.4.1+libbsd
yumaw5x                 gdbm@1.21
lqyznuu                 gettext@0.21+bzip2+curses+git~libunistring+libxml2+tar+xz
depxvya                     tar@1.26 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4
6rlkeoz                 openssl@1.1.1l~docs certs=system
3odg3nn                 sqlite@3.36.0+column_metadata+fts~functions~rtree
5pg4ykn     py-jsonschema@3.2.0
ioq4d6l         py-attrs@20.3.0
dary72b         py-pyrsistent@0.15.7
hj6cjqi             py-six@1.15.0
xlgls2v         py-setuptools@57.4.0
a7ezz65     py-pyyaml@5.3.1+libyaml
dkl2zoo         libyaml@0.2.5
ms3bfgs     yaml-cpp@0.7.0~ipo+pic+shared~tests build_type=RelWithDebInfo
```

I can try with the same compiler version as you to see if that makes a difference.

**Comment by SteVwonder** [comment]
Compiling with `gcc@7.5.0` worked for me as well. Hmm...

```
❯ spack find -ldv flux-core%gcc@7.5.0                                                                                                                                                                                             14:22:52 ()
==> 1 installed package
-- linux-rhel7-x86_64 / gcc@7.5.0 -------------------------------
34gmrup flux-core@0.29.0~cuda~docs
oi6vbwg     czmq@4.1.1
kgrywby         libzmq@4.3.3~drafts+libsodium
sc7whlv             libbsd@0.11.3
3gymnd6                 libmd@1.0.3
knqr3bz             libsodium@1.0.18
3yhwt5i         util-linux-uuid@2.36.2
lz3moj6     hwloc@2.5.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared
hi5wvzw         libpciaccess@0.16
qlcxtc2         libxml2@2.9.12~python
n3gvg34             libiconv@1.16 libs=shared,static
dhu5fn5             xz@5.2.5~pic libs=shared,static
rphwrek             zlib@1.2.11+optimize+pic+shared
mqzbmcg         ncurses@6.2~symlinks+termlib abi=none
3a34czj     jansson@2.13.1~ipo+shared build_type=RelWithDebInfo
fmoazhj     lua@5.3.5~pcfile+shared
4hm74zs         readline@8.1
em42pty         unzip@6.0
7twdnsi     lua-luaposix@35.0
sosiqyj     lz4@1.9.3 libs=shared,static
mu2rzeb     pkgconf@1.8.0
wf7dlw4     py-cffi@1.14.3
yxilgt6         libffi@3.3 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0
zlgx5cy         py-pycparser@2.20
st7b32w             python@3.8.11+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4
shesy7p                 bzip2@1.0.8~debug~pic+shared
g7w2772                 expat@2.4.1+libbsd
bnfgh22                 gdbm@1.19
dg35u7r                 gettext@0.21+bzip2+curses+git~libunistring+libxml2+tar+xz
iloghcx                     tar@1.34
ff6hvya                 openssl@1.1.1l~docs certs=system
dwzmvml                 sqlite@3.36.0+column_metadata+fts~functions~rtree
nvl5hil     py-jsonschema@3.2.0
tcl5rts         py-attrs@20.3.0
xw6u6zo         py-pyrsistent@0.15.7
gywif5k             py-six@1.15.0
loyfmgt         py-setuptools@57.4.0
a65wjsb     py-pyyaml@5.3.1+libyaml
beqybl2         libyaml@0.2.5
7pqjb4u     yaml-cpp@0.7.0~ipo+pic+shared~tests build_type=RelWithDebInfo
```

**Review by bernhardkaindl — APPROVED** [review]

**Comment by bernhardkaindl** [comment]
I'm merging this and follow-up with a new PR for further updates: #26690

**Pull request merged**
