### PR TITLE
Add a PR template with a reference to spackbot commands

### LINKED ISSUE #42271: Make spackbot documentation accessible from spack documentation
### Summary

I can never remember what Spackbot is capable of doing. Searching the documentation found no results.

### Rationale

The problem is I can't remember.

### Description

I would like to have SpackBot style my PR but can't remember the command.

### Additional information

_No response_

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alalazo**
fixes #42271

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM

**Comment by alalazo** [comment]
@tldahlgren I pushed without seeing the review. Do you have preferences between the new version (HTML comment) and the previous version (`<details>` section in the PR)?

**Review by tldahlgren — APPROVED** [review]
Not sure what the difference looks like but I think the latest is more concise.

(FWIW. I usually use `@spackbot run pipeline` to re-run but that's not important so long as one of the key commands is shown for those not familiar with the options.)

**Comment by alalazo** [comment]
> Not sure what the difference looks like but I think the latest is more concise.

The last version will not be rendered, so people will be reminded only when they open or edit a PR. The previous version would have been rendered like below on each and every PR:

----

<details>
<summary>Spackbot commands and options</summary>

- `@spackbot help` shows all the commands that are currently available
- `@spackbot fix style` tries to push a commit to fix style issues in this PR
- `@spackbot re-run pipeline` runs the pipelines again, if you have write access to the repository 
</details>

**Comment by alalazo** [comment]
Lol, let's go with a comment, I suspect `spackbot` might try to execute backtick'ed commands :laughing:

**Comment by alalazo** [comment]
I tried the last template manually in https://github.com/spack/spack/pull/42355 It doesn't seem to have side effects (i.e. spurious calls to `spackbot` due to the commands being present in the PR description)

<details><summary>PR text when editing</summary>
<p>

Screenshot from 2024-01-29 21-20-38


</p>
</details>

**Comment by haampie** [comment]
Almost certainly will have side effects if someone poorly quote replies from their phone's email client or whatever.

Just leave it as a comment :)

**Pull request merged**
