### PR TITLE
py-instrain and py-drep: new version and added maintainer

### PR DESCRIPTION
**Pull request by luke-dt**

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
LGTM!

@MrOlm do you consent to maintaining these build recipes?

**Comment by MrOlm** [comment]
@adamjstewart Yes I do!

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@luke-dt you will have to rebase

**Pull request merged**
