### PR TITLE
Compiling python with gnu c++ on macos fails with toolboxglue enabled.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by davydden** [comment]
@tgamblin could you have a look at this PR, which fixes python on macOS?

**Comment by citibeth** [comment]
Which version of OS X are you using?  I've found that El Capitan is quite different from anything before it.

**Comment by davydden** [comment]
I am on El Capitan and I checked that this patch makes python compile with GCC 6.2.

**Comment by gartung** [comment]
The toolboxglue error occurs on 10.9,10.10 and 10.11.

**Comment by citibeth** [comment]
I'm not surprised... I don't know the exact bounds of when things break.
But I do know that many GCC versions are not able to build Objective C code
on recent Macs.

**Comment by davydden** [comment]
@tgamblin ping.

**Comment by davydden** [comment]
@tgamblin ping ping.

**Comment by tgamblin** [comment]
merged as e6dc448.

**Pull request closed without merging**
