### PR TITLE
seqkit: add 2.4.0, switching to 'go build' install mechanic

### PR DESCRIPTION
**Pull request by A-N-Other**
Adding `seqkit@2.4.0`. As of `@0.15.0:`, `seqkit` switched to a modules system that allows easy building with `go build`. Previously, this `package.py` was pulling precompiled Linux binaries from GitHub, so I've rewritten it to build and install from the source code so that it's not dependent on the arch.

This change breaks with the previous install mechanic, so for now I've left the original `@0.10.1` as it was but have set it as `deprecated` so that it can be removed in the future.

// EDIT // This has been sat here a while now and I've since updated again to add `@2.5.1` and `@2.6.1`. As it's been 6 months, I've dropped the version I deprecated, as above, and removed the conditional build logic.

### CODE REVIEW

**Comment by alalazo** [comment]
@alecbcs Can you comment on the `go build` use here? Do we have more idiomatic ways to deal with Go packages?

**Comment by alecbcs** [comment]
We do, @A-N-Other I'd look at making this a `GoPackage` using [scc](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/scc/package.py) or [glow](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/glow/package.py) as examples.

**Comment by A-N-Other** [comment]
`GoPackage` 😎 

Wasn't about when I wrote this. Will look at switching it over ...

**Comment by A-N-Other** [comment]
@alecbcs Am I being dense here? This package needs to build in the `./seqkit` directory but I can't get this to respect `build_directory = "seqkit"`. Minimally, I'd have expected this to work ...

```
from spack.package import *

class Seqkit(GoPackage):
    url = "https://github.com/shenwei356/seqkit/archive/refs/tags/v2.4.0.tar.gz"
    version("2.7.0", sha256="b5c723ffd4640659860fc70a71c218d8f53bea0eae571cecc98eff04c7291e02")
    depends_on("go@1.17:", type="build")
    build_directory = "seqkit"
```

... but I get `no Go files in {the spack_src directory in here}`.

As an aside, I notice [here](https://github.com/spack/spack/blob/2c4b529896537ca4541fed1b1ea073504ad9af08/lib/spack/spack/build_systems/go.py#L30) that you're using `extends` rather than `depends_on`. Is this something that we should be using in the individual `package.py`s as well? `seqkit` is supposed to require `@1.17:` ... and [`glow`](https://github.com/charmbracelet/glow/blob/1eacfb4ff1240d16811e48c4454a6ff627ee6d30/go.mod#L3) and [`ssc`](https://github.com/boyter/scc/blob/af51102ed6b6a331f1f959bf00ef95a57891cd92/go.mod#L3) should also have these definitions.

**Comment by A-N-Other** [comment]
@alecbcs FYI `GoPackage` doesn't seem to properly respect setting the `build_directory`. Right now it only works by subclassing the builder and adding it in there - see the latest push. All my attempts to make it set 'normally' are ignored.

As an aside, I notice [here](https://github.com/spack/spack/blob/2c4b529896537ca4541fed1b1ea073504ad9af08/lib/spack/spack/build_systems/go.py#L30) that you're using `extends` rather than `depends_on`. Is this something that we should be using in the individual `package.py`s as well? `seqkit` is supposed to require `@1.17:` ... and [`glow`](https://github.com/charmbracelet/glow/blob/1eacfb4ff1240d16811e48c4454a6ff627ee6d30/go.mod#L3) and [`ssc`](https://github.com/boyter/scc/blob/af51102ed6b6a331f1f959bf00ef95a57891cd92/go.mod#L3) should also have these definitions.

**Comment by alecbcs** [comment]
@A-N-Other I can confirm something is up with the `GoPackage` class not respecting overwrites from child classes. I've talked with @alalazo who said he'd help out debugging the class with me. I'll take a look at reviewing this PR in the meantime.

**Review by alecbcs — APPROVED** [review]
Looks good to me. Thanks @A-N-Other

**Pull request merged**
