### PR TITLE
cmake: add v3.30.0-rc1

### PR DESCRIPTION
**Pull request by johnwparent**
Not sure if we want to offer CMake rcs? Feel free to close if we don't, I was adding the 329.5 release and thought might as well see if there's interest for the rc series. 

Adds CMake release candidates for the 3.30 minor release series First release candidate

### CODE REVIEW

**Comment by johnwparent** [comment]
@spackbot fix style

**Comment by haampie** [comment]
Unlikely... but if CI helps finding bugs in cmake that's OK?

**Comment by johnwparent** [comment]
> Unlikely... but if CI helps finding bugs in cmake that's OK?

Sounds all right to me. In that case I'll make this a draft and just keep adding the RC's to see if anything breaks. Thanks!

**Review by alecbcs — APPROVED** [review]
Verified Checksums. Looks good to me. Waiting on final approval from @alalazo.

**Comment by johnwparent** [comment]
> Verified Checksums. Looks good to me. Waiting on final approval from @alalazo.

@alecbcs I think @haampie makes a valid point that RC's don't really need to be in Spack. 
It would be cool to offer them to users, but it could also result in unexpectedly broken pipelines as the RCs are by definition, for testing. 

I'm fine not adding this to Spack, just using this PR to test the RCs in CI and check for errors in the RCs that may end up affecting our pipelines when we actually cut the release.

**Comment by alecbcs** [comment]
This sounds reasonable to me. I'll suggest prefixing the PRs / modifying them with a tag so that we don't accidentally merge them. (There are other packages where we do add release candidates.)

**Comment by johnwparent** [comment]
> This sounds reasonable to me. I'll suggest prefixing the PRs / modifying them with a tag so that we don't accidentally merge them. (There are other packages where we do add release candidates.)

Does GL still run if the PR is a draft? If so, then I feel like draft PRs serve that process pretty well.

**Comment by alecbcs** [comment]
GitLab doesn't currently run on draft PRs but that might be a legacy decision that we could change. @scottwittenburg @kwryankrattiger what do you think?

**Comment by bernhardkaindl** [comment]
Obsoleted by the merged #45418

**Pull request closed without merging**
