### PR TITLE
py-python-lzo: add 1.15

### PR DESCRIPTION
**Pull request by A-N-Other**
Updating to `@1.15`, required by an update to `py-bx-python`.

### CODE REVIEW

**Review by manuelakuhn — COMMENTED** [review]
Starting with version 1.13 `py-setuptools` has a minimal version restriction (see [pyproject.toml](https://github.com/jd-boyd/python-lzo/blob/v1.15/pyproject.toml#L3)
```
depends_on("py-setuptools@42:", when="@1.13:", type="build")
```

In the future, you can add packages that depend on each other, like here with `py-python-lzo` and `py-bx-python`, in one PR if you want. Then you avoid the problem about which package should be merged before what other package.

**Comment by A-N-Other** [comment]
Made that change.

Thanks, I'll note that for the future - I was just attempting to make it clearer in terms of naming the PRs.

**Review by adamjstewart — APPROVED** [review]

**Comment by A-N-Other** [comment]
@spackbot run pipeline

**Comment by A-N-Other** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
