### PR TITLE
Update cmake package with 3.24 major release

### PR DESCRIPTION
**Pull request by johnwparent**
Include 3.24.1 and 3.24.2

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed all three new sha256.  Will defer merge decision until at least one requested reviewer has a chance to comment.

**Comment by adamjstewart** [comment]
@chuckatkins is the maintainer but for some reason didn't get automatically pinged.

I don't know anything about CMake.

**Review by alalazo — DISMISSED** [review]
@johnwparent Can you add yourself or anybody appropriate from Kitware as maintainers in a following PR?

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
@alalazo Didn't notice the auto-merge before I re-approved.  Perhaps a new PR to add a maintainer?

**Pull request merged**
