### PR TITLE
Add variants for libunwind

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by mwkrentel** [comment]
@iarspider I'm curious, are all the new variants things you plan to
actually use, or are they just "in principle"?

Anyway, `spack install` is currently broken.

```
$ spack install libunwind
...
==> Error: TypeError: enable_or_disable() got an unexpected keyword argument 'variant'
...
  >>     99        args += self.enable_or_disable('mindebuginfo', variant='xz')
```

The keyword is `variant_name`, not `variant`.

Btw, I don't know what the automated tests are actually testing for
when all the tests pass but spack install fails. !?

----------

About the libunwind-fix-comma.patch, is there some specific platform
and compiler where the build fails without the patch, or is this just
for style?

I've never seen this kind of thing fail and I don't see any upstream
issue or PR to "fix" it in the libunwind sources.  So, unless it fixes
something that actually breaks, I'd prefer to leave this out.

---------

Several of the new variants don't go back all the way to 1.1 or 1.2.1.
For example, at least mindebuginfo, tests, and weak-backtrace don't
exist in 1.2.1.  I don't think this exactly breaks anything, but it
does generate warnings in the configure output.

Spack doesn't provide a really great way of handling this.  You can
see what I did for zlib: (1) add enable/disable to configure only when
the option exists, and (2) add a quick note about version to the
variant description.

Also, you added a variant `components`, but I don't see where anything
acts on it.

I'm a bit concerned about the `debug-frame` variant.  But default
inside libunwind, they use this in aarch64 but not on x86 or ppc.  I'm
concerned that by pushing this to the spack level, you've made it the
same across all platforms.  In this case, disabling it for aarch64.

I'll need to check into what affect this has.  I kinda recall that you
do want this for aarch64 but not x86_64, or maybe it was powerpc64.
We may need to set the default from python platform.

----------

Also, please alphabetize the variants.  You could put docs, tests,
libs, pic in one group (and alphabetize those), and then all the rest
incuding xz and zlib in another group that is separately alphabetized.

And then alphabetize the enable_or_disable options.

**Review by mwkrentel — CHANGES_REQUESTED** [review]
see previous comment

**Comment by iarspider** [comment]
@mwkrentel thanks for the review.

The kwarg was renamed to `variant` in https://github.com/spack/spack/pull/26064.

The patch is needed for aarch64 and ppc64le platforms, and tested by CMS experiment.

I will address the remaining comments in a follow-up commit.

**Comment by mwkrentel** [comment]
> The kwarg was renamed to variant in #26064.

Ok, in that case, could you rebase your PR to something after that commit?

> The patch is needed for aarch64 and ppc64le platforms, and tested by CMS experiment.

Really?  I build on aarch64 and ppc64le with gcc all the time.

There are two things in the patch: (1) dropping the last comma in an enum,
and (2) changing libdir from lib64 to lib on ppc.

Which of these actually fail?  There's tons of code that does (1), so
it's hard to believe that all of it is broken.  So, that looks more
like a style change than anything else.

(2) should be fixable in spack by proper searching for libraries (I
think, I'd have to check on exactly the way spack does this).

But note: patching configure.ac won't do anything for version 1.5.0
because the released tar files contain the autotool generated files
and don't run autoreconf.  This will only have any affect for the head
of a branch.

Btw, I'd be willing to deprecate 1.1 (from Oct 2012), if you'd like.

**Review by mwkrentel — APPROVED** [review]
Ok, I approve.

@iarspider, I'm still curious if you want to add all the options
because you plan to use them or just out of principle.

Note: I'm not a spack developer, so you'll have to ping someone with
commit access to merge the PR.

There is one small thing, I don't know if it matters.  For all the
other options, the spack default is the same as the autotools default,
which is good.  But for `debug_frame`, the autotools default depends
on the platform: on for arm/aarch64 and off everywhere else.  So, no
single value matches autotools everywhere, but you could match the
autotools behavior with:

```
variant('debug_frame', default=(platform.machine() == 'aarch64' or
                                platform.machine() == 'arm'), ...)
```

I tried a few tests, running it the opposite of the autotools default,
but nothing bad happened, so I don't know if it really matters.

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@spackbot run pipeline

**Comment by iarspider** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]
@mwkrentel is approving and he maintains `hpctoolkit` which is affected by this change so fine with me too :laughing:

**Comment by mwkrentel** [comment]
@alalazo This PR merely exposes the autotools config options as spack
variants.  The spack defaults are all the same as the AT defaults
except for `debug_frame` on ARM (the AT default depends on platform).

Yes, we use this for hpctoolkit.  I tried a few simple examples and
couldn't find anything that broke.  But if the ARM default becomes a
problem, we can fix it as I described above.  Plus, it's just the
default.

**Pull request merged**
