### PR TITLE
zlib-ng: add v2.1.4

### PR DESCRIPTION
**Pull request by haampie**
Let's drop the many patches in the next spack release

### CODE REVIEW

**Comment by michaelkuhn** [comment]
Any reason for actually dropping the patches? In case someone wants to build 2.1.3 for archaeological reasons, it will fail, right?

**Comment by haampie** [comment]
Hm, I don't really see the point of having 2.1.3 + a thousand lines of patches, if it is more or less identical to 2.1.4.

**Comment by haampie** [comment]
Ok, I'll do it properly: keep the patches, deprecated the older patch releases, remove them + patches after Spack 0.21 release.

**Review by michaelkuhn — APPROVED** [review]
LGTM

**Pull request merged**
