### PR TITLE
Add HPX 1.7.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by albestro — DISMISSED** [review]
LGTM

**Review by teonnik — DISMISSED** [review]

**Comment by albestro** [comment]
@msimberg do we want to add here also the conflict with gcc? https://github.com/STEllAR-GROUP/hpx/issues/5442

Maybe just the conflict now, and when there will be the new boost release we can add the correct requirement.

Otherwise ignore this and we will manage it later. As you prefer.

**Comment by msimberg** [comment]
> @msimberg do we want to add here also the conflict with gcc? [STEllAR-GROUP/hpx#5442](https://github.com/STEllAR-GROUP/hpx/issues/5442)
> 
> Maybe just the conflict now, and when there will be the new boost release we can add the correct requirement.
> 
> Otherwise ignore this and we will manage it later. As you prefer.

That sounds like a good idea. However, I've no idea how to express that. What we seem to want is "don't allow building on macos with gcc and boost < 1.77". Would something like this work:
```
    if sys.platform == 'darwin':
        conflicts('%gcc', when='^boost@:1.76', msg='...')
```
? Then again, maybe this should be in the boost recipe, not the hpx one?

**Comment by albestro** [comment]
> ? Then again, maybe this should be in the boost recipe, not the hpx one?

Oh yeah, that's true, it is a boost thing! so, this is ready to be merged ;)

**Comment by albestro** [comment]
@haampie do you have any idea why it is failing the CI?
```
py-setuptools-rust requires py-setuptools-scm variant +toml, but spec asked for ~toml
```

**Comment by eschnett** [comment]
@albestro I assume Spack's concretizer isn't clever enough to satisfy all constraints automatically. The solution is typically to add `py-setuptools-scm +toml` as dependency, or to add `+toml` to if `py-setuptools-scm` is already a dependency.

**Comment by msimberg** [comment]
It'd be nice if one of the core spack developers could comment here. The failure comes from a `spack ci` command (https://gitlab.spack.io/spack/spack/-/jobs/586369#L5716), and it's not clear if and why HPX should have a `py-setuptools-scm +toml` dependency, or if some other package needs it added?

**Comment by haampie** [comment]
@spackbot re-run pipeline

**Comment by haampie** [comment]
Maybe it's trying to build unrelated things which should be fixed in the meantime. Pinging @zackgalbreath / @scottwittenburg, since it seems we're better off with the new concretizer in CI.

Edit: nope. See also https://github.com/spack/spack/pull/24900#issuecomment-880784997

**Comment by haampie** [comment]
I have taken the liberty to rebase, which should make the gitlab pipelines happy.

**Review by haampie — APPROVED** [review]

**Pull request merged**
