### PR TITLE
gettext %nvhpc: constrain patch to @:0.21.0

### PR DESCRIPTION
**Pull request by eugeneswalker**
`gettext %nvhpc`: restrict `nvhpc-builtin.patch` to `gettext@:0.21.0`
* patch is rejected for `gettext@0.21.1` and doesn't seem necessary for build to succeed w/ `%nvhpc`

Perhaps I should also add a lower bound too. I would have to find out what versions this patch doesn't apply to. 

@samcmill @michaelkuhn @wspear

### CODE REVIEW

**Review by michaelkuhn — DISMISSED** [review]
Thanks! Sorry I didn't catch this while adding 0.21.1.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline because of multiple failures unrelated to this PR

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
Pipeline job failures seem unrelated to the content of this PR. For instance:
* https://gitlab.spack.io/spack/spack/-/jobs/3952751/raw
* missing dependency binaries in the cache for jobs that expect them to exist
```
...
==> [2022-10-25-07:02:03.796820] Acquiring a write lock on openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak with timeout 1.000ns
==> [2022-10-25-07:02:03.797045] openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak is now write locked
==> [2022-10-25-07:02:03.805229] Creating stage lock spack-stage-openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak
==> [2022-10-25-07:02:03.808922] Searching for binary cache of openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak
==> [2022-10-25-07:02:03.809292] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2022-10-25-07:02:03.910805] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2022-10-25-07:02:10.652911] Error: No binary for openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak found when cache-only specified
==> [2022-10-25-07:02:10.666158] Flagging openssl-1.1.1q-nkfsdb65z4lwxnix6hfkvh5kpypjfkak as failed: 1
...
```

Unfortunately, this is a known issue right now. I'm not sure what the solution is or will be. Not sure if re-trying the pipeline will do any good.

**Comment by eugeneswalker** [comment]
@spackbut run pipeline because of failures unrelated to the content of this PR

**Comment by eugeneswalker** [comment]
Build pipeline is failing because of specs known to be broken on `develop` for `e4s-oneapi` stack. Will monitor this and shepherd across the finish line as needed.

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by michaelkuhn — APPROVED** [review]
Still LGTM

**Pull request merged**
