### PR TITLE
xcrysden: new package

### PR DESCRIPTION
**Pull request by mikelhermiz**
I created the directory for the xcrysden package and its package.py file

### CODE REVIEW

**Comment by tldahlgren** [comment]
There have been two other attempts to add the package:  https://github.com/spack/spack/pull/29705 and https://github.com/spack/spack/pull/35814.  

@shahzebsiddiqui @germanne Thoughts on this PR?

**Review by bernhardkaindl — COMMENTED** [review]
sorry, forgot to rebase the checkout of the PR first to current develop

**Review by bernhardkaindl — COMMENTED** [review]
Auto-submitted build results on Ubuntu 22.04.4 LTS: (see disclaimer below)

### `xcrysden@1.6.3`:
```py
Command: bin/spack install -v --fail-fast xcrysden@1.6.3
[+] /usr (external glibc-2.35-spkgpfgkrsiezsjbgpao5m6ddj2hchhj)
[+] opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/gcc-runtime-13.1.0-25qo3ld7klulv5juopmjnk73qte743xz
==> Installing xcrysden-1.6.3-rc2-bin-shared-3yb7n2t65zcjlu2663z2qj3jauc4yidw [3/3]
==> No binary for xcrysden-1.6.3-rc2-bin-shared-3yb7n2t65zcjlu2663z2qj3jauc4yidw found: installing from source
==> Fetching http://www.xcrysden.org/download/xcrysden-1.6.3-rc2-bin-shared.tar.gz
==> No patches needed for xcrysden
==> xcrysden: Executing phase: 'install'
==> Error: TypeError: Xcrysden.install() takes 1 positional argument but 3 were given
See build log for details:
  .stage/spack-stage-xcrysden-1.6.3-rc2-bin-shared-3yb7n2t65zcjlu2663z2qj3jauc4yidw/spack-build-out.txt

==> Error: Terminating after first install failure: TypeError: Xcrysden.install() takes 1 positional argument but 3 were given

After the correct fix is pushed, to the PR branch and change the PR status to 'Ready for review'.

Generated and submitted by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -may -b xcrysden@1.6.3
```
This means an update of the installation function in the recipe is needed to accept 2 more arguments.

Tamara found (above):
> There have been two other attempts to add the package: #29705 and #35814.
> @shahzebsiddiqui @germanne Thoughts on this PR?

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
