### PR TITLE
acts,dd4hep: restrict to podio@0 to prevent failures with podio@1

### PR DESCRIPTION
**Pull request by wdconinc**
Podio-1.0 was [recently](https://github.com/spack/spack/pull/44780) added. This version is incompatible with all current versions of acts and dd4hep, at least due to its SameMajorVersion cmake version policy.

This PR restricts all acts and dd4hep versions, including master, to podio@0. When the next acts and dd4hep versions are released, they will likely have support for the podio-1.x releases.

### CODE REVIEW

**Comment by wdconinc** [comment]
Marking as draft since I'll just lump all other packages that are similarly affected into this PR.

**Comment by wdconinc** [comment]
Ready for review. This only affects acts and dd4hep. The other dependent of podio in the spack repository, edm4hep, does not specify a version in the CMakeLists.txt and will therefore continue to work with podio@1.

**Comment by wdconinc** [comment]
Could someone give this a review?

**Comment by jmcarcell** [comment]
Does this break building `dd4hep@<last commit>=develop` when depending on `podio` built with the most recent commit the same way? I think it may and we're using that for our nightly builds. Since master works fine for acts and DD4hep, why not stop the range at the current version of both?

**Comment by wdconinc** [comment]
I've added those limits. Good point.

I'll add acts@36 later too, and make sure to enable the new podio version requirement there. We'll just have to make sure to do so when dd4hep@1.30 is added too.

**Review by jmcarcell — APPROVED** [review]

**Comment by wdconinc** [comment]
@jmcarcell I simplified it quite a bit again, and tested that it works for the main and master versions of acts and dd4hep.

**Review by jmcarcell — APPROVED** [review]
Looks good

**Review by bernhardkaindl — APPROVED** [review]
@wdconinc: Approving due to the maintainer approval by @jmcarcell after all review.

**Pull request merged**
