### PR TITLE
Bugfix/python updates

### PR DESCRIPTION
**Pull request by paulhopkins**
This pull request adds:
  * Several new versions of Python including a switch in the preferred to 2.7.12
  * Changes in how the ucs4 variants configure arguments are applied

### CODE REVIEW

**Comment by adamjstewart** [comment]
Does 3.3: not have that option? Otherwise, looks good.

**Comment by citibeth** [comment]
My comments:

1. Please add something like:

```
elif spec.satisfies('@3.3:'):
    raise ValueError('+ucs4 variant not compatible with Python 3.3 and beyond')
```
Better yet... @tgamblin is it possible to say:

```
variant('ucs4', default=False, when='@3.3:', description='Enable UCS4 (wide) unicode strings')
```

This will avoid unnecessarily changing hashes on Python 3.3 and beyond.

2. Is there a web page somewhere explaining the UCS4 issue?  If so, it would be nice to put a link to it in a comment in the package.

**Comment by paulhopkins** [comment]
Hi Adam, Elizabeth,

From Python 3.3 the encoding for each string depends on the characters in
the string: see Pep 393 and https://docs.python.org/3.3/whatsnew/3.3.html.

I looked at the code for Variants and unlike depends_on and patch it does
not support the when keyword. I would be interested to know if it is worth
incorporating this in.

A quick search reveals this page on the Python c API:
https://docs.python.org/2/c-api/unicode.html

| ... Python’s default builds use a 16-bit type for Py_UNICODE and store
Unicode values internally as UCS2. It is also possible to build a UCS4
version of Python (most recent Linux distributions come with UCS4 builds of
Python). These builds then use a 32-bit type for Py_UNICODE and store
Unicode data internally as UCS4 ...
| ...Note that UCS2 and UCS4 Python builds are not binary compatible.
Please keep this in mind when writing extensions or interfaces....

I am open to suggestions about the best way to handle ucs4 for Python 3.3+.

**Comment by citibeth** [comment]
On Thu, Jul 7, 2016 at 5:13 PM, paulhopkins <notifications@github.com>
wrote:

> Hi Adam, Elizabeth,
>
> From Python 3.3 the encoding for each string depends on the characters in
> the string: see Pep 393 and https://docs.python.org/3.3/whatsnew/3.3.html.
>
> I looked at the code for Variants and unlike depends_on and patch it does
> not support the when keyword. I would be interested to know if it is worth
> incorporating this in.
>
> A quick search reveals this page on the Python c API:
> https://docs.python.org/2/c-api/unicode.html
>
> | ... Python’s default builds use a 16-bit type for Py_UNICODE and store
> Unicode values internally as UCS2. It is also possible to build a UCS4
> version of Python (most recent Linux distributions come with UCS4 builds of
> Python). These builds then use a 32-bit type for Py_UNICODE and store
> Unicode data internally as UCS4 ...
>

Can you add this kind of docs to the package in comments?

| ...Note that UCS2 and UCS4 Python builds are not binary compatible.
> Please keep this in mind when writing extensions or interfaces....
>

Extension packages can `depends_on('python@:2.8~ucs4')` or
`depends_on('python@:2.8+ucs4')` if that is an issue.

Glad this was standardized for Python3.  No need to have two incompatible
kinds of Python running around.


> I am open to suggestions about the best way to handle ucs4 for Python 3.3+.
>

Since the `variant` approach doesn't seem to be available, I'd just go with
the alternate:

```
elif spec.satisfies('@3.3:'):
    raise ValueError('+ucs4 variant not compatible with Python 3.3 and
beyond')
```

This will result in python@3.3 being turned into python@3.3~ucs4 and will
force a rebuild.  But once that's done, I don't expect it to cause any
further issues.

-- Elizabeth

**Comment by adamjstewart** [comment]
Looks good to me!

**Comment by citibeth** [comment]
Looks good to me too.

**Pull request merged**
