### PR TITLE
py-tensorflow: add v2.17.0

### PR DESCRIPTION
**Pull request by adamjstewart**
https://github.com/tensorflow/tensorflow/releases/tag/v2.17.0

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Well this is weird:
```
FileNotFoundError: [Errno 2] No such file or directory: 'patchelf'
```

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by tgamblin** [comment]
Can we add the ROCm version back to CI with this or should that be a separate PR?

**Review by tgamblin — APPROVED** [review]

**Comment by aweits** [comment]
I should note that this as it sits doesn't build for me currently, will have feedback soon.

**Comment by adamjstewart** [comment]
> Can we add the ROCm version back to CI with this or should that be a separate PR?

Separate PR (https://github.com/spack/spack/pull/45302), I want no part in debugging ROCm to try to get it working.

**Comment by adamjstewart** [comment]
> I should note that this as it sits doesn't build for me currently, will have feedback soon.

I should also note that I'm not even sure if TF 2.17 is being built in any of our pipelines because most use GCC and TF no longer supports GCC.

**Comment by adamjstewart** [comment]
Yep, definitely not tested, because the 2.17.0 build is broken. Let me see if I can quickly push a PR to fix it.

**Comment by aweits** [comment]
I got a successful install with this last nite:

```diff
diff --git a/var/spack/repos/builtin/packages/py-tensorflow/package.py b/var/spack/repos/builtin/packages/py-tensorflow/package.py
index 36d17f9f612..4df5b686a50 100644
--- a/var/spack/repos/builtin/packages/py-tensorflow/package.py
+++ b/var/spack/repos/builtin/packages/py-tensorflow/package.py
@@ -3,6 +3,7 @@
 #
 # SPDX-License-Identifier: (Apache-2.0 OR MIT)
 
+import glob
 import os
 import sys
 import tempfile
@@ -378,7 +379,7 @@ class PyTensorflow(Package, CudaPackage, ROCmPackage, PythonExtension):
 
     # https://www.tensorflow.org/install/source#tested_build_configurations
     # https://github.com/tensorflow/tensorflow/issues/70199
-    conflicts("%gcc", when="@2.17:")
+#    conflicts("%gcc", when="@2.17:")
     conflicts("%gcc@:9.3.0", when="@2.9:")
     conflicts("%gcc@:7.3.0")
 
@@ -705,6 +706,11 @@ def configure(self, spec, prefix):
     def post_configure_fixes(self):
         spec = self.spec
 
+        filter_file("patch_so(srcs_dir)",
+                    "pass",
+                    "tensorflow/tools/pip_package/build_pip_package.py",
+                    string=True)
+
         # make sure xla is actually turned off
         if spec.satisfies("~xla"):
             filter_file(
@@ -845,14 +851,23 @@ def build(self, spec, prefix):
 
         bazel(*args)
 
-        build_pip_package = Executable("bazel-bin/tensorflow/tools/pip_package/build_pip_package")
-        buildpath = join_path(self.stage.source_path, "spack-build")
-        build_pip_package("--src", buildpath)
+        if self.spec.satisfies("@:2.16"):
+            build_pip_package = Executable("bazel-bin/tensorflow/tools/pip_package/build_pip_package")
+            buildpath = join_path(self.stage.source_path, "spack-build")
+            build_pip_package("--src", buildpath)
 
     def install(self, spec, prefix):
         tmp_path = env["TEST_TMPDIR"]
-        buildpath = join_path(self.stage.source_path, "spack-build")
-        with working_dir(buildpath):
-            args = std_pip_args + ["--prefix=" + prefix, "."]
-            pip(*args)
+        if self.spec.satisfies("@2.17:"):
+            buildpath = join_path(self.stage.source_path, "bazel-out/k8-opt/bin/tensorflow/tools/pip_package/wheel_house/")
+            with working_dir(buildpath):
+                wheel = glob.glob("*.whl")[0]
+                args = std_pip_args + ["--prefix=" + prefix, wheel]
+                pip(*args)
+        else:
+            buildpath = join_path(self.stage.source_path, "spack-build")
+            with working_dir(buildpath):
+                args = std_pip_args + ["--prefix=" + prefix, "."]
+                pip(*args)
+
         remove_linked_tree(tmp_path)
```

**Comment by aweits** [comment]
gcc issue seems to only be present in gcc<12.

**Comment by adamjstewart** [comment]
Thanks for getting to this first. Want to open a PR?

**Pull request merged**
