### PR TITLE
Add recently added Spack Images on Docker Hub

### PR DESCRIPTION
**Pull request by panda1100**
This PR add recently added Spack Images on Docker Hub thanks to merged PR #36713 by @blue42u

### CODE REVIEW

**Comment by panda1100** [comment]
Hi @alecbcs -san,

"ci/unit-tests/ubuntu" failed, but it looks like error is irrelevant to my commit..
Any assistance is truly appreciated.

**Comment by panda1100** [comment]
Thank you for re-run CI!
Could someone please review this PR?
Or should I "Update with rebase" before review?

**Comment by alecbcs** [comment]
No worries! Definitely seen that test fail on other unrelated PRs before and it's probably something we should look into improving. 

No need to rebase. @alalazo This PR looks good to me but you're more familiar with the containers code and docs.

**Review by alalazo — APPROVED** [review]
Thanks!

**Review by alalazo — APPROVED** [review]
Thanks!

**Comment by panda1100** [comment]
Thank you @alecbcs -san!
Thank you @alalazo -san!

**Pull request merged**
