### PR TITLE
feature : finer locking of the db

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications
- [x] removed global db locks from `install`, `uninstall` and `diy`
- [x] added lock for stage directory (an exclusive lock is taken as part of the `Stage` context manager)
- [x] added lock for prefix directory (an exclusive lock is taken during `Package.do_install`)
- [x] debug output shows locks acquire and release

##### Install and uninstall are not mutually exclusive
This means that if : 
```
spack uninstall ...
``` 
is run concurrently with 
```
spack install ...
```
the former command may cause the latter to fail (the same way an administrator can `sudo rm ...` something that another admin is about to use)

##### Debug output shows acquire and release
```
$ spack -d install  python@3:
==> Reading config file /home/mculpo/.spack/compilers.yaml
==> TOUCH FILE : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2 [Acquiring]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2 [Released]
==> Installing python
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/bzip2-1.0.6-i6a7grcnt5wwn6i3rjh2al25ypwtlyhz [Acquiring]
==> bzip2 is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/bzip2-1.0.6-i6a7grcnt5wwn6i3rjh2al25ypwtlyhz
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/bzip2-1.0.6-i6a7grcnt5wwn6i3rjh2al25ypwtlyhz [Released]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/ncurses-6.0-faybomf54bbh376q54ztgfsrqxa7vavk [Acquiring]
==> ncurses is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/ncurses-6.0-faybomf54bbh376q54ztgfsrqxa7vavk
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/ncurses-6.0-faybomf54bbh376q54ztgfsrqxa7vavk [Released]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/zlib-1.2.8-rv427lhuk7qeq5fh67f36dxq3z22bpu4 [Acquiring]
==> zlib is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/zlib-1.2.8-rv427lhuk7qeq5fh67f36dxq3z22bpu4
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/zlib-1.2.8-rv427lhuk7qeq5fh67f36dxq3z22bpu4 [Released]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/openssl-1.0.2h-d7ykxud2ghnusqhwdzagnpx7inboix75 [Acquiring]
==> openssl is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/openssl-1.0.2h-d7ykxud2ghnusqhwdzagnpx7inboix75
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/openssl-1.0.2h-d7ykxud2ghnusqhwdzagnpx7inboix75 [Released]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/sqlite-3.8.5-5ivjx67knpt477vxen6p6xc73fdq22na [Acquiring]
==> sqlite is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/sqlite-3.8.5-5ivjx67knpt477vxen6p6xc73fdq22na
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/sqlite-3.8.5-5ivjx67knpt477vxen6p6xc73fdq22na [Released]
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/readline-6.3-ie3abif7kh64o7it4lntlcj2wkygqxvf [Acquiring]
==> readline is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/readline-6.3-ie3abif7kh64o7it4lntlcj2wkygqxvf
==> READ LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/readline-6.3-ie3abif7kh64o7it4lntlcj2wkygqxvf [Released]
==> Reading config file /home/mculpo/.spack/mirrors.yaml
==> Trying to fetch from file:///home/mculpo/production/spack-mirror/python/python-3.5.1.tgz
==> /usr/bin/curl -C - -o /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/python-3.5.1.tgz.part -f -D - -L file:///home/mculpo/production/spack-mirror/python/python-3.5.1.tgz -#
######################################################################## 100,0%
==> Staging archive: /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/python-3.5.1.tgz
==> /bin/tar -xf /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/python-3.5.1.tgz
==> Created stage in /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2
==> No patches needed for python
==> Building python
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2.lock [Acquiring]
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2 [Acquiring]
==> Installing /tmp/mculpo/spack-stage/spack-stage-_bO_kd/Python-3.5.1/spack-build.out to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/build.out
==> Installing /tmp/mculpo/spack-stage/spack-stage-_bO_kd/Python-3.5.1/spack-build.env to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/build.env
==> Installing /home/mculpo/PycharmProjects/spack/var/spack/repos/builtin/packages/python/package.py to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/python
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/bzip2-1.0.6-i6a7grcnt5wwn6i3rjh2al25ypwtlyhz/.spack/repos/builtin/packages/bzip2 to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/bzip2
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/ncurses-6.0-faybomf54bbh376q54ztgfsrqxa7vavk/.spack/repos/builtin/packages/ncurses to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/ncurses
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/openssl-1.0.2h-d7ykxud2ghnusqhwdzagnpx7inboix75/.spack/repos/builtin/packages/openssl to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/openssl
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/zlib-1.2.8-rv427lhuk7qeq5fh67f36dxq3z22bpu4/.spack/repos/builtin/packages/zlib to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/zlib
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/readline-6.3-ie3abif7kh64o7it4lntlcj2wkygqxvf/.spack/repos/builtin/packages/readline to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/readline
==> Installing /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/sqlite-3.8.5-5ivjx67knpt477vxen6p6xc73fdq22na/.spack/repos/builtin/packages/sqlite to /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/.spack/repos/builtin/packages/sqlite
==> Warning: Patched overly long shebang in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/bin/idle3.5
==> Warning: Patched overly long shebang in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/bin/pyvenv-3.5
==> Warning: Patched overly long shebang in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/bin/pydoc3.5
==> Warning: Patched overly long shebang in /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2/bin/2to3-3.5
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/.locks/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2 [Released]
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/var/spack/stage/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2.lock [Released]
==> Successfully installed python
  Fetch: 0.06s.  Build: 2m 33.03s.  Total: 2m 33.08s.
[+] /home/mculpo/PycharmProjects/spack/opt/spack/linux-x86_64/gcc-6.1.0/python-3.5.1-wxwrgojeiacr4ckh3jnrqrsi4o5a7jg2
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/.spack-db/lock [Acquiring]
==> WRITE LOCK : /home/mculpo/PycharmProjects/spack/opt/spack/.spack-db/lock [Released]
```

---------

@tgamblin @adamjstewart @hegner As we need this with high priority, and there's much request for this feature (see #636), I thought it was better to share what I am doing early in the development to avoid duplicate work.

### CODE REVIEW

**Comment by citibeth** [comment]
I worry whenever I see locking schemes.  One global lock is inefficient and annoying, but at least we all understand it.  When you go beyond that, it's easy to add a lock here, add a lock there and end up with a system that mostly works... except for the occasional deadlock or maybe race condition.

For that reason, I would want to see a cogent description of how this new locking scheme works (in DOCUMENTATION).  And there needs to be some kind of reasoning that the locking is correct, that it can't deadlock, etc.  Not only will this convince everybody that the current PR is correct --- it will also help some future author who needs to do more stuff with locking later on.

PS: I once worked at a trading firm where our software was full of locks put in through that process.  The software ran slowly, nearly in deadlock state.  A few locks were removed and it ran faster.  Should we have been worried of a race condition?  It's anybody's guess, the system was too hard to understand.  It was replaced by a system based on threads and queues (Erlang-style), which was much faster and more reliable.

**Comment by adamjstewart** [comment]
I agree that more locks can cause more confusion, but in this case more locks are definitely necessary. Right now, I can't even run `spack find` while a `spack install` is running. I envision a future in which multiple users can simultaneously install their own software in their home directories using a global Spack installation. To do this, Spack must have finer locking control.

But yeah, some kind of documentation would be cool eventually. To be fair, most of the nitty gritty inner workings of Spack aren't currently documented. If we documented _everything_, we would never actually get anything done, and the documentation would be ten times longer than the code.

@alalazo: How is this PR related to #843? It feels like you and @hegner split off from #636 in different directions.

**Comment by citibeth** [comment]
In an ideal work, synchronization and "business logic" should be kept
separate.  The docs would need to document just the synchronization
strategy.  It would need to be high level, something like:

Spack implements a multi-read lock and a single-write lock on each
> package.  If one process holds a write lock, the no readlocks can be
> acquired.  If one or more processes holds a read lock, then no write locks
> can be acquired.



> Each Spack command operates in three phases: (1) Acquire all necessary
> locks, (2) Execute the command, (3) Release all locks.  Lock acquisition in
> step 1 is atomic: a single request is made for all locks the Spack command
> will need to complete its job, and that request either succeeds, waits
> until it can proceed, or fails.  This strategy ensures that Spack is
> deadlock-free, eliminating the need for deadlock detection or breaking.


The following locks are acquired by each Spack command:

install: write

uninstall: write (must also figure out how locks work when packages
> disappear)

find: ???


Now that I'm thinking it through a bit more... I don't know the specifics
of these Spack internals.  But I see some red flags that could lead to
deadlock or race conditions:

1. Lock acquisition should be at the top level, not buried inside of
`Stage` and `Package.prefix`.  Not only can this deadlock; **it violates
the principle of not mixing synchronization with business logic.**  It
makes it MUCH harder to understand how locking works in the future.  I
would stick with the three-phase structure outlined above, or something
similar to it.  Keep the locking at the outer level, and then we don't have
to worry about how locking works once you get inside the guts of the
command.

I would STRONGLY advise that locking be moved to a more orderly three-phase
system before this PR is committed.

2. Judging from the code, I don't think much thought has gone into what
happens if you're reading the DB while someone else is writing it.  This
could lead to race conditions on the reading side.

Other possible concern... I see that this uses file locking.  How do such
locks work on a network filesystem (probably not well, if more than one
machine is accessing the Spack DB).  Windows filesystems are also
notoriously evil, for locking things up and not unlocking them, and
generally deadlocking you.  In my experience, the only good network-safe
locking system I've used is Zookeeper.

Not that you want to require a Zookeeper installation for use of Spack.
But you SHOULD abstract away HOW locks are implemented from the rest of
Spack.  Also... it's fine to identify locks by the names of folders on
disk.  But don't ASSUME that locks ARE files.  Because sometimes they will
not be.

What's a good use case for this... suppose I have a cluster with 100 and a
Spack software stack of 100 packages.  I need to build those 100 packages
in 4 combinations.  With a solid concurrency control foundation in place,
Spack should be able to spawn batch jobs for each build, and to do them in
a way to maximize concurrency.  And even as 50 builds are hitting the Spack
DB simultaneously, Spack USERS should expect `spack find`, `spack
location`, to continue to work in a correct, predictable manner.

**Comment by alalazo** [comment]
@adamjstewart 

> How is this PR related to #843? It feels like you and @hegner split off from #636 in different directions.

Right now `spack install ...` is a single-threaded process that :
 1. acquires an exclusive file lock on the installed DB
 1. manipulates a dependency DAG (it installs nodes following a topological ordering)
 1. release the lock at the end of the command

Before installing a single spec the root process forks (to maintain a clean environment for the next installation) and wait for the child to complete. The fact that the DB is under an exclusive lock for the entire installation process is what prevents other users to run commands in the meanwhile.

@hegner in #843 made the single-threaded root process a multi-threaded process. The DAG is still visited following a topological order, but more than one node can be processed at one time (i.e. more than one installation is started concurrently). This seems to give speed-ups because the serial parts of different installations are done concurrently *for the single user*. Still only one install command can run at one time.

This PR tries to tackle the problem from an orthogonal perspective. You don't need to block the DB for everybody for the entire duration of the command. The write lock is acquired only when you need to update the DB after a successful installation, and released immediately afterwards. As the locking is finer, I took care of adding two other locks (on the stage and prefix directory) to prevent concurrent installations of the same spec from different users. The result is that an installation is still single-threaded, but multiple users can query the DB concurrently.

**Comment by adamjstewart** [comment]
@alalazo: Thanks for the clarification! I'll be excited to see both of these PR's merged, although yours probably impacts me more.

**Comment by alalazo** [comment]
@tgamblin Can you please take a look at 6856d7d ? The variable assignment there is weird and I don't really get what the conditional is for (it was something signaled by the `flake8` check)

**Comment by trws** [comment]
So... This seems to have been sitting for quite some time.  Status?

**Comment by tgamblin** [comment]
@trws: needs review, but seems relevant to #1266, actually.

**Comment by trws** [comment]
Nothing obvious is jumping out at me, but a merge/rebase is certainly in order.  Any chance you could take a look @alalazo?

**Comment by tgamblin** [comment]
@trws @alalazo: I rebased this on `develop` -- will be pushing a new PR soon.

**Comment by alalazo** [comment]
@tgamblin Thanks. Feel free to close this PR as soon as the new one will be pushed (or just notify me and I will do that)

**Comment by tgamblin** [comment]
@alalazo: ok the branch is `features/db-locking` (sorry it's only different by a dash) din the main git repo.  I think rather than opening a new PR, you could just replace your branch in `epfl-scitas` with the new one, and force push it here, to keep the discussion and comments.

Everything seems to be working except the `cmd.module` test.  I can't seem to figure out why I get this error:

```
======================================================================
FAIL: test_module_common_operations (spack.test.cmd.module.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gamblin2/src/spack/lib/spack/spack/test/cmd/module.py", line 52, in test_module_common_operations
    self.assertTrue(os.path.exists(item))
AssertionError: False is not true
```

Do you know why that would happen?  It works on `develop`.

**Comment by alalazo** [comment]
@tgamblin I'll try to have a look at it asap, not sure if I can make it today

**Comment by tgamblin** [comment]
@alalazo: nevermind -- I found it.  whitespace error in `package.py`.  New version of branch should be good to force push here.

**Comment by tgamblin** [comment]
I've rebased and reopened this as #1562 -- let's continue to work on it there.

**Comment by alalazo** [comment]
@tgamblin Have there been problems with the push force I did here ?

**Comment by tgamblin** [comment]
@alalazo: Sorry -- I didn't notice the push (ugh -- github doesn't notify me).

I've actually continued working on the commits (fixed a bug) so let's go with the version in #1562.

**Pull request closed without merging**
