### PR TITLE
hdf5: Add missing "close" statement

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Has this patch been submitted upstream? Does the patch apply to all versions of HDF5?

**Review by brtnfld — DISMISSED** [review]
lgtm

**Comment by eschnett** [comment]
Yes, I submitted a ticket with a patch https://github.com/HDFGroup/hdf5/issues/1157 . I do not know to which versions of HDF5 this applies, but the ticket is still open.

**Comment by adamjstewart** [comment]
> I do not know to which versions of HDF5 this applies

You can test this with `spack patch hdf5@X.Y.Z`. If the patch doesn't work for all versions, you should specify which version it is for using `when='@X.Y.Z:'`. Otherwise, all older versions will be broken.

**Comment by eschnett** [comment]
I added a version specification.

**Review by adamjstewart — APPROVED** [review]

**Comment by eschnett** [comment]
*ping* this package is ready to be merged.

**Review by hyoklee — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Comment by sethrj** [comment]
FWIW changing the patch to only apply to 1.10.7 caused me at least an hour of headache when I tried to install 1.10.8. Shouldn't we be applying patches to an open-ended version range if we don't know when it's patched?

**Comment by eschnett** [comment]
I tried that first, but it's patched in 1.12 if I recall correctly, and so I got careful. Too careful it seems – apologies.

**Pull request merged**
