### PR TITLE
feynhiggs: Update url

### PR DESCRIPTION
**Pull request by haralmha**
The old url leads to a fetch error.

### CODE REVIEW

**Comment by vvolkl** [comment]
Thanks! The LCG releases still use 2.10.2, can you add that version as well? (If it builds correctly)

**Comment by haralmha** [comment]
Yes, but I need the ignore_whitespace option for patching it, which is yet to be reviewed: https://github.com/spack/spack/pull/31674

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
There's a conflict to be solved here

**Comment by alalazo** [comment]
@spackbot fix style

**Review by alalazo — APPROVED** [review]

**Pull request merged**
