### PR TITLE
Docker: spack/ubuntu 20.04 container recipe

### PR DESCRIPTION
**Pull request by wdconinc**
In addition to https://hub.docker.com/r/spack/ubuntu-bionic this provides an ubuntu 20.04 container recipe. I'm not suggesting that this actually gets populated on docker hub, but merely providing the recipe for those who wish to build a spack base container themselves may be useful. 

The ubuntu-1804 workaround for lua-posix is not necessary anymore in ubuntu-2004.

[Commit history refers to tutorial updates due to having originally been branched off releases/v0.16.]

### CODE REVIEW

**Comment by alalazo** [comment]
Duplicate of #19991

**Comment by wdconinc** [comment]
The original pr reporter doesn't seem to be responding to requested changes. I don't have permissions to contribute to their branch either. How do we move this forward?

**Comment by alalazo** [comment]
@wdconinc I think #21910 may also serve the same purpose as this PR. With a properly set environment:
```console
$ spack containerize --last-stage=bootstrap
```
Let me check if there are differences among the recipes that get generated.

**Comment by vsoch** [comment]
Ping ping ping ping! Any updates? I'd really appreciate a 20.04 container!

**Comment by alalazo** [comment]
@vsoch #21910 is waiting for review since a while. It adds among other things a few new base images (centos:8, amazonlinux:2, ubuntu:20.04, alpine:3, cuda:11.2.1) that can be used out of the box.

**Pull request closed without merging**
