### PR TITLE
[root] fix cmake args for r variant

### LINKED ISSUE #17390: Installation issue: root+r builds with -Dr=OFF
@chissg @HadrienG2 @drbenmorgan `spack install root+r`  does not actually build root with `-Dr=ON`. Not sure if it is a dependency issue or concerns the logic in the recipe. I think this should be easily reproducible, but let me know if you need more details on the configuration

### PR DESCRIPTION
**Pull request by vvolkl**
@HadrienG2 @chissg @drbenmorgan 
 Fixes #17390

### CODE REVIEW

**Review by drbenmorgan — APPROVED** [review]
Fine for me assuming tests pass (and they should!!), thanks @vvolkl!

**Comment by vvolkl** [comment]
@drbenmorgan installing on a few further machines uncovered a dependency on `readline` that was  missing:
https://github.com/root-project/root/blob/master/bindings/r/CMakeLists.txt#L49
I'm adding the dependency here, but I couldn't get root to build with the spack-installed readline, I had to install the system package.
This could be the fault of the root cmake configuration, which just adds `-lreadline` without trying to find the package.

**Comment by HadrienG2** [comment]
@vvolkl Is ROOT failing to find the readline headers specifically?

If so, you just stepped on my favorite hornet nest in the root spackage, just as I'm investigating whether we can finally get rid of it: https://github.com/spack/spack/pull/17459 .

While I'm figuring this out, you will want to add your own include path hack to the `setup_build_environment` method...

**Comment by vvolkl** [comment]
@HadrienG2 no, the readline headers are not actually used by root, it ... calls readline by `extern "C"` via R? Not sure what's going on here: https://github.com/root-project/root/blob/master/bindings/r/src/TRCompletion.h
It's strange, because if that is the case, I don't see why the spack-installed readline is not working.

**Comment by HadrienG2** [comment]
Can you post an example of a compiler/linker error? It might help me or someone else understand what's going on.

**Review by adamjstewart — APPROVED** [review]
Is this safe to merge or is this PR still a work-in-progress?

**Comment by vvolkl** [comment]
Hi @adamjstewart, it's safe to merge I think, since it fixes this variant. We can continue discussing he build failure with non-existing system readline in an issue.

**Pull request merged**
