### PR TITLE
Add version 5.15.2 for PyQt5

### PR DESCRIPTION
**Pull request by mwm126**

### CODE REVIEW

**Comment by adamjstewart** [comment]
The version you're trying to add does not exist at that URL:
```console
$ spack checksum py-pyqt5 5.15.2
==> Found 1 version of py-pyqt5:
  
  5.15.2  https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.15.2/PyQt5_gpl-5.15.2.tar.gz

==> Something failed on https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.15.2/PyQt5_gpl-5.15.2.tar.gz, skipping.  (All fetchers failed)
==> Error: Could not fetch any versions for py-pyqt5
```

**Comment by tldahlgren** [comment]
> The version you're trying to add does not exist at that URL:
> 
> ```
> $ spack checksum py-pyqt5 5.15.2
> ==> Found 1 version of py-pyqt5:
>   
>   5.15.2  https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.15.2/PyQt5_gpl-5.15.2.tar.gz
> 
> ==> Something failed on https://www.riverbankcomputing.com/static/Downloads/PyQt5/5.15.2/PyQt5_gpl-5.15.2.tar.gz, skipping.  (All fetchers failed)
> ==> Error: Could not fetch any versions for py-pyqt5
> ```

I had the same problem.  There is documentation on the site for the version but, from https://www.riverbankcomputing.com/software/pyqt/download, it looks like a `5.15.3` dev version is accessible.

**Comment by adamjstewart** [comment]
@Sinan81 was going to take a look at updating the PyQt packages to use the PythonPackage build system. It may be possible to download them from PyPI instead which would be more reliable.

**Comment by alalazo** [comment]
Closing as stale, but feel free to reopen if you want to continue the discussion.

**Comment by Sinan81** [comment]
sorry for the late reply. old pyqt packages can be obtained from internet archive's wayback machine. If Spack has a source tar file cache available on the internet, it would be nice to put these older tar files there.

**Comment by adamjstewart** [comment]
#32696 also updates this package with the latest version.

**Pull request closed without merging**
