### PR TITLE
Patch directive doesn't expand non-allowed archives

### PR DESCRIPTION
**Pull request by alalazo**
As required by #4907, patch directive now doesn't try to expand non-allowed archives. Unit tests included.

### CODE REVIEW

**Comment by tgamblin** [comment]
@alalazo: I saw the `qmcpack` PR but why do we need `expand=False` here?  Why not just have the patch fetcher *only* expand patches if `spack.util.compression.allowed_archive(path_to_patch)` is true?

I'm trying to remember why we don't do that for regular archives, as well and wondering whether we should.  With regular archives it's a bit more complicated in that whether you expand the archive determines what directory you're in when `install()` begins.  

For patches, though, there's only one file we care about and we can just assume the downloaded thing *is* the patch if it's not a known archive.

Thoughts?

**Comment by alalazo** [comment]
@tgamblin I'll have a look at this one first thing tomorrow.

**Comment by alalazo** [comment]
There's a unit test for uncompressed patches, but I didn't try it out manually on a real package. Maybe @naromero77 or @wscullin should test it still works with #4907 before merging?

**Comment by naromero77** [comment]
@alalazo I tested it with #4907 and it works.

**Pull request merged**
