### PR TITLE
ratel - add version 0.2.1

### PR DESCRIPTION
**Pull request by jeremylt**

### CODE REVIEW

**Comment by jeremylt** [comment]
Irritatingly

```
$ spack install --test root --verbose --show-log-on-error  ratel@develop
```

vomits out 
```
==> Testing package ratel-develop-4kzzubc
==> [2023-01-11-16:45:46.863695] Running build-time tests
==> [2023-01-11-16:45:46.863841] RUN-TESTS: build-time tests [check]
```

followed by 
```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'prove' 'V=1' 'PROVE_OPTS=-v' 'CEED_DIR=/projects/jeremy/spack/opt/spack/linux-debiann-zen2/gcc-12.2.0/libceed-develop-vrbs4jqejom6ynbigfcjtcbcxgdsoqgb' 'PETSC_DIR=/projects/jeremy/spack/opt/spack/linux-debiann-zen2/gcc-12.2.0/petsc-main-ggtal6dr5kad4cqn2v54ktubxo57sm7h'
```

but it utterly fails to provide the verbose log from `make prove`

```
See build log for details:
  /tmp/jeth8984/spack-stage/spack-stage-ratel-develop-4kzzubctpefetzdl2ojnnivuwzvlnvra/spack-build-out.txt
```
is a lie - zero details from `make prove` are there

**Comment by jeremylt** [comment]
ah, running manually
```
[0]PETSC ERROR: No grid generator of dimension 3 registered You may need to add --download-ctetgen or --download-tetgen in your ./configure options
```

**Comment by jeremylt** [comment]
Perhaps Ratel should make those tests optional - I don't think we need to mandate `ctetgen`

**Review by tldahlgren — DISMISSED** [review]
Confirmed the tag exists.

**Comment by tldahlgren** [comment]
Deferring merge decision to give @jedbrown a chance to commit.

**Comment by jeremylt** [comment]
Updated to v0.2.1 which makes tets optional in the test suite per @jedbrown and I's conversation offline.

Now
```
$ spack install --test root --verbose  ratel@develop
```
works fine in my testing

**Review by jedbrown — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
