### PR TITLE
[darshan-runtime, darshan-util, py-darshan]: darshan 3.4.1 release updates

### PR DESCRIPTION
**Pull request by shanedsnyder**
* new package versions for darshan-runtime, darshan-util, and py-darshan
* added new 'parallel-netcdf' variant to darshan-runtime to enable support for PnetCDF instrumentation available as part of Darshan 3.4.1 release

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Review by carns — DISMISSED** [review]

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
There seems to be legitimate failures here https://gitlab.spack.io/spack/spack/-/pipelines/232041

**Comment by shanedsnyder** [comment]
> There seems to be legitimate failures here https://gitlab.spack.io/spack/spack/-/pipelines/232041

The failures that I quickly scanned should be fixed by PR #34245. Our tests are expecting a file that is no longer available in new versions of Darshan.

**Review by jeanbez — DISMISSED** [review]

**Comment by jeanbez** [comment]
@spackbot run pipeline

**Comment by carns** [comment]
I think the PR needs to be rebased to pick up the (now merged) change from that other PR before the CI will pass?

**Comment by jeanbez** [comment]
@shanedsnyder could you do that?

**Comment by shanedsnyder** [comment]
@jeanbez Done

**Comment by shanedsnyder** [comment]
@spackbot fix style

**Review by carns — APPROVED** [review]

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Review by jeanbez — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
