### PR TITLE
ROOT: add math/gsl conflict and change version-dependent features to conditional variants

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Comment by sethrj** [comment]
@spackbot fix style

**Comment by drbenmorgan** [comment]
I think this is fine, and along the same lines as #34185 though addressing different variants. So I'm fine with the changes here, though @HadrienG2 and @vvolkl should have final say!

**Review by HadrienG2 — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by sethrj** [comment]
@spackbot run pipeline

**Pull request merged**
