### PR TITLE
ASP-based solver: prevent the use of hashes that are not available

### LINKED ISSUE #32348: ASP-based solver: KeyError on spec construction
### Steps to reproduce

The error has been reported on Slack by @blue42u (on buildcaches) and @adamjstewart (on a local store). The steps to reproduce on a buildcache are:
```console
$ spack mirror add tmp-pr s3://spack-binaries-prs/pr31598_hpctoolkit-stack
$ spack -d spec autoconf
```

### Error message

```
==> [2022-08-24-06:55:05.094657] Imported spec from built-in commands
==> [2022-08-24-06:55:05.095964] Imported spec from built-in commands
==> [2022-08-24-06:55:05.097379] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2022-08-24-06:55:05.114014] Reading config file /home/culpo/.spack/config.yaml
==> [2022-08-24-06:55:05.114366] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-08-24-06:55:05.123078] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2022-08-24-06:55:05.135667] Reading config file /home/culpo/.spack/config.yaml
==> [2022-08-24-06:55:05.136020] DATABASE LOCK TIMEOUT: 3s
==> [2022-08-24-06:55:05.136071] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-08-24-06:55:05.136525] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-08-24-06:55:05.141792] DATABASE LOCK TIMEOUT: 3s
==> [2022-08-24-06:55:05.141832] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-08-24-06:55:05.141882] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-08-24-06:55:05.142169] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/culpo/PycharmProjects/spack/etc/spack/defaults
==> [2022-08-24-06:55:05.142198] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/culpo/PycharmProjects/spack/etc/spack/defaults/linux
==> [2022-08-24-06:55:05.142221] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/culpo/.spack/bootstrap/config
==> [2022-08-24-06:55:05.142245] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/culpo/.spack/bootstrap/config/linux
==> [2022-08-24-06:55:05.142459] Reading config file /home/culpo/.spack/bootstrap/config/linux/compilers.yaml
==> [2022-08-24-06:55:05.176990] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2022-08-24-06:55:05.177070] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-08-24-06:55:05.177279] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-08-24-06:55:05.293748] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2022-08-24-06:55:05.345674] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.8 /shqedxgvjnhiwdcdrvjhbd73jaevv7wt" provides the "clingo" Python module
==> [2022-08-24-06:55:05.345934] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/concretizer.yaml
==> [2022-08-24-06:55:05.349508] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2022-08-24-06:55:05.350756] Reading config file /home/culpo/.spack/repos.yaml
==> [2022-08-24-06:55:05.374774] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2022-08-24-06:55:05.387145] Reading config file /home/culpo/.spack/config.yaml
==> [2022-08-24-06:55:05.387763] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/mirrors.yaml
==> [2022-08-24-06:55:05.388972] Reading config file /home/culpo/.spack/mirrors.yaml
==> [2022-08-24-06:55:10.157338] Cached index for s3://spack-binaries-prs/pr31598_hpctoolkit-stack already up to date
==> [2022-08-24-06:55:10.891502] DATABASE LOCK TIMEOUT: 3s
==> [2022-08-24-06:55:10.891628] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-08-24-06:55:12.690787] Reading config file /home/culpo/.spack/linux/compilers.yaml
==> [2022-08-24-06:55:12.715401] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2924, in concretize
    self._new_concretize(tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2899, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 2318, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 695, in solve
    answers = builder.build_specs(tuples)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 2177, in build_specs
    action(*args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/solver/asp.py", line 1984, in hash
    self._specs[pkg] = self._hash_lookup[h]
KeyError: 'tg6ojo7ktvgvnlna557wf7sbdg4zz45x'
```

### Information on your system

* **Spack:** 0.19.0.dev0 (af4788fdefd156efdb9ce7ffbeb57c8f73898e43)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes #32348

### CODE REVIEW

**Comment by alalazo** [comment]
I struggle to find a simple synthetic reproducer, so not sure at the moment how to add a regression test.

**Comment by alalazo** [comment]
@adamjstewart @blue42u Can you check if this works for you?

**Comment by blue42u** [comment]
@alalazo This solves the issue for me. Thanks!

**Comment by adamjstewart** [comment]
Will try to test tonight

**Review by adamjstewart — APPROVED** [review]
Can confirm that this solves my issue.

**Comment by alalazo** [comment]
@adamjstewart Do you remember how did you end up with a local store missing some specs? Wondering if it is a common use case.

**Comment by adamjstewart** [comment]
No idea

**Pull request merged**
