### PR TITLE
e4s oneapi ci: add catalyst build

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `catalyst` to E4S OneAPI CI stack

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
LGTM.

**Comment by tldahlgren** [comment]
The pipeline failed due to 3 jobs with runner failures.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
Closing this per comment here: https://github.com/spack/spack/pull/32483#issuecomment-1234736065

**Pull request closed without merging**
