### PR TITLE
petsc: run a test

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by tgamblin** [comment]
@davydden: is this ready to merge?

**Comment by davydden** [comment]
@tgamblin should be good now.

**Comment by nrichart** [comment]
This breaks petsc. The test is a mpi code run in sequential on our site we have `mvapich2+slurm` if you do not run with `srun` it fails.
And no wrapper `mpirun` is installed when using `+slurm` so just adding `mpirun` will not solve it.

**Comment by davydden** [comment]
@nrichart i will check the example file and if needed switch to another one.

However, the fact that you was not able to run it with MPI in my opinion indicates a bigger issue, not related to petsc per-se.

**Comment by nrichart** [comment]
No don't get me wrong I am able to run it.
`srun ./ex50 <parameters>` works fine, but it mean you cannot hardcode `mpirun` in the package.py of petsc or other packages.
Since depending on the variant of mpi the `mpirun` wrapper might not be installed

**Comment by davydden** [comment]
@nrichart how about we introduce another variable to mpi wrappers `spec['mpi'].run` which for `OpenMPI` would be `mpirun` and for `mvapich2+slurm` -- `srun`, whereas without `slurm` it should probably also be `mpirun`. I am not sure about the parameter for the number of processes, i think this is also not the same among MPI implementations `-np`, `-n`, etc. 

I would then switch these tests to mpi-only and use `spec['mpi'].run` to run them.

**Comment by davydden** [comment]
@nrichart can you check if the following test works with your installation
```
        if 'mpi' in self.spec:
            with working_dir('src/ksp/ksp/examples/tutorials'):
                env['PETSC_DIR'] = self.prefix
                make("ex50", parallel=False)
                make("runex50", parallel=False)
                make("ex52", parallel=False)
                make("runex52", parallel=False)
                make("runex52_mumps", parallel=False)
                make("runex52_superlu_dist", parallel=False)
                make("ex55", parallel=False)
                make("runex55_hypre", parallel=False)
```
It uses PETSc's make file and targets to run. Those are supposed to pick up mpiexec and alike.

**Pull request merged**
