### PR TITLE
blitz: Fix build: Use CMakePackage instead of autotools

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Fix the build by inheriting CMakePackage instead of AutotoolsPackage, fixes:
`configure: error: cannot find install-sh, install.sh, or shtool in config "."/config`

### CODE REVIEW

**Comment by RemiLacroix-IDRIS** [comment]
> fixes: configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

I don't remember getting this error when building blitz.

i don't really have any specific opinion regarding switching to CMake but that will break versions older than 1.0.2 as those don't have the CMake build system.

**Comment by alalazo** [comment]
It seems the head of the development branch only supports CMake. Also, it seems the projects didn't merge a commit in years :cry: Let me know what you want to do with this PR (close or polish it and get it merged).

**Comment by ckhroulev** [comment]
@RemiLacroix-IDRIS Note that versions prior to 1.0.2 are no longer supported because they require Python 2.7.x.

>> fixes: configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
>
> I don't remember getting this error when building blitz.

I get this error as well. It appears to be caused by the `configure` script incompatible with current `autoconf` versions that is present in the Blitz repository. I can build 1.0.2 using `autoconf` if I delete `configure` and then re-generate it. (Looks like the spack package skips the `autoreconf` phase because `configure` is present.)

**Comment by alalazo** [comment]
@RemiLacroix-IDRIS @bernhardkaindl Should we resolve conflict and push the change forward, or close the PR?

**Comment by RemiLacroix-IDRIS** [comment]
Being that the older version are not supported anymore due to Python 2.7 being dropped, I don't mind using CMake.

**Comment by alalazo** [comment]
Ok, then. Feel free to update and remove old versions, and I'll try to merge it asap.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new PR to turn `blitz` to a CMakePackage.

**Pull request closed without merging**
