### PR TITLE
add openmp_max_threads variant and enable avx 512 optimizations for icelake

### PR DESCRIPTION
**Pull request by Andrey1994**
Changes in this PR:

* add variant to control openmp_max_threads, tuning this parameter may lead to better performance on some architectures
* force AVX512 optimizations for cascadelake and icelake, currently its not enabled

### CODE REVIEW

**Comment by danielahlin** [comment]
> add variant to control openmp_max_threads 

looks good

> force AVX512 optimizations for cascadelake and icelake, currently its not enabled 

at least target=cascadelake gives AVX512 for me with the current settings on 0.19.2. With which version did you observe AVX512 not being enabled for target=cascadelake?

Thanks,
Daniel

**Comment by Andrey1994** [comment]
> at least target=cascadelake gives AVX512 for me with the current settings on 0.19.2. With which version did you observe AVX512 not being enabled for target=cascadelake?

`develop` branch but I didn't test with cascadelake, looking at package.py for gromacs it's unclear for me how it can be on for cascadelake..
This if statement will set it for targets with smth like 512 in their name(skylake_avx512 for example) but for cascadelake and icelake its not the case

**Comment by Andrey1994** [comment]
ah, I see, it overrides `__contains__` method.
One last question: in `lscpu` and in avx512 docs these instructions are called like: avx512f, avx512dq, etc. There is no `avx512`. Does spack rename it somehow? If not, should it be changed to avx512f?

**Comment by danielahlin** [comment]
On Fri, May 5, 2023 at 3:16 PM Andrey Parfenov ***@***.***>
wrote:

> ah, I see, it overrides __contains__ method.
> One last question: in lscpu and in avx512 docs these instructions are
> called like: avx512f, avx512sq, etc. There is no avx512. Does spack
> rename it somehow? If not, should it be changed to avx512f?
>
I'm not sure this answers your question - but see
https://github.com/spack/spack/blob/develop/lib/spack/external/archspec/json/cpu/microarchitectures.json#L3074.
While it lacks precision, I would argue that avx512 is a de-facto useful
term for a set of features, but that's just an opinion of course.

FWIW I have thought about suggesting a direct setting/variant for the
corresponding gromacs SIMD setting. The general motivation is that when I
compile for GPU installations I generally do this with AVX2 for a
non-negligible performance gain. With spack I do this by setting the target
to e.g. skylake. However - it would be better to say something like "actual
target architecture without avx512 instructions" and then directly
set GMX_SIMD to what I want gromacs to produce.

**Review by danielahlin — APPROVED** [review]

**Comment by rscohn2** [comment]
@spackbot help

**Comment by rscohn2** [comment]
Close/reopen to trigger another run for failing readthedocs

**Review by rscohn2 — APPROVED** [review]

**Pull request merged**
