### PR TITLE
Flatbuffers: fixes for GCC 10+

### PR DESCRIPTION
**Pull request by robert-mijakovic**

### CODE REVIEW

**Comment by tldahlgren** [comment]
@matz-e Did you want to comment on this PR since you added the package?

**Comment by matz-e** [comment]
Looks OK to me, thanks @robert-mijakovic.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Please resolve the style errors:

```
var/spack/repos/builtin/packages/flatbuffers/package.py:33: [E501] line too long (92 > 88 characters)
15
var/spack/repos/builtin/packages/flatbuffers/package.py:41: [E501] line too long (92 > 88 characters)
```

**Comment by tldahlgren** [comment]
> Looks OK to me, thanks @robert-mijakovic.

Thanks for taking a look!

**Comment by robert-mijakovic** [comment]
> Please resolve the style errors:
> 
> ```
> var/spack/repos/builtin/packages/flatbuffers/package.py:33: [E501] line too long (92 > 88 characters)
> 15
> var/spack/repos/builtin/packages/flatbuffers/package.py:41: [E501] line too long (92 > 88 characters)
> ```

Resolved!

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Pull request merged**
