### PR TITLE
mapl: add 2.44

### PR DESCRIPTION
**Pull request by mathomp4**
This PR adds v2.44 of MAPL. This is a bit more complex than adding a checksum as MAPL 2.44 has some new requirements:

* ESMF 8.6.0
* ESMA_cmake v3.40.0 (as a resource)

I've also updated some GFE libraries to match the versions we test with internally (so I can be confident):

* gFTL v1.11
* gFTL-shared v1.7
* pFlogger v1.11
* fArgparse v1.6

I *think* I did the `when=` bits right (old `depends_on` up to 2.43, new `depends_on` from 2.44), but I hope some spack gurus can take a look. I'm sure it could be cleaned up...

---

NOTE that with this version of MAPL, the CMake target used internally for ESMF is now `ESMF::ESMF` (see https://github.com/GEOS-ESM/MAPL/issues/2569). This isn't really germane to spack, but it's possible someone might see this PR  via a Google search and perhaps this will help. (This was the reason for the ESMA_cmake version uptick.)

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Looks good to me! Thanks for the `ESMF::ESMF` bug fix and note here

**Review by AlexanderRichert-NOAA — CHANGES_REQUESTED** [review]
I am unable to build on my personal computer:
```console

1 error found in build log:
     117    -- Found NetCDF: /dev/shm/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/netcdf-c-4.9.2-lm7x3xwavnbgdvnfye4ldzz27m4hwyxe/include (found version "4.9.2") found components: C Fortran
     118    -- FindNetCDF defines targets:
     119    --   - NetCDF::NetCDF_C [/dev/shm/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/netcdf-c-4.9.2-lm7x3xwavnbgdvnfye4ldzz27m4hwyxe/lib/libnetcdf.so]
     120    --   - NetCDF::NetCDF_Fortran [/dev/shm/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/netcdf-fortran-4.6.1-qjqszssaeahrp6ty3ktskxhtd6fuqi2p/lib/libnetcdff.so]
     121    -- Found HDF5: hdf5-shared (found version "1.14.3")
     122    -- Found ESMF: /dev/shm/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/esmf-8.6.0-l6f6xxaohthjasipkj6fhnnzp44hrl57/lib/libesmf.so (found suitable version "8.6.0", minimum required is "8.6.0")
  >> 123    CMake Error at CMakeLists.txt:160 (target_link_libraries):
     124      Cannot specify link libraries for target "ESMF::ESMF" which is not built by
     125      this project.
     126    
     127    
     128    -- Configuring incomplete, errors occurred!
```

**Comment by AlexanderRichert-NOAA** [comment]
By the way here's what I get if I build against esmf@develop, which has the ESMF::ESMF alias:
```console
     123    -- Found ESMF: /dev/shm/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/esmf-develop-kcbhk3rqe2q5rqut7gaej45avyx2taru/lib/libesmf.so (found suitable version "8.7.0", minimum required is "8.6.0")
  >> 124    CMake Error at CMakeLists.txt:158 (target_link_libraries):
     125      target_link_libraries can not be used on an ALIAS target.
```

**Comment by mathomp4** [comment]
Well, nuts. Thanks @AlexanderRichert-NOAA I'm drafting this for now so it can't be merged. Let me do some tests...

**Comment by mathomp4** [comment]
I think I know the issue. Bad Matt didn't test and it's pretty obvious...

**Comment by mathomp4** [comment]
Closing for now. We need to do some work on our end.

**Pull request closed without merging**
