### PR TITLE
petsc: builds break with gnu-make-4.4.1

### PR DESCRIPTION
**Pull request by balay**
https://github.com/spack/spack/issues/35903

### CODE REVIEW

**Comment by haampie** [comment]
Did you figure out what the actual issue is? Is it a bug in gmake or a broken makefile?

**Comment by balay** [comment]
petsc build attempts to pass in additional arguments via MAKEFLAGS (in recursive make invocation) - and gmake-4.4.1 changed MAKEFLAGS in way that triggers this error. Suggestion is to not modify MAKEFLAGS.

Fixed at:  https://gitlab.com/petsc/petsc/-/commit/5ef50a0f30184c572c1829d0a161b2eb8af8a6a3

This patch will cleanly apply to petsc@3.18 - but not older versions. (well it applies with an offset for petsc-3.17). Hence this attempt to add a gmake dependency to currently released versions.

**Comment by raldone01** [comment]
The install finished successfully.

**Comment by balay** [comment]
@spackbot run pipeline

**Comment by balay** [comment]
For some reason CI fails [and I can't access the relevant logs],

So checking if  an alternate fix goes through CI

**Comment by haampie** [comment]
Hm, `gmake` is supposed to set the `make` global on the parent package, so it should work. (And it should be in the path)

**Comment by balay** [comment]
CI failures were in slepc [but my manual build was fine].
- https://gitlab.spack.io/spack/spack/-/jobs/6338710
- https://gitlab.spack.io/spack/spack/-/jobs/6339865

This alternative fix is also fine - so I think this PR is ready for approval/merge

**Comment by balay** [comment]
Ops - I see the CI is still pending [don't know why I thought it was successfully completed]

**Comment by balay** [comment]
CI completed successfully- so this PR is ready for approval/merge

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
