### PR TITLE
darshan-runtime: generic default log path in run env

### PR DESCRIPTION
**Pull request by matz-e**
When generating centrally deployed modules, the default log path may be
in a location that is not writable by the eventual user. Default to the current
directory.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
@shanedsnyder @carns can one of you review this?

**Comment by carns** [comment]
For some general background (putting aside spack for the moment), Darshan's runtime component supports two configure options: `--with-log-path` for a fixed destination log directory that is expected to contain a subdirectory hierarchy generated with the `darshan-mk-logdirs.pl` utility, and `--with-log-path-by-env` which specifies the log directory via an environment variable that is checked at runtime, and is *not* expected to contain a subdirectory hierarchy.  The former is typically used for system installs with a common log directory for all users, while the latter is typically used for end-users who just want to be able to run their own copy of Darshan in their own directory.

For sure different systems will have different writable directories on compute nodes for end users, though.  I think rather than changing the default env variable to '.' in the spack package (really this should probably be PWD, as this configure option is supposed to refer to an environment variable) for everyone, it might be better to keep it as is and just add a variant that allows installers to override it?

It would probably also be useful to have a variant that lets installers set `--with-log-path` instead of `--with-log-path-by-env` so that the spack package can also be used for system-wide installs with a common log directory.

**Comment by matz-e** [comment]
> For sure different systems will have different writable directories on compute nodes for end users, though. I think rather than changing the default env variable to '.' in the spack package (really this should probably be PWD, as this configure option is supposed to refer to an environment variable) for everyone, it might be better to keep it as is and just add a variant that allows installers to override it?

Note that the environment variable passed to configure remains `DARSHAN_LOG_DIR_PATH`:
```
                   '--with-log-path-by-env=DARSHAN_LOG_DIR_PATH',
```
and this is still controllable by the user (after loading a generated module), just that the default is now `.`, equivalent to `$PWD`. IMO this is the least surprising…

> It would probably also be useful to have a variant that lets installers set `--with-log-path` instead of `--with-log-path-by-env` so that the spack package can also be used for system-wide installs with a common log directory.

I can see that; I assume these two options are mutually exclusive? And thus would require conflicting variants?

**Comment by matz-e** [comment]
> > It would probably also be useful to have a variant that lets installers set `--with-log-path` instead of `--with-log-path-by-env` so that the spack package can also be used for system-wide installs with a common log directory.
> 
> I can see that; I assume these two options are mutually exclusive? And thus would require conflicting variants?

Reading the docs, I don't see a way to arbitrarily set variants, though…

**Comment by carns** [comment]
Ohh, I see.  I skimmed the package.py too quickly and didn't realize that it was setting DARSHAN_LOG_DIR_PATH when the module is loaded.  I need to try actually building the package next time :) 

At any rate, to further discussion:

The `fabrics` variant in the `libfabric` package comes to mind as an example of setting variants to arbitrary strings or lists of strings, if that is helpful.

As for Darshan itself, the configure script requires that _at least one_ of `--with-log-path` or `--with-log-path-by-env` to be specified.  If both are specified, then the env one takes priority, falling back to the non-env one if the specified environment variable(s) are not set.

**Comment by matz-e** [comment]
> The `fabrics` variant in the `libfabric` package comes to mind as an example of setting variants to arbitrary strings or lists of strings, if that is helpful.

OK, thanks! I finally got it. This could actually be used set defaults for both a hard-coded log path and the environment variable. I'm not sure though if that should still be in the scope of this PR?

**Comment by carns** [comment]
What do you think about a) keeping the default as is (to avoid surprising existing Spack Darshan users) and b) adding a variant that allows an installer to specify what should be in the env var set by spack?

If the value of the variant starts with a $ character, it is assumed to be an env variable (like $HOME).  Otherwise it is assumed to be a path (like ".").

We can address the fixed log dir (for system installs) later.  There will be a 3.2.0 release of Darshan before long that will warrant some spack updates anyway.

**Comment by matz-e** [comment]
@carns, thank you, I've integrated your suggestions. Maybe the variant name I chose is a bit cumbersome (same goes for escaping `$` of the environment variable), but it'll do for our deployment and preserves current behavior.

**Comment by carns** [comment]
This looks great, thanks @matz-e !  I tested it out and confirmed that the default behavior remains unchanged and that you can both specify a fixed path and an environment variable using the variant.

I have one more trivial suggestion: it might be helpful for the description of the variant to indicate that if you want to specify an environment variable, that the value needs to have an escaped '$' prefix (like log-path-by-env=\$SOMEDIR).

**Comment by matz-e** [comment]
Yes, that's a good idea! I also removed the value check to get cleaner output of `spack info`.

**Comment by carns** [comment]
Great, thanks @matz-e .  @adamjstewart this PR looks good to me if you want to merge it.

**Comment by alalazo** [comment]
Is this something still needed for `darshan`? Should we rebase and iterate quickly on a merge, or rather close the PR?

**Comment by matz-e** [comment]
> Is this something still needed for `darshan`? Should we rebase and iterate quickly on a merge, or rather close the PR?

I just did a quick rebase, this is still something relevant from our side…

**Comment by alalazo** [comment]
@matz-e I have been looking more closely at this PR and I think having a variant for a location that might be set at runtime is not optimal. Here's a proposal for modifying the implementation to obtain, hopefully, the same result:
1. Remove the current variant
2. Set a well defined environment variable name for `--with-log-path-by-env=`
3. Warn or error in `setup_run_environment` if this variable is not set explicitly

In case we opt for a warning we should also have a default location and say something like:
```
==> Warning: XXX is needed to specify where to store the logs of darshan-runtime and is not set. Using the default value of YYY
```
Does that seem reasonable for your use case?

**Comment by matz-e** [comment]
@alalazo I think overall the intent got changed a bit through the reviews. If I understand you correctly, the changes you propose would only act at module generation time. If modules are centrally deployed/generated, then there is still some end-user intervention required, as before.

Maybe it's best to just close this?

**Pull request closed without merging**
