### PR TITLE
New package py-cdo

### PR DESCRIPTION
**Pull request by kserradell**
Hello,

this is my first attemp to collaborate with spack. I've created the package py-cdo, which is the python interface for the Climate Data Operators.

https://pypi.python.org/pypi/cdo/1.3.2

### CODE REVIEW

**Comment by kserradell** [comment]
@tgamblin the test failed for one space in the header and the other, is because url from pypi is too long.

Instead of 

`url      = "https://pypi.python.org/packages/d6/13/908e7c1451e1f5fb68405f341cdcb3196a16952ebfe1f172cb788f864aa9/cdo-1.3.2.tar.gz"` 

I've tried 

`url      = "https://pypi.python.org/packages/source/c/cdo/cdo-1.3.2.tar.gz"`

but this last url does not work. Any workaround?

**Comment by tgamblin** [comment]
It's actually yelling at you because:
1. You need two blank lines  before `class`, and
2. The docstring line is too long -- you can just wrap that.

We actually exempt URL lines from the length restrictions so they shouldn't show up in the `flake8` checks.

**Comment by citibeth** [comment]
Please specify whether this works with Python2, Python3 or both.  This is done by an appropriate `depends_on()` line right after the `extends('python')` line.

**Comment by adamjstewart** [comment]
I'm not seeing any information on what versions of Python it is compatible with. The `setup.py` is pretty sparse, and doesn't even list the dependencies. The website isn't that helpful either.

**Comment by citibeth** [comment]
@kserradell Welcome to Spack!

Now for the bad news.. I made the "mistake" of looking at the py-cdo source.  Two issues spring up:

1. It looks like they tried to upgrade the source code from Python2 to Python3 (cdo-1.2.1).  It is full of `print()` function calls, which only work on Python3 (unless you've done `from __future__ import print_function`, which this code has not).  HOWWEVER... they also have `print xxx` statements TOO, which won't work on Python3.  Conclusion: **This code won't work fully on Python2 or Python3.**

2. This code calls the CDO program; and figures out where CDO is by looking at the `CDO` env var.  That kind or practice is problematic in a Spack environment, because the user will have to set the `CDO` env var to whatever location Spack installed CDO in.  Alternatively, you must have the `cdo` module loaded in order to run `py-cdo` --- which is also a PITA and the kind of thing we want to avoid with Spack. The "right" way to resolve this issue is to "bake in" the location of Spack's `cdo` at the time that you build `py-cdo`.  Then things will "just work" without any special environment variable settings.  See: https://github.com/Toblerity/rtree/pull/74

For these two reasons, I would recommend that we see if the upstream code can be improved before merging into Spack.  Luckily it's a small project, only 336 lines of Python code total.

**Comment by adamjstewart** [comment]
@citibeth 
```
$ python
Python 2.7.12 (default, Jul 21 2016, 15:23:03) 
[GCC 6.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'hello'
hello
>>> print('hello')
hello
```

**Comment by citibeth** [comment]
Thanks, you learn something new every day!  With that in mind... I would
say the code will run on Python2 but not Python3.  Getting this code
running on Python3 would be rather easy.

**Comment by alalazo** [comment]
@citibeth The statement:
```python
from __future__ import print_function
```
forces the application of [PEP3105](https://www.python.org/dev/peps/pep-3105/) in python 2, and makes the print statement illegal (syntax error).

**Comment by citibeth** [comment]
I believe this is Python 2.7, not 2.6.  So `python@2.6` should be excluded
from this Package?

**Comment by adamjstewart** [comment]
@citibeth 
```
$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'hello'
hello
>>> print('hello')
hello
```
I don't think we need to worry too much about constraining it since the developers don't specify. It might be good to say that it is Python 2 only though. Something as simple as `depends_on('python@:2')` might be enough, although I haven't tested that to make sure it works.

**Comment by citibeth** [comment]
I disagree, the parenthesis format does NOT (really) work on Python2.  But you have to print more than one thing to see why.  Try:
```
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print('hello', 2)
('hello', 2)
```
On Python3 (or with `from future import...`) this will print without the parentheses.  Python2 is interpreting your parentheses as a tuple, rather than function arguments.

**Comment by citibeth** [comment]
I therefore return to my original conclusion that this package is probably Python3, where they forgot to convert a couple of `print` statements.

**Comment by adamjstewart** [comment]
> It looks like they tried to upgrade the source code from Python2 to Python3 (cdo-1.2.1). It is full of `print()` function calls, which only work on Python3 (unless you've done from `__future__ import print_function`, which this code has not). HOWWEVER... they also have `print xxx` statements TOO, which won't work on Python3. Conclusion: **This code won't work fully on Python2 or Python3.**

cdo-1.2.1 is pretty old. The latest version, which this PR adds, is cdo-1.3.2. The very first line of `cdo.py` is:
```python
from __future__ import print_function                                           
```
There are also no cases where they run `print(abc, xyz)`, or `print xxx`. Conclusion: **This code works perfectly fine in Python 2 and Python 3.**

I don't think we should constrain the Python version if the developers don't and there is no evidence that it won't work in both.

**Comment by citibeth** [comment]
Thanks... sorry, I was looking at the wrong version.

The issue of the env var still needs to be addressed, if it hasn't been
already.

**Comment by adamjstewart** [comment]
> This code calls the CDO program; and figures out where CDO is by looking at the CDO env var. That kind or practice is problematic in a Spack environment, because the user will have to set the CDO env var to whatever location Spack installed CDO in. 

There is a way to do this in Spack. It's like `setup_environment` or `setup_dependent_environment` or something. Can someone who is more familiar with this method comment on which to use?

> Alternatively, you must have the cdo module loaded in order to run py-cdo --- which is also a PITA and the kind of thing we want to avoid with Spack. 

I agree that it is nice to avoid, but it is also the way most Spack Python packages currently work, until we figure out a better way to RPATH dependencies.

> The "right" way to resolve this issue is to "bake in" the location of Spack's cdo at the time that you build py-cdo. Then things will "just work" without any special environment variable settings. See: Toblerity/rtree#74

Unless @kserradell is a `cdo` developer and can push out a new release with those changes, I think that's a little much to ask here. We can suggest it to the `cdo` developers, but I don't think this should hold up the PR.

**Comment by citibeth** [comment]
On Tue, Dec 13, 2016 at 2:52 PM, Adam J. Stewart <notifications@github.com>
wrote:

> This code calls the CDO program; and figures out where CDO is by looking
> at the CDO env var. That kind or practice is problematic in a Spack
> environment, because the user will have to set the CDO env var to whatever
> location Spack installed CDO in.
>
> There is a way to do this in Spack. It's like setup_environment or
> setup_dependent_environment or something. Can someone who is more
> familiar with this method comment on which to use?
>
Is this a buildtime thing or a module thing?

Also.. the `cdo` package can't export the `$CDO` variable because it is an
invention of `py-cdo`.

Alternatively, you must have the cdo module loaded in order to run py-cdo
> --- which is also a PITA and the kind of thing we want to avoid with Spack.
>
> I agree that it is nice to avoid, but it is also the way most Spack Python
> packages currently work, until we figure out a better way to RPATH
> dependencies.
>
> The "right" way to resolve this issue is to "bake in" the location of
> Spack's cdo at the time that you build py-cdo. Then things will "just work"
> without any special environment variable settings. See: Toblerity/rtree#74
> <https://github.com/Toblerity/rtree/pull/74>
>
> Unless @kserradell <https://github.com/kserradell> is a cdo developer and
> can push out a new release with those changes, I think that's a little much
> to ask here. We can suggest it to the cdo developers, but I don't think
> this should hold up the PR.
>
The change needs to happen to `py-cdo`, not `cdo`.  It should not be too
hard; looks like a small codebase where the entire package is 336 lines
long.

**Comment by tgamblin** [comment]
@adamjstewart:
>  There is a way to do this in Spack. It's like setup_environment or
> setup_dependent_environment or something. Can someone who is more
> familiar with this method comment on which to use?

* [`setup_environment()`](http://spack.readthedocs.io/en/latest/module_file_support.html#package-file-api)
* [`setup_dependent_environment()`](http://spack.readthedocs.io/en/latest/packaging_guide.html#setup-dependent-environment).

One is really for modules; the other is for dependent packages.  Perhaps we need a reference (like the command index) for functions that can be overridden in `package.py`.

@citibeth:
> Also.. the `cdo` package can't export the `$CDO` variable because it is an
> invention of `py-cdo`.

`py-cdo` doesn't require that the `CDO` var be set. It will just call `cdo` instead of the abspath if `CDO` is not set.

Currently we rely on the module system and/or other environment settings to handle non-RPATH runtime settings. We haven't started forcing packages to patch scripts so they call commands by absolute paths, and I think we should formalize that more before we go requiring it.  We'd need to figure out how to make it more systematic.  `PATH` also isn't the only runtime dependency of `py-cdo` -- it also has a runtime dependency on its Python dependencies being in `PYTHONPATH`.

I think a better way to handle this kind of thing would be to do something more like #643.

**Comment by adamjstewart** [comment]
P.S. Congratulations on your first Spack package @kserradell! I hope we didn't scare you off. I promise it isn't normally this controversial.

**Comment by kserradell** [comment]
First of all, sorry for not participating in the discussion. I'm in Spain and left the office in the afternoon, went home and forgot spack and HPC for a few hours...

@adamjstewart, I'm not scared. In fact I've learnt a lot with the discussion and I realized how reduced is my knowledge even if I been working in HPC and Earth Sciences my last seven years. 

I'm very interested in promoting the usage of spack in Barcelona and in the European earth system modelling community. With @skosukhin we are working on it.

I hope this will be the first contribution of many others in the future.

Thanks to all.

**Pull request merged**
