### PR TITLE
Paraview on windows: Use htf5::hdf5

### PR DESCRIPTION
**Pull request by danlipsa**
Use htf5::hdf5 on Windows

### CODE REVIEW

**Comment by danlipsa** [comment]
@spackbot fix style

**Comment by danlipsa** [comment]
@johnwparent Please review

**Review by johnwparent — CHANGES_REQUESTED** [review]
This looks good, but can we either point to the patch in the VTK package here (and vis-versa), or create a centralized issue on GH so we can track the fact this is a duplicated patch for another package and any updates/follow on changes need to be made to both.

**Comment by danlipsa** [comment]
> This looks good, but can we either point to the patch in the VTK package here (and vis-versa), 

The patches are slightly different: the ParaView has an additional VTK in the path. So we cannot reuse the patch.

> or create a centralized issue on GH so we can track the fact this is a duplicated patch for another package and any updates/follow on changes need to be made to both.

Or simply adding a comment on both stating that they are the same?

**Comment by johnwparent** [comment]
> > This looks good, but can we either point to the patch in the VTK package here (and vis-versa),
> 
> The patches are slightly different: the ParaView has an additional VTK in the path. So we cannot reuse the patch.

Right, sorry, should have been clearer, I don't mean re-use the patch, just indicate they are functionally the same and so any meaningful change made in one (or in the patch directive in the package recipe) should be made in the other.

> > or create a centralized issue on GH so we can track the fact this is a duplicated patch for another package and any updates/follow on changes need to be made to both.
> 
> Or simply adding a comment on both stating that they are the same?

Yes exactly.

**Review by johnwparent — APPROVED** [review]
LGTM

**Comment by johnwparent** [comment]
Looks good, thanks Dan! I'll merge once the GL pipelines pass.

**Comment by danlipsa** [comment]
@spackbot re-run pipeline

**Comment by danlipsa** [comment]
@johnwparent Is this ready to be merged? Thanks!

**Pull request merged**
