### PR TITLE
banner: add v3.5

### PR DESCRIPTION
**Pull request by alecbcs**
Add banner v3.5.

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by cessenat** [comment]
Sorry I arrived too late, but why do you assert that it is release 3.5 ?
When I run it it says
`This is banner 1.3.5.`
Thanks in advance

**Comment by alalazo** [comment]
@cessenat My bad, this one needs to be reverted. I just checked the latest shasum, didn't notice it's the same as the previous one!

**Comment by alalazo** [comment]
@cessenat Reverted.

**Comment by cessenat** [comment]
> @cessenat My bad, this one needs to be reverted. I just checked the latest shasum, didn't notice it's the same as the previous one!

Thanks @alalazo 
@alecbcs can you explain about the release number ?

**Comment by alalazo** [comment]
@cessenat I think the explanation is as simple as `spack checksum` being buggy on this package. This is what I did to verify the checksum:
```console
$ spack checksum banner 3.5
==> Found 1 version of banner:
  
  3.5  https://github.com/pronovic/banner/archive/refs/tags/BANNER_V1.3.5.tar.gz

==> Fetching https://github.com/pronovic/banner/archive/refs/tags/BANNER_V1.3.5.tar.gz

    version("3.5", sha256="fb21c42620a0a668334b5732a6216b23b3990ca5d87cf3b15f0689dc617e7fdc")
```

**Comment by cessenat** [comment]
Oh ya, same as
```
$ spack versions banner 
==> Safe versions (already checksummed):
  1.3.5
==> Remote versions (not yet checksummed):
  3.5

```
I do not know how to correct that.

**Comment by alecbcs** [comment]
> @cessenat My bad, this one needs to be reverted. I just checked the latest shasum, didn't notice it's the same as the previous one!

Apologies I also should have noticed the duplicate checksum! I'd run `spack version banner` noticed a newer `v3.5`, checksummed it, test that it built, and uploaded the PR.

@cessenat it looks like banner is now providing [GitHub releases](https://github.com/pronovic/banner/releases/tag/BANNER_V1.3.5) instead of simply tags. Modifying to the release asset url I not longer encounter this parse bug with the package. Would you be in favor of moving to the provided release tarball? In addition to fixing the parsing error this would also remove the dependency on GitHub's hashing algorithm if they ever decide to change it again.

**Comment by cessenat** [comment]
> @cessenat it looks like banner is now providing [GitHub releases](https://github.com/pronovic/banner/releases/tag/BANNER_V1.3.5) instead of simply tags. Modifying to the release asset url I not longer encounter this parse bug with the package. Would you be in favor of moving to the provided release tarball? In addition to fixing the parsing error this would also remove the dependency on GitHub's hashing algorithm if they ever decide to change it again.

LGTM

**Pull request merged**
