### PR TITLE
libint: add link option for fujitsu compiler

### PR DESCRIPTION
**Pull request by m-shunji**
This PR allows the libint to be built using the Fujitsu Compiler.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot fix style

**Comment by m-shunji** [comment]
@alalazo I apologize for the delayed response. Thank you for the style corrections. Are there any other changes I should make? I appreciate your guidance.

**Comment by alalazo** [comment]
LGTM, as soon as @dev-zero approves. Feel free to ping me in a week or so if there is no response, and I'll merge.

**Comment by m-shunji** [comment]
@alalazo 
Could you please check my last update on the PR when possible? Thanks.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
