### PR TITLE
py-tensorflow-estimator: correct dependencies

### PR DESCRIPTION
**Pull request by adamjstewart**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can't figure out why it can't find `absl`. In previous versions, it was brought in from TF. In this version, even if I explicitly add it as a dep, it still can't find it. I think the current listed deps are correct, so even if we have to remove this new version, we should still keep those changes. Will see if @aweits can figure out what's wrong.

**Comment by adamjstewart** [comment]
@aweits can you look into this when you have time? I may just remove the new version and keep the other changes just to get this merged. The goal here was to avoid building older TF in CI, but they still don't support 2.16, so 2.15 isn't particularly useful to me.

**Comment by adamjstewart** [comment]
Ping @aweits

**Comment by adamjstewart** [comment]
Possible theory: `PYTHONPATH` contains over 21K characters and may be too long for Python to find `absl`.

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
I couldn't get 2.15.0 working, but I still think the changes to deps in this PR are worth merging, so I removed 2.15.0. This should be ready to merge now.

**Review by alalazo — APPROVED** [review]
@adamjstewart Feel free to merge, if you're not waiting further comments

**Pull request merged**
