### PR TITLE
vep: new package

### PR DESCRIPTION
**Pull request by teaguesterling**
This adds the `vep` package, installing it either using the official VEP installer script or by placing the necessary perl scripts and dependencies in the right places. By default it does not use the VEP installer, as it downloads and installs additional perl libraries and doesn't take advantage of Spack's caching and mirroring.

This intentionally does not install the VEP caches, but provides some tie-in tooling to do it. A potential tie-in to create a "data" package is underway in #44523. I'm not sure if that's the best way to handle it, however.

This is dependent on a few other pending PRs to address dependent Perl modules:

 - #44505
 - #44506
 - #44507
 - #44508
 - #44509

### CODE REVIEW

**Comment by EbiArnie** [comment]
Please remove the dependencies that have now become separate PRs.

**Comment by EbiArnie** [comment]
Also - I like this. Nice work!

**Comment by teaguesterling** [comment]
> Also - I like this. Nice work!

Thanks! I was delighted that it worked. My original aim was to get this to be air-gap friendly. I hope others find it useful. Thank you again as well for taking the time to review and test it.

**Comment by EbiArnie** [comment]
An update mainly for @wdconinc :
This is currently waiting for #44507.

**Review by bernhardkaindl — DISMISSED** [review]
Status summary for @teaguesterling, The last remaining dependency PR should be on track to be auto-merged now. You can remove the conflictin other recipes from the already-merged PRs from this PR now:

https://github.com/spack/spack/pull/44506
https://github.com/spack/spack/pull/44507
https://github.com/spack/spack/pull/44508
https://github.com/spack/spack/pull/44509

**Comment by teaguesterling** [comment]
Cleaned up the merge. Should be ready to go once #44507 is done, but probably ready for auto merge as conflicts have been fixed.

**Review by EbiArnie — APPROVED** [review]
I only tested the default variants. With that, this worked fine for me.
Thanks!

**Pull request merged**
