### PR TITLE
Last-minute fix for #26815 (make py-tomli dependency an open range)

### PR DESCRIPTION
**Pull request by iarspider**
Ping @alalazo

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by scottwittenburg** [comment]
I don't know if this should have been merged, the gitlab pipeline looks to have failed legitimately.  I know it's the fault of auto-merge which doesn't care about a check that's not required.   I suspect we're about to see the same failures on the current develop pipeline, [here](https://gitlab.spack.io/spack/spack/-/pipelines/72653), once it retries the jobs.

**Comment by adamjstewart** [comment]
@alalazo #26813 and #26820 were both merged without maintainer approval. Please wait for package maintainers (in this case me) to review before merging so we can avoid these kinds of bugs 😃

**Comment by alalazo** [comment]
So, the original PR (#26813) passed the pipeline: https://gitlab.spack.io/spack/spack/-/pipelines/72582 I noticed that #26547 was also merged so wondering if it is that one having unwanted side effects on pipelines? What I don't understand is why the PR with the fix is building much more packages than the original PR. :thinking:

**Comment by alalazo** [comment]
Ok, I think I have a plausible explanation.The original PR required `setuptools-scm` to depend on `py-tomli@1.0.0`, which is a version we don't have. `clingo` worked that out and used the previous version of `setuptools-scm` (which was working since it was the one we used before). This PR made the constraint right, so the latest version became the one chosen by `clingo` and here we have the legitimate failure.

**Pull request merged**
