### PR TITLE
Metis parmetis cleanup

### PR DESCRIPTION
**Pull request by davydden**
addresses [this](https://github.com/LLNL/spack/issues/614#issuecomment-200948730) comment of @alalazo .

- [x] avoid hardcoding `lm`
- [x] test on Ubuntu 14.04

### CODE REVIEW

**Comment by davydden** [comment]
@nrichart I addressed (hopefully) some concerns raised in https://github.com/LLNL/spack/issues/614, could you please elaborate on your idea of getting `lm` from METIS CMake config?

**Comment by davydden** [comment]
btw, that's how METIS decide on 'lm':
```
if(UNIX)
  target_link_libraries(metis m)
endif()
```
inside `libmetis/CMakeList.txt'.

**Comment by davydden** [comment]
so I would say we should follow the same for now. And if there are some issues with Intel, it should first be resolved upstream in `Metis`, or patched in Spack.

**Comment by nrichart** [comment]
Yes I know for the `if(UNIX)` that is what I mentioned at the end of my first message in fact.
I'm trying to test for what I mentioned with intel is really blocking or not. I guess that adding `m` with clang is not a problem or you would have seen it.

The first solution I proposed would be to add `install(EXPORT ...` in the cmake of metis and a`find_package(metis)` in parmetis in order to get all the compile/linking information from the metis package.
Then if the `libm` is a problem it would have to be solved only in one package and the info would be propagated.

This wold be as mentioned in #614 lot of modifications to maintain through the different versions of metis and parmetis.
Adding something like 
> if(UNIX)
>  target_link_libraries(parmetis m)
> endif()
was what i suggested as second solution.
if you go to implement this could I ask you to modify your `enable_external_metis.patch` with something like that
> CMakeLists.txt
>-#add_subdirectory(${METIS_PATH}/libmetis ${CMAKE_BINARY_DIR}/libmetis)
>+find_library(METIS_LIBRARY metis PATHS ${METIS_PATH}/lib)

> libparmetis/CMakeLists.txt
>-target_link_libraries(parmetis metis ${MPI_LIBRARIES})
>+target_link_libraries(parmetis ${METIS_LIBRARY} ${MPI_LIBRARIES})
The problem I mentioned in #585 was linked to the missing -L<path to metis>

**Comment by davydden** [comment]
@nrichart done, have a look. As for amount of patching of Metis/Parmetis, i think it's not too bad. Essentially: (i) copy all GKlib headers + export a couple; (ii) make Parmetis use external Metis & GKlib headers.

**Comment by nrichart** [comment]
This would do it.
I'm still trying to see if it could be a problem to add `m` explicitly in the link.
But I'm facing some other trouble with the intel compilers

**Comment by nrichart** [comment]
Ok `metis` install correctly with intel compiler

**Comment by davydden** [comment]
@alalazo @tgamblin ping.

**Comment by davydden** [comment]
tested on Ubuntu 14.04

**Comment by tgamblin** [comment]
@nrichart when you're both satisfied with this I'll merge (or if you're not I guess we'll have to discuss more :smile:)

**Comment by tgamblin** [comment]
@nrichart oh it looks like you are already.  Sorry -- too many emails :inbox_tray: :bomb:.  Merging...

**Pull request merged**
