### PR TITLE
libEnsemble: add v0.10.0 - followup

### PR DESCRIPTION
**Pull request by jlnav**
Contains suggested changes from #37954 . I apologize if this is the incorrect way to followup on the other PR.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the sha256, will defer merge to give @adamjstewart a chance to comment

**Comment by adamjstewart** [comment]
@shuds13 what do you think?

Normally I would just push to @shuds13's branch but that depends on whether or not you have those permissions.

**Comment by shuds13** [comment]
@adamjstewart @jlnav Regarding this and  #37954, it doesn't make a lot of sense to me to use "extras' like this (even if the variant existed).

**Comment by adamjstewart** [comment]
The advantage of extras is that `spack install py-libensemble+extras` and `pip install libensemble[extras]` will both result in the same installation. But both of you are the maintainers of this recipe so the final decision is up to you.

**Pull request closed without merging**
