### PR TITLE
ca-certificates-mozilla: add 2022-10-11

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
Will defer merge decision to @haampie .

**Review by alalazo — APPROVED** [review]

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@alalazo @haampie FYI this is currently mergeable

**Pull request merged**
