### PR TITLE
perl: fix macOS build

### PR DESCRIPTION
**Pull request by sethrj**
With both perl@5.34.0 and perl@5.32.1 the build fails on `macos-bigsur-skylake %apple-clang@12.0.5` and `%apple-clang@13.0.0`:
```
2 errors found in build log:
     579013    /private/var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/s3j/spack-stage/spack-stage-perl-5.34.0-tpha2u52qfwaraidpzzbf6u4dbqg7dk5/spack-src/cpan/
               Math-BigInt-FastCalc/../../miniperl "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- FastCalc.bs ../../lib/auto/Math/BigInt/FastCalc/Fas
               tCalc.bs 644
     579014
     579015    	Everything is up to date. Type '/Applications/Xcode.app/Contents/Developer/usr/bin/make test' to run test suite.
     579016    DYLD_LIBRARY_PATH=/private/var/folders/fy/x2xtwh1n7fn0_0q2kk29xkv9vvmbqb/T/s3j/spack-stage/spack-stage-perl-5.34.0-tpha2u52qfwaraidpzzbf6u4dbqg7d
               k5/spack-src  ./perl -Ilib -I. installperl --destdir=
     579017    WARNING: You've never run 'make test' or some tests failed! (Installing anyway.)
     579018      /rnsdhpc/code/spack/opt/spack/apple-clang/perl/tpha2u5/bin/perl5.34.0
  >> 579019    install_name_tool: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Pl
               atforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find install_name_tool 2> /dev/null' failed with exit code 256: (null) (errno=Invalid argument
               )
     579020    xcode-select: Failed to locate 'install_name_tool', requesting installation of command line developer tools.
     579021    Cannot update /rnsdhpc/code/spack/opt/spack/apple-clang/perl/tpha2u5/bin/perl5.34.0 dependency paths
  >> 579022    make: *** [install-all] Error 72
```

The system pops up a dialog box requesting an install of the command line tools -- installing them does nothing.

This is due to SYSTEM_VERSION_COMPAT being set when it should *not* be. I verified that the fix works on `perl@5.34.0`. I'm not sure in what circumstances the original failure took place that caused #21375 to be needed.

### CODE REVIEW

**Comment by sethrj** [comment]
FWIW (since this *does* change some macos build behavior and can be decoupled from both the OS and the XCode versions!) my SDK is:
```
MacOSX11.3.sdk - macOS 11.3 (macosx11.3)
SDKVersion: 11.3
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
PlatformVersion: 11.3
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 20E214
ProductCopyright: 1983-2021 Apple Inc.
ProductName: macOS
ProductUserVisibleVersion: 11.3
ProductVersion: 11.3
iOSSupportVersion: 14.5
```

**Comment by sethrj** [comment]
@spackbot rerun pipeline

**Comment by haampie** [comment]
@sethrj rerun?!

@spackbot re-run pipeline

**Comment by alalazo** [comment]
I don't see any issue on my Mac. The funny thing is that the SDK I am using is:
```console
MacOSX11.3.sdk - macOS 11.3 (macosx11.3)
SDKVersion: 11.3
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
PlatformVersion: 11.3
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 20E214
ProductCopyright: 1983-2021 Apple Inc.
ProductName: macOS
ProductUserVisibleVersion: 11.3
ProductVersion: 11.3
iOSSupportVersion: 14.5
```
which seems exactly the same as yours! The compiler version is `apple-clang@13.0.0`

**Comment by sethrj** [comment]
@alalazo That's bizarre and a little frustrating! What could be different about our installations? I've seen this twice now on two versions of the compiler, and on two machines... I'm still able to reproduce it:
Screen Shot 2021-10-04 at 07 49 11

I tried using xz using a clean environment instead of bash, and saw the same thing. I'm not using any strange externals. I assume now that the problem is on my end, since I would guess that more mac users would be seeing failed perl installs.

Can you try applying my patch and seeing whether it works or what the failure mode is?

Finally, here are a couple more diganostics just in case there's a difference...
```
$ xcode-select -v
xcode-select version 2384.
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ softwareupdate --history | grep Xcode
Command Line Tools for Xcode                       12.4       07/12/2021, 12:21:03
Command Line Tools for Xcode                       12.5       07/12/2021, 12:21:03
Command Line Tools for Xcode                       12.5       07/12/2021, 12:21:03
Command Line Tools for Xcode                       13.0       10/03/2021, 08:33:10
```

**Comment by alalazo** [comment]
Disclaimer: I am an occasional Mac user, definitely not a power user. I think one difference is that I am (don't know why!) still using old command line developer tools:
```console
culpo@MacBook-Pro spack % xcode-select -v
xcode-select version 2384.
culpo@MacBook-Pro spack % xcode-select -p
/Applications/Xcode.app/Contents/Developer
culpo@MacBook-Pro spack % softwareupdate --history | grep Xcode 
Command Line Tools for Xcode                       11.5       04/06/2020, 00:50:55  
Command Line Tools for Xcode                       11.0       04/06/2020, 00:50:55  
```

**Comment by sethrj** [comment]
@alalazo Aha, that's gotta be it then. Those are some of the more important toolchain elements used by xcode. I'm a power user and I'm *still* confused how the different versions of these interact:
- macOS
- Xcode
- Xcode command line tools
- targeted macOS SDK

and they all tend to change the behavior of libraries that have optional GUI components or link against macos frameworks (Qt comes to mind).

I'll see if I can interrogate the command line tools version and then set the environment variable based on that. Sound ok? Since more people will be installing the new CLT this will become more of an issue soon.

**Comment by sethrj** [comment]
So as far as I can tell, the command line tools contains mostly header files and stub libraries for multiple macOS version SDKs -- it's like the `-devel` packages for package managers, I guess.

I'm not sure how this translates to what the perl script is looking for, but from [SO](https://apple.stackexchange.com/questions/180957/determine-xcode-command-line-tools-version) it's pretty easy to detect the installed version:
```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
```
so I'll add that.

**Comment by sethrj** [comment]
Ping @alalazo

**Comment by alalazo** [comment]
@sethrj Can you rebase this one to run the "new" required doc test on readthedocs? I'll take care of doing a test drive on my macOS and merging it soon after if ✅

**Comment by sethrj** [comment]
LLVM build failed again...

@spackbot re-run pipeline

**Review by alalazo — APPROVED** [review]
`perl` built succesfully on my macOS

**Comment by sethrj** [comment]
Thanks @alalazo !

**Pull request merged**
