### PR TITLE
aocl-utils: source sha has changed

### PR DESCRIPTION
**Pull request by stephenmsachs**
Seems like the checksum of the 4.2 source packages has changed.

### CODE REVIEW

**Review by amd-toolchain-support — APPROVED** [review]
Thanks. You beat us to it with the PR

**Comment by amd-toolchain-support** [comment]
@stephenmsachs the sha for our 4.1 release has changed also.  Would you be kind enough to roll that in here please?

**Comment by stephenmsachs** [comment]
Seems like the copy cached on spack.io still has the old checksum:
```
stesachs@ip-10-0-6-68:~$ pushd /tmp; curl -OL "https://mirror.spack.io/_source-cache/archive/a2/a2f271f5eef07da366dae421af3c89286ebb6239047a31a46451758d4a06bc85.tar.gz" ;popd;  sha256sum /tmp/a2f*
/tmp ~
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72775  100 72775    0     0  1776k      0 --:--:-- --:--:-- --:--:-- 1776k
~
a2f271f5eef07da366dae421af3c89286ebb6239047a31a46451758d4a06bc85  /tmp/a2f271f5eef07da366dae421af3c89286ebb6239047a31a46451758d4a06bc85.tar.gz
stesachs@ip-10-0-6-68:~$ spack checksum aocl-utils@4.1
==> Selected 1 of 2 versions. 0 new versions. Filtered by @4.1
  4.1  https://github.com/amd/aocl-utils/archive/refs/tags/4.1.tar.gz

==> Enter number of versions to take, or use a command:
    [c]hecksum  [e]dit  [f]ilter  [a]sk each  [n]ew only  [r]estart  [q]uit
action> c
==> Fetching https://github.com/amd/aocl-utils/archive/refs/tags/4.1.tar.gz

    version("4.1", sha256="660746e7770dd195059ec25e124759b126ee9f060f43302d13354560ca76c02c")
```

**Review by amd-toolchain-support — APPROVED** [review]
Fantastic thank you @stephenmsachs 

Question for Spack dev team: Will the Spack mirror update itself automatically, or will intervention be required?

**Comment by tldahlgren** [comment]
> Question for Spack dev team: Will the Spack mirror update itself automatically, or will intervention be required?

It will get stored with the new sha256.

**Review by tldahlgren — APPROVED** [review]
Confirmed the new sha256s.

**Pull request merged**
