### PR TITLE
boost %oneapi: apply existing patch to @1.76.0:1.79.0

### PR DESCRIPTION
**Pull request by eugeneswalker**
This patch is apparently needed for `boost@1.76:1.79` in some cases.

Without this patch, trying to `spack install boost@1.79.0%oneapi@2022.1.0 +atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~graph_parallel~icu+iostreams~json+locale+log+math+mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave cxxstd=17 visibility=hidden` leads to:
```
...
     19411    For more information, use '-qnextgen-diag'.
     19412    option list:
     19413    	-ip
  >> 19414    clang++: error: no such file or directory: 'bin.v2/libs/math/build/intel-linux-2022.1.0/release/cxxstd-17-iso/threading-multi/visibility-hidden/pch.pchi'
  >> 19415    clang++: error: unsupported argument 'h-create' to option '-pc'
     19416
```

Ref: https://www.intel.com/content/www/us/en/developer/articles/technical/building-boost-with-oneapi.html

### CODE REVIEW

**Comment by hainest** [comment]
That site says this is needed since 1.75.0. I looked at the relevant jamfile in Boost.Build source and confirmed it's the same as for 1.79. Should we include the lower-bound here, as well? I have not tested oneapi builds for Boost.

**Comment by eugeneswalker** [comment]
> That site says this is needed since 1.75.0. I looked at the relevant jamfile in Boost.Build source and confirmed it's the same as for 1.79. Should we include the lower-bound here, as well? I have not tested oneapi builds for Boost.

The current patch applies OK, and the subsequent builds succeed, for:
* `@1.76.0`
* `@1.77.0`
* `@1.78.0`
* `@1.79.0`

But trying to apply the current patch to `@1.75.0` shows:
```
$> spack install boost@1.75.0%oneapi@2022.1.0 +atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~graph_parallel~icu+iostreams~json+locale+log+math+mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave cxxstd=17 visibility=hidden ^mpich
==> Installing boost-1.75.0-p2f7ryl4smxc5psrrr2vi6glh2yvifl4
==> Fetching https://mirror.spack.io/_source-cache/archive/95/953db31e016db7bb207f11432bef7df100516eeb746843fa0486a222e3fd49cb.tar.bz2
==> Applied patch /spack/var/spack/repos/builtin/packages/boost/bootstrap-toolset.patch
1 out of 1 hunk FAILED -- saving rejects to file tools/build/src/tools/intel-linux.jam.rej
==> Patch /spack/var/spack/repos/builtin/packages/boost/1.78-intel-linux-jam.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/spack/var/spack/repos/builtin/packages/boost/1.78-intel-linux-jam.patch' '-d' '.'

real	1m0.546s
user	0m52.709s
sys	0m7.889s
```

What do you think? Should I update this PR to apply the patch to `boost@1.76:1.79` ?

**Comment by eugeneswalker** [comment]
> What do you think? Should I update this PR to apply the patch to `boost@1.76:1.79` ?

Done

**Comment by eugeneswalker** [comment]
Do you approve of this @hainest ? It fixes build of all those versions. I would like to get merged ASAP if you do approve! All tests are passing. Thank you!

**Review by hainest — APPROVED** [review]

**Comment by hainest** [comment]
If it's testing for you, then LGTM.

**Review by wspear — APPROVED** [review]

**Pull request merged**
