### PR TITLE
editres: add v1.0.8

### PR DESCRIPTION
**Pull request by alecbcs**
Add editres v1.0.8.

**Changelog:**
https://cgit.freedesktop.org/xorg/app/editres/log/

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by alecbcs** [comment]
@tldahlgren do you know how to restart a failed docs generate?

**Comment by tldahlgren** [comment]
> @tldahlgren do you know how to restart a failed docs generate?

AFAIK that has to be triggered by an update or push.

**Comment by alecbcs** [comment]
Gotcha! I merged in develop to see if it'll run again. Not sure why it get stuck before and didn't report a status.

**Comment by tldahlgren** [comment]
> Gotcha! I merged in develop to see if it'll run again. Not sure why it get stuck before and didn't report a status.

Sometimes there are delays between a push and updates to check statuses.  Not sure how much a page refresh helps but I've been known to do a few in a row when I'm impatient. 😁

**Pull request merged**
