### PR TITLE
Use __skip_rocmclang for cmake 3.21 in rocblas/rocfft to avoid incomplete compiler support

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by haampie** [comment]
@srekolam could you try this on top of #25246?

**Comment by cgmb** [comment]
I suspect this will be necessary for just about every ROCm library on CMake 3.21. It was a problem in rocSOLVER as well. [And rocRAND](https://github.com/ROCmSoftwarePlatform/rocRAND/issues/198).

**Comment by srekolam** [comment]
sure...i will do that and will let you know. Thanks.
I will add the proposed fix to the other recipes too.

**Comment by srekolam** [comment]
i have verified the rocfft,rocblas for 4.2.0 release. it builds with out any failure.

**Review by srekolam — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
