### PR TITLE
Mesa(18): Use libllvm virtual package

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Depends on #28364 for the Mesa patch to work as expected with the llvm-amdgpu package.

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
@chuckatkins

**Comment by kwryankrattiger** [comment]
@chuckatkins

**Comment by kwryankrattiger** [comment]
This can now replace the need for #28364. @trws @chuckatkins

**Review by trws — DISMISSED** [review]
Looks good to me.

**Review by chuckatkins — APPROVED** [review]

**Pull request merged**
