### PR TITLE
Make hwloc both CudaPackage and ROCmPackage

### LINKED ISSUE #32944: Installation issue: hwloc+rocm
### Steps to reproduce the issue

```console
$ spack install hwloc+rocm
```

### Error message

```
/builds/spack/spack/var/spack/repos/builtin/packages/hwloc/package.py:170, in configure_args:
        167            args.append("--disable-rsmi")
        168
        169        if "+rocm" in self.spec:
  >>    170            args.append("--with-rocm={0}".format(self.spec["rocm"].prefix))
        171            args.append("--with-rocm-version={0}".format(self.spec["rocm"].version))
        172
        173        if "+netloc" in self.spec:
```
The problem is that there is no `rocm` package in Spack. Should it instead be `rocm-smi-lib`?

### Information on your system

* **Spack:** 0.19.0.dev0 (8698ca310e15d799a63d96dfc00f1b5cf71319cd)
* **Python:** 3.9.13
* **Platform:** linux-amzn2-x86_64_v4
* **Concretizer:** clingo

### Additional information

@bgoglin @bvanessen this bug was introduced in #30788

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by wyphan**
This fixes `spack install hwloc+rocm`.

Fixes #32944

### CODE REVIEW

**Comment by wyphan** [comment]
@spackbot maintainers

**Comment by kwryankrattiger** [comment]
You should be able to remove the old `rocm` and `cuda` variants since they are redundant with the variants from the meta packages.

**Comment by bgoglin** [comment]
Looks like I don't know spack enough to review this. At least I don't know why "rocm" is replaced with "hip" in first commit.

**Comment by kwryankrattiger** [comment]
@bgoglin 
> At least I don't know why "rocm" is replaced with "hip" in first commit.

The reason is there isn't a package or spec `rocm` that spack can index and get a version from, `hip` is sort of the root of that stack, and shares the same version as the ROCm stack.

**Comment by bgoglin** [comment]
Sorry but this is too spack-specific for me to provide a review with even minimal confidence.

**Comment by wyphan** [comment]
@kwryankrattiger for some reason I can't add you as reviewer, but please go ahead and review it

**Review by kwryankrattiger — DISMISSED** [review]
Tested and seems to work for me +2

**Review by adamjstewart — APPROVED** [review]
LGTM, will give @bvanessen a chance to review

**Comment by kwryankrattiger** [comment]
@wyphan I think you will need to rebase this to get the CI changes that went in awhile ago to get those last checks to pass.

**Comment by wyphan** [comment]
Hmm, it wouldn't let me rebase due to conflicts, but a merge seems to work.

**Review by bvanessen — APPROVED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Pull request merged**
