### PR TITLE
gdbm: add 1.23

### PR DESCRIPTION
**Pull request by michaelkuhn**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by vsoch** [comment]
y'all this new gdbm version is breaking all our builds that use it - I don't think the source code is reliable?

image

cc @trws and @davidbeckingsale

**Comment by trws** [comment]
The hash ~is wrong:~ did not match a cached copy I somehow got from the gnu mirrors yesterday.

```
Expected 74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd but got 3e42ec3d78c7a166c282c546adb16f0176f2a4b310c6a83e64894afc92d7c436
```

**Comment by vsoch** [comment]
I opened a PR with that hash (@trws I'm not testing building this locally so I'm using your copy pasta!)

**Comment by alalazo** [comment]
@vsoch @trws The checksum ` 74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd` looks correct on my machine :thinking:

**Comment by trws** [comment]
That is a definite concern... are there different packages in different mirrors?

**Comment by alalazo** [comment]
Just tried from the shell:
```console
$ wget https://ftpmirror.gnu.org/gdbm/gdbm-1.23.tar.gz
$ sha256sum gdbm-1.23.tar.gz 
74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd  gdbm-1.23.tar.gz
```

**Comment by alalazo** [comment]
@trws @vsoch I just verified the sha1:
```console
$ sha1sum gdbm-1.23.tar.gz 
50ba1b1d45ce33fd44e4fdaaf3b55a9d8f3dc418  gdbm-1.23.tar.gz
$ sha256sum gdbm-1.23.tar.gz 
74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd  gdbm-1.23.tar.gz
```
What is in Spack right now matches what is advertised at https://www.gnu.org.ua/software/gdbm/download.html

**Comment by trws** [comment]
I don't dispute that, but the same URL has given us different hashes.  Including a cached version in a spack I have on a local machine right now.  It looks like things are now behaving consistently for newly fetched copies, but something strange happened here.  That said, it looks like what's here is the right one at this point.

**Comment by alalazo** [comment]
> I don't dispute that, but the same URL has given us different hashes

:worried: Yeah, I was trying to verify the sha1 to be sure we didn't have anything wrong in the mirror - but apparently `gdbm` has not yet been mirrored in `https://mirror.spack.io`

**Comment by trws** [comment]
That's probably a good thing really, maybe it got swapped out sometime yesterday and we happened to catch it across the swap?

**Pull request merged**
