### PR TITLE
disable oneapi for m4

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by hpcnpatel** [comment]
Hi There; we have been dealing with m4 and autoconf % oneapi issues lately. 

Whenever we use %oneapi to build m4 and autoconf we see these warnings,

        # > configure:6067: icx -c -g  conftest.c >&5
        # > icx: remark: Note that use of '-g' without any optimization-level option will turn 
        # > off most compiler optimizations similar to use of '-O0'; 
        # > use '-Rno-debug-disables-optimization' to disable this remark [-Rdebug-disables-optimization]

I am not sure if this warning breaks dependents of m4 when %oneapi, but more likely: the default optimization level for icx/icpx is "-O2", but building m4 with this level breaks the build of autoconf. 

So the solution for us is to set CFLAGS explicitely to "-O0".

something like,

```
        if self.spec.satisfies("%intel") or self.spec.satisfies("%oneapi"):
            env.append_flags("CFLAGS", "-O0")
```

Do you think this is a solution or another approach? Instead of a conflict that might be too strict?

**Comment by rscohn2** [comment]
> Do you think this is a solution or another approach? Instead of a conflict that might be too strict?

I didn't know `-O0` would fix it. If you want to submit a PR I can close this one and approve yours. The m4 issue makes it hard to build many applications.

**Comment by hpcnpatel** [comment]
I would open a PR with the change proposed. I am building a software stack for our users and realized the same as you mentioned.

**Comment by hpcnpatel** [comment]
FYR, https://github.com/spack/spack/pull/36835

**Comment by rscohn2** [comment]
Resolved by #36835

**Pull request closed without merging**
