### PR TITLE
precice: add release v2.5.1

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds the hotfix release 2.5.1 of the xSDK member preCICE.

### CODE REVIEW

**Review by MakisH — COMMENTED** [review]
The checksum is correct. No updates are needed in terms of dependencies.

This release also fixes compatibility with libxml version 2.12.0. @fsimonis does it make sense to mark this compatibility detail similarly to boost?

**Review by tldahlgren — APPROVED** [review]
Confirmed the new version sha256.

**Comment by tldahlgren** [comment]
@fsimonis @MakisH Let me know when this PR is ready to merge.

**Comment by fsimonis** [comment]
@tldahlgren thanks for the quick review!

It's ready to merge. We will submit dependency updates at a later date.

**Pull request merged**
