### PR TITLE
geant4: new version 11.1.1

### PR DESCRIPTION
**Pull request by wdconinc**
Bugfix release only. No changes in build system.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Adding @drbenmorgan since he is the package's maintainer.

**Comment by wdconinc** [comment]
@spackbot down?

**Comment by tldahlgren** [comment]
> @spackbot down?

Looks like Spack CI needs to catch up.

**Review by drbenmorgan — APPROVED** [review]
All good, thanks @wdconinc !

**Pull request merged**
