### PR TITLE
python: fix bug building matplotlib source files w/ C-specific flags

### PR DESCRIPTION
**Pull request by xjrc**
The changes in this pull request fix a bug in the `py-matplotlib` package that was causing builds with C-specific flags (e.g. `-std=c11`) to fail due to being used to compile C++ files. I've verified that the `py-matplotlib@1.5.3` variant compiles in the `clang%9.0.0 arch=linux-rhel7-power9le` build environment.

As an aside, I'm not thrilled with this fix as it feels very kludgey, but I'm unaware of an alternative for setting the compiler used during the `setup.py` build phase. If there are less clumsy alternatives, please let me know.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I have a few questions about this:

1. Does matplotlib _only_ contain C++ files, or does it contain both C and C++ files?
2. Are the matplotlib developers aware of this issue? Do they suggest any workaround?
3. Have you tried building matplotlib 3.X with these changes? I don't know how many users even use matplotlib 1.X.

**Comment by xjrc** [comment]
@adamjstewart: Here's what I was able to gather:

> 1. Does matplotlib only contain C++ files, or does it contain both C and C++ files?

I've skimmed through the `src` directories of `matplotlib@1.5.3`, `matplotlib@2.2.5`, and `matplotlib@3.2.1`, and all of these iterations of the code include both C and C++ files.

> 2. Are the matplotlib developers aware of this issue? Do they suggest any workaround?

I did some digging through the `matplotlib` project's [official install instructions](https://matplotlib.org/users/installing.html#installing-from-source) and its [issue tracker](https://github.com/matplotlib/matplotlib/issues?page=1&q=C%2B%2B+compiler) and the closest thing I was able to find in reference to building with a C++ compiler was [this issue](https://github.com/matplotlib/matplotlib/pull/1454). Looking at this issue (specifically, the embedded fact that `matplotlib` uses the `PyCXX` library), it's clear that `matplotlib` needs to build at least in part with a C++ compiler, but this seems to clash with Python's `setup.py` infrastructure, which [only checks/uses the `CC` environment variable](https://stackoverflow.com/a/16737674) when building extensions. With these constraints, `CC` replacement seems like the easiest and most convenient solution, but something more comprehensive may involve filtering code-specific flags (e.g. `-std=c++11`) when compiling `matplotlib`.

> 3. Have you tried building matplotlib 3.X with these changes? I don't know how many users even use matplotlib 1.X.

I haven't tried building `matplotlib@3.X` yet (I need to install a `python@3:` stack as a prerequisite, which may take some time), but I have built `matplotlib@2.2.5` and I found that it has the same issue. I will try a newer version though to properly constrain the version range of this fix.

**EDIT**: I also just tried `py-matplotlib@3.2.1` and got the same error related to using C-specific flags when compiling C++ files (this may be limited to `clang`; I haven't tested any other compilers). Interestingly, this error appears to affect `py-kiwisolver` as well (required by `py-matplotlib@2.2.0:`) , and can use the same `CC=${CXX}` approach as a fix.

**Comment by adamjstewart** [comment]
Are you using LLVM Clang? I've never encountered this problem with Apple Clang.

**Comment by xjrc** [comment]
Yes, I've been using LLVM clang for these builds.

**Comment by xjrc** [comment]
Would there be any way to restrict this workaround to just the LLVM clang compiler? The best I can think of off the top of my head is:

```
@when('%clang os=linux')
def setup_build_environment(self, env):
   # ... #
```

**Comment by adamjstewart** [comment]
Yeah, that's about as good as you can do. You can also have a `if not self.spec.satisfies('%clang platform=darwin')`, which would allow a few more OSes. I once opened an issue about splitting Apple Clang and Clang into separate compilers.

Are C++ compilers generally capable of compiling C code?

**Comment by xjrc** [comment]
I've never encountered any C/C++ compatibility issues, but [C++ isn't strictly backwards-compatible with C](https://en.wikipedia.org/wiki/Compatibility_of_C_and_C%2B%2B#Constructs_that_behave_differently_in_C_and_C++), so this isn't a bulletproof solution by any means. I imagine it will work fine for `py-matplotlib` because it seems to target C++ and its C subset, but extending this solution to other packages may cause compatibility issues to crop up. 

As an aside, some rudimentary testing with `gcc/g++` indicates that this flag problem exists beyond non-Apple `clang/clang++`, but `clang++` is the only compiler to treat it as an error. This explains why none of my other installs (which use similar flags) have been halted by this either.

**Comment by adamjstewart** [comment]
What's the exact error message you were seeing? Can you reproduce the problem on any other system? Does your `compilers.yaml` inject the `-std=c11` flag, or is that done by matplotlib?

**Comment by xjrc** [comment]
The exact error message is:

```
/path/to/spack/lib/spack/env/clang/clang -fno-strict-aliasing -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/path/to/spack/install-blueos-0601/linux-rhel7-power9le/clang-9.0.0/py-numpy-1.11.3-7cxb4ntdbcrbpurhvqjey23ntumxlgut/lib/python2.7/site-packages/numpy/core/include -I/path/to/spack/install-blueos-0601/linux-rhel7-power9le/clang-9.0.0/libpng-1.6.37-gi2b6due7qgd3k6i5lf26qywpdyd2hkq/include/libpng16 -I/path/to/spack/install-blueos-0601/linux-rhel7-power9le/clang-9.0.0/zlib-1.2.11-yzrmp2hpaclmynokgwxdktpielm26lpp/include -I/path/to/spack/install-blueos-0601/linux-rhel7-power9le/clang-9.0.0/freetype-2.10.1-swablvo4i6uz3sqkyewa5q4kt5zik7mc/include/freetype2 -I/usr/local/include -I/usr/include -I. -I/path/to/spack/install-blueos-0601/linux-rhel7-power9le/clang-9.0.0/python-2.7.12-sw4n55ldlnoy3driiycho4yr4rm2d4ig/include/python2.7 -c src/ft2font.cpp -o build/temp.linux-ppc64le-2.7/src/ft2font.o
>> 2404    error: invalid argument '-std=gnu11' not allowed with 'C++'
>> 2405    error: command '/path/to/spack/lib/spack/env/clang/clang' failed with exit status 1
```

I've reproduced this problem by running `clang -std=gnu11 main.cpp` on a trivial `main.cpp` program on another platform (specifically, `arch=linux-rhel7-broadwell`). Also, the `-std=gnu11` injection is performed by my `compilers.yaml` configuration and not `py-matplotlib`.

It seems that this bug is unique to Python packages that contain C++ files because their Spack builds use the C compiler. This is normally is not an issue, except it seems for picky compilers like GNU `clang`, which dislikes inapplicable flags to the point of throwing errors.

**Comment by adamjstewart** [comment]
Can we patch things to not add `-std=c11`?

**Comment by xjrc** [comment]
Is such a thing possible for flags embedded via `compilers.yaml`? If it is, then I think the best solution would involve updating `PythonPackage` to remove all configured C++-specific flags from the compile line when building Python source files.

**Comment by adamjstewart** [comment]
@scheibelp or @becker33 would know how to do this.

It sounds like this is a better solution because the same thing might be needed for every Python package, not just matplotlib.

**Comment by becker33** [comment]
It seems like the underlying problem is that the Spack builds of python tools are using the C compiler for C++ code. @xjrc is that accurate?

**Comment by becker33** [comment]
@xjrc are you sure this issue is restricted to clang and non-darwin builds? It looks like it would be a problem for every build.

**Comment by becker33** [comment]
If I understand this correctly, it should be in `setup_build_environment` in `lib/spack/spack/build_systems/python.py`, and we should make sure all subclasses call the superclass method through code review.

**Comment by becker33** [comment]
@adamjstewart I don't think the correct solution is to filter the flags, because the underlying problem is that we're using the wrong compiler, not that we're giving it the wrong flags. The latter is just the only reason we noticed.

**Comment by xjrc** [comment]
@becker33

> It seems like the underlying problem is that the Spack builds of python tools are using the C compiler for C++ code. @xjrc is that accurate?

Yes, that is exactly right. This issue made tricky by the fact that Python's `setup.py` build infrastructure [is set to configure the compiler exclusively via the `CC` environment variable](https://stackoverflow.com/a/16737674) and some packages (e.g. `py-matplotlib`) compile both C and C++ files.

> @xjrc are you sure this issue is restricted to clang and non-darwin builds? It looks like it would be a problem for every build.

The only thing I'm certain about is that it affects Linux `clang` and not Linux `gcc` (and this is true across the couple of Linux platforms I've tested). `gcc` reports the mismatch in file language/compiler flags as a warning, where `clang` throws an error.

**Comment by adamjstewart** [comment]
> @xjrc are you sure this issue is restricted to clang and non-darwin builds?

To add to this, I don't have this problem with Apple Clang, but I'm also not injecting any flags via `compilers.yaml`.

**Comment by xjrc** [comment]
> If I understand this correctly, it should be in `setup_build_environment` in `lib/spack/spack/build_systems/python.py`, and we should make sure all subclasses call the superclass method through code review.

> @adamjstewart I don't think the correct solution is to filter the flags, because the underlying problem is that we're using the wrong compiler, not that we're giving it the wrong flags. The latter is just the only reason we noticed.

Would you propose then, Greg, that we poke around a given Python package for C++ files and adjust the `CC` environment variable if such files are detected? This seems like a reasonable solution to me, and it skirts the problem of identifying all compiler flags that could affect C/C++ mismatches and filtering these out of Python builds.

**Comment by becker33** [comment]
@xjrc Looking around some more, I think we need to do something like https://github.com/NixOS/nixpkgs/pull/19585/files in order to have this work for packages containing both C and C++ code.

@adamjstewart you've done more support for the python ecosystem than I have, do you agree with this? It looks like the NixOS folk are trying to upstream as much of this as possible, but as they pointed out no one is going to release a bugfix for python 2 anymore.

**Comment by xjrc** [comment]
@becker33: I've implemented a solution that uses the patches you suggested. It looks like Python 3 versions of these patches exist (see [this Python patch](https://bugs.python.org/issue1222585)), but I'm only applying those for Python 2 in adherence to NixOS's philosophy regarding likelihood of upstream patching. We could continue to follow NixOS's example by only applying this patch for non-GCC compilers; I'll leave that decision up to you and @adamjstewart. Aside from that detail, I consider this pull request to now be ready (I've reverified the install of `py-matplotlib@1.5.3%clang@9.0.0 arch=linux-rhel7-power9le`).

**Comment by adamjstewart** [comment]
I'm fine with patching for all compilers. I would personally patch both Python 2 and 3, upstreaming Python fixes can take years.

Another thing to note is that this won't work for external Python installations.

**Comment by xjrc** [comment]
That's a great point @adamjstewart. I'll make this patch a default-off variant instead (e.g. `cppmods`) to improve external compatibility and then mark `@conflicts` for the variants of the modules we know have C++ files (e.g. `py-matplotlib%clang ^python~cppmods`, `py-kiwisolver%clang  ^python~cppmods`).

**Comment by adamjstewart** [comment]
I don't usually like to add variants for patches. In the long run, we can hope that external Python will be patched upstream someday. Also, those checks aren't actually correct for Apple Clang (we're thinking about splitting LLVM Clang and Apple Clang into separate compilers someday).

**Comment by xjrc** [comment]
I'm not fond of adding a variant for this purpose either, but it seems to me the only way we can accurately support externals until the upstream is patched (which may never happen for `python@2`). I fear that failing to account for this nuance now could lead someone to repeat all the debugging we've done here. Perhaps the chance of this is small enough where it's outweighed by the inconvenience of updating python once the patches reach the upstream; it's hard to say.

And yes, you're correct; the variants should be `py-matplotlib%clang platform=linux ^python~cppmods`, `py-kiwisolver%clang platform=linux ^python~cppmods` instead (the platform is actually just "not darwin", but I don't think this can be expressed with Spack's spec syntax; I'd likely use an `if` statement instead for this occasion).

**Comment by adamjstewart** [comment]
How many years has matplotlib contained C++ code? As far as I know, you're the first user to stumble on this problem, so if we make this bug more rare than it already is (only affects external Python installations) then I think we'll be safe.

**Comment by xjrc** [comment]
You make a good point; the likelihood is quite low, and hopefully anyone that comes afterward can search through the issues for "matplotlib" and "external python" to find this issue. I'll proceed with a general, non-variant application of this patch.

**Comment by becker33** [comment]
@xjrc If you could add a comment pointing back to this PR to the patch in the python package, that could help a future user find the issue with an external python.

**Comment by xjrc** [comment]
I've updated the `python` package to include documentation linking back to this PR and all of the necessary patches to support the C++ `distuils` fix. Three patches for different version ranges were required (i.e. `@2.7`, `@3.6`, `@3.7:3.8`) due to the nontrivial number of files patched and to the inconsistency of these files across versions.

In order to verify the correctness of these changes, I used `py-kiwisolver` as a test module because [it contains C++ source files](https://github.com/nucleic/kiwi/blob/master/setup.py#L29) and has fewer dependencies than `py-matplotlib`. I've verified that the following variants of this package install using `%clang@9.0.0` in the build environment `arch=linux-rhel7-power9le`:

- `py-kiwisolver ^python@3.8.3`
- `py-kiwisolver ^python@3.7.7`
- `py-kiwisolver ^python@3.6.8`
- `py-kiwisolver ^python@2.7.12`

I've also verified that `py-matplotlib@3.2.1` (a Python3 version) and `py-matplotlib@1.5.3` (a Python2 version) both install in this environment just to be certain this PR is addressing the issue it was intended to fix.

As an aside, the `@3.6` patch doesn't work with earlier versions of Python (I tried versions as recent as `@3.5.7`), but it looks like [patches for these versions may exist](https://bugs.python.org/issue1222585) and could be integrated by any intrepid developer that so needs them!

**Comment by xjrc** [comment]
@becker33, @adamjstewart: I think that this PR is ready; please let me know if I need to make any additional changes.

**Review by becker33 — APPROVED** [review]

**Comment by becker33** [comment]
That was an absolute mess of a bug! Thanks for taking that on!

**Comment by scottwittenburg** [comment]
I just noticed that after this PR was merged, pipelines started failing on gitlab.spack.io due to a failure to build `python`.  Here's an excerpt from the relevant pipeline log (just the exciting part I hope):

```
==> [2020-06-16-18:03:00.121348, 174] '/usr/bin/curl' '-C' '-' '-o' '/tmp/root/spack-stage/spack-stage-python-3.7.3-ltvxpgx4f2dqaxxahnqfkiezrrdvcczo/Python-3.7.3.tgz.part' '-f' '-D' '-' '-L' 'https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz' '-k' '-sS' '--connect-timeout' '10'
==> [2020-06-16-18:03:00.397636, 174] '/bin/tar' '-xf' '/tmp/root/spack-stage/spack-stage-python-3.7.3-ltvxpgx4f2dqaxxahnqfkiezrrdvcczo/Python-3.7.3.tgz'
==> [2020-06-16-18:03:01.152578, 174] '/usr/bin/patch' '-s' '-p' '1' '-i' '/builds/spack/e4s/spack/var/spack/repos/builtin/packages/python/python-3.7+-distutils-C++.patch' '-d' '.'
==> [2020-06-16-18:03:01.161390, 174] ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/builds/spack/e4s/spack/var/spack/repos/builtin/packages/python/python-3.7+-distutils-C++.patch' '-d' '.'
==> [2020-06-16-18:03:01.175726, 168] Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/builds/spack/e4s/spack/var/spack/repos/builtin/packages/python/python-3.7+-distutils-C++.patch' '-d' '.'
Traceback (most recent call last):
  File "/builds/spack/e4s/spack/lib/spack/spack/build_environment.py", line 819, in child_process
    return_value = function()
  File "/builds/spack/e4s/spack/lib/spack/spack/installer.py", line 1063, in build_process
    pkg.do_patch()
  File "/builds/spack/e4s/spack/lib/spack/spack/package.py", line 1222, in do_patch
    patch.apply(self.stage)
  File "/builds/spack/e4s/spack/lib/spack/spack/patch.py", line 86, in apply
    apply_patch(stage, self.path, self.level, self.working_dir)
  File "/builds/spack/e4s/spack/lib/spack/spack/patch.py", line 41, in apply_patch
    '-d', working_dir)
  File "/builds/spack/e4s/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
```

Does it make sense that error could have been caused by this PR?

I'm attaching the full pipeline log below, in case the extra details are useful.

[pipeline_log - 2020-06-16T135656.739.txt](https://github.com/spack/spack/files/4788869/pipeline_log.-.2020-06-16T135656.739.txt)

**Comment by xjrc** [comment]
It's absolutely possible that this PR could cause Python builds to fail; I only tried it on one platform, so other platforms could be encountering issues. I will look into this presently.

**Comment by scottwittenburg** [comment]
Cool, thank you @xjrc!  

If you're looking for a bit more information, the build job ran in the following Docker container: `ecpe4s/ubuntu18.04-spack:0.14.2`.  However, in spite of that container name, spack was cloned from main repo, and the SHA `0095c4c25c459b5d7d25ce0462eed753b4036166` was checked out in order to run the build.  Barring some slight differences I don't imagine will make a difference in this case, it's likely you could use that image to reproduce the build failure.  If you have trouble reproducing the problem, maybe just respond here and I'll help in any way I can.

**Comment by xjrc** [comment]
Thanks for the information, @scottwittenburg. I'm not familiar with Spack's Docker infrastructure, so I'll have to lean on you and @becker33 for help should we need to replicate in exactly that environment. I suspect that this issue is being caused by a set of conflicting patches, so I'm hopeful that I can replicate/resolve it in my own development environment. I'm building a similar variant now (i.e. `python@3.7.3%gcc@4.9.3 arch=linux-rhel7-broadwell patches=(same hash)`) and I'll see where it takes me.

**Comment by xjrc** [comment]
Fortunately, the issue is simpler than I thought; `python-3.7+-distutils-C++.patch` simply doesn't apply to `python@3.7.3` since its `distutils` source files differ from `python@3.7.7:`, so we just need to move the patches around. I had assumed testing the highest patch numbers of each minor release would be sufficient, but evidently Python's internals change with even patch-level fluidity. I'll do some tinkering to ensure the patches work for all Python versions in the range `@:2.8,3.6:`.

**Comment by scottwittenburg** [comment]
Awesome @xjrc, thanks for tracking it down.  And so quickly!

**Pull request merged**
