### PR TITLE
spack audit: allow skipping version checks from package.py

### LINKED ISSUE #28256: spack audit packages: CUDA issues on macOS
### Steps to reproduce

On macOS, run:
```console
$ spack audit packages
```

### Error message

Spack reports thousands of CUDA version issues because CUDA is not supported on macOS:
```console
$ spack audit packages
PKG-DIRECTIVES: 2659 issues found
1. 3dtk: dependency on cuda cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/3dtk/package.py
    known versions of cuda are 
2. accfft: dependency on cuda cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/accfft/package.py
    known versions of cuda are 
3. accfft: dependency on cuda@:6.0 cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/accfft/package.py
    known versions of cuda are 
4. accfft: dependency on cuda@:6.5 cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/accfft/package.py
    known versions of cuda are 
5. accfft: dependency on cuda@2.1:6.5 cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/accfft/package.py
    known versions of cuda are 
...
2655. zfp: dependency on cuda@9.0: cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/zfp/package.py
    known versions of cuda are 
2656. zfp: dependency on cuda@9.0: cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/zfp/package.py
    known versions of cuda are 
2657. zfp: dependency on cuda@10.0: cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/zfp/package.py
    known versions of cuda are 
2658. zfp: dependency on cuda@11.0: cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/zfp/package.py
    known versions of cuda are 
2659. zfp: dependency on cuda@11.1: cannot be satisfied by known versions of cuda
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/zfp/package.py
    known versions of cuda are 
```

### Information on your system

* **Spack:** 0.17.0-751-b23bd81cd9
* **Python:** 3.8.12
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes #28256

A few packages have version directives evaluated within if statements, conditional on the value of `platform.platform()`.

Sometimes there are no cases for e.g. `platform=darwin` and that causes a lot of spurious failures with version existence audits. This PR allows expressing conditions to skip version existence checks in audits and avoid these spurious reports.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
Still seeing a few issues:
```console
> spack audit packages                                                                                                                                                                                              0.1s
PKG-DIRECTIVES: 4 issues found
1. beast2: dependency on javafx cannot be satisfied by known versions of javafx
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/beast2/package.py
    known versions of javafx are 
2. hpctoolkit: dependency on hpcviewer@2022.10: cannot be satisfied by known versions of hpcviewer
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/hpctoolkit/package.py
    known versions of hpcviewer are 
3. hpctoolkit: dependency on hpcviewer cannot be satisfied by known versions of hpcviewer
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/hpctoolkit/package.py
    known versions of hpcviewer are 
4. timemory: dependency on arm-forge cannot be satisfied by known versions of arm-forge
    happening in /Users/Adam/spack/var/spack/repos/builtin/packages/timemory/package.py
    known versions of arm-forge are 
```

**Comment by alalazo** [comment]
@adamjstewart Can you fix them and push to my branch? I think those are issues with Apple M1, and that's why CI is passing. Also, the `hpctoolkit` one seems a bug in `hpcviewer`. Is `platform.machine()` returning "aarch64" or "arm64"?

**Review by adamjstewart — DISMISSED** [review]

**Comment by alalazo** [comment]
@mwkrentel Fyi, there's a bug spotted in this PR on `hpcviewer`, that Adam fixed in the last commit. Let me know if you have comments on that change.

**Comment by mwkrentel** [comment]
@adamjstewart   Is it possible that `platform.machine()` has changed?
Or could python from Xcode be an oddball ?

I don't have a Macbook M1/M2, but I remember about 1.5 years ago
asking someone else.  Either I totally misunderstood the answer, or
else the answer has changed.

Anyway, for hpcviewer, I'd prefer a different fix.
We use `aarch64` as part of the file name in the tar file.
That is, changing aarch64 to arm64 is not a complete fix.

So, take out all the "aarch64" --> "arm64" changes and replace with:

```
--- a/var/spack/repos/builtin/packages/hpcviewer/package.py
+++ b/var/spack/repos/builtin/packages/hpcviewer/package.py
@@ -178,6 +178,8 @@ class Hpcviewer(Package):
 
     system = platform.system().lower()
     machine = platform.machine().lower()
+    if machine == "arm64":
+        machine = "aarch64"
 
     # Versions for MacOSX / Darwin
     if system == "darwin":
```

The PR #28372 is pretty old.  But if it's going to be merged within a
few days, you could fold this into there.  Otherwise, I'd write a
separate PR just for hpcviewer.  Let me know.

**Comment by mwkrentel** [comment]
I'm wondering if openjdk needs any adjustment.
They seem to reference both Darwin-aarch64 and Darwin-arm64.

Well, maybe not adjustment, but they seem to think that the
Darwin-aarch64 case exists.

**Review by haampie — DISMISSED** [review]

**Review by haampie — APPROVED** [review]

**Pull request merged**
