### PR TITLE
kokkos: add v4.2.00

### PR DESCRIPTION
**Pull request by lucbv**
Following the release on github of version 4.2.00 of Kokkos Core we are updating the package.py accordingly!

### CODE REVIEW

**Comment by lucbv** [comment]
Once this is merged a similar PR for Kokkos Kernels will be issued based on the changes in this one.
@crtrott @dalg24 are there any changes to the build system or the build options that should be updated for 4.2.00 in the spack package?

**Comment by rbberger** [comment]
This is missing the changes in `amdgpu_arch_map`.

**Comment by lucbv** [comment]
@rbberger good point, I am adding the new AMD GPU arch

**Comment by masterleinad** [comment]
Given the problems in https://github.com/spack/spack/pull/40565, it might be good to add an option for `oneDPL` and disable it by default (even when `SYCL` support is requested).

**Comment by crtrott** [comment]
@tgamblin what is the policy here for breackage downstream. The E4S OneAPI build is failing (with both 4.0 and 4.2 actually). The thing is that a) Kokkos is very sensitive to the compiler version for SYCL, and different versions of Kokkos only work with different versions of the compiler because Intel is breaking their compiler all the time for us, and b) because SYCL support is experimental we do accept certain breakage in specific situations for our tests - for example because we are waiting for a compiler fix. We ourselves in our internal CI exclude those tests. In this case E4S is blithely triggering everything and apparently with whatever compiler they deem best. And this is blocking the merge of this spack package update. We can't guarantee for experimental capabilities that whatever compiler some downstream thing uses and whatever test settings they use, that it will just work. Any suggestions how to proceed?

Christian

**Comment by tgamblin** [comment]
@crtrott are there particular supported compilers you'd *like* us to test? We don't currently have a policy on what version of OneAPI we're running in CI, but we can update it to make more sense here.  I think it's likely that you know better what versions of OneAPI to test than anyone, so I wouldn't oppose updating that in the OneAPI stack to match what Kokkos needs.

@eugeneswalker @rscohn2: Do you have a preference or a set of recommendations for how we should  roll the tested oneapi versions forward?

**Comment by crtrott** [comment]
There are a couple issues here: one is that its not clear that there IS a compiler version which will work with both 4.0 and 4.2 for SYCL support (its fine for other stuff, like just Host-OpenMP). The bigger problem is that E4S is running our internal tests in a situation where we don't guarantee that it will work. I mean we can control what the Kokkos spack package runs in terms of tests, but someone else turning on our tests for their spack package is a somewhat awkward situation. Maybe we need to set up a meeting with E4S and figuring out what its spack policy should be.

**Comment by tgamblin** [comment]
@crtrott: I do think it would be good to talk to the E4S folks -- @eugeneswalker want to set up a time to talk to @crtrott?

In the meantime, though, note that the stack changes don't have to be limited to just the E4S team.  i.e., you can modify it, iterate, and discuss here if you want.  I think that stack was originally set up to catch errors in the open oneapi release (even though there was a slightly different oneapi used internally).  The stack mainly ensures that we catch compiler errors early -- it's not set in stone.

You can see the whole thing here:
* https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml

Note that no specific version of `kokkos` is listed there -- if two are being built it's because something else in the stack is requiring the older 4.0 version.  I'd be curious to know what that is. @eugeneswalker knows better than I do.

**Comment by eugeneswalker** [comment]
> There are a couple issues here: one is that its not clear that there IS a compiler version which will work with both 4.0 and 4.2 for SYCL support (its fine for other stuff, like just Host-OpenMP). The bigger problem is that E4S is running our internal tests in a situation where we don't guarantee that it will work.

What do you mean we are running your internal tests? We are merely building kokkos with the `+tests` variant which is exposed to everyone via the official kokkos spack package. We could turn it off it would help.
https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml#L205-L206

> In this case E4S is blithely triggering everything and apparently with whatever compiler they deem best. 

We are using what was, until about a week ago, the *latest* official OneAPI compiler coming from Intel's latest official OneAPI container image. In what sense is this arbitrary and in what sense is it blithely? We are happy to disable things if they should be disabled, or alter our configuration to defer to what you and your team knows is best RE kokkos. As far as I know, no one has asked us about this up until now. We do not want to hold up new releases.

**Comment by eugeneswalker** [comment]
> @eugeneswalker want to set up a time to talk to @crtrott?

Of course.

> The stack mainly ensures that we catch compiler errors early -- it's not set in stone.

It is definitely not set in stone and we want to know if it needs improvement.

> Note that no specific version of `kokkos` is listed there -- if two are being built it's because something else in the stack is requiring the older 4.0 version. I'd be curious to know what that is. @eugeneswalker knows better than I do.

The current E4S OneAPI stack is here:
* https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml

Concretizing this environment using this PR branch brings kokkos in in a number of places
- `arborx` -- `^kokkos@4.2.00`
- `cabana` -- `^kokkos@4.2.00`
- `kokkos-kernels+openmp` -- `^kokkos@4.0.00`
- `trilinos+amesos+amesos2+anasazi+aztec+belos+boost+epetra+epetraext+ifpack+ifpack2+intrepid+intrepid2+isorropia+kokkos+minitensor+ml+muelu+nox+phalanx+piro+rol+rythmos+sacado+shards+shylu+stk+stokhos+stratimikos+superlu-dist+teko+tempus+tpetra+trilinoscouplings+zoltan+zoltan2 gotype=long_long` -- `^kokkos@4.1.00`
- `arborx+sycl ^kokkos+examples+openmp+sycl+tests cxxstd=17` -- `^kokkos@4.2.00`
- `cabana+sycl ^kokkos+examples+openmp+sycl+tests cxxstd=17` -- `^kokkos@4.2.00`
- `kokkos-kernels%oneapi build_type=Release ^kokkos+examples+openmp+sycl+tests cxxstd=17` -- `^kokkos@4.0.00`
- `petsc+sycl` -- `^kokkos@4.0.00 ^kokkos-kernels@4.0.00`

I think this is all the places `kokkos` comes in.

**Comment by tgamblin** [comment]
Thanks @eugeneswalker!

@crtrott: we can of course also pin the Kokkos version(s) in CI and allow the Kokkos package to move on w/o the latest versions getting tested.  Then we'd need policies around when the various packages @eugeneswalker mentioned would need to upgrade to a newer Kokkos.

**Comment by crtrott** [comment]
Apologies "blithely" might have been a bit harsh. Yes this thing is our test suite, what we do not guarantee however is that our test suite will actually completely pass for experimental backends. I.e. for experimental backends we accept "known failures" on occasion in particular if they stem from something which is compiler specific. Furthermore, for experimental backends we do not have a well defined "we support all compiler versions from here to there" policy. In fact the Intel compiler has been breaking us fairly frequently, so I wouldn't want to bet on say the next version of Intel OneAPI working with Kokkos 4.0 or 4.2. With production backends (CUDA, OpenMP, HIP, Serial, Threads) we do expect that all our tests work with a range of supported compilers.

We discussed a bit more, and probably the best approach is to modify E4S recipes as part of this thing to apply a patch to make that test work with that backend and that compiler. https://github.com/kokkos/kokkos/pull/6608/commits/ee655c08ad2188474f82930e20083ace0383e625

This will be part of 4.2.01 but didn't make the cut for 4.2.00.

My understanding is there is a patch process in spack we can utilize to work around this?

**Comment by masterleinad** [comment]
> My understanding is there is a patch process in spack we can utilize to work around this?

I would expect
```patch
diff --git a/var/spack/repos/builtin/packages/kokkos/package.py b/var/spack/repos/builtin/packages/kokkos/package.py
index 5eb7ce5cca..1b93408695 100644
--- a/var/spack/repos/builtin/packages/kokkos/package.py
+++ b/var/spack/repos/builtin/packages/kokkos/package.py
@@ -234,6 +234,7 @@ class Kokkos(CMakePackage, CudaPackage, ROCmPackage):
 
     # Patches
     patch("hpx_profiling_fences.patch", when="@3.5.00 +hpx")
+    patch("sycl_bhalft_test.patch", when="@4.2.00 +sycl")
 
     variant("shared", default=True, description="Build shared libraries")
 
diff --git a/var/spack/repos/builtin/packages/kokkos/sycl_bhalft_test.patch b/var/spack/repos/builtin/packages/kokkos/sycl_bhalft_test.patch
new file mode 100644
index 0000000000..dbe0b9a3bc
--- /dev/null
+++ b/var/spack/repos/builtin/packages/kokkos/sycl_bhalft_test.patch
@@ -0,0 +1,15 @@
+diff --git a/core/unit_test/TestNumericTraits.hpp b/core/unit_test/TestNumericTraits.hpp
+index f6fdc8376f..f197a2d889 100644
+--- a/core/unit_test/TestNumericTraits.hpp
++++ b/core/unit_test/TestNumericTraits.hpp
+@@ -110,8 +110,8 @@ struct TestNumericTraits {
+ 
+   KOKKOS_FUNCTION void operator()(Epsilon, int, int& e) const {
+     using Kokkos::Experimental::epsilon;
+-    auto const eps = epsilon<T>::value;
+-    auto const one = T(1);
++    T const eps = epsilon<T>::value;
++    T const one = 1;
+     // Avoid higher precision intermediate representation
+     compare() = one + eps;
+     e += (int)!(compare() != one);
```
to do the trick.

**Comment by wyphan** [comment]
Currently testing the proposed fix on Sunspot.

**Comment by wyphan** [comment]
@masterleinad After scouring at the Spack build logs on Sunspot, looks like the fix worked!
```
[ 52%] Built target Kokkos_CoreUnitTest_Serial1
```

**Comment by eugeneswalker** [comment]
Gitlab CI checks are green here. Do we need to wait for further review or should I approve and merge?

**Review by eugeneswalker — APPROVED** [review]

**Comment by tgamblin** [comment]
The macOS check was failing with something that looks unrelated so I updated the branch.  if all the unit tests pass in addition to the builds (which already passed), this LGTM.

**Comment by wyphan** [comment]
Actually, @eugeneswalker can you revert f6dd67e? That will ensure the fix actually works in the CI stack.

**Comment by eugeneswalker** [comment]
> Actually, @eugeneswalker can you revert [f6dd67e](https://github.com/spack/spack/commit/f6dd67eeee44057ad2b2a9aabb0a7a7867c2406d)? That will ensure the fix actually works in the CI stack.

I’d like to defer to @crtrott on whether we should have this +tests variant on in CI here- it sounds like this is not a good idea based on what he said above, at least w respect to oneapi builds of kokkos. What do you think @crtrott ?

**Comment by lucbv** [comment]
Thanks @tgamblin now we can update Kokkos Kernels...

**Pull request merged**
