### PR TITLE
spec_syntax: added xfailing tests for cases in #4144

### PR DESCRIPTION
**Pull request by alalazo**
It seems that parse_anonymous_spec may fail if more than one part (variant, version range, etc.) is given to the function. Added tests to code against to fix the problem in #4144.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Found a couple more test cases.
```python
patch('file.patch', when='@5: platform=darwin')
```
gives:
```
==> Error: Invalid Version range: 5:platform
```
while
```python
patch('file.patch', when='platform=darwin @5:')
```
gives:
```
==> Error: More than one spec in string: platform=darwin @5:
```
I think order is important here, so I'm not surprised that the latter fails. But the former should work.

**Comment by alalazo** [comment]
@adamjstewart I think both tests are already in the PR. Or am I missing something subtle?

**Comment by adamjstewart** [comment]
Nah, I guess that's the same thing. Just saying it applies to both variants and platforms. Should both specs have separate xfails? Otherwise the first one will fail and the second will never be tested.

**Comment by alalazo** [comment]
@adamjstewart I put the two together because whenever somebody will take a look at it, he needs to fix both to just remove `xfail` (or take extra effort to separate the tests, at which point he will probably try to fix both :laughing: ).

**Comment by tgamblin** [comment]
@becker33: can you look at this one?  I'm merging because the tests are expected to fail, but it should give you an easy reproducer.

**Comment by becker33** [comment]
@tgamblin I'll look into it, I must have written a bug into the parser during #360 or when I fixed the escape quotes.

**Comment by becker33** [comment]
#4199 resolves the issues found in #4144 and removes the XFAIL markings added here.

**Comment by alalazo** [comment]
Thanks @becker33 !

**Pull request merged**
