### PR TITLE
g2tmpl: added NOAA maintainers

### PR DESCRIPTION
**Pull request by edwardhartnett**
g2tmpl: added NOAA maintainers

### CODE REVIEW

**Comment by t-brown** [comment]
Can this PR and the one for [UFS-UTILS](https://github.com/spack/spack/pull/26201), be merged. Also if you want to become maintainers on the UFS stack, it would be nice if you did it all in one PR.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
> Can this PR and the one for [UFS-UTILS](https://github.com/spack/spack/pull/26201), be merged. Also if you want to become maintainers on the UFS stack, it would be nice if you did it all in one PR.

I've gone ahead and approved and enabled auto-merge so this should go in as quickly as the pipeline check can run.  Let me know if you would prefer I disable auto-merge to await your request.

**Comment by edwardhartnett** [comment]
@t-brown sorry for the multitude of PRs - I'm new to spack and learning how things should be done on this project. ;-)

I am one of the team responsible for the release and support of many libraries used by the UFS (but not the UFS itself). We are exploring the operational use of spack for installing these packages, and want to be in the loop with any changes in how they are built by spack.

If we use spack operationally, we will also be updating these package files whenever we release a new version. Occasionally (as with the nemsio package) the dependencies will change and we will need to make the package file smart enough to know what to do.

**Review by t-brown — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
