### PR TITLE
Deprecate py-cmake and py-ninja

### PR DESCRIPTION
**Pull request by adamjstewart**
Most (all?) packages that list a dependency on the PyPI implementation of cmake or ninja actually just need the command line executable. Since py-cmake is notoriously difficult to build and py-ninja is outdated, let's just deprecate them and instruct packages to depend on the binary versions. We already did the same thing with meson.

Disclaimer: I have not tested a single one of these packages. It's possible that some of them import cmake/ninja in setup.py and will not work with this new setup. I would appreciate it if package maintainers would test these packages themselves.

### CODE REVIEW

**Review by peterkasson — APPROVED** [review]
LGTM thanks

**Review by ax3l — APPROVED** [review]
Thanks! Agreed for the packages that I maintain.

**Review by MattToast — APPROVED** [review]
Can confirm that the package I maintain only requires the cmake executable. LGTM and thanks for the update!

**Review by RMeli — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Review by hariharan-devarajan — APPROVED** [review]
This looks good.

**Comment by alalazo** [comment]
We have a lot of approval :slightly_smiling_face:  I'm going to merge, if we get some request for a specific package, we can submit another PR.

**Pull request merged**
