### PR TITLE
Ensure some version known to Spack can satisfy constraints in `depends_on`

### PR DESCRIPTION
**Pull request by alalazo**
Modifications:
 - [x] Add a new check to `spack audit` to scan and verify that version constraints may be satisfied by some version declared in the built-in repository
- [x] Fix issues found by CI

### CODE REVIEW

**Comment by alalazo** [comment]
@adamjstewart We have [204 issues](https://github.com/spack/spack/runs/4607334827?check_suite_focus=true) found in the repository

**Comment by alalazo** [comment]
Half of the issues can be solved dealing with `cuda_arch=10` which is constrained to versions of CUDA that we don't have checksum for.

**Comment by adamjstewart** [comment]
I think I found a bug in `spack audit`. `py-apache-beam` has the following dependency:
```python
    depends_on('py-pyvcf@0.6.8:0.7.0', type=('build', 'run'), when='^python@:2.9')
```
However, this is incorrect, it should actually be:
```python
    depends_on('py-pyvcf@0.6.8:0.6', type=('build', 'run'), when='^python@:2')
```
If I make that change, `spack audit` no longer complains, despite the fact that `py-pyvcf` only has a 0.6.0 version.

**Comment by adamjstewart** [comment]
@alalazo all Python packages should be good now. Let me know if you discover anymore issue once you solve the `py-apache-beam` detection bug I reported above. Note that I did add a new version of `py-pyvcf` so you'll have to comment that out to reproduce the issue.

I think I've fixed a lot of these issues in multiple different PRs now. We really need to start merging these large Python PRs. Rebasing this will be fun.

**Comment by alalazo** [comment]
Thanks @adamjstewart I'll try to take care of what remains to be done by today

**Comment by alalazo** [comment]
@spackbot maintainers

**Comment by alalazo** [comment]
@adamjstewart It seems to me the `py-apache-beam` is a bug with versions :cry: There are possibly other issues that are not caught. The problem is this:
```
>>> c1 = spack.version.VersionRange('0.6.0', '0.6.0')
>>> c2 = spack.version.VersionRange('0.6.8', '0.6')
>>> c1.satisfies(c2)
True
>>> c2.satisfies(c1)
False
```
According to the docstring for `VersionRange.satisfies` this operation should be symmetric i.e. `c1.satisfies(c2) == c2.satisfies(c1)`. When we compare a specific `Version` we first convert it to a range:

https://github.com/spack/spack/blob/afd65a4cd0ce793680561e7ba3c9f0fb15b1852c/lib/spack/spack/version.py#L67-L94

Given that I'd solve this issue in a separate PR (otherwise I think this PR will never get merged :slightly_smiling_face: )

Note this issue is pointed out and discussed in https://github.com/spack/spack/discussions/26557

**Comment by adamjstewart** [comment]
@AndrewGaspar  @Rombur        @albestro      @aprokop  @ax3l   @barrysmith  @gsjaardema  @jedbrown    @junghans  @naromero77  @sethrj   @trws @HadrienG2      @antoniokaust  @aweits   @balay  @dev-zero    @haampie     @joseeroman  @ktsai7    @rspavel     @smolins

Can you review this PR? It modifies packages for which you are listed as maintainers.

**Review by balay — DISMISSED** [review]
removal of xsdk@0.2.0 related stuff from petsc, alquimia looks good to me

Edt: py-slepc4py changes also look good.

**Comment by HadrienG2** [comment]
LGTM

**Comment by dev-zero** [comment]
ACK

**Comment by Rombur** [comment]
LGTM

**Comment by tgamblin** [comment]
@alecbcs: FYI -- it'll be interesting to compare your tests before and after this PR is merged.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
