### PR TITLE
add package py-pyminifier

### PR DESCRIPTION
**Pull request by healther**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@citibeth I'm starting to second-guess renaming Python packages. If that's the name the developer wanted to use on PyPI, it might be best to keep that name. Otherwise, when you find a package on PyPI or try adding a new package, you have to see what the package is called instead of just adding `py-` to the front. Another good example is `pyqt` and `qtpy`, which are different packages on PyPI. What would you rename those to avoid a name conflict?

**Comment by citibeth** [comment]
Having a double `py-` in our package name makes no sense to the average
user.  We are already not consistent in this regard: we have some packages
that are called `pyxyz` upstream, and `py-xyz` in our repo.

I think the best approach is to eliminate unnecessary / distracting double
`py`s, which can only add confusion and make the system more errorprone.

> Otherwise, when you find a package on PyPI or try adding a new package,
you have to see what the package is called instead of just adding py- to
the front.

Come on, the algorithm isn't too hard:
```
if upstream_name[:3] == 'py-':
    root_name = upstream_name[3:]
elif upstream_name[:2] == 'py':
    root_name = upstream_name[2:]
else:
    root_name = upstream_name
spack_name = 'py-' + downcase(upstream_name)
```

> Another good example is pyqt and qtpy, which are different packages on
PyPI. What would you rename those to avoid a name conflict?

So maybe we need a few exceptions.  That should not deter us from squashing
extra `py`'s that would otherwise crop up all over the place.

**Comment by tgamblin** [comment]
Want to just get rid of py-?  It's a convention, mostly for counting Python packages, but I'm not wed to it.  We could add tags and do away with it.

Until then we could stick with py-pypiname so we can easily convert... thoughts?

**Comment by adamjstewart** [comment]
> Always remove double `py`

What about `py-pyqt` and `py-qtpy`?

> Get rid of `py-` altogether

The following packages have both Python and non-Python names:

* cdo
* gnuplot
* meep
* netcdf
* proj
* protobuf
* symengine

**Comment by citibeth** [comment]
On Fri, Mar 3, 2017 at 4:06 PM, Adam J. Stewart <notifications@github.com>
wrote:

> Always remove double py
>
> What about py-pyqt and py-qtpy?
>
A few exceptions to the rule don't bother me.


> Get rid of py- altogether
>
> The following packages have both Python and non-Python names:
>
>    - cdo
>    - gnuplot
>    - meep
>    - netcdf
>    - proj
>    - protobuf
>    - symengine
>
> Speaking for `py-proj`... The name of the upstream package is `pyproj`.
Not wanting to call our package `py-pyproj`, I called it `py-proj`
instead.  If we were to get rid of the `py-`, I would rename the Spack
package to `pyproj`.

**Comment by adamjstewart** [comment]
I prefer adding `py-` to the front of every Python package and keeping the name on PyPI intact. If I have a package that requires `pyminifier`, I'm going to run `spack list pyminifier`, which will show no results if the packages is actually named `py-minifier` (although we can, and probably should fix that). Even if that is fixed, whenever I add a package, I have to look up what we decided to name the dependency. It will never be perfect, but it is at least more consistent. That's just my opinion though.

**Comment by citibeth** [comment]
OK, you've convinced me.  I would rate the three solutions discussed in the
following order:

1. Todd (use tags)
2. Adam (always prefix with py-)
3. Elizabeth (get rid of double py's)

Since we don't have infrastructure for (1), that leaves us with (2) for now.

BTW... tags were introduced to deal with an ever-growing repo.  And lately
I've noticed the growth rate has been high; we are now up to 1231
packages.  I'm really glad we got PythonPackage, etc. in place.

**Comment by adamjstewart** [comment]
We can of course always change our minds later, but for now I think this package name is fine. @citibeth, can you approve?

**Pull request merged**
