### PR TITLE
refactor: packages import `spack.package` explicitly

### PR DESCRIPTION
**Pull request by trws**
Explicitly import package utilities in all packages, and corresponding fallout.  This includes:

* rename `spack.package` to `spack.package_base`
* rename `spack.pkgkit` to `spack.package`
* update all packages in builtin, builtin_mock and tutorials to include `from spack.package import *`
* update spack style
  * ensure packages include the import
  * automatically add the new import and remove any/all imports of `spack` and `spack.pkgkit` from packages when using `--fix`
  * add support for type-checking packages with mypy when SPACK_MYPY_CHECK_PACKAGES is set in the environment
* fix all type checking errors in packages in spack upstream
* update spack create to include the new imports
* update spack repo to inject the new import, injection persists to allow for a deprecation period

Original message below:
 
As requested @adamjstewart, update all packages to use pkgkit.  I ended up using isort to do this, so repro is easy:

```console
$ isort -a 'from spack.pkgkit import *' --rm 'spack' ./var/spack/repos/builtin/packages/*/package.py
$ spack style --fix
```

There were several line spacing fixups caused either by space manipulation in isort or by packages that haven't been touched since we added requirements, but there are no functional changes in here.

* [x] add config to isort to make sure this is maintained going forward

### CODE REVIEW

**Comment by adamjstewart** [comment]
Thanks! Two additional things to think about:

1. We also need to update `spack create` so that new packages come with this import
2. We should consider removing the hack that automatically injects this import into all package files. We probably can't do this right away as it will break non-upstreamed packages, but we could add a `spack audit` test to make sure all new packages use this and remove the hack at a later date.

**Comment by tldahlgren** [comment]
I thought importing of `pkgkit` was automatic as part of the Spack "magic".  @tgamblin is the expert.

Where was it not getting imported?

**Comment by adamjstewart** [comment]
It is. The purpose of this PR is to remove that magic, or at least move in a direction in which we can remove that magic in the future. Our magic doesn't work for a lot of tools like autocompletion in Jupyter Notebooks and type checks in mypy. It's also slower than simply using the import directly. 

EDIT: Another reason is that our magic causes error messages to be off by one line.

**Comment by trws** [comment]
> Thanks! Two additional things to think about:
> 
>     1. We also need to update `spack create` so that new packages come with this import
> 
>     2. We should consider removing the hack that automatically injects this import into all package files. We probably can't do this right away as it will break non-upstreamed packages, but we could add a `spack audit` test to make sure all new packages use this and remove the hack at a later date.

Yes, I agree with all of that, though after a chat with @tgamblin, we were discussing a rename as well, and I have a feeling I should do all of that together.  The preference was `spack.package.util` as the "package utilities" that would be grabbed everywhere.  What do you think about that @adamjstewart?

**Comment by tgamblin** [comment]
Basically I think `spack.pkgkit` is a weird name, and `spack.package.util` is clearer.

**Comment by adamjstewart** [comment]
Personally I would rename spack.package to something else and rename spack.pkgkit to spack.package. I think we already had this discussion when we first decided on the name spack.pkgkit.

**Comment by alalazo** [comment]
When this goes in we can remove import boilerplate from `spack.repo`.

**Comment by trws** [comment]
Some, but not all yet, there are some things this doesn't cover, but this gets us far enough that it helps a lot identifying what's left.

I wouldn't hate renaming package necessarily, but that will touch a lot of places.  What would we rename it to, package_class, package_impl, package_internal..?

**Comment by trws** [comment]
Ok, this was everything and re-updated on develop less than 10 seconds ago.  It now has a conflict. Will probably have to stage this one carefully.

Anyway, I ended up moving package to package_base as we discussed, and then pkgkit is now package_defs.  I know we discussed making it package, but having the ambiguity between spack.package and the package.py file in every package directory proved somewhat unfortunate.  If the decision is to make it package.py, I'll change it one last time to that.

**Comment by trws** [comment]
Something bad happened to the github actions here.  Going to merge in develop to poke it.

**Comment by trws** [comment]
@spackbot run pipeline

**Review by tgamblin — DISMISSED** [review]

**Review by sethrj — APPROVED** [review]

**Pull request merged**
