### PR TITLE
veclibfort: add new package

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by davydden** [comment]
vecLibFort is lightweight but flexible "shim" designed to rectify the incompatibilities between the Accelerate/vecLib BLAS and LAPACK libraries shipped with Mac OS X and FORTRAN code compiled with modern compilers such as GNU Fortran.

You will want this code if you are...

compiling your code directly from FORTRAN source; and
using Apple's BLAS and/or LAPACK for your linear algebra; and
using single-precision or complex arithmetic.
You will not need this code if you are...

using some other linear algebra package; or
calling BLAS and LAPACK only from C; or
using an alternative BLAS/LAPACK package (OpenBlas,MKL); or
using only double-precision real arithmetic.
You may want this code if you are...

running a pre-compiled program, or linking to a pre-compiled library, that seems to exhibit bugs described in the next section. See the section Preloaded (interposing) library for more details on how you may be able to fix these programs without recompilation.

**Comment by davydden** [comment]
@tgamblin : ping on veclibfort new package.

**Comment by ax3l** [comment]
@tgamblin @adamjstewart @davydden OpenBLAS is problematic on modern Mac with M1 processors as well.
Should this one maybe be the default BLAS/LAPACK provider for macOS users in `etc/spack/defaults/packages.yaml` ?

**Comment by adamjstewart** [comment]
I feel like I remember numpy planning on dropping support for this eventually because it was too much work to support. So if that's still the plan then it wouldn't be a good default.

**Comment by ax3l** [comment]
I think the package is also unmaintained after looking closer.

I am using it right now to work-around a quirk on M1. But maybe we can use `Accelerate.Framework` directly as provider somehow?

**Comment by adamjstewart** [comment]
Found it: https://github.com/numpy/numpy/blob/main/INSTALL.rst.txt#macos

> You will need to install a BLAS/LAPACK library. We recommend using OpenBLAS or Intel MKL. Apple's Accelerate also still works, however it has bugs and we are likely to drop support for it in the near future.

and: https://numpy.org/doc/stable/user/building.html?highlight=accelerate#lapack

> _Deprecated since version 1.20:_ The native libraries on macOS, provided by Accelerate, are not fit for use in NumPy since they have bugs that cause wrong output under easily reproducible conditions. If the vendor fixes those bugs, the library could be reinstated, but until then users compiling for themselves should use another linear algebra library or use the built-in (but slower) default, see the next section.

**Comment by ax3l** [comment]
Thank you for the details!

**Pull request merged**
