### PR TITLE
mfem: add nvechip to sundials components when mfem+rocm

### PR DESCRIPTION
**Pull request by balos1**

### CODE REVIEW

**Review by v-dobrev — APPROVED** [review]

**Comment by v-dobrev** [comment]
Thanks @balos1!

**Review by balay — APPROVED** [review]

**Comment by v-dobrev** [comment]
I restarted failed CI jobs -- they looked like random failures.

**Comment by eugeneswalker** [comment]
All CI is green, should we merge?

**Comment by v-dobrev** [comment]
> All CI is green, should we merge?

Yes, I think this is ready to be merged.

**Pull request merged**
