### PR TITLE
cmake: add v3.27.8

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Review by alecbcs — APPROVED** [review]
Confirmed SHA. @johnwparent thanks for the update!

**Comment by alecbcs** [comment]
@spackbot run pipeline 😞

**Comment by alecbcs** [comment]
@spackbot run pipeline 😢

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
(There was an issue on the Cray runner that has possibly been fixed, let's see if this PR passes this time)

**Comment by alecbcs** [comment]
@spackbot rebuild everything

**Comment by alecbcs** [comment]
@eugeneswalker mentioned this failure may be due to a cached version of python that was built on the cray runner. Let's see if rebuilding everything blows away the cache and fixes the error here.

**Comment by eugeneswalker** [comment]
> @eugeneswalker mentioned this failure may be due to a cached version of python that was built on the cray runner. Let's see if rebuilding everything blows away the cache and fixes the error here.

Looking at failures from most recent run, there were two timeouts on UO machines, and one pod system failure from AWS pod. @spackbot run pipeline

**Pull request merged**
