### PR TITLE
Update checksum for latest version of cudnn

### LINKED ISSUE #4248: cudnn@6.0 checksum fails
```
[spackapps@lo-login-02 bin]$ spack install cudnn@6.0 ^cuda@8.0.61 %gcc@4.8.5 arch=linux-centos7-x86_64
==> cuda is already installed in /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/cuda-8.0.61-mxdqob5lveng3f2utljrysrx4vjp7g3m
==> Installing cudnn
==> Fetching http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz
######################################################################## 100.0%
==> Error: ChecksumError: md5 checksum failed for /cluster/apps/spack/var/spack/stage/cudnn-6.0-4sw354jwkals7b7dvq44fptwnwn54zra/cudnn-8.0-linux-x64-v6.0.tgz
    Expected 4aacb7acb93c5e4dfa9db814df496219 but got a08ca487f88774e39eb6b0ef6507451d
/cluster/apps/spack/lib/spack/spack/package.py:928, in do_fetch:
     896      def do_fetch(self, mirror_only=False):
     897          """
     898          Creates a stage directory and downloads the tarball for this package.
     899          Working directory will be set to the stage directory.
     900          """
     901          if not self.spec.concrete:
     902              raise ValueError("Can only fetch concrete packages.")
     903  
     904          start_time = time.time()
     905          if spack.do_checksum and self.version not in self.versions:
     906              tty.warn("There is no checksum on file to fetch %s safely." %
     907                       self.spec.format('$_$@'))
     908  
     909              # Ask the user whether to skip the checksum if we're
     910              # interactive, but just fail if non-interactive.
     911              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     912              ignore_checksum = False
     913              if sys.stdout.isatty():
     914                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     915                                                      default=False)
     916                  if ignore_checksum:
     917                      tty.msg("Fetching with no checksum.", ck_msg)
     918  
     919              if not ignore_checksum:
     920                  raise FetchError("Will not fetch %s" %
     921                                   self.spec.format('$_$@'), ck_msg)
     922  
     923          self.stage.fetch(mirror_only)
     924  
     925          self._fetch_time = time.time() - start_time
     926  
     927          if spack.do_checksum and self.version in self.versions:
  >> 928              self.stage.check()
     929  
     930          self.stage.cache_local()


[spackapps@lo-login-02 bin]$
```

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #4248 

The checksum for the latest version changed. Don't know why.

### CODE REVIEW

**Comment by tgamblin** [comment]
Any idea why?  We should be especially careful of changes to the same version -- see caskroom/homebrew-cask#33354 for a recent example.

**Comment by adamjstewart** [comment]
Just sent an email to the cudNN developers to check.

**Comment by adamjstewart** [comment]
Alright, the developers got back to me and had this to say:

> The checksum is different because we released a minor bugfix update to cuDNN 6 (V6.0.21) to address the following issue:
>
> - Dilated convolutions (dilation_h > 1 or dilation_w > 1) can generate incorrect results on Kepler-based GPUs in release V6.0.20. This has been fixed in V6.0.21.
>
> The details are in the release notes:
> https://developer.nvidia.com/rdp/cudnn-download

I asked if there was a download URL for the minor version. In the meantime, I think we're safe, although I don't have an NVIDIA account to verify the release notes. @weijianwen? @samfux84?

**Comment by adamjstewart** [comment]
Further update from the developers:

> V6.0.20 contained a bug that affected all Kepler GPUs, and generated incorrect results silently and therefore we removed it immediately after it was patched. 

So it sounds like they aren't open to keeping around old releases if they have known bugs. Technically the version number has actually changed, but the download URL hasn't.

**Comment by tgamblin** [comment]
Ugh -- I'm ok with merging this as-is., but is there a chance they could provide a more specifically named tarball?

**Comment by samfux84** [comment]
@adamjstewart I don't either have an NVIDIA account but a colleague in our team has one. I'll ask him to check and verify the release notes today.

**Comment by samfux84** [comment]
I can confirm that the release notes are correct:

cudnn_release_notes

**Comment by adamjstewart** [comment]
@tgamblin 

> is there a chance they could provide a more specifically named tarball, with a redirect link from the more generic URL?

Generic response from the developers:

> I’ll forward this to our release teams so they can consider creating separate links for each minor release moving forward.

**Pull request merged**
