### PR TITLE
Update SLEPc and slepc4py to version 3.15

### PR DESCRIPTION
**Pull request by joseeroman**
Similar to PETSc update #22688

cc: @dalcinl @balay

### CODE REVIEW

**Comment by balay** [comment]
@joseeroman @dalcinl I get build errors with slepc4py that I don't understand.

```     40     In file included from src/SLEPc.c:3:
     41     src/slepc4py.SLEPc.c: In function '__Pyx__ExceptionSave':
  >> 42     src/slepc4py.SLEPc.c:68575:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     43     68575 |     *type = tstate->exc_type;
     44           |                     ^~~~~~~~
     45           |                     curexc_type
```
```
[balay@pj01 spack]$ ./bin/spack find
==> 15 installed packages
-- linux-fedora31-skylake / gcc@9.3.1 ---------------------------
arpack-ng@3.8.0  hypre@2.20.0  mpich@3.3            parmetis@4.0.3  py-mpi4py@3.0.3  py-petsc4py@3.15.0  slepc@3.15.0        zlib@1.2.11
hdf5@1.10.7      metis@5.1.0   netlib-lapack@3.8.0  petsc@3.15.0    py-numpy@1.17.4  python@3.7.9        superlu-dist@6.4.0
```
[spack-build-out.txt](https://github.com/spack/spack/files/6244162/spack-build-out.txt)

**Comment by dalcinl** [comment]
@joseeroman What version of Cython did you use? You should always use the latest to get things up to date for recent Python releases.

**Comment by adamjstewart** [comment]
If a certain version of Cython is required we can add that constraint to the `depends_on`

**Comment by joseeroman** [comment]
@dalcinl yes, the cython version is old, I am trying to regenerate the tarball with a newer version.
@adamjstewart I think the cython version is relevant when creating the tarball, not when using it via spack.

**Comment by balay** [comment]
petsc4py@main adds cython as dependency.

Also we need a fix for this issue in slepc4py as well https://github.com/spack/spack/issues/21451

I guess I can  add slepc4py@main and hte above  to this MR. [will see if I can push]

**Comment by joseeroman** [comment]
I have updated the tarball. Hope it works now.

**Comment by dalcinl** [comment]
@balay @joseeroman petsc4py and slepc4py require Cython when using a git clone, but the tarballs always include C wrappers, such that users do not have to install Cython. However, it is 2020, lots of things improved in Python packaging, particularly when using `pip install package`. We could always require Cython as a build-time dependency for petsc4py and slepc4py, not matter if you are using a git checkout or a release tarball.

**Comment by balay** [comment]
@joseeroman I still get the same errors with the tarball

```
     41     src/slepc4py.SLEPc.c: In function '__Pyx__ExceptionSave':
  >> 42     src/slepc4py.SLEPc.c:68575:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     43     68575 |     *type = tstate->exc_type;
     44           |                     ^~~~~~~~
     45           |                     curexc_type
```
```
[balay@pj01 spack]$ git show -q
commit 2b00e224b4930b277dcf7b0d3cb2ea61d906c2eb (HEAD)
```

**Comment by balay** [comment]
BTW:` py-slepc4py@main` builds fine [using the cython dependency]

```
[balay@pj01 spack]$ ./bin/spack find
==> 16 installed packages
-- linux-fedora31-skylake / gcc@9.3.1 ---------------------------
arpack-ng@3.8.0  mpich@3.3            py-mpi4py@3.0.3     python@3.7.9
hdf5@1.10.7      netlib-lapack@3.8.0  py-numpy@1.17.4     slepc@3.15.0
hypre@2.20.0     parmetis@4.0.3       py-petsc4py@3.15.0  superlu-dist@6.4.0
metis@5.1.0      petsc@3.15.0         py-slepc4py@main    zlib@1.2.11
```

[for some reason py-cython is not listed above - it was specified to spack via ~/.spack/packages.yaml - using system python+cython]

**Comment by dalcinl** [comment]
@joseeroman Looks like the wrappers were generated with Cython 0.26.1. 

Just in case, please run the following in `src/binding/slepc4py`
```
make srcclean
make srcbuild
```
to force regeneration.

**Comment by joseeroman** [comment]
Thanks everyone. I have created a new one.

**Review by adamjstewart — APPROVED** [review]

**Comment by balay** [comment]
works now. Thanks!
```
[balay@pj01 spack]$ ./bin/spack find
==> 16 installed packages
-- linux-fedora31-skylake / gcc@9.3.1 ---------------------------
arpack-ng@3.8.0  mpich@3.3            py-mpi4py@3.0.3     python@3.7.9
hdf5@1.10.7      netlib-lapack@3.8.0  py-numpy@1.17.4     slepc@3.15.0
hypre@2.20.0     parmetis@4.0.3       py-petsc4py@3.15.0  superlu-dist@6.4.0
metis@5.1.0      petsc@3.15.0         py-slepc4py@3.15.0  zlib@1.2.11
```

**Review by balay — APPROVED** [review]

**Pull request merged**
