### PR TITLE
Yaml spec parsing corner case

### LINKED ISSUE #14677: Package specs fail for yaml-cpp package when using namespaces
I've created an external repo to override native packages in spack.
I can use the namespace to properly reference most packages, but yaml-cpp fails when I add the compiler in the spec.

### Steps to reproduce the issue
For example,
`spack find builtin.yaml-cpp`

returns the proper references, but

`spack find builtin.yaml-cpp%gcc@7.2.0`

returns

`==> Error: Spec filename must end in .yaml: 'builtin.yaml-cpp%gcc@7.2.0'`

The following also return the expected results:

`spack find builitin.nalu-wind%gcc@7.2.0`
`spack find builtin.trilinos%gcc@7.2.0`

So it appears to be an issue with yaml-cpp (as far as I know). Guessing it is because there is a "*.yaml" in the spec for this corner case.

Debug output:

[myconsole]$ spack -d find builtin.yaml-cpp%gcc%7.2.0
==> [2020-01-29-14:55:12.384485] Imported find from built-in commands
==> [2020-01-29-14:55:12.386274] Imported find from built-in commands
==> [2020-01-29-14:55:12.387341] SpackError: Spec filename must end in .yaml: 'builtin.yaml-cpp%gcc%7.2.0'
==> [2020-01-29-14:55:12.387410] Error: Spec filename must end in .yaml: 'builtin.yaml-cpp%gcc%7.2.0'
Traceback (most recent call last):
  File "/projects/wind/snl-ceerws/spack/lib/spack/spack/main.py", line 711, in main
    return _invoke_command(command, parser, args, unknown)
  File "/projects/wind/snl-ceerws/spack/lib/spack/spack/main.py", line 456, in _invoke_command
    return_val = command(parser, args)
  File "/projects/wind/snl-ceerws/spack/lib/spack/spack/cmd/find.py", line 197, in find
    results = args.specs(**q_args)
  File "/projects/wind/snl-ceerws/spack/lib/spack/spack/cmd/common/arguments.py", line 69, in _specs
    qspecs = spack.cmd.parse_specs(self.values)
  File "/projects/wind/snl-ceerws/spack/lib/spack/spack/cmd/__init__.py", line 161, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Spec filename must end in .yaml: 'builtin.yaml-cpp%gcc%7.2.0'

### Information on your system

RHEL6, custom package in repo that just allows me to access additional sha's for yaml-cpp, but inherits from yaml-cpp in builtin.  I don't think my package configuration has anything to do with this.

### PR DESCRIPTION
**Pull request by psakievich**
Attempt to fix #14677.  New tests fail deeper in the parser.  Could use some help resolving.

### CODE REVIEW

**Comment by psakievich** [comment]
@tgamblin here's what I've been trying. 

The spec is getting chopped up in the parser though. Not sure I understand the significance of calling `push_tokens` at line 4101 of `spec.py` but it seems like the spec is getting chopped up in an undesirable manner somewhere there, or when it goes back to `do_parse`.

```
        parsed = (" ".join(str(spec) for spec in output))
>       assert expected == parsed
E       AssertionError: assert 'yaml-cpp@0.1.8%gcc' == '8%gcc'
E         - yaml-cpp@0.1.8%gcc
E         + 8%gcc
```

**Comment by becker33** [comment]
@psakievich I think the problem is in the lexer (specifically the regex for finding filenames). I'm trying to reproduce locally so that I can test it.

**Comment by becker33** [comment]
@psakievich I've recreated this locally.

If you change `[^\b]*` to `$` on line 3948 of `$spack/lib/spack/spack/spec.py`, I believe you can undo the rest of this PR and submit only that change and it will fix the source of the bug.

**Comment by psakievich** [comment]
@becker33 thanks!

**Review by becker33 — CHANGES_REQUESTED** [review]
Forgot to request changes.

**Comment by becker33** [comment]
@psakievich reported that after making the changes I recommended, the following test failed:

`test_nice_error_for_no_space_after_spec_filename`

Copied from the slack conversation:

Given the design constraints:
Spec parsing must be agnostic to the actual packages in Spack
“yaml*” are valid names for packages
Any place the parser accepts a Spec, it must also accept a spec.yaml file

It is not possible to satisfy the constraints of that particular test.
There is no way to distinguish whether foo.bar.yamlfoo refers to:
1. The yaml file for the package foo.bar, followed by no space, followed by another spec.
2. The package foo.bar.yamlfoo, referenced as an abstract spec instead of a yaml file.

There are three options as far as I can tell:
1. Remove that test and accept that the error message is slightly less helpful in that case than it used to be.
2. Ban package names from starting with the string “yaml”.
3. 
    a. ~Ban repo namespaces from including the character / if we haven’t already~ We already have
    b. change the parser to be more restrictive parsing filenames if there is no / in the filename, and
    c. ~accept that the error message is slightly less helpful than it used to be when the filename has no / in it~ The filename already has to have a `/` in it.

@scottwittenburg  I think you wrote the initial support for filenames as specs, do you have strong feelings about which path we follow here?
My inclination if Scott doesn’t object is to simply remove that test (following option 1 above).

**Comment by scottwittenburg** [comment]
Thanks @becker33 and @psakievich, I'm okay with option 1.  None of the options seem ideal, but maybe it's the best we can do, given the constraints as you enumerated them.

**Comment by becker33** [comment]
@psakievich as I've dug into this I realize filenames without a `/` in them are not allowed. This makes option 3 more appealing, as a simple code cleanup can make everything work as it should.

I'll push a version that does that now. @scottwittenburg could you give it a review?

Previously, we detected a filename even if there was no `/` in it, and then we backed out if what we found (including overrun to test for missing spaces) matched the "identifier" regex for filenames. That lead to the bug because a spec including other sigils (like `%`) does not match the "identifier" regex.

Now, we just don't detect a filename at all if it doesn't have a `/` in it. Then there's no need to back out, and therefore we can't mess up which strings we need to back out of and treat as specs instead of filenames.

**Comment by psakievich** [comment]
@becker33 I didn't realize that either.  So file names in CWD are still required to include a `/` ?

**Comment by becker33** [comment]
@psakievich, correct.

If you try `spack spec libelf.yaml`, Spack will ask whether you meant `./libelf.yaml`.

**Review by scottwittenburg — APPROVED** [review]
This looks good to me, thanks @psakievich and @becker33.

**Pull request merged**
