### PR TITLE
Fix deptypes

### PR DESCRIPTION
**Pull request by mathstuf**
---
List of contributors who have packages touched here:

 * [x] @mwilliammyers
 * [x] @trws
 * [x] @hartzell
 * [ ] @citibeth
 * [ ] @jgalarowicz
 * [x] @adamjstewart
 * [ ] @glennpj
 * [x] @alalazo

### CODE REVIEW

**Comment by trws** [comment]
This looks right for my packages.  The Go package should really have a different kind of dep on go-bootstrap since it can also be satisfied by either gcc or a local installation of go of a certain version, but I haven't found a good way to express that yet.

**Comment by alalazo** [comment]
LGTM

**Comment by adamjstewart** [comment]
I don't think this touches any packages that I've written, but LGTM

**Comment by hartzell** [comment]
I don't have time to rebuild everything right now to check it "for real", but the changes to the "bop*" and texlive packages look reasonable.

**Comment by mwilliammyers** [comment]
LGTM

**Pull request merged**
