### PR TITLE
py-flask: add 2.2.2 and fix dependencies for py-werkzeug and py-markupsafe

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://github.com/pallets/flask/tree/2.2.2
https://github.com/pallets/werkzeug/tree/2.2.2
https://github.com/pallets/markupsafe/tree/2.1.1

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
Can you resolve the merge conflict?

**Comment by manuelakuhn** [comment]
Sorry for the delay. Here you go.

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
I have rebased this PR but now there is no `py-dataclasses` packages in spack anymore. Where did it go?

**Comment by adamjstewart** [comment]
`py-dataclasses` was removed since it's a builtin library in Python 3.7+ and Spack no longer supports Python 3.6 and older. So you no longer need to list it as a dependency.

**Comment by manuelakuhn** [comment]
Ok thanks for the explanation. I have removed it now.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
