### PR TITLE
ReMPI: add version for github branch

### LINKED ISSUE #30475: Incorrect URL substitution when fetching tarball for version with no checksum
### Steps to reproduce

``` console
$ spack -d install -v rempi@master
```
rempi does not have a `version('master')`, so spack does URL substitution to fetch an unchecksummed version. The `rempi.url` is

    url = "https://github.com/PRUNERS/ReMPI/releases/download/v1.0.0/ReMPI-1.0.0.tar.gz"

Substitution gives

    https://github.com/PRUNERS/ReMPI/releases/download/vmaster/ReMPI-1.0.0.tar.gz
                                                    ---^---

I would submit a patch, but I'm not at all familiar with that part of the code.

### Error message

    ==> [2022-05-04-15:35:03.197167] Checking existence of https://github.com/PRUNERS/ReMPI/releases/download/vmaster/ReMPI-master.tar.gz
    ==> [2022-05-04-15:35:03.387230] FailedDownloadError: Failed to fetch file from URL: https://github.com/PRUNERS/ReMPI/releases/download/vmaster/ReMPI-master.tar.gz
        Urllib fetch failed to verify url                      https://github.com/PRUNERS/ReMPI/releases/download/vmaster/ReMPI-master.tar.gz
     with error Download failed: HTTP Error 404: Not Found

### Information on your system

* **Spack:** 0.18.0.dev0 (6b6147d5a064fdc149d8e1335b5ed62bdb63af25)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by hainest**
This should not be merged until after #28640

Closes #30475

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Can this be merged before #28640 ?

**Comment by hainest** [comment]
> Can this be merged before #28640 ?

No. The master branch has the same problem as the 1.2.0 release. I will try to find some time to work on these.

**Comment by alalazo** [comment]
@hainest Should we close this one too, since we closed #28640 ?

**Comment by hainest** [comment]
@alalazo Yeah, let's close this one, as well.

**Pull request closed without merging**
