### PR TITLE
py-pytz: add 2022.2.1

### PR DESCRIPTION
**Pull request by manuelakuhn**
https://git.launchpad.net/pytz/tree/src?h=release_2022.2.1

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Deferring merge decision to maintainers.

**Review by adamjstewart — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by manuelakuhn** [comment]
@spackbot run pipeline

**Pull request merged**
