### PR TITLE
Updated cassandra versions

### PR DESCRIPTION
**Pull request by danielecesarini**
The current references of cassandra are broken, this PR updates the package with working versions.

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Two questions: 
1. Can we stick to versions on Github (so that we don't have to change all the shas? 
2. Is there a need for v1.X and v2.X to be supported?

**Comment by danielecesarini** [comment]
> Two questions: 
> 1. Can we stick to versions on Github (so that we don't have to change all the shas? 
> 2. Is there a need for v1.X and v2.X to be supported?

1. Unfortunately, the GitHub versions of Cassandra don't work out of box. My first version of this package was based on the GitHub repo but this repo doesn't provide a production tar of Cassandra but only the source code at a specific commit. If you try to run Cassandra directly from GitHub you will find some missing components, I suppose that developers don't commit java binaries for security reasons. The official production archives to redistribute Cassandra are the ones referenced in this PR. BTW, the GitHub repo is not the official GIT repo of Cassandra, it's only a mirror, but also the official repo suffers of the above problems.

2. I have some legacy codes that needs Cassandra 2 at least, I also supported Cassandra 1 for completeness, if you think that we don't need it, I can remove the version 1.

**Comment by alalazo** [comment]
For point 2. I think:
1. Adding back 3.11.6 and 3.11.5 as "deprecated"
2. Adding 3.11.11 and 4.0.1
3. Adding 2.2.19

would be enough here. Point 1 is to try to ensure that versions don't disappear from Spack without being deprecated first.

**Comment by danielecesarini** [comment]
> For point 2. I think:
> 
> 1. Adding back 3.11.6 and 3.11.5 as "deprecated"
> 2. Adding 3.11.11 and 4.0.1
> 3. Adding 2.2.19
> 
> would be enough here. Point 1 is to try to ensure that versions don't disappear from Spack without being deprecated first.

[Fix](https://github.com/spack/spack/pull/28551/commits/7419e2ef362204bb62343ac141a7e2f178613603)

**Review by alalazo — APPROVED** [review]
Thanks!

**Pull request merged**
