### PR TITLE
Cmake: add 3.26.0

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
CI failures appear to be related to pods not being ready.

@spackbot run pipeline

**Comment by tldahlgren** [comment]
I am able to successfully build the package on an LLNL machine.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by johnwparent** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Going to `Update branch` to see if that resolves the odd CI stack issues.

**Comment by johnwparent** [comment]
Current gitlab-ci failures actually look fairly legit. @kwryankrattiger can you confirm for a sanity check before I ask internally about this? AFAIK CMake 3.26 didn't do anything major to the HIP support (at least according to the release notes), so I'm a bit surprised it would be causing this failure.

**Comment by kwryankrattiger** [comment]
that is probably a real error, but not related to cmake. #36335

**Comment by johnwparent** [comment]
> that is probably a real error, but not related to cmake. #36335

Alright, I'll reach out to Ben. It's probably a VTK problem (considering how VTK is failing elsewhere) so we should probably hold off on merging as we don't want to break CI. This likely applies to #36349 as well then. 

Thanks for checking that out @kwryankrattiger!!

**Comment by johnwparent** [comment]
If the error still persists on rebase I'll add a conflict with that version to the paraview package and link to the corresponding CMake issue I'll be creating.

**Review by tldahlgren — APPROVED** [review]
I was able to successfully build the version.

**Pull request merged**
