### PR TITLE
gsl: New version 2.7.1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
@spackbot help

**Comment by eschnett** [comment]
@spackbot run pipeline

**Comment by eschnett** [comment]
The CI error is:
```
==> [2022-04-28-15:27:57.949913] SpackWebError: Download failed: <urlopen error An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.>
```
Re-running CI doesn't help. What does this mean?

**Comment by eschnett** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Pull request merged**
