### PR TITLE
New patch release SLEPc 3.18.2

### PR DESCRIPTION
**Pull request by joseeroman**

### CODE REVIEW

**Review by balay — DISMISSED** [review]

**Review by tldahlgren — DISMISSED** [review]
Confirmed both sha256

**Comment by tldahlgren** [comment]
@adamjstewart Did you want to review addition of new version for `py-slepc4py`?

**Review by adamjstewart — COMMENTED** [review]
Minor change, but `py-cython` should be `py-cython@0.24:`

**Comment by joseeroman** [comment]
> Minor change, but `py-cython` should be `py-cython@0.24:`

Changed. Thanks.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
