### PR TITLE
CrayPE_binutils package fix for CCE

### PR DESCRIPTION
**Pull request by lukebroskop**
CrayPE_binutils package fix for CCE

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Thank you! This resolved the issue for me. Is there any reason you can think of that I shouldn't do the same to resolve the issue with `%gcc@9.4.0` which I am seeing on `Ubuntu 20.04`. See initial issue description here https://github.com/spack/spack/issues/30195#issue-1209823553.

**Review by eugeneswalker — APPROVED** [review]

**Comment by lukebroskop** [comment]
>Thank you! This resolved the issue for me. Is there any reason you can think of that I shouldn't do the same to resolve the issue with %gcc@9.4.0 which I am seeing on Ubuntu 20.04. See initial issue description here https://github.com/spack/spack/issues/30195#issue-1209823553.

Yeah, I think this would also be a solution for https://github.com/spack/spack/issues/30195#issue-1209823553.

**Comment by eugeneswalker** [comment]
I think this may be limited to `binutils@2.38` -- checking now. If so, we should target the additional flags only on this version.

**Comment by eugeneswalker** [comment]
I'm seeing this all the way back to at least `binutils@2.36.1` FYI

**Review by alalazo — APPROVED** [review]

**Pull request merged**
