### PR TITLE
elfutils: add version 0.188

### PR DESCRIPTION
**Pull request by hainest**
@mwkrentel

### CODE REVIEW

**Review by mwkrentel — DISMISSED** [review]
I approve, but also see PR #33695.

@hainest I'm curious, is there anything specific in 0.188 that dyninst
or hpctoolkit particularly want?

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Comment by mwkrentel** [comment]
@spackbot run pipeline

The pipeline failed due to a bad sha256 for tau.
This was fixed a few hours ago.

**Comment by mwkrentel** [comment]
@hainest It's still failing on the stale sha256sum for tau 2.32.
Try rebasing onto the latest spack develop.

**Review by mwkrentel — APPROVED** [review]
I approve (again).

**Review by haampie — APPROVED** [review]

**Comment by hainest** [comment]
>@hainest I'm curious, is there anything specific in 0.188 that dyninst or hpctoolkit particularly want?

The items we want weren't in this release. I just wanted to make sure this version is available for testing.

**Pull request merged**
