### PR TITLE
gdrcopy: allow tests to build against libcuda.so stub

### PR DESCRIPTION
**Pull request by hmenke**
Backport https://github.com/NVIDIA/gdrcopy/pull/261

Also adds a build-time dependency on pkg-config. Otherwise we see
```
  >> 25    make[1]: pkg-config: No such file or directory                                                                                                    
  >> 26    make[1]: pkg-config: No such file or directory
```
and linking against libcheck might fail.

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot maintainers

**Review by alalazo — APPROVED** [review]
Waiiting for maintainer to review / try to build before merging.

**Comment by hmenke** [comment]
Thanks! Please note that the patches only apply to `2.0:2.3`, whereas the latest version is `2.4.1`. In `2.4` the patch to [build against CUDA stubs](https://github.com/NVIDIA/gdrcopy/commit/4e0a2eec2e10db379069ddedf42e9b73a772c3e4) was merged and the [dependency on pkgconfig removed](https://github.com/NVIDIA/gdrcopy/commit/5dfefaf251a964bcbc7250bb4dcbf4b5ddffbc78#diff-36b847ebf9c22d0651fe4856d7a8acb47ee2c483c79f1ccf0ed8c84889c9a394L5-L9).

**Review by alalazo — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
Passed: gdrcopy@master gdrcopy@2.4.1 gdrcopy@2.3 gdrcopy@2.2 gdrcopy@2.1 gdrcopy@2.0

Failed: gdrcopy@1.3
spack find -v:
[+]  gdrcopy@master+cuda build_system=makefile cuda_arch=none
[+]  gdrcopy@2.4.1+cuda build_system=makefile cuda_arch=none
[+]  gdrcopy@2.3+cuda build_system=makefile cuda_arch=none patches=c5efec1,cc18b13
[+]  gdrcopy@2.2+cuda build_system=makefile cuda_arch=none patches=c5efec1,cc18b13
[+]  gdrcopy@2.1+cuda build_system=makefile cuda_arch=none patches=c5efec1,cc18b13
[+]  gdrcopy@2.0+cuda build_system=makefile cuda_arch=none patches=c5efec1,cc18b13
```
@1.3 fails with: `ld: cannot find -lcuda: No such file or directory`
(no libcuda installed on the build host)

**Comment by hmenke** [comment]
> @1.3 fails with: `ld: cannot find -lcuda: No such file or directory`
> (no libcuda installed on the build host)

Yes, sorry about that. In version 1.3 the directory structure is completely different and the patch cannot be applied straightforwardly, which is why I had to skip it.

**Pull request merged**
