### PR TITLE
Updating PyDV, adding IBIS and Trata

### PR DESCRIPTION
**Pull request by sbeljurf**

### CODE REVIEW

**Comment by adamjstewart** [comment]
It seems like pydv is unrelated to ibis/trata, would it be possible to split this into 2 separate PRs?

**Comment by sbeljurf** [comment]
They are all separate packages developed and maintained by WEAVE. I can split them.

**Comment by sbeljurf** [comment]
Also, what's the issue with the style check exactly? I can make the required changes before creating the separate PRs.

**Comment by adamjstewart** [comment]
The style issues can be fixed using `spack style --fix`

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

**Pull request closed without merging**
