### PR TITLE
Seacas add libcatalyst variant 2

### PR DESCRIPTION
**Pull request by jeffmauldin**
@spackbox fix style
adding libcatalyst variant (default off) to seacas package, which, when set to on, sets the TPL_ENABLE_Catalyst2 cmake argument during the seacas build and also adds libcatalyst (spack package for catalyst api 2) as a dependency for seacas

### CODE REVIEW

**Review by gsjaardema — APPROVED** [review]
Looks good to me

**Comment by gsjaardema** [comment]
@spackbot fix-style

**Comment by gsjaardema** [comment]
@spackbot fix style

**Comment by jeffmauldin** [comment]
@spackbot fix style

**Comment by jeffmauldin** [comment]
@spackbot fix style

**Comment by gsjaardema** [comment]
@jeffmauldin  It looks like you need to fix 
```
var/spack/repos/builtin/packages/seacas/package.py:202: [E501] line too long (106 > 99 characters)
``` 
manually.

**Comment by jeffmauldin** [comment]
You are definitely correct, Greg. I have updated line 202 (now 86 characters) and hopefully it will now pass style check.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
