### PR TITLE
IntelOneApiPackage: add envmods variant to toggle environment modifications by oneapi packages

### PR DESCRIPTION
**Pull request by koysean**
Fix for #34196.

Prevents Spack from making modifications to the environment when the IntelOneApiPackage is provided by an external environment module - in these cases we should allow the environment module to set the environment as needed.

This includes a fix to intel-oneapi-mkl which does its own environment modifications in its `setup_build_environment()` in addition to the ones common to the IntelOneApiPackage class.

### CODE REVIEW

**Review by rscohn2 — DISMISSED** [review]
Looks good. Thanks!

**Comment by koysean** [comment]
@rscohn2 could you take a look at this again? I may have done a manual merge when I shouldn't have.

**Comment by rscohn2** [comment]
It looks ok. I don't know why readthedocs fails. I closed/opened the PR to trigger it to run again.

**Comment by rscohn2** [comment]
readthedocs is still broken. Let's wait until tomorrow and hopefully the problem will clear itself.

**Comment by rscohn2** [comment]
macos unit test failed, but it does not look related, closing/opening to trigger again.

**Comment by rscohn2** [comment]
@alalazo Can you review this change? I can no longer approve because I did an 'update-branch' to trigger CI run.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@rscohn2 Done! Fyi, when possible, if you update with a rebase this protection won't be triggered.

**Comment by simonLeary42** [comment]
https://github.com/spack/spack/issues/38401

I raised an issue regarding this change but it hasn't gotten any attention

**Pull request merged**
