### PR TITLE
Features/build spec json ci

### PR DESCRIPTION
**Pull request by nhanford**
This pull request is a copy of #22845 that is testing a CI issue. Plus, coverage should probably be more accurate with this.

### CODE REVIEW

**Comment by tgamblin** [comment]
Ok the problem here seems to be real. We’ll need to figure out what’s causing that hash not to be recognized.

**Comment by nhanford** [comment]
Prior to the missing hash, I see:
```
Did not find linux-ubuntu20.04-ppc64le-gcc-9.3.0-openssl-1.1.1k-mekzw236xq6dw7d7ukzaoic4ker7snxk.spec.json on s3://spack-binaries-prs/pipeline-storage/60376/build_cache/linux-ubuntu20.04-ppc64le-gcc-9.3.0-openssl-1.1.1k-mekzw236xq6dw7d7ukzaoic4ker7snxk.spec.json
```
and
```
Error: Unable to copy build logs from stage to artifacts due to exception: [Errno 2] No such file or directory: '/tmp/root/spack-stage/spack-stage-openssl-1.1.1k-gkehic6xszdjtavcbp74knfi3ppynkvc/spack-build-out.txt'
```
I think this is related to our changes in `binary_distribution.py` to make downloading URLs less defensive...
Is there a quicker way to test this locally?

**Comment by alalazo** [comment]
Hi Nathan, I checked [this failing job](https://gitlab.spack.io/spack/spack/-/jobs/682990) in the Gitlab pipeline and, if it may be of help, the real cause of failure seems to be at line 2806 of the logs. For some reason a deprecated version of `openssl` gets into the spec and these lines:

https://github.com/spack/spack/blob/07a9cb87efa0af647eaa4b6cff8656c69a05a081/lib/spack/spack/package.py#L1349-L1372

make the entire installation fail.

**Comment by nhanford** [comment]
> Hi Nathan, I checked [this failing job](https://gitlab.spack.io/spack/spack/-/jobs/682990) in the Gitlab pipeline and, if it may be of help, the real cause of failure seems to be at line 2806 of the logs. For some reason a deprecated version of `openssl` gets into the spec and these lines:
> 
> https://github.com/spack/spack/blob/07a9cb87efa0af647eaa4b6cff8656c69a05a081/lib/spack/spack/package.py#L1349-L1372
> 
> make the entire installation fail.

Thanks! That's very helpful!

**Comment by alalazo** [comment]
Hi @nhanford You can debug that failure in a docker container if you give the following command (modulo `working_dir` that can be changed to anything appropriate):
```console
$ spack ci reproduce-build --working-dir $PWD https://gitlab.spack.io/api/v4/projects/2/jobs/682990/artifacts
==> [2021-08-31-17:09:40.537888] Fetching artifacts from: https://gitlab.spack.io/api/v4/projects/2/jobs/682990/artifacts
==> [2021-08-31-17:09:44.418306] Job ran with the following image: ghcr.io/scottwittenburg/ecpe4s-ubuntu18.04-runner-x86_64:2020-09-01
checkout_commit: e2b9ba30012aeab5a39f016f6efd7c9cdf9003f0
merge_commit: bd220532d5be1a87c818f68c542a1daf14458d2f
==> [2021-08-31-17:09:46.606560] Job ran with the following tags: ['spack', 'public', 'large', 'x86_64']

Run the following command:

    $ docker run --rm -v /home/culpo/tmp/yaml2json:/builds/spack/spack -ti ghcr.io/scottwittenburg/ecpe4s-ubuntu18.04-runner-x86_64:2020-09-01

Once inside the container:

    - Activate the environment

        $ source /builds/spack/spack/spack/share/spack/setup-env.sh
        $ spack env activate --without-view /builds/spack/spack/jobs_scratch_dir/reproduction

    - Run the install script

        $ /builds/spack/spack/jobs_scratch_dir/reproduction/install.sh
```

**Comment by tgamblin** [comment]
closing this one as work continues on #22845

**Pull request closed without merging**
