### PR TITLE
Package 'libaec': no need to specify per version urls.

### PR DESCRIPTION
**Pull request by skosukhin**
Provided list_url variable lets Spack find URL for a particular version.

### CODE REVIEW

**Comment by skosukhin** [comment]
I reopen this PR because it turned out that the reason why I closed it (#5178) was not related to the package itself.

**Comment by skosukhin** [comment]
The only thing I don't like about this is that Spack reports about a failed attempt to fetch version 1.0.1 from the directory of version 1.0.0:

```(bash)
==> Fetching https://gitlab.dkrz.de/k202009/libaec/uploads/631e85bcf877c2dcaca9b2e6d6526339/libaec-1.0.1.tar.gz
==> Fetching from https://gitlab.dkrz.de/k202009/libaec/uploads/631e85bcf877c2dcaca9b2e6d6526339/libaec-1.0.1.tar.gz failed.
==> Fetching https://gitlab.dkrz.de/k202009/libaec/uploads/926fe2b181865e38a236ad12bf053cfa/libaec-1.0.1.tar.gz
```

We know in advance that this will happen but it looks like we don't have means to express that.

**Comment by skosukhin** [comment]
Should I reopen the PR to rerun the tests?

**Comment by alalazo** [comment]
Restarted tests that errored.

**Pull request merged**
