### PR TITLE
ip2: add NOAA software maintainers and deprecation note

### PR DESCRIPTION
**Pull request by edwardhartnett**
added NOAA software maintainers to maintainer list, added comment about library being deprecated

### CODE REVIEW

**Review by Hang-Lei-NOAA — DISMISSED** [review]

**Comment by t-brown** [comment]
If this is deprecated, I'd prefer to remove it.

Does this mean `wgrib2` can do interpolation when built with `USE_IPOLATES=1`?

**Comment by Hang-Lei-NOAA** [comment]
Yes,  USE_IPOLATES=1 use ip lib
USE_IPOLATES=3 use ip2 lib
These are two different type pf interpolations.

**Comment by kgerheiser** [comment]
They both do interpolation. They difference is that `ip` supports NCEP rotated lat-lon grids (grids 32768, 32769)  while `ip2` uses the WMO rotated lat-lon grib2 definition. I'm working on adding NCEP grid support to the combined ip library and then the options can be combined. Other than that the functionality is identical.

**Comment by edwardhartnett** [comment]
@t-brown ip2 should not be removed yet - it is still important. In a few years, it might be a different story...

**Review by t-brown — APPROVED** [review]

**Comment by edwardhartnett** [comment]
(Although, I guess in a few years, ip2 will be embedded in several versions of important packages, and so will not be able to be removed...)

**Review by sethrj — APPROVED** [review]

**Pull request merged**
