### PR TITLE
biobambam2: Add test method and test scripts.

### PR DESCRIPTION
**Pull request by ghost**
Add test method and test scripts.

### CODE REVIEW

**Comment by haampie** [comment]
Aren't those tests available in the package sources?

**Comment by ghost** [comment]
@haampie
I modifeid testshortsort.sh as follows.
Because testshortsort.sh before modified uses relative path to binary files of biobambam2.
```
-before
sorttestshort | ../src/bamsort | ../src/bamchecksort

-after
sorttestshort | bamsort | bamchecksort
```

And testshortsort.sh, testshortsort.sh and base64decode.sh need to be placed in the same directory.
So I stored three .sh files in the "test" directory.

**Comment by tldahlgren** [comment]
This is a great start but it does not work for me on a linux box I use because the script is not executable. 

Changing
```self.run_test(exe_name,...```
to
```self.run_test('sh', exe_name, ...```
allows me to successfully run the test (and it passes).

However, @haampie is correct in that we want to avoid duplicating files that are available with the staged source code.  It is preferable to add a `cache_test_sources` method to copy the scripts from the staged `test` subdirectory after a successful installation then modify the script for use during smoke testing.

Documentation for this method can be found at https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-build-time-files.  In your case, you'd want to either copy the entire staged `test` subdirectory during installation, or you could pass `self.cache_extra_test_sources` a list of the relative paths to the three scripts.  In that same method you could then either patch -- possibly too heavy weight -- or use spack `filter_file` to make the path changes.  (I've experimented with both.)

**Comment by tldahlgren** [comment]
FWIW.  You could try something along the lines:

```
    test_src_dir = 'test'

    def _fix_shortsort(self):
        """Fix the testshortsort.sh file copied during installation."""
        test_dir = join_path(self.install_test_root, self.test_src_dir)
        filter_file('../src/', '', join_path(test_dir, 'testshortsort.sh'))

    @run_after('install')
    def cache_test_sources(self):
        """Copy the test source files after the package is installed to an
        install test subdirectory for use during `spack test run`."""
        self.cache_extra_test_sources(self.test_src_dir)
        self._fix_shortsort()

    def test(self):
        test_dir = join_path(self.install_test_root, self.test_src_dir)

        self.run_test('sh', ['testshortsort.sh'],
                      expected='Alignments sorted by coordinate.',
                      work_dir=test_dir)
```

**Comment by ghost** [comment]
Thank you for your advice.
I fixed that according to your advice.

**Comment by tldahlgren** [comment]
> Thank you for your advice.
> I fixed that according to your advice.

You are most welcome.

**Review by tldahlgren — APPROVED** [review]
LGTM.  Confirmed I can successfully run the tests from the latest commit.

**Comment by tldahlgren** [comment]
Thank you for your contribution!

**Pull request merged**
