### PR TITLE
darshan-runtime,darshan-util,py-darshan: add 3.4.3 releases

### PR DESCRIPTION
**Pull request by shanedsnyder**
* darshan-runtime 3.4.3
* darshan-util 3.4.3
* py-darshan 3.4.3.0
  - add py-humanize as new dependency

### CODE REVIEW

**Review by carns — APPROVED** [review]

**Review by jeanbez — APPROVED** [review]

**Review by tldahlgren — DISMISSED** [review]
Confirmed the three version sha256.

**Comment by tldahlgren** [comment]
`spack spec py-darshan` succeeds.

**Comment by tldahlgren** [comment]
@adamjstewart did you want to comment on the py-darshan addition or can this be merged?

**Comment by manuelakuhn** [comment]
According to the sources on pypi (from `pyproject.toml` and `setup.py`):
- 3.4.3.0 dropped support for python@3.6
- there is a restriction on `setuptools<64.0.0` starting from 3.4.3.0
- where is the `py-importlib-resources` dependency for newer python versions coming from? I only see it as dependency in 3.4.2.0 for python@3.6 which is not supported any more with 3.4.3.0
- there is a missing build requirement on `py-pyterst-runner` (see `setup_requirements` in `setup.py`)
- where are the version restrictions for `py-numpy` and `py-matplotlib` coming from?

**Comment by shanedsnyder** [comment]
> 3.4.3.0 dropped support for python@3.6

I updated our python dependency to require 3.7+ in the py-darshan package to be clear. ([a864722](https://github.com/spack/spack/pull/38359/commits/a864722116bf1cb7b4c74bbd6d5c35571c9db5d7))

> there is a restriction on `setuptools<64.0.0` starting from 3.4.3.0

This restriction was to support editable Python installs (see https://github.com/darshan-hpc/darshan/pull/890). Given that this functionality is only useful for people building py-darshan from source (e.g., py-darshan developers, likely not using Spack), I don't think we need to bring the dependency in here.

> where is the `py-importlib-resources` dependency for newer python versions coming from? I only see it as dependency in 3.4.2.0 for python@3.6 which is not supported any more with 3.4.3.0

I removed this dependency as well. It's no longer required with 3.6 deprecated. ([543340c](https://github.com/spack/spack/pull/38359/commits/543340c5d6135f1e56e04a0f37f940da34daec67))

> there is a missing build requirement on `py-pyterst-runner` (see `setup_requirements` in `setup.py`)

This is done. ([351f8b4](https://github.com/spack/spack/pull/38359/commits/351f8b4d54fa8bb1e46365ccc282fa627ecdd517))

> where are the version restrictions for `py-numpy` and `py-matplotlib` coming from?

I think the numpy pin was an oversight as it's not used anywhere else in our repo. matplotlib pin is no longer required. Dropped both in [7540216](https://github.com/spack/spack/pull/38359/commits/7540216693d24d0eb5f1e86cdb0d6eedd5df6c8f) & [58405f2](https://github.com/spack/spack/pull/38359/commits/58405f2110deeec185f27940d6b09a0fce44fb56).

**Comment by shanedsnyder** [comment]
I added another commit to properly enforce the strict version requirements between py-darshan and darshan-util. Basically, 3.4.0.x versions of PyDarshan rely strictly on 3.4.0 versions of darshan-util (and 3.4.1.x versions rely on 3.4.1 and so on). See [7febc75](https://github.com/spack/spack/pull/38359/commits/7febc754f74ce2ad532ecf79b98dbf32a6cb7b0e)

I also added proper version checking for the py-humanize dependency, ([187c7d5](https://github.com/spack/spack/pull/38359/commits/187c7d50d00b5724581a3ea0c21b9e8c0e49641a)), dropped a now optional lxml dependency ([ce54c0f](https://github.com/spack/spack/pull/38359/commits/ce54c0f6610d34728f1eced2e78b3e9e0ddb8698)), and added appropriate version check for our indirect scipy dependency ([7ae8332](https://github.com/spack/spack/pull/38359/commits/7ae8332b22f9866e191d5521fcd3c959c59f26f3)).

**Comment by adamjstewart** [comment]
The 3.4.3.0 version still has these constraints though. Should we wait until a 3.4.3.1 release or code these constraints into the 3.4.3.0 version? Spack won't break if we keep things as is because we currently disable pip from checking dependency versions, but if we ever add that or use `pip check` to make sure things are correct, it could break.

**Comment by shanedsnyder** [comment]
Okay, I think I addressed the last comment here: [f9aba5c](https://github.com/spack/spack/pull/38359/commits/f9aba5c72ed0d4a867e9ba51916ca984caf6b386)

I think that's the last of the changes on my end but let me know if there's more issues.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
ping @adamjstewart

**Review by adamjstewart — APPROVED** [review]
LGTM, although I didn't check older versions. I'll let @manuelakuhn give one more review. Also, did you want to deprecate the pre-release versions of darshan-runtime or keep them in there?

**Review by manuelakuhn — APPROVED** [review]
LGTM and installs with "--test=root" on Fedora37 with gcc@12.3.1

**Pull request merged**
