### PR TITLE
nvtop: add version 2.0.2

### PR DESCRIPTION
**Pull request by wyphan**

### CODE REVIEW

**Comment by wyphan** [comment]
@spackbot maintainers

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.  Will defer merge to give @marcost2 a chance to comment.

**Comment by marcost2** [comment]
sha256 looks good; compiles & runs fine. Good by me
@tldahlgren is the change in the URL version even needed? Spack should just be able to detect and replace properly right?

**Comment by tldahlgren** [comment]
> sha256 looks good; compiles & runs fine. Good by me
> @tldahlgren is the change in the URL version even needed? Spack should just be able to detect and replace properly right?

That is correct to say the URL version change is not required; however, some package maintainers like to keep it up-to-date so there's no harm in doing it.

**Pull request merged**
