### PR TITLE
ensure view projections for extensions always point to extendee

### PR DESCRIPTION
**Pull request by becker33**
Fixes bug introduced in #29317

### CODE REVIEW

**Comment by becker33** [comment]
@haampie views outside of environments are the issue

```
$ cat projections.yaml
projections:
  python: python
  all: all
$ spack view add --projection-file projections.yaml my_view py-six
==> Warning: [my_view] Skipping external package: py-pip@0.29.32%apple-clang@14.0.0 build_system=generic arch=darwin-monterey-m1/hzvnhbp
==> Warning: [my_view] Skipping external package: python@3.9%apple-clang@14.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,4c24573,f2fd060 arch=darwin-monterey-m1/tm7bw3r
$ ls -la my_view/
total 0
drwxr-xr-x   4 becker33  51202  128 Nov 11 08:08 ./
drwxr-xr-x  10 becker33  51202  320 Nov 11 08:08 ../
drwxr-xr-x   3 becker33  51202   96 Nov 11 08:08 .spack/
drwxr-xr-x   6 becker33  51202  192 Nov 11 08:08 all/
$ # Made these changes
$ spack view add --projection-file projections.yaml my_new_view py-six
==> Warning: [my_new_view] Skipping external package: py-pip@0.29.32%apple-clang@14.0.0 build_system=generic arch=darwin-monterey-m1/hzvnhbp
==> Warning: [my_new_view] Skipping external package: python@3.9%apple-clang@14.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,4c24573,f2fd060 arch=darwin-monterey-m1/tm7bw3r
$ ls -la my_new_view/
total 0
drwxr-xr-x   4 becker33  51202  128 Nov 11 08:14 ./
drwxr-xr-x  11 becker33  51202  352 Nov 11 08:14 ../
drwxr-xr-x   3 becker33  51202   96 Nov 11 08:14 .spack/
drwxr-xr-x   6 becker33  51202  192 Nov 11 08:14 python/
```

**Comment by haampie** [comment]
Hm, what about `SimpleFilesystemView`? That one is used in environment views iirc.

**Comment by haampie** [comment]
Hm, seems to be OK for environments.

Edit: ah, `get_relative_projection_for_spec` is doing the job in `SimpleFilesystemView`

**Review by haampie — APPROVED** [review]
Thanks!

**Comment by haampie** [comment]
@spackbot rerun pipeline

**Comment by haampie** [comment]
@spackbot rerun pipeline

**Review by tgamblin — APPROVED** [review]

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
