### PR TITLE
flecsi+legion: add cr versions FleCSI depended on in past releases

### PR DESCRIPTION
**Pull request by rbberger**
Following the discussion in https://github.com/spack/spack/pull/43410, this is another attempt at adding the necessary unreleased versions of Legion for building FleCSI releases. @elliottslaughter I tried doing this without touching the Legion spackage, but it seems the Spack devs would prefer this.

### CODE REVIEW

**Comment by elliottslaughter** [comment]
I'm fine with this, although are we really going back all the way to 2019 for commits? We don't even have the official releases of Legion going back that far in this spackage.

**Comment by rbberger** [comment]
FleCSI 1.4 is already marked deprecated and will be removed after the next Spack release. After we get 2.3.0 out I suspect @opensdh might be open to deprecation of more versions.

**Review by elliottslaughter — APPROVED** [review]

**Comment by rbberger** [comment]
@alalazo is this ok with you?

**Comment by rbberger** [comment]
Pushed one more commit on this. FleCSI's `develop` is not something anyone should be using, it's not even used internally. The closest we have to an actual `develop` is the `2.2` and `2`  branches, but we don't want to advertise those via Spack.

**Comment by rbberger** [comment]
@tldahlgren could you take a look? thank you!

**Review by tldahlgren — APPROVED** [review]
Confirmed the branch and version commits.

**Pull request merged**
