### PR TITLE
develop: canonicalize dev paths and base relative paths on `env.path` (#30075)

### PR DESCRIPTION
**Pull request by becker33**
Allow environment variables and spack-specific path substitution variables (e.g. $spack) to be used in the paths associated with develop specs, while maintaining the ability to keep those paths relative to the environment rather than the working directory.

Fixes a bug reported by @tomstitt in an out-of-band conversation.

@tgamblin @scheibelp @kennyweiss let me know if I should ping anyone else.

### CODE REVIEW

**Review by tgamblin — CHANGES_REQUESTED** [review]
LGTM but needs a test

**Comment by becker33** [comment]
> LGTM but needs a test

Really probably needs 5, I don't think I can hit all of those code paths with 1. Working on it

ETA: I probably exaggerate... I think I may be able to cover it with two tests. I'll start there and add more depending on the coverage report.

**Comment by becker33** [comment]
@tgamblin test is included.

**Comment by tgamblin** [comment]
@becker33 failing style

**Comment by alalazo** [comment]
@spackbot fix style

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
