### PR TITLE
cmake: add v3.27.6

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by haampie** [comment]
```
CMake Error: CMake can not determine linker language for target: run_test_zcomplexabs
CMake Error: CMake can not determine linker language for target: run_test_zcomplexdiv
CMake Error: CMake can not determine linker language for target: run_test_zcomplexmult
CMake Error: CMake can not determine linker language for target: run_test_zminMax
```

nice!

**Comment by haampie** [comment]
@johnwparent are you involved in CMake? I see your name on the release announcements. Otherwise pinging @mathstuf since from the release notes it looks like the build failure is likely related to your changes :upside_down_face: 

See https://gitlab.spack.io/spack/spack/-/jobs/8225504 and the relevant cmake stuff: https://github.com/Reference-LAPACK/lapack/blob/ae2f14fe1f0dd94b2dacc1c35107f0ea5b5c6f07/CMakeLists.txt#L50-L80

Is this a regression in CMake?

**Comment by haampie** [comment]
It was reported https://gitlab.kitware.com/cmake/cmake/-/issues/25252

**Comment by johnwparent** [comment]
> @johnwparent are you involved in CMake? I see your name on the release announcements. 

I am involved in CMake. I assist in cutting the releases and contribute features when required by a project. Feel free to ping me on any CMake related issue you're encountering (like this one).  

> See https://gitlab.spack.io/spack/spack/-/jobs/8225504 and the relevant cmake stuff: https://github.com/Reference-LAPACK/lapack/blob/ae2f14fe1f0dd94b2dacc1c35107f0ea5b5c6f07/CMakeLists.txt#L50-L80
> 
> Is this a regression in CMake?

This does seem to be a regression, and it is being looked into on the CMake side. It does seem like Lapack master has resolved this however.

**Comment by alalazo** [comment]
@johnwparent OT: do you want to be added as a maintainer of the CMake package too?

**Comment by johnwparent** [comment]
@alalazo Sure, that's probably a good idea considering.

**Comment by haampie** [comment]
The issue was fixed in 3.27.6, so let's skip .5

**Pull request merged**
