### PR TITLE
ecp-data-vis-sdk: Combine the vis and io SDK packages

### PR DESCRIPTION
**Pull request by chuckatkins**
This better enables the collective set to be deployed together satisfying
eachothers dependencies with desired variants

### CODE REVIEW

**Review by opadron — APPROVED** [review]

**Review by opadron — APPROVED** [review]

**Comment by chuckatkins** [comment]
Okay, so this got heavier than I expected; I ended up implementing a helper function for mapping the Cartesian product of multiple package variants to dependencies.  I'd love a cleaner way to do this but AFAIK it will necessitate using the clingo concretizer.  It's also hung up on python 2.6 compatibility because I'm using dictionary comprehension and the '**' operator.  Aside from the 2.6 compatibility issues it should be ready for review.

**Comment by chuckatkins** [comment]
Okay, this should now be good wrt python 2.6 compatibility

**Comment by alalazo** [comment]
@chuckatkins The tool in #23053 reports non-existing variants (`catalyst`, `cinema`, `visit`). I see in the package this is known and some are marked as outstanding concretization failures. Are they referring to the old or new concretizer? Is there anything I can do to help, or issue I can follow?

**Comment by chuckatkins** [comment]
The concretization failures are with the old, not new, but I can't really assume the new is being used yet even if it does fix the issues.  Just commenting out the variants was the easiest way to disable them but I'm happy to completely comment out where they're used as well.

**Comment by alalazo** [comment]
> Just commenting out the variants was the easiest way to disable them but I'm happy to completely comment out where they're used as well.

No worries. At the moment I'm just testing a few sanity checks from the PR linked above. The comment is just because I'm eager to fix issues with the new concretizer - so I was wondering if I missed an important one here!

**Pull request merged**
