### PR TITLE
New R database packages

### PR DESCRIPTION
**Pull request by glennpj**
This PR adds R packages for interacting with databases. There are several new packages including some non-R dependencies and a binutils patch. 

The binutils patch is necessary to update symbols and set the default version when there are multiple versions set, as is the case with libmysqlclient.so. 

https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=544ddf9322b1b83982e5cb84a54d084ee7e718ea

It will be necessary to rebuild binutils-2.26 for clients linked with libmysqlclient.so to work.

The libaio package was added as a dependency for mariadb. This is Linux only so it was handled in the same way as libpciaccess for Mac, #257.

### CODE REVIEW

**Comment by citibeth** [comment]
Wow, this is a big commit that will provide a lot of useful things to many of us.  Thank you!

Serious issues:

1. Package names need to be all lower-case.  i.e. .../r-dbi/package.py, instead of .../r-DBI/package.py.  Mixed case leads to unending confusion.  Please fix all mixed-case package names.

1. Please move the binutils changes to a separate PR.  This needs more discussion, and may require / produce changes in other packages.  I don't yet understand the justification based on one sentence above.

1. Please move mariadb and libaio to a separate package.  We need more discussion to determine:
   a) Is this the right way to check for Mac architecture?  (I believe there's some new standard functionality for that).
   b) In case this is a Mac, is installing a dummy libaio the right thing to do?  Or should the change be made in mariadb?
   c) Make sure Mariadb installs OK on Mac and non-Mac.  Mariadb is a popular package that many people want, so we need to get this right.
    d) Should mariadb install a virtual 'mysql' package?  Or has MariaDB effectively become the standard?


Nitpicks:

1. Need to decide whether to call it r-mysql or r-rmysql.  We have the same problem in Python land, and unfortunately no clear conclusion.  The result is constant confusion.

1. Consider putting different packages in separate PR's.  Especially ones that are not directly DB-related.  At minimum, I would suggest the following PR's (in addition to the ones mentioned above):
   1. One PR per non-R supporting library
   1. One PR for all new databases, if any (other than MariaDB)
   1. One PR for R/Java stuff.
   1. One PR for all other R interfaces

1. For r-java, do we have a Spack Java build?  Or does this currently use the System Java?  Can we have a Spack Java build?

1. Too many gratuitious whitespace changes.  Please remove when not needed (eg: lining things up in columns when they weren't originally; or formatting the comment on PostGreSQL.)

**Comment by tgamblin** [comment]
@glennpj: If you want to change the package names to lowercase that would make me happy.

RE: other issues by @citibeth:

1. What dose the `binutils` patch do?  Is this just a fix for some binutils compatibility issues?  I've seen many builds fail with `binutils@2.26` so I set the preferred `binutils` version to `2.25`.  If this fixes that issue I think this patch could be very useful.

2. The rest of @citibeth's issues seem to me like things that can be worked on incrementally in the packages.  Generally if something is only going to affect a specific package I'm much more inclined to merge and sort the details out later, than something that will affect the entire Spack core.

**Comment by glennpj** [comment]
@citibeth Thanks for the feedback.
> 1. Package names need to be all lower-case. i.e. .../r-dbi/package.py, instead of .../r-DBI/package.py. Mixed case leads to unending confusion. Please fix all mixed-case package names.

I did not realize that was a policy. I did see other packages that were not all lower case so I stuck with how upstream named them. I can change those.

> 2. Please move the binutils changes to a separate PR. This needs more discussion, and may require / produce changes in other packages. I don't yet understand the justification based on one sentence above.

Here is a link with a bit more detail, and that contains a link to the patch.
FS#48394 : [binutils] [libmariadbclient] Versioned symbols missing from library in 10.1.12-1 - https://bugs.archlinux.org/task/48394

My understanding is that will be in the next release of binutils. Since that does require a rebuild maybe it would be better to wait until the next binutils is released and hold off on mariadb and packages that link to libmysqlclient until then.

> 3. Please move mariadb and libaio to a separate package. We need more discussion to determine:
a) Is this the right way to check for Mac architecture? (I believe there's some new standard functionality for that).

This PR went in before the newarch PR so there may be a better way to check now. I have not had a chance to look at the newarch changes yet.

> b) In case this is a Mac, is installing a dummy libaio the right thing to do? Or should the change be made in mariadb?

There needs to be a way to specify something that is only for a particular architecture. In the absence of that I used the precedent set in #257. It is definitely not ideal. Maybe it is possible with the newarch changes to setup a conditional in the mariadb package now but I do not know.

> c) Make sure Mariadb installs OK on Mac and non-Mac. Mariadb is a popular package that many people want, so we need to get this right.

Agreed.

> d) Should mariadb install a virtual 'mysql' package? Or has MariaDB effectively become the standard?

I am not sure. I think for open source mariadb is the way forward but some people may want the mysql community edition as an option.

> Need to decide whether to call it r-mysql or r-rmysql. We have the same problem in Python land, and unfortunately no clear conclusion. The result is constant confusion.

The name of the package is `rmysql` and that is prefixed with `r-` for spack. I agree that is awkward but I think it is correct.

> Consider putting different packages in separate PR's.

I think the issue there is the dependencies, which is why I tried to group these. Is there a way to handle dependencies in PRs?

> For r-java, do we have a Spack Java build? Or does this currently use the System Java? Can we have a Spack Java build?

There is a jdk build. To use java, R has to be built with java support. That was added to #1000 and rjava should pick it up from there. I could add an explicit dependency for it in rjava as well.

> Too many gratuitious whitespace changes. Please remove when not needed (eg: lining things up in columns when they weren't originally; or formatting the comment on PostGreSQL.)

Admittedly, I may have got carried away with formatting the comment in postgresql (not sure if that was related to autopep8 or not) but many of the whitespace changes are to satisfy flake8. Also, I thought there was a desire to get things pep8 compliant. I have recently tried to separate out those pep8 changes to a separate commit but I have not submitted those PRs yet.

So, I will work on the changes later and I guess we need to decide on mariadb and binutils.

Thanks.

**Comment by glennpj** [comment]
> If you want to change the package names to lowercase that would make me happy.

Will do. I suggest that this requirement be added to the packaging guide, and the template as well, as referenced in issue #326.

Thanks.

**Comment by tgamblin** [comment]
@glennpj: good point.  I don't know if I want this to be a hard requirement, but I think enforcing it as you suggest is a good idea.  I'm actually not opposed to mixed case names with good reason. e.g. I think `R` probably ought to be uppercase.  Thoughts?

**Comment by glennpj** [comment]
I have changed the package directory names to lowercase.
@tgamblin What do you want me to do with mariadb and binutils?

Thanks.

**Comment by tgamblin** [comment]
@glennpj: the binutils patch fixes a known bug so I think it's a good thing to include.  Also, 2.25 is still preferred so we can test out the new 2.26 before using it.  I'm ok with merging this.  Thanks for the truly extensive R support!

**Comment by alalazo** [comment]
@glennpj thanks for all these R related contributions : they will be much appreciated at my site!

**Comment by citibeth** [comment]
+1!

**Pull request merged**
