### PR TITLE
MAGMA: 2.7.1

### PR DESCRIPTION
**Pull request by stomov**
MAGMA 2.7.1 release

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.

**Comment by tldahlgren** [comment]
Looks like there are CI build errors for 2.7.1 (see https://gitlab.spack.io/spack/spack/-/jobs/5730669).


```
...
>> 2859    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:75:54: error: u
             se of undeclared identifier 'hipblasFloatComplex'[0m
     2860        hipblasIcamax( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2861                                                         ^
>> 2862    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:75:74: error: e
             xpected expression[0m
     2863        hipblasIcamax( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2864                                                                      
                    ^
>> 2865    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:107:54: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2866        hipblasIcamin( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2867                                                         ^
>> 2868    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:107:74: error: 
             expected expression[0m
     2869        hipblasIcamin( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2870                                                                      
                    ^
>> 2871    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:139:54: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2872        hipblasScasum( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2873                                                         ^
>> 2874    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:139:74: error: 
             expected expression[0m
     2875        hipblasScasum( queue->hipblas_handle(), int(n), (hipblasFloatC
             omplex*)dx, int(incx), &result );
     2876                                                                      
                    ^
>> 2877    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:53: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2878        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2879                                                        ^
>> 2880    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:73: error: 
             expected expression[0m
     2881        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2882                                                                      
                   ^
>> 2883    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:83: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2884        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2885                                                                      
                             ^
>> 2886    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:103: error:
              expected expression[0m
     2887        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2888                                                                      
                                                 ^
>> 2889    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:120: error:
              use of undeclared identifier 'hipblasFloatComplex'[0m
     2890        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2891                                                                      
                                                                  ^
>> 2892    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:181:140: error:
              expected expression[0m
     2893        hipblasCaxpy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)&alpha, (hipblasFloatComplex*)dx, int(incx), (hipblasFloatC
             omplex*)dy, int(incy) );
     2894                                                                      
                                                                               
                    ^
>> 2895    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:218:53: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2896        hipblasCcopy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy) );
     2897                                                        ^
>> 2898    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:218:73: error: 
             expected expression[0m
     2899        hipblasCcopy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy) );
     2900                                                                      
                   ^
>> 2901    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:218:90: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2902        hipblasCcopy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy) );
     2903                                                                      
                                    ^
>> 2904    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:218:110: error:
              expected expression[0m
     2905        hipblasCcopy( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy) );
     2906                                                                      
                                                        ^
>> 2907    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:257:53: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2908        hipblasCdotc( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy), (hipbla
             sFloatComplex*)&result );
     2909                                                        ^
>> 2910    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:257:73: error: 
             expected expression[0m
     2911        hipblasCdotc( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy), (hipbla
             sFloatComplex*)&result );
     2912                                                                      
                   ^
>> 2913    /tmp/root/spack-stage/spack-stage-magma-2.7.1-4pfvsw4e2g5t6lrxvhto
             wkbvnml47d4f/spack-src/interface_hip/blas_c_v2.cpp:257:90: error: 
             use of undeclared identifier 'hipblasFloatComplex'[0m
     2914        hipblasCdotc( queue->hipblas_handle(), int(n), (hipblasFloatCo
             mplex*)dx, int(incx), (hipblasFloatComplex*)dy, int(incy), (hipbla
             sFloatComplex*)&result );
     2915                                                                      
                                    ^
     2916    fatal error: too many errors emitted, stopping now [-ferror-limit=
             ]
     2917    20 errors generated when compiling for gfx90a.
...
```

**Comment by stomov** [comment]
@tldahlgren Yes, there was error in the order of generations! Thanks for catching it. I updated the tarball for the release and put/updated the new sha256 in the spack pull request.

**Review by tldahlgren — DISMISSED** [review]
Confirmed the (new/revised) sha256.

**Comment by tldahlgren** [comment]
Weird that one stack -- one of the `ml` stacks -- fails seemingly due to a python 3.10 issue.  Not sure if this will help, but worth a try:

@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Review by luszczek — DISMISSED** [review]

**Review by alalazo — APPROVED** [review]

**Review by G-Ragghianti — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
