### PR TITLE
py-pandas: add v2.1.2

### PR DESCRIPTION
**Pull request by adamjstewart**
https://pandas.pydata.org/pandas-docs/version/2.1.2/whatsnew/v2.1.2.html

### CODE REVIEW

**Review by manuelakuhn — COMMENTED** [review]
According to [pyproject.toml#L32-34](https://github.com/pandas-dev/pandas/blob/v2.1.2/pyproject.toml#L32-L34) there are additional `py-numpy` dependencies depending on the used python version:
```
  "numpy>=1.22.4,<2; python_version<'3.11'",
  "numpy>=1.23.2,<2; python_version=='3.11'",
  "numpy>=1.26.0,<2; python_version>='3.12'",
```

**Comment by adamjstewart** [comment]
The same kind of thing appears in scipy as well. I believe these are the minimum versions of numpy needed for support for those versions of Python. @rgommers can you explain why scipy adds these to `pyproject.toml`? I'm guessing it's something to do with building the most compatible possible binary for each Python version (numpy may add features but is less likely to remove them). I'm pretty sure we can skip them and let the concretizer ensure that compatible versions are chosen.

**Comment by rgommers** [comment]
They are different things. The constraints for Pandas two comments up are the actual minimum `numpy` versions that support the given Python versions for <3.11, 3.11 and 3.12. So those are needed in Spack as well. And they are the same as needed for SciPy within Spack.

The SciPy constraints in its pyproject.toml that you ask about contain some of that, but are more restrictive with `==` constraints. Those exact pins to the lowest possible numpy version per Python minor version are due to C ABI constraints. They only apply if there's a scenario where you build SciPy separately from the NumPy in your environment (e.g., you cannot build scipy against numpy 1.24 and then install that built scipy in a different env with numpy 1.23). So that applies for PyPI, but not for most Spack (nor for your typical Linux distro).

**Comment by adamjstewart** [comment]
But don't the `python_requires`/`depends_on` in numpy already control this? Seems like the `dependencies`/`depends_on` in pandas are superfluous. Spack (and presumably pip) already make it impossible to install old versions of numpy that don't support newer Python versions. Is it only there for compatibility with ancient versions of numpy that didn't document an upper bound? We do this in Spack now so I still don't think it's necessary to copy from `pyproject.toml`.

**Comment by rgommers** [comment]
> But don't the `python_requires`/`depends_on` in numpy already control this?

Ah yes, I think you are right. For `==` that doesn't apply, but for `>=` it's true. So here, a simple `numpy>=1.22.4,<2` would be enough and cover all Python versions.

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@adamjstewart Feel free to merge if you're not still polishing the PR

**Pull request merged**
