### PR TITLE
Use define_from_variant in numerous CMakePackages

### PR DESCRIPTION
**Pull request by sethrj**
This is a find-replace job for a lot of different ways to express `self.define_from_variant('foo', 'bar')`. I'm not sure if the best approach to this is to do one huge merge request and try to ping all 83 packages that this touched... or to just have a couple people spot check and address potential issues as they crop up.

There's a possibility that this will cause some package recipes to fail by exposing previously hidden typos due to `'+nonexistent_variant' in spec` returning `False` rather than raising an error.

### CODE REVIEW

**Review by ax3l — DISMISSED** [review]
For the packages where I am listed as maintainer: :shipit: :grin:

**Comment by sethrj** [comment]
Pinging @alalazo and @tgamblin and other high-level maintainers—I double checked the logical equivalence in the packages I reviewed here, and caught at least one instance of a package that referenced a nonexistent variant, so there's likely to be a couple of packages here that also break. (Note that my changes *expose* silent errors in the existing recipe, rather than creating new ones.) Permission to merge? I'll help package authors deal with the fallout if there is any 😅

**Review by alalazo — DISMISSED** [review]
I agree with this change, since it makes recipes a lot terser. It would be good if we can trigger manually an E4S rebuild, but I don't know how easy / feasible that is. @tgamblin @scottwittenburg ?

**Comment by sethrj** [comment]
> I agree with this change, since it makes recipes a lot terser. It would be good if we can trigger manually an E4S rebuild, but I don't know how easy / feasible that is. 

CC @eugeneswalker

**Comment by eugeneswalker** [comment]
I could trigger a rebuild from this PR this afternoon and report results here tomorrow morning. Would that work?

**Comment by sethrj** [comment]
> I could trigger a rebuild from this PR this afternoon and report results here tomorrow morning. Would that work?

That would be perfect! Thank you!

**Comment by eugeneswalker** [comment]
> I could trigger a rebuild from this PR this afternoon and report results here tomorrow morning. Would that work?

The only issue I found was with `faodel` and the non-existence of the `leveldb` variant:

```
$> spack install faodel
...
==> Installing faodel-1.1906.1-eeooxoufstzl5ufldurkcugzspld3bvk
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/4b/4b3caf469ae7db50e9bb8d652e4cb532d33d474279def0f8a483f69385648058.tar.gz
==> Applied patch /spack/var/spack/repos/builtin/packages/faodel/lambda-capture-f0267fc.patch
==> Applied patch /spack/var/spack/repos/builtin/packages/faodel/ugni-target-redef-b67e856.patch
==> faodel: Executing phase: 'cmake'
==> Error: KeyError: '"leveldb" is not a variant of "faodel"'

/spack/lib/spack/spack/build_systems/cmake.py:279, in define_from_variant:
        276        if variant is None:
        277            variant = cmake_var.lower()
        278
  >>    279        if variant not in self.variants:
        280            raise KeyError(
        281                '"{0}" is not a variant of "{1}"'.format(variant, self.name))
        282
```

From package.py:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/faodel/package.py#L45-L50

Any other E4S packages touched by this built OK. All in all there were only about 40 packages in our E4S Spack environment that were affected by this, so there is not complete coverage.

**Comment by sethrj** [comment]
Thanks! I'll try to update the recipe and ping the maintainer since this likely means a recipe bug. Thanks! E4S is probably the most reliable/testable/extensive spack user ☺️ so want to make sure we don't break anything there.

**Comment by sethrj** [comment]
@fbudin69500 — see #11267, I've commented out the `+leveldb` variant usage in faodel. If it needs to be restored, you can delete the comment markers and add a `conflicts` for the old/incompatible versions.

**Comment by sethrj** [comment]
Sorry needs reapproval after the last commit @ax3l or @alalazo 😬

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@sethrj Let me know when you're ready for this to be merged.

**Pull request merged**
