### PR TITLE
Add new MavenPackage build system base class

### PR DESCRIPTION
**Pull request by adamjstewart**
We've seen a lot of new packages lately using the Maven build system. This PR adds a new `MavenPackage` base class to enforce uniformity between these packages and make it easier to write new packages.

According to https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases, Maven packages have a series of lifecycle phases. I tried adding all of these to the base class as separate phases, but from what I can tell it re-runs all prior stages of the lifecycle.

Note that all of these packages pull in dozens to hundreds of dependencies from the internet. At some point, we should find a way to enforce offline builds and add packages for all of the dependencies, but I don't care enough about Maven to be the person to do that.

@darmac I believe you added many of these packages. Can you review this PR and make sure I didn't break any packages you care about?

### CODE REVIEW

**Comment by darmac** [comment]
Got it, I'll study this PR recently.

**Review by alalazo — APPROVED** [review]

**Comment by adamjstewart** [comment]
I confirmed that `zipkin` installs correctly. Many of the other packages don't install for me, and I'm not sure if they ever did.

**Comment by darmac** [comment]
> I confirmed that `zipkin` installs correctly. Many of the other packages don't install for me, and I'm not sure if they ever did.

I'm not verified anything yet, I still check some `maven` doc to make sure I'll not miss some import feature of `maven`.
And after that I will check the codes and some maven package.
I think it may take me 3 or 4 days to finish that.

**Comment by darmac** [comment]
I tested all of the package that @adamjstewart  had refined.
And found : `kinesis, hudi, mrbench, presto, slf4j, phoenix, sqoop, slider, zipkin` build fail.
Some fail caused by upstream code or my environment, and the others may caused by this patch.
I'm still checking how to fix these issue now.

On the other hand, I have some questions about `Maven` build system, I'll comment them later after I made it more clearly.

**Comment by adamjstewart** [comment]
It's weird that zipkin works for me but not for you. I didn't really change the recipe for that one. At some point, someone needs to go through these packages and explicitly list every dependency, but not me.

**Comment by darmac** [comment]
> It's weird that zipkin works for me but not for you. I didn't really change the recipe for that one. At some point, someone needs to go through these packages and explicitly list every dependency, but not me.

My platform is  `CentOS` & `aarch64`, and some websites are difficult for me to access(due to the regional or company firewall reasons), so maybe something diefferent with these environments.

**Comment by darmac** [comment]
I found this package cannot be created as a `MavenPackage`:
https://github.com/alibaba/nacos/archive/1.3.2.tar.gz

It creates `nacos` as a `Package` by using `spack create https://github.com/alibaba/nacos/archive/1.3.2.tar.gz` as following:
```
from spack import *


class Nacos(Package):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "https://www.example.com"
    url      = "https://github.com/alibaba/nacos/archive/1.3.2.tar.gz"

    # FIXME: Add a list of GitHub accounts to
    # notify when the package is updated.
    # maintainers = ['github_user1', 'github_user2']

    version('1.3.2', sha256='1e4d5533c71ddc4971db7b67e83c09adaf6fd3d5fc7fa04915082356893dcf5b')

    # FIXME: Add dependencies if required.
    # depends_on('foo')

    def install(self, spec, prefix):
        # FIXME: Unknown build system
        make()
        make('install')
```

And is `pom.xml` is in the stage directory:
```
[root@Estuary-CentOS8 spack-src]# ls
address  BUILDING      client  CODE_OF_CONDUCT.md  config       console          core          doc      istio    naming  pom.xml    REPORTING-BUGS.md  style
api      CHANGELOG.md  cmdb    common              consistency  CONTRIBUTING.md  distribution  example  LICENSE  NOTICE  README.md  resources          test
```

**Comment by adamjstewart** [comment]
@darmac that's a Spack + GitHub bug unrelated to `MavenPackage`. See #14129, I'm sure there are other examples.

The issue is that GitHub has multiple types of downloads available. When you run:
```console
$ spack create https://github.com/alibaba/nacos/archive/1.3.2.tar.gz
```
the spider finds:
```
  1.3.2         https://github.com/alibaba/nacos/releases/download/1.3.2/nacos-server-1.3.2.tar.gz
  1.3.1-beta    https://github.com/alibaba/nacos/archive/1.3.1-beta.tar.gz
  1.3.1-BETA    https://github.com/alibaba/nacos/releases/download/1.3.1-beta/nacos-server-1.3.1-BETA.tar.gz
  1.3.1         https://github.com/alibaba/nacos/releases/download/1.3.1/nacos-server-1.3.1.tar.gz
  1.3.0-beta    https://github.com/alibaba/nacos/archive/1.3.0-beta.tar.gz
  1.3.0-BETA    https://github.com/alibaba/nacos/releases/download/1.3.0-beta/nacos-server-1.3.0-BETA.tar.gz
  1.3.0         https://github.com/alibaba/nacos/releases/download/1.3.0/nacos-server-1.3.0.tar.gz
  1.2.1         https://github.com/alibaba/nacos/releases/download/1.2.1/nacos-server-1.2.1.tar.gz
  1.2.0-beta.1  https://github.com/alibaba/nacos/releases/download/1.2.0-beta.1/nacos-server-1.2.0-beta.1.tar.gz
  ...
  1.1.4         https://github.com/alibaba/nacos/releases/download/1.1.4/nacos-server-1.1.4.tar.gz
```
Some of these are the original archive we want, while others are a smaller `nacos-server` tarball which doesn't contain `pom.xml`.

**Comment by darmac** [comment]
> I tested all of the package that @adamjstewart had refined.
> And found : `kinesis, hudi, mrbench, presto, slf4j, phoenix, sqoop, slider, zipkin` build fail.

As I tested out of company, the `kinesis, hudi, mrbench, slf4j, sqoop, slider` depends on `java@8`(At least on `aarch64`);
The `zipkin` and `phoenix` is OK;

**Comment by adamjstewart** [comment]
@darmac when you say `java@8` do you mean `java@8` or `java@8:`? I didn't see that requirement in the `pom.xml` but I can add it back.

**Comment by darmac** [comment]
> @darmac when you say `java@8` do you mean `java@8` or `java@8:`? I didn't see that requirement in the `pom.xml` but I can add it back.

`java@8`, when I use `java@8:` or default `java`, It reports error like that(e.g. `mrbench`):
```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ mrbench ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /tmp/root/spack-stage/spack-stage-mrbench-master-hv5uivughzc4qs74xpohnllwthyhkpsy/spack-src/target/classes
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.787 s
[INFO] Finished at: 2020-08-27T09:24:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mrbench: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by adamjstewart** [comment]
@darmac does this PR look good to you now?

**Comment by darmac** [comment]
> @darmac does this PR look good to you now?

I'm tring testing that new patch.

**Comment by darmac** [comment]
LGTM, 
If you tested that OK, you can merge it fisrt.
I will test all of the maven package which failed in the earlier patch, if any new problems, I will open a `PR` or an `issue`.

**Comment by darmac** [comment]
I tested the installation of `kinesis`, `hudi`, `mrbench`, `slf4j`, `sqoop`, `slider`, `phoenix` and `zipkin`.
It looks good now.

**Pull request merged**
