### PR TITLE
hypre: Add v2.29.0

### PR DESCRIPTION
**Pull request by rfalgout**

### CODE REVIEW

**Review by osborn9 — APPROVED** [review]

**Review by alecbcs — DISMISSED** [review]
Confirmed SHA. Looks good to me. Thanks @rfalgout!

**Comment by alecbcs** [comment]
@rfalgout it looks like petsc v3.19.1 is failing to build with the updated version of hypre in CI.

```
  >> 2042    /tmp/root/spack-stage/spack-stage-petsc-3.19.1-uhj2zqaei7c2dkkfojj
             euaz43juhzacr/spack-src/src/ksp/pc/impls/hypre/hypre.c:444:29: err
             or: incompatible types when assigning to type 'hypre_Error {aka st
             ruct <anonymous>}' from type 'int'
     2043             hypre__global_error = 0;
     2044   
```

Any ideas on what might be going wrong here? We could also look at limiting the max version of hypre used to build petsc v3.19.1 if there's a breaking ABI change.

**Comment by rfalgout** [comment]
> @rfalgout it looks like petsc v3.19.1 is failing to build with the updated version of hypre in CI.
> 
> ```
>   >> 2042    /tmp/root/spack-stage/spack-stage-petsc-3.19.1-uhj2zqaei7c2dkkfojj
>              euaz43juhzacr/spack-src/src/ksp/pc/impls/hypre/hypre.c:444:29: err
>              or: incompatible types when assigning to type 'hypre_Error {aka st
>              ruct <anonymous>}' from type 'int'
>      2043             hypre__global_error = 0;
>      2044   
> ```
> 
> Any ideas on what might be going wrong here? We could also look at limiting the max version of hypre used to build petsc v3.19.1 if there's a breaking ABI change.

Yes.  The type of `hypre__global_error` has changed, but line 2043 shouldn't exist outside of hypre (it's an internal global variable in hypre).  I looked at the PETSc repo, and this line doesn't seem to be in the current version of this file.  Is this an old version of PETSc?

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by osborn9** [comment]
> @rfalgout it looks like petsc v3.19.1 is failing to build with the updated version of hypre in CI.
> 
> ```
>   >> 2042    /tmp/root/spack-stage/spack-stage-petsc-3.19.1-uhj2zqaei7c2dkkfojj
>              euaz43juhzacr/spack-src/src/ksp/pc/impls/hypre/hypre.c:444:29: err
>              or: incompatible types when assigning to type 'hypre_Error {aka st
>              ruct <anonymous>}' from type 'int'
>      2043             hypre__global_error = 0;
>      2044   
> ```
> 
> Any ideas on what might be going wrong here? We could also look at limiting the max version of hypre used to build petsc v3.19.1 if there's a breaking ABI change.

Yes, we could add the following to `petsc/package.py` to correctly use a compatible version of hypre. 

@balay what do you think? 
```
# Error handling via internal global variable changed in hypre v2.29.0
# (htpps://github.com/hypre-space/hypre/pull/920)
depends_on("hypre@:2.28.0", when="@:3.19.2+hypre")
depends_on("hypre@2.29.0:", when="@3.19.29:+hypre")
```

**Comment by balay** [comment]
> Yes. The type of hypre__global_error has changed, but line 2043 shouldn't exist outside of hypre (it's an internal global variable in hypre). I looked at the PETSc repo, and this line doesn't seem to be in the current version of this file. Is this an old version of PETSc?

I see this change is in `main` branch - and not in current PETSc release
```diff
-        hypre__global_error = 0;
+        HYPRE_ClearAllErrors();
 ```
https://gitlab.com/petsc/petsc/-/commit/852456159132bc30c5b87b2987f335ad79febdd0

> Yes, we could add the following to petsc/package.py to correctly use a compatible version of hypre.

Yes - I think we should do that. This part of spack spec for petsc needs a bit of cleanup - so will try pushing my changes to this PR branch

**Review by balay — APPROVED** [review]

**Pull request merged**
