### PR TITLE
Trilinos: minimize E4S CUDA build

### PR DESCRIPTION
**Pull request by sethrj**
- Restrict the cuda 11.6 conflict to +stokhos
- Turn off most trilinos packages for the CUDA build

### CODE REVIEW

**Review by eugeneswalker — DISMISSED** [review]
Thank you!

FYI @scottwittenburg

**Comment by sethrj** [comment]
Thank me when it works 😅 
```
trilinos@13.2.0%gcc~adios2~amesos+amesos2~anasazi~aztec~basker+belos~boost~chaco~complex+cuda~debug~dtk~epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus~explicit_template_instantiation~float~fortran~gtest~hypre~ifpack+ifpack2~intrepid~intrepid2~ipo~isorropia+kokkos~mesquite~minitensor~ml+muelu~mumps+nox~openmp~phalanx~piro~rocm~rol~rythmos~sacado~scorec~shards~shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+tpetra~trilinoscouplings~wrapper~x11~zoltan~zoltan2 cuda_arch=70 arch=linux-None-x86_64 is unsatisfiable, errors are:
  A conflict was triggered
```

I tested the concretization but apparently missed something. I will push when I figure it out!

**Review by eugeneswalker — DISMISSED** [review]

**Comment by sethrj** [comment]
Hm homebrew vomited:
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
17
Error: dash: Failed to download resource "dash"
18
Download failed: https://ghcr.io/v2/homebrew/core/dash/blobs/sha256:b7ab66d5cea5b77081f58392eb8f8c66341cf20c94739a77c262f0a1f54716a6
19
==> Downloadin
```

**Comment by sethrj** [comment]
@spackbot re-run pipeline

**Comment by sethrj** [comment]
Strange that this caused the kokkos wrapper concretization to change.. but at leas now the Trilinos CUDA takes "only" 100 minutes to build 😂

**Comment by sethrj** [comment]
@spackbot run pipeline

**Comment by sethrj** [comment]
@spackbot run pipeline

**Comment by sethrj** [comment]
@spackbot hello

**Comment by sethrj** [comment]
@eugeneswalker It looks like the "surprise" packages being built in the pipeline (https://gitlab.spack.io/spack/spack/-/jobs/1668681/raw) are just because of the concretization change for trilinos' dependencies to use CUDA 11.6: the current E4S pipeline has three CUDA versions installed, and the new one has only two. (Superlu-dist [has a restriction](https://github.com/xiaoyeli/superlu_dist/issues/87) on `:11.4` for now.)

**Comment by sethrj** [comment]
Force pushing to try to restart the bizarre pipeline failures :(

**Comment by sethrj** [comment]
@eugeneswalker Now that the mysterious pipeline hangs have been fixed by #28638 could you please reapprove? Thanks!

**Review by eugeneswalker — APPROVED** [review]
thank you for driving this!

**Pull request merged**
