### PR TITLE
Fix OpenMPI CUDA support

### LINKED ISSUE #4322: Error installing OpenMPI+CUDA with external CUDA
I added a `packages.yaml` to take an external cuda installation via
```yaml
packages:
  cuda:
    paths:
      cuda@8.0.61%gcc@5.4.0 arch=linux-ubuntu16-x86_64: /usr/local/cuda
    buildable: False
```

When trying to install a cuda-aware MPI via `openmpi+cuda` it fails (on dev as of 4553b14) since it is kind of weirdly adding the `--with-cuda-libdir` as

`'--with-cuda=/usr/local/cuda' '--with-cuda-libdir=['"'"'/usr/local/cuda/targets/x86_64-linux/lib/stubs'"'"']'`

```
==> Building openmpi [AutotoolsPackage]
==> Error: ProcessError: Command exited with status 1:
    '/home/src/spack/var/spack/stage/openmpi-2.1.1-w22h44f3bzru6544vvhkioccwqiwbmze/openmpi-2.1.1/configure' '--prefix=/home/src/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/openmpi-2.1.1-w22h44f3bzru6544vvhkioccwqiwbmze' '--enable-shared' '--enable-static' '--enable-mpi-cxx' '--without-psm' '--without-psm2' '--without-pmi' '--without-verbs' '--without-mxm' '--without-alps' '--without-lsf' '--without-tm' '--without-slurm' '--without-sge' '--without-loadleveler' '--with-hwloc=/home/src/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/hwloc-1.11.7-nsd5ek5ld357qgjjhkn3ep2w3zzq2pmu' '--disable-java' '--disable-mpi-java' '--disable-mpi-thread-multiple' '--with-cuda=/usr/local/cuda' '--with-cuda-libdir=['"'"'/usr/local/cuda/targets/x86_64-linux/lib/stubs'"'"']'
```

Here is a docker file to reproduce the issue via `docker build .` (add the `packages.yaml` in the same dir):
```
FROM       nvidia/cuda:8.0-devel

# general environment for docker
ENV        HOME /home
ENV        DEBIAN_FRONTEND noninteractive

# spack environment
ENV        PATH "$HOME/src/spack/bin:$PATH"
COPY       packages.yaml $HOME/.spack/packages.yaml

# install minimal spack dependencies
#   also adds gfortran for spack's openmpi package
RUN        apt-get update \
           && apt-get install -y --no-install-recommends \
              autoconf \
              ca-certificates \
              curl \
              gfortran \
              git \
              build-essential \
              python \
           && rm -rf /var/lib/apt/lists/*

# install spack
RUN        git clone --depth 50 https://github.com/llnl/spack.git \
           $HOME/src/spack/

# install PIConGPU dependencies
RUN        spack install cmake \
           && spack install cuda \
           && spack install openmpi+cuda
```

### PR DESCRIPTION
**Pull request by adamjstewart**
@ax3l Can you see if this fixes #4322?

### CODE REVIEW

**Comment by ax3l** [comment]
that looks definitely like the place, but are you sure it's not affecting non-external cuda builds? they seemed to work. not that the error propagates from a higher place down where the external dirs are set, no?

**Comment by adamjstewart** [comment]
Both internal and external builds should be treated the same, the only difference is the installation directory. `libs.directories` returns a list of all directories containing the libraries. If you want a single directory, you have to take the first element of the list.

You said it was working for internal builds? What did the configure line look like? Do they still work with this change?

> not that the error propagates from a higher place down where the external dirs are set, no?

I'm not sure what you mean by this, can you elaborate?

**Comment by ax3l** [comment]
> You said it was working for internal builds? What did the configure line look like? Do they still work with this change?

I did not test internal builds when I saw the error again, but am currently verifying. stand by :)

> I'm not sure what you mean by this, can you elaborate?

I was just wondering if that's just fixing the external build issue, but you are right: it's a list of libs and hopefully the first entry should  do

**Comment by ax3l** [comment]
hm, the line you propose is valid but the flag seems gone in openmpi 2.1.1 anyway. can't nail down the other issue I reported yet... something in hwloc

**Comment by adamjstewart** [comment]
Looking back, I don't see a single version of OpenMPI that accepts the `--with-cuda-lib` flag. I'll just remove it altogether.

**Comment by ax3l** [comment]
Following the open pick FAQ / docs, it might have existed at some point 

https://www.open-mpi.org/faq/?category=buildcuda

**Comment by adamjstewart** [comment]
@ax3l You're absolutely right, I'll fix that.

**Comment by adamjstewart** [comment]
@ax3l I tried to include all of the knowledge from https://www.open-mpi.org/faq/?category=buildcuda in the build recipe. Can you try this out and make sure it works?

**Comment by adamjstewart** [comment]
Ping @ax3l

**Comment by ax3l** [comment]
@adamjstewart thank you! Performed interactively it seems to work for me! (tested with `nvidia-docker` as described in #4322 with cuda 8.0.61 and OpenMPI 2.1.1)

Unfortunately it still crashes for me when running non-interactive during the `build` stage of a docker container.
```bash
$ spack install openmpi+cuda

==> Error: ProcessError: Command exited with status 1:
    '/home/src/spack/var/spack/stage/openmpi-2.1.1-gjy6oliid7io3s3fg27hkl5wy55j6vsq/openmpi-2.1.1/configure' '--prefix=/home/src/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/openmpi-2.1.1-gjy6oliid7io3s3fg27hkl5wy55j6vsq' '--enable-shared' '--enable-static' '--enable-mpi-cxx' '--without-psm' '--without-psm2' '--without-pmi' '--without-verbs' '--without-mxm' '--without-alps' '--without-lsf' '--without-tm' '--without-slurm' '--without-sge' '--without-loadleveler' '--with-hwloc=/home/src/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/hwloc-1.11.7-z3rifyeiamchoka6jsisk5legsysovjj' '--disable-java' '--disable-mpi-java' '--disable-mpi-thread-multiple' '--enable-dlopen' '--with-cuda=/usr/local/cuda'
```

I can't really debug it since it passes as soon as I switch to interactive... but that shall not block your fix for now and could be something weird on my side.

**Pull request merged**
