### PR TITLE
c-blosc2: New version 2.1.0, 2.1.1, 2.2.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed new sha256.

**Comment by tldahlgren** [comment]
Will defer merge until maintainers have a chance to comment.

**Comment by eschnett** [comment]
ping

**Comment by eschnett** [comment]
ping

**Comment by eschnett** [comment]
@spackbot help

**Comment by eschnett** [comment]
@spackbot request review

**Comment by tldahlgren** [comment]
I'm assuming 13 days is long enough to wait for reviewer feedback.

**Pull request merged**
