### PR TITLE
py-numpy: fix build with clang 13.0.1

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
LGTM, will wait for @rgommers to review

**Review by rgommers — COMMENTED** [review]
Thanks @vvolkl. It would be good to add some comments on why these are needed. For the `-Wno-error` one, I assume that avoids a build failure? If so, makes sense to add this - and we should then probably upstream it to NumPy itself. For `-flto` I'm less clear on why it'd be needed.

**Comment by vvolkl** [comment]
Hi @rgommers, thanks for taking a look! Yes, this patch fixes the  build of numpy with clang@13.0.1 . This affects a few other packages as well, see https://github.com/spack/spack/pull/29679. I couldn't investigate this issue in depth, so I'll just leave a comment with the errors you'd see with clang13.

Upstreaming the build flags would certainly be nice, I'll see if I find the time.

**Comment by rgommers** [comment]
I cannot reproduce this locally with Clang 13.0.1 from Arch Linux:
```
$ clang --version
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
(numpy-dev2) rgommers@machine:~/code/numpy (main)$ CC=clang CXX=clang++ python setup.py build_ext -i
...
# builds fine and all tests pass
```
So it's not a NumPy issue. Maybe the Clang Spack package adds some non-default flags?

If this fixes a build problem then it seems fine to merge now @adamjstewart 

@vvolkl sorry I'm still new to Spack, can you tell me how I should reproduce the issue you are seeing?

**Comment by vvolkl** [comment]
I've been testing this with the system clang13 on arch as well. It's strange though, I don't see where spack would add a `-Werror`. You can reproduce the issue with spack with
```
spack compiler find # or spack install llvm@13.0.1; spack compiler find
spack install py-numpy %clang@13.0.1
```

**Comment by vvolkl** [comment]
For me, the error is there even without spack:

```
k4-arch-01: ~/numpy ((v1.22.3))$ CC=clang CXX=clang++ python setup.py build_ext -i
...
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/_bounded_integers.pxd.in
Processing numpy/random/_mt19937.pyx
/home/arch/numpy/tools/cythonize.py:63: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
Processing numpy/random/_philox.pyx
Processing numpy/random/_generator.pyx
Processing numpy/random/_sfc64.pyx
Processing numpy/random/_common.pyx
Processing numpy/random/_bounded_integers.pyx.in
Processing numpy/random/bit_generator.pyx
Processing numpy/random/mtrand.pyx
Processing numpy/random/_pcg64.pyx
INFO: blas_opt_info:
INFO: blas_armpl_info:
INFO: customize UnixCCompiler
INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: blas_mkl_info:
INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: blis_info:
INFO:   libraries blis not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: openblas_info:
INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: accelerate_info:
INFO:   NOT AVAILABLE
INFO: 
INFO: atlas_3_10_blas_threads_info:
INFO: Setting PTATLAS=ATLAS
INFO:   libraries tatlas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: atlas_3_10_blas_info:
INFO:   libraries satlas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: atlas_blas_threads_info:
INFO: Setting PTATLAS=ATLAS
INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: atlas_blas_info:
INFO:   libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
/home/arch/numpy/numpy/distutils/system_info.py:2077: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
INFO: blas_info:
INFO: C compiler: clang -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC

creating /tmp/tmpleh1p5au/tmp
creating /tmp/tmpleh1p5au/tmp/tmpleh1p5au
INFO: compile options: '-I/usr/local/include -c'
INFO: clang: /tmp/tmpleh1p5au/source.c
clang-13: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
INFO: clang /tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o -L/usr/lib64 -lblas -o /tmp/tmpleh1p5au/a.out
/tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o: file not recognized: file format not recognized
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: clang /tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o -L/usr/lib64 -lcblas -lblas -o /tmp/tmpleh1p5au/a.out
/tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o: file not recognized: file format not recognized
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: clang /tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o -L/usr/lib64 -lblas -lblas -o /tmp/tmpleh1p5au/a.out
/tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o: file not recognized: file format not recognized
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: clang /tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o -L/usr/lib64 -lcblas -o /tmp/tmpleh1p5au/a.out
/tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o: file not recognized: file format not recognized
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: clang /tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o -L/usr/lib64 -lblas -o /tmp/tmpleh1p5au/a.out
/tmp/tmpleh1p5au/tmp/tmpleh1p5au/source.o: file not recognized: file format not recognized
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
INFO:   FOUND:
INFO:     libraries = ['blas', 'blas']
INFO:     library_dirs = ['/usr/lib64']
INFO:     include_dirs = ['/usr/local/include']
INFO: 
INFO:   FOUND:
INFO:     define_macros = [('NO_ATLAS_INFO', 1)]
INFO:     libraries = ['blas', 'blas']
INFO:     library_dirs = ['/usr/lib64']
INFO:     include_dirs = ['/usr/local/include']
INFO: 
Traceback (most recent call last):
  File "/home/arch/numpy/setup.py", line 461, in <module>
    setup_package()
  File "/home/arch/numpy/setup.py", line 453, in setup_package
    setup(**metadata)
  File "/home/arch/numpy/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "/home/arch/numpy/setup.py", line 131, in configuration
    config.add_subpackage('numpy')
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/home/arch/numpy/numpy/setup.py", line 9, in configuration
    config.add_subpackage('core')
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/arch/numpy/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/home/arch/numpy/numpy/core/setup.py", line 1018, in configuration
    if can_link_svml() and check_svml_submodule(svml_path):
  File "/home/arch/numpy/numpy/core/setup.py", line 84, in check_svml_submodule
    raise RuntimeError("Missing `SVML` submodule! Run `git submodule "
RuntimeError: Missing `SVML` submodule! Run `git submodule update --init` to fix this.
-bash: ...: command not found
```

**Comment by rgommers** [comment]
That's not due to Clang. As the error message says, run `git submodule update --init` first.

**Comment by vvolkl** [comment]
(yes, sorry, that's unrelated, same thing with all submodules checked out)

**Comment by rgommers** [comment]
Thanks, I'll try that. My machine is now building LLVM & dependencies - that means time for lunch I guess:)

**Comment by rgommers** [comment]
```
spack install llvm@13.0.1
spack compiler find
spack install py-numpy %clang@13.0.1
```
is still not a complete reproducer, that ends with:
```
==> Installing openblas-0.3.20-nbbyn7iuuu2yzgxcfl27pn5gzcs6dmxe
==> No binary for openblas-0.3.20-nbbyn7iuuu2yzgxcfl27pn5gzcs6dmxe found: installing from source
==> Using cached archive: /home/rgommers/code/tmp/spack/var/spack/cache/_source-cache/archive/84/8495c9affc536253648e942908e88e097f2ec7753ede55aca52e5dead3029e3c.tar.gz
==> No patches needed for openblas
==> openblas: Executing phase: 'edit'
==> Error: InstallError: OpenBLAS requires both C and Fortran compilers!

/home/rgommers/code/tmp/spack/var/spack/repos/builtin/packages/openblas/package.py:160, in check_compilers:
        157        # require both.
        158        if self.compiler.fc is None:
        159            raise InstallError(
  >>    160                'OpenBLAS requires both C and Fortran compilers!'
        161            )
```

Clang doesn't have a compatible Fortran compiler to go with it I think (or is Flang functional enough?), so switching to Netlib BLAS/LAPACK:
```
spack install py-numpy %clang@13.0.1 ^netlib-lapack
```

That ends similarly:
```
     24        [spack cc] ERROR: Compiler 'clang@13.0.1' does not have a Fortran 90 compil
           er configured.
  >> 25    make[1]: *** [CMakeFiles/cmTC_69dfc.dir/build.make:78: CMakeFiles/cmTC_69dfc.di
           r/testFortranCompiler.f.o] Error 1
```
MKL then perhaps (that must have a prebaked binary somewhere):
```
spack install py-numpy %clang@13.0.1 ^intel-mkl
```
The build is currently chugging along on a single core. @adamjstewart random question: is there a way to edit the build command to include `-j4`? That would speed things up a lot. There's no way to get the same behavior as for example `ninja` with parallel builds (`n_threads = 2*n_cores + 2`) but 4 threads is always a better default than 1 core I'd think.

**Comment by rgommers** [comment]
I had to kill that build of NumPy after 20 minutes, it was using up all the memory. So far no luck in getting NumPy to build with Clang 13.0.1. With GCC 11.2.0 + MKL the install worked fine.

**Comment by adamjstewart** [comment]
> Clang doesn't have a compatible Fortran compiler to go with it I think (or is Flang functional enough?)

Most people mix Clang + GFortran but Clang + Flang should also work.

> is there a way to edit the build command to include `-j4`?

By default, Spack adds `-j` with the number of cores to all make/ninja commands. For other build systems, if there is an env var or something we can set we can add that.

**Comment by vvolkl** [comment]
Yes, I still think that is a bug in spack compiler find that it doesn't add gfortran if available. You'll want to just edit your compilers.yaml and change
```
       f77: null
       fc: null
```
to 
```
       f77: /usr/bin/gfortran
       fc: /usr/bin/gfortran
```

This issue is the same for me with a spack-installed clang on arch, but I cannot reproduce it on my desktop running ubuntu (using a spack-installed clang13). I'll check a few more things and try to reproduce it in a container to exclude some strange issue with my arch machine.

**Comment by rgommers** [comment]
> By default, Spack adds `-j` with the number of cores to all make/ninja commands. For other build systems, if there is an env var or something we can set we can add that.

Great, NumPy and other projects using `numpy.distutils` listen to the `NPY_NUM_BUILD_JOBS` env var.

**Comment by adamjstewart** [comment]
Did we ever get this PR/issue figured out?

**Comment by rgommers** [comment]
I did not, I didn't get beyond the "it's building for 20 minutes and eating up all my memory, not sure why". I'd have to start over now.

**Comment by alalazo** [comment]
@adamjstewart Should we close this one? Or should we try to finalize it?

**Comment by vvolkl** [comment]
This is likely no longer an issue with newer versions of clang and/or numpy. I just started a build of `py-numpy%clang@13.0.1` with the current spack develop branch, will let you know.

**Comment by alalazo** [comment]
Do we even care about `clang@13`, since we are at v19?

**Comment by vvolkl** [comment]
> Do we even care about `clang@13`, since we are at v19?

Probably not, but I like to add at least a conflict if possible. For me spack is often the go-to tool to check exotic build configurations and do exhaustive matrices of them, in that usecase it's useful to know about know failures.

**Comment by vvolkl** [comment]
BTW llvm@13.0.1 didn't even build with the compiler I had set up ... trying again with the system compiler

**Comment by vvolkl** [comment]
Cannot reproduce. Both current version

/opt/spack/linux-almalinux9-zen2/clang-13.0.1/py-numpy-2.1.2-sgxauo6wdoumaqf4ucv4m7oxaux47xfy

and the one that was current when this issue was opened

/opt/spack/linux-almalinux9-zen2/clang-13.0.1/py-numpy-1.22.3-hzmv6zpxcc57wneuhdehmykxvrkxgkwz

build fine. I was on arch linux at the time, maybe I screwed something up with my setup, won't investigate further.

**Comment by alalazo** [comment]
@vvolkl Thanks for looking into it. As you may guess, I'm doing some cleanup of old Prs while I'm waiting for a few pipelines to finish :slightly_smiling_face:

**Pull request closed without merging**
