### PR TITLE
Xl/superlu dist

### PR DESCRIPTION
**Pull request by serbanmaerean**
When compiling with IBM XL, don't use '_' for BLAS symbols.

### CODE REVIEW

**Comment by serbanmaerean** [comment]
I usually run flake8, but this time around I thought it would fit into 79 chars... :-)  Flake8 should not complain anymore.

**Comment by adamjstewart** [comment]
Btw, I noticed that all of your PRs include a `magma` package and a bunch of develop merges. I think the first 2 commits have already been merged into Spack, correct? If you don't have any other changes in your develop branch and want to resync with upstream, you can run:
```
$ git checkout develop
$ git pull --force upstream develop
$ git push --force origin develop
```
This will overwrite your history so it matches LLNL spack's history.

**Comment by serbanmaerean** [comment]
I did that.  I guess it will show at the next commit.

**Comment by adamjstewart** [comment]
> I guess it will show at the next commit.

It will show in the next branch/PR that you create. If you want to update this particular PR to reflect this change, it would look like:
```
$ git checkout xl/superlu-dist
$ git rebase develop
```
but you don't have to do this if you don't want to. When we merge PRs, we squash all of the changes into a single commit anyway, so it won't make a difference.

**Pull request merged**
