### PR TITLE
protobuf: add v3.27.1

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256. @hyoklee are there other changes needed besides adding the version directive?

**Review by hyoklee — APPROVED** [review]

**Comment by tldahlgren** [comment]
A couple of ML stacks were failing because of py-keras.  Probably should've just re-run the pipeline instead of the update...

**Review by bernhardkaindl — APPROVED** [review]

**Review by bernhardkaindl — APPROVED** [review]
Built on Ubuntu 22.04 and rebased on develop as of Aug 1 now to hopefully have a passing GitLab CI

**Review by bernhardkaindl — APPROVED** [review]
Rebased onto recent develop as current GitLab CI works reliably
and built on Ubuntu 22.04 usong it.

**Comment by tldahlgren** [comment]
Looks like a rebase is required.

**Comment by bernhardkaindl** [comment]
Obsoleted by merge of #46501

**Pull request closed without merging**
