### PR TITLE
DRAFT: Test for spackbot

### PR DESCRIPTION
**Pull request by josephsnyder**
Do not merge this MR.  This is to test updates to spackbot

### CODE REVIEW

**Comment by josephsnyder** [comment]
@scottwittenburg, here is what you requested. Let me know how else I can help

**Comment by scottwittenburg** [comment]
@spackbot fix style

**Comment by scottwittenburg** [comment]
I was really hoping this wouldn't work :cry: 

@tgamblin Do you know how we can be sure @josephsnyder has no special privileges?  Or maybe we should seek another first-time contributor (I think that was the case for the other PR where this didn't work).

**Comment by alalazo** [comment]
Closing, since this doesn't seem relevant anymore.

**Pull request closed without merging**
