### PR TITLE
package_base: Fix Python package tests

### PR DESCRIPTION
**Pull request by michaelkuhn**
Running `spack install --test=root py-nipype` results in the following error:
```
'super' object has no attribute 'test_log_file'
```
Replacing `test_log_file` with `test_install_log_path` (as seems to be intended) still causes the following error:
```
'NoneType' object has no attribute 'append'
```
This can be fixed by making sure that `test_failures` is not `None`.

### CODE REVIEW

**Comment by michaelkuhn** [comment]
cc @tldahlgren (who has refactored this recently)

**Comment by manuelakuhn** [comment]
Other packages where this bug happened were:
- `py-reportlab@3.4.0` (but strangely not version 3.6.12)
- `py-scikit-image`

**Comment by tldahlgren** [comment]
Interesting.  Tried to reproduce the issue.  

I could not build `py-nipype` or `py-scikit-image`.

Did not have the problem with `py-reportlab@3.4.0`, in fact all of the import checks passed for me.

```
* **Spack:** 0.20.0.dev0 (94bac8d6dd9140820dbde9d1dda4ea6c5736ca43)
```

**Review by tldahlgren — COMMENTED** [review]
Cannot reproduce.  I'm very interested in learning why the property isn't set/available when running tests.  It may be relevant to my refactor in https://github.com/spack/spack/pull/34236.

**Comment by michaelkuhn** [comment]
I gave it a try on another system and could also reproduce it there for `py-nipype`:
* **Spack:** 0.20.0.dev0 (94bac8d6dd9140820dbde9d1dda4ea6c5736ca43)
* **Python:** 3.6.8
* **Platform:** linux-centos8-x86_64_v3
* **Concretizer:** clingo

**Comment by adamjstewart** [comment]
I'm also able to reproduce this:
```
$ spack install --test=root py-nipype
...
==> Testing package py-nipype-1.7.0-rs3buym
==> [2022-12-12-17:11:14.767790] Running install-time tests
==> [2022-12-12-17:11:14.767996] RUN-TESTS: install-time tests [test]
==> [2022-12-12-17:11:24.485358] RUN-TESTS: method not implemented [test]
==> Error: TestFailure: 1 tests failed.


'super' object has no attribute 'test_log_file'

RUN-TESTS: method not implemented [test]

See build log for details:
  /var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-py-nipype-1.7.0-rs3buymexzw2ckcn5uj7ugmnndzrgzll/spack-build-out.txt

```
* **Spack:** 0.20.0.dev0 (94bac8d6dd9140820dbde9d1dda4ea6c5736ca43)
* **Python:** 3.10.8
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

**Comment by manuelakuhn** [comment]
I could still reproduce it for all 3 packages (`py-reportlab@3.4.0` is the fastest to check because the others have a lot of dependencies)

```
$ spack install --test=root py-nipype
...
==> Testing package py-nipype-1.7.0-m3xunci
==> [2022-12-13-00:20:57.074414] Running install-time tests
==> [2022-12-13-00:20:57.074461] RUN-TESTS: install-time tests [test]
==> [2022-12-13-00:21:04.163874] RUN-TESTS: method not implemented [test]
==> Error: TestFailure: 1 tests failed.


'super' object has no attribute 'test_log_file'

RUN-TESTS: method not implemented [test]

See build log for details:
  $spack-stage/spack-stage-py-nipype-1.7.0-m3xuncimklvzzafjrmpgcyzwku3zrujf/spack-build-out.txt
```
```
$ spack install --test=root py-scikit-image
...
==> Testing package py-scikit-image-0.18.3-kzswzk2
==> [2022-12-13-00:18:21.985301] Running install-time tests
==> [2022-12-13-00:18:21.985348] RUN-TESTS: install-time tests [test]
==> [2022-12-13-00:18:22.433831] RUN-TESTS: method not implemented [test]
==> Error: TestFailure: 1 tests failed.


'super' object has no attribute 'test_log_file'

RUN-TESTS: method not implemented [test]

See build log for details:
  $spack-stage/spack-stage-py-scikit-image-0.18.3-kzswzk2xvkjrut6oipsxnhdh5ijky6dk/spack-build-out.txt
```
```
$ spack install --test=root py-reportlab@3.4.0
...
==> Testing package py-reportlab-3.4.0-xekzjyn
==> [2022-12-13-00:21:42.089951] Running install-time tests
==> [2022-12-13-00:21:42.089997] RUN-TESTS: install-time tests [test]
==> [2022-12-13-00:21:42.134144] RUN-TESTS: method not implemented [test]
==> Error: TestFailure: 1 tests failed.


'super' object has no attribute 'test_log_file'

RUN-TESTS: method not implemented [test]

See build log for details:
  $spack-stage/spack-stage-py-reportlab-3.4.0-xekzjyndvfhpyzal3dj77mrycssz2caa/spack-build-out.txt
```

* **Spack:** 0.20.0.dev0 (94bac8d6dd9140820dbde9d1dda4ea6c5736ca43)
* **Python:** 3.11.0
* **Platform:** linux-fedora37-skylake
* **Concretizer:** clingo

**Comment by adamjstewart** [comment]
Likely possible to reproduce by adding `import_modules = ['foo']` to any Python package.

**Comment by tldahlgren** [comment]
Thank you all for the additional information.  

I have not liked the idea of only defining that property when calling certain test method(s) so it looks like this demonstrates a case where that approach fails.  The refactor should address this issue but there should definitely be a test to confirm.

**Comment by tldahlgren** [comment]
> Thank you all for the additional information.
> 
> I have not liked the idea of only defining that property when calling certain test method(s) so it looks like this demonstrates a case where that approach fails. The refactor should address this issue but there should definitely be a test to confirm.

Correction.  This is an issue with changes related to the builder and #33942 in particular.

**Comment by alalazo** [comment]
This issue seems of the same kind as https://github.com/spack/spack/pull/34531 and is due to the combination of 2 things:
1. The need to have a run-time generated adapter to maintain backward compatibility with package recipes[^1]
2. The fact that we have many attributes in packages that are monkey-patched after an object is created

Now, when we generate an adapter we do the following to have the adapter look the same as the object it wraps:
```python
self.__dict__.update(wrapped_pkg_object.__dict__)
```
If any attribute used during the installation is monkey-patched on the object after wrapping, we have a mismatch between the wrapped package object and its adapter. Here I think I just missed `test_log_file` and `test_failures` which are set in `PackageBase._setup_test`. 

The best solution imo would be to extract some behavior from `PackageBase` into others, more focused, classes - but that is work for later. In the meanwhile I'll try to submit a 2 lines fix for this.

[^1]: See https://spack.readthedocs.io/en/latest/packaging_guide.html#compatibility-with-single-class-format for an explanation why that is needed

**Pull request closed without merging**
