### PR TITLE
Allow extra_instructions at beginning of container build and final stages

### LINKED ISSUE #26036: Allow extra_instructions at beginning of container stages
### Summary

Some sites may need to add SSL certificates or other things to the beginning of the stages generated by "spack containerize". There are currently "extra_instructions:build" and "extra_instructions:final" options available to add extra commands at the end of each build stage. This request is asking for similar functionality for the beginning of each build stage.

For example:

```
FROM spack/centos7:latest as builder

# Beginning extra_instructions
ADD site_specific_cert.crt /etc/pki/ca-trust/source/anchors/site_specific_cert.crt
RUN update-ca-trust

# Auto-generated content by "spack containerize"

# Ending extra_instructions
RUN yum install -y libgomp

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]
```

### Rationale

Some sites require a site-specific SSL certificate to be installed in order to reach upstream repos outside of the site. Without these certs in place, the "docker build ." fails.

### Description

Add extra_instructions before the Dockerfile contents generated by Spack. Such a feature already exists for extra_instructions after the auto-generated content.

### Additional information

Using spack developer brach:

$ spack --version
0.16.2-4259-5d23638fdc

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by climbfuji**
## Description
This PR adds `pre_build` and `pre_final` extra instructions to `Dockerfile` and `singularity.def`. Credits go to @kgerheiser for suggesting a first version of these changes to me.

As described in https://github.com/spack/spack/issues/26036, it's sometimes necessary to have extra instructions before the build stage. For example, when adding new `apt` sources and installing additional packages.

Likewise, I found it necessary to have extra instructions before the final stage, for example to set environment variables such as `TZ` to avoid linux configuration tools like `debconf` waiting for user input.

## Testing

I tested this extensively with `Dockerfile` for both `pre_build` and `pre_final`, and recently also with `singularity.def`.

Note. I have not updated the documentation yet. I would like to get feedback from the developers first before I go and update the documentation.

## Issues

Fixes https://github.com/spack/spack/issues/26036

### CODE REVIEW

**Comment by climbfuji** [comment]
@ktpedre FYI

**Comment by climbfuji** [comment]
Obviously I didn't do the `singularity.def` changes correctly:
```
lib\spack\spack\test\container\singularity.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
lib\spack\spack\container\writers\__init__.py:288: in __call__
    t = env.get_template(self.template_name)
lib\spack\external\jinja2\environment.py:883: in get_template
    return self._load_template(name, self.make_globals(globals))
lib\spack\external\jinja2\environment.py:857: in _load_template
    template = self.loader.load(self, name, globals)
lib\spack\external\jinja2\loaders.py:127: in load
    code = environment.compile(source, name, filename)
lib\spack\external\jinja2\environment.py:638: in compile
    self.handle_exception(source=source_hint)
lib\spack\external\jinja2\environment.py:832: in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
lib\spack\external\jinja2\_compat.py:28: in reraise
    raise value.with_traceback(tb)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   {% endif %
E   jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'

share\spack\templates\container\singularity.def:14: TemplateSyntaxError
= 2 failed, 1886 passed, 892 skipped, 40 xfailed, 1 xpassed in 735.21 seconds =
Error: Process completed with exit code 1.
```

**Comment by alalazo** [comment]
Just a heads up. This is still on my radar, but I didn't have a chance to review it yet.

**Comment by climbfuji** [comment]
> Just a heads up. This is still on my radar, but I didn't have a chance to review it yet.

@alalazo A gentle reminder to take a look at this PR when you get the chance ... thanks very much in advance.

**Comment by climbfuji** [comment]
> > Just a heads up. This is still on my radar, but I didn't have a chance to review it yet.
> 
> @alalazo A gentle reminder to take a look at this PR when you get the chance ... thanks very much in advance.

@alalazo Sorry to ping you again about this PR ...

**Comment by alalazo** [comment]
Let's get to the bottom of this (and sorry for the slow review!). I checked the implementation and it LGTM. At a high level though I wonder if we could take another approach, i.e. expose the template being used to render the `Dockerfile` or the `singularity.def` file and give that template some extendable blocks.

In that way we can deprecate the current `final` and `build` extra instructions and leave in the YAML file only a reference to the template being used. The template itself will instead extend the blocks similarly to what is done [here](https://jinja.palletsprojects.com/en/3.1.x/templates/#child-template). Would an approach like that fit your use cases?

EDIT: forgot to mention that the appealing part of this other approach, to me, is that we'll remove extraneous verbatim line to the `spack.yaml` file, and we'll move them to where they belong i.e. the Dockerfile.

**Comment by climbfuji** [comment]
> Let's get to the bottom of this (and sorry for the slow review!). I checked the implementation and it LGTM. At a high level though I wonder if we could take another approach, i.e. expose the template being used to render the `Dockerfile` or the `singularity.def` file and give that template some extendable blocks.
> 
> In that way we can deprecate the current `final` and `build` extra instructions and leave in the YAML file only a reference to the template being used. The template itself will instead extend the blocks similarly to what is done [here](https://jinja.palletsprojects.com/en/3.1.x/templates/#child-template). Would an approach like that fit your use cases?
> 
> EDIT: forgot to mention that the appealing part of this other approach, to me, is that we'll remove extraneous verbatim line to the `spack.yaml` file, and we'll move them to where they belong i.e. the Dockerfile.

Yes, that sounds like a very good idea, thanks. This is more flexible and will not only suit our needs, but also that of others.

**Comment by alalazo** [comment]
@climbfuji Do you want to take a stab at it? If so, I'll be happy to assist if you need any help.

**Comment by climbfuji** [comment]
> @climbfuji Do you want to take a stab at it? If so, I'll be happy to assist if you need any help.

It will take me a bit to get to this, but I can try. I'll make the changes on top of this branch so that the updates merge back cleanly into our fork (where we are using the changes in this PR already).

**Comment by alalazo** [comment]
Ok, sounds good to me. Feel free to ping me at any time. Now that we got past release I should be a bit more responsive :sweat_smile:

**Comment by climbfuji** [comment]
> Ok, sounds good to me. Feel free to ping me at any time. Now that we got past release I should be a bit more responsive 😅

past release is before the next release ;-) our next release is coming up in less than a month ...

**Comment by climbfuji** [comment]
@alalazo I am having a hard time finding time to work on this. Wondering if we could merge those changes as they are (you said they look good to you) and create an issue to improve the method as you described above).

**Comment by climbfuji** [comment]
I haven't had time to test https://github.com/spack/spack/pull/35187 yet, but I am closing this PR in favor of #35187.

**Pull request closed without merging**
