### PR TITLE
kokkos: add v3.1.01

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by crtrott** [comment]
Did you intend to remove the tarball urls for the releases?

**Comment by adamjstewart** [comment]
I think this package could use a `url_for_version` function

**Comment by junghans** [comment]
> Did you intend to remove the tarball urls for the releases?

I add the `url` parameter above, which allows spack to automatically generate the urls for all versions.

**Comment by junghans** [comment]
> I think this package could use a `url_for_version` function

Meh, the default will just work fine.

**Comment by adamjstewart** [comment]
But won't it try to download 3.1 from https://github.com/kokkos/kokkos/archive/3.1.tar.gz instead of https://github.com/kokkos/kokkos/archive/3.1.00.tar.gz?

**Comment by junghans** [comment]
> But won't it try to download 3.1 from https://github.com/kokkos/kokkos/archive/3.1.tar.gz instead of https://github.com/kokkos/kokkos/archive/3.1.00.tar.gz?

Good point, we should just follow the upstream versioning scheme.

**Comment by junghans** [comment]
I think this is better as it allow the user to get any future version.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
