### PR TITLE
sundials: add v6.6.2

### PR DESCRIPTION
**Pull request by balos1**
CC @balay

### CODE REVIEW

**Review by gardner48 — DISMISSED** [review]

**Comment by balay** [comment]
I'm seeing build errors:

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5473943972

```
>> 9001    CMake Error at examples/arkode/C_serial/cmake_install.cmake:459 (f
             ile):
     9002      file INSTALL cannot find
     9003      "/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stag
             e/spack-stage-sundials-6.6.2-5htsbcks3s5m3d27li6cgtuaa53iregk/spac
             k-src/examples/arkode/C_serial/ark_kepler_--stepper_SPRK_--step-mo
             de_fixed_--method_ARKODE_SPRK_EULER_1_1_--tf_50_--check-order_--no
             ut_1.out":
     9004      No such file or directory.
```

**Comment by gardner48** [comment]
> I'm seeing build errors:
> 
> https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5473943972
> 
> ```
> >> 9001    CMake Error at examples/arkode/C_serial/cmake_install.cmake:459 (f
>              ile):
>      9002      file INSTALL cannot find
>      9003      "/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stag
>              e/spack-stage-sundials-6.6.2-5htsbcks3s5m3d27li6cgtuaa53iregk/spac
>              k-src/examples/arkode/C_serial/ark_kepler_--stepper_SPRK_--step-mo
>              de_fixed_--method_ARKODE_SPRK_EULER_1_1_--tf_50_--check-order_--no
>              ut_1.out":
>      9004      No such file or directory.
> ```

@balos1 I think this is a problem with the uploaded tarballs. I'm seeing the same error when building from `sundials-6.6.2.tar.gz` but not when building from a fresh checkout of `main`.

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
Based on a sample of the failures, they seem to consistently have the following failure:

```
...
     7664    -- Installing: /home/software/spack/__spack_path_placeholder__/__s
             pack_path_placeholder__/__spack_path_placeholder__/__spack_path_pl
             aceholder__/__spack_path_placeholder__/__spack_path_placeholder__/
             __spack_path_placeholder__/__spack_path_placeholder__/__spack_path
             _placeh/morepadding/linux-ubuntu20.04-x86_64_v3/gcc-11.4.0/sundial
             s-6.6.2-hnnsesrffh2c2s3qddzs66adio5dba4u/examples/arkode/C_serial/
             ark_kepler_--stepper_SPRK_--step-mode_fixed_--count-orbits_--use-c
             ompensated-sums.out
     7665    -- Up-to-date: /home/software/spack/__spack_path_placeholder__/__s
             pack_path_placeholder__/__spack_path_placeholder__/__spack_path_pl
             aceholder__/__spack_path_placeholder__/__spack_path_placeholder__/
             __spack_path_placeholder__/__spack_path_placeholder__/__spack_path
             _placeh/morepadding/linux-ubuntu20.04-x86_64_v3/gcc-11.4.0/sundial
             s-6.6.2-hnnsesrffh2c2s3qddzs66adio5dba4u/examples/arkode/C_serial/
             ark_kepler.c
  [0;91m>> 7666    CMake Error at examples/arkode/C_serial/cmake_install.cmake:459 (f
             ile):[0m
     7667      file INSTALL cannot find
     7668      "/tmp/root/spack-stage/spack-stage-sundials-6.6.2-hnnsesrffh2c2s
             3qddzs66adio5dba4u/spack-src/examples/arkode/C_serial/ark_kepler_-
             -stepper_SPRK_--step-mode_fixed_--method_ARKODE_SPRK_EULER_1_1_--t
             f_50_--check-order_--nout_1.out":
     7669      No such file or directory.
     7670    Call Stack (most recent call first):
     7671      examples/arkode/cmake_install.cmake:47 (include)
     7672      examples/cmake_install.cmake:47 (include)
     7673      cmake_install.cmake:94 (include)
...
```

**Comment by balos1** [comment]
The original tar.gz file was corrupted. They have been reuploaded now so that hash has changed, but the updated ones should fix those errors @tldahlgren @balay.

**Review by balay — APPROVED** [review]

**Review by gardner48 — APPROVED** [review]

**Pull request merged**
