### PR TITLE
Add Kokkos 4.4.00

### PR DESCRIPTION
**Pull request by diehlpk**
[Kokkos 4.4.00](https://github.com/kokkos/kokkos/releases/tag/4.4.00) was released and this adds that to Spack.

### CODE REVIEW

**Comment by diehlpk** [comment]
@spackbot fix style

**Comment by diehlpk** [comment]
@spackbot maintainers

**Comment by lucbv** [comment]
I usually like to have these do both Kokkos and Kokkos-Kernels this way we don't run the ci twice.
Also I would look [here](https://github.com/kokkos/kokkos-kernels/releases/tag/4.4.00) to check if some of the changes to the build system require similar changes in spack?

**Comment by diehlpk** [comment]
> I usually like to have these do both Kokkos and Kokkos-Kernels this way we don't run the ci twice. Also I would look [here](https://github.com/kokkos/kokkos-kernels/releases/tag/4.4.00) to check if some of the changes to the build system require similar changes in spack?

I am not sure how to update kokkos kernels, where can I find instructions?

The only thing came to my mind would be to add grace grace and the RISC-V CPU as a CPU target.

**Comment by diehlpk** [comment]
@lucbv I updated the kokkos kernels package too.

**Review by alalazo — CHANGES_REQUESTED** [review]
Pipelines are failing to build `kokkos`, e.g. see: https://gitlab.spack.io/spack/spack/-/pipelines/793806/failures

**Comment by diehlpk** [comment]
```
==> Error: ChecksumError: sha256 checksum failed for /tmp/root/spack-stage/spack-stage-kokkos-4.4.00-cv2wml722zyyvipmgske2qvnnozxyssa/4.4.00.tar.gz
    Expected c7ed67311b42bdda1bd512d9bc8c74fa3914f0c979e5141c09f1dab3976f129c but got c638980cb62c34969b8c85b73e68327a2cb64f763dd33e5241f5fd437170205a. File size = 2458213 bytes. Contents = b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xec=is\xdb8...\xe5g\xf9y\xac\xcf\xff\x1f\x15E\xe0T\x00\x00\xd7\x00'
```

Ok, I need to investigate why the hash is wrong and not matching with GitHub.

**Comment by diehlpk** [comment]
Ok, it seems that the hash in https://github.com/kokkos/kokkos/releases/download/4.4.00/kokkos-4.4.00-SHA-256.txt is for https://github.com/kokkos/kokkos/releases/download/4.4.00/kokkos-4.4.00.tar.gz
```
shasum -a 256 kokkos-4.4.00.tar.gz 
c7ed67311b42bdda1bd512d9bc8c74fa3914f0c979e5141c09f1dab3976f129c  kokkos-4.4.00.tar.gz
```
And the hash for `Source code (tar.gz)` is the one below

```
shasum -a 256 kokkos-4.4.00\(2\).tar.gz 
c638980cb62c34969b8c85b73e68327a2cb64f763dd33e5241f5fd437170205a
```

it seems that Spack is pulling `Source code (tar.gz) ` and not `kokkos-4.4.00.tar.gz`.

I will update the has accordingly.

**Review by nmm0 — APPROVED** [review]
Good to go from me once the CI succeeds

**Comment by diehlpk** [comment]
@nmm0 and @lucbv and @alalazo  the CI passes now with using the correct hashes.

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks @diehlpk

**Review by masterleinad — APPROVED** [review]

**Comment by nmm0** [comment]
@alalazo I think the pipeline issues were fixed, can you re-review? Thanks!

**Review by cedricchevalier19 — APPROVED** [review]
LGTM

**Review by alalazo — APPROVED** [review]

**Pull request merged**
