### PR TITLE
Fix graph command with ASCII output

### PR DESCRIPTION
**Pull request by suraia**
Currently, calling the `graph` command with ASCII output fails:
```
$ spack graph netcdf
Traceback (most recent call last):
  ...
  File "spack/lib/spack/spack/graph.py", line 105, in topological_sort
    for dep in children(node).values():
AttributeError: 'list' object has no attribute 'values'
```

This PR fixes the ASCII output and also corrects two typos found in the `Spec` and `DependencyMap` classes.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Thanks! Out of curiosity, does this happen to fix #1098? Maybe you could take a look since you know more about how graph works than I do. It doesn't have to be part of this PR.

**Comment by suraia** [comment]
Sadly, it does not fix #1098 but I can take a look after I am done with this PR.

I have now pushed another commit to fix the tests. I tried to make them do something useful because previously they all seemed to do roughly the same.

**Comment by adamjstewart** [comment]
I just checked this out and it does indeed fix the `spack graph` problem. @suraia Can you rebase this off of the current develop and fix any lingering travis failures?

**Comment by suraia** [comment]
I rebased the commits to the current develop. There are a few remaining flake8 errors that I was unable to ignore; having the extra indentation there makes sense in my opinion.

**Pull request merged**
