### PR TITLE
Update amr-wind package with versions

### PR DESCRIPTION
**Pull request by marchdf**
Some relevant discussion is here https://github.com/Exawind/amr-wind/pull/1006

### CODE REVIEW

**Comment by psakievich** [comment]
This looks good to me. Will tarballs work for the release? Or no b/c of the submodules? 

See: https://spack.readthedocs.io/en/latest/packaging_guide.html#spack-checksum

**Comment by marchdf** [comment]
I think the tar balls work: https://github.com/Exawind/amr-wind/releases. They are listed there. So I added the `url` and now you can:
```
spack checksum amr-wind
==> Selected 7 versions. 7 new versions
  1.3.0  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.3.0.tar.gz
  1.2.1  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.2.1.tar.gz
  1.2.0  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.2.0.tar.gz
  1.1.0  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.1.0.tar.gz
  1.0.1  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.0.1.tar.gz
  1.0.0  https://github.com/Exawind/amr-wind/archive/refs/tags/v1.0.0.tar.gz
  0.9.0  https://github.com/Exawind/amr-wind/archive/refs/tags/v0.9.0.tar.gz

==> Enter number of versions to take, or use a command:
    [c]hecksum  [e]dit  [f]ilter  [a]sk each  [n]ew only  [r]estart  [q]uit
action> c
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.2.0.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.0.1.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.3.0.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.0.0.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v0.9.0.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.1.0.tar.gz
==> Fetching https://github.com/Exawind/amr-wind/archive/refs/tags/v1.2.1.tar.gz

    version("1.3.0", sha256="b2fbfd837fb39d76231a9e96ff3cbb1b1b0495e79917cd08e90a9f1db536c6bd")
    version("1.2.1", sha256="1a09bae6486ef9160d6a1894edcc9297dac224623c83748080bdcd94120eecea")
    version("1.2.0", sha256="db389e7ef51f8a0df9083a5925f6899d007c9d59ddbe599ecdaaab8f7cd888ce")
    version("1.1.0", sha256="73bf2f3ec79899538df42e94ac5821069a85a857aca9d9f79e8d475f9162e64d")
    version("1.0.1", sha256="39a49510fb25a4e7580a72ccc1ad6f6e824a683dce761ad80c9ab0b53cd66445")
    version("1.0.0", sha256="5f2c110e978790b825a5ce0547a648ce505688f6db090a09898b184afe463eab")
    version("0.9.0", sha256="bef7049f89359d8250eafae759e0ad3391592e64cd715d14f45cc85897dc1053")
```

Is that what you meant?

**Review by tldahlgren — COMMENTED** [review]
FYI. I confirmed all of the commits exist.

**Comment by psakievich** [comment]
@marchdf yes that is what I meant. Well sort of. So the tarballs can be added instead of a git commit.  That way when spack is fetching a release it doesn't need to use git and can just directly download and unpack the tarball source.  I believe that is the prefered version for releases. @tldahlgren please correct me if I am wrong.  This is fine though.

I tried to  build the `amr-wind+openfast` and the concretizer gave me what I expect.  Unfortunately during the build I got some openfast failures on my mac for not being able to find hdf5.  @jrood-nrel perhaps we need to push some more of our patches and other fixes to spack as well.

**Comment by marchdf** [comment]
OK happy to change things around but please just let me know what the end result should look like or point me to a package that shows how it should look like. I was just poking around using other examples I could find, e.g. libelf, amrex. 

Should the second issue you bring up be fixed with this PR or separately?

**Comment by tldahlgren** [comment]
> @marchdf yes that is what I meant. Well sort of. So the tarballs can be added instead of a git commit. That way when spack is fetching a release it doesn't need to use git and can just directly download and unpack the tarball source. I believe that is the prefered version for releases. @tldahlgren please correct me if I am wrong. This is fine though.

Tarballs with checksums are considered the most trustworthy source since Spack can check that the checksum matches what the package maintainer/author expected at the time the version was added.  Git commits with hashes are also implicitly trusted.  

We have a section on this in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#trusted-downloads.

**Comment by tldahlgren** [comment]
> > @marchdf yes that is what I meant. Well sort of. So the tarballs can be added instead of a git commit. That way when spack is fetching a release it doesn't need to use git and can just directly download and unpack the tarball source. I believe that is the prefered version for releases. @tldahlgren please correct me if I am wrong. This is fine though.
> 
> Tarballs with checksums are considered the most trustworthy source since Spack can check that the checksum matches what the package maintainer/author expected at the time the version was added. Git commits with hashes are also implicitly trusted.
> 
> We have a section on this in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#trusted-downloads.

That said, since you want to set `submodules` to `True`, I believe you need to provide either a branch or commit since the option is related to checking out the code (see https://spack.readthedocs.io/en/latest/packaging_guide.html#git).

**Comment by psakievich** [comment]
Let's go ahead and merge then. I have been having Fortran troubles with checking the submodule. I don't expect it to build since amr-wind vendors its own amrex but I was curious to try.

**Review by psakievich — APPROVED** [review]

**Pull request merged**
