### PR TITLE
julia: fix LLVM paches hashes

### PR DESCRIPTION
**Pull request by viroulep**
It looks like this is a recurring issue and it struck again; these are the past occurrences of the hash changes I could find:
  - #39034 
  - #39955 
  - #40041

### CODE REVIEW

**Comment by giordano** [comment]
If GitHub keeps changing the content of the patches it may be better to host permanent copies at https://github.com/spack/patches and we avoid keep chasing them forever.

**Comment by alalazo** [comment]
To get a more consistent sha256 you can suffix the URL with `?full_index=1`. I believe absence of this suffix was supposed to be caught in CI, but I'll double check.

**Comment by haampie** [comment]
That doesn't work for those urls

**Comment by haampie** [comment]
I've re-uploaded the patches here: https://github.com/spack/patches/tree/master/julia

Can you use those URLs?

```
https://github.com/spack/patches/raw/master/julia/<shasum>.patch
```

**Comment by viroulep** [comment]
Thanks!

My local build is still in progress but it should be good :)

**Comment by viroulep** [comment]
(Build finished and succeeded)

**Review by haampie — APPROVED** [review]

**Pull request merged**
