### PR TITLE
ffmpeg: add v6.0

### PR DESCRIPTION
**Pull request by alecbcs**
Add ffmpeg v6.0.

**Changelog:**
https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n6.0

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the sha256.  Deferring merge decision to give @xjrc a chance to comment.

**Comment by tldahlgren** [comment]
Looks like two versions of `py-torchvision` for two of the ML CI stacks are having issues.

**Comment by alecbcs** [comment]
I don't seeing `ffmpeg` listed in the dag for py-torch so I wonder if something else is going on here. @adamjstewart do these errors look familiar to you?

**Comment by adamjstewart** [comment]
Looks like this is a known issue: https://github.com/pytorch/vision/pull/7378. Can you edit `py-torchvision` from:
```python
depends_on("ffmpeg@3.1:", when="@0.13.0:")
```
to:
```python
# https://github.com/pytorch/vision/pull/7378
depends_on("ffmpeg@3.1:5", when="@0.13.0:")
```
Hopefully ffmpeg 6 will be supported in the next release.

**Comment by alecbcs** [comment]
Ah! Of course! Apologies I'd looked at py-torch instead of py-torchvision. Added the limit to the dependency.

**Review by adamjstewart — DISMISSED** [review]
Will let @trws review.

**Comment by alecbcs** [comment]
Ping @trws

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
