### PR TITLE
Add LLVM 11.0.0

### PR DESCRIPTION
**Pull request by naromero77**
@trws It would be helpful to get at least one other person to building this with GCC.

### CODE REVIEW

**Comment by trws** [comment]
I'll build a version myself, what GCC have you tried with?

**Comment by naromero77** [comment]
GCC 7.5.x

I just tried build this:
`spack install llvm+cuda%gcc cuda_arch=61`

and unfortunately it failed building the CUDA byte code need for OpenMP offload. I will need to dig into it later.

Let me try building the plain vanilla version.

**Comment by trws** [comment]
That's especially disturbing, since it's supposed to build that with the built compiler...  I'll try it with the devtoolset 8 compiler so we get something like a cross rhel7/8 test.

**Comment by naromero77** [comment]
For your reference:
```
- Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED
-- Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED - Failed
CMake Error at libomptarget/cmake/Modules/LibomptargetUtils.cmake:26 (message):
  LIBOMPTARGET: Cannot build CUDA LLVM bitcode offloading device RTL!
Call Stack (most recent call first):
  libomptarget/deviceRTLs/nvptx/CMakeLists.txt:126 (libomptarget_error_say)
```

So it does not get passed the second CMake invocation that builds the byte code. Here is the error that I see:
```
/scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-7.5.0/llvm-11.0.0-p5vk7snzs2ynsjzaj7cyki4qjnkoszn6/bin/clang  -Wall -Wcast-qual -Wformat-pedantic -Wimplic\
it-fallthrough -Wsign-compare -Wno-extra -Wno-pedantic -DCHECK_FUNCTION_EXISTS=__atomic_load_1 -rdynamic CMakeFiles/cmTC_99f89.dir/CheckFunctionExists.c.o -o cmTC_99\
f89
ld: CMakeFiles/cmTC_99f89.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x17): undefined reference to `__atomic_load_1'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/cmTC_99f89.dir/build.make:105: recipe for target 'cmTC_99f89' failed
make[1]: *** [cmTC_99f89] Error 1

```

**Comment by naromero77** [comment]
My machine is not that old:
[naromero@naromero-desktop packages (llvm_release11)]$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by naromero77** [comment]
Plain vanilla llvm7 builds correct with GCC 7.5. Not sure what is going on with the target offload part that creates the GPU bitcode.

**Comment by eschnett** [comment]
I think the patch file `constexpr_longdouble_9.0.patch` is missing a dash `-` in the first line. There are supposed to be three dashes, but there are only two.

**Comment by eschnett** [comment]
LLVM 11 has a new component `flang`. Ideally, there would be a new variant to enable building it. (`flang` isn't yet production-ready, so this doesn't seem strictly necessary.)

**Comment by naromero77** [comment]
@eschnett I was specifically told by the ECP Flang PI not to add flang because it is not production ready.

**Comment by naromero77** [comment]
> I think the patch file `constexpr_longdouble_9.0.patch` is missing a dash `-` in the first line. There are supposed to be three dashes, but there are only two.

Yes, that does not look correct.

**Comment by eschnett** [comment]
I am trying (and failing) to install `llvm` on MacOS. I am building with a MacPorts installed GCC 10.2.0, using this command:
```
spack install -v llvm ~libcxx ~lldb @11.0.0 %gcc ^cmake %apple-clang ^python %apple-clang
```

`cmake` and `python` don't build with GCC, thus I use Clang instead. Since these are build-time tools I don't think this causes problems.

When I enable `libcxx` or `lldb`, the build process aborts with errors. Since I don't need these I disabled them above.

This build command aborts with the error:
```
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:97:5: error: 'xpc_connection_send_message' was not declared in this scope; did you mean 'xpc_connection_handler_t'?
   97 |     xpc_connection_send_message(clientConnection, response);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     xpc_connection_handler_t
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp: In function 'void {anonymous}::xpcClosure::connection_handler(xpc_connection_t)':
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:149:3: error: 'xpc_connection_set_target_queue' was not declared in this scope
  149 |   xpc_connection_set_target_queue(clientConnection, dispatch_get_main_queue());
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:54: error: expected primary-expression before '^' token
  155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
      |                                                      ^
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:69: error: expected primary-expression before 'message'
  155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
      |                                                                     ^~~~~~~
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:68: error: expected ')' before 'message'
  155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
      |                                                       ~            ^~~~~~~~
      |                                                                    )
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:3: error: 'xpc_connection_set_event_handler' was not declared in this scope
  155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: Leaving directory '/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-build-u2vfnjr'
/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:185:3: error: 'xpc_connection_resume' was not declared in this scope; did you mean 'xpc_connection_t'?
  185 |   xpc_connection_resume(clientConnection);
      |   ^~~~~~~~~~~~~~~~~~~~~
      |   xpc_connection_t
```
I put the full log output into a gist at <https://gist.github.com/eschnett/3c27332cbfb55cd97c71efb0ad0f3445>.

**Comment by naromero77** [comment]
> I am trying (and failing) to install `llvm` on MacOS. I am building with a MacPorts installed GCC 10.2.0, using this command:
> 
> ```
> spack install -v llvm ~libcxx ~lldb @11.0.0 %gcc ^cmake %apple-clang ^python %apple-clang
> ```
> 
> `cmake` and `python` don't build with GCC, thus I use Clang instead. Since these are build-time tools I don't think this causes problems.
> 
> When I enable `libcxx` or `lldb`, the build process aborts with errors. Since I don't need these I disabled them above.
> 
> This build command aborts with the error:
> 
> ```
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:97:5: error: 'xpc_connection_send_message' was not declared in this scope; did you mean 'xpc_connection_handler_t'?
>    97 |     xpc_connection_send_message(clientConnection, response);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |     xpc_connection_handler_t
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp: In function 'void {anonymous}::xpcClosure::connection_handler(xpc_connection_t)':
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:149:3: error: 'xpc_connection_set_target_queue' was not declared in this scope
>   149 |   xpc_connection_set_target_queue(clientConnection, dispatch_get_main_queue());
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:54: error: expected primary-expression before '^' token
>   155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
>       |                                                      ^
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:69: error: expected primary-expression before 'message'
>   155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
>       |                                                                     ^~~~~~~
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:68: error: expected ')' before 'message'
>   155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
>       |                                                       ~            ^~~~~~~~
>       |                                                                    )
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:155:3: error: 'xpc_connection_set_event_handler' was not declared in this scope
>   155 |   xpc_connection_set_event_handler(clientConnection, ^(xpc_object_t message) {
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: Leaving directory '/private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-build-u2vfnjr'
> /private/var/folders/gb/x5lhfpj15ln66g6br549tz5m0000gn/T/eschnett/spack-stage/spack-stage-llvm-11.0.0-u2vfnjrpev6crbs4cq2jk4l7htlx65me/spack-src/clang-tools-extra/clangd/xpc/XPCTransport.cpp:185:3: error: 'xpc_connection_resume' was not declared in this scope; did you mean 'xpc_connection_t'?
>   185 |   xpc_connection_resume(clientConnection);
>       |   ^~~~~~~~~~~~~~~~~~~~~
>       |   xpc_connection_t
> ```
> 
> I put the full log output into a gist at https://gist.github.com/eschnett/3c27332cbfb55cd97c71efb0ad0f3445.

Is this specific to the Spack package or does this happen outside of Spack?

Tom and I volunteered to maintain the Spack package but we are not full time LLVM developers. If there is some specific combination that is known to work outside of Spack, then we should make sure it works in the Spack environment. But if the bug is with LLVM build system itself, your bug would be better addressed by the LLVM developers.

**Comment by eschnett** [comment]
I don't know whether this also happens outside Spack. I find LLVM a bit difficult to build from scratch and have never succeeded in doing so. (I can build GCC just fine.)

Since MacOS is a difficult platform, and since I don't know whether things work better with llvm @10, feel free to ignore my report.

**Comment by trws** [comment]
I'd bet that would happen in or out of Spack, that error looks like the blocks extension isn't supported in the GCC you were using @eschnett, which probably means clangd on Mac has to be built with a clang built with objective-c and/or blocks support.

**Comment by naromero77** [comment]
> For your reference:
> 
> ```
> - Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED
> -- Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED - Failed
> CMake Error at libomptarget/cmake/Modules/LibomptargetUtils.cmake:26 (message):
>   LIBOMPTARGET: Cannot build CUDA LLVM bitcode offloading device RTL!
> Call Stack (most recent call first):
>   libomptarget/deviceRTLs/nvptx/CMakeLists.txt:126 (libomptarget_error_say)
> ```
> 
> So it does not get passed the second CMake invocation that builds the byte code. Here is the error that I see:
> 
> ```
> /scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-7.5.0/llvm-11.0.0-p5vk7snzs2ynsjzaj7cyki4qjnkoszn6/bin/clang  -Wall -Wcast-qual -Wformat-pedantic -Wimplic\
> it-fallthrough -Wsign-compare -Wno-extra -Wno-pedantic -DCHECK_FUNCTION_EXISTS=__atomic_load_1 -rdynamic CMakeFiles/cmTC_99f89.dir/CheckFunctionExists.c.o -o cmTC_99\
> f89
> ld: CMakeFiles/cmTC_99f89.dir/CheckFunctionExists.c.o: in function `main':
> CheckFunctionExists.c:(.text+0x17): undefined reference to `__atomic_load_1'
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> CMakeFiles/cmTC_99f89.dir/build.make:105: recipe for target 'cmTC_99f89' failed
> make[1]: *** [cmTC_99f89] Error 1
> ```

@trws Can you try building with OpenMP offload target to the NVidia backend? I don't understand the CMake error, it says `__atomic_load_1` is undefined, but `-latomic` seems to be on the link line.

**Comment by naromero77** [comment]
It looks like 
`spack install llvm+cuda%gcc ^cuda@9.2.88 cuda_arch=61`

works for me. My guess is that there is some incompatibility between newer versions of the NVidia Toolkit and my configuration (GCC and/or my old GPU card). I could a conflict in now, but I am not sure where this conflict is coming from.

@adamjstewart  recommend merging this in once the travis-ci stuff completes, we can figure out the conflicts later.

**Comment by adamjstewart** [comment]
You folks would also be interested in #19347

**Review by adamjstewart — APPROVED** [review]

**Comment by naromero77** [comment]
@adamjstewart I have narrow the problem down, let me push one more commit. It looks like its just the most recent CUDA toolkit that is causing the problem.

**Comment by eschnett** [comment]
@trws `spack install -v llvm ~compiler-rt` (i.e. building with the Apple Clang compiler) works, as you predicted.

**Comment by naromero77** [comment]
@adamjstewart Just go ahead merged in. The failure on my workstation appears to be only with CUDA 11.1. I need to study this more, perhaps the conflict, if there is one, should go into the CUDA build system.

**Pull request merged**
