### PR TITLE
e4s ci: add catalyst

### PR DESCRIPTION
**Pull request by eugeneswalker**
Add `catalyst` to E4S CI stack

FYI @wspear @danlipsa @kwryankrattiger

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
LGTM.  Hopefully pipeline builds *and* the stand-alone tests pass.

**Review by tldahlgren — APPROVED** [review]

**Review by wspear — APPROVED** [review]

**Comment by kwryankrattiger** [comment]
FYI, this package is deprecated after 5.6 and was replaced by just using the paraview package which builds the catalyst tools.

**Comment by kwryankrattiger** [comment]
This is worth noting since the ecp-data-vis-sdk blocks buliding paraview < 5.10 which is the "preferred" way for deploying paraview in e4s.

**Comment by eugeneswalker** [comment]
> FYI, this package is deprecated after 5.6 and was replaced by just using the paraview package which builds the catalyst tools.

Closing this PR! Thanks!

**Pull request closed without merging**
