### PR TITLE
[babelstream] OpenMP Implementation Feature Update

### PR DESCRIPTION
**Pull request by kaanolgu**
# Changelog 
## New
[std-data,ranges,indices]
- Added Offload functionality to NVHPC for the std-data,indices,ranges
## Fix
[OpenCL]
- intel compiler having hardcoded version number

[OpenMP]
- Previously the OpenMP implementation was offloading to the Intel automatically. 
- Removed that and now in order to offload to intel user needs to specify a value to the `intel_target` variant.
- No variant provided will result in execution without any offloads

### CODE REVIEW

**Comment by kaanolgu** [comment]
@spackbot fix style

**Review by tomdeakin — APPROVED** [review]

**Comment by haampie** [comment]
Could you potentially also fix the hard-coded path https://github.com/spack/spack/blob/45838cee0b8b01ad999b459ed6d19e37686859c0/var/spack/repos/builtin/packages/babelstream/package.py#L322? It doesn't make a lot of sense :upside_down_face: notice `2023.0.0` is the compiler version and should be interpolated

**Comment by kaanolgu** [comment]
@haampie  Thanks for pointing out ! I have updated it to detect the version from the package name

**Comment by kaanolgu** [comment]
@spackbot fix style

**Comment by kaanolgu** [comment]
@spackbot fix style

**Comment by kaanolgu** [comment]
@spackbot fix style

**Pull request closed without merging**
