### PR TITLE
py-pythran: add new version

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on macOS 10.15.7 with Python 3.8.11 and Apple Clang 12.0.0.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@spackbot help

**Comment by adamjstewart** [comment]
@spackbot commands

**Comment by adamjstewart** [comment]
@spackbot re-run pipeline

**Comment by adamjstewart** [comment]
Failing CI seems like a concretization issue? @scottwittenburg could we use Spack's new concretizer?

**Comment by tgamblin** [comment]
I do think it would be good to switch the pipeline over to clingo.

**Comment by tgamblin** [comment]
@spackbot commands

**Comment by tgamblin** [comment]
@spackbot commands

**Comment by sethrj** [comment]
Spackbot is responding to itself... great 😂

**Comment by tgamblin** [comment]
@sethrj I think this is fixed -- we were testing it

@spackbot commands

**Comment by tgamblin** [comment]
@spackbot help

**Comment by tgamblin** [comment]
@sethrj yep works now! @vsoch FYI

**Comment by vsoch** [comment]
@sethrj we all like talking to ourselves sometimes, spackbot was just having a morning. :)

**Comment by vsoch** [comment]
Also I really did think of and test that comment case, and the regular expression to test if spack bot was the one making the comment worked for my development bot but not the production bot! So that’s me having a day :)

**Comment by tgamblin** [comment]
@vsoch spackbot is great and helping out lots! If it makes you feel any better here are all the spack bugs: https://github.com/spack/spack/issues there are only 1.6k 😅

**Comment by adamjstewart** [comment]
So, back to the failing CI... I think we can either use clingo in CI, or set an older version as `preferred` so that the old concretizer doesn't break. Thoughts?

**Comment by haampie** [comment]
Let's switch to clingo, cause this issue pops up in different prs, and I don't think it's a great idea to change all kinds of recipes to support the old concretizer, unless they are required deps for bootstrapping. In fact we already have recipes that are clingo-only.

**Review by haampie — APPROVED** [review]

**Pull request merged**
