### PR TITLE
hipcc: new package for HIP

### PR DESCRIPTION
**Pull request by afzpatel**

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
@srekolam, @renjithravindrankannath, @haampie: LGTM, do have a comment?

We'd have to give you a few more days to comment, then we'd merge at some point!

**Review by renjithravindrankannath — APPROVED** [review]
LGTM

**Comment by pranav-sivaraman** [comment]
I'm not too familiar with the HIP toolchain, but what's the point of this package when` llvm-amdgpu `exists? Especially since the [README](https://github.com/ROCm/HIPCC/blob/develop/README.md) for hipcc mentions its a deprecated read-only mirror of `llvm-amdgpu`. Does it fix some issue that requires using the hipcc driver versus compiling with an application using amdclang++?  Or is it just to ease compiling with HIP?

**Review by bernhardkaindl — APPROVED** [review]
@afzpatel / @srekolam:

JFYI, @pranav-sivaraman has a question:

> I'm not too familiar with the HIP toolchain, but what's the point of this package when`llvm-amdgpu`exists? Especially since the [README](https://github.com/ROCm/HIPCC/blob/develop/README.md) for hipcc mentions its a deprecated read-only mirror of `llvm-amdgpu`. Does it fix some issue that requires using the hipcc driver versus compiling with an application using amdclang++? Or is it just to ease compiling with HIP?

PS: If all is good (or there is no further comment), then AFAIK, I think this can be merged early next week.

@afzpatel: Can you check the title of this PR?
I'm updating it to "**hipcc: new package for HIP**"
(It should be used as the new commit message when squashing your commits during merge)

**Comment by srekolam** [comment]
> @afzpatel / @srekolam:
> 
> JFYI, @pranav-sivaraman has a question:
> 
> > I'm not too familiar with the HIP toolchain, but what's the point of this package when`llvm-amdgpu`exists? Especially since the [README](https://github.com/ROCm/HIPCC/blob/develop/README.md) for hipcc mentions its a deprecated read-only mirror of `llvm-amdgpu`. Does it fix some issue that requires using the hipcc driver versus compiling with an application using amdclang++? Or is it just to ease compiling with HIP?
> 
> PS: If all is good (or there is no further comment), then AFAIK, I think this can be merged early next week.
> 
> @afzpatel: Can you check the title of this PR? I'm updating it to "**hipcc: new package for HIP**" (It should be used as the new commit message when squashing your commits during merge)

@pranav-sivaraman  you can read about hipcc - https://rocm.docs.amd.com/projects/HIPCC/en/latest/ 
the current hipcc repo is being moved inside /amd subdirectory of llvm-amdgpu but we will still be having a spack package for hipcc for newer releases.

**Comment by pranav-sivaraman** [comment]
Alright fair enough. LGTM.

**Comment by tldahlgren** [comment]
Is this PR ready to merge?

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
