### PR TITLE
enable packages that use numpy for oneapi e4s stack

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by eugeneswalker** [comment]
Looks like the `geopm` build failed ??
* [(specs) geopm/3afbzx5 1.1.0 oneapi@2022.1.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/3101083)
```
==> [2022-08-21-06:42:08.982342] '/usr/bin/bash' './autogen.sh'
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
sh: 5: [: Illegal number: 
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
sh: 5: [: Illegal number: 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
sh: 5: [: Illegal number: 
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
sh: 5: [: Illegal number: 
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
sh: 5: [: Illegal number: 
Useless use of a variable in void context at /home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/automake-1.16.5-qt4orqmf3aocrfd6tg7wf65yz5ehnfq3/bin/automake line 8469.
autoreconf: automake failed with exit status: 255
==> [2022-08-21-06:42:19.254093] Error: ProcessError: Command exited with status 1:
    '/usr/bin/bash' './autogen.sh'
See build log for details:
  /tmp/root/spack-stage/spack-stage-geopm-1.1.0-3afbzx573vtzrlr5mbj5nlof4yjibhqi/spack-build-out.txt
```

**Comment by rscohn2** [comment]
I am following the spack ci instructions for reproducing the error. I thought it passed with my first commit, but now I am not sure if it ran.

**Comment by eugeneswalker** [comment]
Looking closer at the `geopm` package, it looks like `ruby` only comes in as a dependency when we build `geopm +docs` (which is set by default). We should probably request explicitly `geopm ~docs` so that we don't have to deal with ruby at all. Even doing that, it looks like we'll still have some issues, but at least we can cut ruby out of the dag entirely.

**Comment by rscohn2** [comment]
Yes, ruby can be eliminated. They said the next release will not use ruby for documentation. There were some tricky c++ issues that need to be resolved so I removed geopm from this PR and just add the numpy dependent packages instead. Everything is passing now so can you take a look at it?

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@eugeneswalker If this is fine with you I'd merge

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
