### PR TITLE
environment: match concrete specs only if they have the same build hash

### LINKED ISSUE #25563: Pipelines failing if two specs have same dag hash, but different full hashes
### Steps to reproduce

The issue can be reproduce locally with this simple environment:
```yaml
spack:
  specs:
  - libpciaccess ^libtool@2.4.6
  - libpciaccess ^libtool@develop
```
which installs the same spec using two different build dependencies. This results in the two specs having:
- The same value for `dag_hash`
- Different values for `build_hash` and `full_hash`

The environment can be concretized correctly and produces a valid `spack.lock`:

<details>

<summary>$ spack concretize</summary>

```console
==> Concretized libpciaccess ^libtool@2.4.6
 -   hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   swnsnhf      ^libtool@2.4.6%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   grd2nfx          ^m4@1.4.19%gcc@11.1.0+sigsegv arch=linux-ubuntu18.04-broadwell
[+]  oo46dbm              ^libsigsegv@2.13%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
[+]  o55dukk      ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
[+]  gzatf2b      ^util-macros@1.19.3%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell

==> Concretized libpciaccess ^libtool@develop
 -   hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   7fvqcq5      ^libtool@develop%gcc@11.1.0 patches=055fdac32f7768c44f64dfc18c183233a7909ff8b7556f67038350eed2056571 arch=linux-ubuntu18.04-broadwell
 -   nw7erwd          ^autoconf@2.69%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   grd2nfx              ^m4@1.4.19%gcc@11.1.0+sigsegv arch=linux-ubuntu18.04-broadwell
[+]  oo46dbm                  ^libsigsegv@2.13%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   276j6k5              ^perl@5.34.0%gcc@11.1.0+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
[+]  zygezsz                  ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu18.04-broadwell
 -   maxtuqi                  ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared arch=linux-ubuntu18.04-broadwell
 -   cxdoxv2                      ^diffutils@3.7%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
[+]  kju5v7i                          ^libiconv@1.16%gcc@11.1.0 libs=shared,static arch=linux-ubuntu18.04-broadwell
 -   fpjhmtn                  ^gdbm@1.19%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   uycefnd                      ^readline@8.1%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   6peormu                          ^ncurses@6.2%gcc@11.1.0~symlinks+termlib abi=none arch=linux-ubuntu18.04-broadwell
[+]  o55dukk                              ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
[+]  5rs6nuu                  ^zlib@1.2.11%gcc@11.1.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
 -   gvowywk          ^automake@1.16.3%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   7fpysee          ^help2man@1.47.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
 -   s5tjkhg          ^texinfo@6.5%gcc@11.1.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-ubuntu18.04-broadwell
[+]  o7bfci5          ^xz@5.2.5%gcc@11.1.0~pic libs=shared,static arch=linux-ubuntu18.04-broadwell
[+]  gzatf2b      ^util-macros@1.19.3%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
```

</details>

It can also be installed correctly as a whole by:
```console
$ spack install
```
However, trying to install only part of it fails:
```console
$ spack install --no-add libpciaccess
==> Error: libpciaccess matches multiple specs in the environment /home/culpo/tmp/fullhash: 
Root spec libpciaccess ^libtool@2.4.6
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
Root spec libpciaccess ^libtool@develop
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
```
Not that **this also happens if we use a spec.yaml from a concrete spec** which is what we do in pipelines:
```console
$ spack install --no-add -f libpciaccess.yaml
==> Error: libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^libsigsegv@2.13%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^libtool@2.4.6%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^m4@1.4.19%gcc@11.1.0+sigsegv arch=linux-ubuntu18.04-broadwell ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^util-macros@1.19.3%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell matches multiple specs in the environment /home/culpo/tmp/fullhash: 
Root spec libpciaccess ^libtool@2.4.6
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
Root spec libpciaccess ^libtool@develop
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
```

### Error message

```console
$ spack install --no-add -f libpciaccess.yaml
==> Error: libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^libsigsegv@2.13%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^libtool@2.4.6%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^m4@1.4.19%gcc@11.1.0+sigsegv arch=linux-ubuntu18.04-broadwell ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell ^util-macros@1.19.3%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell matches multiple specs in the environment /home/culpo/tmp/fullhash: 
Root spec libpciaccess ^libtool@2.4.6
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
Root spec libpciaccess ^libtool@develop
  hihk3pi  libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu18.04-broadwell
```

### Information on your system

This should not be extremely relevant. The error was first spotted in pipelines, e.g. [here](https://gitlab.spack.io/spack/spack/-/jobs/659647) I reproduced it on:

* **Spack:** 0.16.2-4008-2971a630b8
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell
* **Concretizer:** original

Another thing to note is that _the issue happens also with the original concretizer_, but for some reason `clingo` is more likely to change build dependencies than the original concretizer.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by alalazo**
fixes #25563

When we have a concrete environment and we ask to install a concrete spec from a file, currently Spack returns a list of specs that are all the one that match the argument DAG hash. Instead we want to compare build hashes, which also account for build-only dependencies.

### CODE REVIEW

**Review by becker33 — APPROVED** [review]
Wasn't this already committed as part of another PR?

**Comment by alalazo** [comment]
@becker33 No, this is cherry-picked from #25502 since I think we might want to check a few more things before merging that.

**Comment by tldahlgren** [comment]
> Wasn't this already committed as part of another PR?

I asked if it could be separate from the PR for making clingo the default since I've been having issues with this for my RADIUSS CI work.  I spent a little time yesterday trying to see if this PR helps in a local context but don't have the configuration quite right to be sure.  BUT, it LGTM.

**Review by tldahlgren — APPROVED** [review]
Thank you!

**Comment by tldahlgren** [comment]
@alalazo Thanks again for this fix!  My `RADIUSS` Cloud CI build was able to get past its multiple `font-util` issue thanks to this change.  🎊 🍾

**Comment by alalazo** [comment]
Glad this was helpful!

**Pull request merged**
