### PR TITLE
expat: add v2.6.4

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Review by wdconinc — APPROVED** [review]
Verified checksum. Builds correctly.

**Comment by wdconinc** [comment]
Pipeline failure at https://gitlab.spack.io/spack/spack/-/jobs/13474310. At first glance this looks unrelated to this PR.

**Comment by wdconinc** [comment]
If I were to guess (and I'll attempt to confirm later) this is a possible regression introduced by https://github.com/spack/spack/pull/47495. (@haampie FYI).

**Comment by wdconinc** [comment]
@hartwork Could you rebase to pick up #47537 which should fix CI checks?

**Comment by hartwork** [comment]
> @hartwork Could you rebase to pick up #47537 which should fix CI checks?

@wdconinc sure, done :+1:

**Pull request merged**
