### PR TITLE
llvm-amdgpu and composable-kernel: fix build failures

### PR DESCRIPTION
**Pull request by afzpatel**
llvm-amdgpu issue https://github.com/spack/spack/issues/46832:
Dependent packages are failing when libclang_rt.asan-x86_64.so is not installed by llvm-amdgpu. Thanks @teaguesterling for finding the issue and suggesting the fix!

composable-kernel:
Disabling compiler warnings since the build is failing on gfx906 with the following error:
```
/tmp/root/spack-stage/spack-stage-composable-kernel-6.2.0-bi5qajt5kucqchsw6hri4nxbfxf3nycj/spack-src/include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_weight_two_stage_xdl_cshuffle.hpp:50:38: error: unused parameter 'a_grid_desc_ak0_m_ak1' [-Werror,-Wunused-parameter]
   50 |             const AGridDesc_AK0_M_K1 a_grid_desc_ak0_m_ak1,
      |
```

### CODE REVIEW

**Comment by afzpatel** [comment]
The ck build issue has been fixed with this commit: https://github.com/ROCm/composable_kernel/commit/959073842c0db839d45d565eb260fd018c996ce4

The commit doesn't apply onto 6.2, so I added a patch with only the code that is required to fix the issue.

**Review by srekolam — APPROVED** [review]

**Review by renjithravindrankannath — APPROVED** [review]

**Comment by afzpatel** [comment]
@bernhardkaindl could you please review and merge this pr?

**Comment by afzpatel** [comment]
Hi @bernhardkaindl,

@srekolam, @renjithravindrankannath and I are the AMD maintainers of ROCm recipes on spack

@amd-toolchain-support does not maintain ROCm recipes on spack and should not be added for ROCm related issues and pull requests. From my understanding, @amd-toolchain-support is only for AMD CPU tools.

**Review by bernhardkaindl — APPROVED** [review]
@afzpatel, thanks, and as I see you already got two approvals, I approve and merge!

**Pull request merged**
