### PR TITLE
Suite sparse rename

### PR DESCRIPTION
**Pull request by davydden**
as nobody objected renaming `suite sparse` here https://github.com/LLNL/spack/issues/580, that's what this PR is about.

### CODE REVIEW

**Comment by alalazo** [comment]
I am not against this change, but please let's avoid an holy war on renaming...

**Comment by davydden** [comment]
it's the only package which is named badly without a reason. Before we go ahead and use it in many other packages, i would suggest to fix the name.

**Comment by alalazo** [comment]
You know why I say that : it adds nothing and may leave bug behind. Try to install `eigen+suitesparse` now...

**Comment by alalazo** [comment]
Another thing is : it's not named badly without a reason. It was created following exactly what the documentation prescribes. If other software packagers decides to use CamelCase in a `tar.gz` the command `spack create <url>` won't produce a good name if we start to adopt this rule.

I find it more annoying than something prescribed in the docs doesn't work rather than a name in CamelCase. Of course this may be just my personal taste.

**Comment by davydden** [comment]
i see you point. I grepped for `SuiteSparse`, so it should be good now with `eigen` and `octave`.

**Comment by davydden** [comment]
as always, this is just a proposition. I ain't gonna be pissed of if the PR is not merged :smile:

**Comment by alalazo** [comment]
Naturally, nothing personal intended, my comments were just to share my opinion on this. If I am minority and people want to merge I'll also get along with it :smile:

**Comment by tgamblin** [comment]
I'm leaving this up to @alalazo.  I'm kind of agnostic and `git blame` shows he's the guy who added the package.  I like lowercase + dashes and wouldn't be unhappy if `spack create` started naming things that way.  I'm also not opposed to people renaming things away from what `spack create` picks if they think they've got a better name -- `spack create` is automatic and was intended mainly to get packagers up and running, not to create a precedent.  You may be interested (or irritated?) to know that you *can* name packages starting with numbers... MacPorts had `3proxy` (http://3proxy.ru) so I figured why not?  Blame the Russians...

So up to you @alalazo.

**Comment by alalazo** [comment]
I am not against this change in particular, so it's fine with me to merge. My point more generally is that usually renaming spates bring more troubles than benefits : you know today it's suite sparse, tomorrow all the python modules... :smile:

**Pull request merged**
