### PR TITLE
plumed 2.9.1 

### PR DESCRIPTION
**Pull request by draenog**
Add plumed 2.9.1 and configure gromacs to use it.

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Review by mabraham — APPROVED** [review]

**Comment by mabraham** [comment]
@junghans You can merge, I can't

**Review by alalazo — APPROVED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
On a second look, there's one issue in pipelines: https://gitlab.spack.io/spack/spack/-/jobs/12339802

**Comment by mabraham** [comment]
> On a second look, there's one issue in pipelines: https://gitlab.spack.io/spack/spack/-/jobs/12339802

Unlikely related to this MR. Is that configuration working reliably for other PRs?

**Comment by alalazo** [comment]
Let's try to re-run, but in general yes - that configuration was building reliably before.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by junghans** [comment]
```
configure: error: C++ compiler cannot create executables
```
seems unrelated, but we still need to fix this!

**Comment by mabraham** [comment]
@alalazo https://gitlab.spack.io/spack/spack/-/jobs/12342276#L112 looks like some preliminary download failed, so I guess that's why the compiler wasn't functional. Any ideas?

**Comment by alalazo** [comment]
@mabraham That seems to be retried and ok 2 lines below. The real error seems https://gitlab.spack.io/spack/spack/-/jobs/12342276#L486

**Comment by mabraham** [comment]
> @mabraham That seems to be retried and ok 2 lines below. The real error seems https://gitlab.spack.io/spack/spack/-/jobs/12342276#L486

Indeed, but that makes no sense if all the change is doing is upgrading a point version of plumed. I'm guessing the failing pipeline is broken and this is just the first (gromacs?) PR to show it. I've opened https://github.com/spack/spack/pull/46050 to try to test that idea.

**Comment by mabraham** [comment]
So #46050 has net no changes, and passes all CI, so maybe plumed 2.9.1 somehow has broken exactly this configuration. Weird. I don't see anything in their release notes https://www.plumed.org/doc-v2.9/user-doc/html/_c_h_a_n_g_e_s-2-9.html (or for the 2.8.x series)

**Comment by junghans** [comment]
@GiovanniBussi any suggestions?

**Comment by GiovanniBussi** [comment]
> @GiovanniBussi any suggestions?

Hi, where can I see the failure? Is this it [this](https://github.com/spack/spack/pull/46022#issuecomment-2310524894)? It would be quite puzzling. Can you confirm that 2.9.0 can build and 2.9.1 cannot build with everything else being the same?

**Comment by alalazo** [comment]
@eugeneswalker Do you know if there was any change to those runners recently? I have seen failures on `cray-rhel` in other PRs too, which seem unrelated to the PR itself.

**Comment by mabraham** [comment]
> > @GiovanniBussi any suggestions?
> 
> Hi, where can I see the failure? Is this it [this](https://github.com/spack/spack/pull/46022#issuecomment-2310524894)? It would be quite puzzling. Can you confirm that 2.9.0 can build and 2.9.1 cannot build with everything else being the same?

https://gitlab.spack.io/spack/spack/-/jobs/12342276#L486 has the full details. I tried at https://github.com/spack/spack/pull/46050 to get it to rebuild 2.9.0 but even though that CI succeeded, it didn't build any new artefacts. So my guess is still that that image is broken somehow.

I've now made an unrelated real PR to the GROMACS recipe (https://github.com/spack/spack/pull/46065), which might uncover whether that build image is working for plumed 2.9.0

**Comment by mabraham** [comment]
> I've now made an unrelated real PR to the GROMACS recipe (#46065), which might uncover whether that build image is working for plumed 2.9.0

Nope, that didn't rebuild the failing configuration either.

**Comment by mabraham** [comment]
GROMACS 2024.4 is expected to release later this week, at which point we can make a spack PR that will definitely trigger all configurations, and thereby learn something here.

**Comment by mabraham** [comment]
> GROMACS 2024.4 is expected to release later this week, at which point we can make a spack PR that will definitely trigger all configurations, and thereby learn something here.

Let's see what https://github.com/spack/spack/pull/46117 teaches us

**Comment by mabraham** [comment]
Indirectly we have learned that the rhel-cray configuration is indeed broken (#46111) so if we update this PR then CI should pass because failure there is tolerated.

**Review by alalazo — APPROVED** [review]

**Comment by zhan4429** [comment]
> ```
> configure: error: C++ compiler cannot create executables
> ```
> 
> seems unrelated, but we still need to fix this!

Hello, I am trying to build gromacs@2023.5 +cuda + plumed with openmpi and plumed@2.9.2. But the configuration step of plumed 2.9.2 got `configure: error: C++ compiler cannot create executables`. I saw your post and wonder how to fix this issue. Thanks!

**Pull request merged**
