### PR TITLE
Celeritas: new versions 0.1.4 and 0.2.0

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed both new sha256.

**Comment by sethrj** [comment]
Thanks @tldahlgren !

**Comment by sethrj** [comment]
RTD build "terminated due to inactivity".

@spackbot run pipeline

**Comment by sethrj** [comment]
Closed and reopened to try to restart the RTD pipeline :(

**Comment by sethrj** [comment]
The CI build passed but wasn't reported to the status check. The RTD timed out again...

**Comment by tldahlgren** [comment]
> The CI build passed but wasn't reported to the status check. The RTD timed out again...

If this doesn't work, let's try "Update branch" (button or a manual rebase).

**Comment by sethrj** [comment]
Did that once, still waiting...

**Review by drbenmorgan — APPROVED** [review]
Also good from my side!

**Pull request merged**
