### PR TITLE
Add new variants (OPENCL and HIP)  for MIVisionX recipe  and their dependencies correctly.

### PR DESCRIPTION
**Pull request by srekolam**
Add the new variants for each backend that MIVisionX supports . Also correctly choose the dependencies for each variant.
for OPENCL - rocm-opencl, miopengemm and miopen-opencl
for HIP - miopen-hip
Earlier this was adding both the dependencies -miopen-hip and miopen-opencl
for both the backends which did not seem correct.
Also corrected the miopen-hip or miopen-opencl config.h  in patch() depending on the
backend
Also added libjpeg-turbo as it is required for building ROCAl .
the AMDRpp is still required for ROCAL inclusion but it currently does not build
AMDRpp will be added as a new spack recipe and the mivisionx will refer to that as a
dependency in future.
 
This PR is dependent on changes for rocm-5.2.1 release . Refer to the PR #32195

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed new sha256.  Rest LGTM.

**Comment by tldahlgren** [comment]
Please resolve the file conflict.

**Comment by srekolam** [comment]
i will be submitting  a new spack package for rpp which is required for RocAL ..which is part of mivisionx . Since rpp is not currently present , RocAL is not built as part of MIVisionx for both the back end - HIP and OPENCL. Also, in future (5.3.0 +) RoCAL will be a new spack package .

**Comment by tldahlgren** [comment]
Updating branch to pick up #32733 changes.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
@renjithravindrankannath Are you okay with this PR being merged?

**Review by renjithravindrankannath — APPROVED** [review]

**Review by renjithravindrankannath — APPROVED** [review]

**Pull request merged**
