### PR TITLE
petsc: a temporary workaround for concretizer bug in all packages whi…

### PR DESCRIPTION
**Pull request by davydden**
…ch depend on SLEPc

see https://github.com/LLNL/spack/issues/5753#issuecomment-336492344

@balay @barrysmith ping

### CODE REVIEW

**Comment by balay** [comment]
I don't really understand the issue here. But this temporary workaround  is ok with me

Also current slepc-'master' should work with petsc-3.8 [and should be released as slepc-3.8 sometime in the near future]

**Comment by davydden** [comment]
@tgamblin @junghans  ping.

**Comment by davydden** [comment]
@alalazo can you merge this one as well? 😄

**Comment by davydden** [comment]
@junghans ping

**Comment by davydden** [comment]
@tgamblin Todd, can you please merge this workaround? A concretization issue makes packages which use SLEPc broken at the moment.... So i would really like this `preferred` workaround to be merged ASAP.

**Comment by davydden** [comment]
@tgamblin thanks!

**Pull request merged**
