### PR TITLE
py-horovod: add py-tensorflow-estimator dependency

### LINKED ISSUE #28656: Installation issue: py-horovod missing dependency when framework is tensorflow
### Steps to reproduce the issue

It seems that py-horovod is missing dependency `py-tensorflow-estimator`. 
Currently if I build it with `frameworks=tensorflow`, the output of `horovodrun --check-build` is
```console
Horovod v0.23.0:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [ ] MPI
    [ ] Gloo 
```

Using verbose output shows the exception:
```console
ModuleNotFoundError: No module named 'tensorflow_estimator'
Extension tensorflow was NOT built.
```

Add `py-tensorflow-estimator` as dependency seems to solve the issue.

### Information on your system

* **Spack:** 0.17.1-957-bed3a69498
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

@adamjstewart  @aweits  @tgaddair

The build succeeds, but it is not usable, giving
```console
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).
```
since each time it runs, it will first check installation which imports `tensorflow_estimator`
[spack-build-env.txt](https://github.com/spack/spack/files/7957256/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7957257/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #28656 

@asesidaa @glennpj

### CODE REVIEW

**Review by glennpj — APPROVED** [review]
LGTM

**Comment by glennpj** [comment]
It is probably worthwhile giving this a test with the new tensorflow versions. I can do that.

**Comment by glennpj** [comment]
Well, clingo selects TF-2.6 for py-horovod rather than the expected TF-2.7. Is there any way to find out why clingo is doing that?

**Comment by glennpj** [comment]
If I add `^py-tensorflow@2.7.0` it successfully concretizes.

**Comment by adamjstewart** [comment]
> Is there any way to find out why clingo is doing that?

I think you want to run `spack solve py-horovod` and `spack solve py-horovod ^py-tensorflow@2.7.0` and compare the badness of both to see why it made the decision it did.

**Pull request merged**
