### PR TITLE
grass: Update spec for gdal dependency

### PR DESCRIPTION
**Pull request by jlegewie**
Grass 8.2.0 works with more recent versions of gdal so I relaxed the dependency for @8.2. @7.8 should be unchanged. It might be possible to further relax the version of gdal but I haven't tested all combinations.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
Personally I would use no upper bound unless we know for a fact that it isn't compatible. I can't even remember why I locked down the older versions. I wonder if the supported GDAL versions are documented anywhere, especially the lower bound.

**Comment by jlegewie** [comment]
Agree about the upper bounds. I just wasn't able to find anything definitive on GDAL versions required by GRASS GIS aside from (fixed) bug reports related to gdal 3 on windows (https://github.com/OSGeo/grass/issues/1872). The current PR played it safe and only made changes that I explicitly tested.

**Comment by adamjstewart** [comment]
Looks like this change was made in #24737. @alecbcs do you remember why this was needed?

**Comment by alecbcs** [comment]
> Looks like this change was made in #24737. @alecbcs do you remember why this was needed?

I don't. This was before we had proper CI testing many of these packages. I likely ran into an error building grass with a newer gdal and thus limited it to a version that'd build successfully. If we can test that this builds without an upper bound limit, I'm happy to remove the limit or scope it to previous versions of grass.

**Review by alecbcs — DISMISSED** [review]
Looks good to me. Thanks @jlegewie!

**Comment by adamjstewart** [comment]
I would at least remove the :3.7 upper bound. Would be nice to test the :3.2 upper bound to figure out where it should actually be. Also, during building I found some possible issues with the Python version. It seems like 7.8 uses collections imports that are no longer valid in Python 3.10+. Might want to add an upper bound on Python version for older grass.

**Comment by alecbcs** [comment]
ping @jlegewie

**Comment by jlegewie** [comment]
Happy to update the pull request with any suggestion here but unsure about the direction. Is the idea to remove the :3.7 upper bound as suggested by @adamjstewart and leave :3.2 in place for grass@7.8 until someone does more testing?

**Comment by adamjstewart** [comment]
I would like the constraints to be as loose as possible. That is, unless you know for a fact that a certain combination is invalid, then there shouldn't be a conflict. So if you know that 8.2+ supports all known versions of GDAL, I would use:
```python
depends_on("gdal", when="+gdal")
conflicts("^gdal@3.3:", when="@7.8")
```
Ideally, you would test the min/max versions of GDAL for a few versions of GRASS to confirm that things build.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
