### PR TITLE
AMD ROCm 4.3: Bump up rvs version to 4.3 and fix hip patch

### PR DESCRIPTION
**Pull request by arjun-raj-kuppala**

### CODE REVIEW

**Comment by srekolam** [comment]
can you also include the changes for fixing the sudo issue in this PR?

**Comment by srekolam** [comment]
i meant the commit from this   
https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/commit/35a877b43dac4bdcc2397f7ef520fad8ec7786d6

**Comment by arjun-raj-kuppala** [comment]
ack

**Comment by arjun-raj-kuppala** [comment]
> i meant the commit from this
> [ROCm-Developer-Tools/ROCmValidationSuite@35a877b](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/commit/35a877b43dac4bdcc2397f7ef520fad8ec7786d6)

This patch is added to the recipe

**Review by haampie — APPROVED** [review]

**Pull request merged**
