### PR TITLE
vecgeom: add v1.1.19

### PR DESCRIPTION
**Pull request by drbenmorgan**
Simple version bump with the latest tag, plus small adjustment to CUDA build args due to migration of build to use native CMake CUDA support.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]
Thanks @drbenmorgan !

**Comment by sethrj** [comment]
@drbenmorgan It looks like the `CUDA_ARCH` flag also needs to be changed to the standard `CMAKE_CUDA_ARCHITECTURES`, correct? I just did a build of vecgeom with `-DCUDA_ARCH:STRING=35` and it built with `--generate-code=arch=compute_52,code=[compute_52,sm_52]`.

**Comment by drbenmorgan** [comment]
@sethrj, ah ...., sorry I missed that, let me prep a fix PR right now.

**Comment by sethrj** [comment]
I'm on it already.. gimme 30 seconds and you can just approve mine :) No problem!

**Pull request merged**
