### PR TITLE
Add double batched FFT library package

### PR DESCRIPTION
**Pull request by uphoffc**
Adds a package for the double batched FFT library that provides FFT routines for Intel GPUs and supports the Level Zero, OpenCL, and SYCL run-time.

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed the branches exist and the version sha256.

**Review by tldahlgren — COMMENTED** [review]
FYI.  I am unable to build using `spack install double-batched-fft-library`:

```
...
==> Installing double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q
==> No binary for double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q found: installing from source
==> Fetching https://github.com/intel/double-batched-fft-library/archive/refs/tags/v0.3.6.tar.gz
==> No patches needed for double-batched-fft-library
==> double-batched-fft-library: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cmake-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q/lib;/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q/lib64;/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/oneapi-level-zero-1.7.15-l7ub7swv7ubbjtmzgza5gn4hejeinezp/lib64' '-DCMAKE_PREFIX_PATH:STRING=/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/oneapi-level-zero-1.7.15-l7ub7swv7ubbjtmzgza5gn4hejeinezp;/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cmake-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DBUILD_SYCL:BOOL=ON' '' '' '-DBUILD_BENCHMARK:BOOL=OFF' '-DBUILD_EXAMPLE:BOOL=OFF' '-DBUILD_TESTING:BOOL=OFF' '/var/tmp/dahlgren/spack-stage/spack-stage-double-batched-fft-library-0.3.6-bx2mc7dow67wydimejow562teivkyh3q/spack-src'

1 error found in build log:
     29    -- Looking for CL_VERSION_1_2
     30    -- Looking for CL_VERSION_1_2 - not found
     31    -- Looking for CL_VERSION_1_1
     32    -- Looking for CL_VERSION_1_1 - not found
     33    -- Looking for CL_VERSION_1_0
     34    -- Looking for CL_VERSION_1_0 - not found
  >> 35    CMake Error at /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel
           7-broadwell/gcc-8.3.1/cmake-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt/
           share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (me
           ssage):
     36      Could NOT find OpenCL (missing: OpenCL_INCLUDE_DIR OpenCL_LIBRARY
     37      OpenCL_COMPILE_DEFINITIONS OpenCL_VERSION_STRING)
     38    Call Stack (most recent call first):
     39      /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/g
           cc-8.3.1/cmake-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt/share/cmake-3
           .26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_
           MESSAGE)
     40      cmake/FindOpenCL.cmake:117 (find_package_handle_standard_args)
     41      src/cl/CMakeLists.txt:23 (find_package)
...

$ spack debug report
* **Spack:** 0.20.0.dev0 (ba7e517571daf66eab13258ff962c4ae9e4a4c05)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo
```

**Comment by uphoffc** [comment]
Hi,

thanks for the review.

The package needs a SYCL-enabled compiler. Currently, only the oneapi C++ compiler is supported although I plan to support other SYCL implementations in the future. When writing the package I did not really find any good way to model the compiler dependency and I understood that such a feature is still WIP (#31357).

For now I added an InstallError when the compiler name != icpx or dpcpp, although I am not particularly happy with that. I would appreciate suggestions on how to improve modelling the compiler dependency.

Best regards,
Carsten

**Comment by tldahlgren** [comment]
> 
> For now I added an InstallError when the compiler name != icpx or dpcpp, although I am not particularly happy with that. I would appreciate suggestions on how to improve modelling the compiler dependency.

I understand.  It's nice that we can use `conflicts()` for specific compilers (https://spack.readthedocs.io/en/latest/packaging_guide.html#conflicts) but, unfortunately, not for this case.

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
