### PR TITLE
esmf: add v8.7.0

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to add new version (8.7.0) to ESMF package - https://github.com/esmf-org/esmf/releases/tag/v8.7.0

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants esmf@8.7.0%gcc@13 esmf@8.7.0%gcc@12 esmf@8.7.0%gcc@11 esmf@8.7.0%gcc@10
-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
esmf@8.7.0~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf~python+shared~xerces build_system=makefile esmf_comm=auto esmf_os=auto esmf_pio=auto patches=f63d405 snapshot=none

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
esmf@8.7.0~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf~python+shared~xerces build_system=makefile esmf_comm=auto esmf_os=auto esmf_pio=auto patches=f63d405 snapshot=none

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
esmf@8.7.0~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf~python+shared~xerces build_system=makefile esmf_comm=auto esmf_os=auto esmf_pio=auto patches=f63d405 snapshot=none

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
esmf@8.7.0~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf~python+shared~xerces build_system=makefile esmf_comm=auto esmf_os=auto esmf_pio=auto patches=f63d405 snapshot=none
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
/home/bkaindl/spack/build-quality-tools/build_pr_changes.py -c gcc@13,gcc@12,gcc@11,gcc@10 -a --yes
```

**Review by climbfuji — COMMENTED** [review]
Wohoo, we've been waiting for this release!

**Review by theurich — APPROVED** [review]
Checked sha256. Looks good!

**Comment by uturuncoglu** [comment]
@spackbot rebuild everything

**Comment by uturuncoglu** [comment]
@theurich Probably you have experience about it but do I need to do anything related with this PR? It seems that one of the required test is pending.

**Comment by theurich** [comment]
> @theurich Probably you have experience about it but do I need to do anything related with this PR? It seems that one of the required test is pending.

In my experience it just goes through eventually. Maybe a question for @bernhardkaindl ?

**Review by bernhardkaindl — APPROVED** [review]
@theurich:
> In my experience it just goes through eventually. Maybe a question for @bernhardkaindl ?

Correct: GitLab CI had an issue that caused a blacklog of 1-2 dozen packages. The issue was fixed and the situation is improving. GitLab CI was successfully finished 8 hours ago. Will merge now.

**Pull request merged**
