### PR TITLE
QA : make qa checking less painful

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by alalazo** [comment]
@tgamblin Do we need a finer control than this ?

**Comment by tgamblin** [comment]
@alalazo: I wish I could ignore E501 ONLY for lines starting with `r'^\s*url\s*='`.  I am not sure if we can get that level of control.

**Comment by alalazo** [comment]
@tgamblin I don't think we can do something like that out of the box. Don't know if we want to give a try at [this](https://github.com/aristiden7o/flake8-regex.git) or write something similar within spack...

**Comment by hegner** [comment]
@tgamblin @alalazo I believe you'd like to add `[E241] multiple spaces after ','` to the exceptions as well.

**Comment by alalazo** [comment]
@hegner Personally I don't mind having `E241` on, but I think style management is really up to @tgamblin

**Comment by adamjstewart** [comment]
I personally wouldn't like enforcing `[E241] multiple spaces after ','` as I'm a big fan of lining things up. It might be the only thing in PEP8 that I disagree with.

**Comment by tgamblin** [comment]
Let's disable E241 -- I'm not a stickler for it but I occasionally like things lined up.

**Comment by tgamblin** [comment]
@alalazo: what if we run this on package files before running `flake8`:

    perl -i~ -pe 's/^(\s*url\s*=.*)$/\1 # NOQA/' */package.py

That would auto-NOQA the URLs.

**Comment by alalazo** [comment]
@tgamblin I think the approach above is worth a try for URLs. I'll try to do my best to help people stuck with `flake8` checks in the meanwhile...

BTW, I set up this PR just because I thought it would have been clearer and faster to show case a code diff than to explain the modifications in words. If you think we don't need two separate configuration files, feel free to close this.

**Comment by tgamblin** [comment]
ok I just pushed this in a branch with the URL exemption: [epfl-scitas-differentiate_framework_from_packages](/LLNL/spack/tree/epfl-scitas-differentiate_framework_from_packages)

**Comment by alalazo** [comment]
@tgamblin Fine with me. Should I close this then?

Just a reminder : if I set everything correctly you should be able to push on `epfl-scitas` repository. Feel free to do it whenever you see it fit to speed-up iterations on a PR :smile:

**Comment by tgamblin** [comment]
@alalazo: don't close it; it's the same branch (this will merged when I push it)

**Comment by alalazo** [comment]
@tgamblin ok

**Comment by tgamblin** [comment]
ok pushing to EPFL seems to be working.  yay!

**Comment by tgamblin** [comment]
@alalazo: i think maintaining two files is kind of a pain, and i can't keep all the error codes straight.  I switched it to one file, ignored a few checks, and added some custom marking for `package.py` files so that the `url` lines are exempted.  There is also a script now that the user can just run:

```
    share/spack/qa/run-flake8
```

And there is only `/.flake8` for the input file to `flake8`.

**Comment by alalazo** [comment]
@tgamblin I may be missing the obvious, but I don't see the `share/spack/qa/run-flake8` in the list of changes...

**Comment by tgamblin** [comment]
Nope, looks like *I'm* missing the obvious.

**Comment by trws** [comment]
Why did this PR remove the yapf style?

**Comment by alalazo** [comment]
@trws I think it was removed because  we were using the default (pep8)

**Comment by trws** [comment]
Makes sense.  Do we have an autopep8 package in the works?

**Pull request merged**
