### PR TITLE
+ Provide fpic variant for netlib-lapack.

### PR DESCRIPTION
**Pull request by KineticTheory**
I saw some traffic on the mailing list about a more general 'fpic' option for all packages, but I'm uncertain of the status of this effort. So, for now, simply provide an '+fpic' variant for netlib-lapack.

### CODE REVIEW

**Comment by tgamblin** [comment]
@KineticTheory: we're trying to standardize on `+shared` instead of `+fpic` -- can you update the PR?

**Comment by alalazo** [comment]
@tgamblin `+shared` is already in netlib-lapack, I guess the main point is that `netlib-blas` has only `+fpic` and not `+shared`. Would #485 be good enough to deal with this and vendor blas?

**Comment by tgamblin** [comment]
@alalazo: Oh.  I see now we've got two options here.  Hm.  Typically `+shared` implies building with `pic`, but I know there are cases where people wan to link static libs into shared libs.  We really need to make a list of standard variants -- I think an orthogonal `fpic` is going to be rarely used, but I could be wrong.

@KineticTheory: do you want this option so you can link static, `fpic` libs into shared libs?  Or is this just intended to be used with `+shared`?  If it's the latter, I would just combine the two options into `+shared`...

**Comment by tgamblin** [comment]
@alalazo I'll take a look at #485

**Comment by KineticTheory** [comment]
@alalazo #485 would be a big improvement over the current split between netlib-blas and netlib-lapack.  Particularly, since building those at the same time produces a lapack-config.cmake that has import targets for both BLAS and LAPACK. I think I can convince the teams that I support to use shared libraries instead of static ones. If so, I can remove this PR and use #485.

@tgamblin As you guessed, my use case was static BLAS and static LAPACK linked into a shared library. This scenario is a frequent request from the teams that I support. Is there any downside to setting PIC for static libraries (besides larger libraries)? Since `static+PIC` is a common request that I hear, I would like to see options for:
- shared libraries (`+shared`)
- static libraries (`~shared`)
- static libraries built with PIC (`~shared+pic`)

I'll chat with a few members of my team on Monday to find out if they are okay using libblas.so and liblapack.so.

**Comment by eschnett** [comment]
On 32-bit x86, PIC code is slower than non-PIC code since there is one fewer integer register available (5 instead of 6).

I believe modern versions of Clang have a way to mitigate this for compute kernels (they can spill EBX), and so should modern versions of GCC, and thus I don't know whether this is still true any more. However, the belief that shared libraries are slower is by now probably entrenched in the HPC community.

**Comment by tgamblin** [comment]
There is also the scalable launch problem. See our [paper on spindle](http://apps.fz-juelich.de/jsc-pubsystem/aigaion/attachments/spindle.pdf-ba1b63cc5af29b55c262409671c1a7dd.pdf) for more on that.

And there are [LTO considerations](https://gcc.gnu.org/onlinedocs/gccint/WHOPR.html).  It would be nice if one day spack could automate some of the steps needed to get that working well, as it is usually a pain to set up.

**Comment by mathstuf** [comment]
Is 32-bit x86 a real target for spack users? Are there any 32-bit supercomputers? Development machines?

**Comment by eschnett** [comment]
Ubuntu still offers 32-bit downloads. We should continue to support this as well. If a package using BLAS requires a `+fpic` variant, it needs to specify so. The easiest is to build both a fast `libblas.a` and a shared `libblas.so`. If someone wants to explicitly build a static BLAS that can be put into another shared library, then that is a special case.

You mentioned that some people want this -- I didn't ask before: Why is this preferred? It seems to lead to code duplication, namely if another package also links against BLAS; you could end up with two copies of BLAS in this case.

**Comment by tgamblin** [comment]
> You mentioned that some people want this -- I didn't ask before: Why is this preferred? It seems to lead to code duplication, namely if another package also links against BLAS; you could end up with two copies of BLAS in this case.

@eschnett agreed, this actually goes against some recommendations of a lot of the solver teams; see the [xSDK Guide](https://docs.google.com/document/d/1DCx2Duijb0COESCuxwEEK1j0BPe2cTIJ-AjtJxt3290/edit#).  Item M12 has been a major source of contention for library interoperability.

**Comment by tgamblin** [comment]
I don't mind merging the variant -- we can debate why people use it later.  It's not commonly needed and defaults to `off` so I think this should be fine.

**Comment by KineticTheory** [comment]
I recommending that we reject PR #582.

I've spoken with several teams who use the static netlib LAPACK and BLAS libraries that I install.  There doesn't appear to be a reason that they prefer static libraries - only a historical precedent.  These libraries are linked into other dynamic libraries and then into an executable (thus the request for PIC).  

I asked the same teams if they had experienced performance issues when running dynamically linked executables across thousands of nodes.  On our current systems, this doesn't appear to be an issue. It is not clear to me if the hardware layer is doing something to mitigate the cost of loading the libraries or if the developers are unaware of this cost.

My plan is to release dynamic versions of LAPACK and BLAS.  Thank you for the insightful comments related to this topic.

**Comment by KineticTheory** [comment]
@tgamblin I think I am moving too slowly for you.  I just noticed that you already merged PR #582. This variant may still be useful for me.  Thank you.

**Pull request merged**
