### PR TITLE
petsc: update hypre dependency wrt 2.18.2 -> 2.19.0 API change

### LINKED ISSUE #17974: Build fail: petsc on RHEL 7, Ubuntu 18.04 (x86_64 and ppc64le)
`petsc` build is failing using `spack@develop` (10-Aug, 1398038beead1a1532fc337165e2b6bf9d58c284) on:
* `Ubuntu 18.04` `x86_64 + ppc64le` `%gcc@7.5.0`
* `RHEL 7` `x86_64 + ppc64le` `%gcc@8.3.1`

Concrete spec for `petsc` on RHEL7-x86_64: [petsc-stemyz.yml.txt](https://github.com/spack/spack/files/5052331/petsc-stemyz.yml.txt)
Build log: [petsc-build-out.txt](https://github.com/spack/spack/files/5052364/petsc-build-out.txt)

**RHEL7 x86_64 Error**
```
$> spack install -f ./petsc-stemyz.yml
...
==> Installing petsc
==> petsc: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.7.8-6em5koj4zvl5rv4gu77f2kcqjvtpiyhx/bin/python3.7' 'configure' '--prefix=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' 'CFLAGS=' 'FFLAGS=' 'CXXFLAGS=' '--with-cc=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/mpich-3.2.1-sy6nknikubw4oimdegcslfqd5yahd5cn/bin/mpicc' '--with-cxx=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/mpich-3.2.1-sy6nknikubw4oimdegcslfqd5yahd5cn/bin/mpic++' '--with-fc=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/mpich-3.2.1-sy6nknikubw4oimdegcslfqd5yahd5cn/bin/mpif90' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-64-bit-indices=0' 'COPTFLAGS=' 'FOPTFLAGS=' 'CXXOPTFLAGS=' '--with-blas-lapack-lib=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/openblas-0.3.10-uh6r2aprc43b3mm24nwumzkvmcxi6tlz/lib/libopenblas.so' '--with-x=0' '--with-clanguage=C' '--with-scalapack=0' '--with-cuda=0' '--with-metis=1' '--with-metis-dir=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/metis-5.1.0-7rcixsk24ch3w2oewcrnbq6xbrkgrkpz' '--with-hypre=1' '--with-hypre-dir=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/hypre-2.19.0-7amcokfszpiykyyas2wc5ejqthmhmjp4' '--with-parmetis=1' '--with-parmetis-dir=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/parmetis-4.0.3-tssafa2c6pu7aovphwaobwgbyhqhsccs' '--with-mumps=0' '--with-trilinos=0' '--with-fftw=0' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=0' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-libjpeg=0' '--with-cxx-dialect=C++11' '--with-superlu_dist-include=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/superlu-dist-6.3.0-rtbtondidwhh7ic35ldmoxj5t3kubmwr/include' '--with-superlu_dist-lib=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/superlu-dist-6.3.0-rtbtondidwhh7ic35ldmoxj5t3kubmwr/lib/libsuperlu_dist.a' '--with-superlu_dist=1' '--with-suitesparse=0' '--with-hdf5-include=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/hdf5-1.10.6-oa6ixwl3s2ayhgmhk3wkmo2rvt43aret/include' '--with-hdf5-lib=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/hdf5-1.10.6-oa6ixwl3s2ayhgmhk3wkmo2rvt43aret/lib/libhdf5.so' '--with-hdf5=1' '--with-zlib-include=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/zlib-1.2.11-kzcdykxiwmefakdug4fnprjxe4s4g6mj/include' '--with-zlib-lib=/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/zlib-1.2.11-kzcdykxiwmefakdug4fnprjxe4s4g6mj/lib/libz.so' '--with-zlib=1'

2 warnings found in build log:
     19     TESTING: setExternalPackagesDir from PETSc.options.externalpackagesdir(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/PE
            TSc/options/externalpackagesdir.py:15)
     20     TESTING: cleanExternalpackagesDir from PETSc.options.externalpackagesdir(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/
            PETSc/options/externalpackagesdir.py:22)
     21     TESTING: configureCLanguage from PETSc.options.languages(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/PETSc/options/la
            nguages.py:27)
     22     TESTING: printEnvVariables from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/se
            tCompilers.py:1725)
     23     TESTING: resetEnvCompilers from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/se
            tCompilers.py:1732)
     24                   ===============================================================================
  >> 25     ***** WARNING: F77 (set to /spack/lib/spack/env/gcc/gfortran) found in environment variables - ignoring
     26                          use ./configure F77=$F77 if you really want to use that value ******
     27                   ===============================================================================
     28
     29     TESTING: checkEnvCompilers from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/se
            tCompilers.py:1762)
     30     TESTING: checkMPICompilerOverride from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/co
            nfig/setCompilers.py:1695)
     31     TESTING: requireMpiLdPath from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/set
            Compilers.py:1716)

     ...

     215    TESTING: configurePrecision from PETSc.options.scalarTypes(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/PETSc/options/
            scalarTypes.py:81)
     216    TESTING: configureMkdir from config.programs(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/programs.
            py:22)
     217    TESTING: configureAutoreconf from config.programs(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/prog
            rams.py:44)
     218    TESTING: configurePrograms from config.programs(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/progra
            ms.py:71)
     219    TESTING: configureMake from config.packages.make(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/packa
            ges/make.py:87)
     220                    ===============================================================================
  >> 221    ***** WARNING: You have an older version of Gnu make, it will work,
     222                          but may not support all the parallel testing options. You can install the
     223                          latest Gnu make with your package manager, such as brew or macports, or use
     224                          the --download-make option to get the latest Gnu make *****
     225                    ===============================================================================
     226
     227    TESTING: setupGNUMake from config.packages.make(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ryx455hkhpztnyinbg6kp2anxr2owzaf/spack-src/config/BuildSystem/config/packag
            es/make.py:121)
```

@balay @jedbrown @BarrySmith @scottwittenburg @shahzebsiddiqui

### PR DESCRIPTION
**Pull request by balay**
Ref: #17809

### CODE REVIEW

**Comment by eugeneswalker** [comment]
I am testing now in my pipelines, will report results back ASAP. Thank you for quick fix!

**Comment by eugeneswalker** [comment]
This resolved `petsc` build issues in all cases EXCEPT `CentOS 8` and `RHEL 8` (fails on both x86_64 and ppc64le).

Works:
* CentOS 7
* RHEL 7
* Ubuntu 18.04
* Ubuntu 20.04

Doesn't work:
* CentOS 8
* RHEL 8

Do you have an opinion on how to proceed? Should I get the failure logs and put them up here, try to resolve that before we merge this, or should we merge, and I'll create issues for the remaining issues after the fact?

**Comment by balay** [comment]
> Do you have an opinion on how to proceed? Should I get the failure logs and put them up here, try to resolve that before we merge this, or should we merge, and I'll create issues for the remaining issues after the fact?

Can you provide the logs? Then we can see if its related to this issue/MR or something else..

**Comment by balay** [comment]
@eugeneswalker BTW: If mfem is also in the install package list - likely the issue is:

https://github.com/spack/spack/commit/9979aa28ce8fc31dd8730eb2bc68d995a10261b6#commitcomment-41346237

**Comment by eugeneswalker** [comment]
> > Do you have an opinion on how to proceed? Should I get the failure logs and put them up here, try to resolve that before we merge this, or should we merge, and I'll create issues for the remaining issues after the fact?
> 
> Can you provide the logs? Then we can see if its related to this issue/MR or something else..

For `RHEL 8` on `x86_64`:

Concretized spec: [petsc-xta2sw.yml.txt](https://github.com/spack/spack/files/5052934/petsc-xta2sw.yml.txt)
Full build log: [petsc-build-out.txt](https://github.com/spack/spack/files/5052939/petsc-build-out.txt)

Concretized spec excerpt:
```
spec:
- petsc:
    version: 3.13.4
    arch:
      platform: linux
      platform_os: rhel8
      target: x86_64
    compiler:
      name: gcc
      version: 8.3.1
    namespace: builtin
    parameters:
      X: false
      batch: false
      cgns: false
      clanguage: C
      complex: false
      cuda: false
      debug: false
      double: true
      exodusii: false
      fftw: false
      giflib: false
      hdf5: true
      hypre: true
      int64: false
      jpeg: false
      knl: false
      libpng: false
      libyaml: false
      memkind: false
      metis: true
      moab: false
      mpfr: false
      mpi: true
      mumps: false
      p4est: false
      random123: false
      saws: false
      shared: true
      suite-sparse: false
      superlu-dist: true
      trilinos: false
      valgrind: false
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
```

I think the culprit is this, from the full build log:
```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Could not locate diff executable
*******************************************************************************
```

So looks like it needs a dependency on `diffutils` ? In a normal, full system environment you wouldn't see this, but my pipelines runs in minimal docker containers, and I guess the rhel8 and centos8 base images don't come with diffutils installed via system package manager.

Spack install output:
```
$> spack install -f petsc-xta2sw.yml
...
==> Installing petsc
==> petsc: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/python-3.7.8-ib4y5lyeqw6pcsomqgwqir5ygln73zls/bin/python3.7' 'configure' '--prefix=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' 'CFLAGS=' 'FFLAGS=' 'CXXFLAGS=' '--with-cc=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/mpich-3.2.1-6jdsolvmzeoimvepzndjv5m3d3fh2r7v/bin/mpicc' '--with-cxx=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/mpich-3.2.1-6jdsolvmzeoimvepzndjv5m3d3fh2r7v/bin/mpic++' '--with-fc=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/mpich-3.2.1-6jdsolvmzeoimvepzndjv5m3d3fh2r7v/bin/mpif90' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-64-bit-indices=0' 'COPTFLAGS=' 'FOPTFLAGS=' 'CXXOPTFLAGS=' '--with-blas-lapack-lib=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/openblas-0.3.10-yiwdmf4jg2avyjcvsmi4buh773dfdeci/lib/libopenblas.so' '--with-x=0' '--with-clanguage=C' '--with-scalapack=0' '--with-cuda=0' '--with-metis=1' '--with-metis-dir=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/metis-5.1.0-ahuci2nwesonop73arnq5uzvsyxnwsy4' '--with-hypre=1' '--with-hypre-dir=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/hypre-2.18.2-3houaqkzmrpqfita2lhruwzxha5dyc74' '--with-parmetis=1' '--with-parmetis-dir=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/parmetis-4.0.3-gvhcnqhhjedv4d36pjvk7fyxqe7zmafj' '--with-mumps=0' '--with-trilinos=0' '--with-fftw=0' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=0' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-libjpeg=0' '--with-cxx-dialect=C++11' '--with-superlu_dist-include=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/superlu-dist-6.3.0-3xf7my63lxzum3zdviippa637ar4ehag/include' '--with-superlu_dist-lib=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/superlu-dist-6.3.0-3xf7my63lxzum3zdviippa637ar4ehag/lib/libsuperlu_dist.a' '--with-superlu_dist=1' '--with-suitesparse=0' '--with-hdf5-include=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/hdf5-1.10.6-aovrp4fnlyimkdlhll3kfy27tc7lqd6y/include' '--with-hdf5-lib=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/hdf5-1.10.6-aovrp4fnlyimkdlhll3kfy27tc7lqd6y/lib/libhdf5.so' '--with-hdf5=1' '--with-zlib-include=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/zlib-1.2.11-xqjeqtupcfqqqlaw5ehjlfjjly7zoe3b/include' '--with-zlib-lib=/spack/opt/spack/linux-rhel8-x86_64/gcc-8.3.1/zlib-1.2.11-xqjeqtupcfqqqlaw5ehjlfjjly7zoe3b/lib/libz.so' '--with-zlib=1'

1 warning found in build log:
     19    TESTING: setExternalPackagesDir from PETSc.options.externalpackagesdir(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/PET
           Sc/options/externalpackagesdir.py:15)
     20    TESTING: cleanExternalpackagesDir from PETSc.options.externalpackagesdir(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/P
           ETSc/options/externalpackagesdir.py:22)
     21    TESTING: configureCLanguage from PETSc.options.languages(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/PETSc/options/lan
           guages.py:27)
     22    TESTING: printEnvVariables from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/BuildSystem/config/set
           Compilers.py:1725)
     23    TESTING: resetEnvCompilers from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/BuildSystem/config/set
           Compilers.py:1732)
     24                  ===============================================================================
  >> 25    ***** WARNING: F77 (set to /spack/lib/spack/env/gcc/gfortran) found in environment variables - ignoring
     26                         use ./configure F77=$F77 if you really want to use that value ******
     27                  ===============================================================================
     28
     29    TESTING: checkEnvCompilers from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/BuildSystem/config/set
           Compilers.py:1762)
     30    TESTING: checkMPICompilerOverride from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/BuildSystem/con
           fig/setCompilers.py:1695)
     31    TESTING: requireMpiLdPath from config.setCompilers(/tmp/root/spack-stage/spack-stage-petsc-3.13.4-ltjeo63hjjikv7uyo6ljcabhuiv3qzhx/spack-src/config/BuildSystem/config/setC
           ompilers.py:1716)
```

**Comment by eugeneswalker** [comment]
> I think the culprit is this, from the full build log:
> 
> ```
> *******************************************************************************
>          UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
> -------------------------------------------------------------------------------
> Could not locate diff executable
> *******************************************************************************
> ```
> 
> So looks like it needs a dependency on `diffutils` ? In a normal, full system environment you wouldn't see this, but my pipelines runs in minimal docker containers, and I guess the rhel8 and centos8 base images don't come with diffutils installed via system package manager.

I can confirm, if I install `diffutils` via system package manager, `petsc` builds fine using this PR. This should probably be an explicit dependency. What do you think? Maybe we submit this PR, then I follow up with a PR to add `depends_on('diffutils')` ?

**Review by eugeneswalker — APPROVED** [review]

**Comment by balay** [comment]
> Maybe we submit this PR, then I follow up with a PR to add depends_on('diffutils') ?

yes. Thanks!

**Pull request merged**
