### PR TITLE
Kokkos Kernels: updating the package for release 3.6.00

### PR DESCRIPTION
**Pull request by lucbv**
This reflects the release of Kokkos and Kokkos Kernels 3.6.00
To be merged this requires PR #30315

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed sha256.

**Review by alalazo — CHANGES_REQUESTED** [review]
```
PKG-DIRECTIVES: 1 issue found
1. kokkos-kernels: dependency on kokkos@3.6.00 cannot be satisfied by known versions of kokkos
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/kokkos-kernels/package.py
    known versions of kokkos are master, develop, 3.5.00, 3.4.01, 3.4.00, 3.3.01, 3.3.00, 3.2.01, 3.2.00, 3.1.01, 3.1.00, 3.0.00
```

**Comment by lucbv** [comment]
@alalazo now that the Kokkos PR has merged this works just fine : )
Would you mind removing your change request.

**Review by brian-kelley — APPROVED** [review]

**Comment by lucbv** [comment]
@alalazo can you review this again

**Comment by lucbv** [comment]
@alalazo @tldahlgren
What is blocking the PR at this point?
The associated PR in Kokkos has been merged and I rebased on top of develop to include the relevant changes (I thought the github framework would do that automatically?).
All the tests are passing fine.

**Review by alalazo — APPROVED** [review]

**Comment by lucbv** [comment]
Thanks for looking at this @alalazo

**Pull request merged**
