### PR TITLE
qhull: fix compilation with Intel 17.02

### PR DESCRIPTION
**Pull request by alalazo**
See issue [here](https://github.com/qhull/qhull/issues/24)

### CODE REVIEW

**Comment by alalazo** [comment]
@wscullin Can you check and confirm that this solves the issue you were noticing when building `qhull`?

**Comment by adamjstewart** [comment]
@ssergien Did you mention that you were also having trouble compiling `qhull` with `%intel`? Can you try out this PR?

**Comment by alalazo** [comment]
Just wanted to mention that what they do here without the patch is really broken. If the compiler is Intel they end up doing:
```cpp
extern "C" {
template <typename T>
inline void qhullUnused(T &x) { (void)x; } 
#  define QHULL_UNUSED(x) qhullUnused(x);
}
```
and clearly you can't have templates in a C linkage block. Also, this function exist for the sole purpose of tricking the compiler not to emit an "unused variable" warning...

**Comment by alalazo** [comment]
@davydden @adamjstewart Do you have some time to test that `qhull` wasn't working before, but works with this patch?

**Comment by davydden** [comment]
I am traveling, unfortunately can't test anything now

**Comment by alalazo** [comment]
> Confirmed that qhull@2015.2 %intel@17.0.2 fails to build in develop but works with this patch. Did you submit this patch to the developers?

@adamjstewart I'll do that aap

**Comment by alalazo** [comment]
@adamjstewart Fine to merge this then?

**Comment by adamjstewart** [comment]
We can merge this for now. If the developers come back with a "better" solution, we can switch the patch to that.

**Comment by alalazo** [comment]
Update: this issue was solved upstream by [this PR](https://github.com/qhull/qhull/issues/8) which fixes the linkage declarations in the whole code-base. Nobody cared to make a new release though.

**Comment by adamjstewart** [comment]
It would probably be best to replace your patch with this one.

**Comment by alalazo** [comment]
I pinged @qhull in the issue upstream. Let's see if they are releasing a new version soon. Otherwise I'll prepare a patch with the PR above.

**Pull request merged**
