### PR TITLE
Add missing doc variant to fenics package

### LINKED ISSUE #4472: fenics doesn't install on Ubuntu 16
Would love to get this working but I keep getting the following super ambiguous error

[repos]$ spack install fenics @2016.2.0
==> Error: 'doc'
[repos]$ spack install fenics @2016.1.0
==> Error: 'doc'
[repos]$ spack install fenics @2017.1.0
==> Error: 'doc'
[repos]$ spack install fenics @1.6.0
==> Error: 'doc'
[repos]$ spack install fenics
==> Error: 'doc'

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #4472.

@mpilosov Can you test this out? The problem was that one of the optional dependencies (sphinx) depended on whether or not the `+doc` variant was on, but there was no `+doc` variant! As far as I can tell, it looks like this variant was always missing. I'm not sure why it didn't raise an error message before. Possibly related to @alalazo's recent work on multi-valued variants. I agree the error message could be more helpful though. I don't know how to fix that one but @alalazo might.

While I was at it I made a few unrelated changes. Converted `fenics` to `CMakePackage`. Also fixed a couple deptypes. I can't imagine that `eigen` is only a build dependency or `cmake` is a run-time dependency, but correct me if I'm wrong. Also separated the Python component installation into 2 phases. I think this makes much more logical sense now.

### CODE REVIEW

**Comment by mpilosov** [comment]
hm. pulled your branch and while I didn't get the doc error, I wasn't able to figure out the proper syntax to resolve the following (sorry, very new to spack, but if I can get this particular thing resolved, I know a few people who would be very interested so I'm doing some exploration). 

==> Error: Multiple providers found for 'lapack': ['intel-parallel-studio@professional.2017.3%gcc@5.4.0~all+daal~ilp64+ipp+mkl+mpi~newdtags~openmp+rpath+shared+tools arch=linux-ubuntu16-x86_64', 'openblas@0.2.19%gcc@5.4.0~openmp+pic+shared arch=linux-ubuntu16-x86_64']

**Comment by adamjstewart** [comment]
Hmm, never seen that bug before. @alalazo, @davydden?

**Comment by davydden** [comment]
It's this bug, introduced/discovered with multi valued variants https://github.com/LLNL/spack/issues/4107

**Comment by adamjstewart** [comment]
> very new to spack, but if I can get this particular thing resolved, I know a few people who would be very interested so I'm doing some exploration

We should really get this bug fixed, we're scaring off new users 😛 

@tgamblin Do you have any time to track this one down?

**Comment by davydden** [comment]
> We should really get this bug fixed, we're scaring off new users 😛

no joke we do... ;-( i was introducing a friend of mine to Spack and he hit this issue and asked me what this is... IMO it should be fixed ASAP.

**Comment by mpilosov** [comment]
@adamjstewart quite the contrary. the activity and dedication to getting this fixed in a timely manner is really impressive. please give me a mention when the changes are ready to pull. 

You have no idea how difficult fenics has been to download (I have a hashdist version but want it installed with conda instead), so the prospect of doing it easily is well worth the wait. I know quite a few people who'd love this sort of ease of installation as well for this particular package.

If I can add a pair of packages as well, this is going to become my research team's go-to solution for new users of our software. Y'all are working on a much needed product in the scientific computing community.

**Comment by davydden** [comment]
> give me a mention when the changes are ready to pull.

there is a workaround to this bug -- you need to explicitly specify MPI and Blas from the command line,  i.e. `spack install fenics+mpi ^openmpi ^openblas`. 

> If I can add a pair of packages as well, this is going to become my research team's go-to solution for new users of our software.

that is always welcome. Just do `spack create path-to-tarbal` and you will get a good starting point. Have a look at http://spack.readthedocs.io/en/latest/packaging_guide.html for more info.

**Comment by mpilosov** [comment]
the openblas flag complained at me. removed it, ran into the same issue as issue #3305 

re-ran it with `spack install fenics+trilinos+mpi ^trilinos@12.8.1 ^openpmi` 

and got the same error as in the aforementioned issue, but I think on a different line. 

==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
/home/mpilosov/Dropbox/Coding/repos/spack/lib/spack/spack/build_systems/cmake.py:154, in build:
     151      def build(self, spec, prefix):
     152          """Make the build targets"""
     153          with working_dir(self.build_directory):
  >> 154              inspect.getmodule(self).make(*self.build_targets)

what am I doing wrong?

**Comment by davydden** [comment]
this looks like a build error. you need to check logs to see what's going on.

**Pull request merged**
