### PR TITLE
paraview: add cdi support

### PR DESCRIPTION
**Pull request by albestro**
Create new (basic) package for CDI and add variant to Paraview.

### CODE REVIEW

**Comment by albestro** [comment]
@spackbot fix style

**Comment by albestro** [comment]
@kwryankrattiger do you think this PR needs anything else?

**Comment by albestro** [comment]
@kwryankrattiger @vicentebolea @danlipsa can you have a look, please?

**Comment by kwryankrattiger** [comment]
I am going to approve this since I don't think the issues I have with adding this are necessarily issues to be resolved here.

@vicentebolea @danlipsa I think we need to find a better way of representing paraview features that does not entail adding a new variant for every feature. There should be some UX abstraction for the package, otherwise the spec is going to become unreadable very quickly.

**Comment by vicentebolea** [comment]
@kwryankrattiger I agree, should we follow the pattern of full/lite package as we do in some linux distros?

**Review by kwryankrattiger — APPROVED** [review]

**Review by msimberg — APPROVED** [review]

**Pull request merged**
