### PR TITLE
openmpi : added variants

### PR DESCRIPTION
**Pull request by alalazo**
##### Modifications
- [x] added variants (mainly related to fabrics, schedulers and pms)

### CODE REVIEW

**Comment by alalazo** [comment]
@adamjstewart @davidbeckingsale Are these changes fine with you?

**Comment by davidbeckingsale** [comment]
Looks okay to me! 😊

**Comment by adamjstewart** [comment]
Looks good to me too!

**Comment by luigi-calori** [comment]
I' ve merged and build openmpi with gcc, no problems.
I have problems instead with intel compiler, the compilation seems ok but then when used with other dependent packages like parmetis, runtime errors occurs.
Looking at how it has been built on my system, seems that hwloc is not required and maybe --disable-dlopen instead. 
Is it worthwhile to add other variants to this PR ( to be used with intel compiler ) or better to submit another PR or wait for merge?

**Comment by trws** [comment]
Looks like this needs a rebase.  Also, I'd make the "--with-pmi" the default, is there any good reason not to have support for being launched by the standard interface? It doesn't add any dependencies.

**Comment by alalazo** [comment]
@trws PR rebased. I didn't change the default for `+pmi` to avoid unexpected rebuilds for people who have already an `openmpi` installed.

**Comment by alalazo** [comment]
@trws @tgamblin re-rebased :smile: Maybe due to the amount of merging commits, this is better squash merged...

**Comment by trws** [comment]
Fair enough.  I'm sorry to ping back on this one more time, but when the sqlite variant is included, shouldn't it `depends_on` sqlite?

**Comment by adamjstewart** [comment]
@alalazo: I wouldn't worry much about changing the defaults and causing unexpected rebuilds. Everyone will have to re-install OpenMPI anyway since new variants were added.

@trws: It looks like sqlite3 comes with the package. You can't install it separately since OpenMPI doesn't allow you to point to an external build path. So no need for `depends_on`

**Comment by trws** [comment]
@adamjstewart, you're right that it doesn't ask for a path, but it uses OMPI_CHECK_PACKAGE to find it in common library and header paths.  Since it looks for a system sqlite, and doesn't include one internally, I'd much rather have the depends_on than not.

**Comment by adamjstewart** [comment]
Oh interesting, didn't know that. So we would need to set that variable to the path? Or is depending on it and passing include flags sufficient?

**Comment by trws** [comment]
The way they're doing it, passing the include and link flags should be sufficient.  I think all it should take is adding the depends_on to get it working, but you could do a build that way and check with an ldd on the libmpi that pops out.

**Comment by alalazo** [comment]
@trws Good spot! I'll push the modifications tomorrow...

**Comment by adamjstewart** [comment]
@alalazo: #920 is actually requesting that PMI not be enabled by default. Thoughts?

**Comment by alalazo** [comment]
@adamjstewart For me this is up to @trws I am fine either ways (I'll use a more explicit spec in case)

**Comment by trws** [comment]
@adamjstewart: leave it off by default, I'll look into this and see if we can put in a generic PMI for them to build against by default.  OpenMPI makes the ridiculous assumption that building support for PMI means you must be using slurm, this is really frustrating behavior, but it's something we can work around.

**Comment by alalazo** [comment]
@trws @adamjstewart The PR looks fine to me now. Please tell me if you see anything else that needs to be added.

**Comment by tgamblin** [comment]
@trws: feel free to merge this if you think it's good.

**Comment by luigi-calori** [comment]
Did someone tested openmpi with Intel compiler? I had some problems on my site but maybe is better to first merge this PR  even if not working with Intel and then eventually do another PR. 

Would it make sense to somewhere ( maybe in the commit message) report the full spec that the PR has been tested with? 

I have the impression that this could help when testing / modifying for other compiler / platform to avoid regression

**Comment by adamjstewart** [comment]
Probably good to merge this PR and open another Issue/PR if problems with the Intel compiler still persist. If the PR _introduced_ problems with a compiler, that would be another story.

**Comment by trws** [comment]
Looks good.  Sounds like we need an issue for the intel compiler, and maybe another one to figure out a generic PMI for the MPIs to build against, but this is ready to go, merging.

**Comment by adamjstewart** [comment]
@luigi-calori: Have you seen #784? Is this similar to the problem you are having? I would really love more attention on that issue. It's the last Intel bug I have unsolved.

**Comment by luigi-calori** [comment]
@adamjstewart: What was happening on my side was  that OpenMPI with intel was apparently compiling fine but then it was unusable: linking with it was giving errors.
Did you tried to use your mpi with other things apart HDF5? I remember also problem with parmetis: the simple executable was not able to run.

I looked at how my colleagues were building it and I found differences, like  --disable-dlopen
and probably  not linking hwloc , see https://github.com/RemoteConnectionManager/spack/commit/19c5725a70ce430b0ad5cb5fff3d07deaf49a96f.  
We also have customized the PBS version to use,  so I tried to build a void package in order to be able to specify a custom path to pass to --with-tm=<path> option:
https://github.com/RemoteConnectionManager/spack/commit/19c5725a70ce430b0ad5cb5fff3d07deaf49a96f

As this stuff was colliding with this PR I decided to wait for this to be merged.
I have no idea of how  properly handle merging with a PR that is not merged yet. 
Any hint on how is the correct workflow for contributing to not jet merged PR would be greatly appreciated.

**Comment by adamjstewart** [comment]
I think you need push permission to contribute to a PR branch in someone else's repo. Anyway, since this PR is merged, let's move the discussion to #784. I didn't try building anything else with Intel OpenMPI, but it sounds like we're running into the same problem.

**Comment by luigi-calori** [comment]
Wow .. i missed the merge label... Tomorrow I' ll try to build openmpi and see how's going on and maybe I' ll open a new PR for Intel.
I am not yet using spack installed Intel but still relying on the compiler available as an environment module that I have to pre-load before compliling, Is fine for testing OpenMPI builds?

**Comment by adamjstewart** [comment]
Yes, that's fine. My problems also occur with an Intel compiler build outside of Spack.

**Pull request merged**
