### PR TITLE
Remove mesa18

### PR DESCRIPTION
**Pull request by kwryankrattiger**

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
Depends on: https://github.com/spack/spack/pull/27200

**Comment by trws** [comment]
Context? Is this a rocm-specific mesa package or..?

**Comment by kwryankrattiger** [comment]
> Context? Is this a rocm-specific mesa package or..?

Yes, this is the change that triggered the `libllvm` stuff.

**Review by adamjstewart — CHANGES_REQUESTED** [review]
Before removing a package, all versions should first be deprecated, then the package can be removed in the next Spack minor release: https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions

**Comment by chuckatkins** [comment]
After re-assessing the use-case for `mesa18` @kwryankrattiger and I determined that it does still need to be there for packages that need `python@2` and can't use the meson-based `mesa`.  However, most of the packages depending directly on `mesa` or `mesa18` can probably get by with instead using the `gl` and `glx` virtual packages.  We'll get into that and address in a new PR if appropriate.

**Comment by bernhardkaindl** [comment]
> After re-assessing the use-case for `mesa18` @kwryankrattiger and I determined that it does still need to be there for packages that need `python@2` and can't use the meson-based `mesa`. However, most of the packages depending directly on `mesa` or `mesa18` can probably get by with instead using the `gl` and `glx` virtual packages. We'll get into that and address in a new PR if appropriate.

`qt+webkit` is one of those: It depends on `python@2` because the`qtwebengine` which is based on the Google Chromium browser depends on it. There might be ways around this as well, but they are not in place or trivial so far.

See PR #27466 for the details. I'd prefer to not remove mesa18 at all. It is a separate package which is only used when needed, so it should hurt nobody to just keep it.

**Pull request closed without merging**
