### PR TITLE
AMD ROCm rccl - numa.h issue fix

### PR DESCRIPTION
**Pull request by arjun-raj-kuppala**

### CODE REVIEW

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@srekolam Can you give a quick look too and eventually ping me back to merge this?

**Comment by adamjstewart** [comment]
@haampie may also want to review

**Comment by haampie** [comment]
Hm yeah... if the compiler wrapper was in place for AMD's LLVM fork this wouldn't be necessary :man_shrugging:. This might work, but it's not very spack-esque. For work on getting the compiler wrapper in place see #18483.

**Comment by adamjstewart** [comment]
I'm pretty hesitant about #18483, at least in its current form, so let's merge this as is for now.

**Pull request merged**
