### PR TITLE
llvm: Fix ASM files treated as C

### LINKED ISSUE #20103: Installation issue: llvm fails to build assembler files with CMake 3.19.0
### Steps to reproduce the issue

```console
$ spack install llvm
...
-- Performing Test LIBCXX_SUPPORTS_WEXTRA_SEMI_FLAG
/spack-stage-dir/202269/root/spack-stage-llvm-11.0.0-stpte4xqkfbkbahzzcdnqw5pvxrjm6hs/spack-src/compiler-rt/lib/tsan/rtl/tsan_rtl_amd64.S:7:1: error: expected identifier or '(' before '.' token
 .section .text
 ^
/spack-stage-dir/202269/root/spack-stage-llvm-11.0.0-stpte4xqkfbkbahzzcdnqw5pvxrjm6hs/spack-src/compiler-rt/lib/tsan/rtl/tsan_rtl_amd64.S:16:5: error: invalid preprocessing directive #Save
   # Save scratch registers.
     ^~~~
/spack-stage-dir/202269/root/spack-stage-llvm-11.0.0-stpte4xqkfbkbahzzcdnqw5pvxrjm6hs/spack-src/compiler-rt/lib/tsan/rtl/tsan_rtl_amd64.S:44:5: error: invalid preprocessing directive #Align
   # Align stack frame.
     ^~~~~
...
make: *** [Makefile:174: all] Error 2
==> [2020-11-25-20:09:46.809565] Error: ProcessError: Command exited with status 2:
```

This is a combination of both an LLVM and CMake issue:

LLVM bug: https://bugs.llvm.org/show_bug.cgi?id=48234
LLVM fix: https://reviews.llvm.org/D86308
CMake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/21469
CMake fix: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5519

This is a placeholder issue that will be closed by the above referenced patches being applied

### PR DESCRIPTION
**Pull request by chuckatkins**
Fixes #20103

### CODE REVIEW

**Comment by chuckatkins** [comment]
This same issue is simultaneously addressed by #20104 but this fixes it for previous versions of CMake as well.

**Comment by haampie** [comment]
Instead of yet another LLVM patch, can't we just add a conflict with cmake 3.19.0 and wait for 3.19.1 to address this? In particular considering that multiple versions of LLVM are affected, I would opt for just adding

```
conflicts('^cmake@3.19.0')
```

The new concretizer doesn't automatically restrict the version to 3.18.4 currently, but I can only assume it will do so in the near future.

**Comment by haampie** [comment]
Since 3.19.1 was already released, I would definitely recommend adding a conflicts statement and drop the patch :)

**Review by opadron — APPROVED** [review]
Tested on our D&V SDK Pipeline and I confirmed that these changes do fix the build failure.

**Comment by chuckatkins** [comment]
Yep.  A conflict makes sense here since a newer CMake version that addresses it is already available.

**Review by haampie — APPROVED** [review]

**Review by alalazo — APPROVED** [review]

**Pull request merged**
