### PR TITLE
sherpa: add v3.0.0, remove deprecated @:2.2.10

### PR DESCRIPTION
**Pull request by jmcarcell**
3.0.0 now builds with CMake. I added options from the CMakeLists.txt for the existing variants, although there are more options that can be enabled or disabled. Building with the defaults seems to work fine:

``` 
sherpa@3.0.0%gcc@11.4.1+analysis~blackhat~cms+fastjet~gzip+hepmc2+hepmc3~hepmc3root~hztool~ipo+lhapdf~lhole~mpi~openloops+pythia~python~recola~rivet~root~ufo build_system=cmake build_type=Release cxxstd=11 generator=make libs=shared,static arch=linux-almalinux9-x86_64
```

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the version sha256 and that the variants used in cmake_args are listed.

Defer to @vvolkl and or @wdconinc as maintainers since this isn't a trivial change.

**Review by vvolkl — APPROVED** [review]
Nice, looks good to me. I'm running some tests and giving @wdconinc a chance to comment, but can be merged from my side.

**Comment by wdconinc** [comment]
(Outside of commentable context)

1. With disjoint build system version ranges:
https://github.com/spack/spack/blob/e76f550c67bf7ea27f121c11079c7df0f96b0f01/var/spack/repos/builtin/packages/sherpa/package.py#L32-L34
it now doesn't make sense anymore to have an `@3:` in `configure_args`:
https://github.com/spack/spack/blob/e76f550c67bf7ea27f121c11079c7df0f96b0f01/var/spack/repos/builtin/packages/sherpa/package.py#L162-L165

2. The variants `fastjet` and `hepmc2` are now unused and can be removed when @3: (fastjet is [vendored](https://gitlab.com/sherpa-team/sherpa/-/commit/fee8e87a350dd330fb899a248132975b235c8952) in @3:).

3. The autotools dependencies are not needed anymore when CMake is used:
https://github.com/spack/spack/blob/e76f550c67bf7ea27f121c11079c7df0f96b0f01/var/spack/repos/builtin/packages/sherpa/package.py#L79-L82

**Comment by vvolkl** [comment]
@jmcarcell Getting this error when installing sherpa@3.0.0 from scratch from your branch:
```
==> Installing sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus [51/51]
==> No binary for sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus found: installing from source
==> Fetching https://gitlab.com/sherpa-team/sherpa/-/archive/v3.0.0/sherpa-v3.0.0.tar.gz
==> Ran patch() for sherpa
==> sherpa: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/cmake-3.29.6-3ayato34vvceosl5iqtzwtciqpogwqb6/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_POLICY_DEFAULT_CMP0090:STRING=NEW' '-DCMAKE_FIND_USE_PACKAGE_REGISTRY:BOOL=OFF' '-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus/lib64;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/gcc-runtime-11.4.1-6uswpwvtrxj4brk2ithd77jbfp5snfyo/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/fastjet-3.4.2-gswjgfyvnemlwa4znzxtl3s2pglgleas/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc-2.06.11-jmrql6h3emcpig4j5iejvjif76nyzrwc/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/lhapdf-6.5.4-wrzk3ch536toot3smil2gxusn6wizzw4/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libtool-2.4.7-cp32j5p7jgcobob4fb3lbdsmxuoyatdt/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/zlib-ng-2.2.1-geyumkcxsvzdj4yt3t3wv242jzz4avm4/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libsigsegv-2.14-ctri7wbi7gpssc3cafxrudp5rhw7i5di/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/pythia6-6.4.28-4w2nw6utx6wax73s3bosar2nvrap2yz5/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/sqlite-3.43.2-wnirxlr46flcxzliahvxxnvouht3il4u/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/readline-8.2-djs5bpthgreb2lxe7birhprs4fhy5oeg/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/ncurses-6.5-ccyutvdmotq3xwbeaipf4vq3jead2mr3/lib;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc3-3.2.7-mx54up4fsdm6ojum7mzg72pr5vkujtb4/lib64;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libzip-1.10.1-wxdoz5eoknhjfttraz2r3nv4q4oo4g4e/lib64' '-DCMAKE_PREFIX_PATH:STRING=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/texinfo-7.1-rtccc5i3sjkp3h5nc57cfrunzmsbvmzd;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/pythia6-6.4.28-4w2nw6utx6wax73s3bosar2nvrap2yz5;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libzip-1.10.1-wxdoz5eoknhjfttraz2r3nv4q4oo4g4e;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/lhapdf-6.5.4-wrzk3ch536toot3smil2gxusn6wizzw4;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/sqlite-3.43.2-wnirxlr46flcxzliahvxxnvouht3il4u;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libtool-2.4.7-cp32j5p7jgcobob4fb3lbdsmxuoyatdt;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc3-3.2.7-mx54up4fsdm6ojum7mzg72pr5vkujtb4;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc-2.06.11-jmrql6h3emcpig4j5iejvjif76nyzrwc;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/fastjet-3.4.2-gswjgfyvnemlwa4znzxtl3s2pglgleas;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/cmake-3.29.6-3ayato34vvceosl5iqtzwtciqpogwqb6;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/automake-1.16.5-be62gaisgjvw4zvub45bz525v5nzoeh2;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/autoconf-2.72-5ptqeowoksyxdzr5b4uet3c7que6u2vp;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/zlib-ng-2.2.1-geyumkcxsvzdj4yt3t3wv242jzz4avm4;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/readline-8.2-djs5bpthgreb2lxe7birhprs4fhy5oeg;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/ncurses-6.5-ccyutvdmotq3xwbeaipf4vq3jead2mr3;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/m4-1.4.19-dwgsr5tyzcmnkevz4tv7docxejfbn245;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libsigsegv-2.14-ctri7wbi7gpssc3cafxrudp5rhw7i5di;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/gmake-4.4.1-xy5to265suvfcqgequat2lhqyztftsyr;/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/gcc-runtime-11.4.1-6uswpwvtrxj4brk2ithd77jbfp5snfyo' '-DSHERPA_ENABLE_ANALYSIS:BOOL=ON' '-DSHERPA_ENABLE_BLACKHAT:BOOL=OFF' '-DSHERPA_ENABLE_GZIP:BOOL=OFF' '-DSHERPA_ENABLE_HEPMC3:BOOL=ON' '-DSHERPA_ENABLE_HEPMC3_ROOT:BOOL=OFF' '-DSHERPA_ENABLE_LHAPDF:BOOL=ON' '-DSHERPA_ENABLE_LHOLE:BOOL=OFF' '-DSHERPA_ENABLE_MPI:BOOL=OFF' '-DSHERPA_ENABLE_OPENLOOPS:BOOL=OFF' '-DSHERPA_ENABLE_PYTHIA8:BOOL=ON' '-DSHERPA_ENABLE_PYTHON:BOOL=OFF' '-DSHERPA_ENABLE_RECOLA:BOOL=OFF' '-DSHERPA_ENABLE_RIVET:BOOL=OFF' '-DSHERPA_ENABLE_ROOT:BOOL=OFF' '-DSHERPA_ENABLE_UFO:BOOL=OFF' '/tmp/vavolkl/spack-stage/spack-stage-sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus/spack-src'

1 error found in build log:
     83    -- SHERPA: LibZip_VERSION=1.10.1 LibZip_LIBRARIES=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/libzip-1.10.1-wxdoz5eoknhjfttraz2r3nv4q4oo4g4e/lib64/libzip.so LibZip_INCLUDE_DIR=/var/tmp/spack/opt/spack/linu
           x-almalinux9-zen2/gcc-11.4.1/libzip-1.10.1-wxdoz5eoknhjfttraz2r3nv4q4oo4g4e/include
     84    -- Found LHAPDF: /var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/lhapdf-6.5.4-wrzk3ch536toot3smil2gxusn6wizzw4/include/../include (found version "6.5.4")
     85    -- SHERPA: LHAPDF_VERSION=6.5.4 LHAPDF_LIBRARIES=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/lhapdf-6.5.4-wrzk3ch536toot3smil2gxusn6wizzw4/lib/../lib/libLHAPDF.so LHAPDF_INCLUDE_DIRS=/var/tmp/spack/opt/spa
           ck/linux-almalinux9-zen2/gcc-11.4.1/lhapdf-6.5.4-wrzk3ch536toot3smil2gxusn6wizzw4/include/../include
     86    -- Performing Test Fortran_COMPILER_SUPPORTS_legacy
     87    -- Performing Test Fortran_COMPILER_SUPPORTS_legacy - Success
     88    -- SHERPA: HEPMC3_VERSION=3.02.07 HEPMC3_LIBRARIES=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc3-3.2.7-mx54up4fsdm6ojum7mzg72pr5vkujtb4/lib64/libHepMC3.so;/var/tmp/spack/opt/spack/linux-almalinux9-zen
           2/gcc-11.4.1/hepmc3-3.2.7-mx54up4fsdm6ojum7mzg72pr5vkujtb4/lib64/libHepMC3search.so  HEPMC3_INCLUDE_DIR=/var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/hepmc3-3.2.7-mx54up4fsdm6ojum7mzg72pr5vkujtb4/include
  >> 89    CMake Error at /var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/cmake-3.29.6-3ayato34vvceosl5iqtzwtciqpogwqb6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     90      Could NOT find Pythia8 (missing: PYTHIA8_INCLUDE_DIR PYTHIA8_LIBRARIES
     91      PYTHIA8_XMLDOC_DIR) (Required is at least version "8.220")
     92    Call Stack (most recent call first):
     93      /var/tmp/spack/opt/spack/linux-almalinux9-zen2/gcc-11.4.1/cmake-3.29.6-3ayato34vvceosl5iqtzwtciqpogwqb6/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
     94      cmake/Modules/FindPythia8.cmake:60 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
     95      CMakeLists.txt:742 (find_package)

See build log for details:
  /tmp/vavolkl/spack-stage/spack-stage-sherpa-3.0.0-aklcsjwf5fdgbhd7typj2a2pwcn6mnus/spack-build-out.txt
```

**Comment by vvolkl** [comment]
Still trying to install pythia6 for `@3:`  , needs to be updated to pythia8

**Review by vvolkl — CHANGES_REQUESTED** [review]
Update pythia dependency to pythia8 for sherpa 3:

**Review by vvolkl — DISMISSED** [review]

**Review by wdconinc — COMMENTED** [review]
There are still some issues with this. Please take a look at https://spack.readthedocs.io/en/latest/packaging_guide.html#multiple-build-systems

In particular, you should consider introducing a separate builder for each, e.g.
```python
class CMakeBuilder(spack.build_systems.cmake.CMakeBuilder):
    def cmake_args(self):
        return [
            self.define_from_variant("MY_FEATURE", "my_feature")
        ]

class AutotoolsBuilder(spack.build_systems.autotools.AutotoolsBuilder):
    def configure_args(self):
        return self.with_or_without("my-feature", variant="my_feature")
```
This avoids having the various argument functions in the same package class and puts them within their build system context.

**Comment by jmcarcell** [comment]
I applied the last comments and built it and installed it successfully.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
