### PR TITLE
Add test operation to tau package

### PR DESCRIPTION
**Pull request by wspear**
Copy over the general purpose mm matmult testcase. On test run build, execute (with mpi as needed) and process profile output.

### CODE REVIEW

**Comment by khuck** [comment]
@wspear - I am wondering if it would make sense to copy the `mm` directory to a different example directory, like `slack-test` or something like that.  Because the `mm` example sometimes gets committed with changes to the Makefile (or other files), it might break the test in the future.  Another thought would be to use the tests in the `tests` directory?  You'd have to set some environment variables for them to work, though.  But it depends on how robust you want this test to be - just a smoke test to confirm the build worked, or something to check a few corner cases?

**Comment by wspear** [comment]
@khuck This first run is a bare-bones sanity check. More feature specific tests might come eventually. I would rather stick with mm since it is also one of the primary tests for real-time development. Since it is actively used I think it is less subject to bitrot. I'm not sure how much attention the tests directory gets. I know some of the old tau validate stuff just doesn't work any more.

**Review by eugeneswalker — APPROVED** [review]

**Comment by tldahlgren** [comment]
> @wspear - I am wondering if it would make sense to copy the `mm` directory to a different example directory, like `slack-test` or something like that. Because the `mm` example sometimes gets committed with changes to the Makefile (or other files), it might break the test in the future. Another thought would be to use the tests in the `tests` directory? You'd have to set some environment variables for them to work, though. But it depends on how robust you want this test to be - just a smoke test to confirm the build worked, or something to check a few corner cases?

@khuck The goal of stand-alone tests is to be able to run the tests against the software days to months after it is installed. The intention is to use quick checks of functionality that can provide confidence the installed software still works.  Caching and using tests and examples from the software's repository -- that are taken at the same time as the software being installed -- is ideal.

There are plans for follow-on testing that, should the stand-alone tests pass, could be launched to perform more thorough testing that could include at scale.

We have more information on the capability in the docs: https://spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-or-smoke-tests.

**Comment by tldahlgren** [comment]
@khuck Any objections to this initial set of tests being merged into TAU?

**Comment by khuck** [comment]
> @khuck Any objections to this initial set of tests being merged into TAU?

No, no objections.  Carry on!

**Comment by shahzebsiddiqui** [comment]
@tldahlgren are we back porting these standalone tests to e4s branches like https://github.com/spack/spack/tree/e4s-21.05 and e4s-21.02 https://github.com/spack/spack/tree/e4s-21.02. 

If these changes are backported we could potentially use these for spack deployments that we have deployed. I think these should be done in sync with a spack release at one time so we are aware of when e4s tags have new updates so we can sync our facility deployment with the new tests.

**Pull request merged**
