### PR TITLE
libtheora: improved libpng dependency.

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Comment by RemiLacroix-IDRIS** [comment]
As far as I can tell libpng is only needed to build the examples. I can add a variant for this if you think it is useful.

**Review by alalazo — APPROVED** [review]

**Comment by Billae** [comment]
Hello,

I am a bit confused by this new version of the libtheora recipe:

I don't understand why fetching the patch is better than storing it in the spack directory, and why only one patch is fetched and not the other one ?

I also confronted with a new problem:
 I work on a offline machine and use spack mirrors to recreate the spack environment on my machine. Now that patch is fetched on internet, the recipe is not executable in my offline environment. Or maybe you have some tricks to solve this ?

I am new with the use of spack and you surely have some reasons that i have not seen. Could you please explain them to me ? Thanks a lot :)

Regards, 
Eloise

**Comment by RemiLacroix-IDRIS** [comment]
Hi,

> I don't understand why fetching the patch is better than storing it in the spack directory, and why only one patch is fetched and not the other one ?

That was not the main point of this PR. The `dont_use_png_sizeof.patch` was added while working on it and I didn't see the point of duplicating on official patch so I kept it as I originally wrote it. I don't think the other patch is part of the official libtheora repository (or was when added in Spack) so there is (was) nowhere it can be downloaded from.

But anyway, this PR mostly fixes the missing libpng dependency and incorrect condition to apply the `dont_use_png_sizeof` patch.

> I work on a offline machine and use spack mirrors to recreate the spack environment on my machine. Now that patch is fetched on internet, the recipe is not executable in my offline environment. Or maybe you have some tricks to solve this ?

Not sure about this, Spack devs should know.

Rémi

**Comment by Billae** [comment]
Thanks for your quick answer. 
I just discovered that spack also mirrored the patch, so all is fine=)

Regards,
Eloïse

**Pull request merged**
