### PR TITLE
Upgrade Portage to 3.0.0

### PR DESCRIPTION
**Pull request by raovgarimella**
Added new options and dependencies needed for 3.0.0 of Portage

### CODE REVIEW

**Comment by raovgarimella** [comment]
I know Spack doesn't yet have an official policy for deprecation and we are encouraged to keep old versions around but the break between version 1.2.2 (and 2.2.3 which is what most people are using) and 3.0.0 is so drastic that they are completely incompatible.

**Comment by alalazo** [comment]
@raovgarimella I think we have a sort of unofficial policy that if someone signs up to be a maintainer of a package and  considers correct to remove old versions, then it's fine to do so. In any case we'll redirect any request to restore old versions towards you :laughing: 

Would it be fine with you @adamjstewart ?

**Comment by raovgarimella** [comment]
Yes. I am the point person for any requests for old versions. Thank you

**Review by alalazo — CHANGES_REQUESTED** [review]
There are style issue, but otherwise this LGTM

**Review by alalazo — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
