### PR TITLE
Update git

### PR DESCRIPTION
**Pull request by mathstuf**
---
Cc: @timattox @adamjstewart

### CODE REVIEW

**Comment by adamjstewart** [comment]
Is there any reason we can't always build with Spack curl and expat? That would solve #817.

**Comment by mathstuf** [comment]
Well, curl is hard to skip (you're limited to local and git:// URLs…and git:// is getting rarer these days; I think GitHub has it turned off now). This branch forces the spack curl if you have +curl on. Expat is only needed when *pushing* to https URLs which might be able to be skipped for some use cases and if you need it, it forces spack's expat as well.

**Comment by adamjstewart** [comment]
I propose we remove the variants and always depend on Spack-built curl and expat.

**Comment by tgamblin** [comment]
I'm ok with this.  We can bring back system versions through discoverable externals when @mathstuf implements it.

**Comment by mathstuf** [comment]
Updated it to depend on curl and expat unconditionally

**Comment by adamjstewart** [comment]
Looks good to me!

**Comment by mathstuf** [comment]
And just squashed the commits down to get rid of the intermediate ones.

**Pull request merged**
