### PR TITLE
STRUMPACK: Add e4s testsuite-inspired smoke test

### PR DESCRIPTION
**Pull request by sshudler**
This PR represents a preliminary smoke test for the `strumpack` package and is intended to serve the following purposes:

1. leverage the current E4S test suite for the software; and
2. demonstrate to package maintainers how to start a Spack smoke test.

@pghysels these are the changes I mentioned in the meeting today.

### CODE REVIEW

**Comment by pghysels** [comment]
Thank you @sshudler for adding this test!

The test seems to work, I tried:
```
spack test run --log-file strumpack_test_log.txt --log-format junit strumpack
==> Spack test w2znvugacdjnuemnf5mbse3k5c3nxluf
==> Testing package strumpack-5.1.1-zcn3kmy
spack test results
==> Results for test suite 'w2znvugacdjnuemnf5mbse3k5c3nxluf':
==>   strumpack-5.1.1-zcn3kmy PASSED
```


However, when I look at the strumpack_test_log.txt output file, I see that the solver diverged.
`# relative error = ||x-x_exact||_F/||x_exact||_F = nan`
The same test runs correctly when I compile the code outside of spack. I will investigate further.

**Comment by tldahlgren** [comment]
> Thank you @sshudler for adding this test!
> 
> The test seems to work, I tried:
> 
> ```
> spack test run --log-file strumpack_test_log.txt --log-format junit strumpack
> ==> Spack test w2znvugacdjnuemnf5mbse3k5c3nxluf
> ==> Testing package strumpack-5.1.1-zcn3kmy
> spack test results
> ==> Results for test suite 'w2znvugacdjnuemnf5mbse3k5c3nxluf':
> ==>   strumpack-5.1.1-zcn3kmy PASSED
> ```
> 
> However, when I look at the strumpack_test_log.txt output file, I see that the solver diverged.
> `# relative error = ||x-x_exact||_F/||x_exact||_F = nan`
> The same test runs correctly when I compile the code outside of spack. I will investigate further.

The testing infrastructure (i.e., use of `self.run_test`) only checks, by default, that the return code from execution is `0`.  As written, the output, if any, from the command is not checked.

It is possible to provide one or more expected return codes and or outputs that can be checked to refine what it means for a given `run_test` execution to pass or fail.  (See the second-to-last paragraph under `Add Install Tests` at https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-install-tests.)  `RAJA` has examples of checking output from running multiple examples in the `_test_examples` method at https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/raja/package.py.

**Comment by tldahlgren** [comment]
@pghysels Do you want the @sshudler to modify this test since the result shows the solver diverged?

> > Thank you @sshudler for adding this test!
> > The test seems to work, I tried:
> > ```
> > spack test run --log-file strumpack_test_log.txt --log-format junit strumpack
> > ==> Spack test w2znvugacdjnuemnf5mbse3k5c3nxluf
> > ==> Testing package strumpack-5.1.1-zcn3kmy
> > spack test results
> > ==> Results for test suite 'w2znvugacdjnuemnf5mbse3k5c3nxluf':
> > ==>   strumpack-5.1.1-zcn3kmy PASSED
> > ```
> > 
> > 
> > However, when I look at the strumpack_test_log.txt output file, I see that the solver diverged.
> > `# relative error = ||x-x_exact||_F/||x_exact||_F = nan`

The test could be changed to check the output of this file too as an extra `run_test` after the first finishes IF that would be useful.

**Comment by tldahlgren** [comment]
Oops.  Wrong button.

**Comment by pghysels** [comment]
It might be better to run `test_sparse_seq` and `test_sparse_mpi` from the test folder, since they will not return `0` if the test failed.
As input you can use the small matrix in `examples/data/pde900.mtx`.
testPoisson2d is meant as an example for the user, and it doesn't check the convergence (but maybe it should).

I still need to figure out why the test fails.

**Comment by pghysels** [comment]
I tested a lot of configurations. It looks like the test produces wrong results if openblas was compiled without threading support. If openblas was compiled with pthreads, then it prints out many warnings:
`OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.                                                                                                                     
`

I think we need to add:

```
conflicts('^openblas@0.3.6: threads=none', when='+openmp', msg='STRUMPACK requires openblas to be build with OpenMP threading support')
conflicts('^openblas@0.3.6: threads=pthreads', when='+openmp', msg='STRUMPACK requires openblas to be build with OpenMP threading support')
```

Edit: added '"when='+openmp'"

**Comment by sshudler** [comment]
> It might be better to run `test_sparse_seq` and `test_sparse_mpi` from the test folder, since they will not return `0` if the test failed.
> As input you can use the small matrix in `examples/data/pde900.mtx`.
> testPoisson2d is meant as an example for the user, and it doesn't check the convergence (but maybe it should).
> 
> I still need to figure out why the test fails.

@pghysels this is a good suggestion - I switched the smoke test to use the `test_sparse_seq` and `test_sparse_mpi`

**Comment by sshudler** [comment]
> I tested a lot of configurations. It looks like the test produces wrong results if openblas was compiled without threading support. If openblas was compiled with pthreads, then it prints out many warnings:
> `OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option. `
> 
> I think we need to add:
> 
> ```
> conflicts('^openblas@0.3.6: threads=none', when='+openmp', msg='STRUMPACK requires openblas to be build with OpenMP threading support')
> conflicts('^openblas@0.3.6: threads=pthreads', when='+openmp', msg='STRUMPACK requires openblas to be build with OpenMP threading support')
> ```
> 
> Edit: added '"when='+openmp'"

@pghysels that's a good point as well, with this fix the test runs consistently now

**Comment by pghysels** [comment]
This looks good to me.

**Review by tldahlgren — APPROVED** [review]
LGTM too.

**Pull request merged**
