### PR TITLE
Remove references to gmake executable, only use make

### LINKED ISSUE #37241: External `gmake` package on macOS from homebrew provides only `gmake` executable, not `make`
### Steps to reproduce

When spack finds an external `gmake` package in a macOS homebrew installation, it wants to use that one but can’t find `/usr/local/bin/make` (because homebrew leaves it as `gmake`). Poking around in the spack code I see that the spack install of `gmake` creates a symlink from `gmake` to `make` after installation, but of course it doesn’t do that for external packages.

I noticed that the concretizer output for an older (December 2022) spack doesn’t contain a `gmake` package at all, assuming therefore that spack always called `make` under the assumption that whatever is in the search path works? Meanwhile, the current spack version makes `gmake` an explicit dependence but then trips over the non-existent in `/usr/local/bin/make`.

### Error message

Errors are therefore something like `/usr/local/bin/make - no such file or directory`

### Information on your system

```
* **Spack:** 0.20.0.dev0 (ce81f15e6f7390953e0035ada5c0399da0c4e44b)
* **Python:** 3.10.8
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Fixes https://github.com/spack/spack/issues/37241 by removing all references to the `gmake` executable - use `make` only.

### CODE REVIEW

**Review by haampie — APPROVED** [review]
This looks good to me

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
Failures on trilinos are known issues I've been told. Let's wait for those to be fixed and then merge this.

**Comment by climbfuji** [comment]
@haampie Gentle reminder to get this merged, if possible ... thanks very much!

**Comment by haampie** [comment]
@spackbot run pipeline

**Review by haampie — APPROVED** [review]

**Comment by climbfuji** [comment]
@haampie Any chance to merge this soon? I'll be on leave starting the end of May for several weeks. Thanks!

**Pull request merged**
