### PR TITLE
[WIP] Adding CUDA 12.2.0 support

### PR DESCRIPTION
**Pull request by fspiga**
Adding CUDA 12.2.0 support.

- [x] Check that current default (11.8) can be moved to 12.x.

### CODE REVIEW

**Comment by alalazo** [comment]
There seems to be a legit pipeline failure here: https://gitlab.spack.io/spack/spack/-/jobs/7645177

**Comment by fspiga** [comment]
I'll investigate locally, I see it is related to boost

**Comment by fspiga** [comment]
@alalazo is there a simple way to re-trigger the pipeline with CUDA `12.1.1` as default instead of `CUDA 12.2.0`?

**Comment by alalazo** [comment]
@fspiga I think you need to modify the `spack.yaml` of the pipeline

**Comment by alalazo** [comment]
Outdated by other PRs

**Pull request closed without merging**
