### PR TITLE
Calm "spack flake8"

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
There should be two blank lines in front of a class definition.

Error message:
[E302] expected 2 blank lines, found 0

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]

**Comment by alalazo** [comment]
Any clue why this wasn't caught on submission by CI, or locally by `spack flake8` (I submitted EnTT)?

**Comment by ChristianTackeGSI** [comment]
> Any clue why this wasn't caught on submission by CI, or locally by `spack flake8` (I submitted EnTT)?

No idea, really.
Maybe my local flake8 is too nitpicky?

(rebased, tests pass now)

**Comment by alalazo** [comment]
Can you post:
```
$ flake8 --version
3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.5 on Linux
```
?

**Review by alalazo — CHANGES_REQUESTED** [review]
I just updated to:
```console
$ flake8 --version
3.8.4 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.5 on Linux
```
and modified `entt`. This is what I get:
```console
$ spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
  var/spack/repos/builtin/packages/entt/package.py
=======================================================

Flake8 checks were clean.
```
That's a minor thing, but I'd like to understand if this is necessary before merging.

**Comment by ChristianTackeGSI** [comment]
Sure:
```console
$ flake8 --version
3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.3 on Linux
```
(Debian-10 default install)

> @alalazo requested changes

Okay, I am missing something: What should I change?

**Comment by alalazo** [comment]
@ChristianTackeGSI Can you try updating your `flake8` version? After a quick look this seems a bug in `flake8` solved by https://github.com/PyCQA/pycodestyle/pull/919

**Comment by ChristianTackeGSI** [comment]
Okay, updated flake8 using virtualenv:
```console
3.8.4 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.7.3 on
Linux
```

With that applied, the changes in this PR are not strictly required.

That said, I'd still vote for consistent formatting.

**Comment by alalazo** [comment]
> That said, I'd still vote for consistent formatting.

I would close this instead. I don't see the point in starting to argue about whitespaces if `flake8` is not complaining about that. I'm really looking forward to when we could get rid of Python 2.6, so that we can start introducing the use of `black` - at which point everybody will be equally unsatisfied about formatting :laughing:

**Comment by ChristianTackeGSI** [comment]
Okay, in other phrasing: Do my changes hurt anyone?

(just looking at black…)

**Comment by adamjstewart** [comment]
I have no opinions, I could go either way. It would be good to support a wider range of flake8 versions, not just the latest. Even when we move to black, I imagine we'll still be using flake8 as well (black and flake8 control a very different subset of things).

**Comment by alalazo** [comment]
>  It would be good to support a wider range of flake8 versions

I would just close this. Reasons:
1. It's a bug in `flake8` that was resolved, so we would support a bug in a previous version of `flake8`. I see no reasons for that.
2. If we don't enforce that behavior there's no guarantee we'll be consistent in the future

> black and flake8 control a very different subset of things

This particular issue comes from `pycodestyle` which is, as far as I know, common ground for both.

**Pull request closed without merging**
