### PR TITLE
py-f90wrap: new version

### PR DESCRIPTION
**Pull request by myan-rarcellino-nnl**
Could not build on the develop branch without being more specific about numpy versions. numpy versions taken from oldest-supported-numpy repo

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you share the error message you were seeing? We shouldn't need to lock down to a specific version, a range of versions should work.

**Comment by myan-rarcellino-nnl** [comment]
> Can you share the error message you were seeing? We shouldn't need to lock down to a specific version, a range of versions should work.

My mistake. I dug into the logs some more and actually read some of the errors and seems like the system compiler, gcc v4.8.5, might be a little too old. I built with gcc 8, 9, and 10 instead and py-f90wrap was able to build with the latest numpy. I was only using gcc v4.8.5 to quickly test before submitting the PR so I am willing to depend on the later versions of gcc.

I attached the build log from the failing attempt with gcc v4.8.5
[spack-build-out.txt](https://github.com/spack/spack/files/8931674/spack-build-out.txt)

**Review by adamjstewart — APPROVED** [review]

**Comment by adamjstewart** [comment]
^ @rgommers some numpy build issues with GCC 4.8.5 that you might be interested in

**Comment by rgommers** [comment]
I _think_ 4.8.5 still works, but that GCC version <5.0 or 5.1 need `-std=c99` added for the build to not fail.

**Comment by rgommers** [comment]
The above I wrote from memory, and is consistent with the build error in the linked log:
```
error: 'for' loop initial declarations are only allowed in C99 mode
```

**Comment by adamjstewart** [comment]
We _should_ be adding that: https://github.com/spack/spack/blob/v0.18.0/var/spack/repos/builtin/packages/py-numpy/package.py#L156,L158

No idea why it wouldn't be working.

**Pull request merged**
