### PR TITLE
Remove readme and licence files from install prefix

### PR DESCRIPTION
**Pull request by haralmha**

### CODE REVIEW

**Comment by haampie** [comment]
Why? Did you read the license?

**Comment by vvolkl** [comment]
This is in order to fix file path conflicts when creating views.

@haralmha, I'd suggest to copy those files to `<prefix>/share/doc/keyutils/` instead.

**Comment by haampie** [comment]
Out of curiosity, how do you use views s.t. this merge conflict is triggered?

Seems like environment views simply ignore file conflicts. So you're using `spack view` then?

**Comment by haralmha** [comment]
@haampie we are creating and activating a new environment on a gitlab runner:
```
test-install-lcg-release-rolling:
    stage: installtest
    only:
      refs:
          - schedules # Only execute this on scheduled pipelines
    tags:
      - lcg-test-centos8 
    script:
        - git clone --depth 1 https://gitlab.cern.ch/sft/spack.git
        - source spack/share/spack/setup-env.sh
        - spack env create lcgrelease-installtest
        - spack env activate lcgrelease-installtest 
        - spack repo add .
        - spack add lcg-release
        - spack concretize
        - spack install
```
where lcg-release is a bundle package which depends on packages in the LCG stack. When changed the install prefix to be in a persistent directory (to not re-install things over and over for each run), we got this error:
```
==> Error: Package merge blocked by file: File blocks directory: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/owjslfkwyol7trarkpj3nopkuc4bgm4x/README
==> Updating view at /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/view
```
Which is the README file for keyutils. By the wat, why is there `._` in front of `view` and what is the hash of the view for?

**Comment by haampie** [comment]
Okay, confusing. Spack environments have a hard-coded `ignore_conflicts=True`

https://gitlab.cern.ch/sft/spack/-/blob/lcg-develop/lib/spack/spack/environment/environment.py#L453

So I would say you're hitting a bug here, somehow.

Can you run with `-d` for a stacktrace?

> why is there ._ in front of view and what is the hash of the view for?

It's a hash of the specs, so that for every set of specs you get a unique (modulo collisions) view directory.

**Comment by haralmha** [comment]
```
==> [2022-03-17-09:03:07.185270, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9-config to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/python3.9-config
==> [2022-03-17-09:03:07.186601, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9-config'
==> [2022-03-17-09:03:07.235447, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/python3.9-config [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.237368, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/2to3-3.9 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/2to3-3.9
==> [2022-03-17-09:03:07.238108, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/2to3-3.9'
==> [2022-03-17-09:03:07.275937, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/2to3-3.9 [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.276814, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pydoc3.9 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pydoc3.9
==> [2022-03-17-09:03:07.277573, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pydoc3.9'
==> [2022-03-17-09:03:07.313234, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pydoc3.9 [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.314877, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pip3.9 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pip3.9
==> [2022-03-17-09:03:07.315621, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pip3.9'
==> [2022-03-17-09:03:07.350448, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pip3.9 [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.351317, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9-gdb.py to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/python3.9-gdb.py
==> [2022-03-17-09:03:07.352260, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9-gdb.py'
==> [2022-03-17-09:03:07.390122, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/python3.9-gdb.py [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.393806, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pip3 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pip3
==> [2022-03-17-09:03:07.394768, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/pip3'
==> [2022-03-17-09:03:07.435147, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/pip3 [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.446885, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/idle3.9 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/idle3.9
==> [2022-03-17-09:03:07.447841, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/idle3.9'
==> [2022-03-17-09:03:07.489404, 3824611] FILTER FILE: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/idle3.9 [replacing "/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw"]
==> [2022-03-17-09:03:07.501448, 3824611] Copying /cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9 to /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/bin/python3.9
==> [2022-03-17-09:03:07.502501, 3824611] 'file' '-b' '-h' '/cvmfs/builds/linux-centos8-skylake_avx512/gcc-8.5.0/python-3.9.10-3cgnvhbwnzpwr55x54nraog6dnubsylw/bin/python3.9'
==> [2022-03-17-09:03:12.210097, 3824611] READ LOCK (database): /cvmfs/builds/.spack-db/lock[0:0] [Released at 09:03:12.210025] 
==> [2022-03-17-09:03:12.210435, 3824611] WRITE LOCK: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/transaction_lock[0:0] [Released at 09:03:12.210407] 
==> [2022-03-17-09:02:42.225453, 3824611] Updating view at /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/view
Traceback (most recent call last):
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/main.py", line 916, in main
    return _main(argv)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/main.py", line 871, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/main.py", line 899, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/main.py", line 556, in _invoke_command
    return_val = command(parser, args)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/cmd/concretize.py", line 42, in concretize
    env.write()
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/environment/environment.py", line 1849, in write
    self.regenerate_views()
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/environment/environment.py", line 1308, in regenerate_views
    view.regenerate(specs, self.roots())
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/environment/environment.py", line 524, in regenerate
    with_dependencies=False)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/filesystem_view.py", line 334, in add_specs
    if all(map(self.add_standalone, standalones)):
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/filesystem_view.py", line 388, in add_standalone
    self.merge(spec)
  File "/cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/lib/spack/spack/filesystem_view.py", line 415, in merge
    raise MergeConflictError(conflicts[0])
llnl.util.link_tree.MergeConflictError: Package merge blocked by file: File blocks directory: /cvmfs/gitlab-runner/VHY8orns/0/sft/sft-spack-repo/spack/var/spack/environments/lcgrelease-installtest/.spack-env/._view/55pbsasbcoich5whayvhkzreuxsewdev/README
```

**Comment by haampie** [comment]
@becker33 this is a bug right? environment views ignore file conflicts. any clue?

**Comment by alecbcs** [comment]
@haralmha @haampie is this PR still relevant or has this since been fixed for `keyutils`?

**Comment by alecbcs** [comment]
Closing with no response. @haralmha feel free to reopen if this is still something you want to work on.

**Pull request closed without merging**
