### PR TITLE
SWIG: new versions 4.1.x

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the new sha256.

**Comment by sethrj** [comment]
@spackbot rerun pipeline

**Comment by tldahlgren** [comment]
Pod scheduling issues for two stacks.

@spackbot run pipeline

**Review by bernhardkaindl — APPROVED** [review]
Built sensei with this (arm64-linux)

**Pull request merged**
