### PR TITLE
CI: Update Data Vis SDK image

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Supersedes #34224

CC: @eugeneswalker

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
@scottwittenburg I am also open to making this a rhel8 based image for a more diverse offering of binaries. @eugeneswalker could you point be at the Dockerfile for the e4s ubuntu image? Or do you have another variation that is rhel based.

**Review by eugeneswalker — APPROVED** [review]
Thank you!

**Comment by eugeneswalker** [comment]
> @scottwittenburg I am also open to making this a rhel8 based image for a more diverse offering of binaries. @eugeneswalker could you point be at the Dockerfile for the e4s ubuntu image? Or do you have another variation that is rhel based.

https://github.com/UO-OACISS/e4s/tree/master/docker-recipes/runner
https://github.com/UO-OACISS/e4s/tree/master/docker-recipes/runner/ubuntu20.04-x86_64

There is a RHEL8 recipe there as well. It is very similar to our Ubuntu 20 runner image except it has not been attended to in a number of months as we rarely have a use for it.

**Comment by scottwittenburg** [comment]
> I am also open to making this a rhel8 based image for a more diverse offering of binaries.

Let's table that for now, but it's something to keep in mind for the future.

**Pull request merged**
