### PR TITLE
ParaView: Add variant for raytracing

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Add raytracing capability for ParaView.

CC: @mvictoras @willdunklin

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
This should close #32656

**Comment by kwryankrattiger** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
LGTM  Deferring merge decision to one or more additional maintainer.

**Comment by tldahlgren** [comment]
Oops.  I didn't realize auto merge was enabled or I would have just left a comment.

**Comment by kwryankrattiger** [comment]
@vicentebolea want to give a quick post-merge review?

**Comment by vicentebolea** [comment]
> @vicentebolea want to give a quick post-merge review?

LGTM :)

**Pull request merged**
