### PR TITLE
Paraview rocm

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Continuing #33653 work to get CI to pass.

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
CC: @eugeneswalker @wspear

**Review by eugeneswalker — CHANGES_REQUESTED** [review]
Could you move the `ecp-data-vis-sdk +rocm ...` spec to right after `chai` so that it is in alpha order?

**Review by eugeneswalker — DISMISSED** [review]
Thank you!

**Comment by eugeneswalker** [comment]
CI failing because of this:
* [radiuss-aws-aarch64-pr-generate](https://gitlab.spack.io/spack/spack/-/jobs/5122315)
```
...
$ spack ci generate --check-index-only --buildcache-destination "${SPACK_BUILDCACHE_DESTINATION}" --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir" --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/cloud-ci-pipeline.yml"
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-aarch64-gcc-10.2.1-patchelf-0.16.1-kjmrsrd7akfwzlejzsdyoun7fwgmvjgk.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-aarch64/gcc-10.2.1/patchelf-0.16.1/linux-centos7-aarch64-gcc-10.2.1-patchelf-0.16.1-kjmrsrd7akfwzlejzsdyoun7fwgmvjgk.spack
==> Installing "patchelf@0.16.1%gcc@10.2.1 ldflags="-static-libstdc++ -static-libgcc"  build_system=autotools arch=linux-centos7-aarch64" from a buildcache
==> Starting concretization pool with 16 processes
==> Warning: 'target=graviton2' is deprecated, use 'target=neoverse_n1' instead
```

**Review by eugeneswalker — DISMISSED** [review]

**Review by eugeneswalker — APPROVED** [review]

**Comment by eugeneswalker** [comment]
Is this ready to merge? Happy to proceed, if yes.

**Pull request merged**
