### PR TITLE
openblas: Allow specifying CPU architecture

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by alalazo** [comment]
How do we deal with the fact that targets are moving? I mean, it's very likely that the upcoming versions of `openblas` will drop support for some architecture, and add support for new ones. I fear this will become a mess similar to the libraries in `boost`.

**Comment by eschnett** [comment]
@alalazo We can make this a free-form variant where any string is allowed as argument, with respective build-time tests.

**Comment by alalazo** [comment]
@eschnett This seems to me a good compromise between correctness and flexibility. :+1:

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/openblas/package.py:69: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:83: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:88: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:101: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:104: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:111: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:114: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:118: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/openblas/package.py:125: [W293] blank line contains whitespace
```

**Comment by alalazo** [comment]
@eschnett ping

**Pull request closed without merging**
