### PR TITLE
Enable *nix ci windows

### PR DESCRIPTION
**Pull request by johnwparent**
Enable Linux and MacOS CI tests on the Windows feature branch to prevent Windows development from producing breaking changes. 

* Small additional change: Enable windows-testing when on develop - will be required later

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
@johnwparent can this PR be closed?

**Comment by johnwparent** [comment]
It needs a rebase, but we don't have CI for unix running on PRs into the windows feature branch at the moment, and I believe we had discussed requiring that.

**Comment by BetsyMcPhail** [comment]
> It needs a rebase, but we don't have CI for unix running on PRs into the windows feature branch at the moment, and I believe we had discussed requiring that.

You are correct, I thought we already had those changes on the windows branch. I agree they should be merged in so we don't accidently break anything on develop

**Comment by johnwparent** [comment]
> You are correct, I thought we already had those changes on the windows branch. I agree they should be merged in so we don't accidently break anything on develop

I also thought we had, but my last few PR's only triggered the Windows CI so I guess we must have dropped that commit out somewhere along the way.

**Comment by johnwparent** [comment]
@BetsyMcPhail Based on this commit it looks like we previously did the exact opposite of what this PR is doing 0c3801733b040708844a8223b0e3c52088ea9ced

**Pull request closed without merging**
