### PR TITLE
New package: py-pathml

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
Just so you know, you can submit a single PR with all new packages in it as long as they are directly related to each other.

**Comment by alalazo** [comment]
```
PKG-DIRECTIVES: 7 issues found
1. py-pathml: unknown package 'py-anndata' in 'depends_on' directive
     in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
2. py-pathml: unknown package 'py-scanpy' in 'depends_on' directive
     in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
3. py-pathml: wrong variant used for a dependency in a 'depends_on' directive
    the variant 'contrib' does not exist in package 'opencv'
    in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
4. py-pathml: unknown package 'py-python-bioformats' in 'depends_on' directive
     in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
5. py-pathml: dependency on py-anndata@0.7.6: cannot be satisfied by known versions of py-anndata
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
6. py-pathml: dependency on py-scanpy cannot be satisfied by known versions of py-scanpy
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
7. py-pathml: dependency on py-python-bioformats@4.0.0: cannot be satisfied by known versions of py-python-bioformats
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-pathml/package.py
```

**Comment by qwertos** [comment]
@spackbot fix style

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
Let me know if this PR is no longer a draft and I can merge.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
