### PR TITLE
Revert "py-setuptools-scm: make py-tomli dependency an open range (#2…

### PR DESCRIPTION
**Pull request by scottwittenburg**
…6820)"

This reverts commit a678a666838212bb054a5dd28a731820dae57668, as it broke
several python packages.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you clarify "how" this PR broke these packages? This PR was a bugfix and as far as I can tell is the right thing to do. The current behavior (depending only on a specific version of tomli that isn't even in Spack) seems more like a bug to me.

**Comment by scottwittenburg** [comment]
> Can you clarify "how" this PR broke these packages? 

I have no idea, but the first place I saw those build failures was in the gitlab pipeline for #26820 before it was merged.  However, it's possible the cause is something else.  Reverting will either fix the problem or it won't, and either way we'll have more information on which to base a decision at that point.

> This PR was a bugfix and as far as I can tell is the right thing to do. The current behavior (depending only on a specific version of tomli that isn't even in Spack) seems more like a bug to me.

Yeah, makes sense, and I agree.  Maybe #26820 wasn't the problem.

Here's a snippet from a [job](https://gitlab.spack.io/spack/spack/-/jobs/1148488) that failed in that PR:

```
Traceback (most recent call last):
  File "/builds/spack/spack/lib/spack/spack/build_environment.py", line 1028, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 1952, in build_process
    return installer.run()
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 1809, in run
    self._real_install()
  File "/builds/spack/spack/lib/spack/spack/installer.py", line 1916, in _real_install
    phase(pkg.spec, pkg.prefix)
  File "/builds/spack/spack/lib/spack/spack/package.py", line 119, in phase_wrapper
    phase(spec, prefix)
  File "/builds/spack/spack/lib/spack/spack/build_systems/python.py", line 178, in build
    self.setup_py('build', *args)
  File "/builds/spack/spack/lib/spack/spack/build_systems/python.py", line 167, in setup_py
    self.python('-s', setup, '--no-user-cfg', *args, **kwargs)
  File "/builds/spack/spack/lib/spack/spack/build_systems/python.py", line 161, in python
    inspect.getmodule(self).python(*args, **kwargs)
  File "/builds/spack/spack/lib/spack/spack/util/executable.py", line 231, in __call__
    raise self.error
spack.util.executable.ProcessError: Command exited with status 1:
    '/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.10-ihtrj5dmjbjmlc2satbke4h4kagkrnq3/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
```

**Comment by tgamblin** [comment]
Will we not know from the pipeline here whether this fixes the issue?  Seems like we don't have to revert if this doesn't actually result in a green pipeline.

**Comment by scottwittenburg** [comment]
> Will we not know from the pipeline here whether this fixes the issue? Seems like we don't have to revert if this doesn't actually result in a green pipeline.

That was my thinking.

**Comment by alalazo** [comment]
Would it be fine to pin the preferred version to 2.6.1, i.e. the version used before I merged #26813

**Comment by scottwittenburg** [comment]
> Would it be fine to pin the preferred version to 2.6.1, i.e. the version used before I merged #26813

I think so, but just so I'm clear: Are you saying we should do that pinning using package preferences in the E4S and RADIUSS environments (those are the stacks that were affected)?

**Comment by alalazo** [comment]
> I think so, but just so I'm clear: Are you saying we should do that pinning using package preferences in the E4S and RADIUSS environments (those are the stacks that were affected)?

I pinned the version since I think the new recipe is broken, sorry: https://github.com/spack/spack/pull/26831

> Can you clarify "how" this PR broke these packages? This PR was a bugfix and as far as I can tell is the right thing to do. The current behavior (depending only on a specific version of tomli that isn't even in Spack) seems more like a bug to me.

Here's a possible explanation: https://github.com/spack/spack/pull/26820#issuecomment-947100546 Waiting for the pipeline to finish on my PR above to see if the hypothesis holds.

**Comment by scottwittenburg** [comment]
Closing because @26831 is the right solution.

**Pull request closed without merging**
