### PR TITLE
perl-memoize: add new package with version 1.16

### PR DESCRIPTION
**Pull request by ChristopherChristofi**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the homepage and version sha256.

**Comment by tldahlgren** [comment]
@EbiArnie Looks like this is on the standard list so I should probably not have merged it.  

@ChristopherChristofi @EbiArnie Is there a chance it isn't automatically installed on a system or should this PR be reverted?

**Comment by ChristopherChristofi** [comment]
Well it is used and listed as a specific dependency for Perl software that are and could be spack packages.
There are some related comments in PR #41915

**Comment by EbiArnie** [comment]
Regarding the question 'is this needed':
```
$ corelist Memoize

Data for 2021-05-20
Memoize was first released with perl v5.7.3
```

Meaning that yes, this is a core module and has been since Perl 5.7.3. If we want to support Perl older than 5.7.3 (released 2002) then yes, else no.
So I'd say it is not needed and should be removed.
If there are packages with an explicit 'depends_on("perl-memoize")', this should also be removed.

But, as I said in the other PR comments - I don't know what the policy is at the moment. The main pro/cons are:

- No packages for core modules: Makes for less modules, easier solves. It is what most current packages expect. Package authors have to be aware of the core modules that come with Perl.

- Packages for core modules. The packages would be virtuals and Perl would become a provider for these, with the actual package for the module being the other provider. Advantage: You can depend on a module, not on a Perl version. So, more correct in a sense. No remembering which modules are in core in which Perl version. Disadvantage: more modules, bigger solves, most current Perl packages should be updated.

**Comment by ChristopherChristofi** [comment]
This is great, thank you @EbiArnie and for taking the time to share this, makes it a lot clearer and saves me time when determining the validity of a potential spack package core module.
> Package authors have to be aware of the core modules that come with Perl.

The above seems good. plus simpler. In the case of new or removal of core modules, a relevant dedicated spack package for the module would prove useful. Although, I suspect depending on the spack provided Perl would be the cleaner option for the majority of core modules that have been well embedded and continued since much older versions of Perl. It should be noted there are other core module included spack packages that exist in the repo that fit this same criteria

**Comment by tldahlgren** [comment]
> Meaning that yes, this is a core module and has been since Perl 5.7.3. If we want to support Perl older than 5.7.3 (released 2002) then yes, else no. So I'd say it is not needed and should be removed. If there are packages with an explicit 'depends_on("perl-memoize")', this should also be removed.
> 

I see I have to be careful with case since my first attempt to use `corelist` on 5.26.3 (using all lower case) said it wasn't part of the core.

**Pull request merged**
