### PR TITLE
Add kuberry to list of Trilinos recipe maintainers

### PR DESCRIPTION
**Pull request by kuberry**

### CODE REVIEW

**Comment by sethrj** [comment]
- Context: https://github.com/spack/spack/pull/24565#issuecomment-873030962
- Previous contributions: https://github.com/spack/spack/pull/22205 

Generally speaking, desiring notifications does not merit becoming a maintainer, but if you're willing to help maintain trilinos the more the merrier. Do you work with the trilinos folks at sandia?

**Comment by kuberry** [comment]
Hi @sethrj. Yes, I'm the lead developer for the Compadre package inside Trilinos. I maintain the Xyce recipe for Spack as well, which relies pretty extensively on Trilinos.

**Review by sethrj — APPROVED** [review]

**Comment by sethrj** [comment]
Super. Welcome aboard!

**Comment by kuberry** [comment]
Thanks!

**Comment by sethrj** [comment]
Spurious CI failure (this doesn't even change the recipe of trilinos but will end up causing it to rebuild 3 times...):
```
fatal: unable to access 'https://gitlab.spack.io/spack/spack.git/': Could not resolve host: gitlab.spack.io
```

**Comment by sethrj** [comment]
More unrelated failures, https://gitlab.spack.io/spack/spack/-/jobs/553414 . @alalazo could you please force-merge this since it simply adds a maintainer? Thanks!

**Comment by sethrj** [comment]
Thanks!

**Pull request merged**
