### PR TITLE
petsc: add 64bit variant

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by eschnett** [comment]
Does this require that LAPACK uses 64-bit integers as well? OpenBLAS does have such an option (it's not exposed to Spack yet), netlib's LAPACK probably doesn't unless one uses certain compiler flags when building it.

The name `64bit` is a bit misleading since it is too generic. What about e.g. `int64` instead?

I don't think that PETSc (or LAPACK) change their function names when indices have 64 bits. This means that this variable for PETSc (and probably LAPACK and BLAS) affect many other packages as well. Mismatches can lead to segfaults, especially in Fortran 77 code that doesn't check function argument types. This probably means that many packages will add `~int64` to their dependencies.

**Comment by davydden** [comment]
> Does this require that LAPACK uses 64-bit integers as well?

don't know, PETSc did not complain during config. In either way, you can't forward variants to virtual packages right now, see https://github.com/LLNL/spack/issues/1712

> Mismatches can lead to segfaults, especially in Fortran 77 code that doesn't check function argument types.

correct, it's possible. I personally won't use this, so we need to wait and see when somebody come across an issue.

> What about e.g. int64 instead?

sounds good to me. @Rombur what do you think about this in deal.II as well?

**Comment by Rombur** [comment]
I am not a fan of `int64` because what we do in deal is that some variables use `unsigned long long int` instead of `unsigned int`.  But I think uniformity is the most important so if you decide that `int64` is the way to go for `petsc` and its dependencies then I am in favor of changing it in `deal.II`

**Comment by davydden** [comment]
@tgamblin do you have preferences in naming this variant uniformly in Spack?

**Comment by tgamblin** [comment]
@davydden: I agree with @eschnett that `64bit` is generic.  I actually like `int64`.

@Rombur: do you not like the `int` part?  `unsigned long long` is short for `unsigned long long int`, and it's guaranteed to be at least `64` bits, so I think `int64` covers it.  `uint64` seems too specific to me since the real point is that all sizes/bounds/counts will be this large, not that the type is unsigned, right?

**Comment by Rombur** [comment]
@tgamblin if I see `int64` I expect most of the `int32` to become `int64`. So for example, if I use a lapack function I expect to have to change most of the `int` to `int64` since the matrix is now using `int64`. However, in deal 99% of the functions are unchanged. This is not a blanket change. However, like I said, uniformity is the most important. I just gave my opinion because @davydden asked for it.

**Comment by citibeth** [comment]
I like `int64`.  My first thought when I read about a "64bit variant" was, "doesn't it already use double precision?"  Having the word "int" in there makes it clear what's going on.

**Comment by davydden** [comment]
Ok, then let's use int64 throughout. This PR already has it.

**Comment by davydden** [comment]
@tgamblin @becker33 ping.

**Comment by tgamblin** [comment]
@BarrySmith FYI -- this modifies PETSc.  Can you review?

**Comment by BarrySmith** [comment]
hypre, superlu_dist, and metis/parmetis all support int64. If PETSc is built with int64 then these packages must also be built with int64. The flag for these packages are --enable-bigint,  -D_LONGINT and -DMETIS_USE_LONGINDEX=1 (now Todd can understand why xSDK tried to make some standards for configure arguments).

Mumps, as you note, does not support int64.

PETSc can use hdf5 even when PETSc is built with int64 (we convert appropriately for hdf5 calls)

PETSc, hypre, superlu_dist  when built with int64 use 32 bit integers with BLAS/LAPACK (we convert automatically as needed).

**Comment by davydden** [comment]
Thanks for detailed comments @BarrySmith, i will update this PR accordingly...

**Comment by davydden** [comment]
@tgamblin @BarrySmith i updated  the PR with `int64` for PETSc and friends.

**Comment by davydden** [comment]
p.s. `metis` calls this variant `idx64`, I left it unchanged for now.

**Comment by citibeth** [comment]
I have no problem if you go ahead and change it.

**Comment by davydden** [comment]
@nrichart @goxberry @xjrc i rename a variant in `mumps` and `metis`, you may want to comment on whether or not you like the name `int64` to be used consistently in Spack.

**Comment by nrichart** [comment]
For  mumps it was for consistency  with metis if I recall correctly. Metis potentially has different integer types and index is one of them. 
But on principle I am not against homogenizing the variant names.

**Comment by davydden** [comment]
@tgamblin @becker33: I think this is ready. I am fine with naming the variant `int64`, but if someone prefers `idx64` which was used in `metis` prior to this PR, i can rename all the variants.

**Comment by eschnett** [comment]
I would use `int64` if all integer arguments have 64 bits, and `idx64` if only indices have 64 bits. (Other integers might include e.g. "number of arguments", "number of iterations", or integer error codes.)

For example, if a packages uses the Fortran `-i8` compiler flag, then it would be `int64`.

**Comment by davydden** [comment]
> I would use int64 if all integer arguments have 64 bits, and idx64 if only indices have 64 bits. (Other integers might include e.g. "number of arguments", "number of iterations", or integer error codes.)

that a fair comment, but this would certainly lead to a mixture of both names. 

I quickly checked `hypre`, and it does indeed use 64bit integers everywhere, so this one is `int64`. Most likely same applies to `superlu-dist` and most certainly to `petsc` which uses `PetscInt`.
`blas` and `lapack` also fall into this category.
 
On another hand, `metis` and `mumps` would probably stay as `idx64` as @nrichart noted that `metis` has different integer types. The same `idx64` would be used in `dealii`.

If everyone is on board with distinguishing the two scenarios, I am fine to make changes and quickly document it in `Packaging Guide`.

**Comment by davydden** [comment]
@tgamblin @becker33 ping.

**Comment by davydden** [comment]
@tgamblin can we get this one merged for `0.10` testing? If we decide to rename things later for `1.0`, we can always do this.

**Comment by tgamblin** [comment]
@davydden: done!

**Pull request merged**
