### PR TITLE
Add hipblas dependency when rocm variant for pika package

### PR DESCRIPTION
**Pull request by aurianer**
Hipblas is compulsory when building pika with rocm.

### CODE REVIEW

**Review by msimberg — APPROVED** [review]

**Comment by msimberg** [comment]
This seems unrelated: https://gitlab.spack.io/spack/spack/-/jobs/2036265. Does the job need to be retriggered?

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by msimberg** [comment]
Does someone know why this is failing? Does it need a(nother) rerun?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
