### PR TITLE
oneapi : fix library class hierarchy

### PR DESCRIPTION
**Pull request by mabraham**

### CODE REVIEW

**Comment by mabraham** [comment]
The implementation of `headers` method tries to use functionality from the `Library` class that is now its superclass. Is that appropriate @rscohn2 ?

**Comment by rscohn2** [comment]
I don't understand the problem you are seeing. But I don't have objections to the change. Can you explain the problem in more detail?

**Comment by mabraham** [comment]
> I don't understand the problem you are seeing. But I don't have objections to the change. Can you explain the problem in more detail?

I want to make variants for heffte and GROMACS to depend on ITT via `intel-oneapi-vtune` package (which implements  `IntelOneApiLibraryPackageWithSdk`), which means I want to use the `headers` method for that VTune package. That method depends on the `sdk.include` property that's only implemented by `IntelOneApiLibraryPackage` that should have been the superclass for `IntelOneApiLibraryPackageWithSdk`. Currently that superclass is `IntelOneApiPackage`, which is not sufficient.

**Comment by mabraham** [comment]
That is, nobody's using `headers` from `IntelOneApiLibraryPackageWithSdk` so we haven't seen that it's broken :-)

**Review by rscohn2 — APPROVED** [review]
Thanks.

**Comment by mabraham** [comment]
Usage now proposed in #47764

**Pull request merged**
