### PR TITLE
ParaView: add new ParaView-5.9.0-RC4 release

### PR DESCRIPTION
**Pull request by vicentebolea**
Hi there, first release of the year!

This morning we have just released the latest ParaView version.

I have made that changes in the ParaView Spack package which adds this new version and removes the previous RC.

Note that this is a release candidate.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@chuckatkins @danlipsa can you review? @vicentebolea would you like to be added as an official maintainer of the package?

**Comment by vicentebolea** [comment]
> @vicentebolea would you like to be added as an official maintainer of the package?

Sure thing, I actually will be in charge of following releases, so this makes sense.

**Comment by vicentebolea** [comment]
@adamjstewart should I make the change to add myself in this PR or open another one?

**Comment by adamjstewart** [comment]
It's fine to add yourself as a maintainer in this PR. Thanks for volunteering!

**Pull request merged**
