### PR TITLE
py-pyprecice: simplify package

### LINKED ISSUE #86: Phase install_lib fails using Spack if system's Python is used
i tried to install the bindings using Spack on a system where external packages were set up with `spack external find`. This command also found the pre-installed Python of the system. Now, building the package `py-pyprecice` fails with the following error message:

```
==> Installing py-pyprecice-2.2.0.1-z4ojdrz6aqadiqidezkkubiifvwjr4uk
==> No binary for py-pyprecice-2.2.0.1-z4ojdrz6aqadiqidezkkubiifvwjr4uk found: installing from source
==> Fetching https://github.com/precice/python-bindings/archive/v2.2.0.1.tar.gz
##################################################################################################################################### 100.0%#-=#=- #     #                                                                                                                             
==> No patches needed for py-pyprecice
==> py-pyprecice: Executing phase: 'install_lib'
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python3.9' '-s' 'setup.py' '--no-user-cfg' 'install_lib'

1 error found in build log:
     63     8611 |   __pyx_v_self->thisptr->writeBlockScalarData(__pyx_t_4, __pyx_v_size, ((int const *)__pyx_v__vertex_ids->data), ((doubl
           e const *)__pyx_v__values->data));
     64          |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     65    /home/alex/software/spack/lib/spack/env/gcc/g++ -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interpos
           ition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.9/tmp/alex/spack-stage/spack-stage-py-pyprecic
           e-2.2.0.1-z4ojdrz6aqadiqidezkkubiifvwjr4uk/spack-src/cyprecice/cyprecice.o -L/usr/lib -o build/lib.linux-x86_64-3.9/cyprecice.cp
           ython-39-x86_64-linux-gnu.so -lprecice
     66    UPDATING build/lib.linux-x86_64-3.9/precice/_version.py
     67    set build/lib.linux-x86_64-3.9/precice/_version.py to 'v2.2.0.1'
     68    copying build/lib.linux-x86_64-3.9/cyprecice.cpython-39-x86_64-linux-gnu.so -> /usr/lib/python3.9/site-packages
  >> 69    error: could not create '/usr/lib/python3.9/site-packages/cyprecice.cpython-39-x86_64-linux-gnu.so': Permission denied
```

The `install_lib` phase creates the necessary `_version.py` file , but it also wants to copy files into the system path
```
   68    copying build/lib.linux-x86_64-3.9/cyprecice.cpython-39-x86_64-linux-gnu.so -> /usr/lib/python3.9/site-packages
>> 69    error: could not create '/usr/lib/python3.9/site-packages/cyprecice.cpython-39-x86_64-linux-gnu.so': Permission denied
```
which is not possible without super user rights. Thus, the phase fails. 

Why does the build phase want to copy data over and is it necessary? The answer should be no as all `py-pyprecice` related files should end up in the corresponding Spack directory that is user-writable. 

This might be related to the problem observed during the workshop which led to https://github.com/precice/python-bindings/issues/84.

### LINKED ISSUE #87: Consider replacing build_lib by build_py phase in Spack recipe
We could check whether it is possible to replace the phase `build_lib` with `build_py` in the Spack recipe as it creates the needed `_version.py`. However, it fails with an error since the directory `build/lib.linux-x86_64-3.9/precice/` seems to be missing.  A grep of the logfile is given here:
```
11:copying precice/_version.py -> build/lib/precice                                                                                         
13:UPDATING build/lib/precice/_version.py                                                                                                   
14:set build/lib/precice/_version.py to 'v2.2.0.1'                                                                                          
72:UPDATING build/lib.linux-x86_64-3.9/precice/_version.py                                                                                  
73:error: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-3.9/precice/_version.py'
```

### PR DESCRIPTION
**Pull request by adamjstewart**
Although all versions of `py-pyprecice` use `setuptools`, older versions override the `distutils` version of `install`, so the `--single-version-externally-managed` flag wasn't being respected. This PR replaces the `distutils` version of `install` with the `setuptools` version. By using `filter_file`, a single line can be used instead of a different patch for each version.

By using Spack's default `install` method, the library will be installed to the correct location, even for external system Python installations.

Tested 2.0.0.1 and develop on Ubuntu 20.04 with Spack-installed Python 3.8.11 and GCC 9.3.0. Can someone test with an externally installed Python for me? Would be good to test other versions too.

Closes #25035
Closes https://github.com/precice/python-bindings/issues/86
Closes https://github.com/precice/python-bindings/issues/87

### CODE REVIEW

**Comment by ajaust** [comment]
Thank you so much for your work on this! You solution so much shorter than mine. :open_mouth: : 

I just installed `2.0.0.1` successfully using your fork. The package was installed in `<prefix>/lib/python3/dist-packages/` and calling `python -c "import precice"` worked like a charm.

I am currently building the package for version `2.1.1.2` just to be extra safe.

**Review by ajaust — APPROVED** [review]
The changes look very good. I like that the solution is this short. I have successfully tested the PR for `2.0.0.1`, `2.1.1.2` and `2.2.1.1`.

**Comment by ajaust** [comment]
One (partially related question). The spack-bot invited me to join the Spack organization due to this PR. Is this intentional? I am very happy to get the invitation, but I do not feel like I have contributed much to deserve that honor.

**Comment by adamjstewart** [comment]
@ajaust there are many levels of membership within the Spack organization. The level that spack-bot invited you to is "maintainer", which allows us to request review from you but doesn't give you merge privileges or anything else. This is why spack-bot was able to request review from @BenjaminRodenberg and @IshaanDesai but not you.

**Comment by ajaust** [comment]
Great! Thanks for the clarification.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
