### PR TITLE
Cflags requirements: regression fix

### LINKED ISSUE #39671: Compiler flags in spec requirements regression
### Steps to reproduce

Create the following environment:

```
spack:
  specs:
  - zlib
  view: false
  concretizer:
    unify: true
  packages:
    zlib:
      require: cflags="-g"
```

with this environment active, `spack concretize` fails.

This is on d9d1eb24f9e1ef3550256ca16d5b0c567c3102c7

I can also reproduce it on 9bb5cff but not 87d4bdaa025b624d3b891f4e2f0c4034b502496b. So I'm guessing this logic needs to be updated with a better understanding of https://github.com/spack/spack/pull/38447.

What I find strange is that we have a test for this: `test_require_cflags`, which uses nearly exactly this config and passes (on all mentioned commits).

### Error message

```
$ spack -d concretize -f
...
==> [2023-08-28-18:03:55.024834] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'zlib'.
==> [2023-08-28-18:03:55.024946] Error: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'zlib'.
Traceback (most recent call last):
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/main.py", line 1023, in main
    return _main(argv)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/main.py", line 978, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/main.py", line 1006, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/main.py", line 647, in _invoke_command
    return_val = command(parser, args)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/cmd/concretize.py", line 44, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/environment/environment.py", line 1333, in concretize
    return self._concretize_together(tests=tests)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/environment/environment.py", line 1428, in _concretize_together
    concrete_specs: List[spack.spec.Spec] = spack.concretize.concretize_specs_together(
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/concretize.py", line 741, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/concretize.py", line 748, in _concretize_specs_together_new
    result = solver.solve(abstract_specs, tests=kwargs.get("tests", False))
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/solver/asp.py", line 2944, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/solver/asp.py", line 864, in solve
    error_handler.raise_if_errors()
  File "/g/g17/scheibel/repos/spack-requireflags/spack/lib/spack/spack/solver/asp.py", line 683, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'zlib'.
```

### Information on your system

I can reproduce this on Linux and Mac, e.g.

```
$ spack debug report
* **Spack:** 0.21.0.dev0 (d9d1eb24f9e1ef3550256ca16d5b0c567c3102c7)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by scheibelp**
fixes #39671

Reapply targeted changes from #39880

Based on discussion there, this logic is due for some refactoring. It would be good to have a fix in for the 0.21 release though (and refactoring might take longer).

### CODE REVIEW

**Comment by scheibelp** [comment]
Items meriting refactor that are longer-term (not addressed here):

* cyclic impose/condition is confusing to read for requirement groups
* separate numbering system for requirement groups and impose/condition (which overlaps)

**Review by alalazo — CHANGES_REQUESTED** [review]
The fix looks good to me, but the unit test doesn't fail on develop (for the same reason the previous test didn't catch the bug). I suggest using the mock repo instead:
```diff
diff --git a/lib/spack/spack/test/concretize_requirements.py b/lib/spack/spack/test/concretize_requirements.py
index f3dad1a195..51747dd992 100644
--- a/lib/spack/spack/test/concretize_requirements.py
+++ b/lib/spack/spack/test/concretize_requirements.py
@@ -91,25 +91,6 @@ class U(Package):
 )
 
 
-_pkgw = (
-    "w",
-    """\
-class W(Package):
-    provides('virtual-w')
-    version('1.0')
-""",
-)
-
-
-_virtualw = (
-    "virtual-w",
-    """\
-class VirtualW(Package):
-    virtual = True
-""",
-)
-
-
 @pytest.fixture
 def create_test_repo(tmpdir, mutable_config):
     repo_path = str(tmpdir)
@@ -123,7 +104,7 @@ def create_test_repo(tmpdir, mutable_config):
         )
 
     packages_dir = tmpdir.join("packages")
-    for pkg_name, pkg_str in [_pkgx, _pkgy, _pkgv, _pkgt, _pkgu, _pkgw]:
+    for pkg_name, pkg_str in [_pkgx, _pkgy, _pkgv, _pkgt, _pkgu]:
         pkg_dir = packages_dir.ensure(pkg_name, dir=True)
         pkg_file = pkg_dir.join("package.py")
         with open(str(pkg_file), "w") as f:
@@ -488,25 +469,25 @@ def test_one_package_multiple_oneof_groups(concretize_scope, test_repo):
 
 
 @pytest.mark.regression("34241")
-def test_require_cflags(concretize_scope, test_repo):
+def test_require_cflags(concretize_scope, mock_packages):
     """Ensures that flags can be required from configuration."""
     conf_str = """\
 packages:
   all:
     providers:
-      virtual-w: [w]
-  y:
+      mpi: [mpich]
+  mpich2:
     require: cflags="-g"
-  virtual-w:
-    require: w cflags="-O1"
+  mpi:
+    require: mpich cflags="-O1"
 """
     update_packages_config(conf_str)
 
-    spec_y = Spec("y").concretized()
+    spec_y = Spec("mpich2").concretized()
     assert spec_y.satisfies("cflags=-g")
 
-    spec_w = Spec("virtual-w").concretized()
-    assert spec_w.satisfies("w cflags=-O1")
+    spec_w = Spec("mpi").concretized()
+    assert spec_w.satisfies("mpich cflags=-O1")
 
 
 def test_requirements_for_package_that_is_not_needed(concretize_scope, test_repo):
```
I'll be posting benchmark results next

**Comment by alalazo** [comment]
Confirmed that there is no impact on performance.

[radiuss-develop.csv](https://github.com/spack/spack/files/13215806/radiuss-develop.csv)
[radiuss-pr.csv](https://github.com/spack/spack/files/13215808/radiuss-pr.csv)
[radiuss.txt](https://github.com/spack/spack/files/13215809/radiuss.txt)

radiuss


Tested on:

* **Spack:** 0.21.0.dev0 (160bfd881ddcb32a9b0fa1bd6eabe2f70b9bba41)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Thanks!

**Pull request merged**
