### PR TITLE
make git fetching quiet

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/LLNL/spack/issues/3179

with this PR
```
$ spack install dealii@develop
==> Installing dealii
==> zlib is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.10-oh65pcwikiqep74vtfaitp6ojgzivaag
...
==> gsl is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gsl-2.3-zpffzwkqlu2zkpp6f4gv6xppiqsxz63m
==> Trying to clone git repository:
  https://github.com/dealii/dealii.git
==> No checksum needed when fetching with git
==> Already staged dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm in /Users/davydden/spack/var/spack/stage/dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm
==> No patches needed for dealii
==> Building dealii [CMakePackage]
==> Executing phase : 'cmake'
...
```

### CODE REVIEW

**Comment by davydden** [comment]
anyone knows how to make
```
tty.msg("Trying to clone git repository:", self.url, *args)
```
output in one line?

**Comment by adamjstewart** [comment]
> anyone knows how to make... output in one line?

Removing the commas sometimes works.

**Comment by BarrySmith** [comment]
> anyone knows how to make... output in one line?

tty.msg("Trying to clone git repository:" + str(self.url), *args)

?

**Comment by davydden** [comment]
updated versions makes the output in one line:
```
==> Trying to clone git repository: https://github.com/xianyi/OpenBLAS.git on branch develop
```

**Comment by tgamblin** [comment]
@davydden: FYI, @trws ran into issues like this when making the `GitFetchStrategy` -- which is why there are so many version checks in `GitFetchStrategy.fetch()` for all the different ways to check out.  I am reminded once again of [git koans](http://stevelosh.com/blog/2013/04/git-koans/).

**Comment by davydden** [comment]
@tgamblin 

> Can you look into whether --quiet is supported on all these commands back through git 1.6 (default in RHEL6)

fully agree. I have not thought about it. So here's what I can tell based on online-documentation which is available from `1.8` (~2012):


| Command  | Version |  Link |
| ------------- | ------------- |-----|
| clone  | 1.8.1.5  | https://git-scm.com/docs/git-clone/1.8.1.5 |
| checkout | 1.8.2 | https://git-scm.com/docs/git-checkout/1.8.2 |
| pull | 1.8.1.6 | https://git-scm.com/docs/git-pull/1.8.1.6 |
| submodule | 1.8.1 | https://git-scm.com/docs/git-submodule/1.8.1 |
| clean | 1.8.2  | https://git-scm.com/docs/git-clean/1.8.2  |

I don't know how one would check those commands in `1.6`, i don't have it around. If someone could test it, that would be great!

p.s. I update the PR to remove `--quiet` when in debug mode.

**Comment by adamjstewart** [comment]
Tested on CentOS 6 with the system git (1.7.1). `--quiet` is accepted by all of the aforementioned commands.

**Comment by adamjstewart** [comment]
Ping @tgamblin

**Pull request merged**
