### PR TITLE
py-argcomplete: add 1.12.3

### PR DESCRIPTION
**Pull request by manuelakuhn**

### CODE REVIEW

**Review by bernhardkaindl — APPROVED** [review]

**Review by adamjstewart — APPROVED** [review]

**Comment by manuelakuhn** [comment]
@spackbot re-run pipeline

**Comment by bernhardkaindl** [comment]
I'm building the dependents of py-argcomplete@1.12.3, which might be even better than completing the pipeline, so I think we can spare keeping the pipeline runners busy with running the gitlab pipelines for this package. I merge this PR this way.

**Comment by bernhardkaindl** [comment]
@spackbot help

**Comment by manuelakuhn** [comment]
I wanted to take advantage of the enabled auto-merge without bothering anybody again, that's why I tried to re-run the pipeline (closing and reopening revokes auto-merge).
Thanks for taking care of this!

**Pull request merged**
