### PR TITLE
wgrib2: add NOAA software maintainers 

### PR DESCRIPTION
**Pull request by edwardhartnett**
added NOAA software maintainers to maintainer list to wgrib2

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@kgerheiser you have the following in your version of the file:

```
variant('jasper', default=True)
    variant('ipolates', default=0, values=('0', '1', '3'), multi=False)
    variant('netcdf4', default=False)
    variant('regex', default=True)
    variant('tigge', default=True)
    variant('spectral', default=False)
    variant('openmp', default=False)
    variant('proj4', default=False)
    variant('wmo-validation', default=False)
    variant('timezone', default=False)
    variant('g2c', default=False)
    variant('png', default=True)
    variant('aec', default=False)
    variant('lib', default=True)
    variant('shared', default=False)

    depends_on('ip2', when='ipolates=3')
    depends_on('ip', when='ipolates=1')
    depends_on('jasper', when='+jasper')
    depends_on('netcdf-c', when='netcdf4')
    depends_on('libpng', when='+png')

    def cmake_args(self):
        args = [
            self.define_from_variant('USE_JASPER', 'jasper'),
            self.define_from_variant('USE_IPOLATES', 'ipolates'),
            self.define_from_variant('USE_NETCDF4', 'netcdf4'),
            self.define_from_variant('USE_REGEX', 'regex'),
            self.define_from_variant('OPENMP', 'openmp'),
            self.define_from_variant('BUILD_LIB', 'lib'),
            self.define_from_variant('USE_SPECTRAL', 'spectral'),
            self.define_from_variant('USE_TIGGE', 'tigge'),
            self.define_from_variant('USE_PNG', 'png')
        ]
        return args

```

Should these be added? @t-brown will that break anything from your point of view?

This library has a dependency change, it used to depend on ip2, but now depends on ip.

**Review by Hang-Lei-NOAA — COMMENTED** [review]
This (spack for wgrib2) should be totally changed. Since we have moved from NCEPLIBS-wgrib2 repo to Wesley's wgrib2 repo.
URL="https://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz.v${version}"

**Comment by t-brown** [comment]
> Should these be added? @t-brown will that break anything from your point of view?
> 
> This library has a dependency change, it used to depend on ip2, but now depends on ip.

Yes, by default I use `wgrib2` to do interpolation after UPP/NCEP Post, which depends on ip2. Would it be possible to make that the default?

**Review by sethrj — APPROVED** [review]

**Comment by sethrj** [comment]
Do you want to make other package changes in this PR or leave it as the subject says (adding maintainers)?

**Review by t-brown — APPROVED** [review]

**Comment by edwardhartnett** [comment]
@sethrj and @t-brown let's merge these changes and I'll circle back around for the other changes that may need to be made in a future PR.

**Pull request merged**
