### PR TITLE
New patch releases SLEPc 3.21.1 and 3.21.2

### PR DESCRIPTION
**Pull request by joseeroman**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed the two version sha256s.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Confirmed the version sha256s.  

According to `pyproject.toml`, `cython` needs to be `>= 3`.

**Comment by balay** [comment]
It requires [in sync with petsc4py change in b19c4cdcf66beb1c2386bec64e8071bc6d559ab1]:
```diff
diff --git a/var/spack/repos/builtin/packages/py-slepc4py/package.py b/var/spack/repos/builtin/packages/py-slepc4py/package.py
index 59fd8fc378..38d623d7e0 100644
--- a/var/spack/repos/builtin/packages/py-slepc4py/package.py
+++ b/var/spack/repos/builtin/packages/py-slepc4py/package.py
@@ -45,6 +45,7 @@ class PySlepc4py(PythonPackage):
 
     patch("ldshared.patch", when="@:3.18")
 
+    depends_on("py-cython@3:", when="@3.20:", type="build")
     depends_on("py-cython@0.29.32:", when="^python@3.11:", type="build")
     depends_on("py-cython@0.24:", type="build")
     depends_on("py-setuptools", type="build")
```

**Comment by balay** [comment]
might as well add `v3.21.2` here.

**Comment by joseeroman** [comment]
Added the fix for cython and the new patch release of SLEPc

**Review by balay — APPROVED** [review]

**Comment by balay** [comment]
@tldahlgren I think this PR is ready-for-merge

**Comment by balay** [comment]
Closing as this change is merged via https://github.com/spack/spack/pull/46647

**Pull request closed without merging**
