### PR TITLE
adios2: add v2.10.0-rc1 release

### PR DESCRIPTION
**Pull request by vicentebolea**
:tada: :tada: :tada: 

Finally! ADIOS2 v2.10.0-rc1 release is out.

This bring exiting new features and bugfixes. Find the release notes at:
https://github.com/ornladios/ADIOS2/releases/tag/v2.10.0-rc1

Let me know if we need to change anything else in the package

ViB

:tada: :tada: :tada:

### CODE REVIEW

**Comment by vicentebolea** [comment]
@spackbot fix style

**Comment by vicentebolea** [comment]
@spackbot fix style

**Review by tldahlgren — APPROVED** [review]
Confirmed the version sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
Looks like `fides` update was merged 2 days ago so this might really need to be rebased to develop.

**Comment by vicentebolea** [comment]
@tldahlgren rebased

**Pull request merged**
