### PR TITLE
Fix test: prune untouched specs from gitlab ci pipeline

### PR DESCRIPTION
**Pull request by scottwittenburg**
As mentioned in the commit message, the `test_ci_generate_prune_untouched` method depended on the state of the spack repo where the test was running, i.e. if the repo held a change that prevented pruning of untouched specs (e.g. the `.gitlab-ci.yml` was edited in the most recent commit), then the test would fail.  This PR removes the state of the spack repo from the equation by mocking the `get_stack_changed` method.  It also adds a new test to cover the `get_stack_changed` method by running it against a mock git repo under testing control.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@trws Once this is merged, rebasing on it should fix the failing test in your dev-tools PR (#29708).  Sorry for the holdup.

**Comment by trws** [comment]
Excellent, thanks!  Also, no worries on the delay, I'm really hoping to land the lua fix before I land the dev env PR anyway, because we currently can't build neovim and some of the other tools properly in a combined build.

**Review by trws — CHANGES_REQUESTED** [review]
Nice work on the new mock_git_repo, you avoided all the issues with the one we use elsewhere.  That said, would you mind adding `--local` to the `config` lines? I've been bit a lot lately by spack tests assuming git is using defaults, and I'm not 100% sure the GIT_CONFIG_GLOBAL and similar env vars are reliably cleared in tests.

**Comment by scottwittenburg** [comment]
> would you mind adding --local to the config lines?

Done!  The manpage for `git config` says that `--local` is the default, but I agree it's good to make it explicit.

**Review by trws — APPROVED** [review]
You're right, it is, and it can't be overridden by a config file, but I think it can be overridden with GIT_CONFIG in the environment, and even if it can't I just plain don't trust git commands to use the defaults after the bugs we had with commands assuming master was the default name, or assuming that a spack repo must be named "spack" or what have you.

**Pull request merged**
