### PR TITLE
p7zip build fails with gcc10+

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Comment by vmiheer** [comment]
@tgamblin, @adamjstewart  would you like to be maintainers for p7zip package?

**Comment by adamjstewart** [comment]
Nope

**Comment by vmiheer** [comment]
Can you review this PR? I guess from next PR onward I can review this package?

**Review by adamjstewart — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
