### PR TITLE
OneAPI Release intel-oneapi-2023.1

### PR DESCRIPTION
**Pull request by prstrnn**
@rscohn2

### CODE REVIEW

**Review by rscohn2 — APPROVED** [review]
Looks good. Thanks.

**Comment by imangohari1** [comment]
A comment to follow here. Thank you.

**Review by tldahlgren — APPROVED** [review]
Confirmed all 13 version sha256.

**Comment by hpcnpatel** [comment]
@rscohn2 @prstrnn Is there a specific reason to name the newly added versions "2023.1" and not "2023.1.0"?  

I thought most of the one API release has the format "AAAA.B.C"

This needs to look more consistent. At least one component is versioned "23.1.0".

**Comment by rscohn2** [comment]
> Is there a specific reason to name the newly added versions "2023.1" and not "2023.1.0"?

It's a mistake. @prstrnn: Can you submit a PR to fix it?

**Comment by prstrnn** [comment]
@rscohn2 Here is the fix: https://github.com/spack/spack/pull/36665

**Pull request merged**
