### PR TITLE
Libevent depends on OpenSSL

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by trws** [comment]
OpenSSL is an optional dependency for encryption support at the libevent level.  Shouldn't this be a variant?

**Comment by tgamblin** [comment]
@eschnett: can you make this a variant?

**Comment by eschnett** [comment]
Note: Yes, this is possible if one sets `--disable-ssl` when configuring.

**Comment by trws** [comment]
@eschnett, it's the default behavior if OpenSSL isn't found.  Using the option is a better idea so that it follows the requirements in the spec, but it's an optional dependency either way.

**Comment by tgamblin** [comment]
@trws @eschnett I'll merge once the variant's in

**Comment by tgamblin** [comment]
variant-ized with `default=True`.

**Pull request merged**
