### PR TITLE
Add papyrus to the list of broken tests

### PR DESCRIPTION
**Pull request by alalazo**
See https://gitlab.spack.io/spack/spack/-/jobs/8983875

The job is hanging on tests for 6 hrs.

### CODE REVIEW

**Comment by alalazo** [comment]
The next pipeline passed, so this is likely not needed https://gitlab.spack.io/spack/spack/-/jobs/8986591

**Comment by eugeneswalker** [comment]
> See https://gitlab.spack.io/spack/spack/-/jobs/8983875
> 
> The job is hanging on tests for 6 hrs.

@tldahlgren @wspear I thought there was a way to enforce a timeout on hung tests? Do you know?

**Review by eugeneswalker — DISMISSED** [review]

**Comment by tldahlgren** [comment]
> > See https://gitlab.spack.io/spack/spack/-/jobs/8983875
> > The job is hanging on tests for 6 hrs.
> 
> @tldahlgren @wspear I thought there was a way to enforce a timeout on hung tests? Do you know?

We don't have a way yet to enforce a timeout on packages whose tests fail.  At this point the package can be marked as having failing (including hung) tests.  See the `broken-tests-packages:` configuration in the docs at https://spack.readthedocs.io/en/latest/pipelines.html#ci-yaml.

It is described further in https://spack.readthedocs.io/en/latest/pipelines.html#spack-ci-rebuild.

**Review by tldahlgren — COMMENTED** [review]
Would be preferable to add the package to the `ci:broken-tests-packages:` list.  Though I haven't checked to see if inheritance is override or additive (see https://github.com/spack/spack/blob/develop/share/spack/gitlab/cloud_pipelines/configs/ci.yaml).

**Review by tldahlgren — CHANGES_REQUESTED** [review]
My 2 cents about the configuration change.

**Comment by tldahlgren** [comment]
> My 2 cents about the configuration change.

It is calling `mpirun -n 4`.

**Comment by scottwittenburg** [comment]
I've seen `papyrus` do that in another stack as well (see [here](https://gitlab.spack.io/spack/spack/-/jobs/9025564)), so maybe it makes sense to just add it to the `broken-tests-packages` at the top level of the ci configs?

**Comment by alalazo** [comment]
Change done

**Review by tldahlgren — APPROVED** [review]
Thanks.

**Pull request merged**
