### PR TITLE
netlib-lapack: Apply ibm-xl-3.9.1 patch to cce

### PR DESCRIPTION
**Pull request by quellyn**
The somewhat inaccurately-named `ibm-xl.patch` and its successor `ibm-xl-3.9.1.patch` contain fixes that apply not only to `xl` and `xl_r` builds, but to Cray `cce` as well.

This PR updates the `cce` constraints so that
- `ibm-xl.patch` is applied to `netlib-lapack @3.7:3.8` on cce
- `ibm-xl-3.9.1.patch` is applied to `netlib-lapack @3.9.1` on cce

Note that the `ibm-xl-3.9.1.patch` has been accepted upstream and should be in future releases of `netlib-lapack`.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Review by alalazo — COMMENTED** [review]
The patch was already there, so fine with me to merge. Just wondering, if you have cycles, would you mind adding two comments (at line 44 and line 48) explaining what the patch does and maybe leave a reference to the PR that was accepted upstream?

**Comment by quellyn** [comment]
I added a brief description of the patches in the `package.py`, and a longer one at the top of each patch file (hope that's okay).

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
Asked for further review by @lukebroskop who certainly knows Cray specific requests better than me. Ping me in a few days if this PR seems stale to proceed with merging.

**Comment by quellyn** [comment]
@lukebroskop, have you had a chance to look this over before @alalazo pulls the trigger?

**Review by lukebroskop — APPROVED** [review]
@quellyn, LGTM!

**Pull request merged**
