### PR TITLE
Updating default tag for libcatalyst

### PR DESCRIPTION
**Pull request by ayenpure**
Updating the default tag from 2.0.0-rc4 to 2.0.0

### CODE REVIEW

**Comment by cquammen** [comment]
@ayenpure I think the URL for the tar ball needs to be updated, too. It was set by @mathstuf  2 years ago, so it can't be the 2.0.0 tar ball:

https://github.com/spack/spack/blame/develop/var/spack/repos/builtin/packages/libcatalyst/package.py#L19

The URL should be updated to

https://gitlab.kitware.com/paraview/catalyst/-/archive/v2.0.0/catalyst-v2.0.0.tar.gz

and the sha256 in this PR will need to be updated.

**Comment by mathstuf** [comment]
We should use official, static tarballs, not `/archive/` links. See #35250.

**Comment by ayenpure** [comment]
@spackbot re-run pipeline

**Comment by cquammen** [comment]
> We should use official, static tarballs, not `/archive/` links. See #35250.

Great. Where is the official static tarball for Catalyst 2.0?

**Comment by ayenpure** [comment]
> > We should use official, static tarballs, not `/archive/` links. See #35250.
> 
> Great. Where is the official static tarball for Catalyst 2.0?

**Comment by ayenpure** [comment]
> > We should use official, static tarballs, not `/archive/` links. See #35250.
> 
> Great. Where is the official static tarball for Catalyst 2.0?

I've got the same question @mathstuf

**Comment by ayenpure** [comment]
@cquammen The link in the file already downloads the latest source for v2.0.0
Also, the SHA of the package pointed by that link and the one from here seems to be the same
https://gitlab.kitware.com/paraview/catalyst/-/packages/277
@mathstuf are the packages available here manually uploaded -- and hence similar to the once "not in the archive"

**Comment by mathstuf** [comment]
CI uploads the releases. See job descriptions [here](https://gitlab.kitware.com/paraview/catalyst/-/blob/master/.gitlab/release.yml). I also recommend using the `https://gitlab.kitware.com/api/v4/projects/5912/packages/generic/catalyst/v2.0.0/catalyst-v2.0.0.tar.gz` URL as spack will be able to find-replace the version number in this URL accurately.

**Review by mathstuf — APPROVED** [review]

**Review by mathstuf — APPROVED** [review]

**Comment by mathstuf** [comment]
Apparently my review is not enough anymore :) . @alalazo ?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
