### PR TITLE
boost: Add 1.85.0

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by hainest — APPROVED** [review]
SHA confirmed. This release added charconv and scope. I'll take care of those in #30627.

**Comment by msimberg** [comment]
Ugh, the new `stacktrace` library leads to build errors on non-x86 platforms. The cause seems to be this change: https://github.com/boostorg/stacktrace/pull/150/files. The define that guards the `#error` is here: https://github.com/boostorg/stacktrace/blob/a33e198cf660c213e700d6f050a4641b74ea880a/src/exception_headers.h#L9-L13.

We could:
- make the new "stacktrace from exception" feature a variant that is off by default, and let those who enable it deal with the build failure locally
- define `BOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK` always when gcc is used since that can't use `libc++`, leave it up to users to define it in `cxxflags` with other compilers
- add conflicts with non-x86 platforms
- some combination of the above or something else?

From what I could tell all the failing CI configurations are using GCC, so only doing the second option as a first "get CI working" option seems reasonable to me, with potential conflicts/variants easily added later as needed. The fact that the `#error` in boost doesn't actually try to detect use of libc++ makes me suspicious about what the actual failing configurations are though...

@hainest do you have a preference here?

**Comment by hainest** [comment]
I would recommend adding a conflict when `+stacktrace +clanglibcpp` for `boost@1.85:`. That protects users from accidentally using the feature even if they aren't throwing exceptions concurrently, and likely covers the majority of use cases. If someone would like us to add the `BOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK` override, we can handle that in the future.

**Comment by hainest** [comment]
Ah, sorry, I somehow failed to grock the fact that it doesn't build on non-x86 (not finished my first coffee yet). It is unclear why this is failing in these cases. The `b2` invocation for `%gcc@11.4.0 arch=linux-ubuntu22.04-neoverse_v2 E4S ARM Neoverse V2` is

```
'./b2'
'install'
'threading=multi'
'-j' '2'
'--user-config=/tmp/root/spack-stage/spack-stage-boost-1.85.0-bpt2mjlwkwnfh2lv4m5yojafyr6yrjyb/spack-src/user-config.jam'
'variant=release'
'--disable-icu'
'-s'
'BZIP2_INCLUDE=...'
'-s'
'BZIP2_LIBPATH=...'
'-s'
'ZLIB_INCLUDE=...'
'-s'
'ZLIB_LIBPATH=...'
'-s'
'LZMA_INCLUDE=...'
'-s'
'LZMA_LIBPATH=...'
'-s'
'ZSTD_INCLUDE=...'
'-s'
'ZSTD_LIBPATH=...'
'link=static,shared'
'--layout=system'
'toolset=gcc'
'cxxstd=17'
'visibility=global'
```

which is definitely not arm-specific. I'll investigate.

**Comment by hainest** [comment]
I sent an email to the boost mailing list to make sure the current checks lead to an accidental error and that there isn't some hidden knowledge about why the non-padding version wouldn't work on non-x86+libstdc++ (even with clang). I'll update once I've heard back. We should still do the `clanglibcpp` for the general case, but we may also need to conflict for all non-x86.

**Comment by msimberg** [comment]
The builds seem to be running just fine with the added conflicts now, but perhaps good to still wait for a response from the Boost developers (in case there's a patch or similar that we can/need to apply).

**Review by tldahlgren — APPROVED** [review]
Also confirmed the sha256.

**Comment by balay** [comment]
One of my builds fails with this change. I can work-around with `^boost@1.84.0`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/6778628239

```
==> [2024-05-04-00:08:50.309758] './bootstrap.sh' '--prefix=/home/xsdk/builds/rZPizn2W/1/xsdk-project/spack-xsdk/opt/spack/linux-ubuntu20.04-skylake/oneapi-2022.2.0/boost-1.85.0-i6v3kyklfts5hfvlzxv2cjq3p7kvqnbi' '--with-toolset=intel-linux' '--with-libraries=exception,filesystem,graph,log,math,program_options,stacktrace,system,test,thread' '--without-icu'
Building B2 engine..

A C++11 capable compiler is required for building the B2 engine.
Toolset 'intel-linux' does not appear to support C++11.

> /home/xsdk/builds/rZPizn2W/1/xsdk-project/spack-xsdk/lib/spack/env/oneapi/icpx -x c++ -std=c++11  check_clib.cpp check_cxx11.cpp
/usr/bin/ld: /tmp/check_cxx11-e3c094.o: in function `main':
check_cxx11.cpp:(.text+0x71): undefined reference to `pthread_create'
```

**Comment by hainest** [comment]
@balay That is because many of the Boost libraries require at least C++11 as of 1.85.0. If your compiler doesn't support that version of the standard, then you'll have to continue to use 1.84.0.

**Comment by balay** [comment]
> check_cxx11.cpp:(.text+0x71): undefined reference to `pthread_create'

Likely the above c++11 test is broken [i.e missing `-lpthread`?]

The above build is with `oneapi@2022.2.0` [on Ubuntu 20.04 and gcc@9.4.0] which should support cxx11

**Comment by hainest** [comment]
Yeah, that's something different. Could you open a separate issue for this?

**Comment by balay** [comment]
Ok - filed at https://github.com/spack/spack/issues/44003

**Pull request merged**
