### PR TITLE
Add Orca version 5.0.3-f.1

### PR DESCRIPTION
**Pull request by awvwgk**

### CODE REVIEW

**Comment by snehring** [comment]
@awvwgk where can I find this version's archive?

**Comment by awvwgk** [comment]
That version is distributed by [faccts](https://faccts.de).

**Comment by snehring** [comment]
Guessing that's not freely available. I'll just assume the hash is correct and this installs as expected. It may be worthwhile to note somewhere that the -f version is distributed from faccts.

**Review by snehring — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
