### PR TITLE
containers: Don't install epel-release on Fedora

### LINKED ISSUE #37765: containerize: Fedora fails to find `epel-release`
### Steps to reproduce

```console
$ cat spack.yaml
spack:
  specs: [zlib]
  container:
    images:
      os: fedora:37
      spack: develop
    os_packages:
      final: [gcc]
$ spack containerize > Dockerfile
$ buildah build --format=docker
```

### Error message

```console
... snip ...
Last metadata expiration check: 0:00:05 ago on Thu May 18 15:38:24 2023.
No match for argument: epel-release
Error: Unable to find a match: epel-release
error building at STEP "RUN yum update -y && yum install -y epel-release && yum update -y  && yum install -y gcc  && rm -rf /var/cache/yum  && yum clean all": error while running runtime: exit status 1
```
This error comes from this incorrect command in the generated `Dockerfile`:
```dockerfile
RUN yum update -y && yum install -y epel-release && yum update -y \
 && yum install -y gcc \
 && rm -rf /var/cache/yum  && yum clean all
```
Fedora does not have (nor does it require) `epel-release`. That package is specific to RHEL and its rebuilds Alma Linux and Rocky Linux.

### Information on your system

* **Spack:** 0.21.0.dev0 (c2ce9a6d930891c708d822be8ce22aa5f12a58ee)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

### PR DESCRIPTION
**Pull request by blue42u**
Fixes https://github.com/spack/spack/issues/37765

This PR specializes the "`yum update`" command sequence for Fedora, to remove the attempt to install `epel-release`.

### CODE REVIEW

**Review by michaelkuhn — COMMENTED** [review]
Since we only support Fedora 37 and 38, can we just change this to use DNF? Yum is just a symlink to DNF nowadays. Moreover, `/var/cache/yum` actually does not exist on Fedora anymore.

**Review by alalazo — CHANGES_REQUESTED** [review]
I kind of agree with @michaelkuhn Also, there is a documentation update in a reference table at https://spack.readthedocs.io/en/latest/containers.html#configuration-reference missing.

**Comment by blue42u** [comment]
Agreed. I've swapped out all usage of `yum` for `dnf` in relevant images: Alma/Rocky 8/9, Fedora 37/38, and CentOS Stream. The new options for `os_packages:command` are `"dnf"` (for Fedora) and `"dnf_epel"` (for the others).

**Comment by blue42u** [comment]
To get this to pass CI I've disabled the `rockylinux:9` images for `ppc64le`, since [`ppc64le` is held back upstream with the Rocky 9.2 release](https://docs.rockylinux.org/release_notes/9_2/) and accordingly the [upstream Docker tag does not include a `ppc64le` version](https://hub.docker.com/layers/library/rockylinux/9/images/sha256-3387f6adc2fcdba59b9ff07acb955b4dbb610d3d93f7c68182107c1d25fac39c?context=explore).

This should, in theory, be a temporary change.

**ADD:** This 1-line change has been merged in https://github.com/spack/spack/pull/38202, and thus has been dropped from this PR.

**Review by alalazo — APPROVED** [review]
LGTM I'll give it a test drive later in the day and merge.

**Comment by alalazo** [comment]
Thanks!

**Pull request merged**
