### PR TITLE
Update HDF5 VOL async

### PR DESCRIPTION
**Pull request by jeanbez**
Include new release, fix prefered version and fix environment variable.

### CODE REVIEW

**Review by hyoklee — APPROVED** [review]

**Review by houjun — APPROVED** [review]

**Comment by hyoklee** [comment]
@spackbot re-run ci

**Review by hyoklee — APPROVED** [review]

**Comment by hyoklee** [comment]
@tldahlgren, GitLab CI is stuck so I can't merge PR. Please help!

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
> @tldahlgren, GitLab CI is stuck so I can't merge PR. Please help!

If it happens again, you can try the command I entered.  IIRC you should be able to run it yourself.

**Comment by tldahlgren** [comment]
Wow! They all appeared to pass too.

**Comment by tldahlgren** [comment]
🤔 That Pending reason is relatively new.

**Comment by hyoklee** [comment]
Is there a way to merge without waiting for ci/gitlab-ci?

**Comment by tgamblin** [comment]
Not generally — we want to make sure everything builds with the new release.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
