### PR TITLE
python: add 3.10.7, 3.9.14, 3.8.14, 3.7.14

### PR DESCRIPTION
**Pull request by zzzoom**

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
Thanks!

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Review by adamjstewart — DISMISSED** [review]

**Comment by adamjstewart** [comment]
@spackbot run pipeline

**Comment by michaelkuhn** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@adamjstewart believe it or not, but this PR is merge-able!

**Review by haampie — APPROVED** [review]

**Comment by adamjstewart** [comment]
Miracles do happen!

**Pull request merged**
