### PR TITLE
bml: add shared variant

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
ping @davydden

**Comment by davydden** [comment]
I already approved, I don't have merge rights

**Comment by junghans** [comment]
@scheibelp: I don't like to merge my own PR.

**Comment by scheibelp** [comment]
> @scheibelp: I don't like to merge my own PR.

I prefer that too (and you shouldn't have to). That being said when I merge a PR I like to have reviewed it myself. In this case the changes follow the format of some other PR's I've looked at so it's easy. In general I can't guarantee that. If I haven't commented in the thread or merged it, you can assume I haven't reviewed it. So generally feel free to ping me and I'll add it to my queue.

**Pull request merged**
