### PR TITLE
NextFlow: Add versions 24.10.2 and  24.10.3.

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Review by dialvarezs — COMMENTED** [review]
Thank you for this. The checksum is ok.

Could you please also add v24.10.3?

**Comment by RemiLacroix-IDRIS** [comment]
> Could you please also add v24.10.3?

Done, it was released in the meantime. I could drop version 24.10.2 if you want.

**Review by dialvarezs — APPROVED** [review]
Fot me it's ok to leave both. Thanks.

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256s.

**Pull request merged**
