### PR TITLE
CI: TensorFlow needs huge runners

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Add the TensorFlow package to the Huge mapping group.

### CODE REVIEW

**Review by scottwittenburg — APPROVED** [review]
Even though the failures we were looking at this morning were in the ml stacks (where `py-tensorflow` is already mapped to the largest resource requests), it seems like it can't hurt to make sure this is the case everywhere.

**Comment by kwryankrattiger** [comment]
I am going to close this in favor of #35996 which is likely a better solution

**Comment by haampie** [comment]
it probably still needs "huge" runners, -j8 is gonna take an eternity, that's for sure.

**Comment by kwryankrattiger** [comment]
The boilerplate PR had already moved it to "huge"

**Pull request closed without merging**
