### PR TITLE
perl-exporter: add new package

### PR DESCRIPTION
**Pull request by ChristopherChristofi**

### CODE REVIEW

**Review by EbiArnie — CHANGES_REQUESTED** [review]
Exporter is a core Perl package - it is always there when you install Perl. It should not become a separate package in my opinion.

**Comment by EbiArnie** [comment]
See here: https://perldoc.perl.org/modules

**Comment by tldahlgren** [comment]
@ChristopherChristofi Do you want to just close this PR then?

**Comment by ChristopherChristofi** [comment]
```
Data for 2023-07-02
Exporter was first released with perl 5
```
Has been a core module since version 5, which pre-dates all end of life Perl releases in spack

**Pull request closed without merging**
