### PR TITLE
Hotfix: Fix CI unit test after CI refactor

### PR DESCRIPTION
**Pull request by kwryankrattiger**
Follow up to fix unit-test

CC: @haampie

### CODE REVIEW

**Comment by haampie** [comment]
Uhm, I didn't follow the boilerplate PR much, but if there's a breaking change in yaml keys, then please don't make the old key an error, but allow both until the next Spack release.

**Comment by haampie** [comment]
@spackbot fix style

**Comment by kwryankrattiger** [comment]
The refactor completely restructured the CI section of the config, there wasn't really a way to support both.

**Comment by kwryankrattiger** [comment]
The refactor completely restructured the CI section of the config, there wasn't really a way to support both.

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
The failure on `macos` is unrelated...

> FAILED lib/spack/spack/test/install.py::test_install_prefix_collision_fails[mock_archive0] - spack.build_environment.ChildError: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/runner/spack-stage/spack-stage-libelf-0.8.13-u6xq6fpjaupqxokh2w53qucwxoiuow54/spack-build-out.txt'

It happens quite often there.

**Comment by haampie** [comment]
lmao, if this PR  is not force merged, it's also blocked by gitlab CI, because that needs to run on the commit that introduced the unit test failure first :laughing:

**Comment by kwryankrattiger** [comment]
@tgamblin @alalazo @adamjstewart

**Comment by becker33** [comment]
@kwryankrattiger we 100% need to be able to read old environments with the old key, or at least provide a `spack config update` command that will fix them

**Comment by tgamblin** [comment]
@kwryankrattiger: I missed this concern:
> The refactor completely restructured the CI section of the config, there wasn't really a way to support both.

we need a way to support the old CI at least as deprecated.  We've done this before with other schemas.

**Pull request merged**
