### PR TITLE
Tau rocm fix

### PR DESCRIPTION
**Pull request by lukebroskop**

### CODE REVIEW

**Review by khuck — CHANGES_REQUESTED** [review]
I think this needs support for roctracer, too.

**Comment by lukebroskop** [comment]
@khuck, I agree. Let me add that it.

**Review by tldahlgren — APPROVED** [review]

**Review by khuck — APPROVED** [review]
Looks good, thanks!

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
