### PR TITLE
cmake: add v3.30.3, v3.30.4, v3.30.5

### PR DESCRIPTION
**Pull request by johnwparent**
Adds CMake 3.30.3 and 3.30.4

### CODE REVIEW

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Review by eugeneswalker — DISMISSED** [review]

**Comment by eugeneswalker** [comment]
Lots of CI failures here, they seem unrelated to content of the PR. ParaView is failing all over the place due to timeout, a known issue. And openfoam is failing. I don't think it's the PR here. We may need to wait for this to be fixed on develop and then re-base on the fixed develop/

**Comment by johnwparent** [comment]
@spackbot run pipeline

**Review by bernhardkaindl — APPROVED** [review]
Rebased on yesterday's `develop`: The timeouts were due to a severe performance regression in the compiler wrapper: Thus we have to re-base all PR that fail from that commit to a recent develop that has the fix.

**Review by bernhardkaindl — DISMISSED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants cmake@3.30.4%clang@14.0.0 cmake@3.30.4%gcc@9.5.0 cmake@3.30.4%gcc@13.1.0 cmake@3.30.4%gcc@12.3.0 cmake@3.30.4%gcc@11.4.0 cmake@3.30.4%gcc@10.5.0 cmake@3.30.3%clang@14.0.0 cmake@3.30.3%gcc@9.5.0 cmake@3.30.3%gcc@13.1.0 cmake@3.30.3%gcc@12.3.0 cmake@3.30.3%gcc@11.4.0 cmake@3.30.3%gcc@10.5.0
-- linux-ubuntu22.04-skylake / clang@14.0.0 ---------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
cmake@3.30.3~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
cmake@3.30.4~doc+ncurses+ownlibs~qtgui build_system=generic build_type=Release patches=dbc3892
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
/home/bkaindl/build-quality-tools/build_pr_changes.py -c all -may
```

**Review by bernhardkaindl — APPROVED** [review]
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants cmake@3.30.5
-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
cmake@3.30.5+ncurses+ownlibs build_system=generic patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
cmake@3.30.5+ncurses+ownlibs build_system=generic patches=dbc3892

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
cmake@3.30.5+ncurses+ownlibs build_system=generic patches=dbc3892
```

Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
/home/bkaindl/build-quality-tools/build_pr_changes.py -k cmake v3 -b cmake@3.30.5 -may
```

**Pull request merged**
