### PR TITLE
vecgeom: new version 1.2.5

### PR DESCRIPTION
**Pull request by sethrj**

### CODE REVIEW

**Comment by drbenmorgan** [comment]
@spackbot help

**Comment by drbenmorgan** [comment]
@spackbot fix style

**Review by drbenmorgan — DISMISSED** [review]
Hash is good, style fixed so good to merge on CI success. Thanks @sethrj!

**Comment by wdconinc** [comment]
It's slightly OT, but I'm getting sha256 failures on the previous 1.2.4 version (not earlier). Did something change?

```console
$ curl -L https://gitlab.cern.ch/VecGeom/VecGeom/-/archive/v1.2.4/VecGeom-v1.2.4.tar.gz | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2444k    0 2444k    0     0  1769k      0 --:--:--  0:00:01 --:--:-- 1769k
4f5d43a9cd34a5e0200c41547a438cbb1ed4439f5bb757857c5a225d708590ce  -
```

**Comment by sethrj** [comment]
Oh crap, this is because of the `export-subst` gitattribute property: the same thing happened to celeritas in #32000 . The git archive *does* change the content of the download.

I reported this to @tgamblin and he said he'd seen the same thing, and furthermore he makes a habit of downloading the archive **and re-uploading as an artifact** to avoid hash changes due to opaque changes in server-side compression behavior.

@agheata I've used the GitLab "release" interface to formally create archived repository data for the past two releases. We should use that interface henceforth rather than simply pushing a tag.

**Review by tldahlgren — APPROVED** [review]
Confirmed the three new version sha256.

**Comment by wdconinc** [comment]
Is the hash for 1.2.5 really going to be more stable now? It still refers to the branch https://gitlab.cern.ch/VecGeom/VecGeom/-/tree/v1-patches inside the describe line https://gitlab.cern.ch/VecGeom/VecGeom/-/blob/v1.2.5/cmake/CgvFindVersion.cmake#L93 inside the archive. As soon as that branch either disappears or gets another commit, then the hash for 1.2.5 will change, right? Or what if another branch is created that points to the same hash, does it not get added to the `$Format:%D$` anyway? Can we verify that before merging?

**Comment by sethrj** [comment]
I'm hoping that since I created a "gitlab release" for it, which claims to "archive a copy of the source code", it will be stable. I can't really test it until we have another point release (or other change that affects the git description).

**Comment by agheata** [comment]
> @agheata I've used the GitLab "release" interface to formally create archived repository data for the past two releases. We should use that interface henceforth rather than simply pushing a tag.

OK, noted :+1:

**Comment by sethrj** [comment]
Apparently the "release" archive isn't stable either 😞 @stognini reports the checksum has changed.

**Pull request merged**
