### PR TITLE
python: RPATH on Cray

### PR DESCRIPTION
**Pull request by mjwoods**
On a Cray system, I had a number of python packages fail to build (e.g. py-numpy, py-netcdf4). In each case, gcc was being passed a `-R` option to set the RPATH, but gcc on linux requires the decorated form `-Wl,-R` to pass the `-R` option to the linker.

It turns out that python distutils uses a (self-described) "Hackish" method to guess the correct compiler options for setting RPATH (see Lib/distutils/unixccompiler.py). The identity of the compiler is guessed from the basename of the compiler executable, which is `cc` for all compilers when using the Cray compiler driver.

My solution involves patching the unixccompiler.py script on Cray systems when using gcc (or intel compilers, which use the same options for RPATH). With this patch, py-numpy and py-netcdf4 both installed without errors.

This patch may have some relevance to numpy/numpy#8653. Intel compilers would not be identified as gcc, and would therefore use an undecorated `-R` option to set the RPATH. (Update - my tests show that the rpath option is not being used at all in numpy builds with intel. I wonder why?)

### CODE REVIEW

**Comment by becker33** [comment]
@lee218llnl it would be great if you could take a look at this. It looks good to me, but I'm not as familiar with the python build system.

**Comment by mjwoods** [comment]
Hi @lee218llnl - as requested, my latest commit patches the `runtime_library_dir_option` function instead of `_is_gcc`. The two versions of the patch work for all released versions of python from 2.3 up to 3.6.1. I have removed `%gcc` and `%intel` from `when` arguments in package.py, because the patches should also work for Cray and PGI compilers (on Cray Linux) - although I haven't tested these compilers with python.

(Travis-CI checks are currently failing. There seems to be a bug in another package. The error message says: `Error: Class constructor failed for package 'builtin.antlr'`).

**Comment by mjwoods** [comment]
It turns out that I had a syntax error in my package.py. I had to test without the `platform=cray` restriction today, because I cannot access the Cray from this machine. It seems that the `when` argument of `patch()` is a bit fussy when multiple specs are included in the string.

**Comment by lee218llnl** [comment]
It sounds like a bug in Spack that you needed to add the "4.0" in when="@3.1:4.0". The "@3.1:" should work and I believe it is OK in other packages. @tgamblin and @becker33 are you aware of any other reports of this problem? @mjwoods, can you describe the problem you saw before you added the "4.0"?

The potential Spack bug aside, I might suggest making the terminal version 3.99 instead of 4.0. If/when a 4.0 version is released, we will probably have to re-evaluate this patch anyway.

**Comment by adamjstewart** [comment]
@lee218llnl I think the problem that @mjwoods is referring to will be fixed by #4199. Basically:
```python
when='@3.1:'
```
works fine, but:
```python
when='@3.1: platform=cray'
```
crashes. Spack tries to interpret `platform=cray` as the end version number.

**Comment by lee218llnl** [comment]
Thanks @adamjstewart. If that is the case, I might suggest undoing the last commit (i.e., remove the "4.0") and then rebase with develop once #4199 is merged.

**Comment by mjwoods** [comment]
I've chosen to limit the patches to `python@:3.99`. We can safely assume that the transition from python 3 to 4 will cause problems.

**Comment by mjwoods** [comment]
It looks like Travis-CI died - all test jobs were cancelled. I'll close and reopen the issue to trigger a rebuild.

**Comment by adamjstewart** [comment]
Don't worry about Travis until #4266 is merged. The documentation tests are broken for everyone in the meantime.

**Comment by mjwoods** [comment]
Hi @adamjstewart and @lee218llnl , Travis-CI is working again. Can you please have another look at this merge request?

**Comment by adamjstewart** [comment]
I don't use Cray, so I'll leave this up to someone else to test.

**Comment by lee218llnl** [comment]
I'm not going to be able to test this on a Cray, but it LGTM.

**Pull request merged**
