### PR TITLE
openblas and others: change flag_handler idiom to respect incoming flags

### PR DESCRIPTION
**Pull request by becker33**
A few packages have an idiom in flag_handler that ignores all flags from the spec

```
flag_handler(self, name, flags):
    iflags = []
    ...  # does not add flags to iflags
    return (iflags, None, None)
```

This PR removes this idiom.

### CODE REVIEW

**Comment by Chrismarsh** [comment]
I tested this on macos with develop spack. The PR resolves the issue I had with Openblas

**Comment by haampie** [comment]
curious, was this pattern promoted somewhere? or just copy/paste?

**Review by eugeneswalker — APPROVED** [review]
Thanks!

**Comment by eugeneswalker** [comment]
> curious, was this pattern promoted somewhere? or just copy/paste?

This pattern wasn't mine originally, but I did copy+paste it into a couple places when I needed to add some flags. I had grepped other packages to see how they setup the `flag_handler` method and did not pay as much attention as I should have, as, looking at it now, I see this is not something one would generally want! My apologies.

**Pull request merged**
