### PR TITLE
Molden: update URLs.

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256 are unchanged by the URL changes.

**Comment by tldahlgren** [comment]
Will defer merge decision until @dev-zero  has a chance to comment.

**Comment by tldahlgren** [comment]
Hmmm.  The `develop` pipeline already succeeded so this isn't getting updated.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by dev-zero — APPROVED** [review]

**Pull request merged**
