### PR TITLE
e4s ci: add packages: drishti, dxt-explorer

### PR DESCRIPTION
**Pull request by eugeneswalker**
E4S CI: adding new packages:
* `drishti`
* `dxt-explorer`

If there are any non-default variants we should be building as part of CI here, let us make those changes here.
@jeanbez @sbyna

### CODE REVIEW

**Comment by jeanbez** [comment]
@eugeneswalker, no variants so we should be good.

**Comment by eugeneswalker** [comment]
OneAPI CI is failing to get to the `dxt-explorer` build because of the following failures:
* [r/yy5rhf6 4.3.0 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8031830)
* [py-pandas/drit3bz 0.24.2 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8031833)

I will investigate and update this PR accordingly.

**Comment by jeanbez** [comment]
> OneAPI CI is failing to get to the `dxt-explorer` build because of the following failures:
> 
> * [r/yy5rhf6 4.3.0 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8031830)
> * [py-pandas/drit3bz 0.24.2 oneapi@=2023.2.0 linux-ubuntu20.04-x86_64 E4S OneAPI](https://gitlab.spack.io/spack/spack/-/jobs/8031833)
> 
> I will investigate and update this PR accordingly.

hi @eugeneswalker thank for looking into that! Did you find out what was causing the failure?

**Comment by eugeneswalker** [comment]
@spackbot run pipeline

**Comment by eugeneswalker** [comment]
> hi @eugeneswalker thank for looking into that! Did you find out what was causing the failure?

Not exactly. There've been a lot of updates, some of which I believe will help resolve the errors we were seeing before. I'm trying to get an up to date pipeline so we can assess where we are at and get this across the finish line. I will take inventory of any remaining build errors here ASAP.

**Comment by eugeneswalker** [comment]
The only blocker right now that we can't build `dxt-explorer`'s dependency `r` in our E4S OneAPI stack.
* https://github.com/spack/spack/issues/40257

I am updating this PR to comment out dxt-explorer from the OneAPI stack in the meantime. When the build issue with `r`  is resolved we can enable it at that time.

**Review by sethrj — APPROVED** [review]

**Pull request merged**
