### PR TITLE
bugfix : spack mirror add too verbose

### PR DESCRIPTION
**Pull request by roottreej**
Proposition to get only one value of  'spack mirror add foo /my_path '  command.       Actually, two elements are added to yaml file (.spack/mirrors.yaml) and same two mirror are visible by 'spack mirror list' command.
```yaml
mirrors:
  foo:
    fetch:
      url: file:///my_path
    push:
      url: file:///my_path
```
With this simple proposition, we could add only once mirror.

### CODE REVIEW

**Comment by roottreej** [comment]
mail to @Jordan474

**Comment by roottreej** [comment]
Just to precise some extra informations (in my opinion) on file .spack/mirrors.yaml.
The full signature of this redondant information is so verbose.
```yaml
mirrors:
  foo:
    fetch:
      url: file:///my_path
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///my_path
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
```

**Comment by roottreej** [comment]
with this simple proposition, with "spack mirror add foo /my_path" we only get
```yaml
mirrors:
  foo: file:///my_path
```

**Comment by haampie** [comment]
How about something like

```diff
diff --git a/lib/spack/spack/mirror.py b/lib/spack/spack/mirror.py
index 8e914306e0..987af03bc5 100644
--- a/lib/spack/spack/mirror.py
+++ b/lib/spack/spack/mirror.py
@@ -524,7 +524,7 @@ def mirror_cache_and_stats(path, skip_unstable_versions=False):
     return mirror_cache, mirror_stats
 
 
-def add(name, url, scope, args={}):
+def add(name, url, scope, args):
     """Add a named mirror in the given scope"""
     mirrors = spack.config.get("mirrors", scope=scope)
     if not mirrors:
@@ -534,18 +534,20 @@ def add(name, url, scope, args={}):
         tty.die("Mirror with name %s already exists." % name)
 
     items = [(n, u) for n, u in mirrors.items()]
-    mirror_data = url
-    key_values = ["s3_access_key_id", "s3_access_token", "s3_profile"]
-    # On creation, assume connection data is set for both
-    if any(value for value in key_values if value in args):
-        url_dict = {
-            "url": url,
-            "access_pair": (args.s3_access_key_id, args.s3_access_key_secret),
-            "access_token": args.s3_access_token,
-            "profile": args.s3_profile,
-            "endpoint_url": args.s3_endpoint_url,
-        }
+
+    if args.s3_access_key_id or args.s3_access_key_secret or args.s3_access_token or args.s3_profile or args.s3_endpoint_url:
+        url_dict = {"url": url}
+        if args.s3_access_key_id and args.s3_access_key_secret:
+            url_dict["access_pair"] = (args.s3_access_key_id, args.s3_access_key_secret)
+        if args.s3_access_token:
+            url_dict["access_token"] = args.s3_access_token
+        if args.s3_profile:
+            url_dict["profile"] = args.s3_profile
+        if args.s3_endpoint_url:
+            url_dict["endpoint_url"] = args.s3_endpoint_url
         mirror_data = {"fetch": url_dict, "push": url_dict}
+    else:
+        mirror_data = url
 
     items.insert(0, (name, mirror_data))
     mirrors = syaml_dict(items)
```

The default value for `arg` was also wrong given that the rest uses `args.s3...`

**Comment by roottreej** [comment]
I just tested proposition https://github.com/spack/spack/pull/34210#issuecomment-1332355474 of @haampie and I agree with that.

**Comment by haampie** [comment]
Actually, can we reduce verbosity even more?

```yaml
mirrors:
  name:
    url: s3://bucket
    access_pair: [x, y]
```

instead of duplicating `pull` / `fetch`?

We don't have the command line options to differentiate between pull/fetch anyways.

It's sure useful to set say http:// fetch urls without auth, and s3:// push urls with auth, but as long as we can't do that from the command line, it's still just too much yaml.

**Comment by haampie** [comment]
What's the status here?

**Comment by roottreej** [comment]
In my opinion, I agree with https://github.com/spack/spack/pull/34210#issuecomment-1332355474, so I commit it.    
But not agree with extreme verbosity reduce on https://github.com/spack/spack/pull/34210#issuecomment-1350807884.

**Comment by haampie** [comment]
Ok, I just rebased onto develop and pushed some changes because tests were failing

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
Thanks @roottreej for starting this :D

**Comment by roottreej** [comment]
Thank you @haampie for your interesting proposition at https://github.com/spack/spack/pull/34210#issuecomment-1332355474/ :)

**Pull request merged**
