### PR TITLE
Mesa: newer versions and off-screen rendering

### PR DESCRIPTION
**Pull request by olesenm**

### CODE REVIEW

**Comment by olesenm** [comment]
Independent of spack, my experience with building mesa-12 versions has been suboptimal. I never seemed to be able to generate GL includes with those versions. Older and newer ones seem to work.

**Comment by adamjstewart** [comment]
There are currently 4 open PRs for Mesa: #4134 (@luigi-calori), #4258 (@mjwoods), #4316 (@JusticeForMikeBrown), and now #4602 (@olesenm). They all make similar changes, but go about it in different ways. Since I don't know any more about Mesa than the rest of you, I don't know which one to merge. I would like all of you to test out each others PRs and hopefully agree on a single PR that will solve all of your problems. Then I can merge whichever one you decide on.

**Comment by luigi-calori** [comment]
I' m still newbie regardin github workflow: 
Is it possible to have PR on PR's or to have a branch where we could work together?
Mesa is quite long to build and, in order to test in my environment,  I need spack X11 stack and turbovnc,
plus some binary opengl code like ParaView.
I test it with module environment so to be able to do 
`module load mesa`
that set up runtime LD_LIBRARY_PATH  to spack installed mesa as well as GALLIUM_DRIVER
variable to 'swr'

I set up this following  suggestion for running paraview on headless ( no GPU ) nodes 

https://www.paraview.org/Wiki/ParaView/ParaView_And_Mesa_3D

I tested it on broadwell nodes, performance are good provided you use at least 8 cores.

I did tested mesa 13, maybe the 14 version does not need those setups but I  think that LD_LIBRARY_PATH is required to support running binaries that do not have any rpath

If some of the other PR has been tested on a configuration similar to  mine, I can try it and see how' s working for me

**Comment by adamjstewart** [comment]
Yes, you can all work together on the same branch if you want to. You can create that branch from LLNL/spack or from any fork you want to. The person who creates the branch may have to click a checkbox to allow edits from maintainers or something like that. I've never done it before, but it works.

**Comment by adamjstewart** [comment]
Alternatively, if you all agree that one of these PRs is "good enough for now", I can merge it and you can rebase your PRs off of the latest develop and add any additional things you've found you need.

**Comment by olesenm** [comment]
I am perfectly happy to leave the mess of building mesa to one of the other pull requests. It would be nice to avoid too many tiny options, but I'll take whatever people decide on and work from there. The llvm update alone (to version 4.0.0) might be nice to have as a cherry-pick though.

**Comment by luigi-calori** [comment]
I' m fine to test llvm 4.0 and latest mesa, my only requirements are env setup to allow for opengl binary execution and gallium performance driver. It seems to  me gallium is more specific than osmesa
If you have tested spack dependency on osmesa, without the setup_dependent_environment, it is likely it' s not needed 
I would like to test it with both binary as well as spack built sw ( I was thinking of ParaView, but any other would be ok) using opengl in interactive way through VNC
On my side, is also ok to have other PR merged first and then add my stuff as a more specific variant

**Comment by davydden** [comment]
A master student of mine needed to install paraview with mesa on a cluster and we successfully used one of the @luigi-calori 's branches. I think it was prior to PR mentioned above, but must be similar.

**Comment by olesenm** [comment]
Hi Luigi (@luigi-calori), good to see a familiar face. My changes are a minimal changeset that reflect what some people have been using with OpenFOAM third-party, but it is not going to be as stress-tested as what CINECA will have. If we move ahead with @mjwoods PR as a basis, it could be helpful if you rebase on that, but also squash together some of your commits to reduce intermediate noise.

Re: MESA, I've heard various conflicting reports of the speed of with/without the llvmpipe. It'd be interesting to see what you've seen. BTW: there was also a note on the paraview mailing list about needing to limit the number of threads per mpi proc so that machine doesn't get flooded (essentially each mpi proc each trying to grab all cores). This was mentioned a few months back.

**Comment by JusticeForMikeBrown** [comment]
@olesenm 

I don't think this will build on Centos / RHEL6

Can you add my things from #4316 that make it possible?

```
import distro

    def configure_args(self):
        spec = self.spec
        v = distro.linux_distribution()[1]
        distname = distro.linux_distribution()[0]

        # libudev too old on centos / rhel 6 so do sysfs
        if distname == "RedHatEnterpriseServer" or distname == "CentOS":
            if Version('6.0') <= Version(v) <= Version('6.999'):
                args = ['--enable-sysfs']
            else:
                args = []
        else:
            args = []
```

**Comment by olesenm** [comment]
Still waiting for email response from @mjwoods .

**Comment by JusticeForMikeBrown** [comment]
Can we please merge?

@olesenm can you please add logic that will allow to build on centos / rhel 6?

**Comment by adamjstewart** [comment]
Since we seem to have reached an impasse with the other 3 PRs and multiple people seem to be in favor of this PR, I'm going to merge this one first. For the other 3 people who have created PRs, if there is still something missing, can you rebase off of develop and update your PRs? If not, feel free to close them. Thanks for your patience everyone!

**Comment by olesenm** [comment]
Hi @adamjstewart ,  sorry about this - we hadn't actually reached an impasse, we (Milton, Luigi and myself) took it off-line for some reworking: https://github.com/olesenm/spack/tree/mesa-unified

... where we tried to incorporate and consolidate everything. I'll put some of the blame on @mjwoods (was waiting for more of his feedback) and some on me (I was travelling and not paying any more attention to this PR). No blame left for Luigi!

Nonetheless, the good news is that the three of us are principally very largely in agreement and we just need some fine-tuning and testing to check that we have everything covered.  When it is done, it will mostly resemble the mesa-unified branch, which I could also slate for a PR (soon, I hope -> @mjwoods ??)

**Comment by adamjstewart** [comment]
No worries, just rebase it off of develop and it should be good to go. Unless you want to revert this one first.

**Comment by mjwoods** [comment]
Hi @olesenm ,  in my tests of the mesa-unified branch, I found that glx support is only provided by the +hwrender variant. I also found that +hwrender fails to build on RHEL6 (with the system compiler). That rules out my main use case for mesa, which is to run basic opengl applications on remote hosts running RHEL6. (The hosts do not provide their own opengl/glx libraries, which is my main reason for installing mesa through spack).

I think we need to reorganise things a bit. For example, the hwrender variants enable/disable a number of features that seem unrelated to hardware rendering, such as egl and glx-tls.

**Comment by olesenm** [comment]
Hi Milton @mjwoods, glad you can look at this. Do what you need to sort things out and we'll go in the next round.

@adamjstewart No need to revert - I've rebased off of develop. The next pull request could come from either Milton or myself. judging by his email address, it's winter there and he has lots of time ;)

**Comment by mjwoods** [comment]
Hi @olesenm , I have a suggested change to your mesa-unified branch that builds the main opengl libraries by default. This allows downstream packages to depend on mesa for opengl support, without requiring special variants of mesa (+hwrender) which are difficult to build on some platforms (e.g. RHEL6). For details, please see https://github.com/mjwoods/spack/commit/9fe2d042cf96bd566e13529b976df3ed9ff08c92

With this change, I have successfully built the default mesa package on RHEL6 using the native compiler. I have also built all of the mesa variants and versions on RHEL7 using the native compiler. I have checked that many of the mesa variants (except +llvm) and versions can be built on RHEL6 using newer gcc compilers from spack.

@olesenm - are you happy to include my changes into mesa-unified?

**Comment by mjwoods** [comment]
For the record, I also checked that mesa+llvm builds on RHEL6, using gcc@4.8.5 and gcc@6.3.0. The main difficulty was building llvm, which requires a newer binutils than the platform provides. Thankfully the spack package binutils+gold+plugins can be loaded as a suitable replacement.

**Pull request merged**
