### PR TITLE
hypre: fix a bug with blas/lapack names

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/LLNL/spack/issues/1840

@sarich ping

### CODE REVIEW

**Comment by tgamblin** [comment]
@sarich: does this fix your issue?

**Comment by tgamblin** [comment]
@davydden that was fast :smile:

**Comment by sarich** [comment]
How do I check out the branch to test? (davydden:bugfix/hypre_blas_lapack)

**Comment by davydden** [comment]
just copy-paste the changes, simplest in this case

**Comment by sarich** [comment]
That change works, thanks for the quick reply

Jason

**Pull request merged**
