### PR TITLE
Amrex: switch from CMake to makefiles

### LINKED ISSUE #5812: Amrex fails to build with intel
```
spack install amrex%intel@17.0.1
...
     167   cd /tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build/Src/Base && /home/certik/repos/spack/opt/spack/linux-fedora25-x86_64/intel-17.0.1/openmpi-2.1.1-u2jgcqpr5pyxnqnotrpjyrg53ypfzvki/bin/mpic++  -DBL_FORT_USE_UNDERSCORE -DBL_Linux -DBL_NOLINEVALUES -DBL_PARALLEL_IO -DBL_SPACEDIM=3 -DBL_USE_DOUBLE -DBL_USE_MPI -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Boundary -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Particle -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Amr -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/AmrCore -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_CellMG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_TensorMG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_to_F_MG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Extern/amrdata -I/home/certik/repos/spack/opt/spack/linux-fedora25-x86_64/intel-17.0.1/openmpi-2.1.1-u2jgcqpr5pyxnqnotrpjyrg53ypfzvki/include  -DBL_USE_FORTRAN_MPI=1 -DBL_USE_F_BASELIB=1 -std=c++11 -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/box_c.dir/AMReX_Orientation.cpp.o -c /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_Orientation.cpp
  >> 168   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(240): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     169          call amrex_abort("amrex_parmparse: get_intarr failed to get "
     170   --------------------------------------------------------------------^
  >> 171   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(255): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     172          call amrex_abort("amrex_parmparse: get_realarr failed to get "
     173   ---------------------------------------------------------------------^
  >> 174   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(275): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     175          call amrex_abort("amrex_parmparse: get_stringarr failed to get "
     176   -----------------------------------------------------------------------^
     177   compilation aborted for /tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build/Src/Base/AMReX_parmparse_mod.F90.f90 (code 1)
  >> 178   Src/Base/CMakeFiles/box_c.dir/build.make:1297: recipe for target 'Src/Base/CMakeFiles/box_c.dir/AMReX_parmparse_mod.F90.f90.o' failed
  >> 179   make[2]: *** [Src/Base/CMakeFiles/box_c.dir/AMReX_parmparse_mod.F90.f90.o] Error 1
     180   make[2]: *** Waiting for unfinished jobs....
     181   make[2]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
  >> 182   CMakeFiles/Makefile2:262: recipe for target 'Src/Base/CMakeFiles/box_c.dir/all' failed
  >> 183   make[1]: *** [Src/Base/CMakeFiles/box_c.dir/all] Error 2
     184   make[1]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
     185   Makefile:143: recipe for target 'all' failed
  >> 186   make: *** [all] Error 2

See build log for details:
  /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/spack-build.out
```

### PR DESCRIPTION
**Pull request by certik**
Amrex does not support CMake, one must use the custom Makefiles and configure
script in order to build it.

Fixes #5812.

### CODE REVIEW

**Comment by certik** [comment]
This is not perfect, but at least it builds with both intel and gcc now:
```
spack install --restage amrex@develop%intel@16.0.2
spack install --restage amrex@develop%gcc@7.2.0
```
The intel build however does not pick up the Intel compiler, which causes it to not install the `*.mod` files correctly. To do that, I believe instead of spack executing:
```
make
```
It needs to execute:
```
make COMP=intel
```
How do I achieve that with spack? After that I think it will work properly.

**Comment by junghans** [comment]
You can add `COMP=intel` to `build_targets`.

**Comment by tgamblin** [comment]
@markcmiller86, can you look at this?

**Comment by certik** [comment]
@markcmiller86 I am not insisting on using make, but right now Amrex does not build with Spack. My past experience with it is that they only use their make build system, and not test their cmake system, so it does not build by default. A few examples from the past:

https://github.com/AMReX-Codes/amrex/issues/63
https://github.com/AMReX-Codes/amrex/issues/69

So in this PR I am just using whatever the upstream authors prefer to use. That's all. I personally like and prefer cmake a lot.

**Comment by markcmiller86** [comment]
@asalmgren ...can you weigh in here. The current spack package for AMReX uses CMake to build AMReX. Is this the preferred modality? Or is GNU/Autotools? Do both support the same build functionality?

**Comment by asalmgren** [comment]
Our most common mode is just with gmake but we also support cmake.

They do both support the same functionality so I'd say whichever makes more
sense with spack, go with that one.

**Comment by certik** [comment]
@junghans thanks. I did this in 0b0fa839b5f9b829cebd0beba128b418a2ce8fa5, but it also needs to be used for the `make install` command, so I just reworked the build script completely in 26cb1d46261d68ddbdaf6c6440a8879ffcf243f4.

Now both of these work:
```
spack install amrex@develop%intel@16.0.2
spack install amrex@develop%gcc@7.2.0
```
and it installs the Fortran .mod files correctly now in both cases.

@markcmiller86, now this PR makes amrex actually working for me. In order to use cmake, one would have to patch amrex itself I am afraid. I don't have the time to do that.

**Comment by asalmgren** [comment]
If you can tell me how we would need to patch cmake in AMReX itself I'd be
happy to do that.

Ann

**Comment by junghans** [comment]
AMReX-Codes/amrex#69 is needed, but it is stalled for 3 months!

**Comment by certik** [comment]
@asalmgren unfortunately I don't know how to patch it. As I said, it seems it is not fully supported upstream for all compilers and Fortran wrappers. The makefile system, however, seems to always work.

**Comment by markcmiller86** [comment]
@certik ... Apart from the CMake/Autotools question (which is still in flux here), this PR removes a slew of build options including PIC, precision, fortran, debug mode, particle support and openmp support. It appears that AMReX's Autotools script does indeed have options to control these...So, I am wondering why you have decided to explicitly remove them. If we accept this PR as is, we're loosing build functionality.

**Comment by markcmiller86** [comment]
> @certik  I am not insisting on using make...

Indeed by totally changing this package from a CMake package to an Autotools package, you *are* insisting on using Autotools to build AMReX and not CMake. And, BTW, AMReX has built with Spack for me in multiple contexts though I can't recall whether I ever attempted the Fortran builds. Based on your experiences with it, I am inclined to believe I never did. That said, to get Fortran builds working, I don't think the best approach is to wholly change the build system the package is using and them remove a slew of build options we had. Here are the best options I think...

- Supply the patch(es) necessary to get CMake build system to build fortran and update this package to use those patches as appropriately but leave the CMake build otherwise intact
- Switch to Autotools but support *all* the build options the CMake version did
  - Though, it would be best to get guidance from AMReX team on whether CMake or Autotools build systems is the preferred method going forward. Again, last I worked on this package, it was my understanding that AMReX team *prefers* CMake going forward.
- Wait for and/or help AMReX team to resolve Fortran/CMake isssues

**Comment by markcmiller86** [comment]
> Though, it would be best to get guidance from AMReX team on whether CMake or Autotools build systems is the preferred method going forward. Again, last I worked on this package, it was my understanding that AMReX team prefers CMake going forward.

Looks like I am wrong on this point. AMReX team is fine with using either Autotools or CMake or maybe even straight/vanilla make.

**Comment by tgamblin** [comment]
@markcmiller86:

> Indeed by totally changing this package from a CMake package to an Autotools package, you are insisting on using Autotools to build AMReX and not CMake.

I agree with your suggested options above, though I also don't think @certik is insisting on anything.  He just submitted a PR that fixed his issue with the Fortran build, which is still useful.  I agree it should preserve the original build options, and I think @certik would be equally happy with a CMake build that actually worked.

From a Spack perspective, we don't care which build system the project uses -- we just want one that works.  We should pick the one most likely to continue working.  That's generally the one that the developers *actually use*.

@asalmgren: which one do the AMReX developers and users actually use themselves?  Based on @junghans' point above (RE: AMReX-Codes/amrex#69), it seems like the CMake build isn't getting as much love.  Which build system do you use in your nightly tests?

I don't have an opinion about which one AMReX should use, though from past experience with other packages, I'd say it's generally better to just pick one and go with it rather than support two systems.  Inevitably one or the other is in disrepair, which can be painful for packagers.  AMReX isn't the first package we've debated like this.

**Comment by certik** [comment]
@markcmiller86 I am just trying to help. As @tgamblin just wrote, I am really not insisting on anything, and I have also not explicitly removed any options, as you seem to accuse me. The options are implicitly removed, simply because I haven't had time to implement them, and more importantly, I wasn't sure whether you guys want to go the Make route, as opposed to cmake route. So I just provided something that works, and one can improve upon it. Again, I am really just trying to help and make it work, so that I can use spack to install amrex with various compilers for our work at LANL.

**Comment by asalmgren** [comment]
Here's what I just sent Mark -- hope this helps:



*   We don't use autotools at all.*


*   Straight/vanilla make is our default -- that is always the first to get
updated.*


*   But we do have an important ECP application that uses cmake so we
always update cmake after updating straight make.     *
*  So I guess we are committed to maintaining both of those.*

**Comment by markcmiller86** [comment]
Ok, after email exchanges with @asalmgren, it looks like we're both wrong. It should be a straight make package as that is the default everyone on the AMReX team uses.

So, we should not be using CMake or Autotools for it. That suggests to my anyways, we should reject this PR and start a new one with the package adjusted to use straight make.

I don't have time for that now. @certik?

**Comment by tgamblin** [comment]
It's not clear from @asalmgren's response whether the client code relies on the CMake build (e.g. through `xxxx-config.cmake` files or some other mechanism), or whether they just want to build AMReX with CMake. 

So, two questions for @asalmgren:
1. What's the dependent code?
1. If we go with `gmake`, will the other code still work, or is this a case where the client code *needs* something about the cmake build?

**Comment by junghans** [comment]
This PR changes to the `Package` class, not the `AutoToolsPackage` class, even though it calls some sort of `configure` script!

**Comment by certik** [comment]
@markcmiller86 this PR is already using plain makefiles, not autotools...

**Comment by asalmgren** [comment]
There is not a single dependent code.

Most codes that build with AMReX use regular makefiles.

One code in particular uses cmake but it doesn't use spack.   The
application code drives the cmake process but relies on there being support
for cmake within AMReX.

If spack just wants to support one then regular makefiles are definitely
the easier and most popular way to go.

**Comment by jrood-nrel** [comment]
I don't have too much to add here, because AMReX in Spack confuses me.

I use AMReX for one of my projects and it never made sense to me in Spack, because the way we use it is AMReX is compiled and built at the exact same time as our application by using pure makefiles as stated before. I definitely think Spack works the best with CMake in my opinion, but in this case I'm curious what the install even looks like? Does it install the source code and then if I added my application as a package with an AMReX dependency, would I just use `package.py` to setup my make files? I guess that's the way I see it working.

**Comment by asalmgren** [comment]
Jon -- what you describe is the way many/most of the AMReX-based codes
works, but we do have applications that can build amrex first as a library
then use it that way.  That functionality is enabled through cmake.

Ann

**Comment by jrood-nrel** [comment]
I would love to have good CMake support in AMReX though as the makefiles make it difficult to extend when trying to add in third party libraries to our application, etc. However, I like the makefiles, because performance-wise, we set a lot of options in the makefile that will preprocess our code into a much more customized build specific to the intended simulation.

**Comment by asalmgren** [comment]
Jon -- we do have working CMake support in AMReX -- this is how MFIX builds
with it.

**Comment by jrood-nrel** [comment]
Sorry, I should have said CMake in my application (Pele) 🙂 .

**Comment by certik** [comment]
@tgamblin why don't you decide which way you want to go. I just want a working amrex in spack, one way or another.

Regarding cmake there seem to be many issues:

* the latest develop branch fails with both gcc and intel in spack, with the error: https://github.com/LLNL/spack/issues/5812#issuecomment-337728062, which seems unrelated to Fortran.

* The cmake build system was not supporting Fortran until we reported it (https://github.com/AMReX-Codes/amrex/issues/63, https://github.com/AMReX-Codes/amrex/issues/69, ...), so I assume it can break in the future as well.

* We also need Nag, which works with the make files since https://github.com/AMReX-Codes/amrex/pull/87, but not in cmake, as far as I know, since it requires some extra options.


I like and use cmake every day, but I don't have the capacity to be fixing and maintaining the cmake build system in Amrex. That really should be the job of the amrex library developers.

**Comment by markcmiller86** [comment]
All, it looks like we need to adjust this Spack packge to use straight make and not use either CMake (original impl. by @markcmiller86) or Autotools (new PR submitted by @certik).

Instead, we need to adjust this Spack package to use AMReX's vanilla make system which is straight/vanilla make.  This means instead of being `Amrex(CMakePackage)` or `Amrex(AutotoolsPackage)` or `Amrex(Package)` and then calling `configure(..)` from within the install method, it will look more like [pacbio-damasker](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/pacbio-damasker/package.py). In addition, it appears we also need to support installing of sources and not just libraries which @jrood-nrel mentions above.

Here is my conundrum...

- The current state of the package is that it supports a number of _useful_ build options and works on various platfroms where I've built it though apparently not  the `+fortran` option.
- The change proposed in this PR supports fortran, but not as an option...it is by fiat which means everyone now needs a fortran compiler to build it even those not using the Fortran parts of AMReX. In addition, this PR explicitly _removes_ support of all the other options we had including debug, particles, openmp and precision.

I can accept the PR if it is, _minimally_, revised to support the options it was supporting before except through configure as opposed to CMake. Without them, I feel like we're just exchanging one subset of working options for another, albeit even smaller subset.

**Comment by certik** [comment]
@markcmiller86 and I talked over phone and we agreed that we'll go ahead and use make, since that's what Amrex developers seem to be using themselves. I will implement the missing options, they are essentially all exposed here: https://github.com/AMReX-Codes/amrex/blob/819b1a5789c78314317531d4e663debbb6b91126/Tools/libamrex/configure.py, and later on we don't even need to call this `configure.py` Python script, and just create the makefile with the options ourselves, but that can be done in other PRs.

I will try to get to it in the coming days. I will keep you updated.

**Comment by tgamblin** [comment]
@certik @markcmiller86: the plan sounds good to me, but now I'm a bit confused by @jrood-nrel's comments.

Ok, I read [the docs here](https://amrex-codes.github.io/amrex/BuildingAMReX.html).  To be honest, I'm no longer sure what the right thing to do is.  It seems like there are 3 different ways to use AMReX, and there's not currently a good way to install AMReX so that it can be used in *all* of those ways.  Further explanation:

1. The first way described to use AMReX is to set `AMREX_HOME` to the AMReX source directory, then to use AMReX gmakefiles to include the various gmakefiles that come with AMReX.  For this, it seems like the full AMReX source should be copied to the installation directory, and the AMReX package should set `AMREX_HOME` to point to that directory in its `setup_dependent_environment()` method so that dependent packages can easily use it this way.  I would do one of three things for this:
    1. I'd initially be inclined to install AMReX as a library via (2) or (3), then re-untar the entire source code into `$prefix/share/amrex/home` or some similar `man hier`-compliant path.  Then I would set `$AMREX_HOME` to `$prefix/share/amrex/home` in `setup_dependent_environment` in the AMReX spack package.
    2. If an AMReX build already installs its own source somewhere, I would just point `AMREX_HOME` at that.
    3. I *might* consider just making a separate package called `amrex-source`, that installs the entire source tree in the install prefix, and points `AMREX_HOME` at that prefix.  This way, packages that need to use AMReX's build system can just `depend_on('amrex-source')` and be done with it.  This may be simpler than either of the above two options.

2. You can install AMReX as a library via Makefiles, which is what @certik's build does.  At the moment, this seems to be the main *working* build.  However...

3. It seems like installing with `CMake` (if it worked) would provide all the same functionality as (2) BUT also makes AMReX findable by CMake's `find_package` command (see [here](https://amrex-codes.github.io/amrex/BuildingAMReX.html#importing-amrex-configuration-into-a-cmake-project)).  If you do not install with CMake, you don't get the extra config files, and a CMake build can't find AMReX.

So:
1. Just doing (1) means that client codes that expect AMReX as a any type of library will fail.  
2. Doing (2) and (1) means that client codes that expect AMReX as a CMake-findable library will fail.
3. (3) apparently doesn't work, but it seems like it would actually be the best way to install AMReX as a library, since codes expecting AMReX as a gmake-build OR cmake-built library would work.

In a perfect world, I would do (1) and (3), since (3) is ostensibly compatible with (2) (both install  libraries) and I think (1) + (3) covers all the bases.  However, if (3) doesn't work, maybe we should do (1) and (2)... that would cover some of the bases, but I agree with the Makefile method if the AMReX library is going to lag behind the Makefile version.

@asalmgren: is the intuition above accurate?  Is there a chance that AMReX's will accept the `CMake` support patch that @junghans sent along, and would that enable us to do (1) and (3) in a way that works for Fortran?  Does the AMReX team have an opinion on how it should be used and which of these should be supported? It would be nice if the CMake tracked the Makefile builds.

**Comment by certik** [comment]
@tgamblin we use cmake in our internal code, and we simply discover amrex like any other library that does not use cmake, here is the code snippet:
```cmake
$ cat cmake/FindAMReX.cmake find_path(AMREX_INCLUDE_DIR NAMES AMReX.H)
find_library(AMREX_LIBRARY NAMES amrex)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AMREX DEFAULT_MSG
    AMREX_INCLUDE_DIR AMREX_LIBRARY)

add_library(tpl::amrex INTERFACE IMPORTED)
set_property(TARGET tpl::amrex PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    ${AMREX_INCLUDE_DIR})
set_property(TARGET tpl::amrex PROPERTY INTERFACE_LINK_LIBRARIES
    ${AMREX_LIBRARY} ${MPI_CXX_LIBRARIES} ${MPI_Fortran_LIBRARIES}
    ${CMAKE_CXX_IMPLICIT_LINK_LIBRARIES})
```
This is only for the Fortran interface, but a similar code can be written for the C++ interface.

Your point 3. can be applied to any package that does not use cmake.

**Comment by tgamblin** [comment]
> Your point 3. can be applied to any package that does not use cmake.

True, though others may expect the CMake configs and the variables in them -- there are more of them than your config provides.

But, yes, it's easy to re-engineer your snippet.  Maybe not intuitive for someone who didn't write the client code, though.  But it wouldn't be the only non-intuitive thing we've discussed in this thread, so it's a minor price to pay for a working Fortran install.

**Comment by certik** [comment]
I think it all boils down to: is somebody willing to keep maintaining the Amrex's cmake build system by (timely) submitting PRs upstream (and getting them merged) to keep things working, as they develop their `develop` branch? I cannot do that myself, but if somebody is available to do that, then I would say let's use the cmake build system. Otherwise let's use the makefiles.

**Comment by tgamblin** [comment]
Yeah I agree with @certik.  @junghans?

**Comment by asalmgren** [comment]
Yes we can do that.

**Comment by asalmgren** [comment]
FYI -- I have lost track of what our current status is wrt all of this --
do you need the AMReX development branch to change in some way as of this
point?

I'm hoping that our cmake stuff will become much more stable.  in our first
year of ECP there were very rapid changes and it was the first time in
years that we actually got cmake working

i am hoping that things will be much more stable but of course we will need
your feedback when things arent' working so we can fix them

**Comment by certik** [comment]
@asalmgren the current status is that the `develop` branch of Amrex does not build with either Intel or gcc compilers in spack, here is the error: https://github.com/LLNL/spack/issues/5812#issuecomment-337728062

**Comment by tgamblin** [comment]
@asalmgren: it sounds like, per @junghans' comment above, that all we need is to get AMReX-Codes/amrex#69 merged and this could be enough for @certik.  Can the AMReX folks review and merge that PR?

If the AMReX folks are planning to keep CMake up to date with makefile builds then I think that's the most fully-featured way to go.

I guess the other question is whether AMReX CMake build also installs the source so that people who depend on AMReX in way (1) above can use that too.  If it doesn't, we should probably add that to the Spack package (see my long-ish comment).

**Comment by certik** [comment]
@tgamblin no, the error in https://github.com/LLNL/spack/issues/5812#issuecomment-337728062 is separate from https://github.com/AMReX-Codes/amrex/issues/69.

**Comment by asalmgren** [comment]
Ok here's where I'm confused.

We have an application that uses CMake to build with AMReX and it is
working fine with gnu or intel.

I don't know enough about spack to understand why the AMReX cmake files
would work with that application but not with spack

Ann

**Comment by certik** [comment]
@asalmgren --- I think all we need is this: are you willing to support cmake as part of Amrex for building things? If so, then I am happy to report all issues, get them fixed in amrex and then just use cmake in spack.

**Comment by asalmgren** [comment]
All,

I'm handing this issue over to Michele Rosso who handles our cmake.

One of the things in the issues you linked to has been fixed.

He is cc'ed here -- I think we're close to having it all good again.

Ann

**Comment by asalmgren** [comment]
Hi everybody,

as Ann mentioned, one of the ECP codes, i.e. MFIX, uses CMake to build
AMReX. MFIX supports two modes:

1) Superbuild: MFIX's CMake drives the download, configuration and build of
AMReX. In this mode, AMReX becomes a target of the MFIX CMake system.

2) External AMReX installation. In this mode, AMReX is installed as a
separate library. MFIX is then linked to the external AMReX install.

It's my understanding that Spack uses AMReX as an external library: can you
confirm this is correct? If so, the configuration step must include the
option

"-DENABLE FORTRAN INTERFACES=ON"

for the Fortran interfaces to be enabled.   Could you please verify that
this option was used for the AMReX build?

Michele

**Comment by asalmgren** [comment]
There is a typo in my previous message. The correct option to use is:

"-DENABLE_FORTRAN_INTERFACES=ON"

**Comment by certik** [comment]
@asalmgren thanks. We can figure out the technical details. Based on this latest exchange, I now think we should use the cmake interface in spack. @tgamblin, @markcmiller86 let me know if you agree. If so, I'll try to figure out why it fails and what to do, and/or report a reproducible bug to amrex.

**Comment by markcmiller86** [comment]
>  @tgamblin, @markcmiller86 let me know if you agree.

Yeah, I agree. Sounds like the crux of the problem was my failure to add something like...

```
'-DENABLE_FORTRAN_INTERFACES=%s' % ('+fortran' in spec),
```

after line 68.

This assumes that a value of `true` for the aforementioned CMake variable has the same effect as  `ON` and `false` has the same effect as `OFF` which I am pretty sure is true.

**Comment by certik** [comment]
I will work on this soon, probably next week. I am going to close this PR, since we decided to go with cmake, and once I have something, I'll open a new PR.

**Comment by tgamblin** [comment]
Thanks for all the help on this @certik!

**Pull request closed without merging**
