### PR TITLE
Initial changes needed to build paraview@5.9.0%xl_r

### PR DESCRIPTION
**Pull request by EthanS94**
@danlipsa @chuckatkins This MR adds patches to help with building ParaView in an XL environment. These changes help us to build `paraview@5.9.0%xl_r ^eigen@3.3.4%xl_r` successfully.

Thanks!

### CODE REVIEW

**Comment by danlipsa** [comment]
Looks reasonable. +1

**Comment by alalazo** [comment]
Can you also rebase this one and ping maintainers? After we got :heavy_check_mark: from tests and reviews I'll gladly merge these PRs.

**Comment by EthanS94** [comment]
@chuckatkins @danlipsa @vicentebolea

**Comment by EthanS94** [comment]
Ping @vicentebolea @danlipsa @chuckatkins

**Review by vicentebolea — DISMISSED** [review]

**Comment by vicentebolea** [comment]
@EthanS94 could you kick the CI, the gitlab build got an internal error.

**Comment by EthanS94** [comment]
@vicentebolea I probably shouldn't have done a force push on the rebase. I think it dismissed your review. Tests look good.

**Review by vicentebolea — DISMISSED** [review]

**Comment by EthanS94** [comment]
@alalazo

**Comment by alalazo** [comment]
@EthanS94 Sorry about that, but there's a conflict to be solved :slightly_frowning_face:

**Review by alalazo — APPROVED** [review]

**Pull request merged**
