### PR TITLE
perl: remove mkdirp from setup_dependent_package

### LINKED ISSUE #43725: Installation issue: perl
### Steps to reproduce the issue

This isn't technically a build error with perl, it's a probably with its effect on downstream packages.
```console
# with, e.g., root:
$ spack install ecflow
# with some other user:
$ spack load ecflow
```

### Error message

```
PermissionError: [Errno 13] Permission denied: '/myfs/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/ecflow-5.8.3-v54njvwdorvcyzaivcaxgimfch5s7tlh/lib/perl5'
```

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### Additional information

The problem is that the `setup_dependent_package()` function is called in loading downstream packages (at least, some; I don't know exactly when/why this happens), and contains a `mkdirp()` call:
```
            # Make the site packages directory for extensions,
            # if it does not exist already.
            mkdirp(module.perl_lib_dir)
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alexrichert**
Fixes https://github.com/spack/spack/issues/43725

### CODE REVIEW

**Comment by alexrichert** [comment]
@haampie -- All I took out was the mkdirp itself. Does the rest of `setup_dependent_package()` still do something?

**Comment by haampie** [comment]
thanks, it does

**Review by haampie — APPROVED** [review]

**Comment by alecbcs** [comment]
I don't really understand how this wasn't caught by the CI run on the merge commit, but I can't successfully build rust after this PR on either MacOS or Linux. All attempts seem to fail with the following error after building with the new hash of libssh2 created by the perl change.

@haampie @alexrichert do you all know what might be causing this incompatibility? Reverting the change fixes the failing rust build for me.

```
  >> 8489      cargo:warning=libssh2/src/kex.c:1473:50: error: use of undeclared identifier 'LIBSSH2_DH_GEX_OPTGROUP'
     8490
     8491      cargo:warning=        _libssh2_htonu32(key_state->request + 5, LIBSSH2_DH_GEX_OPTGROUP);
     8492
     8493      cargo:warning=                                                 ^
     8494
  >> 8495      cargo:warning=libssh2/src/kex.c:1474:50: error: use of undeclared identifier 'LIBSSH2_DH_GEX_MAXGROUP'
     8496
     8497      cargo:warning=        _libssh2_htonu32(key_state->request + 9, LIBSSH2_DH_GEX_MAXGROUP);
     8498
     8499      cargo:warning=                                                 ^
     8500
     8501      cargo:warning=libssh2/src/kex.c:2322:9: warning: 'EC_KEY_free' is deprecated [-Wdeprecated-declarations]
```

**Comment by AlexanderRichert-NOAA** [comment]
I'm not sure, but I'll look into it. Would it make sense to try making this change in setup_dependent_build_environment so that it's done once at dependent install time rather than dependent load time? I'm still not sure what that part of the perl recipe is for.

**Comment by alexrichert** [comment]
@alecbcs when you say the new hash of libssh2, do you mean that this change affected the libssh2 hash..?
I'll test it out on my personal machine and let you know what I find.

**Comment by alecbcs** [comment]
Additional debugging and I don't think it was actually this PR/commit. It looks like it was 82df0e549dbebcc8c10cc91eb505cfd7df293175 which changed the way Rust is (or isn't) finding its dependencies this was just the first commit to change the concretization of `rust`/`libssh2` after that change went in.

Confusingly if you use a `libssh2` that was built prior to 82df0e549dbebcc8c10cc91eb505cfd7df293175 then rust builds but anything after fails with the previous error so after this commit you get a new concretization and failing builds.

Sorry for the false alarm on this PR.

**Comment by haampie** [comment]
Can you make an issue elsewhere?

**Pull request merged**
