### PR TITLE
New package: r-styler

### PR DESCRIPTION
**Pull request by qwertos**

### CODE REVIEW

**Review by glennpj — DISMISSED** [review]
This looks fine.

Note that there is a newer version available.

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by glennpj** [comment]
@spackbot run pipeline

**Comment by glennpj** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@spackbot run pipeline

**Comment by glennpj** [comment]
@spackbot run pipeline

**Review by glennpj — APPROVED** [review]

**Pull request merged**
