### PR TITLE
Faster virtuals and concretization

### LINKED ISSUE #676: Spack is Great, but too slow
Any ideas on what is causing the slowness, and how to speed it up?

### PR DESCRIPTION
**Pull request by tgamblin**
This should fix #676.

@citibeth, @davydden, @alalazo, @becker33, @mplegendre and others will be interested in this.  The changes here bring `deal` concretization down to around 3 seconds from around 20.  `dealii` might be one of the most complicated packages in off-the-shelf spack.  We have larger ones internally and so does @citibeth, so hopefully this will ease their life a bit.

Things in this PR (or related to it):

- [X] e8b4d5fb6 (already in `develop` because it was a major time saver) fixes large amount of time spent in [re.Scanner](http://lucumr.pocoo.org/2015/11/18/pythons-hidden-re-gems/).  A `Lexer` (implemented with `re.Scanner`), which compiles regexes, was being constructed every time we parse a spec, and that is expensive.  Since spec parsing is a large part of evaluating directives like `depends_on`, this caused `package.py` import to take a long time.  Adding a single lexer for all parsers fixes this.
- [X] Cache the `ProviderIndex`.  We have to import *all* `package.py` files when we concretize specs that have virtual dependencies, because we have to find providers but we don't know which `package.py` files actually call `provides`.  The `ProviderIndex` holds that information and is now cached per package repository and automatically updated when `package.py` files are newer than the index.  It can also be updated incrementally, so updates after the first will not be very expensive.
- [X] Lazy evaluation of `all_package_names()` so that processing small specs doesn't even look at most `package.py` files.
- [X] Faster hash key function for compiler flags (`FlagMap`) -- uses tuples and doesn't manipulate strings.  This saves a second or so for `dealii`.
- [X] To make the `ProviderIndex` compact, `Spec.to_yaml` won't write out empty fields in abstract specs.  This should not affect things like `spec.yaml` or the install database, as those only contain concrete specs.
- [x] Allow ProviderIndex caches to be stored in `~/.spack/caches` when `$repo/index.yaml` is not writable.  This would let users cache providers even for multi-user spack repos.
- [x] Tests for the new `ProviderIndex` cache.

All of these commits attack the problem that concretization (and running many spack commands) require some fairly expensive operations to happen *for every `package.py` file*.  This PR reduces the cost of these operations and avoids *O(num packages)* operations where it can.  In the best case, only has to `stat` each `package.py` file instead of loading all of them and parsing specs.  Generally just running`stat` is pretty fast.

The concretization algorithm is still at least quadratic, but the DAGs are still small by modern standards in Spack, so this is not killing us yet.

### CODE REVIEW

**Comment by citibeth** [comment]
Is this ready to beta test in regular use?

**Comment by tgamblin** [comment]
@citibeth I think so.  The only reason I have not merged it yet is that I have not written unit tests for the `ProviderIndex` cache, and I want to ensure the cache works even if you can't read the repository directory.  If you want to beta test it, the only thing you would need to remember is that if things go wrong, remove `$repo_root/index.yaml` and `$repo_root/lock`.  If you are just using the builtin spack repository, `$repo_root` is `$spack_root/var/spack/repos/builtin`.

**Comment by willelm** [comment]
I've been frustrated by speed and eager to try the fix. I merged with 9411cb1, and I think there's an issue with python activation. Try building py-ipython and activating it. It builds fine but gives errors when I start it about readline services being unavailable. Readline is clearly a dependency of python in the spec, but doesn't seem to be followed.

**Comment by citibeth** [comment]
I got the problem below.  Maybe my merge was bad.

```
[rpfische@gs611-gibbs spack]$ spack install patchelf
Traceback (most recent call last):
  File "/home2/rpfische/spack/bin/spack", line 179, in <module>
    main()
  File "/home2/rpfische/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home2/rpfische/spack/lib/spack/spack/cmd/install.py", line 82, in install
    explicit=True)
  File "/home2/rpfische/spack/lib/spack/spack/package.py", line 870, in do_install
    if 'install' in install_phases and spack.install_layout.check_installed(self.spec):
  File "/home2/rpfische/spack/lib/spack/spack/directory_layout.py", line 272, in check_installed
    path = self.path_for_spec(spec)
  File "/home2/rpfische/spack/lib/spack/spack/directory_layout.py", line 138, in path_for_spec
    path = self.relative_path_for_spec(spec)
  File "/home2/rpfische/spack/lib/spack/spack/directory_layout.py", line 208, in relative_path_for_spec
    spec.dag_hash(self.hash_len))
  File "/home2/rpfische/spack/lib/spack/spack/spec.py", line 743, in dag_hash
    self.to_node_dict(), default_flow_style=True, width=sys.maxint)
  File "/home2/rpfische/spack/lib/spack/external/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home2/rpfische/spack/lib/spack/external/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 41, in represent_data
    if self.ignore_aliases(data):
  File "/home2/rpfische/spack/lib/spack/external/yaml/representer.py", line 142, in ignore_aliases
    if data in [None, ()]:
  File "/home2/rpfische/spack/lib/spack/llnl/util/lang.py", line 240, in <lambda>
    setter('__eq__', lambda s,o: (s is o) or (o is not None and s._cmp_key() == o._cmp_key()))
AttributeError: 'tuple' object has no attribute '_cmp_key'
```

**Comment by citibeth** [comment]
I've had success with a different merge.  This PR has made my life with Spack so much better.  I recommend it be merged without delay.

**Comment by tgamblin** [comment]
This is ready to merge.  I've cleaned up a number of changes, and caching is now done in `~/.spack` so it doesn't require write access to Spack repos to work.  I also simplified file locking a bit.

It's rebased on current develop, so the merge should be clean.  Can @citibeth, @alalazo, @gartung, @davydden, @glennpj try this out and let me know if it helps?

@glennpj: I think your issue in #676 may be something different, but this is worth a try.

**Comment by davydden** [comment]
@tgamblin thanks! sorry, did not have time to check it out, but ought to be fine.

**Pull request merged**
