### PR TITLE
New URL scheme for newer (and older) versions of PDT

### PR DESCRIPTION
**Pull request by robertdfrench**
I had to explicitly tell flake8 to ignore the long url on line 38, is that the right thing to do?

### CODE REVIEW

**Comment by adamjstewart** [comment]
Hmm, you shouldn't have to tell flake8 to ignore that line. It automatically ignores all lines that begin with `url =`. Did you branch off of the latest develop or are you on an older branch? Make sure your `share/spack/qa/run-flake8` looks like [this](https://github.com/LLNL/spack/blob/develop/share/spack/qa/run-flake8)

**Comment by robertdfrench** [comment]
@adamjstewart I forgot there was a built-int flake8 runner! I was running my local flake8 directly.

**Comment by adamjstewart** [comment]
LGTM

**Comment by pramodk** [comment]
@robertdfrench, @adamjstewart, @tgamblin : sorry for looking at this very later, I have following question:

- there are two packages that pdt provides: pdt-X.tar.gz and pdtoolkit-X.tar.gz. We should download 2nd because the first has support for only x86,cray platform but 2nd also include support for os-x, BG-Q, Power-8, ARM etc.
- hence #1466 added `url_for_version` method

Am I missing something? I will open new PR if above is fine. (otherwise tau installation fails on bg-q, power8, OS X etc..)

**Comment by adamjstewart** [comment]
I don't know anything about pdt/tau, but from glancing at the download tarball contents I think you're right. I'll let @robertdfrench respond as to whether or not he agrees.

As for #1466, if you want to change the download URL, just change `url`. There's no need for a `url_for_version` function unless the URL is particularly complicated and difficult to parse.

**Pull request merged**
