### PR TITLE
gaudi: Specify boost dependencies explicitly and cleanup package

### PR DESCRIPTION
**Pull request by tmadlener**
With the upcoming version 39, `boost +fiber` becomes a requirment (see [this MR](https://gitlab.cern.ch/gaudi/Gaudi/-/merge_requests/1553)). I also took the chance to specify the boost dependencies that are needed instead of going with the defaults. The variants are compiled from the `find_package` call for `Boost` in https://gitlab.cern.ch/gaudi/Gaudi/-/blob/master/cmake/GaudiDependencies.cmake

I also limited `fmt@:10` because building Gaudi with `fmt@11` does not work yet for any version of Gaudi.

Finally, I have removed patches that applied for `@:34` since that version is no longer available via spack.

### CODE REVIEW

**Comment by wdconinc** [comment]
Thanks for narrowing the boost dependency. For v34r1, there is also boost in other places, e.g.
```
19:36:37 wdconinc@menelaos ~/git/Gaudi ((tags/v34r1)) $ grep -r boost Gaudi* | grep find_package
GaudiCoreSvc/CMakeLists.txt:find_package(Boost COMPONENTS system filesystem regex thread python${boost_python_version} REQUIRED)
GaudiExamples/CMakeLists.txt:find_package(Boost COMPONENTS python${boost_python_version} REQUIRED)
GaudiProfiling/CMakeLists.txt:find_package(Boost COMPONENTS python${boost_python_version} REQUIRED)
```

**Comment by tmadlener** [comment]
Right. I didn't go lower than 35, because that is the lowest version available from the package in any case.

edit: I check those places as well in v34r1. those are all subsets of the ones that we have in any case.

**Review by wdconinc — COMMENTED** [review]
Sorry, I didn't scroll up high enough to the versions and saw the patches with `when="@:34"` so I figured we had v34 still in this package. Since you include multiple aspects, would you also be willing remove the patches that only apply to older versions that are not included here anymore?

**Review by wdconinc — APPROVED** [review]
Thanks a lot!

**Pull request merged**
