### PR TITLE
Setting library path as lib similar to other rocm packages.

### PR DESCRIPTION
**Pull request by renjithravindrankannath**
Setting library path to lib for comgr, hsakmt-roct and llvm-amdgpu similar to other rocm packages.

### CODE REVIEW

**Comment by renjithravindrankannath** [comment]
@spackbot rerun pipeline

**Comment by renjithravindrankannath** [comment]
@spackbot rerun pipeline

**Review by srekolam — APPROVED** [review]

**Comment by renjithravindrankannath** [comment]
Hi @tldahlgren , Could you please review the changes.

**Review by srekolam — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
