### PR TITLE
must: new package for the RWTH mpi checker must

### PR DESCRIPTION
**Pull request by melven**
package.py for the MPI error checker from the RWTH Aachen University (https://itc.rwth-aachen.de/must/).

### CODE REVIEW

**Comment by melven** [comment]
I'm not a maintainer of must but people in our group want to use the must software and somehow there was no package for must in spack yet...

**Comment by melven** [comment]
I checked that different variants of must build and run with openmpi and gcc 9.4.0 on two different systems.

I didn't check other compilers / mpi vendors though.

**Comment by melven** [comment]
I don't see an error message for the failing unit tests (2.7, original). Any input, what is going wrong here?

**Comment by michaelkuhn** [comment]
It looks like a must package has been created in the meantime. Can this be closed?

**Comment by alalazo** [comment]
Superseded by #32329

**Pull request closed without merging**
