### PR TITLE
flux-core: remove deprecated versions

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by alalazo** [comment]
Removing the deprecated versions in `flux-core` causes some old versions in `flux-sched` to not be buildable anymore. I removed them too, but if the thing has to be dealt with more "gracefully" we can add a deprecation to those versions and merge the removal after the November release.

**Review by vsoch — COMMENTED** [review]
This seems OK to me, as long as nobody needs to build these. I'll defer to @grondo on that.

**Review by grondo — APPROVED** [review]
LGTM!

**Review by vsoch — APPROVED** [review]

**Comment by alalazo** [comment]
@spackbot run pipeline

**Pull request merged**
