### PR TITLE
openssl: New version 1.1.1p

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed new sha256.

**Comment by eschnett** [comment]
@tldahlgren Something is failing in the CI pipeline. I don't understand exactly what.

**Comment by tldahlgren** [comment]
> @tldahlgren Something is failing in the CI pipeline. I don't understand exactly what.

It looks like everything passed 4 days ago.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by tldahlgren** [comment]
> > @tldahlgren Something is failing in the CI pipeline. I don't understand exactly what.
> 
> It looks like everything passed 4 days ago.

Interesting.  I checked again and apparently now have access to the failure:

```
...
Error: Failed to install py-cython due to NoChecksumException: Package tarball failed checksum verification.
 ...
Error: py-numpy-1.22.4-ocuhqta6blsswuvm6577dxvw6dtjird3: Package was not installed
```

**Review by alalazo — APPROVED** [review]

**Pull request merged**
