### PR TITLE
Update kokkos amd gpu archs and required C++ level

### PR DESCRIPTION
**Pull request by robertmaynard**

### CODE REVIEW

**Comment by alalazo** [comment]
@jjwilke

**Comment by tldahlgren** [comment]
Closing and re-opening to force re-running checks since `style` still `Waiting for status to be reported`.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
Please resolve the package conflict.

**Comment by robertmaynard** [comment]
> Please resolve the package conflict.

Done

**Review by tldahlgren — APPROVED** [review]
Thanks for the fix.

**Comment by tldahlgren** [comment]
Thank you for your contribution.

**Pull request merged**
