### PR TITLE
all-library: add v0.9.3

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@spack/merge-to-develop please review

**Comment by sethrj** [comment]
@junghans Instead of messaging all the maintainers without any context, which is noisy and not very informative, could you please in the future select one or two potential reviewers and ping them? Or post an RFR on the `#maintainers` channel which is less intrusive? When I get notifications about spack reviews I generally expect them to be about packages I regularly work with. Thanks!

**Comment by junghans** [comment]
> @junghans Instead of messaging all the maintainers without any context, which is noisy and not very informative, could you please in the future select one or two potential reviewers and ping them? Or post an RFR on the `#maintainers` channel which is less intrusive? When I get notifications about spack reviews I generally expect them to be about packages I regularly work with. Thanks!

Noted, thanks!

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.

**Pull request merged**
