### PR TITLE
Bazel: add post-installation tests

### PR DESCRIPTION
**Pull request by adamjstewart**
We already have tests for `spack install --test`, this uses those tests for `spack test` too.

### CODE REVIEW

**Comment by aweits** [comment]
> We already have tests for `spack install --test`, this uses those tests for `spack test` too.

Gave this a try, doesn't seem to actually work - but still prints that the test passed?

**Comment by adamjstewart** [comment]
When you say it doesn't work you mean there's an error message?

**Comment by aweits** [comment]
> When you say it doesn't work you mean there's an error message?

It's not actually running the tests, there's no output - but it reports success...
if I comment out ```@on_package_attributes(run_tests=True)``` it seems to do the right thing...

**Comment by adamjstewart** [comment]
@aweits good catch!

@tldahlgren this highlights a few problems with Spack's standalone testing that I've been complaining about for a while:

1. `spack test run` doesn't have any way to show you the output of the test (I know you're working on this)
2. `spack test results` told me that these tests passed despite no test actually being run
3. It doesn't seem to be easy (possible) to run tests both during and after installs?

The third point in particular is problematic. I realize that there are some tests that can only be run during a build (`make test`), but I'm unaware of any tests that can't be run `@run_after('install')` in addition to `spack test run`. In fact, I think Spack should automatically add all `def test` methods to `spack install --test`. Is there any reason we can't do this? I've somewhat hacked this into our Python build system, but the build seems to succeed even if the tests fail, or seems to raise an error when trying to log the test failure.

Overall, I get the impression that `spack test` was glued on top of Spack with no consideration at all towards the fact that `spack install --test` already exists and is used by many users. We really do need to integrate these two a little better. Otherwise, I'm considering removing `def test` from thousands of packages (everything that inherits from `PythonPackage`) to better support `spack install --test`, which is obviously unideal.

**Review by tldahlgren — CHANGES_REQUESTED** [review]
You cannot currently use directives with the reserved `test()` method.

I recommend "moving" all of the code for `install_test()` to an undecorated method that you call from `install_test` *and* `test` if you want to re-use the code in both cases.

**Comment by adamjstewart** [comment]
@tldahlgren is there any reason we can't do this automatically for all packages that have a `test` method? This seems quite cumbersome and would need to be done in hundreds of places, resulting in a lot of code duplication.

**Comment by tldahlgren** [comment]
> @aweits good catch!
> 
> @tldahlgren this highlights a few problems with Spack's standalone testing that I've been complaining about for a while:
> 
> 1. `spack test run` doesn't have any way to show you the output of the test (I know you're working on this)

Yes, it's in https://github.com/spack/spack/pull/28700.


> 2. `spack test results` told me that these tests passed despite no test actually being run

That's because the default has been to not complain if packages don't have tests.  This is something that was discussed during the initial design and implementation. 

IIRC, it makes it easier to not error out if a provider's virtual packages don't have tests.  But @becker33 can correct me if I am misremembering.


> 3. It doesn't seem to be easy (possible) to run tests both during and after installs?
> 
> The third point in particular is problematic. I realize that there are some tests that can only be run during a build (`make test`), but I'm unaware of any tests that can't be run `@run_after('install')` in addition to `spack test run`. 

It depends.  There can be issues with dependencies being available at build-time that aren't available post-build.  This is a known issue with our dependency model that, IIRC, can't be addressed until we convert to full hashes.

>In fact, I think Spack should automatically add all `def test` methods to `spack install --test`. Is there any reason we can't do this? I've somewhat hacked this into our Python build system, but the build seems to succeed even if the tests fail, or seems to raise an error when trying to log the test failure.
> 
> Overall, I get the impression that `spack test` was glued on top of Spack with no consideration at all towards the fact that `spack install --test` already exists and is used by many users. We really do need to integrate these two a little better. Otherwise, I'm considering removing `def test` from thousands of packages (everything that inherits from `PythonPackage`) to better support `spack install --test`, which is obviously unideal.

That seems harsh.  As I mentioned in my review, the problem here is trying to re-use a decorated method tied to a build-time phase.

@becker33 Did you want to respond to these criticisms?

**Comment by tldahlgren** [comment]
> @tldahlgren is there any reason we can't do this automatically for all packages that have a `test` method? This seems quite cumbersome and would need to be done in hundreds of places, resulting in a lot of code duplication.

Do what automatically?  Do you mean have stand-alone tests always run methods flagged with the `run_tests` attribute?  If so, I'd have to do some investigation.

@tgamblin @becker33

**Comment by adamjstewart** [comment]
> That's because the default has been to not complain if packages don't have tests. This is something that was discussed during the initial design and implementation.

Perhaps it would make more sense to mark a package as `SKIPPED` if it has not tests instead of `PASSED`?

> There can be issues with dependencies being available at build-time that aren't available post-build.

Yes, this is why not all build-time tests can be post-install tests, but not a reason why not all post-install tests can be build-time tests. We already need to make run-time deps available at build-time in order to run Python import tests.

> Do what automatically? Do you mean have stand-alone tests always run methods flagged with the run_tests attribute? If so, I'd have to do some investigation.

I'm actually proposing the opposite, we should run stand-alone tests as part of `spack install --test` even if they aren't explicitly flagged with the `run_tests` attribute. These can be run after the final install phase has been completed.

**Comment by tldahlgren** [comment]
> Perhaps it would make more sense to mark a package as `SKIPPED` if it has not tests instead of `PASSED`?

Given the need/desire to distinguish between having and *not* having tests to run, `NO-TESTS` might be preferable to `SKIPPED` under the right circumstances.


> 
> > There can be issues with dependencies being available at build-time that aren't available post-build.
> 
> Yes, this is why not all build-time tests can be post-install tests, but not a reason why not all post-install tests can be build-time tests. We already need to make run-time deps available at build-time in order to run Python import tests.

Fair enough.  


> 
> > Do what automatically? Do you mean have stand-alone tests always run methods flagged with the run_tests attribute? If so, I'd have to do some investigation.
> 
> I'm actually proposing the opposite, we should run stand-alone tests as part of `spack install --test` even if they aren't explicitly flagged with the `run_tests` attribute. These can be run after the final install phase has been completed.

This is certainly doable.  Supporting this requires more than the equivalent of adding `test` to `install_time_test_callbacks`.  We still need the proper set up to execute `run_test` at that stage (see #26594 ).

**Comment by adamjstewart** [comment]
Okay, my current solution seems to work. Unfortunately I can't use `self.run_test` since that doesn't work at install-time.

**Comment by tldahlgren** [comment]
> Okay, my current solution seems to work. Unfortunately I can't use `self.run_test` since that doesn't work at install-time.

I'm trying to get the fix for that merged.  See #26594 .

**Comment by adamjstewart** [comment]
Should we merge this in the meantime or should we close this assuming that `test` will be automatically added to `spack install --test` someday?

**Comment by adamjstewart** [comment]
Ping @tldahlgren

**Pull request closed without merging**
