### PR TITLE
Update Orca versions

### PR DESCRIPTION
**Pull request by awvwgk**
- add Orca 5.0.4-f.1
- add Orca 5.0.3-f.4

cc Christoph @christophriplinger

### CODE REVIEW

**Comment by snehring** [comment]
@awvwgk Would it make more sense to split the faccts distributed version into it's own package? Sort of like how ncbi-rmblastn is handled? It's just kind of a pain when the -f version is seen as the newest one vs the original distribution.

**Comment by awvwgk** [comment]
I can add an orca-faccts package instead

**Review by snehring — APPROVED** [review]
lgtm

**Comment by tillhanke** [comment]
Would it be possible to directly add 5.0.4 to the orca package as well?

**Comment by awvwgk** [comment]
I guess we are waiting for a reviewer to approve and merge this PR.

**Comment by snehring** [comment]
I've reached out in the slack about this PR

**Review by alalazo — APPROVED** [review]

**Pull request merged**
