### PR TITLE
quantum-espresso: fix build fail @6.6 and add conflicts a64fx.

### PR DESCRIPTION
**Pull request by tkameyama**
When we specify FFT_LIBS to configure of quantum-espresso 6.6, fft related macro are not defined.
and FFTXlib/fft_scalar.f90 is not compiled.
This PR fixed if FFTW_INCLUDE is defined, __FFTW is defined.

quantum-espresso is cause internal compiler error when gcc 8 and a64fx.
(gcc8 and thunderX2 is OK, I think that is gcc and SVE problem,)
This PR add conflicts when gcc8 and a64fx.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
@naromero77 can you review?

**Comment by naromero77** [comment]
Is your FFT patch available in QE develop? (i.e. is this essentially a backport).

**Comment by tkameyama** [comment]
> 
> 
> Is your FFT patch available in QE develop? (i.e. is this essentially a backport).

Yes.
I submited it and merged.
https://gitlab.com/QEF/q-e/-/merge_requests/1156

**Comment by naromero77** [comment]
For the FFT patch, if possible, please apply the merged commit directly as a patch to 6.6. Here is an example of how I have done it in the past:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/quantum-espresso/package.py#L195-L212

If its not possible to apply the commit directly as a patch, I would still request:
- Move patch into QE UPSTREAM PATCH section: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/quantum-espresso/package.py#L195
- Condition to apply patch should be `when='+patch@6.6'`
- Please put a 1 - 2 comment documenting as to why the FFT patch is needed.

**Comment by tkameyama** [comment]
> 
> 
> For the FFT patch, if possible, please apply the merged commit directly as a patch to 6.6. Here is an example of how I have done it in the past:
> https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/quantum-espresso/package.py#L195-L212
> 
> If its not possible to apply the commit directly as a patch, I would still request:
> 
>     * Move patch into QE UPSTREAM PATCH section: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/quantum-espresso/package.py#L195
> 
>     * Condition to apply patch should be `when='+patch@6.6'`
> 
>     * Please put a 1 - 2 comment documenting as to why the FFT patch is needed.

done.

**Comment by naromero77** [comment]
@adamjstewart looks good to me. BTW, are you not able to assign me as a reviewer?

**Comment by adamjstewart** [comment]
It looks like I'm not able to assign you as a reviewer. Not sure which permissions are needed, but @tgamblin would know

**Pull request merged**
