### PR TITLE
Make gromacs use cuda_arch

### PR DESCRIPTION
**Pull request by danielahlin**
As stated in the commit - this PR does not change version-specific gencode handling for older gromacs
versions. Potentially this should be done in this or a subsequent PR.

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Review by junghans — DISMISSED** [review]

**Review by alalazo — CHANGES_REQUESTED** [review]
I think you can also remove the `cuda` variant, since now it's inherited

**Comment by danielahlin** [comment]
> I think you can also remove the cuda variant, since now it's inherited

TBH I had not thought about that aspect. Still it seems that {+cuda,~cuda} would be good to retain in order to mark if  cuda support should be compiled in or not and do things differently in the package file as a consequence. See e.g. how this is done in OpenMPI and hwloc. Having this decided on whether the user adds ^cuda may be a bit too implicit?

**Comment by alalazo** [comment]
@danielahlin Not sure I understand what you mean. If you remove the `cuda` variant in `gromacs`, you still have the variant since it's inherited from `CudaPackage` (the same way `cuda_arch` is):

https://github.com/spack/spack/blob/93cad904136c6e7581f108f475127ab4757df0e3/lib/spack/spack/build_systems/cuda.py#L51

**Comment by danielahlin** [comment]
@alalazo I misunderstood what you meant. I thought you meant entirely disabling the possibility of having cuda as a variant - but I understand now that it is rather inherited from CudaPackage. I'll update and test.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
