### PR TITLE
paraview: add python to rpath

### PR DESCRIPTION
**Pull request by EthanS94**
@chuckatkins @danlipsa this is a fix for #21759

### CODE REVIEW

**Comment by danlipsa** [comment]
isn't this solved by 'module load python'?

**Comment by EthanS94** [comment]
> isn't this solved by 'module load python'?

Yes, but not for environments as described in the issue. This is for a use case where the variables that cause `module load python` to work are blacklisted. So there needs to be a way to make the python link happen without it.

**Comment by danlipsa** [comment]
Oh, I see. What are these environments that blacklist LD_LIBRARY_PATH?

**Comment by EthanS94** [comment]
> Oh, I see. What are these environments that blacklist LD_LIBRARY_PATH?

There are environments that do this at LANL and are hitting this problem. I can't speak to why blacklisting LD_LIBRARY_PATH is done.

**Comment by danlipsa** [comment]
Looks reasonable. +1

**Review by tldahlgren — APPROVED** [review]
LGTM and already approved by a package maintainer.

**Comment by tldahlgren** [comment]
Thank you for your contribution!

**Pull request merged**
