### PR TITLE
Add py-h5py version 3.3.0

### PR DESCRIPTION
**Pull request by takluyver**
The mpi4py dependency was bumped to 3.0.2 in setup.py. I'm not sure if that's actually required or not, but nothing lower is still tested.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@takluyver would you like to add yourself to the list of `maintainers` for this build recipe? Then you'll get automatically pinged on PRs that modify the package just like @bryanherman was.

**Comment by sethrj** [comment]
@takluyver There's a patch in the current recipe for `3.0.0:` that fails with 3.0.2:
```
==> Installing py-h5py-3.3.0-jo2wqmxlzejao7hcb4ennf4ix7wfmgka
==> No binary for py-h5py-3.3.0-jo2wqmxlzejao7hcb4ennf4ix7wfmgka found: installing from source
==> Fetching https://files.pythonhosted.org/packages/source/h/h5py/h5py-3.3.0.tar.gz
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
==> Patch /projects/spack2020/var/spack/repos/builtin/packages/py-h5py/h5py-3-setuprequires.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/projects/spack2020/var/spack/repos/builtin/packages/py-h5py/h5py-3-setuprequires.patch' '-d' '.'
```

**Review by sethrj — CHANGES_REQUESTED** [review]
Needs update to patching process to for 3.3 to install correctly

**Comment by sethrj** [comment]
Looks like that patch is due to #22262, could @bryanherman weigh in?

**Comment by bryanherman** [comment]
> Looks like that patch is due to #22262, could @bryanherman weigh in?

We added that patch because of the strict "==" checking in the setup.py. If that environment variable disables that checking, I am in favor of removing the patch file, setting that build environment variable and controlling the dependencies only through the Spack recipe.

**Review by adamjstewart — APPROVED** [review]

**Review by sethrj — APPROVED** [review]

**Pull request merged**
