### PR TITLE
sollve: remove sollve package

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
This PR removes `sollve`, which is superseded by `llvm-doe` (#20719).

Since #20767 has not been merged. I would like to remove `sollve`. As far as I checked with users, removal is okay (`llvm-doe` should be used instead).

(@clementval, @jdoerfert, @Meinersbur, @vlkale)

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
@alalazo Could you please review this PR?

**Review by alalazo — APPROVED** [review]
@adamjstewart Let me know if you have any objection removing this package directly without passing from deprecating it.

**Comment by adamjstewart** [comment]
I don't use this package, and no other package depends on it. I do really think we should be moving towards a deprecation model, which is why I opened #20767 and #15896. Basically, I won't complain if you remove the package without warning, but other users might, and I think they have a right to complain. So neither an approval or disapproval from me 😄

**Comment by shintaro-iwasaki** [comment]
Thanks. Keeping this package doesn't hurt us, so we will keep this package if it's okay until #20767 is merged.

Unless someone wants to remove this package immediately, I will recreate a PR that deprecates `sollve` after #20767 is merged.

**Comment by adamjstewart** [comment]
#20767 has been merged now!

**Comment by shintaro-iwasaki** [comment]
I created a PR #21578 to deprecate `sollve`. Once #21578 is merged, I will close this PR.

**Comment by shintaro-iwasaki** [comment]
Since #21578 has been merged, this PR is not necessary. I will close this PR.
Thank all the reviewers for reviewing our series of PRs.

**Pull request closed without merging**
