### PR TITLE
gurobi: update and fix build

### PR DESCRIPTION
**Pull request by glennpj**
- add version 9.5.1
- this package can not be install with pip, it uses distutils

### CODE REVIEW

**Comment by glennpj** [comment]
@spackbot start pipeline

**Comment by glennpj** [comment]
@spackbot run pipeline

**Comment by alalazo** [comment]
@glennpj Can you please rebase (sorry about that, this is needed for generating a new commit for pipelines)?

**Comment by glennpj** [comment]
@alalazo I used the new "Update branch" button. That seemed to do the trick.

**Review by alalazo — APPROVED** [review]

**Pull request merged**
