### PR TITLE
GCC Compiler Dependencies

### PR DESCRIPTION
**Pull request by rgmiller**
Change the package to use gcc's built-in script for downloading some of its dependencies.

### CODE REVIEW

**Comment by alalazo** [comment]
With this `gcc` can't be mirrored anymore.

**Comment by tgamblin** [comment]
In addition to making `gcc` un-mirrorable, this also prevents people from building combinatorial versions of `gcc`.  The idea with Spack is to actually expose all of the dependencies.  Is there a reason you want this behavior?

**Comment by rgmiller** [comment]
@alalazo Why is fetching tarballs a problem?  You do that anyway for the gcc tarball, after all.   (I'm new to spack; what do you mean by "un-mirrorable".)

@tgamblin Yes.  The problem is that the dependencies specified in the depends_on() statements aren't always used during the build(!)  The only reason I noticed this was that I was trying to build gcc 7 on a SLES12 distribution that includes an old isl library.  In the original version of the package, Spack dutifully downloaded and built a new isl, but when it went to compile gcc, it was still using the system-installed isl (which was tool old and caused the gcc build to fail).  I ended up having to manually load the module for the isl package (and other dependencies) and then build gcc with the "--dirty" flag in order to get the new versions of the dependencies.

**Comment by rgmiller** [comment]
@tgamblin  There's some more details available in the comments for issue #5397

**Comment by tgamblin** [comment]
@rgmiller: 
> Why is fetching tarballs a problem? You do that anyway for the gcc tarball, after all. (I'm new to spack; what do you mean by "un-mirrorable".)

See here: https://spack.readthedocs.io/en/latest/mirrors.html

`spack mirror` puts all the dependencies and other resources needed for a build into a directory that you can ship across an airgapped network, and still build on the other side.  If *you* fetch the dependencies, Spack doesn't know how to mirror them, so this would break offline builds.

Also, if you install the dependencies, Spack can't reproduce an arbitrary `gcc` configuration for, say, testing.  We want all the packages to be able to build with any combination of dependencies.

> Yes. The problem is that the dependencies specified in the depends_on() statements aren't always used during the build(!)

I think this is the main problem -- so it looks like our `gcc` build isn't perfect.  The right thing to do here is to get the right RPATHs into the build -- I put some comments over on #5397.

**Pull request closed without merging**
