### PR TITLE
py-parsl - added recipe for Parsl (see https://parsl-project.org/)

### PR DESCRIPTION
**Pull request by hategan**
Status: To be updated to have it's dependencies added:
It depends on #26395 (now merged) and #26411 (should be merged in the next days, at least by the start of next week)

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
Please remove all versions below 1.1.0 except those your project really requires.

Different versions of packages often have different depends and just supporting the single current version from the start helps to start off simple. Later more versions are added over time anyway.

**Comment by bernhardkaindl** [comment]
@hategan  When running `spack install -v --test=root py-parsl`, I get:
```py
==> [2021-09-30-09:42:52.815555] RUN-TESTS: install-time tests [test]
=> [2021-09-30-09:42:52.821528] checking import of parsl
==> [2021-09-30-09:42:52.821697] '/home/kaindlb/spack/spack/.tree/linux-ubuntu18.04-zen/gcc-8.4.0/python-3.8.11-3uwlldorpbj3p3kkyjiqob4yzr6ppfql/bin/python3.8' '-c' 'import parsl'
...
    import typeguard
ModuleNotFoundError: No module named 'typeguard'
```
Maybe there is more after fixing that, please run that `--test=root` yourself:

I guess that py-typegard should be a test and runtime dependency, maybe also check the requirements.txt or so if that mentions such dependencies. As it seems that py-typeguard isn't a package yet, you can add it either in the PR with one more commit or a new PR, YMMV and maybe Adam's. I guess if it's a completely trivial small package, then you could see if it in this PR as well, as it would make testing and merging your branch much easier, I think.

example how the dependencty on py-typeguard could be added (and likely just with 'test' and 'run', I guess...):
```py
py-tomopy/package.py:    depends_on('py-scipy',                      type=('build', 'test', 'run'))
```
Just a comment to possible readers in general: This looks like a cool project to identify all the different python-requirement formats: https://github.com/dephell/dephell We'd need something that can check this automatically.

**Comment by hategan** [comment]
>> py-typegard should be a test and runtime dependency

> I was under the (false) impression that the dependencies are installed as part of running `setup.py install`, but now I see that Spack invokes it with `--single-version-externally-managed`, which prevents that. Sorry about that. I'm changing this to a draft until relevant dependencies are added.

Yes, Adam told me in another PR that the automatic dependency install in setup.y install caused build problems.
Doing it this way allows spack to track and solve all dependencies (version requirements) between all parts of the build. I think this is what he might have ment.

BTW: #26395 is now merged, #26411 should be merged soon, at least by the start of next week.

**Comment by hategan** [comment]
Relevant dependencies have been added, some of which needed to be added as new packages. This branch was also rebased on top of develop so that the new packages can be used by this PR. Additionally, Parsl needs specific versions of `mypy` and `sphinx`, so there is now a commit in this branch that adds those specific versions to existing packages.

PS: commit 56c70271806ecbe565c619a286f7e52a856bca72 contains the requested changes.

**Review by bernhardkaindl — APPROVED** [review]

**Comment by hategan** [comment]
Thanks for all the help @bernhardkaindl !

**Pull request merged**
