### PR TITLE
Fix linux/cmake

### PR DESCRIPTION
**Pull request by serbanmaerean**
Module/FindDoxygen.cmake uses Windows based directory for file globbing that create issues on Linux.  I removed that code on Linux.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Does this bug also affect macOS? We don't really support Windows, so if this affects all non-Windows OSes, you can always apply the patch.

Have you notified the developers of this bug?

**Comment by adamjstewart** [comment]
@mathstuf

**Comment by serbanmaerean** [comment]
I did not try it on MacOS.  However, on Linux, the shell does not like '(' and that throws the file command off.
Also, it seems that some of the checks did not complete and were marked as wrong:
"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated"
Don't know what it means.

**Comment by serbanmaerean** [comment]
I sent a note to cmake@cmake.org, but no response from them yet.

**Comment by serbanmaerean** [comment]
@adamjstewart Hi Adam, is it possible to restart the Travis CI build?  I cannot tell what trigger that error.  Thanks.

**Comment by adamjstewart** [comment]
@serbanmaerean Restarted the failing job. It looks like it was a Homebrew problem. Failed to install GCC.

**Comment by serbanmaerean** [comment]
When I tried to reproduce the problem for cmake developers, I cannot do that.  I reckon we had a network issue (it was very slow for a few days around that time).  Also, based on the response received from the cmake developers, cmake is using quotes around the paths produced, so the Windows paths should not create problems, just extra work.

**Comment by adamjstewart** [comment]
So it sounds like this PR is no longer needed? Do you mind if I close it then?

**Pull request closed without merging**
