### PR TITLE
babl: add v0.1.102

### PR DESCRIPTION
**Pull request by alecbcs**
Add Babl v0.1.102.

**Changelog:**
https://gegl.org/babl/index.html#News

### CODE REVIEW

**Comment by benkirk** [comment]
Looks good!

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256.  Will defer merge decision to give @benkirk a chance to comment.

**Comment by tldahlgren** [comment]
While the checks for this pass, my attempt to build this has already surpassed 45 minutes and it is still in the `'build'` phase. Is it supposed to take that long?

**Comment by alecbcs** [comment]
I can check the build log when I get home tonight. I do remember some of these packages taking quite a long time to compile though I don't remember if babl was one specifically.

**Comment by alecbcs** [comment]
@tldahlgren it doesn't seem like babl took very long to install for me. Does it still get stuck on your system?

```
==> Installing babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7
==> No binary for babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7 found: installing from source
==> Fetching https://download.gimp.org/babl/0.1/babl-0.1.102.tar.xz
==> No patches needed for babl
==> babl: Executing phase: 'meson'
==> babl: Executing phase: 'build'
==> babl: Executing phase: 'install'
==> babl: Successfully installed babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7
  Stage: 2.37s.  Meson: 2.83s.  Build: 7.27s.  Install: 0.25s.  Total: 12.90s
```

**Comment by tldahlgren** [comment]
> @tldahlgren it doesn't seem like babl took very long to install for me. Does it still get stuck on your system?
> 
> ```
> ==> Installing babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7
> ==> No binary for babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7 found: installing from source
> ==> Fetching https://download.gimp.org/babl/0.1/babl-0.1.102.tar.xz
> ==> No patches needed for babl
> ==> babl: Executing phase: 'meson'
> ==> babl: Executing phase: 'build'
> ==> babl: Executing phase: 'install'
> ==> babl: Successfully installed babl-0.1.102-lm7dx2w2yq2mlmoxz6fg7va62elrsnw7
>   Stage: 2.37s.  Meson: 2.83s.  Build: 7.27s.  Install: 0.25s.  Total: 12.90s
> ```

```
==> Installing babl-0.1.102-ru57i326v36os7e4ep3um5vq5hrf22y6
==> No binary for babl-0.1.102-ru57i326v36os7e4ep3um5vq5hrf22y6 found: installing from source
==> Fetching https://download.gimp.org/babl/0.1/babl-0.1.102.tar.xz
==> No patches needed for babl
==> babl: Executing phase: 'meson'
==> babl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status -6:
    '/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/ninja-1.11.1-vofbrynwe2frtqzdfm2cv3tf3cqvxylv/bin/ninja' '-j16' '-v'

1 warning found in build log:
     65    Run-time dependency vapigen found: YES 0.40.8
     66    Program git found: YES (/usr/tce/bin/git)
     67    Program env found: YES (/usr/bin/env)
     68    Program rsvg-convert found: YES (/usr/bin/rsvg-convert)
     69    Program w3m found: YES (/usr/bin/w3m)
     70    Configuring config.h using configuration
  >> 71    WARNING: You should add the boolean check kwarg to the run_command c
           all.
     72             It currently defaults to false,
     73             but it will default to true in future releases of meson.
     74             See also: https://github.com/mesonbuild/meson/issues/9300
     75    Program gen_babl_map.py found: YES (/usr/tce/packages/python/python-
           3.7.2/bin/python3 /tmp/dahlgren/spack-stage/spack-stage-babl-0.1.102
           -ru57i326v36os7e4ep3um5vq5hrf22y6/spack-src/gen_babl_map.py)
     76    Checking if "-Wl,--version-script" : links: YES
     77    Configuring babl-version.h using configuration

See build log for details:
  /var/tmp/dahlgren/spack-stage/spack-stage-babl-0.1.102-ru57i326v36os7e4ep3um5vq5hrf22y6/spack-build-out.txt

1385.898u 3626.562s 1:25:59.56 97.1%	0+0k 242312+1152io 228pf+0w

$ cat /var/tmp/dahlgren/spack-stage/spack-stage-babl-0.1.102-ru57i326v36os7e4ep3um5vq5hrf22y6/spack-build-out.txt
...
[282/283] /usr/WS1/dahlgren/releases/spack/lib/spack/env/gcc/gcc  -o tools/babl-benchmark tools/babl-benchmark.p/babl-benchmark.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/../babl:/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/lcms-2.13.1-sdkdxa73matf7y7u2xbrskb6tjc4g2wx/lib' -Wl,-rpath-link,/tmp/dahlgren/spack-stage/spack-stage-babl-0.1.102-ru57i326v36os7e4ep3um5vq5hrf22y6/spack-build-ru57i32/babl -Wl,-rpath-link,/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/lcms-2.13.1-sdkdxa73matf7y7u2xbrskb6tjc4g2wx/lib -Wl,--start-group babl/libbabl-0.1.so.0.201.1 -lm -pthread /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/lcms-2.13.1-sdkdxa73matf7y7u2xbrskb6tjc4g2wx/lib/liblcms2.so -Wl,--end-group
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by alecbcs** [comment]
@benkirk could you do a build of this locally and see if you can reproduce @tldahlgren's error?

**Comment by benkirk** [comment]
@alecbcs & @tldahlgren I will build locally.  This is one of my first Spack contributions, so I hope you afford me a question or two...

@tldahlgren anything you can share about your host machine or the Spack environment that is creating your issue?

**Comment by alecbcs** [comment]
Oh sorry @benkirk, I didn't mean to sign you up for a bunch of work. I just meant if you could also attempt to build the new package version then I'd know if for some reason something is present on my system that isn't in the recipe.

**Comment by tldahlgren** [comment]
> @alecbcs & @tldahlgren I will build locally. This is one of my first Spack contributions, so I hope you afford me a question or two...
> 
> @tldahlgren anything you can share about your host machine or the Spack environment that is creating your issue?

```
$ spack debug report
* **Spack:** 0.20.0.dev0 (e5a992ba5126b46536f638fdcc71eae8fef96bd1)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo
```

**Comment by tldahlgren** [comment]
I'm going to try something.  I just clicked `Update branch`.  Let me see if some recent dependency updates help with my build.

**Comment by alecbcs** [comment]
@tldahlgren did updating the branch fix it for you? Looks like it has passed all of the CI tests now.

**Comment by tldahlgren** [comment]
> @tldahlgren did updating the branch fix it for you? Looks like it has passed all of the CI tests now.

Not getting the previous issue.

**Pull request merged**
