### PR TITLE
dependency fix for python3

### PR DESCRIPTION
**Pull request by marcmengel**
We don't need py-backports stuff in python 3...

### CODE REVIEW

**Comment by adamjstewart** [comment]
`install_requires` lists the dependency unconditionally. If you make the change in this PR and build in verbose mode, does it look like setuptools is downloading the dependency automatically?

**Comment by marcmengel** [comment]
in 8.3.0,the setup.cfg says:
...
setup_requires = 
	setuptools_scm>=1.15.0
	setuptools_scm_git_archive>=1.0
install_requires = 
	backports.functools_lru_cache; python_version < '3.3'
	six>=1.11.0
	more_itertools>=2.6
	jaraco.functools
...

and of course, there *is* *no* backports_functools_lru_cache in python 3.4+, as 
that is where it is backported from...

Attaching the spack-build-out.txt from reinstalling it in a python 3.8.3 environment, if that's helpful.
[spack-build-out.txt](https://github.com/spack/spack/files/5086816/spack-build-out.txt)

**Comment by adamjstewart** [comment]
Ah, I was looking at the old release. Can you sort the versions from newest to oldest and put each version on a single line? We ignore versions and URLs in our flake8 line-length checks.

**Comment by marcmengel** [comment]
Done.

**Review by adamjstewart — APPROVED** [review]

**Pull request merged**
