### PR TITLE
qt: Fix the assimp dependency specification

### PR DESCRIPTION
**Pull request by chuckatkins**
libassimp has been a dependency for all of 5.x.  The initial behavior
was to use an external version and fallback to an internal version if
not found.  An external assimp has always worked, however it wasn't
until 5.9 that internal vs external was configure-selectable.  The
previous patch addressed the fallback case of an internally supplied
libassimp and is no longer necessary with the correctly specified
when='@5:' range which will ensure an external version is always available.

### CODE REVIEW

**Review by sethrj — APPROVED** [review]

**Comment by wdconinc** [comment]
I just verified that by removing the patch this PR **reintroduces the build error** that the patch was intended to resolve, that is described in https://bugreports.qt.io/browse/QTBUG-84037, and for which a fix is not available in the upstream archives. See this build log: [spack-build-out.txt](https://github.com/spack/spack/files/8606363/spack-build-out.txt). 

The underlying issue is that the following code is incorrect:
```c++
qtConfig(system-assimp):!if(cross_compile:host_build) {
    QMAKE_USE_PRIVATE += assimp
} else {
    include(../../../3rdparty/assimp/assimp.pri)
}
```
The `QMAKE_USE_PRIVATE += assimp` is relevant when a system-wide assimp is used (our desired condition), but the target for that system-wide assimp is not `assimp`, but `quick3d-assimp`.

**Comment by wdconinc** [comment]
Relevant lines:
```
     8262    Project ERROR: Library 'assimp' is not defined.
  >> 8263    make[4]: *** [Makefile:73: sub-assimp-make_first] Error 3
```

**Comment by sethrj** [comment]
Sorry @wdconinc I was too quick with the merge button.

@chuckatkins is your goal to prefer the *vendored* internal Qt dependency to a spack-built (and reusable) dependency? Can you please explain your use case the errors you got with the existing version?

**Comment by chuckatkins** [comment]
Hmm, yeah this wasn't expected at all.  The patch was causing a build error for me and removing the patch caused it to succeed.  My intent was to make qt always use an external assimp.  As I understood it the patch forces the internal assimp even when an external one is specified.

**Pull request merged**
