### PR TITLE
linaro-forge: moved package file following rebranding and added 23.0

### PR DESCRIPTION
**Pull request by kenche-linaro**

### CODE REVIEW

**Comment by tldahlgren** [comment]
Adding maintainers associated with affected packages to include @NickRF and @robgics .

**Review by tldahlgren — COMMENTED** [review]
Should `ddt` (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ddt/package.py) also be changed since it also uses the `arm-force` URL?

**Review by tldahlgren — COMMENTED** [review]
FYI. Confirmed the version sha256 for x86_64.

**Comment by kenche-linaro** [comment]
> Should `ddt` (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ddt/package.py) also be changed since it also uses the `arm-force` URL?

Thanks. I have removed this package entirely because the download link will become outdated and we do not have a link for 22.0.2 at Linaro (we have 22.0.4 instead). It also silently accepts the EULA.

**Comment by kenche-linaro** [comment]
@tldahlgren, could you advise on how we can move this forward? Thanks.

**Comment by kenche-linaro** [comment]
@tldahlgren , I'll recreate this PR with a change that doesn't touch the other files.

**Pull request closed without merging**
