### PR TITLE
ngspice: adding version 37

### PR DESCRIPTION
**Pull request by cessenat**
and that's all there is to it.

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
Confirmed sha256.

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Comment by aweits** [comment]
> and that's all there is to it.

builds for me:

```
==> ngspice: Successfully installed ngspice-37-4q4rywthciyytn7mkstgfjxk5lfxktgp
  Fetch: 5.12s.  Build: 1m 28.53s.  Total: 1m 33.65s.
[+] /dev/shm/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/ngspice-37-4q4rywthciyytn7mkstgfjxk5lfxktgp
```

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Pull request merged**
