### PR TITLE
Dbcsr: Patch for resolving .mod file conflicts in ROCm by implementin…

### PR DESCRIPTION
**Pull request by BOUDAOUD34**
When installing Cp2k version>2023.2 with ``build_system=cmake``, we encountered issues with .mod file incompatibility between different compilers while installing the Dbcsr dependency. 

This PR is dependent on #45848 (now merged)

### CODE REVIEW

**Review by mtaillefumier — APPROVED** [review]
I have no objections to this changes. 
I would however suggest not to mix different compilers if possible because it is always source of errors. I also wonder if we should not push these changes directly in dbcsr.

**Comment by BOUDAOUD34** [comment]
I installed Cp2k with gcc, but when enabling "+rocm", it uses the file ``/opt/rocm-5.7.1/llvm/include/iso_c_binding.mod`` which causes the error : `` Fatal Error: File /opt/rocm-5.7.1/llvm/include/iso_c_binding.mod opened at (1) is not a GNU Fortran module file``

**Comment by mtaillefumier** [comment]
Interesting bug. Can you post the command line you used so that I can have a look later on

**Comment by BOUDAOUD34** [comment]
``cp2k@2024.1%gcc@12.1+cosma~cuda~dlaf+elpa+libint~libvori+libxc+mpi+openmp~pexsi~plumed+rocm~sirius+spglib~spla amdgpu_target=gfx90a build_system=cmake build_type=Release lmax=5 smm=blas  ^cray-libsci ^cray-fftw ^tiled-mm amdgpu_target=gfx90a ^dbcsr+rocm amdgpu_target=gfx90a ^elpa amdgpu_target=gfx90a
``

**Review by mtaillefumier — APPROVED** [review]
We should merge this PR as it seems to be blocking some users.

**Comment by BOUDAOUD34** [comment]
@dev-zero Could you please approve this PR ? 
@alalazo 
@RMeli

**Comment by BOUDAOUD34** [comment]
@alalazo could you please approve this PR ?

**Review by alalazo — APPROVED** [review]

**Pull request merged**
