### PR TITLE
ci: require x86_64_v3 everywhere

### PR DESCRIPTION
**Pull request by haampie**
previously there was a preference for a generic arch x86_64,
but CI would concretize to avx512 in some cases.

Instead, require x86_64_v3 uniformly in all x86 pipelines

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
@zackgalbreath @scottwittenburg  I thought we had discussed this previously and there was a reason for not doing this for all of the stacks. The ML pipelines were unique in this, which is why they are set up to use the `.../configs/linux/x86_64_v4` configs, but everything else was using the generic arch.

**Comment by haampie** [comment]
v4? I would be very surprised if we ran on machines that did not support AVX2 :thinking: they would be very ancient (> 10yo) Ivy/Sandy bridge machines. I don't think data centers still run those because they're not very efficient.

**Comment by zackgalbreath** [comment]
> v4? I would be very surprised if we ran on machines that did not support AVX2 🤔 they would be very ancient (> 10yo).

We do separately support x86_64_v2 nodes in our autoscaling setup:

https://github.com/spack/spack-infrastructure/tree/main/k8s/karpenter/provisioners/runners/x86_64

That being said, I'm not opposed to requiring a minimum of v3 and dropping our v2 provisioner if that seems like the right thing to do

**Comment by haampie** [comment]
https://aws.amazon.com/intel/ this suggests AWS's oldest CPU type is Haswell, which is the first to support AVX2.

**Comment by zackgalbreath** [comment]
> https://aws.amazon.com/intel/ this suggests AWS's oldest CPU type is Haswell, which is the first to support AVX2.

Last fall we ran archspec on all the EC2 instance types we could get our hands on. Here's the list of instance types we found that were too old to be considered x86_64_v3.



| instance type  | uarch |
| ------------- | ------------- |
c3.large | ivybridge
g2.2xlarge | ivybridge
i2.xlarge | ivybridge
m3.medium | ivybridge
r3.large | ivybridge
m2.xlarge | nehalem
t1.micro | nehalem
c1.medium | westmere
m1.small | westmere

**Comment by haampie** [comment]
Is requiring v3 an option? A package manager for HPC that forbids use of vector registers is kinda ridiculous...

In any case, the point of this PR is mostly not to build for x86-64-v4 by accident.

**Comment by zackgalbreath** [comment]
> Is requiring v3 an option?

No objections from me. I guess the only benefit of keeping v2 around would be a slightly larger pool of nodes to draw from. Doesn't seem like that big of a deal in my opinion.

**Comment by kwryankrattiger** [comment]
I am remembering something about "building for the 1%" or something along those lines. I am not sure who said that, but it was ringing in my head.

On the update side of this, then the other change that will be needed is in the `share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml` the `.linux-x86_64` variables will need to point to the same place as the `.linux-x86_64_v4` variables, or delete the `v4` version and change the ML stacks to just use the x86_64, move the `.../configs/linux/x86_64_v4 -> .../configs/linux/x86_64`, and delete the old v4 references.

I think it would also be helpful to put a `packages.yaml` in the `.../configs/linux/x86_64` path that contains the

```yaml
packages:
   all:
      require: `target=x86_64_v3`
```

That way we don't have to apply it to all of the `spack.yaml`s and new stacks using that umbrella will get it for free.

**Comment by haampie** [comment]
Lol yeah, that was me about v4 😆 that's definitely not universal. But v3 is pretty universal.

I'm confused about this v4 label in gitlab. Is it meant to be v3?

**Comment by kwryankrattiger** [comment]
Yeah, so I think there was a tagging issue or something along those lines, but in Spack CI v4 means v3 and generic means v2 I believe. @zackgalbreath could correct me on that.

There might be some additional infrastructure changes required to fix the tagging, but if you look at how the ml stack is done it tags v4 but then requests v3. I would love to drop the `x86_64_v4` configs and consolidate those if possible, having both was only done to replicate what was there before.

**Comment by zackgalbreath** [comment]
> Yeah, so I think there was a tagging issue or something along those lines, but in Spack CI v4 means v3 and generic means v2 I believe. @zackgalbreath could correct me on that.

I could be wrong, but that sounds crazy to me 😄 . In my opinion:
* x86_64 should mean v1 (you'll probably get lucky & get a CPU manufactured in the past 20 years, but no guarantees unless you're more specific in your requirements)
* x86_64_v2 means v2
* v3 means v3
(etc)

**Comment by haampie** [comment]
@zackgalbreath this is only causing confusion... What's the current state of things? There are runners tagged v4 that are v3, correct? And that's because nobody updated those after the ML stack went from v4 (which was a mistake) to v3 (which is good).

**Comment by zackgalbreath** [comment]
> There are runners tagged v4 that are v3, correct?

That is not my understanding.

v4 runners [ask for nodes from](https://github.com/spack/spack-infrastructure/blob/main/k8s/runners/public/x86_64/v4/release.yaml#L80
) the `glr-x86-64-v4` node pool

The list of EC2 instance types that [fall into this node pool](https://github.com/spack/spack-infrastructure/blob/main/k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml#L27) were identified by the previously mentioned archspec experiment last fall.

**Comment by haampie** [comment]
Okay, we're not building anything for v4, so then that pool should be made bigger.

**Comment by haampie** [comment]
> I think it would also be helpful to put a packages.yaml in the .../configs/linux/x86_64 path that contains the

I won't do that because `all:` is not extensible at this point, so it would get overridden by individual pipelines.

**Comment by adamjstewart** [comment]
> The ML pipelines were unique in this, which is why they are set up to use the `.../configs/linux/x86_64_v4` configs, but everything else was using the generic arch.

Just to clarify, when I wrote the original pipelines, I had absolutely no idea what I was doing and simply tried to copy other pipelines. So from my end, there's no reason to make the ML pipelines special, feel free to unify them if possible.

**Comment by scottwittenburg** [comment]
I could be mis-remembering, but I thought the v2 and v3 pools were taken offline or broken at one point, so any jobs for specs targeting v3 had to be tagged so they'd run on hardware that could handle them (meaning not-v1, aka v4).

**Comment by haampie** [comment]
I've set `tags: ["x86_64_v3, "x86_64_v4"]` hoping that means either/or.

Can you create a runner group `x86_64_v3` so resolve this confusing stuff once and for all? It doesn't make sense to use only avx-512 nodes to build avx2 stuff.

**Comment by zackgalbreath** [comment]
> Can you create a runner group `x86_64_v3` so resolve this confusing stuff once and for all? It doesn't make sense to use only avx-512 nodes to build avx2 stuff.

To clarify, we already have the following types of cloud runners:
* x86_64_v2
* x86_64_v3
* x86_64_v4
* graviton2
* graviton3

Each of these groups are split into public and protected subgroups.

**Comment by zackgalbreath** [comment]
> I've set `tags: ["x86_64_v3, "x86_64_v4"]` hoping that means either/or.

I would set this to "x86_64_v3". These runner groups are not mutually exclusive. For example, a v4 runner can pick up v2 or v3 jobs.

**Comment by haampie** [comment]
okay, sanity restored :laughing: why was this not pointed out in review when going from v4 -> v3 in the stacks I wonder...

**Comment by haampie** [comment]
oof, ci runs on a merge commit with c29168eff1b37c9c89db3d2de8aad94e998cb8db which just doesn't include the spec.json minification revert. rebasing...

Ah, that was not necessary cause pr pipelines are unsigned and don't run into the gpg-long-line-bug

**Comment by haampie** [comment]
@spackbot run pipeline

**Comment by haampie** [comment]
@adamjstewart I've changed your pipeline to force openmpi as mpi provider, is that OK? It concretized to _checks notes_ `mpilander`?! On develop it's `mvapich2`? Generally confusing, I thought it should just pick `openmpi`/`mpich` since those are the default preferences... Does the implementation matter?

**Review by alalazo — APPROVED** [review]
LGTM, waiting for :heavy_check_mark:  from @adamjstewart (for the ML change) and either @zackgalbreath or @scottwittenburg before merging

**Comment by haampie** [comment]
Let's merge it in the next couple hours though, before it gets out of date again.

**Review by adamjstewart — APPROVED** [review]

**Review by zackgalbreath — APPROVED** [review]

**Comment by haampie** [comment]
Thanks!

**Pull request merged**
