### PR TITLE
duckdb: version 1.1.2 + install headers and libraries

### PR DESCRIPTION
**Pull request by mdorier**
This PR does the following:

- Add version 1.1.2
- Install the headers and libraries (previously, only the duckdb executable was installed)

I have tested the installation with all the non-deprecated versions.

### CODE REVIEW

**Comment by teaguesterling** [comment]
Thanks for implementing the libs and headers install @mdorier! You beat me to adding v1.1.2 :-)

This looks good to me. I've verified the checksum.

**Review by teaguesterling — APPROVED** [review]
LGTM

**Review by tldahlgren — APPROVED** [review]
confirmed the sha256.

**Comment by glentner** [comment]
I was too slow to get to this so missed it prior to already getting merged. But can confirm successful fresh build (a) of v1.1.2 with headers and libraries included.

(a) with RHEL 8 (GCC 8.5.0) on AMD Zen3 server.

**Pull request merged**
