### PR TITLE
openbabel: add 3.1.0 and 3.1.1

### PR DESCRIPTION
**Pull request by RMeli**

### CODE REVIEW

**Comment by alalazo** [comment]
@spackbot run pipeline

**Review by alalazo — APPROVED** [review]

**Comment by tldahlgren** [comment]
FYI. I am trying to build a package that depends on v3.1.1 and am getting a `syntax` error `scripts/openbabel-python.i:79:\nError: Syntax error in input(1).`.

```
...
==> Installing openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty
==> No binary for openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty found: installing from source
==> No patches needed for openbabel
==> openbabel: Executing phase: 'cmake'
==> openbabel: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/make' '-j16'

6 errors found in build log:
     104     
     105     
     106     -- Found SWIG: /usr/bin/swig (found version "2.0.10")
     107     -- Found SWIG: /usr/bin/swig (found suitable version "2.0.10", min
             imum required is "2.0")
     108     -- Found PythonLibs: /usr/WS1/dahlgren/releases/spack/opt/spack/li
             nux-rhel7-broadwell/gcc-8.3.1/python-3.10.8-ilzdwnyddk5jhoiyfx7x4o
             ccjnxjpdbr/lib/libpython3.10.so (found version "3.10.8")
     109     -- Python bindings will be compiled
  >> 110     <string>:1: DeprecationWarning: The distutils package is deprecate
             d and slated for removal in Python 3.12. Use setuptools or check P
             EP 632 for potential alternatives
  >> 111     <string>:1: DeprecationWarning: The distutils.sysconfig module is 
             deprecated, use sysconfig instead
     112     -- Configuring done (14.4s)
     113     -- Generating done (1.0s)
     114     -- Build files have been written to: /tmp/dahlgren/spack-stage/spa
             ck-stage-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-bu
             ild-ftfvutf
     115     ==> openbabel: Executing phase: 'build'
     116     ==> [2023-03-21-10:20:53.197708] '/usr/bin/make' '-j16'
     117     /usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/g
             cc-8.3.1/cmake-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt/bin/cmake -
             S/var/tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutf
             hihkdaumnreqt2pw54fdcjnty/spack-src -B/tmp/dahlgren/spack-stage/sp
             ack-stage-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-b
             uild-ftfvutf --check-build-system CMakeFiles/Makefile.cmake 0

     ...

     2409    [ 86%] Built target obthermo
     2410    [ 87%] Linking CXX executable ../bin/obgrep
     2411    cd /tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfhi
             hkdaumnreqt2pw54fdcjnty/spack-build-ftfvutf/tools && /usr/WS1/dahl
             gren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cmak
             e-3.26.0-srzx5o53zkfeknlrx4cxvlntrgaqpfdt/bin/cmake -E cmake_link_
             script CMakeFiles/obgrep.dir/link.txt --verbose=1
     2412    [ 87%] Building CXX object test/CMakeFiles/test_runner.dir/canonco
             nsistenttest.cpp.o
     2413    cd /tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfhi
             hkdaumnreqt2pw54fdcjnty/spack-build-ftfvutf/test && /usr/WS1/dahlg
             ren/releases/spack/lib/spack/env/gcc/g++ -DFORMATDIR=\"/tmp/dahlgr
             en/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw
             54fdcjnty/spack-build-ftfvutf/lib//\" -DHAVE_EIGEN -DHAVE_EIGEN3 -
             DHAVE_LIBZ -DHAVE_RADPIJSON -DHAVE_SHARED_POINTER -DHAVE_WXWIDGETS
              -DTESTDATADIR=\"/var/tmp/dahlgren/spack-stage/spack-stage-openbab
             el-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-src/test/files/\" 
             -DUSING_DYNAMIC_LIBS -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXG
             TK__ -I/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broa
             dwell/gcc-8.3.1/zlib-1.2.13-ka5j3ojbhkydgkv3rvwxadc4rh3f5ak4/inclu
             de -I/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadw
             ell/gcc-8.3.1/boost-1.81.0-kohyvajala7k34olkeybbjw57eo7jtf4/includ
             e -I/tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfh
             ihkdaumnreqt2pw54fdcjnty/spack-build-ftfvutf/include -I/var/tmp/da
             hlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfhihkdaumnreq
             t2pw54fdcjnty/spack-src/data -I/var/tmp/dahlgren/spack-stage/spack
             -stage-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-src/
             include -I/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7-b
             roadwell/gcc-8.3.1/eigen-3.4.0-b4qhaop3xuijbstppui3tff6a4dfvvr6/in
             clude/eigen3 -I/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rh
             el7-broadwell/gcc-8.3.1/rapidjson-1.2.0-2022-03-09-23aahqpnbogxgj5
             yqetauo53un332w7e/include -I/var/tmp/dahlgren/spack-stage/spack-st
             age-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-src/tes
             t -isystem /usr/lib64/wx/include/gtk2-unicode-release-2.8 -isystem
              /usr/include/wx-2.8 -pthread -O2 -g -DNDEBUG -O2 -g -std=gnu++11 
             -fPIE -pthread -MD -MT test/CMakeFiles/test_runner.dir/canonconsis
             tenttest.cpp.o -MF CMakeFiles/test_runner.dir/canonconsistenttest.
             cpp.o.d -o CMakeFiles/test_runner.dir/canonconsistenttest.cpp.o -c
              /var/tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutf
             hihkdaumnreqt2pw54fdcjnty/spack-src/test/canonconsistenttest.cpp
     2414    /usr/WS1/dahlgren/releases/spack/lib/spack/env/gcc/g++  -pthread -
             O2 -g -DNDEBUG -O2 -g -Wl,--enable-new-dtags -Wl,--fatal-warnings 
             -Wl,--no-undefined -lc -Wl,--enable-new-dtags -Wl,--fatal-warnings
              -Wl,--no-undefined -lc  -rdynamic CMakeFiles/obgrep.dir/obgrep.cp
             p.o -o ../bin/obgrep  -Wl,-rpath,/tmp/dahlgren/spack-stage/spack-s
             tage-openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-build-
             ftfvutf/lib:/usr/WS1/dahlgren/releases/spack/opt/spack/linux-rhel7
             -broadwell/gcc-8.3.1/zlib-1.2.13-ka5j3ojbhkydgkv3rvwxadc4rh3f5ak4/
             lib::::::::::::::::: ../lib/libopenbabel.so.7.0.0 -lm -ldl /usr/WS
             1/dahlgren/releases/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.
             1/zlib-1.2.13-ka5j3ojbhkydgkv3rvwxadc4rh3f5ak4/lib/libz.so -pthrea
             d
  >> 2415    /var/tmp/dahlgren/spack-stage/spack-stage-openbabel-3.1.1-ftfvutfh
             ihkdaumnreqt2pw54fdcjnty/spack-src/scripts/openbabel-python.i:79: 
             Error: Syntax error in input(1).
  >> 2416    make[2]: *** [/var/tmp/dahlgren/spack-stage/spack-stage-openbabel-
             3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-src/scripts/python/op
             enbabel/openbabel-python.cpp] Error 1
     2417    make[2]: Leaving directory `/tmp/dahlgren/spack-stage/spack-stage-
             openbabel-3.1.1-ftfvutfhihkdaumnreqt2pw54fdcjnty/spack-build-ftfvu
             tf'
  >> 2418    make[1]: *** [scripts/CMakeFiles/bindings_python.dir/all] Error 2
     2419    make[1]: *** Waiting for unfinished jobs....
     2420    [ 87%] Building CXX object test/CMakeFiles/test_runner.dir/canonfr
             agmenttest.cpp.o
...
```

**Comment by RMeli** [comment]
Thanks for the report @tldahlgren. ~~I've seen this same issue very recently, but haven't got the time to try to reproduce it. With GCC 11.3.0 (which is what I normally use) the issue does not appear.~~

~~You can see the original report here, from someone trying to install `gnina`:~~ https://github.com/gnina/gnina/pull/184#issuecomment-1476782086

~~So it seems to work with GCC 11.3.0 and fail with GCC 12.1.0 and GCC 8.3.1...~~

**Comment by RMeli** [comment]
Related to https://github.com/openbabel/openbabel/issues/2407

**Comment by RMeli** [comment]
```
     106     -- Found SWIG: /usr/bin/swig (found version "2.0.10")
     107     -- Found SWIG: /usr/bin/swig (found suitable version "2.0.10", min
             imum required is "2.0")
```

I think this is the issue. `openbabel` finds SWIG in `/usr/bin/swig/` instead of finding the one installed by Spack.

**Pull request merged**
