### PR TITLE
mpich: Add `external find` support

### PR DESCRIPTION
**Pull request by rblake-llnl**
Tested and seems to work.

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
I don't know `mpich` very well so I'll wait for someone else to review. It would be great if you could contact the `mpich` developers and ask if anyone of them would like to be official "maintainers" for the Spack recipe.

**Comment by rblake-llnl** [comment]
@yiguo, could I ask you to review this package?  Would you like to volunteer as a maintainer?

We just need someone to confirm that we're not adding any nonsensical compiler flags to the mpich configure line.

**Comment by adamjstewart** [comment]
@rblake-llnl if you don't get a response in a week let me know and I'll merge.

**Review by alalazo — APPROVED** [review]
This is great, thanks!

**Pull request merged**
