### PR TITLE
Add the rocm tag to packages from the Radeon Open Compute Platform.

### PR DESCRIPTION
**Pull request by bvanessen**

### CODE REVIEW

**Review by srekolam — DISMISSED** [review]

**Comment by becker33** [comment]
I'm going to leave this up for a minute and see if anyone like @tgamblin or @haampie has strong feelings about the name of this tag. It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.

**Comment by srekolam** [comment]
@bvanessen  there are still more rocm packages that would require this tag. I can provide the info or i can follow up with a new PR after this one goes in

**Comment by cgmb** [comment]
> It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.

If one tag won't do,
why not use two?
Tag 'amd' and tag 'rocm';
the intersection will be awesome!

**Comment by bvanessen** [comment]
> @bvanessen there are still more rocm packages that would require this tag. I can provide the info or i can follow up with a new PR after this one goes in

@srekolam Please feel free to provide me with the rest of the list.

**Comment by bvanessen** [comment]
> I'm going to leave this up for a minute and see if anyone like @tgamblin or @haampie has strong feelings about the name of this tag. It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.

I understand the concern, but I think that the tag is fair in that these are all part of the ROCm software distribution.  As I said after I asked, I am not sure that it makes sense to provide a common tag for all packages that use a set of libraries, aka rocm-users

**Comment by cgmb** [comment]
> I am not sure that it makes sense to provide a common tag for all packages that use a set of libraries, aka rocm-users

Despite the poem, I agree with you about this. I was thinking an `amd` tag might be nice to help find the AMD CPU libraries, but perhaps those should be `aocl`. I'm rather uninformed on this topic, but choosing paint is always fun. :p

**Comment by srekolam** [comment]
below are the additional rocm recipes. 
hsakmt-roct, llvm-amdgpu , rocm-device-libs , hipify-clang , hip-rocclr
rocm-clang-ocl , atmi,  rocm-bandwidth-test, rocprofiler-dev
rocm-gdb , rocm-openmp-extras , rocprim
rocthrust ,  hipcub , hipfort , rocm-validation-suite
mivisionx ,  hipfft , mlirmiopen

**Comment by bvanessen** [comment]
> llvm-amdgpu

@srekolam I have added all of these packages except for mivisionx, since that is an AMD package, but not part of the ROCm distribution directly.

**Comment by tldahlgren** [comment]
> > I'm going to leave this up for a minute and see if anyone like @tgamblin or @haampie has strong feelings about the name of this tag. It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.
> 
> I understand the concern, but I think that the tag is fair in that these are all part of the ROCm software distribution. As I said after I asked, I am not sure that it makes sense to provide a common tag for all packages that use a set of libraries, aka rocm-users

IMHO When I see `rocm` as a tag, I tend to think the package is associated with `rocm` as in a component similar to how we use the `e4s` tag to associate packages as part of the Extreme-scale Scientific Software Stack (E4S) project.

**Review by tldahlgren — DISMISSED** [review]
LGTM.  Deferring merge decision until someone confirms that the following is a complete list that you want as part of this PR.

```
$ spack tags rocm
rocm:
    atmi          hsakmt-roct     rocfft               rocm-validation-suite
    comgr         llvm-amdgpu     rocm-bandwidth-test  rocprim
    hip           migraphx        rocm-clang-ocl       rocprofiler-dev
    hip-rocclr    miopen-hip      rocm-cmake           rocrand
    hipblas       miopen-opencl   rocm-dbgapi          rocsolver
    hipcub        miopen-tensile  rocm-debug-agent     rocsparse
    hipfft        miopengemm      rocm-device-libs     rocthrust
    hipfort       mlirmiopen      rocm-gdb             roctracer-dev
    hipify-clang  rccl            rocm-opencl          roctracer-dev-api
    hipsolver     rdc             rocm-openmp-extras
    hipsparse     rocalution      rocm-smi
    hsa-rocr-dev  rocblas         rocm-smi-lib
 ```
 
Could the PR title be misleading in the sense that the packages are from different repositories?

**Comment by srekolam** [comment]
rocm-smi  package is deprecated..It would be nice if we can remove tag from that package.

**Comment by tldahlgren** [comment]
Based on a search of packages with repositories under `https://github.com/ROCmSoftwarePlatform`, should the tag be added to `rocm-tensile`?

**Comment by tldahlgren** [comment]
Similarly, a check of packages under `RadeonOpenCompute` suggests `rocminfo` should be included.

**Comment by srekolam** [comment]
rocminfo - yes ..the tag needs to be there. I missed it to tell. With regard to rocm-tensile,  its primarily used by rocblas package . there is no rpm or deb package that is specfic to rocm-tensile that can be installed from the rocm-release. Due that reason, we may skip it for now.

**Comment by bvanessen** [comment]
@

> rocminfo - yes ..the tag needs to be there. I missed it to tell. With regard to rocm-tensile, its primarily used by rocblas package . there is no rpm or deb package that is specfic to rocm-tensile that can be installed from the rocm-release. Due that reason, we may skip it for now.

@srekolam @tldahlgren I added the `rocminfo` and `rocm-tensile` packages.  Also removed the deprecated `rocm-smi` package.

**Comment by bvanessen** [comment]
> > > I'm going to leave this up for a minute and see if anyone like @tgamblin or @haampie has strong feelings about the name of this tag. It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.
> > 
> > 
> > I understand the concern, but I think that the tag is fair in that these are all part of the ROCm software distribution. As I said after I asked, I am not sure that it makes sense to provide a common tag for all packages that use a set of libraries, aka rocm-users
> 
> IMHO When I see `rocm` as a tag, I tend to think the package is associated with `rocm` as in a component similar to how we use the `e4s` tag to associate packages as part of the Extreme-scale Scientific Software Stack (E4S) project.

@tldahlgren So is there another name that you would propose?

**Comment by tldahlgren** [comment]
> > > > I'm going to leave this up for a minute and see if anyone like @tgamblin or @haampie has strong feelings about the name of this tag. It doesn't quite sit right with me, but I'm not thinking of anything better to clarify that this is rocm components, not rocm users.
> > > 
> > > 
> > > I understand the concern, but I think that the tag is fair in that these are all part of the ROCm software distribution. As I said after I asked, I am not sure that it makes sense to provide a common tag for all packages that use a set of libraries, aka rocm-users
> > 
> > 
> > IMHO When I see `rocm` as a tag, I tend to think the package is associated with `rocm` as in a component similar to how we use the `e4s` tag to associate packages as part of the Extreme-scale Scientific Software Stack (E4S) project.
> 
> @tldahlgren So is there another name that you would propose?

If you really want/need a tag that identifies packages that use rocm, the one you proposed or a variant seem reasonable, such as 'rocm-user' or 'uses-rocm'.

I am curious about the use case.  

UPDATE:  If the use case is intended to identify packages that *support* ROCm then perhaps `supports-rocm`.  I tend to associate `user` with people.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Pull request merged**
