### PR TITLE
Move Python 2.6 unit tests to Github Actions

### PR DESCRIPTION
**Pull request by alalazo**
This PR moves Python 2.6 unit tests from Travis to Github Actions. To do so an ad-hoc container image based on CentOS 6 has been created. The image `Dockerfile` is maintained in a [new repository](https://github.com/spack/spack-ci-containers)  of the Spack organization and the image is built and [hosted on Dockerhub](https://hub.docker.com/repository/docker/alalazo/github-actions).

### CODE REVIEW

**Comment by adamjstewart** [comment]
Correct me if I'm wrong, but right now, only the Travis tests need to pass for a PR to be mergeable, correct? We should start adding some of these GitHub Actions as required for merger.

**Comment by alalazo** [comment]
@adamjstewart I agree with that, but to do it we need somebody who can change settings on Spack's repository (it's done through Github UI)

**Comment by becker33** [comment]
@adamjstewart @alalazo I've added to the required tests

I would love to get this merged soon, the queue times in Travis have been killing me while trying to finish up the release.

**Review by adamjstewart — APPROVED** [review]

**Comment by alalazo** [comment]
@becker33 Currently fighting with Centos 6. Running our tests as `root` (determined by running under a Docker image in a VM) causes a bunch of failures. If you think it might  help I can move everything but Python 2.6 and have a final PR for that, since it might take a while to get it done.

**Comment by alalazo** [comment]
Trying to prepare a base image where we run as a normal user. Let's see how it goes. If it's fine, I'll push the `Dockerfile` under `share/qa` and the image on our Dockerhub repository.

**Comment by becker33** [comment]
@alalazo I think we might need to structure this as two PRs.

First PR: Move the flake, shell, and doc tests to github actions

Between PRs: Make the Travis tests not "required"

Second PR: Move the python2.6 tests and drop travis entirely

I don't want to make the Travis tests not required while that includes flake/docs/shell tests, but if we remove travis tests in the first PR it won't let us merge it because it didn't complete a required test.

**Comment by alalazo** [comment]
@becker33 Completely agree with the plan. Also the second PR needs some discussion, since here I tried to get this done on Giuthub Actions using a pushed Docker image. If we want to merge this solution we need to store the Dockerfile (preferably in a separate repo) and build the image on e.g. Dockerhub so what is in there is clear to everybody.

**Comment by alalazo** [comment]
@becker33 @tgamblin This is mostly done. The only thing remaining is to move  the [alalazo/github-actions](https://hub.docker.com/repository/docker/alalazo/github-actions) repository on Dockerhub to something similar in the Spack organization. It's possible we might need to create a [service user](https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds) for somebody other than Todd to be able to link the build to a Github repository.

**Comment by alalazo** [comment]
With respect to this comment:

>  It's possible we might need to create a service user for somebody other than Todd to be able to link the build to a Github repository.

I think we can avoid relinking on the Dockerhub side if we use the official [docker action](https://github.com/docker/build-push-action) to build and push images from https://github.com/spack/spack-ci-containers . Using that action we possibly just need to create a service user and store its credentials as secrets in the repository containing the Dockerfile.

**Review by tgamblin — APPROVED** [review]

**Pull request merged**
