### PR TITLE
mii: update version to fix build error

### PR DESCRIPTION
**Pull request by darmac**
According to https://github.com/codeandkey/mii/issues/5
we should update `mii` to version `1.0.4`

### CODE REVIEW

**Review by alalazo — CHANGES_REQUESTED** [review]
Can we update the `url` and use the `url=` argument to the `version` directive, instead of coding a custom `url_for_version` (which seems overkill)? Also, I'll leave to @codeandkey to say if this is a good idea or not, but we can mark v1.0.2 and v1.0.3 as deprecated.

**Comment by codeandkey** [comment]
1.0.2 and 1.0.3 can safely be marked as deprecated, 1.0.4 is backwards compatible with older versions and just fixed some bugs on newer gccs.

**Comment by darmac** [comment]
Got it, I'll update the patch.

**Comment by darmac** [comment]
Any suggestion for this patch?

**Review by codeandkey — APPROVED** [review]
Looks good!

**Review by alalazo — APPROVED** [review]

**Comment by alalazo** [comment]
@codeandkey Feel free to submit a follow up PR to sign up as a maintainer of the package!

**Pull request merged**
