### PR TITLE
Deprecate old tasmanian

### PR DESCRIPTION
**Pull request by mkstoyanov**
* deprecate older versions of Tasmanian
* update some of the dependencies

### CODE REVIEW

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by mkstoyanov** [comment]
Thanks, @tldahlgren !

The CI system seems stalled again.

**Review by tldahlgren — APPROVED** [review]
LGTM

**Comment by tldahlgren** [comment]
> Thanks, @tldahlgren !
> 
> The CI system seems stalled again.

Let's see if "Update Branch" gets it past the initial changes check.

**Pull request merged**
