### PR TITLE
WIP: switch package import tests to sanity checks

### PR DESCRIPTION
**Pull request by tldahlgren**
TODO

- [ ] Resolve build-time check issues

### CODE REVIEW

**Comment by adamjstewart** [comment]
What is the purpose of this PR? From what I can tell, it removes smoke tests from ~1,600 packages, which sounds pretty bad to me...

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
I'm sorry that I was too busy last week to share my added understanding from last week:

The import tests done in all the python packages are actually dual install-time ***and*** standalone tests:

They run at install time ***and*** with `spack test run <package>`. That means they are correct as they are. They just don't end in a exception with `spack install --test` now.

Another issue I have is that the spack test status/report commands don't show me any test results. 

That means the initial diagnosis that self.run_test() is mis-used for them is wrong. Just the implementation isn'dt completely well integrated yet.

Again sorry for not explaining this earlier, but I also just understood that after trying `spack test run` on such package. The status is that the run_test() is correct, but copying the log file and reportin the error to stdout/the termainal needs improvement.

And we need to improve the developer and user documentation on that so that we ourself at least understand what the status of the import tests is, and how to fix them if they fail ;)

A good example is Manuela Kuhn's fix for `py-pandas`: She replaces the use of the "import_modules" variable and should be on the "don't use it" list with by setting `ignored_imports` and the associated code to implement it instead. It would be even better to support defining the ignored_imports directly in PythonPackage: https://github.com/spack/spack/pull/26668/commits/d68fe41148807fc01b3dc7d48e7eb01b59be28fc

**Comment by adamjstewart** [comment]
I like the idea of supporting an import module blacklist directly in `PythonPackage`. That's adjacent to this PR though, we should open up a separate issue/PR for that feature.

**Comment by tldahlgren** [comment]
> What is the purpose of this PR? From what I can tell, it removes smoke tests from ~1,600 packages, which sounds pretty bad to me...

The intention is *not* to remove the import checks from the packages but to make them more a 'sanity check' (like we can do for the presence of files and directories).  Those checks can then be run after the installation *and*, if desired, as part of the stand-alone test process.

A number of people want to be able to distinguish between the different types of checks in a more automated way.  A package that just does import tests is not testing the functionality of the installed software, for example.

I did not push all of the files I changed.  I'm locally encountering build-time failures for some imports, IIRC when I'm trying to run using a Spack-installed python.

**Comment by adamjstewart** [comment]
> Those checks can then be run after the installation _and_, if desired, as part of the stand-alone test process.

This _is_ desired. Before this PR, these tests are run as stand-alone tests. After this PR, they are not. That's what I mean by removing smoke tests from ~1,600 packages.

> A package that just does import tests is not testing the functionality of the installed software, for example.

From my experience, import tests have caught 99% of build issues with Python libraries. The developers themselves run more extensive unit tests in CI. These tests are only designed to make sure that the package is installed correctly.

I would love to have more extensive unit tests for Python packages. Until then, import tests are better than nothing, and I don't think anyone will be writing ~1,600 more intensive tests themselves.

**Comment by tldahlgren** [comment]
> I'm sorry that I was too busy last week to share my added understanding from last week:

Np. I can relate.

> 
> The import tests done in all the python packages are actually dual install-time _**and**_ standalone tests:
> 
> They run at install time _**and**_ with `spack test run <package>`. That means they are correct as they are. They just don't end in a exception with `spack install --test` now.

There is no intention to change the fact that they run in both cases.  

You mentioned there are packages not extending `python` or `sip` that have import checks so my intention was to move those import checks up in the class hierarchy so they are more readily available.

> 
> Another issue I have is that the spack test status/report commands don't show me any test results.

Have you tried `spack test results -l` to get the results?  The requirement of providing the `-l` option was a design decision early on.  The command will display the contents of the test log file.

> 
> That means the initial diagnosis that self.run_test() is mis-used for them is wrong. Just the implementation isn'dt completely well integrated yet.
> 
> Again sorry for not explaining this earlier, but I also just understood that after trying `spack test run` on such package. The status is that the run_test() is correct, but copying the log file and reportin the error to stdout/the termainal needs improvement.

Writing to and copying the test log file are consistent with how Spack works.  I did discuss this with Todd G. but we can discuss it further.

> 
> And we need to improve the developer and user documentation on that so that we ourself at least understand what the status of the import tests is, and how to fix them if they fail ;)

I agree the documentation needs to be improved. And how to deal with test failures -- including from the stand-alone/smoke tests -- is an on-going off-line discussion topic for some efforts.

> 
> A good example is Manuela Kuhn's fix for `py-pandas`: She replaces the use of the "import_modules" variable and should be on the "don't use it" list with by setting `ignored_imports` and the associated code to implement it instead. It would be even better to support defining the ignored_imports directly in PythonPackage: [d68fe41](https://github.com/spack/spack/commit/d68fe41148807fc01b3dc7d48e7eb01b59be28fc)

I was not aware of the `ignored_imports` list.  I'll have to see if such imports are part of the problem I've had with testing.  Thanks!

**Comment by tldahlgren** [comment]
> > Those checks can then be run after the installation _and_, if desired, as part of the stand-alone test process.
> 
> This _is_ desired. Before this PR, these tests are run as stand-alone tests. After this PR, they are not. That's what I mean by removing smoke tests from ~1,600 packages.

Yes, I agree it is desired.  Didn't intend to imply it wasn't.

> 
> > A package that just does import tests is not testing the functionality of the installed software, for example.
> 
> From my experience, import tests have caught 99% of build issues with Python libraries. The developers themselves run more extensive unit tests in CI. These tests are only designed to make sure that the package is installed correctly.

That's a great metric to hear.  That's why it seems IMO like a 'sanity check'.

> 
> I would love to have more extensive unit tests for Python packages. Until then, import tests are better than nothing, and I don't think anyone will be writing ~1,600 more intensive tests themselves.

I agree wholeheartedly!

**Comment by tldahlgren** [comment]
Closing this PR since we're taking a different approach to support these tests with PRs like #34236.

**Pull request closed without merging**
