### PR TITLE
Support environment variable expansion inside module projections

### PR DESCRIPTION
**Pull request by psakievich**
Allow spack config variables to appear in view and module projections. So we can do things like:

``` yaml
module:
  tcl:
    projections:
       all: "{name}/$date/$user/{hash:4}"
```

We could also do the more general `canonicalize_path` to include environment variable injection.

That would be my preference, but I went more conservative for this PR.

### CODE REVIEW

**Comment by psakievich** [comment]
@spackbot fix style

**Comment by psakievich** [comment]
I updated to `canonicalize_path` since that is what I would prefer, but I will revert if there are issues with that under review.

**Comment by psakievich** [comment]
This has a problem I need to fix. `canonicalize_path` puts the absolute path at the front of the string, which is not what we want.

**Review by tgamblin — APPROVED** [review]
LGTM.

**Comment by alalazo** [comment]
Can we add a couple lines of docs and a unit test to avoid accidental regression in a follow up PR?

**Pull request merged**
