### PR TITLE
duckdb: add v1.0.0, v0.10.3

### PR DESCRIPTION
**Pull request by teaguesterling**
Observed an issue with AVX2-specific block of code that I attempted to `conflict` out. I may have not been specific enough, however.

Issue is in `third_party/re2/re2/prog.cc` around line 1170 and will be reported upstream.

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed the two version sha256s.

**Comment by teaguesterling** [comment]
Upstream issue: https://github.com/duckdb/duckdb/issues/12362

**Comment by teaguesterling** [comment]
> Confirmed the two version sha256s.

Sorry! I added a commit after you've reviewed.

**Review by tldahlgren — DISMISSED** [review]
I would prefer to see a *bit* more, like "See <url>" but it's your package.

**Comment by teaguesterling** [comment]
> I would prefer to see a _bit_ more, like "See " but it's your package.

Happy to do that and welcome the suggestion.

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
Checks seem to be in an odd state.  Closing and re-opening to see if that removes the problem.

**Pull request merged**
