### PR TITLE
add flux-core v0.31.0 and flux-sched v0.20.0

### PR DESCRIPTION
**Pull request by grondo**
Update flux-core and flux-sched packages with latest release versions.

### CODE REVIEW

**Review by bernhardkaindl — CHANGES_REQUESTED** [review]
The fixes for newer compilers haven't been submitted or merged upstream it seems:
```diff
--- a/var/spack/repos/builtin/packages/flux-sched/package.py
+++ b/var/spack/repos/builtin/packages/flux-sched/package.py
@@ -103,7 +103,7 @@ def autoreconf(self, spec, prefix):
             bash = which('bash')
             bash('./autogen.sh')
 
-    @when('@:0.19')
+    @when('@:0.20')
     def patch(self):
         """Fix build with clang@13 and gcc@11"""
         filter_file('NULL', 'nullptr', 'resource/schema/sched_data.hpp')
```
`spack install --test=root flux-sched@0.19` failed for me on Ubuntu 18.04 when built with a Ubuntu `gcc-11.1.0` (from the Ubuntu `ppa`) with:
```py
  >> 1621    FAIL: t5000-valgrind.t 1 - valgrind reports no new errors on 2 broker run
  >> 1700    FAIL: t1018-rv1-bootstrap2.t 5 - rv1-bootstrap: resource idempotency preserved
  >> 1718    FAIL: t1017-rv1-bootstrap.t 4 - rv1-bootstrap: resource idempotency preserved
```
Can't open perl script "/mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-q34fwlwsf5dmbmug7bbfkvzwhdresqog/spack-src/spack-build/t/test-terminal.perl": No such file or directory

```py
# failed 1 among 17 test(s)                                                                                                                                                                                                                      
2021-11-11T00:53:29.969160Z broker.err[0]: rc2.0: /bin/bash -c sh /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-q34fwlwsf5dmbmug7bbfkvzwhdresqog/spack-src/t/t1017-rv1-bootstrap.t  Exited (rc=1) 614.2s
flux-start: 0 (pid 18856) exited with rc=1                                      
1..17                                                                           
ERROR: t1017-rv1-bootstrap.t - exited with status 1                             
```
```
not ok 5 - rv1-bootstrap: resource idempotency preserved                        
FAIL: t1018-rv1-bootstrap2.t 5 - rv1-bootstrap: resource idempotency preserved  
#                                                                               
#       JOBID=$(flux mini batch -n4 -N4 -c44 -g4 \                              
#       ./nest.sh high 4 4 44 4 nest.json) &&                                   
#       $WAITFILE -t 600 -v -p \"R_lite\" nest.json &&                          
#       jq " del(.execution.starttime, .execution.expiration) " \               
#       nest.json > nest.norm.json &&                                           
#       flux job info ${JOBID} R | \                                            
#       jq " del(.execution.starttime, .execution.expiration) " \               
#       > job.norm.json &&                                                      
#       test_cmp job.norm.json nest.norm.json                                   
#                                                                               
```
```
ERROR: t5000-valgrind                                                           
=====================                                                           
                                                                                
not ok 1 - valgrind reports no new errors on 2 broker run                       
FAIL: t5000-valgrind.t 1 - valgrind reports no new errors on 2 broker run          
#                                                                               
#       run_timeout 400 \                                                       
#       flux start -s ${VALGRIND_NBROKERS} \                                    
#           --killer-timeout=120 \                                              
#           --wrap=libtool,e,${VALGRIND} \                                      
#           --wrap=--tool=memcheck \                                            
#           --wrap=--leak-check=full \                                          
#           --wrap=--gen-suppressions=all \                                     
#           --wrap=--trace-children=no \                                        
#           --wrap=--child-silent-after-fork=yes \                              
#           --wrap=--num-callers=30 \                                           
#           --wrap=--leak-resolution=med \                                      
#           --wrap=--error-exitcode=1 \                                         
#           --wrap=--suppressions=$VALGRIND_SUPPRESSIONS \                      
#            ${VALGRIND_WORKLOAD}                                               
#                                                                               
# failed 1 among 1 test(s)                                                      
1..1                                                                            
ERROR: t5000-valgrind.t - exited with status 1                                  
```

**Comment by grondo** [comment]
Thanks!

```
not ok 5 - rv1-bootstrap: resource idempotency preserved                        
FAIL: t1018-rv1-bootstrap2.t 5 - rv1-bootstrap: resource idempotency preserved  
```

I believe this is a known intermittent test failure:  see https://github.com/flux-framework/flux-sched/issues/799

The valgrind errors are probably due to new false positive leaks brought in by some combination of dependencies we haven't used before. I'm going to suggest we suppress that test by default outside of flux-sched's own CI with a controlled environment.

**Comment by grondo** [comment]
Force pushed with requested changes.

I've added a patch for flux-sched which will disable the valgrind tests by default, since they are really only meant to be run under controlled conditions of flux-sched CI (i.e. known suppressions from dependencies).

I also found that one of the flux-sched unit tests got a SIGABRT in yaml-cpp with `yaml-cpp@0.7.0` and GCC 11. The problem does not occur with `yaml-cpp@0.6.3` so I've pinned the version for flux-sched to that.

**Comment by grondo** [comment]
I was able to successfully run `spack install -vvv --test=root flux-core %gcc@11.2.0` and `spack install -vvv --test=root flux-sched %gcc@11.2.0` with a locally built gcc 11.2.0.

**Review by bernhardkaindl — APPROVED** [review]

**Pull request merged**
