### PR TITLE
Allow setting variant name  in AutotoolsPackage._activate_or_not

### PR DESCRIPTION
**Pull request by iarspider**
Based on a discussion with @haampie here: https://github.com/spack/spack/pull/26032#discussion_r711731513

I will also try to update tests with this new feature, if I can figure them out...

### CODE REVIEW

**Comment by haampie** [comment]
This looks useful!

Somewhere I feel like we've overloaded the with/without and enable/disable functions with too many features though :sweat_smile: how does this PR interact with multi-valued variants for instance?

**Comment by iarspider** [comment]
@haampie it doesn't do much to multi-valued variants. Not sure if it should though.

**Comment by haampie** [comment]
Try `spack style` next time ;)

**Comment by iarspider** [comment]
> 
> 
> Try `spack style` next time ;)

Yep. I was going to do style first, but got distracted...

**Review by haampie — APPROVED** [review]

**Comment by haampie** [comment]
Oh, I somehow missed the keyword became `variant_name` not `variant`... I think it's better to keep it short, so that things can stay on one line more easily. @sethrj opinions? I assumed this in #26064 :grimacing:

**Comment by haampie** [comment]
Case in point, the first PR that uses it fails style tests ^^

>   var/spack/repos/builtin/packages/gperftools/package.py:35: [E501] line too long (115 > 88 characters)

**Comment by sethrj** [comment]
@haampie Definitely prefer the shorter `variant`. The `_name` doesn't disambiguate so it should be dropped (it's not like you're going to accidentally pass a class of type `Variant` instead of a string).

**Comment by haampie** [comment]
Ok, can you review https://github.com/spack/spack/pull/26064 then? :D

**Pull request merged**
