### PR TITLE
Bugfixes/r base routines

### PR DESCRIPTION
**Pull request by tmerrick1**
These routines were calling lattice, mass, and other base routines.  You would not see any error until you try and activate them.

### CODE REVIEW

**Comment by adamjstewart** [comment]
See #3031. I already proposed this solution but I believe it was rejected.

**Comment by tmerrick1** [comment]
I agree with your fake package idea.  I would have found these when installing rather than activating.

**Comment by adamjstewart** [comment]
I actually prefer the idea of not installing the base packages with R at all. It's not hard to install them for a user if they need them. And it means that activation still works. But that idea was shot down too. We never really came to an agreement on the best solution.

**Comment by tmerrick1** [comment]
How do I get rid of the r-rmpfr modification that keeps showing up?  I think that I accidentally committed it to the tmerrick1/develop site one time.

The other files here are to make r-adegenet able to activate.  Right now r-ggplot2 will not activate.

**Comment by adamjstewart** [comment]
To fix your develop branch, run:
```
$ git checkout develop          # ensure that you are on the right branch
$ git pull -f upstream develop  # force pull the correct develop history
$ git push -f origin develop    # force push the correct develop history
```
To fix other branches that branched off the wrong develop, run:
```
$ git checkout bugfixes/R-base-routines        # ensure that you are on the right branch
$ git rebase develop                           # rebase off of the new "correct" develop history
$ git push -f origin bugfixes/R-base-routines  # update your remote branch as well
```

**Comment by adamjstewart** [comment]
P.S. I've accidentally done this so many times myself, you're not alone. Git bash prompt completion helps a lot, see https://github.com/adamjstewart/dotfiles for an example of what my terminal prompt looks like.

**Comment by tmerrick1** [comment]
Right now R is broken in spack as you cannot activate most programs.  One of the 3 solutions proposed in #3031 should be implemented to fix activation.

I noticed that my activation takes place in the spack/opt/spack/r-.../rlib/R/library directory which affects all users, but can only be done by the spack administrator.  Shouldn't this be done in the users ~/.spack area?

**Comment by adamjstewart** [comment]
Yes, activation is something that only admins can do at the moment. There has been talk of a Spack Environments working group that I believe plans on having better integration with something like virtualenv. At the moment, `~/.spack` is only for configuration settings.

I agree that we need to fix the activation problem. You'll just have to get everyone from #3031 together again to come up with a single solution that everyone is happy with.

**Comment by adamjstewart** [comment]
Closing in favor of #4516

**Pull request closed without merging**
