### PR TITLE
openfoam: Fix for aarch64

### PR DESCRIPTION
**Pull request by t-nojiri**
There was a difference with the assets I confirmed in the following PR.
https://github.com/spack/spack/pull/19778#event-3971525322

### CODE REVIEW

**Comment by adamjstewart** [comment]
@olesenm

**Comment by olesenm** [comment]
@t-nojiri  - I think we can close.

**Comment by t-nojiri** [comment]
@olesenm 
My following PR has been merged, so I'll get an error if I don't revert the fix.
https://github.com/spack/spack/pull/19622

**Comment by olesenm** [comment]
@adamjstewart - closed by #19778

**Comment by tkameyama** [comment]
Currently, update_arch on aarch64 returns Arm64 by #19622.
https://github.com/spack/spack/blob/e80276cd1422ec22bccd7a7625ead43e75525ae8/var/spack/repos/builtin/packages/openfoam/package.py#L908
And we cannot build openfoam on aarch64.

**Comment by olesenm** [comment]
Thank you @tkameyama and @t-nojiri for noticing this embarrassing slip-up.
Your fix is indeed correct, not sure how the other one got in there.

**Comment by olesenm** [comment]
@t-nojiri it is probably worth adding a comment to your fix, as reminder for the future. Eg,

```
elif target == 'aarch64':
    platform += 'ARM64'  ## overwritten as 'Arm64' in openfoam-org
```
Might prevent others from thinking this is a mistake in the future.

**Comment by t-nojiri** [comment]
@olesenm 
I added a comment.

Thank you for your comment.

**Review by adamjstewart — APPROVED** [review]

**Review by olesenm — APPROVED** [review]

**Comment by olesenm** [comment]
Thanks @adamjstewart and @alalazo for dealing with the noise of these one-line changes!

**Comment by samcom12** [comment]
@olesenm I have tried building OpenFOAM on apollo80 system. I get the below error.
```
==> Added file spack-Allwmake
==> Added file README-spack
==> openfoam: Executing phase: 'configure'
==> openfoam: Executing phase: 'build'
==> Error: InstallError: No wmake rule for cray Gcc

/home/apps/spack/var/spack/repos/builtin/packages/openfoam/package.py:728, in build:
        725        its environment first.
        726        Only build if the compiler is known to be supported.
        727        """
  >>    728        self.foam_arch.has_rule(self.stage.source_path)
        729        self.foam_arch.create_rules(self.stage.source_path, self)
        730
        731        args = ['-silent']

```
Kindly look into it.

**Comment by olesenm** [comment]
@samcom12 - cray is a bit of a weird one. I think that it should be using the linux64Cray set of rules, which actually use `cc` for the c-compiler and `CC` for the c++ compiler, not gcc directly. Please open a new issue and copy the comments there. Will need some help.

**Pull request merged**
