### PR TITLE
Fix NameError in foreground/background test

### PR DESCRIPTION
**Pull request by haampie**
Hopefully this fixes the notoriously flaky foreground/background test

### CODE REVIEW

**Comment by haampie** [comment]
@spackbot rerun pipeline

**Comment by haampie** [comment]
@spackbot help

**Comment by haampie** [comment]
@spackbot re-run pipeline

**Comment by haampie** [comment]
@spackbot re-run pipeline

**Review by alalazo — APPROVED** [review]

**Pull request merged**
