### PR TITLE
trilinos: add variant to build tests

### PR DESCRIPTION
**Pull request by eugeneswalker**
CC @jmlapre @sebrowne @jwillenbring @keitat @kuberry @sethrj

### CODE REVIEW

**Comment by sebrowne** [comment]
I like the concept (speaking as somebody who tried this out at our site).  I can't speak for whether this is acceptable from a Spack community POV, but it's fine by me.

**Review by psakievich — APPROVED** [review]
This seems like a good idea. I think a lot of people want ways to debug trilinos issues.  Being able to run the tests is a straight forward way to link the developers with people deploying trilinos via spack.

**Comment by sebrowne** [comment]
You still need to use `--keep-stage` or `spack develop` to actually access the build directory to run the tests once they've been enabled, but agree, still very useful to allow end-users to run the tests in a fairly low-overhead manner.

**Comment by kuberry** [comment]
> I like the concept (speaking as somebody who tried this out at our site). I can't speak for whether this is acceptable from a Spack community POV, but it's fine by me.

I also like the idea of adding this. Looking through existing packages, it seems that `+test` is most popular with `+tests` following closely behind (60/40 split). I don't see any other examples using`+testing`, though.

**Comment by eugeneswalker** [comment]
> Looking through existing packages, it seems that `+test` is most popular with `+tests` following closely behind (60/40 split). I don't see any other examples using`+testing`, though.

Good call. I just pushed a commit to change it to `+test` to keep with standard conventions.

**Review by sethrj — CHANGES_REQUESTED** [review]
I don't think this is the right approach. As stated, this doesn't affect the installed distribution, as every variant should. There's a "run tests" attribute you can activate by adding a command line flag, and that seems like a better fit here.

**Comment by sebrowne** [comment]
@sethrj I think there are a couple of use cases for this.  The one in which I'm primarily interested is in activating the tests so that I can run them after I use spack to configure/build, but not through spack (I want to use `ctest` directly).  Would that still work, or would enabling that (I assume with `--test root`) cause the tests to be run automatically?

That is, is there a way to independently build (enable) the tests vs. actually RUN the tests with that approach?

**Comment by eugeneswalker** [comment]
> I don't think this is the right approach. As stated, this doesn't affect the installed distribution, as every variant should. There's a "run tests" attribute you can activate by adding a command line flag, and that seems like a better fit here.

But this is useful for doing `spack dev-build` of Trilinos. I have already been using this in my own fork to have Spack do nightly builds of trilinos master branch in a way that enables me to run the ctests outside of Spack, and inspect the output as @sebrowne says he is also interested in doing. This allows us to configure the build with Spack and run comprehensive tests to verify that there are no issues with how Spack is configure the build. @sethrj

**Comment by sethrj** [comment]
```
The one in which I'm primarily interested is in activating the tests so that I can run them after I use spack to configure/build, but not through spack
```

I don't understand this use case. Are you staging the files, building them, waiting until your trilinos build completes, canceling during the installation, and then running the unit tests after the installation??

The only way I could see a `+test` configuration making sense is if Trilinos installs the tests so that you can check e.g. GPU hardware in a cross-compilation situation (where the head nodes and the compute nodes have different configurations). It doesn't do this presently.

**Comment by eugeneswalker** [comment]
> I don't understand this use case. Are you staging the files, building them, waiting until your trilinos build completes, canceling during the installation, and then running the unit tests after the installation??

```
...
$> git clone https://github.com/trilinos/Trilinos.git
$> cd Trilinos
$> spack dev-build trilinos +cuda cuda_arch=80 ...
$> ctest ...
```

This is being used right now to do this. It isn't a theoretical use case. It is being used, right now, to do nightly Trilinos builds where we use Spack to configure the build for various NVIDIA and AMD GPUs, and then we run the comprehensive `ctest` to identify issues and report them. 
* https://spack-tutorial.readthedocs.io/en/lanl19/tutorial_developer_workflows.html

**Comment by psakievich** [comment]
I think there is a gap in the spack infrastructure right now for tests that can't be run from the install directory.  i.e. they require more artifacts than you would __NOT__ (edit 🙂 ) want in the installation directory. This is inline with the concept of nightly tests for a heavy weight investigation of the software on a given platform.  This is not the standard spack installation case to deploy binaries where you just want a light weight smoke test.

For the broader trilinos community and spack adoption there in I think this is a valuable variant even if it is outside the current variant definition.  It might be worth a broader discussion on how to handle these cases. We do something similiar for exawind and I know several other SNL projects that are pursuing spack driven test suites as well.

@tgamblin and I have discussed in the past adding a staging of "resources" for tests.  Perhaps just capturing/relocating the stage directory could be an option for these sorts of tests? IDK thinking out loud here.

**Review by sethrj — APPROVED** [review]
Interesting use case; it would be better if trilinos added an option to make the tests installable. Add one more variant to the pile 🤪

**Comment by psakievich** [comment]
lol. indeed. Yeah this is how many codes I work with operate. The tests are specifically not installable at the moment and it's that way on purpose.  I suppose we need to think about a way to merge these mentalities together programmatically in the spack universe.  More and more teams at SNL are interested in running their testing via spack, but the tests are quite heavy...

**Pull request merged**
