### PR TITLE
initial docs for find and flake8 cleanup

### PR DESCRIPTION
**Pull request by trws**
Small doc addition for explicit on find and various flake8 fixes related to same.

### CODE REVIEW

**Comment by alalazo** [comment]
@trws Did you use `yapf` to fix style issues ? If so, can you share your configuration file ?

**Comment by trws** [comment]
I used autopep8, a package for which is also in the commit.  I do have a yapf file I could send, but it doesn't follow the style we're checking quite as well.


________________________________

**Comment by alalazo** [comment]
Thanks for the reply @trws . What worries me a bit is the fact that the signal to noise ratio didn't decrease for `cmd/find.py`. To be more clear : yesterday I committed a `flake8` compliant version of `cmd/find.py` obtained with:
```
yapf -i cmd/find.py
```
The change in logic for #968 was `+1/-1` line, the overall PR was `+83/-54` line. Fine : it was the first time that file went through `flake8` checks.

In this PR I see that the same file has a `+15/-25` lines just for style issues. This I think happened just because we used two different way of reformatting the same file (plus maybe this PR was not up to date with the latest develop, but of this I am not really sure). What I would like to avoid next time I'll modify the code, is to generate another `+25/-15` lines change that revert yours, just because I resolved the style issue I had with a different tool than the one you used.

Maybe we should agree on the same procedure to resolve style issues. I don't really mind either using `autopep8` or `yapf` based on `pep8`, as long as they remain consistent for lines I didn't change in files that were already checked. What do you think ? @tgamblin ?

**Comment by tgamblin** [comment]
@alalazo: Maybe we should turn off the flake8 checks until we actually format the entire repo to pass them. I think I probably should've done that before merging the original pull request.

I don't have a preference about which auto-formatter to use.  I've used `autopep8` a couple times and liked what it did.

**Comment by trws** [comment]
Agreed, that's best avoided.  That's actually why I switched to using autopep8, where yapf is my normal preference, since @tgamblin mentioned using it the other day.  At least having a style file that gets used consistently would be good.

For what it's worth, I did do a rebase, and only had to make one manual change, so the rest is a difference in formatter configuration.

**Comment by trws** [comment]
That would be good @tgamblin, but none of the python formatters I've seen can actually enforce line length in comments or strings to pep8's satisfaction.  I'm sure you've run into how much manual fixup that takes in some of the larger files. =/

**Comment by tgamblin** [comment]
@trws: yes.  It'll take a while -- I just worry that PR submitters are going to get sick of PEP8 errors until we do it...

**Comment by trws** [comment]
I actually didn't get any.  Literally none at all, from the run_flake8 script on this last pass.  I had to run flake8 on each manually to get it to give me something, which is probably another issue entirely... Understood though.

Really, the only frustrating issue is the 79-char line length limit being enforced for everything, including comments, strings, chained list comprehensions... with that loosened a bit, everything else (just about) gets fixed by either of the formatters.

**Comment by alalazo** [comment]
@tgamblin I don't know if that will solve the issue : as long as a few lines in a file are modified and the issue is resolved with a tool that is different from what is previously used we will encounter the same problem, even if the whole repo was compliant to the checks.

**Comment by alalazo** [comment]
@trws That explains the thing! Right now flake8 checks are done on what you change in your PR. You didn't change anything in `cmd/find.py` so the script didn't check the file. If you didn't update it though running flake8 manually would reveal all the problems that were in the version you checked out.

**Comment by alalazo** [comment]
@tgamblin So `autopep8` from now on ?

**Comment by tgamblin** [comment]
@alalazo sounds good to me!

**Pull request merged**
