### PR TITLE
mercury: add version 2.2.0

### PR DESCRIPTION
**Pull request by soumagne**
add psm, psm2 and hwloc variants

### CODE REVIEW

**Review by carns — DISMISSED** [review]
Looks great to me.  I appreciate the inclusion of the new psm and hwloc variants.

**Comment by soumagne** [comment]
[data-vis-sdk-pr-build](https://gitlab.spack.io/spack/spack/-/pipelines/150248) failed in https://gitlab.spack.io/spack/spack/-/jobs/2955038#L1721
Because mercury 2.2.0 is now more strict on the libraries that it includes through pkg-config, I suspect unifyfs will have to be either updated to link against the mercury NA library by using the na.pc file or it should remove its use of the `NA_Set_log_level()` call, which should really not be needed.

**Review by alalazo — CHANGES_REQUESTED** [review]
Pipelines are required to pass for the PR to be merged

**Comment by carns** [comment]
The Unify team is aware of the build problem and looking at how to best handle it.  We can re-kick the CI action once we get an all clear from them.

**Comment by bernhardkaindl** [comment]
@alalazo I test-built this PR, and triggered CI, could you approve? That the build didn't pass is fixed now

**Review by alalazo — APPROVED** [review]

**Pull request merged**
