### PR TITLE
Fix dire package

### PR DESCRIPTION
**Pull request by iarspider**
Pythia version numbering was changed in #26255

### CODE REVIEW

**Comment by iarspider** [comment]
~~The [dire website](https://dire.gitlab.io/) doesn't put an upper limit on Pythia8 version for Dire 2.004, and in CMS dire is built with pythia 8.306, will test.~~
Dire is included in pythia8 starting with 8.301. I think adding a `conflicts` clause is better than just restricting version range.

**Comment by iarspider** [comment]
@spackbot re-run pipeline

**Comment by iarspider** [comment]
@spackbot hello!

**Comment by iarspider** [comment]
@spackbot re-run pipeline

**Comment by iarspider** [comment]
@spackbot re-run pipeline

**Review by bernhardkaindl — APPROVED** [review]
LGTM

**Pull request merged**
