### PR TITLE
Package express: version update to 1.5.3

### PR DESCRIPTION
**Pull request by dlkuehn**
Updated package express to version 1.5.3.

### CODE REVIEW

**Review by alalazo — DISMISSED** [review]

**Comment by alalazo** [comment]
@dlkuehn Can you please rebase to trigger Gitlab pipelines on a new merge commit?

**Comment by snehring** [comment]
Sorry if that makes too much noise. Our fork was pretty behind.

**Comment by alalazo** [comment]
Can you rebase? The list of changes seems wrong...

**Comment by tldahlgren** [comment]
@spackbot run pipeline

**Review by tldahlgren — APPROVED** [review]
Confirmed the sha256

**Pull request merged**
