### PR TITLE
adding butterflypack 2.2.0

### PR DESCRIPTION
**Pull request by liuyangzhuan**

### CODE REVIEW

**Review by tldahlgren — DISMISSED** [review]
Confirmed new sha256.

**Comment by tldahlgren** [comment]
Will defer merge until @balay has a chance to comment.

**Review by balay — DISMISSED** [review]
BTW: 'url' doesn't need updating for every release [its used primarily as a template for location of all tarballs]

**Comment by tldahlgren** [comment]
> BTW: 'url' doesn't need updating for every release [its used primarily as a template for location of all tarballs]

I used to tell people that too but I can appreciate that some people might like the idea of the tarball reflecting the latest version. 😀

**Comment by tldahlgren** [comment]
Ah.  I'm still trying to get used to `black`'s style requirements.

@spackbot fix style

**Review by balay — APPROVED** [review]

**Review by tldahlgren — APPROVED** [review]

**Pull request merged**
