### PR TITLE
heffte: new version and rocm fix

### PR DESCRIPTION
**Pull request by mkstoyanov**
* adds the new version of heffte
* fixes an issue with heffte+rocm

### CODE REVIEW

**Review by tldahlgren — COMMENTED** [review]
Confirmed sha256 for new version.

**Comment by tldahlgren** [comment]
Looks like there are some issues with the E4S pipeline stack wrt running the stand-alone tests:

https://gitlab.spack.io/spack/spack/-/jobs/3988266 reports:

```
'/home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/cmake-3.24.2-vfgkleihjfox4gwozyiks6t7mvjv2n75/bin/cmake' '/tmp/root/spack-stage/spack-standalone-tests/s2iiyiiffr7i7zpwbjq5zc3bcnupfaeq/heffte-2.3.0-lmokbrq/cache/heffte/testing'
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /builds/spack/spack/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- heFFTe post-installation testing
-- Configuring incomplete, errors occurred!
See also "/tmp/root/spack-stage/spack-standalone-tests/s2iiyiiffr7i7zpwbjq5zc3bcnupfaeq/heffte-2.3.0-lmokbrq/CMakeFiles/CMakeOutput.log".
CMake Error at /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/cmake-3.24.2-vfgkleihjfox4gwozyiks6t7mvjv2n75/share/cmake-3.24/Modules/FindCUDAToolkit.cmake:679 (message):
  Could not find nvcc, please set CUDAToolkit_ROOT.
Call Stack (most recent call first):
  /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/morepadding/linux-ubuntu20.04-x86_64/gcc-11.1.0/heffte-2.3.0-lmokbrqggljfdu23jtjx4earbw2cz7vx/lib/cmake/Heffte/HeffteConfig.cmake:67 (find_package)
  CMakeLists.txt:16 (find_package)
```

And https://gitlab.spack.io/spack/spack/-/jobs/3988267 reports:

```
Running tests...
Test project /tmp/root/spack-stage/spack-standalone-tests/bzfg3qofors3fgzwdfnoc7o2exzewrob/heffte-2.3.0-qny3uok
    Start 1: example_fftw
Could not find executable MPIEXEC_EXECUTABLE-NOTFOUND
Looked in the following places:
MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
1/5 Test #1: example_fftw .....................***Not Run   0.00 sec
    Start 2: example_r2r
Could not find executable MPIEXEC_EXECUTABLE-NOTFOUND
Looked in the following places:
MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
2/5 Test #2: example_r2r ......................***Not Run   0.00 sec
    Start 3: example_options
Could not find executable MPIEXEC_EXECUTABLE-NOTFOUND
Looked in the following places:
MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
3/5 Test #3: example_options ..................***Not Run   0.00 sec
    Start 4: example_vectors
Could not find executable MPIEXEC_EXECUTABLE-NOTFOUND
Looked in the following places:
MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
4/5 Test #4: example_vectors ..................***Not Run   0.00 sec
    Start 5: example_r2c
Could not find executable MPIEXEC_EXECUTABLE-NOTFOUND
Looked in the following places:
MPIEXEC_EXECUTABLE-NOTFOUND
MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Release/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
Debug/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
MinSizeRel/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
RelWithDebInfo/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Deployment/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
Development/MPIEXEC_EXECUTABLE-NOTFOUND
5/5 Test #5: example_r2c ......................***Not Run   0.00 sec

0% tests passed, 5 tests failed out of 5

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - example_fftw (Not Run)
	  2 - example_r2r (Not Run)
	  3 - example_options (Not Run)
	  4 - example_vectors (Not Run)
	  5 - example_r2c (Not Run)
Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
Errors while running CTest
Output from these tests are in: /tmp/root/spack-stage/spack-standalone-tests/bzfg3qofors3fgzwdfnoc7o2exzewrob/heffte-2.3.0-qny3uok/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8



1 error found in test log:
     146    Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
     147    Unable to find executable: MPIEXEC_EXECUTABLE-NOTFOUND
     148    Errors while running CTest
     149    Output from these tests are in: /tmp/root/spack-stage/spack-standal
            one-tests/bzfg3qofors3fgzwdfnoc7o2exzewrob/heffte-2.3.0-qny3uok/Tes
            ting/Temporary/LastTest.log
     150    Use "--rerun-failed --output-on-failure" to re-run the failed cases
             verbosely.
     151    make: *** [Makefile:71: test] Error 8
  [0;91m>> 152    FAILED: Command exited with status 2:[0m


[1;31m==>[0m Error: 1 test(s) in the suite failed.

Traceback (most recent call last):
  File "/builds/spack/spack/lib/spack/spack/main.py", line 998, in main
    return _main(argv)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 953, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 981, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 630, in _invoke_command
    return_val = command(parser, args)
  File "/builds/spack/spack/lib/spack/spack/cmd/test.py", line 479, in test
    globals()["test_%s" % args.test_command](args)
  File "/builds/spack/spack/lib/spack/spack/cmd/test.py", line 250, in test_run
    test_suite(
  File "/builds/spack/spack/lib/spack/spack/install_test.py", line 212, in __call__
    raise TestSuiteFailure(self.fails)
spack.install_test.TestSuiteFailure: 1 test(s) in the suite failed.

======================== 1 failed, 0 passed of 1 specs =========================
[1;34m==>[0m View your build results here:
[1;34m==>[0m heffte: https://cdash.spack.io/buildSummary.php?buildid=2044420
[1;34m==>[0m SPACK_BUILDCACHE_DESTINATION=s3://spack-binaries-prs/pr33536_heffte_new_version/e4s
```

UPDATE:  Job https://gitlab.spack.io/spack/spack/-/jobs/3988268 reports:

```
...
   16 | #pragma message(": warning : This file is deprecated. Use the header file from /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/rocfft-5.2.3-auowajb4ew7c3lx7rsybaw24cykqyqu7/include/rocfft/rocfft.h by using #include <rocfft/rocfft.h>")
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
/usr/bin/ld: CMakeFiles/heffte_example_gpu.dir/heffte_example_gpu.cpp.o: undefined reference to symbol 'hipMemcpy@@hip_4.2'
/usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-wbwbe4zbzdxjg5kszszjuj3kxotsfjkz/lib/libamdhip64.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/heffte_example_gpu.dir/build.make:101: examples/heffte_example_gpu] Error 1
make[1]: *** [CMakeFiles/Makefile2:210: examples/CMakeFiles/heffte_example_gpu.dir/all] Error 2
make: *** [Makefile:101: all] Error 2



1 error found in test log:
     175          |                                                            
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                 ^
     176    /usr/bin/ld: CMakeFiles/heffte_example_gpu.dir/heffte_example_gpu.c
            pp.o: undefined reference to symbol 'hipMemcpy@@hip_4.2'
     177    /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spac
            k_path_placeholder__/__spack_path_placeholder__/__spack_path_placeh
            older__/__spack_path_placeholder__/__spack_path_placeholder__/__spa
            ck_path_placeholder__/__spack_path_placeholder__/__spack_path_place
            holder__/__spack_path_placeholder__/__spack_path_placeholder__/__sp
            ack_path_placeholder__/__spack_path_placeholder__/__spack_path_plac
            eholder__/__spack_path_placeholder__/__spack_path_placeholder__/__s
            pack_path_placeholder__/__spack_path_placeholder__/__spa/linux-ubun
            tu20.04-x86_64/gcc-11.1.0/hip-5.2.3-wbwbe4zbzdxjg5kszszjuj3kxotsfjk
            z/lib/libamdhip64.so.5: error adding symbols: DSO missing from comm
            and line
     178    collect2: error: ld returned 1 exit status
     179    make[2]: *** [examples/CMakeFiles/heffte_example_gpu.dir/build.make
            :101: examples/heffte_example_gpu] Error 1
     180    make[1]: *** [CMakeFiles/Makefile2:210: examples/CMakeFiles/heffte_
            example_gpu.dir/all] Error 2
  [0;91m>> 181    make: *** [Makefile:101: all] Error 2[0m
     182    
     183      File "/builds/spack/spack/bin/spack", line 100, in <module>
     184        sys.exit(spack.main.main())
     185      File "/builds/spack/spack/lib/spack/spack/main.py", line 998, in 
            main
     186        return _main(argv)
     187      File "/builds/spack/spack/lib/spack/spack/main.py", line 953, in 
            _main


[1;31m==>[0m Error: 1 test(s) in the suite failed.

Traceback (most recent call last):
  File "/builds/spack/spack/lib/spack/spack/main.py", line 998, in main
    return _main(argv)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 953, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 981, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/builds/spack/spack/lib/spack/spack/main.py", line 630, in _invoke_command
    return_val = command(parser, args)
  File "/builds/spack/spack/lib/spack/spack/cmd/test.py", line 479, in test
    globals()["test_%s" % args.test_command](args)
  File "/builds/spack/spack/lib/spack/spack/cmd/test.py", line 250, in test_run
    test_suite(
  File "/builds/spack/spack/lib/spack/spack/install_test.py", line 212, in __call__
    raise TestSuiteFailure(self.fails)
spack.install_test.TestSuiteFailure: 1 test(s) in the suite failed.

======================== 1 failed, 0 passed of 1 specs =========================
...
```

**Comment by mkstoyanov** [comment]
One of them cannot find CUDA and the other cannot find MPI. Why can that be?

I cannot reproduce either problem on my system.

**Comment by tldahlgren** [comment]
> One of them cannot find CUDA and the other cannot find MPI. Why can that be?
> 
> I cannot reproduce either problem on my system.

@eugeneswalker The stand-alone tests for `heffte` are failing.

We only have one stack -- `e4s` -- that runs the stand-alone tests ATM.  The `heffte` specs can be found at:

- CPU: https://github.com/spack/spack/blob/5d0ae001a1184a7cf4cea3e2043b39fcc278dae6/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml#L95
- CUDA: https://github.com/spack/spack/blob/5d0ae001a1184a7cf4cea3e2043b39fcc278dae6/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml#L181
- ROCm: https://github.com/spack/spack/blob/5d0ae001a1184a7cf4cea3e2043b39fcc278dae6/share/spack/gitlab/cloud_pipelines/stacks/e4s/spack.yaml#L214

I forgot to check for rocm test results when I reported previously.

**Comment by mkstoyanov** [comment]
The issues are from CUDA and MPICH, and in both cases those are loaded externally to spack. 

When spack takes CUDA and MPICH from the system environment, I cannot reproduce the build even if I have the heffte sepcific specs. All I can do is ask around if anyone has the seen the issue and knows how to help.

**Comment by tldahlgren** [comment]
> I cannot reproduce either problem on my system.

Each job has a `Download` and `Browse` button.  You can select `Download` to git a `.zip` file containing logs, files to help reproduce the build, and the test logs/outputs.

Spack's `spack ci reproduce-build` (https://spack.readthedocs.io/en/latest/pipelines.html#spack-ci-reproduce-build) can also be used.  For example, you can copy the link of the `Download` button and paste it as the command argument. 

I'm not in my clone and don't have your branch available, so I get the following instructions (thanks to @scottwittenburg):

```
$ spack ci reproduce-build https://gitlab.spack.io/spack/spack/-/jobs/3988266/artifacts/download
==> Fetching artifacts from: https://gitlab.spack.io/spack/spack/-/jobs/3988266/artifacts/download

==> Job ran with the following image: ecpe4s/ubuntu20.04-runner-x86_64:2022-10-01
checkout_commit: b497581ce792ca6152e9d787ba55ffa488246d77
merge_commit: e01ec5e3c4fb347eecfd85de5deb96d075c29a9b
==> Error: Missing commit: b497581ce792ca6152e9d787ba55ffa488246d77
==> Error: Failed to automatically setup the tested version of spack in your local reproduction directory.

        This can happen if the spack you are using to run this command is not a git
        repo, or if it is a git repo, but it does not have the commits needed to
        recreate the tested merge commit.  If you are trying to reproduce a spack
        PR pipeline job failure, try fetching the latest develop commits from
        mainline spack and make sure you have the most recent commit of the PR
        branch in your local spack repo.  Then run this command again.
        Alternatively, you can also manually clone spack if you know the version
        you want to test.
            
==> Job ran with the following tags: ['spack', 'medium', 'x86_64', 'public']

Run the following command:

    $ docker run --rm -v /usr/WS1/dahlgren/reproduce/ci_reproduction:/builds/spack/spack -ti ecpe4s/ubuntu20.04-runner-x86_64:2022-10-01

Once inside the container:

    - Clone spack and acquire tested commit

commit 266619538d748ef2e0b9b49f1ce78e62c73cd07e
Merge: b497581c e01ec5e3
Author: Miroslav Stoyanov <30537612+mkstoyanov@users.noreply.github.com>
Date:   Wed Oct 26 17:41:48 2022 +0000

    Merge e01ec5e3c4fb347eecfd85de5deb96d075c29a9b into b497581ce792ca6152e9d787ba55ffa488246d77

    - Activate the environment

        $ source <spack-clone-path>/share/spack/setup-env.sh
        $ spack env activate --without-view /builds/spack/spack/jobs_scratch_dir/reproduction

    - Run the install script

        $ /builds/spack/spack/jobs_scratch_dir/reproduction/install.sh
```

But that only gets the build reproduced.  The tests still have to be run.

**Comment by mkstoyanov** [comment]
I had to rebase to sync with the current develop branch, but then in the container I get:
```
root@2074ac477fb8:/builds/spack/spack/jobs_scratch_dir/reproduction# ./install.sh 
==> Error: no environment in /builds/spack/spack/jobs_scratch_dir/concrete_environment
```
Maybe I need to wait for this to run with the latest `develop` and see then.

@tldahlgren  Thanks for you help, I didn't know I can get access to the spack containers.

**Comment by eugeneswalker** [comment]
> One of them cannot find CUDA and the other cannot find MPI. Why can that be?
> 
> I cannot reproduce either problem on my system.

I am reproducing it locally now, will post logs here ASAP.

**Comment by mkstoyanov** [comment]
This is an issue with spack filing to load the proper environment. I managed to reproduce the error, but all gets fixed with a simple:
```
spack load heffte
spack unload heffte
spack test run heffte
```
Not sure what would be the proper way to work around this. I have the manual cmake links to the ROCm libraries, do I have to add the same for all of my dependencies?

**Review by eugeneswalker — APPROVED** [review]

**Pull request merged**
