### PR TITLE
wrf: fixing the config issue

### PR DESCRIPTION
**Pull request by amd-toolchain-support**
- Removing "-enable-boscc" config option

### CODE REVIEW

**Comment by tldahlgren** [comment]
@MichaelLaufer @ptooley Did you want to comment on this PR since you are maintainers of the associated package?

**Comment by MichaelLaufer** [comment]
@tldahlgren @amd-toolchain-support 
I do not have access to an aocc based system, but as this only affects aocc, it should be fine. :)

**Comment by amd-toolchain-support** [comment]
@MichaelLaufer 
you are right, it affects only `aocc`

**Review by tldahlgren — APPROVED** [review]

**Comment by tldahlgren** [comment]
> @tldahlgren @amd-toolchain-support
> I do not have access to an aocc based system, but as this only affects aocc, it should be fine. :)

Thank you for responding.

**Pull request merged**
