### PR TITLE
Update opencv package

### PR DESCRIPTION
**Pull request by mwilliammyers**
- Add CUDA support
- Now builds the `cv2` module & add more explicit python cmake params (note: this requires #1188 to be merged, although it won't break anything to merge it before #1188)
- Fix pep8 style issues

### CODE REVIEW

**Comment by becker33** [comment]
Can you make python a conditional extender? That's a big package to bring in by default when it's optional.

**Comment by adamjstewart** [comment]
Packages shouldn't be able to `depends_on('python')` **and** `extends('python')`. If this doesn't complain, then that's a bug.

**Comment by mwilliammyers** [comment]
@becker33 Yeah, I meant to do that but I guess I forgot.
@adamjstewart No complaints from spack and I am up to date with develop

**Comment by tgamblin** [comment]
@mwilliammyers: can you make this `extends('python', when='+python')` and add a variant for Python that defaults to false?  Python's a pretty big dependency and people might not want to drag it in.

**Pull request merged**
