### PR TITLE
XSBench: added tags to package description.

### PR DESCRIPTION
**Pull request by pkondamudi**

### CODE REVIEW

**Comment by pkondamudi** [comment]
Is it OK to add something like ```XSBench(proxy-app)``` to the description? 

We want to have someway to isolate so the users to find these applications.

**Comment by alalazo** [comment]
@pkondamudi You are already using the word "mini-app" everywhere:
```console
$ spack list -d "mini-app"
==> 5 packages.
cleverleaf  cloverleaf3d  miniaero  tealeaf  xsbench
```
Would that be sufficient?

**Comment by pkondamudi** [comment]
Actually we are writing the Spack packaging scripts for other apps which we did not develop. 'mini-app' is something provided in the project description of the application developers.

Few application might have that keyword and few might not. So we would like have something concrete for users to find and install them through Spack. We are putting up a website and we would have to mention in the website, a common way they could find them.

**Comment by alalazo** [comment]
> We are putting up a website and we would have to mention in the website, **a common way** they could find them.

That's exactly my point. We need a common way to add and use tags, not three different ones.

---
That said, I think it shouldn't be hard to modify `spack info` and `spack list` to make use of a `tags` attribute if present in the package. I'll try to put together a PR early next week and see if I can get it accepted. If you are in a hurry you're welcome to take a stab at it.

**Comment by adamjstewart** [comment]
Closing in favor of #4786.

**Pull request closed without merging**
