### PR TITLE
Parse oneapi version

### LINKED ISSUE #19216: Intel 2020.09.15.001 misidentified as Intel<11.1?
Using `spack@develop` (d43522deeb4af2f435aaa920c266f8282a815f72 from 6-Oct-2020) on `JLSE Iris` and it *looks* like `Intel@2020.09.15.001` is being misidentified as an Intel < 11.1, and is thus unable to use `cxx11_flag` ??

```
$> spack compilers
...
-- intel opensuse_leap15-x86_64 ---------------------------------
intel@2020.09.15.001
```

```
$> spack install superlu-dist%intel ^m4%gcc
...
==> Installing superlu-dist
==> No binary for superlu-dist found: installing from source
==> Error: UnsupportedCompilerFlag: intel (< 11.1) does not support the C++11 standard (as compiler.cxx11_flag).
    If you think it should, please edit the compiler.intel subclass to implement the cxx11_flag property and submit a pull request or issue.

/home/eugeneswalker/spack/var/spack/repos/builtin/packages/superlu-dist/package.py:89, in flag_handler:
         86    def flag_handler(self, name, flags):
         87        flags = list(flags)
         88        if name == 'cxxflags':
  >>     89            flags.append(self.compiler.cxx11_flag)
         90        if name == 'cflags' and '%pgi' not in self.spec:
         91            flags.append('-std=c99')
         92        return (None, None, flags)
```

Any ideas?

@becker33 @shahzebsiddiqui @frankwillmore

### PR DESCRIPTION
**Pull request by frankwillmore**
This is a brief mod to compiler.py which enables the proper parsing of the version identification string generated by Intel OneAPI compilers, as the generated output differs from previous compiler versions.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I think we'll also want to do this in the `intel` package. @alalazo can you review?

**Comment by alalazo** [comment]
Why aren't we creating a standalone `IntelOneAPI` class in `spack.compilers`? Is there some issue proceeding that way?

**Comment by frankwillmore** [comment]
A standalone IntelOneAPI compiler class would be a good way to isolate the OneAPI toolchain. With Intel's move to clang, there will probably be enough things different that we'd want to separate the old/new versions.

**Comment by frankwillmore** [comment]
Superseded by https://github.com/spack/spack/pull/19330
which a defines Oneapi compiler class, distinct from Intel compiler class

**Pull request closed without merging**
